### ISSUE TITLE
woocommerce v4.5.2 / update product / Text panel does not working

### ISSUE THREAD

**Issue by rondepierre** [woocommerce/woocommerce#27784] opened 2020-09-25 12:23 UTC
when you want update one product: 
url like this : wp-admin/post.php?post=ID&action=edit

the panel visual & text are not working, when you click on it , nothing happens.

bug comes on the v4.5.2.

best regards

**Comment by tammullen** [comment] 2020-09-25 16:20
Hi @rondepierre 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 
![Screenshot_2020-09-25_at_17_17_54](https://user-images.githubusercontent.com/24649833/94291235-426c8c80-ff53-11ea-9836-00c53b98940f.png)

Please provide us with more details about the issue which may help us to evaluate it further. 

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by rondepierre** [comment] 2020-09-25 16:33
Hi Team,

thanks for your support, 

I just tested all theme and plugins… yes it seems, that problem is coming from one plugin.

I will dig on it and report it  on plugin's owner.


thanks again


best regards

@rondepierre

**Comment by tammullen** [comment] 2020-09-25 16:41
Thanks @rondepierre!

I will close this for now.

**Closed by tammullen** 2020-09-25 16:41 UTC
Labels: can't reproduce, status: needs feedback
