### ISSUE TITLE
Can't activate woocommerce version 3.4.2

### ISSUE THREAD

**Issue by wbcomdev** [woocommerce/woocommerce#20503] opened 2018-06-12 13:11 UTC
I am not able to activate woocommerce 3.4.2 at my localhost wordpress installation, it gives fatal error.

Also, it's a fresh wordpress installation and does not contain any conflicting plugin.

 Fatal error: Declaration of DateTime::($interval) must be compatible with DateTimeInterface::diff($object, $absolute = NULL) in C:\MAMP\htdocs\wcwordpress\wp-content\plugins\woocommerce\includes\class-wc-datetime.php on line 107

**Comment by mikejolley** [comment] 2018-06-12 14:03
@wbcomdev PHP version?

**Comment by mikejolley** [comment] 2018-06-12 14:06
There is nothing on line 107 - https://github.com/woocommerce/woocommerce/blob/3.4.2/includes/class-wc-datetime.php#L107 Have you customised the file?

**Comment by rodrigoprimo** [comment] 2018-06-12 14:14
@mikejolley it seems to me that for this particular error, PHP uses the last line of the class instead of the line where the declaration is not compatible :man_shrugging:

**Comment by wbcomdev** [comment] 2018-06-13 05:01
I have not customized any of woocommerce file, infact its fresh wp installation. The PHP version I am using is 7.1.5

**Comment by mikejolley** [comment] 2018-06-13 15:59
What are you running local host on? I don't know how to replicate this one. No other reports suggest it's something specific to your environment.

**Comment by mikejolley** [comment] 2018-06-14 11:06
Looked at this some more. WC_Datetime does not add anything for "interval" related and extends Datetime directly.

http://php.net/manual/en/class.datetime.php

Which implements the date time interface: http://php.net/manual/en/class.datetimeinterface.php

I see no wrongdoing there at all, and there are similar examples on the datetime documentation page.

Since there are no other reports in the wild of this (searching your error message only finds this Github topic) I'm afraid there isn't much we can do our side. No way to reproduce it (so far).

I wonder if the server you're running locally has some custom PHP modules changing how Datetime works.. we use VVV for testing here, but I also tested Mamp just to be sure our code was working :)

Let us know if you can provide instructions to replicate this on other machines. For now I'm closing this as non-reproducible.

Thanks

**Closed by mikejolley** 2018-06-14 11:06 UTC
Labels: status: needs feedback
