### ISSUE TITLE
WP_Error causes woocommerce/includes/wc-formatting-functions.php to crashes on line 294

### ISSUE THREAD

**Issue by The3IC** [woocommerce/woocommerce#24931] opened 2019-10-30 08:39 UTC
**Describe the bug**
Seeing this in the wc error log on a regular basis:
`2019-10-30T02:16:30+00:00 CRITICAL Object of class WP_Error could not be converted to string in /srv/site/wp-content/plugins/woocommerce/includes/wc-formatting-functions.php on line 294`

No other errors and not sure what causes this, no obvious problem found. Not reproducible on stagings (as I don't know what is the root cause).

WP 5.1.3, WC 3.6.5

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

Anything I can do to extract some more information?

**Comment by kloon** [comment] 2019-10-30 13:05
@The3IC the error seems to be related to the function that registers the WooCommerce orders post type. You are also running an outdated version of WooCommerce so chances are the issue has been fixed already in a recent version.

I had a look at the code and in the latest version we do have a check for WP_Error so the error should not happen in the latest version of WooCommerce.

If you are able to see the WooCommerce menu and can access orders in the backend and can place new orders all should be fine. I'd just continue to monitor the error log to see if you spot this happening more.

I am going to close this issue as I am not able to reproduce this issue locally using the latest version of WooCommerce and a default theme like Storefront. If you can produce us with steps to reproduce this while having all plugins disabled except WooCommerce and switched to a default theme like Storefront or Twentyseventeen then I will gladly reopen and look into this further.

**Closed by kloon** 2019-10-30 13:05 UTC
