### ISSUE TITLE
Generate keys with rest call

### ISSUE THREAD

**Issue by yilmazchef** [woocommerce/woocommerce#26205] opened 2020-04-17 13:24 UTC
Dear WooCommerce team,

I have been developing a cross-platform application that collects products information from multiple websites, and provides a match result for the end users.

I use WP CLI commands to create, edit, and generate fully funtional wordpress based woocommerce store. However, the only step I stucked is when I try to generate authentication keys (consumer_key and consumer_secret) via command line or via a rest call. I could not find a proper solution for that.

Could you please guide me on this.?

Sincere regards, and thank you very much for providing us such an amazing platform.

yilmazchef.

**Comment by tammullen** [comment] 2020-04-18 12:47
Hi @yilmazchef 
​
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
-Review  [WooCommerce Rest API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#rest-api-keys) to see if the solutions listed there apply to your case **especially the linked section on authentication**.
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
Label:

**Closed by tammullen** 2020-04-18 12:47 UTC
