### ISSUE TITLE
Text gets chopped off when using browser's auto-complete feature

### ISSUE THREAD

**Issue by nabsul** [woocommerce/woocommerce#12622] opened 2016-12-16 15:13 UTC
ref: ZD: 506488-zd-woothemes

Hi,

When I try to use my browser's auto-complete issue, I go to the street address line and start typing in the first couple of characters from my address like so:

![image](https://cloud.githubusercontent.com/assets/11143071/21266961/4a48fba4-c376-11e6-88e7-9a1e9e1921cd.png)

As an avid keyboard user, I will then press enter or tab. What happens is that all the fields get filled (city, zip, name, etc.), EXCEPT for the the address line. It gets chopped to the letters I was typing (notice the city field was correctly filled):

![image](https://cloud.githubusercontent.com/assets/11143071/21267094/d36b5922-c376-11e6-8795-14478267195d.png)

At first I thought this might be a browser issue, but I tried this in Chrome/Firefox/Edge. I also tried to use Amazon's address form, and it did not chop off the content:

![image](https://cloud.githubusercontent.com/assets/11143071/21267150/1a326814-c377-11e6-870d-174f231c8b12.png)

I also considered that this might be a theme issue, but I noticed that it's happening in Storefront as well a customer's custom theme. So I thought it might be more relevant here. It could still be a theme issue though. I'll leave it up to you folks to decide.

PS: If there is a temporary work-around that I could relay to customer, that would be fantastic!

Thanks!

**Comment by nabsul** [comment] 2016-12-16 15:21
In case this is useful: Customer reports this issues starting around December 2. Could this be some sort of regression?

**Comment by mikejolley** [comment] 2016-12-16 17:22
Seems to be caused by select2, so it's not a regression in WC I can see.

**Comment by jessepearson** [comment] 2016-12-16 20:22
![screen capture on 2016-12-16 at 15-16-03](https://cloud.githubusercontent.com/assets/4634416/21277132/c3fd0f9a-c3a2-11e6-9d1d-a047357a9ef9.gif)

@nabsul Sorry I took so long to get this in. I believe this is a browser issue. The animation shows me type, arrow down, then hit enter to make a selection; and I also click on the selection and the other items are populated, but not the main address line.

**Comment by nabsul** [comment] 2016-12-16 22:06
@jessepearson Since Amazon's address forms don't have this behavior, I'm guessing it's something that we can fix on our end.

@mikejolley Can you elaborate on "select2"? Where/how can this be avoided? Should I copy this ticket to Storefront instead?

**Comment by mikejolley** [comment] 2016-12-16 22:58
Select2 is the script we use for the country and state dropdowns. When it cuts off, notice the country select gets focus. Not sure why yet but it looks like a select2 bug.

**Comment by mikejolley** [comment] 2016-12-21 14:31
This won't be fixed until select2 us upgraded to v4. I'm putting in a PR but it will need reviewing to see if suitable for 2.7.

**Comment by mikejolley** [comment] 2016-12-21 14:31
See #12666

**Closed by mikejolley** 2016-12-21 14:31 UTC
Labels: Bug
