### ISSUE TITLE
Spelling issues with special characters in French list of countries

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#27211] opened 2020-08-03 18:53 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When you check the list of countries name in French, those that starts with a special character in French are not properly listed alphabetically.

**Expected behavior**
If a country name starts with a special character like
- Î, it should be listed with the list of regular I countries
- É, it should be listed with the list of regular E countries

**Actual behavior**
All countries with special characters are listed at the top of the list, causing wrong alphabetical list.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to checkout page
2. Switch to French

**Screenshots**
https://sgevcen.tinytake.com/tt/NDUwNzY5MF8xNDI4MzE1Ng

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-08-03 19:17
Hi @gevcen,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Here are the countries that start with `É` appearing in the alphabetical order:

![french1](https://user-images.githubusercontent.com/19143190/89218413-faa53680-d59b-11ea-868d-3dba3870d3e0.jpg)

And here are countries starting with `Î` appearing in the alphabetical order:

![french2](https://user-images.githubusercontent.com/19143190/89218421-fe38bd80-d59b-11ea-8dc5-6cf4bd55c369.jpg)

The first thing that I recommend you to check if there are any updates to translation available via `Dashboard / Updates`:

![french3](https://user-images.githubusercontent.com/19143190/89218545-3e983b80-d59c-11ea-95d7-c47057dfe85d.jpg)

If updating translations doesn't help or if no updates available, please test your site for a theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Closed** 2020-08-04 13:31 UTC
Labels: can't reproduce, status: needs feedback
