### ISSUE TITLE
CSV Product Importer in WooCommerce 4.3.1 is broken

### ISSUE THREAD

**Issue by misterproton** [woocommerce/woocommerce#27184] opened 2020-07-30 21:29 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Using a fully updated Ubuntu 18.04 system, CSV Product Importer in WooCommerce 4.3.1 is broken.  It appears the importer fails to "paginate" and only updates a few products, with no visible indication via the progress bar and only a single attempt.

**Expected behavior**
The importer should loop repeatedly as it paginates through the import file.  This was working 10 days ago.

**Actual behavior**
No matter how many products I attempt to update, the progress bar never moves, and the importer never finishes.  If I do even just one product, it will update, however, the progress bar never moves.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. In the admin, go to Products > Import
2. Upload a properly formatted CSV file with products to update
3. Wait

**Isolating the problem (mark completed items with an [x]):**
- [n/a] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [n/a] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [n/a] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://xxx
Site address (URL): https://xxx
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.24-0ubuntu0.18.04.6
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.31-0ubuntu0.18.04.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Total Database Size: 23.39MB
Database Data Size: 14.41MB
Database Index Size: 8.98MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_frm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_frm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.42MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 5.52MB + Index: 5.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.45MB + Index: 0.30MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.20MB + Index: 0.44MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_wps_key: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 32
acf-field-group: 5
attachment: 320
frm_form_actions: 1
frm_styles: 1
page: 9
post: 3
product: 1648
revision: 98
shop_order: 1
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.8.12
Classic Editor: by WordPress Contributors – 1.5
Formidable Forms: by Strategy11 – 4.06.01
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.2
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.22 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.5.3
WooCommerce Product Search: by itthinx – 2.21.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.45 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce: by Automattic – 4.3.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #765 - /shop/
Cart: #776 - /cart/
Checkout: #777 - /checkout/
My account: #778 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: xxx
Version: 0.1
Author URL: http://xxx
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: xxx-theme/woocommerce/archive-product.php
xxx-theme/woocommerce/content-product.php
xxx-theme/woocommerce/content-single-product.php
xxx-theme/woocommerce/single-product.php

### Action Scheduler ###

Complete: 22
Oldest: 2020-07-04 11:04:39 -0400
Newest: 2020-07-30 16:55:51 -0400

`
</details>

**Comment by tammullen** [comment] 2020-07-31 14:14
Hi @misterproton 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 
​
![Screenshot 2020-07-31 at 11 23 28](https://user-images.githubusercontent.com/24649833/89043159-02689f00-d340-11ea-97c7-47dfc670b861.png)
I imported new products using the sample csv file included in WooCommerce (https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv)
![Screenshot 2020-07-31 at 11 24 17](https://user-images.githubusercontent.com/24649833/89043168-04326280-d340-11ea-89b4-afd519a1185c.png)
![Screenshot 2020-07-31 at 11 24 36](https://user-images.githubusercontent.com/24649833/89043177-0694bc80-d340-11ea-9f83-a5312f87e8f7.png)

I then updated some values in that CSV file and imported again in order to update existing products
![Screenshot 2020-07-31 at 11 32 17](https://user-images.githubusercontent.com/24649833/89043222-101e2480-d340-11ea-86e4-61c4daa6e0b2.png)
![Screenshot 2020-07-31 at 15 08 01](https://user-images.githubusercontent.com/24649833/89043239-16140580-d340-11ea-9aad-424b78f1b2b9.png)

Would you be able to provide us a copy of a CSV file that is giving you this issue?
​
I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by misterproton** [comment] 2020-07-31 22:08
Thank you sir!  I followed your steps and will do that next time before submitting.

I found the culprit, it is the "Conditional Shipping and Payments" plugin, which is an official WooCommerce product.  I see in the 1.8.2 update it added:

> Feature - Added support for importing/exporting product-level Restrictions via the WooCommerce Importer/Exporter tool.

So that seems pretty likely the cause of my problem.  When I click on "plugin details" it just takes me to the WooCommerce home page.  Can you help me get to the right place so I can update my import columns?  I'm sure some others must have the same issue.

**Comment by juliaamosova** [comment] 2020-08-06 21:05
Hi @misterproton,

Sorry for the delayed response here. Great to hear that you found the cause of the issue. The best next step would be to reach out to the developers of the `Conditional Shipping and Payments` plugin directly. You can do that on the page below by clicking on the `Contact Support` button:

https://woocommerce.com/vendor/somewherewarm/

I am closing this thread as it is not WooCommerce Core related. However, please feel free to comment on it in case we missed something and we'd take another look.

**Closed by juliaamosova** 2020-08-06 21:05 UTC
Labels: can't reproduce, status: needs feedback
