### ISSUE TITLE
SKU not showing on all products and variable products images not changing on change size.

### ISSUE THREAD

**Issue by jansmaar** [woocommerce/woocommerce#23480] opened 2019-04-24 10:36 UTC
Installed the newest version of woocommerce.

After the update i got some problems.

SKU won't show on any product.
After adding a new image to a variable product (it says sold out)
And normally i can swap between sizes in products and te product image will be change form for example 1 litre to 5 litre. (small bottle to big bottle)

**Comment by jansmaar** [comment] 2019-04-24 10:39
wc_update_product_lookup_tables_column | Complete | 'column' => 'sku' | wc_update_product_lookup_tables | Non-repeating | 2019-04-24 09:22:47 +0000(1 hour 16 minutes ago) | 2019-04-24 09:22:45 +0000action created2019-04-24 09:23:44 +0000action started2019-04-24 09:23:45 +0000action complete
-- | -- | -- | -- | -- | -- | --

**Comment by mikejolley** [comment] 2019-04-24 11:30
Hi,

This is caused by a bug which makes the parent variable product out of stock if the tables are not generated before it's updated. This is resolved in https://github.com/woocommerce/woocommerce/pull/23455

- I've confirmed variation images swap after attributes are changed on the clean install using sample data
- I've confirmed SKUs are displayed as normal

If after the above patch is implemented you can try regenerating lookup table data. See https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-after-the-update

Additionally, you'll need to rule out conflicts if the issue persists. I don't know what you're running because you didn't share the status report but some plugins such as WPML require updating in order to be compatible with the new lookup tables.

Thanks!

**Closed by mikejolley** 2019-04-24 11:30 UTC

**Comment by jansmaar** [comment] 2019-04-24 14:42
@mikejolley 

`
### WordPress Environment ###

WordPress address (URL): https://hidden.nl
Site address (URL): https://hidden.nl
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.16
PHP Post Max Size: 100 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.25
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Totale databasegrootte: 7.92MB
Database datagrootte: 6.27MB
Database index grootte: 1.65MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.02MB + Index: 0.02MB
wp_gdpr_consent: Data: 0.00MB + Index: 0.00MB
wp_gdpr_userlogs: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.38MB + Index: 0.10MB
wp_pay_options: Data: 0.00MB + Index: 0.00MB
wp_pay_option_subs: Data: 0.00MB + Index: 0.00MB
wp_pay_transactions: Data: 0.00MB + Index: 0.00MB
wp_pmxe_exports: Data: 0.08MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB
wp_pmxe_posts: Data: 0.00MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.00MB + Index: 0.00MB
wp_pmxi_files: Data: 0.00MB + Index: 0.00MB
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB
wp_pmxi_images: Data: 0.03MB + Index: 0.01MB
wp_pmxi_imports: Data: 0.11MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.00MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 2.38MB + Index: 0.83MB
wp_posts: Data: 1.46MB + Index: 0.19MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.06MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.02MB
wp_term_relationships: Data: 0.03MB + Index: 0.07MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.27MB + Index: 0.23MB
wp_users: Data: 0.04MB + Index: 0.03MB
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.04MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wp_yoast_seo_links: Data: 0.01MB + Index: 0.01MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 654
basel_sidebar: 2
clients: 6
cms_block: 5
custom_css: 1
customize_changeset: 13
fpf_fields: 1
mc4wp-form: 1
nav_menu_item: 5
page: 29
post: 5
product: 85
product_variation: 336
revision: 393
scheduled-action: 74
services: 21
shop_order: 6
team: 3
testimonial: 3
wc_afrsm: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Redux Framework: door Team Redux – 3.6.15
XTEMOS Post Types plugin: door  – 1.7
CMB2: door CMB2 team – 2.6.0
Contact Form 7: door Takayuki Miyoshi – 5.1.1
Duplicate Post: door Enrico Battocchi – 3.2.2
Flexible Product Fields: door WP Desk – 1.1.17
Flexible Shipping: door WP Desk – 3.3.7
WPBakery Page Builder: door Michael M - WPBakery.com – 5.7
Mailchimp for WordPress: door ibericode – 4.5.1
Really Simple SSL: door Rogier Lankhorst
Mark Wolters – 3.1.5

Recent Posts Widget Extended: door Satrya – 0.9.9.7
Slider Revolution: door ThemePunch – 5.4.8.3
Safe SVG: door Daryll Doyle – 1.9.3
WooCommerce - Show only lowest prices in variable products: door Fernando Tellado – 0.9.8
Woocommerce Pay.nl Payment Methods: door Pay.nl – 3.3.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.2.12
WooCommerce: door Automattic – 3.6.1
Yoast SEO: door Team Yoast – 11.0 – Niet getest met de actieve versie van WooCommerce
WP All Import Pro: door Soflyy – 4.5.6-beta-3.5

### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #808 - /shop/
Winkelmand: #1156 - /cart/
Afrekenen: #1159 - /checkout/
Mijn account: #2325 - /mijn-account/
Algemene voorwaarden: #4392 - /algemene-voorwaarden/

### Theme ###

Name: Basel Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Basel
Parent Theme Version: 4.6.1
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: basel/woocommerce/archive-product.php
basel/woocommerce/cart/cart.php
basel/woocommerce/cart/cross-sells.php
basel/woocommerce/cart/mini-cart.php
basel/woocommerce/checkout/form-checkout.php
basel/woocommerce/content-product.php versie 3.4.0 is verouderd. De hoofdversie is 3.6.0
basel/woocommerce/content-product_cat.php
basel/woocommerce/content-single-product.php versie 3.4.0 is verouderd. De hoofdversie is 3.6.0
basel/woocommerce/content-widget-product.php
basel/woocommerce/global/breadcrumb.php
basel/woocommerce/global/form-login.php versie 3.3.0 is verouderd. De hoofdversie is 3.6.0
basel/woocommerce/global/quantity-input.php versie 3.4.0 is verouderd. De hoofdversie is 3.6.0
basel/woocommerce/loop/loop-end.php
basel/woocommerce/loop/loop-start.php
basel/woocommerce/loop/no-products-found.php
basel/woocommerce/loop/orderby.php versie 3.3.0 is verouderd. De hoofdversie is 3.6.0
basel/woocommerce/loop/pagination.php
basel/woocommerce/loop/sale-flash.php
basel/woocommerce/myaccount/form-login.php versie 3.5.0 is verouderd. De hoofdversie is 3.6.0
basel/woocommerce/myaccount/navigation.php
basel/woocommerce/product-searchform.php
basel/woocommerce/single-product/add-to-cart/variable.php
basel/woocommerce/single-product/meta.php
basel/woocommerce/single-product/product-image.php
basel/woocommerce/single-product/product-thumbnails.php
basel/woocommerce/single-product/related.php
basel/woocommerce/single-product/sale-flash.php
basel/woocommerce/single-product/tabs/tabs.php
basel/woocommerce/single-product/title.php
basel/woocommerce/single-product/up-sells.php
basel/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Action Scheduler ###

Complete: 73
Oldest: 2019-04-24 08:28:57 +0000
Newest: 2019-04-24 13:50:46 +0000

Pending: 1
Oldest: 2019-05-01 13:50:46 +0000
Newest: 2019-05-01 13:50:46 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by jansmaar** [comment] 2019-04-24 14:42
Still can't fix the problems

**Comment by mikejolley** [comment] 2019-04-24 14:56
@jansmaar 

```
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
```

Rule out conflicts (with extensions and the theme), and provide a link to a broken product. 

Bare in mind that if you applied https://github.com/woocommerce/woocommerce/pull/23455 you will need to re-save the affected variable product to get the stock status back to the correct value.
