### ISSUE TITLE
Better stock audit

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#28559] opened 2020-12-11 10:57 UTC
**Is your feature request related to a problem? Please describe.**
There is an inconsistency between orders placed via the front end (shop) and orders placed (or changes made to an existing order) via the admin panel that makes the stock audit very hard. When placing an order via the frontend a meta tag is added to every "line_items" with the name "_reduced_stock" and a value of boolean but when an item is added to an order in the backend and it reduces stock there is no meta tag added.
This makes it very hard to audit and control stock, a essential task for a store, which proved lately to be very important when several bugs where introduced in recent releases (already solved) that had a huge impact in running store. If our stocks get badly synced due to some problem the store owners have to do a complete inventory (huge task) and deal with a lot of angry costumers. A coherent use of tags like "_order_stock_reduced" on the order and "_reduced_stock" on "line_items" is crucial.

**Describe the solution you'd like**
When an item is added to an order via the admin panel and that item reduces stock then add the "_reduced_stock" meta tag.

**Additional context**
Please please take this seriously, there is always a feeling of the developers of this great plug-in (and you do a fantastic work) to be disconnected from the problems of running a real store and of course that is understandable, you do not run an everyday store, but stock management is at the heart of every online store. The stock management at the order flow was greatly improved on the latest releases but there are still problems. Thanks

**Comment by juliaamosova** [comment] 2020-12-11 20:45
Hi @negapo,

Thanks for raising the issue!

It sounds like there is still some kind of a bug related to stock management. 

>There is an inconsistency between orders placed via the front end (shop) and orders placed (or changes made to an existing order) via the admin panel that makes the stock audit very hard.

Can you please describe how to reproduce this and what would the merchant see at the front end?

>Please please take this seriously, there is always a feeling of the developers of this great plug-in (and you do a fantastic work) to be disconnected from the problems of running a real store and of course that is understandable, you do not run an everyday store, but stock management is at the heart of every online store. The stock management at the order flow was greatly improved on the latest releases but there are still problems. Thanks

Some of us actually do run real WooCommerce stores 😀 . But this a great feedback nonetheless, thank you! Please continue to share and thank you for your patience as we work through resolving high priority issues in this repository.

**Comment by juliaamosova** [comment] 2020-12-23 22:44
Hi @negapo,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-12-23 22:44 UTC
Labels: needs feedback
