### ISSUE TITLE
Layered nav widget with 'OR' behavior keep showing attributes applying to (0) products

### ISSUE THREAD

**Issue by opportus** [woocommerce/woocommerce#12393] opened 2016-11-17 21:58 UTC
## EXPLANATION OF THE ISSUE

Everything is in the title...
See the related PR #12395

**Comment by mikejolley** [comment] 2016-11-18 12:38
To quickly explain why this is not a bug, or at least not fixed by your PR.

- OR queries expand the search to include another attribute
- Counts show how many products match the current query.
- The count of an attribute may therefore be 0 if it does not match the current results
- OR however may reveal new matches, as the query is then expanded further.

**Comment by opportus** [comment] 2016-11-18 13:48
Hi @mikejolley, thanks for your explanation.

Then, I believe to solve this ~~bug~~ issue, we can simply conditionnally (basing on the `$count`) output the term here and there ? 

- https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-layered-nav.php#L246
- https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-layered-nav.php#L458

This way it shouldn't interfer with the rest of the processing ? Or do I miss something again ?

**Comment by opportus** [comment] 2016-11-18 15:10
Hi @mikejolley, thanks for your explanation.

If this is not a bug then it is intended ?

On a ecommerce in production, there might be hundreds of attributes... No doubt that it leads to a poor user experience when for example the visitor has to look for a particular attribute amoung potentially a high number of them with a "0" count.

Out of WC scope, ecommerces usually have a similar 'OR' behavior in their layered nav, because that's the behavior the user is naturally expecting. From my experience I can tell you that the 'AND' behavior leads customers to confusion. These ecommerces don't show terms applying to 0 products.

**Closed** 2016-11-22 15:56 UTC
