### ISSUE TITLE
Woocommerce Address issue 

### ISSUE THREAD

**Issue by jhimli2015** [woocommerce/woocommerce#25653] opened 2020-02-13 02:19 UTC
Description
As we are Manufacturer from New Zealand, we sell dairy products via woocommerce, from past week I am facing some address issue , my store only sale at New Zealand, but some customers from USA as well India can place an order and purchased our Item, and we loss all valuable customer like this way , how its possible to Why woocommerce not give any validation when customer enter their town or City other than New Zealand, here is the proof http://prntscr.com/r1jht9
Can any one please give me some resolution on this issue

is there any options to verify town also my store Link: https://milkio.co.nz/buynow/

Jhimli
On behalf of Milkio Foods

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by tammullen** [comment] 2020-02-19 00:45
Hi @jhimli2015 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-02-19 00:45 UTC
