### ISSUE TITLE
Inconsistent meta_data json format in API

### ISSUE THREAD

**Issue by BrianHenryIE** [woocommerce/woocommerce#14907] opened 2017-05-05 18:42 UTC
### EXPLANATION OF THE ISSUE

3.0.5  REST API /products returns meta_data as Array for some products, as Dictionary for others.

I expect it to consistently return either array or dictionary.

### STEPS TO REPRODUCE THE ISSUE

Use Postman to hit `https://mywoocommercesite.com/wp-json/wc/v2/products` with basic authentication and consumer key/secret pair obtained from Settings/API/Keys-Apps.

```
	"meta_data": {
		"0": {
			"id": 123456,
			"key": "inline_featured_image",
			"value": "0"
		},
		"1": {
			"id": 567890,
			"key": "_psad_onsale_order",
			"value": "10000000000000"
		}
	}
```

```
	"meta_data": [{
			"id": 987654,
			"key": "inline_featured_image",
			"value": "0"
		},
		{
			"id": 76543,
			"key": "_psad_onsale_order",
			"value": "10000000000000"
		}
	]
```

This is possibly "by design" but it makes it difficult to parse the json.

**Comment by claudiulodro** [comment] 2017-05-05 21:53
Have you noticed any rhyme or reason as to which product gets which format?

**Comment by BrianHenryIE** [comment] 2017-05-05 22:12
I'm afraid not. I'm not very familiar with WooCommerce and don't populate the products to be conscious of the differences as they were entered. I'll be back in the office next week and can ask whoever does it to run me through things and then focus on two offending examples – they were in the ten most recent so should hopefully be fresh in the mind. I don't think it's appropriate for me to share the full JSON output, I'm afraid, and as I try to compare two, it just looks like a wall of JSON to me, very difficult to distinguish!

**Comment by claudiosanches** [comment] 2017-05-05 22:39
Not an issue on REST API if have two formats, since this comes from `$product->get_meta_data()`, so need to fixed in Products CRUD.
Still no idea where or how this is caused.

@BrianHenryIE have you any idea of how to reproduce it?

**Comment by BrianHenryIE** [comment] 2017-05-05 23:39
This was just the first API call I made, and as I parsed it I narrowed down where it was failing. I'll ask next week for the OK to show you more detailed output. I'm still so new at WooCommerce, I don't even know if there's anything sensitive in the returned JSON.

The API documentation says it should be Array.

**Comment by claudiosanches** [comment] 2017-05-06 00:44
Not too sensitive for products, still meta data for some plugins can maybe contain a files and other things.

I agree, it should always return an array, and is what returns from `$product->get_meta_data()`.

Have you tried to disable other plugins?
Have imported products?

**Comment by mikejolley** [comment] 2017-05-08 15:39
Used here:

https://github.com/woocommerce/woocommerce/blob/b3fc0f31fa28f094643936480ea568d98a316f2a/includes/api/class-wc-rest-products-controller.php#L617

https://github.com/woocommerce/woocommerce/blob/5ca593f7826e217ab5aefb9eadc13d1de6cd0f18/includes/api/class-wc-rest-product-variations-controller.php#L198

https://github.com/woocommerce/woocommerce/blob/84dfaf3c099cfe2f351f703f28abe762dccb0b7a/includes/abstracts/abstract-wc-data.php#L224

And the getter is here:

https://github.com/woocommerce/woocommerce/blob/84dfaf3c099cfe2f351f703f28abe762dccb0b7a/includes/abstracts/abstract-wc-data.php#L265

And this is where it gets read: https://github.com/woocommerce/woocommerce/blob/84dfaf3c099cfe2f351f703f28abe762dccb0b7a/includes/abstracts/abstract-wc-data.php#L448

It's always an array from what I can see. I wasn't able to get it to return anything else but an array in testing..

You may want to see if those products are of a custom type or have any other similarities. Let us know if you can narrow it down so we can reproduce our side, but for now I'm not seeing an issue with the returned data types.

Thanks

**Closed by mikejolley** 2017-05-08 15:39 UTC

**Comment by rrlime** [comment] 2017-11-30 21:04
I am also having this. It seems to have appeared when I added the Facebook/Woo module.

"Normal" meta_data in response text
"meta_data":[
{"id":19880,"key":"fb_image","value":""},
{"id":19881,"key":"fb_visibility","value":"1"},
{"id":19882,"key":"fb_product_group_id","value":"1740700109335555"}],

One product:
"meta_data":{"0":{"id":7124,"key":"_min_variation_price","value":"25.00"},
"1":{"id":7125,"key":"_max_variation_price","value":"25.00"},
"2":{"id":7126,"key":"_min_price_variation_id","value":"705"},
"3":{"id":7127,"key":"_max_price_variation_id","value":"705"},
"4":{"id":7128,"key":"_min_variation_regular_price","value":"25.00"},
"5":{"id":7129,"key":"_max_variation_regular_price","value":"25.00"},
"6":{"id":7130,"key":"_min_regular_price_variation_id","value":"705"},
"7":{"id":7131,"key":"_max_regular_price_variation_id","value":"705"},
"12":{"id":19998,"key":"fb_image","value":""},
"13":{"id":19999,"key":"fb_visibility","value":"1"},
"14":{"id":20000,"key":"fb_product_group_id","value":"1587604627998464"}},

Any thoughts on this?
