### ISSUE TITLE
Publish whole section missing

### ISSUE THREAD

**Issue by Ashok5000** [woocommerce/woocommerce#28623] opened 2020-12-18 05:09 UTC
Accedetly I have press the up arrow key on the Publish Section and now I can't get it back. 
![Web capture_18-12-2020_103011_tera tera lk](https://user-images.githubusercontent.com/42916082/102576684-32acb080-411c-11eb-8bdd-4ed0a578ed9a.jpeg)

After that, I create a new admin Account now the publish section appears. But can't get the publish section for the previous admin account.

**Comment by tammullen** [comment] 2020-12-18 14:13
Hi @Ashok5000 

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. 

![Screenshot 2020-12-18 at 14 12 45](https://user-images.githubusercontent.com/24649833/102623931-2c79fc80-413b-11eb-9c91-be8442922d97.png)
![Screenshot 2020-12-18 at 14 12 52](https://user-images.githubusercontent.com/24649833/102623937-2f74ed00-413b-11eb-8ea5-2df5a9b4abe0.png)
![Screenshot 2020-12-18 at 14 13 00](https://user-images.githubusercontent.com/24649833/102623944-33087400-413b-11eb-9404-4aeb01c8d3b6.png)



The number of details you provided is not enough for us to work with and identify what could be going on.

Please provide us with steps to reproduce the issue on our end. We need to know how your category pages are set-up - step by step instructions for us to recreate your use case.

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by juliaamosova** [comment] 2020-12-29 21:10
Hi @Ashok5000,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-12-29 21:10 UTC
Labels: category: can't reproduce, needs feedback
