### ISSUE TITLE
[GlobalStep] On Frontend, Website goes into an infinite loading upon clicking "Pay for order" option for pending payment order.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29275] opened 2021-03-04 14:51 UTC
## Bug Description:
On Frontend, Website goes into an infinite loading upon clicking "Pay for order" option for pending payment order. 

## Test instructions:
https://github.com/woocommerce/woocommerce/wiki/Critical-Flows
(Shopper->My Account->Pay for Order)

## Environment:
Woocommerce Version : WooCommerce 5.1 RC1 and 5.0
WordPress version: (v5.7 RC2)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Add some products.
1. Go to frontend and place a order for any of the product.
1. Go to WooCommerce->Orders.
1. Change the order status to "Pending payment".
1. Now go to "My Account->Orders" on frontend.
1. Click on "Pay" option for order placed in step 5.
1. Select any payment option and click on "Pay for Order".
1. Observe that on front end, Website goes into infinite loading.

**Note:**
This issue is observed for specific site and able to reproduce the same issue for Guest User and Login User scenario as well.

## Actual Result:
On Frontend, Website goes into an infinite loading upon clicking "Pay for order" option for pending payment order. 

## Expected Result:
Order should get placed upon clicking "Pay for order" option for pending payment order on frontend.

## Video:

https://user-images.githubusercontent.com/41110392/109982075-8d22d980-7d27-11eb-9a66-e2a86bc40b29.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://unique-chinchilla.jurassic.ninja
Site address (URL): https://unique-chinchilla.jurassic.ninja
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: ❌ 5.7-RC2-50482 - There is a newer version of WordPress available (5.8-alpha-50487)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.15
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 4.71MB
Database Data Size: 3.17MB
Database Index Size: 1.54MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 6
nav_menu_item: 5
page: 9
post: 2
product: 20
product_variation: 7
revision: 4
shop_coupon: 1
shop_order: 5
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Query Monitor: by John Blackbourn – 3.6.7
Code Snippets: by Code Snippets Pro – 2.14.0
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.2
Facebook for WooCommerce: by Facebook – 2.3.2
Gutenberg: by Gutenberg Team – 10.1.0
Jetpack by WordPress.com: by Automattic – 9.5
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.3.0

Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
Mollie Payments for WooCommerce: by Mollie – 6.1.0
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce PayPal Payments: by WooCommerce – 1.1.0
WooCommerce Shipping & Tax: by Automattic – 1.25.8
WooCommerce: by Automattic – 5.0.0
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.1.0


### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Admin: by WooCommerce – 2.0.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 30
Oldest: 2021-03-03 09:03:45 +0000
Newest: 2021-03-04 13:01:34 +0000

Pending: 2
Oldest: 2021-03-04 13:27:14 +0000
Newest: 2021-03-04 13:27:14 +0000

`
```
</details>

**Comment by tammullen** [comment] 2021-03-08 11:51
Hi @gglobalstep 

Thank you for taking the time to report this bug, we really appreciate your help. With only WooCommerce installed I can't reproduce it on my end. 

![Screenshot 2021-03-08 at 10 51 10](https://user-images.githubusercontent.com/24649833/110316901-4a9d1d80-8003-11eb-86f7-4af12c1680c2.png)
![Screenshot 2021-03-08 at 10 51 22](https://user-images.githubusercontent.com/24649833/110316907-4cff7780-8003-11eb-9673-49ddc85f9f48.png)
![Screenshot_2021-03-08_at_10_51_44](https://user-images.githubusercontent.com/24649833/110316977-66082880-8003-11eb-99ce-9ba0c3f81f42.png)

However I then created a site that matched the versions of WordPress, WooCommerce and Installed and Activated all the plugins in your status report and I was able to reproduce the issue.

![Screenshot 2021-03-08 at 11 02 01](https://user-images.githubusercontent.com/24649833/110317080-8a640500-8003-11eb-8f1d-8427821bf031.png)
![Screenshot 2021-03-08 at 11 03 09](https://user-images.githubusercontent.com/24649833/110317095-8df78c00-8003-11eb-9774-a9f58e1704fd.png)

Infinite loading after trying to Pay with Cash or Cheque.

**After some debugging I have narrowed it down to the Klarna Payments for WooCommerce**

When installing and activating Klarna Payments for WooCommerce with WooCommerce 5.0 or 5.1 RC on both WordPress 5.6.2 and WordPress 5.7 RC this infinite loading occurs for the Payment Methods I tried. I also checked on Storefront Theme.

![Screenshot 2021-03-08 at 11 46 33](https://user-images.githubusercontent.com/24649833/110317533-3279ce00-8004-11eb-9e89-953d8c82ddf7.png)

I'm going to close this for now as I will raise an issue on your behalf in the repository for Klarna Payments for WooCommerce

**Closed by tammullen** 2021-03-08 11:51 UTC

**Comment by tammullen** [comment] 2021-03-08 12:00
Issue Raised here: https://github.com/krokedil/klarna-payments-for-woocommerce/issues/215
