### ISSUE TITLE
has been removed from your cart because it can no longer be purchased.

### ISSUE THREAD

**Issue by baraklevy** [woocommerce/woocommerce#26531] opened 2020-05-16 11:27 UTC
**Describe the bug**
We get emails from visitors that write to us they can't purchase a product because it is not available anymore, and we are talking about virtual products

**To Reproduce**
1. Go to 'https://www.anabella.co.il/es/producto/introduccion-a-la-psicologia-individual/'
2. Click on 'Anadir al carrito'  (add to cart)
3. close the browser or remove the product from the cart
4. try to add it again

**Screenshots**
https://www.dropbox.com/sh/97sekiex0a43790/AACP4J74_c0kdrdUhM9eEshea?dl=0

**Expected behavior**
the products need to be available always

**Isolating the problem (mark completed items with an [x]):**
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.anabella.co.il
Site address (URL): https://www.anabella.co.il
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.10
PHP Version: 7.2.18
PHP Post Max Size: 256 MB
PHP Time Limit: 256
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.60-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: yas_
Total Database Size: 153.44MB
Database Data Size: 108.89MB
Database Index Size: 44.55MB
yas_woocommerce_sessions: Data: 0.23MB + Index: 0.02MB + Engine InnoDB
yas_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_woocommerce_downloadable_product_permissions: Data: 0.14MB + Index: 0.27MB + Engine InnoDB
yas_woocommerce_order_items: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
yas_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
yas_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yas_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aryo_activity_log: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_blc_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blc_instances: Data: 0.06MB + Index: 0.01MB + Engine MyISAM
wp_blc_links: Data: 0.28MB + Index: 0.04MB + Engine MyISAM
wp_blc_synch: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_cf7dbplugin_st: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_submits: Data: 0.38MB + Index: 0.41MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_addon_payment_callback: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_addon_payment_transaction: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 2.17MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_view: Data: 5.52MB + Index: 4.03MB + Engine InnoDB
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_languages_translations: Data: 0.10MB + Index: 0.10MB + Engine MyISAM
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_node: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_strings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_positions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_translations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translate: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translate_job: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translations: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_icl_translation_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_insert_link_classes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_iwp_backup_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.64MB + Index: 0.04MB + Engine MyISAM
wp_postmeta: Data: 1.03MB + Index: 0.28MB + Engine MyISAM
wp_posts: Data: 1.69MB + Index: 0.17MB + Engine MyISAM
wp_redirection_404: Data: 25.05MB + Index: 7.05MB + Engine MyISAM
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_redirection_logs: Data: 7.77MB + Index: 2.44MB + Engine MyISAM
wp_redirection_modules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_campaignmonitor: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_meta: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_view: Data: 5.02MB + Index: 2.81MB + Engine MyISAM
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.56MB + Index: 0.06MB + Engine MyISAM
wp_rg_lead_detail: Data: 0.89MB + Index: 1.00MB + Engine MyISAM
wp_rg_lead_detail_long: Data: 0.28MB + Index: 0.01MB + Engine MyISAM
wp_rg_lead_meta: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_paypal: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_paypal_transaction: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_toolset_associations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_toolset_relationships: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_toolset_type_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfConfig: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLeechers: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfStatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_actionscheduler_actions: Data: 0.30MB + Index: 0.34MB + Engine InnoDB
yas_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_actionscheduler_logs: Data: 0.30MB + Index: 0.22MB + Engine InnoDB
yas_caos_webfonts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_caos_webfonts_subsets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
yas_fv_enteries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_fv_entry_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yas_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_gf_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
yas_gf_form_revisions: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
yas_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_icl_cms_nav_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
yas_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_icl_mo_files_domains: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
yas_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_icl_strings: Data: 3.52MB + Index: 6.61MB + Engine InnoDB
yas_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_icl_string_positions: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
yas_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_icl_string_translations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
yas_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_icl_translate: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
yas_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_icl_translations: Data: 0.23MB + Index: 0.67MB + Engine InnoDB
yas_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_icl_translation_status: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
yas_iwp_backup_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_mo_campaign_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_mo_campaign_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_mo_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_mo_email_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_mo_email_campaigns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_mo_optin_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_mo_optin_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_options: Data: 5.19MB + Index: 1.50MB + Engine InnoDB
yas_postmeta: Data: 23.48MB + Index: 5.92MB + Engine InnoDB
yas_posts: Data: 11.52MB + Index: 0.89MB + Engine InnoDB
yas_redirection_404: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
yas_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_redirection_items: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
yas_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
yas_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
yas_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
yas_revslider_slides: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
yas_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
yas_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_toolset_associations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yas_toolset_post_guid_id: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_toolset_relationships: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
yas_toolset_type_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_usermeta: Data: 1.47MB + Index: 2.94MB + Engine InnoDB
yas_users: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
yas_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yas_wc_customer_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
yas_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
yas_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
yas_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
yas_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_yoast_indexable: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
yas_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yas_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yas_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yas_yoast_seo_links: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
yas_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 1
amn_mi-lite: 1
attachment: 414
customize_changeset: 1
elementor_lead: 1797
elementor_library: 28
event: 184
iwp_log: 225
lecture: 126
lp: 2
nav_menu_item: 44
oembed_cache: 12
page: 91
pojo_forms: 2
post: 49
product: 50
publications: 10
recommendation: 9
revision: 1534
shop_coupon: 1
shop_order: 606
shop_order_refund: 2
tablepress_table: 1
view: 3
view-template: 4
wp-types-group: 1
zoom-meetings: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (50) ###

Admin Menu Editor Pro: by Janis Elsts – 2.11
Advanced Custom Fields PRO: by Elliot Condon – 5.8.11
Akismet Anti-Spam: by Automattic – 4.1.5
Classic Editor: by WordPress Contributors – 1.5
CMS Tree Page View: by Pär Thernström – 1.6
Custom Related Products for WooCommerce: by Scott Nelle – 1.3 – Installed version not tested with active version of WooCommerce 4.1.0
Disable Comments: by Samir Shah – 1.10.2
Disable Google Fonts: by Milan Dinić – 2.0
Duplicate Post: by Enrico Battocchi – 3.2.4
Ele Custom Skin: by Dudaster.com – 2.1.0
Elementor Pro: by Elementor.com – 2.9.4
Elementor: by Elementor.com – 2.9.8
Enable Media Replace: by ShortPixel – 3.3.12
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.18
Woo Pelecard Gateway: by Ido Friedlander – 1.3-iCount+EZcount – Installed version not tested with active version of WooCommerce 4.1.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Gravity Forms: by Gravity Forms – 2.4.18
Gravity Forms Campaign Monitor Add-On: by Gravity Forms – 3.8
OMGF: by Daan van den Bergh – 3.4.3
Insert Headers and Footers: by WPBeginner – 1.4.5
Karma Music Player by Kadar: by Kadar Claudiu – 1.1.2
Lenix Elementor Leads addon: by Lenix – 1.8.0
Page Links To: by Mark Jaquith – 3.3.3
Pojo Custom Fonts: by Pojo Team – 1.0.5
Pojo News Ticker: by Pojo Team – 1.0.3
Pojo Sidebars: by Pojo Team – 1.0.3
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.3.2

Redirection: by John Godley – 4.7.2
WPML Multilingual CMS: by OnTheGoSystems – 4.3.12
TablePress: by Tobias Bäthge – 1.11
Toolset Types: by OnTheGoSystems – 3.3.10
Ultimate Addons for Elementor: by Brainstorm Force – 1.24.2
User Switching: by John Blackbourn & contributors – 1.5.4
Zoom Integration for WooCommerce: by CodeManas – 2.1.6 – Installed version not tested with active version of WooCommerce 4.1.0
Video Conferencing with Zoom: by Deepen Bajracharya – 3.3.11
WC Disable Zoom / Lightbox features: by Rynaldo Stoltz – 1.0 – Installed version not tested with active version of WooCommerce 4.1.0
WeSafe by uPress: by uPress – 1.7.2
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.4 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.21 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.8.1

WooCommerce Multilingual: by OnTheGoSystems – 4.8.0 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce: by Automattic – 4.1.0
Music Player for WooCommerce: by CodePeople – 5.0.102 – Installed version not tested with active version of WooCommerce 4.1.0
Yoast SEO: by Team Yoast – 14.1
Yoast SEO Multilingual: by OnTheGoSystems – 1.1.1
Toolset Views: by OnTheGoSystems – 3.1.3
WPML CMS Nav: by OnTheGoSystems – 1.5.2
WPML Media: by OnTheGoSystems – 2.5.5
WPML String Translation: by OnTheGoSystems – 3.0.9
WPML Translation Management: by OnTheGoSystems – 2.9.6

### Inactive Plugins (2) ###

WooCommerce Admin: by WooCommerce – 1.1.1
WP Rocket: by WP Media – 3.2.5

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
zoom_meeting (zoom_meeting)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8315 - /shop/
Cart: #8316 - /cart-2/
Checkout: #8317 - /checkout-2/
My account: #8318 - /my-account-2/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Atlanta Child
Version: 1.0.0
Author URL: http://pojo.me/
Child Theme: ✔
Parent Theme Name: Atlanta
Parent Theme Version: 5.2.0
Parent Theme Author URL: http://pojo.me
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: atlanta-child/woocommerce/emails/customer-completed-order.php version 3.5.0 is out of date. The core version is 3.7.0
atlanta-child/woocommerce/emails/email-downloads.php version - is out of date. The core version is 3.4.0
atlanta-child/woocommerce/emails/email-order-details.php version 3.3.1 is out of date. The core version is 3.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 1,008
Oldest: 2020-04-18 18:03:48 +0300
Newest: 2020-05-16 13:54:14 +0300

`
```
</details>

**Comment by tammullen** [comment] 2020-05-18 14:26
Hi @baraklevy 

Thank you for raising the issue. However, I can’t reproduce it on my end.
​
I was able to add and remove and add again a Virtual Product with no issues.
​
I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-05-26 13:37
Hi @baraklevy,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-05-26 13:37 UTC
Labels: can't reproduce, status: needs feedback
