### ISSUE TITLE
Is there a way to create a separate Order Summary Page after checkout page?

### ISSUE THREAD

**Issue by namanmodidigital** [woocommerce/woocommerce#26040] opened 2020-03-31 10:29 UTC
I'm setting up the functionality of the Multiple Shipping Address for Multiple products in Single order. I wanted to create a separate page after checkout which will show the complete order summary along with payment gateway. I wanted toIs there a way to add that? Currently, the checkout page contains the entire order details along with payment gateway. Let me know the possible options to achieve the same.

**Comment by tammullen** [comment] 2020-03-31 19:25
Hi @namanmodidigital 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
Label:

**Closed by tammullen** 2020-03-31 19:25 UTC
