### ISSUE TITLE
Bug dropdown widget

### ISSUE THREAD

**Issue by mRelby** [woocommerce/woocommerce#30438] opened 2021-08-05 21:13 UTC
Yesterday I discovered a bug that does not allow using the drop-down list when the WordPress admin bar is active.

I created a [topic](https://wordpress.org/support/topic/bug-dropdown-widgets-do-not-work-with-the-active-wordpress-admin-bar-video/) (**be sure to check it out**!). But so far no one has answered anything sensible to me.

I am adding ONE MORE video showing the bug!

And just don't say that everything is all right! Finally open your eyes and test the plugin with the current version of WordPress!

last video:
https://youtu.be/Wiy2cWiWLB0
Enjoy!

**Comment by mRelby** [comment] 2021-08-06 10:12
Isn't that interesting to anyone?

**Comment by juliaamosova** [comment] 2021-08-06 14:34
Hi @mRelby,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mRelby** [comment] 2021-08-06 14:41
> Hi @mRelby,
> 
> Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
> 
> **Describe the bug**
> A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Isolating the problem (mark completed items with an [x]):**
> 
> * [ ]  I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> * [ ]  This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
> * [ ]  I can reproduce this bug consistently using the steps above.
> 
> **WordPress Environment**
> 
> ``` Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin. ```

Firstly. I cannot describe it in detail and clearly, since I do not speak English. And Google Translate will do it very badly that you will not understand anything.

Secondly. I recorded a video, and more than one, where I clearly show what the essence of the problem is. This is not enough? Sorry, but I believe you have staff looking for and checking the plugin for bugs and errors. And I'm not one of them.

I get the impression that I need it more than the developers.

No. I am tired of this. It's easier for me to use another plugin.

And if you have no regrets to deal with this bug - your right. But I believe that after thousands of other users update WordPress to version 5.8, you will receive many similar complaints about this error.

**Comment by mRelby** [comment] 2021-08-06 15:25
https://youtu.be/yj7GAvPictE

**Comment by nerrad** [comment] 2021-08-06 15:59
@mRelby while I appreciate you creating videos for us showing how to reproduce, the template for filling out bug reports is important for us to be able to more quickly ensure we have environments setup to match replication steps (without having to watch an entire video). Videos/screenshots are great as supplements to reports, but not as the _only_ support for a bug report.

With that said, I was able to reproduce this:

**WordPress Version**: 5.8
**WooCommerce Version**: 5.5.2
**Theme**: Storefront 3.7.0 (although I don't think theme matters, I could reproduce with with Twenty Twenty One as well)
**Browser**: Firefox (although browser doesn't seem to matter, I can reproduce in Chrome).

Steps:

1. Add legacy widget for "filter by attribute" set to dropdown in the sidebar for the theme (minimal reproduction is with no other widgets).
2. Make sure you are logged in as admin.
3. Visit the shop page (website.com/shop).
4. The first selection of a color attribute will work. Subsequent selections do not trigger the dropdown field unless you click and hold.

| clicking only | click and hold |
|--------------| --------------|
|![CleanShot 2021-08-06 at 11 50 34](https://user-images.githubusercontent.com/1429108/128538475-bae9d03b-2130-4187-b55f-be7e7e0eb889.gif) | ![CleanShot 2021-08-06 at 11 54 33](https://user-images.githubusercontent.com/1429108/128538519-26111799-814c-4813-b0a8-9b2bfc484d83.gif) |

There are no errors in the console.

If you are **not logged in** then the dropdown works as expected where clicking opens up the dropdown and the user is able to select.

@juliaamosova this looks like a _regression_ as I was unable to reproduce on another dev site running 5.5.0-dev of WooCommerce (but still running WordPress 5.8).

**Comment by mRelby** [comment] 2021-08-06 16:06
@nerrad, oh my God! Finally, finally, at least someone managed to understand where and what the problem is 👍🤝
The others thought I was a fool. And supposedly this problem does not exist...

ps. I confirm that the error occurs regardless of the browser or the theme used.

**Comment by nerrad** [comment] 2021-08-06 16:14
> The others thought I was a fool.

This may be a language barrier thing, but I don't think it's fair to assume anyone thought you were a fool. We're all motivated to resolve discovered and reproducible bugs.

**Comment by mRelby** [comment] 2021-08-06 16:22
@nerrad No. Everything is correct here :)

When I talked about this issue in another community (telegram chat), I was told that I was doing something wrong. And that no one else has such a problem.

But, as you can see, I'm not alone.
And something tells me that in the near future hundreds, if not thousands of other WordPress users will face this problem, who will update the CMS to version 5.8...

**Thanks** again for being able to explain the problem. I couldn't have done it because of the language barrier.

**Comment by mRelby** [comment] 2021-08-06 17:12
@juliaamosova, до меня только дошло, что вы знаете русский 😅 а это существенно упрощает коммуникацию.

Итак, давайте сначала...
Проблема заключается в том, что если выбрать устаревший виджет фильтрации по атрибутам, при этом указать тип **Выпадающее меню**, то он не будет работать...
https://prnt.sc/1jxqhkw
...ну как не будет, первый раз сработает (но не всегда), а дальше если на него нажать, то как будто отменяется нажатие. В итоге пользователь не сможет корректно воспользоваться таким фильтром.

**Самое интересное то, что проблема наблюдается только в том случае, когда активна админ-панель WordPress**:
https://prnt.sc/1jxpb4u
Если же её скрыть, либо зайти на сайт, как **неавторизированный** пользователь - то всё прекрасно работает. 

Из этого делаю вывод, что у WooCoomerce 5.5.2 конфликт с WordPress 5.8.
Напомню, что я использую актуальные (самые свежие версии) WP и WC. 

Браузер, а также его режим (приватный/инкогнито) на ошибку никак не влияет. Точно также, как неважно, какая тема используется на сайте. Более того, ради интереса создавал сайт на двух разных хостинга - и снова есть ошибка.

@nerrad чуть выше описал практически тоже самое. За что ему отдельное спасибо! Хотя бы ему удалось понять, что я имею ввиду...
Надеюсь, что ваши коллеги найдут причину и устранят. Что-то мне подсказывает, что особенно эта проблема будет актуальна после массового обновления WP до 5.8. Так что получается, что я своего рода первопроходец, которому удалось выявить ошибку до того, как это стало мейнстримом 😅😂

За такую "находку" мне полагается "пирожок" 😊

Как-то так.

**Comment by juliaamosova** [comment] 2021-08-06 18:53
Thank you for taking the time to reproduce this issue and getting to the bottom of it @nerrad! Flagging this as a `bug`. 

@mRelby thank you again for reporting the issue. I second what @nerrad wrote above:

>while I appreciate you creating videos for us showing how to reproduce, the template for filling out bug reports is important for us to be able to more quickly ensure we have environments setup to match replication steps (without having to watch an entire video). Videos/screenshots are great as supplements to reports, but not as the only support for a bug report.

Videos do help to understand the issue but being able to quickly scan written steps to reproduce the issue help us to get to the bottom of the issue a lot quicker. This is why we request folks to fill out the template here. Help us to help you faster so that we could collectively resolve the issue quicker. 

In any case, thank you for writing another comment and explanation of the issue in the Russian language. It is against our best practices here for me to reply to you in Russian as others will not understand our communication. The next person who will pick up the issue may not be me which is why we aim to communicate here in English. 

In order for others to understand your comment, I used [Google Translate](https://translate.google.com/) to translate your message:

>@juliaamosova, it just dawned on me that you know Russian 😅 and this greatly simplifies communication.

>So let's first ...
The problem is that if you select the outdated attribute filtering widget and specify the Drop-down menu type, it won't work ...
https://prnt.sc/1jxqhkw
... well, how it will not be, the first time it will work (but not always), and then if you click on it, it seems as if the click is canceled. As a result, the user will not be able to use this filter correctly.

>The most interesting thing is that the problem only occurs when the WordPress admin panel is active:
https://prnt.sc/1jxpb4u
If you hide it, or go to the site as an unauthorized user, then everything works fine.

>From this I conclude that WooCoomerce 5.5.2 has a conflict with WordPress 5.8.
Let me remind you that I am using the current (most recent versions) WP and WC.

>The browser, as well as its mode (private / incognito), does not affect the error in any way. In the same way, it doesn't matter what theme is used on the site. Moreover, for the sake of interest, I created a site on two different hosting - and again there is an error.

>@nerrad described almost the same thing just above. For which special thanks to him! At least he managed to understand what I mean ...
Hope your colleagues find the cause and fix it. Something tells me that this problem will be especially relevant after the massive update of WP to 5.8. So it turns out that I'm kind of a trailblazer who managed to spot the bug before it went mainstream :)

>For such a "find" I am entitled to a "pie" 😊

>Something like this.

Priority of this issue will be assigned shortly after we'd go through a round of prioritization.

**Comment by mRelby** [comment] 2021-08-09 15:59
Hello everyone!

Is there any information? Does it make sense to expect that the bug will be resolved soon, or should I pay attention to some other plugin that will provide the same functionality?

**Comment by nerrad** [comment] 2023-10-12 20:22
I'm closing this issue because the classic (or legacy) product widgets are no longer available. The new filter blocks can be used on the Shop page and this bug doesn't happen with them.

**Closed by nerrad** 2023-10-12 20:22 UTC
Labels: type: bug, priority: high, focus: shop [team:Proton], focus: product [team:Mothra], plugin: woocommerce
