### ISSUE TITLE
Add new product issue - setting product image and product tags not working (after the update)

### ISSUE THREAD

**Issue by ornellapal** [woocommerce/woocommerce#28208] opened 2020-11-06 23:20 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When I want to add a new product, there are 2 steps that bugs.
1. Can't add Product tags -  the button add doesn't work, as well as the link "Choose from the most used tags". I am able to type a tag name in the box field, however I can't submit it. 
2. Can't add a Product Image - I click the "set product image" link, then I click "Media Library" to choose the image I want. I click "Show" and then the "use as product image" link doesn't work. In addition, I can click the "Save all changes" button at the bottom of that page to save changes, however there's no way I can exit this page and go back to editing my new product....  

**Expected behavior**
I should be able to add an image and product tags without being stuck on that page.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'Products' tab
2. Click on 'Add New'
3. Scroll down to 'Product tags'
4. Error: "Add" button and "Choose from the most used tags" link doesn't work
AND'
1. Scroll down to 'Product image'
2. Click on 'Set product image'
3. Click on 'Media Library'
4. Click on 'Show' on an image
5. Error: cant add that image and can't exit the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/74078880/98423469-4c0a0980-2054-11eb-8acf-dbd435ec94f4.png)
![image](https://user-images.githubusercontent.com/74078880/98423591-b91d9f00-2054-11eb-85f9-2375686dd3e6.png)

![image](https://user-images.githubusercontent.com/74078880/98423559-97bcb300-2054-11eb-86b1-8b2bbaf08ead.png)

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-11-13 19:56
Hi @ornellapal,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested using WooCommerce 4.7:

![](http://g.recordit.co/czMRDyfwhB.gif)

Can you please confirm that you tested your site for theme and plugins conflict? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by tammullen** [comment] 2020-11-23 12:59
Hi @ornellapal 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2020-11-23 12:59 UTC
Labels: can't reproduce, status: needs feedback
