### ISSUE TITLE
changing pages when pressing 'Apply'

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12476] opened 2016-11-28 06:51 UTC
If for example I am in page 6 of my orders and I select 4 orders with the checkbox then in 'Bulk Actions' I choose one action and press 'Apply', the action is done but it sends me back to the first page of the orders instated of staying in page 6.

This is extremely uncomfortable. It should leave me on the same page.

**Comment by justinshreve** [comment] 2016-11-28 19:03
Confirmed. Doesn't seem to happen with products / quick edit, but this is happening for me with orders.

**Comment by mikejolley** [comment] 2016-12-07 12:59
We'd need to split bulk-actions from filters. Filter should go to page 1 because they reduce the result set.

Punting.

**Comment by mikejolley** [comment] 2016-12-15 15:51
Fixed in 4.7 :D

**Closed** 2016-12-15 15:52 UTC
Labels: Bug
