### ISSUE TITLE
Python - raise JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by dengwen168** [woocommerce/woocommerce#29811] opened 2021-05-02 11:26 UTC
I am trying to use python & woocommerce API to post products, but it doesn't work.

`Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(wcapi.get("products").json())
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Kevin\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Kevin\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Kevin\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Here is the test code:

`from woocommerce import API

wcapi = API(
    url="http://www.xx.net/",
    consumer_key="ck_xxxxxcea1735394c5f82dbb2b190d4b5c79e6",
    consumer_secret="cs_xxxxx62fe133302510438b20ffb7f4ebf9",
    version="wc/v3"
)

print(wcapi.get("products").json())`

**Comment by tammullen** [comment] 2021-05-09 10:42
Hi @dengwen168  

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-05-09 10:42 UTC
