### ISSUE TITLE
[3.2] No Shipping Methods Available allows for checkout

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#17025] opened 2017-10-02 19:10 UTC
In 3.2 RC1, if there are no shipping methods configured, the user can check out with physical objects (that have dimensions and weights).

## To Reproduce ##

On a new install on WC 3.2, check out with a non-virtual item when no shipping method has been configured. You should be able to check out without any messages or errors. I can check out this way with Stripe and something like Check Payments.

It should be noted that if there just aren't any _matching_ rates, i.e. nothing set for your country, then it returns the correct error message of "No Shipping Methods Available". This means that existing customers shouldn't encounter this problem (only sites who haven't set up shipping yet).

### Extra Note - Stripe Checkout Popup ###

With No Shipping Methods Available, the Stripe Checkout popup still allows you to enter card info and it looks like it's going to the next step, but it returns you back to the checkout page.

Mini Screencast: http://recordit.co/1HD7FT3Bsw

## Possible Solutions ##

Ideally, we would want the store owner to set Free Shipping if that is their intention - I could see this being very problematic for new users, as if they forgot to enable a shipping method during setup or if no methods are added in the cart it would allow for the order to process without any shipping charges.

We could add the "No Shipping Methods Available" text so users can't check out, or a notice in the backend that nags the store administrator if they haven't configured shipping rates yet.

Finally, it would be nice to grey out the Stripe popup button if there aren't any matching shipping methods, though I know that's a payment vs. a shipping thing so it might be a little trickier.

@gspitzer 's excellent debugging found this one, I was able to confirm.

**Comment by DanielSantoro** [comment] 2017-10-02 19:27
Hold on this, testing a little further to see if it's a specific trigger. _May_ only be with Stripe Checkout enabled, will come back.

**Comment by DanielSantoro** [comment] 2017-10-02 19:51
Updated with clarification on what happens with stores who have rates that don't match the customer location vs. no rates set at all.

**Comment by claudiulodro** [comment] 2017-10-03 18:15
The Stripe thing should definitely get fixed (@roykho, @gedex looks like your team maintains the extension?). I don't know about the shipping problem, though. WC has had that behavior since at least 3.0 (just tested), and that is likely the expected behavior that users have for that. @mikejolley?

**Comment by claudiulodro** [comment] 2017-10-04 00:10
OK. Got clarification. The shipping settings are supposed to behave like that. Closing this issue since there is nothing in WooCommerce core to fix.

**Closed by claudiulodro** 2017-10-04 00:10 UTC
Labels: Status: Needs Review, Type: Bug

**Comment by gedex** [comment] 2017-10-04 01:12
> With No Shipping Methods Available, the Stripe Checkout popup still allows you to enter card info and it looks like it's going to the next step, but it returns you back to the checkout page.

Would you mind to log that in Stripe GH issue, @DanielSantoro?

**Comment by gspitzer** [comment] 2017-10-04 07:42
@gedex it seems @DanielSantoro and I totally missed these: 

- the Stripe issue has already been logged in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/161 

- and fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
