### ISSUE TITLE
woocom not creating customer account if coupon applied

### ISSUE THREAD

**Issue by RudyBekker** [woocommerce/woocommerce#28769] opened 2021-01-09 20:39 UTC
hey guys, does anyone know why woocomerce is not creating an account for my customer when they use a coupon? 

I am using a 100% discount coupon

The order is processed and email sent with the download file for the customer..

But its not creating an account like it does with people who are normally purchasing 

Anyone have any ideas as to what the issue can be?

**Comment by juliaamosova** [comment] 2021-01-10 23:18
Hi @RudyBekker,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-01-10 23:18 UTC
