### ISSUE TITLE
E-mail for completed orders

### ISSUE THREAD

**Issue by xstocler** [woocommerce/woocommerce#21221] opened 2018-08-29 19:19 UTC
Every time I complete an order, changing the status to complete, I receive an email as a new order.

Sending e-mail when the customer opens the order is normal

would you be able to change or disable it?

**Comment by claudiulodro** [comment] 2018-08-30 17:43
Hi there,

I'm not sure exactly what you are describing as the problem, but there is an order complete email sent out when the order status changes to complete. You can deactivate any emails in the **WooCommerce > Settings > Emails** settings page. Hope this clears things up. 

I'm closing this issue, as there isn't sufficient information for me to reproduce or determine the issue you are describing. In my testing e-mail sending is working correctly and as-intended.

Thanks.

**Closed by claudiulodro** 2018-08-30 17:43 UTC

**Comment by xstocler** [comment] 2018-08-30 18:01
I apologize for the lack of information

I'm getting the same email when the customer makes the purchase.
But in this case, upon completing the request.
