### ISSUE TITLE
Gallery Thumbnail Images Unspecified Dimensions

### ISSUE THREAD

**Issue by demian1985** [woocommerce/woocommerce#25461] opened 2020-01-22 09:00 UTC
**Describe the bug**
Lately I noticed that the native thumbnails in the woocommerce product gallery are loaded with unspecified dimensions. This came from a GTMetrix Report. I have narrowed it down, by only having the WC plugin and a default theme, and it shows that the gallery thumbnails are missing the height and width attributes.

**Screenshots**
GTMetrix report: http://prnt.sc/qr5bt1

**Expected behavior**
Gallery thumbails need width and height attributes, so it will reduce calculating these and it benefits page load time

**Isolating the problem:**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WooCommerce Storefront theme
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): _private_
Site address (URL): _private_
WC Version: 3.9.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.25
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.29-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wpws_
Total Database Size: 610.19MB
Database Data Size: 333.95MB
Database Index Size: 276.24MB
wpws_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpws_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpws_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpws_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpws_woocommerce_order_items: Data: 6.52MB + Index: 2.52MB + Engine InnoDB
wpws_woocommerce_order_itemmeta: Data: 38.58MB + Index: 31.09MB + Engine InnoDB
wpws_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpws_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpws_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpws_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpws_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpws_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpws_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpws_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpws_commentmeta: Data: 0.23MB + Index: 0.33MB + Engine InnoDB
wpws_comments: Data: 40.58MB + Index: 31.09MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): 
❌Your store is not using HTTPS. 
✔Hide errors from visitors: 

### Active Plugins (4) ###
WooCommerce: by Automattic – 3.9.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###
Shop base: ❌ Page not set
Cart: #9294 - /winkelwagen/
Checkout: #9290 - /kassa/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: #9121 - /algemene-voorwaarden/

### Theme ###
Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ 
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 23
Oldest: 2020-01-02 17:08:47 +0100
Newest: 2020-01-21 23:47:53 +0100

Pending: 1
Oldest: 2020-01-28 23:47:52 +0100
Newest: 2020-01-28 23:47:52 +0100

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 82
Oldest: 2019-04-28 18:58:24 +0200
Newest: 2019-11-04 19:22:48 +0100
`
</details>

**Comment by tammullen** [comment] 2020-01-24 18:14
Hi @demian1985 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

With just WooCommerce 3.90 active on the default shop page and using the same GTMetrix Analysis tool I don't get the warnings you saw in your screenshot
![Screenshot 2020-01-24 at 18 03 17](https://user-images.githubusercontent.com/24649833/73092649-e12c7f00-3ed4-11ea-9adf-44489c1de27a.png)


Please provide us with more details about the issue which may help us to evaluate it further such as the setup of the page you had analysed. Is it the default shop page, what is the name of the theme used and have you used any WooCommerce blocks such as the All Products block?

**Comment by demian1985** [comment] 2020-01-25 09:42
Hi @tammullen 

Thanks for coming back. The product image gallery with thumbnails is part of the single product page, so its thumnbnails: [http://prnt.sc/qsn9bg](http://prnt.sc/qsn9bg)

As mentioned in my description, I have only woocommerce enabled and the default storefront theme, nothing else.

I hope this helps.

**Comment by demian1985** [comment] 2020-02-07 17:54
Hello @tammullen 

Were you able to reproduce this? I have currently updated to 3.9.1 and it's still missing the attributes.

Thank you

**Comment by juliaamosova** [comment] 2020-02-27 21:50
Hi @demian1985,

Thank you for getting back to us with more details and apologies for the delayed response. I can reproduce it on my end (using https://gtmetrix.com/):

![dimensions](https://user-images.githubusercontent.com/19143190/75489923-2c78f800-5981-11ea-8bd7-777a09dd2632.jpg)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by diggeddy** [comment] 2020-11-13 15:05
Hi @juliaamosova 

the absence of the width and height attributes means that the layout cannot be defined prior to those images being loaded. This has severe consequences for Googles new WebDev metrics, particularly CLS.

You can see the impact this has on the Storefront Demos Pagespeed Insight report:

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fthemes.woocommerce.com%2Fstorefront%2Fproduct%2Fbuild-your-dslr%2F%23camera-body

The element listed under Avoid Large Layout Shifts it is affecting is the:

`<ol class="flex-control-nav flex-control-thumbs">`

This elements height cannot be defined until the images are loaded.

The new WebDev metrics will become part of Googles Ranking algorithm in 2021. It would be good to see this resolved before it has a negative affect on a sites ranking.

**Comment by mfs-mindsize** [comment] 2021-02-02 18:46
@tammullen @juliaamosova - I've done some drilling down on this and would like to report in with what I have so far:

1) Ultimately, it looks to me that this is a FlexSlider issue. The initial markup produced by WC for the thumbs (via wc_get_gallery_image_html()) has attributes for height and width (as well as sizes, srcset, and more). However, then FlexSlider strips that down to the bare minimum. Apparently too much so ;)

2) In a semi-related note, in looking for an available solution, I tried - via the filter 'woocommerce_single_product_carousel_options' - to use some of the other FlexSlider properties ([https://github.com/woocommerce/FlexSlider/wiki/FlexSlider-Properties](https://github.com/woocommerce/FlexSlider/wiki/FlexSlider-Properties)) and couldn't get itemWidth, itemMargin, or maxItems to work. (Note: I didn't try all of the advanced properties so there may be others in this bunch). On the other hand, adding 'randomize' true did randomize, as did changing 'animation' to 'fade' did as well. I mention 'randomize' and the change to 'animation' to verify that some filtering of those args did work. So it wasn't me. I don't think :)

3) Finally, spitballing, if itemWidth did work (read: it gets added to the <li> wrapper of each thumb), and an itemHeight was added, if the img width was set 100% would that be sufficent for Google and other metrics? @diggeddy @demian1985, any idea? You can see itemWidth and itemMargin working here in the FS demo: [http://flexslider.woothemes.com/thumbnail-slider.html](http://flexslider.woothemes.com/thumbnail-slider.html)

**Comment by daveloodts** [comment] 2021-04-26 08:34
Hi, is the issue of bad CLS for a productpage still being handled?
As what is noted in this ticket: the gallery has no height/width and Google punished this with bad CLS. Not a nice site in Search Console when you have +1000 productpages and a few "normal" pages. :-)

I've tested 4/5 sites via Lighthouse in the Chrome browser.
Same issue for every product page on every site.

So, is there more news around a specific solution in core?

**Comment by robin-scott** [comment] 2021-04-28 08:50
Just chiming in here as @daveloodts flagged this on Slack.

Re @mfs-mindsize point 3 - img width alone would not be sufficient for CLS (and other) CWV warnings, because the layout shift they are complaining about is vertical - the image loading would "push" the rest of the content lower (particularly on mobile).

Any element which contains a vertical element which after the first paint should have it's height (and width) set, to avoid layout shifts. The width in this case is not so important - because this does not shift the layout.

@daveloodts - as a workaround, you can set the height of the containing element, particularly useful if you know what this will always be (i.e. if your product pics / thumbs have a fixed height). You can do this using CSS. This does stop PageSpeed Insights from squeaking at you.

**Comment by robin-scott** [comment] 2021-04-28 08:52
CLS is basically saying "does the height of this whole page change after FCP?" - and, assuming you load elements lazy or after FCP without height set, this is exactly what happens. The problem? Well, let's say you click an anchor link below one of these elements. You go to press a button, then an image up the page loads, pushing the button down. Uh oh. You missed. Try again! This is poor UX, and now a ranking factor in Google search.

**Comment by tammullen** [comment] 2021-04-28 08:58
Thanks all for the additional information. It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 
​
Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by daveloodts** [comment] 2021-04-28 09:43
Thanks Robin for your fantastic feedback.
In Search Console we only got "orange" improvement notifications for the desktop-version; the mobile-version is mostly okay for the CLS.
As what you've said, the height-parameter is important here.

**Comment by vdwijngaert** [comment] 2021-04-28 11:12
Looks like the required changes for this to work are needed [here](https://github.com/woocommerce/FlexSlider/blob/690832b7f972298e76e2965714657a2beec9e35c/jquery.flexslider.js#L246).

**Comment by cometto277** [comment] 2021-05-03 10:56
I have the same problem... tried to find solution for weeks and I surrended. Is there any chance that it may be fixed? Bad CLS is dropping google rating because its almost 0,15... Changing image size has no sense if you have horizontal + vertical images.

I think many peope have similar problem but they didnt realize it exists...

**Comment by weroh** [comment] 2021-05-21 05:50
I'm way too lazy to create a PR for this, but here is a replacement for jquery.flexslider.js... which you can minify on your own to create jquery.flexslider.min.js. Anyway, two lines of code seems to fix this problem for me. The solution is to pull the img height/width from the original markup and bring it into the generated img tag. Easy cheese.

Should work as a drop in replacement
https://gist.github.com/weroh/160839d5324e30de9bfc95a808eb880e

* There is still an svg icon appearing without height/width info. Does anyone know where this is coming from? <img draggable="false" role="img" class="emoji" alt="🔍" src="https://s.w.org/images/core/emoji/13.0.1/svg/1f50d.svg">

**Comment by timholz** [comment] 2021-05-22 23:25
Simply enqueue your own single-product.js:

`add_action( 'wp_enqueue_scripts', 'my_single_product_script' );
    function my_single_product_script() {
        if (is_product()){
        global $wp_scripts; 
        $wp_scripts->registered[ 'wc-single-product' ]->src = get_stylesheet_directory_uri() . '/js/my_woo_scripts/my-single-product.js';
    }`

and in my-single-product.js you add:

`$(document.body).on('wc-product-gallery-after-init', function() {
    //add image dimensions if flex control nav is present
    if ($('.flex-control-nav').length){
      console.log('present');
    $('.flex-control-nav li img').each(function() {
      $(this).attr('width',65).attr('height',65); //add your specific dimensions
    });
   }
  });`

This adds the required width and height attribute.
theo

**Comment by cometto277** [comment] 2021-05-23 10:01
hey @timholz 

I would like to test your improvement but im not a professional and im afraid I can break my website. Could you describe with more details steps you wrote?
enque single-product.js
adding in my-single-product.js

I see single-product.js in folder woocommerce but should I remove it ot or delete part of it and put code you wrote? I will be grateful for step by step instruction. 

Thanks in advance mate!
Adrian

**Comment by timholz** [comment] 2021-05-23 12:09
Hi Adrian
Ok, i’ll try.
The goal is to inject the missing attributes with jquery. That is, when the page has loaded.
This is done principally like so: 

`$(selector).attr('width',value).attr('height',value);`

You can place the injection script in the standard js file of your child-theme.
(I hope you do have a child theme, otherwise i recommend to learn about this important feature.)

Open your standard.js (or whatever it is called) and add:

if ($('.flex-control-nav').length){ //comment: first check if the flex-control-nav element is present
   console.log('present'); //comment: if so, you can check it’s presence in the console. Delete this line afterwards
   $('.flex-control-nav li img').each(function() { //comment: the each function loops through all specified elements: .flex-control-nav li img
   $(this).attr('width',65).attr('height',65); //comment: add the width and heigth attribute. In my case the value is 65. You will have to inspect what dimension your theme serves
 }); 
}

Load the script. Probably you will have to empty the cache. Mind if caching plugins are working.
Check the console. If it says 'present'. Then the script has recognized the element in question.
Then inspect the .flex-control-nav li img and find the attributes width and height.
If it all works, the delete the console.log line and eventually minify the script.

Try this first. The method described above is a little more complicated. If you want to learn more, i can explain that too.
But for now, take the easy way.
Good luck
theo

**Comment by cometto277** [comment] 2021-05-23 12:34
hey @timholz 

You can place the injection script in the standard js file of your child-theme.
(I hope you do have a child theme, otherwise i recommend to learn about this important feature.)

- yes, I have a child theme. where should I search this js.? (woocommerce/assets/js/frontend/single-product.js)?

I have also plugin PHP inserter. Can I use it or just edit woocommerce/template files manually?

**Comment by timholz** [comment] 2021-05-23 13:36
For now, leave all woocommerce files alone.
In the directory of your child-theme look for functions.php.
Look for all the js files that are enqueued. Look in the js folder of your child theme.
Eventually you will find a js file that holds basic functions.
Send me a link to your website.

**Comment by diggeddy** [comment] 2021-05-23 15:19
@timholz this method may eliminate the missing width/height attributes warning in Lighthouse as i believe this is audited post render - but i am not sure it will resolve the CLS problem.
To eliminate the layout shift the browser needs to be able to reserve space for those images. To do that effectively the attributes need to be present in the HTML Tree before it is passed to the browser Layout Engine. Or as near as damn it to the instance of first contentful paint. 
Have you check for Layout Shift on the single product with and without this script? 

Alternative fix:
In most instances the missing width/height attributes can be ignored if they are not generating Layout Shift. In the event they do cause Layout Shift, and there is no direct way to add the attributes ( as in this instance ) the simplest fix is to use CSS to set a minimum height on the parent container like so:

```
.flex-control-nav {
    min-height: 100px;
}
/* adjust height if necessary for mobile */
@media(max-width: 768px) {
    .flex-control-nav {
        min-height: 100px;
    }
}
```

But ultimately the fix @weroh provided [here](https://github.com/woocommerce/woocommerce/issues/25461#issuecomment-845673185) is the solutions and something that should merged into the plugin

**Comment by timholz** [comment] 2021-05-23 15:27
@diggeddy You are right. The layout shift remains. I my case, it is very small. Thanks for your input

**Comment by weroh** [comment] 2021-05-23 19:46
Thanks @diggeddy ! Yeah unfortunately there are no events, hooks or filters to bind to. So we're stuck just rewriting an existing script. I've replaced ours and will continue to do so manually until WooCommerce merges this change or revises the script in another way.

**Comment by cometto277** [comment] 2021-05-23 20:27
@timholz @weroh @diggeddy 
gentlemen, thank you for contributing to the solution of the problem. css given by diggeddy seems to solve the problem. This is not a good place to ask a question, but I see that I deal with specialists - maybe you can tell me how to solve another problem (I did not find the answer on forums, facebook groups, I wrote to the creator of the template, on stackoverflow) and nothing ... 

I have a problem with the size of the photos on the product page for mobile devices. Despite the small target size, mobile phones are loaded with large sizes such as 1024w etc. The problem concerns the flex-viewport element. I have tried all possible solutions and spent tens of hours trying to fix the problem. Link to my product page that can be researched by GPSI (https://bit.ly/3wpbYa7). If you are able to help me or direct me to a solution, I will delete this post so as not to clutter the thread. Thanks in advance.
Adrian

**Comment by timholz** [comment] 2021-05-23 20:36
Check out wordpress plugin «adaptive images».

**Comment by cometto277** [comment] 2021-05-23 20:42
@timholz  you mean this one? https://wordpress.org/plugins/adaptive-images/

I tried (not sure if this or similar one) and it didnt help.

**Comment by timholz** [comment] 2021-05-23 20:43
yes, i use it since years.

**Comment by cometto277** [comment] 2021-05-23 20:45
@timholz is there a risk to break some images or images quality? during tests of different optimizing plugins broke my website once and had to restore all data...

**Comment by timholz** [comment] 2021-05-23 20:48
Sorry to hear that. I never had any problems with adaptive images. But anyway, always backup your working site.

**Comment by diggeddy** [comment] 2021-05-23 21:17
@cometto277 yeah - this isn't the right place for support -  i would suggest speaking with your Theme author. Some pointers: The problem arises because of the src-set `sizes` your theme is outputting - if you inspect one of your images you will see:

`sizes="(max-width: 705px) 100vw, 705px"`

More info on this [see here](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/) 
Your theme is using WP's default sizes - it was setup this way with the good intentions of always ensuring an image would fill the space available to it... but it makes the assumption that on smaller screens the image will fill the width of the viewport - which it does not because of the container padding - and because of this the browser is left to its own devices and generally grabs a larger then required image.

However, the `sizes` attribute does have a filter hook: `wp_calculate_image_sizes` [see here](https://developer.wordpress.org/reference/hooks/wp_calculate_image_sizes/)

Heres a quick a dirty PHP Snippet example of that - note that this may not be applicable with your theme:

```
function db_modify_srcset_sizes($sizes, $size) {
	return '(max-width: 420px) 300px, (min-width: 421px) 768px, (min-width: 769px) 1024px, 100vw';
}
add_filter('wp_calculate_image_sizes', 'db_modify_srcset_sizes', 10 , 2);
```
Have a chat with your theme developer about applying this.

**Comment by cometto277** [comment] 2021-05-24 10:43
@diggeddy  Hey,

thank you for code. It seems that problem has been solved - no more warning from GPSI. 
Thank you very much mate and big beer for you!
Adrian

**Comment by jesscga** [comment] 2021-07-26 19:11
Additional report in 4171922-zen - customer noticed poor CLS score on single product pages on mobile and mentioned that "when you remove the [gallery] thumbnails (using a product with only one image), the CLS issue simply vanishes"

**Comment by Anikora** [comment] 2021-08-09 11:10
> 
> 
> I tested with lighthouse and it clearly reports, that width and height attributes are lacking.
> With a little work, this lack can be removed.
> Simply enqueue your own single-product.js:
> 
> `add_action( 'wp_enqueue_scripts', 'my_single_product_script' ); function my_single_product_script() { if (is_product()){ global $wp_scripts; $wp_scripts->registered[ 'wc-single-product' ]->src = get_stylesheet_directory_uri() . '/js/my_woo_scripts/my-single-product.js'; }`
> 
> and in my-single-product.js you add:
> 
> `$(document.body).on('wc-product-gallery-after-init', function() { //add image dimensions if flex control nav is present if ($('.flex-control-nav').length){ console.log('present'); $('.flex-control-nav li img').each(function() { $(this).attr('width',65).attr('height',65); //add your specific dimensions }); } });`
> 
> This adds the required width and heigth attribute.
> theo

@timholz 
I tried to fix it with the above code, but I always get the console error:
"Uncaught TypeError: $ is not a function"

This is the content of my custom js file (I created a blank .js file with this content, uploaded it in my childtheme's js folder and enqueued it:
`$(document.body).on('wc-product-gallery-after-init',function(){
	if ($('.flex-control-nav').length){ 
		console.log('present'); 
		$('.flex-control-nav li img').each(function() { 
			$(this).attr('width',65).attr('height',65);  
		}); 
	} 
});`
Is there anything I have to place before that code? I have no clue of jquery, so any help would be really appreciated.

**Comment by juliaamosova** [comment] 2021-08-09 13:32
I am changing the priority from `low` to `high` here given the number of comments we have on the issue. cc @vedanshujain

**Comment by timholz** [comment] 2021-08-11 10:48
Hi Anikora
If you get this uncaught typeError: $ is not a function, then jQuery is not available.
For the script to work, the jQuery library must be loaded first.
How do you load the jQuery library?
I hope that helps to solve the error.
theo

**Comment by Mte90** [comment] 2021-09-06 17:33
I did a pr with the code of the modified version of @weroh from https://github.com/woocommerce/woocommerce/issues/25461#issuecomment-845673185 


With the hope that is reviewed and merged but the library last commit is from 2019.

https://github.com/woocommerce/FlexSlider/pull/1799

**Comment by vedanshujain** [comment] 2021-09-07 10:49
@Mte90 For better or worse, we forked flexslider before inclusion, so we can make this change in WC directly as well, would you be interested in sending another PR targeting core? See the file here: https://github.com/woocommerce/woocommerce/blob/trunk/assets/js/flexslider/jquery.flexslider.js

**Comment by Mte90** [comment] 2021-09-07 11:06
Done https://github.com/woocommerce/woocommerce/pull/30648

I don't understand why keep a repository opened to the world if the project is not developed there anymore. Maybe archive the repository to avoid the confusions?

**Comment by weroh** [comment] 2021-09-08 07:45
> 
> 
> I did a pr with the code of the modified version of @weroh from [#25461 (comment)](https://github.com/woocommerce/woocommerce/issues/25461#issuecomment-845673185)
> 
> With the hope that is reviewed and merged but the library last commit is from 2019.
> 
> [woocommerce/FlexSlider#1799](https://github.com/woocommerce/FlexSlider/pull/1799)

This is the way

**Comment by Mte90** [comment] 2021-09-08 10:51
I had to change your code @weroh as it takes all the sliders height and width and not the real width of the image.
My version do some calculations and set a better width/height and not just a filler to silence lighthouse.

**Comment by cometto277** [comment] 2021-09-08 13:46
Hello,

@Mte90 

Im using function:
`function db_modify_srcset_sizes($sizes, $size) {
	return '(max-width: 420px) 300px, (min-width: 421px) 768px, (min-width: 769px) 1024px, 100vw';
}
add_filter('wp_calculate_image_sizes', 'db_modify_srcset_sizes', 10 , 2);`

Is it better to apply code from last posts in this conversation? When I disable code from above PSI immediately tells about wrong image size.

**Comment by Mte90** [comment] 2021-09-08 14:23
I don't think that this affect this part. As gallery thumbnails HTML is generated by JS and not PHP.

**Comment by cometto277** [comment] 2021-09-08 14:25
@Mte90 should I leave it as it is or try improvements? im no professional

**Comment by Mte90** [comment] 2021-09-08 14:35
Depends, lighthouse reports troubles that with this line are fixed? I have no idea

**Comment by weroh** [comment] 2021-09-08 18:06
> 
> 
> I had to change your code @weroh as it takes all the sliders height and width and not the real width of the image.
> My version do some calculations and set a better width/height and not just a filler to silence lighthouse.

Thanks for that. I didn't realize it was using the wrong dimensions. My intention wasn't to silence LH, but to actually fix it. So this is good stuff. I'll review these changes and most likely drop them into my websites that use this feature. :)

**Comment by erikyo** [comment] 2021-09-11 10:23
Sorry to join the discussion only now, but I want to share the fix because I guess i've already solved this issue in the past... Anyhow, this is only a part of the speed optimizations needed in 2021, another important change would be to fix the attribute that prevents lazyloading.

Basically, we wait the image load, to then add width and height
```
// jquery.flexslider.js#L244
item = $( '<a></a>' ).attr( 'href', '#' ).text( j );
if ( slider.vars.controlNav === "thumbnails" ) {
  item = $('<img/>', {
	  load: function (el) {
		  el.currentTarget.width = el.currentTarget.naturalWidth;
		  el.currentTarget.height = el.currentTarget.naturalHeight;
	  },
	  src: slide.attr('data-thumb'),
	  alt: slide.attr('alt')
  })
}
```

https://github.com/erikyo/woocommerce/blob/dbc22d6f8968cf64909e89943764720eb7eed647/assets/js/flexslider/jquery.flexslider.js#L244

**Comment by ashleythewebdeveloper** [comment] 2021-12-03 18:21
> @timholz this method may eliminate the missing width/height attributes warning in Lighthouse as i believe this is audited post render - but i am not sure it will resolve the CLS problem. To eliminate the layout shift the browser needs to be able to reserve space for those images. To do that effectively the attributes need to be present in the HTML Tree before it is passed to the browser Layout Engine. Or as near as damn it to the instance of first contentful paint. Have you check for Layout Shift on the single product with and without this script?
> 
> Alternative fix: In most instances the missing width/height attributes can be ignored if they are not generating Layout Shift. In the event they do cause Layout Shift, and there is no direct way to add the attributes ( as in this instance ) the simplest fix is to use CSS to set a minimum height on the parent container like so:
> 
> ```
> .flex-control-nav {
>     min-height: 100px;
> }
> /* adjust height if necessary for mobile */
> @media(max-width: 768px) {
>     .flex-control-nav {
>         min-height: 100px;
>     }
> }
> ```
> 
> But ultimately the fix @weroh provided [here](https://github.com/woocommerce/woocommerce/issues/25461#issuecomment-845673185) is the solutions and something that should merged into the plugin

Can confirm this works.

**Closed** 2021-12-09 20:22 UTC
Labels: type: bug, category: performance, priority: high
