### ISSUE TITLE
I am not able to get to the helpdesk from the the backend of WP

### ISSUE THREAD

**Issue by jessicabob** [woocommerce/woocommerce#23576] opened 2019-05-01 17:46 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by jessicabob** [comment] 2019-05-01 17:49
I also am not a github master. To reproduce the issue click on "help" and click on Woocommerce helpdesk and you will get a white screen on the firefox browser.
I am going to see if it is the same in the other browsers.

**Comment by rodrigoprimo** [comment] 2019-05-01 21:34
Thanks for your report, @jessicabob. I was able to reproduce this issue.

If I click on "Help" in the top right corner of any WooCommerce admin page and then click on "WooCommerce Helpdesk" (link: https://woocommerce.com/my-account/tickets/?utm_source=helptab&utm_medium=product&utm_content=tickets&utm_campaign=woocommerceplugin), I'm redirected to a blank page in the following URL: https://woocommerce.com/wc-api/wpcom-signin?next=my-dashboard&code=SOME_CODE&state=SOME_STRING. I noticed that, in my case, I only get the blank page if I don't have an active session on WooCommerce.com. If before clicking on the link, I log in on WooCommerce.com, the page https://woocommerce.com/my-account/tickets loads fine. We will investigate and work on a fix. Meanwhile, if you need to contact WooCommerce.com you can do so in this link https://woocommerce.com/contact-us/

@mattyza is this something you or some else from your team can take a look?

**Comment by claudiosanches** [comment] 2019-05-06 13:00
I can login automatically without any problem, however after login I'm redirected for the WooCommerce.com's dashboard instead of https://woocommerce.com/my-account/tickets/

**Comment by rodrigoprimo** [comment] 2019-05-06 13:25
@claudiosanches, @dwainm merged a WC.com PR earlier today that fixed the white screen problem.

When I don't have a WooCommerce.com session, I'm also landing on the dashboard instead of https://woocommerce.com/my-account/tickets/. @dwainm, could you please take a look as this is potentially confusing for the users?

**Comment by dwainm** [comment] 2019-05-06 14:17
I've created an issue on the WooCommerce.com repository. We will action this and update here. Feel free to close at your discretion.

**Comment by dwainm** [comment] 2019-05-06 14:17
https://github.com/Automattic/woocommerce.com/issues/5857

**Comment by rodrigoprimo** [comment] 2019-05-08 18:43
After talking to @claudiosanches, I'm reopening this issue. I will close it again once the WooCommerce.com issue is fixed.

**Comment by kloon** [comment] 2019-05-22 08:15
The WooCommerce.com team is aware of this and have it logged to be fixed. Not sure when they will implement a fix but since this is outside our control I am closing this issue.

**Closed by kloon** 2019-05-22 08:15 UTC
Labels: bug

**Comment by claudiosanches** [comment] 2019-05-22 22:41
@kloon When I talked with @rodrigoprimo he thought it would be best to leave it open until resolved, so this thread will show to users that people are working on it.
