### ISSUE TITLE
Importing Dummy Data Can Exceed Maximum Execution Time

### ISSUE THREAD

**Issue by BFTrick** [woocommerce/woocommerce#12507] opened 2016-12-02 15:40 UTC
## Importing the Dummy Data in WooCommerce Can Create an Error

<img width="1123" alt="importing-woocommerce-bug" src="https://cloud.githubusercontent.com/assets/1065372/20839474/c00273d6-b87a-11e6-86ea-a9da1f4afb30.png">

If you're running the import on slower machine you could get a fatal error. 

You would have to modify the `max_input_time` variable in your `php.ini` file to get past it. Most users won't know how to do this.

Can we reduce the size of the import? I assume it's not the # of products. I assume it's more likely to be the server downloading images. Can we remove a few images or optimize or shrink them?

**Comment by mikejolley** [comment] 2016-12-05 12:03
@jameskoster you brought this up the other day? Let's redo the dummy data.

**Comment by jameskoster** [comment] 2016-12-05 12:36
Yeah there ongoing discussions around our dummy products, no decisions there yet.

I'd like to know more about the environment in which this occurred. Our current dummy data is ~4mb including the images. How old is the computer? I'm genuinely surprised that a modern computer cannot handle a 4mb WordPress import in 60 seconds.

If the issue is the internet connection there's always the option of not importing the images. Not ideal I know, but I'd rather not remove products as that will reduce the effectiveness of the 'demo'.

**Comment by mikejolley** [comment] 2016-12-05 12:48
@jameskoster Semi-related, the default product images are a bit outdated. Can we jazz those up :)?

**Comment by jameskoster** [comment] 2016-12-05 14:30
> Yeah there ongoing discussions around our dummy products, no decisions there yet.

:p

Or do you mean the placeholders?

**Comment by mikejolley** [comment] 2016-12-05 16:03
@jameskoster yes that placeholder image. Must be something better we can do there :) At least dump the image?

**Comment by BFTrick** [comment] 2016-12-05 21:13
This was caught by QA going through one my courses.

> So I'm not sure what type of computer was used (although I'm fairly certain it wasn't a virtual setup) but apparently this is a common problem - particularly with Wordpress. 

> I actually remember having this same issue with Carrie which we gave the same instructions for. Other producers have had the same issue as well so it's definitely not unique.

I haven't seen an actual user with this problem but however this QA team setup their computer it seemed to take a quite a while.

I did a google search and found similar errors but never one mentioning WooCommerce specifically.

IMO if this isn't a simple fix it's probably not worth investigating until we get more reports.

**Comment by jameskoster** [comment] 2016-12-06 11:30
@mikejolley yeah we can replace the image, but can't people filter the src? So we'd need to factor that in.

@BFTrick yeah it's a tricky one because this is more of a local issue than a WooCommerce issue I think. Making our dummy data any smaller is going to make it pretty worthless imo, and there is the option to not import images which should help a bit.

I'll close this out for now, but keep it in mind for the new dummy data discussions.

**Closed by jameskoster** 2016-12-06 11:30 UTC
Labels: Enhancement, Performance
