### ISSUE TITLE
Allow ability to remove tax if customer is tax exempt in particular state.

### ISSUE THREAD

**Issue by ThomasSultana** [woocommerce/woocommerce#28990] opened 2021-02-01 15:05 UTC
**Is your feature request related to a problem? Please describe.**
I have a customer at the moment who requires that tax rates are set up for each US state. However if the customer has meta_data stored in their profile which allows them to be tax exempt for that state, then the tax rates should not be visible/calculated and charged to the customer.  This logic needs to occur on the checkout stage. e.g. a customer may be tax exempt in NY, however if they were to ship to CA then they will be charged Tax as they are not Tax Exempt in that state.

At first my goal was to take advantage of the `woocommerce_calculate_item_totals_taxes` filter so that i can parse the cart data to check if the customer is vat exempt for that shipping state and then return an empty `$taxes` array, however the 3rd argument in that filter class `WC_Cart_Totals` has a protected `$cart` property that i am unable to access in that filter. 

**Describe the solution you'd like**
Ideally i should be able to access the `$cart` property so i can parse the shipping address and therefore make the decision if i should remove taxes for that customer. I know that `WC_Order` has a filter `woocommerce_order_is_vat_exempt` which should allow me to remove Tax, however i believe this is too late in the process? (just a hunch here). I feel like the customer would already be charged and shown the tax amount before this WC_Order filter actually runs?

This logic should also be available for calculating shipping and fee rates.

Thank you

**Comment by jonathansadowski** [comment] 2021-09-28 19:44
Hi  @ThomasSultana,

Thanks for the report. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions.

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel.

In this case specifically, you may be able to hook into the loading of the customer object and use `set_is_vat_exempt` to specify that the customer is exempt.

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by jonathansadowski** 2021-09-28 19:44 UTC
Labels: needs developer feedback
