### ISSUE TITLE
''Generate Aliexpress key'' button not working

### ISSUE THREAD

**Issue by bizlond** [woocommerce/woocommerce#27355] opened 2020-08-17 15:52 UTC
**Expected result:**

Clicking on 'Generate Aliexpress Key'' button should open a box with information that the key has been sent to my e-mail.

**Actual result:**
Clicking on 'Generate Aliexpress Key'' is not working and did not open any box.

**Comment by tammullen** [comment] 2020-08-17 18:24
Hi @bizlond 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by a 3rd party plugin. 
​
Please contact the author of the plugin directly for further help. 

I am closing this issue for now as it seems to be a 3rd party support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-08-17 18:24 UTC

**Comment by bizlond** [comment] 2020-08-17 18:29
Thanks Tammullen. I bought the 'Woocommerce dropshipping' extension from Woocommerce. I installed and activated it but when it got to generating key for dropshipping, the button did not work.
