### ISSUE TITLE
Paging Through Shop Pages returns the Wrong # of Products still not fixed.

### ISSUE THREAD

**Issue by martinsmagic** [woocommerce/woocommerce#13770] opened 2017-03-24 21:13 UTC
## EXPLANATION OF THE ISSUE

Hi MIke,

I have reported this issue twice so far: #13398 and #13616 but it has not been fixed yet as far as I can tell.  I have rebuilt the site from scratch here http://www.qualitymagicsales.com/ each time and re-ran the updater.

## STEPS TO REPRODUCE THE ISSUE

Check the box that says: Hide out of stock items from the catalog under Settings/Products/Inventory
Run the updater on any site with out of stock products using Woocommerce 2.6.14.

Instead of seeing: Showing 1–10 of 13 products it shows 1-10 of 136
https://beta.qualitymagicsales.com/

So it doesn't show the outofstock products but it doesn't take it into account when it calculates how many products there are to show.

Let me know if you need more information.

Thanks,

andy

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://beta.qualitymagicsales.com
Site URL: https://beta.qualitymagicsales.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.21 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 180
PHP Max Input Vars: 1620
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

BM Custom Login: by BinaryMoon – 2.1
EZP Maintenance Mode: by Snap Creek Software – 1.0.1
OpenID: by DiSo Development Team – 3.4.2
WooCommerce: by Automattic – 3.0.0-rc.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #826 - /
Cart: #827 - /cart/
Checkout: #828 - /checkout/
My account: #830 - /my-account/

### Theme ###

Name: Twenty Twelve
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment] 2017-03-24 22:35
Did you run the SQL query i gave you last time?

**Comment by martinsmagic** [comment] 2017-03-24 22:38
Mike,

I rebuilt the system from scratch and just ran the updater.  I wasn't aware that I had to do anything different.  Surely the updater should take care of any changes?

Thanks,

andy

Andy Martin, Ph.D. www.martinsmagic.com [http://www.martinsmagic.com]
Magician & Collector www.qualitymagicsales.com [http://www.qualitymagicsales.com]
andy@martinsmagic.com www.qualitymagicsites.com [http://www.qualitymagicsites.com]
On 3/24/2017 5:37:04 PM, Mike Jolley <notifications@github.com> wrote:
Did you run the SQL query i gave you last time?

**Comment by mikejolley** [comment] 2017-03-24 23:46
Yes, if you have the latest code/fix. It should be in the rc2. If not i need a full XML product export to see if that term exists or not.

**Comment by martinsmagic** [comment] 2017-03-25 00:10
Hi Mike,

Here you go here is one of the outofstock products - let me know if you need more.

{{
   "_links" : {
      "collection" : [
         {
            "href" : "https://beta.qualitymagicsales.com/wp-json/wc/v1/products"
         }
      ],
      "self" : [
         {
            "href" : "https://beta.qualitymagicsales.com/wp-json/wc/v1/products/31314"
         }
      ]
   },
   "attributes" : [],
   "average_rating" : "0.00",
   "backordered" : false,
   "backorders" : "no",
   "backorders_allowed" : false,
   "button_text" : "",
   "catalog_visibility" : "visible",
   "categories" : [
      {
         "id" : 2329,
         "name" : "Close-up",
         "slug" : "close-up"
      },
      {
         "id" : 2383,
         "name" : "Money",
         "slug" : "money"
      }
   ],
   "cross_sell_ids" : [],
   "date_created" : "2017-03-19T14:55:13",
   "date_modified" : "2017-03-19T14:55:19",
   "date_on_sale_from" : "",
   "date_on_sale_to" : "",
   "default_attributes" : [],
   "description" : "<p>If you are a fan of the <a href=\"http://www.martinsmagic.com/allmagic/close-up/coin-of-the-realm-by-dave-powell/\">Coin of the Realm</a> or <a href=\"http://www.martinsmagic.com/allmagic/close-up/streamline-art-deco-steel-ball-through-glass-by-dave-powell/\">Cabala</a> style effects you will love what <a href=\"http://www.martinsmagic.com/product-tag/brian-cook/\">Brian Cook</a> has created here.  He has taken the effect to the next level by creating this beautiful box out of high quality clear acrylic so the audience can see everything that is happening as the coin penetrates the solid piece of glass right in front of their eyes!  This is a rare beauty for sure.</p>\n",
   "dimensions" : {
      "height" : "",
      "length" : "",
      "width" : ""
   },
   "download_expiry" : -1,
   "download_limit" : -1,
   "download_type" : "standard",
   "downloadable" : false,
   "downloads" : [],
   "external_url" : "",
   "featured" : false,
   "grouped_products" : [],
   "id" : 31314,
   "images" : [
      {
         "alt" : "",
         "date_created" : "2017-03-19T14:55:14",
         "date_modified" : "2017-03-19T14:55:14",
         "id" : 31315,
         "name" : "brian-cook-coinatration",
         "position" : 0,
         "src" : "https://beta.qualitymagicsales.com/wp-content/uploads/2017/03/brian-cook-coinatration.jpg"
      },
      {
         "alt" : "",
         "date_created" : "2017-03-19T14:55:15",
         "date_modified" : "2017-03-19T14:55:16",
         "id" : 31316,
         "name" : "brian-cook-coinatration_02",
         "position" : 1,
         "src" : "https://beta.qualitymagicsales.com/wp-content/uploads/2017/03/brian-cook-coinatration_02.jpg"
      },
      {
         "alt" : "",
         "date_created" : "2017-03-19T14:55:16",
         "date_modified" : "2017-03-19T14:55:16",
         "id" : 31317,
         "name" : "brian-cook-coinatration_03",
         "position" : 2,
         "src" : "https://beta.qualitymagicsales.com/wp-content/uploads/2017/03/brian-cook-coinatration_03.jpg"
      },
      {
         "alt" : "",
         "date_created" : "2017-03-19T14:55:16",
         "date_modified" : "2017-03-19T14:55:17",
         "id" : 31318,
         "name" : "brian-cook-coinatration_04",
         "position" : 3,
         "src" : "https://beta.qualitymagicsales.com/wp-content/uploads/2017/03/brian-cook-coinatration_04.jpg"
      },
      {
         "alt" : "",
         "date_created" : "2017-03-19T14:55:17",
         "date_modified" : "2017-03-19T14:55:19",
         "id" : 31319,
         "name" : "brian-cook-coinatration_05",
         "position" : 4,
         "src" : "https://beta.qualitymagicsales.com/wp-content/uploads/2017/03/brian-cook-coinatration_05.jpg"
      },
      {
         "alt" : "",
         "date_created" : "2017-03-19T14:55:19",
         "date_modified" : "2017-03-19T14:55:19",
         "id" : 31320,
         "name" : "brian-cook-coinatration_06",
         "position" : 5,
         "src" : "https://beta.qualitymagicsales.com/wp-content/uploads/2017/03/brian-cook-coinatration_06.jpg"
      }
   ],
   "in_stock" : false,
   "manage_stock" : true,
   "menu_order" : 0,
   "name" : "Clear Coinatration by Brian Cook",
   "on_sale" : false,
   "parent_id" : 0,
   "permalink" : "https://beta.qualitymagicsales.com/shop/clear-coinatration-by-brian-cook/",
   "price" : "325.00",
   "price_html" : "<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>325.00</span>",
   "purchasable" : true,
   "purchase_note" : "",
   "rating_count" : 0,
   "regular_price" : "325.00",
   "related_ids" : [
      30589,
      29928,
      30077,
      29932,
      28593
   ],
   "reviews_allowed" : true,
   "sale_price" : "",
   "shipping_class" : "",
   "shipping_class_id" : 0,
   "shipping_required" : true,
   "shipping_taxable" : true,
   "short_description" : "",
   "sku" : "5947",
   "slug" : "clear-coinatration-by-brian-cook",
   "sold_individually" : false,
   "status" : "publish",
   "stock_quantity" : 0,
   "tags" : [
      {
         "id" : 3332,
         "name" : "Brian Cook",
         "slug" : "brian-cook"
      },
      {
         "id" : 3331,
         "name" : "March 2017",
         "slug" : "march-2017"
      },
      {
         "id" : 2907,
         "name" : "scarce",
         "slug" : "scarce"
      },
      {
         "id" : 3266,
         "name" : "simon-aronson",
         "slug" : "simon-aronson"
      }
   ],
   "tax_class" : "",
   "tax_status" : "taxable",
   "total_sales" : 1,
   "type" : "simple",
   "upsell_ids" : [
      31163,
      31272,
      31292
   ],
   "variations" : [],
   "virtual" : false,
   "weight" : ""
}

Thanks,

andy

**Comment by thomas-zg** [comment] 2017-03-25 21:45
Mike,

Another issue, but maybe the same reason: the shop page display is setup to categories, the number of products is correct. As soon as I switch the Hide out of stock items from the catalog setting to true, the number of products shown in the category label is incorrect. The hidden products will also included in the calculation.

best regards,
Thomas

**Comment by mikejolley** [comment] 2017-03-27 10:45
I'm pretty sure this is due to the way these RC versions are being installed i.e. you update without 'activation' so the terms do not exist for the updater.

I can do term insertion as part of the updater to workaround.

**Comment by martinsmagic** [comment] 2017-03-27 12:56
Hi Mike,

I tried it this way:

- made a copy of the working site

- deactivated all of the plugins, including woocommerce

- updated the woocommerce plugin with 3.0.0-rc.2

- activated woocommerce

- Ran the updater

Still saw the same issue.  If there is a different approach I should take let me know.

Thanks,

andy

Thanks,

andy

**Comment by mikejolley** [comment] 2017-03-27 13:02
I did the above change and had it update fine - prior to running the updater I had the same issue.

**Comment by martinsmagic** [comment] 2017-03-27 13:13
Mike,

Just to be clear - it is nothing to do with how I'm installing the RC version after all, and your latest fix is required?

Thanks again for your work on this.

andy

**Comment by mikejolley** [comment] 2017-03-27 13:18
Install master and try for yourself @martinsmagic - I couldn't replicate it with a clean 2.6 -> 3.0 install.

**Comment by mikejolley** [comment] 2017-03-27 13:19
Sorry, not master it's not merged yet. But with the contents of that PR.

**Comment by martinsmagic** [comment] 2017-03-27 14:00
Hi Mike,

So I:

Rebuilt the site from the working site (http://www.qualitymagicsales.com/)
Did the usual things (removed extra plugins, changed theme to 2012 etc.)
Confirmed everything was still working correctly with WC 2.6.14.
Deactivated woocommerce plugin.  
Updated the plugin code with 3.0.0-rc.2 and your latest fix (6f3d0c1).  
Activated the plugin.
Applied the updater.

And I'm still seeing the same issue (https://beta.qualitymagicsales.com/)

Let me know if there is anything else I can try.

Thanks again,

andy

**Comment by mikejolley** [comment] 2017-03-27 14:03
Why not look at the error logs and see if there are any sql errors reported? The updater just runs a query.

**Comment by mikejolley** [comment] 2017-03-27 14:03
@martinsmagic  https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1055-L1057

**Comment by martinsmagic** [comment] 2017-03-27 14:06
Mike,

here are some errors:

[Mon Mar 27 08:52:39.404317 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'attribute_name' for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD KEY `attribute_name` (`attribute_name`(20)) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:39.413217 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'download_order_key_product' for query ALTER TABLE wp_woocommerce_downloadable_product_permissions ADD KEY `download_order_key_product` (`product_id`,`order_id`,`order_key`(16),`download_id`) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:39.552554 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'meta_key' for query ALTER TABLE wp_woocommerce_order_itemmeta ADD KEY `meta_key` (`meta_key`(32)) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:39.561897 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'tax_rate_state' for query ALTER TABLE wp_woocommerce_tax_rates ADD KEY `tax_rate_state` (`tax_rate_state`(2)) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:39.562115 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'tax_rate_class' for query ALTER TABLE wp_woocommerce_tax_rates ADD KEY `tax_rate_class` (`tax_rate_class`(10)) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:39.567937 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'location_type_code' for query ALTER TABLE wp_woocommerce_tax_rate_locations ADD KEY `location_type_code` (`location_type`(10),`location_code`(20)) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:39.578772 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'location_type_code' for query ALTER TABLE wp_woocommerce_shipping_zone_locations ADD KEY `location_type_code` (`location_type`(10),`location_code`(20)) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:39.595682 2017] [:error] [pid 33012] [client 254.162.139.212:9633] WordPress database error Duplicate key name 'meta_key' for query ALTER TABLE wp_woocommerce_payment_tokenmeta ADD KEY `meta_key` (`meta_key`(32)) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://beta.qualitymagicsales.com/wp-admin/plugins.php
[Mon Mar 27 08:52:46.483303 2017] [:error] [pid 20300] [client 64.91.229.135:32026] WordPress database error Duplicate entry '30828-3343' for key 'PRIMARY' for query INSERT INTO wp_term_relationships SELECT post_id, 3343, 0 FROM wp_postmeta WHERE meta_key = '_stock_status' AND meta_value = 'outofstock'; made by do_action('wp_ajax_wp_wc_updater'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WP_Background_Process->maybe_handle, WP_Background_Process->handle, WC_Background_Updater->task, call_user_func, wc_update_300_product_visibility, referer: https://beta.qualitymagicsales.com/wp-admin/admin-ajax.php?action=wp_wc_updater&nonce=03e9a67fc1

andy

**Comment by mikejolley** [comment] 2017-03-27 14:13
> WordPress database error Duplicate entry '30828-3343' for key 'PRIMARY' for query INSERT INTO wp_term_relationships SELECT post_id, 3343, 0 FROM wp_postmeta WHERE meta_key = '_stock_status' AND meta_value = 'outofstock'

**Comment by martinsmagic** [comment] 2017-03-27 14:24
Mike,

so it looks like the terms are there.  Anything else you want me to try?

Thanks,

andy

**Comment by mikejolley** [comment] 2017-03-27 14:26
It's either missing relationships, or you still have code in place querying your catalog. Are you 100% sure that database was clean when you did the migration? Because if it was clean, you'd see the same error ^ for all of the update queries, and not just this one.

**Comment by martinsmagic** [comment] 2017-03-27 14:39
Mike,

if you mean by "clean", that it was showing the correct results before the migration, yes it was.  I have repeated it a few times this morning to be sure.  The only code that I know of is the woocommerce plugin - I've removed everything extra that I could find.

andy

**Comment by mikejolley** [comment] 2017-03-27 16:17
@martinsmagic No by clean I mean no data from 3.0.0 in your database when you begin.

Check your export - Tools > Export > WordPress and export products. See if the missing products have a term called outofstock in the product_visibility taxonomy.

**Comment by mikejolley** [comment] 2017-03-27 16:33
Tested again; this issue is not happening with my own clean install after upgrade. The queries are correctly excluding any products with 'outofstock' term.

**Closed** 2017-03-27 17:18 UTC
Labels: Status: has-pr

**Comment by mikejolley** [comment] 2017-03-27 17:19
We've confirmed the fixes and cannot replicate a problem on other sites @martinsmagic. If you can look into the above and check your data/code alongside that would be good. You can mail me if you cannot work it out over the next day or so and I'll look privately since you cannot give access or anything here. mike.jolley at automattic.com

**Comment by martinsmagic** [comment] 2017-03-27 17:23
Thanks Mike,

I will start fresh with a different store and hopefully there is just something strange about http://www.qualitymagicsales.com/ that I'm copying from.  I was unable to find any reference anywhere to outofstock in the product_visibility taxonomy, but if you are not seeing the error it is reasonable to think something else is wrong with the data which is currently not obvious.

Thanks again for your time on this I'll let you know what I find via email.

andy

**Comment by mikejolley** [comment] 2017-03-27 17:56
What about in the wp_terms table? Not there?

**Comment by martinsmagic** [comment] 2017-03-27 18:17
Hi Mike,

I was unable to find any reference to outofstock in wp_terms.  

Although I have not figured out the issue with http://www.qualitymagicsales.com/ I can confirm that a fresh install, not copied from http://www.qualitymagicsales.com/ does appear to upgrade correctly.  I'm next going to try a site with a lot more products.  It could be that one of the plugins I'm using is tainting the DB in someway that is not obvious which is causing the upgrade problem.

I'll try to figure it out as I try more sites and see if I can find a pattern.

Thanks again for all your help and input. I'm well aware with so many plugins available it is very possible that something is clashing with the upgrade.

andy

**Comment by martinsmagic** [comment] 2017-03-27 18:56
Hi Mike,

one more update from me.  I also tried the update on a store with 15,000 products and about 1,500 outofstock products and it also ran correctly.  So clearly the source site: http://www.qualitymagicsales.com/ has the issue.

Thanks again.

andy
