### ISSUE TITLE
If Redux Framework (Redux.io) is conflicting...

### ISSUE THREAD

**Issue by dovy** [woocommerce/woocommerce#27439] opened 2020-08-21 14:02 UTC
Hey WooCommerce team, lead dev of Redux Framework here (redux.io). I've noticed a few WordPress issues appear where Redux is installed. Namely:

https://wordpress.org/support/topic/variable-product-option-disappeared/
https://wordpress.org/support/topic/inventory-units-by-products-increases-or-decreases-randomly/

I don't believe we are at fault in any way, but if there is anything we can do to help resolve these issues (if we play any part) let me know. I am ready and willing to work with you. Just let me know and I will assist.

**Comment by juliaamosova** [comment] 2020-08-24 18:25
Hi @dovy,

Thanks for reaching out and offering help to work together if needed! 

>https://wordpress.org/support/topic/variable-product-option-disappeared/

We have fixed this issue on the WooCommerce side of things in WooCommerce 4.3.2 (https://github.com/woocommerce/woocommerce/pull/27170). However, this issue is still present on some sites using WooCommerce 4.3.2+ with the issue being caused by 3rd party plugins. 

While WordPress 5.5 removed `jquery-migrate` (reference [here](https://core.trac.wordpress.org/ticket/37110#comment:139) and [here](https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/)), some of the plugins seem to still rely on it. Until these plugins will address the issue on their side, the workaround is to use [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin to include the javascript files in the meantime which is what we are recommending to our users. 

In the case of the particular forum thread that you linked, the user is still using WooCommerce 4.2.2 version which doesn't include the fix we introduced in WooCommerce in 4.3.2. 

>https://wordpress.org/support/topic/inventory-units-by-products-increases-or-decreases-randomly/

This issue needs further investigation and troubleshooting. But we haven't received any other reports in regards to that so likely also nothing to do with Redux. 

In any case, thanks again for pinging us here. I will keep this thread open for some time in case the need for collaboration will raise.

**Comment by juliaamosova** [comment] 2020-11-06 21:39
Hi @dovy,

I am closing this thred as there wasn't anything to be done on either of our sides in regard to the compatibility of our products. Please feel free to comment back in case I missed something and we'd take another look.

**Closed by juliaamosova** 2020-11-06 21:39 UTC
