### ISSUE TITLE
Subtotal and order total prices are not displaying properly

### ISSUE THREAD

**Issue by Adnan0293** [woocommerce/woocommerce#24060] opened 2019-07-03 06:18 UTC
**Theme Name: Minera** 

The subtotal and the order total doesn't appears correctly.
For eg: the product price is 300 (we have increased the quantity as 3), the total price should be 900, but instead the subtotal and the order comes to 899.99 which is incorrect.

**product prices - appear correctly on cart and checkout, incorrectly on order received and email
subtotal and total - appear correctly on cart, checkout, order received and email.**

Below is the url which has the screenshots of the same.
The 
![cart](https://user-images.githubusercontent.com/52481400/60566126-863e0980-9d83-11e9-9946-794d365b8731.png)

![checkout](https://user-images.githubusercontent.com/52481400/60567631-2eee6800-9d88-11e9-8efa-1f01b685cfe2.png)

<img width="550" alt="email" src="https://user-images.githubusercontent.com/52481400/60567632-2eee6800-9d88-11e9-8c88-5150b2860ce7.png">
![order-received](https://user-images.githubusercontent.com/52481400/60567633-2f86fe80-9d88-11e9-9c01-bdf31ec736be.png)

**Comment by vedanshujain** [comment] 2019-07-18 12:03
Can you fill the placeholder template that was there while creating the issue? Specially the system report from WooCommerce > System Status. This will help us in reproducing the issue, and see what version of WooCommerce you are using.

I cannot reproduce this on latest beta version, maybe this was fixed by https://github.com/woocommerce/woocommerce/pull/24024. I am closing the issue, but please comment back if its there on latest beta as well.

**Closed by vedanshujain** 2019-07-18 12:03 UTC
