### ISSUE TITLE
Shipping Methods Does not open

### ISSUE THREAD

**Issue by Judith527** [woocommerce/woocommerce#28089] opened 2020-10-25 18:14 UTC
With the set up of WooCommerce I entered prices for shipping.
But I can not find anywhere where I can change these shipping prices.

On top of that... I also can not :
* Add a shipping zone. Clicking on that button (WC> Settings>Shipping>Shipping zones) ingnites no action. No matter what I fill in... Zone name and then Zone region. I can never add a shipping method. There is just nothing saved. It immediatly deletes the names I filled in as Names or Regions. 
* Neither can I add a Shipping Class
* Neither can I add a Shipping Method
None of these buttons work. There is not even any message or error notification.
What is going on? I can not access nor manage any shipping setting.

I checked the complete status:
- I upgraded the  WP_MEMORY_LIMIT to 90M
_ Updated the missing terms and condition pages
_ Updated plugins
The rest was okay. I checked the systemreport and added it here. 

### WordPress Environment ###

WordPress address (URL): https://marijkeschurink.com
Site address (URL): https://marijkeschurink.com
WC Version: 4.6.1
REST API Version: ✔ 4.6.1
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.34
PHP Post Max Size: 256 MB
PHP Time Limit: 50
PHP Max Input Vars: 5000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.25-MariaDB-1:10.3.25+maria~bionic
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.1
WC Database Prefix: 0_
Total Database Size: 22.54MB
Database Data Size: 19.56MB
Database Index Size: 2.98MB
0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
0_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_cwa: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_expm_hiiden_content: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_expm_maker: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_expm_maker_pages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_find_and_replace: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_formmaker: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
0_formmaker_backup: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
0_formmaker_blocked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_formmaker_display_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_formmaker_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_formmaker_query: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_formmaker_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_formmaker_submits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_formmaker_themes: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
0_formmaker_views: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_fv_DigiWidgetsData: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_fv_DigiWidgetsLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_fv_DigiWidgetsLogHistory: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_fv_DigiWidgetsTemplates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_huge_it_contact_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_huge_it_contact_contacts_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_huge_it_contact_general_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_huge_it_contact_styles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_huge_it_contact_style_fields: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
0_huge_it_contact_submission: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
0_huge_it_contact_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_huge_it_reslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_huge_it_reslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_layerslider: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
0_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_new_royalsliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_options: Data: 3.02MB + Index: 0.30MB + Engine MyISAM
0_postmeta: Data: 2.09MB + Index: 0.30MB + Engine MyISAM
0_posts: Data: 1.31MB + Index: 0.11MB + Engine MyISAM
0_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
0_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_sliders_bkp: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
0_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_slides_bkp: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
0_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
0_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_tinvwl_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_usermeta: Data: 0.07MB + Index: 0.07MB + Engine MyISAM
0_users: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
0_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
0_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wfblockediplog: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
0_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_wfconfig: Data: 2.27MB + Index: 0.00MB + Engine InnoDB
0_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wffilemods: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
0_wfhits: Data: 1.02MB + Index: 0.23MB + Engine InnoDB
0_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
0_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wflogins: Data: 0.38MB + Index: 0.16MB + Engine InnoDB
0_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
0_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_woocommerce_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woof_query_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_yoast_indexable: Data: 0.44MB + Index: 0.20MB + Engine InnoDB
0_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_yoast_seo_links: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
0_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

_: 1
attachment: 379
custom_css: 1
customize_changeset: 1
elementor_library: 3
fmemailverification: 2
form-maker: 1
ml-slider: 1
nav_menu_item: 12
oembed_cache: 3
page: 31
pexcontentslider: 2
pexfullslider: 4
pexservice: 11
portfolio: 153
post: 2
product: 111
revision: 323
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Classic Editor: by WordPress Contributors – 1.6
Elementor: by Elementor.com – 3.0.12
Envato Market: by Envato – 2.0.5
Read More: by Edmon – 2.6.1
Flexible Shipping: by WP Desk – 3.15.0
Form Maker: by 10Web Form Builder Team – 1.13.45
Elementor - Header, Footer & Blocks: by Brainstorm Force
Nikhil Chavan – 1.5.3

Easy HTTPS (SSL) Redirection: by Tips and Tricks HQ – 1.9.1
Imsanity: by Exactly WWW – 2.6.0
Insert Headers and Footers: by WPBeginner – 1.4.6
Jetpack by WordPress.com: by Automattic – 9.0.2
Google Ads & Marketing by Kliken: by Kliken – 1.0.6 – Installed version not tested with active version of WooCommerce 4.6.1
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.6.1
Maintenance: by WebFactory Ltd – 3.97
PayPro Gateways - WooCommerce: by PayPro – 1.3.2 – Installed version not tested with active version of WooCommerce 4.6.1
Really Simple SSL: by Really Simple Plugins – 3.3.5
Slider Revolution: by ThemePunch – 6.2.23
Simple Custom CSS: by John Regan
Danny Van Kooten – 4.0.4

Story Portfolio Items: by Pexeto – 1.0
Story Recent Posts Widget: by Pexeto – 1.0
TI WooCommerce Wishlist: by TemplateInvaders – 1.21.12
Vimeo Youtube Popup Plugin: by N. Rivers – 2.2
YellowPencil Pro: by WaspThemes – 7.3.1
Woo Out Of Stock Products: by Andrew Gunn – 2.3 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.3 – Installed version not tested with active version of WooCommerce 4.6.1
WOOF - WooCommerce Products Filter: by realmag777 – 2.2.4 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce: by Automattic – 4.6.1
Wordfence Security: by Wordfence – 7.4.12
Yoast SEO: by Team Yoast – 15.1.1
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.93.3

### Inactive Plugins (4) ###

Facebook for WooCommerce: by Facebook – 2.0.5 – Installed version not tested with active version of WooCommerce 4.6.1
Mollie Payments for WooCommerce: by Mollie – 5.9.0 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Product Filter by WooBeWoo: by WooBeWoo – 1.3.8
WooCommerce Shipping & Tax: by Automattic – 1.25.0 – Installed version not tested with active version of WooCommerce 4.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #909 - /winkel/
Cart: #910 - /winkelmand/
Checkout: #911 - /afrekenen/
My account: #912 - /mijn-account/
Terms and conditions: #1482 - /terms-and-conditions/

### Theme ###

Name: Story
Version: 1.9.12
Author URL: http://pexetothemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 148
Oldest: 2020-10-18 16:04:03 +0000
Newest: 2020-10-25 20:07:11 +0000

`

![Schermafbeelding 2020-10-25 om 19 07 32](https://user-images.githubusercontent.com/64659428/97115295-47f5f780-16f6-11eb-82fa-5f1965a559de.png)

**Comment by juliaamosova** [comment] 2020-10-28 21:25
Hi @Judith527,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-28 21:25 UTC
