### ISSUE TITLE
database update won't complete

### ISSUE THREAD

**Issue by jbrenner99** [woocommerce/woocommerce#26883] opened 2020-06-26 21:26 UTC
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
Contact WooCommerce support by opening a ticket.
https://woocommerce.com/contact-us/ 

**For help with custom code**
WooCommerce Slack Community: https://woocommerce.com/community-slack/ in the `#developers` channel. 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The Official WooCommerce Facebook Group https://www.facebook.com/groups/advanced.woocommerce/

**Comment by peterfabian** [comment] 2020-06-29 09:44
Hi @jbrenner99 

Thanks for opening an issue. Could you please elaborate on the issue you're seeing? Can you include the [system status report](https://docs.woocommerce.com/document/how-to-review-your-woocommerce-system-status/) and add a steps to reproduce this problem? Is it actually the database that hasn't updated or maybe just a notice stuck on your dashboard? 

Thanks!

**Comment by jbrenner99** [comment] 2020-06-29 14:08
The scheduled tasks to update the database were stuck.  I did a chat with someone from WooCommerce on Friday and they were able to get the tasks to process and verify the update completed.  However, the import of the historical data is doing the same thing.   I see that the number of scheduled tasks is growing and the queue even though it tells me in will begin processing in the next xxx seconds, nothing comes off the queue.  We are in a GoDaddy Mananaged Hosting environment.


`
### WordPress Environment ###

WordPress address (URL): https://kappapuzzles.com
Site address (URL): https://kappapuzzles.com
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.12
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32-78.0-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: wp_1mcgxq2kjc_
Total Database Size: 658.29MB
Database Data Size: 530.99MB
Database Index Size: 127.30MB
wp_1mcgxq2kjc_woocommerce_sessions: Data: 76.13MB + Index: 1.34MB + Engine InnoDB
wp_1mcgxq2kjc_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_woocommerce_downloadable_product_permissions: Data: 2.41MB + Index: 2.65MB + Engine MyISAM
wp_1mcgxq2kjc_woocommerce_order_items: Data: 4.82MB + Index: 2.94MB + Engine MyISAM
wp_1mcgxq2kjc_woocommerce_order_itemmeta: Data: 41.47MB + Index: 22.50MB + Engine MyISAM
wp_1mcgxq2kjc_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_1mcgxq2kjc_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1mcgxq2kjc_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1mcgxq2kjc_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_1mcgxq2kjc_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1mcgxq2kjc_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1mcgxq2kjc_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_1mcgxq2kjc_commentmeta: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_comments: Data: 12.45MB + Index: 5.75MB + Engine MyISAM
wp_1mcgxq2kjc_daily_quotes: Data: 0.20MB + Index: 0.02MB + Engine MyISAM
wp_1mcgxq2kjc_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_gf_entry: Data: 0.35MB + Index: 0.06MB + Engine MyISAM
wp_1mcgxq2kjc_gf_entry_meta: Data: 2.27MB + Index: 2.06MB + Engine MyISAM
wp_1mcgxq2kjc_gf_entry_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_gf_form_meta: Data: 0.17MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_gf_form_view: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_1mcgxq2kjc_gglcptch_whitelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_field_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_options: Data: 5.05MB + Index: 0.13MB + Engine InnoDB
wp_1mcgxq2kjc_pmxe_exports: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB + Engine MyISAM
wp_1mcgxq2kjc_pmxe_posts: Data: 0.37MB + Index: 0.16MB + Engine MyISAM
wp_1mcgxq2kjc_pmxe_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_postmeta: Data: 118.38MB + Index: 76.70MB + Engine MyISAM
wp_1mcgxq2kjc_posts: Data: 12.65MB + Index: 4.13MB + Engine MyISAM
wp_1mcgxq2kjc_responsive_menu: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_css_bkp: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_sliders: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_sliders_bkp: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_slides: Data: 0.74MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_slides_bkp: Data: 0.58MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_rg_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_rg_form_meta: Data: 0.14MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_rg_form_view: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_rg_lead: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_rg_lead_detail: Data: 0.34MB + Index: 0.52MB + Engine MyISAM
wp_1mcgxq2kjc_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_rg_lead_meta: Data: 0.07MB + Index: 0.03MB + Engine MyISAM
wp_1mcgxq2kjc_rg_lead_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_sfa_abandoned_carts: Data: 44.66MB + Index: 0.77MB + Engine MyISAM
wp_1mcgxq2kjc_sgpb_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sgpb_subscription_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sg_fblike_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sg_html_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sg_image_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sg_popup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sg_popup_addons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1mcgxq2kjc_sg_popup_addons_connection: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sg_popup_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_sg_shortCode_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_1mcgxq2kjc_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_1mcgxq2kjc_term_relationships: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_1mcgxq2kjc_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_usermeta: Data: 8.37MB + Index: 5.41MB + Engine MyISAM
wp_1mcgxq2kjc_users: Data: 0.52MB + Index: 0.50MB + Engine MyISAM
wp_1mcgxq2kjc_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1mcgxq2kjc_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1mcgxq2kjc_wc_download_log: Data: 0.60MB + Index: 0.57MB + Engine MyISAM
wp_1mcgxq2kjc_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1mcgxq2kjc_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_1mcgxq2kjc_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_1mcgxq2kjc_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1mcgxq2kjc_wc_product_meta_lookup: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
wp_1mcgxq2kjc_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_1mcgxq2kjc_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_1mcgxq2kjc_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1mcgxq2kjc_wpml_mails: Data: 196.57MB + Index: 0.25MB + Engine MyISAM

### Post Type Counts ###

amn_mi-lite: 1
attachment: 841
custom_css: 1
customize_changeset: 2
ich_cpt: 1
mts_notification_bar: 25
nav_menu_item: 21
page: 41
popupbuilder: 9
post: 8
product: 62
product_variation: 504
revision: 715
shop_coupon: 82
shop_order: 38175
shop_order_refund: 221
wbcr-snippets: 7
wpcf7_contact_form: 2
yith-wcbm-badge: 13

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Gravity Forms: by rocketgenius – 2.4.17
HTML in Category Descriptions: by Arno Esterhuizen – 1.2.3
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 2.3.2.5
Contact Form 7 Conditional Fields: by Jules Colle – 1.9.4
Classic Editor: by WordPress Contributors – 1.5
Cleverwise Daily Quotes: by Jeremy O'Connell – 2.8
Contact Form 7: by Takayuki Miyoshi – 5.1.9
Easy Google Fonts: by Titanium Themes – 1.4.4
Error Log Monitor: by Janis Elsts – 1.6.10
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
reCaptcha by BestWebSoft: by BestWebSoft – 1.57
iframe: by webvitaly – 4.5
Insert Headers and Footers: by WPBeginner – 1.4.5
Woody ad snippets (PHP snippets | Insert PHP): by Will Bontrager Software
LLC
Webcraftic  – 2.3.5

Popup Builder: by Sygnoos – 3.68.1
Post Expirator: by Aaron Axelsen – 2.4.0.1
Quick Page/Post Redirect Plugin: by anadnet – 5.1.9
Responsive Image Maps: by Philip Newcomer – 1.4
Slider Revolution: by ThemePunch – 6.2.15
TAO Schedule Update: by TAO Digital – 1.15
Theme Customisations: by Virtina – 1.0.0
Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.6.1
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.3.2 – Installed version not tested with active version of WooCommerce 4.2.2
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.4 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Product Attachment: by theDotstore – 1.5.4 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Boost Sales Premium: by Andy Ha (villatheme.com) – 1.4.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.2.7
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.14
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.9.2

WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.6
WooCommerce Remove Product Sorting: by SkyVerge – 1.0.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0 – Installed version not tested with active version of WooCommerce 4.2.2

WooCommerce: by Automattic – 4.2.2
Crossword Compiler Puzzles: by WordWeb Software – 11.0
WP Mail Logging: by MailPoet – 1.9.6
WP Mail SMTP: by WPForms – 2.1.1
WP Notification Bars: by MyThemeShop – 1.0.5
WP Rollback: by Impress.org – 1.7.0
YITH WooCommerce Badge Management: by YITH – 1.4.2

### Inactive Plugins (7) ###

Akismet Anti-Spam: by Automattic – 4.1.4
Storefront Product Pagination: by WooThemes – 1.2.4 – Installed version not tested with active version of WooCommerce 4.2.2
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Sticky Add to Cart: by WooThemes – 1.1.9
WooCommerce Helper: by WooCommerce – 1.7.2 – Installed version not tested with active version of WooCommerce 4.2.2 – Network enabled
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.6
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Must Use Plugins (1) ###

System Plugin: by  – 3.16.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Merlin Child Theme
Version: 1.0.0
Author URL:
Child Theme: ✔
Parent Theme Name: Merlin
Parent Theme Version: 1.2.3 – 1.4.2 is available
Parent Theme Author URL: https://themezee.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
Webhooks Enabled: ❌
                                                                                                Not generated

### Action Scheduler ###

Canceled: 7
Oldest: -0001-11-29 19:03:58 -0456
Newest: -0001-11-29 19:03:58 -0456

Complete: 88
Oldest: 2020-06-26 09:24:44 -0400
Newest: 2020-06-26 18:09:47 -0400

Pending: 137
Oldest: 2020-06-26 18:15:39 -0400
Newest: 2020-06-29 09:41:40 -0400

`
____________________________________________________
Joann Brenner |Senior Director - Information Technology | SPARTAN ORGANIZATION, INC.
Representing:  KAPPA PUBLISHING  GROUP, INC.  | KAPPA MAP GROUP, LLC
6198 Butler Pike, Suite 200 | Blue Bell, PA 19422| P: 215.643.6385 X108 | F: 215.628.3571 | E: jbrenner@spartanorg.com<mailto:jbrenner@spartanorg.com>

**Comment by tammullen** [comment] 2021-03-24 18:19
Hi @jbrenner99 

Apologies for the delayed reply.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-24 18:19 UTC
Labels: has feedback
