### ISSUE TITLE
WooCommerce + MediaFire DL links using website bandwidth

### ISSUE THREAD

**Issue by Beats24-7** [woocommerce/woocommerce#29106] opened 2021-02-11 19:08 UTC
Hi there,
I’m using WooCommerce in your latest version and include MediaFire download links in the product settings (virtual, downloadable) to serve digital downloads. WooCommerce generates a download link that proxies the connection to MediaFire and then serves it through the URL of the website in order to mask the URL of the file the customer is downloading. The File download method in WC is set to ‘force downloads’.

This is causing a problem because customer downloads, while being served by MediaFire, are using my *hosting* account’s bandwidth usage (350+GB per month), causing outages due to bandwidth limits being reached. I have invested two months of time and effort trying to figure out what is causing these crazy bandwidth spikes occuring on my shared server and it looks like this is it. I have checked the whole website, logs etc and this has to be the root of the issue as everything else looks normal. It also doesn’t happen with a clone of the website on a subdomain so it definitely is caused by (download) traffic. My website strictly serves "https" but I have a few "http" MediaFire links. Could this be an issue? Any help with this issue is greatly appreciated!

Thank you. Best regards, Lars

**Comment by tammullen** [comment] 2021-02-11 21:26
Hi @Beats24-7 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case such as the guide to handling downloads https://docs.woocommerce.com/document/digital-downloadable-product-handling/; 
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-02-11 21:26 UTC

**Comment by Beats24-7** [comment] 2021-02-12 00:08
Hi @tammullen,
thanks for your reply. I will further investigate this and update you. However, I have the latest version of WooCommerce and I am not using an additional plugin to serve the download links for the virtual and downloadble product files (simply the WC settings: -> Add file, download link). Furthermore, as already mentioned, the same exact website on a subdomain without download traffic doesn't generate this amount of bandwidth. I am installing New Relic infrastructure on the server right now to be able to investigate it further and send you proof if necessary.
I also already created a post on the Wordpress WC community forum about 2 days ago. This forum is getting flooded with requests though and I don't think I will receive a response over there. Thank you for your understanding.

**Comment by Beats24-7** [comment] 2021-02-15 19:03
Hi @tammullen,
I wanted to give you an update. So on Friday I set the download method in the WC product download settings to "redirect only" and removed the filename string option. The issue has been gone ever since and the bandwidth consumption has gone back to normal, as with my previous shop system, Easy Digital Downloads. Proof -> https://prnt.sc/zmvkhx
WC shows that the "redirect option" has deprecated but it still seems to work and fix the issue. I will further test if the unique string option for the filename is an issue as well. So this severe issue is 100% caused by your software.

**Comment by Beats24-7** [comment] 2021-02-16 19:03
Hello there,
did you receive the update?
