### ISSUE TITLE
Tax not updating after refund

### ISSUE THREAD

**Issue by kgoedecke** [woocommerce/woocommerce#21208] opened 2018-08-28 00:32 UTC
**Describe the bug**
The tax amount is not being updated after a refund has been issued.

**To Reproduce**
1. Create order including items with tax
2. Refund item with tax (manual refund)
3. Open order in wp-admin 
4. Order shows correct updated totals but order tax is still the one prior to refund

**Screenshots**
![image](https://user-images.githubusercontent.com/5519740/44693776-5d196200-aa6a-11e8-8a66-8b52f3caded4.png)

**Expected behavior**
Show updated tax amount after refund along with initial tax amount (strike through).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 4.9.6
WooCommerce 3.4.0

**Comment by claudiulodro** [comment] 2018-08-28 18:30
Hi there,

I was not able to reproduce this problem on a site running only WooCommerce 3.4.0 or the latest version of WooCommerce (3.4.4):

<img width="630" alt="screen shot 2018-08-28 at 11 19 51 am" src="https://user-images.githubusercontent.com/7317227/44742373-8f4fb180-aab4-11e8-9a25-980cba6d555a.png">

Can you reproduce this issue on a site with only WooCommerce and no third-party plugins that may affect calculations? If so, please provide more details so that we can investigate it better.

Can it have been user error while issuing the refund? It is possible to do a refund without refunding the tax by putting a '0' in the tax input when issuing the refund:
<img width="632" alt="screen shot 2018-08-28 at 11 25 14 am" src="https://user-images.githubusercontent.com/7317227/44742635-33395d00-aab5-11e8-8ad4-7b89e63c1568.png">

Since this issue cannot be reproduced on a site with only WooCommerce, and you have not provided any extra info that may help us reproduce the issue, I must close this issue as non-reproducible. Thanks.

**Closed by claudiulodro** 2018-08-28 18:30 UTC

**Comment by kgoedecke** [comment] 2018-08-28 18:50
@claudiulodro I actually ran an other test, and it was exactly how you assumed... a user error. Thanks a lot for taking the time and looking into it!
