### ISSUE TITLE
Custom product attribute name with an apostrophe shows backslash on frontend

### ISSUE THREAD

**Issue by menakas** [woocommerce/woocommerce#22438] opened 2019-01-14 07:23 UTC
**Describe the bug**
When A Custom product attribute name is added with an apostrophe in it, it shows the apostrophe with the escape character of backslash in the [backend](http://pic.pros.pr/308d99e1f4b6) and [frontend](http://pic.pros.pr/d5b94c9cc6a1). 

Repeated clicks on "Save attributes" increase the number of backslashes: [http://pic.pros.pr/1fedd75895db](http://pic.pros.pr/1fedd75895db)

**To Reproduce**
1. Go to the Admin interface, "Edit Product". Choose Variable Product.
2. Click on Attributes tab. Click on Add (Custom product attribute)
3. Give a name with an apostrophe in it.
4. Click on "Save attributes".
5. The name displays with **\\'** in it.
6. Save Product. 
7. Click on View Product. The name displays with **\\'** in it.
8. While saving attributes, multiple saves increase the number of backslashes.

**Screenshots**
[http://pic.pros.pr/308d99e1f4b6](http://pic.pros.pr/308d99e1f4b6)
[http://pic.pros.pr/1fedd75895db](http://pic.pros.pr/1fedd75895db)
[http://pic.pros.pr/d5b94c9cc6a1](http://pic.pros.pr/d5b94c9cc6a1)

**Expected behavior**
The backslashes should not appear, at least on the frontend.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://one.wordpress.test
Site URL: http://one.wordpress.test
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: ❌ 5.0.2 - There is a newer version of WordPress available (5.0.3)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.8
PHP Version: 7.2.13-1+ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.11-MariaDB-1:10.3.11+maria~trusty
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 36.57MB
Database Data Size: 23.14MB
Database Index Size: 13.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.11MB + Index: 0.05MB
wp_woocommerce_order_itemmeta: Data: 1.48MB + Index: 0.63MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 1.48MB + Index: 0.94MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 10.02MB + Index: 0.06MB
wp_postmeta: Data: 7.38MB + Index: 9.63MB
wp_posts: Data: 1.36MB + Index: 0.41MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.39MB + Index: 0.42MB
wp_users: Data: 0.06MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.05MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.08MB + Index: 0.02MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_admin_note_actions: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 19
customize_changeset: 5
page: 14
post: 7
product: 33
product_variation: 45
scheduled-action: 473
shop_coupon: 11
shop_order: 982
shop_order_refund: 1
shop_subscription: 309
wc_membership_plan: 1
wc_user_membership: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.0-dev

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rrennick** [comment] 2019-01-14 13:38
This is duplicate of #22147 & will be fixed in #22370.

**Comment by menakas** [comment] 2019-01-14 13:55
@rrennick 
There is a difference. #22147 refers to apostrophes in the attribute values, while this concerns apostrophes in attribute names.

**Comment by rrennick** [comment] 2019-01-15 17:57
I tested this against #22370 and it fixes this issue as well. @menakas do you want to confirm?

**Comment by menakas** [comment] 2019-01-16 03:17
@rrennick Yes. it fixes this issue as well.

**Comment by rrennick** [comment] 2019-01-16 13:31
@menakas Awesome, thanks.

**Closed** 2019-01-16 13:30 UTC
Labels: bug
