### ISSUE TITLE
I am receiving an error Sorry, you cannot list resources

### ISSUE THREAD

**Issue by anish1982** [woocommerce/woocommerce#26889] opened 2020-06-29 12:33 UTC
Please can you help

We have given all the read/write permission also yet there is the error.

https://www.onlinemantra.in/wp-json/wc/v2/products?consumer_key=ck_504cf404b8e009f8dbc6d71ebce362b009403689&consumer_secret=cs_59aab2d4c6db8e48c6cd632b48d703f8a5101d9f

**Comment by tammullen** [comment] 2020-06-29 13:42
hi @anish1982 
​
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Rest API Documentation](https://docs.woocommerce.com/document/woocommerce-rest-api/) 
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-06-29 13:42 UTC
