### ISSUE TITLE
Not all products appearing in a category 

### ISSUE THREAD

**Issue by konnessa** [woocommerce/woocommerce#15156] opened 2017-05-18 16:33 UTC
On my site I have several products not appearing in a category they have been assigned. This has happened on several different categories. 

For example the boot category has 5 items in but actually has 8 products set to it. The missing items which visited directly and going back one level on the breadcrumb to the sub category still don't appear. 

I've checked against plugins and with the theme developer but no one seems to be able to fix the issue so could be an issue with woocommerce itself.

**Comment by konnessa** [comment] 2017-05-18 16:39
Latest version of woocommerce and Wordpress installed.

**Comment by mikejolley** [comment] 2017-05-19 09:55
You've not added much detail here or steps to reproduce so all I can do is list some things you need to check.

For the missing products:

- Enable they are in stock, stock status
- In the top right of the edit screen look at the visibility option. They need to be visible in the catalog to appear.
- Check for plugin conflicts and try another theme.

There are no known issues here so closing - not able to reproduce.

**Closed by mikejolley** 2017-05-19 09:55 UTC
