### ISSUE TITLE
Incusive tax rate calculation fails when Store Address is set to India and Billing Address is set to US

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28689] opened 2020-12-30 12:51 UTC
## Bug Description:
 Inclusive tax rate calculation fails when Store Address is set to India and Billing Address is set to US

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)
                
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard and set the Store Address to India.
1. Go to WooCommerce->Settings->Payments->Set to Cash on Delivery
1. Create or import Products
1. Go to WooCommerce->Settings->Tax options
1. Set "Price entered with Tax:  Yes, I will enter prices inclusive of tax"
1. Set "Calculate Tax based on: Customer Shipping address/Billing Address"
1. Set "Display Price during cart and checkout: Including Tax"
1. Set "Display Tax Totals: As a single Total"
1. Click on "Save changes" button
1. Go to WooCommerce->Settings->Tax->Standard Tax rate and either import us_tax_rate.csv" file or add a US, California to 7.5% tax rate.
1. Go to front end and add a product say of 55$ to cart
1. Click on View Cart
1. Click on Procced to Checkout
1. Set the Billing address to US, California
1. Note that price displayed is 59.12 with 4.12 tax added
1. As per the inclusive tax formula calculation : tax_amount = price - ( price / ( ( tax_rate_% / 100 ) + 1 ) ) , the tax needs to be 3.84 when product price is 55 and tax rate is 7.5%
1. Observe that Inclusive tax rate calculation fails when Store Address is set to India and Billing Address is set to US

**Note**:
Tax document: https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/
 
## Actual Result:
Inclusive tax rate calculation fails when Store Address is set to India and Billing Address is set to US

## Expected Result:
 Inclusive tax rate calculation should work properly when Store Address is set to India and Billing Address is set to US

## Artifacts:
[#28689.zip](https://github.com/woocommerce/woocommerce/files/5754240/28689.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://fresh-fish.jurassic.ninja
Site address (URL): https://fresh-fish.jurassic.ninja
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.2
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.13
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.32-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 3.95MB
Database Data Size: 2.51MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 7
post: 2
product: 18
product_variation: 7
revision: 1
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Query Monitor: by John Blackbourn – 3.6.5
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.2.4 – Installed version not tested with active version of WooCommerce 4.0
Jetpack by WordPress.com: by Automattic – 9.2.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.6
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
Razorpay for WooCommerce: by Team Razorpay – 2.5.0
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce: by Automattic – 4.9.0-rc.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.0 (update to version 1.1 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2020-12-30 07:07:52 +0000
Newest: 2020-12-30 07:45:49 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-12-30 16:27
Hi @gglobalstep,

Thank you for reporting the issue! 

I think everything is working correctly though and the tax amount is calculated as expected.

Documenting my steps below.

My store is based in India:

![i1](https://user-images.githubusercontent.com/19143190/103366546-f02a9280-4a90-11eb-8c35-db5603c7a095.jpg)

I have a tax rate of 7.5% set up for California, US:

![i2](https://user-images.githubusercontent.com/19143190/103366567-fde01800-4a90-11eb-8761-3a0bed8884f5.jpg)

I have configured tax settings as described in the steps to reproduce. 

Here I am testing the case where `Calculate Tax based on:` is set to `Customer Billing Address`:

![i3](https://user-images.githubusercontent.com/19143190/103366659-308a1080-4a91-11eb-850e-d8ce2f59e060.jpg)

On the Checkout, I am seeing the price of $59.12 which is correct because the tax is based on the customer's billing address which is California, US:

![i4](https://user-images.githubusercontent.com/19143190/103366675-3d0e6900-4a91-11eb-8129-bc2fdc9cf2b3.jpg)

>As per the inclusive tax formula calculation : tax_amount = price - ( price / ( ( tax_rate_% / 100 ) + 1 ) ) , the tax needs to be 3.84 when product price is 55 and tax rate is 7.5%

Hmm, the tax here is calculated as $55 + 7.5% = $59.125 - rounded to $59.12 which is what we are seeing on the Checkout page. 

![i5](https://user-images.githubusercontent.com/19143190/103366825-92e31100-4a91-11eb-8e48-1b1b7cb97682.jpg)

If I switch `Calculate Tax based on:` to `Shop base address` (which is India with zero tax rate):

![i6](https://user-images.githubusercontent.com/19143190/103366904-b908b100-4a91-11eb-8208-2eeebe24dda4.jpg)

I am getting the price displayed as $55.00 on the Checkout because we don't have any tax rates set up for India so $55.00 is correct:

![i7](https://user-images.githubusercontent.com/19143190/103366948-db023380-4a91-11eb-9366-488610e1b444.jpg)

Unless I am missing something, everything seems to be in order. I'll leave this open for a bit for @vedanshujain to take a look as well to verify my logic.

**Comment by vedanshujain** [comment] 2023-06-22 09:51
Apologies for missing this, calculations here are correct, closing this issue!

**Closed by vedanshujain** 2023-06-22 09:51 UTC
Labels: Bug, Tax, needs: developer feedback, type: question, plugin: woocommerce
