### ISSUE TITLE
Not all meta_data items are returned when calling /customers (varying according to type of authorization)

### ISSUE THREAD

**Issue by hexoquinasa** [woocommerce/woocommerce#28068] opened 2020-10-22 22:06 UTC
Wordpress version 5.5.1
Woocommerce version 4.6.0
PHP 7.3

Hello,
I have two tabs in Postman and run the same payload using different auth types,
with the auth in the url like: https://www.mystore.com/wp-json/wc/v2/customers?
page=1&per_page=10&consumer_key=myke&consumer_secret=mysecret

The problem is that it doesn't return all the metadata. It just returns the preset by woocommerce:
```
"meta_data": [
"id": 469,
"key": "shipping_method",
"value": [
"flat_rate:2"
]
},
{
"id": 470,
"key": "shipping_phone",
"value": "4168888888"
},
{
"id": 471,
"key": "wc_last_active",
"value": "1602892800"
}
]...
```

When calling the api using postman and Oauth 1.0, HMAC-SHA1 it works
I get the extra metadata.

```
"meta_data": [
{
"id": 469,
"key": "shipping_method",
"value": [
"flat_rate:2"
]
},
{
"id": 470,
"key": "shipping_phone",
"value": "4168888888"
},
{
"id": 471,
"key": "wc_last_active",
"value": "1602892800"
},
{
"id": 684,
"key": "CustomerPrimaryCode",
"value": "Woo_11"
}
],
```

I could find it in the issues tab, is this a known issue? 

Thank you
E. Lopez

**Comment by peterfabian** [comment] 2020-10-23 13:22
Sorry, I wasn't able to reproduce this one. As you can see from the screenshot, even third party `meta_data` is present (like the one from mailchimp)

<img width="1288" alt="Screenshot 2020-10-23 at 15 20 17" src="https://user-images.githubusercontent.com/2207451/97008578-4b954d00-1543-11eb-95b3-c56da07d341a.png">


Have you tried to check this with no other plugins only WC core active? Thx!

**Comment by hexoquinasa** [comment] 2020-10-26 03:45
Hi Peterfabian
Thank you for your answer. You are right, I don't know exaclty how it works but, when I disable any plugin it works (I tried WP101 Video Tutorials and Search Engine Visibility), then after reenabling the plugin  it continues working (showing all metadata).
I really don't understand how this could affect the woocommerce api results.

Thank you

**Comment by tammullen** [comment] 2020-11-04 21:57
Hi @hexoquinasa 

As a part of this repository’s maintenance, I am closing this issue as it looks like it has been resolved. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2020-11-04 21:57 UTC
Labels: status: needs feedback
