### ISSUE TITLE
Adding a manual refund amount via PayPal is not possible anymore

### ISSUE THREAD

**Issue by FritzHerbers** [woocommerce/woocommerce#25840] opened 2020-03-06 19:59 UTC
**Describe the bug**
Since an upgrade to 3.8.1 (from some 3.7), it is not possible to set the refund amount manually.

**To Reproduce**
Since the 3.8.1 version the refund is calculated from the return items and prices.
We have a restocking fee on items, also we need the possibility to subtract additional costs from the total.
We used the shipping costs to set the refund amount, looking really bad, with a big negative number on the order. 

**Expected behavior**
Bring back previous input field or add an additional field to allow to enter a self calculated refund value.

**WordPress Environment**
woocommerce: 3.8.1

**Comment by FritzHerbers** [comment] 2020-04-16 10:58
We are really missing the old feature. Can you please provide us with an update how this issue will be addressed.

**Comment by juliaamosova** [comment] 2020-05-14 21:19
Hi @FritzHerbers,

Apologies for the delayed response here! Can you please specify what do you mean exactly? 

I am not seeing any difference on the order screen (paid by PayPal) between 3.7 and 4.2 beta versions:

![pp1](https://user-images.githubusercontent.com/19143190/81987042-f0137a80-9606-11ea-8efa-a10f40dabf61.jpg)

![pp2](https://user-images.githubusercontent.com/19143190/81987055-f43f9800-9606-11ea-98a4-c0b454c1d953.jpg)

**Comment by FritzHerbers** [comment] 2020-05-14 22:07
In older WC versions it was possible to set a refund amount explicitly.
On WC 3.8.1 it is only possible to set a refund on a product (or shipping).

We would like to have the possibility to set a refund on the order (additional to setting a refund on single items).

For example, an order of 1000 (subtotal) is returned, with a restocking fee of 15%, the customer gets a refund of 1000 - 15%*1000 = 850.

We don't like to calculate on each item the restocking fee of 15%:
item1, 100, refund 85
item2, 135, refund (100%-15% * 135)...
etc.
with 20 positions this gets very tedious.

(We abused the shipping to refund, resulting in negative shipping amounts on screen.)

**Comment by tammullen** [comment] 2021-03-25 19:50
Hi @FritzHerbers 

Apologies in the delay in replying.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 19:50 UTC
Labels: has feedback

**Comment by FritzHerbers** [comment] 2021-03-25 20:08
@tammullen 
Well it is how you look at it.
In previous versions we had the possibility to add an explicit refund amount.

So this is an enhancement request (for a lost feature).

**Comment by tammullen** [comment] 2021-03-25 21:49
Thanks @FritzHerbers 

Can you submit an enhancement request using the enhancement request template https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=5-Enhancement.md&title=
