### ISSUE TITLE
CART display issues; WC 3.7.1

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#24949] opened 2019-10-31 22:59 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

**1. Cart display issues, Woocommerce version 3.7.1
2. www.dreamesper.com
3. When adding items to cart, the cart displays items all over the place, so to speak... no clue as to how to fix at the moment...**

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by juliaamosova** [comment] 2019-11-05 14:49
Hi @dreamesper!

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs specific to the WooCommerce plugin only. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

At a quick glance, the issue seems to be related to your theme. 

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-11-05 14:49 UTC
Labels: can't reproduce
