### ISSUE TITLE
fail to set featured product

### ISSUE THREAD

**Issue by thefrozenbear** [woocommerce/woocommerce#27694] opened 2020-09-17 08:25 UTC
hello, good morning.
i have a problem with the feature product. i want to add some selected product as feature product in my home page and i already set my product as "feature" like how it should be.. but in my home page feature product section,it fail to show the products i have selected. is that bug or? i tried to deactive my caching plugin but still the same. 

### WordPress Environment ###

WordPress address (URL): https://www.thefrozenbear.com
Site address (URL): https://www.thefrozenbear.com
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: ❌ 5.4.2 - There is a newer version of WordPress available (5.5.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.17
PHP Post Max Size: 135 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 
WC Database Prefix: wp_
Total Database Size: 11.27MB
Database Data Size: 9.24MB
Database Index Size: 2.03MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_options: Data: 4.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 2.50MB + Index: 0.25MB + Engine InnoDB
wp_posts: Data: 1.47MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

astra_adv_header: 4
attachment: 77
custom_css: 1
customize_changeset: 75
elementor_library: 19
nav_menu_item: 6
oembed_cache: 1
page: 21
post: 3
product: 17
product_variation: 20
revision: 85

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Advanced WordPress Backgrounds: by nK – 1.6.7
Astra Pro: by Brainstorm Force – 2.6.4
Premium Starter Templates: by Brainstorm Force – 2.3.5
Astra Widgets: by Brainstorm Force – 1.2.5
Customizer Reset: by WPZOOM – 1.0.1
Elementor Pro: by Elementor.com – 3.0.4
Elementor: by Elementor.com – 3.0.8.1
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
LiteSpeed Cache: by LiteSpeed Technologies – 3.4.2
Ultimate Addons for Elementor: by Brainstorm Force – 1.27.0
WooCommerce: by Automattic – 4.5.2
Yoast SEO: by Team Yoast – 14.9 – Installed version not tested with active version of WooCommerce 4.5.2

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Contact Form 7: by Takayuki Miyoshi – 5.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Must Use Plugins (1) ###

closte-requirements.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Astra
Version: 2.5.4 (update to version 2.5.5 is available)
Author URL: https://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-09-16 16:59:42 +0000
Newest: 2020-09-16 16:59:42 +0000

Complete: 13
Oldest: 2020-08-23 09:12:27 +0000
Newest: 2020-09-16 18:42:45 +0000

`

**Comment by juliaamosova** [comment] 2020-09-21 21:05
Hi @thefrozenbear,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-09-21 21:05 UTC
