### ISSUE TITLE
custom product details not showing app on product page

### ISSUE THREAD

**Issue by kenokiya** [woocommerce/woocommerce#21166] opened 2018-08-23 14:20 UTC
I am using woocomerce and i have activated wc frontend manager and i have woobooking activated.trying to add custom details for a woobooking product and unfortunately it does not show up on the product page

**Comment by claudiulodro** [comment] 2018-08-23 19:09
Hi there,

If this is an issue with the WooCommerce Bookings plugin I recommend [contacting support](https://woocommerce.com/my-account/create-a-ticket/), as we don't provide support or investigate bugs in Bookings on the WooCommerce GitHub page.

If this is an issue caused by WC Frontend Manager, you'll have to follow up with their support team.

I'm closing this issue as this is not a bug in the WooCommerce core plugin. Hope this clears things up.

Thanks.

**Closed by claudiulodro** 2018-08-23 19:09 UTC

**Comment by kenokiya** [comment] 2018-08-23 19:29
thanks
