### ISSUE TITLE
Sort By Price Variant Issue

### ISSUE THREAD

**Issue by jefreylandicho** [woocommerce/woocommerce#19726] opened 2018-04-15 22:46 UTC
Sort by price order issue with multiple products variant 
Tested the sorting order via  admin as well as on default templates gives incorrect order.
I tried filtering it that used to work on old woo version but doesn't work either.
These products with multiple variants contains the same price e.g sizes
![wooissue](https://user-images.githubusercontent.com/6689625/38784265-e82bcf96-4141-11e8-926b-166965367651.png)

`
function add_postmeta_ordering_args( $args_sort ) {

	$orderby_value = isset( $_GET['orderby'] ) ? wc_clean( $_GET['orderby'] ) :
        apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby' ) );
	switch( $orderby_value ) {
		case 'lowprice':
			$args_sort['orderby'] = 'meta_value_num';
			$args_sort['order'] = 'asc';
			$args_sort['meta_key'] = '_price';
			break;
       case 'highprice':
            $args_sort['orderby'] = 'meta_value_num';
            $args_sort['order'] = 'desc';
            $args_sort['meta_key'] = '_price';
            break;

	}

	return $args_sort;
}
add_filter( 'woocommerce_get_catalog_ordering_args', 'add_postmeta_ordering_args' );
function add_new_postmeta_orderby( $sortby ) {
   $sortby['lowprice'] = __( 'Sort By Low Price', 'woocommerce' );
   $sortby['highprice'] = __( 'Sort By High Price', 'woocommerce' );
   return $sortby;
}
add_filter( 'woocommerce_default_catalog_orderby_options', 'add_new_postmeta_orderby' );
add_filter( 'woocommerce_catalog_orderby', 'add_new_postmeta_orderby' );``

**Comment by peterfabian** [comment] 2018-04-16 14:13
Hi Jefrey, 

I can't seem to reproduce the issue, it seems to me the order is correct (and the order is the same in both admin and product listing in the shop):
![price_ordering](https://user-images.githubusercontent.com/2207451/38813974-a46d12a2-4190-11e8-9b10-dbbb9965a872.png)

Therefore, we would require more details to be able to reproduce the problem. 
Can you please try to follow the [Self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to rule out possible plug in conflict?

It would also help if you attached your system log for us to see what version of WooCommerce you're using and if you could test this behavior with the latest `master` branch.

**Comment by jefreylandicho** [comment] 2018-04-16 15:25
Hi Peter,
Yes, you are correct, I just added the filter to test it out.
Regarding the issue, it seems to affect products that are either imported via CSV or the value of the price is generated through custom fields means.

if the product is added normally, the price works out fine
but price generate with csv or custom field don't sort out
the temporary fixed, I had to do is to re-update the price
for example the price of the produc is 10 I would changed it to 10.00 and vice versa
these mostly affect variant products 


### WordPress Environment ###

Home URL: http://109.199.101.145/~zuvaa
Site URL: http://109.199.101.145/~zuvaa
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.29 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.0.29
PHP Post Max Size: 32 MB
PHP Time Limit: 45
PHP Max Input Vars: 1000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 24 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wpiu_
Total Database Size: 124.60MB
Database Data Size: 71.25MB
Database Index Size: 53.35MB
wpiu_woocommerce_sessions: Data: 0.19MB + Index: 0.02MB
wpiu_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpiu_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpiu_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpiu_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpiu_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpiu_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpiu_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpiu_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpiu_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpiu_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpiu_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpiu_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpiu_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpiu_chat_table: Data: 0.02MB + Index: 0.00MB
wpiu_commentmeta: Data: 0.02MB + Index: 0.03MB
wpiu_comments: Data: 0.02MB + Index: 0.09MB
wpiu_emailTemplate: Data: 0.02MB + Index: 0.00MB
wpiu_failed_jobs: Data: 0.02MB + Index: 0.00MB
wpiu_links: Data: 0.02MB + Index: 0.02MB
wpiu_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wpiu_mpcommision: Data: 0.02MB + Index: 0.00MB
wpiu_mpfeedback: Data: 0.02MB + Index: 0.00MB
wpiu_mpsellerinfo: Data: 0.02MB + Index: 0.00MB
wpiu_mpseller_asktoadmin: Data: 0.02MB + Index: 0.00MB
wpiu_mpseller_meta: Data: 0.02MB + Index: 0.00MB
wpiu_mpseller_orders: Data: 0.02MB + Index: 0.00MB
wpiu_mp_notifications: Data: 0.06MB + Index: 0.00MB
wpiu_options: Data: 5.09MB + Index: 0.23MB
wpiu_postmeta: Data: 8.05MB + Index: 6.91MB
wpiu_posts: Data: 2.08MB + Index: 0.58MB
wpiu_queue: Data: 0.02MB + Index: 0.00MB
wpiu_seller_transaction: Data: 0.02MB + Index: 0.00MB
wpiu_social_users: Data: 0.02MB + Index: 0.02MB
wpiu_termmeta: Data: 0.09MB + Index: 0.09MB
wpiu_terms: Data: 0.05MB + Index: 0.03MB
wpiu_term_relationships: Data: 2.05MB + Index: 1.14MB
wpiu_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wpiu_usermeta: Data: 49.08MB + Index: 39.13MB
wpiu_users: Data: 3.52MB + Index: 4.55MB
wpiu_user_table: Data: 0.02MB + Index: 0.00MB
wpiu_user_table_meta: Data: 0.02MB + Index: 0.00MB
wpiu_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpiu_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpiu_woof_query_cache: Data: 0.02MB + Index: 0.02MB
wpiu_yith_vendors_commissions: Data: 0.02MB + Index: 0.00MB
wpiu_yith_vendors_commissions_notes: Data: 0.02MB + Index: 0.00MB
wpiu_yith_vendors_payments: Data: 0.02MB + Index: 0.00MB
wpiu_yith_vendors_payments_relathionship: Data: 0.02MB + Index: 0.00MB
wpiu_yith_wcdn_desktop_notification: Data: 0.02MB + Index: 0.00MB
wpiu_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wpiu_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wpiu_ylc_chat_rows: Data: 0.02MB + Index: 0.00MB
wpiu_ylc_chat_sessions: Data: 0.02MB + Index: 0.02MB
wpiu_ylc_chat_visitors: Data: 0.02MB + Index: 0.00MB
wpiu_ylc_offline_messages: Data: 0.02MB + Index: 0.00MB
wpiu_ywcars_messagemeta: Data: 0.02MB + Index: 0.00MB
wpiu_ywcars_messages: Data: 0.02MB + Index: 0.00MB

**Comment by mikejolley** [comment] 2018-04-17 18:01
> Regarding the issue, it seems to affect products that are either imported via CSV or the value of the price is generated through custom fields means.

Imported via which plugin/solution? Variable products have 2 _price fields - one for upper price and one for lower price. If the products are not created correctly, via our CRUD system, this meta may be missing. And if thats the case, it's not within our hands to fix.

**Comment by jefreylandicho** [comment] 2018-04-18 02:38
csv is created using woo product import/export feature.
wouldn't be variable price is considered _price ?

product variable is priced with 
- lower and higher price
- same price on all variable
- price with sale price

price are also showing in the backend and frontend

**Comment by mikejolley** [comment] 2018-04-18 09:14
I'd need to see the CSVs. The price sync will be done after import, since the _price fields of the variable product is determined by the children.

**Comment by jefreylandicho** [comment] 2018-04-19 14:46
Hi please see attached file

[test.zip](https://github.com/woocommerce/woocommerce/files/1928573/test.zip)

**Comment by mikejolley** [comment] 2018-04-19 15:39
Those CSVs don't work. Since they lack SKUs I don't think they are mapping to parents correctly so that example is not going to help.

I suspect your import files have affected your sorting. This could occur if for example the product was not synced after import with it's children. Or if children have no price. Or if a child's parent was changed.

Note: variable products have multiple _price, and this is used when sorting to it uses the max/min price during the sort.

Changing the price of a variation within an affect product should trigger the sync and fix the issue for you, unless it's a plugin conflict. We cannot see what else you're running as you didn't provide the full status report.

Confirmed the sync event is queued after saving a variation https://github.com/woocommerce/woocommerce/blob/28a4e88811abd53280cc05f20067ce26e54826e4/includes/abstracts/abstract-wc-product.php#L1341 Also confirmed sorting works after importing the dummy data. Since several over us cannot reproduce this I'm closing the issue. Feel free to reply back if you can give better steps to replicate on a clean install and we'll give it another shot.

Thanks

**Closed by mikejolley** 2018-04-19 15:39 UTC
Labels: Status: Needs Feedback
