### ISSUE TITLE
WooCommerce function not working correctly after moving from the functions.php into a class

### ISSUE THREAD

**Issue by Johnny99211** [woocommerce/woocommerce#26161] opened 2020-04-11 09:05 UTC
First I want to say sorry for asking this question here but I've tried a lot like StackOverflow and WP Forum but I've no other choice. This is a really important customer topic for me and currently I need every job I can get. So I would be very happy if someone knows the problem and how I can fix it.

I've a problem with my child theme. I first had all my stuff and hooks for WooCommerce inside my child themes `function.php` file. Everything worked fine until I moved it into a class which get's loaded with an autoloader. For example I've added custom notices when a user saves the account details page:

```
<?php

namespace App;

defined( 'ABSPATH' ) || exit;

/**
 * Account class
 */
class Account {
    /**
     * @var Account
     */
    private static ?Account $instance = null;

    /**
     * Get instance of class
     *
     * @return Account
     */
    public static function get_instance(): Account {
        if ( self::$instance === null ) {
            self::$instance = new self;
        }

        return self::$instance;
    }

    public function __construct() {
        $this->register();
    }
    private function register(): void {
        add_action( 'woocommerce_save_account_details', [ $this, 'save_edit_account_form' ], 12, 1 );
    }

    /**
     * Save account form
     *
     * @param $user_id int
     */
    public function save_edit_account_form( $user_id ): void {
        wc_clear_notices();
        wc_add_notice( 'Test' ); //Gets no longer displayed anymore

        exit( wp_safe_redirect( wc_get_account_endpoint_url( 'settings' )  ) );
    }
}
```

I'm just loading the class in my `functions.php` file like this:

`Account::get_instance();`

I can verify that the class get's loaded and the hook get's fired. There are no error messages. I'm just expecting the notice output on the account page like it was before I moved the hook and everything into the class.

Also when I work with the non-singleton way like doing `new Account()` in the `functions.php` the hook get's fired but there is no notice displayed in the account.

When I put the hook back into my `functions.php` file of my child theme:

```
add_action( 'woocommerce_save_account_details', 'save_edit_account_form', 12, 1 );
function save_edit_account_form( $user_id ): void {
	wc_clear_notices();
	wc_add_notice( 'Test' );

	wp_safe_redirect( wc_get_account_endpoint_url( 'settings' ) );
	exit;
}
```

The notice get's displayed every time I press the safe button.

But putting everything into my `functions.php` would end in 90000+ lines of code because there are a lot of custom things. Thats why I created classes for a lot of functions and hooks.

Does someone has an idea why this happens? Maybe it's a problem with the `WC()->session` variable?

**Comment by juliaamosova** [comment] 2020-04-28 17:57
Hi @Johnny99211,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed** 2020-05-21 16:32 UTC
