### ISSUE TITLE
Page blank in admin

### ISSUE THREAD

**Issue by bafmin** [woocommerce/woocommerce#24482] opened 2019-08-23 13:41 UTC
**Describe the bug**
All pages in woocommerce admin are blank unless I scroll

**To Reproduce**
1. Go to any page in woocommerce settings
2. Pages loads blank
3. Scroll up or down and the page appears
4. 100% of the time

**Expected behavior**
I expect the page to load like any other page in the admin system

**Comment by uok** [comment] 2019-08-23 15:49
Please state what version of Wordpress and Woo you are using.
Try disabling all plugins except Woo to check for possible conflicts. 
Take a look at PHP/HTTP error log for possible details and errors.

**Comment by kloon** [comment] 2019-08-29 07:49
Please follow the steps as asked initially when you opened the bug report. I am unable to replicate what you describe, so chances are likely this is caused by your theme or another plugin conflicting with WooCommerce.

Test with all plugins disabled except WooCommerce and switch your theme to a default one like Storefront or Twentynineteen and test again. If all works you can then enable plugins one by one testing inbetween to find the offending plugin and then lastly switch your theme back.

Closing this due to insufficient information to reproduce and your troubleshooting instructions. I will gladly reopen the issue if you can provide detailed steps to reproduce this with just WooCommerce and a default theme.

**Closed by kloon** 2019-08-29 07:49 UTC
