### ISSUE TITLE
WooCommerce 3.06 New Account Customer Data Breach Issue

### ISSUE THREAD

**Issue by vandanga** [woocommerce/woocommerce#15096] opened 2017-05-16 09:25 UTC
### EXPLANATION OF THE ISSUE

New customer can see orders placed by an existing customer an My Account/Orders .

### STEPS TO REPRODUCE THE ISSUE

New user uses the account function and enters their email address this allows them access to their account immediately and an email is sent to their email address with account name and password O.K.  If the user then looks at "Orders" they can see previous orders (2) from a different account, and by clicking on the Order No. the can see all the details of the order including the personal details of that account.  This is a Data Breach issue.  This happened all day yesterday with new customers and my testing on the live site.
All Plugins and Themes are uptodate.
I noticed that Excel-Like Product Manager for WooCommerce and WP E-commerce: by Holest Engineering was not up todate and doesn't seem to up date through the plugin interface but through the help website with a download. I have deleted the old version and up dated to version – 2.0.91 with a plugin upload.
Then having tried to recreate the issue late last nigh and this morning it seems to have resolved and I get a No order has been made yet message.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://stedall.co.uk
Site URL: https://stedall.co.uk
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

LayerSlider WP: by Kreatura Media – 6.4.0
Child Theme Configurator: by Lilaea Media – 2.2.4.1
Excel-Like Product Manager for WooCommerce and WP E-commerce: by Holest Engineering – 2.0.91
IgniteWoo Updater: by IgniteWoo.com – 2.1.9
Max Mega Menu - Pro Addon: by Tom Hemsley – 1.6.2.1
Max Mega Menu: by Tom Hemsley – 2.3.6
news ticker benaceur: by benaceur – 2.5.5
Pootle Pagebuilder (Premium): by Pootlepress – 4.0.0
Projects: by WooThemes – 1.5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
Cookie Consent: by Catapult_Themes – 2.3.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.13.1.21

WooCommerce Address Validation: by SkyVerge – 2.1.0
WooCommerce Customizer: by SkyVerge – 2.4.0
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Email Validation: by Hugh Lashbrooke – 2.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.2
WooCommerce Live Search: by IgniteWoo.com – 2.3.1
WooCommerce Product Archive Customiser: by jameskoster – 1.0.5
WooCommerce: by Automattic – 3.0.6
WooDojo: by WooThemes – 1.5.4
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.8
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.7.1
WPFront Scroll Top: by Syam Mohan – 1.5
WPFront User Role Editor: by Syam Mohan – 2.13.1
YITH Maintenance Mode: by YITHEMES – 1.3.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)


### WC Pages ###

Shop base: #6 - /products/
Cart: #7 - /cart/
Checkout: #3112 - /checkout-2/
My account: #3113 - /my-account-2/

### Theme ###

Name: Stedall
Version: 1.0.1486986687
Author URL: http://freestonedesign.co.uk
Child Theme: ✔
Parent Theme Name: Canvas
Parent Theme Version: 5.11.4
Parent Theme Author URL: http://www.woothemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: Stedall/content-product.php
`
```
</details>

**Comment by mikejolley** [comment] 2017-05-16 10:58
There is no core issue here I can see; the account page is only showing orders from my logged in user on my test site.

You can see the query used here: https://github.com/woocommerce/woocommerce/blob/master/templates/myaccount/my-orders.php#L20-L26 

I suggest you run tests with no other plugins active and a different theme AND ensure the account page is not being cached by either a plugin, server side cache or other.

Closing as this is not reproducible on a clean install and has had no other reports. Feel free to comment back if you narrow the issue down but it looks to be specific to your site.

-- 

O and if you're talking about the backend 'orders' screen, customers do not have access to that panel. `manage_woocommerce` capability is required which is given to admin only by default.

Thanks

**Closed by mikejolley** 2017-05-16 10:58 UTC

**Comment by vandanga** [comment] 2017-05-16 11:25
I dont’ quit understand as the template you refer to says depreciated in the third line and shortcake orders.php is now used.
Even after I updated the Excel-Like Product Manager plugin I managed to recreate the problem once. But now I can’t and I haven’t done anything to the site since.

We do have a dev. site for this live site with exactly the same theme and plugins and could not recreate it there last night.
Very strange

I attach screen grab of orders screen associated with new account creation.  There should not have been any orders associated.

**Comment by mikejolley** [comment] 2017-05-16 11:28
The more up to date query is here https://github.com/woocommerce/woocommerce/blob/e92b93f99221f705805dd438b11f3bebeac903d2/includes/wc-template-functions.php#L2287

> I attach screen grab of orders screen associated with new account creation.  There should not have been any orders associated.

if the user signs up with an email address which has guest orders associated with it, they will be linked.

**Comment by vandanga** [comment] 2017-05-16 11:39
I understand that but they didn’t, and the one I created yesterday was a test one and not used on the site before.
As it was a live site is difficult to shut everything off but I did check and the orders associated with the new account had no connection, email address or username.

**Comment by mikejolley** [comment] 2017-05-16 11:48
Then I suggest you look into caching etc.

**Comment by vandanga** [comment] 2017-05-16 16:29
What caching are you referring to. Browser or site. We don’t have site cache running.
The problem occurred on more than one computer and IP address so it’s not a local cache.

**Comment by mikejolley** [comment] 2017-05-16 16:41
Server side caching.

**Comment by vandanga** [comment] 2017-05-16 16:50
I can’t see how caching is the issue as it was across different new accounts and existing accounts and orders getting mixed up.
We did have CloudFlair running on this account but turned it off some months ago.

I did query the problem with our hosting company yesterday and was told there wasn’t a problem there and I also checked the html logs and didn’t see an issue that day.
I’m just trying to understand where the issue might be.

**Comment by mikejolley** [comment] 2017-05-16 16:52
If it caches a logged in users account page, that could then be shown to another. It's not common but I've seen it happen before.

Anyhow, that was just one of my suggestions. Since core itself and other installs are not affected you'll need to look into this yourself.

**Comment by vandanga** [comment] 2017-05-16 17:06
I hope it’s not the core.  Tat was my main concern.
To me it’s a database issue as the orders page is picking up records from another user.
Let hope it doesn’t re-appear.

Thanks anyhow.
