### ISSUE TITLE
Force WC cookies to be SameSite=None;Secure?

### ISSUE THREAD

**Issue by flamingtop** [woocommerce/woocommerce#27331] opened 2020-08-14 01:12 UTC
Is there a way to force woocommerce cookies to have SameSite=None;Secure? Asking because my site must share state with a 3rd party shipping service which takes the customer out of my site temporarily and let him pick shipping address then return to my site. I need share woocommerce state with this 3rd party service. Right now all the WC cookies seems to have no specific SameSite values which will defaults to Lax, this prevents my site to interact with the 3rd party shipping service.

**Comment by juliaamosova** [comment] 2020-08-14 23:07
Hi @flamingtop,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-08-14 23:07 UTC
