### ISSUE TITLE
Cart not updating

### ISSUE THREAD

**Issue by Fribik** [woocommerce/woocommerce#25704] opened 2020-02-19 00:28 UTC
Hello,
i have proble at my website https://rumble.cz/ when you somenting add to card, and after add something else, cart is not updating, when you add more pcs at card and click to update cart, cart is again not update. You can try it at my website https://rumble.cz/
Thank for help.

**Comment by tammullen** [comment] 2020-02-19 01:14
Hi @Fribik 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-02-19 01:14 UTC
