### ISSUE TITLE
Variations created from identical attribute values only show one of the variations on the front end.

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce#29983] opened 2021-05-25 13:06 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Variations created from identical attribute values only show one of the variations in the dropdown on the front end.

Not sure if this is even supposed to work.

**Expected behavior**
Even with identical variation (attribute value) names, all existing variations should appear in the dropdown.

**Actual behavior**
Only one of the variations is displayed.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Variable product - create a custom attribute with two identical values https://d.pr/i/Y4gdst
2. Create variations from those: https://d.pr/i/kWvMTH
3. See the product page - only one variation in the dropdown: https://d.pr/i/Hrnp08

**Screenshots**
https://d.pr/i/Y4gdst
https://d.pr/i/kWvMTH
https://d.pr/i/Hrnp08

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
Irrelevant, but let me know if it's necessary and I'll add it.
```
</details>

**Comment by rodelgc** [comment] 2021-05-25 14:53
Hi @grig-23,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I set two identical variations in Admin:
<img width="1022" alt="Screen Shot 2021-05-25 at 10 47 08 PM" src="https://user-images.githubusercontent.com/4509348/119519407-f9076200-bdab-11eb-9118-5274406f5060.png">

And when I looked at the customer side, I only see one of them:
<img width="794" alt="Screen Shot 2021-05-25 at 10 49 23 PM" src="https://user-images.githubusercontent.com/4509348/119519488-0b819b80-bdac-11eb-90f1-07b58a95552c.png">


We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment] 2023-10-25 20:01
> Not sure if this is even supposed to work.

@grig-23 No, this is not supposed to work. I'm closing this as a question. If you have a valid use case where identical variation should all be shown, pleas open a new issue as an enhancement and explain the use case.

**Closed by rrennick** 2023-10-25 20:01 UTC
Labels: type: bug, priority: low, focus: variation [team:Proton], focus: product [team:Mothra], type: question, plugin: woocommerce
