### ISSUE TITLE
Woocommerce Subscription: shipping charges according to the number of deliveries

### ISSUE THREAD

**Issue by Aparajita591** [woocommerce/woocommerce#26098] opened 2020-04-07 12:20 UTC
I need help with: WooCommerce Subscriptions Plugin

Hi, We want to apply the shipping charges on the basis of the number of deliveries. We have added the following code in functions.php for this:

function custom_calculated_shipping() {
    global $woocommerce;
    $attribute_term_pricing = '';
    $cart_contents = '';
    $custom_shipping = 1;
    if (isset($woocommerce->cart->cart_contents) && !empty($woocommerce->cart->cart_contents)) {
        $cart_contents = $woocommerce->cart->cart_contents;
        foreach ($cart_contents as $cart_content) {
            if (isset($cart_content['variation']['attribute_pa_term_pricing']) && $cart_content['variation']['attribute_pa_term_pricing'] != '') {
                $attribute_term_pricing = $cart_content['variation']['attribute_pa_term_pricing'];
            }
        }
        if(isset($attribute_term_pricing) && $attribute_term_pricing != ''){
            if(stripos($attribute_term_pricing,'3') !== FALSE){
                $custom_shipping = 3;
            }else if(stripos($attribute_term_pricing,'6') !== FALSE){
                $custom_shipping = 6;
            }else if(stripos($attribute_term_pricing,'12') !== FALSE){
                $custom_shipping = 12;
            }
        }
    }
    return $custom_shipping;
}

add_filter( 'woocommerce_package_rates', 'custom_shipping_rate_cost_calculation', 10, 2 );
function custom_shipping_rate_cost_calculation( $rates, $package ) {
    foreach( $rates as $rate_key => $rate ) {
        if ( 'flat_rate' === $rate->method_id ){

            // Get rate cost and Custom cost
            $initial_cost = $rates[$rate_key]->cost;
            $additional_cost = custom_calculated_shipping();

            // Calculation
            $new_cost = $initial_cost * $additional_cost;
            // Set Custom rate cost
            $rates[$rate_key]->cost = round($new_cost, 2);

            // Taxes rate cost (if enabled)
            $new_taxes = array();
            $has_taxes = false;
            foreach ( $rate->taxes as $key => $tax ){
                if( $tax > 0 ){
                    // Calculating the tax rate unit
                    $tax_rate = $tax / $initial_cost;
                    // Calculating the new tax cost
                    $new_tax_cost = $tax_rate * $new_cost;
                    // Save the calculated new tax rate cost in the array
                    $new_taxes[$key] = round( $new_tax_cost, 2 );
                    $has_taxes = true;
                }
            }
            // Set new tax rates cost (if enabled)
            if( $has_taxes )
                $rate->taxes = $new_taxes;
        }
    }

    return $rates;
}

But we are facing an issue that it is giving correct result for Shipping Charges but for recurring shipping charges, it is not giving the correct result.

For example, if the shipping charge for 1 delivery is - 2GBP, then for 3 deliveries it will be 2 * 3 = 6GBP. But the recurring shipping charges are coming as 6 * 3 = 18GBP but it should be 6GBP only.

Can anyone please check this?

**Comment by juliaamosova** [comment] 2020-04-10 21:33
Hi @Aparajita591,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The question you have is related to the WooCommerce Subscriptions plugin which is one of the paid products on our marketplace. This plugin is also being developed by another team. 

I recommend you make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/) in order to get further help with your question. 

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-04-10 21:33 UTC
