### ISSUE TITLE
Multilingual Variable Products

### ISSUE THREAD

**Issue by pascalknecht** [woocommerce/woocommerce#21872] opened 2018-11-09 12:49 UTC
Variable Products fail to render on detail page on multilingual installations when having special characters (Ö, Ä, Ü).

1. Install Multilingual Plugin (Polylang in our case)
2. Create a multilingual product
3. Create an attribute which has a special character Ö in it
4. Variation selection will not be usable

**Expected behavior**
Variation select should work.

**Debug information**
The variation dropdown does not work as the Ö is changed to oe in German but to o in English. See code here: https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L1934

**Proposed solution**
Don't rely on sanitize_title to create important selectors as it has some unintended side-effects.

**Comment by kloon** [comment] 2018-11-15 10:57
Can you replicate this without the multilingual plugin?

I tested this with just WooCommerce and it works fine for me http://cld.wthms.co/b9l0rd and http://cld.wthms.co/3J9dYM

The issue is most likely with the multilingual plugin, I suggest you contact them for support on this.

Closing as I am not able to reproduce.

**Closed by kloon** 2018-11-15 10:57 UTC
