### ISSUE TITLE
Blank page in Edit order page

### ISSUE THREAD

**Issue by simonaluka** [woocommerce/woocommerce#29501] opened 2021-03-25 18:55 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

Hi, when using WooCommerce orders, i press to edit order it goes as a blank page and does not allow me to see or do anything. Pls help
![Edit order](https://user-images.githubusercontent.com/81384629/112527987-48c9ad00-8dac-11eb-85a3-83a8d09bbbaa.png)
![Order 1](https://user-images.githubusercontent.com/81384629/112527990-49fada00-8dac-11eb-968d-f9cc9119437d.png)
![Order 1](https://user-images.githubusercontent.com/81384629/112527996-4bc49d80-8dac-11eb-9567-807aeef9d546.png)
![Edit order](https://user-images.githubusercontent.com/81384629/112527997-4bc49d80-8dac-11eb-85d3-70686124016f.png)

### WordPress Environment ###

WordPress address (URL): https://www.sveikasdumas.lt
Site address (URL): https://www.sveikasdumas.lt
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: lt_LT
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.3.27
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.75.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Bendras duomenų bazės dydis: 13.07MB
Duomenų bazės duomenų dydis: 11.26MB
Duomenų bazės indekso dydis: 1.81MB
wp_woocommerce_sessions: Duomenys: 1.52MB + Indeksas: 0.02MB + Variklis InnoDB
wp_woocommerce_api_keys: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_woocommerce_attribute_taxonomies: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_woocommerce_downloadable_product_permissions: Duomenys: 0.02MB + Indeksas: 0.17MB + Variklis InnoDB
wp_woocommerce_order_items: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_woocommerce_order_itemmeta: Duomenys: 0.05MB + Indeksas: 0.05MB + Variklis InnoDB
wp_woocommerce_tax_rates: Duomenys: 0.02MB + Indeksas: 0.08MB + Variklis InnoDB
wp_woocommerce_tax_rate_locations: Duomenys: 0.02MB + Indeksas: 0.05MB + Variklis InnoDB
wp_woocommerce_shipping_zones: Duomenys: 0.02MB + Indeksas: 0.00MB + Variklis InnoDB
wp_woocommerce_shipping_zone_locations: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_woocommerce_shipping_zone_methods: Duomenys: 0.02MB + Indeksas: 0.00MB + Variklis InnoDB
wp_woocommerce_payment_tokens: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_woocommerce_payment_tokenmeta: Duomenys: 0.02MB + Indeksas: 0.05MB + Variklis InnoDB
wp_woocommerce_log: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_actionscheduler_actions: Duomenys: 0.06MB + Indeksas: 0.11MB + Variklis InnoDB
wp_actionscheduler_claims: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_actionscheduler_groups: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_actionscheduler_logs: Duomenys: 0.05MB + Indeksas: 0.03MB + Variklis InnoDB
wp_commentmeta: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_comments: Duomenys: 0.02MB + Indeksas: 0.09MB + Variklis InnoDB
wp_links: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_mc_banklinks: Duomenys: 0.02MB + Indeksas: 0.00MB + Variklis InnoDB
wp_options: Duomenys: 7.02MB + Indeksas: 0.06MB + Variklis InnoDB
wp_postmeta: Duomenys: 0.34MB + Indeksas: 0.19MB + Variklis InnoDB
wp_posts: Duomenys: 1.48MB + Indeksas: 0.06MB + Variklis InnoDB
wp_termmeta: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_terms: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_term_relationships: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_term_taxonomy: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_usermeta: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_users: Duomenys: 0.02MB + Indeksas: 0.05MB + Variklis InnoDB
wp_wc_admin_notes: Duomenys: 0.02MB + Indeksas: 0.00MB + Variklis InnoDB
wp_wc_admin_note_actions: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_wc_category_lookup: Duomenys: 0.02MB + Indeksas: 0.00MB + Variklis InnoDB
wp_wc_customer_lookup: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_wc_download_log: Duomenys: 0.02MB + Indeksas: 0.05MB + Variklis InnoDB
wp_wc_order_coupon_lookup: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_wc_order_product_lookup: Duomenys: 0.02MB + Indeksas: 0.06MB + Variklis InnoDB
wp_wc_order_stats: Duomenys: 0.02MB + Indeksas: 0.05MB + Variklis InnoDB
wp_wc_order_tax_lookup: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB
wp_wc_product_meta_lookup: Duomenys: 0.02MB + Indeksas: 0.09MB + Variklis InnoDB
wp_wc_reserved_stock: Duomenys: 0.02MB + Indeksas: 0.00MB + Variklis InnoDB
wp_wc_tax_rate_classes: Duomenys: 0.02MB + Indeksas: 0.02MB + Variklis InnoDB
wp_wc_webhooks: Duomenys: 0.02MB + Indeksas: 0.03MB + Variklis InnoDB

### Post Type Counts ###

attachment: 76
customize_changeset: 35
nav_menu_item: 7
page: 15
post: 2
product: 36
revision: 102
shop_order: 22

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Futurio Extra: autorius FuturioWP – 1.4.4
"LP Express" Shipping Method for WooCommerce: autorius Martynas Žaliaduonis – 1.0.6
MakeCommerce for WooCommerce: autorius Maksekeskus AS – 2.6.2
Omniva siuntimas: autorius Omniva – 1.6.2
WooCommerce: autorius Automattic – 5.1.0

### Inactive Plugins (3) ###

Montonio for WooCommerce: autorius Montonio – 2.3.0
MultiParcels Shipping For WooCommerce: autorius MultiParcels – 1.12
WooCommerce Payment Gateway - Paysera: autorius Paysera – 2.6.2

### Must Use Plugins (1) ###

installatron_hide_status_test.php: autorius  –

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Parduotuvės bazė: #48 - /parduotuve/
Krepšelis: #49 - /krepselis/
Apmokėjimas: #50 - /apmokejimas/
Paskyra: #51 - /paskyra/
Pirkimo taisyklės ir sąlygos: #131 - /taisykles-ir-salygos/

### Theme ###

Name: Futurio
Version: 1.4.0
Author URL: https://futuriowp.com/about/
Child Theme: ❌ – Jei keičiate WooCommerce veikimą per tėvinę temą
kurios kūrėjas nesate Jūs pats
rekomenduojame naudoti potemes. Daugiau infomacijos: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Jūsų temoje yra failas woocommerce.php
todėl Jūs negalėsite perrašyti šablono woocommerce/archive-product.php Taip yra todėl
kad woocommerce.php turi prioritetą lyginant su archive-product.php. Ši taisyklė leidžia išvengti klaidų.

Overrides: futurio/woocommerce/emails/customer-processing-order.php

### Action Scheduler ###

Įvykdytas: 104
Oldest: 2021-03-05 08:49:37 +0000
Newest: 2021-03-25 18:41:29 +0000

### Status report information ###

Generated at: 2021-03-25 18:44:48 +00:00
`

**Comment by tammullen** [comment] 2021-03-26 14:57
Hi @simonaluka 

Thank you for raising the issue. However, I can’t reproduce it on my end.

![Screenshot 2021-03-26 at 14 51 36](https://user-images.githubusercontent.com/24649833/112650721-93e2cf00-8e43-11eb-9707-7c5d28eefa0b.png)


I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2021-04-02 19:10
Hi @simonaluka,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-04-02 19:10 UTC
Labels: category: can't reproduce, needs feedback

**Comment by simonaluka** [comment] 2021-04-02 20:26
Hi,

Sorry for not coming back! The issue was with The plugin, thanks for
checking, it is resolved now

Regards,
Simona

2021 m. bal. 2 d., pn 22:10, Julia Amosova ***@***.***> rašė:
