### ISSUE TITLE
Helper merge to core should preserve active license(s) connected 

### ISSUE THREAD

**Issue by msdesign21** [woocommerce/woocommerce#15709] opened 2017-06-20 22:42 UTC
## Steps to reproduce the issue

1. Have Woo products active and connected with the old helper
2. Upgrade to WooCommerce 3.1 
3. Go to WooCommerce > Extensions > "WooCommerce.com Subscriptions"
4. Notice that the products you previously had connected are now inactive.  

It's not ideal that all WooCommerce users would need to go in and reconnect their licenses that were already connected on their site. Particularly since there is no prompt letting people know that the Helper management has moved into core. 

## Expected behavior and actual behavior

When I follow those steps, I see...

<img src="http://cld.wthms.co/7JsVxZ+"/>

Those two products at the bottom were previously connected. 

I was expecting...

The extensions that I previously had connected to remain connected. 

## Environment

<details>
```
http://cld.wthms.co/4kAqpG
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)

**Comment by WPprodigy** [comment] 2017-06-21 02:11
@msdesign21 Do you know what version (beta or RC?) of WooCommerce you were running when testing?

The master branch should have this resolved: https://github.com/woocommerce/woocommerce/pull/15519/commits/465285144b0e88aaa66d09be17803850a08ee748

**Comment by msdesign21** [comment] 2017-06-21 18:37
Looks like that commit was 11 days ago. I downloaded the master from here yesterday. cc @kovshenin

**Comment by jeffstieler** [comment] 2017-06-21 23:06
I can confirm the behavior @msdesign21 is seeing - on current `master`:

<img width="1111" alt="screen shot 2017-06-21" src="https://user-images.githubusercontent.com/63922/27410287-e1556634-56a3-11e7-858e-873bf7be9dba.png">

<img width="1254" alt="screen shot 2017-06-21" src="https://user-images.githubusercontent.com/63922/27410292-eaacc3a8-56a3-11e7-8dcb-fa6633a3510d.png">

**Comment by WPprodigy** [comment] 2017-06-21 23:44
Did you have to reconnect to your WooCommerce/WordPress.com account after the update?

I think the last PR was focused on keeping the connection there. Now it just seems the issue is that the plugins don't stay `active`.

**Comment by msdesign21** [comment] 2017-06-22 05:40
Our accounts remained connected. Just the subscriptions that were previously active were inactive upon updating.

**Comment by kloon** [comment] 2017-06-22 09:20
@msdesign21 curious if the key you entered belonged to your or was it someone else's key?

**Comment by kloon** [comment] 2017-06-22 11:05
Just an update, this should be fixed in an upcoming PR.

**Comment by msdesign21** [comment] 2017-06-22 15:56
@kloon I was using Brian's account to test. So the key belonged to the account it was connected to

**Closed** 2017-06-23 12:22 UTC
Labels: Status: has-pr, Status: Needs Review, Type: Enhancement
