### ISSUE TITLE
Problem with search

### ISSUE THREAD

**Issue by RiKaZaRai** [woocommerce/woocommerce#24230] opened 2019-07-25 13:45 UTC
**Describe the bug**
I have problem with search. Don't possible to search with order number, email, name...

**To Reproduce**
1. Go to woocommerce
2. Go to orders
2. complete search with number
3. click "search"

**Screenshots**
I had a screenshots 
[problème recherche.pdf](https://github.com/woocommerce/woocommerce/files/3431828/probleme.recherche.pdf)

**Comment by RiKaZaRai** [comment] 2019-07-25 14:28
I  found. This problem comes from Modern Event Calendar after the last upgrade (Version 4.4.0)
I put the problem together Webmus

**Comment by rodrigoprimo** [comment] 2019-07-30 22:47
Closing as, if I understood correctly, after opening the issue you realized that it is caused by another plugin and this issue tracker is used only for WooCommerce core problems. Please let me know if I misunderstood something.

**Closed by rodrigoprimo** 2019-07-30 22:47 UTC
