### ISSUE TITLE
[3.9] Backend orders setting unused tax rate to 0.00

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#25463] opened 2020-01-22 11:29 UTC
**Describe the bug**
When creating a backend order with multiple tax rates, the tax amounts for rates that are not used on a product are set to 0.00 - this is incorrect because 0.00 tax (which could be a 0% rate) is not the same as **no** tax. This is also inconsistent with frontend orders, which only set the tax amounts for tax rates that are applicable to a product (= the correct way).

**To Reproduce**
1. Create a frontend order with 2 products with different tax rates
2. Create a backend order with the same products
3. Compare `_line_tax_data` of the items in both orders: The frontend order only has the applicable rate set for each product, the backend order has also set the tax rate of the non-applicable rate (to i:0).

**Expected behavior**
Tax amounts (whether zero or not) should only be set for applicable tax rates.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment] 2020-01-23 09:38
Hi, I tried to reproduce this by adding two tax rates based on location and creating a manual order. I only see 1 tax rate applied in the backend data as it should: `a:2:{s:5:"total";a:1:{i:1;s:5:"34.73";}s:8:"subtotal";a:1:{i:1;s:5:"34.73";}}`. 

Can you please provide more details about your tax setup? Specifically how the two rates are added, and how the product is configured to be applied only one rate to help us reproduce the problem. Screenshots of tax rates, tax settings and product detail setting would be great if possible.

**Comment by Spreeuw** [comment] 2020-01-23 10:03
Yes I can do that.
Here is the tax setting for the reduced rate product:
![25463-product-reduced](https://user-images.githubusercontent.com/3217773/72973964-81e44700-3dce-11ea-91c1-4009745d5281.png)
and the tax rate itself:
![25463-tax-reduced](https://user-images.githubusercontent.com/3217773/72973990-8b6daf00-3dce-11ea-8853-7242eb2193a8.png)

and the standard rate product:
![25463-product-standard](https://user-images.githubusercontent.com/3217773/72974010-96c0da80-3dce-11ea-8471-40b0a63f5479.png)

and the rate itself:
![25463-tax-standard](https://user-images.githubusercontent.com/3217773/72974025-9cb6bb80-3dce-11ea-8617-730a25310a45.png)

Note that I am only adding BOTH products to the order, I am not adding tax rates manually - I let this be applied by the 'recalculate' button.

Interestingly it seems the backend displaying is inconsistent too... While viewing a frontend order that has only set the applicable rates set (so no 0.00 here), it still shows 0.00 for the products while the shipping row correctly shows '-' as not being set:
![25463-3 9-price-backend](https://user-images.githubusercontent.com/3217773/72974332-1babf400-3dcf-11ea-9f43-bb6a72b1c8ae.png)

Viewing the **same** order in 3.8 correctly represents the data:
![25463-3 8-price-backend](https://user-images.githubusercontent.com/3217773/72974796-f370c500-3dcf-11ea-98d3-4a4be8364834.png)

And viewing a 3.9 manual backend order in 3.8 clearly shows the 0.00 set:
![25463-3 8-price-backend-manual](https://user-images.githubusercontent.com/3217773/72974825-071c2b80-3dd0-11ea-8f7b-c89db502d4df.png)

**Comment by vedanshujain** [comment] 2020-01-23 11:01
Thanks for the screenshot, I can reproduce on my end using the settings you provided. I am investigating this now and should have a fix soonish.

**Comment by Spreeuw** [comment] 2020-01-23 11:39
Can you tell my why this is set to priority low and 3.10.0? This seems like a pretty serious bug to me (not a feature that should be postponed for a release). This creates invalid tax data for all manual orders.

**Comment by vedanshujain** [comment] 2020-01-23 12:16
@Spreeuw I marked it a low priority because as far as I can see this seems to be a presentation bug, nothing in the database is actually changed. I have raised #25472 to fix. Also, we have changed how we release so the next one is actually scheduled pretty quick for early March if all goes as planned.

**Comment by Spreeuw** [comment] 2020-01-23 12:36
It is **not** a representation bug, the tax data is incorrect. In 3.9 it stores an amount of $0.00 instead of `NULL` or ''. Fiscally these are very different things, and all these orders will need to be corrected - the longer this takes the more orders will have to be fixed and I think 2 months worth of incorrect tax data is a serious issue.

**Comment by Spreeuw** [comment] 2020-01-23 19:36
@vedanshujain to better illustrate why this is not simply a presentation bug, consider the scenario where an order has both a 0% rate and 21% rate applied to different products. In WooCommerce 3.9 manual orders there is no way to determine which items have the 0% rate (after the order has been created) because they _all_ have the 0% rate set in the `_line_tax_data`.

**Comment by vedanshujain** [comment] 2020-01-24 07:39
I would prefer not doing a fix release for this bug alone because, in a normal release cycle, testing is much more extensive than in a fix release. cc'ing @woocommerce/proton for the second opinion in case I am underestimating the severity of this bug.

That said, you can apply changes in #25472 in your install as a workaround till this patch gets included in a release.

**Comment by peterfabian** [comment] 2020-01-24 09:32
Adjusted the priority to high as it affects also orders created on the front end, but later updated on the backend (e.g. when updating status). Also, 0 tax and no tax are quite different beasts, especially when it comes to VAT. 
We're evaluating pushing a fix release out.

**Comment by claudiosanches** [comment] 2020-01-28 16:09
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25472.

**Closed by claudiosanches** 2020-01-28 16:09 UTC
Labels: bug, has pull request, priority: high
