### ISSUE TITLE
WooCommerce Slack Extension - Hourly report of orders statuses

### ISSUE THREAD

**Issue by Thonk-Steve** [woocommerce/woocommerce#26940] opened 2020-07-02 15:44 UTC
One problem i've found with moving my workforce to remote working and shifts during Covid-19 is that it's really easy for people to lose sight of simply how many processing orders there are. Any store owner knows this is the key minute to minute metric!

For security reasons we prefer people to not log into our woocomm website or the mobile app when outside our business network.

However if the Slack application had an option to publish say an hourly status update of which order statuses have changed since the last update, it might populate a Slack channel with something like:

**17:00** - Processing (**127**) On Hold (**2**) Pending Payment (**4**)
**18:00** - Processing (**136**) On Hold (**1**) Pending Payment (**1**)
**19:00** - Processing (**165**)

**Comment by Thonk-Steve** [comment] 2020-07-02 15:46
Then that would be amazingly useful and a secure way for my team to check the status.

**Comment by tammullen** [comment] 2020-07-02 20:08
Hi @Thonk-Steve 

Have a look at the [WooCommerce Slack](https://woocommerce.com/products/woocommerce-slack/) plugin. It might help with what you are after.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-07-02 20:08 UTC

**Comment by Thonk-Steve** [comment] 2020-07-02 22:06
Hi @tammullen yes I already have and use this plugin but it has no features to post order status updates as requested. 

I contacted support on Woocommerce.com and in the support chat was told:

> WP.com Thu, Jul 2, 3:37 PM
> You can post it as an enhancement request to the GitHub WooCommerce: https://github.com/woocommerce/woocommerce/issues
