### ISSUE TITLE
Problemi con gli apostrofi '

### ISSUE THREAD

**Issue by Sam9999it** [woocommerce/woocommerce#21492] opened 2018-10-03 17:19 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Durante la ricerca e quindi l trattamento dei prodotti in area amministrativa se nella ricerca c'è un apotrofo come in "dell'unione" "dell'angelo" la ricerca funziona ma i risultati sono messi con non tutti i dati dei prodotti (es. non si vedono le immagini) poi andando avanti si ha anche errore e si arriva al puo che se clicchi ti dice "non sei abilitato ad avere accesso a questa cartella" oppure "accesso negato"

**To Reproduce**
1. Go to ricerca prodotti
2. Click on ricerca un prodotto con all'interno un apostrofo '
3. Scroll down to vai al prodotto o altro nelal ricerca.

**Screenshots**
https://rituali.ga/banners/Istantanea_2018-10-03_19-13-50.png
https://rituali.ga/banners/Istantanea_2018-10-03_19-14-01.png

**Expected behavior**
Mi aspetto che le ricerche rendano i risultati e che siano clicabili per la modifica e l'uso normale.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://magiko.biz
Site URL: https://magiko.biz
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.10-0ubuntu0.18.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 36
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Il tuo server non ha la classe SoapClient attiva - alcuni plugin gateway che usano SOAP potrebbero non funzionare correttamente.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: avwp_
MaxMind GeoIP Database: ✔
Dimensione totale database: 92.49MB
Dimensione dati database: 85.04MB
Dimensione indice database: 7.45MB
avwp_woocommerce_sessions: Dati: 69.33MB + Indice: 1.43MB
avwp_woocommerce_api_keys: Dati: 0.00MB + Indice: 0.00MB
avwp_woocommerce_attribute_taxonomies: Dati: 0.00MB + Indice: 0.01MB
avwp_woocommerce_downloadable_product_permissions: Dati: 0.00MB + Indice: 0.00MB
avwp_woocommerce_order_items: Dati: 0.01MB + Indice: 0.01MB
avwp_woocommerce_order_itemmeta: Dati: 0.07MB + Indice: 0.06MB
avwp_woocommerce_tax_rates: Dati: 0.00MB + Indice: 0.01MB
avwp_woocommerce_tax_rate_locations: Dati: 0.00MB + Indice: 0.00MB
avwp_woocommerce_shipping_zones: Dati: 0.00MB + Indice: 0.00MB
avwp_woocommerce_shipping_zone_locations: Dati: 0.00MB + Indice: 0.01MB
avwp_woocommerce_shipping_zone_methods: Dati: 0.00MB + Indice: 0.00MB
avwp_woocommerce_payment_tokens: Dati: 0.00MB + Indice: 0.00MB
avwp_woocommerce_payment_tokenmeta: Dati: 0.00MB + Indice: 0.00MB
avwp_woocommerce_log: Dati: 0.00MB + Indice: 0.00MB
avwp_adtribes_my_conversions: Dati: 0.02MB + Indice: 0.02MB
avwp_affiliates_banners_tbl: Dati: 0.00MB + Indice: 0.00MB
avwp_affiliates_clickthroughs_tbl: Dati: 0.02MB + Indice: 0.00MB
avwp_affiliates_payouts_tbl: Dati: 0.00MB + Indice: 0.00MB
avwp_affiliates_sales_tbl: Dati: 0.00MB + Indice: 0.00MB
avwp_affiliates_tbl: Dati: 0.00MB + Indice: 0.00MB
avwp_aff_affiliates: Dati: 0.00MB + Indice: 0.00MB
avwp_aff_affiliates_users: Dati: 0.00MB + Indice: 0.00MB
avwp_aff_hits: Dati: 0.00MB + Indice: 0.00MB
avwp_aff_referrals: Dati: 0.00MB + Indice: 0.00MB
avwp_aff_robots: Dati: 0.00MB + Indice: 0.00MB
avwp_awpcp_adfees: Dati: 0.00MB + Indice: 0.00MB
avwp_awpcp_admeta: Dati: 0.00MB + Indice: 0.00MB
avwp_awpcp_ads: Dati: 0.01MB + Indice: 0.01MB
avwp_awpcp_ad_regions: Dati: 0.00MB + Indice: 0.01MB
avwp_awpcp_categories: Dati: 0.00MB + Indice: 0.00MB
avwp_awpcp_credit_plans: Dati: 0.00MB + Indice: 0.00MB
avwp_awpcp_media: Dati: 0.02MB + Indice: 0.00MB
avwp_awpcp_payments: Dati: 0.01MB + Indice: 0.00MB
avwp_awpcp_tasks: Dati: 0.00MB + Indice: 0.00MB
avwp_captcha_booster: Dati: 0.13MB + Indice: 0.00MB
avwp_captcha_booster_meta: Dati: 1.52MB + Indice: 0.00MB
avwp_cf7dbplugin_st: Dati: 0.00MB + Indice: 0.00MB
avwp_cf7dbplugin_submits: Dati: 0.00MB + Indice: 0.00MB
avwp_cleantalk_sfw: Dati: 0.00MB + Indice: 0.00MB
avwp_commentmeta: Dati: 0.00MB + Indice: 0.01MB
avwp_comments: Dati: 0.05MB + Indice: 0.03MB
avwp_contact_form_7: Dati: 0.00MB + Indice: 0.00MB
avwp_gdbc_attempts: Dati: 0.08MB + Indice: 0.02MB
avwp_links: Dati: 0.00MB + Indice: 0.00MB
avwp_loginizer_logs: Dati: 0.00MB + Indice: 0.01MB
avwp_loginradius_custom_object_data: Dati: 0.00MB + Indice: 0.00MB
avwp_lrgawidget_global_settings: Dati: 0.02MB + Indice: 0.00MB
avwp_lr_addresses: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_albums: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_basic_profile_data: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_certifications: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_companies: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_contacts: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_courses: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_current_status: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_custom_fields_data: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_education: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_emails: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_extended_location_data: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_extended_profile_data: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_facebook_events: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_facebook_likes: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_facebook_posts: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_favorites: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_groups: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_imaccounts: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_inspirational_people: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_languages: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_linkedin_companies: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_patents: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_phone_numbers: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_popup_custom_fields_data: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_popup_custom_fields_dropdown: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_popup_custom_fields_map: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_positions: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_recommendations_received: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_skills: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_sports: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_status: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_twitter_mentions: Dati: 0.00MB + Indice: 0.00MB
avwp_lr_volunteer: Dati: 0.00MB + Indice: 0.00MB
avwp_messages: Dati: 0.00MB + Indice: 0.00MB
avwp_options: Dati: 1.52MB + Indice: 0.13MB
avwp_participants_database: Dati: 0.01MB + Indice: 0.00MB
avwp_participants_database_fields: Dati: 0.00MB + Indice: 0.00MB
avwp_participants_database_groups: Dati: 0.00MB + Indice: 0.00MB
avwp_postmeta: Dati: 6.54MB + Indice: 2.22MB
avwp_posts: Dati: 2.89MB + Indice: 0.43MB
avwp_prli_clicks: Dati: 0.09MB + Indice: 0.23MB
avwp_prli_groups: Dati: 0.02MB + Indice: 0.02MB
avwp_prli_links: Dati: 0.02MB + Indice: 0.16MB
avwp_prli_link_metas: Dati: 0.02MB + Indice: 0.03MB
avwp_ps_exclude: Dati: 0.00MB + Indice: 0.00MB
avwp_ps_postmeta: Dati: 0.01MB + Indice: 0.01MB
avwp_ps_posts: Dati: 0.08MB + Indice: 0.03MB
avwp_ps_product_sku: Dati: 0.03MB + Indice: 0.04MB
avwp_sampro_stats: Dati: 0.00MB + Indice: 0.00MB
avwp_sampro_zones: Dati: 0.00MB + Indice: 0.00MB
avwp_sampro_zones_rules: Dati: 0.00MB + Indice: 0.00MB
avwp_social_metrics: Dati: 0.00MB + Indice: 0.00MB
avwp_termmeta: Dati: 0.13MB + Indice: 0.10MB
avwp_terms: Dati: 0.11MB + Indice: 0.19MB
avwp_term_relationships: Dati: 0.35MB + Indice: 0.64MB
avwp_term_taxonomy: Dati: 0.11MB + Indice: 0.09MB
avwp_translations: Dati: 0.08MB + Indice: 0.01MB
avwp_translations_log: Dati: 0.08MB + Indice: 0.02MB
avwp_usermeta: Dati: 0.05MB + Indice: 0.05MB
avwp_users: Dati: 0.00MB + Indice: 0.01MB
avwp_wc_download_log: Dati: 0.02MB + Indice: 0.03MB
avwp_wc_webhooks: Dati: 0.02MB + Indice: 0.02MB
avwp_woobe_history: Dati: 0.02MB + Indice: 0.05MB
avwp_woobe_history_bulk: Dati: 0.02MB + Indice: 0.03MB
avwp_woof_query_cache: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_actions: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_affiliates: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_affiliates_fields: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_creatives: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_events: Dati: 0.42MB + Indice: 0.21MB
avwp_wpam_impressions: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_messages: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_paypal_logs: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_tracking_tokens: Dati: 0.07MB + Indice: 0.02MB
avwp_wpam_tracking_tokens_purchase_logs: Dati: 0.00MB + Indice: 0.00MB
avwp_wpam_transactions: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_also_bought: Dati: 0.01MB + Indice: 0.01MB
avwp_wpsc_cart_contents: Dati: 0.02MB + Indice: 0.01MB
avwp_wpsc_cart_item_extras: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_cart_item_meta: Dati: 0.00MB + Indice: 0.01MB
avwp_wpsc_cart_item_variations: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_categorisation_groups: Dati: 0.00MB + Indice: 0.01MB
avwp_wpsc_category_tm: Dati: 0.34MB + Indice: 0.51MB
avwp_wpsc_checkout_forms: Dati: 0.00MB + Indice: 0.01MB
avwp_wpsc_claimed_stock: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_coupon_codes: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_currency_list: Dati: 0.02MB + Indice: 0.01MB
avwp_wpsc_download_status: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_haet_purchase_details: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_item_category_assoc: Dati: 0.03MB + Indice: 0.04MB
avwp_wpsc_logged_subscriptions: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_meta: Dati: 0.03MB + Indice: 0.03MB
avwp_wpsc_productmeta: Dati: 0.26MB + Indice: 0.25MB
avwp_wpsc_product_categories: Dati: 0.01MB + Indice: 0.01MB
avwp_wpsc_product_files: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_product_images: Dati: 0.04MB + Indice: 0.02MB
avwp_wpsc_product_list: Dati: 0.22MB + Indice: 0.01MB
avwp_wpsc_product_order: Dati: 0.03MB + Indice: 0.05MB
avwp_wpsc_product_rating: Dati: 0.01MB + Indice: 0.01MB
avwp_wpsc_product_variations: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_purchase_logs: Dati: 0.02MB + Indice: 0.02MB
avwp_wpsc_purchase_meta: Dati: 0.00MB + Indice: 0.01MB
avwp_wpsc_purchase_statuses: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_region_tax: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_submited_form_data: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_variation_assoc: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_variation_combinations: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_variation_properties: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_variation_values: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_variation_values_assoc: Dati: 0.00MB + Indice: 0.00MB
avwp_wpsc_visitors: Dati: 0.00MB + Indice: 0.01MB
avwp_wpsc_visitor_meta: Dati: 0.00MB + Indice: 0.01MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 2124
nav_menu_item: 23
page: 24
popup: 2
popup_theme: 6
post: 23
product: 1415
shindiri-woo-slider: 1
shipping_rules: 1
shop_coupon: 1
shop_order: 49
shop_order_refund: 4
wafs: 1
wc_category_slider: 1
wcps: 1
wpsc-product: 611
wpsc-product-file: 1
wpws_content: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

WPBruiser: by Mihai Chelaru – 3.1.21
Login Custom Admin: by Weblizar – 2.7.5
Advanced Cron Manager: by BracketSpace – 2.3.4
WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.6.0

amr shortcode any widget: by anmari – 3.6
WooCommerce CoinPayments.net Gateway: by CoinPayments.net – 1.0.11 – Non testato con la versione attiva di WooCommerce
Comet Cache: by WebSharks
Inc. – 170220

Cookie Law Bar: by WidgetPack  – 1.2.1
Google XML Sitemaps: by Arne Brachhold – 4.0.9
GTranslate: by Translate AI Multilingual Solutions – 2.8.42
Hello Dolly: by Matt Mullenweg – 1.6
hs woocommerce Best Selling Products widget: by heliossolutions – 1.0 – Non testato con la versione attiva di WooCommerce
Google Analytics: by Amr M. Ibrahim – 2.0.2
Loginizer: by Raj Kothari – 1.4.0
PayPal for WooCommerce: by Angell EYE – 1.4.16
Popup Maker: by WP Popup Maker – 1.7.30
Simple Basic Contact Form: by WPKube – 20181001
Social Login Lite For WooCommerce: by phoeniixx – 1.5.2 – Non testato con la versione attiva di WooCommerce
WP WooCommerce Best Selling Products by Category: by WP Online Support – 1.2 – Non testato con la versione attiva di WooCommerce
SpectroCoin: by SpectroCoin – 0.1 – Non testato con la versione attiva di WooCommerce
Storefront Footer Bar: by WooThemes – 1.0.3
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Homepage Contact Section: by WooThemes – 1.0.5
Storefront Product Pagination: by WooThemes – 1.2.4 – Non testato con la versione attiva di WooCommerce
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Sticky Add to Cart: by WooThemes – 1.1.9
Super Progressive Web Apps: by SuperPWA – 1.9
Woo Add Custom Fee: by wpexpertsio – 1.4
WooCommerce Bulk Editor: by realmag777 – 1.0.3
Woo Button Text: by Rupom Khondaker – 6.0.3 – Non testato con la versione attiva di WooCommerce
WooCommerce Category Slider: by pluginever – 3.1.0 – Non testato con la versione attiva di WooCommerce
Woo Message Support: by WooExtend – 2.0
Woo Product Slider and Carousel with category: by WP Online Support – 1.2.1 – Non testato con la versione attiva di WooCommerce
Woo Related Products: by Vagelis P. – 3.3.2
WooCommerce Save For Later Cart Enhancement: by Multidots – 1.0.9 – Non testato con la versione attiva di WooCommerce
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.3 – Non testato con la versione attiva di WooCommerce
WooCommerce Cart Tab: by jameskoster – 1.1.2 – Non testato con la versione attiva di WooCommerce
WooCommerce Category Slider: by gVectors Team – 1.2.0 – Non testato con la versione attiva di WooCommerce
WooCommerce Image Zoom: by wpbean – 1.02.7
WooCommerce Predictive Search LITE: by a3rev Software – 4.2.1
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.1
WooCommerce: by Automattic – 3.4.5
Importatore WordPress: by wordpressdotorg – 0.6.4
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.2.4


### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3069 - /negozio/
Carrello: #3071 - /negozio/carrello/
Cassa: #3073 - /negozio/checkout/
Il mio account: #3075 - /negozio/mio-account/
Termini e condizioni: #21 - /condizioni-vendita/

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rodrigoprimo** [comment] 2018-10-19 13:57
Unfortunately, we are not able to provide help in languages other than English. I happen to understand a little bit of Italian and I might have understood the issue that you described but I'm not sure.

I created a product with the title `Test'test` and searched for `'test`. The product was properly displayed in the search results and, if a click on it, the product page opens correctly.

I noticed in the status report that you have several plugins active. Are you able to reproduce this issue on a site running exclusively WooCommerce? I'm asking this because it is possible that another plugin is causing the problem.

**Comment by Sam9999it** [comment] 2018-10-19 14:32
I'm sorry, but in English I cannot explain ti so good.
I've not try the issue disallowing other's plugins.
I normally have not so much plugins, just what needed and use.
I'll try to disable some plugins and try again a search with some ' into the search field and post the results. now I can think that a old plugin, maybe not more compatible now, can do it....

**Comment by rodrigoprimo** [comment] 2018-10-23 13:49
Ok, closing for now. Please leave another comment if you are able to confirm that this is a WC core issue. Thanks.

**Closed by rodrigoprimo** 2018-10-23 13:49 UTC
Labels: status: needs feedback
