### ISSUE TITLE
Weird order total calculation

### ISSUE THREAD

**Issue by biswajit-paul** [woocommerce/woocommerce#19542] opened 2018-03-27 12:23 UTC
There are displaying two different CA tax in order details backend page. One is $71.26 & another is $131.26 ( Shipping + CA Tax ). This is displaying only for this order. Another CA Tax calculation is ok. How can I fix this issue for this order?

![file](https://user-images.githubusercontent.com/14993725/37966117-1470e8c8-31e5-11e8-91b3-31a8416d5ce2.png)
Screenshot of affected order
![file2](https://user-images.githubusercontent.com/14993725/37966668-d79ee650-31e6-11e8-999e-16c6cc4db119.png)
Screenshot of perfect order
![plugins](https://user-images.githubusercontent.com/14993725/37966968-906c8bba-31e7-11e8-96a9-24cb99287f98.png)
Screenshot of active plugins

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. WP Version: 4.7.8
2. WC Version: 2.6.14
3. PHP Version: 5.6.33
4. MySQL Version: 5.6.38
5. WC Database Version: 2.6.14

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment] 2018-03-27 14:47
If it's just that one order and it's already been paid for the only thing you can really do is provide a refund for the extra tax collected. You're still using WooCommerce version 2.6.14 which is out-of-date at this point. If the issue happens again I recommend updating to the latest version of WooCommerce to take advantage of bug fixes and improvements.

Closing this issue because I can't reproduce this problem and it's for an old version of WooCommerce.

**Closed by claudiulodro** 2018-03-27 14:47 UTC

**Comment by biswajit-paul** [comment] 2018-03-28 06:50
Is there any way I can bring back "Calculate Taxes" & "Calculate Total" buttons though the order is no longer editable. I think If recalculating can fix the issue?

**Comment by mikejolley** [comment] 2018-03-28 07:44
You have to change status to pending in order to edit. It won't refund user.
