### ISSUE TITLE
Issue while retrieving customer with specific email parameter

### ISSUE THREAD

**Issue by awaidanjum** [woocommerce/woocommerce#27201] opened 2020-08-01 17:07 UTC
using woocommerce rest API package automatic/woo-commerce
Want to retrieve guest user details and orders of guest user 
 $woocommerce->get("customers", ['email'=>$email]);
return array is empty
when i login in to store and serach for customer the customer is available.
Please help.

**Comment by juliaamosova** [comment] 2020-08-07 22:49
Hi @awaidanjum,

Thank you for raising the question. I tested on my end and can successfully retrieve the details of the customer with the specified email. My request looks as follows:

`print_r($woocommerce->get('customers?email=udmurtika@gmail.com'));`

Screenshot:

![customer](https://user-images.githubusercontent.com/19143190/89694017-56462b80-d8de-11ea-9d31-470de8341aa0.jpg)

On your end, I would check if the user you are looking for has a `customer` role and not some other role. If there are other plugins installed like Subscriptions or Memberships, the role can be `subscriber` or `member` even though that user is also a customer in which case that request won't work. 

If the user is in fact a `customer`, I recommend you test your site for plugins and theme conflicts. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-08-14 23:08
Hi @awaidanjum,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-08-14 23:08 UTC
Labels: can't reproduce, status: needs feedback
