### ISSUE TITLE
Restrict customer advancing to the checkout if they do not have a particular product category in their basket & notify them with an error message that no delivery for this particular category product.

### ISSUE THREAD

**Issue by ktchan1811** [woocommerce/woocommerce#28108] opened 2020-10-27 02:40 UTC
Hi,

I would like to Restrict customer advancing to the checkout if they do not have a mandatory product category in their basket & notify them with an error message that no delivery for this particular category product. Example : As this particular category product is an addon product to the Mandatory Product . Therefore, customer need to purchase the mandatory product before they can purchase this add on product.

How can i do this Woocommerce?

**Comment by juliaamosova** [comment] 2020-10-28 21:14
Hi @ktchan1811,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-28 21:14 UTC
