### ISSUE TITLE
404 Page in Thank You / order-recieved page

### ISSUE THREAD

**Issue by jazir5** [woocommerce/woocommerce#28890] opened 2021-01-22 01:00 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
404 on thank you page, "page not found." The slug of the url thats auto generated is: /checkout-2/order-received/4991/?key=wc_order_IJALzYZ2PxTJc

Any url with wc_order 404's. The checkout url works fine(/checkout-2/)

**Expected behavior**
A working thank you page

**Actual behavior**
404 on order complete, even with different checkout plugins or the default shortcode.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Make a checkout page via elementor
2. test checkout using any payment gateway
3. receive a 404 error page not found.

**Screenshots**

![not found](https://user-images.githubusercontent.com/31750063/105431047-bc630880-5c09-11eb-9dea-12515af8a784.PNG)

This is not a plugin conflict, have tested with plugins disabled except the necessary ones.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

here is a pastebin of the log since i cannot find the system status report button anywhere:

https://pastebin.com/CMeUAkyj

```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by zhongruige** [comment] 2021-01-26 21:27
Hi @jazir5,

Thank you for submitting the issue. Everything is working as expected on my end. I landed on the order received page as expected:

<img width="837" alt="Screen Shot 2021-01-26 at 2 23 18 PM" src="https://user-images.githubusercontent.com/71906536/105907531-4cc29400-5fe2-11eb-998e-5bf3bacd6b78.png">

The issue you are having appears it could be caused by the 3rd party plugin Elementor based on these replication steps:

 > Make a checkout page via elementor
 > test checkout using any payment gateway
 > receive a 404 error page not found.

To help us further investigate, can you confirm if you disable Elementor, and only create the page that the same behavior occurs?

Thank you!

**Comment by zhongruige** [comment] 2021-02-16 21:31
Hi @jazir5,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by zhongruige** 2021-02-16 21:31 UTC
Labels: needs feedback

**Comment by thesuss** [comment] 2024-12-17 21:09
This thread made me (5 hours later) realize the problem 
In elementor woocommerce settings one MUST select at thankyou-page. 
If not selected it might become 404. There are code-snippets around to solve it, but they create other problems. 
Setting a thank-you page will solve it beautifully. 
But very very very frustrating process to find the hard way. 

So this comment is for everyone finding this on Google before Elementor fixes a warning or something.
