### ISSUE TITLE
Urgent v5.1.0 <-- Can't add Array datatype as value of meta key via Rest API

### ISSUE THREAD

**Issue by luissimo** [woocommerce/woocommerce#29392] opened 2021-03-15 21:14 UTC
Since the last release v5.1.0 we can't add array datatypes as meta value when creating new orders through the Rest API

-- [Rest API endpoint] (http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order)

**Example request body:**
```
{ 
shipping_lines: [],
meta_data: [ { key: "meta_1", value: ["Doesnt", "Work"] }, { key: "meta_2", value: "i am a string and i work fine" } ]
}
```

In this case meta_1 gets rejected and meta_2 gets added as meta data to the order.
Prior to release v5.1.0 it was accepting arrays and now it is not.

This is a urgent bug which ruins automatic processes.

**Comment by ObliviousHarmony** [comment] 2021-03-29 19:44
Hi @luissimo,

Thank you for raising the issue. However, I can’t reproduce it on my end.

We've tested out this endpoint and haven't experienced any problems creating `meta_data` with an array `value`.

Please try deactivating all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Closed by ObliviousHarmony** 2021-03-29 19:44 UTC
Labels: needs developer feedback
