### ISSUE TITLE
Hide "quantity selector" and "add to cart" if variations are out of stock

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#26243] opened 2020-04-22 16:25 UTC
**SIMPLE PRODUCT**

1) If a simple product is out of stock, the quantity selector is hidden => OK

![image](https://user-images.githubusercontent.com/51261962/80007340-68829200-84c6-11ea-8411-2d97df2d03f9.png)

**VARIABLE PRODUCT**

2) If a particular variation of a variable product is out of stock (while other variations of the same product are not out of stock), we should hide the quantity selector when the user selects that particular variation that is out of stock.

![image](https://user-images.githubusercontent.com/51261962/80007559-aed7f100-84c6-11ea-8132-40e1beb5e401.png)

3) If all the variations of a variable product are all out of stock, we should always hide the quantity selector (whether a variation is selected by the user or not) => same behavior as simple product

![image](https://user-images.githubusercontent.com/51261962/80007462-8f40c880-84c6-11ea-981b-b6dffe630571.png)

**Comment by dabex** [comment] 2020-04-22 21:02
Hello @gevcen. 
I am fixing this issue on CSS way:
.woocommerce-variation-add-to-cart.variations_button.woocommerce-variation-add-to-cart-disabled {
    display: none;
}
(the simpliest way to do it)
You can also do it by using some jQuery, if you want to.

**Comment by dabex** [comment] 2020-04-22 21:15
Here you have jQuery snippet for this issue:
add_action( 'wp_footer', 'hide_var_atc_block' );
function hide_var_atc_block() {
    global $product;
    if( ! ( is_product() && $product->is_type('variable') ) )
        return;
    ?>
        <script type="text/javascript">
        jQuery(function($){
            var vs = 'table.variations select',         vi = 'input.variation_id',
            atc = 'woocommerce-variation-add-to-cart',  atcd = atc+'-disabled',
            atc = '.'+atc;
            setTimeout(function(){
                if ( 0 < $(vi).val() && $(atc).hasClass(atcd) ) {
                    $(atc).hide();
                }
            }, 250);
            $('.variations_form').on( 'blur', vs, function(){
                if( 0 < $(vi).val() && $(atc).hasClass(atcd) ){
                    $(atc).hide();
                } else {
                    $(atc).show();
                }
            });
        })
        </script>
    <?php
}

**Comment by gevcen** [comment] 2020-04-24 17:02
Hi @dabex

I didn't think that a so simple CSS code would do the job :)
I just tested it and it's working great

Thanks!

**Comment by dabex** [comment] 2020-04-24 19:22
Hi @gevcen 
I will trully recommend usign the jQuery solution, not the CSS one.
I had no downside with both of them.
Thanks

**Comment by gevcen** [comment] 2020-04-24 21:47
Hi @dabex 
May I ask what's the advantage to use the jQuery compared to the CSS?
Thanks

**Comment by juliaamosova** [comment] 2020-05-06 18:39
Hi @gevcen,

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. 

I've tried both to manage stock of the variation and without it:

Stock managed:

![var1](https://user-images.githubusercontent.com/19143190/81215453-63821000-8fa7-11ea-991f-c0e3bff4d976.jpg)

Stock is not managed:

![var2](https://user-images.githubusercontent.com/19143190/81215462-67ae2d80-8fa7-11ea-99c2-9b6d7bf4cecd.jpg)

In both cases, the variation that is out of stock is not offered at the front end at all:

![var3](https://user-images.githubusercontent.com/19143190/81215479-6bda4b00-8fa7-11ea-8acc-2204da5faf33.jpg)

Could it be that one of the plugins you are using or a theme is overriding that behavior? In which case I recommend you do a theme and plugins conflict testing. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-07-07 20:24
Hi @gevcen,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-07-07 20:24 UTC
Labels: can't reproduce, status: needs feedback
