### ISSUE TITLE
Product set_catalog_visibility issue

### ISSUE THREAD

**Issue by yiangos14** [woocommerce/woocommerce#26134] opened 2020-04-08 23:36 UTC
Hello

i am using the set_catalag_visibility in my code and i am getting this error 
Fatal error: Uncaught Error: Call to a member function set_catalog_visibility() on boolean

i cannot troubleshoot this issue 

Can you please assist?
This is my code
	  $product=wc_get_product($post_id);
	  $product->set_catalog_visibility(wc_clean('visible'));
	  $product->save();

WooCommerce Version 4.0.1

**Comment by tammullen** [comment] 2020-05-12 00:04
Hi @yiangos14 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-05-12 00:04 UTC
