### ISSUE TITLE
Double Stock Reduction since V3

### ISSUE THREAD

**Issue by robyholmes** [woocommerce/woocommerce#14790] opened 2017-04-28 16:42 UTC
### EXPLANATION OF THE ISSUE

Every order on our system since WC V3 was installed is reducing the stock twice. 

### STEPS TO REPRODUCE THE ISSUE

Customer orders items which have 'Managed Stock' enabled. The order is placed using PayPal express checkout set to 'Authorise'. In the dashboard order page in the order notes the stock reduction note is shown twice. The message is not the same and stock is reduced double the amount it should. This is all before the order is set to processing or complete.

### SYSTEM STATUS

<details>
WordPress environment
Home URL:		http://slrmodels.co.uk
Site URL:		http://slrmodels.co.uk
WC version:		3.0.4
Log directory writable:		 /home/abbeyh5/public_html/slrmodels.co.uk/wp-content/uploads/wc-logs/
WP version:		4.7.4
WP multisite:		–
WP memory limit:		512 MB
WP debug mode:		–
WP cron:		
Language:		en_GB
Server environment
Server info:		Apache
PHP version:		5.6.30
PHP post max size:		128 MB
PHP time limit:		30
PHP max input vars:		4000
cURL version:		7.45.0, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.33
Max upload size:		128 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.4
Database prefix	 	wpxb_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /home/abbeyh5/public_html/slrmodels.co.uk/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (15)
Check Email	 	by Chris Taylor – 0.5.5
Google Analytics Dashboard for WP	 	by Alin Marcu – 4.9.6.2
Image Watermark	 	by dFactory – 1.6.1
Loginizer	 	by Raj Kothari – 1.3.4
Smart Forms	 	by RedNao – 2.5.6
Theme Customisations	 	by WooThemes – 1.0.0
Facebook Feed WD	 	by WebDorado – 1.0.19
Woo Stickers by Webline	 	by Weblineindia – 1.0.4
WooCommerce PayPal Express Checkout Gateway	 	by WooCommerce – 1.2.1
WooCommerce Product Add-ons	 	by Automattic – 2.7.26 – 2.8.1 is available
WooCommerce Product Bundles	 	by WooThemes – 5.1.1 – 5.2.2 is available
WooCommerce Shipment Tracking	 	by WooCommerce – 1.6.3 – 1.6.4 is available
WooCommerce Stock Manager	 	by Vladislav Musílek – 1.1.4
WooCommerce	 	by Automattic – 3.0.4
YITH WooCommerce Custom Order Status	 	by YITHEMES – 1.1.0
Settings
API enabled:		
Force SSL:		–
Currency		GBP (£)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		bundle (bundle), external (external), grouped (grouped), simple (simple), variable (variable), wcpb (wcpb)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#4 - /shop/
Basket:		#5 - /basket/
Checkout:		#6 - /checkout/
My account:		#7 - /my-account/
Theme
Name:		Storefront
Version:		2.1.8
Author URL:		https://woocommerce.com/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides:	 	–

</details>

**Comment by claudiosanches** [comment] 2017-04-28 16:50
It's working just fine in all my tests, but I noticed that you are using `WooCommerce Stock Manager by Vladislav Musílek – 1.1.4`, for sure this is the problem, maybe need to update to make work with WooCommerce 3.0.
But will be great if you chec and update all other of your plugins too.
Still closing since not able to reproduce and does not sound like an issue with WooCommerce.

**Closed by claudiosanches** 2017-04-28 16:50 UTC

**Comment by robyholmes** [comment] 2017-04-28 16:54
I've disabled the plugin but the issue remains.

**Comment by claudiosanches** [comment] 2017-04-28 17:06
@robyholmes tested disabling all plugins? With other theme?

**Comment by robyholmes** [comment] 2017-04-28 17:11
@claudiosanches Just done that. Leaving only WooCommerce and PayPal Express Checkout enabled and it still reduced it twice.

**Comment by claudiosanches** [comment] 2017-04-28 17:51
@robyholmes so probably the problem is on PayPal Express Checkout. Better report in https://woocommerce.com/my-account/create-a-ticket/ so they can help you fix it.

**Comment by robyholmes** [comment] 2017-05-21 19:54
Just replying to say we're stilling having a problem with this. We're currently using the PayPal standard checkout rather than express. It doesn't do it on every order, only some. We can't find any link with the orders which take double stock. Members or not, different items etc. It will always reduce stock on all items on the order, not just some.
Running V3.0.7 of Woocommerce & V4.7.5 of WordPress.

**Comment by TuureKaunisto** [comment] 2017-06-05 06:40
We're having similiar issues after updating to WooCommerce 3.0.7. We're using WooCommerce Paytrail payment gateway instead of PayPal.

The order comments show that the reduction has been done twice. Once after the status has changed from pending to processing and again after a comment saying: "Transaction Approved via Paytrail"

**Comment by ifede84** [comment] 2018-07-15 10:05
It' s a double notification issue. I had the same issue, both PDT and IPN activated, and i solved it disabling one of them

**Comment by Yaseer-sk** [comment] 2018-07-16 07:12
@ifede84 Just want to know which version of woocommerece you are using and how did u disabled one of them?

**Comment by ifede84** [comment] 2018-07-16 09:33
@Yaseer-sk: Sure: woo 3.4.3

This is how to disable PDT ----> https://imgur.com/a/xon6k8p

Anyway, I suggest asking help to Paypal Support to disable one of them!

**Comment by ifede84** [comment] 2018-07-16 10:41
@SCL-Admin I' was in the same situations. Everything works properly until issue occurs. If you disable PDT, every order is going to be notified by IPN. If you keep both active, sometimes woo receives both notifications and does double action (stock reduction, email).

Disabling PDT worked for me. I suggest you try

**Comment by SCL-Admin** [comment] 2018-07-16 11:15
@ifede84  Yes, I think it works and thanks for your solution. But it would be interesting what the actual cause is for the error.

As you say. You get both statuses, IPN and PDT, and the logs look absolutely identical. But once the stock is reduced twice and another time, ... not! That's what I dont understand.
I updated to WC 3.4.3 last week. Maybe it depends on it?!? ...

https://woocommerce.wordpress.com/2018/06/20/woocommerce-3-4-3-fix-release-notes/

**Comment by ifede84** [comment] 2018-07-16 11:22
I had issue with older woo, 2.x, so i' don't think it 's related to woo version. I don't know why sometimes issue occurs and sometimes no! I just fixed disabling PDT and go ahead, but let me know if you understand the cause!

**Comment by SCL-Admin** [comment] 2018-07-16 11:46
hmm, ... i had the problem in the past (i think it was with PDT) that sometimes no status came from PayPal and the order was canceled, but it was paid with PayPal. So I set both methods in parallel to fix it. I hope now with just IPN everything works and not the old problem occurs again.

**Comment by Demuri** [comment] 2018-07-25 13:19
Same issue — double stock reduction on Paypal orders. Wocommerce 3.4.3. IPN and PDT confirmations received.

**Comment by ifede84** [comment] 2018-07-25 13:21
Disable PDT :P

**Comment by Demuri** [comment] 2018-07-25 13:21
Yepp, I'll try

**Comment by SCL-Admin** [comment] 2018-07-25 21:15
so far this works well for me. still no problems  missing IPN messages.

**Comment by justinahsnyder** [comment] 2018-08-28 22:33
I am having same issue... how to solve?
