### ISSUE TITLE
Sales by Category incorrect calculations when there are refunds

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#24293] opened 2019-08-01 18:28 UTC
**Describe the bug**
When viewing WooCommerce > Reports > Orders > Sales by category, if there is a refund in the category, the amount is subtracted from what seems like twice. 

**To Reproduce**
1. Create a new product, and create a new category for it
2. Purchase product
3. Refund product
4. Go to WooCommerce > Reports > Orders > Sales by category and choose that new product
5. You will see a negative amount for the category. 
6. If you then order the product again, the amount is 0. 
7. If you then refund the second order, the amount is double the first negative amount. 

**Screenshots**
![](https://cld.wthms.co/biRsja+)
Image Link: https://cld.wthms.co/biRsja

**Expected behavior**
For the report to be 0, not negative. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-01-17 16:58
Hi @jessepearson,

Thanks for raising the issue and providing clear steps to reproduce it. Apologies for the delayed response. We are now going over older bugs without priority, hence the delayed response on our end. 

I am getting incorrect results in the reports after refunding the product but they are different from what you are seeing:

- I have a product that costs $63.00 and is assigned to category `test category`:

![cat1](https://user-images.githubusercontent.com/19143190/72629701-be382300-3948-11ea-862a-39710314d4b0.jpg)

- For the sake of the test, this product is the only one assigned to this category

![cat2](https://user-images.githubusercontent.com/19143190/72629721-c728f480-3948-11ea-9b8c-27725a77e2aa.jpg)

- Placed order and refunded it:

![cat3](https://user-images.githubusercontent.com/19143190/72630105-8aa9c880-3949-11ea-997d-bb97d851d614.jpg)

- Checked `WooCommerce > Reports > Orders > Sales by category` and saw that I am getting $63 x 10 = $630 instead of zero `0`:

![cat4](https://user-images.githubusercontent.com/19143190/72630206-c93f8300-3949-11ea-90c9-cc2f0919bb37.jpg)

I tested on another site of mine just to be sure that I can reproduce the same and got the same results. 

While this is clearly a bug, we won't be fixing it as if you install [WooCommerce Admin](https://wordpress.org/plugins/woocommerce-admin/) plugin, you will see that reports work as expected there:

![cat5](https://user-images.githubusercontent.com/19143190/72630339-04da4d00-394a-11ea-9d69-6cb2d29f1904.jpg)

WooCommerce Admin plugin will be merged to WooCommerce Core some time in Q1/Q2 and will fully replace existing reports which is the reason why we won't be fixing this bug in the existing reports. We recommend suggesting users install a free WooCommerce Admin plugin instead and start getting accustomed to it. 

I am going to close this issue with a `won't fix` label, however, feel free to comment in case you think I missed something and I will take another look.

**Closed by juliaamosova** 2020-01-17 16:58 UTC
Labels: bug
