### ISSUE TITLE
Product variable options in mobile view

### ISSUE THREAD

**Issue by zameer85** [woocommerce/woocommerce#20756] opened 2018-07-11 11:54 UTC
I have many product variables which have quite long (over 90 characters) product names and they do not appear on the mobile view drop down. Can the variable product drop down list be mobile friendly? and perhaps bring the line down to fit in the mobile view?

**Describe the solution you'd like**
A product variable if too long, should show up in the next line. Woocommerce is not mobile friendly 100% unless the product variables show up on the screen when 'choose an option' is tapped.

**Describe alternatives you've considered**
I have request Woo commerce support but they asked to create a ticket here, they didn't a solution exists at the moment.
![screenshot_1](https://user-images.githubusercontent.com/29456267/42569738-760ee78e-8509-11e8-89bb-b9aa04fc6185.png)

**Additional context**

**Comment by claudiosanches** [comment] 2018-07-12 00:38
@tiagonoronha do you know something that can improve it?

**Comment by peterfabian** [comment] 2018-07-12 14:30
I've found this trick that we might be able to use: https://stackoverflow.com/questions/19398154/how-to-fix-truncated-text-on-select-element-on-ios7

Not sure if we want to include it with all selects or just some?

**Comment by tiagonoronha** [comment] 2018-07-12 14:44
Woah what a weird hack. I just tested it quick, it definitely works.

![img_5734](https://user-images.githubusercontent.com/1177726/42640505-5afab09a-85ea-11e8-8b92-df93581ab2dc.jpg)

vs.

![img_5735](https://user-images.githubusercontent.com/1177726/42640517-616bc978-85ea-11e8-924c-e5e6256fd030.jpg)

**Comment by tiagonoronha** [comment] 2018-07-12 14:48
It's worth noting that this hack changes the behaviour of the select control. Instead of using your thumb to scroll and select the option you want, you have to tap to select.

**Comment by claudiosanches** [comment] 2018-07-12 15:35
@tiagonoronha do you think that we should change it on WooCommerce core, or it's something specific for some user cases or themes?

**Comment by tiagonoronha** [comment] 2018-07-12 16:41
@claudiosanches this is an iOS bug. What's our policy regarding browser bugs? 

The fix suggested here works, but I don't like that it changes the behaviour of the select. This is also a bit of an edge case. 

Perhaps a quick snippet to fix the issue is enough for now?

Side note: from the screenshot in the original post, I can see there's a bug in Storefront and selectboxes are overflowing the container. I'll open a PR for that.

**Comment by claudiosanches** [comment] 2018-07-12 17:48
@tiagonoronha I think we can go with a snippet, since it's iOS related and can be fixed in themes by JS or CSS.

**Comment by zameer85** [comment] 2018-07-13 08:12
Hi, i have noticed that this issue with drop down is on Samsung phones as well...
I have tested this on a live website using Divi, elegant themes... I reported this and they also suggested that it was an issue with WooCommerce...and not a theme issue...

![screenshot_20180713-090917](https://user-images.githubusercontent.com/29456267/42680341-aa879c62-867c-11e8-80be-df5e2255e9d6.png)

**Comment by claudiosanches** [comment] 2018-07-13 16:50
@zameer85 does not sound an issue on WooCommerce, even more because if you include any form on your website should happens the same, working with WordPress or not, that's why I'm saying that is specif for your user case.

**Comment by claudiosanches** [comment] 2018-07-13 16:51
Closing since this seems the regular behavior on iOS and Android browsers for drop-boxes which contains long names.

**Closed by claudiosanches** 2018-07-13 16:51 UTC
Labels: status: needs review

**Comment by zameer85** [comment] 2018-07-16 07:36
Too bad that this can't be resolved. Agree that it is a regular problem with iOS and Android, but that shouldn't stop you improving your product. Did @peterfabian 's trick not help? I've found this trick that we might be able to use: https://stackoverflow.com/questions/19398154/how-to-fix-truncated-text-on-select-element-on-ios7 . I would have appreciated if this was resolved, it makes a big issue for my site which has 2900 variable product with almost all long names.  I am sure there would be many other sites experiencing similar problems.. Is there anything that i could add to my css or any file that could fix it?

**Comment by peterfabian** [comment] 2018-07-16 18:41
@zameer85 you can try the JS code suggested at in the StackOverflow as `iOS 7 hack`, that should do the trick.

**Comment by zameer85** [comment] 2018-07-18 07:00
Thanks @peterfabian Which file and where could I insert that code? Is there anything that I could do with the child theme?

**Comment by peterfabian** [comment] 2018-07-19 14:38
@zameer85 I think the easiest is to use a plugin that allows adding custom JS to your website, there are quite a few of them: https://wordpress.org/plugins/search/custom+js/

Alternatively, you can create a separate JS file for your customizations (so that your changes won't get overwritten by updates of themes or plugins). You could then create a child theme and use [wp_enqueue_script()](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) function in your child theme to include the JS file you created.

**Comment by zameer85** [comment] 2018-07-19 14:54
Thanks @peterfabian
