### ISSUE TITLE
product.created web hook sent a product not found error

### ISSUE THREAD

**Issue by WebMedic-X** [woocommerce/woocommerce#28137] opened 2020-10-29 08:20 UTC
Hi,

Today we received a web hook request from a website on product.created

Instead of the usual data in the request we would expect from documentation such as the product information, this is what was sent by the website:

{
  "code": "woocommerce_rest_product_invalid_id",
  "message": "Invalid ID.",
  "data": {
    "status": 404
  }
}

Not sure why the web hook would send this data on a product.created web hook?

Thank you

**Comment by WebMedic-X** [comment] 2020-11-10 14:56
Hi

This is happening again and not sure why

Thanks

**Comment by rrennick** [comment] 2021-01-21 18:11
Hi @WebMedic-X ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by WebMedic-X** [comment] 2021-01-25 13:23
This is happening on the web hooks from Woocommerce 

When receiving data from product.created

Data is

{
"code": "woocommerce_rest_product_invalid_id",
"message": "Invalid ID.",
"data": {
"status": 404
}
}

Which doesn't make sense

Happened more than once now

Don't know how to reproduce the issue

**Comment by tammullen** [comment] 2021-03-25 22:25
Hi @WebMedic-X 


The number of details you provided is not enough for us to work with and identify what could be going on.

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by juliaamosova** [comment] 2021-04-02 19:20
Hi @WebMedic-X,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-04-02 19:20 UTC
Labels: needs feedback
