### ISSUE TITLE
New Order Email Settings cannot be saved in WC 3.7.0

### ISSUE THREAD

**Issue by youngmicroserf** [woocommerce/woocommerce#24405] opened 2019-08-14 15:11 UTC
**Describe the bug**
New Order Email Settings, and *only* new order Email settings (saving other order email settings work fine), cannot be saved after upgrade to Version 3.7.0, - reproduced in two installations.

**To Reproduce**
try that.

**Screenshots**

**Expected behavior**
should save

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
happened in two different current setups

**Comment by bradlymcgregorhale** [comment] 2019-08-14 16:34
I can also confirm this issue, and it seems to be occurring with the hands-raised emoji in the `Additional Content` textarea. It is preventing all fields from being updated. Removing the emoji allows the fields to be updated. 

1) Go to `*/wp-admin/admin.php?page=wc-settings&tab=email&section=wc_email_new_order`
2) Change `Congratulations on the sale 🙌` to `Congratulations on the sale! 🙌`
3) When the page loads, it will look as though the field is updated. However, upon page refresh (`command` + `R`), you'll see that `Congratulations on the sale 🙌` persists.
4) Remove the emoji:  `Congratulations on the sale!` 
5) Now modify any field, save the modification, and refresh the page. The form data will be saved.

**Comment by youngmicroserf** [comment] 2019-08-14 17:36
I can confirm that removing the emoji allows changes to be saved.

**Comment by kloon** [comment] 2019-08-16 07:36
I did some tests now and am unable to replicate this using the steps @bradlymcgregorhale provided. See GIF below:

![](https://cld.wthms.co/wILm2F+)

**Comment by dsmithweb** [comment] 2019-08-18 15:19
Hi there! I have tested this with all other plugins disabled. Did you (as specified in [my earlier bug report](https://github.com/woocommerce/woocommerce/issues/24397)) refresh the New Order Email page, after saving it? In my testing, it *appears* to save successfully at first, but reverts to the earlier content upon refresh.

**Comment by claudiosanches** [comment] 2019-08-20 00:01
I'm also not able to reproduce this issues, that emoji saves without any issue.
What user level are you all using? All administrators?

**Comment by manesvenom** [comment] 2019-08-20 07:00
To store emoji to MySQL, COLLATE is required to be utf8mb4 
[https://stackoverflow.com/questions/39463134/how-to-store-emoji-character-in-mysql-database](url)

**Comment by claudiosanches** [comment] 2019-08-20 15:01
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24450.

**Closed by claudiosanches** 2019-08-20 15:01 UTC
Labels: has pull request
