### ISSUE TITLE
What is the default formula to calculate cart total ?

### ISSUE THREAD

**Issue by Bradzer** [woocommerce/woocommerce#27582] opened 2020-09-03 20:30 UTC
Hi.

I would like to know what is the default formula to calculate the cart total.

When I retrieve the cart totals, this is what I get :

```
array (
  'subtotal' => '200.00',
  'subtotal_tax' => 2.0,
  'shipping_total' => '10.00',
  'shipping_tax' => 0.1,
  'shipping_taxes' => 
  array (
    1 => 0.1,
  ),
  'discount_total' => 0,
  'discount_tax' => 0,
  'cart_contents_total' => '200.00',
  'cart_contents_tax' => 2.0,
  'cart_contents_taxes' => 
  array (
    1 => 2.0,
  ),
  'fee_total' => '0.00',
  'fee_tax' => 0,
  'fee_taxes' => 
  array (
  ),
  'total' => '212.10', // <= how is this calculated ?
  'total_tax' => 2.1,
)
```

WooCommerce version 4.3.1

**Comment by tammullen** [comment] 2021-03-26 19:42
Hi @Bradzer 

Sorry for the delay in replying

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-26 19:42 UTC
Labels: needs developer feedback
