### ISSUE TITLE
The logout functionality is very inconsistent and buggy... cannot figure out why.

### ISSUE THREAD

**Issue by simplicity17** [woocommerce/woocommerce#28493] opened 2020-12-03 23:17 UTC
When logging in, everything works perfeclty. When logging out, there are a number of outcomes.

1) There is a strange URL and a blank white page. URL reads https://tikumi.simplicitydesign.business/wp-login.php?action=logout&redirect_to=https%3A%2F%2Ftikumi.simplicitydesign.business%2Fmy-account%2F&_wpnonce=39b6cbd1fe

2) You are able to logout, but when you log back in, there is a notification on the My Account page that says "Are you sure you want to logout?". From here...
     a) If you click the original Log Out button, you are logged out successfully.
     b) If you click the "I'm sure I want to logout" button, you get the strange URL above and a blank white screen.

Even if you manage to logout successfully, the "Are you sure you want to logout" message appears. This is driving me crazy, I have no clue what is happening. This is my only website this is happening on. I am using the Woostify theme (my account page is built using their template system in conjunction with Elementor). 

Thank you in advance for your help!!

View screen recording of what is happening here: https://youtu.be/jNaXdRMM3wo

**Comment by juliaamosova** [comment] 2020-12-04 16:45
Hi @simplicity17,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I tested with Twenty Twenty and Storefront themes which are the default themes that we usually test against.

**Twenty Twenty:**

![](http://g.recordit.co/OPUncCkQAC.gif)

**Storefront:**

![](http://g.recordit.co/j2sMfQGwlX.gif)

The Woostify theme + Elementor combination you are using could the cause of the issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

You can also open the browser console as you are trying to log out and see what errors will be listed in the console (if any) when you can reproduce the issue. It often leads to an understanding of what could be going on. If you are on a Mac computer and use Chrome browser, you can open the console by using the `Option + Command + I` keys combo.

**Comment by juliaamosova** [comment] 2020-12-11 20:05
Hi @simplicity17,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Comment by tammullen** [comment] 2020-12-18 12:10
Reopening to add feedback from https://github.com/woocommerce/woocommerce/issues/28619

> I have tried it with Wordpress 2020 theme and WooCommerce default barebones My Account widget/shortcode and the results are the same. No matter what I do, what I deactivate, etc. I get the same bug.
> 
> Thank you in advance for your help!!
> 
> View screen recording of what is happening here: https://youtu.be/mBuNQadeI4Q

Hi @simplicity17, Thank you for including more information on the linked issue. However, I also can’t reproduce it using the steps you provided. Everything is working as expected on my end, I tired with both the default My Account page and an additional page using the My Account shortcode

Your video shows The Woostify theme + Elementor combination you mentioned. Can you provide a video or screenshots of your attempt with Wordpress 2020 theme and WooCommerce default barebones My Account widget/shortcode 

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by simplicity17** [comment] 2020-12-18 20:35
Thank you for reopening the ticket and for your help, has been very busy here and wanted Woostify to get back to me with their take on the bug.

So this video is with Woostify theme and their WooCommerce Account widget and other widgets on the page, built with Elementor: https://www.youtube.com/watch?v=jNaXdRMM3wo&feature=youtu.be

This last video is with 2019 Theme installed, haven't updated Wordpress yet, (it still appears styled because I have the header and footer templates set in Elementor) and the WooCommerce shortcode inserted on the My Account page with other widgets on that same page buit with Elementor: https://www.youtube.com/watch?v=mBuNQadeI4Q&feature=youtu.be

Here is a video of it happening with Wordpress 5.6, 2020 theme, page built in Wordpress without Elementor with the barebones WooCommcerce My Account shortcode: https://youtu.be/AinsxSmqS94

It is some sort of redirect issue with WooCommerce, just don't know what is causing it. Site status below.

NOTE: Before getting the site status data I switched the site back to Woostify theme since it doesn't appear to be causing the issue. I did not touch the My Account page from my last test (no Elementor, just the shortcode on the page) but the status says that it does not see the shortcode on the page... but the page does work, shows the login screen and then dashboard, just doesn't logout properly. Not sure if this is related. That data is what is attached.

`
### WordPress Environment ###

WordPress address (URL): https://tikumi.simplicitydesign.business
Site address (URL): https://tikumi.simplicitydesign.business
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.11
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 6200
cURL Version: 7.72.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.36-MariaDB-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wphu_
Total Database Size: 38.61MB
Database Data Size: 37.80MB
Database Index Size: 0.81MB
wphu_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wphu_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_options: Data: 2.95MB + Index: 0.08MB + Engine MyISAM
wphu_postmeta: Data: 27.10MB + Index: 0.31MB + Engine MyISAM
wphu_posts: Data: 7.44MB + Index: 0.10MB + Engine MyISAM
wphu_redirection_404: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wphu_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_redirection_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_redirection_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_relevanssi: Data: 0.04MB + Index: 0.07MB + Engine MyISAM
wphu_relevanssi_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_relevanssi_stopwords: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_usermeta: Data: 0.07MB + Index: 0.02MB + Engine MyISAM
wphu_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wphu_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_yoast_indexable: Data: 0.07MB + Index: 0.03MB + Engine MyISAM
wphu_yoast_indexable_hierarchy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wphu_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wphu_yoast_seo_links: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wphu_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

acf-field: 31
acf-field-group: 2
attachment: 103
customize_changeset: 1
elementor_font: 1
elementor_icons: 1
elementor_library: 31
nav_menu_item: 11
oembed_cache: 6
page: 13
post: 4
product: 10
product_filter: 1
revision: 971
shop_order: 3
vendor: 6
woo_builder: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

a3 Lazy Load: by a3rev Software – 2.4.2
Advanced Custom Fields PRO: by Elliot Condon – 5.9.3
Advanced Custom Fields: by Elliot Condon – 5.9.3
Advanced Post Queries: by Shabti Kaplan – 1.0.15
Classic Editor: by WordPress Contributors – 1.6
Code Snippets: by Code Snippets Pro – 2.14.0
Custom Post Type UI: by WebDevStudios – 1.8.1
Duplicate Page: by mndpsingh287 – 4.3
Dynamic Content for Elementor: by Dynamic.ooo – 1.9.6.7.2
Extras for Elementor: by Namogo – 2.2.42
Elementor Pro: by Elementor.com – 3.0.8
Elementor: by Elementor.com – 3.0.14
Enable Media Replace: by ShortPixel – 3.5.0
Piotnet Addons For Elementor Pro: by Luong Huu Phuoc (Louis Hufer) – 6.3.40
PowerPack Pro for Elementor: by Team IdeaBox - PowerPack Elements – 2.2.1
Premium Addons for Elementor: by Leap13 – 4.1.1
Premium Addons PRO: by Leap13 – 2.2.3
Redirection: by John Godley – 4.9.2
Relevanssi: by Mikko Saari – 4.10.2
Temporary Login Without Password: by StoreApps – 1.6.6
Ultimate Addons for Elementor: by Brainstorm Force – 1.28.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.43

Ajax add to cart for WooCommerce: by QuadLayers – 1.1.4
Multi Currency for WooCommerce: by VillaTheme – 2.1.6
WooCommerce Order Test: by WP Fix It – 1.6 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce: by Automattic – 4.8.0
Woostify Pro: by Woostify – 1.4.6
Yoast SEO: by Team Yoast – 15.5
WP Fastest Cache: by Emre Vona – 0.9.1.3

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #13 - /shop/
Cart: #1389 - /cart/
Checkout: #491 - /checkout/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: #68 - /terms-conditions/

### Theme ###

Name: Woostify
Version: 1.8.0
Author URL: https://woostify.com/about
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-12-08 19:09:23 -0800
Newest: 2020-12-08 19:09:23 -0800

Complete: 17
Oldest: 2020-11-19 09:26:37 -0800
Newest: 2020-12-08 19:15:58 -0800

`

**Comment by simplicity17** [comment] 2021-01-05 17:55
Any updates on this issue?

**Comment by simplicity17** [comment] 2021-01-11 13:07
@juliaamosova I added additional details as requested but have not heard anything back. I need to launch this site but can't with this major issue. Please see information above.

**Closed** 2021-01-11 13:22 UTC
Labels: category: can't reproduce, has feedback

**Comment by simplicity17** [comment] 2021-01-11 13:23
PowerPack plugin was the culprit! Even if you don't use their login/register widgets, if you do not set the Login and My Account pages in their plugin settings, everything breaks. Going to report it now but just wanted to put this information here for anyone else having this issue!

**Comment by tammullen** [comment] 2021-01-11 23:00
Thanks @simplicity17 for the update!
