### ISSUE TITLE
Cart issues with Block Shop theme

### ISSUE THREAD

**Issue by jakewangner** [woocommerce/woocommerce#27180] opened 2020-07-30 16:52 UTC
I have attached screenshots of the two issues I'm having. First is that that site colors are set to a black background and white text, but on the checkout page/cart page the order total is in black text. Next is that the cart icon on the right side pulls out and the checkout button is underneath the paypal buttons. So you can only click the paypal buttons and can't click view cart or checkout normally. The website is https://www.jakewangner.com
![site-issue-1](https://user-images.githubusercontent.com/69008909/88951035-11c1ec80-d25b-11ea-958c-3e666c82fc04.JPG)
![site-issue-2](https://user-images.githubusercontent.com/69008909/88951038-11c1ec80-d25b-11ea-8bd5-a7c6ae5868fd.JPG)

**Comment by tammullen** [comment] 2020-07-30 17:20
Hi @jakewangner 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party theme Block Shop. 
​
Please contact the author of the theme directly for further help. 

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-07-30 17:20 UTC
