### ISSUE TITLE
While updating the order status, its post_date gets updated as well.

### ISSUE THREAD

**Issue by Aparajita591** [woocommerce/woocommerce#24697] opened 2019-09-27 05:54 UTC
I have found an issue while updating the order status using WooCommerce API. Basically it is updating the post_date automatically.
For example,
Let's say a post has the following values currently:
post_date_gmt = "2019-09-22 08:40:19"
post_date = "2019-09-21 08:40:19"

If I manually change the post_date_gmt value of a post to "2019-09-23 08:40:19".
Now I update the order status via Woocommerce orders API.
_Kindly Note: I am just updating the status and nothing else._

But as the status updates, its post_date value is updating to "2019-09-23 08:40:19". But I don't want my post_date value to be updated

**Comment by rodrigoprimo** [comment] 2019-09-30 19:35
I was not able to reproduce this issue on my local environment. I started with an order that I already had on my WooCommerce install. The ID of this order is 65. I first checked the order date and its status:

```
MariaDB [wccore]> select post_date, post_date_gmt, post_status from wp_posts where id = 65;
+---------------------+---------------------+---------------+
| post_date           | post_date_gmt       | post_status   |
+---------------------+---------------------+---------------+
| 2019-09-30 19:27:59 | 2019-09-30 19:27:59 | wc-processing |
+---------------------+---------------------+---------------+
```

Then I updated the order status using the REST API:

```
curl -X PUT https://example.com/wp-json/wc/v3/orders/65 \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "status": "completed"
}'
```

After that, I rechecked the fields on MySQL, and the post_date and post_date_gmt didn't change:

```
MariaDB [wccore]> select post_date, post_date_gmt, post_status from wp_posts where id = 65;
+---------------------+---------------------+--------------+
| post_date           | post_date_gmt       | post_status  |
+---------------------+---------------------+--------------+
| 2019-09-30 19:27:59 | 2019-09-30 19:27:59 | wc-completed |
+---------------------+---------------------+--------------+
```

I am closing this issue as non-reproducible. If I missed something, please leave a comment, and I will take a second look.

**Closed by rodrigoprimo** 2019-09-30 19:35 UTC
