### ISSUE TITLE
"Coupons" Update Notification Makes "Coupons" Disappear

### ISSUE THREAD

**Issue by wallswonders** [woocommerce/woocommerce#27091] opened 2020-07-21 20:44 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When I login to one of my woocommerce site today, it showed a message saying the Coupons now is under Marketing, and said would remove the legacy coupons table.
The Coupons now under Woocomemrce is gone and does NOT appear under "marketing" as stated.
However, the coupon box on the Checkout page is also gone, even I have checked the “Enable the use of coupon codes” in Woocommerce setting is enable.

**Expected behavior**
"Coupons" should have moved under "Marketing" and not disappeared entirely. The coupon box should still appear on the checkout page.

**Actual behavior**
There is now nowhere to create coupons, nor enter coupon codes upon checkout.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to '...' Login to your account
2. Click on '....' Coupons, see the notification, click accept the notification. 
4. See error See that "Coupons" is gone and does not appear under Marketing.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

I have no idea how to program, nor answer most of these questions. This is a larger issue, as I was able to find someone else asking about it in the help section of Wordpress.org. I hope this is enough to have the issue resolved. Thank you mucho.

**Comment by tammullen** [comment] 2020-07-30 13:57
Hi @wallswonders 

Sorry for the delay in replying, thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

![Screenshot 2020-07-30 at 14 56 33](https://user-images.githubusercontent.com/24649833/88931608-f6fc7180-d274-11ea-837d-a92c70664bbf.png)


We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.

**Comment by juliaamosova** [comment] 2020-08-05 20:57
Hi @wallswonders,

Can you please let us know if you are still experiencing the issue? If so, it will be great if you could perform a theme and plugins conflict on your site. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-08-12 14:03
Hi @wallswonders,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-08-12 14:03 UTC
Labels: status: needs feedback
