### ISSUE TITLE
Woocommerce Coupon Code list shows some duplicates and hides some other coupons

### ISSUE THREAD

**Issue by gnuyork** [woocommerce/woocommerce#17033] opened 2017-10-03 11:10 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Issue 
I've created 100 coupon codes in WooCommerce. When I go to the coupon list overview (showing 30 items per page) the following strange behavior occurs:

- the list shows exactly 100 coupons,
- but some of the created coupon codes are missing,
- instead of them other coupon codes are listed multiple times (exactly the same coupons with the same IDs).

When I use the search box to search for one of the missing coupons the system finds it.

Setting up the view to show all created codes on one page (I've set it to 999 items per page) solves the problem. Therefore I guess that the problem is related to the splitting of the database query results into subsets for pagination.

## Steps to reproduce the issue

1. Create a lot of coupon codes and set up the coupon code overview to show less items per page.
2. Browse through the pages to see that there are duplicate and missing items

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by rodrigoprimo** [comment] 2017-10-03 14:05
Thanks for your report.

I was not able to reproduce this problem on a clean WordPress install running only WooCommerce core. I used the following shell code to generate 100 coupons and they were all listed in the admin coupons page.

```
for ((i=1;i<=100;i++)); do
    wp --user=1 wc shop_coupon create --code=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1) --amount=50;
done
```

Closing this issue for now. Please reopen it if you can reproduce this problem in an environment where only WooCommerce core is active or if you have more information to share that might help us reproduce the issue.

**Closed by rodrigoprimo** 2017-10-03 14:05 UTC
