### ISSUE TITLE
Variation product not added to cart in mobile mode if no default variation is selected

### ISSUE THREAD

**Issue by DjMagicFingers** [woocommerce/woocommerce#21417] opened 2018-09-22 09:37 UTC
A product with several variations is not added to cart when selecting one of the variations while using a mobile device (works fine in tablet and desktop mode), if the field "default value" is empty on the variations form.

1. Go to product details, make sure you have several variations of the product and that default variation is NOT setup.
2. go to the store from a mobile phone device and find the specific product.
3. Add the product to cart
4. check cart to see that the product is not added.

### WordPress Environment ###

Home URL: https://www.lakonim.co.il
Site URL: https://www.lakonim.co.il
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.0
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.6.40
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

````

**Comment by claudiulodro** [comment] 2018-09-24 17:46
Hi there.

I wasn't able to reproduce this problem on a site running a default theme and only WooCommerce.

I notice many JavaScript errors coming from the theme on your site. Your theme also seems to have special handling for mobile vs. desktop, and WooCommerce doesn't have that handling for Add to Cart. My recommendation is to upgrade your theme to the latest version if possible or contact the theme authors. It also may be a plugin conflict with different plugins you are running. I recommend following the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4) for troubleshooting the issue to get a better view of where specifically the problem is coming from. Hope this helps.

As this issue does not seem to be from the core WooCommerce plugin, I am closing this issue. Thanks.

**Closed by claudiulodro** 2018-09-24 17:46 UTC
