### ISSUE TITLE
Order review - Payment methods stuck. It keeps loading and nothing happens

### ISSUE THREAD

**Issue by davramos** [woocommerce/woocommerce#17905] opened 2017-11-24 12:52 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a product to the shopping cart
2. Go to checkout
3. The block of order review and payment methods is not working, it keeps loading

## Expected/actual behavior

The problem is when the users tries to complete the checkout, they cannot chose the payment method because it keeps loading and nothing happens. This issue is not happening every single time, some orders get through but quite often it fails so the customers cannot complete the order.

I have tried to deactivate all the plugins, reinstall Woocommerce, modify payment methods and nothing solves the issue. Furthermore, it is quite weird because sometimes it has a strange behavior. It loads a discount code not used by this customer, it is like if the sessions are replicated across different users. I am deleting the sessions, through the Tools of Woocommercer but it doesn´t make any difference neither.

Please, this is quite urgent as customers cannot pay for their products!

Many thanks in advance.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

`
### WordPress Environment ###

Home URL: http://www.fifantastic.com
Site URL: http://www.fifantastic.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.6.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25
PHP Post Max Size: 55 MB
PHP Time Limit: 300
PHP Max Input Vars: 100000
SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 55 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Publicación remota: ✔
Obtención remota: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (24) ###

Polylang: por Frédéric Demarle – 2.2.5
Límitador de intentos de login: por Johan Eenfeldt – 1.7.1
Share Buttons by AddThis: por The AddThis Team – 6.1.1
Akismet Privacy Policies: por Inpsyde GmbH – 1.1.2
Akismet Anti-Spam: por Automattic – 4.0.1
Batch Comment Spam Deletion: por Pippin Williamson – 1.0.6
Delete Pending Comments: por Nicolas Kuttler – 0.2.1.1
DNUI: por Nicearma – 2.5.7
Easy FancyBox: por RavanH – 1.6
Google AdSense: por Google – 1.2.1
MailChimp for WordPress: por ibericode – 4.1.11
Max Mega Menu: por Tom Hemsley – 2.4
P3 (Plugin Performance Profiler): por GoDaddy.com – 1.5.3.9
Popup Builder PRO: por Sygnoos – 3.1.4
Redirection: por John Godley – 2.9.2
Related Posts by Sovrn: por Sovrn
zemanta – 1.14

Smart Passworded Pages: por Brian Layman – 2.0.0
TinyMCE Advanced: por Andrew Ozz – 4.4.1
WF Cookie Consent: por wunderfarm – 1.1.2
WooCommerce Checkout Manager: por Visser Labs – 4.1.6
WooCommerce: por WooThemes – 2.5.5
Yoast SEO: por Equipo Yoast – 5.7.1
WP Super Cache: por Automattic – 1.5.8
WP-Usuario-Avatar: por flippercode – 2.0.9

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Base de la tienda: #15036 - /tienda
Carrito: #15037 - /carro
Finalizar compra: #15038 - /finalizar-comprar
Mi cuenta: #15039 - /mi-cuenta

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Nexus
Version: 1.7.3
Author URL: http://www.elegantthemes.com
Child Theme: ✕ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: : Cómo crear un tema hijo

WooCommerce Support: No declarada

### Templates ###

Overrides: Nexus/Nexus/woocommerce/emails/customer-completed-order.php
Nexus/Nexus/woocommerce/emails/customer-processing-order.php

`


```
</details>

**Comment by claudiosanches** [comment] 2017-11-27 13:39
Not able to reproduce it.
Generally things like what you are experiencing comes from errors on themes or other plugins.
Like fatal errors on ajax request or even JavaScripts.

Closing since is not an issue on WooCommerce core.

**Closed by claudiosanches** 2017-11-27 13:39 UTC
