### ISSUE TITLE
When adding product to manual order, WC incorrectly offers parent of variable product

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce#21759] opened 2018-10-30 19:14 UTC
**Describe the bug**
When you are adding products to an order within wp-admin, and begin typing the name of a variable product, you will be offered the parent product's name, without a specified variation name. This normally invalid psuedo-variation can then be added to the order and will be priced at the lowest price of the product's variations.

**Screenshots**
![product-price-when-manually-entered-in-woo-commerce](https://user-images.githubusercontent.com/20285748/47743871-0be64400-dc4e-11e8-8456-720e15424c2c.jpg)

**Expected behavior**
If the parent product is offered as a search result and selected within wp-admin as above, it should at least be added to the order using the default variation if one is set (with the default variation name and price). 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment] 2018-10-31 08:14
If you select the parent variation it will by default just show the lowest priced product's price.

Since the backend is for manual order manipulation there are situations where you would want to just add the main variable product and then assign custom meta and prices to it which does not match a specific variation.

This is not a bug but something that allows store managers more flexibility for managing orders. Think of a one time special order of a specific product, you may offer different variations by default but you could offer a customer a special request and in such case you do not want to assign the product to a variation.

Closing as won't fix.

**Closed by kloon** 2018-10-31 08:14 UTC

**Comment by ProactiveCode** [comment] 2018-11-01 10:41
Hi, just to illustrate my use case. We have regional product pricing, with some councils offering cheaper subsidised product.

By defaulting to the cheapest price, any call centre staff member that selects the top level product will accidentally grant the most extreme subsidised price. 

Could there be an option to select by cheapest or standard pricing?
