### ISSUE TITLE
"Undefined index: billing_email" when email field is removed

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#29263] opened 2021-03-02 17:20 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When remove email field using snippet from this official site:
https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/#section-2
```
add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );
function custom_override_checkout_fields( $fields ) {
     unset($fields['billing']['billing_email'] );
     return $fields;
}
```

it will cause warning in "wp-content/plugins/woocommerce/includes/class-wc-checkout.php" on line: 369 message: "Undefined index: billing_email"

To see this warning you need to install debugger plugin like 'query monitor'.

**Expected behavior**
No warning message

**Actual behavior**
warning in "wp-content/plugins/woocommerce/includes/class-wc-checkout.php" on line: 369 message: "Undefined index: billing_email"

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. install 'query monitor' or other debugger plugin
2. try above code

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://wpsandbox2.organica-labs.com
Site address (URL): https://wpsandbox2.organica-labs.com
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.18-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB-1:10.4.13+maria~bionic
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 10.37MB
Database Data Size: 7.71MB
Database Index Size: 2.66MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_actions_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_automations_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_logs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_triggers_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_dimension: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_fields_matching: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_label_sheets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_paper_formats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_template_to_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_barcode_v3_user_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_commercekit_waitlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commercekit_wishlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commercekit_wishlist_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_digits_blocked_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_digits_mobile_otp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_digits_requests_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_loginizer_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.14MB + Engine InnoDB
wp_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wp_posts: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wa_confirmationlinks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wa_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wa_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

_pods_pod: 1
attachment: 20
custom_css: 1
customize_changeset: 19
dtwcbe_woo_library: 1
echo: 4
elementor_library: 1
nav_menu_item: 1
page: 13
post: 2
product: 29
product_variation: 3
revision: 45
shop_order: 229
wpcf7_contact_form: 1
xxx_post_type: 5
xxxposttype: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Query Monitor: by John Blackbourn – 3.6.7
WooCommerce: by Automattic – 4.9.0 (update to version 5.0.0 is available)

### Inactive Plugins (46) ###

Ajax Load More: by Darren Cooney – 5.4.2.1
Akismet Anti-Spam: by Automattic – 4.1.7
Astra Pro: by Brainstorm Force – 2.7.2
ATR structured sku generator for Woocommerce: by Yehuda Tiram – 2.0.1 – Installed version not tested with active version of WooCommerce 4.0
Barcode Printing for WooCommerce & Contact Form 7 - (demo): by UkrSolution – 3.2.0
Cart All In One For WooCommerce: by VillaTheme – 1.1.0
CommerceGurus Commercekit: by CommerceGurus – 1.1.7
Contact Form 7: by Takayuki Miyoshi – 5.3.2
Debug This: by WPChill – 0.6.3
DIGITS: Wordpress Mobile Number Signup and Login: by UnitedOver – 7.5.0.3
Easy Auto SKU Generator for WooCommerce: by Dan Zakirov – 1.0.4
Elementor: by Elementor.com – 3.0.14
Elementor Pro: by Elementor.com – 3.0.8
Email Verification / SMS verification / Mobile Verification: by miniOrange – 3.6.3
Facebook for WooCommerce: by Facebook – 2.2.0
Google Ads & Marketing by Kliken: by Kliken – 1.0.6
GP Premium: by Tom Usborne – 1.12.3
Hello Dolly: by Matt Mullenweg – 1.7.2
Kirki Customizer Framework: by David Vongries – 3.1.6
Loco Translate: by Tim Whitlock – 2.5.0
Loginizer: by Softaculous – 1.6.6
Nextend Social Login: by Nextendweb – 3.0.26
Ongkoskirim.id: by jogja.camp – 1.0.6 – Installed version not tested with active version of WooCommerce 4.0
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.7.26
PowerPack Pro for Elementor: by Team IdeaBox - PowerPack Elements – 2.2.1
Products Admin Notes Simple: by Jamie Hall – 1.1
RY WC City Select: by Richer Yang – 1.0.10
Show Hooks: by rafiq91 – 0.1.2
Side Cart WooCommerce: by XootiX – 2.1 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.40 (update to version 4.1.41 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.38
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.11
WooCommerce JNE Shipping ( Free Version ): by AgenWebsite – 8.2.5 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Load More Products: by BeRocket – 1.1.7.5
WooCommerce One Page Checkout: by Automattic – 1.7.10
WooCommerce Page Builder For Elementor: by DawnThemes – 1.1.6.2
WooCommerce Product SKU Generator: by SkyVerge – 2.4.5
WooCommerce Product Table: by Barn2 Plugins – 2.8
WooCommerce Shipment Tracking: by WooCommerce – 1.6.24
WooCommerce Smart COD: by woosmartcod.com – 1.6.1
Woongkir: by Sofyan Sitorus – 1.2.16
WP Webhooks: by Ironikus – 2.1.2
WunderAutomation: by Wundermatics – 1.5.11 – Installed version not tested with active version of WooCommerce 4.0
Yandex Metrica: by Mustafa Uysal – 1.8.2
YITH WooCommerce Barcodes Premium: by YITH – 2.0.3
YITH WooCommerce Wishlist: by YITH – 3.0.17

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: IDR (Rp)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Flatsome Child
Version: (update to version 0 is available)
Author URL: https://childthemewp.com/flatsome/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.13.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php


### Action Scheduler ###

Complete: 280
Oldest: 2021-01-30 17:50:28 +0000
Newest: 2021-03-02 17:10:05 +0000

Pending: 1
Oldest: 2021-03-03 06:14:27 +0000
Newest: 2021-03-03 06:14:27 +0000

`
```
</details>

**Comment by tammullen** [comment] 2021-03-08 00:17
Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 
​

- I installed Code Snippets plugin https://wordpress.org/plugins/code-snippets/
- I installed Query Monitor
- I confirmed email appears on checkout
![Screenshot_2021-03-08_at_00_12_55](https://user-images.githubusercontent.com/24649833/110260280-65d84080-7fa3-11eb-8495-4c67202b232d.png)
- I added your code as a snippet in Code Snippets
![Screenshot 2021-03-08 at 00 16 52](https://user-images.githubusercontent.com/24649833/110260333-a1730a80-7fa3-11eb-8894-42c937fda4e5.png)
- Confirmed email not longer appears on checkout
![Screenshot 2021-03-08 at 00 13 12](https://user-images.githubusercontent.com/24649833/110260283-683a9a80-7fa3-11eb-9acf-8ac042042ff2.png)

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
​

**Closed by tammullen** 2021-03-08 00:17 UTC

**Comment by erikdemarco** [comment] 2021-03-08 06:29
@tammullen 

To make sure once again. I do fresh installation of wordpress and woocommerce. Its same. I get this error:
=> https://ibb.co/4JnMSrd

I'm sure its because you set your php.ini setting to hide php warning or maybe you set your php error level to low.

The logic is like this: Let's look at the error line:
=> https://github.com/woocommerce/woocommerce/blob/30d7b2ce9d4ae732d1b036bd221328e5b7e870b8/includes/class-wc-checkout.php#L369

If you see inside the function all data inside variable '$data' is checked using 'isset'. only $data['billing_email'] is not checked first.

**Comment by buddudevelopers** [comment] 2021-09-14 17:50
@tammullen This issue was erroneously closed. I think you could not reproduce because of your error level. I am also experiencing it
![undefinedindex](https://user-images.githubusercontent.com/56328383/133308417-143de658-ea32-45ca-a203-b09d066ab5e5.PNG)

**Comment by ser** [comment] 2022-12-22 11:43
I can confirm this bug

**Comment by AforDesign** [comment] 2023-09-26 17:16
Still present in WooCommerce 8.1.1
Now at line 424
