### ISSUE TITLE
WooCommerce 3.5.1 use parent theme templates instead of child 

### ISSUE THREAD

**Issue by jflaflamme** [woocommerce/woocommerce#21869] opened 2018-11-09 08:31 UTC
**Describe the bug**
The child theme WooCommerce templates seem not overriding the parent.

**To Reproduce**
Precisely if I do a change in single-product/tabs/tabs.php (and WooCommerce status clearly show this template as used) it is not working. If I delete the parent file single-product/tabs/tabs.php then the child is used. 

**Expected behavior**
Expect to override the file with the child as it was working before latest updates.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2018-11-09 13:38
I tested this with Storefront & a Storefront child and could not reproduce the problem.

**Comment by jflaflamme** [comment] 2018-11-10 01:28
I read you on Storefront, as my bug report, I didn't check that it happen or not with storefront theme. 
But also, on WooCommerce status,  it says it is loading the one (tabs.php) in child theme but it is not.

I am on WP 4.9.8, using the bridge theme 17.

Permissions are ok as well. If I delete or rename the parent file/folder the child equivalent is used. Not for all but only for single-product folder or files underneath. 

Other files are using the child theme as expected, only the single-product folder create this bug. That's also the folder from WooCommerce 3.5 copied there with just a HELLO randomly in it to see the difference. Appearing only when the parent theme equivalent is not there.

I can replicate this with any files under this folder and only happens since WooCommerce 3.5.
AFAIK, the get_template part is not supplied by the themes.

I saw a commit in 3.5 related to templates .. maybe that could be related.

Best.

**Comment by kloon** [comment] 2018-11-11 19:56
Can you please try and replicate this with another theme such as Storefront or Twentyseventeen? It's likely an issue with your theme that is causing this, I would also suggest you test this with all plugins except WooCommerce disabled.

As @rrennick I am unable to reproduce and I tested with Storefront as well as Twentyseventeen themes.

Closing, will gladly reopen when you have tested with a different theme and all plugins disabled and can provide steps to replicate it with another theme.

**Closed by kloon** 2018-11-11 19:56 UTC
