### ISSUE TITLE
Find variations using the parent SKU when creating orders manually

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#25543] opened 2020-01-31 15:05 UTC
**Is your feature request related to a problem? Please describe.**

I have a customer, who is:

- creating orders manually using the backend
- adding products using the SKU for search
- Adding only one SKU (at product level) for variable products
  - no extra SKU for each variation

The **problem** 

- Variations are not found, when using the SKU within the search dialog.
- but the parent SKU is shown as placeholder in each variation, which implies, that this is also the SKU for the variation

**Describe the solution you'd like**

Also show variations using the SKU of the "parent" product for search.

**Comment by mdmoore** [comment] 2020-02-10 19:00
I've removed the enhancement label in favor a bug after noticing that this previously worked well.  In WooCommerce 3.8, variable products that contained **only parent SKUs** were found in the search when adding a product to an order.  As of WooCommerce 3.9, those variable products are no longer found.

**Comment by henrikdamdk** [comment] 2020-02-17 18:52
I have the exact same issue as described by @scrobbleme. Would be really nice to get a fix for this 🙏 

And perhaps anyone has an idea for any temporary fix?

**Comment by ObliviousHarmony** [comment] 2020-02-17 23:46
Hi scrobbleme,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

- Create a variable product and set the SKU only on the parent.
- Attempt to add the product to an order, will not be visible.

This bug is another caused by #25162. We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Closed** 2020-08-12 19:58 UTC
Labels: bug, priority: high
