### ISSUE TITLE
[REST API] Multiple tax class POST concurrency issue

### ISSUE THREAD

**Issue by tsoftp** [woocommerce/woocommerce#22164] opened 2018-12-06 18:09 UTC
**Describe the bug**
Using a Qt c++ desktop app to connect to the REST API I cannot successively create tax classes despite the API response being successfull (returning all the supposedly created tax classes objects). For instance if I try to creat 3 tax classes only the last one to be POSTed will actually be created even though all three returned sucess responses.

I am using separate POST requests with only one tax classe per request.

Maybe this is a concurrency problem from the API?

**To Reproduce**
1. Programmaticly try to create multiple tax classes (in quick succession?)
2. Apparenly no error is returned from the API
3. Problem: only one of the multiple post requests actually creates a tax class.

**Screenshots**

![bug](https://user-images.githubusercontent.com/45667933/49603025-fb7a6500-f981-11e8-946b-fa059d3d24f7.png)

In this example I'm trying to create two tax classes. I am executing this code twice.

You can see that the API's response is successfull on both requests, yet if push the "create tax classes" button on my app again it will tell me only the tax class "Isento" was actually created the first time, because it now only creates the other tax class, "Normal".

**Expected behavior**
I expect the API to create multiple tax classes when I tell it to using the desktop app, I only want to use this code snippet once, creating all my tax classes. This isn't possible with the current behaviour of the woocommerce API.
I have tried the exact same code with products and it works fine. 

Again all of this is using separate POST requests, I am NOT trying to create multiple tax classes on the same request.

Thank you for your time!

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://192.168.0.175/wordpress
Site URL: http://192.168.0.175/wordpress
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.10-0ubuntu0.18.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 18000
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.66MB
Database Data Size: 1.75MB
Database Index Size: 0.91MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.05MB + Index: 0.05MB
wp_postmeta: Data: 0.09MB + Index: 0.06MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 1
page: 8
post: 2
product: 15
revision: 2
shop_order: 2
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5 – 2.4.1 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rrennick** [comment] 2018-12-07 18:08
I'm not able to reproduce this with my rest client.

**Comment by tsoftp** [comment] 2018-12-10 09:36
I never happened to me on Postman either, I'm guessing because I can't make requests as "fast" as my program, hence cause concurrency?

**Comment by rrennick** [comment] 2018-12-10 16:53
If you wanted to try to confirm the issue you could try submitting the same tax class requests with a different REST tool.

**Comment by tsoftp** [comment] 2018-12-10 18:23
> If you wanted to try to confirm the issue you could try submitting the same tax class requests with a different REST tool.

Okay so I was able to consistently reproduce this. 
Steps:
1) Using postman I created two collections, each collection with 10tax class post requests.
2) Used Postman's Collection Runner to run both collections simultaneously.
3) Every single request returns Status 201 Created.

Problem: Only 9-12 of the requested 20 tax classes are ACTUALLY created on the shop.

**Comment by rrennick** [comment] 2018-12-12 14:58
> Maybe this is a concurrency problem from the API?

The reproduce steps suggest that this might be the case.

**Comment by tsoftp** [comment] 2018-12-13 17:24
> The reproduce steps suggest that this might be the case.

Anymore info on this? 

Should I wait for a bugfix, since this is now proven reproducible?

Thanks once again.

**Comment by rrennick** [comment] 2018-12-13 21:02
> Should I wait for a bugfix, since this is now proven reproducible?

If it is a concurrency issue then there won't be a quick bug fix for this. In the interim I suggest you look at ways to add the classes at a slower rate.

**Comment by mikejolley** [comment] 2019-02-12 16:31
We'd need to add something like an etag or checks on the last update to work around this type of concurrentcy issue. WordPress core doesn't support this at present.

https://sookocheff.com/post/api/optimistic-locking-in-a-rest-api/
https://www.kennethlange.com/avoid-data-corruption-in-your-rest-api-with-etags/
https://github.com/WP-API/WP-API/issues/1856

@claudiosanches ?

**Comment by claudiosanches** [comment] 2019-02-12 17:08
@tsoftp @mikejolley @rrennick this only happens on tax classes, because we use the same option to save all tax classes,  should be nice implement etag, but this sounds like something that should be nice on WP core, still we can move this tax classes into a new table or something like, instead of just an option on `wp_options`.

**Comment by dhavalgshah** [comment] 2019-03-20 12:57
While this is a WordPress core [bug (see #31245)](https://core.trac.wordpress.org/ticket/31245) and will affect even on normal requests, this can be remedied by either:

1.  Not using autoload on WC options. By explicitly declaring `$autoload` to `off` in `add/update/delete_option` call across WooCommerce. In most requests, we are not even using half* of the options autoloaded this way. We can use WooCommerce's own caching, which is better at invalidation.

2. Force delete 'autoload' cache when adding/updating/deleting options which are marked to autoload. Similar workaround is used at many sites including at [WordPress VIP](https://core.trac.wordpress.org/ticket/31245#comment:57).


----

_WooCommerce on a fresh install uses 79 autoloaded options._
Calling `wp option list --search=woocommerce* --autoload=on --field=option_name --format=csv` gives following output:

```
woocommerce_store_address
woocommerce_store_address_2
woocommerce_store_city
woocommerce_default_country
woocommerce_store_postcode
woocommerce_allowed_countries
woocommerce_all_except_countries
woocommerce_specific_allowed_countries
woocommerce_ship_to_countries
woocommerce_specific_ship_to_countries
woocommerce_default_customer_address
woocommerce_calc_taxes
woocommerce_enable_coupons
woocommerce_currency
woocommerce_currency_pos
woocommerce_price_thousand_sep
woocommerce_price_decimal_sep
woocommerce_price_num_decimals
woocommerce_shop_page_id
woocommerce_cart_redirect_after_add
woocommerce_enable_ajax_add_to_cart
woocommerce_placeholder_image
woocommerce_weight_unit
woocommerce_dimension_unit
woocommerce_enable_reviews
woocommerce_enable_review_rating
woocommerce_manage_stock
woocommerce_notify_no_stock_amount
woocommerce_hide_out_of_stock_items
woocommerce_stock_format
woocommerce_prices_include_tax
woocommerce_tax_based_on
woocommerce_shipping_tax_class
woocommerce_tax_round_at_subtotal
woocommerce_tax_classes
woocommerce_tax_display_shop
woocommerce_tax_display_cart
woocommerce_price_display_suffix
woocommerce_shipping_cost_requires_address
woocommerce_shipping_debug_mode
woocommerce_registration_privacy_policy_text
woocommerce_checkout_privacy_policy_text
woocommerce_cart_page_id
woocommerce_checkout_page_id
woocommerce_myaccount_page_id
woocommerce_checkout_pay_endpoint
woocommerce_checkout_order_received_endpoint
woocommerce_myaccount_add_payment_method_endpoint
woocommerce_myaccount_delete_payment_method_endpoint
woocommerce_myaccount_set_default_payment_method_endpoint
woocommerce_myaccount_orders_endpoint
woocommerce_myaccount_view_order_endpoint
woocommerce_myaccount_downloads_endpoint
woocommerce_myaccount_edit_account_endpoint
woocommerce_myaccount_edit_address_endpoint
woocommerce_myaccount_payment_methods_endpoint
woocommerce_myaccount_lost_password_endpoint
woocommerce_logout_endpoint
woocommerce_api_enabled
woocommerce_single_image_width
woocommerce_thumbnail_image_width
woocommerce_checkout_highlight_required_fields
woocommerce_permalinks
woocommerce_queue_flush_rewrite_rules
woocommerce_admin_notices
woocommerce_meta_box_errors
woocommerce_catalog_rows
woocommerce_catalog_columns
woocommerce_maybe_regenerate_images_hash
woocommerce_product_type
woocommerce_allow_tracking
woocommerce_ppec_paypal_settings
woocommerce_cheque_settings
woocommerce_bacs_settings
woocommerce_cod_settings
woocommerce_flat_rate_1_settings
woocommerce_flat_rate_2_settings
woocommerce_version
woocommerce_db_version
```

**Comment by mikejolley** [comment] 2019-03-20 15:31
Added new table @claudiosanches suggested in https://github.com/woocommerce/woocommerce/pull/23093 Feedback can be added there or we can choose a different approach.

**Closed by mikejolley** 2019-03-20 15:31 UTC
Labels: api, status: needs feedback
