### ISSUE TITLE
Session data serialize issue in database

### ISSUE THREAD

**Issue by rufus87** [woocommerce/woocommerce#24714] opened 2019-09-28 17:43 UTC
**Describe the bug**
Session data stored as incorrect serialized value in database.

**To Reproduce**
1. Go to Shop
2. Add any product to cart
3. Look in sessions table in database
You should see something like 
```
a:11:{s:4:"cart";s:410:"a:1:{s:32:"34173cb38f07f89ddbebc2ac9128303f";a:11:{s:3:"key";s:32:"34173cb38f07f89ddbebc2ac9128303f";s:10:"product_id";i:30;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:1;s:9:"data_hash";s:32:"b5c1d5ca8bae6d4896cf1807cdf763f0";s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:13:"line_subtotal";d:18;s:17:"line_subtotal_tax";i:0;s:10:"line_total";d:18;s:8:"line_tax";i:0;}}";s:11:"cart_totals";s:405:"a:15:{s:8:"subtotal";s:5:"18.00";s:12:"subtotal_tax";d:0;s:14:"shipping_total";s:4:"0.00";s:12:"shipping_tax";d:0;s:14:"shipping_taxes";a:0:{}s:14:"discount_total";d:0;s:12:"discount_tax";d:0;s:19:"cart_contents_total";s:5:"18.00";s:17:"cart_contents_tax";d:0;s:19:"cart_contents_taxes";a:0:{}s:9:"fee_total";s:4:"0.00";s:7:"fee_tax";d:0;s:9:"fee_taxes";a:0:{}s:5:"total";s:5:"18.00";s:9:"total_tax";d:0;}";s:15:"applied_coupons";s:6:"a:0:{}";s:22:"coupon_discount_totals";s:6:"a:0:{}";s:26:"coupon_discount_tax_totals";s:6:"a:0:{}";s:21:"removed_cart_contents";s:6:"a:0:{}";s:22:"shipping_for_package_0";s:372:"a:2:{s:12:"package_hash";s:40:"wc_ship_674a61ef62ac3cee96b2f827a6b038a7";s:5:"rates";a:1:{s:11:"flat_rate:1";O:16:"WC_Shipping_Rate":2:{s:7:"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10531492/65820354-c143c200-e238-11e9-8dbf-c4dea20d8b13.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://wordpress.local
Site address (URL): https://wordpress.local
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29
PHP Version: 7.2.19-0ubuntu0.18.04.2
PHP Post Max Size: 8 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.27-0ubuntu0.18.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 3.86MB
Database Data Size: 2.86MB
Database Index Size: 1.00MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gamipress_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gamipress_logs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gamipress_user_earnings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gamipress_user_earnings_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17
WooCommerce: by Automattic – 3.7.0

### Inactive Plugins (2) ###

GamiPress: by GamiPress – 1.7.7
Yoast SEO: by Team Yoast – 12.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #21 - /shop/
Cart: #22 - /cart/
Checkout: #23 - /checkout/
My account: #24 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Sixteen
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 1
Oldest: 2019-09-28 17:23:32 +0000
Newest: 2019-09-28 17:23:32 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by rodrigoprimo** [comment] 2019-09-30 20:05
I was not able to reproduce this issue on my local environment. Adding a product to cart results in a valid entry being added to `wp_woocomerce_sessions` and not an invalid entry as it is happening in your environment. I will close this issue for now, but please leave a comment if I missed something and I will take a second look.

**Closed by rodrigoprimo** 2019-09-30 20:05 UTC

**Comment by rufus87** [comment] 2019-09-30 20:28
Thanks a lot for your time.

It's very strange that you can't reproduce the issue, as it really happens. Copy and paste the value from `session_value` column, and you will find invalid serialized value.

I tried to show the same in the screenshot in the ticket description.

Thanks again.

**Comment by rodrigoprimo** [comment] 2019-10-02 17:42
I'm sorry but I can't help you further as this is not a support forum. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

So far this doesn't look like a WooCommerce core bug, but if you find more information indicating that it is please leave a comment and I will take a second look. Thanks.
