### ISSUE TITLE
[GlobalStep] On MAC, "403 forbidden…” error message is displayed while uploading comment on Newest Product and On Sale Product block

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26708] opened 2020-06-04 15:12 UTC
**Environment:**
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Go to Post.
3. Add new post.
4. Select block type as Newest Product or On Sale Product.
5. Click on Publish button.
6. Click on View post.
7. Scroll to the Comment section.
8. Add some comment and tap on Comment button.
9. Observe that "403 forbidden…” error message is displayed while uploading comment on Newest Product and On Sale Product block

**Actual Result:**
"403 forbidden…” error message is displayed while uploading comment on Newest Product and On Sale Product block.

**Expected Result:**
"403 forbidden…” error message should not be displayed while uploading comment on Newest Product and On Sale Product block.

[#2636.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4730958/2636.zip)

**Comment by juliaamosova** [comment] 2020-06-05 18:03
Thanks @nerrad! I reached out to WP Engine via live chat and confirmed that the Heartbeat being disabled is indeed expected. Quoting WP Engine support agent below:

>Alright! So the two main updates that we've had with our Heartbeat Control is we throttle the heartbeat rate from the default 15 seconds down to every 60 seconds. And we've also disabled the Heartbeat script entirely on non-editing pages. The screenshot you've sent me is a non-editing page which would be the reason why it's showing as missing. 

I was also offered to have the Heartbeat disabled on non-editing pages but declined since this is a test site. It is good to know that we can have it enabled if needed though. 

Closing this as a non-issue.

**Comment by juliaamosova** [comment] 2020-06-05 18:34
Hi @gglobalstep,

Thanks for raising the issue. I took a look at the video you provided and I noticed that you actually trying to leave a review won the page that had not been published yet. You are previewing a non-published page and leaving a review on it. The 403 error seems to be expected. 

Some screenshots are below taken from the video:

![atomic1](https://user-images.githubusercontent.com/19143190/83911016-8a17a000-a739-11ea-9c98-05dd72200976.jpg)

![atomic2](https://user-images.githubusercontent.com/19143190/83911024-8dab2700-a739-11ea-951c-3b24827773be.jpg)

![atomic3](https://user-images.githubusercontent.com/19143190/83911039-91d74480-a739-11ea-9656-915e7831d8e2.jpg)

Perhaps we can have a pop-up message letting the user know that they are trying to leave a comment on a non-published page in the preview. 

What do you think @nerrad?

**Comment by nerrad** [comment] 2020-06-05 21:28
There’s a couple things to consider here:

- This has to do with leaving a comment which isn’t really a WooCommerce core issue.
- It’s been a while since I dove into WP comments so it’s unclear to me currently whether this would be a WP core thing to address or something that a theme might address if it’s modifying default WP comment functionality (which I know themes can do), but my gut feeling here is that this is a WP core thing. 

So your suggestion is good, but likely something needing posted to the WP Trac if it’s verified this isn’t specific to themes.

**Comment by tammullen** [comment] 2020-10-22 19:16
As a part of this repository’s maintenance, I am closing this issue due to inactivity.

**Closed by tammullen** 2020-10-22 19:16 UTC
