### ISSUE TITLE
Woocommerce resets my settings every time it updates

### ISSUE THREAD

**Issue by 4pawscanineacademy** [woocommerce/woocommerce#25188] opened 2019-12-06 18:40 UTC
Hi,
I have a problem that Woocommerce keeps resetting my settings at random (so not always the same settings, and not always all settings) when it updates. 

I know that everyone always says to backup before you update, however, I never know when woocommerce updates.

Therefore, could you please ensure that woocommerce does not reset ANYTHING when it updates? It is quite annoying that I am loosing shipping money because it keeps adding the free shipping feature even though I've deleted it. I ever only notice once someone managed to order something with free shipping. I don't have orders every day as I am a very small business whose main customers are face-to-face customers, so I might only sell one item per month sometimes - and if woocommerce has updated in between then, then I ALWAYS lose the shipping money and have to pay for that myself which is not the plan. Please fix this.

**Comment by juliaamosova** [comment] 2019-12-09 13:14
Hi there @4pawscanineacademy,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue. 

Regarding your issue specifically - WooCommerce doesn't reset any settings during updates. Something else could be going on on your site. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-12-09 13:14 UTC
