### ISSUE TITLE
checkout fields are not customizeable

### ISSUE THREAD

**Issue by determin1st** [woocommerce/woocommerce#25142] opened 2019-11-29 21:45 UTC
```
add_filter('woocommerce_checkout_fields' , function($fields) {
  $fields['billing']['billing_first_name']['label'] = 'test 1'; // works
  $fields['billing']['billing_city']['label'] = 'test 2'; // doesnt work
  return $fields;
});
```

`priority` doesnt work too

**Comment by determin1st** [comment] 2019-11-30 14:20
The problem is in `woocommerce\assets\js\frontend\address-i18n.js` line `56`:

it forcefully replaces any custom label/placeholder if locale information present.. 
will try to find some quickfix..

**Comment by determin1st** [comment] 2019-11-30 14:26
https://wordpress.org/support/topic/address-i18n-js-overrides-custome-street-address-label/

**Comment by juliaamosova** [comment] 2019-12-03 13:08
@determin1st we have a guide on how to [customize checkout fields using actions and filters](https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/). Please take a look there and let us know if you find any issues.

**Comment by determin1st** [comment] 2019-12-03 18:00
@juliaamosova 

Definately, it should be corrected..

for example, https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/#section-2
the statement

> Hooking into the  woocommerce_checkout_fields filter lets you override any field.

is not true.. something may be done but not everything (like setting label/placeholder)

**Comment by juliaamosova** [comment] 2020-01-29 19:02
@determin1st apologies for the delayed response. 

In order to set a new label for the `billing_city` for example, you need to use `woocommerce_default_address_fields` filter as per [documentation](https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/#section-2). This filter is applied to all billing and shipping default fields. 

So for example, to change the `billing_city` label, you need to first unset the existing default label and then create a new custom one and make it required. 

Below in my snippet, I am changing the billing city label & also changing the label and placeholder of the order note field:

```
// Change checkout order note label & placeholder
// Hook in
add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );

// Our hooked in function - $fields is passed via the filter!
function custom_override_checkout_fields( $fields ) {
	 $fields['order']['order_comments']['label'] = 'My new shiny test label';
     $fields['order']['order_comments']['placeholder'] = 'My new shiny test placeholder';
     return $fields;
}

// Unsetting billing city checkout field
// Hook in
add_filter( 'woocommerce_checkout_fields' , 'partial_unsetting_checkout_fields' );
function partial_unsetting_checkout_fields( $fields ) {
     unset($fields['billing']['billing_city']);
     return $fields;
}

// Hook in
add_filter( 'woocommerce_default_address_fields' , 'custom_override_default_address_fields' );

// Our hooked in function - $address_fields is passed via the filter!
function custom_override_default_address_fields( $address_fields ) {
     $address_fields['billing_city']['label'] = 'My new billing city test label';
	 $address_fields['billing_city']['required'] = true;
     return $address_fields;
}
```

As a result, I am getting the following:

![checkout](https://user-images.githubusercontent.com/19143190/73387709-d739c000-42c8-11ea-953b-858bd6954a11.jpg)

>priority doesnt work too

Can you please specify what doesn't work exactly?

**Comment by determin1st** [comment] 2020-01-31 10:21
Oke, thanks Julia :]

I mean, you change `priority` to put **Email** before **Phone** (for example) and with `woocommerce_checkout_fields` it wont work (I'm not sure about it right now, made custom template to workaround these hooks).

**Comment by juliaamosova** [comment] 2020-02-04 18:47
>I mean, you change priority to put Email before Phone (for example) and with woocommerce_checkout_fields it wont work (I'm not sure about it right now, made custom template to workaround these hooks).

@determin1st I updated my snippet with priority to change the priority of the custom billing city field I created in my previous comment. I wanted for the billing city field to appear before `State` - as you can see in my previous screenshot, it currently appears after `ZIP` field. 

New updates snippet (that includes priority of the new custom billing city field):

```
// Change checkout order note label & placeholder
// Hook in
add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );

// Our hooked in function - $fields is passed via the filter!
function custom_override_checkout_fields( $fields ) {
	 $fields['order']['order_comments']['label'] = 'My new shiny test label';
     $fields['order']['order_comments']['placeholder'] = 'My new shiny test placeholder';
     return $fields;
}

// Unsetting billing city checkout field
// Hook in
add_filter( 'woocommerce_checkout_fields' , 'partial_unsetting_checkout_fields' );
function partial_unsetting_checkout_fields( $fields ) {
     unset($fields['billing']['billing_city']);
     return $fields;
}

// Hook in
add_filter( 'woocommerce_default_address_fields' , 'custom_override_default_address_fields' );

// Our hooked in function - $address_fields is passed via the filter!
function custom_override_default_address_fields( $address_fields ) {
     $address_fields['billing_city']['label'] = 'My new billing city test label';
	 $address_fields['billing_city']['required'] = true;
	 $address_fields['billing_city']['priority'] = 70;
     return $address_fields;
}
```

The result - billing city field now appears before `State`:

![city](https://user-images.githubusercontent.com/19143190/73775749-6427c200-477e-11ea-938f-d789f6dd54d3.jpg)

The priority of the fields for the reference:

![Screen Shot 2020-02-04 at 6 45 18 PM](https://user-images.githubusercontent.com/19143190/73775840-9507f700-477e-11ea-8cfc-663a99e7df09.png)

I am closing this issue as there seems to be no confirmed bug. 

Please feel free to comment on it in case I missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-02-04 18:47 UTC
Labels: status: needs feedback
