### ISSUE TITLE
Strange Qty element in the middle of a product page

### ISSUE THREAD

**Issue by StefanPeev** [woocommerce/woocommerce#29199] opened 2021-02-23 10:40 UTC
WordPress address (URL): https://localfonts.eu
Site address (URL): https://localfonts.eu
WooCommerce version: 5.0.0
WordPress version:	5.6.2
Browsers: Chrome, Firefox

A strange Qty element in the middle of a product page. See the picture below

![WC_01](https://user-images.githubusercontent.com/12949369/108830427-07d65100-75d2-11eb-8552-ca4660c2f840.jpg)

**Comment by juliaamosova** [comment] 2021-02-23 20:11
Hi @StefanPeev,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-02-23 20:11 UTC
