### ISSUE TITLE
Error al Iniciar el Woocommerce con el Asistente de Configuración

### ISSUE THREAD

**Issue by Darsport** [woocommerce/woocommerce#29936] opened 2021-05-18 18:32 UTC
Soy nuevo en WordPress por lo que este error puede no ser grave, sin embargo al iniciar el Asistente de Configuración de WooCommerce y completar el primer formulario, el botón no me dirige a la siguiente parte de la configuración y queda atascado incapaz de usar WooCommerce, en general e intentado reinciar el plugin, el pc, el caché, pero no sirve de nada, podría ser un error de codigo?
Muchas gracias por su tiempo.

**Comment by zhongruige** [comment] 2021-05-18 20:09
Hi @Darsport,

Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

>I am new to WordPress so this error may not be serious, however when I start the WooCommerce Setup Wizard and fill in the first form, the button does not direct me to the next part of the setup and I get stuck unable to use WooCommerce, in general and tried to restart the plugin, the pc, the cache, but it is useless, could it be a code error?
Thank you very much for your time. 

I just tested the setup wizard and was able to proceed without issue. Can you help provide a bit more context on what you're seeing? The following will be helpful to help us further investigate:

* How the form is filled out (if using an auto fill or typing in manually, etc).
* Any screenshots showing how the wizard is stuck
* What browser/OS is being used
* What version on WordPress/WooCommerce this is on
* If you can navigate to `{your-domain}/wp-admin/admin.php?page=wc-status`, once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment. 

Thank you in advance!

**Comment by Darsport** [comment] 2021-05-20 02:26
Ok i will, but my problem has already been solved changing the version of php in the host, sorry for the loss of time and thanks for the answer.

**Comment by zhongruige** [comment] 2021-05-20 14:26
Glad to hear the problem is resolved--and no worries about the loss of time at all, happy to try and help out!

I will close this issue for now, but feel free to reply and let us know if there is anything else we can help investigate with this. Have a good rest of your day :)

**Closed by zhongruige** 2021-05-20 14:26 UTC
Labels: has feedback
