### ISSUE TITLE
Prices lose decimal points upon product save

### ISSUE THREAD

**Issue by mihaigrigori** [woocommerce/woocommerce#15294] opened 2017-05-26 15:06 UTC
### EXPLANATION OF THE ISSUE

This is happening with a master branch after this change: f940961c6fdb1e382d671944eec7db2b0bc09cde

If your site uses '.' for the thousands separator and ',' for decimal separators, when you create a product and enter a price with decimals, after saving the product, the price loses the decimals separator. 

### STEPS TO REPRODUCE THE ISSUE

* set up a new site and use Romanian for the locale options (this will set ',' for decimals separator and '.' for thousands
* create a simple product and enter a value for the regular price
* you're prompted to use the correct decimals separator (,) and no thousands separator
* enter a price like 12,34
* after you save, the price becomes 1234

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://spiridon.rom/wp47
Site URL: http://spiridon.rom/wp47
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.17 (Win64) OpenSSL/1.0.2j PHP/7.1.0
PHP Version: 7.1.0
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.7.9
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.0-alpha

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by Ninos** [comment] 2017-05-26 15:27
Strange, because I've tested it for german localization (',' as decimal and '.' as thousand separator). I'll check it again with latest master.

**Comment by Ninos** [comment] 2017-05-26 15:47
Bug confirmed. This is because of following code parts:
https://github.com/woocommerce/woocommerce/blob/a3b89a9efc3f579294f2cf642820562b1b0edb06/includes/abstracts/abstract-wc-product.php#L805
https://github.com/woocommerce/woocommerce/blob/a3b89a9efc3f579294f2cf642820562b1b0edb06/includes/abstracts/abstract-wc-product.php#L815
https://github.com/woocommerce/woocommerce/blob/a3b89a9efc3f579294f2cf642820562b1b0edb06/includes/abstracts/abstract-wc-product.php#L825

`wc_format_decimal()` is wrong there because the price in the database must always be as raw as possible (already in float format). I recommend removing this part of line or replacing it with floatval() if you need a float type.

**Comment by mikejolley** [comment] 2017-05-26 17:18
First off, https://github.com/woocommerce/woocommerce/commit/f940961c6fdb1e382d671944eec7db2b0bc09cde is not the change I merged. I adjusted it to only replace the store thousand separator.

The PR reintroduces the server thousands seps we don't want.

**Comment by Ninos** [comment] 2017-05-26 17:23
@mikejolley You mean my bugfix is ok, if I remove the server thousands seps (`$locale['thousands_sep']`)? Yeah you're right, such thousands seps are not needed in this function. I added them by mistake. Should be removed now from PR.

**Comment by mikejolley** [comment] 2017-05-26 17:24
Looks like it's because we format the user input value (string).

Then format the DB stored value (string) which already uses the '.' decimal.

Therefore this patch is no good and we should revert and keep the old behavior. The function expects a string with no thousand chars. I don't see another way to support this - without context args.

**Comment by mikejolley** [comment] 2017-05-26 17:26
```
public function set_regular_price( $price ) {
		$this->set_prop( 'regular_price', wc_format_decimal( $price ) );
	}
```

Used on read too - the DB version is already normalised.

**Comment by Ninos** [comment] 2017-05-26 17:27
Following check should solve the problem:
`if ( ! is_float( $number ) && $number !== strval( floatval( $number ) ) ) {`

It checks if the $number is already in correct float format. If yes, don't change separators.

**Comment by mikejolley** [comment] 2017-05-26 17:29
Then it needs more unit tests or I'm not comfortable shipping it.

**Comment by Ninos** [comment] 2017-05-26 17:34
Should I add some additional unit tests for that patch?

**Closed** 2017-05-30 10:56 UTC
Labels: Release: Minor, Type: Bug
