### ISSUE TITLE
Cannot completely hide  woocommerce message with filters since upgrade to 3.9

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/woocommerce#25478] opened 2020-01-23 21:07 UTC
We are currently using 

```
add_filter( 'wc_add_to_cart_message_html', '__return_false' );

```
to hide add to cart messages

since upgrade to 3.9 'woocommerce-message' is not being removed anymore 

**To Reproduce**
1. add the filters to functions.php
2. Go to shop
2. add to cart
3. observe how **_only_** the text strings have been removed. 

We do not want to have to add css to hide woocommerce-message, as there are other messages we want to be able to see.

**Expected behavior**
filters should completely remove the message (string and wrapping div)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Giacomo Bruzzo

**Comment by tammullen** [comment] 2020-01-24 16:09
Hi @gbruzzo,
​
Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end in 3.90

![Screenshot_2020-01-24_at_15_46_36](https://user-images.githubusercontent.com/24649833/73083334-e4b70a80-3ec2-11ea-921c-08528d0d97c6.png)
Message appears ok when add to cart from product page

![Screenshot_2020-01-24_at_15_58_42](https://user-images.githubusercontent.com/24649833/73083363-f3052680-3ec2-11ea-9155-4168fd87b238.png)
Added filter

![Screenshot_2020-01-24_at_15_52_01](https://user-images.githubusercontent.com/24649833/73083388-fbf5f800-3ec2-11ea-88f0-da57f0cda231.png)
With the filter added the message text is removed when adding to cart but the message border still appears

![Screenshot 2020-01-24 at 16 00 58](https://user-images.githubusercontent.com/24649833/73083471-25168880-3ec3-11ea-8a56-36f6284f3815.png)
`woocommerce-message` `div` is still there

When I try in 3.81 with the filter added the entire message is removed
![Screenshot 2020-01-24 at 15 50 39](https://user-images.githubusercontent.com/24649833/73083578-5727ea80-3ec3-11ea-8908-d9f66be8191d.png)
![Screenshot 2020-01-24 at 16 01 56](https://user-images.githubusercontent.com/24649833/73083587-5c853500-3ec3-11ea-9ed7-485f93db8039.png)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by gbruzzo** [comment] 2020-01-24 16:12
Thank you

Please don’t forget it though ... :-)

**Comment by claudiosanches** [comment] 2020-01-24 16:34
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25484.

**Closed by claudiosanches** 2020-01-24 16:34 UTC
Labels: bug, has pull request, priority: low
