### ISSUE TITLE
Variable Product Attribute lost on product update

### ISSUE THREAD

**Issue by umang-metatagg** [woocommerce/woocommerce#20793] opened 2018-07-13 13:14 UTC
Hello Team,

    I have recently update woocommerce 3.4.3 and wordpress 4.7.9. I found issue when I added variable product then set attribute and variation and lastly saved it. it works properly but again i make some modification and click on again update button, attributes not showing. means second time click on update button makes attributes removed. can you help us to solve this issue? Thanks!

**Comment by claudiosanches** [comment] 2018-07-13 16:07
Sorry not able to reproduce this issue, it's missing a lot of information and the issue template has been removed. When reporting a bug, please use the "bug" template, so you can provide valuable information of how to reproduce an issue and so we can know how to fix.
Anyway sounds like a edge case caused by some plugin or connection problem while saving.
Closing since does not sound like an issue on WooCommerce and there's no steps or way to reproduce it.
Thanks for reporting.

**Closed by claudiosanches** 2018-07-13 16:07 UTC
