### ISSUE TITLE
Add STEP argument for FILTER: woocommerce_available_variation

### ISSUE THREAD

**Issue by stefanstatescu1** [woocommerce/woocommerce#29246] opened 2021-02-28 00:55 UTC
I have a WHOLESALE plugin and I am trying to set the input step for different variations. 

For example the item COFFEE, might be sold in 3 variations:
- small bags: sold in packages of 10
- medium: sold in packages of 6
- large: sold in packages of 3

**woocommerce_quantity_input_args** supports step, so I can set the input step for simple products, or the entire variable product

**woocommerce_available_variation** however surprisingly only supports min and max qty, but does not support step. So I cannot set different steps for different variations in the product page.

**Comment by tammullen** [comment] 2021-03-01 20:18
Hi @stefanstatescu1 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-01 20:18 UTC

**Comment by stefanstatescu1** [comment] 2021-03-01 20:59
It is not a bug, nor a custom code related question.

It is an **Enhancement** request.

I am asking you to add a 'step' argument to the "woocommerce_available_variation" filter. That would give more options to developers.
