### ISSUE TITLE
WooCommerce products page (backend)

### ISSUE THREAD

**Issue by hossok** [woocommerce/woocommerce#26155] opened 2020-04-10 06:37 UTC
**Describe the bug**
WooCommerce products (All products) page can't show all attributes so it putting them as a column! please check attached image.
![image](https://user-images.githubusercontent.com/63442322/78968974-cfa45c00-7b40-11ea-8ad4-4a507846b5f0.png)

I tried to deactivate some plugins to make less attributes but didn't change.
I think this is a bug after recent updates because I didn't face this issue before.
Hope to hear from you soon

```
`
### WordPress Environment ###

WordPress address (URL): https://japan-shoppy.com
Site address (URL): https://japan-shoppy.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.15
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.13
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: f12_
Total Database Size: 15.73MB
Database Data Size: 14.79MB
Database Index Size: 0.94MB
f12_woocommerce_sessions: Data: 2.35MB + Index: 0.13MB + Engine MyISAM
f12_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_order_itemmeta: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_actionscheduler_actions: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
f12_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_actionscheduler_logs: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
f12_cegg_autoblog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_cegg_price_alert: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_cegg_price_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_cegg_product: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_commentmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
f12_comments: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
f12_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
f12_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
f12_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
f12_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
f12_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
f12_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_options: Data: 7.95MB + Index: 0.18MB + Engine MyISAM
f12_postmeta: Data: 1.85MB + Index: 0.23MB + Engine MyISAM
f12_posts: Data: 1.92MB + Index: 0.07MB + Engine MyISAM
f12_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
f12_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
f12_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_termmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
f12_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
f12_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
f12_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
f12_ulp_campaigns: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_ulp_campaign_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_ulp_layers: Data: 0.16MB + Index: 0.00MB + Engine MyISAM
f12_ulp_popups: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
f12_ulp_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_ulp_targets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_ulp_webfonts: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
f12_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
f12_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_wcfm_daily_analysis: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_detailed_analysis: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_enquiries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_enquiries_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_enquiries_response: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_enquiries_response_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_fbc_chat_rows: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_fbc_chat_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_fbc_chat_visitors: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_fbc_offline_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_following_followers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_orders_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_product_multivendor: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_refund_request: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_refund_request_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_reverse_withdrawal: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_reverse_withdrawal_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_reviews: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_reviews_response: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_reviews_response_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_review_rating_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_store_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_vendor_ledger: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_withdraw_request: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_marketplace_withdraw_request_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_membership_subscription: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_messages_modifier: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_messages_stat: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_support: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_support_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_support_response: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcfm_support_response_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_cust_answers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_cust_questions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_products_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_vendor_ledger: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_vendor_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wcmp_visitors_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wc_cancel_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
f12_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
f12_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woo_wallet_transactions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_woo_wallet_transaction_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wpfepp_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
f12_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 207
custom_css: 1
elementor_library: 23
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 4
page: 42
popup_theme: 6
post: 10
product: 57
product_variation: 4
revision: 6
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Advanced Database Cleaner: by Younes JFR. – 3.0.0
AfterShip - WooCommerce Tracking: by AfterShip – 1.9.18 – Not tested with the active version of WooCommerce
Arabic Webfonts: by Jozoor – 1.4.6
Loco Automatic Translate Addon: by Cool Plugins – 1.7
Autoptimize: by Frank Goossens (futtta) – 2.6.2
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: by SeedProd – 5.1.0
Content Egg: by keywordrush.com – 5.0.0
Dokan: by weDevs – 3.0.3
Elementor: by Elementor.com – 2.9.7
Envato Market: by Envato – 2.0.3
Flexible Shipping Locations: by WP Desk – 1.1.9
Flexible Shipping PRO: by WP Desk – 1.9.5
Flexible Shipping: by WP Desk – 3.9.15
Geolocation IP Detection: by Yellow Tree (Benjamin Pick) – 3.0.3.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Site Kit by Google: by Google – 1.7.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.3
Layered Popups: by Halfdata
Inc. – 6.61

Loco Translate: by Tim Whitlock – 2.3.3
Mailchimp for WooCommerce: by Mailchimp – 2.3.6
MOJO Marketplace: by Mike Hansen – 1.5.2
One Click Demo Import: by ProteusThemes – 2.5.2
OptinMonster API: by OptinMonster Team – 1.9.6 – Not tested with the active version of WooCommerce
Popup Maker: by Popup Maker – 1.9.2
Product Filter for WooCommerce: by 7VX LLC
USA CA – 7.2.4 – Not tested with the active version of WooCommerce

Preferred Languages: by Pascal Birchler – 1.6.0
REHub Framework: by Sizam – 4.2
Slider Revolution: by ThemePunch – 6.1.5
RH Cloak Affiliate Links: by Wpsoul – 1.3.1
RH Frontend Publishing Pro: by Wpsoul – 4.0.8
RH WooCommerce Tools: by Wpsoul.com – 1.1.6 – Not tested with the active version of WooCommerce
Shortcode in Menus: by Gagan Deep Singh – 3.5
Tawk.to Live Chat: by Tawkto – 0.4.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.23

WC Cancel Order: by Vikram Singh – 2.9.1 – Not tested with the active version of WooCommerce
WooCommerce Country Restrictions - Advanced Pro: by WP Super Admins – 1.10.2
WooCommerce Blocks: by Automattic – 2.5.15
WooCommerce Locations Pack: by dangoodman – 1.4.8.1 – Not tested with the active version of WooCommerce
woocommerce Product Editor: by zizou1988 – 1.3 – Not tested with the active version of WooCommerce
TeraWallet: by WCBeginner – 1.3.14 – Not tested with the active version of WooCommerce
Woocommerce app by phoeniixx: by phoeniixx – 1.0.1 – Not tested with the active version of WooCommerce
WOOCS - WooCommerce Currency Switcher: by realmag777 – 2.3.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.20 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.3
WooCommerce Services: by Automattic – 1.23.0
WooCommerce: by Automattic – 4.0.1
WPForms Lite: by WPForms – 1.5.9.5

### Inactive Plugins (12) ###

Ad Inserter: by Igor Funa – 2.6.7
Akismet Anti-Spam: by Automattic – 4.1.4
Anti-Spam by CleanTalk: by СleanTalk <welcome@cleantalk.org> – 5.136.4
Beeketing For WooCommerce: by Beeketing – 3.8.16 – Not tested with the active version of WooCommerce
Facebook for WooCommerce: by Facebook – 1.10.2
NinjaFirewall (WP Edition): by The Ninja Technologies Network – 4.1.1
Ninja Forms: by Saturday Drive – 3.4.24.1
Product Feed PRO for WooCommerce: by AdTribes.io – 7.8.8
SEOPress: by SEOPress – 3.8.4
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 1.7.0 – Not tested with the active version of WooCommerce

Ultimate FAQ: by Etoile Web Design – 1.8.31 – Not tested with the active version of WooCommerce
WPC Product Bundles for WooCommerce: by WPClever.net – 4.0.3

### Must Use Plugins (4) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 1.9
Endurance PHP Edge: by Mike Hansen – 0.2
SSO: by Garth Mortensen
Mike Hansen – 0.3


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #13 - /shop/
Cart: #14 - /cart/
Checkout: #15 - /checkout/
My account: #16 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Rehub child theme
Version: 9.4
Author URL: https://wpsoul.com
Child Theme: ✔
Parent Theme Name: Rehub theme
Parent Theme Version: 9.9.8
Parent Theme Author URL: https://wpsoul.com/
WooCommerce Support: ✔

### Templates ###

Overrides: rehub-theme/woocommerce/archive-product.php
rehub-theme/woocommerce/cart/cross-sells.php
rehub-theme/woocommerce/content-product.php
rehub-theme/woocommerce/content-product_cat.php
rehub-theme/woocommerce/global/wrapper-end.php
rehub-theme/woocommerce/global/wrapper-start.php
rehub-theme/woocommerce/loop/add-to-cart.php
rehub-theme/woocommerce/loop/loop-end.php
rehub-theme/woocommerce/loop/loop-start.php
rehub-theme/woocommerce/loop/rating.php
rehub-theme/woocommerce/loop/sale-flash.php
rehub-theme/woocommerce/product-searchform.php
rehub-theme/woocommerce/single-product/add-to-cart/external.php
rehub-theme/woocommerce/single-product/meta.php
rehub-theme/woocommerce/single-product/product-image.php
rehub-theme/woocommerce/single-product/product-thumbnails.php
rehub-theme/woocommerce/single-product/sale-flash.php
rehub-theme/woocommerce/single-product/share.php
rehub-theme/woocommerce/single-product/tabs/additional-information.php
rehub-theme/woocommerce/single-product/tabs/description.php
rehub-theme/woocommerce/single-product-reviews.php
rehub-theme/woocommerce/single-product.php


### Action Scheduler ###

Complete: 185
Oldest: 2020-03-11 01:46:57 +0900
Newest: 2020-04-10 13:24:26 +0900

Pending: 3
Oldest: 2020-04-11 03:00:00 +0900
Newest: 2020-04-11 09:56:45 +0900
</details>

**Comment by juliaamosova** [comment] 2020-04-10 18:09
Hi @hossok,

Thank you for submitting the issue. However, I can’t reproduce it on my end. We had a similar issue reported previously through - noting here for the record: https://github.com/woocommerce/woocommerce/issues/25780. 

Have you tried testing your site for theme and plugins conflict? 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by hossok** [comment] 2020-04-11 00:53
Thank you for your response.

I found that "Dokan" plugin was making the issue.
Sorry for wrong report and thank you for your support.

Best Regards

**Closed** 2020-04-13 19:18 UTC
Labels: can't reproduce, status: needs feedback
