### ISSUE TITLE
Hide products from search with default WordPress search when set to "hidden" in catalog

### ISSUE THREAD

**Issue by katinthehatsite** [woocommerce/woocommerce#28693] opened 2020-12-30 16:08 UTC
At the moment, there are two searches available with WordPress and WooCommerce - WooCommerce Product Search and WordPress search. The rough difference could be illustrated by two widgets:

<img width="704" alt="download" src="https://user-images.githubusercontent.com/25575134/103365497-16175d80-4ab8-11eb-99e3-99ea867279ac.png">

The product search has this sample link for searching: http://yoursite.com/?s=test&post_type=product
The default WordPress search has this sample link: http:/yoursite.com/?s=test+product

**Is your feature request related to a problem? Please describe.**
 
It seems that this creates a lot of confusion when hiding the product from catalog. Example:

* Set the settings on **Catalog visibility** to **hidden** on a product like so: 

<img width="352" alt="download (1)" src="https://user-images.githubusercontent.com/25575134/103365679-87efa700-4ab8-11eb-9503-ff7fe0ec00b2.png">

The expectation that seems to come from this setting is that this would hide the product from all search results on the site. It does hide it from the product search or from http://yoursite.com/?s=test&post_type=product but the product still comes through the WordPress default search: http:/yoursite.com/?s=test+product

Default WordPress search:

![download (2)](https://user-images.githubusercontent.com/25575134/103365828-df8e1280-4ab8-11eb-96e7-141e2abc8db0.png)

WooCommerce product search:

![download (3)](https://user-images.githubusercontent.com/25575134/103365848-f0d71f00-4ab8-11eb-9d48-71ec021e90bf.png)

**Describe the solution you'd like**

For the WooCommerce products also be hidden from the general default WordPress search. 

**Additional context**

* It looks like a similar issue has been reported before as a bug: https://github.com/woocommerce/woocommerce/issues/25563
* Same issue has also been discussed in several forum threads: https://wordpress.org/support/topic/products-still-show-in-search-results-even-with-catalog-visibility-set-to-hidden/

Is there any reason or explanation for the products not being hidden in the general site search? Thanks!

**Comment by kevinruscoe** [comment] 2020-12-31 16:38
This makes sense. WC has both a "status" and "catalog visibility" option. But WP doesn't really care about the "catalog visibility" when it's doing it's normal search. 

If you search for the word "product" the SQL ran is 

```
SELECT
	SQL_CALC_FOUND_ROWS wp_posts.ID
FROM
	wp_posts
WHERE
	1 = 1
	AND(((wp_posts.post_title LIKE '%product%')
	OR(wp_posts.post_excerpt LIKE '%product%')
	OR(wp_posts.post_content LIKE '%product%')))
	AND wp_posts.post_type IN('post', 'page', 'attachment', 'product')
	AND(wp_posts.post_status = 'publish'
		OR wp_posts.post_author = 1
		AND wp_posts.post_status = 'private')
ORDER BY
	wp_posts.post_title LIKE '%product%' DESC,
	wp_posts.post_date DESC
LIMIT 0,
10;
```

and the clause that limis the resuts to the "status" is

```
wp_posts.post_status = 'publish' OR wp_posts.post_author = 1 AND wp_posts.post_status = 'private'
```

Having a dig around in the tables, in the 'wp_terms' table, there's a term named "exclude-from-search", which should be considered when running the search. The existance of this term on a product means it shouldn't get returned with the search.

I hope someone with a bit more SQL knowledge could correct me, but adding a second SELECT to the search query to count the existance of this row, when adding a `HAVING` clause on it should be enough to correctly remove the products set to "hidden" (or "exclude from search").

so the new query becomes:

```
SELECT
	SQL_CALC_FOUND_ROWS wp_posts.ID,
	(
		SELECT
			count(*)
		FROM
			wp_term_relationships
		WHERE
			object_id = wp_posts.ID
			AND term_taxonomy_id in(
				SELECT
					term_id FROM wp_terms
				WHERE
					name = 'exclude-from-search')) AS wc_excluded_from_search
	FROM
		wp_posts
	WHERE
		1 = 1
		AND(((wp_posts.post_title LIKE '%product%')
		OR(wp_posts.post_excerpt LIKE '%product%')
		OR(wp_posts.post_content LIKE '%product%')))
		AND wp_posts.post_type IN('post', 'page', 'attachment', 'product')
		AND(wp_posts.post_status = 'publish'
			OR wp_posts.post_author = 1
			AND wp_posts.post_status = 'private')
	HAVING
		wc_excluded_from_search = 0
	ORDER BY
		wp_posts.post_title LIKE '%product%' DESC,
		wp_posts.post_date DESC
	LIMIT 0,
	10;
```

We only need to hook into `posts_clauses_request` to get this to work, adding to the 'fields' key (for the select) and the 'where' key (adding our HAVING, as WP doesn't have a array for this).

I'll open a PR for this. But the links you'd added to the issue does raise some good points.

1 - @claudiosanches says that specifying `post_type=products` limits it correctly. This is correct. It seems WC hijacks the entire search page and renders their own which a modified query.
2 - WP not supporting the a native HAVING clause is dodgy. I'll be hijacking the WHERE clause and adding the HAVING part afterwards, meaning any plugins that fire their filter later is going to have a bad time. I would open a RP on WordPress itself, but it'll take a year to even get looked at. There's a `posts_request` filter, but I think it'll be a pain to use regex to correctly insert the HAVING clause.

Anyone have any thoughts on this?

**Comment by rrennick** [comment] 2021-10-22 16:45
I have confirmed this is still an issue in WC 5.8 and have updated the labels. The linked PR is stale and is waiting for a response from the author.

**Comment by tomasztunik** [comment] 2022-02-02 10:49
Still present in WC 6.2

Also there is a possible gap when using Product Search block to find a hidden product. Searching using the Product Search block will have it hidden in results but will take you to WordPress search results page which has regular WordPress search input on it possibly exposing hidden products on consecutive search.

**Comment by AashikP** [comment] 2023-03-17 09:10
Another report in 6045281-zen

**Comment by seanconklin** [comment] 2023-07-06 21:07
I always thought that hidden from search means any WP Query search, not just the post_type=product search template. 

This code snippet on StackExchange fixed the problem for me: https://wordpress.stackexchange.com/questions/283393/hidden-woocommerce-products-still-showing-up-in-search-results

**Comment by rrennick** [comment] 2023-09-11 19:22
Closing this as a duplicate of a more recent report #39387

**Closed by rrennick** 2023-09-11 19:22 UTC
Labels: type: bug, priority: low, focus: shop [team:Proton], focus: search [team:Proton], plugin: woocommerce, team: Mothra
