### ISSUE TITLE
WC Admin borked with 4.8 (works fine with 4.7.1)

### ISSUE THREAD

**Issue by martinsotirov** [woocommerce/woocommerce#28604] opened 2020-12-16 19:39 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After updating to the latest WooCommerce I noticed that all Javascript seems to be disabled on all Woo-Pages - the classic editor on product pages can't be initialized, the hover state doesn't work in the admin menu etc. There are no js errors in the console, only jquery migrate deprecations. I tried installing the jQuery Migration Helper Plugin and setting the jQuery version to legacy but that didn't help.

**Expected behavior**
Woo Admin should work.

**Actual behavior**
Woo Admin doesn't work.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Update Woo from 4.7.1 to 4.8.0

**Screenshots**
![Screenshot 2020-12-16 at 20 28 05](https://user-images.githubusercontent.com/1459200/102397510-4520d000-3fde-11eb-9251-7a4283eb1d04.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>
`
### WordPress Environment ###

WordPress address (URL): ----------
Site address (URL): --------
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.2
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.65.1
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 24.29MB
Datenbank-Datengröße: 16.81MB
Datenbank-Indexgröße: 7.48MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Daten: 0.13MB + Index: 0.06MB + Engine MyISAM
wp_gf_draft_submissions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Daten: 0.41MB + Index: 0.11MB + Engine InnoDB
wp_gf_entry_meta: Daten: 1.52MB + Index: 2.16MB + Engine InnoDB
wp_gf_entry_notes: Daten: 0.27MB + Index: 0.08MB + Engine InnoDB
wp_gf_form: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Daten: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Daten: 0.25MB + Index: 0.20MB + Engine InnoDB
wp_gp_oauth_users: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_moodle_enrollment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 1.52MB + Index: 0.61MB + Engine MyISAM
wp_postmeta: Daten: 5.60MB + Index: 1.28MB + Engine MyISAM
wp_posts: Daten: 3.19MB + Index: 0.26MB + Engine MyISAM
wp_rg_form: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Daten: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Daten: 0.34MB + Index: 0.56MB + Engine InnoDB
wp_rg_lead_detail_long: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Daten: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_taxonomy: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_uam_accessgroups: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_uam_accessgroup_to_object: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Daten: 0.41MB + Index: 0.30MB + Engine MyISAM
wp_users: Daten: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woo_moodle_course: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 4
acf-field: 104
acf-field-group: 22
attachment: 1150
dozenten: 32
eb_course: 45
events: 97
kurse: 29
nav_menu_item: 51
oembed_cache: 1
page: 57
post: 147
product: 7
projekte: 15
revision: 702
shop_coupon: 37
shop_order: 342
vg_gateway_condition: 1
workshops: 7

### Security ###

Secure connection (HTTPS): ❌
					Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (18) ###

Gravity Perks | Shared By Themes24x7.com: von David Smith – 1.2.12
Gravity Forms: von Gravity Forms – 2.4.21
Advanced Custom Fields Sidebar: von Webman Technologies – 1.0.0
Classic Editor: von WordPress-Mitwirkende – 1.6
Fluid Video Embeds: von jamie3d – 1.2.9
Google XML Sitemaps: von Auctollo – 4.1.1
GP Limit Choices: von David Smith – 1.6.22
Post Duplicator: von Metaphor Creations – 2.22
WordPress Post-Type-Archiv Links: von Stephen Harris – 1.3.1
Quick Page/Post Redirect Plugin: von anadnet – 5.1.9
Simple Page Sidebars: von Cedaro – 1.2.1
WooCommerce Conditional Payment Methods Pro: von WP Super Admins – 1.10.0
PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.2.1
WooCommerce EU VAT Number: von WooCommerce – 2.3.7 – Installed version not tested with active version of WooCommerce 4.0
Germanized für WooCommerce: von Vendidero – 3.1.5
WooCommerce Moodle Integration: von Martin Sotirov – 0.3.0 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce: von Automattic – 4.8.0
WP Social Sharing: von Arjun Jain – 2.2

### Inactive Plugins (1) ###

Enable jQuery Migrate Helper: von The WordPress Team – 1.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
group_license (group_license)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: ❌ Seite nicht festgelegt
Warenkorb: #3902 - /warenkorb/
Kasse: #3903 - /kasse/
Mein Konto: #3904 - /mein-konto/
Allgemeine Geschäftsbedingungen: #1008 - /impressum/agb/

### Theme ###

Name: --------
Version: 1.0.0
Author URL: --------
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: nawik_2/woocommerce/cart/cart-totals.php
nawik_2/woocommerce/cart/cart.php
nawik_2/woocommerce/cart/proceed-to-checkout-button.php
nawik_2/woocommerce/checkout/form-billing.php
nawik_2/woocommerce/checkout/form-checkout.php
nawik_2/woocommerce/checkout/form-login.php
nawik_2/woocommerce/checkout/review-order.php
nawik_2/woocommerce/checkout/thankyou.php
nawik_2/woocommerce/content-product.php
nawik_2/woocommerce/emails/customer-processing-order.php
nawik_2/woocommerce/emails/customer-reset-password.php
nawik_2/woocommerce/emails/email-order-details.php
nawik_2/woocommerce/emails/email-order-items.php
nawik_2/woocommerce/myaccount/dashboard.php
nawik_2/woocommerce/myaccount/form-edit-account.php
nawik_2/single-product.php

### Action Scheduler ###

Abgeschlossen: 86
Oldest: 2020-11-17 10:36:45 +0000
Newest: 2020-12-16 18:18:21 +0000

`
</details>

**Comment by tammullen** [comment] 2020-12-17 11:11
Hi @martinsotirov 

I see from the system report you provided that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-12-23 22:42
Hi @martinsotirov,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-12-23 22:42 UTC
Labels: needs feedback

**Comment by martinsotirov** [comment] 2021-01-19 16:22
@tammullen following your advice of disabling all plugins and switching to the Storefront theme I was able to track down the problem to a snippet of php in my theme that adds a password repeat field on the checkout page:

```
add_action('woocommerce_checkout_init', function ($checkout) {
    if (get_option('woocommerce_registration_generate_password') == 'no' ) {
        $fields = $checkout->get_checkout_fields();

        $fields['account']['account_confirm_password'] = [
            'type'        => 'password',
            'label'       => 'Passwort bestätigen',
            'required'    => true,
            'placeholder' => 'Passwort'
        ];

        $checkout->__set('checkout_fields', $fields);
    }
}, 10, 1);
```

Apparently for some reason this hook gets called when viewing the WC dashboard from the admin, which triggers the following PHP exception, which itself kills some part of the js responsible for the WC admin UI.

```
[19-Jan-2021 16:15:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /Users/martin/Sites/nawik/nawik_de/src/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php:96
```

As a workaround I added an `!is_admin()` check to my if block so that the additional checkout field gets added only on the frontend.
