### ISSUE TITLE
[4.0.1][regression] User with "shop manager" role is unable to edit orders after upgrade

### ISSUE THREAD

**Issue by wparuch** [woocommerce/woocommerce#26023] opened 2020-03-27 09:58 UTC
**Describe the bug**
User with "shop manager" role is unable to edit orders after upgrade from Woocommerce 3.8.x

**To Reproduce**
1. Create user with "shop manager" role and login
2. Go to 'Woocommerce -> Orders'
3. Click on any order
4. See blank page

**Expected behavior**
Shop manager should be able to edit orders as before.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.28
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.44-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Całkowity rozmiar bazy danych: 41.24MB
Rozmiar bazy danych: 37.43MB
Rozmiar indeksu bazy danych: 3.81MB
wp_woocommerce_sessions: Dane: 1.03MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_woocommerce_order_items: Dane: 0.05MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_order_itemmeta: Dane: 0.14MB + Indeks: 0.16MB + Silnik InnoDB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_actions: Dane: 0.05MB + Indeks: 0.11MB + Silnik InnoDB
wp_actionscheduler_claims: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_groups: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_logs: Dane: 0.05MB + Indeks: 0.03MB + Silnik InnoDB
wp_aepc_custom_audiences: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_aepc_logs: Dane: 23.52MB + Indeks: 0.00MB + Silnik InnoDB
wp_commentmeta: Dane: 0.00MB + Indeks: 0.01MB + Silnik MyISAM
wp_comments: Dane: 0.22MB + Indeks: 0.09MB + Silnik MyISAM
wp_giftvouchers_activity: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_giftvouchers_list: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_giftvouchers_setting: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_giftvouchers_template: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_links: Dane: 0.00MB + Indeks: 0.00MB + Silnik MyISAM
wp_mailpoet_custom_fields: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_dynamic_segment_filters: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_feature_flags: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_forms: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_log: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_mapping_to_external_entities: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletters: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_newsletter_links: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_newsletter_option: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_option_fields: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_posts: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_segment: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_templates: Dane: 2.52MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_scheduled_tasks: Dane: 0.06MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_scheduled_task_subscribers: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_segments: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_sending_queues: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_settings: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_statistics_clicks: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_mailpoet_statistics_forms: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_statistics_newsletters: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_statistics_opens: Dane: 0.02MB + Indeks: 0.08MB + Silnik InnoDB
wp_mailpoet_statistics_unsubscribes: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_mailpoet_stats_notifications: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_subscribers: Dane: 0.05MB + Indeks: 0.11MB + Silnik InnoDB
wp_mailpoet_subscriber_custom_field: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_subscriber_ips: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_subscriber_segment: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_user_flags: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_ms_snippets: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_newsletter: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_newsletter_emails: Dane: 0.03MB + Indeks: 0.00MB + Silnik InnoDB
wp_newsletter_sent: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_newsletter_stats: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_newsletter_user_logs: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_nextend2_image_storage: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_nextend2_section_storage: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_nextend2_smartslider3_generators: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_nextend2_smartslider3_sliders: Dane: 0.03MB + Indeks: 0.00MB + Silnik InnoDB
wp_nextend2_smartslider3_sliders_xref: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_nextend2_smartslider3_slides: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_options: Dane: 2.60MB + Indeks: 0.15MB + Silnik MyISAM
wp_pimwick_gift_card: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_pimwick_gift_card_activity: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_postmeta: Dane: 1.52MB + Indeks: 0.73MB + Silnik MyISAM
wp_posts: Dane: 3.31MB + Indeks: 0.14MB + Silnik MyISAM
wp_rad_uptin_stats: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_redirection_404: Dane: 0.06MB + Indeks: 0.06MB + Silnik InnoDB
wp_redirection_groups: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_redirection_items: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wp_redirection_logs: Dane: 0.02MB + Indeks: 0.08MB + Silnik InnoDB
wp_sbi_instagram_feeds_posts: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_sbi_instagram_posts: Dane: 0.14MB + Indeks: 0.00MB + Silnik InnoDB
wp_snippets: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_termmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_terms: Dane: 0.00MB + Indeks: 0.01MB + Silnik MyISAM
wp_term_relationships: Dane: 0.01MB + Indeks: 0.02MB + Silnik MyISAM
wp_term_taxonomy: Dane: 0.01MB + Indeks: 0.01MB + Silnik MyISAM
wp_usermeta: Dane: 0.16MB + Indeks: 0.11MB + Silnik MyISAM
wp_users: Dane: 0.01MB + Indeks: 0.01MB + Silnik MyISAM
wp_wc_admin_notes: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_admin_note_actions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_category_lookup: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_customer_lookup: Dane: 0.05MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_coupon_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_product_lookup: Dane: 0.09MB + Indeks: 0.06MB + Silnik InnoDB
wp_wc_order_stats: Dane: 0.06MB + Indeks: 0.05MB + Silnik InnoDB
wp_wc_order_tax_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_product_meta_lookup: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wp_wc_tax_rate_classes: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woobe_history: Dane: 0.06MB + Indeks: 0.05MB + Silnik InnoDB
wp_woobe_history_bulk: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_p24_custom_data: Dane: 0.00MB + Indeks: 0.01MB + Silnik MyISAM
wp_yoast_seo_links: Dane: 0.06MB + Indeks: 0.02MB + Silnik InnoDB
wp_yoast_seo_meta: Dane: 0.06MB + Indeks: 0.00MB + Silnik InnoDB

### Post Type Counts ###

attachment: 184
custom_css: 2
customize_changeset: 16
gift_card: 1
landingpage: 1
mailpoet_page: 1
nav_menu_item: 11
oembed_cache: 7
page: 21
popup: 3
popup_theme: 6
post: 26
product: 22
product_variation: 43
revision: 587
shop_coupon: 201
shop_order: 268
wcp_ruleset: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Add-on WooCommerce MailPoet 3: przez Tikweb – 1.1.7 – Nietestowane z używaną wersją WooCommerce
Code Snippets: przez Code Snippets Pro – 2.14.0
Conditional Payments for WooCommerce: przez Lauri Karisola / WooElements.com – 2.1.4 – Nietestowane z używaną wersją WooCommerce
Contact Form 7: przez Takayuki Miyoshi – 5.1.7
Informacja o ciasteczkach: przez dFactory – 1.2.51
WooCommerce Coupon Generator: przez Jeroen Sormani – 1.1.0 – Nietestowane z używaną wersją WooCommerce
Custom Fonts: przez Brainstorm Force – 1.2.1
Easy Table of Contents: przez Steven A. Zahm – 2.0.4
Facebook for WooCommerce: przez Facebook – 1.10.2
Mongoose Page Plugin: przez Mongoose Marketplace – 1.7.1
Smash Balloon Instagram Feed: przez Smash Balloon – 2.3
Jetpack z WordPress.com: przez Automattic – 8.3
Multiple Themes: przez David Gewirtz – 7.1.1
Limit Login Attempts: przez Johan Eenfeldt – 1.7.1
Loco Translate: przez Tim Whitlock – 2.3.1
MailPoet 3 (New): przez MailPoet – 3.46.6
Newsletter: przez Stefano Lissa wraz z zespołem Newslettera – 6.5.7
Pixel Caffeine: przez AdEspresso – 2.1.1 – Nietestowane z używaną wersją WooCommerce
Popup Maker: przez Popup Maker – 1.9.2
WooCommerce Przelewy24 Payment Gateway: przez DialCom24 Sp. z o.o. – 3.4.4 – Nietestowane z używaną wersją WooCommerce
PW WooCommerce Copy Coupon: przez Pimwick
LLC – 1.7

PW WooCommerce Gift Cards: przez Pimwick
LLC – 1.115

Really Simple SSL: przez Rogier Lankhorst
Mark Wolters – 3.3

Redirection: przez John Godley – 4.7.1
Shop Isle Companion: przez Themeisle – 1.0.9
WooCommerce Bulk Editor: przez realmag777 – 1.0.5.1 – Nietestowane z używaną wersją WooCommerce
WP Sheet Editor - WooCommerce Coupons: przez WP Sheet Editor – 1.3.3
WooCommerce Blocks: przez Automattic – 2.5.14
InPost dla WooCommerce: przez Inspire Labs – 1.3.5 – Nietestowane z używaną wersją WooCommerce
Variation Swatches for WooCommerce: przez Emran Ahmed – 1.0.78
WooCommerce Google Analytics Integration: przez WooCommerce – 1.4.19
Booster for WooCommerce: przez Algoritmika Ltd – 4.8.0
WooCommerce: przez Automattic – 4.0.1
Yoast SEO: przez Zespół Yoast – 13.3
WPFront Notification Bar: przez Syam Mohan – 1.7.1
YITH WooCommerce Quick View: przez YITH – 1.4.0

### Inactive Plugins (5) ###

Additional Variation Images Gallery for WooCommerce: przez Emran Ahmed – 1.1.39
Classic Editor: przez WordPress Contributors – 1.5
Facebook Pixel: przez Facebook – 1.6.0
WooCommerce Admin: przez WooCommerce – 1.0.3
XT WooCommerce Floating Cart: przez XplodedThemes – 1.5.2.2 – Nietestowane z używaną wersją WooCommerce

### Must Use Plugins (1) ###

installatron_hide_status_test.php: przez  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### Theme ###

Name: Shop Isle
Version: 1.1.60
Author URL: https://themeisle.com
Child Theme: ❌
`
```
</details>

**Comment by tammullen** [comment] 2020-03-31 10:21
Hi @wparuch 

Thank you for raising the issue. However, I can’t reproduce it on my end.
​
Using a user with shop manager role I can access orders with no issues
![Screenshot_2020-03-31_at_11_20_01](https://user-images.githubusercontent.com/24649833/78015771-c990cd00-7341-11ea-82d9-7ca622633b98.png)

​
I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-04-06 19:00
Hi @wparuch,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-04-06 19:00 UTC
Labels: can't reproduce, status: needs feedback
