### ISSUE TITLE
Price filter widget does not show for products imported using sample data

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#26093] opened 2020-04-07 08:29 UTC
**Describe the bug**
We recently created a test website and added the sample data, we noticed the price filter widget wouldn't show for our products. If we added a product through the dashboard then the price filter would show but only filter based off the new products added. It seems like the sample data may no longer have the required data needed for the price filter widget to show.

**To Reproduce**
1. Create a new WooCommerce install
2. Import the sample data from sample-data folder (we used the WordPress importer)
3. Add the price filter widget to your shop based sidebar
4. Price filter does not show
5. Manually create a product
6. Check the price filter again and it will show but only take into account the new product added through the dashboard

**Expected behavior**
Price filter widget shows and is functional for products imported from sample data.

**WordPress Environment**
WordPress 5.4
WooCommerce 4.0.1
Storefront Theme 2.5.5

**Comment by jonathansadowski** [comment] 2020-05-17 20:19
Hi @ninetyninew,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

**Steps I took**
1. Started with a fresh WooCommerce install.
2. Navigated to Tools and then Import in wp-admin.
3. Selected "Run Importer" under "WooCommerce products (CSV)" in the list of Importers.
![image](https://user-images.githubusercontent.com/363749/82158652-c77dc180-984e-11ea-9836-928f97dc6f06.png)

4. Selected the `sample-data/sample_products.csv` file and selected "Continue" without changing any of the default options.
![image](https://user-images.githubusercontent.com/363749/82159013-14629780-9851-11ea-95fc-2f3c598f92a9.png)

5. Accepted the defaults for column mapping and selected "Run the importer".
6. From Appearance -> Widgets, added the "Filter Products by Price" widget to the Sidebar.
7. Navigated to the shop and updated the price filters. Doing so appears to work, and I don't have any products that weren't imported from the sample data.

![image](https://user-images.githubusercontent.com/363749/82159124-ac608100-9851-11ea-86c0-0553176c576f.png)


Please provide us with more details about the issue which may help us to evaluate it further. 

Are you still able to recreate this issue? Did you update any of the column mappings in the import or use any additional settings, or did you accept the defaults?

**Comment by ninetyninew** [comment] 2020-05-18 06:32
This was actually using the WordPress importer, which I've always used since before the WooCommerce importers there existed. I think looking into this a little further it probably used to work fine as it would import products and their meta but since Woo now has the additional tables for quick look ups which I assume the price filter uses then I think it's why I am probably seeing this result. The fix is probably use the dedicated WooCommerce importer and stop using the WordPress importer I've been using for years!

**Comment by juliaamosova** [comment] 2020-05-22 13:54
Hi @ninetyninew,

Thanks for your follow-up and feedback. It is indeed recommended to use WooCommerce products importer in order for all the functionality of WooCommerce and its products to be supported. 

In any case, it looks like you are all set for now. I am closing this issue but please feel free to comment again in case we missed something and we'd take another look.

**Closed by juliaamosova** 2020-05-22 13:54 UTC
Labels: status: needs feedback
