### ISSUE TITLE
Uncaught Error: Call to undefined function get_home_path() after update to 3.5.1

### ISSUE THREAD

**Issue by tomanatura** [woocommerce/woocommerce#21895] opened 2018-11-13 08:30 UTC
After update to Woo 3.5.1 Im getting Uncaught Error: Call to undefined function get_home_path() on checkout page by my email attachments function `$file_path = get_home_path() . '/doc/';` I didnt have any problem until update.
Do you have any idea / are there any changes (in emails) or anything that can cause `Uncaught Error: Call to undefined function get_home_path()`?
Thanks you

Im on WP 4.9.8

Error log:
```
[12-Nov-2018 18:11:05 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_home_path() in /hosting/www/example.com/www/wp-content/themes/test/functions.php:950
Stack trace:
#0 /hosting/www/example.com/www/wp-includes/class-wp-hook.php(286): custom_email_attachments(Array, 'customer_on_hol...', Object(WC_Order))
#1 /hosting/www/example.com/www/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /hosting/www/example.com/www/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(399): apply_filters('woocommerce_ema...', Array, 'customer_on_hol...', Object(WC_Order))
#3 /hosting/www/example.com/www/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-on-hold-order.php(92): WC_Email->get_attachments()
#4 /hosting/www/example.com/www/wp-includes/class-wp-hook.php(286): WC_Email_Customer_On_Hold_Order->trigger(1071, Object(WC_Order))
#5 /hosting/www/example.com/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL in /hosting/www/example.com/www/wp-content/themes/test/functions.php on line 950

``````

**Comment by rrennick** [comment] 2018-11-13 15:58
The first line indicates where `get_home_path` was called.

```
Call to undefined function get_home_path() in /hosting/www/example.com/www/wp-content/themes/test/functions.php:950
```

**Comment by tomanatura** [comment] 2018-11-13 16:09
Thanks you rrennick.
I understand that _(see what I wrote)_, it comes from my function _(in function.php)_ that is attaching pdfs to emails. But why it stopped work after last Woo update?

```
	add_filter( 'woocommerce_email_attachments', 'custom_email_attachments', 20, 3 );
	function custom_email_attachments ( $attachments = [] , $email_id, $order ) {
		 
		$excluded_customer_email_ids = array( 'customer_reset_password', 'customer_new_account' );
		$excluded_admin_email_ids = array( 'new_order', 'low_stock' );
	
		 
		if( in_array( $email_id, $excluded_admin_email_ids ) ) 
			return [];
	
		$file_path = get_home_path() . '/doc/';
	
		$attachments[] = $file_path . 'Zasady_ochrany_osobnich_udaju.pdf'; 
	
		 
		if( ! in_array( $email_id, $excluded_customer_email_ids ) ) {
	
			$attachments[] =  $file_path . 'VOP.pdf'; 
			$attachments[] =  $file_path . 'Reklamacni_rad.pdf'; 
			$attachments[] =  $file_path . 'Reklamacni_protokol.pdf'; 
			$attachments[] =  $file_path . 'Formular_pro_odstoupeni_od_smlouvy.pdf'; 
	
		}	
		return $attachments;
	}
```

**Comment by rrennick** [comment] 2018-11-14 15:16
Thanks for following up with those details.

**Comment by rrennick** [comment] 2018-11-14 17:13
I've tested your filter with both WC 3.4.7 & 3.3.5 and the same error is logged in my error log.

**Comment by rodrigoprimo** [comment] 2018-11-19 12:39
Closing as @rrennick was not able to reproduce the problem and it doesn't seem this is a regression as initially reported.

**Closed by rodrigoprimo** 2018-11-19 12:39 UTC
