### ISSUE TITLE
Database version issue

### ISSUE THREAD

**Issue by usmantransdata** [woocommerce/woocommerce#19513] opened 2018-03-23 19:08 UTC
I update the woo commerce and also run the data update. My woo commerce database version show the new version and then after some time it revert it back to 3.2.6. How can i fix thsi issue

**Comment by claudiulodro** [comment] 2018-03-27 18:26
We need [the system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to better see what's going on. We can't reproduce this locally, so we need more information and details on how best to reproduce the issue. 

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

**Closed by claudiulodro** 2018-03-27 18:26 UTC

**Comment by usmantransdata** [comment] 2018-04-04 15:03
Here is the report. You can see the Database version is 3.2.6 .
I run the updater it update the version and in couple of hours it revert the database version and then i see the notification to run the updater to update the database.

**Comment by vatri** [comment] 2018-04-27 07:41
Same problem here. I think this causes me a 404 page showing for "success order" URL.

**Comment by claudiulodro** [comment] 2018-04-27 16:55
Interesting. Something is [changing the `woocommerce_db_version ` option to '3.2.6'](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php#L243) at some point after the upgrade has run. WooCommerce doesn't have any sort of mechanism that would do that, so the issue is most likely coming from one of your active plugins or something to do with your hosting.

@vatri are you using any of these plugins from the system status report?

**Comment by vatri** [comment] 2018-04-28 13:27
@claudiulodro  , in my case it reverts to 3.0.x (3.0.8 I think) version. I tried to turn off all plugins and same happens. I tried to switch to TwentySeventeen theme as well.
