### ISSUE TITLE
Postcodes with spaces do not match Zones for specific countries

### ISSUE THREAD

**Issue by jimjasson** [woocommerce/woocommerce#24369] opened 2019-08-09 13:05 UTC
**Describe the bug**
Currently, it is possible to define Shipping Zones by using only postcodes -- without selecting any countries, states or continents. The expected behavior is that when a customer uses the same postcode in the checkout page as the one used in the Shipping Zone then the Shipping Zone is matched. 

I noticed that if I use a postcode with spaces when setting up the Shipping Zone, similar to this: https://cl.ly/cc4d55280856 and then I use the same postcode in the checkout page as well, the Zone is matched for specific countries (e.g. UK): https://cl.ly/aeb0793a66d5 but not for others (e.g. Greece): https://cl.ly/81b8c53a3f3e.

Moreover, if I set up a Shipping Zone using ranges and the min/max postcodes contain spaces: https://cl.ly/0b46eef68694, then if I:

- use one postcode with spaces within this range in the checkout page and, 

- select a country (e.g. Greece) that did not previously match, then;

the Shipping Zone is correctly matched.

PR incoming.

**To Reproduce**
1. Go to *WooCommerce > Shipping > Shipping Zones* and set up a Shipping Zone using a postcode with spaces, similar to this: https://cl.ly/3715463e6ce8.
2. Add a product to the cart and go to the checkout page.
3. Add the same postcode as the one used in the Shipping Zone.
3. Choose 'United Kingdom' as the Shipping Country -- the Zone is matched and Shipping Methods show up.
4. Choose 'Greece' as the Shipping Country -- the Zone is not matched and not any Shipping Methods show up.

**Screenshots**
Here's a video demonstrating this behavior: https://cl.ly/53f23d4de4e3

**Expected behavior**
If a Shipping Zone is defined using only a Shipping Postcode, then this Zone should be matched when the same postcode is used in the checkout -- regardless of the selected country.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### WordPress Environment ###

WordPress address (URL): http://somewherewarm.test/support
Site address (URL): http://somewherewarm.test/support
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.13.2
PHP Version: 7.1.6-1~ubuntu16.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18-0ubuntu0.16.04.1
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 14.65MB
Database Data Size: 9.46MB
Database Index Size: 5.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.48MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 1.02MB + Index: 0.11MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.19MB + Index: 0.25MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.02MB + Index: 0.08MB
wp_postmeta: Data: 2.17MB + Index: 2.66MB
wp_posts: Data: 0.44MB + Index: 0.17MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 39
custom_css: 1
customize_changeset: 3
nav_menu_item: 5
page: 30
post: 1
product: 75
product_variation: 79
revision: 129
scheduled-action: 109
shop_coupon: 3
shop_order: 195
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Query Monitor: by John Blackbourn – 3.3.7
WooCommerce: by Automattic – 3.6.4 – 3.6.5 is available

### Inactive Plugins (0) ###

---

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types:
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 2.4.3 – 2.5.1 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 69
Oldest: 2019-07-08 10:40:42 +0000
Newest: 2019-08-07 12:58:08 +0000

Pending: 14
Oldest: 2019-08-08 09:26:13 +0000
Newest: 2020-05-28 14:19:08 +0000

Canceled: 26
Oldest: 2019-07-08 07:56:50 +0000
Newest: 2019-08-02 13:35:00 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

**Comment by vedanshujain** [comment] 2019-10-02 09:03
Reopening because mentioned PR was closed without merge.

**Comment by vinodglobalstep** [comment] 2021-09-09 16:24
Hi @jimjasson ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using WooCommerce 5.6 version.

Here are the screenshots of the results :

![6_1](https://user-images.githubusercontent.com/46351294/132724714-54c629bb-6873-4c3e-beae-d771c1c2da76.png)

![6_2](https://user-images.githubusercontent.com/46351294/132724735-12deb5a8-5d9e-4066-86d1-6fcd2ed488df.png)
 

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by jimjasson** [comment] 2021-09-13 07:01
Hey @vinodglobalstep, 

Thank you for taking the time to test this! 

I revisited this issue and noticed that I can still replicate it on a local site with only WooCommerce (latest version) + Storefront active. 

I created a short video to illustrate what I am seeing, in case you spot a setting that is different in your configuration: https://share.getcloudapp.com/X6ul70wq. 

Is there a chance that you have added any Shipping Methods in the _Locations not covered by your other zones_ Zone? These methods could show up if none of the other Zones are matched.

**Comment by swatipawarGS** [comment] 2021-11-25 18:06
Hi @jimjasson ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version and WordPress 5.8.2 version.


Please find below screenshots documenting for reference:


https://user-images.githubusercontent.com/94531721/143403992-86a83d58-3be5-4972-accc-a843fd56001b.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment] 2023-10-30 22:54
This is a duplicate of #36797. I'll close this one as a duplicate.

**Closed by rrennick** 2023-10-30 22:54 UTC
Labels: type: bug, type: good first issue, priority: low, focus: shipping [team:Escargot], plugin: woocommerce
