### ISSUE TITLE
Author name isn't correct

### ISSUE THREAD

**Issue by filipemmacedo** [woocommerce/woocommerce#26450] opened 2020-05-11 12:23 UTC
Hello so I want to display the name of the vendor in the product page.
When it shows on shop archive its ok, but on single product displays always the same author.

Can you help me? I display also the biography and the works.

Screenshots attached

<img width="308" alt="Captura de ecrã 2020-05-11, às 13 20 07" src="https://user-images.githubusercontent.com/64608203/81561268-d6fe9580-938a-11ea-911b-dd2c87692c4f.png">
<img width="978" alt="Captura de ecrã 2020-05-11, às 13 19 26" src="https://user-images.githubusercontent.com/64608203/81561271-d8c85900-938a-11ea-9342-6545f7bbb34a.png">
<img width="221" alt="Captura de ecrã 2020-05-11, às 13 19 13" src="https://user-images.githubusercontent.com/64608203/81561274-da921c80-938a-11ea-8f26-f81f6ef8a6c9.png">

**Comment by juliaamosova** [comment] 2020-05-11 14:15
Hi @filipemmacedo,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-05-11 14:15 UTC
