### ISSUE TITLE
[GlobalStep - WooCommerce 4.9] [IE 11] Website fails to display "Increase/Decrease" icon for all the fields at front-end and back-end.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28817] opened 2021-01-14 14:51 UTC
## Bug Description:
Website fails to display "Increase/Decrease" icon for all the fields at front-end and back-end.

## Environment:
Windows 10
Browser: IE11(version 11.1139.18362.0)
                
 ## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Add Some products.
1. Go to frontend.
1. Add some products to the cart.
1. Go to cart page.
1. Observe that "Increment/Decrement icon" fails to display to update the product quantity.

## Actual Result:
Website fails to display "Increase/Decrease" icon for all the fields at front-end and back-end.
 
## Expected Result:
Website should display "Increase/Decrease" icon for all the fields at front-end and back-end.

## Screenshots:

![#28817_1](https://user-images.githubusercontent.com/41110392/104606999-5bd24980-56a6-11eb-86a1-ae1d3c13cbc2.png)

![#28817_2](https://user-images.githubusercontent.com/41110392/104607034-62f95780-56a6-11eb-9d7d-e0bd6fcd9e33.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2021-02-06 19:27
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. The issue is still present in WooCommerce 5.0 RC3. Tested using Browserstack account.

Here is what is expected (in Chrome) - note that when you hover over the entry fields, the up and down arrows appear:

![](http://g.recordit.co/B1mDzpmJ7l.gif)

And here is what happens in IE (and Windows) - see gif below:

https://recordit.co/Vm7XiYzlX9

This is not really a huge deal but we should still likely fix it as WordPress still supports IE.

**Comment by roykho** [comment] 2021-08-05 14:05
Hi @gglobalstep - Thanks for reporting this however this is a browser capability issue as evident from this documentation https://caniuse.com/input-number

IE 10 & 11 simply does not support `number` input type with spinner UI. It does however work with latest Edge browser.

Because of the above findings, we'll be closing this as a won't fix.

**Closed by roykho** 2021-08-05 14:05 UTC
Labels: component: product, priority: high, type: bug
