### ISSUE TITLE
VAT (tax) not applied correctly by manual order (product variations)

### ISSUE THREAD

**Issue by giesbergen1997** [woocommerce/woocommerce#17024] opened 2017-10-02 17:14 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set up a product variation with reduced tax (6% in the Netherlands)
2. Make a manual order in Woocommerce with this product. 
3. Click at Recalculate and take a look at the VAT Column. It should be 6% now, but it shows 21%.

## Expected/actual behavior

When I follow those steps, I see 21% VAT (Normal rate)

I was expecting to see 6% VAT (Reduced rate)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://www.haag-planten.nl/testomgeving
Site URL: https://www.haag-planten.nl/testomgeving
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.1.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
Total Database Size: 24.20MB
Database Data Size: 12.58MB
Database Index Size: 11.62MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.23MB + Index: 0.11MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 2.00MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.06MB + Index: 0.06MB
wp_comments: Data: 0.39MB + Index: 0.34MB
wp_et_social_stats: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nextend_smartslider_layouts: Data: 0.00MB + Index: 0.00MB
wp_nextend_smartslider_sliders: Data: 0.01MB + Index: 0.00MB
wp_nextend_smartslider_slides: Data: 0.07MB + Index: 0.00MB
wp_nextend_smartslider_storage: Data: 0.13MB + Index: 0.01MB
wp_options: Data: 1.38MB + Index: 0.06MB
wp_postmeta: Data: 4.52MB + Index: 6.03MB
wp_posts: Data: 1.52MB + Index: 0.55MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.05MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_relevanssi: Data: 1.52MB + Index: 1.20MB
wp_relevanssi_log: Data: 0.16MB + Index: 0.00MB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.41MB + Index: 0.42MB
wp_users: Data: 0.05MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 57
c_p_tab: 18
flamingo_contact: 386
flamingo_inbound: 244
nav_menu_item: 87
page: 17
post: 2
product: 47
product_variation: 513
revision: 157
safecss: 1
shop_coupon: 2
shop_order: 860
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Maintenance: door fruitfulcode – 3.5.1
WooCommerce: door Automattic – 3.2.0-beta.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #5 - /producten/
Winkelmand: #6 - /winkelwagen/
Afrekenen: #7 - /afrekenen/
Mijn account: #8 - /mijn-account/
Terms and conditions: #153 - /algemene-voorwaarden/

### Theme ###

Name: Boutique
Version: 2.0.10
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rodrigoprimo** [comment] 2017-10-03 14:53
Thanks for your report.

I was not able to reproduce this bug.

Running WooCommerce master on a clean WordPress install with WC dummy data imported (https://docs.woocommerce.com/document/importing-woocommerce-dummy-data/), I enabled taxes and added one tax rate (20%) for the "Standard rates" tax class and another tax rate (6%) for the "Reduced Rate" tax class.

I then changed the tax class of one of the variations of the product "Ship your idea" hoodie to "Reduced Rate". When creating a manual order via the admin, I added the variation product with the reduced tax rate and clicked "Recalculate". Tax where calculated using the correct tax percentage (6%).

Closing this issue for now. Please reopen it if you can provide more details that will help us reproduce the problem.

**Comment by giesbergen1997** [comment] 2017-10-03 18:46
I figered out what is causing (my) problem: at general level I selected Reduced rate. In the product variations I choose "Same as main item", but it changes in "Default". 

So "Same as main item" doesn't seem to work, and all my product variations are set on "Same as main item". In Woocommerce 3.1.2 however, "Same as main item" works properly. 

I have made an Gif image to explain what I mean: https://gyazo.com/d4b4768dc210cf88d51891a4df82642b

I hope you can reproduce this problem now. Apologies for my bad English.

**Comment by rodrigoprimo** [comment] 2017-10-04 12:10
Just to make sure I will test exactly what you are describing, please confirm my assumptions below.

> I figered out what is causing (my) problem: at general level I selected Reduced rate.

You selected "Reduced rate" as the default "Tax class" for a variable product, right?

> In the product variations I choose "Same as main item", but it changes in "Default".

Maybe you mean you selected "Same as parent" (I can't find a option that is labelled "Same as main item", but please correct me if I'm missing it) as the "Tax class" for one of the product variations?

I'm not sure what you meant by "but it changes in 'Default'". Can you please elaborate?

One thing that might help is a screencast showing the configuration of the variable product and the creation of the order with the wrong tax percentage.

Thanks for taking the time to give more information about this issue.

**Comment by giesbergen1997** [comment] 2017-10-04 14:50
> You selected "Reduced rate" as the default "Tax class" for a variable product, right?

Right!

> Maybe you mean you selected "Same as parent" (I can't find a option that is labelled "Same as main item", but please correct me if I'm missing it) as the "Tax class" for one of the product variations?

I'm using the Dutch version, I mean "Same as parent" indeed. 

I have made a screencast, I hope this will clarify my problem. I have uploaded it in here: https://youtu.be/rvwxNCjUNGA

**Comment by rodrigoprimo** [comment] 2017-10-09 13:52
Thanks for the screencast @giesbergen1997. It really helped me understand the problem.

I was able to reproduce it. It seems that on `master` branch it is not possible to save the tax class of a product variation as "Same as parent". You can select this option and save it, but after the variations list reloads it will show "Standard" as the tax class instead of "Same as parent".

I wasn't able to reproduce this problem on WC 3.1.2 so seems like something that was introduced during the development of the upcoming WC 3.2. I will further investigate to understand what is causing this and if it is an intentional change or not.

**Closed** 2017-10-10 11:32 UTC
Labels: Type: Bug

**Comment by mblokdijk** [comment] 2017-10-13 15:51
i am having the same issues here after update 3.2.0 i need to set my product variations tax calcuations to standard (not same as parent, which it is by default, otherwise the variation price is consided ex tax, and does a double tax calculation.

**Comment by giesbergen1997** [comment] 2017-10-13 16:18
@mblokdijk I had this problem too, but installing the master branch of WooCommerce on Github solved the problem! You can find the master branch at the top, click on "code".
