### ISSUE TITLE
[UPDATE SHIPPING COST VIA API] It doesnt works

### ISSUE THREAD

**Issue by PaolinoAngeletti** [woocommerce/woocommerce#28146] opened 2020-10-30 09:45 UTC
I want to update shipping cost to "FLAT RATE" shipping method.
I'm using this data:
data = {
                "enabled" : True,
                "regular_price": {
                    "cost" : str(cost_to_set)
                }
            }

It doesnt' works.. why ???
Enabled works fine, but cost NOT.

**Comment by tammullen** [comment] 2020-11-03 13:38
Hi @PaolinoAngeletti 


While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-11-03 13:38 UTC
