### ISSUE TITLE
Shipping not updating when shipping zone/location is selected in Woocommerce Checkout

### ISSUE THREAD

**Issue by Bossquiat** [woocommerce/woocommerce#28850] opened 2021-01-19 11:10 UTC
in my woocomerce store i have set up shipping for a number of zones. when in the checkout if the user selects one of the shipping locations the shipping cost does not seem to be updating. I have configured the shipping zones correctly, i have double and triple checked them. I have deactivated plugins to see if there was a conflict, but still not change. 

the only time the shipping cost changes, is when i change shipping zone arrangement. for example, united kingdom, canada, india and united states in order. If i move India to the top of the list then India's shipping cost will then become the shipping cost for the entire store.

I have also activated Maxmind Geolocator which hoepfully allows the users location to be captured automatically. But to be sure i wanted to see if there was a way the regular shipping update method could be applied and why it is not working.

the website is geneticbullz.com

@mikejolley @claudiulodro

**Comment by juliaamosova** [comment] 2021-02-06 19:02
Hi @Bossquiat,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-02-06 19:02 UTC
