### ISSUE TITLE
"wc-admin_import_orders" Cron Jobs Do Not Run 

### ISSUE THREAD

**Issue by hwsiew** [woocommerce/woocommerce#29655] opened 2021-04-12 01:49 UTC
**Describe the bug**
When orders are created, from both frontend and backend, the wc-admin_import_orders crons job are scheduled but do not run. The analytics reports remain empty. 

**To Reproduce**

1. Create an order
2. Check 'WooCommerce' -> 'Status' -> 'Schedule Actions' to see if 'wc-admin_import_orders' with the respective order id is scheduled?
3. Reload page to after scheduled time of the cron job.
4. See if the cron job is run and analytic reports show the updated value with the order.

**Expected behavior**
An updated analytic reports with respective order.

**Screenshots**
![image](https://user-images.githubusercontent.com/51040350/114330351-1a055200-9b74-11eb-814d-40b058534e73.png)

**Desktop (please complete the following information):**

* OS: [e.g. iOS] window
* Browser [e.g. chrome, safari] chrome
* Version [e.g. 22] 89

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**
`
### WordPress Environment ###

WordPress address (URL): https://treazpass.local
Site address (URL): https://treazpass.local
WC Version: 5.2.0
REST API Version: ✔ 5.2.0
WC Blocks Version: ✔ 4.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.6
PHP Version: 8.0.1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.5-MariaDB-1:10.5.5+maria~focal
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Total Database Size: 9.24MB
Database Data Size: 7.37MB
Database Index Size: 1.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.05MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Data: 0.25MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 85
custom_css: 2
nav_menu_item: 15
page: 23
post: 3
product: 8
product_variation: 3
revision: 7
shop_coupon: 2
shop_order: 63
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Advanced Custom Fields: by Elliot Condon – 5.9.5
Error Log Monitor: by Janis Elsts – 1.7
Treazpass: by Actiweb Technology – 1.0.0
User Role Editor: by Vladimir Garagulya – 4.59
WooCommerce: by Automattic – 5.2.0-RC.2
WP Crontrol: by John Blackbourn & crontributors – 1.10.0

### Inactive Plugins (1) ###

WooCommerce: by Automattic – 5.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: woocommerce/woocommerce-admin#6 - /shop/
Cart: woocommerce/woocommerce-admin#7 - /cart/
Checkout: woocommerce/woocommerce-admin#8 - /checkout/
My account: woocommerce/woocommerce-admin#9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 20
Oldest: 2021-04-08 14:50:13 +0800
Newest: 2021-04-08 17:31:34 +0800

Pending: 7
Oldest: 2021-04-08 17:35:35 +0800
Newest: 2021-04-12 09:32:24 +0800

### Status report information ###

Generated at: 2021-04-12 09:48:02 +08:00
`

**Comment by barryhughes** [comment] 2021-04-27 17:44
Hi there @hwsiew,

I'm unable to replicate the same problem and I also notice that this seems to be happening in the context of a local dev site: that makes me thing the problem is likely a local environmental issue (there are a few reasons this might happen, including a block on local loopbacks).

To help diagnose this, you might take advantage of a plugin such as [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/). Or, if you happen to have access to a remote hosting environment that you know to support WordPress (that might include hosting provided by [any of these orgs](https://wordpress.org/hosting/)), you could test things there and see if the same problem occurs—if things work as expected in that proven environment, for instance, you'll have a strong hint that the problem is indeed local.

Given the above, I'm thinking that this is essentially a support request rather than a confirmed bug and, given that, you may also wish to follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case.
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/).
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/).

For now, though, I am going to go ahead and close this issue. If I missed something or you can show that this is a general bug rather than a localized issue, please leave a further comment and we will take a second look.

**Closed by barryhughes** 2021-04-27 17:44 UTC
Labels: needs developer feedback
