### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_payment_method() on null

### ISSUE THREAD

**Issue by barrychapman** [woocommerce/woocommerce#25490] opened 2020-01-25 21:29 UTC
**Describe the bug**
On the `canned` thankyou.php template, it throws an error as seen above

**To Reproduce**
1. Add items to cart
2. Pay for items
3. See error on confirmation

Not only that, but this is occurring in `/wp-content/plugins/woocommerce/includes/gateways/paypal/class-wc-gateway-paypal.php:464`

We have the paypal payment gateway DISABLED, so I do not know why this file is even getting invoked.

**Screenshots**
![image](https://user-images.githubusercontent.com/152958/73127530-b6533100-3f8f-11ea-9e57-ffef74ce0c43.png)

**Expected behavior**
To display order details

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://buyessentialhemp.com
Site address (URL): https://buyessentialhemp.com
WC Version: 3.9.0
REST API Version: ✔ 1.0.6
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.2.22
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.21-MariaDB-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.0
WC Database Prefix: wp_
Total Database Size: 19.18MB
Database Data Size: 16.40MB
Database Index Size: 2.78MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_as3cf_items: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_cf_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cf_form_entry_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.05MB + Index: 0.28MB + Engine InnoDB
wp_postmeta: Data: 7.44MB + Index: 0.48MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.22MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 117
custom_css: 1
customize_changeset: 41
elementor_library: 8
nav_menu_item: 22
page: 20
post: 5
product: 17
product_variation: 27
revision: 343
scheduled-action: 199
shop_coupon: 1
shop_order: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

WP Offload Media - Assets Pull Addon: by Delicious Brains – 1.1.1
WP Offload Media: by Delicious Brains – 2.3.2
Astra Pro: by Brainstorm Force – 2.2.5
Code Snippets: by Code Snippets Pro – 2.13.3
Elementor Pro: by Elementor.com – 2.8.3
Elementor: by Elementor.com – 2.8.4
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.3.0 – Not tested with the active version of WooCommerce
Insert Headers and Footers: by WPBeginner – 1.4.4
Jetpack by WordPress.com: by Automattic – 8.1.1
Password Protected: by Ben Huson – 2.2.5
Safe SVG: by Daryll Doyle – 1.9.7
SendGrid: by SendGrid – 1.11.8
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.0.12
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.21

User Role Editor: by Vladimir Garagulya – 4.52.2
Enable Visual Mode in CloudFront: by kawax – 1.0.3
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.3.3 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.24.0 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.7 – Not tested with the active version of WooCommerce
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.8.1 – Not tested with the active version of WooCommerce
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.7.1 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.9.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3
WooCommerce Shipment Tracking: by WooCommerce – 1.6.15 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by StoreApps – 4.5.1 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.0.8 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.9.0
Yoast SEO Premium: by Team Yoast – 12.8.1
WP LB Server ID: by Barry Chapman – 1.0.0

### Inactive Plugins (8) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Caldera Forms: by Caldera Labs – 1.8.9
Klaviyo: by Klaviyo
Inc. – 2.1.4 – Not tested with the active version of WooCommerce

Redirection: by John Godley – 4.6.2
Variation Swatches for WooCommerce: by Emran Ahmed – 1.0.71 – Not tested with the active version of WooCommerce
Variation Swatches for WooCommerce - Pro: by Emran Ahmed – 1.0.39 – Not tested with the active version of WooCommerce
Wordfence Security: by Wordfence – 7.4.5
WP Rocket: by WP Media – 3.4.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #15 - /all-products/
Cart: #16 - /cart/
Checkout: #17 - /checkout/
My account: #18 - /my-account/
Terms and conditions: #69 - /terms-of-service/

### Theme ###

Name: Astra
Version: 2.2.1
Author URL: https://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Google Product Feed fields ###

Product description: Main product description (full preferred) plus variation description.
Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Defaults to "Essential Hemp".
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: 
Google Product Category: 
Size system: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled

### Square ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Display at Checkout

### Customer/Order CSV Export ###

Order Export Format: default
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

### Action Scheduler ###

Complete: 195
Oldest: 2020-01-17 16:58:29 +0000
Newest: 2020-01-25 21:23:56 +0000

Pending: 2
Oldest: 2020-01-25 22:05:42 +0000
Newest: 2020-01-27 17:44:24 +0000

Canceled: 2
Oldest: 2020-01-17 17:00:39 +0000
Newest: 2020-01-24 18:29:31 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by juliaamosova** [comment] 2020-01-27 18:23
Hi {username},

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. I can successfully place an order (via Stripe as an example):

![thank_you page](https://user-images.githubusercontent.com/19143190/73201966-0538cc00-4132-11ea-8a29-cde613ac814d.jpg)

What payment gateway are you using? 

Please provide us with more details about the issue which may help us to evaluate it further. 

Are you able to reproduce the same with all plugins disabled except for WooCommerce and the payment gateway you are using?

**Comment by WillBrubaker** [comment] 2020-01-27 23:22
heya @juliaamosova got another report of this in #2660543-zen

the thankyou.php has a conditional check here: https://github.com/woocommerce/woocommerce/blob/3.9.0/templates/checkout/thankyou.php#L23

but if that conditional evaluates to false, we end up on https://github.com/woocommerce/woocommerce/blob/3.9.0/templates/checkout/thankyou.php#L80 and pass a null value as the 2nd parameter to the `woocommerce_thankyou_order_received_text` filter here: https://github.com/woocommerce/woocommerce/blob/3.9.0/templates/checkout/thankyou.php#L82

Seems there would want to be something completely different ouput there in the case of not an order.

**Comment by galbaras** [comment] 2020-01-28 05:31
@juliaamosova Looks like the Stripe gateway doesn't use the `woocommerce_thankyou_order_received_text` filter. To confirm, use PayPal, as per the OP's conditions.

@WillBrubaker Under what conditions, other than calling the page out of sequence, would `$order` not be set during the processing of the thankyou page?

**Comment by juliaamosova** [comment] 2020-01-28 11:47
@WillBrubaker @galbaras thanks for the additional feedback. I can reproduce the issue now:

![screencapture-jamosova2-mystagingwebsite-checkout-order-received-2020-01-28-11_44_29](https://user-images.githubusercontent.com/19143190/73261388-e08d3480-41c3-11ea-8f1d-2103b074fab0.png)

**Comment by claudiosanches** [comment] 2020-01-28 16:13
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25507.

**Closed** 2020-01-28 16:12 UTC
Labels: bug, has pull request, priority: high
