### ISSUE TITLE
Cart is showing Empty in Internet Explorer and in Safari

### ISSUE THREAD

**Issue by a2zwebtech** [woocommerce/woocommerce#26199] opened 2020-04-16 19:00 UTC
Hi!
I am using Boutique Version: 2.0.17 in my store. It have latest WooCommerce 4.0.1. Its working fine in firefox, chrome etc browser. But in Internet explorer or in safari, after add product in cart and go checkout page, cart showing empty. I have deactivated all plugins and there no any caching plugin used. My system status is like below

```
### WordPress Environment ###

WordPress address (URL): https://thedogsstore.co.uk
Site address (URL): https://thedogsstore.co.uk
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.12
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32-78.0-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_n87kx54caf_
Total Database Size: 26.83MB
Database Data Size: 23.67MB
Database Index Size: 3.16MB
wp_n87kx54caf_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_n87kx54caf_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_n87kx54caf_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_n87kx54caf_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_n87kx54caf_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_n87kx54caf_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_n87kx54caf_actionscheduler_actions: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_n87kx54caf_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_n87kx54caf_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_n87kx54caf_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_n87kx54caf_commentmeta: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_formmaker: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_backup: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_blocked: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_display_options: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_query: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_submits: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_themes: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_formmaker_views: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_frm_fields: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_frm_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_frm_items: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_frm_item_metas: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_n87kx54caf_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_chunks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_field_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_object_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_nf3_upgrades: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_ninja_table_items: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_options: Data: 6.28MB + Index: 0.32MB + Engine MyISAM
wp_n87kx54caf_postmeta: Data: 1.48MB + Index: 0.43MB + Engine MyISAM
wp_n87kx54caf_posts: Data: 1.00MB + Index: 0.14MB + Engine MyISAM
wp_n87kx54caf_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_n87kx54caf_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_usermeta: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_n87kx54caf_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_n87kx54caf_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_n87kx54caf_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_n87kx54caf_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_n87kx54caf_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_n87kx54caf_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_n87kx54caf_wc_product_meta_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_n87kx54caf_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfBlockedIPLog: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_wfBlocks7: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfConfig: Data: 2.42MB + Index: 0.02MB + Engine MyISAM
wp_n87kx54caf_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfFileMods: Data: 1.93MB + Index: 0.40MB + Engine MyISAM
wp_n87kx54caf_wfHits: Data: 6.32MB + Index: 0.76MB + Engine MyISAM
wp_n87kx54caf_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfIssues: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_n87kx54caf_wfKnownFileList: Data: 1.00MB + Index: 0.12MB + Engine MyISAM
wp_n87kx54caf_wfLiveTrafficHuman: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_n87kx54caf_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfLogins: Data: 0.15MB + Index: 0.04MB + Engine MyISAM
wp_n87kx54caf_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_n87kx54caf_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_n87kx54caf_wfNotifications: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wfStatus: Data: 0.19MB + Index: 0.08MB + Engine MyISAM
wp_n87kx54caf_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_n87kx54caf_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 399
customize_changeset: 8
fmemailverification: 1
form-maker: 1
frm_form_actions: 4
frm_styles: 1
nav_menu_item: 17
ninja-table: 5
page: 16
pewc_field: 40
pewc_group: 18
pewc_product_extra: 15
popup_theme: 6
post: 2
postman_sent_mail: 9
pricingtable: 1
product: 193
product_variation: 37
revision: 311
shop_coupon: 2
shop_order: 21
shop_order_refund: 1
sln_attendant: 2
sln_service: 4
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Akismet Anti-Spam: by Automattic – 4.1.4
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.7
Contact Widgets: by GoDaddy – 1.7.0
Facebook for WooCommerce: by Facebook – 1.9.7 – Not tested with the active version of WooCommerce
Fast Velocity Minify: by Raul Peixoto – 2.3.2
Form Maker: by 10Web Form Builder Team – 1.13.22
Formidable Forms: by Strategy11 – 4.03.03
Fusion Core: by ThemeFusion – 3.3.1
Handmade Framework: by g5plus – 1.3
Insert Headers and Footers: by WPBeginner – 1.4.5
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Mega Addons For WPBakery Page Builder: by Nasir – 4.0
Ninja Forms: by Saturday Drive – 3.4.24.1
Ninja Tables: by WPManageNinja LLC – 3.5.12
Google Fonts Typography: by Fonts Plugin – 2.0.0
WooCommerce Product Add-Ons Ultimate: by Plugin Republic – 3.6.3
Responsive WordPress Slider - Soliloquy Lite: by Soliloquy Team – 2.5.10
Theme Authenticity Checker (TAC): by builtBackwards – 1.5.3
Addon for Stripe and WooCommerce: by Estatic Infotech Pvt Ltd – 2.0.4 – Not tested with the active version of WooCommerce
Woo Variations Table: by Alaa Rihan – 2.2.0
WooCommerce: by Automattic – 4.0.1
Wordfence Security: by Wordfence – 7.4.6
WP File Manager: by mndpsingh287 – 5.9
WP Reset: by WebFactory Ltd – 1.77

### Inactive Plugins (5) ###

Mailchimp for WooCommerce: by Mailchimp – 2.3.6
Storefront Footer Copyright Text: by Storefront Footer Text – 1.0.0
Storefront Product Pagination: by WooThemes – 1.2.3 – Not tested with the active version of WooCommerce
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Sticky Add to Cart: by WooThemes – 1.1.8

### Dropin Plugins (1) ###

object-cache.php: APCu Object Cache

### Must Use Plugins (1) ###

System Plugin: by  – 3.16.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Boutique
Version: 2.0.17
Author URL: http://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8 – 2.5.5 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 281
Oldest: 2020-03-16 22:48:34 +0000
Newest: 2020-04-16 17:37:30 +0100

`)
```
Please check and let me know if someone can help me for solve it.
Thanks!

**Comment by tammullen** [comment] 2020-04-17 00:05
Hi @a2zwebtech 

Thank you for raising the issue. However, I can’t reproduce it on my end.
​
I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme to [Storefront](https://en-gb.wordpress.org/themes/storefront/) instead of Boutique. Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-04-24 19:44
Hi @a2zwebtech,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-04-24 19:44 UTC
Labels: can't reproduce, status: needs feedback
