### ISSUE TITLE
Reviews are Posting in Duplicate

### ISSUE THREAD

**Issue by kimatliah** [woocommerce/woocommerce#24436] opened 2019-08-19 18:31 UTC
When a review is left on a product in our WooCommerce store it duplicates. Screenshot is attached. 

![Screenshot_4](https://user-images.githubusercontent.com/54287041/63289845-17166900-c28e-11e9-8907-2f7ac4a2f203.png)

**Comment by claudiosanches** [comment] 2019-08-19 21:45
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried test what you said in a clean install of WooCommerce and it appeared to work correctly.

Not sure what could be, since all issue template has been removed, and no details about plugins or anything else, but I can guess that is just your theme showing it twice.

Please post back if you can provide more details on how to reproduce this issue on a clean install of WooCommerce. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-08-19 21:45 UTC
