### ISSUE TITLE
Display of products and subcategories of the current category

### ISSUE THREAD

**Issue by oweichpold** [woocommerce/woocommerce#27176] opened 2020-07-30 08:16 UTC
Hello! 

I'm having problems displaying the categories and sub categories and products. 

It is set to display only products and subcategories of the current category.

Unfortunately ALL subcategories and ALL products of the sub categories of the current category are displayed. 

What else can I set or change here? 

Thanks a lot in advance!

**Comment by tammullen** [comment] 2020-07-30 09:49
Hi @oweichpold 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-07-30 09:49 UTC
