### ISSUE TITLE
Stock does not reduce if item is added to an already processing order.

### ISSUE THREAD

**Issue by MarkHaynes** [woocommerce/woocommerce#27445] opened 2020-08-21 20:38 UTC
[ x] I have carried out troubleshooting steps and I believe I have found a bug.
[ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have made processing orders editable so that we can add items to stock after a customer has made a purchase.

In the past (prior to 4.4) adding an item to an already processing order reduced that items stock, however, it no longer does.

Even adding the items and clicking save or update order does not reduce stock. The only way is to move the order back to pending payment add the items, save the order then change it to processing?

I believe this is linked to Commit 26642 – https://github.com/woocommerce/woocommerce/pull/26642

**Is this the intention?**

**Expected behaviour**
Adding stock to already processing orders reduces the item's stock.

**Actual behaviour**
Stock is not reduced.

Steps to reproduce the bug:
1. Prerequisite - Allow processing orders to be editable.
2. Create an order manually, add items set it to processing.
3. Now add more items to the already processing order.
4. Observe no stock has reduced.

**Comment by tijosh** [comment] 2020-09-02 17:53
+1, able to reproduce this

**Comment by tijosh** [comment] 2020-09-08 15:07
To add more context, adding products to existing orders that are `On hold` does not reduce stock of those items. The stock of the originally-added item does reduce if modified. 

The order must be set to `Pending Payment` and then back to `Processing` for stock levels to update. 

![Screenshot](https://d.pr/i/7hlRaC+)
*Link: https://d.pr/i/7hlRaC*

Here's the best procedure to add items to existing orders:

1. Set the order to `Pending Payment`
2. Modify the products in the order
3. Request payment from customer (if necessary)
4. Set order back to `Processing`

@vedanshujain what do you think? Is this the expected behavior for adding items to existing `On hold` orders?

**Comment by bamarlay** [comment] 2020-09-10 02:10
Hi,

Thanks for the clarification. I also have the same problem, and didn't realized this behavior until I have updated a few orders (customers called to our shop to add a few more items after they raise the order). We had to manually search all those updated orders, record all the items added and manually reduce the stock quantity, which is a bit annoying. We use Woocommerce not only only as an online store but also manage phone orders and orders coming from Facebook messenger through it, and allow our customers to change their order before we ship the orders. Imagine a store owner who never realized this behavior and wondering where his stocks disappear when they still show as available on Woocommerce! 

My suggestion is that if we do not update the inventory when new items are added to the On Hold orders, then this function (to add new items) should be disable for On Hold order as well, and only enable it for pending orders. This way, all changes to the order have to be made in pending status, and stock updated when its status changed to On Hold/Processing.

Thnaks

Myat

**Comment by vedanshujain** [comment] 2020-09-23 19:42
Looks like this is because the change in PR #26642 exposed an underlying bug where we are checking if the `_reduced_stock` meta is already set in `wc_maybe_adjust_line_item_product_stock`. This is not accurate, as that function should work regardless. 
I am restoring back the original behavior in #27763 while we discuss if we should limit stock updates for status changes, or do it for everything.

**Comment by Diabolikjn** [comment] 2020-10-05 15:17
Hello, I just wanted to chime in here and express my displeasure at this change overall.  Can we please move back to the inventory amounts adjusting when an order is on hold.  It wasn't broken, so why fix it ?

**Comment by Diabolikjn** [comment] 2020-10-07 15:58
Any update on this ?  It looks like the last ticket update was 2 weeks ago and this impacting business every day

**Comment by vedanshujain** [comment] 2020-10-08 10:51
@diablodale the fix is waiting for approval, if approved it will be included in our November release (4.7). as a workaround, if you are comfortable with editing code, editing this line should fix the issue meanwhile:

On line 213, in file woocommerce/includes/admin/wc-admin-functions.php
https://github.com/woocommerce/woocommerce/pull/27763/files#diff-552b5c356f0782a4d69ea8ef1a604455R213

(All other changes in the PR are unit tests which are not included in the final release).

**Comment by diablodale** [comment] 2020-10-08 11:33
I think V meant to type @Diabolikjn instead. :-)

**Closed** 2020-10-15 08:01 UTC
Labels: bug, priority: high, question

**Comment by negapo** [comment] 2020-11-02 10:39
Hi, why was this closed? Its still not solved.

**Comment by Konamiman** [comment] 2020-11-03 08:51
This was closed automatically because [the fixing pull request](https://github.com/woocommerce/woocommerce/pull/27763) was merged. It should have been included in 4.7 beta, wasn't it the case?

**Comment by negapo** [comment] 2020-11-03 09:13
Sorry, thought it was part of 4.6.1

**Comment by Konamiman** [comment] 2020-11-03 09:17
@negapo No problem, but here's a tip that you may find useful: for merged pull requests you can see which version they are included in by looking at "Milestone" on the right 🙂

**Comment by negapo** [comment] 2020-11-03 09:20
thanks for the tip @Konamiman

**Comment by zdenys** [comment] 2020-11-10 11:34
There has been another report in https://wordpress.org/support/topic/pending-and-on-hold-statuses-doesnt-reduce-products-stock/ I'm glad to see that a patch has been created already 🎉

**Comment by jasongm98** [comment] 2020-11-12 18:43
The error still presents but only for the API endpoints (with the administration panel works) I will open a new request.
