### ISSUE TITLE
Unwanted meta information adding on every order

### ISSUE THREAD

**Issue by robi06** [woocommerce/woocommerce#26969] opened 2020-07-07 07:27 UTC
Hello, We are getting unwanted order meta information attached with order's line item or sometime with shipping method thos are not related with that order or line items. This is happening randomly almost on every orders. For better understanding check the screenshot i have attached. It's been a long time we are using Woocommerce,  it's never happened before. Currently we are using latest Woocommerce  version.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Expected behavior**
Unwanted meta information should not be stored on db randomly.

Steps to reproduce the bug:
You just need to create a new order then check that order details on admin orders section.

**Screenshots**
![Standard_Products_presenting_as_Variable](https://user-images.githubusercontent.com/7699935/86735248-7cb14680-c054-11ea-8de9-0b2159dc8168.jpg)

![Variable_Products_Order_in_admin_is_showing__2_sizes_instead_of_just_one](https://user-images.githubusercontent.com/7699935/86735437-a0748c80-c054-11ea-8090-a4f0c1e064fb.png)

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X]  This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://secure.jeffdunham.com
Site address (URL): https://secure.jeffdunham.com
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.19
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 8192
cURL Version: 7.71.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: wp_
Total Database Size: 1178.25MB
Database Data Size: 667.69MB
Database Index Size: 510.56MB
wp_woocommerce_sessions: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 7.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 92.64MB + Index: 83.22MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_abj404_logsv2: Data: 56.04MB + Index: 31.58MB + Engine MyISAM
wp_abj404_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_abj404_permalink_cache: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_abj404_redirects: Data: 8.95MB + Index: 14.82MB + Engine MyISAM
wp_abj404_spelling_cache: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_actions: Data: 29.56MB + Index: 26.56MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.52MB + Index: 5.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 44.58MB + Index: 43.09MB + Engine InnoDB
wp_lecm_rewrite: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 1.41MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 43.08MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 39.53MB + Index: 9.20MB + Engine InnoDB
wp_postmeta: Data: 219.78MB + Index: 199.55MB + Engine InnoDB
wp_posts: Data: 25.55MB + Index: 14.06MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stock_log: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_term_relationships: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 54.59MB + Index: 50.14MB + Engine InnoDB
wp_users: Data: 7.52MB + Index: 7.55MB + Engine InnoDB
wp_vxcf_mailchimp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vxcf_mailchimp_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vxcf_mailchimp_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 6.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.20MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_stats: Data: 10.52MB + Index: 10.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.17MB + Index: 0.22MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wsal_metadata: Data: 4.52MB + Index: 6.03MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.42MB + Index: 0.47MB + Engine InnoDB
wp_wsal_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 2.52MB + Index: 0.45MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1278
blocks: 5
customize_changeset: 2
fusion_tb_section: 1
nav_menu_item: 35
page: 19
post: 6
product: 367
product_variation: 632
revision: 180
shop_coupon: 9
shop_order: 96151
shop_order_refund: 5
wfcm_file_event: 1
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

404 Solution: by Aaron J – 2.22.9
Advanced Custom Fields: by Elliot Condon – 5.8.12
Contact Form 7 Connector: by ARI Soft – 1.1.9
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.2
Site Kit by Google: by Google – 1.10.0
Login or Logout Menu Item: by cartpauj – 1.2.0
Mailchimp for WooCommerce: by Mailchimp – 2.4.1 – Installed version not tested with active version of WooCommerce 4.2.2
Nextend Social Login: by Nextendweb – 3.0.24
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.6.6
Website File Changes Monitor: by WP White Security – 1.6.1
WooCommerce Authorize.Net Gateway: by Pledged Plugins – 5.1.15
WooCommerce AvaTax: by SkyVerge – 1.9.4 – Installed version not tested with active version of WooCommerce 4.2.2
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.5.5 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.6.6
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.22
WooCommerce Sequential Order Numbers: by SkyVerge – 1.9.5 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce UPS Shipping: by WooCommerce – 3.2.23 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce USPS Shipping: by WooCommerce – 4.4.40 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce - StampscomEndicia Integration: by Stamps.comEndicia – 2.0.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Stock Manager: by StoreApps – 2.3.0
WooCommerce: by Automattic – 4.2.2
WooSidebars: by WooCommerce – 1.4.5
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO: by Team Yoast – 14.4.1
WP Activity Log: by WP White Security – 4.1.2
YITH WooCommerce Wishlist: by YITH – 3.0.11

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #149 - /terms-of-use/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.11.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome-child/woocommerce/archive-product.php
flatsome-child/woocommerce/cart/cart-empty.php
flatsome-child/woocommerce/cart/cart-shipping.php
flatsome-child/woocommerce/cart/cart-totals.php
flatsome-child/woocommerce/cart/cart.php
flatsome-child/woocommerce/cart/proceed-to-checkout-button.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome-child/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome-child/woocommerce/single-product/product-attributes.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### Action Scheduler ###

Canceled: 159
Oldest: 2020-06-08 23:41:22 +0000
Newest: 2020-07-06 13:56:14 +0000

Complete: 108,749
Oldest: 2020-06-10 12:42:32 +0000
Newest: 2020-07-07 07:05:29 +0000

Failed: 1
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment] 2020-07-07 15:17
Hi @robi06,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

Here is the order I placed for one of the variable products on my test site:

![variable_order](https://user-images.githubusercontent.com/19143190/86802879-75ce0800-c043-11ea-86aa-a5762f9acdbd.jpg)

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by robi06** [comment] 2020-07-08 06:29
Hi @juliaamosova,
   Thank you very much. Though i already tried what you just said, i will try again today with caution. Let's see what happen next. I will get back soon :)

**Comment by juliaamosova** [comment] 2020-07-15 21:41
Hi @robi06,

Please let us know if you've tested again and if you have any more feedback to share. Thanks!

**Comment by juliaamosova** [comment] 2020-07-31 19:04
Hi @robi06,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-07-31 19:04 UTC
Labels: can't reproduce, status: needs feedback
