### ISSUE TITLE
Emoji in customer note results in customer emails not sent 

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce#28767] opened 2021-01-09 12:51 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When a customer adds an emoji to the customer note at checkout, transactional customer emails are not sent out. Admin emails still go out as expected. 

**Expected behavior**
Even if an emoji is added to the customer note at checkout, emails should still be sent out.

**Actual behavior**
When an emoji is included in the customer note, the order is created as usual. However, the order confirmation and completed emails are not sent. The option "resend customer invoice" from the order also has no impact.

No error is displayed, no mention in the logs, and the emails are not shown in the mail log (using the [Mail Logging ](https://wordpress.org/plugins/wp-mail-logging/)plugin). 

When the emoji is removed from the order notes, the order can be sent out as usual. 

It may be related to #24405 where emails could not be saved when an emoji was included.

Reported in #3634816-zen

Confirmed on the customer's site and my own test site.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new order from the website front end by adding a product to the cart and proceeding to checkout. 
2. At checkout, add a customer note and include an emoji ([example](https://emojipedia.org/smiling-face-with-smiling-eyes/)).
3. Submit the order
4. Confirm that the store admin emails are sent and received, but the customer confirmation is not sent
5. Edit the order and remove the emoji from the order note
6. In the order, resend the invoice and note that it is now sent correctly

**Screenshots**

<img width="616" alt="Screen Shot on 2021-01-09 at 13-45-13" src="https://user-images.githubusercontent.com/17844465/104092125-3696a300-5282-11eb-9568-6ca8425fb257.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
### WordPress Environment ###

WordPress address (URL): https://woodev.mystagingwebsite.com
Site address (URL): https://woodev.mystagingwebsite.com
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.25
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 21.18MB
Database Data Size: 12.47MB
Database Index Size: 8.71MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.28MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_commentmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
30_wp_comments: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
30_wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
30_wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_email_orders: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
30_wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
30_wp_followup_followup_history: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_options: Data: 0.19MB + Index: 0.05MB + Engine InnoDB
30_wp_postmeta: Data: 0.39MB + Index: 0.39MB + Engine InnoDB
30_wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
30_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
30_wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
30_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
30_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
30_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.38MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.22MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 50
aw_workflow: 1
bookable_person: 7
bookable_resource: 9
custom_css: 2
customize_changeset: 1
event_ticket: 4
fgf_rules: 1
follow_up_email: 12
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 16
page: 37
post: 3
product: 59
product_variation: 37
revision: 89
shop_coupon: 10
shop_order: 235
shop_order_refund: 8
shop_subscription: 11
slide: 2
user_request: 1
warranty_request: 6
wc_booking: 27
wc_membership_plan: 5
wc_product_tab: 2
wc_user_membership: 2
wcpf_item: 5
wcpf_project: 2
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.7.0
WooCommerce: by Automattic – 4.8.0
WP Mail Logging: by MailPoet – 1.9.7

### Inactive Plugins (118) ###

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.5.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.8.0 (update to version 3.1.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 195
Oldest: 2020-12-09 13:12:04 +0000
Newest: 2021-01-09 12:44:14 +0000

Pending: 5
Oldest: 2021-01-09 12:50:54 +0000
Newest: 2021-01-11 08:35:29 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2021-01-10 23:14
Hi @hannahswain,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I am receiving a customer new order email when I am adding an emoji as a customer to my order. Please see below:

**Order without emoji:**

![o-emoji](https://user-images.githubusercontent.com/19143190/104138051-75eeed80-536f-11eb-887f-5aaaf8f14730.jpg)

**Order with an emoji:**

![emoji](https://user-images.githubusercontent.com/19143190/104138052-7a1b0b00-536f-11eb-8b4e-29749ab412b9.jpg)

I wonder if it makes a difference how an emoji was added. I added mine by selecting an emoji on the MacBook touch bar as I was typing a note. Please share details of how the emoji was added in your case?

**Comment by Luminus** [comment] 2021-01-11 07:47
I've just tested this and I'm not able to reproduce it either. The customer email is sent and the emojis come through just fine.

I tested both on a local test site and a Pressable site to make sure I had consistent results regardless of infrastructure.

![Order Notes With Emoji](https://user-images.githubusercontent.com/248077/104155471-3233cc80-53df-11eb-8587-ab57a640eda4.jpg)

I use [Rocket](https://matthewpalmer.net/rocket/) to enter emojis since it allows Slack-like notation.

I don't think how the emojis are added is a material issue as they are Unicode characters.

I suspect that this might be something specific to the customer's site.

**Comment by hannahswain** [comment] 2021-01-11 11:51
Thanks for testing, @juliaamosova and @Luminus.

I tested this on a Pressable site and copy/pasted an emoji from here: 
https://emojipedia.org/smiling-face-with-smiling-eyes/

I was using Firefox on MacOS.

> I don't think how the emojis are added is a material issue as they are Unicode characters.

Exactly, this should either work or not work. I'll also follow up with our customer in the ticket (#3634816-zen) to confirm how they added the emoji.

**Comment by jessLundie** [comment] 2021-01-12 16:59
The customer in 3634816-zen reported back that they added the emoji via her Android Samsung S10e - she did not use a shortcut. It was just selecting it from her phone keyboard.

I was able to replicate this on my Pressable site with the current version of WooCommerce by copy/pasting the same emoji that @hannahswain did. Additionally, in my test no admin order emails were logged in WP Mail Logging for this order. Chrome + MacOS. I also tried editing the order, replacing the emoji with one from my MacBook touchbar, and resending - no luck. No Order Invoice email was logged. 

However, I think we need to double check how we're confirming email sends in our testing, because...

* I was using WP Mail Logging, which did not log order emails or admin emails with an emoji
* I did actually *receive* the New Order Email with an emoji
* The email I received was not logged by WP Mail Logging

When I tested on a local environment (Local by Flywheel), I also saw no emoji-emails logged by WP Mail Logging. However, Mailhog *did* log both the *Order Processing* and *New Order* emails with their emoji.

The customer also mentioned in their original chat that they confirmed the failed send by checking WP Mail Logging.
Could we be looking at a WP Mail Logging issue here? How did you all confirm whether or not an email was sent in your testing?

**Comment by jessLundie** [comment] 2021-01-12 17:58
This customer just got back to us with the results of a test I requested - the emails are sending, they're just not being logged in WP Mail Logging when they have an emoji.

I think we can close this! I'll reach out to the MailPoet team directly and let them know what we've found on WP Mail Logging :)

**Comment by hannahswain** [comment] 2021-01-13 07:47
Thanks for digging into this and catching that it's actually a problem with Mail Logging, @jess!

**Comment by juliaamosova** [comment] 2021-01-13 15:52
Thanks for getting to the bottom of it @jessLundie! I am closing this issue then. However, please feel free to comment here again in case we missed something so we could take a look further.

**Closed by juliaamosova** 2021-01-13 15:52 UTC
Labels: category: can't reproduce, needs feedback
