### ISSUE TITLE
Can't make billing_state required.

### ISSUE THREAD

**Issue by degregar** [woocommerce/woocommerce#25989] opened 2020-03-21 13:15 UTC
**Describe the bug**
While trying to make billing_state field required, it's rendered in edit billing address form as optional and dropdown. If I change country from PL to different country it shows text field with required indicator. I think some JavaScript used to render state after selecting country is rendered incorrectly, but I can't find where and how is it made.

**To Reproduce**

Add this code to functions.php to custom made theme.
```
add_filter('woocommerce_billing_fields', function ($address_fields) {
    $address_fields['billing_state']['required'] = true;
}, 9000, 1);

add_filter('woocommerce_states', function ($states) {
    $states['PL'] = [
            "dolnośląskie" => "dolnośląskie",
            "kujawsko-pomorskie" => "kujawsko-pomorskie",
            "lubelskie" => "lubelskie",
            "lubuskie" => "lubuskie",
            "łódzkie" => "łódzkie",
            "małopolskie" => "małopolskie",
            "mazowieckie" => "mazowieckie",
            "opolskie" => "opolskie",
            "podkarpackie" => "podkarpackie",
            "podlaskie" => "podlaskie",
            "pomorskie" => "pomorskie",
            "śląskie" => "śląskie",
            "świętokrzyskie" => "świętokrzyskie",
            "warmińsko-mazurskie" => "warmińsko-mazurskie",
            "wielkopolskie" => "wielkopolskie",
            "zachodniopomorskie" => "zachodniopomorskie",
    ];

    return $states;
}, 10, 1);

```

**Screenshots**
![Zaznaczenie_281](https://user-images.githubusercontent.com/7668271/77226589-ce06fa00-6b79-11ea-84c4-9d82d28670e2.png)

**Expected behavior**
Setting billing_state as required shows red required indicator in edit billing address form if having dropdown list.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**Comment by AmeenJalali** [comment] 2020-03-27 01:50
Try this:

add_filter('woocommerce_get_country_locale', 'make_PL_state_required');
function make_PL_state_required($locale){
  $locale['PL']['state']['required'] = true;
  return $locale;
}

**Comment by AmeenJalali** [comment] 2020-03-27 01:50
Try this:

`add_filter('woocommerce_get_country_locale', 'make_PL_state_required');
function make_PL_state_required($locale){
$locale['PL']['state']['required'] = true;
return $locale;
}`

**Comment by deyil** [comment] 2020-04-01 08:34
I am facing the same issue. 
After contacting my theme developer (thought it their issue) the mentioned that by default State is required. 

But in Greece State field in shipping and billing is optional. In other EU countries, it is required?!

I am attaching relevant photos.
<img width="606" alt="Screenshot 2020-04-01 at 11 33 55 AM" src="https://user-images.githubusercontent.com/872880/78116271-b5fe6880-740c-11ea-8df6-d8d4c8853a25.png">
<img width="609" alt="Screenshot 2020-04-01 at 11 33 45 AM" src="https://user-images.githubusercontent.com/872880/78116279-b7c82c00-740c-11ea-8983-580a24039747.png">

**Comment by tammullen** [comment] 2020-05-19 14:26
Hi @degregar 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
Label:

**Closed by tammullen** 2020-05-19 14:26 UTC
