### ISSUE TITLE
get_current_page was called incorrectly

### ISSUE THREAD

**Issue by wpessential** [woocommerce/woocommerce#27621] opened 2020-09-09 08:03 UTC
Hi Team WooCommerce,
I found an error on my demo import page and error is:

**Notice: get_current_page was called incorrectly. Current page retrieval should be called on or after the `current_screen` hook. Please see **

![error](https://user-images.githubusercontent.com/24288930/92571666-d4f70580-f29c-11ea-99a9-a38ba78066cc.jpg)

**Comment by wpessential** [comment] 2020-09-09 08:04
And WooCommerce Version is 4.5.0

**Comment by juliaamosova** [comment] 2020-09-09 12:49
Hi @wpessential,

Thanks for raising the issue. However, I am not sure yet it is coming from WooCommerce. Can you please provide more clear steps to reproduce the issue? Are you using the WooCommerce plan on the WordPress.com website? Are you trying to import products via CSV file to your site? 

The more details you can provide, the faster we will be able to understand what could be happening.

**Comment by wpessential** [comment] 2020-09-13 18:03
Hi @juliaamosova,
Thanks for your response. We are using woocommerce with our themes. and try to import the theme dummy demo, the demo screen set the error as I attached on above. When I deactivate the woocommerce plugin, then the errors disappeared on my demo screen. And demo import is [MerlinWP](http://merlinwp.com/).

**Comment by tammullen** [comment] 2021-03-25 20:56
Hi @wpessential 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. The issue you are having seems to be caused by the theme you are using.

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 20:56 UTC
Labels: has feedback
