### ISSUE TITLE
Bug checkout coupon

### ISSUE THREAD

**Issue by NicolasKulka** [woocommerce/woocommerce#21854] opened 2018-11-07 16:01 UTC
Add coupon in checkout and bug with json wc-ajax

SyntaxError: Unexpected token i in JSON at position 0

**Comment by kloon** [comment] 2018-11-07 19:31
Not able to reproduce. Please test with all plugins except WooCommerce disabled and also with your theme switched to Twentyseventeen or Storefront. Since you omitted to fill out the template when opening the issue it is hard for us to debug this or see if it might be related to a theme or plugin conflict.

Closing this, will reopen once you can confirm you get the issue by following the steps outlined in the template when you opened this issue and can provide step by step instructions to reproduce.

**Closed by kloon** 2018-11-07 19:31 UTC
