### ISSUE TITLE
Pagination and product count error

### ISSUE THREAD

**Issue by jbrandek** [woocommerce/woocommerce#23858] opened 2019-06-03 03:39 UTC
Hi guys i dont know if anyone of you had this issue but the product count says showing 1-20 of 275 products
And on that category i only have in stock 185 and showing 17 in stead of 20 as it says, i dont have empy spaces just finish the page before all the 20 product show up

i uploaded the products before the import of woocommerce but even updating the product from their import suite wont fix it.
Tried to add a code on functions that i find on this page but nothing fix it.
Even chnge the theme and disable all plugins and still the same...

How can i fix the instock? taxonomy?

try to recount on woocommerce status and didnt fix it either... cant find any other solution

one more thing, if i dont hide out of stock status or if i make all theproducts in the category with stock pagination and product count work fine, is something to do with the out of stock products

**Comment by claudiosanches** [comment] 2019-06-03 10:52
Missing several information in this bug report, can you please fill an the fields below?

<pre>
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

</pre>

**Comment by jbrandek** [comment] 2019-06-03 14:02
Sorry i post you the link
https://judaicapanama.com/productos/infantiles/
if you check the link, the count says 1 of 20 but only showing 17 products
also the total count says 275 products when they are really 171 in stock
same happens to all the categories i dont know why it not showing 20 products per page as it should be.

i have deactivated all plugis and did not fix it
i change theme and did not fix it
it always happen and in all shopping pages

the only way to fix it right now is to show all inventory, but i only want to show only in stock items...
if you chose a category and change all stock to 1 so everything is in stock all works perfect i think is somthing that out of stock products are leaving some space butl it places at the end... not spaces in the middle or between products

**Comment by claudiosanches** [comment] 2019-06-03 14:41
@jbrandek sorry, but still not what I'm asking, can you please fill that template? Will help a lot to help you.
Probably better to start a new issue: https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=

I'll close this as `invalid` since the template has been ignored.

**Closed by claudiosanches** 2019-06-03 14:41 UTC
Labels: status: needs feedback
