### ISSUE TITLE
Problem about WC Admin

### ISSUE THREAD

**Issue by rodolphebertozzo** [woocommerce/woocommerce#25979] opened 2020-03-20 08:37 UTC
My dashboard is not loading, I refreshed the page but nothing to do. The problem occurs exclusively with the "Revenue" part of the dashboard
![bug1](https://user-images.githubusercontent.com/56270626/77147783-61fb9780-6a8e-11ea-9343-552fce421bf0.PNG)
![bug2](https://user-images.githubusercontent.com/56270626/77147786-62942e00-6a8e-11ea-920b-64ca64bcfbc9.PNG)

**Comment by juliaamosova** [comment] 2020-03-20 14:20
Hi @rodolphebertozzo,

Sorry to hear about the trouble! It is very difficult to understand what is causing the issue based on the screenshot you provided. It could be all kinds of things. 

Do you see any errors in the error logs or browser console? 

Another thing to try is a theme and plugins conflict test. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Closed** 2020-03-21 16:32 UTC
Labels: status: needs feedback
