### ISSUE TITLE
Woocommerce 3.0.2 tax display issue

### ISSUE THREAD

**Issue by jkhopkins** [woocommerce/woocommerce#14331] opened 2017-04-13 07:00 UTC
### EXPLANATION OF THE ISSUE

I always enter prices including tax and I've set Woocommerce to always display prices including tax, so the price I enter is the same price which shows on the website.  Now, since updating to 3.0.2, the frontend is adding tax on top of the price even though it already includes tax.
Example:
I enter a product with a price of $200 including tax, it should display on the website as $200, but instead it is showing as $220 because it's adding the tax again (GST 10% tax).

### STEPS TO REPRODUCE THE ISSUE

My settings are:
Prices entered with tax:  Yes, I will enter prices inclusive of tax
Calculate tax based on:  Customer shipping address	
Shipping tax class:  Standard
Rounding:  unticked
Additional tax classes:  none	
Display prices in the shop:  Including tax
Display prices during cart and checkout	:  Including tax
Price display suffix:  inc. GST
Display tax totals:  Itemized

I've tried toggling the setting between "Yes, I will enter prices inclusive of tax" and "No, I will enter prices exclusive of tax" and it makes no difference, it still shows the price on the frontend with tax added.
I've also tried it with all plugins disabled, and different themes, but problem persists.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://dev.jkhopkins.com.au
Site URL: http://dev.jkhopkins.com.au
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 100 MB
PHP Time Limit: 900
PHP Max Input Vars: 5000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (12) ###

Redux Framework: by Team Redux – 3.6.4
XTEMOS Post Types plugin: by  – 1.1
CMB2: by WebDevStudios – 2.2.4
Contact Form 7: by Takayuki Miyoshi – 4.7
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
LiteSpeed Cache: by LiteSpeed Technologies – 1.0.14.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.4.1
WooCommerce: by Automattic – 3.0.2
YITH WooCommerce Compare: by YITHEMES – 2.2.0
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Basel
Version: 3.1.1
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: basel/woocommerce/archive-product.php
basel/woocommerce/cart/cart.php
basel/woocommerce/cart/cross-sells.php
basel/woocommerce/cart/mini-cart.php
basel/woocommerce/checkout/form-checkout.php
basel/woocommerce/content-product.php
basel/woocommerce/content-product_cat.php
basel/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
basel/woocommerce/global/breadcrumb.php
basel/woocommerce/global/quantity-input.php
basel/woocommerce/loop/loop-end.php
basel/woocommerce/loop/loop-start.php
basel/woocommerce/loop/no-products-found.php
basel/woocommerce/loop/orderby.php
basel/woocommerce/loop/pagination.php
basel/woocommerce/loop/sale-flash.php
basel/woocommerce/myaccount/form-login.php
basel/woocommerce/product-searchform.php
basel/woocommerce/single-product/add-to-cart/variable.php
basel/woocommerce/single-product/meta.php
basel/woocommerce/single-product/product-image.php version 3.0.0 is out of date. The core version is 3.0.2
basel/woocommerce/single-product/product-thumbnails.php version 3.0.0 is out of date. The core version is 3.0.2
basel/woocommerce/single-product/related.php
basel/woocommerce/single-product/tabs/tabs.php
basel/woocommerce/single-product/title.php
basel/woocommerce/single-product/up-sells.php
basel/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
```
</details>

**Comment by mensmaximus** [comment] 2017-04-13 07:11
I can not confirm this issue. Same settings with WP 4.7.3, WOO 3.0.2 and Twenty Sixteen. Prices are displayed including tax for existing and newly created products. Might be you should disable plugins, switch to twenty seventeen/sixteen and check again.

**Comment by jkhopkins** [comment] 2017-04-13 07:15
Hi Mensmaximus, I already tried that - disabled all plugins and tried with Twenty Seventeen theme, problem still persists.

**Comment by dcthelord** [comment] 2017-04-13 07:26
I can confirm this issue. Same thing happening to me after updating to Woocommerce 3.0.2

Have tried a few themes. Same issue in all

System Report 
`
### WordPress Environment ###

Home URL: https://motofusion.in
Site URL: https://motofusion.in
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_mf_in_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

AfterShip - WooCommerce Tracking: by AfterShip – 1.6.8
All In One SEO Pack: by Michael Torbert – 2.3.12.2.1
WooCommerce CCAvenue gateway: by mRova – 1.2.4
Contact Form DB: by Michael Simpson – 2.10.28
Contact Form 7: by Takayuki Miyoshi – 4.7
EWWW Image Optimizer: by Shane Bishop – 3.2.7
Export User Data: by Q Studio – 1.3.1
Facebook Comments Plugin: by talspotim – 2.3.6
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Kirki Toolkit: by Aristeides Stathopoulos – 2.3.7
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Kadence Toolkit: by Kadence Themes – 4.3
W3 Total Cache: by Frederick Townes – 0.9.5.2
Advanced Order Export For WooCommerce: by AlgolPlus – 1.3.0
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce POS: by kilbot – 0.4.6
WooCommerce: by Automattic – 3.0.2
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

Custom Product Tabs for WooCommerce: by YIKES
Inc – 1.5.12


### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #14 - /my-account/

### Theme ###

Name: Alpha Store
Version: 1.4.0
Author URL: http://themes4wp.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`

**Comment by mensmaximus** [comment] 2017-04-13 08:02
If I 
1. change the base location of the shop to be not within that country the tax has been assigned to and
2. set the default customer location to base address and 
3. add a wildcard tax with 0% and
4. visit the site while logged with a user that has an address within that country the tax has been assigned to
than all prices get tax added which is correct.

Base Location: Ghana
Default Customer Location: Shop Base Address
Standard Tax 1: DE 19%
Standard Tax 2: * 0%
Visiting the shops while logged in with user from DE (germany)

Did you check your tax settings, base location and default customer location? I tested it with three other woocommerce installations and can not reproduce the described issue.

**Comment by jkhopkins** [comment] 2017-04-13 08:13
Yes I've checked all of those settings, nothing has been changed since updating Woocommerce.

**Comment by ZXCVLuke** [comment] 2017-04-13 08:30
I can also confirm this issue. It has affected any product with variations. I suspect that it has something to do with this; 

`*Fix - For variations, pull tax status and sold individually from the parent since there is no UI to set this at variation level.`

we are working with prices entered that include 10% tax and for any product that has variations It is applying that 10% twice. 

Changing the individual variation setting 'Tax Class' from 'Same as Parent' to 'Standard Tax Rate' fixes the problem. This is despite the parent (General settings) already being set to 'Standard Tax Rate'.

**Comment by jkhopkins** [comment] 2017-04-13 08:35
Thank you ZXCVLuke, I did some more checking and found the same as you.  The issue only affects variable products, and only those products which were in the database **before** the update.  I've entered both simple and variable products after the update and they work fine.

**Comment by mensmaximus** [comment] 2017-04-13 08:38
@ZXCVLuke confirmed. All my products and variations where set to standard tax so I could not reproduce the issue. I have changed the tax rate for one variation to 'same as parent' now and the tax gets applied twice.

**Comment by ZXCVLuke** [comment] 2017-04-13 08:41
@mensmaximus great! I really hope this means you have a solution in mind...?

My colleague here has suggested that it may have been the database update that accompanied the update to version 3.0.2 (We jumped from a 2.x.x version) that has caused the issue as reverting to 3.0.1 doesn't seem to have helped.

**Comment by ZXCVLuke** [comment] 2017-04-13 09:02
Something seems to have happened and the variations have all changed to 'Standard Tax Rate' on their own and all is well again! We're pretty confused and happy. Perhaps this was part of the database update that presumably has been slowly working away in the background.

**Comment by dcthelord** [comment] 2017-04-13 09:16
@ZXCVLuke Thanks. Atleast the reason behind is now known. But sadly, updating all variations manually could take very long.
How long did it take to automatically change variations to 'Standard tax rate' after updating the plugin?

**Comment by astridsvs** [comment] 2017-04-13 09:24
SAME ISSUE HERE

All variations show a wrong and absurd price. That's since today and is absolutely not okay.

**Comment by mikejolley** [comment] 2017-04-13 09:30
> Changing the individual variation setting 'Tax Class' from 'Same as Parent' to 'Standard Tax Rate' fixes the problem. This is despite the parent (General settings) already being set to 'Standard Tax Rate'.

What is the parent set to in this case? I'm confused why people are saying they have tax included in prices, but are not using tax rates? And if tax rates in WC are not needed, why enable the tax system?

**Comment by mensmaximus** [comment] 2017-04-13 09:33
@ZXCVLuke we will have to wait for one of the core developers to get into this. What I see in class WC_Product_Variation is if the variation tax class is set to 'parent' tha parent's tax class shall be fetched

´´´
if ( 'view' === $context && 'parent' === $value ) {
	$value = $this->parent_data['tax_class'];
}
´´´

However ´$this->parent_data['tax_class']´ is empty. 
Even if I try to get the tax class using the new CRUD classes

´´´
if ( 'view' === $context && 'parent' === $value ) {
	$parent = wc_get_product($this->get_parent_id());
	$value = $parent->get_prop( 'tax_class', $context );
}
´´´

The returned value is empty

**Comment by mensmaximus** [comment] 2017-04-13 09:42
@mikejolley feel free to check it on woo.mensmaximus.com 

I have set the variable product 'TEST VARIABLE' tax class to standard tax
I have set the variation 'GELB' tax class to same as parent
The two other variations tax class is set to variation

You can view the product at https://woo.mensmaximus.com/product/test-variable/
You can see the variation and the parent object from my above text [here](https://woo.mensmaximus.com/wp-content/uploads/debug.txt)

**Comment by diickens** [comment] 2017-04-13 10:30
@mensmaximus Just for your information. Your URL is .htaccess protected

I fixed the Tax problem quick and dirty as I overwrote the following lines in WC_Product_Variation 

`if ( 'view' === $context && 'parent' === $value ) {
$value = $this->parent_data['tax_class'];
}`

with

`if ( 'view' === $context && 'parent' === $value ) {
	$value = $this->get_prop( 'tax_class', $context );
	}`

I know it's a dirty way but i needed a quick fix and it does what I wanted.

**Comment by mensmaximus** [comment] 2017-04-13 10:32
@diickens I know it is protected. Only those supposed to work with have access.

**Comment by mensmaximus** [comment] 2017-04-13 10:48
The issue stems from $content. In case $value is 'parent' the variable $content contains '1' instead of 'view'.

**Comment by mikejolley** [comment] 2017-04-13 11:07
It seems some function send 'true' to the get_tax_class() method. Not sure why yet - may be a past version thing. Looking into it.

Context should be view.

**Comment by mensmaximus** [comment] 2017-04-13 11:38
function wc_get_price_including_tax() line 911 
$base_tax_rates = WC_Tax::get_base_tax_rates( $product->get_tax_class( true ) );

function wc_get_price_excluding_tax() line 960
$tax_rates  = WC_Tax::get_base_tax_rates( $product->get_tax_class( true ) );

**Comment by AntBentinck** [comment] 2017-04-13 11:47
Hello we are now seeing all our prices showing + tax even though our prices are inclusive of tax.

This needs to be patched and released as soon as possible.

**Comment by mensmaximus** [comment] 2017-04-13 11:49
Some occur in class WC_Cart as well from line 1141 to 1150
```
// Get base tax rates
if ( empty( $shop_tax_rates[ $product->get_tax_class( true ) ] ) ) {
	$shop_tax_rates[ $product->get_tax_class( true ) ] = WC_Tax::get_base_tax_rates( $product->get_tax_class( true ) );
}

// Get item tax rates
if ( empty( $tax_rates[ $product->get_tax_class() ] ) ) {
	$tax_rates[ $product->get_tax_class() ] = WC_Tax::get_rates( $product->get_tax_class() );
}

$base_tax_rates = $shop_tax_rates[ $product->get_tax_class( true ) ];
$item_tax_rates = $tax_rates[ $product->get_tax_class() ];
```

**Comment by mikejolley** [comment] 2017-04-13 11:54
Can you test this works as intended https://github.com/woocommerce/woocommerce/pull/14340/files?

Looks like 'parent' was not replaced with 'true' context, so the price was "inclusive" with 0 VAT, making the real VAT add on top.

**Comment by mensmaximus** [comment] 2017-04-13 12:05
The changes in includes/wc-product-functions.php are not solving the issue. If I replace `$product->get_tax_class( 'unfiltered' )` with `$product->get_tax_class()` it works.

**Comment by mensmaximus** [comment] 2017-04-13 12:11
'unfiltered' has the same effect as if $context would be 'edit'

```
public function get_tax_class( $context = 'view' ) {
	$value = $this->get_prop( 'tax_class', $context );

	// Inherit value from parent.
	if ( 'view' === $context && 'parent' === $value ) {
		$value = $this->parent_data['tax_class'];
	}
	return $value;
}
```

**Comment by mikejolley** [comment] 2017-04-13 12:22
You're not applying all of the changes @mensmaximus

**Comment by mensmaximus** [comment] 2017-04-13 12:23
:-( I downloaded the whole zip and applied it. I try it again.

**Comment by f3bruary** [comment] 2017-04-13 12:39
It seems to be working for me, but only after re-saving the product. Is this really going to be necessary to do for all variable products ?

**Comment by mensmaximus** [comment] 2017-04-13 12:59
Applied the patch this time and the variation price displays well. However the html price range still is wrong. Switched theme from twenty sixteen to seventeen as well.

![tax](https://cloud.githubusercontent.com/assets/4742179/25005565/b58cdf30-2059-11e7-8714-6d69d4fb7d24.png)

**Comment by mensmaximus** [comment] 2017-04-13 13:00
The html price seems to be cached and the variable product needed to be saved again to modify the html price.

**Comment by f3bruary** [comment] 2017-04-13 13:01
I can't reproduce that @mensmaximus Without having updated the product, the price range shows correct.

**Comment by mikejolley** [comment] 2017-04-13 13:15
It is transient cache. A save flushes it.

**Comment by mikejolley** [comment] 2017-04-13 13:16
But the variation prices should be correct after the patch. If that looks good we'll push asap.

**Comment by mensmaximus** [comment] 2017-04-13 13:17
@mikejolley yes the variation price displays correct after the patch

**Closed** 2017-04-13 15:21 UTC
Labels: Status: has-pr, Type: Bug

**Comment by Chekki** [comment] 2017-04-13 16:47
I still have the problem that on sales page the price incl. tax  and in cart the price excl. will be shown. A lot of customers asked our support for this problem. Please see and add the product to cart:

https://meinewanddeko.de/shop/schmetterlinge-wanddeko/

When do you think the update will be available for this problem? 

Thanks in advance.

Best regards

Chekki

**Comment by mikejolley** [comment] 2017-04-13 16:55
@Chekki  this change is not live yet.

**Comment by VHBP** [comment] 2017-04-13 17:25
Hi, we have indeed the same /similar issue. We are using the woocommerce subscriptions plugin and filled in the prices including taxes but now they are all shown in the store without taxes (nothing changed in the settings). And also, during the entire checkout process as well as in the shop, taxes are not stated anywhere anymore.

**Comment by VHBP** [comment] 2017-04-14 10:17
The newest update of woocommerce subscriptions and woocommerce solved the problem partly. Most correct prices are showing and taxes are showing throughout the process, though for variable subscriptions, the from ''....'' price is still showing exclusive taxes.

http://imgur.com/a/nlLDl

**Comment by mikejolley** [comment] 2017-04-14 12:13
@VHBP this is cached and will clear on save.

**Comment by moorubys** [comment] 2017-06-21 15:26
Hi there,

I'm still getting the same issue. In my case, prices are still shown in the store without taxes, but within the cart and checkout prices are shown with taxes. You can take a look at www.moorubys.com. My current woocommerce version is 3.0.8. Could you kindly confirm if this is already fixed or should I do something else in my environment?

I'm not a developer, so any help is more than appreciated.

Thanks!

**Comment by vijayvp710** [comment] 2017-06-29 11:19
Hello,
You need to select base location under general setting  And  Select base location country depend on your site. That's it.

**Comment by moorubys** [comment] 2017-06-29 13:37
@vijayvp710 thanks a lot for your reply! I really appreciate it. 

Base location is configured properly (Spain - Madrid). Taxes are calculated properly in the cart, but prices still appearing without taxes in the store, which is driving me crazy since March Woocommerce update :-(

Any other hint?

**Comment by webwitches** [comment] 2017-08-11 12:30
@moorubys I have exactly the same issue - how did you resolve it please?

**Comment by moorubys** [comment] 2017-08-14 16:26
Hi @webwitches ! Sorry for my late reply. I deactivated all plugins within Wordpress and, after I disabled all plugins problem dissappeared. I started to enable them one by one and.. you know what? I realized that when I enabled "WooCommerce Currency Switcher" problem appeared again, so this was the root cause of the issue. Check your installed plugins because maybe you are in the same situation and a specific plugin is causing your problem. Hope this helps!!

**Comment by sonicunix** [comment] 2017-09-14 19:16
Hi there,

I'm still getting the same issue. In my case, prices are still shown in the store without taxes, but within the cart and checkout prices are shown with taxes.  My current woocommerce version is 3.1.2. Could you kindly confirm if this is already fixed or should I do something else in my environment?

Thanks!

**Comment by damircalusic** [comment] 2017-10-12 23:46
The issue has returned in WooCommerce 3.2.0. Needs a fix as sson as possible!

**Comment by gorossil** [comment] 2017-10-13 09:57
I can also confirm that this problem exist, just had a very angry webshopowner on the phone :-).
All variationproducts which points to "Same as parent" Taxrate starts calculating tax even though the settings are "all prices are incl. tax". PLEASE FIX !!

**Comment by moorubys** [comment] 2017-10-13 10:12
Yes... same problem here 👎 . We need it fixed ASAP !!

**Comment by lvl99** [comment] 2017-11-01 10:39
I have this issue. It might be because I'm running WPML's WooCommerce Multilingual with multicurrency enabled -- just disabled it and seems the issue still persists.

I've found when I do `$wc_product->get_tax_class()` on a variable product that it is an empty string (should be "standard", I think?). When I get the variable product's first variation and do the same, the tax class is "parent". Since the parent's tax class is empty, then I get the product excluding tax (all prices are including tax and viewing user is within a taxable zone).

**Comment by lvl99** [comment] 2017-11-01 11:42
Well, seems still some hijinx afoot.

I'm attempting to write a filter that modifies the suffix depending on if the viewing user is in a taxable zone (i.e. saying if the price is with or without tax):

```php
    /**
     * Show "incl./excl. VAT" label for taxable prices
     *
     * @param string $html
     * @param \WC_Product $wc_product
     * @param string $price
     * @param number $qty
     * @return string
     */
    function add_tax_labels_to_price ( $html, $wc_product, $price, $qty )
    {
      if ( wc_tax_enabled() && 'taxable' === $wc_product->get_tax_status() )
      {
        if ( '' === $price ) {
          $price = $wc_product->get_price();
        }
        $price = floatval( $price );
        $price_incl_tax = wc_get_price_including_tax( $wc_product, array( 'qty' => $qty, 'price' => $price ) );
        $price_excl_tax = wc_get_price_excluding_tax( $wc_product, array( 'qty' => $qty, 'price' => $price ) );

        if ( $price === $price_incl_tax )
        {
          $suffix = _x( '(incl. VAT)', 'Price suffix: including VAT', 'mywebsite' );
        }
        else
        {
          $suffix = _x( '(excl. VAT)', 'Price suffix: excluding VAT', 'mywebsite' );
        }

        $html = ' <small class="price-suffix">' . wp_kses_post( $suffix ) . '</small>';
      }

      return $html;
    }
    add_filter( 'woocommerce_get_price_suffix', __NAMESPACE__ . '\\add_tax_labels_to_price', PHP_INT_MAX, 4 );
```

I'm finding that both the prices with/without tax are the same (this is after clearing the transients):
![image](https://user-images.githubusercontent.com/238480/32272192-44fbfe48-befd-11e7-94fa-f13c51601d64.png)

I have two standard tax rates set: 1 for FR (to call it TVA) and 1 for EU (to call it VAT), both are 20%

The product should have value of 400 excl. VAT and 500 incl. VAT.

I've disabled plugins and still get this issue.

**Comment by mikejolley** [comment] 2017-11-01 12:17
Default customer location affects this because the customer may not have an address/tax location yet. In those cases, the values will be the same.

I'm going to go ahead and close this issue out/disable comments. The original logged issue was from 3.0 release and has been resolved.
