### ISSUE TITLE
Shop page showing large thumbnails with no images and wrong categories

### ISSUE THREAD

**Issue by JWDSN** [woocommerce/woocommerce#18801] opened 2018-02-04 07:02 UTC
![woocomm_bug](https://user-images.githubusercontent.com/36123811/35775040-d15207e8-09d0-11e8-85f6-b22ab4312804.png)

My store page is not working since the latest update - large no image thumbnails and categories are incorrect. This also happens on category pages when using links to navigate to specific product categories. Everything else seems to be working OK.

`
### WordPress Environment ###

Home URL: https://jwdsn.net/assets
Site URL: https://jwdsn.net/assets
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wpzv_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.17MB
Database Data Size: 1.72MB
Database Index Size: 0.45MB
wpzv_woocommerce_sessions: Data: 0.11MB + Index: 0.01MB
wpzv_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB
wpzv_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.02MB
wpzv_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wpzv_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpzv_commentmeta: Data: 0.00MB + Index: 0.00MB
wpzv_comments: Data: 0.00MB + Index: 0.01MB
wpzv_links: Data: 0.00MB + Index: 0.00MB
wpzv_loginizer_logs: Data: 0.00MB + Index: 0.01MB
wpzv_options: Data: 0.93MB + Index: 0.13MB
wpzv_postmeta: Data: 0.35MB + Index: 0.12MB
wpzv_posts: Data: 0.24MB + Index: 0.04MB
wpzv_termmeta: Data: 0.00MB + Index: 0.01MB
wpzv_terms: Data: 0.00MB + Index: 0.01MB
wpzv_term_relationships: Data: 0.00MB + Index: 0.01MB
wpzv_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wpzv_usermeta: Data: 0.04MB + Index: 0.03MB
wpzv_users: Data: 0.00MB + Index: 0.01MB
wpzv_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpzv_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpzv_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wpzv_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 114
custom_css: 1
customize_changeset: 48
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 11
page: 11
post: 2
product: 13
revision: 34
sa_slider: 1
shop_coupon: 1
shop_order: 27
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Akismet Anti-Spam: by Automattic – 4.0.2
Contact Form 7: by Takayuki Miyoshi – 5.0
Jetpack by WordPress.com: by Automattic – 5.7.1
Loginizer: by Raj Kothari – 1.3.8
MailChimp for WordPress: by ibericode – 4.1.14
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.6.0 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Slide Anything - Responsive Content / HTML Slider and Carousel: by Simon Edge – 2.1.2
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.1
WooCommerce Max Quantity: by Isabel Castillo – 1.5.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.11.0
WooCommerce: by Automattic – 3.3.0
YITH WooCommerce Wishlist: by YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #28 - /shop/
Cart: #29 - /cart/
Checkout: #30 - /checkout/
My account: #31 - /my-account/
Terms and conditions: #69 - /eula/

### Theme ###

Name: SShop
Version: 1.1.0
Author URL: http://sshopwp.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: sshop/woocommerce/content-product.php
sshop/woocommerce/loop/add-to-cart.php
sshop/woocommerce/loop/loop-end.php
sshop/woocommerce/loop/loop-start.php
sshop/woocommerce/loop/pagination.php
sshop/woocommerce/single-product/tabs/additional-information.php
sshop/woocommerce/single-product/tabs/description.php

`

**Comment by GlennMartin1** [comment] 2018-02-04 12:29
This is a known issue caused by out-of-date themes.

Be sure your theme is up-to-date. 

WC 3.3.1 will be released the week February 5, and will better accommodate out-of-date themes. 

See: https://woocommerce.wordpress.com/2018/02/01/woocommerce-3-3-1-status-update/

**Comment by WPprodigy** [comment] 2018-02-04 20:11
@JWDSN - if you can, please do test with version 3.3.1 and report back if this helps solve the issue.

**Closed** 2018-02-04 20:11 UTC
Labels: Invalid / Duplicate

**Comment by JWDSN** [comment] 2018-02-04 23:56
3.3.1 update fixed the issue.

**Comment by WPprodigy** [comment] 2018-02-05 05:13
Thanks for confirming and testing :)
