### ISSUE TITLE
errors on the product page 

### ISSUE THREAD

**Issue by samiakazi** [woocommerce/woocommerce#26388] opened 2020-05-05 20:58 UTC
**Describe the bug**
when i click on the product on the shop page, it takes me to a more detailed information about the product, but the page is full of bugs. 

**To Reproduce**
1. Go to 'https://www.arabianchild.org/shop/
2. Click on the training course
3. it takes you to this page 
https://www.arabianchild.org/product/%d8%a5%d8%b9%d8%af%d8%a7%d8%af-%d9%85%d8%b9%d9%84%d9%85%d8%a9-%d8%b7%d9%81%d9%88%d9%84%d8%a9-%d9%85%d8%a8%d9%83%d8%b1%d8%a9-certificate-in-preparing-early-childhood-teachers-and-caregivers/

**Comment by juliaamosova** [comment] 2020-05-06 20:35
Hi @samiakazi,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-05-06 20:35 UTC
