### ISSUE TITLE
woocommerce_order_status_cancelled

### ISSUE THREAD

**Issue by peretc001** [woocommerce/woocommerce#28212] opened 2020-11-07 09:31 UTC
Woocommerce automatically cancels orders from the pending payment status to canceled after a specified period of time

If I manually change the status, it works, but it doesn't work when WC automaticly canceling order. 

How to subscribe to this event?

My functions.php

```
add_action( 'woocommerce_order_edit_status', 'switips_update_order' );
add_action( 'woocommerce_order_status_changed', 'switips_update_order' );
add_action( 'woocommerce_order_status_cancelled', 'switips_update_order' );

function switips_update_order( $order_id )
{
    $order = new WC_Order($order_id);
    setcookie( 'order', (string)$order->get_status(), time() + 3600 * 24 * 30, "/");
};

```

**Comment by peretc001** [comment] 2020-11-07 12:09
I find this code for cancell order
```
function wc_cancel_unpaid_orders() {
  ...

  wp_clear_scheduled_hook( 'woocommerce_cancel_unpaid_orders' );
  wp_schedule_single_event( time() + ( absint( $held_duration ) * 60 ), 'woocommerce_cancel_unpaid_orders' );
}
add_action( 'woocommerce_cancel_unpaid_orders', 'wc_cancel_unpaid_orders' );
```

And i`m try to do this:
```
add_action( 'wc_cancel_unpaid_orders', 'switips_update_order_test', 10, 1 );
function switips_update_order_test( $order_id )
{
    setcookie('order', 'cancelled', time() + 3600 * 24 * 30, "/");
}

```

But its not work

**Comment by juliaamosova** [comment] 2020-11-13 19:49
Hi @peretc001,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-11-13 19:49 UTC
