### ISSUE TITLE
Coupon usage limit has been reached

### ISSUE THREAD

**Issue by Wayne-Ehr-Surprenant** [woocommerce/woocommerce#23836] opened 2019-05-28 19:57 UTC
**Describe the bug**
Create an order manually from the back-end. Add-in some product then click on "Apply Coupon". Enter coupon code and the error happen. This issue happens with coupon that I used for 5 orders in the past, and happens also with newly created coupon.

Please note this bug happens only since the update from WC 3.6.3 to WC 3.6.4

**To Reproduce**
1. Create an order manually from the back-end
2. Add-in some product
3. click on "Apply Coupon"
4. Enter coupon code
5. Click OK

**Expected behavior**
Coupon is applied to the order

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://ksldress.com
Site address (URL): https://ksldress.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.3.5
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 331.85MB
Database Data Size: 209.94MB
Database Index Size: 121.91MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB
wp_woocommerce_order_itemmeta: Data: 9.52MB + Index: 10.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 2.52MB + Index: 3.02MB
wp_comments: Data: 8.52MB + Index: 9.09MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.06MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 4.52MB + Index: 4.97MB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB
wp_icl_string_pages: Data: 0.38MB + Index: 0.27MB
wp_icl_string_positions: Data: 0.11MB + Index: 0.05MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 4.52MB + Index: 2.52MB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 5.52MB + Index: 1.52MB
wp_icl_translate_job: Data: 0.09MB + Index: 0.05MB
wp_icl_translations: Data: 1.52MB + Index: 4.00MB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Data: 9.52MB + Index: 0.13MB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletters: Data: 1.52MB + Index: 0.00MB
wp_mailpoet_newsletter_links: Data: 0.08MB + Index: 0.08MB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_templates: Data: 14.52MB + Index: 0.00MB
wp_mailpoet_premium_newsletter_extra_data: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB
wp_mailpoet_scheduled_task_subscribers: Data: 4.52MB + Index: 1.52MB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_sending_queues: Data: 2.52MB + Index: 0.03MB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_statistics_clicks: Data: 0.48MB + Index: 0.66MB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_statistics_newsletters: Data: 2.52MB + Index: 3.03MB
wp_mailpoet_statistics_opens: Data: 1.52MB + Index: 1.38MB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB
wp_mailpoet_subscribers: Data: 1.52MB + Index: 0.95MB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB
wp_mailpoet_subscriber_segment: Data: 1.52MB + Index: 0.83MB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 9.06MB + Index: 2.34MB
wp_postmeta: Data: 61.59MB + Index: 39.13MB
wp_posts: Data: 10.52MB + Index: 7.77MB
wp_termmeta: Data: 0.19MB + Index: 0.23MB
wp_terms: Data: 0.09MB + Index: 0.13MB
wp_term_relationships: Data: 1.36MB + Index: 0.41MB
wp_term_taxonomy: Data: 0.11MB + Index: 0.11MB
wp_usermeta: Data: 11.52MB + Index: 11.03MB
wp_users: Data: 1.52MB + Index: 0.69MB
wp_wclsi_items: Data: 0.02MB + Index: 0.17MB
wp_wclsi_item_attribute_sets: Data: 0.02MB + Index: 0.05MB
wp_wclsi_item_categories: Data: 0.02MB + Index: 0.06MB
wp_wclsi_item_e_commerce: Data: 0.02MB + Index: 0.03MB
wp_wclsi_item_images: Data: 0.02MB + Index: 0.09MB
wp_wclsi_item_prices: Data: 0.02MB + Index: 0.02MB
wp_wclsi_item_shops: Data: 0.02MB + Index: 0.08MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Data: 0.42MB + Index: 0.27MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 1.14MB
wp_wc_order_stats: Data: 1.52MB + Index: 0.50MB
wp_wc_order_tax_lookup: Data: 0.38MB + Index: 0.30MB
wp_wc_point_of_sale_sale_reports: Data: 0.00MB + Index: 0.00MB
wp_wc_poin_of_sale_tabs: Data: 0.02MB + Index: 0.00MB
wp_wc_poin_of_sale_tabs_meta: Data: 0.02MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 1.34MB + Index: 1.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB
wp_wp_wc_poin_of_sale_cache: Data: 0.02MB + Index: 0.00MB
wp_wsal_metadata: Data: 10.52MB + Index: 7.52MB
wp_wsal_occurrences: Data: 1.52MB + Index: 1.52MB
wp_wsal_options: Data: 0.02MB + Index: 0.00MB
wp_yith_wcbk_booking_notes: Data: 0.02MB + Index: 0.00MB
wp_yith_wcbk_external_bookings: Data: 0.02MB + Index: 0.00MB
wp_yith_wcbk_logs: Data: 0.02MB + Index: 0.00MB
wp_yith_wcch_emails: Data: 0.02MB + Index: 0.00MB
wp_yith_wcch_sessions: Data: 12.52MB + Index: 0.00MB
wp_yith_wccl_meta: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yith_ywrac_email_log: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.23MB + Index: 0.00MB
wp_ywcars_messagemeta: Data: 0.02MB + Index: 0.00MB
wp_ywcars_messages: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

attachment: 6600
event: 12
gift_card: 214
mailpoet_page: 1
nav_menu_item: 89
oembed_cache: 40
page: 44
personne: 1
pos_temp_register_or: 1
post: 35
product: 880
product_variation: 4788
revision: 178
scheduled-action: 4120
shop_coupon: 970
shop_order: 9678
shop_order_refund: 228
yith_price_rule: 1
yith_refund_request: 95
yith-wcbm-badge: 8
yith-wccos-ostatus: 31
yith-wcgpf-feed: 1
yith-wcpsc-wc-chart: 1
ywar_reviews: 30

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

ManageWP - Worker: by GoDaddy – 4.8.0
Gravity Forms: by rocketgenius – 2.4.6
WPML Multilingual CMS: by OnTheGoSystems – 4.2.6
AJAX Thumbnail Rebuild: by junkcoder
ristoniinemets – 1.13

Cart2Cart: Password Migration: by MagneticOne – 1.1
Classic Editor: by WordPress Contributors – 1.5
Support EspritsLibres.design: by Charles St-Pierre
en collaboration avec Esprits Libres Design – 1.1.10

GA Google Analytics: by Jeff Starr – 20190501
Google XML Sitemaps: by Arne Brachhold – 4.1.0
Gravity Forms Multilingual: by OnTheGoSystems – 1.5.0
Imagify: by WP Media – 1.9.2
Jetpack by WordPress.com: by Automattic – 7.3.1
Loco Translate: by Tim Whitlock – 2.2.2
Mailgun: by Mailgun – 1.7.1
MailPoet 3 Premium (New): by MailPoet – 3.0.53
MailPoet 3 (New): by MailPoet – 3.27.0
Multiple Roles: by Florian TIAR – 1.2.0
Customization KSL: by Esprits Libres Design – 1.0.0
User Role Editor: by Vladimir Garagulya – 4.51
User Switching: by John Blackbourn & contributors – 1.5.0
Preview E-mails for WooCommerce: by Digamber Pradhan – 1.5.1
WooCommerce Admin: by WooCommerce – 0.12.0
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.6.3
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce Multilingual: by OnTheGoSystems – 4.6.3
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.3 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.20.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.28
WooCommerce: by Automattic – 3.6.4
Yoast SEO: by Team Yoast – 11.3 – Not tested with the active version of WooCommerce
WP Security Audit Log: by WP White Security – 3.4.1
WPML Media: by OnTheGoSystems – 2.5.2
WPML String Translation: by OnTheGoSystems – 2.10.4
WPML Translation Management: by OnTheGoSystems – 2.8.5
YITH Advanced Refund System for WooCommerce Premium: by YITH – 1.1.4
YITH Custom ThankYou Page for Woocommerce Premium: by YITH – 1.1.5
YITH Google Product Feed for WooCommerce Premium: by YITH – 1.1.5
YITH Infinite Scrolling Premium: by YITH – 1.1.9
YITH WooCommerce Badge Management Premium: by YITH – 1.3.21
YITH WooCommerce Bulk Product Editing Premium: by YITH – 1.2.14
YITH WooCommerce Color and Label Variations Premium: by YITH – 1.8.9
YITH WooCommerce Custom Order Status Premium: by YITH – 1.1.12
YITH WooCommerce Customer History Premium: by YITH – 1.1.11
YITH WooCommerce Gift Cards Premium: by YITH – 2.2.5
YITH WooCommerce PDF Invoice and Shipping List Premium: by YITH – 2.0.0
YITH WooCommerce Product Bundles Premium: by YITH – 1.2.20
YITH WooCommerce Wishlist Premium: by YITH – 2.2.9

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.2
WP Rocket: by WP Media – 3.3.3.1
YITH WooCommerce Ajax Product Filter Premium: by YITH – 3.6.2 – Not tested with the active version of WooCommerce
YITH WooCommerce Role Based Prices Premium: by YITH – 1.1.10 – Not tested with the active version of WooCommerce

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: by GoDaddy –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-fr)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-fr)
featured (featured)
featured (featured-fr)
outofstock (outofstock)
outofstock (outofstock-fr)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-fr)
rated-4 (rated-4)
rated-4 (rated-4-fr)
rated-5 (rated-5)
rated-5 (rated-5-fr)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My account: #12 - /my-space/
Terms and conditions: #18112 - /terms-and-conditions/

### Theme ###

Name: KSL Life
Version: 1.0.0
Author URL: http://www.espritslibres.design
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: ksl/woocommerce/archive-product.php
ksl/woocommerce/content-single-product.php version 3.4.0 is out of date. The core version is 3.6.0
ksl/woocommerce/emails/customer-new-account.php version 1.6.4 is out of date. The core version is 3.5.2
ksl/woocommerce/loop/loop-end.php
ksl/woocommerce/loop/loop-start.php
ksl/woocommerce/single-product/up-sells.php
ksl/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Customer/Order CSV Export ###

Order Export Format: default_one_row_per_item
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

### Action Scheduler ###

Complete: 3,971
Oldest: 2019-05-28 08:35:19 -0400
Newest: 2019-05-28 15:54:28 -0400

Pending: 7
Oldest: 2019-05-28 15:54:33 -0400
Newest: 2019-05-28 16:40:28 -0400

Canceled: 134
Oldest: 2019-05-28 09:21:48 -0400
Newest: 2019-05-28 09:24:31 -0400

In-progress: 0
Oldest: –
Newest: –

Failed: 8
Oldest: 2019-05-28 09:32:31 -0400
Newest: 2019-05-28 14:14:23 -0400

`
</details>

**Comment by claudiosanches** [comment] 2019-05-29 00:00
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried the steps you provided and it appeared to work correctly.

Note that since 3.6.4 we check for usage limit, see https://github.com/woocommerce/woocommerce/pull/23775
So sounds like that the coupon you are using already hit the usage limit. Try create a new coupon with a new usage limit, or maybe increase this limit.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Comment by Wayne-Ehr-Surprenant** [comment] 2019-05-29 02:01
Hey there,

Figured out it's happening only when the order is assigned to a guest customer.
Coupon is not restricted by any usage rule such as price, category. 

Same order, one with guest, one assigned to a user. The one as guest says limit reached, and the other works just fine!

**Comment by keninbassart** [comment] 2019-05-29 14:54
re-opened in error

**Comment by ajayghaghretiya** [comment] 2019-05-31 07:33
Fixed this issue #23851.

**Comment by claudiosanches** [comment] 2019-06-07 14:10
Fixed by https://github.com/woocommerce/woocommerce/pull/23851

**Closed by claudiosanches** 2019-06-07 14:10 UTC
Labels: bug, has pull request
