### ISSUE TITLE
Linking WooCommerce Endpoint to a Page

### ISSUE THREAD

**Issue by CordialGit** [woocommerce/woocommerce#27837] opened 2020-10-02 04:43 UTC
Please, I copied a Code from https://github.com/woocommerce/woocommerce/wiki/Customising-account-page-tabs

And when I customized it, the code actually added an endpoint to my WooCommerce Account Page, and the Name of the endpoint is as I wanted. I wanted the name of the endpoint to be called "**ADD PRODUCT**" and it is so.

The challenge I'm facing now is that I want the endpoint to open a Page on my site, when it is clicked. The Page is https://styleandpatterns.com.ng/add-product

How do I do that?

**Comment by tammullen** [comment] 2020-10-02 21:40
Hi @CordialGit 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-10-02 21:40 UTC
Labels: support request
