### ISSUE TITLE
How randomize products display on a page using Divi theme and Woocommerce

### ISSUE THREAD

**Issue by erikamercier** [woocommerce/woocommerce#28804] opened 2021-01-12 23:23 UTC
I am doing a shop page using Divi theme and I am trying to display randomly products from a certain category.

The problem I have is that the theme does not have options to randomize the way the articles are displaying on the shop page.

I also tried a woocommerce shortcode:

[products limit="30" columns="3" category="cardigans-sweaters" cat_operator="AND" orderby="rand" order="rand"]

It worked well on desktop, but the problem is that the visual I get on mobile is not the one I want (it is one column instead of two, plus it kinda lost the CSS I did myself).

So yeah if someone knows a PHP code, or any code I could use to randomize, I would be really happy!

**Comment by tammullen** [comment] 2021-01-14 22:42
Hi @erikamercier 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-01-14 22:42 UTC
