### ISSUE TITLE
Get_html_price displays prices incorrectly

### ISSUE THREAD

**Issue by marekka** [woocommerce/woocommerce#20860] opened 2018-07-20 11:00 UTC
There is an issue on Woocommerce when Calculate tax based on Customer Shipping address is enabled.

It's bid difficult to explain what exactly is making this, so I recorded a video:

https://drive.google.com/file/d/1lgzniKqUaGdgWWQbcYz0ucMj0AnKRjZB/view

**Comment by rodrigoprimo** [comment] 2018-07-20 14:15
Hi,

I was not able to reproduce the problem you described in the video. Documenting here the steps that I took in case I missed something:

- Make sure "Calculate tax based on" is set to "Customer shipping address" (default value) and change "Display prices in the shop" and "Display prices during cart and checkout" to "Including tax".
- Create a new tax class called "UK Standard Rate (20%)" and add a new row with the following configuration:

![screenshot from 2018-07-20 11-00-04](https://user-images.githubusercontent.com/77215/43006460-2893d398-8c0c-11e8-9170-a1b71649ec63.png)

- To test the new tax class, I changed the tax class of the "V-Neck T-Shirt" variable product (one of the products in the [WooCommece sample data](https://docs.woocommerce.com/document/importing-woocommerce-sample-data/)) to "UK Standard Rate (20%)".

In my tests, the price is always displayed with tax included in the shop, cart, and checkout pages if the billing country is set to UK and without tax included if the billing country is set to something else (I used Brazil). I got the same behavior if I set the tax class of each individual variation to "UK Standard Rate (20%)" or "Same as parent".

Would you be able to try to reproduce this on a clean WC core install?

**Comment by marekka** [comment] 2018-07-20 14:31
Thanks for this, however, you will have to test variation product, not a standard one. The standard products display prices correctly. Also, in the example I'm showing, variations having different prices - that also may be related.

**Comment by marekka** [comment] 2018-07-20 14:54
https://drive.google.com/file/d/1CjSmtee8mwcF_lKBh87V9ALWTMhb2a4Y/view

**Comment by kloon** [comment] 2018-07-23 07:56
@marekka I see you did not fill out the template when you opened the issue, the questions and info we request there are vital in troubleshooting issues.

As Rodrigo I am also unable to replicate this. Have you tested with all plugins except WooCommerce disabled? Do you have any custom code running on your theme that is altering the price? Have you tested by switching themes to a default one temporarily and testing?

Also please attach your System Status Report.

**Comment by rodrigoprimo** [comment] 2018-07-23 17:59
> Thanks for this, however, you will have to test variation product, not a standard one.

As I mentioned in my last comment, I tested using a variable product, not a standard one.

**Comment by marekka** [comment] 2018-07-24 08:54
@kloon Yes, I have only the default theme enabled and WooCommerce only.

STATUS:
`
### WordPress Environment ###

Home URL: https://www.wbcme.co.uk
Site URL: https://www.wbcme.co.uk
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.8
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.34

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 146.31MB
Database Data Size: 100.47MB
Database Index Size: 45.84MB
wp_woocommerce_sessions: Data: 1.52MB + Index: 0.05MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.14MB + Index: 0.06MB
wp_woocommerce_order_itemmeta: Data: 0.47MB + Index: 0.53MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_comments: Data: 0.14MB + Index: 0.09MB
wpstg0_datalist: Data: 0.00MB + Index: 0.00MB
wpstg0_lecm_import: Data: 0.09MB + Index: 0.09MB
wpstg0_lecm_recent: Data: 0.02MB + Index: 0.00MB
wpstg0_lecm_update: Data: 0.02MB + Index: 0.02MB
wpstg0_lecm_user: Data: 0.02MB + Index: 0.00MB
wpstg0_links: Data: 0.02MB + Index: 0.02MB
wpstg0_options: Data: 0.41MB + Index: 0.09MB
wpstg0_postmeta: Data: 6.52MB + Index: 4.03MB
wpstg0_posts: Data: 3.52MB + Index: 0.58MB
wpstg0_redirection_404: Data: 0.02MB + Index: 0.06MB
wpstg0_redirection_groups: Data: 0.02MB + Index: 0.03MB
wpstg0_redirection_items: Data: 0.02MB + Index: 0.08MB
wpstg0_redirection_logs: Data: 0.02MB + Index: 0.08MB
wpstg0_staging_commentmeta: Data: 0.00MB + Index: 0.00MB
wpstg0_staging_comments: Data: 0.00MB + Index: 0.01MB
wpstg0_staging_links: Data: 0.00MB + Index: 0.00MB
wpstg0_staging_options: Data: 1.52MB + Index: 0.16MB
wpstg0_staging_postmeta: Data: 0.00MB + Index: 0.01MB
wpstg0_staging_posts: Data: 0.00MB + Index: 0.01MB
wpstg0_staging_termmeta: Data: 0.00MB + Index: 0.00MB
wpstg0_staging_terms: Data: 0.00MB + Index: 0.01MB
wpstg0_staging_term_relationships: Data: 0.00MB + Index: 0.00MB
wpstg0_staging_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpstg0_staging_usermeta: Data: 0.06MB + Index: 0.03MB
wpstg0_staging_users: Data: 0.02MB + Index: 0.05MB
wpstg0_staging_wfConfig: Data: 0.42MB + Index: 0.00MB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB
wpstg0_term_relationships: Data: 0.06MB + Index: 0.05MB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpstg0_usermeta: Data: 1.52MB + Index: 1.86MB
wpstg0_users: Data: 0.14MB + Index: 0.14MB
wpstg0_vp_id: Data: 5.52MB + Index: 5.03MB
wpstg0_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg0_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wpstg0_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wpstg0_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wpstg0_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wpstg0_wfConfig: Data: 0.44MB + Index: 0.00MB
wpstg0_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wpstg0_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wpstg0_wfFileMods: Data: 2.52MB + Index: 0.00MB
wpstg0_wfHits: Data: 0.23MB + Index: 0.09MB
wpstg0_wfHoover: Data: 0.00MB + Index: 0.00MB
wpstg0_wfIssues: Data: 0.06MB + Index: 0.06MB
wpstg0_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wpstg0_wfLeechers: Data: 0.02MB + Index: 0.00MB
wpstg0_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB
wpstg0_wfLocs: Data: 0.02MB + Index: 0.00MB
wpstg0_wfLogins: Data: 0.06MB + Index: 0.03MB
wpstg0_wfNet404s: Data: 0.00MB + Index: 0.00MB
wpstg0_wfNotifications: Data: 0.02MB + Index: 0.00MB
wpstg0_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wpstg0_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wpstg0_wfScanners: Data: 0.02MB + Index: 0.00MB
wpstg0_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wpstg0_wfStatus: Data: 0.13MB + Index: 0.09MB
wpstg0_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_order_itemmeta: Data: 0.45MB + Index: 0.50MB
wpstg0_woocommerce_order_items: Data: 0.13MB + Index: 0.05MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_sessions: Data: 0.30MB + Index: 0.02MB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpstg0_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB
wpstg1_commentmeta: Data: 0.17MB + Index: 0.03MB
wpstg1_comments: Data: 0.25MB + Index: 0.09MB
wpstg1_datalist: Data: 0.00MB + Index: 0.00MB
wpstg1_lecm_import: Data: 0.09MB + Index: 0.09MB
wpstg1_lecm_recent: Data: 0.02MB + Index: 0.00MB
wpstg1_lecm_update: Data: 0.02MB + Index: 0.02MB
wpstg1_lecm_user: Data: 0.02MB + Index: 0.00MB
wpstg1_links: Data: 0.02MB + Index: 0.02MB
wpstg1_options: Data: 1.52MB + Index: 0.19MB
wpstg1_postmeta: Data: 6.52MB + Index: 5.03MB
wpstg1_posts: Data: 4.52MB + Index: 0.63MB
wpstg1_redirection_404: Data: 0.02MB + Index: 0.06MB
wpstg1_redirection_groups: Data: 0.02MB + Index: 0.03MB
wpstg1_redirection_items: Data: 0.02MB + Index: 0.08MB
wpstg1_redirection_logs: Data: 0.02MB + Index: 0.08MB
wpstg1_staging_commentmeta: Data: 0.00MB + Index: 0.00MB
wpstg1_staging_comments: Data: 0.00MB + Index: 0.01MB
wpstg1_staging_links: Data: 0.00MB + Index: 0.00MB
wpstg1_staging_options: Data: 1.52MB + Index: 0.16MB
wpstg1_staging_postmeta: Data: 0.00MB + Index: 0.01MB
wpstg1_staging_posts: Data: 0.00MB + Index: 0.01MB
wpstg1_staging_termmeta: Data: 0.00MB + Index: 0.00MB
wpstg1_staging_terms: Data: 0.00MB + Index: 0.01MB
wpstg1_staging_term_relationships: Data: 0.00MB + Index: 0.00MB
wpstg1_staging_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpstg1_staging_usermeta: Data: 0.06MB + Index: 0.03MB
wpstg1_staging_users: Data: 0.02MB + Index: 0.05MB
wpstg1_staging_wfConfig: Data: 0.42MB + Index: 0.00MB
wpstg1_termmeta: Data: 0.05MB + Index: 0.03MB
wpstg1_terms: Data: 0.02MB + Index: 0.03MB
wpstg1_term_relationships: Data: 0.06MB + Index: 0.05MB
wpstg1_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wpstg1_usermeta: Data: 1.52MB + Index: 1.86MB
wpstg1_users: Data: 0.14MB + Index: 0.14MB
wpstg1_vp_id: Data: 5.52MB + Index: 6.03MB
wpstg1_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpstg1_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg1_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg1_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wpstg1_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wpstg1_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wpstg1_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wpstg1_wfConfig: Data: 0.42MB + Index: 0.00MB
wpstg1_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wpstg1_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wpstg1_wfFileMods: Data: 4.52MB + Index: 0.00MB
wpstg1_wfHits: Data: 1.52MB + Index: 0.42MB
wpstg1_wfHoover: Data: 0.00MB + Index: 0.00MB
wpstg1_wfIssues: Data: 0.02MB + Index: 0.06MB
wpstg1_wfKnownFileList: Data: 2.52MB + Index: 0.00MB
wpstg1_wfLeechers: Data: 0.09MB + Index: 0.00MB
wpstg1_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB
wpstg1_wfLocs: Data: 0.02MB + Index: 0.00MB
wpstg1_wfLogins: Data: 0.06MB + Index: 0.03MB
wpstg1_wfNet404s: Data: 0.00MB + Index: 0.00MB
wpstg1_wfNotifications: Data: 0.02MB + Index: 0.00MB
wpstg1_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wpstg1_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wpstg1_wfScanners: Data: 0.05MB + Index: 0.00MB
wpstg1_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wpstg1_wfStatus: Data: 0.14MB + Index: 0.09MB
wpstg1_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg1_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpstg1_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_order_itemmeta: Data: 0.47MB + Index: 0.52MB
wpstg1_woocommerce_order_items: Data: 0.14MB + Index: 0.06MB
wpstg1_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg1_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_sessions: Data: 2.52MB + Index: 0.05MB
wpstg1_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg1_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg1_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg1_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg1_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpstg1_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpstg1_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB
wp_commentmeta: Data: 0.14MB + Index: 0.03MB
wp_comments: Data: 0.25MB + Index: 0.09MB
wp_datalist: Data: 0.00MB + Index: 0.00MB
wp_lecm_import: Data: 0.09MB + Index: 0.09MB
wp_lecm_recent: Data: 0.02MB + Index: 0.00MB
wp_lecm_update: Data: 0.02MB + Index: 0.02MB
wp_lecm_user: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.22MB + Index: 0.13MB
wp_postmeta: Data: 6.52MB + Index: 5.03MB
wp_posts: Data: 4.52MB + Index: 0.64MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_staging_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_staging_comments: Data: 0.00MB + Index: 0.01MB
wp_staging_links: Data: 0.00MB + Index: 0.00MB
wp_staging_options: Data: 1.52MB + Index: 0.16MB
wp_staging_postmeta: Data: 0.00MB + Index: 0.01MB
wp_staging_posts: Data: 0.00MB + Index: 0.01MB
wp_staging_termmeta: Data: 0.00MB + Index: 0.00MB
wp_staging_terms: Data: 0.00MB + Index: 0.01MB
wp_staging_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_staging_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_staging_usermeta: Data: 0.06MB + Index: 0.03MB
wp_staging_users: Data: 0.02MB + Index: 0.05MB
wp_staging_wfConfig: Data: 0.42MB + Index: 0.00MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_usermeta: Data: 1.52MB + Index: 0.86MB
wp_users: Data: 0.14MB + Index: 0.14MB
wp_vp_id: Data: 5.52MB + Index: 6.03MB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfConfig: Data: 0.44MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 6.52MB + Index: 0.00MB
wp_wfHits: Data: 1.38MB + Index: 0.19MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 3.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.06MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.06MB + Index: 0.03MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.14MB + Index: 0.09MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1146
flamingo_contact: 74
flamingo_inbound: 150
nav_menu_item: 64
page: 22
portfolio: 12
post: 24
product: 150
product_variation: 469
revision: 415
shop_order: 478
shop_order_refund: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #2320 - /terms-and-conditions-of-use/

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by rodrigoprimo** [comment] 2018-10-19 14:43
Closing as we were not able to reproduce this and no one else reported this problem, so it is probably not a WooCommerce core issue. If you are still experiencing this issue, are you able to reproduce it on another WooCommerce install?

**Closed by rodrigoprimo** 2018-10-19 14:43 UTC
Labels: status: needs feedback
