### ISSUE TITLE
Woocomerce Button "Buy" and login accounts don't working.

### ISSUE THREAD

**Issue by mariofrancoz** [woocommerce/woocommerce#23988] opened 2019-06-24 02:12 UTC
**Describe the bug**
When clicked in the button BUY  the redirec don't work and  return to the same page. 
You can try several times.

When you try to login account, is the same mistake. 
You can try several times.

When I try change the status of one order  at the woocommerce dashboard show me the  erro " This web page was not found"  
You can try several times. 

At the navegation at the Wordpress dashboard  somethis bug the page then exib the erro: " This web page was not found"  
You can try several times.  

**Screenshots**
I didn't  

**Expected behavior**
I need help to fix it.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://digitalinsta.pt
Site address (URL): https://digitalinsta.pt
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_PT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.19
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.20-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wpot_
MaxMind GeoIP Database: ✔
Tamanho total da base de dados: 95.45MB
Tamanho dos dados da base de dados: 92.00MB
Tamanho do índice da base de dados: 3.45MB
wpot_woocommerce_sessions: Dados: 2.39MB + Índice: 0.02MB
wpot_woocommerce_api_keys: Dados: 0.00MB + Índice: 0.01MB
wpot_woocommerce_attribute_taxonomies: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_downloadable_product_permissions: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_order_items: Dados: 0.06MB + Índice: 0.03MB
wpot_woocommerce_order_itemmeta: Dados: 0.45MB + Índice: 0.30MB
wpot_woocommerce_tax_rates: Dados: 0.00MB + Índice: 0.01MB
wpot_woocommerce_tax_rate_locations: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_shipping_zones: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_shipping_zone_locations: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_shipping_zone_methods: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_payment_tokens: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_payment_tokenmeta: Dados: 0.00MB + Índice: 0.00MB
wpot_woocommerce_log: Dados: 0.00MB + Índice: 0.00MB
wpot_ac_abandoned_cart_history_lite: Dados: 0.54MB + Índice: 0.01MB
wpot_ac_email_templates_lite: Dados: 0.01MB + Índice: 0.00MB
wpot_ac_guest_abandoned_cart_history_lite: Dados: 0.01MB + Índice: 0.00MB
wpot_ac_sent_history_lite: Dados: 0.00MB + Índice: 0.00MB
wpot_commentmeta: Dados: 0.03MB + Índice: 0.03MB
wpot_comments: Dados: 0.68MB + Índice: 0.21MB
wpot_duplicator_packages: Dados: 0.00MB + Índice: 0.00MB
wpot_egoi_form_subscribers: Dados: 0.00MB + Índice: 0.00MB
wpot_egoi_map_fields: Dados: 0.00MB + Índice: 0.00MB
wpot_failed_jobs: Dados: 0.02MB + Índice: 0.00MB
wpot_groups_capability: Dados: 0.00MB + Índice: 0.02MB
wpot_groups_group: Dados: 0.00MB + Índice: 0.00MB
wpot_groups_group_capability: Dados: 0.00MB + Índice: 0.00MB
wpot_groups_user_capability: Dados: 0.00MB + Índice: 0.00MB
wpot_groups_user_group: Dados: 0.00MB + Índice: 0.00MB
wpot_links: Dados: 0.00MB + Índice: 0.00MB
wpot_mailchimp_carts: Dados: 0.02MB + Índice: 0.00MB
wpot_mailpoet_custom_fields: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_feature_flags: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_forms: Dados: 0.02MB + Índice: 0.00MB
wpot_mailpoet_log: Dados: 0.02MB + Índice: 0.00MB
wpot_mailpoet_mapping_to_external_entities: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_newsletters: Dados: 0.02MB + Índice: 0.00MB
wpot_mailpoet_newsletter_links: Dados: 0.02MB + Índice: 0.05MB
wpot_mailpoet_newsletter_option: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_newsletter_option_fields: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_newsletter_posts: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_newsletter_segment: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_newsletter_templates: Dados: 4.13MB + Índice: 0.00MB
wpot_mailpoet_scheduled_tasks: Dados: 0.02MB + Índice: 0.03MB
wpot_mailpoet_scheduled_task_subscribers: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_segments: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_sending_queues: Dados: 0.02MB + Índice: 0.03MB
wpot_mailpoet_settings: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_statistics_clicks: Dados: 0.02MB + Índice: 0.05MB
wpot_mailpoet_statistics_forms: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_statistics_newsletters: Dados: 0.02MB + Índice: 0.03MB
wpot_mailpoet_statistics_opens: Dados: 0.02MB + Índice: 0.05MB
wpot_mailpoet_statistics_unsubscribes: Dados: 0.02MB + Índice: 0.05MB
wpot_mailpoet_statistics_woocommerce_purchases: Dados: 0.02MB + Índice: 0.06MB
wpot_mailpoet_stats_notifications: Dados: 0.02MB + Índice: 0.03MB
wpot_mailpoet_subscribers: Dados: 0.05MB + Índice: 0.06MB
wpot_mailpoet_subscriber_custom_field: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_subscriber_ips: Dados: 0.02MB + Índice: 0.02MB
wpot_mailpoet_subscriber_segment: Dados: 0.02MB + Índice: 0.03MB
wpot_mailpoet_user_flags: Dados: 0.02MB + Índice: 0.02MB
wpot_mo_openid_linked_user: Dados: 0.00MB + Índice: 0.00MB
wpot_options: Dados: 77.26MB + Índice: 0.15MB
wpot_postmeta: Dados: 2.04MB + Índice: 1.16MB
wpot_posts: Dados: 2.74MB + Índice: 0.15MB
wpot_queue: Dados: 0.02MB + Índice: 0.00MB
wpot_social_users: Dados: 0.00MB + Índice: 0.00MB
wpot_termmeta: Dados: 0.00MB + Índice: 0.01MB
wpot_terms: Dados: 0.00MB + Índice: 0.01MB
wpot_term_relationships: Dados: 0.01MB + Índice: 0.04MB
wpot_term_taxonomy: Dados: 0.00MB + Índice: 0.01MB
wpot_usermeta: Dados: 0.64MB + Índice: 0.18MB
wpot_users: Dados: 0.02MB + Índice: 0.02MB
wpot_vtprd_purchase_log: Dados: 0.00MB + Índice: 0.00MB
wpot_vtprd_purchase_log_product: Dados: 0.00MB + Índice: 0.00MB
wpot_vtprd_purchase_log_product_rule: Dados: 0.00MB + Índice: 0.00MB
wpot_wc_admin_notes: Dados: 0.02MB + Índice: 0.00MB
wpot_wc_admin_note_actions: Dados: 0.02MB + Índice: 0.02MB
wpot_wc_customer_lookup: Dados: 0.05MB + Índice: 0.03MB
wpot_wc_download_log: Dados: 0.00MB + Índice: 0.00MB
wpot_wc_order_coupon_lookup: Dados: 0.02MB + Índice: 0.03MB
wpot_wc_order_product_lookup: Dados: 0.06MB + Índice: 0.06MB
wpot_wc_order_stats: Dados: 0.05MB + Índice: 0.05MB
wpot_wc_order_tax_lookup: Dados: 0.02MB + Índice: 0.03MB
wpot_wc_product_meta_lookup: Dados: 0.02MB + Índice: 0.09MB
wpot_wc_webhooks: Dados: 0.00MB + Índice: 0.00MB
wpot_yith_wapo_groups: Dados: 0.02MB + Índice: 0.00MB
wpot_yith_wapo_types: Dados: 0.02MB + Índice: 0.00MB
wpot_yoast_seo_links: Dados: 0.02MB + Índice: 0.02MB
wpot_yoast_seo_meta: Dados: 0.02MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 120
custom_css: 1
customize_changeset: 6
feedback: 93
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mailpoet_page: 1
nav_menu_item: 33
o-discount: 1
o-list: 1
page: 24
post: 1
product: 14
product_variation: 150
revision: 278
scheduled-action: 80
schema: 2
shop_coupon: 10
shop_order: 463
shop_order_refund: 14
vtprd-rule: 1
wcccf: 3
wccpf: 15
wp_block: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

VaultPress: por Automattic – 1.9.10
Akismet Anti-Spam: por Automattic – 4.1.2
Duplicator: por Snap Creek – 1.3.14
Easy WP SMTP: por wpecommerce
alexanderfoxc – 1.3.9.1

Google Analytics Dashboard for WP (GADWP): por ExactMetrics – 5.3.8
Jetpack por WordPress.com: por Automattic – 7.4.1
MailPoet 3 (New): por MailPoet – 3.29.0
Social Login, Social Sharing by miniOrange: por social login (miniOrange) – 7.2.4
Multibanco e MBWAY (gateway IfthenPay) para WooCommerce: por Webdados – 3.6.3.1
PayPal for WooCommerce: por Angell EYE – 1.5.7 – Não testado com a versão activa do WooCommerce
Real-Time Find and Replace: por Marios Alexandrou – 3.9
Really Simple SSL: por Rogier Lankhorst
Mark Wolters – 3.2.2

Tawk.to Live Chat: por Tawkto – 0.3.7
WC Fields Factory: por Saravana Kumar K – 3.0.3 – Não testado com a versão activa do WooCommerce
Checkout Field Editor for WooCommerce: por ThemeHiGH – 1.3.2
Woo Discount Rules: por Flycart Technologies LLP – 1.7.16
WooCommerce Blocks: por Automattic – 2.1.0
Abandoned Cart Lite for WooCommerce: por Tyche Softwares – 5.3.4
WooCommerce Cart Tab: por jameskoster – 1.1.2 – Não testado com a versão activa do WooCommerce
WooCommerce Services: por Automattic – 1.21.0
WooCommerce: por Automattic – 3.6.4
Yoast SEO: por Team Yoast – 11.4 – Não testado com a versão activa do WooCommerce

### Inactive Plugins (1) ###

Nextend Social Login: por Nextendweb – 3.0.20

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Página da Loja: #17 - /loja/
Carrinho: #362 - /carrinho/
Finalizar compras: #369 - /finalizar-compra/
Minha conta: #20 - /minha-conta/
Termos e condições: #278 - /politica-de-privacidade-seguranca/

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se estiver a modificar o tema do WooCommerce ou um tema principal que não construiu pessoalmente
recomendamos o uso de um tema dependente. Veja: Como criar um tema dependente

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 78
Oldest: 2019-05-28 03:29:09 +0000
Newest: 2019-06-19 20:07:15 +0000

Pending: 1
Oldest: 2019-06-26 20:07:15 +0000
Newest: 2019-06-26 20:07:15 +0000

Canceled: 1
Oldest: 2019-05-29 02:31:20 +0000
Newest: 2019-05-29 02:31:20 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by claudiosanches** [comment] 2019-06-24 15:48
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried in a clean install and it appeared to work correctly.

> [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> [x ] This bug happens with a default WordPress theme active, or Storefront.
Have you relay tried those?
Because if this bug is not caused by a 3rd party plugin, then something is wrong on your web server, maybe not registering cookies and sessions properly, or something else. I advise you try in a new web server and contact your web server support.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-06-24 15:48 UTC

**Comment by mariofrancoz** [comment] 2019-06-24 15:54
Please,  You can just acess the website: milharesdeseguidores.pt   and try to  creat a new account or add something to the cart shop and you will see what I Sayed before.

This is not closed because I still have the problem could you help me?

**Comment by claudiosanches** [comment] 2019-06-24 16:32
@mariofrancoz can you reproduce it in another hosting environment? Have you tried anything that I said to you? It's closed because there's no steps to reproduce this in another environment, so doesn't sound like an bug on WooCommerce, sounds like an issue on your hosting environment.

**Comment by mariofrancoz** [comment] 2019-06-24 16:39
Claudio I tryed all the steps,  what do you sugesst this could be?  hosting environment Why? I have another sites there and they are working normal.   

I try to use a simple theme  storefront only with woocommerce  active nothing more and still don't working.

**Comment by claudiosanches** [comment] 2019-06-24 16:41
@mariofrancoz so tell me how to reproduce it in my own environment.

**Comment by mariofrancoz** [comment] 2019-06-24 16:43
I don't know Claudio,  I'm asking for help!

**Comment by claudiosanches** [comment] 2019-06-24 16:59
@mariofrancoz Here is an issue tracker for WooCommerce, what you are reporting is not a bug on WooCommerce, at least not possible to reproduce in another environments, also you don't provide any steps of how to reproduce, so doesn't sounds like a bug on WooCommerce. That's why is closed and you should try the public forum if you need general help with WooCommerce: https://wordpress.org/support/plugin/woocommerce/
