### ISSUE TITLE
Customer details within the New Order email TAX issues 

### ISSUE THREAD

**Issue by darknova11** [woocommerce/woocommerce#18164] opened 2017-12-14 09:13 UTC
Hi,

there is an issue with TAX statement in
customer details within the New Order email.

My prices are shown wit TAX on my woo shop but when
new order comes in - customer and admin receive an
email with all details but the price of products
and subtotal have that suffix that states that its
without TAX

All plugins and WP are up to date.

I did setup the options in Woo preferences
that my prices will be added with TAX included…

Need help and suggestions.
Thanks

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!) --DID THAT ON MY LOCAL INSTALMET
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an order
2. Use the option pay on delivery (Plaćanje prilikom preuzimanja)
3. Now you and admin will get the new order details where price of products
and subtotal will say TAX not included but it should be with TAX included price

Problem shown on this image : https://ibb.co/mtNDEm

## Expected/actual behavior

As I mentioned the New Order email displays prices
that already have TAX included but the suffix states 
otherwise.

The final subtotal price is right  

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://medjimurka-bs.hr
Site URL: https://medjimurka-bs.hr
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: hr

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.26
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: dnmbs_wp_
MaxMind GeoIP Database: ✔
Ukupna veličina baze podataka: 194.47MB
Veličina podataka baze podataka: 172.54MB
Indeks veličina baze podataka: 21.93MB
dnmbs_wp_woocommerce_sessions: Podaci: 9.02MB + Index: 0.08MB
dnmbs_wp_woocommerce_api_keys: Podaci: 0.02MB + Index: 0.03MB
dnmbs_wp_woocommerce_attribute_taxonomies: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_woocommerce_downloadable_product_permissions: Podaci: 0.02MB + Index: 0.03MB
dnmbs_wp_woocommerce_order_items: Podaci: 0.08MB + Index: 0.02MB
dnmbs_wp_woocommerce_order_itemmeta: Podaci: 0.33MB + Index: 0.31MB
dnmbs_wp_woocommerce_tax_rates: Podaci: 0.02MB + Index: 0.06MB
dnmbs_wp_woocommerce_tax_rate_locations: Podaci: 0.02MB + Index: 0.05MB
dnmbs_wp_woocommerce_shipping_zones: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_woocommerce_shipping_zone_locations: Podaci: 0.02MB + Index: 0.05MB
dnmbs_wp_woocommerce_shipping_zone_methods: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_woocommerce_payment_tokens: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_woocommerce_payment_tokenmeta: Podaci: 0.02MB + Index: 0.03MB
dnmbs_wp_woocommerce_log: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_blc_filters: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_blc_instances: Podaci: 0.14MB + Index: 0.05MB
dnmbs_wp_blc_links: Podaci: 0.19MB + Index: 0.06MB
dnmbs_wp_blc_synch: Podaci: 0.06MB + Index: 0.05MB
dnmbs_wp_cf_participants: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_cf_participants_meta: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_commentmeta: Podaci: 0.05MB + Index: 0.03MB
dnmbs_wp_comments: Podaci: 0.14MB + Index: 0.09MB
dnmbs_wp_cptch_blacklist_ip: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_cptch_images: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_cptch_packages: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_cptch_track_countries: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_cptch_track_visitor: Podaci: 11.52MB + Index: 0.00MB
dnmbs_wp_cptch_whitelist: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_enquiry_detail_new: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_enquiry_history: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_enquiry_meta: Podaci: 0.02MB + Index: 0.03MB
dnmbs_wp_enquiry_products: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_enquiry_quotation: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_enquiry_quotation_version: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_enquiry_thread: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_et_bloom_stats: Podaci: 4.52MB + Index: 0.00MB
dnmbs_wp_et_social_stats: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_failed_jobs: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_hctpc_images: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_hctpc_packages: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_hctpc_whitelist: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_links: Podaci: 0.02MB + Index: 0.02MB
dnmbs_wp_mailchimp_carts: Podaci: 0.06MB + Index: 0.00MB
dnmbs_wp_options: Podaci: 6.08MB + Index: 1.05MB
dnmbs_wp_postmeta: Podaci: 35.56MB + Index: 15.86MB
dnmbs_wp_posts: Podaci: 103.16MB + Index: 3.34MB
dnmbs_wp_queue: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_ta_link_clicks: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_ta_link_clicks_meta: Podaci: 0.02MB + Index: 0.00MB
dnmbs_wp_termmeta: Podaci: 0.08MB + Index: 0.09MB
dnmbs_wp_terms: Podaci: 0.06MB + Index: 0.03MB
dnmbs_wp_term_relationships: Podaci: 0.13MB + Index: 0.06MB
dnmbs_wp_term_taxonomy: Podaci: 0.08MB + Index: 0.06MB
dnmbs_wp_usermeta: Podaci: 0.17MB + Index: 0.14MB
dnmbs_wp_users: Podaci: 0.02MB + Index: 0.05MB
dnmbs_wp_yoast_seo_links: Podaci: 0.30MB + Index: 0.08MB
dnmbs_wp_yoast_seo_meta: Podaci: 0.09MB + Index: 0.00MB

### Post Type Counts ###

attachment: 6232
contestfriend: 2
custom_css: 1
et_pb_layout: 135
nav_menu_item: 140
page: 30
post: 59
product: 1389
product_variation: 1399
project: 20
revision: 476
shop_coupon: 4
shop_order: 332
thirstylink: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Akismet Anti-Spam: od Automattic – 4.0.1
Bloom: od Elegant Themes – 1.2.22
Broken Link Checker: od Janis Elsts
Vladimir Prelovac – 1.11.5

Captcha: od simplywordpress – 4.4.5
contestfriend za WordPress: od Nick Berry – 1.0
WP-CPIS: od  – 1.0.20 – Nije testirano s aktivnom inačicom WooCommercea
Elegant Themes Support: od Elegant Themes – 1.3
Elegant Themes Updater: od Elegant Themes – 1.0
Jetpack by WordPress.com: od Automattic – 5.6
WooCommerce Custom Thank You Page: od Jelly Pixel Studio – 1.0 – Nije testirano s aktivnom inačicom WooCommercea
MailChimp for WooCommerce: od MailChimp – 2.1.2 – Nije testirano s aktivnom inačicom WooCommercea
Max Mega Menu: od Tom Hemsley – 2.4
Monarch Plugin: od Elegant Themes – 1.3.24
Orbisius Child Theme Creator: od Svetoslav Marinov (Slavi) – 1.4.6
WooCommerce Product Filter: od Mihajlovic Nenad – 6.5.1 – Nije testirano s aktivnom inačicom WooCommercea
Product Brands For WooCommerce: od Varun Sridharan – 0.7 – Nije testirano s aktivnom inačicom WooCommercea
Product Enquiry Pro for WooCommerce (A.K.A QuoteUp): od WisdmLabs – 6.0.0 – Nije testirano s aktivnom inačicom WooCommercea
Rewrite Rules Inspector: od Daniel Bachhuber
Automattic – 1.2.1

Search By SKU - for Woocommerce: od Matthew Lawson – 0.6.1 – Nije testirano s aktivnom inačicom WooCommercea
ThirstyAffiliates: od Rymera Web Co – 3.1.3
WooCommerce MX R1 račun: od Media X – 1.0 – Nije testirano s aktivnom inačicom WooCommercea
WooCommerce: od Automattic – 3.2.6
Yoast SEO: od Tim Yoast – 5.9.3
WP-Optimize: od David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP-Sweep: od Lester 'GaMerZ' Chan – 1.0.12

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: HRK (Kn)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Osnova trgovine: #49 - /trgovina/
Košarica: #50 - /kosarica/
Blagajna: #51 - /placanje/
Moj račun: #52 - /moj-racun/
Odredbe i uvjeti: #177 - /uvijeti-koristenja/

### Theme ###

Name: Divi Child 01
Version: 2.6.4.4
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.91
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child-01/woocommerce/content-single-product.php
Divi-child-01/woocommerce/emails/admin-cancelled-order.php
Divi-child-01/woocommerce/emails/admin-new-order.php
Divi-child-01/product-searchform.php

`
```
</details>

**Comment by mikejolley** [comment] 2017-12-14 13:55
I couldn't replicate this one on local. You look to have no tax rates set up which I can tell because there is no tax amount shown. The only bug which I found relating to this was it shows `(includes $0 tax)` on my local install. I'll fix that.

Other than that it looks fine - maybe you can screenshot your tax settings for us.

**Comment by mikejolley** [comment] 2017-12-15 12:29
If you have extra feedback please reply back. The issue I noticed was fixed in #18172. The other issues don't seem to be reproducible. Let me know if you can help me reproduce the issue with your settings.

Thanks

**Closed by mikejolley** 2017-12-15 12:29 UTC
Labels: Status: Needs Author Feedback

**Comment by vadikcoma** [comment] 2018-01-31 21:28
I'm having the exact same issue. All prices in shop are with taxes, however when customer orders something, admin and customer receives email without tax. 

Screens are attached

Will appreciate your help and advice

![screenshot 27](https://user-images.githubusercontent.com/15925904/35648415-5f96877c-06de-11e8-825f-20f7f85c800e.png)
![screenshot 25](https://user-images.githubusercontent.com/15925904/35648362-308d8822-06de-11e8-8076-b5f7a6bfe381.png)
![screenshot 26](https://user-images.githubusercontent.com/15925904/35648373-3d66a07e-06de-11e8-95a3-1d9073277f9e.png)

**Comment by mikejolley** [comment] 2018-01-31 21:32
Display prices in cart checkout is set to excl.

**Comment by vadikcoma** [comment] 2018-01-31 21:38
Thanks @mikejolley! 

I tried that, however in this case I dont get to see how much of tax customer pays. We need to have this on current project

![screenshot 28](https://user-images.githubusercontent.com/15925904/35648883-e0123a30-06df-11e8-87ab-ab9966da80fd.png)

**Comment by mikejolley** [comment] 2018-01-31 21:53
It shows itemised after the order total. Just doesn't have its own row!

**Comment by vadikcoma** [comment] 2018-01-31 21:57
Ah, really. Thank you so much!
