### ISSUE TITLE
Tax are not apply to guest user

### ISSUE THREAD

**Issue by redsparkers** [woocommerce/woocommerce#20908] opened 2018-07-26 11:06 UTC
Hello,
i my site i have added tax for some specific state like florida.
tax are applied to the logged in user but not apply to guest user
Please also refer the screenshots
![tax for logged in user](https://user-images.githubusercontent.com/35765884/43258873-ffb4283e-90f1-11e8-8483-d0933f444191.png)
![not showing tax for logged out user](https://user-images.githubusercontent.com/35765884/43258875-0203858a-90f2-11e8-9427-d7a335c6f378.png)

**Comment by claudiulodro** [comment] 2018-07-26 18:48
Hi there,

I was unable to reproduce this issue; I set up a tax for Florida, went to check out as a guest, and the tax was correctly applied. Make sure you have fully filled out the address as the guest user when testing and [your taxes are set up correctly](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-12).

In the absence of more information, I am going to close this issue as non-reproducible. Thanks.

**Closed by claudiulodro** 2018-07-26 18:48 UTC
