### ISSUE TITLE
order failed notification 

### ISSUE THREAD

**Issue by adiboo67** [woocommerce/woocommerce#26735] opened 2020-06-09 17:07 UTC
Hi
i have a problem with woocommerce 4.2.0
when a customer buy i product ( that was out of stock or low stock) he paid by credit card , he receive a first email pending  order and another email order failed.
Can someone tell me how to desactivate the order email failed for customer. thanks
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**Comment by juliaamosova** [comment] 2020-06-09 19:07
Hi @adiboo67,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. 

I am happy to help ss a one-time exception. You can deactivate `Failed order` email by navigating to `WooCommerce / Settings / Emails` and clicking on `Failed order` section:

![email](https://user-images.githubusercontent.com/19143190/84189200-e3960c80-aa62-11ea-98af-90ba885275c9.jpg) 

In the future, in order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-06-09 19:07 UTC

**Comment by adiboo67** [comment] 2020-06-10 07:50
Hi thanks for your reply
but the order failed that you show on screenshot is for the admin, my problem is **the customer receive failed order** after a first email order in process, when one productin hisd order is out of stock.
Thanks for your help
