### ISSUE TITLE
inventory management

### ISSUE THREAD

**Issue by richsanyam** [woocommerce/woocommerce#30003] opened 2021-05-29 11:32 UTC
Actually there is a very serious bug in woocommerce inventory management , i have a footwear store , so as you all know that footwear have multiple sizes , the issue i am facing is that whenever even a single size goes out of stock , the whole product is marked as out of stock . 
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
only the variation should be marked as out of stock but not the whole product

**Expected behavior**
whenever the size goes as out of stock ,that size should be marked as out of stock and not the whole product
**Actual behavior**
Actually there is a very serious bug in woocommerce inventory management , i have a footwear store , so as you all know that footwear have multiple sizes , the issue i am facing is that whenever even a single size goes out of stock , the whole product is marked as out of stock . 
**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'https://stylestry.com/shop/     you will see most of the products as out of stock
2. Click on '. any one out of stock product
3. Select any size any colour, you will realize that the stock is available and only one particular size  does not have inventory
4.

**Comment by tammullen** [comment] 2021-06-02 11:07
Hi @richsanyam 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request related to setting up variable products which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review our [Variable Product docs](https://docs.woocommerce.com/document/variable-product/) for a guide on creating a product with variations. The section on [Inventory Management](https://docs.woocommerce.com/document/variable-product/#inventory-management) will possibly help with your issue.
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case; 
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-06-02 11:07 UTC
