### ISSUE TITLE
Order update webhook not firing

### ISSUE THREAD

**Issue by PBradstreet01** [woocommerce/woocommerce#26794] opened 2020-06-17 11:19 UTC
Hi,
I have created a webhook  with topic 'order updated' and it works properly if I go into an order and update it manually. However it is not firing automatically when a new order is received or modified from the front end. I have checked  the logs and there are no log entries around the period that a new order is received.

It seems that the webhook is just not getting added to the queue when the order is received. Could you please help me troubleshoot this?

### WordPress Environment ###

WordPress address (URL): https://cliffordbrewing.creativeinterface.com
Site address (URL): https://cliffordbrewing.creativeinterface.com
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.17
PHP Post Max Size: 40 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 39 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_21_
Total Database Size: 50.99MB
Database Data Size: 39.94MB
Database Index Size: 11.05MB
wp_21_woocommerce_sessions: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
wp_21_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_21_woocommerce_order_items: Data: 0.27MB + Index: 0.09MB + Engine InnoDB
wp_21_woocommerce_order_itemmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_21_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_21_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_actionscheduler_actions: Data: 0.25MB + Index: 0.22MB + Engine InnoDB
wp_21_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_actionscheduler_logs: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_21_cleantalk_sessions: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_21_cleantalk_sfw: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_cleantalk_sfw_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_cleantalk_spamscan_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_comments: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_21_et_bloom_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_mec_dates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_21_mec_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_21_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_nextend2_section_storage: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_21_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_nextend2_smartslider3_sliders: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_21_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_nextend2_smartslider3_slides: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_21_options: Data: 15.20MB + Index: 0.08MB + Engine InnoDB
wp_21_postmeta: Data: 3.05MB + Index: 4.55MB + Engine InnoDB
wp_21_posts: Data: 13.02MB + Index: 0.33MB + Engine InnoDB
wp_21_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_21_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_wc_order_product_lookup: Data: 0.31MB + Index: 0.34MB + Engine InnoDB
wp_21_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_21_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_21_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_21_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_wcsc_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_21_woocommerce_square_customers: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_21_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_21_wpforms_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_wpforms_entry_fields: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_21_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_21_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 2.39MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 102
custom_css: 3
customize_changeset: 145
divi_bars: 2
et_body_layout: 2
et_pb_layout: 15
et_template: 7
et_theme_builder: 3
mec_calendars: 12
nav_menu_item: 14
oembed_cache: 1
page: 35
post: 5
product: 17
product_variation: 27
revision: 584
shop_order: 559

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

WP-Cron Status Checker: by Webhead LLC – 1.2.1
Admin Menu Editor: by Janis Elsts – 1.9.5
Bloom: by Elegant Themes – 1.3.10
Check Email: by Chris Taylor – 0.5.7
Anti-Spam by CleanTalk: by СleanTalk  – 5.139
Code Snippets: by Code Snippets Pro – 2.14.0
Cookie Notice: by dFactory – 1.3.2
Age Verification: by Devio Digital – 2.3.2
Divi Bars: by Divi Life — Tim Strifler – 1.8.6.1
Duplicate Page: by mndpsingh287 – 4.2
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.3.9.3

Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.6.5 – Installed version not tested with active version of WooCommerce 4.2.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
SSL Insecure Content Fixer: by WebAware – 2.7.2
Wicked Folders: by Wicked Plugins – 2.17.2
Booster for WooCommerce: by Pluggabl LLC – 5.0.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Square: by WooCommerce – 2.1.5 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0
WP Crontrol: by John Blackbourn & contributors – 1.8.5
WP File Manager: by mndpsingh287 – 6.4
WP Test Email: by Boopathi Rajan – 1.1.4
WordPress MU Domain Mapping: by Donncha O Caoimh – 0.5.5.1
Multisite Plugin Manager: by Aaron Edwards – 3.1.6
Multisite Plugin Stats: by Lew Goettner – 1.1
Imagify: by WP Media – 1.9.10
Hummingbird: by WPMU DEV – 2.4.2

### Inactive Plugins (45) ###

All In One SEO Pack: by All in One SEO Team – 3.5.2
Asgaros Forum: by Thomas Belser – 1.15.4
Astero WordPress Weather Plugin: by ArchTheme – 1.4.3
Bulk Delete: by Sudar – 6.0.2
Child Theme Configurator: by Lilaea Media – 2.5.5
Child Theme Generator: by Serafino Corriero – 2.2.6
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.4.1

Collapse-O-Matic: by twinpictures
baden03 – 1.7.12

Divi Builder: by Elegant Themes – 4.4.8
Divi Collage: by munirkamal – 1.0.0
Divi Mega Pro: by Divi Life — Tim Strifler – 1.6.4
Divi Team Member: by Shourov – 1.0.1
DTS Blog Module Pro: by DiviFlix – 3.0.0
Duplicator Pro: by Snap Creek – 3.8.6.2
Email Encoder - Protect Email Addresses: by Ironikus – 2.0.7
Export Media Library: by Mass Edge Inc. – 3.0.1
Facebook for WooCommerce: by Facebook – 1.11.4
Featured Images in RSS for Mailchimp & Other Email: by 5 Star Plugins – 1.5.6
Fullwidth Page Templates: by Brainstorm Force – 1.1.0
Google Ads for WooCommerce: by Kliken – 1.0.4 – Installed version not tested with active version of WooCommerce 4.2.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
HTTP Headers: by Dimitar Ivanov – 1.15.1
Jetpack by WordPress.com: by Automattic – 8.6.1
Mailchimp for WooCommerce: by Mailchimp – 2.4.0 – Installed version not tested with active version of WooCommerce 4.2.0
Modern Events Calendar: by Webnus Team – 4.7.5
MultiSite Clone Duplicator: by Julien OGER
Pierre DARGHAM
David DAUGREILH
GLOBALIS media systems – 1.5.3

Network Subsite User Registration: by Justin Fletcher – 2.8
NS Cloner - Site Copier: by Never Settle – 4.0.8
Polylang: by WP SYNTEX – 2.7.3
Product Subtitle For WooCommerce: by Varun Sridharan – 4.5.1
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.3.3

Shortcodes Ultimate: by Vladimir Anokhin – 5.9.0
Smart Slider 3 Pro: by Nextend – 3.4.1.6
Tabs Pro wpshopmart: by wpshopmart – 5.0
Tidio Chat: by Tidio Ltd. – 4.2.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.25

WooCommerce Services: by Automattic – 1.23.2
Woosquare Payment: by wpexperts.io – 2.8 – Installed version not tested with active version of WooCommerce 4.2.0
WordPress Importer: by wordpressdotorg – 0.7
WP-CORS: by Tim Stephenson – 0.2.1
WP All Import: by Soflyy – 3.5.3
WPForms: by WPForms – 1.5.6.2
WP Mail SMTP: by WPForms – 2.1.1
Yoast SEO: by Team Yoast – 14.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
sunrise.php: sunrise.php

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5-2)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #14955 - /shop/
Cart: #14972 - /cart/
Checkout: #15818 - /checkout/
My account: #14974 - /my-account/
Terms and conditions: #15011 - /privacy/

### Theme ###

Name: CliffordBrewery
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.4.8
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Action Scheduler ###

Complete: 782
Oldest: 2020-05-24 12:16:24 -0400
Newest: 2020-06-17 06:05:20 -0400

Pending: 1
Oldest: 2020-06-23 11:44:58 -0400
Newest: 2020-06-23 11:44:58 -0400

`

**Comment by tammullen** [comment] 2020-06-18 21:57
Hi @PBradstreet01 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using an order update webhook. Everything is working as expected on my end and it is firing on order update and new order.

For reference this is my webhook setup

![Screenshot_2020-06-18_at_22_53_21](https://user-images.githubusercontent.com/24649833/85075796-e0172980-b1b6-11ea-90e1-20f22869e44e.png)

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Webhook Guide](https://docs.woocommerce.com/document/webhooks/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-06-18 21:57 UTC
