### ISSUE TITLE
How to change variants in cart without plugin

### ISSUE THREAD

**Issue by fnxit** [woocommerce/woocommerce#26638] opened 2020-05-29 11:26 UTC
Hi,

right now i got WC Fields Factory plugin to make field editable in cart, but i would like to got this option without any plugin, but "inside" woocommerce. Is there any option?

**Comment by juliaamosova** [comment] 2020-05-29 20:28
Hi @fnxit,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-05-29 20:28 UTC
