### ISSUE TITLE
Sku Won't update 

### ISSUE THREAD

**Issue by Aspenlightglass** [woocommerce/woocommerce#21035] opened 2018-08-12 15:49 UTC
I am using the duplicate product to create a new product, but when I go to update the SKU number, it will not update.  It continues to use the duplicate SKU number assigned when I created the copy.

**Comment by rodrigoprimo** [comment] 2018-08-14 13:07
I'm not able to reproduce this issue. I was able to successfully duplicate a product and then change its SKU. Closing for now as invalid. If you are still experiencing this problem and you can reproduce it on a clean WooCommerce install, please open another issue following the bug report template. The information that is asked there is crucial for us to help understand the problem.

**Closed by rodrigoprimo** 2018-08-14 13:07 UTC
