### ISSUE TITLE
Table Does Not Exist False Positive After Upgrade

### ISSUE THREAD

**Issue by MojoCreator** [woocommerce/woocommerce#21874] opened 2018-11-09 21:05 UTC
The tables actually do exist and there are no errors associated with the tables.  This was an upgrade to WooCommerce DB 3.5.1.  This is on Apache 2.4 running PHP 7.2. All theme templates are updated. I am using a db table prefix for the tables. The only errors on the status page are the "Table does not exist" errors.

I was also able to "Clear Sessions" using the Tools>Clear Sessions button and it showed that the sessions table was cleared. I checked the woocommerce_sessions table and sure enough, all sessions were cleared.

**WooCommerce Table Status:** https://www.screencast.com/t/Ab4PoWnOs
**WooCommerce Clear Sessions:** https://www.screencast.com/t/byvxYvFinp
**WooCommerce Collation:** https://www.screencast.com/t/qgDvfiYA

_Originally posted by @MojoCreator in https://github.com/woocommerce/woocommerce/issue_comments#issuecomment-437494408_

**Comment by maddisondesigns** [comment] 2018-11-10 10:38
I've just upgraded two sites to WC 3.5.1 and seeing the same issue. One site is the prod site and another is my local dev version of the site. Both are running on Apache and both are showing a dozen tables as not existing, even when they do actually exist.

**Comment by rodrigoprimo** [comment] 2018-11-13 18:36
Duplicate of #21657

**Closed by rodrigoprimo** 2018-11-13 18:36 UTC
