### ISSUE TITLE
Woocommerce order mail is blocked at Hotmail and live because of URL in Order number

### ISSUE THREAD

**Issue by Hbitvof** [woocommerce/woocommerce#27515] opened 2020-08-29 08:43 UTC
Hi,

We received several complaints from customers with Hotmail and Live mail who didn't receive orderinformation mail send from out Woocommerce shop. 

We setup everything like, SPF and DKIM and sending normal mail to Hotmail and Live from our website is no problem.

I noticed when I remove the link in the ordernumber the mail is accepted again in Hotmail and Live:
![image](https://user-images.githubusercontent.com/41229269/91632876-363cf000-e9e4-11ea-9d72-c3f4bb5f0cc9.png)

I don't see an option to remove this link in the e-mailtemplate.

Can you please take a look at this issue and for now make an update to remove this link in the mail's that's being send from Woocommerce?

**Comment by Hbitvof** [comment] 2020-09-14 16:15
Any action or reply would be nice. This is a major thing.

**Comment by Hbitvof** [comment] 2020-10-17 11:05
Why is no one responding to this issue?

**Comment by tammullen** [comment] 2020-10-22 20:00
Hi @Hbitvof 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 
​

> customers with Hotmail and Live mail who didn't receive orderinformation mail send from out Woocommerce shop.

I assume this means you are referring to Completed Order emails

![Screenshot_2020-10-22_at_20_43_16](https://user-images.githubusercontent.com/24649833/96922921-77172980-14a8-11eb-8714-33e69b19c98d.png)

I tried this out and the emails do not have an order number that is a hyperlink

This is because by default in the code for customer completed orders `sent_to_admin` is set to `false`

https://github.com/woocommerce/woocommerce/blob/02cf0dfaed5923513de0c88add597d1560c2cfd2/includes/emails/class-wc-email-customer-completed-order.php#L107 

And in the template if `sent_to_admin` is set to `false` the order number is not made a hyperlink
https://github.com/woocommerce/woocommerce/blob/02cf0dfaed5923513de0c88add597d1560c2cfd2/templates/emails/email-order-details.php#L26

For further email debugging help please see https://docs.woocommerce.com/document/email-faq/#section-4

If you are still experiencing this issue can you confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

If you have performed a conflict test and you are still experiencing the issue it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment. Without these details, we can’t fully evaluate this issue.

**Comment by juliaamosova** [comment] 2020-10-29 18:31
Hi @Hbitvof,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-10-29 18:31 UTC
Labels: can't reproduce, status: needs feedback

**Comment by Hbitvof** [comment] 2020-11-20 07:25
Hi,

I think you are wrong. I disabled all plugins switched to a default WP theme (Twenty Twenty) and still the URL is in the order number.

And I am not the only one who is complaining about this, please check https://www.businessbloomer.com/woocommerce-remove-permalink-product-order-table/

**Comment by Hbitvof** [comment] 2020-11-20 07:25
@juliaamosova can you please reopen this issue?
