### ISSUE TITLE
Incorrect/misleading message for Shipping options in cart

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce#24674] opened 2019-09-24 12:49 UTC
**Describe the bug**
When setting up the Shipping options/calculations in the cart for a new WooCommerce store - you can select from the following two options:

<img width="600" alt="Screenshot 2019-09-24 at 13 45 19" src="https://user-images.githubusercontent.com/10805911/65512672-91f82280-ded1-11e9-9237-123f57ecc23b.png">

if you unselect both of those options and then go view the shipping options in the cart you get the following message:

<img width="541" alt="Screenshot 2019-09-23 at 13 10 04" src="https://user-images.githubusercontent.com/10805911/65512712-a9cfa680-ded1-11e9-8a0c-0ab9494359ae.png">

However, you cannot enter an address on the cart page and instead - based on the settings you have chosen that text should rather read something like this instead:

> Shipping costs are calculated during checkout

**To Reproduce**
1. Setup a new install of WooCommerce
2. Install Storefront
3. Uncheck both those options highlighted in the screenshot above
4. Add an item to your cart and view the message alongside the shipping options

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment] 2019-10-02 10:49
Thanks for reporting. I agree it's confusing. 
It's a good first issue if anyone wants to help out :)

**Comment by dev-vip** [comment] 2019-10-03 00:49
can't reproduce :(  new store, unticked and i got exactly what was sought. 

'Shipping options will be updated during checkout'

**Comment by claudiosanches** [comment] 2019-10-14 15:19
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24807.

**Closed by claudiosanches** 2019-10-14 15:19 UTC
Labels: enhancement, hacktoberfest, help wanted, priority: low
