### ISSUE TITLE
Search Option does not work for Products

### ISSUE THREAD

**Issue by 5aplus** [woocommerce/woocommerce#24733] opened 2019-10-01 13:28 UTC
Search option does not work for Products. 

**To Reproduce**
1. Go to 'All Products->Products'
2. Click on 'Search'
3. Write 'business card'
4. As you can see, there is no business card. 
See attached screenshots.

**Expected behavior**

We want search to be functional. 
We want this issue to be fixed as soon as possible.
Thank you!

![image_2019_10_01T13_18_28_125Z](https://user-images.githubusercontent.com/39902596/65966132-5bd61800-e468-11e9-92b3-f9308f60acb3.png)
![image_2019_10_01T13_19_43_089Z](https://user-images.githubusercontent.com/39902596/65966133-5bd61800-e468-11e9-97f6-7e3d7b20a715.png)

**Comment by vedanshujain** [comment] 2019-10-02 08:34
Hi, thanks for reporting the issue, but unfortunately I am not able to reproduce on my end. Can you please fill the template provided while you were opening the issue, specifically please post the system status report from **WooCommerce > System Status** in WordPress admin.

I am closing this issue as non-reproducible, but please comment if you still see this. Thanks.

**Closed by vedanshujain** 2019-10-02 08:34 UTC
