### ISSUE TITLE
Send duplicated emails to CC or BCC recipients using woocommerce_email_headers hook 

### ISSUE THREAD

**Issue by lomars** [woocommerce/woocommerce#23553] opened 2019-04-30 06:46 UTC
When using the filter hook `woocommerce_email_headers` located in WC_Email Class to add a CC _(or a BCC)_  recipient, an email is sent twice to this recipient when targeting for exemple `customer_on_hold_order` email ID _(or any other customer notification)_. 

But it doesn't happen when targeting `new_order` email ID… This seems to happen since Woocommerce 3.5 release (may be before).

To reproduce this issue use the following simple function adding a functional email as CC:

```
add_filter( 'woocommerce_email_headers', 'additional_cc_email_recipient', 10, 3 );
function additional_cc_email_recipient( $headers, $email_id, $order ) {
    if ( in_array( $email_id, array( 'customer_on_hold_order', 'customer_processing_order' ) ) {
        // Set a functional email address
        $cc_email = 'john.doe@gmail.com'
		
        $headers .= 'Cc: ' . $cc_email . '\r\n';
    }
    return $headers;
}
```
Then place an order like a customer can do. The email set on CC receive the notification twice.

**Comment by claudiosanches** [comment] 2019-05-06 21:32
I tested your code, there's a few syntax errors, but didn't manage to reproduce this issue.
It's just sending one email.
Have you tested in a clean install?

**Comment by lomars** [comment] 2019-05-07 10:15
Yes I have tested that on a clean install and I have the same behavior… 

I have reported that bug from the following StackOverFlow thread: https://stackoverflow.com/q/55913946/3730754

_(Tested on WooCommerce 3.5.8 and 3.6.2, using Storefront theme)_

**Comment by claudiosanches** [comment] 2019-05-07 13:42
> Yes I have tested that on a clean install and I have the same behavior…

Sorry, but in this bug report is missing a several information and steps to reproduce:

<pre>
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
</pre>

**Comment by claudiosanches** [comment] 2019-05-07 19:37
I did more tests, and still I can't reproduce this issue.

This is the email header that email getting:

![2019-05-07-16-08-32](https://user-images.githubusercontent.com/1264099/57326229-63280e00-70e2-11e9-99db-0ae4514ae95f.png)

All seems fine, no duplicated email.

Also I checked the headers from `woocommerce_email_headers`:

```php
add_filter( 'woocommerce_email_headers', function( $headers, $email_id ) {
    if ( in_array( $email_id, array( 'customer_on_hold_order', 'customer_processing_order' ) ) ) {
        // Set a functional email address.
        $cc_email = 'john.doe@gmail.com';

        $headers .= "Cc: $cc_email \r\n";
    }

    error_log( print_r( $headers, true ) );

    return $headers;
}, 10, 2 );
```

This will only output it:

![2019-05-07-16-14-02](https://user-images.githubusercontent.com/1264099/57326550-26a8e200-70e3-11e9-8993-9b20d1e20c9b.png)

The first one is for `new_order`, and then the second for `customer_on_hold_order`.

Here a screenshot of my last orders, so check that is really changing to `on-hold`:

![Screenshot from 2019-05-07 16-15-16](https://user-images.githubusercontent.com/1264099/57326667-6243ac00-70e3-11e9-898a-1de96167fead.png)

So definitely is sending just one email for `customer_on_hold_order`.

Checking the code, all data is passed to `wp_mail()`:

https://github.com/woocommerce/woocommerce/blob/f66e523c5f1aa51802e420e6323673a11d6a75e3/includes/emails/class-wc-email.php#L593-L618

Maybe one of your plugins is causing it, since as you can see, it's possible to replace `wp_mail()`, also `wp_mail()` have a few filters that may be used by 3rd party plugins too.

I'll close this issue since I'm not able to reproduce with the code and steps you provided.

**Closed by claudiosanches** 2019-05-07 19:37 UTC
Labels: status: needs feedback, status: needs review
