### ISSUE TITLE
After Reset Variations, Duplicate data Weight & Dimentions

### ISSUE THREAD

**Issue by Prima699** [woocommerce/woocommerce#27635] opened 2020-09-09 20:07 UTC
I got some issue at the detail product page, that was a single product.
I try to figure out what's make the duplicate data. The bug at view single-products 
after change or choose the variations of items, the button reset will appear.

![Screenshot_7](https://user-images.githubusercontent.com/39323979/92643453-022ecc80-f30c-11ea-910f-20de822a2c5a.png)

And after I click the reset button

![Screenshot_8](https://user-images.githubusercontent.com/39323979/92647317-e3333900-f311-11ea-9999-8ee9c7eeda09.png)

after resetting the value of the weight and dimensions was double the value.

for the theme I use Astra.

Can someone help me with this issue? 

[Bug Description]

If you select the color of an item using multiple selection columns, the problem will only happen if the information in the color selection column is changed back to "Pilih Opsi". In the information column only on row weight and dimension, the contents of the description are changed to duplicate.

![Images](https://user-images.githubusercontent.com/39323979/92994733-01be4d80-f527-11ea-8880-be0e7a3c7285.jpg)

Video Bug Reproduce:

[https://youtu.be/OtKRK3BzLcw](https://youtu.be/OtKRK3BzLcw)
[Video by loom](https://www.loom.com/share/9768eb9aafce461fb53629e05edfc46b)

**Comment by juliaamosova** [comment] 2020-09-10 21:54
Hi @Prima699,

Thank you for submitting the issue. However, I am not sure how to reproduce this. Can you please provide more clear steps?

In particular, I don't understand what the action below means:

>after resetting the value of the weight and dimensions was double the value.

Can you please clarify how exactly your product is set up and what actions do you take to see the issue?

In addition to that, please also test by switching the theme to our default [Storefront](https://en-gb.wordpress.org/themes/storefront/) theme and see if the issue persists there. 

If the issue is resolved with the default theme, it means that the theme Astra could be causing the issue.

**Comment by Prima699** [comment] 2020-09-11 08:46
Hi @juliaamosova 
Thank you for responding to my issue.
I attach loom link that you might be can see to reproduce the issue [Video Reproduce](https://www.loom.com/share/9768eb9aafce461fb53629e05edfc46b).

I have done switching the theme to default using [Storefront](https://en-gb.wordpress.org/themes/storefront/) theme. But it's still the same.

**Comment by rodrigoprimo** [comment] 2020-12-04 15:33
Just documenting here that I stumble across this issue when reviewing PR #28476 and that I was also not able to reproduce the problem when running Storefront. This looks like a problem with the theme being used or another plugin. The "Hapus" button that is shown in the video is the "Clear" button that is displayed once the user selects at least one attribute when viewing the page of a variable product.

**Comment by roykho** [comment] 2020-12-22 20:23
I've tested this however I am also unable to replicate this. @Prima699 - Do you perhaps have a conflicting plugin?

**Comment by tammullen** [comment] 2021-03-26 17:08
Hi @Prima699 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2021-03-26 17:08 UTC
Labels: needs feedback
