### ISSUE TITLE
Partial refunds not reflected in "Taxes by code" report

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#25311] opened 2019-12-24 13:26 UTC
**Describe the bug**
When issuing partial refunds, they aren't reflected in **Reports > Taxes > Taxes by code**, and this is inconsistent with the overview and the taxes by date report.

**To Reproduce**

* Give yourself an order with at least 2 items (make sure taxes are added to your store) - review the reports 
* Issue a partial refund - review the reports overview, the taxes by code and the taxes by date. Taxes by code is not consistent with the other two. 

In the example below, I bought 2*$12 ($10 + $2 VAT). Then I issued a partial refund of 1 of those products.

**Reports overview**: correct

![](https://d.pr/i/doAcnv+)
Link to image here: https://d.pr/i/doAcnv.

**Reports > Taxes > Taxes by date**: correct

![](https://d.pr/i/ZKZdQv+)
Link to image here: https://d.pr/i/ZKZdQv.

**Reports > Taxes > Taxes by code**: incorrect

![](https://d.pr/i/Y6ZBO5+)
Link to image here: https://d.pr/i/Y6ZBO5.

This is incorrect; this should be $2 given that the (partial) refund already happened. Note, when I issue the rest of the refund (the second product), then this goes to $0:

![](https://d.pr/i/i6tJm4+)
Link to image here: https://d.pr/i/i6tJm4.

**Expected behavior**
All three tabs are consistent

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://shop.test
Site address (URL): https://shop.test
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.3
PHP Version: 7.1.32 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.64.1
(SecureTransport) LibreSSL/2.8.3

SUHOSIN Installed: –
MySQL Version: 5.7.27
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 5.49MB
Database Data Size: 4.02MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.25MB + Index: 0.17MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpdatacharts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpdatatables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpdatatables_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.50MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Query Monitor: by John Blackbourn – 3.5.2
Admin Color Schemes: by WordPress Core Team – 2.2
Code Snippets: by Code Snippets Pro – 2.13.3
String Locator: by Clorith – 2.3.1
WooCommerce Blocks: by Automattic – 2.5.7
WooCommerce Admin: by WooCommerce – 0.23.2
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.26
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.15
WooCommerce Points and Rewards: by WooCommerce – 1.6.26
WooCommerce Product Vendors: by WooCommerce – 2.1.22
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.0.9
WooCommerce: by Automattic – 3.8.1
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Mail Logging: by MailPoet – 1.9.5
WP phpMyAdmin: by Puvox.software – 2.93

### Inactive Plugins (8) ###

Printful Integration for WooCommerce: by Printful – 2.1.8
WooCommerce Advanced Notifications: by WooCommerce – 1.2.18
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.1.2
WooCommerce Dropshipping: by WooCommerce – 1.2.23 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.30
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.10
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.18
WooCommerce USPS Shipping: by WooCommerce – 4.4.35

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 2
Custom formats: 0
Next export: Not scheduled

### Action Scheduler ###

Complete: 84
Oldest: 2019-11-25 13:29:33 +0000
Newest: 2019-12-24 13:25:51 +0000

Pending: 4
Oldest: 2019-12-24 14:12:08 +0000
Newest: 2019-12-25 13:12:08 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment] 2019-12-24 15:44
Hi @jobthomas,

Thank you for reporting the issue! 

While I can reproduce it on my end, we don't have plans to work on the `Reports` section since it will soon be replaced by the [WooCommerce Admin](https://wordpress.org/plugins/woocommerce-admin/) plugin's `Reports` section which is currently a plugin but it will be merged to core and will be a part of core sometime in Q1/Q2 of 2020. 

I tested the same use case you provided in your report - the tax refunds work correctly in Reports in the WooCommerce Admin plugin. Documenting my steps for the records:

- Placed order with 2 products and tax each:

![tax1](https://user-images.githubusercontent.com/19143190/71418480-91069680-2662-11ea-82e3-2ecfc304036b.jpg)

- Issued a refund for one item (tax for that item got refunded as well):

![tax2](https://user-images.githubusercontent.com/19143190/71418531-d3c86e80-2662-11ea-85dc-613c7826d405.jpg)

- Checked **Reports > Taxes > Taxes by date:** correct:

![tax3](https://user-images.githubusercontent.com/19143190/71418612-3faad700-2663-11ea-8ccf-9fe8e85d5d8d.jpg)

- Checked **Reports > Taxes > Taxes by code:** incorrect:

![tax4](https://user-images.githubusercontent.com/19143190/71418642-60732c80-2663-11ea-9a88-a2c0809a1130.jpg)

- Checked **WooCommerce Admin > Analytics > Taxes:** correct:

![tax5](https://user-images.githubusercontent.com/19143190/71418697-a03a1400-2663-11ea-9438-dfc4f0fc65ee.jpg)

I am closing this issue since this is something we won't be working on. Sorry!

**Closed by juliaamosova** 2019-12-24 15:44 UTC
