### ISSUE TITLE
'Phone Field' in Checkout - cannot set 'required'

### ISSUE THREAD

**Issue by jazzerysav** [woocommerce/woocommerce#24933] opened 2019-10-30 12:05 UTC
Hi, within page editor, I can select 'hide' and 'optional' for 'Phone Field' but when I select 'required', the field still behaves as if 'optional'.

I need this to be a required field for courier purposes. Please help!
Thanks

**Comment by kloon** [comment] 2019-10-30 12:56
Hi @jazzerysav, I tested this with the lastest version and are unable to replicate this. When I set the field to required via the customizer I cannot checkout without entering a phone number, see my gif below

![](https://cld.wthms.co/KaTiAS+)

Since you left out your system status report it is hard to tell what the issue for you could be, but my guess would be your theme is overriding the templates and causing the issue for you. You could also have a plugin that is causing a conflict.

Please switch your theme to a default one like twentysventeen or Storefront and test again.

Closing as I am unable to reproduce this.

**Closed by kloon** 2019-10-30 12:56 UTC

**Comment by JimmyAppelt** [comment] 2019-11-13 14:53
@kloon I've found this happens when the plugin _WooCommerce PayPal Checkout Gateway_ is installed.
It has a setting on its own to 'require' the field, which interferes with the WC option in the customizer.
