### ISSUE TITLE
WC 4.0 issue causing another plugin to crash website

### ISSUE THREAD

**Issue by mackayjamesusa** [woocommerce/woocommerce#25886] opened 2020-03-11 19:28 UTC
**Describe the bug**
Upgraded to WooCommerce 4.0 today and in the WordPress error log gave the following message.

After upgrading WooCommerce I activated a plugin called Wicked Folders Pro.  The website had a Fatal Error.  I activated WooCommerce First then Wicked Folders.

I reached out to Wicked Folders and they said the error was coming from WooCommerce and sent me back this section of our error log.

[11-Mar-2020 15:31:04 UTC] PHP Fatal error:  Uncaught Exception: Invalid data store. in /home/facimorg/public_html/members/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107
Stack trace:
#0 /home/facimorg/public_html/members/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin')
#1 /home/facimorg/public_html/members/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(121): WC_Data_Store::load('admin-note')
#2 /home/facimorg/public_html/members/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(59): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name('wc-admin-deacti...')
#3 /home/facimorg/public_html/members/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Deactivate_Plugin::delete_note()
#4 [internal function]: Automattic\WooCommerce\Admin\Composer\Package::init()
#5 /home/facimorg/public_html/members/wp-content/plugins/woocommerce/src/Pac in /home/facimorg/public_html/members/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 107

**Comment by rrennick** [comment] 2020-03-11 19:59
@mackayjamesusa Thanks for the report. The issue is being addressed in https://github.com/woocommerce/woocommerce-admin/issues/3869 so I will close this one.

**Closed by rrennick** 2020-03-11 19:59 UTC

**Comment by mackayjamesusa** [comment] 2020-03-11 22:42
> @mackayjamesusa Thanks for the report. The issue is being addressed in [woocommerce/woocommerce-admin#3869](https://github.com/woocommerce/woocommerce-admin/issues/3869) so I will close this one.

Thank you for letting me know.  Will look forward to upcoming release.
