### ISSUE TITLE
Rest API keys not generated

### ISSUE THREAD

**Issue by michaldang** [woocommerce/woocommerce#21827] opened 2018-11-06 13:30 UTC
I can not generate API Keys. Everything is enabled and some of my previously generated keys work. Adding a new key stopped working in 3.3.1 version of WooCommerce. Expecting the keys and the QR code to show up, there was a message "Settings saved". After updating to 3.5.1, the message is not there, it seems like the page just refreshes after trying to generate the keys. The text fields are blank but nothing is generated/shown. The problem is there no matter how hard I try.

My steps:
1. Go to 'WooCommerce -> Settings'
2. Click on 'Advanced'
3. Click on 'Rest API'
4. Insert description, user and Read/Write

I expected generated keys to show up including the QR code. I am sure I have the Rest API enabled as some of the previously generated keys work.

I am using the latest version of WooCommerce and Wordpress.

**Comment by rodrigoprimo** [comment] 2018-11-06 21:38
I was not able to reproduce this issue. I can generate new Rest API keys on WC 3.5.1. Are you testing this on a clean WP install with only WooCommerce active to rule out plugin conflicts? Do you get any errors in your PHP error log when you try to generate new keys?

**Comment by kloon** [comment] 2018-11-15 09:35
Closing due to no feedback and not able to replicate.

**Closed by kloon** 2018-11-15 09:35 UTC
Labels: status: needs feedback
