### ISSUE TITLE
The author of the product receives mail

### ISSUE THREAD

**Issue by MOSHE1111** [woocommerce/woocommerce#29010] opened 2021-02-03 09:53 UTC
I am currently creating a new add-on for a multi-vendor store, and I would like the new order to be sent dynamically to the author of the post. I did not find a variable in the of official software variables that is responsible for the author post of the product type post. Can I use this code for this purpose?
`<?php
global $post, $product;
$author_email = get_the_author_meta( 'user_email', $product->post->post_author );
return $author_email;
?>`

**Comment by MOSHE1111** [comment] 2021-02-03 10:19
I saw a code that can help here.
https://toolset.com/forums/topic/add-product-author-email-in-the-order/
I personally could not let him work.
I'd be happy if anyone here can explain to me how to do that.

**Comment by juliaamosova** [comment] 2021-02-03 20:29
Hi @MOSHE1111,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-02-03 20:29 UTC
