### ISSUE TITLE
Misalignment on Product Listing Page

### ISSUE THREAD

**Issue by JeremaineJohnson** [woocommerce/woocommerce#26472] opened 2020-05-12 17:53 UTC
On the product listing page, there tends to be some misalignment on the page. Very strange. Have you seen this before? 

http://www.syncterfacemedia.com/bookstore/page/2/

![image](https://user-images.githubusercontent.com/39373122/81728046-bc5b1800-9481-11ea-8412-32b1f9776448.png)

**Comment by juliaamosova** [comment] 2020-05-12 18:16
Hi @JeremaineJohnson,

Thank you for raising the issue. 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-05-19 15:08
Hi @JeremaineJohnson,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-05-19 15:08 UTC
Labels: status: needs feedback
