### ISSUE TITLE
flexslide bug causing variable product selection price misfire. 

### ISSUE THREAD

**Issue by Rivmedia** [woocommerce/woocommerce#25045] opened 2019-11-14 22:02 UTC
**Describe the bug**
Problem when 2 global variables are setup in a product,   it doesnt trigger the display of the price.   This seems to be related when flexslide has only 1 thumbnail and you click it - you get JS error. https://i.imgur.com/8cwhoQV.gifv 

Which seems to effect various problems ( such as the variable products not working properly in some instances.  All other errors can be based on this one (like in out case)

**Comment by juliaamosova** [comment] 2019-11-18 12:12
Hi @Rivmedia,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. 

From the short description you provided, it looks like there are 2 issues:

1) Related to product price with variations;
2) Related to JS error when hovering over the product image thumbnail. 

So far, the type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). **If you confirm the bug on your end, please provide us with clear steps to reproduce the issue.** 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-11-18 12:12 UTC
