### ISSUE TITLE
If product is virtual, shipping content dosn't hide

### ISSUE THREAD

**Issue by dangereyes88** [woocommerce/woocommerce#27574] opened 2020-09-03 10:38 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Product data section (add new product page) page, if shipping tab is selected, and you click on virtual tab. Shipping tab will hide, but shipping content section will remain open.

**Expected behavior**
If shipping tab is selected, and you click on virtual tab, it should switch to General tab (First Tab).

**Actual behavior**
Shipping tab hides, no tab is selected but Shipping tab content section still showing

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Add new product.
2. Scroll down to Product data section.
3. Click on Shipping tab, then click virtual checkbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/27726982/92103307-329cd500-edf9-11ea-9b13-f74ed52c1c7e.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-09-03 21:14
Hi @dangereyes88 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![](http://g.recordit.co/XbdnVm0wsD.gif) 

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by Knyazevich** [comment] 2020-10-06 01:39
@dangereyes88

Working on it.

**Comment by rodrigoprimo** [comment] 2020-12-05 18:34
Closing as this was fixed in #28414.

**Closed by rodrigoprimo** 2020-12-05 18:34 UTC
Labels: bug, component: shipping, has pull request, priority: low
