### ISSUE TITLE
Attribute sort order inconsistent after update from 3.5.X

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#23492] opened 2019-04-24 15:47 UTC
**Describe the bug**
After updating from a previous version of WooCommerce, my attribute sort order is no longer respected

**To Reproduce**
1. On a fresh install of WooCommerce 3.5.8, configure an attribute like this:
![see screen shot](https://cld.wthms.co/kxEmyZ+)
2. Configure some terms for that attribute:
![see screen shot](https://cld.wthms.co/AMSEvB+)
2. Create a variable product to use those attributes:
![see screen shot](https://cld.wthms.co/JWEEc5+)
3. View the product on the frontend, see that the attributes are in the order expected:
![see screen shot](https://cld.wthms.co/SqUONr+)
4. Update to WooCommerce 3.6.1 and complete all database updates. After all updates have completed, revisit the imported product. The attribute sort order has changed :(
![see screen shot](https://cld.wthms.co/GNxxp9+)

**Expected behavior**
For my attribute sorting to remain intact.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://att-sort-order-test-site.local
Site address (URL): http://att-sort-order-test-site.local
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.10MB
Database Data Size: 2.16MB
Database Index Size: 0.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.02MB
wp_postmeta: Data: 0.05MB + Index: 0.03MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 2
page: 6
post: 2
product: 1
product_variation: 4
scheduled-action: 54

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 53
Oldest: 2019-04-24 15:39:32 +0000
Newest: 2019-04-24 15:41:44 +0000

Pending: 1
Oldest: 2019-05-01 15:39:32 +0000
Newest: 2019-05-01 15:39:32 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by mikejolley** [comment] 2019-04-24 15:57
With that setup, I get incorrect sorting on both release/3.5 and release/3.6 branches. There are passing unit tests for name_num sorting in 3.6.2.

I'm pretty sure it's because you're applying numeric sorting to a non number - the # is throwing it off. In this use-case you'd need to resort to the manual drag and drop sorting for it to work in a reliable way.

**Comment by or128** [comment] 2019-04-25 11:31
Yes, I suffer from the same issue.
After updating to WC 3.6.1 my terms' order changed, is would seem that Name (numeric) Default sort order is broken on 3.6.1.

**Comment by mikejolley** [comment] 2019-04-25 13:29
If it were broken, the unit test for numeric sort would be failing too. But that appears working.

What are your term names? Are they numbers or strings like in this issue? That is not numeric data so the sort order won't be reliable..

**Comment by or128** [comment] 2019-04-27 14:38
> If it were broken, the unit test for numeric sort would be failing too. But that appears working.
> 
> What are your term names? Are they numbers or strings like in this issue? That is not numeric data so the sort order won't be reliable..

You can check it out here: https://www.japanese-knives.co.il/product/hikari-whetstones/
It's sorted manually now, since selecting Name (numeric) would result in something that looks random. It broke after 3.6.1.

**Comment by mikejolley** [comment] 2019-05-07 09:40
Right, it's the non-numeric hashes. These are not numeric strings.

**Comment by kloon** [comment] 2019-05-22 08:28
The only thing that changed with the term sorting was moved to using the default WP hook get_terms_defaults for determining defaults.

That said if you apply numeric sorting the #'s will through it out since those are at the beginning and then it is seen as a string.

Closing as this is not a bug but how numeric sorting works, that is why we have other sorting options available to utilise.

**Closed by kloon** 2019-05-22 08:28 UTC
Labels: status: needs feedback
