### ISSUE TITLE
No Error Messages in Login & Register

### ISSUE THREAD

**Issue by imapious** [woocommerce/woocommerce#25941] opened 2020-03-17 00:45 UTC
**Describe the bug**
Hi, I just updated my woocommerce to V 4.0.0 and found out that there is no Error messages being displayed when trying to submit in register & login with no value in the fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/32483941/76811165-8ad02280-682b-11ea-9dcf-66e0d6b91975.png)

**Expected behavior**
There should be error message on top of the form

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://pilmicoordering.dice205.asia
Site address (URL): https://pilmicoordering.dice205.asia
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.1
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Amazon) OpenSSL/1.0.2k-fips PHP/7.1.33
PHP Version: 7.1.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 GB
PHP Time Limit: 30000
PHP Max Input Vars: 1000
cURL Version: 7.53.1
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.31-MariaDB
Max Upload Size: 8 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: s2lt0_
Total Database Size: 30.04MB
Database Data Size: 26.19MB
Database Index Size: 3.85MB
s2lt0_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
s2lt0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
s2lt0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
s2lt0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
s2lt0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s2lt0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s2lt0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_actionscheduler_actions: Data: 0.23MB + Index: 0.14MB + Engine InnoDB
s2lt0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_actionscheduler_logs: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
s2lt0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
s2lt0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s2lt0_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s2lt0_options: Data: 3.03MB + Index: 0.08MB + Engine InnoDB
s2lt0_postmeta: Data: 2.48MB + Index: 0.66MB + Engine InnoDB
s2lt0_posts: Data: 14.23MB + Index: 0.25MB + Engine InnoDB
s2lt0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_usermeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
s2lt0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
s2lt0_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s2lt0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s2lt0_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
s2lt0_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
s2lt0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s2lt0_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
s2lt0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s2lt0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 128
custom_css: 3
customize_changeset: 3
et_footer_layout: 3
et_header_layout: 12
et_pb_layout: 37
et_template: 25
et_theme_builder: 5
nav_menu_item: 6
page: 12
post: 21
product: 93
revision: 697
shop_coupon: 19
shop_order: 91

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Default featured image: by Jan Willem Oostendorp – 1.6.1
Woo Tabbed Category Product Listing: by QuantumCloud – 2.2.1 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 1.0.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.20 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.19
WP WooCommerce Mailchimp: by Saint Systems – 2.3.10 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 4.0.0

### Inactive Plugins (3) ###

Bloom: by Elegant Themes – 1.3.10
Union Bank Pay: by Team WP –
WooCommerce Dragonpay: by Denns P – 2.0 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: PHP (₱)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #44 - /shops/
Cart: #76 - /cart/
Checkout: #78 - /checkout/
My account: #84 - /my-account/
Terms and conditions: #82 - /terms-and-condition/

### Theme ###

Name: My Child Theme
Version: 1.0.1
Author URL: http://link%20to%20your%20website
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.0.11
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 556
Oldest: 2020-02-15 12:25:25 +0800
Newest: 2020-03-17 08:05:26 +0800

Pending: 2
Oldest: 2020-03-17 09:05:26 +0800
Newest: 2020-03-17 09:05:26 +0800

`
```
</details>

**Comment by mohitmishra-cedcoss** [comment] 2020-03-17 06:29
Hello, @imapious I have checked your issue and everything is working at my end.I think you are using the Divi theme that's why you are not getting this error. Please switch to the storefront updated version. Then everything is works well.

**Comment by tammullen** [comment] 2020-03-17 09:27
​Hi @imapious 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

I believe @mohitmishra-cedcoss is correct that is is related to the theme you are using.

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-03-23 20:04
Hi @imapious,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-03-23 20:04 UTC
Labels: can't reproduce, status: needs feedback
