### ISSUE TITLE
woocommerce_api_create_coupon hook is not working

### ISSUE THREAD

**Issue by himanshuahuja96** [woocommerce/woocommerce#25631] opened 2020-02-11 10:02 UTC
**Describe the bug**
I am trying to attach a product to the coupon created using restapi using the woocommerce_api_create_coupon, but it doesn't seem to be working.

**To Reproduce**
function fun_logg_funtion_wccoupon($id, $data){
    $addThisProduct = 8753;    
    update_post_meta( $id, 'product_ids', $addThisProduct );
}
add_action('woocommerce_api_create_coupon','fun_logg_funtion_wccoupon', 10, 2);

**Expected behavior**
It should attach the product to the coupon which are created using rest API.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): #
Site address (URL): #
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.26
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.46-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: wp_
Total Database Size: 17.16MB
Database Data Size: 14.37MB
Database Index Size: 2.79MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.30MB + Index: 0.09MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.21MB + Index: 0.13MB + Engine MyISAM
wp_acym_action: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acym_automation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_campaign: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acym_condition: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acym_configuration: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_list: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_acym_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_mail_has_list: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_acym_mail_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_queue: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_acym_rule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_step: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acym_tag: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acym_url_click: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acym_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acym_user_has_field: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_acym_user_has_list: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_acym_user_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.24MB + Index: 0.19MB + Engine MyISAM
wp_esign_documents: Data: 1.15MB + Index: 0.02MB + Engine MyISAM
wp_esign_documents_events: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_esign_documents_fields_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_esign_documents_meta: Data: 0.18MB + Index: 0.05MB + Engine MyISAM
wp_esign_documents_signatures: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
wp_esign_documents_signer_field_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_esign_documents_stand_alone_docs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_esign_document_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_esign_invitations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_esign_settings: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_esign_signatures: Data: 0.10MB + Index: 0.00MB + Engine MyISAM
wp_esign_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gens_raf: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gens_rafmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_giftvouchers_activity: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_giftvouchers_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_giftvouchers_setting: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_giftvouchers_template: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_imagify_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_imagify_folders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_optimizepress_assets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_optimizepress_launchfunnels: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_optimizepress_launchfunnels_pages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_optimizepress_layout_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_optimizepress_pb_products: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_optimizepress_post_layouts: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_optimizepress_predefined_layouts: Data: 0.46MB + Index: 0.00MB + Engine MyISAM
wp_optimizepress_presets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.71MB + Index: 0.25MB + Engine MyISAM
wp_p2p: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_p2pmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta: Data: 1.65MB + Index: 0.27MB + Engine MyISAM
wp_posts: Data: 1.04MB + Index: 0.22MB + Engine MyISAM
wp_rio_process_queue: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wp_sbi_instagram_feeds_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sbi_instagram_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_social_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_strong_views: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_um_metadata: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.20MB + Index: 0.10MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_w3tc_cdn_pathmap: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcs_payment_retries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfConfig: Data: 0.36MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 2.01MB + Index: 0.30MB + Engine MyISAM
wp_wfHits: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 1.06MB + Index: 0.13MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.15MB + Index: 0.06MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_entries: Data: 0.14MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_entry_fields: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_wpforms_entry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url_mail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.12MB + Index: 0.13MB + Engine MyISAM

### Post Type Counts ###

achievement-type: 2
attachment: 289
badgeos-log-entry: 47
custom_css: 2
customize_changeset: 8
GOTMLS_quarantine: 2
intergeo: 1
jetpack_migration: 2
logosliderwp: 14
nav_menu_item: 31
oembed_cache: 14
omg-digital-badge: 4
page: 45
post: 7
product: 21
product_variation: 19
revision: 200
shop_coupon: 14
shop_order: 36
shop_subscription: 6
um_directory: 1
um_form: 6
um_social_login: 1
wp-rest-api-log: 29
wpforms: 3
wpgv_voucher_product: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

ManageWP - Worker: by GoDaddy – 4.9.2
Autocomplete WooCommerce Orders: by Liam McArthur – 1.1.0 – Not tested with the active version of WooCommerce
Autoptimize: by Frank Goossens (futtta) – 2.6.1
Classic Editor: by WordPress Contributors – 1.5
WP E-Signature Business add-ons: by Approve Me – 1.5.4.9
WP E-Signature: by Approve Me – 1.5.5.3
Gift Up!: by Gift Up! – 1.4.1 – Not tested with the active version of WooCommerce
GiftUp Customizations Om: by WebiLabs – 1.0.0
Smash Balloon Instagram Feed: by Smash Balloon – 2.2
Limit Login Attempts Reloaded: by WPChef – 2.10.0
Logo Slider WP: by LogicHunt – 1.3.4
OMGuarantee: by  – 1.0
OptimizePress: by OptimizePress – 2.5.23
Image optimization service by Optimole: by Optimole – 2.2.8
Product Visibility by User Role for WooCommerce: by WP Wham – 1.5.2 – Not tested with the active version of WooCommerce
Webcraftic Robin image optimizer: by Webcraftic  – 1.4.2
Lazy Load by WP Rocket: by WP Rocket – 12.3.2
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.23
Orbit Fox Companion: by Themeisle – 2.9.1
Ultimate Member: by Ultimate Member – 2.1.3
Ultimate Member - Social Login: by Ultimate Member – 2.3.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.21

Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.0 – Not tested with the active version of WooCommerce
Amazon Pay WooCommerce payment gateway: by Subhadeep Mondal – 2.9 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.25.1
WP E-Signature - WooCommerce: by Approve Me – 1.5.5.3 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by WooCommerce – 3.0.1
WooCommerce: by Automattic – 3.9.1
Yoast SEO: by Team Yoast – 13.0
WP Forms Signature Contract Add-on: by Approve Me – 1.5.5.3
WP Staging: by WP-Staging – 2.6.8
WP Super Cache: by Automattic – 1.7.1
WPForms Custom Captcha: by WPForms – 1.3.0
WPForms: by WPForms – 1.5.8.2
Refer a Friend for WooCommerce PREMIUM: by WPGens – 2.3.9

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Imagify: by WP Media – 1.9.8.1
Nextend Social Login: by Nextendweb – 3.0.20
Refer A Friend for WooCommerce by WPGens: by Goran Jakovljevic – 1.1.9 – Not tested with the active version of WooCommerce
REST API Log: by Pete Nelson – 1.6.7
Search & Replace: by Inpsyde GmbH – 3.2.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

installatron_hide_status_test.php: by  –
ManageWP - Worker Loader: by GoDaddy –
WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: donation (donation)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #381 - /purchase-omgs/
Cart: #385 - /cart/
Checkout: #387 - /checkout/
My account: #400 - /account/
Terms and conditions: #905 - /omg-agreement-terms-and-conditions/

### Theme ###

Name: ShopIsle PRO
Version: 2.2.52
Author URL: https://themeisle.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: shop-isle-pro/woocommerce/emails/customer-completed-order.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: #
Subscription Statuses: wc-active: 5
wc-on-hold: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 5
wc-on-hold: 1


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

PayPal: subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_delayed_change
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ✔ Yes
Direct bank transfer: products
Amazon Pay PluginStar: refunds
Stripe Alipay: products
refunds


### Action Scheduler ###

Complete: 799
Oldest: 2020-01-11 05:28:16 -0500
Newest: 2020-02-11 04:47:41 -0500

Pending: 7
Oldest: 2020-02-11 05:47:41 -0500
Newest: 2020-02-29 03:00:00 -0500

````
</details>

**Comment by claudiosanches** [comment] 2020-04-29 22:04
Hi @himanshuahuja96,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-04-29 22:04 UTC
