### ISSUE TITLE
font-family generated after the "style" tag is closed on email headers

### ISSUE THREAD

**Issue by regisramillien** [woocommerce/woocommerce#20733] opened 2018-07-09 14:08 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Send an email with woocommerce (email template for instance)
2. Watch the source HTML on <H1 style="..." helvetica>

## Expected/actual behavior

When I follow those steps, I see  that font is not defined in the style tag but just after it (after quote but before closing '>'
style="display: inline-block; color: #ffffff; font-family: " helvetica>Modèle d’e-mail HTML

I was expecting to see.
style="display: inline-block; color: #ffffff; font-family: helvetica">Modèle d’e-mail HTML

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://s581942976.onlinehome.fr
Site URL: http://s581942976.onlinehome.fr
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.6
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0+deb7u1 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: storemigration_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 23.94MB
Taille de la base de données: 22.00MB
Taille de l’index: 1.94MB
storemigration_woocommerce_sessions: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_api_keys: Données : 0.02MB + Index: 0.03MB
storemigration_woocommerce_attribute_taxonomies: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index: 0.05MB
storemigration_woocommerce_order_items: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_order_itemmeta: Données : 0.08MB + Index: 0.03MB
storemigration_woocommerce_tax_rates: Données : 0.02MB + Index: 0.06MB
storemigration_woocommerce_tax_rate_locations: Données : 0.02MB + Index: 0.03MB
storemigration_woocommerce_shipping_zones: Données : 0.02MB + Index: 0.00MB
storemigration_woocommerce_shipping_zone_locations: Données : 0.02MB + Index: 0.03MB
storemigration_woocommerce_shipping_zone_methods: Données : 0.02MB + Index: 0.00MB
storemigration_woocommerce_payment_tokens: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_payment_tokenmeta: Données : 0.02MB + Index: 0.03MB
storemigration_woocommerce_log: Données : 0.02MB + Index: 0.02MB
storemigration_commentmeta: Données : 0.02MB + Index: 0.03MB
storemigration_comments: Données : 0.05MB + Index: 0.09MB
storemigration_links: Données : 0.02MB + Index: 0.02MB
storemigration_options: Données : 3.13MB + Index: 0.06MB
storemigration_popup_country_d: Données : 0.02MB + Index: 0.02MB
storemigration_popup_form_results: Données : 0.02MB + Index: 0.00MB
storemigration_popup_meta: Données : 0.02MB + Index: 0.00MB
storemigration_popup_visits: Données : 0.02MB + Index: 0.00MB
storemigration_popup_windows: Données : 0.02MB + Index: 0.00MB
storemigration_postmeta: Données : 1.52MB + Index: 0.47MB
storemigration_posts: Données : 14.42MB + Index: 0.36MB
storemigration_quform_entries: Données : 0.02MB + Index: 0.03MB
storemigration_quform_entry_data: Données : 0.02MB + Index: 0.02MB
storemigration_quform_entry_entry_labels: Données : 0.02MB + Index: 0.02MB
storemigration_quform_entry_labels: Données : 0.02MB + Index: 0.02MB
storemigration_quform_forms: Données : 0.05MB + Index: 0.03MB
storemigration_quform_sessions: Données : 0.02MB + Index: 0.00MB
storemigration_revslider_css: Données : 0.13MB + Index: 0.00MB
storemigration_revslider_layer_animations: Données : 0.02MB + Index: 0.00MB
storemigration_revslider_navigations: Données : 0.02MB + Index: 0.00MB
storemigration_revslider_sliders: Données : 0.03MB + Index: 0.00MB
storemigration_revslider_slides: Données : 0.11MB + Index: 0.00MB
storemigration_revslider_static_slides: Données : 0.02MB + Index: 0.00MB
storemigration_termmeta: Données : 0.02MB + Index: 0.03MB
storemigration_terms: Données : 0.06MB + Index: 0.03MB
storemigration_term_relationships: Données : 0.02MB + Index: 0.02MB
storemigration_term_taxonomy: Données : 0.06MB + Index: 0.06MB
storemigration_usermeta: Données : 0.11MB + Index: 0.03MB
storemigration_users: Données : 0.02MB + Index: 0.05MB
storemigration_vtprd_purchase_log: Données : 0.02MB + Index: 0.02MB
storemigration_vtprd_purchase_log_product: Données : 0.02MB + Index: 0.02MB
storemigration_vtprd_purchase_log_product_rule: Données : 0.02MB + Index: 0.02MB
storemigration_wc_download_log: Données : 0.02MB + Index: 0.03MB
storemigration_wc_webhooks: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_sogenactifcw_customer_contexts: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_sogenactifcw_documents: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_sogenactifcw_ecc: Données : 0.02MB + Index: 0.00MB
storemigration_woocommerce_sogenactifcw_schema_version: Données : 0.02MB + Index: 0.02MB
storemigration_woocommerce_sogenactifcw_storage: Données : 0.02MB + Index: 0.00MB
storemigration_woocommerce_sogenactifcw_transactions: Données : 1.36MB + Index: 0.00MB
storemigration_yoast_seo_links: Données : 0.02MB + Index: 0.02MB
storemigration_yoast_seo_meta: Données : 0.05MB + Index: 0.00MB

### Post Type Counts ###

attachment: 90
custom_css: 1
customize_changeset: 306
jetpack_migration: 2
nav_menu_item: 10
page: 47
post: 2
product: 6
product_variation: 2
revision: 1283
shop_coupon: 28
shop_order: 16
us_footer: 1
us_grid_layout: 5
us_header: 3
vtprd-rule: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (25) ###

BackupBuddy: par iThemes – 8.2.7.0
Contact Form 7: par Takayuki Miyoshi – 5.0.2
Cookie Notice: par dFactory – 1.2.44
Enable Media Replace: par ShortPixel – 3.2.6
Head, Footer and Post Injections: par Stefano Lissa – 3.1.1
Hotjar Connecticator: par Blue Medicine Labs – 1.1.1
Indeed Smart PopUp: par indeed – 4.8
iThemes Sync: par iThemes – 2.0.9
Éditeur de page: par Michael M - WPBakery.com – 5.4.7
Loco Translate: par Tim Whitlock – 2.1.4
Mailjet for Wordpress: par Mailjet SAS – 4.3.0
NK Google Analytics: par Manfred Rodríguez – 1.4.15
Slider Revolution: par ThemePunch – 5.4.8
Header Builder: par UpSolution – 2.1.1
WooCommerce Address Book: par Hall Internet Marketing – 1.3.6 – Non testé avec la version active de WooCommerce
WooCommerce Alloga: par biose – 1.0.0-alpha – Non testé avec la version active de WooCommerce
WooCommerce Extended Coupon Features PRO: par Soft79 – 2.6.2 – Non testé avec la version active de WooCommerce
WooCommerce Export: par biose – 1.0.0-alpha – Non testé avec la version active de WooCommerce
WooCommerce PDF Invoices: par Andrew Benbow – 4.1.9 – Non testé avec la version active de WooCommerce
WooCommerce Sponsorship: par biose – 1.0.0-alpha – Non testé avec la version active de WooCommerce
WooCommerce: par Automattic – 3.4.3
WooCommerce SogenactifCw: par customweb GmbH – 1.0.112 – Non testé avec la version active de WooCommerce
Yoast SEO Premium: par L’équipe Yoast – 7.4.2
WPS Hide Login: par WPServeur
NicolasKulka
tabrisrp – 1.3.4.2

Yoast SEO : WooCommerce: par L’équipe Yoast – 7.4 – Non testé avec la version active de WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base boutique: #673 - /boutique
Panier: #49 - /panier
Validation de la commande: #50 - /commande
Mon compte: ❌ La page ne contient pas le code court.
Conditions générales de vente et d’utilisation: #207 - /cgv

### Theme ###

Name: Impreza Child
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Impreza
Parent Theme Version: 5.1
Parent Theme Author URL: http://us-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: Impreza-child/woocommerce/archive-product.php version 3.3.0 est obsolète. La version du noyau est 3.4.0
Impreza-child/woocommerce/checkout/thankyou.php
Impreza-child/woocommerce/content-single-product.php version - est obsolète. La version du noyau est 3.4.0
Impreza-child/woocommerce/single-product/add-to-cart/variable.php version 3.0.0 est obsolète. La version du noyau est 3.4.1
Impreza-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.0.0 est obsolète. La version du noyau est 3.4.0
Impreza-child/woocommerce/single-product/add-to-cart/variation.php
Impreza-child/woocommerce/single-product/price.php
Impreza-child/woocommerce/single-product/rating.php
Impreza-child/woocommerce/single-product/tabs/tabs.php
Impreza-child/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour
`
</details>

**Comment by claudiulodro** [comment] 2018-07-10 20:08
Hi there,

I was not able to reproduce it on a site running only WooCommerce:

`<h1 style='color: #ffffff; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 30px; font-weight: 300; line-height: 150%; margin: 0; text-align: left; text-shadow: 0 1px 0 #ab79a1;'>HTML email template</h1>`

It is most likely because of the bug in issue #20707, in which case there is a patch available in #20723 which you can apply manually now if you're comfortable with that. Otherwise the patch will be included in WC 3.4.4.

If the patch does not solve the issue for you, I see at least one mail plugin active in the system status report and some other plugins that could potentially cause the problem. I suggest trying without other plugins active and seeing if the problem still happens.

Hope this helps. Thanks.

**Closed by claudiulodro** 2018-07-10 20:08 UTC
