### ISSUE TITLE
[GlobalStep] "Missing Dependencies" error is displayed upon login WPENGINE TEST SITE under Scripts section

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26684] opened 2020-06-03 15:28 UTC
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:**
1. Go to "http://wpe.testwc.com/wp-login.php"
2. Login using valid credential.
3. Tap on Query Monitor.
4. Observe that Scripts error stating "Missing Dependencies" is displayed.

**Actual Result:**
"Missing Dependencies" error is displayed upon login WPENGINE TEST SITE under Scripts section.

**Expected Result:**
No error message should be displayed.

![#2620](https://user-images.githubusercontent.com/41110392/83656326-05177400-a5dd-11ea-9f0d-f40deec9236f.png)

**Comment by nerrad** [comment] 2020-06-03 21:30
@juliaamosova if memory serves me correctly, I think WPEngine disables WP heartbeat on all routes except specific ones. If that's still the case, that's probably the cause here.

**Comment by juliaamosova** [comment] 2020-06-05 18:04
Thanks @nerrad! I reached out to WP Engine via live chat and confirmed that the Heartbeat being disabled is indeed expected. Quoting WP Engine support agent below:

>Alright! So the two main updates that we've had with our Heartbeat Control is we throttle the heartbeat rate from the default 15 seconds down to every 60 seconds. And we've also disabled the Heartbeat script entirely on non-editing pages. The screenshot you've sent me is a non-editing page which would be the reason why it's showing as missing. 

I was also offered to have the Heartbeat disabled on non-editing pages but declined since this is a test site. It is good to know that we can have it enabled if needed though. 

Closing this as a non-issue.

**Closed by juliaamosova** 2020-06-05 18:04 UTC
