### ISSUE TITLE
Inventory synchronization help?

### ISSUE THREAD

**Issue by hqin2013** [woocommerce/woocommerce#26702] opened 2020-06-05 00:41 UTC
Hey,

I'm building a WooCommerce online store, which needs Inventory synchronization from another place.

I search in [stackoverflow.com](https://stackoverflow.com/questions/51940338/updating-product-stock-programmatically-in-woocommerce-3),get these codes:

```
$out_of_stock_staus = 'outofstock';

// 1. Updating the stock quantity
update_post_meta($product_id, '_stock', 0);

// 2. Updating the stock quantity
update_post_meta( $product_id, '_stock_status', wc_clean( $out_of_stock_staus ) );

// 3. Updating post term relationship
wp_set_post_terms( $product_id, 'outofstock', 'product_visibility', true );

// And finally (optionally if needed)
wc_delete_product_transients( $product_id );
```

But after testing, not work in WooCommerce 4.X(these codes work in WC3), any suggestion?!

Thank you for help
Qin

**Comment by tammullen** [comment] 2020-06-05 10:14
Hi @hqin2013 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-06-05 10:14 UTC
