### ISSUE TITLE
Crash when applying coupon to order with deleted product

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#27077] opened 2020-07-20 09:08 UTC
**Prerequisites:**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When manually adding a coupon to an order in which there is at least one product that was deleted from the WC Product database, WC crashes/hangs, with the following stack trace:

> PHP Fatal error:  Uncaught Error: Call to a member function is_type() on bool in \wp-content\plugins\woocommerce\includes\class-wc-coupon.php:864
Stack trace:
> 1. \wp-content\plugins\woocommerce\includes\class-wc-discounts.php(327): WC_Coupon->is_valid_for_product(false, Object(WC_Order_Item_Product))
> 2. \wp-content\plugins\woocommerce\includes\class-wc-discounts.php(260): WC_Discounts->get_items_to_apply_coupon(Object(WC_Coupon))
> 3. \wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-order.php(1130): WC_Discounts->apply_coupon(Object(WC_Coupon))
> 4. \wp-content\plugins\woocommerce\includes\class-wc-ajax.php(1153): WC_Abstract_Order->apply_coupon('10')
> 5. \wp-includes\class-wp-hook.php(287): WC_AJAX::add_coupon_discount('')
> 6. \wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> 7. \wp-includes\p in \wp-content\plugins\woocommerce\includes\class-wc-coupon.php on line 864

**Expected behavior**
Coupon should be applied and product check on manual product should be skipped

**Actual behavior**
Coupon is not applied, WC backend shows infinite spinner

**Steps to reproduce the bug**
Steps to reproduce the bug:
1. Create a new order (frontend or backend), adding 2 or more products
2. Delete one of the products in the order from the WC products (permanently)
3. Go to the order and click 'Apply coupon'
4. WC hangs

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WC 4.3.0
WP 5.4.3

**Comment by juliaamosova** [comment] 2020-08-03 20:09
Hi @Spreeuw,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I tested using the following:

- WC 4.3.1 + WP 5.4.2
- WC 4.4. beta1 + WP 5.4.2
- WC 4.4. beta1 + WP 5.5 rc1

In every case, I am getting the same successful results. 

Before applying the coupon (you can see that `Product 1` has no link - this is the product that had been deleted after the order was placed ):

![before](https://user-images.githubusercontent.com/19143190/89222641-663ed200-d5a3-11ea-8870-c45de09514a6.jpg)

Applied coupon but didn't save the order yet:

![during](https://user-images.githubusercontent.com/19143190/89222739-8a9aae80-d5a3-11ea-9ffd-7d6e5501a554.jpg)

Saved the order and marked as `Completed`:

![after](https://user-images.githubusercontent.com/19143190/89222751-8ec6cc00-d5a3-11ea-8cef-7bfddd91adad.jpg)

The issue on your issue could be caused by a theme or plugins conflict. 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by Spreeuw** [comment] 2020-08-04 07:31
Thanks for testing. I did test with only WC + storefront. I think it is the type of coupon that makes the difference.
The line referred to in the error is this one:
https://github.com/woocommerce/woocommerce/blob/78eb69d30d8781078a08bc775dc9010ceafd4451/includes/class-wc-coupon.php#L864

Which is part of the method `is_valid_for_product`. This only performs that check if it is a product type discount:
https://github.com/woocommerce/woocommerce/blob/78eb69d30d8781078a08bc775dc9010ceafd4451/includes/class-wc-coupon.php#L859-L861

e.g. `fixed_product` or `percent`
https://github.com/woocommerce/woocommerce/blob/548b00c66000d39ca8ad67318dd64388ae03db7e/includes/wc-coupon-functions.php#L46-L48

What is the coupon type you used?

**Comment by YordanSoares** [comment] 2021-07-16 13:58
Hi @Spreeuw and @juliaamosova,

I'm having this same issue with `fixed_product` and `percent` discount types. I followed the steps above to reproduce this issue, and after adding the coupon, the order editing area stuck:

![wc-stucks](https://user-images.githubusercontent.com/38109855/125957804-ed917cf0-543f-454a-9bf3-d39493f97edc.gif)

And I got the same error that @Spreeuw mentioned:

![image](https://user-images.githubusercontent.com/38109855/125956739-5f198bc3-6cd0-4b45-b0cc-da7c2749e2b3.png)

Note: If you have only 1 or more products, and permanent delete them all, you won't receive this error, but a JavaScript notice:

![image](https://user-images.githubusercontent.com/38109855/125958703-a99a9ffe-e018-4060-a975-383928c56362.png)

This issue happens if you have at least 1 existing product and 1 deleted permanent product in the order.

**WordPress Environment**
- WordPress 5.7.2
- WooCommerce 5.5.1
- Storefront 3.7.0

**Comment by patrick-leb** [comment] 2021-07-16 17:27
I can confirm this is happening - on 5.5.1 - I was about to write a new ticket.

**Comment by AashikP** [comment] 2021-09-03 03:18
Thank you all for taking the time to report this bug. I can reproduce it on my end using WooCommerce 5.6. 

*I tested with `Fixed Product Discount` on a product that was deleted.*

![https://d.pr/i/29Kt9j+](https://d.pr/i/29Kt9j+)

(The product assignment for the coupon under **Edit Coupon > Usage Restriction > Products >** was removed when I trashed and permanently deleted the product)

When I attempted to apply the coupon on the order after the product was deleted, the order page kept loading forever:

![https://d.pr/i/g5BaGI+](https://d.pr/i/g5BaGI+)

And there's a different Fatal Error recorded:

```
2021-09-03T03:10:08+00:00 CRITICAL Uncaught Error: Call to a member function get_parent_id() on bool in /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-discounts.php:744
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(993): WC_Discounts->validate_coupon_product_ids(Object(WC_Coupon))
#1 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(252): WC_Discounts->is_coupon_valid(Object(WC_Coupon))
#2 /srv/htdocs/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1132): WC_Discounts->apply_coupon(Object(WC_Coupon))
#3 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(1190): WC_Abstract_Order->apply_coupon('fixed_product')
#4 /wordpress/core/5.8/wp-includes/class-wp-hook.php(303): WC_AJAX::add_coupon_discount('')
#5 /wordpress/core/5.8/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#6 /wordpress/core/5.8/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#7 /wordpress/core/5.8/wp-admin/admin-ajax.php(187): do_action('wp_ajax_woocomm...')
#8 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-discounts.php on line 744
```

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by Sidsector9** [comment] 2023-04-19 03:53
@ObliviousHarmony @peterfabian I would like to work on this.

**Closed** 2024-04-05 10:53 UTC
Labels: type: bug, priority: high, focus: coupon, focus: data-store, plugin: woocommerce, Contributor Day - H1 2023, team: Proton
