### ISSUE TITLE
Woocommerce 3.5 keeps writing .htaccess file

### ISSUE THREAD

**Issue by AdnPix** [woocommerce/woocommerce#21688] opened 2018-10-26 10:17 UTC
**Describe the bug**
It seems that since we upgraded to woocommerce 3.5, the action scheduler running every minute is launching something which overwrites the .htaccess file every minute… and sometimes even emptying it.

We disabled all others plugins… same problem.

We disabled the theme... same problem.

Deactivating woocommerce plugin stops the overwriting.

We have no scheduled actions…

**Isolating the problem :**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

We are running WordPress 4.9.8 with Impreza theme 5.5.1
Woocommerce 3.5

**Comment by kloon** [comment] 2018-10-26 12:06
How sure are you that this is caused by Action Scheduler? I tried to replicate this now but am unable and I also checked the AS library and there is no code I could fine that will rewrite the htaccess file.

Usually this file is only rewritten when the permalinks are saved or when something in the code calls the [Rewrite API](https://codex.wordpress.org/Rewrite_API) This is done in WooCommerce at certain times, like when update WooCommerce to a new version, change attributes or make changes to any of the shop URLs.

By the sound of things you are confusing the WP Cron with the Action Scheduler, like I mentioned we do schedule a single event to run once you do an upgrade to a new version of WooCommerce and this is probably what is happening here, but your setup may have some weird behaviour.

Looking at the code it should only execute once, it can go into an infinite loop if there are issues retrieving the wc_installing transient, this could be caching related so start there, try and clear your caches on the host side, or if you have a plugin like WP Total cache try and disable that and remove the cache folder before proceeding.

**Comment by kloon** [comment] 2018-10-29 07:45
@AdnPix I am unable to replicate this locally. Yes the cron will fire every minute but it only does it to check if it should process any actions.

In no way is there an action tied to that event that will rewrite your htaccess file, I tested this several times now and cannot replicate this, so my only reasoning is you have something running where it should not be running that is rewriting the htaccess file, could be a plugin/theme running code on a hook that will fire on every page load.

Can you maybe test this on a different server to test if you can replicate this? Since I am unable to replicate it with the steps provided I cannot do much more.

I am closing the issue now, but if you can provide steps to replicate this on a different environment then I will gladly reopen and troubleshoot further.

**Closed by kloon** 2018-10-29 07:45 UTC
Labels: status: needs feedback

**Comment by AdnPix** [comment] 2018-10-29 08:08
i understand you closing the ticket but just to be clear... it happens with zero plugin except woocommerce and with wordpress twenty sixteen theme

**Comment by kloon** [comment] 2018-10-29 08:53
@AdnPix I understand, but please use my suggestion. As I said I was able to replicate it the mini-cart being out of sync somewhat, but that was due to the way I called the code, adding a later priority fixed it.

If you call your code on the correct hook and not just from your theme's functions.php file or a plugin then it will work fine, even just altering the priority can make it work again, unfortunately we cannot control the order in which plugins or other code loads, that is up the developers using the hooks to ensure their code is executed at the right time.

**Comment by AdnPix** [comment] 2018-10-29 08:59
I think your comment is not associated to this thread ;)

**Comment by kloon** [comment] 2018-10-29 09:15
You are right, sorry about that. What I meant to say is each environment is different. If I cannot recreate this locally I am unable to debug what the issue is. That is why as a last resort we will as people to test on a staging or development environment to confirm if they recreate and then provide the steps. We cannot fix issues we cannot recreate, there are so many factors that can contribute towards an issue.
