### ISSUE TITLE
Allow sale price to 23:59:59 on last sale date

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#22545] opened 2019-01-24 07:15 UTC
Version 3.5.4, you allow sale price to 23:59:59 on last sale date https://github.com/woocommerce/woocommerce/pull/22189. But you **+DAY_IN_SECONDS** when loading, not change **_sale_price_dates_to** when saving. Your change will cause problem with plugins and themes which use this setting for countdown. Also, there is a problem with cron **woocommerce_scheduled_sales**. It clears Sale Price, From Date, To Date if To Date is today.

**Comment by rrennick** [comment] 2019-01-24 11:32
This is a duplicate of this comment https://github.com/woocommerce/woocommerce/pull/22189#issuecomment-456324933 .

> not change _sale_price_dates_to when saving.

It would be confusing for users to pick Feb 1 as sales end date and have it return as Feb 2. In a brick & mortar store that is open 9AM - 9PM, if a sale runs from Monday to Friday, then the sales ends at 9PM Friday not 9AM Saturday morning. An online shop is open 24 hours but the sale still ends at the end of the day not at the beginning of the next day.

> there is a problem with cron woocommerce_scheduled_sales. It clears Sale Price, From Date, To Date if To Date is today.

@stormit if there is a bug related to this can you fill out the bug reporting template in a new issue.

**Comment by stormit** [comment] 2019-01-25 02:54
Hello @rrennick,

> not change _sale_price_dates_to when saving.

You might not understand what I mentioned. I mean you need to change **_sale_price_dates_to** (+DAY_IN_SECONDS) when saving. So, if Feb 1 is sale end date, **_sale_price_dates_to** should be 23:59:59 in Feb 1. Because in Feb 1, product still are discounted.

> there is a problem with cron woocommerce_scheduled_sales. It clears Sale Price, From Date, To Date if To Date is today.

I think this is easy to test. You just set Feb 1 as sale end date. In Feb 1, you go to your website. Cron **woocommerce_scheduled_sales** will run and clear Sale price. So, it does not show Sale price to the end of day as your change.

**Comment by rrennick** [comment] 2019-01-25 13:59
@stormit Thanks for the clarification. I'll look at this next week.

**Comment by stormit** [comment] 2019-01-31 13:50
Hello @rrennick,

Why didn't you add **DAY_IN_SECONDS** to **_sale_price_dates_to** when saving? I think it is easy and the best way. It won't also affect plugins and themes which use **_sale_price_dates_to** for count down as my said.

Best regards,

**Comment by rrennick** [comment] 2019-01-31 14:02
If you add DAY_IN_SECONDS to midnight you get midnight the next day.

**Comment by stormit** [comment] 2019-01-31 14:13
Hello @rrennick,

I still don't understand. Could you please explain more?

Currently, if you set To Date is 2 Feb, _sale_price_dates_to will be 00:00:00 in 2 Feb. But Sale Price still displays to 23:59:59. It is not reasonable. So, my recommendation is you should change _sale_price_dates_to to 23:59:59 in the last sale day. So, everything should be fine. You won't need to add DAY_IN_SECONDS when checking is on sale or cron. Plugins and themes which use _sale_price_dates_to for count down also work fine without changing anything.

Best regards,

**Comment by rrennick** [comment] 2019-02-05 14:46
@stormit There are 2 main reasons I implemented the fix with a calculation instead of changing what was stored in the database.

1. Changing what was stored in the database would have required an update routine to update all of the existing sales end dates. Even though this change would not be a compute intensive update, any DB update routine involves an amount of risk.

2. The UI for the end date field accept a date not a datetime. Doing this additional calculations allow continuing to store it as that date. Also, there could be many sites customized to add a time field to end the sale at some point during the day (ex. 5PM) that are adding the time to the date. Changing what is stored could break those customizations.

**Comment by stormit** [comment] 2019-02-13 04:29
Hello @rrennick,

1. I know it needs to update DB. But as I said: if you set To Date is 2 Feb, _sale_price_dates_to will be 00:00:00 in 2 Feb. But Sale Price still displays to 23:59:59. **It is not reasonable**. It is not uniformity and developer may be confused about this.

2. I don't know about this. But I'm sure that your current change will affect plugins and themes which use _sale_price_dates_to for countdown. I know many themes on themeforest are using this field for countdown.

**Comment by mikejolley** [comment] 2019-03-08 13:42
Adjusted in https://github.com/woocommerce/woocommerce/pull/22973 please review.

**Closed by mikejolley** 2019-03-08 13:42 UTC
Labels: bug, has pull request
