### ISSUE TITLE
Add-to-cart button still visible for out-of-stock variations

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#22032] opened 2018-11-24 09:24 UTC
**Describe the bug**

When a simple product is out of stock, the add to cart button is no longer visible. This is not the case with variable products, with variable products, the add to cart button is not clickable but still visible which makes for an inconsistent UI

Simple product:

![http://cld.wthms.co/9cf0I2](http://cld.wthms.co/9cf0I2+)
Link to image here: http://cld.wthms.co/9cf0I2.

Variable product:

![http://cld.wthms.co/UNMZSs](http://cld.wthms.co/UNMZSs+)
Link to image here: http://cld.wthms.co/UNMZSs.

**To Reproduce**

1. Have an out-of-stock simple and variable product
2. Check the frontend to see the differences

**Expected behavior**

Consistent UI.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment] 2018-12-10 08:29
I am unable to reproduce. I have a variation set to out of stock and then the option is hidden from the frontend.

Blue variation set to 0 stock http://cld.wthms.co/zxEd4b and on the frontend http://cld.wthms.co/9fSm3h

In your tests did you remember to select the manage stock option on the variation? http://cld.wthms.co/R0ieMD

Closing, can reopen when there are step to reproduce this.

**Closed by kloon** 2018-12-10 08:29 UTC

**Comment by jobthomas** [comment] 2018-12-10 09:34
Still able to reproduce @kloon with this specific config:

![http://cld.wthms.co/QtNV0b](http://cld.wthms.co/QtNV0b+)
Link to image here: http://cld.wthms.co/QtNV0b.

Result:

![http://cld.wthms.co/RljMyk](http://cld.wthms.co/RljMyk+)
Link to image here: http://cld.wthms.co/RljMyk.

**Comment by kloon** [comment] 2018-12-10 09:38
Ah, you probably have the hide out of stock option disabled on your store. WooCommerce -> Settings -> Products -> Inventory.

That is intended behavior and is controlled by that option in the settings.

**Comment by jobthomas** [comment] 2018-12-10 09:41
@kloon but shouldn't it react the same for simple and variable products then? For simple products the add to cart button is not visible when out of stock, but it is above for variable products? 

This issue is focusing on the inconsistent UI, not necessarily deciding what the best flow is. I really don't mind if the add to cart button is visible for simple products; it's that it's not the same across them.

**Comment by kloon** [comment] 2018-12-10 09:45
The reason it is visible is that you have multiple variations and some of them are available for purchase.  IMO hiding the button would be more confusing if you have variations available for purchase. Say your default variation is out of stock and you have the button, that would make it confusing for the user.

Variations and simple products are different types of products and as such, I do not think they have to have a consistent UI, it is similar but the UI already differs because of the options you need to choose.

**Comment by jobthomas** [comment] 2018-12-10 09:47
Cool. Happy to leave this closed then. Thanks for the feedback.
