### ISSUE TITLE
Coupon in Trash is still applied to live cart

### ISSUE THREAD

**Issue by JiveDig** [woocommerce/woocommerce#22052] opened 2018-11-26 19:32 UTC
**Describe the bug**
At one time my client created a coupon for 100% off a product (fixed product coupon). This coupon was put into the trash yet anyone can apply this coupon and it still works. We found out after a customer found the coupon and used it for a free sale :(

<img width="1469" alt="screen shot 2018-11-26 at 2 28 12 pm" src="https://user-images.githubusercontent.com/540990/49037298-db7bc200-f187-11e8-9623-dc4c47c3c5f4.png">

**To Reproduce**
1. Create a coupon for 100% off a fixed product (or any coupon?)
2. Put the coupon in the trash.
3. Add a product to cart and apply the coupon in the cart.
4. Coupon successfully updates and makes the product/cart free.

**Expected behavior**
I expect the coupon to no longer work since it is in the trash.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: https://www.lovebugprobiotics.com
Site URL: https://www.lovebugprobiotics.com
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.11
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.61.1
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.6.41-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
Total Database Size: 61.12MB
Database Data Size: 32.36MB
Database Index Size: 28.76MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.36MB + Index: 0.13MB
wp_woocommerce_order_itemmeta: Data: 2.38MB + Index: 3.70MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 1.42MB + Index: 0.94MB
wp_facetwp_index: Data: 0.02MB + Index: 0.05MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.38MB + Index: 0.08MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.02MB + Index: 0.03MB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 14.48MB + Index: 15.97MB
wp_posts: Data: 6.27MB + Index: 1.86MB
wp_sp_email_logs: Data: 0.02MB + Index: 0.02MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 3.52MB + Index: 5.03MB
wp_users: Data: 0.17MB + Index: 0.22MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.16MB + Index: 0.05MB
wp_yoast_seo_meta: Data: 0.44MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 5
acf-field-group: 1
attachment: 227
custom_css: 1
favorite: 17
gs_faq: 19
ml-slide: 15
ml-slider: 1
nav_menu_item: 19
oembed_cache: 2
page: 17
post: 74
product: 48
revision: 5
scheduled-action: 28
shop_coupon: 14
shop_order: 1705
shop_subscription: 4
testimonial: 2
wc_order_status: 8
wpsl_stores: 2232

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Query Monitor: by John Blackbourn & contributors – 3.1.1
Gravity Forms: by rocketgenius – 2.3.6
Advanced Custom Fields PRO: by Elliot Condon – 5.7.7
Akismet Anti-Spam: by Automattic – 4.1
Enable Media Replace: by ShortPixel – 3.2.7
FacetWP: by FacetWP
LLC – 3.2.9

Genesis Connect for WooCommerce: by StudioPress – 1.0 – Not tested with the active version of WooCommerce
Genesis Simple FAQ: by StudioPress – 0.9.1
Imsanity: by Exactly WWW – 2.4.1
Instagram Feed: by Smash Balloon – 1.10.1
Mai Ads & Extra Content: by MaiTheme.com – 0.8.2
Mai Favorites: by Mike Hemberger
BizBudding Inc – 1.0.2

Mai Testimonials: by MaiTheme.com – 0.5.2
Mai Theme Engine: by MaiTheme.com – 1.5.3
MetaSlider: by Team Updraft – 3.10.2
Shared Counts: by Bill Erickson & Jared Atchison – 1.2.0
Simple Google Analytics Tracking: by Dustyn Doyle – 1.3
Simple Page Ordering: by Jake Goldman
10up – 2.3.2

Simple Social Icons: by StudioPress – 3.0.0
SparkPost: by SparkPost – 3.2.0
User Switching: by John Blackbourn & contributors – 1.4.0
Wampum - Forms: by Mike Hemberger – 1.3.3
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.5.4 – 3.5.5 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.13
WooCommerce Order Status Manager: by SkyVerge – 1.9.3
WooCommerce Subscribe All the Things: by Prospress Inc. – 2.1.2 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.0.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.4.4
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.3 – 3.0.12 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.1
Yoast SEO: by Team Yoast – 9.2.1
WP All Import: by Soflyy – 3.4.9
WP Crontrol: by John Blackbourn & contributors – 1.6.2
WP Rocket: by WP Media – 3.2.2
WP Store Locator - CSV Manager: by Tijmen Smit – 1.2.0
WP Store Locator: by Tijmen Smit – 2.2.17
YoImages: by Sirulli – 0.1.8
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.8 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #12547 - /terms-conditions/

### Theme ###

Name: Lovebug Probotics
Version: 1.0.1
Author URL: https://bizbudding.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.7.1
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: /site/aharri18/public_html/wp-content/plugins/mai-theme-engine/templates/woocommerce/content-product.php
/site/aharri18/public_html/wp-content/plugins/mai-theme-engine/templates/woocommerce/content-product_cat.php
/site/aharri18/public_html/wp-content/plugins/mai-theme-engine/templates/woocommerce/loop/loop-end.php
/site/aharri18/public_html/wp-content/plugins/mai-theme-engine/templates/woocommerce/loop/loop-start.php


### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.lovebugprobiotics.com
Subscription Statuses: wc-active: 1
wc-pending: 2
wc-on-hold: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 1
wc-on-hold: 1
wc-pending: 2


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders
```
</details>

**Comment by rrennick** [comment] 2018-11-26 20:11
Have you tried this in an environment without caching? I'm not able to reproduce this in my local dev install. I also tried applying the coupon to the cart, deleting the coupon then refreshing the cart - the coupon was removed.

**Comment by dws122** [comment] 2018-11-26 20:48
Object Caching is in use. However, moving the coupon to the trash should remove the object from the cache, but it doesn't.

Looking at the code in WooCommerce, it appears the object cache is only cleared on Permanently deleting the coupon, and not when the coupon is trashed.

https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-coupon-data-store-cpt.php#L205-L215

Here's testing history to support above statement.

Using WP CLI --> wp cache flush purged the entire cache and the trashed coupon in the cart failed upon page refresh.

To continue testing, we created a new coupon 'davefree' and then trashed the coupon. The coupon remained active in the object cache. Next step in testing was to permanently delete the coupon, and refresh the cart.

Doing so caused a fatal error:
```
Message Uncaught Exception: Invalid coupon. 
in /site/account/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:107 
Stack trace: 
#0 /site/account/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Coupon_Data_Store_CPT->read(Object(WC_Coupon)) 
#1 /site/account/public_html/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(129): WC_Data_Store->read(Object(WC_Coupon)) 
#2 /site/account/public_html/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(117): WC_Coupon->read_object_from_database() 
#3 /site/account/public_html/wp-content/plugins/woocommerce/includes/class-wc-cart.php(725): WC_Coupon->__construct('davefree') 
#4 /site/account/public_html/wp-includes/class-wp-hook.php(286): WC_Cart->check_cart_coupons('') 
#5 /site/account/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(true, Array) 
#6 /site/account/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#7 /site/account/pu

File /site/account/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php

```

The cart continues this error, until the object cache is subsequently flushed.

To further test, we created a new coupon 'mikefree'. And immediately trashed the coupon, and immediately permanently deleted the coupon. Subsequent testing of the coupon code does not apply a discount to the cart, however, no error message is returned that the coupon is invalid.

It appears the delete permanently function removed the discount value from the object cache, but not the coupon itself.

Testing a completely random and arbitrary coupon code returns invalid coupon.

**Comment by dws122** [comment] 2018-11-26 20:53
I've also tested this on two different domains with the same results as documented above.

**Comment by claudiulodro** [comment] 2018-11-27 20:05
Fix in #22053

**Comment by jonathansadowski** [comment] 2021-08-13 16:18
It looks like the fix in #22053 wasn't ever actually merged to trunk. Therefore, I'm reopening this issue, as it appears the original bug still exists.

In addition, we should make sure the following cases work as intended when readdressing the issue:
* Force-delete
* Trash
* Trash then delete
* Untrashing (coupon should be usable again)

**Comment by nickpagz** [comment] 2022-08-24 19:15
This may be covered in the[ pending PR](https://github.com/woocommerce/woocommerce/pull/33791), but I've noticed that if a user applies the coupon (whether already trashed or not), and the coupon is then permanently deleted, the user will experience a critical error on the site. The following error comes up in my testing:

```
Uncaught Exception: Invalid coupon. in /srv/htdocs/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:118
```

The critical error goes away after clearing customer sessions.

**Comment by barryhughes** [comment] 2022-08-25 00:02
Good catch, thanks @nickpagz. Though related, it's a different problem so I've created a new issue for this:

https://github.com/woocommerce/woocommerce/issues/34459

**Closed** 2022-08-25 12:26 UTC
Labels: type: bug, priority: high, plugin: woocommerce
