### ISSUE TITLE
Shipping Failure

### ISSUE THREAD

**Issue by beautiti** [woocommerce/woocommerce#25167] opened 2019-12-04 10:12 UTC
I have an online hair product shopping site, I have the option to buy - but when a customer puts products in the basket -> enters the shipping data -> when he clicks credit and then the checkout button -> he goes back to the same page again -> it Does not transfer it to credit clearing at all.

**Comment by juliaamosova** [comment] 2019-12-04 10:17
Hi there @beautiti,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. You also completely ignored the bug report template. 

In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-12-04 10:17 UTC
