### ISSUE TITLE
Order total does not round up correctly when using fixed price discount coupon.

### ISSUE THREAD

**Issue by kristinaplauche** [woocommerce/woocommerce#13802] opened 2017-03-28 16:46 UTC
## EXPLANATION OF THE ISSUE

WooCommerce 2.6.14 (only active plugin)
Storefront theme.

If you use a fixed price discount coupon, the order total does not round up if the 3rd decimal place in the calculation is a 5 or below.  If it is a 6 or above the order total does round up.
Reported here: 552929-zd-woothemes
Recreated on my test site. Also @jessepearson confirmed this behavior

Could be related to https://github.com/woocommerce/woocommerce-smart-coupons/issues/39
or this https://github.com/woocommerce/woocommerce-smart-coupons/issues/39

## STEPS TO REPRODUCE THE ISSUE

Product price: $5.99
Coupon: Cart Discount- $59.90
Add 34 items to your cart.
Enter coupon code.
Place your order.
View Order from WooCommerce>Orders list to see detailed calculations:
**$143.76 + $8.63 ≠ $152.38  
$143.76 + $8.63 = $152.39**

![screenshot](http://cld.wthms.co/29dg+)
Image link: http://cld.wthms.co/29dg

#### I know that WC calculates based on 4 decimals not 2, so I looked at the calculation in a spreadsheet.
![screenshot](http://cld.wthms.co/MhWv+)
Image link: http://cld.wthms.co/MhWv

 

I finagled the numbers so that I could have a 4 decimal calculation with a 6 in the 3rd decimal place & still use a fixed coupon.
Product price: $4.23
Coupon: Cart Discount- $59.88
Add 34 items to your cart.
Enter coupon code.
Place your order.

The order total is correct.
![screenshot](http://cld.wthms.co/Q6An+)
Image link: http://cld.wthms.co/Q6An

### The difference in the two scenarios (and the many others that I tried) is in the 3rd decimal place of the calculation as you can see below.  If the 3rd decimal is 5 or below the order total will not round. If it is 6 or above the order total will round.

![screenshot](http://cld.wthms.co/g2rR+)
Image link: http://cld.wthms.co/g2rR

I tried with % coupons and did not see the issue.
## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://mamabear.mystagingwebsite.com
Site URL: https://mamabear.mystagingwebsite.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.17
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.53.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.14

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment] 2017-03-28 17:34
@kristinaplauche This is because of the fixed cart discount. Since you cannot discount 'tax', the cart level discount has to be split between all individual items in the cart.

Since there are 34 items to split, it's not a clean number, so once round to 4dp and worked with, you're getting a 1cent discrepancy.

Fixed product and percent coupons are not affected.

As for a fix, there isn't really one. You can increase precision to get around it - the `WC_ROUNDING_PRECISION` constant defaults to 4. Setting to 6 would fix this specific case and is something you can pass onto the user.

I'll put in a PR for core to increase it, but it won't be in 3.0.0 as it requires extra testing. For now, it's won't fix.

**Comment by mikejolley** [comment] 2017-03-28 17:41
See  #13805

**Closed by mikejolley** 2017-03-28 17:41 UTC
Labels: Type: Bug

**Comment by kristinaplauche** [comment] 2017-03-28 19:25
Increasing the calculation to 6 decimal places does not seem that it will resolve this issue.  In the example above, the calculations only went to 4 decimal places so increasing to 6 won't change the outcome of the calculation. The issue is that the order total is not rounding when a 5 is in the 1000's place. It's seems that the rounding threshold is off in this specific situation, not that the calculation is bad.

>This is because of the fixed cart discount. Since you cannot discount 'tax',
I believe you are saying that tax can't be discounted _because_ of the fixed cart discount.  So a different rule is applied and only the subtotal is discounted. The discount is divided up equally between the number of items in the cart.  
Like this right? **(price-(discount÷quantity))x quantity= subtotal**

**Side Note:** In the example for the $5.99 product, the $59.90 discount ÷ 34 quantity= $1.76.
If you are a customer looking at your order and you do the math (5.99-1.76)x34)= $143.82 which is 6¢ different than the $143.76 shown. $143.76 is the _correct_ answer (because of rounding), but it does not appear to be correct. I would suggest not showing the discount underneath the product price in the order. instead only show the discount in the order total area.
![screenshot](http://cld.wthms.co/sxSs+)
Image link: http://cld.wthms.co/sxSs

**Comment by mikejolley** [comment] 2017-03-28 22:56
@kristinaplauche I confirmed 6 dp works before posting. It makes the split discount more accurate thus avoiding the issue when getting the item total.

It's the item total at fault; if you edit the line item you'll see it's not a whole number.

**Comment by matildafloyd** [comment] 2017-07-13 09:14
Hi all,
![regular price with extra decimal](https://user-images.githubusercontent.com/24999818/28159144-99149410-67ee-11e7-8cc2-fb1cbd4af4e2.png)
![bulk discount with extra decimal](https://user-images.githubusercontent.com/24999818/28159153-9d4cdf7e-67ee-11e7-9353-8eaffbb74df7.png)

 dont know if this is a workaround/handy for you guys but I added an extra decimal to either price and/or the discounted percentage number. Cray nums as you can see but worked for me.
