### ISSUE TITLE
Can not add shipping class, shipping method

### ISSUE THREAD

**Issue by kihoshin** [woocommerce/woocommerce#27351] opened 2020-08-17 04:31 UTC
Just updated WooCommerce to 5.5, now I can not add any Shipping Class, Shipping Method.

**Comment by tammullen** [comment] 2020-08-17 12:01
Hi @kihoshin 

Thank you for submitting the issue. 

It may be that you have plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

WordPress 5.5 removed a javascript file called jQuery migrate that some of your plugins might have relied on, so until they update, you might want to use this plugin to include the javascript files in the meantime: https://wordpress.org/plugins/enable-jquery-migrate-helper/.

WIth just WooCommerce 4.33 and WordPress 5.5 active I can’t reproduce the issue you reported. Everything is working as expected on my end. I can add Shipping Class & Shipping Method.
![Screenshot 2020-08-17 at 12 56 43](https://user-images.githubusercontent.com/24649833/90393745-428e8800-e089-11ea-8fa5-fc32d74ab9ac.png)
![Screenshot 2020-08-17 at 12 56 34](https://user-images.githubusercontent.com/24649833/90393753-46220f00-e089-11ea-908c-47c23047def3.png)
![Screenshot 2020-08-17 at 12 56 18](https://user-images.githubusercontent.com/24649833/90393757-491cff80-e089-11ea-9168-c0f3c61c09ce.png)


You didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​

**Comment by tammullen** [comment] 2020-08-26 16:45
Hi @kihoshin 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2020-08-26 16:45 UTC
Labels: can't reproduce, status: needs feedback
