### ISSUE TITLE
Categories set to "Uncategorized" for non authorized import process. 

### ISSUE THREAD

**Issue by bliteknight** [woocommerce/woocommerce#27300] opened 2020-08-11 21:14 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Cron job used for importing csv product updates puts all products into "Uncategorized" due to there not being a currently authenticated user in the session.

**Expected behavior**
Existing categories will be unchanged, new categories (not created by an authenticated user) will be "Uncategorized".
 
**Actual behavior**
All products are updated with  "Uncategorized" because there is no user in context, so function parse_categories_field returns an empty array.

This code change that introduced this behavior: https://github.com/woocommerce/woocommerce/commit/ea17484e42fb64d6a0eaec826bcf7653cd9eda67

specifically the change to not return existing categories regardless of an authorized user being in context.
I understand not allowing a non authorized user to create new categories, but if the category exist, it should be returned rather then returning an empty array.

Another issue I noticed is only the last category is set if I bypass the authorized check; so in my example below Furniture > Table - only Table will be set for the product update.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new product that has an SKU, name, description, and category.
SKU: TBL-0001
Name: Beach table
Category: Furniture > Tables
Description: Very Trendy table for the beach
Price: 200
Quantity: 5

2. Create a csv file located somewhere on the server that contains the new product you just created with headers like so:
```
sku,name,category_ids,description,regular_price,stock_quantity
TBL-0001,"Beach table", Furniture > Tables,"It's a beach table", 600.00, 2
```

3. Create a WP Cron Job that will update woocommerce via WC_Product_CSV_Importer
(scope of which is too in depth to list here). Quickest way would be to use Cron Events and have it run at an interval, with the code looking for the csv like so:
```
$importJob =  new WC_Product_CSV_Importer(<path to csv>,['update_existing'=>1, 'prevent_timeouts'=>false, 'lines'=>120,'parse'=>1]);
$result = $importJob->import();
```
4. When the job run successfully, you will see the product has been updated with the new price, description, quantity. But the category will be set to "Uncategorized".

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
WC Version: 4.3.2
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache:
</details>

**Comment by claudiosanches** [comment] 2020-10-22 22:49
Hello @bliteknight, thanks for submitting this report.

>  Cron job used for importing csv product updates puts all products into "Uncategorized" due to there not being a currently authenticated user in the session.

It's easy to solve it by authenticating some user, it's already custom code to run it, so it's easy to include a code like:

```php
wp_set_current_user( 1 ); // Default admin ID, but you can change to any other admin or shop manager.

$importJob =  new WC_Product_CSV_Importer(<path to csv>,['update_existing'=>1, 'prevent_timeouts'=>false, 'lines'=>120,'parse'=>1]);
$result = $importJob->import();
```

The other issues you reported also sounds like due custom code and could be solved, since works just fine on our side.

Please note that while our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-10-22 22:49 UTC

**Comment by bliteknight** [comment] 2020-11-07 18:05
Thanks for looking at this, will try setting a user in context before calling WC_Product_CSV_Importer
