### ISSUE TITLE
The "Uncaught (in promise)" error appears when user tries to add second item to the cart

### ISSUE THREAD

**Issue by kvolchkov** [woocommerce/woocommerce#26681] opened 2020-06-03 13:17 UTC
**Describe the bug**
Given User wants to add two items into the cart
When User clicks the Add to cart button
Then first product is added to the cart
When User clicks the Add to cart button
Then second product IS NOT added to the cart and spinners keeps on spinning - Failed

**To Reproduce**
1. Open the https://beenut.com.ua/ in Chrome
2. Switch to the Mobile view in the Dev Tools to emulate mobile device
3. Scroll down to the items
4. Click the green Add button on the first product
5. Click the green Add button on the second product – Failed (see the screenshot and gif)
Actual Result: second item can’t be added, error appears in the Dev Console
Expected Result: second item is added, error doesn’t appear

Browser: Chrome
Device: Mac, iPhone, Android

**Screenshots**
<img width="1676" alt="Screenshot 2020-06-03 at 14 48 55" src="https://user-images.githubusercontent.com/12866189/83638816-0a0f0000-a5aa-11ea-820c-55e76545c14c.png">

![Bug 2020-06-03 at 15 00 34](https://user-images.githubusercontent.com/12866189/83640869-09c43400-a5ad-11ea-9a82-b71e0e383b82.gif)

**Expected behavior**
The second product is added to the cart. No error appears in the Dev Console.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress: 5.4.1
Theme: Twenty Seventeen
```
`
### WordPress Environment ###

WordPress address (URL): https://beenut.com.ua
Site address (URL): https://beenut.com.ua
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: uk
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.6
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wpetsl_
Total Database Size: 2.53MB
Database Data Size: 2.03MB
Database Index Size: 0.50MB
wpetsl_woocommerce_sessions: Data: 0.11MB + Index: 0.01MB + Engine MyISAM
wpetsl_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_actionscheduler_actions: Data: 0.31MB + Index: 0.10MB + Engine MyISAM
wpetsl_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_actionscheduler_logs: Data: 0.17MB + Index: 0.18MB + Engine MyISAM
wpetsl_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_mo_openid_linked_user: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_options: Data: 1.28MB + Index: 0.05MB + Engine MyISAM
wpetsl_postmeta: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
wpetsl_posts: Data: 0.09MB + Index: 0.02MB + Engine MyISAM
wpetsl_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpetsl_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 16
customize_changeset: 42
elementor_library: 2
nav_menu_item: 7
page: 11
post: 2
product: 8
revision: 38
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Facebook for WooCommerce: by Facebook – 1.11.3 – Installed version not tested with active version of WooCommerce 4.2.0
Official Facebook Pixel: by Facebook – 2.0.2
WooCommerce Side Cart: by XootiX – 2.1 – Installed version not tested with active version of WooCommerce 4.2.0
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.0.2
Widget Shortcode: by Hassan Derakhshandeh – 0.3.5
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.2 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: UAH (₴)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #83 - /shop/
Cart: #88 - /cart/
Checkout: #89 - /checkout/
My account: #90 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Twenty Seventeen
Version: 2.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 4
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

Complete: 821
Oldest: 2020-05-18 16:41:18 +0000
Newest: 2020-06-03 12:55:42 +0000

Pending: 1
Oldest: 2020-06-03 12:56:07 +0000
Newest: 2020-06-03 12:56:07 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-06-03 18:58
Hi @kokavolchkov,

Thank you for raising the issue. However, I can’t reproduce it on my end. See gif below (I tested using WooCommerce 4.2 and Storefront theme):

![](http://g.recordit.co/NR01Ugrxxt.gif)

I see that you have several plugins installed. You also noted that you tested with all plugins deactivated. Can you please confirm you indeed did it? 

If not, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by kokavolchkov** [comment] 2020-06-06 09:04
Hi @juliaamosova 
I was able to reproduce this bug, when **only** Woocommerce plugin is Activated. Steps to reproduce are the same.

Here is the gif:

![Bug 720](https://user-images.githubusercontent.com/12866189/83940497-de2b8e80-a7e4-11ea-88cd-e8b845831b31.gif)

Here is the system status:

```
### WordPress Environment ###

WordPress address (URL): https://beenut.com.ua
Site address (URL): https://beenut.com.ua
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: uk
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.6
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wpetsl_
Total Database Size: 2.77MB
Database Data Size: 2.19MB
Database Index Size: 0.58MB
wpetsl_woocommerce_sessions: Data: 0.11MB + Index: 0.01MB + Engine MyISAM
wpetsl_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_actionscheduler_actions: Data: 0.39MB + Index: 0.12MB + Engine MyISAM
wpetsl_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_actionscheduler_logs: Data: 0.22MB + Index: 0.22MB + Engine MyISAM
wpetsl_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_mo_openid_linked_user: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_options: Data: 1.28MB + Index: 0.05MB + Engine MyISAM
wpetsl_postmeta: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wpetsl_posts: Data: 0.10MB + Index: 0.03MB + Engine MyISAM
wpetsl_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpetsl_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpetsl_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpetsl_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 19
custom_css: 1
customize_changeset: 54
elementor_library: 2
nav_menu_item: 7
page: 11
post: 1
product: 8
revision: 41
shop_order: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.2.0

### Inactive Plugins (6) ###

Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.2 – Installed version not tested with active version of WooCommerce 4.2.0
Facebook for WooCommerce: by Facebook – 1.11.3 – Installed version not tested with active version of WooCommerce 4.2.0
Official Facebook Pixel: by Facebook – 2.0.2
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.0.2
Widget Shortcode: by Hassan Derakhshandeh – 0.3.5
WooCommerce Side Cart: by XootiX – 2.1 – Installed version not tested with active version of WooCommerce 4.2.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: UAH (₴)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #83 - /shop/
Cart: #88 - /cart/
Checkout: #89 - /checkout/
My account: #90 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Twenty Seventeen
Version: 2.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,055
Oldest: 2020-05-18 16:41:18 +0000
Newest: 2020-06-06 07:59:18 +0000

Pending: 1
Oldest: 2020-06-06 08:14:18 +0000
Newest: 2020-06-06 08:14:18 +0000

```

**Comment by tammullen** [comment] 2021-03-24 19:55
Thanks @kvolchkov for the extra information

Apologies for the delay in replying.

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

![Screenshot 2021-03-24 at 19 51 22](https://user-images.githubusercontent.com/24649833/112375105-ca510a80-8cda-11eb-84d5-6fed63929b92.png)

Are you still experiencing this issue?

**Comment by kvolchkov** [comment] 2021-03-25 19:38
This issue is solved. Thank you.

**Closed** 2021-03-25 19:38 UTC
Labels: category: can't reproduce, needs feedback
