### ISSUE TITLE
wc_update_order_item_meta not work

### ISSUE THREAD

**Issue by golendercaria** [woocommerce/woocommerce#26817] opened 2020-06-18 17:46 UTC
Hello,

I'm trying to find out why this piece of code doesn't work. I tried several functions, remove the meta and add the meta, but the behavior seems random.

For information, if i get the meta after updater, i have a good value, but if i refresh order page, this is no good and the data in database not change.

```
    add_action( 'woocommerce_update_order', 'action_woocommerce_update_order', 10, 1 ); 
    
    function action_woocommerce_update_order( $order_get_id ) { 
	    
	    $order = wc_get_order( $order_get_id );
		$items = $order->get_items();

		foreach ( $order->get_fees() as $fee_item_id => $fee_item ) {
			if( $fee_item['name'] == "custom_fee" ){
				
				$current_fee_amount = wc_get_order_item_meta($fee_item_id, "_fee_amount", true);
				$current_line_total = wc_get_order_item_meta($fee_item_id, "_line_total", true);
				
				wc_update_order_item_meta( $fee_item_id, '_fee_amount', wc_format_decimal(45), wc_get_order_item_meta($fee_item_id, "_fee_amount", true) );
				wc_update_order_item_meta( $fee_item_id, '_line_total', wc_format_decimal(45), wc_get_order_item_meta($fee_item_id, "_line_total", true) );

			}
		}
    } 
```
Thank.

**Comment by juliaamosova** [comment] 2020-06-18 21:53
Hi @golendercaria,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-06-18 21:53 UTC
