### ISSUE TITLE
Price incl. tax and subtotal calculation goes wrong

### ISSUE THREAD

**Issue by efoken** [woocommerce/woocommerce#25347] opened 2020-01-02 17:36 UTC
**Describe the bug**
Price calculation incl. taxes goes completely wrong in backend and also in emails and invoices created with the "Germanized for WooCommerce" plugin. In frontend on the cart page everything is calculated and displayed correctly.

I also reported that bug to the developers of Germanized, but it seems to be a problem with WooCommerce as I disabled other plugins.

**To Reproduce**
1. Create two different products with a price of 15,50
2. Tax rate configured in WooCommerce is `19.0000`
3. The "rounding" option in WooCommerce tax settings is disabled
4. Create an order with 3 of the one product and 5 of the other
5. See that calculation goes wrong

**Screenshots**
<img width="954" alt="Bildschirmfoto 2020-01-02 um 18 29 06" src="https://user-images.githubusercontent.com/522446/71681742-cc554380-2d8d-11ea-8b5f-27c20166293a.png">

<img width="695" alt="Bildschirmfoto 2020-01-02 um 17 42 22" src="https://user-images.githubusercontent.com/522446/71681758-d8410580-2d8d-11ea-816c-c5730595c0aa.png">

**Expected behavior**
Taxes and subtotals should be calculated correctly.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://farbularasa.de/wp
Site address (URL): https://farbularasa.de
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.3.9-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.0.2n

SUHOSIN Installed: –
MySQL Version: 5.6.33-0ubuntu0.14.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 65.80MB
Datenbank-Datengröße: 45.26MB
Datenbank-Indexgröße: 20.54MB
wp_woocommerce_sessions: Daten: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Daten: 0.45MB + Index: 0.25MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Daten: 5.32MB + Index: 2.80MB + Engine MyISAM
wp_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Daten: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_comments: Daten: 1.65MB + Index: 0.95MB + Engine MyISAM
wp_fwwl_wishlists: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_consent: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_userlogs: Daten: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_masterslider_options: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_masterslider_sliders: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_options: Daten: 3.04MB + Index: 0.38MB + Engine MyISAM
wp_postmeta: Daten: 22.58MB + Index: 10.48MB + Engine MyISAM
wp_posts: Daten: 5.72MB + Index: 1.33MB + Engine MyISAM
wp_rank_math_404_logs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_sc_analytics: Daten: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_termmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_relationships: Daten: 0.26MB + Index: 0.58MB + Engine MyISAM
wp_term_taxonomy: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Daten: 1.11MB + Index: 0.78MB + Engine MyISAM
wp_users: Daten: 0.06MB + Index: 0.06MB + Engine MyISAM
wp_wcpdf_invoice_number: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.31MB + Index: 0.34MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.31MB + Index: 0.64MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmm_subscribers: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Daten: 0.17MB + Index: 0.08MB + Engine InnoDB
wp_yith_wcwl_lists: Daten: 0.22MB + Index: 0.30MB + Engine InnoDB
wp_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

The SEO Framework: von The SEO Framework Team – 4.0.4
BackWPup: von Inpsyde GmbH – 3.7.0
Contact Form 7: von Takayuki Miyoshi – 5.1.6
The GDPR Framework: von Data443 – 1.0.33
Grid Masonry Related Posts: von ThemeREX – 1.0
Jetpack von WordPress.com: von Automattic – 8.0
ShortPixel Image Optimizer: von ShortPixel – 4.15.3
ThemeREX Addons: von ThemeREX – 1.7.7.2
Vendidero Helper: von Vendidero – 1.2.1
YellowPencil Pro: von WaspThemes – 7.2.3
WooCommerce Weight Based Shipping: von weightbasedshipping.com – 5.3.2.2
WooCommerce Admin: von WooCommerce – 0.23.3
WooCommerce Stripe-Gateway: von WooCommerce – 4.3.1
Germanized für WooCommerce Pro: von Vendidero – 2.0.9
Germanized for WooCommerce: von Vendidero – 3.0.8
WooCommerce: von Automattic – 3.8.1
WP Maintenance Mode: von Designmodo – 2.2.4
WordPress Sentry: von Alex Bouma – 3.2.0
YITH WooCommerce Wunschliste: von YITH – 3.0.5

### Inactive Plugins (3) ###

Rank Math SEO: von Rank Math – 1.0.36.3
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.18
YITH WooCommerce Zoom Magnifier: von YITH – 1.3.15

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (4) ###

Bedrock Autoloader: von Roots – 1.0.0
Disallow Indexing: von Roots – 1.0.0
Register Theme Directory: von Roots – 1.0.0
Setup PHPMailer: von Eike Foken – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #9 - /shop/
Warenkorb: #10 - /cart/
Kasse: #11 - /checkout/
Mein Konto: #12 - /my-account/
Allgemeine Geschäftsbedingungen: #14 - /agb/

### Theme ###

Name: Farbularasa Theme
Version: 1.0
Author URL: https://eikefoken.com/
Child Theme: ✔
Parent Theme Name: GutenType
Parent Theme Version: 1.9.0
Parent Theme Author URL: http://ancorathemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1.596
Oldest: 2019-12-02 18:25:48 +0000
Newest: 2020-01-02 17:25:13 +0000

Pending: 2
Oldest: 2020-01-02 18:25:13 +0000
Newest: 2020-01-02 18:25:13 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```
</details>

**Comment by thomas-zg** [comment] 2020-01-02 17:51
Maybe #24828 will solve the issue, but this is a part of version 3.9. Have you got the possibility to install the 3.9 RC 2 in a test environment?

**Comment by tammullen** [comment] 2020-01-14 12:08
Screenshot Translation (From German using Google Translate)
<hr><br>

<img width="954" alt="71681742-cc554380-2d8d-11ea-8b5f-27c20166293a" src="https://user-images.githubusercontent.com/24649833/72343331-85891700-36c6-11ea-959f-4bf0b03a8b15.png">
<img width="695" alt="71681758-d8410580-2d8d-11ea-816c-c5730595c0aa" src="https://user-images.githubusercontent.com/24649833/72343335-8621ad80-36c6-11ea-8e52-ced14449d33f.png">

**Comment by tammullen** [comment] 2020-01-14 15:42
Hi @efoken,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end and I believe the calculations are correct. 

Can you provide more details on exactly which of the calculations are incorrect and any extra steps to reproduce it?

Order Details from wp-admin
<img width="921" alt="Screenshot 2020-01-14 at 15 36 54" src="https://user-images.githubusercontent.com/24649833/72358119-f854bb00-36e3-11ea-9b7f-976fcbbc0477.png">
Order Email
<img width="533" alt="Screenshot 2020-01-14 at 15 10 03" src="https://user-images.githubusercontent.com/24649833/72358120-f854bb00-36e3-11ea-8045-2e1f7dd93e05.png">

**Comment by efoken** [comment] 2020-01-20 21:23
Hi @tammullen ,

and thanks for translating screenshots. Well, I see you reproduced the issue correctly – have you looked at your first screenshot carefully? In which world is `13,03€ * 3 = 39,08€` and `13,03€ * 5 = 65,13€` ?? 😄

**Comment by efoken** [comment] 2020-01-20 21:31
Oh! I've seen another one in your second screenshot that says, there are 19,79 € VAT – how can it be that then the total is 124,00€ and subtotal is 104,20€ ? 😄

**Comment by juliaamosova** [comment] 2020-01-29 13:24
@efoken thanks for additional feedback. I can see that this is still an issue in WooCommerce 3.9.1. 

My Tax Settings:

![Screen Shot 2020-01-29 at 1 13 36 PM](https://user-images.githubusercontent.com/19143190/73359747-7050e280-4299-11ea-9f51-eff1f925cd78.png)

The Standard tax rate is 19% for the US:

![Screen Shot 2020-01-29 at 1 13 46 PM](https://user-images.githubusercontent.com/19143190/73359776-7fd02b80-4299-11ea-9314-9d78b7179194.png)

Created:

- Product A - $15.50
- Product B - $15.50

Products on the Shop page:

![cart0](https://user-images.githubusercontent.com/19143190/73360138-316f5c80-429a-11ea-8eb2-f3177c55a1b4.jpg)

Cart:

![cart1](https://user-images.githubusercontent.com/19143190/73360145-36341080-429a-11ea-8da9-32de33263811.jpg)

Thank you page (after placing an order):

![cart2](https://user-images.githubusercontent.com/19143190/73360308-8c08b880-429a-11ea-920f-82a2af1d6005.jpg)

Order page in wp-admin:

![cart3](https://user-images.githubusercontent.com/19143190/73360319-91660300-429a-11ea-81ba-9361f7c81a65.jpg)

It seems like a rounding issue for us to address.

**Comment by vedanshujain** [comment] 2020-02-06 13:42
Closing in favor of #24619, as both these issues have same root cause and will be fixed together.

**Closed by vedanshujain** 2020-02-06 13:42 UTC
Labels: bug, priority: high

**Comment by boutzamat** [comment] 2022-03-17 08:11
Only, it hasn't been fixed yet 2 years later. How are you not focusing on something as essential as tax? 
Imo that should have the highest priority before all the new fancy gimmick features that only promotes Automatic from my point of view. 
I know WC is free, but i've invested countless of money in your eco-system so i really feel i'm in the place to complain when you don't fix something as vital as this, after 2 years.
