### ISSUE TITLE
Product Listing Issues With Hide Out Of Stock

### ISSUE THREAD

**Issue by Schurke** [woocommerce/woocommerce#22986] opened 2019-03-10 22:22 UTC
**Describe the bug**
When using the "Hide out of stock items from the catalog" option in Settings > Products > Inventory (on stores with out of stock items) product listings suffer unusual offsets and display issues. Examples include:

Products shortcode; limit 4; Whenever the data set contains out of stock items, it will display less than 4 items.

Products loop; Whenever the data set contains out of stock items, it will display less than (the specified quantity of items) and pagination values will be inaccurate.

It's almost as though the out of stock items are pulled-out after the query, rather than the query including (must have stock) as a term.

**To Reproduce**
1. Products data set with out of stock items
2. Setting for Hide out of stock items from the catalog set to true
3. Observe behaviour anywhere lists of products are shown.

**Expected behavior**
Shortcode: Always get the <limit> number of products
Product Loop: Pagination accurately reflects displayed/hidden items.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

![Screenshot_1](https://user-images.githubusercontent.com/4356133/54092310-1a154100-4361-11e9-9312-e60ebcb729fc.png)

**Comment by kloon** [comment] 2019-03-11 09:07
Hi @Schurke 

Would it be possible to test this by switching your theme to a default one like Storefront or Twentyseventeen and testing this again?

I tested this locally and was not able to reproduce this, in my tests the pages filled correctly, product totals updated correctly and it did not have any gaps.

It is possible the theme you are using is overriding one of the templates and not accommodating for hiding out of stock products, you also omitted your system status report so it is hard to tell exactly but since I am unable to replicate this my hunch is this is your theme.

![Products shortcode without hiding out of stock items](https://cld.wthms.co/itly4r+)
* Not hiding out of stock products *

![Products hiding out of stock](https://cld.wthms.co/eki4P8+)
* Hiding out of stock items *

As per the screenshots above you can see that when I hide out of stock items it updates the totals and hides the products without leaving a gap, see the Album product.

Closing this due to not able to replicate using a standard theme, but will gladly reopen if you can provide clear and precise steps to replicate this on a standard theme with just the WooCommerce plugin active.

**Closed by kloon** 2019-03-11 09:07 UTC

**Comment by Schurke** [comment] 2019-03-12 02:30
Hi, Kloon

Additional details: The dataset I'm using was transitioned as part of an upgrade from WooCommerce 2.x to 3.x. I'm uncertain of how meaningful that is... or how to provide precise steps for reproduction in this case... The steps that have gotten us here sound (anecdotally) like "have a functional WC2.x site; Upgrade to WC3.x; perform in place updates on the legacy theme to get it up to spec; discover that product lists have issues with out of stock items; switch to a recent version of Storefront and discover the issue is still present; disable all plugins other than WC and be disappointed that the issue is still present."

Are there any other factors that could mess up the pagination/enumeration?

Attached: New example using storefront theme (I have new storefront re-labelled Storefront2 to avoid conflicts with the legacy child theme I'm reworking).

![Screenshot_1](https://user-images.githubusercontent.com/4356133/54170082-a308a700-444b-11e9-96fc-ac999e603941.png)


Any insight you can provide would be much appreciated.

System report is as follows:

`
### WordPress Environment ###

Home URL: https://dev.betteruniforms.com
Site URL: https://dev.betteruniforms.com
WC Version: 3.5.6
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - There is a newer version of WordPress available (5.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 62.79MB
Database Data Size: 33.36MB
Database Index Size: 29.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.38MB + Index: 0.42MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.23MB + Index: 0.13MB
wp_comments: Data: 0.22MB + Index: 0.28MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 4.25MB + Index: 0.20MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.11MB + Index: 0.00MB
wp_pmxi_posts: Data: 1.52MB + Index: 0.31MB
wp_pmxi_templates: Data: 0.06MB + Index: 0.00MB
wp_postmeta: Data: 18.55MB + Index: 21.06MB
wp_posts: Data: 3.52MB + Index: 3.59MB
wp_s3j7v1p8_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_s3j7v1p8_comments: Data: 0.00MB + Index: 0.01MB
wp_s3j7v1p8_links: Data: 0.00MB + Index: 0.00MB
wp_s3j7v1p8_options: Data: 0.04MB + Index: 0.01MB
wp_s3j7v1p8_postmeta: Data: 0.00MB + Index: 0.01MB
wp_s3j7v1p8_posts: Data: 0.00MB + Index: 0.01MB
wp_s3j7v1p8_terms: Data: 0.00MB + Index: 0.01MB
wp_s3j7v1p8_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_s3j7v1p8_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_s3j7v1p8_usermeta: Data: 0.00MB + Index: 0.01MB
wp_s3j7v1p8_users: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.05MB + Index: 0.03MB
wp_term_relationships: Data: 3.52MB + Index: 2.52MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_usermeta: Data: 0.33MB + Index: 0.30MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_sdr_credentials: Data: 0.02MB + Index: 0.00MB
wp_wc_sdr_receipts: Data: 0.02MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpmelon_advbedit_temp: Data: 0.00MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 19
acf-field-group: 2
attachment: 518
ct_size_guide: 77
customize_changeset: 2
nav_menu_item: 58
page: 21
post: 5
product: 490
product_variation: 7620
revision: 186
shop_coupon: 148
shop_order: 131
shop_order_refund: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #165 - /terms-and-conditions/

### Theme ###

Name: Storefront2
Version: 2.4.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by Schurke** [comment] 2019-03-13 04:01
@kloon I did a bit of digging -- this seems to be a discrepancy that's created by migrating up from WC2 to WC3 regarding product stock status handling. 

From what I understand, products in WC2 used a meta value called _stock_status to indicate whether something was in or out of stock, where products in WC3 use a taxonomy called visibility. 

The "Hide out of stock items from the catalog" seems to only -sort of- respect both, where it does indeed hide items that have the old meta value, but this creates a discrepancy in the enumeration/pagination in doing so.

Is there a means by which one can (automatically) update their products (ditching the meta value and moving to the taxonomy)? Or does does the WC2->WC3 upgrade essentially commit one to... writing custom query actions all over the place to better handle the mixed bag stock status data that's bound to affect the site?
