### ISSUE TITLE
Tax Reports not accounting for refunded tax on refunded orders

### ISSUE THREAD

**Issue by mouligreenlaw** [woocommerce/woocommerce#24029] opened 2019-06-28 04:34 UTC
**Describe the bug**
If an order is refunded, the tax report still shows the tax from the order as having been paid

**To Reproduce**

* Create an Order that includes a tax component.
* Check the Tax Report for the relevant time period
* Refund the order
* Check the tax report again

**Screenshots**
Order with tax applied ($19.50)

![https://cld.wthms.co/KhBvz0](https://cld.wthms.co/KhBvz0+) 
Full Size: https://cld.wthms.co/KhBvz0

Tax is shown in report

![https://cld.wthms.co/R873nZ](https://cld.wthms.co/R873nZ+) 
Full Size: https://cld.wthms.co/R873nZ

Refunded one of the items

![https://cld.wthms.co/aM2gNH](https://cld.wthms.co/aM2gNH+) 
Full Size: https://cld.wthms.co/aM2gNH

Report still shows full tax amount

![https://cld.wthms.co/G4kx34](https://cld.wthms.co/G4kx34+) 
Full Size: https://cld.wthms.co/G4kx34

**Expected behavior**
The tax total in the tax report should account for refunded tax amounts

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://mywoocommerce.mystagingwebsite.com
Site address (URL): https://mywoocommerce.mystagingwebsite.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_NZ
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.19
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.65.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 9.92MB
Database Data Size: 6.17MB
Database Index Size: 3.75MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.14MB + Index: 0.13MB
wp_email_log: Data: 0.08MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.05MB + Index: 0.09MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.06MB + Index: 0.06MB
wp_postmeta: Data: 1.52MB + Index: 0.63MB
wp_posts: Data: 0.28MB + Index: 0.13MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 0.05MB + Index: 0.00MB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB
wp_wps_index: Data: 0.13MB + Index: 0.20MB
wp_wps_key: Data: 0.02MB + Index: 0.02MB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB
wp_wps_query: Data: 0.02MB + Index: 0.02MB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB
wp_wrd_discounts: Data: 0.02MB + Index: 0.02MB
wp_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 34
bookable_person: 1
bookable_resource: 5
custom_css: 1
customize_changeset: 4
event_ticket: 3
follow_up_email: 7
global_product_addon: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 7
order_shipment: 3
page: 16
post: 1
product: 60
product_variation: 40
revision: 35
scheduled-action: 216
shipping_package: 2
shop_coupon: 8
shop_order: 59
shop_order_refund: 3
shop_subscription: 5
wc_booking: 13
wc_membership_plan: 1
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.4

### Inactive Plugins (92) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Classic Editor: by WordPress Contributors – 1.5
Email Log: by Sudar – 2.3.1
Facebook for WooCommerce: by Facebook – 1.9.10 – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.8.13
Gravity Forms: by rocketgenius – 2.4.10
Gutenberg: by Gutenberg Team – 5.9.2
Health Check & Troubleshooting: by The WordPress.org community – 1.3.2
Jetpack by WordPress.com: by Automattic – 7.4.1
Loco Translate: by Tim Whitlock – 2.3.0
Mailchimp for WooCommerce: by Mailchimp – 2.1.16 – Not tested with the active version of WooCommerce
Product Filters for WooCommerce: by WooCommerce – 1.1.12 – 1.1.15 is available – Not tested with the active version of WooCommerce
Quantity Field on Shop Page for WooCommerce: by Wooassist – 1.1.0 – Not tested with the active version of WooCommerce
Storefront Mega Menus: by WooCommerce – 1.6.2 – Not tested with the active version of WooCommerce
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.4.15
TablePress: by Tobias Bäthge – 1.9.2
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 2.3.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.28
WooCommerce - Store Toolkit: by Visser Labs – 2.0.2 – Not tested with the active version of WooCommerce
WooCommerce 360° Image: by WooCommerce – 1.1.7 – 1.1.8 is available – Not tested with the active version of WooCommerce
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.6 – 1.1.8 is available
WooCommerce Admin: by WooCommerce – 0.12.0
WooCommerce Advanced Notifications: by WooCommerce – 1.2.15 – 1.2.16 is available – Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.5 – Not tested with the active version of WooCommerce
WooCommerce All Products For Subscriptions: by SomewhereWarm – 2.2.2 – 2.3.0 is available
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.7 – 2.4.11 is available – Not tested with the active version of WooCommerce
WooCommerce AvaTax: by SkyVerge – 1.6.6 – 1.7.2 is available – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.1.0
WooCommerce Bookings: by WooCommerce – 1.14.5
WooCommerce Bookings Availability: by WooCommerce – 1.0.0
WooCommerce Box Office: by WooCommerce – 1.1.11 – 1.1.12 is available – Not tested with the active version of WooCommerce
WooCommerce Bulk Variations: by Lucas Stark – 1.6.5
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.7 – 2.5.9 is available – Not tested with the active version of WooCommerce
WooCommerce Cart Add-Ons: by WooCommerce – 1.5.20
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.2.2 – 3.2.4 is available – Not tested with the active version of WooCommerce
WooCommerce Chained Products: by WooCommerce – 2.8.3 – 2.9.2 is available – Not tested with the active version of WooCommerce
WooCommerce Checkout Add-Ons: by SkyVerge – 1.12.6 – 2.0.5 is available – Not tested with the active version of WooCommerce
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.21
WooCommerce Composite Products: by SomewhereWarm – 4.0.6 – 4.1.0 is available
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.1 – 1.5.6 is available – Not tested with the active version of WooCommerce
WooCommerce Currency Converter: by WooCommerce – 1.6.12 – 1.6.13 is available – Not tested with the active version of WooCommerce
WooCommerce Deposits: by WooCommerce – 1.4.11 – 1.4.12 is available
WooCommerce Distance Rate Shipping: by Automattic – 1.0.11
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13 – Not tested with the active version of WooCommerce
WooCommerce FedEx Shipping: by WooCommerce – 3.4.18 – 3.4.19 is available
WooCommerce Force Sells: by WooCommerce – 1.1.18 – 1.1.19 is available
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.8 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.13.7 – 3.14.2 is available – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.13.0 – 1.13.1 is available
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.6
WooCommerce Multi-currency: by WooCommerce – 1.13.0 – 1.16.0 is available – Not tested with the active version of WooCommerce
WooCommerce Name Your Price: by Kathy Darling – 2.9.5 – 2.9.6 is available
WooCommerce One Page Checkout: by Prospress Inc. – 1.6.0 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.14 – 1.6.15 is available
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.2.4 – 2.2.5 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.15 – 4.4.16 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Pro Hosted: by WooCommerce – 1.0.18 – 1.0.19 is available – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Andrew Benbow – 4.4.2 – Not tested with the active version of WooCommerce
WooCommerce Photography: by WooCommerce – 1.0.16 – 1.0.17 is available – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.19 – 1.6.22 is available
WooCommerce Pre-Orders: by WooCommerce – 1.5.13
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.6.2 – 3.6.7 is available – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.11
WooCommerce Product Bundles: by SomewhereWarm – 5.10.2 – 5.11.0 is available
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.22 – 1.10.23 is available
WooCommerce Product Finder: by WooCommerce – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Products Compare: by WooCommerce – 1.0.12 – 1.0.13 is available – Not tested with the active version of WooCommerce
WooCommerce Product Search: by itthinx – 2.12.1 – 2.13.3 is available – Not tested with the active version of WooCommerce
WooCommerce Product Vendors: by WooCommerce – 2.1.17
WooCommerce Quick View: by WooCommerce – 1.2.1
WooCommerce Review for Discount: by WooCommerce – 1.6.8
WooCommerce Sales Report Email: by WooCommerce – 1.1.5 – 1.1.7 is available – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.20.0 – 1.21.0 is available
WooCommerce Shipping Per Product v2: by WooCommerce – 2.2.15 – 2.3.0 is available – Not tested with the active version of WooCommerce
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.5 – 3.6.8 is available – Not tested with the active version of WooCommerce
WooCommerce Shipwire: by SkyVerge – 2.3.4 – 2.4.0 is available – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by StoreApps – 4.0.0 – 4.0.8 is available – Not tested with the active version of WooCommerce
WooCommerce SnapScan Gateway: by WooCommerce – 1.1.3 – 1.1.4 is available – Not tested with the active version of WooCommerce
WooCommerce Splash Popup: by WooCommerce – 1.2.8 – 1.2.9 is available – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 1.0.37
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce Subscriptions: by Prospress Inc. – 2.5.6
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15
WooCommerce UPS Shipping: by WooCommerce – 3.2.14 – 3.2.16 is available – Not tested with the active version of WooCommerce
WooCommerce URL Coupons: by SkyVerge – 2.7.5
WooCommerce USPS Shipping: by WooCommerce – 4.4.25 – 4.4.26 is available
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.11 – 3.0.12 is available – Not tested with the active version of WooCommerce
WooCommerce Xero Integration: by WooCommerce – 1.7.16 – 1.7.17 is available – Not tested with the active version of WooCommerce
WP Mail Logging: by Christian Zöller – 1.9.1
WP Staging: by WP-Staging – 2.5.8
Yoast SEO: by Team Yoast – 11.2.1 – Not tested with the active version of WooCommerce

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/admin-new-order.php

### Action Scheduler ###

Complete: 202
Oldest: 2019-05-29 08:40:58 +1200
Newest: 2019-06-28 16:05:21 +1200

Pending: 5
Oldest: 2019-06-28 17:05:21 +1200
Newest: 2020-03-12 13:50:41 +1300

Canceled: 9
Oldest: 2019-06-05 15:52:23 +1200
Newest: 2019-06-14 18:12:29 +1200

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment] 2019-11-20 12:10
Thank you for reporting this issue @mouligreenlaw. And apologies for the delayed response. I can reproduce this issue.

**Comment by juliaamosova** [comment] 2019-11-26 16:17
@mouligreenlaw on the 2nd look at this issue, we don't have plans to work on the Reports section since it will soon be replaced by the [`WooCommerce Admin`](https://wordpress.org/plugins/woocommerce-admin/) Reports section which is currently a plugin but it will be  merged to core and will be a part of core sometime  in Q1/Q2 of 2020. 

I tested the same use case you provided in your report - the tax refunds work correctly in Reports in the WooCommerce Admin plugin. 

I am closing this issue since this is something we won't be working on. Sorry!

**Closed by juliaamosova** 2019-11-26 16:17 UTC
Labels: won't fix

**Comment by giacogiaco** [comment] 2021-03-07 20:21
This problem still exists with the new WooCommerce Admin Reports section. Can you reopen the issue? Thanks!

**Comment by John-belt** [comment] 2021-07-03 14:47
Yup still not fixed.
