### ISSUE TITLE
API returns wrong prices on order lines

### ISSUE THREAD

**Issue by johnknoop** [woocommerce/woocommerce#29085] opened 2021-02-10 14:07 UTC
I've created a product with a sale price:
![image](https://user-images.githubusercontent.com/3394270/107519645-cd6fbb80-6bb0-11eb-8e99-0091c5e55b95.png)

Then I placed an order for that product. Here's a screenshot of the order confirmation page:
![image](https://user-images.githubusercontent.com/3394270/107519762-ec6e4d80-6bb0-11eb-820f-064cfa0045d7.png)

When I fetch the order via the API, the total price is correct:

![image](https://user-images.githubusercontent.com/3394270/107519931-22abcd00-6bb1-11eb-8b10-094e7111c11c.png)

But the line item has a price of 1,199.20:

![image](https://user-images.githubusercontent.com/3394270/107520046-42db8c00-6bb1-11eb-88b1-951a2fe85200.png)

Which is wrong. The price of the line item should be 1,499.00.

I'm using Woocommerce 4.0.1 on top of Wordpress 5.4.4 hosted on Hostinger.

**Comment by adevade** [comment] 2021-02-10 21:21
The price is listed without tax. 

If you add the total and the tax for the line item you get the correct amount: `1199.20 + 299.80 = 1499.00`

**Comment by johnknoop** [comment] 2021-02-10 21:45
@adevade I see. So the "prices_includes_tax" property doesn't apply to the line items?

**Comment by johnknoop** [comment] 2021-02-11 11:47
`shipping_lines` appears to work differently.

I've opted to enter prices inclusive of tax:

![image](https://user-images.githubusercontent.com/3394270/107632495-dc18aa00-6c66-11eb-9290-44cc7c12cf0b.png)

So when I enter the flat rate shipping price, I assume I should enter it including the tax:

![image](https://user-images.githubusercontent.com/3394270/107632574-f783b500-6c66-11eb-9797-006bd43a7600.png)

And if that is the case, the API returns the shipping cost **including** tax:

![image](https://user-images.githubusercontent.com/3394270/107632350-ad9acf00-6c66-11eb-9cf5-2c0930259010.png)

**Comment by tammullen** [comment] 2021-02-11 21:15
Hi @johnknoop 

> So when I enter the flat rate shipping price, I assume I should enter it including the tax:

The Flate Rate Shipping Cost as mentioned on the tooltip is entered excluding tax.

![Screenshot_2021-02-11_at_21_09_09](https://user-images.githubusercontent.com/24649833/107699216-ad71f200-6cad-11eb-8be6-6cb0056606f3.png)

Everything else here seems to be working as expected.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-02-11 21:15 UTC

**Comment by johnknoop** [comment] 2021-02-12 16:05
@tammullen I see. So can you confirm if this is correctly understood then:

- If `prices_include_tax` is `true` then
  - `total` contains the sum total of the order including tax
  - All other properties, including `line_items`, `shipping` and `discount_total` are excluding tax
- If `prices_include_tax` is `false` then
  - `total` contains the sum total of the order excluding tax
  - All other properties, including `line_items`, `shipping` and `discount_total` are still excluding tax

Is this right?
