### ISSUE TITLE
Guest Checkout option: I cannot enable it in Woocommerce settings 

### ISSUE THREAD

**Issue by adch** [woocommerce/woocommerce#25824] opened 2020-03-05 08:24 UTC
When i try to enable the option Guest Checkout, after i click Save it just get unchecked.

PS. I never used this option (in this webisite), the need came up now.
 
## WordPress Environment

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.geopechlivanidis.gr
Site address (URL): https://www.geopechlivanidis.gr
WC Version: 3.9.3
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: ❌ 5.2.5 - There is a newer version of WordPress available (5.3.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.28
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 5120
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.44-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.1
WC Database Prefix: E_
Total Database Size: 118.13MB
Database Data Size: 103.96MB
Database Index Size: 14.17MB
E_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
E_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
E_woocommerce_order_items: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
E_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
E_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
E_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_actionscheduler_actions: Data: 2.52MB + Index: 0.95MB + Engine InnoDB
E_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_actionscheduler_logs: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
E_ac_abandoned_cart_history_lite: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
E_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
E_comments: Data: 0.47MB + Index: 0.28MB + Engine InnoDB
E_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_fb3d_pages: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
E_gmwfb_mapdetails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
E_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_newsletters: Data: 0.39MB + Index: 0.03MB + Engine InnoDB
E_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
E_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_newsletter_templates: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
E_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
E_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_segments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_sending_queues: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
E_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
E_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
E_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
E_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
E_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_mailpoet_subscribers: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
E_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_mailpoet_subscriber_segment: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
E_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_options: Data: 23.52MB + Index: 1.52MB + Engine InnoDB
E_postmeta: Data: 12.52MB + Index: 5.03MB + Engine InnoDB
E_posts: Data: 28.52MB + Index: 0.72MB + Engine InnoDB
E_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_revslider_css: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
E_revslider_css_bkp: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
E_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_revslider_sliders: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
E_revslider_sliders_bkp: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
E_revslider_slides: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
E_revslider_slides_bkp: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
E_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_termmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
E_terms: Data: 0.25MB + Index: 0.27MB + Engine InnoDB
E_term_relationships: Data: 0.41MB + Index: 0.22MB + Engine InnoDB
E_term_taxonomy: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
E_usermeta: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
E_users: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
E_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
E_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
E_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
E_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
E_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
E_wc_product_meta_lookup: Data: 0.14MB + Index: 0.31MB + Engine InnoDB
E_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
E_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
E_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wffilemods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
E_wfhits: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
E_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
E_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
E_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wflogins: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
E_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
E_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
E_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
E_wfstatus: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
E_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wpeditor_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_wpmll_magic_links: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
E_yith_wcwl: Data: 0.27MB + Index: 0.09MB + Engine InnoDB
E_yith_wcwl_lists: Data: 0.23MB + Index: 0.22MB + Engine InnoDB
E_yoast_seo_links: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
E_yoast_seo_meta: Data: 0.27MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

3d-flip-book: 2
attachment: 1880
custom_css: 2
gdpr_request: 1
gdpr_service: 11
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
mailpoet_page: 1
mpc_content_preset: 3
mtbf: 1
nav_menu_item: 213
oembed_cache: 8
option-tree: 1
page: 63
polylang_mo: 2
post: 44
product: 355
product_variation: 853
revision: 1010
shop_coupon: 6
shop_order: 268
static_block: 4
vc_grid_item: 1
vc_settings_preset: 4
wafs: 1
wcct_countdown: 3
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

Polylang: by WP SYNTEX – 2.6.10
Add-on Contact Form 7 - Mailpoet 3: by Tikweb – 1.3.13
Admin Menu Editor: by Janis Elsts – 1.9.3
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Electro Extensions: by MadrasThemes – 2.2.6 – Not tested with the active version of WooCommerce
Envato Market: by Envato – 2.0.3
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Google Map with FancyBox Popup: by Gopi Ramasamy – 2.5
Improved Sale Badges for WooCommerce: by Mihajlovic Nenad – 3.3.0 – Not tested with the active version of WooCommerce
Invisible reCaptcha: by Mihai Chelaru – 1.2.3
Jetpack by WordPress.com: by Automattic – 8.3
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
Loco Translate: by Tim Whitlock – 2.3.1
MailPoet 3 (New): by MailPoet – 3.45.0
ModelTheme Black Friday: by ModelTheme – 1.6.1 – Not tested with the active version of WooCommerce
Massive Addons for WPBakery Page Builder: by MassivePixelCreation – 2.4.6.1
Product Feed for WooCommerce: by WPWhale – 1.7.6
Redux Framework: by Team Redux – 3.6.17
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Slider Revolution: by ThemePunch – 5.4.8
Theme Editor: by mndpsingh287 – 2.3
Timologia for WooCommerce: by John Athanasiou – 2.6 – Not tested with the active version of WooCommerce
WC Custom Add to Cart labels: by Rynaldo Stoltz – 1.2
WooCommerce Smart COD: by Stratos Vetsos – 1.4.9.6 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.5.14
Variation Swatches for WooCommerce: by Emran Ahmed – 1.0.76
Abandoned Basket Lite for WooCommerce: by Tyche Softwares – 5.7.1
WooCommerce Admin: by WooCommerce – 0.23.3 – Not tested with the active version of WooCommerce
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.1.2 – Not tested with the active version of WooCommerce
WooCommerce Email Test: by RaiserWeb – 1.10 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.20
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.18
WooCommerce Product SKU Generator: by SkyVerge – 2.4.3
WooCommerce Product Stock Alert: by WC Marketplace – 1.6.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.4
WooCommerce Unit Of Measure: by Bradley Davis – 3.0.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.9.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Not tested with the active version of WooCommerce – Network enabled
Wordfence Security: by Wordfence – 7.4.6
WordPress GDPR: by weLaunch – 1.9.1
Yoast SEO: by Team Yoast – 13.2
WP Fastest Cache: by Emre Vona – 0.9.0.3
WP Mail SMTP: by WPForms – 1.8.1
ReCaptcha v2 for Contact Form 7: by IQComputing – 1.2.4
YITH WooCommerce Compare: by YITH – 2.3.18
YITH WooCommerce Social Login: by YITH – 1.3.9
YITH WooCommerce Wishlist: by YITH – 3.0.8

### Inactive Plugins (8) ###

3D FlipBook - Light Edition: by iberezansky – 1.9.20
Minimal Coming Soon & Maintenance Mode: by WebFactory Ltd – 2.17
One Click Demo Import: by ProteusThemes – 2.5.2
Protect WP-Admin: by MR Web Solution – 3.0.3
WooCommerce Print Invoice & Delivery Note: by Tyche Softwares – 4.5.3 – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: by realmag777 – 2.2.3 – Not tested with the active version of WooCommerce
WPForms Lite: by WPForms – 1.5.8.2
WP Magic Link Login: by Pixolette – 1.5.4

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #3853 - /shop/
Basket: #3134 - /cart/
Checkout: #3135 - /checkout/
My account: #3854 - /my-account/
Terms and conditions: #2183 - /oroi-kai-proipotheseis/

### Theme ###

Name: Electro Child
Version: 2.0.10
Author URL: https://madrasthemes.com/
Child Theme: ✔
Parent Theme Name: Electro
Parent Theme Version: 2.5.4
Parent Theme Author URL: https://madrasthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: electro/woocommerce/archive-product.php
electro-child/woocommerce/emails/admin-cancelled-order.php
electro/woocommerce/global/quantity-input.php


### Action Scheduler ###

Complete: 5,529
Oldest: 2020-02-03 10:22:56 +0200
Newest: 2020-03-05 10:12:40 +0200

Pending: 4
Oldest: 2020-03-05 10:27:40 +0200
Newest: 2020-03-05 11:03:41 +0200
```
`
</details>

**Comment by tammullen** [comment] 2020-03-05 11:41
Hi @adch 

Thank you for raising the issue. However, I can’t reproduce it on my end.
​
![Screenshot 2020-03-05 at 11 40 11](https://user-images.githubusercontent.com/24649833/75978301-1f568e80-5ed6-11ea-8d3b-017eca646981.png)
I can enable this setting ok on version 3.93

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-03-11 22:09
Hi @adch,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-03-11 22:09 UTC
Labels: can't reproduce, status: needs feedback
