### ISSUE TITLE
Woocommerce account/lost-password to /lost-password url change

### ISSUE THREAD

**Issue by Narendra93** [woocommerce/woocommerce#29933] opened 2021-05-18 06:53 UTC
Woocommerce how can i possible to account/lost-password to /lost-password url change.
I have used this code but not working for me.

I have write down in function.php file.

```
add_filter( 'lostpassword_url',  'wdm_lostpassword_url', 10, 0 );
 function wdm_lostpassword_url() {
  return site_url('/lost-password');
 }
```
 But not working 404 page not found.I need to change on website but not working that.
 Can you help me for this issue.

**Comment by zhongruige** [comment] 2021-05-18 20:59
Hi @Narendra93,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by zhongruige** 2021-05-18 20:59 UTC
