### ISSUE TITLE
Create New Order need info with the parameter

### ISSUE THREAD

**Issue by adampsb** [woocommerce/woocommerce#12224] opened 2016-11-01 07:32 UTC
in there i need info how i can input data using default api woocommerce ( class-wc-api-orders.php ) :

my problem now, is i dont know format what i need input so i get response :

```
{
  "errors": [
    {
      "code": "woocommerce_api_missing_callback_param",
      "message": "Missing parameter data"
    }
  ]
}
```
but i ve try input data on my postman :
![add](https://cloud.githubusercontent.com/assets/20830472/19882287/15fe1410-a03f-11e6-98dd-f932ace62f3d.png)

`[{
    "order": {
        "payment_details": {
            "method_id": "bacs",
            "method_title": "Direct Bank Transfer",
            "paid": true
        },
        "billing_address": {
            "first_name": "John",
            "last_name": "Doe",
            "address_1": "969 Market",
            "address_2": "",
            "city": "San Francisco",
            "state": "CA",
            "postcode": "94103",
            "country": "US",
            "email": "john.doe@example.com",
            "phone": "(555) 555-5555"
        },
        "shipping_address": {
            "first_name": "John",
            "last_name": "Doe",
            "address_1": "969 Market",
            "address_2": "",
            "city": "San Francisco",
            "state": "CA",
            "postcode": "94103",
            "country": "US"
        },
        "customer_id": 2,
        "line_items": [{
            "product_id": 546,
            "quantity": 2
        }, {
            "product_id": 613,
            "quantity": 1,
            "variations": {
                "pa_color": "Black"
            }
        }],
        "shipping_lines": [{
            "method_id": "flat_rate",
            "method_title": "Flat Rate",
            "total": 10
        }]
    }
}]`

have someone tell me whats wrong ? and show me how fill the parameter ?

thanks

woocommerce i use :
 * Plugin Name: WooCommerce
 * Plugin URI: https://www.woothemes.com/woocommerce/
 * Description: An e-commerce toolkit that helps you sell anything. Beautifully.
 * Version: 2.6.2
 * Author: WooThemes
 * Author URI: https://woothemes.com
 * Requires at least: 4.4
 * Tested up to: 4.5

**Comment by mikejolley** [comment] 2016-11-02 19:06
I don't think you're sending the JSON right. The JSON should be the body of the request, not under a specific param. I don't use postman, but this is how I send data in insomnia:

![2016-11-02 at 19 05](https://cloud.githubusercontent.com/assets/90977/19943479/7b4e875a-a12f-11e6-92e7-9c24f9701436.png)

There are no issues with the order api, so closing this as it's not a bug.

**Closed by mikejolley** 2016-11-02 19:06 UTC
