### ISSUE TITLE
Different languages on the dashboard

### ISSUE THREAD

**Issue by oweichpold** [woocommerce/woocommerce#26994] opened 2020-07-09 12:51 UTC
Woocommerce 4.3 is set to German, but on my dashboard texts are still displayed in english:

![woocommerce_4_3_dashboard](https://user-images.githubusercontent.com/6630469/87041943-452cd080-c1f3-11ea-8ef4-1f679c56ee1d.png)

The translation files are correct, apparently there is an error in the output.

Many thanks in advance!

Best regards!

**Comment by oweichpold** [comment] 2020-07-09 15:30
Short update, when I change the language to "German formal (Sie) - de_DE_formal", Woocommerce appears completely in English, only with de_DE it works (partially).

**Comment by juliaamosova** [comment] 2020-07-09 20:54
Hi @oweichpold,

Thank you for reporting the issue. I confirm that I can reproduce the same. Here is, for example, a detailed stats overview page of WooCommerce Admin (note that some strings are in German and some are in English):

![Screen Shot 2020-07-09 at 3 00 05 PM](https://user-images.githubusercontent.com/19143190/87084223-e15ad580-c1fb-11ea-851c-15517c0da4b8.png)

What I've done so far on the WooCommerce Core side of things:

- Confirmed that German translation is at 100% for WooCommerce (since testing German translation): https://translate.wordpress.org/projects/wp-plugins/woocommerce/

- Confirmed that the translation strings are available at https://translate.wordpress.org/

- Checked if there are new translations available via `Dashboard / Update / Translations` - there are new translations (at least on my test site) but the issue is not being solved after running translations update on my test site: 

![translations](https://user-images.githubusercontent.com/19143190/87089502-88dc0600-c204-11ea-8ede-cdd66712a214.jpg)

![Screen Shot 2020-07-09 at 4 47 42 PM](https://user-images.githubusercontent.com/19143190/87089518-8d082380-c204-11ea-8ecb-0ee48d2a0bfe.png)

- Checked how the issue was fixed previously (we encountered it before) but everything seems to be correct this time in that regard: https://github.com/woocommerce/woocommerce/pull/26339

We are still looking into this issue and will update this thread further with new details as soon as we have them.

**Comment by claudiosanches** [comment] 2020-07-13 14:04
Hello @oweichpold 

> Short update, when I change the language to "German formal (Sie) - de_DE_formal", Woocommerce appears completely in English, only with de_DE it works (partially).

So I just checked and I noticed that the `de_DE_formal` translation is implement, it's missing 252 strings to translate, you can see all missing strings in: https://translate.wordpress.org/locale/de/formal/wp-plugins/woocommerce/

Only the `de_DE` is complete, as you can see in: https://translate.wordpress.org/locale/de/default/wp-plugins/woocommerce/

**Comment by grigorijurasov** [comment] 2020-07-21 09:02
Hi!

Not sure if this is related, but I can't seem to translate "Gross sales", "Returns" and a few more strings. I've tried German, Spanish and English:

![Screenshot](https://d.pr/i/uywVf3+)
Screenshot direct link: https://d.pr/i/uywVf3

Translations are up-to-date, I'm using Loco Translate:

![Screenshot](https://d.pr/i/fH8lAS+)
Screenshot direct link: https://d.pr/i/fH8lAS

Reported in 3153210-zen

**Comment by josegallo** [comment] 2020-07-22 12:04
Hi, 

We have the strings for Analytics section of Woocommerce not being translated. We have tried:
- setting back the admin language to English, after that switching back to Spanish, with no change. 
- We also tried reinstalling WordPress.
- We have tested that woocommerce.po file is correctly translated and the issue keeps occurring with only WooCommerce and not other translated plugins as WPML and Loco activated and with a basic theme as Twenty Twenty

As examples of strings not being translated are (as grigorijurasov comments )  Returns -> devoluciones or Gross Sales -> Ventas Brutas.

If you want to see the complete tickets:
- with WPML https://wpml.org/forums/topic/strings-are-not-being-translated-on-woocommerce-analysis-section/#post-6626173 
- with woocommerce: https://woocommerce.com/my-account/tickets/?id=3153210

Could you help us, Is there any solution?
Thanks indeed

**Comment by grigorijurasov** [comment] 2020-08-04 07:13
It sounds like Javascript-based parts cannot be translated with the usual tools anymore. This is a different kind of task:

* https://pascalbirchler.com/internationalization-in-wordpress-5-0/

* https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/

* https://developer.wordpress.org/apis/handbook/internationalization/#internationalizing-javascript

**Comment by mrleemon** [comment] 2020-08-19 12:58
This problem persists in WooCommerce 4.4. In screens where JS is heavily used, most of the strings are in English, with a few only translated (PO files are 100% translated). Another issue is that accents are not printed in translated strings.

![woocommerce](https://user-images.githubusercontent.com/2060659/90637426-460e4480-e22c-11ea-9aff-f792f1a87b50.jpg)

**Comment by starypop** [comment] 2020-08-24 13:45
@mrleemon I've submitted the bug with accents at WooCommerce Admin repository: https://github.com/woocommerce/woocommerce-admin/issues/4854

I can also confirm that the original bug with mixed languages at Analytics section occurs with WC 4.4.1 and Polish language.

**Comment by starypop** [comment] 2020-09-09 14:34
@juliaamosova @peterfabian Any updates on this issue? WC Admin screens for non-english shop owners and managers are still not translated, labels are in English for more than 2 months now.

At least mark this issue as a Bug with high priority.

**Comment by juliaamosova** [comment] 2020-09-09 14:39
@starypop thanks for the ping here. And apologies for the delayed response. Adding a `high` priority here so that we could take a look further. 

Also linking this thread for a possible solution?: https://github.com/woocommerce/woocommerce/issues/27622.

**Comment by mrleemon** [comment] 2020-09-09 15:47
Thanks for the heads up! Just in case, the language problems persist in the recently released WooCommerce 4.5.

**Comment by Frisoni** [comment] 2020-09-11 15:15
My experience with WooCommerce Admin translations problems.

Before 4.4:
Admin translations were correctly called in WooCommerce, but there was some JS problems, solved in this issue: https://github.com/woocommerce/woocommerce-admin/issues/2336

After 4.4:
Admin translations are not called from WooCommerce. Translations files are not even downloaded to languages/plugins folder.
If I install and activated WooCommerce Admin plugin, translations are downloaded and everything works fine.
But, if I deactivate Admin, even with translations files in language/plugins folder translations are missing again.

It seems WooCommerce can't find correct path to download and check for woocommerce-admin translation files.

**Comment by rodrigoprimo** [comment] 2020-09-11 19:04
@jeffstieler should we create an issue on the woocommerce-admin repository or your team is already working on a fix for this? Thanks.

**Comment by jeffstieler** [comment] 2020-09-11 21:39
> @jeffstieler should we create an issue on the woocommerce-admin repository or your team is already working on a fix for this? Thanks.

We're working on a fix

**Closed** 2020-09-15 15:36 UTC
Labels: bug, i18n, priority: high
