### ISSUE TITLE
add_action for woocommerce_cart_calculate_fees to add_fee inside a payment gateway gets reset/deleted at checkout page

### ISSUE THREAD

**Issue by hounw** [woocommerce/woocommerce#26252] opened 2020-04-23 01:29 UTC
**Describe the bug**
When using action hook woocommerce_cart_calculate_fees inside a payment gateway (extends WC_Payment_Gateway) to add a fee (cart->add_fee) the fee shows up for a bit and after the checkout page finishes loading it gets deleted.

**To Reproduce**
add_action( 'woocommerce_cart_calculate_fees', array( $this, 'my_method_to_add_fee' ));

public function my_method_to_add_fee() {
	// add the fee
	WC()->cart->add_fee( 'Fee', 5 );
}

**Screenshots**
![Image 4](https://user-images.githubusercontent.com/7231700/80048812-79cf9c80-84ce-11ea-8b4e-4c1c87a9c12d.png)
![Image 5](https://user-images.githubusercontent.com/7231700/80048823-8227d780-84ce-11ea-850f-c1d7e63145f4.png)

**Expected behavior**
You see the fee and then the fee disappears.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://wptgt.tgt
Site address (URL): http://wptgt.tgt
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_MX
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.3.7
PHP Version: 7.3.7
PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.16-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient activada - puede que algunos plugins de pasarela de pago que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Tamaño total de la base de datos: 4.93MB
Tamaño de los datos de la base de datos: 3.17MB
Tamaño del índice de la base de datos: 1.76MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_itsec_distributed_storage: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_itsec_fingerprints: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_itsec_geolocation_cache: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_itsec_lockouts: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_itsec_logs: Datos: 0.09MB + Índice: 0.09MB + Motor InnoDB
wp_itsec_mutexes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_itsec_opaque_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_itsec_temp: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_itsec_user_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options: Datos: 2.03MB + Índice: 0.06MB + Motor InnoDB
wp_postmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_posts: Datos: 0.06MB + Índice: 0.06MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 1
custom_css: 1
et_pb_layout: 1
page: 6
post: 3
product: 2
product_variation: 2
revision: 12
shop_order: 2

### Security ###

Secure connection (HTTPS): ❌
					Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (6) ###

iThemes Security Pro: por iThemes – 6.4.2
Loco Translate: por Tim Whitlock – 2.3.1
Webicommerce: por Webifica – 0.1.2 – No probado con la versión activa de WooCommerce
Webifica Configurations: por Webifica – 0.0.2
Webifica Woocommerce Pagalo Payment Gateway: por Webifica – 0.0.1 – No probado con la versión activa de WooCommerce
WooCommerce: por Automattic – 4.0.1

### Inactive Plugins (2) ###

WooCommerce Pagogt payment gateway: por Webifica – 0.0.1 – No probado con la versión activa de WooCommerce
WP Mail SMTP: por WPForms – 1.6.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GTQ (Q)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #7 - /tienda/
Carrito: #8 - /carrito/
Finalizar compra: #9 - /finalizar-comprar/
Mi cuenta: #10 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Divi
Version: 3.26.6
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completar: 37
Oldest: 2020-04-22 17:43:47 +0000
Newest: 2020-04-22 18:57:51 +0000

`
</details>

**Comment by juliaamosova** [comment] 2020-05-06 18:05
Hi @hounw,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

As an alternative, we have a plugin available on our Marketplace that lets you add payment gateway based fees: [Payment Gateway Based Fees](https://woocommerce.com/products/payment-gateway-based-fees/). 

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-05-06 18:05 UTC

**Comment by hounw** [comment] 2020-05-06 20:36
@juliaamosova 

Sorry I mean to contribute, I can't confirm it's a BUG since I didn't code woocommerce, but it is at the very least, an undocumented feature.

Here is the gist of it:

Issue:
Whatever fee applied in a method inside the PG class, is deleted, it makes it impossible to add a fee inside the payment gateway class.

Workaround:
The way I fixed it is to add the fee at the "plugin" level (good ol' fashioned wp plugin code no classes) and get the config from the payment gateway plugin so the store owner can setup the fee inside the payment gateway standard configurations. Same code, just outside the payment gateway class.

As I said, I mean to contribute, if this is expected behavior at the very least it deserves a mention somewhere (here?) for future devs to know that it is impossible to add a fee inside a payment gateway class method, it gets reset by the system at some point.

Cheers!
