### ISSUE TITLE
woocommerce change stockstatus

### ISSUE THREAD

**Issue by craven89** [woocommerce/woocommerce#29937] opened 2021-05-18 18:58 UTC
hello,

I'm building a webshop and i want to change the name of the stock status "in backorder" to "order article". so people can  buy the product that i don't have in stock and than i order it and send it later (or by dropshipment).
people on woocommerce gave me the idea for a paying plugin but for the litle change i wan't to make 49$/ year is to expensive for me (also i'm starting my business so don't want to waste my money on this plugin for such a litle "thing" i want to change...)

they also give me the idea to contact you guys if you maybe have a solution for this here.
i looked already but didn't find it right away...

thnx you for your time!
kind regards,
J.

**Comment by zhongruige** [comment] 2021-05-18 20:32
Hi @craven89,

I did a quick search for plugins that may work that are freely available, and found the following:

* [Woo Custom Stock Status](https://wordpress.org/plugins/woo-custom-stock-status/)

If that plugins doesn't work, then most likely this will require adding in custom code. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by zhongruige** 2021-05-18 20:32 UTC
