### ISSUE TITLE
Customer account info not displaying after login

### ISSUE THREAD

**Issue by hagbeb** [woocommerce/woocommerce#25579] opened 2020-02-05 00:40 UTC
When returning users log into my site on the My Account page, the page just refreshes and looks as it did before. My Sucuri logs say that user login was successful, but none of their personal account info is displayed. The page appears as it does by default. New users that are created since I noticed the bug, and any user where I have reset their password in the backend, are able to login with their info correctly displayed. 

**To Reproduce**
Trying to login to worldsfair.co.uk on My Account page using my previously created test account.

**Screenshots**
![what the screen actually looks like](https://user-images.githubusercontent.com/60677150/73800312-3ce9e880-47b0-11ea-955d-feb05dbc0b2f.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).[tried using Twenty Twenty]
- [x ] I can reproduce this bug consistently using the steps above.

Other steps I have attempted:
1. disabling Cloudflare and purging cache (though I don't use cache by default anyway)
2. deleting all custom .htaccess files and custom functions, and resetting default .htaccess files by saving settings in WordPress > Settings > Permalinks
3. downloading fresh wp-login.php file from latest WordPress version and replacing existing login file with it.
4. removing custom login page that I am using via All in One WP Security and Firewall
5. adding these two lines of code to wp-config.php  (but with actual URLs)
define('WP_HOME','http://www.mysite.com');
define('WP_SITEURL','http://www.mysite.com');
6. cleaning and optimizing database using WP Optimize
7. reinstalling WordPress using the option in dashboard > Updates
8. changing non-password user settings in WordPress backend
9. changing user settings in phpMyAdmin, including changing encrypted password value, saving, then changing back to original, and saving again.

**WordPress Environment**
worldsfair.co.uk
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WordPress address (URL): https://worldsfair.co.uk
Site address (URL): https://worldsfair.co.uk
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.2
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.64-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: 3swe9Ab86_
Total Database Size: 13.34MB
Database Data Size: 11.46MB
Database Index Size: 1.88MB
3swe9Ab86_woocommerce_sessions: Data: 0.15MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
3swe9Ab86_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_aiowps_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_aiowps_failed_logins: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_aiowps_global_meta: Data: 3.17MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_aiowps_login_activity: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_aiowps_login_lockdown: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_comments: Data: 0.32MB + Index: 0.21MB + Engine MyISAM
3swe9Ab86_dynamic_widgets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_evf_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_evf_entrymeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_evf_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_gg_attributes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_gg_galleries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_gg_galleries_resources: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_gg_photos: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_gg_settings_sets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_gg_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_imagify_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_imagify_folders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_lockdowns: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_login_fails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_ngg_album: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_ngg_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_ngg_pictures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_options: Data: 2.22MB + Index: 0.26MB + Engine MyISAM
3swe9Ab86_postmeta: Data: 0.95MB + Index: 0.22MB + Engine MyISAM
3swe9Ab86_posts: Data: 0.47MB + Index: 0.17MB + Engine MyISAM
3swe9Ab86_redirection_404: Data: 3.65MB + Index: 0.71MB + Engine MyISAM
3swe9Ab86_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_redirection_items: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
3swe9Ab86_redirection_logs: Data: 0.15MB + Index: 0.04MB + Engine MyISAM
3swe9Ab86_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_term_relationships: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
3swe9Ab86_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_usermeta: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
3swe9Ab86_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_wpml_mails: Data: 0.20MB + Index: 0.00MB + Engine MyISAM
3swe9Ab86_yoast_seo_links: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
3swe9Ab86_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 231
contx_post_type: 1
custom_css: 1
envira: 2
ft_gallery: 4
mg_items: 38
nav_menu_item: 42
ngg_gallery: 1
ngg_pictures: 5
nimble_post_type: 1
option-tree: 1
page: 17
post: 20
product: 66
revision: 5
scheduled-action: 1045
shop_order: 15
shop_order_refund: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

AddToAny Share Buttons: by AddToAny – 1.7.39
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.3

Antispam Bee: by pluginkollektiv – 2.9.1
Autoptimize CriticalCSS.com Power-Up: by Deny Dias & Optimizing Matters – 1.18.0
Autoptimize: by Frank Goossens (futtta) – 2.6.1
Cookie Notice: by dFactory – 1.2.50
Featured Image Caption: by Christiaan Conover – 0.8.9
Feed Them Gallery Premium: by  – 1.1.1 – Not tested with the active version of WooCommerce
Feed Them Gallery: by SlickRemix – 1.2.6 – Not tested with the active version of WooCommerce
Google Authenticator: by Ivan Kruchkoff – 0.52
Inactive Logout: by Deepen Bajracharya – 1.9.3
Media Grid: by Luca Montanari – 6.47
Moosend Website Tracking: by Moosend – 1.0.176
Moosend For WordPress: by Moosend – 1.0.115
No Right Click Images Plugin: by Keith P. Graham – 3.4
Redirection: by John Godley – 4.6.2
SiteOrigin CSS: by SiteOrigin – 1.2.4
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.22
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.21

Widget Options: by Widget Options Team – 3.7.4
WooCommerce: by Automattic – 3.9.1
Yoast SEO: by Team Yoast – 12.9.1
WP Super Cache: by Automattic – 1.7.1

### Inactive Plugins (1) ###

WooCommerce Admin: by WooCommerce – 0.24.0 – Not tested with the active version of WooCommerce

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #143 - /shop/
Basket: #145 - /basket/
Checkout: #147 - /checkout/
My account: #149 - /my-account/
Terms and conditions: #2114 - /terms-and-conditions/

### Theme ###

Name: Bam Child Theme
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Bam
Parent Theme Version: 1.1.0
Parent Theme Author URL: https://themezhut.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,043
Oldest: 2020-01-05 00:48:44 +0000
Newest: 2020-02-03 23:08:31 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 2
Oldest: 2020-02-03 18:58:39 +0000
Newest: 2020-02-03 18:58:40 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by juliaamosova** [comment] 2020-02-10 16:49
Hi @hagbeb,

Thank you for raising the issue. However, I can’t reproduce it on my end.

Here I am logged in as a customer and can see my order:

![order](https://user-images.githubusercontent.com/19143190/74170612-1949f680-4c25-11ea-9d74-569a617d9866.jpg)

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. 

I see also that you marked that you tested for a theme and plugins conflict, however, I always like to confirm.

If you haven't done so yet, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by hagbeb** [comment] 2020-02-11 01:09
Hi,

I tested it again tonight with all plugins (except WooCommerce) disabled, and had the same problem. I also tested it with the plugins disabled and using Storefront theme (I had previously testing using TwentyTwenty theme), and again the problem was there. It only relates to accounts created before a certain point (at least Feb 3). Newer accounts, and old accounts but with a new password generated, are OK. Bear in mind that my logs say login was successful, but user info doesn't display properly, the page just appears to refresh.

If you like, you can test it using the test account I set up:
Login: wjboffiii@gmail.com
PW: testgmail
Login URL: https://worldsfair.co.uk/my-account/

The email is my real email address so please do not share, and delete when finished testing.

Many thanks,

hagbeb
________________________________

**Comment by tammullen** [comment] 2020-02-19 00:21
@hagbeb Just to make you aware replying to Github Issue notification emails will show your reply on the public issue. I have deleted sensitive data you included.

**Comment by juliaamosova** [comment] 2020-02-27 21:20
Hi @hagbeb, thanks for getting back here and apologies for the delayed response. 

It is really difficult to tell what could be going on in your case. It does look specific to your setup as well as we haven't received similar reports lately and could not reproduce the same either. 

Have you tried reproducing this on a brand new WordPress + WooCommerce installation and using perhaps another hosting company?

**Comment by juliaamosova** [comment] 2020-03-11 22:45
Hi @hagbeb,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-03-11 22:45 UTC
Labels: can't reproduce, status: needs feedback
