### ISSUE TITLE
product cart doesnt show product images

### ISSUE THREAD

**Issue by axcar95** [woocommerce/woocommerce#27691] opened 2020-09-16 16:57 UTC
hi. ı am working at turquazarts.com 
and my product cart in responsive is complete mess. in responsive my product images doesnt shown unlike the desktop version which is fine. and because of my products long names one product covers the whole screen. ı need to set a limit for how much space a product covers in the cart page and ı cant find the product images.
is there anybody to help me with this issues?
thanks a lot.
![Screenshot_3](https://user-images.githubusercontent.com/48660460/93368634-e8830d00-f856-11ea-9ab3-04f4a4d65073.jpg)

**Comment by juliaamosova** [comment] 2020-09-16 17:56
Hi @axcar95,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-09-16 17:56 UTC

**Comment by axcar95** [comment] 2020-09-16 19:06
actually the fact taht responsive product image didnt appear is a bug i suppose. but you know better
