### ISSUE TITLE
Duplicate note order - Woocommerce - Wordpress 

### ISSUE THREAD

**Issue by stoicafloringeorge** [woocommerce/woocommerce#26201] opened 2020-04-16 19:54 UTC
Hello,

Please help me to solve this problem on woocommerce orders for wordpress 5.4. 
If a customer order a product and re-view the order details it is generated 2 notes with the same details (different language). 

1. Thursday 16th of April 2020, 10:46am

Plata receptionata.
Comanda este in curs de procesare.
Vom face livrarea in curand.
NETOPIA Transaction ID: 1053872

2. Thursday 16th of April 2020, 10:46am

Payment Received.
Your order is currently being processed.
We will be shipping your order to you soon.
MobilPay Transaction ID: 1053872

![image](https://user-images.githubusercontent.com/61707524/79500434-14466080-8035-11ea-9bdd-1d088975a247.png)

Please let me know if you have any ideas.

Regards,
Florin

**Comment by tammullen** [comment] 2020-04-17 22:48
Hi @stoicafloringeorge 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
Label:

**Closed by tammullen** 2020-04-17 22:48 UTC
