### ISSUE TITLE
Pre-populate checkout form fields passing variables in the url

### ISSUE THREAD

**Issue by frnkoc** [woocommerce/woocommerce#26530] opened 2020-05-15 21:04 UTC
Issue:
Hi. I was able to pre-populate wc checkout forms with the following parameters in prior version of WC: https://site.com/?add-to-cart=1234&firstname=NAME&lastname=LNAME

I guess recent wc updates changed the name of the autocomplete fields. Now the same fields are:
?given-name=NAME&family-name=LNAME but this is not passing the values like before either.

I found this article that suggest using the actual field id  not the the autocomplete field names. This doesn't work either.

https://buildwoofunnels.com/docs/aerocheckout/parameters/pre-populate-checkout-form-data-using-parameters/

Was this an intentional change of wc core? what else would impact this?
what is the correct way to pre-populate fields in woocommerce version 4.1.0 checkout form using the autocomplete tags?

Thanks 
FC

**Comment by tammullen** [comment] 2020-05-19 13:54
Hi @frnkoc 

Thank you for submitting the issue. 

However, I can’t reproduce the issue you reported as I don't believe we have ever provided pre-populating checkout fields solely by passing them from the URL.

It may be possible to achieve what you are describing by adding some custom code that can detect the parameters in the URL and populate the fields. This is likely what the 3rd party plugin documentation you linked to does.
​​
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it and the other information we ask for in the bug reporting template.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-05-19 13:54 UTC
