### ISSUE TITLE
Product attributes deleted after 3.6.2 Update

### ISSUE THREAD

**Issue by frankymagana** [woocommerce/woocommerce#23586] opened 2019-05-02 07:45 UTC
**Describe the bug**
All product attributes were deleted after the update.

**To Reproduce**
Update to 3.6.2

**Expected behavior**
Nothing to get deleted.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://www.qualitydme.com
Site URL: http://www.qualitydme.com
WC Version: 3.5.6
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.28 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 19.94MB
Database Data Size: 16.59MB
Database Index Size: 3.35MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.13MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.27MB + Index: 0.38MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.16MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.08MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.47MB + Index: 0.08MB
wp_postmeta: Data: 2.52MB + Index: 0.61MB
wp_posts: Data: 4.52MB + Index: 0.34MB
wp_redirection_404: Data: 0.08MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_rg_zapier: Data: 0.02MB + Index: 0.02MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Categories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB
wp_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tags: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Videos: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.08MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfConfig: Data: 0.41MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 2.52MB + Index: 0.00MB
wp_wfHits: Data: 0.02MB + Index: 0.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.06MB + Index: 0.03MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 446
nav_menu_item: 18
page: 23
post: 19
product: 40
product_variation: 94
responsive_accordion: 2
revision: 659

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (31) ###

ManageWP - Worker: by GoDaddy – 4.7.7
Gravity Forms: by rocketgenius – 2.4.8
Redux Framework: by Team Redux – 3.6.15
AddToAny Share Buttons: by AddToAny – 1.7.35
Admin Menu Editor: by Janis Elsts – 1.8.8
All-in-One WP Migration: by ServMask – 6.92
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.3

HIPAA Forms: by Code Monkeys LLC – 2.1.7
Display Posts: by Bill Erickson – 3.0.1
Fuse Social Floating Sidebar: by Daniyal Ahmed – 4.0
Genesis Connect for WooCommerce: by StudioPress – 1.0 – Not tested with the active version of WooCommerce
Genesis Portfolio Pro: by StudioPress – 1.2.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.6.0
Gravity Forms Survey Add-On: by rocketgenius – 3.3
Members: by Justin Tadlock – 2.1.0
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.7.6
Redirection: by John Godley – 4.2.3
Responsive Accordion And Collapse: by wpshopmart – 2.0.8
Search & Replace: by Inpsyde GmbH – 3.2.0
SG Optimizer: by SiteGround – 5.1.2
Simple Social Icons: by StudioPress – 3.0.0
Smart Variations Images for WooCommerce: by David Rosendo – 4.0.24
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.14

W3 Total Cache: by Frederick Townes – 0.9.7.3
What The File: by Never5 – 1.5.4
Widget Importer & Exporter: by ChurchThemes.com – 1.5.5
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.5

WooCommerce: by Automattic – 3.5.6 – 3.6.2 is available
Yoast SEO: by Team Yoast – 11.1
Smush: by WPMU DEV – 3.2.0.1
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.6.10


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Studio Pro
Version: 2.1.3
Author URL: http://www.seothemes.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.10.0
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by kloon** [comment] 2019-05-02 12:43
Your system status report indicates you are running 3.5.6 and not 3.6?

**Comment by frankymagana** [comment] 2019-05-02 15:33
Yea, I got the report after restoring back to the last version. 

-franky

**Comment by claudiosanches** [comment] 2019-05-06 21:38
>  Update to 3.6.2

I'm not able to reproduce, closing since it's not possible to reproduce, please let us know if this issue persists and if you find what to reproduce.
Thanks.

**Comment by frankymagana** [comment] 2019-05-06 21:53
I did update. That’s what causes the issue. It’s easy to reproduce. I simply update and it causes the issue.

The report was created after I had restored to previous update. 

-franky

**Comment by kloon** [comment] 2019-05-07 06:52
@frankymagana neither me nor @claudiosanches are able to replicate this using the steps you describe. Also, you ticked you tested with just WooCommerce and with a default theme activated but from your system status report it shows that you have 31 plugins active as well as not using a default theme so the issues could be a theme conflict.

It is also possible that you experienced this straight after updating while the DB upgrade routine were still running, you need to give it some time to complete in order for the new lookup tables to populate, if you do not then you will have missing products and info while the upgrade routine is running in the background.

**Comment by frankymagana** [comment] 2019-05-15 06:47
I’m gave this another try and same results. Please help.


Here are the steps I took:

I deactivated all plugins (I left Updraft plus because that’s what I was using to restore, but i all tried will this deactivated too.)
Used a default theme
Updated WooCommerce (My attributes are there at this point)
Update the WC database
Then my attributes are deleted
DB Updated said it was done. Then I waited 20 mins (Still nothing)

Here is my new report

`
### WordPress Environment ###

WordPress address (URL): http://www.qualitydme.com
Site address (URL): http://www.qualitydme.com
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 18.87MB
Database Data Size: 15.54MB
Database Index Size: 3.33MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.13MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.27MB + Index: 0.38MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.16MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.08MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.50MB + Index: 0.06MB
wp_postmeta: Data: 2.52MB + Index: 0.61MB
wp_posts: Data: 4.52MB + Index: 0.34MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_rg_zapier: Data: 0.02MB + Index: 0.02MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Categories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB
wp_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tags: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Videos: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfConfig: Data: 0.41MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 2.52MB + Index: 0.00MB
wp_wfHits: Data: 0.02MB + Index: 0.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.06MB + Index: 0.03MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 449
nav_menu_item: 18
page: 23
post: 15
product: 40
product_variation: 94
responsive_accordion: 2
revision: 671
scheduled-action: 14

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.14

WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (30) ###

AddToAny Share Buttons: by AddToAny – 1.7.36
Admin Menu Editor: by Janis Elsts – 1.9
All-in-One WP Migration: by ServMask – 6.93
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.3

Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.6.10

Display Posts: by Bill Erickson – 3.0.2
Fuse Social Floating Sidebar: by Daniyal Ahmed – 4.0
Genesis Connect for WooCommerce: by StudioPress – 1.0 – Not tested with the active version of WooCommerce
Genesis Portfolio Pro: by StudioPress – 1.2.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.6.0
Gravity Forms: by rocketgenius – 2.4.9
Gravity Forms Survey Add-On: by rocketgenius – 3.3
HIPAA Forms: by Code Monkeys LLC – 2.2.0
ManageWP - Worker: by GoDaddy – 4.8.0
Members: by Justin Tadlock – 2.1.0
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.7.6
Redirection: by John Godley – 4.2.3
Redux Framework: by Team Redux – 3.6.15
Responsive Accordion And Collapse: by wpshopmart – 2.1
Search & Replace: by Inpsyde GmbH – 3.2.0
SG Optimizer: by SiteGround – 5.1.2
Simple Social Icons: by StudioPress – 3.0.0
Smart Variations Images for WooCommerce: by David Rosendo – 4.0.25
Smush: by WPMU DEV – 3.2.0.1
W3 Total Cache: by Frederick Townes – 0.9.7.4
What The File: by Never5 – 1.5.4
Widget Importer & Exporter: by ChurchThemes.com – 1.5.5
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.5

YITH WooCommerce Ajax Product Filter: by YITH – 3.6.3
Yoast SEO: by Team Yoast – 11.1.1 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 14
Oldest: 2019-05-15 02:39:33 -0400
Newest: 2019-05-15 02:41:33 -0400

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by claudiosanches** [comment] 2019-05-16 19:52
@frankymagana still there's something strange on it, I'm not able to reproduce as you are saying, and this kind of bug should be cause problems for more users if is an issue on WooCommerce, I haven't see any reports like that.

**Comment by frankymagana** [comment] 2019-05-16 21:25
Would you like for me to set up a staging website and give you access?

If not, how do you think I should go about updating. About 20 products use the attributes, also use attributes for search filters.

Is there a way to update, then import those attributes and still have them assigned to each product?

-franky

**Comment by mikaelbang** [comment] 2019-05-17 07:41
This also happened to me yesterday when updating from 3.5.4 to 3.6.2. This was on a Multisite install and on the main site the update worked fine but on the other connected site the attributes were deleted.

**Comment by GlennMartin1** [comment] 2019-05-17 17:30
Hopefully this will be helpful:

(I believe) there is an un-diagnosed product attribute bug that appears sometimes when upgrades are done, but everyone's failing to reproduce it.

See https://github.com/woocommerce/woocommerce/issues/21338
And see https://wordpress.org/support/topic/product-attributes-disappeared/

At this last link, someone suggested:
> Hi, this is solved, I got a solution from one backend developer. He said that he has saw this problem on multiple websites. Solution is to add new random attribute in products > attributes and after I have done that all my old attributes and variations were back.

I had exactly the same issue, and resolved it in this way, but I have never been able to reproduce it. I'd be interested if this resolves it for you.

If anyone can reproduce it, that should be a Github issue, but until then....

**Comment by claudiosanches** [comment] 2019-05-20 13:01
Maybe not related, since Frank's system status says `WP Multisite: –`, or do you are using Multisite @frankymagana ?

**Comment by pihedy** [comment] 2019-05-22 07:33
This is also a problem with us. There is a problem with 'Load variations via Ajax' javascript code. 

When you change an attribute for a product or create it, it will appear. Clicking the save button collects all the attributes that have been added and sends the request. Select2 breaks and does not receive formatting, and then retrieves attribute data. But the entire attribute field is now empty. I clicked on xdebugger all the way and the problem was found within the wrapper variable. At ajax request, the attributes variable (attributes: wrapper.data ('attributes')) is empty. And drawing back returns empty attributes. If I do not click the save attributes button but simply update it, it will go down well.

Otherwise, this problem also occurs with version 3.5.8 because we are currently using it, but yesterday I upgrade from 3.4.x. This issue has been coming up since the update yesterday.

**Comment by tonybahama** [comment] 2019-05-24 11:16
Any news? We also experience this exact same problem!

**Comment by kristof9401** [comment] 2019-05-24 12:48
A have also experience this problem.

**Comment by vigoncas** [comment] 2019-05-25 15:01
Hi guys,

similar problem. After update Woocommerce to 3.6.3 in a multisite Wordpress 4.7.13, some attributes are not showed in autocomplete selects. In attribute lists some attributes are not showed but are counted in the number of records of the list.

Thkx

**Comment by 10h30** [comment] 2019-05-30 16:32
Hello,

I also experience the exact problem. After update Woocommerce to 3.6.1, 3.6.2, 3.6.3 or the latest 3.6.4, 99% of my attributes are gone. Rolling back to 3.5.7 solves the problem.

**Comment by tonybahama** [comment] 2019-05-30 18:37
3.5.8 has the same problem
meaning this has something to do with this issue:
 * Security - Added escaping for SelectWoo selected options.

**Comment by evincedev** [comment] 2019-07-02 07:57
I got the same issue today. I had so many attributes and all are gone..

**Comment by frankymagana** [comment] 2019-07-17 18:32
Just realized this is caused simply by adding a new attribute from Products> Attributes. Not even having to update and it happens.

**Comment by claudiosanches** [comment] 2019-07-31 20:57
@tonybahama
> 3.5.8 has the same problem
> meaning this has something to do with this issue:
> 
>     Security - Added escaping for SelectWoo selected options.

Doesn't sounds like to be a problem, since it should affect more people than we have in this thread, also should break another parts of WooCommerce, not only hiding or deleting attributes.

**Comment by claudiosanches** [comment] 2019-07-31 21:04
@frankymagana

> Just realized this is caused simply by adding a new attribute from Products> Attributes. Not even having to update and it happens.

I can't reproduce it, maybe caused by a 3rd party plugin?
Also those terms are really deleted, have you checked in the database?

I'm closing it since there's no steps to reproduce it, and also sounds related to a 3rd party plugin or code.

**Closed by claudiosanches** 2019-07-31 21:04 UTC

**Comment by tonybahama** [comment] 2019-08-01 05:18
Still a problem, only solved by changing a Woo core file.

Would you like to get the modified file?

**Comment by frankymagana** [comment] 2019-08-01 06:52
Not sure what the best solution for someone with many lost attributes. But here is what I did to get mine back.

I only have 4 attributes with several terms.

1. I updated WooCommerce (Attributes disappear)
2. Added my attributes 1 by 1 (with exact slug)
3. On each, I clicked on "Configure Terms" and all terms reappeared.

I just did that for each attribute and each attribute and product was still intact. Hope that could be a solution for someone else too.

**Comment by claudiosanches** [comment] 2019-08-02 21:57
@tonybahama please submit a pull request.

**Comment by tonybahama** [comment] 2020-02-06 22:42
@pihedy please submit a pull request for this if the problem still happens on our site

**Comment by stian-overasen** [comment] 2020-05-13 10:34
This still keeps happening on all WooCommerce updates on multisites, lastly from 4.0.0 til 4.0.1. The `wp_woocommerce_attribute_taxonomies` is cleared and all taxonomies must the manually put back one by one. The terms reappear when the taxonomy with the correct slug is reintroduced like @frankymagana pointed out.

**Comment by mcmito** [comment] 2021-04-06 15:56
One year later and the problem is still there. I´m having this problem right now after upgrading to 5.1.0. Fun.
