### ISSUE TITLE
Issue on Expedition

### ISSUE THREAD

**Issue by JonathanRanz** [woocommerce/woocommerce#27815] opened 2020-09-30 16:22 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
![image](https://user-images.githubusercontent.com/72154316/94711905-08cbc500-0349-11eb-942d-0423f581f7f4.png)

**Describe the bug**
We have written (copy/paste) too much Postal Code (Maybe 30000) and the api take too long time to get the Expedition page as the image below :
![image](https://user-images.githubusercontent.com/72154316/94712150-5ba57c80-0349-11eb-9d2a-da63b7d59586.png)

**Expected behavior**
When I click on Expedition I'm able to customize this part.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. I click on Expedition 
2. It takes long times and an error message is displayed : Fatal error: Maximum execution time of 30 seconds exceeded in /homepages/22/d844513318/htdocs/app844513500/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php on line 692

Is is possible for you to delete what we have today on expedition part and we will redo this part ? 

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment] 2020-09-30 19:58
Hi @JonathanRanz 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-09-30 19:58 UTC
