### ISSUE TITLE
Invalid or duplicated SKU

### ISSUE THREAD

**Issue by bstori** [woocommerce/woocommerce#15981] opened 2017-07-05 19:50 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Open Product
2. Update Product, I just was trying to update a product form out of stock to back in stock
3. click the update button
4. I got the error Invalid or duplicated SKU, even on the variation I was not updating. 

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...the product to save, so I can publish my changes and get my out of stock product back on my online store.

## Environment

Wordpress with the latest version of wordpress
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: http://rspnutrition.com
Site URL: http://rspnutrition.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 600 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔  1 active Zapier Feed.
Zapier Integration - Cron Tasks: ✔  0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔  Zap New Order Save as Salesforce Lead
Zapier Feed #1 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/2147565/1ruh53/
Zapier Feed #1 Trigger: ✔  New Order
Zapier Feed #1 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/2147565/1ruh53/.

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: HR4Ng_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (74) ###

Gravity Forms: by rocketgenius – 2.2.3
Advanced Custom Fields PRO: by Elliot Condon – 5.5.14
Affiliates Coupons: by itthinx – 1.2.0
Affiliates Enterprise: by itthinx – 2.17.0
Affiliates Export: by itthinx – 1.0
Affiliates Gravity Forms Integration: by itthinx – 1.2.4
Affiliates Role: by itthinx – 1.0.0
Affiliates WooCommerce Views: by itthinx – 1.0.0
Affiliates WooCommerce Integration: by itthinx – 1.7.1
Campaign Monitor Ajax Forms: by Lee Willis – 1.5.0
Alpine PhotoTile for Instagram: by the Alpine Press – 1.2.7.7
BAW Login/Logout menu: by Juliobox – 1.3.3
Campaign Monitor for WooCommerce: by Campaign Monitor – 1.3.2
Carts Guru WooCommerce Plugin: by Carts Guru – 1.4.0
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.10
Edit Author Slug: by Brandon Allen – 1.5.2
Export User Data: by Q Studio – 1.3.1
GEO my WP: by Eyal Fitoussi – 2.7
Gravity Forms Geolocation Add-on: by Eyal Fitoussi – 2.4
Gravity Forms Approvals: by Steve Henty – 1.0.1
Gravity Forms Campaign Monitor Add-On: by rocketgenius – 3.5
Gravity Forms User Registration Add-On: by rocketgenius – 3.7
WooCommerce Variation Report: by Infosoft Consultants – 3.3
Import users from CSV with meta: by codection – 1.10.6.5
Instagram Feed: by Smash Balloon – 1.4.9
Itthinx Updates: by itthinx – 1.2.0
Login and Logout Redirect: by patilswapnilv – 1.0.3
MailChimp for WooCommerce: by MailChimp – 2.0.0
Menu Items Visibility Control: by Hassan Derakhshandeh – 0.3.5
Multiple Roles: by Florian TIAR – 1.1.4
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by XAdapter – 1.2.0
Status Tracking Plugin: by Etoile Web Design – 2.9.7
PayPal for WooCommerce: by Angell EYE – 1.4.5
Post Types Order: by Nsp Code – 1.9.3.1
PW WooCommerce BOGO Free: by Pimwick
LLC – 1.2

Recover Abandoned Cart: by Fantastic Plugins – 14.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Scripts n Styles: by unFocus Projects – 3.4.0
Simple Share Buttons Adder: by Simple Share Buttons – 6.3.6
Sitemap: by webvitaly – 4.3
SSL Insecure Content Fixer: by WebAware – 2.4.0
Super Store Finder Wordpress: by Joe Iz – 3.5
Uber Login Logo: by UberWeb – 1.5.1
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.5

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.13.4.21

UPS (BASIC) WooCommerce Shipping: by XAdapter – 1.2.4
User Meta Manager: by Jason Lau – 3.4.9
User Shortcodes: by HappyPlugins – 1.0.1
WooCommerce USAePay Payment Gateway: by Oragon – 1.2.2
Weglot Translate: by Remy B – 1.4.6
Woocommerce Advanced Bulk Edit: by George Iron – 3.9.2
WooCommerce Customizer: by SkyVerge – 2.5.0
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.9
Woocommerce Table Rate Shipping: by JEM Plugins – 1.2.3
Follow-Up Emails: by WooThemes – 4.4.18 – 4.4.20 is available
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce Multiple Free Gift PRO: by Ankit Pokhrel – 1.2.3
WooCommerce Product Bundles: by SomewhereWarm – 5.3.1
WooCommerce Shipping Per Product v2: by WooThemes – 2.2.8 – 2.2.10 is available
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.16
WooCommerce Square: by WooCommerce – 1.0.19 – 1.0.20 is available
WooCommerce - Store Exporter Deluxe: by Visser Labs – 2.3.5.1
WooCommerce Subscriptions: by Prospress Inc. – 2.2.7 – 2.2.8 is available
WooCommerce Waitlist: by Neil Pie – 1.5.5
WooCommerce Zapier Integration: by OM4 – 1.6.7 – 1.6.8 is available
WooCommerce: by Automattic – 3.1.0
WordPress Login Redirect: by Christopher Ross – 2.5.0
Yoast SEO: by Team Yoast – 4.9
WP All Import Pro: by Soflyy – 4.4.8
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.6
WPB WooCommerce Product slider: by wpbean – 2.0.2
YITH WooCommerce Quick View: by YITHEMES – 1.2.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #28 - /products/
Cart: #24 - /cart/
Checkout: #30 - /checkout/
My account: #21 - /my-account/

### Theme ###

Name: RSP Nutrition
Version: 1.0.0
Author URL: http://jamesrossadvertising.com
Child Theme: ✔
Parent Theme Name: Bootstrap Basic
Parent Theme Version: 1.0.12 – 1.0.13 is available
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: rsp/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.1.0
rsp/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.9
rsp/woocommerce/checkout/form-checkout.php
rsp/woocommerce/checkout/review-order.php
rsp/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
rsp/woocommerce/emails/customer-refunded-order.php
rsp/woocommerce/myaccount/dashboard.php
rsp/woocommerce/myaccount/navigation.php
rsp/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
rsp/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.1.0
rsp/woocommerce/single-product/title.php
rsp/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0

Outdated Templates: ❌Learn how to update

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Templates ###

Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by claudiosanches** [comment] 2017-07-05 21:16
> 1.Open Product
> 2. Update Product, I just was trying to update a product form out of stock to back in stock
> 3. click the update button
> 4. I got the error Invalid or duplicated SKU, even on the variation I was not updating.

I just did the same and no look, works just fine.
Probably related to one of your 74 plugins, you even said that you did not tried to isolate the problem in:

![screenshot from 2017-07-05 18-16-18](https://user-images.githubusercontent.com/1264099/27885341-0f16fabe-61ae-11e7-902f-dac0be233a7c.png)
 
So I'm closing since it's impossible to reproduce the error and you have not tested all your activated plugins and theme.

**Closed by claudiosanches** 2017-07-05 21:16 UTC
