### ISSUE TITLE
Woocommerce "email hidden, Javascript" error on email field

### ISSUE THREAD

**Issue by rustys27** [woocommerce/woocommerce#26078] opened 2020-04-03 22:21 UTC
I'm getting a "email hidden, javascript" error on my email field using WooCommerce checkout page.  I've tried everything to get rid of this, and am unable to do so. 
![Screen Shot 2020-04-03 at 6 21 34 PM](https://user-images.githubusercontent.com/63129162/78409551-f9f19900-75d7-11ea-9e4d-e697d2e3a800.png)

**Comment by AmeenJalali** [comment] 2020-04-10 15:54
Hi @rustys27, 
It seems it's a front-end issue. Please try and let me know if this bug happens with a default WordPress theme active, or Storefront. 
Have you tried deactivating all other plugins except WooCommerce?
I'm pretty sure it happens only with your theme and you changed some files in your-theme/woocommerce/checkout directory.

**Comment by juliaamosova** [comment] 2020-05-13 19:48
Hi @rustys27,

Thank you for raising the issue. 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-05-19 15:17
Hi @rustys27,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-05-19 15:17 UTC
Labels: status: needs feedback

**Comment by UnionDesign** [comment] 2020-05-25 14:19
Are you using the plugin PHPEnkoder? That was causing this same issue for me.

**Comment by blue7hand** [comment] 2020-12-08 18:31
Yes, I had the same issue with PHPEncoder.
Solution:
Add 
[noenkode] 
in your file. So edit the checkout file. It will then look like this:
[noenkode]
[woocommerce_checkout]
