### ISSUE TITLE
[GlobalStep] "Search" field appears misaligned on "Downloadable product permission" section.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#30156] opened 2021-06-24 15:06 UTC
## Bug Description:
"Search" field appears misaligned when "Downloadable product permission" section is moved to side panel on Edit order page. 

## Environment:
Woocommerce Version : WooCommerce 5.5.0 Beta and 5.4.1
WordPress version: v5.8-beta3-51218

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the OBW setup.
1. Add some products.
1. Create some orders.
1. Go to WooCommerce->Orders and click on any order.
1. Now move the Downloadable product permission section to side panel by dragging on its header.
1. Observe that "Search" field appears misaligned.

## Actual Result:
"Search" field appears misaligned on "Downloadable product permission" section

## Expected Result:
"Search" field should be properly aligned on "Downloadable product permission" section

## Screenshot:

![#30156](https://user-images.githubusercontent.com/41110392/123287019-0c812680-d52c-11eb-9107-19d7f6142eb5.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment] 2021-06-24 16:31
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

<img width="309" alt="Screen Shot 2021-06-25 at 12 26 53 AM" src="https://user-images.githubusercontent.com/4509348/123299734-6bef2e80-d54c-11eb-837c-0e9af8e32a7d.png">

It's also worth noting that this bug is also happening in the latest release builds for WordPress (version 5.7.2) and WooCommerce (version 5.4.1).

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by 9ete** [comment] 2021-09-30 23:01
I've added a fix for this issue here: https://github.com/woocommerce/woocommerce/pull/30856

Steps to reproduce (same as above):

1. Create any test site using JN site.
2. Install and activate all the required plugins.
3. Complete the OBW setup.
4. Add some products.
5. Create some orders.
6. Go to WooCommerce->Orders and click on any order.
7. Now move the Downloadable product permission section to side panel by dragging on its header.
8. Observe that "Search" field appears misaligned.

Before:
![Screen Shot 2021-09-30 at 3 52 04 PM](https://user-images.githubusercontent.com/1033613/135540780-d1c4b2e8-fa03-4af2-98c1-74f7c95e7e7e.png)

After:
![Screen Shot 2021-09-30 at 3 51 40 PM](https://user-images.githubusercontent.com/1033613/135540793-9aff5e6f-a0c1-4a18-9ead-cd47bb5328d3.png)

**Comment by 9ete** [comment] 2021-10-05 21:39
@rodelgc @vedanshujain tagging you both for review or triage.  Thanks!

**Closed** 2022-03-17 19:14 UTC
Labels: type: bug, type: good first issue, priority: low, plugin: woocommerce
