### ISSUE TITLE
Clicking toggle-row button to get product details in mobile admin view expands the wrong product

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce#26770] opened 2020-06-15 08:25 UTC
**Describe the bug**
`toggle-row` buttons on product admin list on mobile are displayed on the previous product. Because of this, when I try to expand some product details, I end up expanding the product below it.

**To Reproduce**
1. Go to Products > All Products on a mobile phone, or switch to mobile view in Chrome;
2. Click the arrow on the right of any product.
3. Observe the next product gets expanded instead.

**Screenshots**
I click to expand the top product:

![Screenshot](https://d.pr/i/1J7NYt+)
Screenshot: https://d.pr/i/1J7NYt

And get this one expanded instead:

![Screenshot](https://d.pr/i/2CHcyM+)
Screenshot: https://d.pr/i/2CHcyM

**Expected behavior**
`toggle-row` is displayed within its own respective row, so that it's easy to understand how to display more details about the product.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://new.test
Site address (URL): http://new.test
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.3
PHP Version: 7.3.10
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.17
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Total Database Size: 74.31MB
Database Data Size: 49.76MB
Database Index Size: 24.55MB
wp_woocommerce_sessions: Data: 3.50MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 22.03MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 17.55MB + Index: 20.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.72MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.34MB + Index: 0.22MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.59MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 1
attachment: 998
aw_workflow: 7
follow_up_email: 1
global_product_addon: 1
oembed_cache: 1
page: 15
post: 3
product: 783
product_variation: 1535
revision: 12
shop_coupon: 17
shop_order: 82
shop_order_refund: 1
shop_subscription: 17
wc_booking: 2
wc_membership_plan: 1
wc_user_membership: 1
wcpf_item: 5
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.2.0

### Inactive Plugins (45) ###

Akismet Anti-Spam: by Automattic – 4.1.6
All-in-One WP Migration: by ServMask – 7.23
AutomateWoo: by WooCommerce – 4.9.5
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.1.2 – Installed version not tested with active version of WooCommerce 4.2.0
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.5 – Installed version not tested with active version of WooCommerce 4.2.0
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.2.0
Child Theme Configurator: by Lilaea Media – 2.5.5
Codepen Block: by madeincosmos – 1.0.0
Code Snippets: by Code Snippets Pro – 2.14.0
Follow-Up Emails: by WooCommerce – 4.9.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Loco Translate: by Tim Whitlock – 2.4.0
Product Filters for WooCommerce: by WooCommerce – 1.2.1
Request a Quote for WooCommerce: by Addify – 1.4.1 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce 360° Image: by WooCommerce – 1.1.15
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.17
WooCommerce Additional Variation Images: by WooCommerce – 1.7.23
WooCommerce Advanced Notifications: by WooCommerce – 1.2.25
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.13
WooCommerce Blocks: by Automattic – 2.7.0
WooCommerce Bookings: by WooCommerce – 1.15.21
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.28
WooCommerce FedEx Shipping: by WooCommerce – 3.4.31
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.13 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Memberships: by SkyVerge – 1.17.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.2 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Points and Rewards: by WooCommerce – 1.6.33
WooCommerce Pre-Orders: by WooCommerce – 1.5.26
WooCommerce Product Add-ons: by WooCommerce – 3.0.34
WooCommerce Product Bundles: by SomewhereWarm – 6.2.5
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.34
WooCommerce Products Compare: by WooCommerce – 1.0.20
WooCommerce Product Vendors: by WooCommerce – 2.1.34
WooCommerce Shipment Tracking: by WooCommerce – 1.6.23
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.10
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.18
WooCommerce Smart Coupons: by StoreApps – 4.7.6
WooCommerce Square: by WooCommerce – 2.1.5 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Subscriptions: by WooCommerce – 3.0.4 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.1 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.44
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Mail Logging: by MailPoet – 1.9.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 182
Oldest: 2020-05-19 14:10:05 +0200
Newest: 2020-06-15 10:03:48 +0200

Pending: 3
Oldest: 2020-06-15 10:26:08 +0200
Newest: 2020-07-04 10:21:56 +0200

Canceled: 1
Oldest: 2020-06-15 09:53:58 +0200
Newest: 2020-06-15 09:53:58 +0200

`
```
</details>

**Comment by tammullen** [comment] 2020-06-16 22:57
Hi @madeincosmos!

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end using Chrome Mobile on Android
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by grigorijurasov** [comment] 2020-06-17 11:20
This was reported in 2984512-zen

**Comment by tammullen** [comment] 2021-11-05 20:39
Removing `priority: low ` due to the number of reports.

An updated priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by elizaan36** [comment] 2021-11-06 19:38
Thanks for letting me know this issue already exists @tammullen! I did a search but didn't go back this far into last year.
Some thoughts on the priority of this issue from a UX perspective - Mobile web users are around 10% of our user base and growing, and this is a bug that could cause people quite a bit of confusion. When you click on one product row, a different one expands. This could lead to incorrect data entry with regard to product pricing or other specs, mistakes in communications with customers, etc.

**Comment by louwie17** [comment] 2024-04-19 06:56
Closing this, as I was not able to reproduce this anymore at-least in the chrome phone browser.
Feel free to re-open if it is still present.

**Closed by louwie17** 2024-04-19 06:56 UTC
Labels: type: bug, focus: mobile, focus: product, plugin: woocommerce, team: Mothra
