### ISSUE TITLE
Fatal error uncaught error call to a member function get_price() on null on WooCommerce

### ISSUE THREAD

**Issue by tanmoy-web** [woocommerce/woocommerce#27472] opened 2020-08-25 13:26 UTC
HI, 
I am using Flatsome theme with WooCommerce and I am working on WooCommerce API calls.
For Orders and Customers, it is working perfectly.
However, I get this error for Products:

**fatal error uncaught error call to a member function get_price() on null in home/xxx/public_html/wp-content/plugins/woocommerce/inc/wc-products-functions.php 1046.**

**I have added the following code in this file location: /home/xxx/public_html/wp-content/themes/flatsome/woocommerce/single-product/price.php.**

```
<?php
function sv_change_product_price_display( $price ) {
    global $product;
    $price_excl_tax = wc_get_price_excluding_tax( $product ); 
    $price_incl_tax = wc_get_price_including_tax( $product );  
    <p class="price">Ex. VAT:<?php echo wc_price( $price_excl_tax ); ?>
    <p class="price-incl">Incl. VAT: <?php echo wc_price( $price_incl_tax ); ?>
    <?php 
    //return $price;
}
add_filter( 'woocommerce_get_price_html', 'sv_change_product_price_display' );
```

**I have added this code functions.php files:**
```
<?php
function sv_change_product_price_display( $price ) {
    global $product;
    $price_excl_tax = wc_get_price_excluding_tax( $product ); 
    $price_incl_tax = wc_get_price_including_tax( $product );  
    <p class="price">Ex. VAT:<?php echo wc_price( $price_excl_tax ); ?>
    <p class="price-incl">Incl. VAT: <?php echo wc_price( $price_incl_tax ); ?>
    <?php 
    //return $price;
}
add_filter( 'woocommerce_get_price_html', 'sv_change_product_price_display' );
```

What I am doing wrong?

Thanks

**Comment by tammullen** [comment] 2020-08-25 14:20
Hi @tanmoy-web 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-08-25 14:20 UTC

**Comment by tanmoy-web** [comment] 2020-08-25 18:12
Thanks
