### ISSUE TITLE
Bringing back a true “any” functionality to product attribute variations

### ISSUE THREAD

**Issue by mjdewitt** [woocommerce/woocommerce#24027] opened 2019-06-27 17:28 UTC
Hi,

I am testing Woo 3.4.6 under WP 5.2.2 and see that I still am not allowed to have product variation attributes without values. This was not the case in 2.6 as product attributes could be defined with no values. Under 2.6, this meant was that product variations with dynamically driven attribute data could be generated and accepted when adding the product to the cart. “Any” used to mean that literally any non-null value would be accepted. This was a great feature when you have products with hundreds or thousands of variations. There is no need to pre-define them.

I think it was in Woo 3.0 that the “any” functionality changed. Saving a product attribute with no values defined is no longer possible. In addition, any legacy attributes with no values created under 2.6 are silently deleted when edited/saved. This changes the definition of “any” to be “any defined value on the attribute.”

I believe there is usefulness in three kinds of attribute value matching: match a single value, match any defined value, and match any non-null value. By allowing product attributes to be saved with no values and revising the validation tests to accept any posted non-null value when none have been defined, dynamically generated product variations will work again. As it is now, I have been modifying class-wc-form-handler.php to make it work by relaxing the requirement that the posted value has to match a defined product attribute value.

In the comments on class-wc-form-handler.php, I see “If no attribute was posted, only error if the variation has an ‘any’ attribute which requires a value,” which I feel doesn’t really reflect the nuances of product attributes defining variations. I would like to suggest the following clarifications to the rules:

If posted data does not contain product variation attribute data, it won’t be considered a variation.

If posted data contains some product variation attribute data, but not all defined, it will throw an error for the missing data.

If a product variation attribute is posted with a non-null value and the product variation attribute has defined values, that value must match or an error will be thrown.

If a product variation attribute has no defined values (a true “any”), any non-null value will be accepted (within length/format criteria).

If the variation attribute’s posted value is NULL, an error will be thrown.

I hope that you will agree.

Mike

I originally posted this in https://wordpress.org/support/topic/bringing-back-a-true-any-functionality-to-product-attribute-variations/  as I wasn't sure how to characterize this -- is it a bug? an enhancement?  Fernando suggested that this was the more appropriate place.

**Comment by claudiosanches** [comment] 2019-06-28 13:42
> I am testing Woo 3.4.6

Why 3.4.6 and not the latest?
3.4.6 it's an outdated version, also we made several changes in attributes a little while, I recommend you doing tests using latest versions.
And the usage of any is still to apply to all not defined variables, and if we had any changes from 2.6, it's based on users feedback.

> I originally posted this in https://wordpress.org/support/topic/bringing-back-a-true-any-functionality-to-product-attribute-variations/ as I wasn't sure how to characterize this -- is it a bug? an enhancement? Fernando suggested that this was the more appropriate place.

As I said, changes are made based on feedback, but still better if you use a latest version instead of 3.4.6, that's why I'm closing, since is targeting a specific version that we don't maintain anymore.

**Closed by claudiosanches** 2019-06-28 13:42 UTC

**Comment by mjdewitt** [comment] 2019-06-28 14:25
My mistake, it was a typo, Woo version 3.6.4.

**Comment by mjdewitt** [comment] 2019-06-28 14:28
Hi,

Apologies for the typo, the Woo version is 3.6.4. I updated the post.

Mike

**Comment by claudiosanches** [comment] 2019-08-02 20:06
Still not able to reproduce with the steps you provided.

**Comment by mjdewitt** [comment] 2019-08-03 00:12
Claudio,

I am astonished and delighted to hear from you.

It seems that you are saying that you can create a product attribute that
has no values? On my system, any attribute with no values is silently
removed as if the system is saying, attributes must have predefined values
in order to be valid.

Mike
