### ISSUE TITLE
Variation purchases can be manipulated by purchasing 'main product'

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#28194] opened 2020-11-05 09:33 UTC
**Prerequisites:**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Variable products can be bought for the price of the first variation, without regard for the variation attribute.
So if a product "Broccoli" has a variation attribute "weight" with options "100gr|1kg|10kg", it can be added to the cart with the 10kg attribute and the price will be that of the 100gr attribute but only passing the main product_id and the desired attribute.

**Expected behavior**
It should not be possible to purchase a "main product" of a variable product
It should not be possible to add a random product attribute to a simple product

**Actual behavior**
Main product (the parent of the variations) is added to the cart, with the attribute of the variation. This attribute doesn't show in the cart, but after placing the order, it does show as item meta in the backend and emails to the customer. The customer pays the price of the first variation.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a variable product "Broccoli"
2. Under Attributes, add the weight attribute:
![broccoli-weight](https://user-images.githubusercontent.com/3217773/98222161-c18cb180-1f50-11eb-98a0-c606947c16a6.png)
3. Under Variations, select "Create variations for all products"
4. Set the prices for each varation:
- 100gr - €1.00
- 1kg - €8.00
- 10kg - €75.00
5. Save the product
6. Go to the product page in the store, inspect element and search for `data-product_id` (you can get this from the backend page too, but this is where a customer would get it)
7. Add the product to the cart with the following URL: http://yoursite.com/?add-to-cart=PRODUCT_ID&attribute_weight=10kg where
- `PRODUCT_ID` is the product ID from step 6
- `attribute_weight` is the `name` of the variable product dropdown,
- `10kg` is the value of that option
8. Go to checkout - the price shown will be **€1.00 instead of €75.00**.
9. Finish the order (note that at this point the attribute is not yet visible in the cart!)
10. Thank you page, order email and order backend will all show **weight: 10kg**
![broccoli-meta](https://user-images.githubusercontent.com/3217773/98223274-2b598b00-1f52-11eb-9783-62549d358772.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.
- [x] This works with Avocados and other expensive vegetables too.

**Comment by gregs-legs** [comment] 2020-11-05 14:40
I'm seeing this on my live site.  Items are being added to the cart without variation_id - today for example a customer bought 1kg of coffee beans for the price of 227g.   It also means the cart weight is zero (multiplication of a non-numeric value) and therefore the shipping cost is undercharged.  All of my products are variable and have been for many years.  This issue is intermittent and was first observed on 2nd November 2020.

Should it be compulsory to include the variation_id when adding a variable product to the cart ?

**Comment by gregs-legs** [comment] 2020-11-05 17:36
Reading through the function add_to_cart in class-wc-cart.php, if the variation_id is missing:

    Line 1026:  `$product_data = wc_get_product( $variation_id ? $variation_id : $product_id );`

means that $product_data becomes the variable product of type 'variable' therefore:

   Line 1033: `if ( $product_data->is_type( 'variation' ) ) {`

fails and none of the 'variation' specific checks are done.  For example the following (at line 1077) never happens:

`// Do we have a variation ID?
if ( empty( $variation_id ) ) {
throw new Exception( __( 'Please choose product options&hellip;', 'woocommerce' ) );
}`

So if I'm reading this correctly, it's possible to add a variable product to the cart without a variation_id and nothing gets validated.

**Comment by Spreeuw** [comment] 2020-11-05 18:58
@gregs-legs you may want to check your site for JS errors in the console. While the above description is a simple way to replicate, a more common way for this to happen is if for some reason jQuery crashes and none of the variation scripts apply. The customer can still change the dropdown selection but because no variation ID is passed, as a result the item is added with only the weight and variation attribute.

I believe this has been possible for MUCH longer (months or years) since I have observed something like this in the context of another plugin but never made the connection.

**Comment by gregs-legs** [comment] 2020-11-05 19:24
I can't reproduce any JS errors - this seems to be an intermittent problem.  But I think you might be right - I've just found this thread:  [https://github.com/woocommerce/woocommerce/issues/27756](url) .  It looks like it can result from slow (or deferred) loading of JS - if the customer is quick fingered.  There's a fix on the way which I'll try.  

The validation code in class-wc-cart.php still appears to be ineffective though.

**Comment by tammullen** [comment] 2020-11-05 19:44
Hi @Spreeuw 
Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27756. 
We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Closed by tammullen** 2020-11-05 19:44 UTC
