### ISSUE TITLE
Product categories sorting

### ISSUE THREAD

**Issue by rashadmammadli1** [woocommerce/woocommerce#21477] opened 2018-10-02 06:54 UTC
Hi. I can't sort product categories with drug & drop button. Is it a bug or I must do this action on other page? See attached file, please.
![product categories](https://user-images.githubusercontent.com/43773768/46333453-7a28ee00-c631-11e8-9f5f-6f3f78187136.PNG)

**Comment by claudiulodro** [comment] 2018-10-02 11:35
Hi there,

I was able to sort the categories that way in my testing on a site running only WooCommerce. My guess is that whatever plugin you have that is adding those extra columns with the flags may be causing the issue (or another plugin you may have active). I recommend going through [the self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to try and find your problem.

I am closing this as non-reproducible since you have not provided any more information and it is not possible to troubleshoot this further. Thanks.

**Closed by claudiulodro** 2018-10-02 11:35 UTC
