### ISSUE TITLE
Shipping zone not updating on checkout

### ISSUE THREAD

**Issue by sonnax** [woocommerce/woocommerce#24805] opened 2019-10-10 23:29 UTC
**Describe the bug**
When you are not logged in and visit checkout, shipping zones wont update when you change the zip code so customers dont see the correct shipping cost.

**To Reproduce**
1. Go to 'Checkout (as guest) you must have a product in your cart'
2. Assign a value to ZIP Code (corresponding to your shipping zones - shipping cost wont change.

For my website this has a big negative impact

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: sq_AL
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.2.22
PHP Post Max Size: 2 GB
PHP Time Limit: 500
PHP Max Input Vars: 7840
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.1
WC Database Prefix: wp_
Total Database Size: 360.25MB
Database Data Size: 277.85MB
Database Index Size: 82.40MB
wp_woocommerce_sessions: Data: 18.20MB + Index: 0.99MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.43MB + Index: 0.18MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 2.94MB + Index: 1.97MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_abandoned_cart_analystic_fb: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_abandoned_cart_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_abandoned_cart_statistical: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_abandoned_cart_user_add: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cart_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 1.42MB + Index: 0.64MB + Engine MyISAM
wp_elfsight_instagram_feed_widgets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.17MB + Index: 0.38MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 63.01MB + Index: 1.00MB + Engine MyISAM
wp_pmxe_exports: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 60.17MB + Index: 13.66MB + Engine MyISAM
wp_posts: Data: 8.68MB + Index: 1.85MB + Engine MyISAM
wp_po_plugins: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 3.02MB + Index: 2.72MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_revslider_css: Data: 0.10MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css_bkp: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders_bkp: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.82MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides_bkp: Data: 0.52MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smartiplog: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tab_event_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_tab_tests: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tab_test_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_tcb_api_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_td_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_td_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.43MB + Index: 0.20MB + Engine MyISAM
wp_terms: Data: 0.06MB + Index: 0.13MB + Engine MyISAM
wp_term_relationships: Data: 0.73MB + Index: 1.34MB + Engine MyISAM
wp_term_taxonomy: Data: 0.09MB + Index: 0.08MB + Engine MyISAM
wp_tg_item_elements: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tg_item_skins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tve_leads_contacts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tve_leads_contact_download: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tve_leads_event_log: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_tve_leads_form_variations: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_tve_leads_group_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tve_leads_saved_group_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tve_leads_split_test: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tve_leads_split_test_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 2.65MB + Index: 1.63MB + Engine MyISAM
wp_users: Data: 0.09MB + Index: 0.10MB + Engine MyISAM
wp_user_ref_abandoned_cart: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcsc_logs: Data: 1.02MB + Index: 2.03MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.45MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woochimp_scheduled_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_recommendations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_session_activity: Data: 57.58MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_msgs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_sessions: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_departments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 8.52MB + Index: 21.64MB + Engine InnoDB
wp_wps_index: Data: 18.55MB + Index: 25.25MB + Engine InnoDB
wp_wps_key: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_wps_uri: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_wps_user_agent: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
wp_yith_wcch_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcch_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcps_shippings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_yith_ywpar_points_log: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_yith_ywrac_email_log: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_ylc_chat_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ylc_chat_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ylc_chat_visitors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ylc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_meta: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_ywrr_email_blocklist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ywrr_email_schedule: Data: 0.09MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (56) ###

WP-Cron Status Checker Pro: by Webhead LLC – 1.0.1
Akismet Anti-Spam: by Automattic – 4.1.2
Autoptimize: by Frank Goossens (futtta) – 2.5.1
Capability Manager Enhanced: by PublishPress – 1.7.5
Classic Editor: by WordPress Contributors – 1.5
CMB2: by CMB2 team – 2.6.0
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Smart Content Protector: by Fantastic Plugins – 8.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.5
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
NC Woo Commerce PW: by Farma-City.al – 1.0
Woocommerce Easy Checkout Fields Editor: by phppoet – 1.7.1 – Not tested with the active version of WooCommerce
PixelYourSite PRO: by PixelYourSite – 7.3.3
Product Filter for WooCommerce: by 7VX LLC
USA CA – 7.1.3

Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 4.0.4
Redirection: by John Godley – 4.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Slider Revolution: by ThemePunch – 6.1.3
SG Optimizer: by SiteGround – 5.3.2
Shoppable Social Media Galleries by SNPT: by Snapppt – 1.1.7
Tbay Framework Pro: by Team Thembay – 1.2.3
Thrive Leads: by <a href="https://thrivethemes.com">Thrive Themes</a> – 2.2.4.2
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.12.0
WooCommerce Cart Reports: by WooCommerce – 1.2.4 – Not tested with the active version of WooCommerce
WooCommerce Cost of Goods: by SkyVerge – 2.9.1
WooCommerce Product Bundles: by SomewhereWarm – 5.13.0
WooCommerce Product Search: by itthinx – 2.17.0
WooCommerce Recommendation Engine: by Lucas Stark – 3.2.2
WooCommerce Smart Coupons: by StoreApps – 4.3.0
WooCommerce Tab Manager: by SkyVerge – 1.11.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15 – Not tested with the active version of WooCommerce
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.12 – Not tested with the active version of WooCommerce
WooCommerce Waitlist: by WooCommerce – 2.1.6 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.1
Yoast SEO Premium: by Team Yoast – 12.2
WP Mail Logging: by Christian Zöller – 1.9.1
WP Mail SMTP: by WPForms – 1.6.2
WP User Avatar: by flippercode – 2.2.4
Yoast SEO: WooCommerce: by Team Yoast – 12.1
WPSSO Schema Breadcrumbs Markup: by JS Morisset – 2.2.1
WPSSO Inherit Parent Meta: by JS Morisset – 2.0.2
WPSSO Ratings and Reviews: by JS Morisset – 2.3.1
WPSSO Schema JSON-LD Markup (Premium): by JS Morisset – 2.12.0
WPSSO Strip Schema Microdata: by JS Morisset – 2.0.2
WPSSO Update Manager: by JS Morisset – 2.2.1
WPSSO Core (Premium): by JS Morisset – 6.7.1
YITH WooCommerce Brands Add-on Premium: by YITH – 1.3.5
YITH WooCommerce Cart Messages Premium: by YITH – 1.6.1
YITH WooCommerce Checkout Manager: by YITH – 1.2.13
YITH WooCommerce PDF Invoice and Shipping List Premium: by YITH – 2.0.6
YITH WooCommerce Points and Rewards Premium: by YITH – 1.6.4
YITH WooCommerce Quick View Premium: by YITH – 1.4.5
YITH WooCommerce Recover Abandoned Cart Premium: by YITH – 1.3.7
YITH WooCommerce Review Reminder Premium: by YITH – 1.5.4
YITH WooCommerce Social Login Premium: by YITH – 1.4.3
YITH WooCommerce Wishlist Premium: by YITH – 2.2.12

### Inactive Plugins (31) ###

Code Snippets: by Code Snippets Pro – 2.13.3
Improved Badges for WooCommerce: by 7VX LLC
USA CA – 3.5.2

MC4WP: Mailchimp for WordPress: by ibericode – 4.6.1
Meta Generator and Version Info Remover: by Pankaj Kumar Mondal – 6.0.2
Plugin Organizer: by Jeff Sterup – 10.1.2
Plugins Garbage Collector: by Vladimir Garagulya – 0.10.4
Query Monitor: by John Blackbourn – 3.4.0
Slider Revolution Bubblemorph AddOn: by ThemePunch – 2.0.2
SVG Support: by Benbodhi – 2.3.15
Thrive Architect: by <a href="http://www.thrivethemes.com">Thrive Themes</a> – 2.4.3
TotalPoll – Pro: by TotalSuite – 4.0.7
Transients Manager: by Pippin Williamson – 1.7.7
WebP Express: by Bjørn Rosell – 0.17.2
WooCommerce Coupon Campaigns & Tracking: by WooCommerce – 1.1.7
WooCommerce Currency Converter: by WooCommerce – 1.6.14
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.8.1
WooCommerce Nested Category Layout: by SkyVerge – 1.13.1
WooCommerce URL Coupons: by SkyVerge – 2.8.0
WP Disable: by optimisation.io - jody nesbitt – 1.5.21
WP File Manager: by mndpsingh287 – 5.4
WP Live Chat Support: by WP-LiveChat – 8.0.37
WP Live Chat Support - Cloud Server: by WP-LiveChat – 2.0.00
WP Live Chat Support Pro: by WP Live Chat – 7.0.06
WP Maintenance Mode: by Designmodo – 2.2.4
WP Snow Effect: by WPManiax – 1.1.9
WP Widget in Navigation: by Yudiz Solutions Pvt. Ltd. – 2.0.0
YITH Live Chat Premium: by YITH – 1.3.4
YITH WooCommerce Advanced Reviews: by YITH – 1.3.9
YITH WooCommerce Bulk Product Editing Premium: by YITH – 1.2.16
YITH WooCommerce Customer History Premium: by YITH – 1.1.12
YITH WooCommerce Surveys Premium: by YITH – 1.1.4 – Not tested with the active version of WooCommerce

### Dropin Plugins (1) ###

object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ALL (Lekë)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #1551 - /products/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: puca Child
Version: 1.0
Author URL: https://thembay.com/
Child Theme: ✔
Parent Theme Name: Puca
Parent Theme Version: 1.5.5
Parent Theme Author URL: https://thembay.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: puca/woocommerce/cart/cart.php
puca/woocommerce/cart/cross-sells.php
puca/woocommerce/checkout/form-billing.php
puca/woocommerce/checkout/form-checkout.php
puca/woocommerce/checkout/form-coupon.php
puca/woocommerce/checkout/form-login.php
puca/woocommerce/checkout/form-shipping.php
puca/woocommerce/checkout/payment.php
puca/woocommerce/checkout/review-order.php
puca/woocommerce/content-product.php
puca/woocommerce/content-product_cat.php
puca/woocommerce/global/breadcrumb.php
puca/woocommerce/global/form-login.php
puca/woocommerce/global/quantity-input.php
puca/woocommerce/loop/add-to-cart.php
puca/woocommerce/loop/loop-end.php
puca/woocommerce/loop/loop-start.php
puca/woocommerce/loop/orderby.php
puca/woocommerce/loop/pagination.php
puca/woocommerce/loop/rating.php
puca/woocommerce/myaccount/form-add-payment-method.php
puca/woocommerce/myaccount/form-edit-account.php
puca/woocommerce/myaccount/form-login.php
puca/woocommerce/myaccount/form-lost-password.php
puca/woocommerce/myaccount/my-address.php
puca/woocommerce/myaccount/my-orders.php
puca/woocommerce/single-product/product-image.php
puca/woocommerce/single-product/product-thumbnails.php
puca/woocommerce/single-product/rating.php
puca/woocommerce/single-product/related.php
puca/woocommerce/single-product/review.php
puca/woocommerce/single-product/stock.php
puca/woocommerce/single-product/tabs/additional-information.php
puca/woocommerce/single-product/tabs/description.php
puca/woocommerce/single-product/tabs/tabs.php
puca/woocommerce/single-product/up-sells.php
puca/woocommerce/single-product-reviews.php


### Product Bundles ###

Database Version: 5.13.0
Template Overrides: –

### Action Scheduler ###

Complete: 41
Oldest: 2019-09-10 16:54:46 +0200
Newest: 2019-10-06 21:04:14 +0200

Pending: 1
Oldest: 2019-10-16 18:03:01 +0200
Newest: 2019-10-16 18:03:01 +0200

Canceled: 3
Oldest: 2019-10-07 17:09:58 +0200
Newest: 2019-10-09 18:02:53 +0200

In-progress: 0
Oldest: –
Newest: –

Failed: 70
Oldest: 2019-05-29 17:10:18 +0200
Newest: 2019-06-13 23:07:38 +0200

`
```
</details>

**Comment by juliaamosova** [comment] 2019-10-11 12:28
Hi @sonnax, thanks for reporting the issue. 

However, I can't reproduce it. It will be helpful to know how the shipping is set up exactly (shipping zones, flat rate, local pickup etc). 

So far, I've tried with Flat Rate as described below - shipping rate worked as expected:

- US - New York - $10
- US - Florida - $5

See gif below showing that shipping rate was updated on my end:

![](http://g.recordit.co/SdORlD7cvn.gif)

Note that shipping does not refresh unless you provide all required shipping fields first. Could it be that you didn't have a town or state specified?

**Comment by claudiosanches** [comment] 2019-10-14 15:48
Also not able to reproduce with the steps provided in this report.

**Comment by claudiosanches** [comment] 2019-10-27 17:14
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried following the steps you provided and it appeared to work correctly.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-10-27 17:14 UTC
Labels: can't reproduce

**Comment by Bossquiat** [comment] 2021-01-18 22:17
Hi i am having this same issue in my woocommerce store. the website is www.geneticbullz.com i have set up the shipping zones correctly but when in checkout, if i the location is change the page updates but the shipping cost stays the same. Do you have any suggestions
