### ISSUE TITLE
"Verified owner" review features not working

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce#26561] opened 2020-05-20 01:50 UTC
**Describe the bug**
In `Settings > Products`, there are some `Verified owner` options for reviews: 

<img width="631" alt="Screen Shot 2020-05-20 at 1 42 03 PM" src="https://user-images.githubusercontent.com/4167300/82395500-c98a8f00-9a9f-11ea-8704-0f1150741a60.png">

One limits reviews to those who have purchased a product, the other shows a special `verified` thing on reviews from customers who've for real bought the product.

I couldn't get either of these to work in my testing (WooCommerce 4.2.0 RC 1, Storefront 2.5.7 RC 1, WooCommerce Blocks 2.6.0 RC 1).

Perhaps there's something broken in the `verified owner` logic affecting both? Or maybe there's a gotcha/setup quirk that I missed. 

**To Reproduce**
1. Get a Woo site set up with some products.
2. Go to `Settings > Products`.
3. Scroll down to `Reviews`.
4. Enable `Show "verified owner" label on customer reviews` and / or `Reviews can only be left by "verified owners"` .
5. Switch to a different browser, create a customer account, purchase the product.
7. View product page as customer user, click reviews tab, leave a review.

**Screenshots**
<img width="1039" alt="woo core verified owner can't review after purchase" src="https://user-images.githubusercontent.com/4167300/82395883-9e546f80-9aa0-11ea-9ab5-ae25accc3743.png">

**Expected behavior**
`Show "verified owner" label on customer reviews` – should see a label on the review somewhere. Tested this in Storefront and Twenty Twenty.

`Reviews can only be left by "verified owners"`  – should be able to leave a review on products I have purchased.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://ephemeral-haszari-20200519.atomicsites.blog
Site address (URL): https://ephemeral-haszari-20200519.atomicsites.blog
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.6.0-rc1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.2
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.18
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.70.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Total Database Size: 2.52MB
Database Data Size: 1.14MB
Database Index Size: 1.38MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 22
customize_changeset: 10
nav_menu_item: 10
page: 11
post: 4
product: 12
revision: 15
shop_coupon: 1
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.5
AMP: by AMP Project Contributors – 1.5.3
Jetpack by WordPress.com: by Automattic – 8.5
WooCommerce Blocks: by Automattic – 2.6.0-rc1 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Services: by Automattic – 1.23.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0-RC.1

### Inactive Plugins (4) ###

CoBlocks: by GoDaddy – 1.26.1
Full Site Editing: by Automattic – 1.4
Gutenberg: by Gutenberg Team – 8.0.0
Layout Grid: by Automattic – 1.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.7-rc.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 11
Oldest: 2020-05-19 21:25:42 +0000
Newest: 2020-05-20 01:47:04 +0000

Pending: 1
Oldest: 2020-05-21 00:33:09 +0000
Newest: 2020-05-21 00:33:09 +0000

```
</details>

**Comment by juliaamosova** [comment] 2020-05-20 14:15
Hi @haszari,

Thanks for rasing the issue here. However, I can't reproduce it - the functionality around verified owners works as expected for me. 

What I did to reproduce it:

1) Created a user with a `customer` role on the site as admin - noted the email address I assigned to this user;
2) Via incognito browser, logged in to the site as a customer using the same email address and login details as in step 1;
3) Purchased a product on the site;
4) Left a review on the product as a customer (while still being logged in);
5) A verified owner green icon appeared next to the customer's user name (`Show "verified owner" label on customer reviews` setting is working):

![v1](https://user-images.githubusercontent.com/19143190/82456641-82da6c00-9a82-11ea-83a6-fd0a6b2b25b5.jpg)

![v2](https://user-images.githubusercontent.com/19143190/82456656-866df300-9a82-11ea-8bda-21804c2a4774.jpg)

6) Next, I logged out of the customer's account as a customer;
7) Navigated back to the same product;
8) A notice was shown to me that only logged in customers who purchased the product can leave a review (`Reviews can only be left by "verified owners"` setting is working):

![v3](https://user-images.githubusercontent.com/19143190/82456841-bb7a4580-9a82-11ea-8977-52288924ff80.jpg)

Do you think I am missing some steps and maybe you discovered some scenario where these settings don't work indeed?

**Comment by haszari** [comment] 2020-05-20 20:29
> Do you think I am missing some steps and maybe you discovered some scenario where these settings don't work indeed?

Not sure! My customer signed up themselves, via `Allow customers to create an account on my account page` option. So perhaps their account was less verified or missing some flag.

**Comment by juliaamosova** [comment] 2020-06-03 20:27
>Not sure! My customer signed up themselves, via Allow customers to create an account on my account page option. So perhaps their account was less verified or missing some flag.

@haszari sorry for the delay here! I tested again but this time I followed your steps to reproduce precisely and created a customer (1) user via `Allow customers to create an account on my account page` option. I then proceeded to purchase an item on the site and was successfully able to leave comments and have a `verified owner` icon appear next to my newly created customer (1) on the site. 

I then logged out and created another customer (2). As that 2nd customer, I navigated to the product that customer 1 purchased but was not able to leave a comment as I have specified that only verified owners can leave a review:

![rev](https://user-images.githubusercontent.com/19143190/83685736-21a0b580-a5b7-11ea-9086-d29ffe6b680a.jpg)

Can you please retest when you get a chance to see if this is still an issue for you? I tested with WooCommerce 4.2.

**Comment by haszari** [comment] 2020-06-09 04:17
Retested – I got it to work.

I'm using `check payments` payment method. I needed to fulfil the order - i.e. mark as `Completed` status, and then the customer could leave a review. I bet that was the problem – happy for this to close :)

**Comment by juliaamosova** [comment] 2020-06-09 13:59
Thanks for retesting it @haszari! Yep, looks like `check payments` payment method was playing a role indeed. Thanks for your follow-up. Closing this as a non-issue.

**Closed by juliaamosova** 2020-06-09 13:59 UTC
Labels: can't reproduce, status: needs feedback
