### ISSUE TITLE
Deadlock on wp_woocommerce_sessions

### ISSUE THREAD

**Issue by crstauf** [woocommerce/woocommerce#20912] opened 2018-07-26 15:15 UTC
Error log indicates deadlocks occur on `wp_woocommerce_sessions` regularly (not frequently, about a handful per day); these deadlocks were occurring on version 3.4.1, and continue now after 3.4.3.

Tables are InnoDB, and memcached is being used.

```SQL
------------------------
LATEST DETECTED DEADLOCK
------------------------
2018-07-26 11:52:24 0x7f9cddb2d700
*** (1) TRANSACTION:
TRANSACTION 449649393, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 5295390, OS thread handle 140292609775360, query id 289749654 127.0.0.1 XXXXXX update
REPLACE INTO `wp_woocommerce_sessions` (`session_key`, `session_value`, `session_expiry`) VALUES ('272fb37d4c42ee592447397de3bb1aae', ...
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 8246 page no 2345 n bits 400 index session_id of table `wp_XXXXXX`.`wp_woocommerce_sessions` trx id 449649393 lock_mode X insert intention waiting
*** (2) TRANSACTION:
TRANSACTION 449649394, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
4 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 2
MySQL thread id 5295391, OS thread handle 140311711110912, query id 289749655 127.0.0.1 XXXXXX update
REPLACE INTO `wp_woocommerce_sessions` (`session_key`, `session_value`, `session_expiry`) VALUES ('4', ...
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 8246 page no 2345 n bits 400 index session_id of table `wp_XXXXXX`.`wp_woocommerce_sessions` trx id 449649394 lock_mode X
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 8246 page no 2345 n bits 400 index session_id of table `wp_XXXXXX`.`wp_woocommerce_sessions` trx id 449649394 lock_mode X insert intention waiting
*** WE ROLL BACK TRANSACTION (1)
```

**Comment by crstauf** [comment] 2018-08-08 04:44
Going to mention a few people that have participated in deadlock issues before, since this continues to occur, and hasn't received attention in nearly two weeks: 
@mikejolley @claudiulodro @rodrigoprimo @kloon

**Comment by kloon** [comment] 2018-08-08 08:30
@crstauf can you try adding the following to your theme's functions.php file, I have a suspicion this might be caused by the use of transactions on the DB layer.

`define( 'WC_USE_TRANSACTIONS', false );`

**Comment by kloon** [comment] 2018-08-08 08:41
@crstauf are you running into this issue on site with large amount of visitors and add to carts? Reason I ask is because I think this might be related to the session cleanup which happens twice a day, what I suspect is happening is that you have a large amount of sessions that needs deleting and then when someone adds to cart during that cleanup period it can't update the DB because the cleanup code is busy running a delete which locks the table.

**Comment by crstauf** [comment] 2018-08-09 06:18
@kloon I thought 3.4.3 removed the use of transactions?

And yes, we've lots of visitors and add to carts; I see three deadlocks that occurred today on the `wp_woocommerce_sessions` table.

I will investigate the use of `WC_USE_TRANSACTIONS` constant and report back.

**Comment by rodrigoprimo** [comment] 2018-08-10 18:01
A few comments below but bear in mind that I'm not a database expert:

- This issue made me wonder about deadlocks in WooCommerce in general: shouldn't WordPress/WooCommerce catch the deadlock error and retry the transaction? As far as I know, this doesn't happen, and occasional deadlocks are not entirely avoidable in InnoDB.

> Reason I ask is because I think this might be related to the session cleanup which happens twice a day,

- I don't believe these deadlocks are related to the sessions cleanup routine. I say this because the [cleanup routine](https://github.com/woocommerce/woocommerce/blob/3f82ecee8ca0252b00a163494230ed71db94430f/includes/class-wc-session-handler.php#L265) runs a `DELETE` query and the two queries involved in this particular deadlock are `REPLACE` queries triggered by [WC_Session_Handler::save_data()](https://github.com/woocommerce/woocommerce/blob/3f82ecee8ca0252b00a163494230ed71db94430f/includes/class-wc-session-handler.php#L215).

- I have another theory to the cause of the deadlocks, but I don't know enough about InnoDB internals to be sure. The one thing that stood out to me when checking `wp_woocommerce_sessions` [definition](https://github.com/woocommerce/woocommerce/blob/d679a881568db7b2b8098b84f11e3c8a10afdff5/includes/class-wc-install.php#L625) is that this table uses a char(32) column as its primary key and has a unique and auto increment session_id column that doesn't seem to be used anywhere. Could the deadlocks be caused by conflicting gap locks on the `session_key` index?

- The biggest problem I see with the theory above is that the error log seems to mention that the problem was caused by two transactions waiting to get insertion intention locks on the `session_id` index:

> RECORD LOCKS space id 8246 page no 2345 n bits 400 index session_id of table `wp_XXXXXX`.`wp_woocommerce_sessions` trx id 449649394 lock_mode X insert intention waiting

- Does anyone know why `wp_woocommerc_sessions` has a char(32) primary key and a unique session_id field that doesn't seem to be used?

**Comment by rodrigoprimo** [comment] 2018-08-31 20:07
@crstauf could you please test #21245 and see if it helps to reduce the number of deadlocks?

I imagine you will have to test this change on production as I'm assuming you are not able to reproduce the deadlocks on a development environment. If that is the case, be aware that, while MySQL is changing the indexes, it will lock `wp_woocommerce_sessions`. So, it is probably a good idea to put your site in maintenance mode before triggering the database update. Please let me know if you have any questions or concerns.

**Comment by crstauf** [comment] 2018-09-01 04:29
@rodrigoprimo Excellent; thanks! Will give it a shot.

Before I test it out, can you please provide the query that would restore the database's structure to WC database version 3.4.3, just in case?

**Comment by rodrigoprimo** [comment] 2018-09-03 14:50
Sure, @crstauf. The query below will restore the table indexes (you might need to change the table name prefix in case you use something other than `wp_`):

```
ALTER TABLE `wp_woocommerce_sessions` DROP PRIMARY KEY, DROP KEY `session_key`, ADD PRIMARY KEY(`session_key`), ADD UNIQUE KEY(`session_id`);
```

You can use the following query to see the indexes before and after the change:

```
ALTER TABLE `wp_woocommerce_sessions` DROP PRIMARY KEY, DROP KEY `session_key`, ADD PRIMARY KEY(`session_key`), ADD UNIQUE KEY(`session_id`);
```

Before the change proposed in #21245 it should be:

```
+-------------------------+------------+------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                   | Non_unique | Key_name   | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-------------------------+------------+------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| wp_woocommerce_sessions |          0 | PRIMARY    |            1 | session_key | A         |           1 |     NULL | NULL   |      | BTREE      |         |               |
| wp_woocommerce_sessions |          0 | session_id |            1 | session_id  | A         |           1 |     NULL | NULL   |      | BTREE      |         |               |
+-------------------------+------------+------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
```

And after:

```
+-------------------------+------------+-------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                   | Non_unique | Key_name    | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-------------------------+------------+-------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| wp_woocommerce_sessions |          0 | PRIMARY     |            1 | session_id  | A         |           1 |     NULL | NULL   |      | BTREE      |         |               |
| wp_woocommerce_sessions |          0 | session_key |            1 | session_key | A         |           1 |     NULL | NULL   |      | BTREE      |         |               |
+-------------------------+------------+-------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
```

**Comment by crstauf** [comment] 2018-09-04 15:03
Thanks, @rodrigoprimo! 

Noting that the two queries provided are identical.

**Comment by rodrigoprimo** [comment] 2018-09-04 17:59
Copy and paste error :)

I edited the second query in the original comment. Thanks for pointing that out.

**Comment by kloon** [comment] 2018-09-12 11:04
Closing, changes was merged in #21245

**Comment by pento** [comment] 2018-09-13 05:33
Hey friends, @claudiulodro asked me to review this issue, but due to travel and vacation, it's taken me a bit of time to get to it.

I had a look at #21245, I'm not sure if that will fix it this particular problem: as `session_id` isn't being referred to in the query, InnoDB creating record locks based on that index will involve some dark magic inside of InnoDB, which I don't think can be addressed by turning it into the PK. 🙂It's usually a good idea to use an auto-increment field as the PK, however, so I'd be fine with keeping this change.

I agree with @rodrigoprimo's assessment that it isn't to do with the cleanup routine: the cleanup routine runs in a cron job, but both of the queries in this deadlock come from the `::save_data()` function, which is called on `shutdown`. This is two visitors who happen to doing something that interacts with the same area of the session table at the same.

@claudiulodro asked me to go into a bit more detail on how to investigate MySQL issues, so this comment is kind of a brain dump of what I looked at.

For investigating MySQL issues, my approach is always the same: read and understand every part of the error message, and read the manual for every query involved. It's something of a trial-and-error process: does this idea match the data available? If not, look for something else.

In this case, I came across a likely suspect early on. It seemed strange that transaction 2 already held a lock, and had multiple undo log entries. Assuming @crstauf's MySQL server has the default `autocommit` setting, then that shouldn't be possible at first glance: each query (assuming appropriate indexing, which seems to be the case here) should grab one lock, and only need one undo log entry. Even more peculiar was that it held an exclusive lock without an insert intention: this is a lock for updating or deleting a row (https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html#innodb-shared-exclusive-locks).

Now, `REPLACE` queries are slightly different from other write queries (https://dev.mysql.com/doc/refman/8.0/en/replace.html). It works by attempting to insert the data, if that fails due to an existing unique key, it deletes the offending row, then inserts a new row. This gives us a scenario where transaction 2 could hold the lock that it does, and be seeking to get an "insert intention" lock, too.

In order to clash with an insert intention lock on an auto-increment column, the value of `session_id` in the row being deleted would need to be in the same lock gap as the next auto-increment value: ie, it needs to be one of the last rows in the table.

So, a likely scenario to match this bug report is that a user with an existing session with a `session_id` in the last one or two entries of the table causes the `REPLACE` query to be run (which runs an insert that fails on a `session_key` clash, then runs a delete which evidently locks on the `session_id`, then runs a new insert), at the same time as a user who doesn't have an existing session causes the `REPLACE` query to be run (which just runs an insert).

So, how do we prevent this?

I think the best option would be to replace the `REPLACE` query with an `INSERT ... ON DUPLICATE KEY UPDATE` query. This has several advantages:
- As the `session_id` column will only ever be inserted (rows won't be updated or deleted by it), queries should only ever lock it with insert intention, which allows writing in the same lock gap. (The scenario above won't cause a deadlock.)
- Updates to existing session data will no longer create a new row at the end of the table. This will help distribute normal read/write activity across the entire `session_id` range, which would help to prevent deadlocks in other potential scenarios.
- Updating rows, instead of constantly deleting and re-inserting them, will help prevent table fragmentation, which is always good for performance.

The down side is that WPDB doesn't provide a helper function for this (see: https://core.trac.wordpress.org/ticket/22196), but it's safe to use this query here, as it's only being run against one index with a `UNIQUE` constraint.

**Comment by rodrigoprimo** [comment] 2018-09-26 18:08
Thanks for your detailed comment, @pento. It helped a lot. PR #21455 changes the query used to save session data as you suggested.

**Closed by rodrigoprimo** 2018-09-26 18:08 UTC
Labels: has pull request, performance, status: needs feedback

**Comment by crstauf** [comment] 2019-01-14 18:14
@rodrigoprimo @pento Since updating to WC 3.5.3, we've not seen any more deadlocks; thanks!

**Comment by rodrigoprimo** [comment] 2019-01-15 17:03
@crstauf that is great to hear. Thanks for taking the time to inform us.

**Comment by faridmovsumov** [comment] 2021-01-11 13:52
Unfortunately, the current solution causing a lot of problems. We having performance issues due to this query and it is always the top heaviest query in the system. I looking for a way to find an alternative solution. If someone facing the same problem please share your experience.
