### ISSUE TITLE
Checkout Stuck

### ISSUE THREAD

**Issue by shayoo** [woocommerce/woocommerce#18167] opened 2017-12-14 10:47 UTC
checkout form got stuck and my request keeps loading(not responding). When I comment out wc_set_time_limit( 0 ) in "/MyProject/wp-content/plugins/woocommerce/includes/class-wc-checkout.php" (function process_checkout())  checkout form runs perfectly.

I am newbie in woocommerce and I figure out above problem from my own, please help me out.

Support Details:
1) PHP 5.6.31
2) mysql 5.7
3) Wordpress 4.9.1
4) WooCommerce 3.2.6

Thanks in Advance :)

**Comment by rodrigoprimo** [comment] 2017-12-14 12:16
@shayoo, could you please try the following:

- Check PHP error log to see if there is any error when you try to check out.
- Change line 1427 in `includes/wc-core-functions.php` and remove the error control operator (`@`) (https://github.com/woocommerce/woocommerce/blob/master/includes/wc-core-functions.php#L1427). After the change, it should read:
`		set_time_limit( $limit ); // @codingStandardsIgnoreLine`
- Check PHP error log again to see if there is any new errors.

**Comment by shayoo** [comment] 2017-12-15 06:25
@rodrigoprimo I checked error_log but there is no new error after remove the error control operator

**Comment by mikejolley** [comment] 2017-12-15 12:25
@shayoo We're lacking enough information to decide whether or not this needs to be changed. It seems server related. WP core also uses `@` error suppression on calls like this which can be seen here:

https://github.com/WordPress/WordPress/search?utf8=%E2%9C%93&q=set_time_limit&type=

Can you log a support request either on https://woocommerce.com/my-account/tickets/ or via the contact us page https://woocommerce.com/contact-us/, make sure to reference this issue, and provide details so we can have access? This will allow us to debug on the problem server since none of us can replicate the issue and it's not affecting other users.

Also be sure to send the system status report when you do so.

I'm closing this issue as non reproducible for now.

Thanks

**Closed by mikejolley** 2017-12-15 12:25 UTC
Labels: Status: Needs Author Feedback
