### ISSUE TITLE
On the Order view page in Admin end we cant modify the coupon link/title if that coupon is virtual coupon

### ISSUE THREAD

**Issue by rajeshsingh520** [woocommerce/woocommerce#29487] opened 2021-03-25 09:17 UTC
We are adding a coupon using this way

https://gist.github.com/rajeshsingh520/82168a0e7bf8178b4af1df5377bf8508

everything works file but on the Admin side we want to show the coupon name and link it to our different coupon edit page 

https://imgur.com/a/tO3ffTH

https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/includes/admin/meta-boxes/views/html-order-items.php#L134

Can we have a filter function here so we can change the coupon output

**Comment by tammullen** [comment] 2021-03-26 14:27
Hi @rajeshsingh520 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it. 

If you wish to suggest an enhancement please use the enhancement template.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-26 14:27 UTC
