### ISSUE TITLE
WooCommerce widget form overlapse

### ISSUE THREAD

**Issue by daveloodts** [woocommerce/woocommerce#26806] opened 2020-06-18 11:03 UTC
When adding the WooCommerce Search widget in a sidebar, in some themes it can overlap the sidebar.
This has to do with WooCommerce styling.

The class .woocommerce-product-search got the styling display:flex, but no wrapper.

So, add here the styling flex-wrap: wrap and the search form doesn't jump out of the sidebar.

**Comment by tammullen** [comment] 2020-06-18 21:14
Hi @daveloodts 

Thank you for submitting the issue. To make it easier to fully evaluate this issue can you please provide more details.
- Can you provide examples of the themes this happens in with some screenshots?
- Can you confirm the Widget you are referring to is the "Product Search" Widget?
![Screenshot 2020-06-18 at 22 13 08](https://user-images.githubusercontent.com/24649833/85072379-f1f5ce00-b1b0-11ea-96d9-9d67482dc7ba.png)
- If the examples are on a site you have admin access to can you please provide the system status report from **WooCommerce > System Status** in WordPress admin.

**Comment by daveloodts** [comment] 2020-06-22 05:10
Yes, it is that widget.
For some reason i can not simulate the issue.
Was on this page: https://www.vanlommelprinting.be/webshop/
We've set the button to hidden, but before it's overlapses the vertical line.

**Comment by tammullen** [comment] 2021-03-24 19:03
Thanks @daveloodts for the feedback, apologies for the delay in replying.

I'm going to close this as it appears that the issue is resolved.

**Closed by tammullen** 2021-03-24 19:03 UTC
Labels: has feedback
