### ISSUE TITLE
Randomly incorrect order currency recorded in database

### ISSUE THREAD

**Issue by axelra82** [woocommerce/woocommerce#14966] opened 2017-05-09 19:34 UTC
### EXPLANATION OF THE ISSUE
Updated to woocommerce 3.0.1 about a month ago (beginning of April). Just today we noticed that some (not all, rather somewhat random but pretty consistent in occurrence) orders placed with alternative currencies (using [aelia currency switcher for woocommerce](https://aelia.co/shop/currency-switcher-woocommerce/)) are randomly recorded with the base currency. e.g. order is placed with EUR (€) but stored as being in SEK (kr) in woocommerce. For now (after having a smaller heart attack) we've noticed that the amount due in the respective payment gateways (PayPal and Klarna) are registered correctly, i.e. customer chose to pay in EUR, paypal/klarna has charge in EUR.
However, this will for one stop us from being able to handle refunds in woocommerce for said orders as the payment gateways only accepts the currency it has stored for the order. So for now, refunds don't work on random orders. It will also make the reporting completely "wonky" since it's calculating on incorrect data (and I've made a custom reporting plugin since the default one is really incorrect and very unusable when handling multiple currencies. Nevertheless, this would obviously affect the standard reporting as well). But more than that, we are storing incorrect information about our order history. Not good.

**I've been in contact with aelia** and they claim that this is without a doubt woocommerce related (see quote from support ticket with aelia earlier today)
"The Currency Switcher changes the active currency at checkout, then WooCommerce takes it and stores it against the order before the payment. From that moment on, everything is in WooCommerce's "hands".
The currency information is not "our" data, but standard, core WooCommerce data, which has been there ever since WooCommerce 1.6.x. The same applies to any payment data recorded against the order (e.g. in order log, order notes, etc)." 

So the only possible conclusion I can draw from this, is that this is a woocommerce bug that happened with the 3.0.1 update. i.e. this is not a support issue, from what I can tell, it's a legitimate bug repport (this is my first time posting an issue here, so I just want to be clear that I'm not just posting the try and get support. All data is pointing to this being a woocommerce bug).

This was all working fine back in March this year, since then the only major (that would be relevant to this issue) update has been the big woocommerce 2.x -> 3.0.x.

Really just looking to solve the issue (and of course getting the bug fixed. The bug being whatever it is that's interfering with the currencies stored in the database at the time of the finished purchase). Manually going thru a couple of hundred orders I can see that we have about 20-30 orders that are affected by this bug (they're easy to spot as the amount total in the orders list view is of by ~ x10 (since it should be Euro which is roughly 10 times more than Swedish Kronor). Hopefully I will be able to manually correct these in the database (aelia has been very supportive in trying to find a solution). I'm assuming this would be a question of appending rows with the affected orders is for the post_id in post meta table? Any help/suggestion/guidance on the manual correction of this is widely appreciated.

### STEPS TO REPRODUCE THE ISSUE
- Set up a multi currency shop using aelia 4.4.16.170424 (this was updated today after talking with aelia support. But since they claim that the issue is woocommerce related it should have no effect on the bug)
- complete a purchase in paypal (and/or Klarna). Since the bug is acting random, I'm assuming that multiple purchases would have to be done.
- currencies will not always show the one that was used during checkout in woocommerce (the correct currency will however have been sent to the respective payment gateway).

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://bringsportswear.com
Site URL: https://bringsportswear.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 3000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: bspwe_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

WooCommerce Back In Stock Notifier: by Fantastic Plugins – 9.3.2
iThemes Security: by iThemes – 6.2.1
Bring Reports: by Axel Roussille Åberg – 1.0.0
Cookie Notice: by dFactory – 1.2.38
Cornerstone: by Themeco – 2.0.1
Envato Market: by Derek Herman – 1.0.0-RC2
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 6.0.4
MonsterInsights Pro: by MonsterInsights – 6.1.7
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress: by ibericode – 4.1.2
MailChimp for WordPress - Premium: by ibericode – 3.3.10
Slider Revolution: by ThemePunch – 5.4.1
Social Collabs: by Axel Roussille Åberg – 1.0.0
W3 Total Cache: by Frederick Townes – 0.9.5.4
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.6.170405
WC Variations Radio Buttons: by 8manos – 2.0.0
Aelia Currency Switcher for WooCommerce: by Aelia – 4.4.16.170424
WooCommerce Klarna Gateway: by WooCommerce – 2.3.6
Woocommerce Mailchimp Discount: by Magnigenie – 2.1
WooCommerce: by Automattic – 3.0.5 – 3.0.6 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.8
Yoast SEO: by Team Yoast – 4.7
X – Under Construction: by Themeco – 1.2.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #25 - /products/
Cart: #50 - /products/cart/
Checkout: #48 - /products/checkout/
My account: #46 - /account/

### Theme ###

Name: X – Child Theme
Version: 1.0.0
Author URL: http://theme.co/
Child Theme: ✔
Parent Theme Name: X
Parent Theme Version: 4.6.4
Parent Theme Author URL: http://theme.co/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: x/woocommerce/cart/cart-empty.php
x-child/woocommerce/cart/cart-shipping.php
x-child/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
x-child/woocommerce/cart/proceed-to-checkout-button.php
x-child/woocommerce/checkout/form-checkout.php
x-child/woocommerce/checkout/form-coupon.php
x-child/woocommerce/checkout/form-login.php
x-child/woocommerce/checkout/form-pay.php
x-child/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
x-child/woocommerce/checkout/payment-method.php
x-child/woocommerce/checkout/payment.php
x/woocommerce/loop/loop-end.php
x/woocommerce/loop/loop-start.php
x/woocommerce/loop/pagination.php
x-child/woocommerce/loop/price.php
x-child/woocommerce/loop/sale-flash.php
x-child/woocommerce/myaccount/form-login.php
x-child/woocommerce/myaccount/orders.php version 2.6.0 is out of date. The core version is 3.0.0
x/woocommerce/notices/error.php
x/woocommerce/notices/notice.php
x/woocommerce/notices/success.php
x-child/woocommerce/order/order-details.php
x-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
x-child/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
x-child/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.2
x-child/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
x-child/woocommerce/single-product/sale-flash.php
x-child/woocommerce/single-product/short-description.php
x-child/woocommerce/single-product/tabs/description.php
x/woocommerce/single-product/tabs/tabs.php
x-child/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
x/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: ✔
Norway: ✔
Finland: ✔
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`
</details>

**Comment by daigo75** [comment] 2017-05-09 20:12
@axelra82 What you wrote about the payment process is indeed correct. The payment process is handled by WooCommerce, and the currency is set against it during the order creation. The currency code stored against an order, at its creation, is fetched by calling `get_woocommerce_currency()`, and it's then used for payment. Since payments were processed in the correct currency, this most likely indicates that the currency selection worked fine:
1. Active currency was EUR.
2. The order currency was set to EUR.
3. The payment took the currency from the order, and was processed in EUR.

Due to that, it looks like something else might have changed the order currency at a later stage. The key would be to find out when that occurred, and why.

I would just have to make a small correction to the original report. Although the updated plugin I sent you did not contain fixes that specifically addressed the issue you reported (we haven't seen it before), there is still a chance that the issue was due to some edge condition that occurred with the old version. WooCommerce 3.0.x received several fixes in the past weeks, and we updated our plugins as needed, therefore it might be possible that installing the latest version of our plugin already sorted the issue. We might have fixed an edge condition indirectly, without having seen it.
We will have to wait and see if the issue occurs again, before we can be sure that there is still a bug to be fixed somewhere.

For completeness, we haven't received other reports of this issue so far, and we couldn't reproduce it either. If we can narrow down the conditions in which it occurs, it will be possible to prepare a solution.

**Comment by axelra82** [comment] 2017-05-09 20:26
From what I've found (so far), there are rows in the following format (for individual orders in _postmeta table):
_order_total_base_currency -> 573.11
_order_total -> 59.03
In this example, the _order_currency was set to SEK, when it should have been EUR (since it was payed in EUR via paypal).

**Comment by daigo75** [comment] 2017-05-09 20:30
`_order_total_base_currency` is the total in SEK, converted by the currency plugin from the `_order_total` value in EUR. This is another indicator that the order was created in the correct currency originally.

**Comment by mikejolley** [comment] 2017-05-10 08:05
FWIW currency is only SET to store default on creation, if the currency is blank https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/abstract-wc-order-data-store-cpt.php#L54

The only other use of this setter is within the create order and create function functions.

Anything else would require a plugin to explicitly set/change the meta.

The other possibility is that the calcs were done in the correct currency,  but it was never stored to the order on creation.

I'd do the updates as Daigo suggests. It could be a meta conflict (one of the things fixed in more recent 3.0.x releases too).

Another thing you could try would be to try to see when the change occurs. Monitor the meta for a new order and do actions like refunding etc to see if it changes at any point.

As much as I love @daigo75 I cannot purchase premium plugins to test this myself :) Happy to look again if you narrow the cause.

Thanks

**Closed by mikejolley** 2017-05-10 08:05 UTC

**Comment by daigo75** [comment] 2017-05-10 08:27
@mikejolley Thanks for your reply. I was in fact wondering if this behaviour is correct:

`$order->set_currency( $order->get_currency() ? $order->get_currency() : get_woocommerce_currency() );`

In my opinion, it makes little sense to retrieve a currency from an order that has not yet been created, as it will always be empty. Since `WC_Order::get_currency()` always returns a non-empty value (it returns the base currency when the order's one is empty), your statement is the equivalent of this:

`$order->set_currency( $order->get_currency() );`

It looks a bit silly. :smile: 
During order creation, when the order currency is empty, it should be set to the active one, not the base one. That was the behavior since WC 1.6.x, and worked fine up until WC 2.6.x. From what I see, it makes little sense to always create an order in base currency. The purpose of `get_woocommerce_currency()` is precisely to return the currency to use, therefore I would change that line to just:

`$order->set_currency( get_woocommerce_currency() );`

Also, I remember seeing an issue caused by the behaviour of the new `WC_Order::get_currency()` function. That function does indeed return shop's base currency if the order has no currency, but that's not necessarily correct. When an order has no currency, then it's missing a key piece of information. There is no "default" that works: the order is effectively "broken" and should be fixed. Assuming that it was created in base currency is incorrect, and can cause unpredictable side effects, such as incorrect reports, or wrong information displayed on the UI.

I would even go to the extent of saying that taking the base currency as a default works by coincidence: since in a "vanilla" WooCommerce installation there is only one currency, one may tend to assume that the base currency and the active one are always the same. That assumption becomes incorrect as soon as more than currency comes into play.
The change I proposed, creating orders in the **active** currency, would allow WooCommerce to work as it used to, and could prevent issues down the line.

**Comment by mikejolley** [comment] 2017-05-10 08:48
@daigo75 

```
$order->set_currency( $order->get_currency() ? $order->get_currency() : get_woocommerce_currency() );
```

This is just shorthand instead of an if/else checking if currency is already set, which is may well be.

Get currency itself does not return the default - it just returns what is currency set on the object:

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L230

**Comment by daigo75** [comment] 2017-05-10 08:59
I know about the shorthand. :smile: 
I clearly remember following the logic that initialises the order class, and seeing that `$order->get_currency()` never returned an empty value (hence my remark that the shorthand might not be necessary). I can't remember the exact details, and I wouldn't be able to dig through the whole change logs, but it was a "head scratcher". 

Anyway, I still think it would make more sense to take the active currency when creating an order. One should not even try to fetch the currency from an order that hasn't been created, it should be expected to be empty.
Alternatively, it should be easy enough to add a filter, during order creation, to override the existing logic. Something like this should be sufficient:

`$order->set_currency( apply_filters(' woocommerce_create_order_currency', $order->get_currency() ? $order->get_currency() : get_woocommerce_currency(), $order ) );`

**Comment by mikejolley** [comment] 2017-05-10 09:01
There are existing hooks that can be used to SET the currency before this logic is even called.

**Comment by daigo75** [comment] 2017-05-10 09:07
Yes, there are hooks for `get_woocommerce_currency()`, which I've been using for years now. I was referring to a hook in the context of order creation (and **only** on order creation, not on order update). I haven't seen such hooks so far, but, if there is one, I will be happy to use it. I would just need to know the name.

**Comment by axelra82** [comment] 2017-05-15 12:11
This error is still happening! Please, I'm asking that someone looks in to this. It would be great if both woocommerce and aelia could try to work together on this. Rather than "shifting blame". It strikes me as odd that this just started happening out of nowhere. There has to be a solution to the problem?

**Comment by mikejolley** [comment] 2017-05-15 12:59
Core has no multiple-at-once-currency support so I cannot debug something for you which another plugin adds. Core records the currency at time of order creation and keeps that value around on future reads/saves. AFAIK that is working as it should.

If @daigo75 finds an issue or needs additional hooks we can add them no problem.

> I've been in contact with aelia and they claim that this is without a doubt woocommerce related (see quote from support ticket with aelia earlier today)

@daigo75 I know it's easy for a 3rd party to shift blame over to the core codebase but it's not reasonable to expect core devs to install 3rd party plugins (especially paid ones!) to do debugging on your customer behalf. 

It's also not great to get customers to log issues on Github directly because it leaves them in no-mans land if core team cannot reproduce.

It would be much better to _find_ the issue, then have your team log proper details here for us to patch on your customer's behalf. Or better yet send a PR. 

cc @mattyza

**Comment by axelra82** [comment] 2017-05-15 13:41
@mikejolley thank you for replying! Look, to be honset I'm right where you say, "in no-mans land". I don't really understand how or why this is happening (as it, from where I'm looking, seems completely random).
I can only go on what I've been told by @daigo75 that this is a core issue. But I don't want to place blame, since I honestly don't understand how bug is even possible (seeing as it does record some orders with the correct currency, and randomly with the base currency).

Like I said in my previous post, I just want this problem solved  😄  and I hope that aelia team takes this seriously enough to try and work with woocommerce, to find a solution. Either way, it sounds to me like wether this is a core issue or not, it inevitably will require something from aelia as well seeing as their plugin has to work within the core functionality?

PS. I've posted back to aelia on my initial support ticket stating that this error/issue is still happening. Here's hoping that both the github issue and ticket will have some effect.

**Comment by daigo75** [comment] 2017-05-15 14:05
@axelra82 as I already explained, none of our plugins changes the currency associated to an order, which is why I excluded them from the possible causes. Besides, there are several elements that indicate that the cause could be somewhere else:
- Orders are paid in the correct currency, but the currency code seems to change after the payment. Our plugin is idle from the moment the payment process starts, and doesn't alter orders that have been created by WooCommerce.
- The glitch occurs randomly. Both WooCommerce and the Currency Switcher are consistent in their behaviour, and process every order the exact same way. There isn't a random element, in those plugins, that could explain why the currency changes only sometimes.
- We still couldn't reproduce the issue on any of our test sites, and we received no reports of it from any other customer. It looks like it's specific to your setup, although I wouldn't be able to speculate what the exact cause could be.

Once we find a way to reproduce the issue consistently, it will be possible to address it.

**Comment by daigo75** [comment] 2017-05-15 15:18
@mikejolley I think there's a misunderstanding. I didn't instruct the customer to open a bug report here. I just explained the client the workflow of the payment process and, since he mentioned that an issue occurred only when PDT payments were processed, I suggested to check with the WC team if there was any setting to be configured about it. That was the only reason why I suggested to contact you.

Shortly after that, it turned out that PDT is not the key element we thought it was, and the customer decided to open a bug report here, by his own initiative. He let me know about it only **after** he created it. I then joined in to provide some clarifications about the topic.

In short, I didn't shift the blame, nor did I try to "dump" a customer to someone else. Simply, we don't know what the cause of the issue is, we can't reproduce it either, and we only know what elements can be excluded (our plugin being one). 

@axelra82 the following statement is incorrect:

> I've been in contact with aelia and they claim that this is without a doubt woocommerce related (see quote from support ticket with aelia earlier today)

I never said anything like that, especially not in that terms. I simply stated that, in the normal flow, the order currency is set by WooCommerce itself (correct), and our plugin doesn't change it (also correct). If that led you to the conclusion that WooCommerce *must* be the culprit, then I didn't express myself clearly, as that's not what I meant.

I will resume the conversation on our own support platform, as it was never meant to be shifted here.

**Comment by axelra82** [comment] 2017-05-15 15:34
@daigo75 OK, I will keep looking on my own. In all fairness it is true that you never instructed me to open an issue here  😄   I did that on my own. And it was simply because, to my understanding from our initial contact, that this issue had to be with woocommerce. Which from what I'm getting now, is not necessarily (or probably at all) the case.

Let me be clear, I'm not interested in finger pointing or blaming. I just want the issue to be resolved (it's somewhat tedious to go thru orders every day to try and see which ones are in incorrect currencies and change them in the database). From my initial understanding this could only come from woocommerce (since it wasn't an aelia issue), it's clear now that this was just a misunderstanding from the original support ticket.

**Comment by axelra82** [comment] 2017-06-09 12:53
I just wanted to inform that this issue has been resolved (for, and if, anyone else encounters similar issues)  : )

The problem was that our external, third party, warehouse software (called ongoing) was using an outdated API version for Woocommerce.
Why and how changes on the currency (reverting back to base currency) on correctly synced order statuses between our store (Woocommerce) and our warehouse (with ongoing) happened is still unknown. But once ongoing updated the API calls, orders that were updated and synced with our warehouse no longer reverted back to our base currency.

PS. We're based in Sweden. I don't know if ongoing is used internationally, but I thought it would be worth mentioning, e.g. for others that might encounter similar problems.

**Comment by daigo75** [comment] 2017-06-09 13:31
@axelra82 Thanks for the update. I'm glad to hear that the issue was found. I will take note of the issue, in case it happens in the future.

**Comment by daigo75** [comment] 2017-09-07 09:53
The issue seems related to a (sneaky) bug I just discovered, reported #16736.
