### ISSUE TITLE
GEOLOCATION not Working even with MaxMind mmdb file in Uploads

### ISSUE THREAD

**Issue by woocommercecodes** [woocommerce/woocommerce#23571] opened 2019-05-01 08:22 UTC
Fresh install of WP 5.1.1 with WC 3.6.2. Checking status WC complains about no geolocation mmdb file. After downloading and uploading said file, WC status is green and okay. WC settings are set to Geolocate. Checkout is still not finding / auto-populating the country list.

See pictures for more details.
Is this normal or a bug?

![blank_country](https://user-images.githubusercontent.com/38051739/57010068-fcdf4f00-6bfa-11e9-8718-f7939ab87ed8.png)
![geodb_installed](https://user-images.githubusercontent.com/38051739/57010069-fcdf4f00-6bfa-11e9-99af-332b342309b1.png)
![geolocation_not_working](https://user-images.githubusercontent.com/38051739/57010070-fd77e580-6bfa-11e9-94ef-29623cc09648.png)

**Comment by rodrigoprimo** [comment] 2019-05-01 19:10
Is the setting "Default customer location" set to "Geolocate" (`/wp-admin/admin.php?page=wc-settings`)? Could you please provide your system status report as request in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=)?

**Comment by woocommercecodes** [comment] 2019-05-01 22:05
Yes, the setting is set to Geolocate.

### WordPress Environment ###
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.4
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 3000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.43-cll-lve
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: local
MaxMind GeoIP Database: ✔
Total Database Size: 1.19MB
Database Data Size: 1.03MB
Database Index Size: 0.16MB
localwoocommerce_sessions: Data: 0.01MB + Index: 0.00MB
localwoocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
localwoocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
localwoocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
localwoocommerce_order_items: Data: 0.00MB + Index: 0.00MB
localwoocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
localwoocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
localwoocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
localwoocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
localwoocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
localwoocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
localwoocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
localwoocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
localwoocommerce_log: Data: 0.00MB + Index: 0.00MB
local: Data: 0.00MB + Index: 0.00MB
localcommentmeta: Data: 0.00MB + Index: 0.01MB
localcomments: Data: 0.00MB + Index: 0.01MB
locallinks: Data: 0.00MB + Index: 0.00MB
localoptions: Data: 0.86MB + Index: 0.03MB
localpostmeta: Data: 0.09MB + Index: 0.03MB
localposts: Data: 0.06MB + Index: 0.02MB
localtermmeta: Data: 0.00MB + Index: 0.01MB
localterms: Data: 0.00MB + Index: 0.01MB
localterm_relationships: Data: 0.00MB + Index: 0.01MB
localterm_taxonomy: Data: 0.00MB + Index: 0.00MB
localusermeta: Data: 0.01MB + Index: 0.01MB
localusers: Data: 0.00MB + Index: 0.01MB
localwc_download_log: Data: 0.00MB + Index: 0.00MB
localwc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
localwc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 26
custom_css: 1
customize_changeset: 2
nav_menu_item: 8
page: 11
post: 1
product: 14
product_variation: 7
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Atomic Blocks - Gutenberg Blocks Collection: by atomicblocks – 1.7.0
Genesis Connect for WooCommerce: by StudioPress – 1.0 – Not tested with the active version of WooCommerce
Genesis eNews Extended: by Brandon Kraft – 2.1.1
Simple Social Icons: by StudioPress – 3.0.0
WooCommerce: by Automattic – 3.6.2
WPForms Lite: by WPForms – 1.5.2.3

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

install.php: install.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #79 - /shop/
Cart: #80 - /cart/
Checkout: #81 - /checkout/
My account: #82 - /my-account/
Terms and conditions: #57 - /block-content-examples/

### Theme ###

Name: Monochrome Pro
Version: 1.2.0
Author URL: https://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.9.1
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: monochrome-pro/woocommerce/global/quantity-input.php

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by rodrigoprimo** [comment] 2019-05-02 13:59
Thanks for sharing the system status report. Nothing in it stood out to me.

I was not able to reproduce this problem. Geolocation seems to be working as expected in WooCommece core.

Unfortunately, this is not a support forum so I will close this issue. We use it only for WooCommerce core bug reports. For support, you can try the WordPress.org support forum (https://wordpress.org/support/plugin/woocommerce/). Alternatively, if you are a paying WooCommerce.com user, you can contact their support (http://woocommerce.com/contact-us/).

You might also want to check this page (https://docs.woocommerce.com/document/how-to-test-for-conflicts/) to rule out plugin/theme conflict.

**Closed by rodrigoprimo** 2019-05-02 13:59 UTC
Labels: status: needs feedback

**Comment by rodrigoprimo** [comment] 2019-05-02 14:00
If I missed something and you are able to reproduce this issue on a clean WooCommerce install, please leave a comment with the steps to reproduce and we will investigate. Thanks.

**Comment by woocommercecodes** [comment] 2019-05-03 19:02
Yes, the issue exist but only for logged in users without any previous orders.

**Comment by rodrigoprimo** [comment] 2019-05-06 18:17
I'm sorry but I'm still not able to reproduce. Are you testing this on a clean WooCommerce install using Storefront or one of the WP official themes? Asking as your system status report mentions a few active plugins and a custom theme.

**Comment by theswedishbear** [comment] 2019-05-06 18:59
Yes, always test everything using a clean install. Yes, using a child theme. The issue is there but it's fine, close it. Now I know how to fix it.
