### ISSUE TITLE
Woocommerce product CSV importer stuck at progress bar

### ISSUE THREAD

**Issue by panaloptec** [woocommerce/woocommerce#28636] opened 2020-12-20 04:40 UTC
Hello!

Following the latest Woocommerce update, I found that my CSV product importer is not working. It allows me to choose the CSV file, then detects the columns, following it goes to the importer but the progress bar won't iniciate and the loading mark keeps going.

I've tried the following:
1) The CSV file has 1325 entries, I've splitted the file in 2. It didn't work.
2) I've disabled all other plugins bit Woocommerce. It didn't work.

This is the first time it causes me trouble. I'll appreciate all the help available. Thanks!

``
### WordPress Environment ###

WordPress address (URL): https://panaloptec.com
Site address (URL): https://panaloptec.com
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.12
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_8gcjnaxhf9_
Tamaño total de la base de datos: 65.12MB
Tamaño de los datos de la base de datos: 54.37MB
Tamaño del índice de la base de datos: 10.75MB
wp_8gcjnaxhf9_woocommerce_sessions: Datos: 29.56MB + Índice: 0.34MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_order_itemmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_actionscheduler_actions: Datos: 0.09MB + Índice: 0.11MB + Motor InnoDB
wp_8gcjnaxhf9_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_actionscheduler_logs: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_cf_forms: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_cf_form_entries: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_8gcjnaxhf9_cf_form_entry_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_cf_form_entry_values: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_8gcjnaxhf9_cf_pro_messages: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_cf_queue_failures: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_cf_queue_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_8gcjnaxhf9_import_detail_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_import_log_detail: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_import_postID: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_ms_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_options: Datos: 6.47MB + Índice: 0.30MB + Motor InnoDB
wp_8gcjnaxhf9_postmeta: Datos: 7.52MB + Índice: 6.03MB + Motor InnoDB
wp_8gcjnaxhf9_posts: Datos: 6.52MB + Índice: 0.66MB + Motor InnoDB
wp_8gcjnaxhf9_smackcsv_file_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_smackuci_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_termmeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_term_relationships: Datos: 0.28MB + Índice: 0.16MB + Motor InnoDB
wp_8gcjnaxhf9_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_tm_taskmeta: Datos: 0.11MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_tm_tasks: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_ulike: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_8gcjnaxhf9_ulike_activities: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_8gcjnaxhf9_ulike_comments: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_8gcjnaxhf9_ulike_forums: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_8gcjnaxhf9_ulike_meta: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_8gcjnaxhf9_ultimate_csv_importer_acf_fields: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_ultimate_csv_importer_mappingtemplate: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_ultimate_csv_importer_media: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_ultimate_csv_importer_shortcode_manager: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_um_metadata: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_8gcjnaxhf9_usermeta: Datos: 0.34MB + Índice: 0.06MB + Motor InnoDB
wp_8gcjnaxhf9_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_8gcjnaxhf9_wap_nex_forms: Datos: 0.02MB + Índice: 0.00MB + Motor MyISAM
wp_8gcjnaxhf9_wap_nex_forms_email_templates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_8gcjnaxhf9_wap_nex_forms_entries: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_8gcjnaxhf9_wap_nex_forms_files: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_8gcjnaxhf9_wap_nex_forms_stats_interactions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_8gcjnaxhf9_wap_nex_forms_views: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_8gcjnaxhf9_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_8gcjnaxhf9_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_8gcjnaxhf9_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_wc_product_meta_lookup: Datos: 0.16MB + Índice: 0.34MB + Motor InnoDB
wp_8gcjnaxhf9_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_wfpklist_template_data: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_woo_shippment_provider: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_8gcjnaxhf9_yoast_indexable: Datos: 1.52MB + Índice: 0.86MB + Motor InnoDB
wp_8gcjnaxhf9_yoast_indexable_hierarchy: Datos: 0.05MB + Índice: 0.05MB + Motor InnoDB
wp_8gcjnaxhf9_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_8gcjnaxhf9_yoast_primary_term: Datos: 0.13MB + Índice: 0.14MB + Motor InnoDB
wp_8gcjnaxhf9_yoast_seo_links: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_8gcjnaxhf9_yoast_seo_meta: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

acf-field: 6
acf-field-group: 1
advgb_profiles: 1
attachment: 1340
custom_css: 2
customize_changeset: 3
elementor_library: 5
logosliderwp: 1
mc4wp-form: 2
ml-slide: 18
ml-slider: 1
nav_menu_item: 12
oembed_cache: 28
page: 10
post: 2
product: 974
product_variation: 458
revision: 321
shop_coupon: 2
shop_order: 15
um_directory: 1
um_form: 3
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Advanced Custom Fields: por Elliot Condon – 5.9.3
Blog Designer: por Solwin Infotech – 2.1.6
Checkout Files Upload for WooCommerce: por WP Wham – 2.0.3
Clear Cache For Me: por Webhead LLC – 1.5
CoBlocks: por GoDaddy – 2.5.3
Custom CSS Injector: por 77 Solutions – 1.0.1
Excel Like Price Change for WooCommerce and WP E-commerce - Light: por Holest Engineering – 2.2.15 – Versión instalada no está probada con la versión activa de WooCommerce 4.0
Facebook for WooCommerce: por Facebook – 2.2.0
Jetpack by WordPress.com: por Automattic – 9.2.1
MetaSlider: por MetaSlider – 3.19.1
Official Facebook Pixel: por Facebook – 2.2.2
Perfect Brands for WooCommerce: por QuadLayers – 1.8.5
Post Expirator: por Aaron Axelsen – 2.4.1
SiteOrigin CSS: por SiteOrigin – 1.2.12
Ultimate Addons for Gutenberg: por Brainstorm Force – 1.19.0
Ultimate Member: por Ultimate Member – 2.1.13
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.16.43

User Blocker: por Solwin Infotech – 1.5.2
WebData Custom Shipping Methods for WooCommerce: por web-data.online – 1.3.6 – Versión instalada no está probada con la versión activa de WooCommerce 4.0
WebP Converter for Media: por Mateusz Gbiorczyk – 2.0.1
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.4.4
WooCommerce AJAX Cart: por Moises Heberle – 1.3.19
WooCommerce Checkout Field Editor: por WooCommerce – 1.5.38
WooCommerce Shipping & Tax: por Automattic – 1.25.4
WooCommerce: por Automattic – 4.8.0
WP Font Awesome: por Zayed Baloch – 1.7.7
WP-Optimize - Clean, Compress, Cache: por David Anderson
Ruhani Rabin
Team Updraft – 3.1.6

Smush: por WPMU DEV – 3.8.2

### Inactive Plugins (3) ###

PublishPress Blocks: por PublishPress – 2.5.0
WP Ultimate Exporter: por Smackcoders – 1.5.7 – Versión instalada no está probada con la versión activa de WooCommerce 4.0
Yoast SEO: por Team Yoast – 15.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: APCu Object Cache

### Must Use Plugins (1) ###

System Plugin: por  – 3.23.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la tienda: #213 - /productos/
Carrito: #31 - /carrito/
Finalizar compra: #32 - /finalizar-compra/
Mi cuenta: #33 - /mi-cuenta/
Términos y condiciones: #3 - /privacy-policy/

### Theme ###

Name: Ultimate Ecommerce Shop
Version: 0.3.6
Author URL: https://www.logicalthemes.com
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: ultimate-ecommerce-shop/woocommerce/archive-product.php
ultimate-ecommerce-shop/woocommerce/checkout/form-checkout.php
ultimate-ecommerce-shop/woocommerce/global/wrapper-end.php
ultimate-ecommerce-shop/woocommerce/global/wrapper-start.php
ultimate-ecommerce-shop/woocommerce/single-product.php

### Checkout Files Upload Settings ###

WooCommerce Checkout Files Upload: yes
Total file uploaders: 1
Form extras: yes
Enable alert on successful file upload: no
Enable alert on successful file remove: no
Max file size: 0
alg_checkout_files_upload_max_file_size_exceeded_message: Allowed file size exceeded (maximum %max_file_size% MB).
Attach files to admin's new order emails: yes
Attach files to customer's processing order emails: no
Send additional email to admin on user actions: Array
(
)
Attach file on upload action: yes
Recipient(s): (set)
Subject: [{site_title}] Comprobante de compra de ({order_number}) - {order_date}
Email heading: {action}: File #{file_num}
Email content: File name: {file_name}
Action: File removed: File removed
Action: File uploaded: File uploaded
Before: Label:
					 
					%field_label%%required_html%
				
												
					Field Container:
					 
					%button_html% %field_html%
				
												
					Uploaded File:
					 
					%image% %file_name% %remove_button%
				
												
					After:
Label: 
%field_label%%required_html%: 
Field Container: 
%button_html% %field_html%: 
Uploaded File: %image% %file_name% %remove_button%
After: 
"Delete" button style: color:red;
Image style: width:64px;
Enable/disable: yes
Required: no
Accepted file types: 
Validate image dimensions: 
Width: 1
Height: 1
Checkout page: woocommerce_after_checkout_form
Position order (i.e. priority): 20
"Thank You" page: no
"My Account" page: no
Label: Si ya tiene listo su comprobante de pago
puede adjuntarlo a continuación:

Upload button (single): Choose File
Wrong file type: Wrong file type: "%s"!
Wrong image dimensions: Wrong image dimensions: "%s"! Current: %current_width% x %current_height%. Required: %required_width% x %required_height%.
Couldn't get image dimensions: Couldn't get image dimensions: "%s"!
File is required: File is required!
File was successfully uploaded: File "%s" was successfully uploaded.
No file selected: Please select file to upload!
File was successfully removed: File "%s" was successfully removed.
Require products: Array
(
)
Require product categories: Array
(
)
Require product tags: Array
(
)
Label: 
%field_label%%required_html%: 
Field Container: 
%button_html% %field_html%: 
Uploaded File: %image% %file_name% %remove_button%
After: 

### Action Scheduler ###

Completo: 163
Oldest: 2020-11-24 22:34:37 +0000
Newest: 2020-12-20 04:20:42 +0000

Pendiente: 1
Oldest: 2020-12-20 04:29:23 +0000
Newest: 2020-12-20 04:29:23 +0000

``

**Comment by juliaamosova** [comment] 2020-12-29 21:05
Hi @panaloptec,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- You seem to be a paying customer of WooCommerce which allows you to contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-12-29 21:05 UTC
