### ISSUE TITLE
Further Education Link is Broken

### ISSUE THREAD

**Issue by pikurasa** [woocommerce/woocommerce#26277] opened 2020-04-24 15:05 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Go to 'help' for WooCommerce (at top of screen)
2. Click on 'education' and then 'further education'
3. It sends you to https://docs.woocommerce.com/document/further-education/?utm_source=helptab&utm_medium=product&utm_content=edupartners&utm_campaign=woocommerceplugin
4. See error "Oops! That page can’t be found"

**Expected behavior**
I expect that the user would be sent to a page with more educational materials (and no "page not found". I do not know what the new page is, however. When searching for "education" on the docs page, I see two links https://docs.woocommerce.com/?s=education&post_type=documentation&search_in=

**Comment by juliaamosova** [comment] 2020-04-24 15:19
Hi @pikurasa,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported. I don't see the `education` option. Could it be that you are using older version of WooCommerce?

Here is how the new `Help` section will look like [as soon as we release WooCommerce 4.1 on May 5th](https://woocommerce.wordpress.com/2020/04/22/woocommerce-4-1-release-candidate-available-now/):

![help](https://user-images.githubusercontent.com/19143190/80228633-48b1b200-861d-11ea-9fd5-f267e14d3dda.jpg)

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by pikurasa** [comment] 2020-04-24 16:23
> Could it be that you are using older version of WooCommerce?

I am on `WooCommerce version: 		4.0.1`

**Comment by juliaamosova** [comment] 2020-04-24 16:36
Thanks for clarification @pikurasa! We removed the `Education` section altogether in the upcoming version of WooCommerce (will be released on May 5th). 

Instead, users can click on `please read our documentation` in the `Help & Support` section:

![doc1](https://user-images.githubusercontent.com/19143190/80235631-f32ed280-8627-11ea-96b0-03623256aaa6.jpg)

There is also a new Marketing section with `WooCommerce knowledge base` (related to marketing specifically, however):

![doc2](https://user-images.githubusercontent.com/19143190/80235742-21141700-8628-11ea-919f-66c60a7e0d77.jpg)

I am closing this issue since there is no action for us to take on this at the moment.

**Closed by juliaamosova** 2020-04-24 16:36 UTC
Labels: can't reproduce, status: needs feedback
