### ISSUE TITLE
Misalignment on the Store Setup screen on the onboarding wizard

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#24704] opened 2019-09-27 16:52 UTC
**Describe the bug**
There are some input fields on the Store Setup screen that are not aligned (address, address line 2, city, postcode and the checkbox of "I will also sell products in person"): https://cld.wthms.co/IgHu6d

**Comment by peterfabian** [comment] 2019-10-02 10:25
Thanks for reporting. 
Please see: https://github.com/woocommerce/woocommerce/pull/24700

**Comment by rodrigoprimo** [comment] 2019-10-03 13:36
I am reopening this as I believe that only part of the problems on the OBW were fixed in #24708. On a quick check, it seems to me that those problems (at least part of them) were caused by a CSS change introduce in WP 5.2.3. More specifically, the addition of the file `/wp-admin/css/forms.css`, which is enqueued when loading the OBW running WP 5.2.3, but it is not when running WP 5.2.2 seems to be related.

There are at least two changes that I believe we should fix as the interface looks broken. As I mentioned in https://github.com/woocommerce/woocommerce/pull/24700#issuecomment-535968334, the checkboxes in the payment step are wider then what they used to be. Besides that, in the store setup step, the right side of all the input fields used to be vertically aligned with the select fields, and now they are not anymore.

There are also some minor changes, and we might want to ignore them (though I don't think I'm the best person to make this decision): there is a small difference in the height of the input fields, and also the font used for the `<button>` elements changed.

See screenshots below for a visual representation of what I described above. I only took screenshots of the first two steps as I couldn't notice any difference in the other steps (besides the different font for the buttons, which affects all OBW pages).

**Store Setup step**

WP 5.2.2:

![Screenshot from 2019-10-03 10-15-09](https://user-images.githubusercontent.com/77215/66129892-2a279300-e5c7-11e9-8729-19cd652659f0.png)

WP 5.2.3:

![Screenshot from 2019-10-03 10-15-14](https://user-images.githubusercontent.com/77215/66129963-49262500-e5c7-11e9-87b8-217ef02e3598.png)


**Payment step**

WP 5.2.2:

![Screenshot from 2019-10-03 10-20-24](https://user-images.githubusercontent.com/77215/66130219-bd60c880-e5c7-11e9-998c-738c36b587fa.png)

WP 5.2.3:

![Screenshot from 2019-10-03 10-20-51](https://user-images.githubusercontent.com/77215/66130216-bb970500-e5c7-11e9-962a-f2dd5091c827.png)

**Comment by peterfabian** [comment] 2019-10-17 08:15
PR #24832 should fix these problems.

**Closed by peterfabian** 2019-10-17 08:15 UTC
Labels: bug
