### ISSUE TITLE
Search box on admin screen pushed to bottom and covered by footer on smaller screens < 782px

### ISSUE THREAD

**Issue by ralphonz** [woocommerce/woocommerce#22162] opened 2018-12-06 16:45 UTC
**Describe the bug**
The search box is covered by the admin footer text on the products table page.

**To Reproduce**
1. Make window less than 782 (smaller the better)
2. Go to "Products"
3. Scroll down to the bottom of the page
4. See error - footer text overlaps the search box

**Screenshots**
<img width="660" alt="screenshot 2018-12-06 at 16 41 47" src="https://user-images.githubusercontent.com/5305856/49598193-04fdd000-f976-11e8-9a6d-068f933dc37e.png">
<img width="504" alt="screenshot 2018-12-06 at 16 42 32" src="https://user-images.githubusercontent.com/5305856/49598194-062efd00-f976-11e8-8b82-fc663ddea102.png">

**Expected behavior**
Search box should at least push the footer down the page.  In my opinion the search should appear at the top of the page not the bottom anyway....

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2018-12-06 16:51
Duplicate of #22163

**Comment by ralphonz** [comment] 2018-12-06 16:55
> Duplicate of #22163

Arrgh!  Github gave me a 404 the first time I tried to submit the issue!  Sorry for the duplicate.

**Comment by rrennick** [comment] 2018-12-06 17:09
@ralphonz If you have a minute, can you close this issue?

**Closed** 2018-12-06 18:01 UTC
