### ISSUE TITLE
Hang when trying to use variations

### ISSUE THREAD

**Issue by eurowoocommerce** [woocommerce/woocommerce#30346] opened 2021-07-24 16:26 UTC
Howdy,

I have a problem when I try to add variation, it get stuck on it, and in the browser console I have some errors, about a missing function.
What can I do?
WP and EC is the latest.

Thanks in advanced,

![image](https://user-images.githubusercontent.com/87908500/126874865-645709ee-5411-44ff-ae1e-5cc3b22ef56a.png)

**Comment by rajeshsingh520** [comment] 2021-07-26 10:17
Hi,

Make sure you are not loading multiple copies of jQuery and you are loading the selectWoo.full.min.js file 

you can deactivate all the plugin in your site and only keep Woo Commerce active and switch to Twenty-Twenty theme to test it out so other plugin do not interfere with your Woo Commerce working

**Comment by rodelgc** [comment] 2021-07-28 07:23
Hi @eurowoocommerce,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodelgc** 2021-07-28 07:23 UTC
