### ISSUE TITLE
German umlauts (ö,ä,ü,ß) will be removed in mails

### ISSUE THREAD

**Issue by XKEYFA** [woocommerce/woocommerce#30005] opened 2021-05-29 19:39 UTC
In german version of the send mails (translated) all umlauts are removed.
I identified the following lines which remove the umlauts:

https://github.com/woocommerce/woocommerce/blob/84f8fcd01612cac82ffa35cf489d84daea24e4c4/includes/emails/class-wc-email.php#L571
https://github.com/woocommerce/woocommerce/blob/84f8fcd01612cac82ffa35cf489d84daea24e4c4/includes/emails/class-wc-email.php#L572
https://github.com/woocommerce/woocommerce/blob/84f8fcd01612cac82ffa35cf489d84daea24e4c4/includes/emails/class-wc-email.php#L573

I think is a problem of the html pruner, but I'm not sure. I removed the lines for tests then the mails are fine.

**Comment by lkraav** [comment] 2021-05-30 12:10
https://github.com/woocommerce/woocommerce/pull/26075#commitcomment-51291465

This is probably a #26075 regression confirmation.

**Comment by tammullen** [comment] 2021-06-02 11:40
Hi @XKEYFA 

I couldn't reproduce this, I added a note to an order with umlauts and that they didn't get removed in the email.

![Screenshot 2021-06-02 at 12 24 28](https://user-images.githubusercontent.com/24649833/120473941-78de8f00-c39f-11eb-96c2-e63e33a9dfe7.png)
![Screenshot 2021-06-02 at 12 24 48](https://user-images.githubusercontent.com/24649833/120473953-7d0aac80-c39f-11eb-91a7-fa38a4d6d03e.png)

Can you provide steps to reproduce this issue?

**Comment by XKEYFA** [comment] 2021-06-02 16:57
Hello @tammullen, 
Thank you for the feedback. 
I think i do nothing special but all umlauts are missing in my mails. See attached one.
Prune removed from code result:
![prune_removed_edit](https://user-images.githubusercontent.com/14006351/120520229-d7256500-c3d3-11eb-8938-57d9445fb8ab.jpg)
Prune active (without changes):
![prune_active_edit](https://user-images.githubusercontent.com/14006351/120520231-d8569200-c3d3-11eb-80ea-d200b7ac4386.jpg)

As you can see all umlauts are missing. I don't know what effects the pruner. Perhaps this can be a special behavior of the used php version?
i currently use: 

PHP Version 7.2.34

Best regards,

Sebastian

**Comment by AashikP** [comment] 2021-07-31 03:37
Hi there!

While not on PHP 7.2 ([as it has reached EOL](https://www.php.net/supported-versions.php)), I did test on PHP 7.3, but couldn't replicate the same behavior:

![https://d.pr/i/ZXyVXG+](https://d.pr/i/ZXyVXG+)

Considering [WooCommerce Recommends PHP 7.4 or greater](https://docs.woocommerce.com/document/server-requirements/#section-1), I'm closing this issue for now.

Please feel free to comment here again if there's another way to replicate this issue (along with your System Status Report), or if we missed any steps here, and we'll be glad to investigate further.

**Closed by AashikP** 2021-07-31 03:37 UTC
Labels: category: can't reproduce, has feedback
