### ISSUE TITLE
Missing database tables after upgrade to Wordpress 5.0.3

### ISSUE THREAD

**Issue by checkm94** [woocommerce/woocommerce#22509] opened 2019-01-21 08:20 UTC
**Describe the bug**
After upgrading to Wordpress 5.0.3, Woocommerce stopped calculating shipping costs. I've checked the Woocommerce system status

**To Reproduce**
1. Go to 'Woocommerce'
2. Click on 'System Status'
3. Scroll down to '### Database ###.'

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

Home URL: https://[...].it
Site URL: https://[...].it
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.8
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.33-cll-lve
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Il tuo server non ha la classe SoapClient attiva - alcuni plugin gateway che usano SOAP potrebbero non funzionare correttamente.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: IOd_
MaxMind GeoIP Database: ✔
Dimensione totale database: 34.44MB
Dimensione dati database: 30.76MB
Dimensione indice database: 3.68MB
IOd_woocommerce_sessions: ❌ La tabella non esiste
IOd_woocommerce_api_keys: ❌ La tabella non esiste
IOd_woocommerce_attribute_taxonomies: ❌ La tabella non esiste
IOd_woocommerce_downloadable_product_permissions: ❌ La tabella non esiste
IOd_woocommerce_order_items: ❌ La tabella non esiste
IOd_woocommerce_order_itemmeta: ❌ La tabella non esiste
IOd_woocommerce_tax_rates: ❌ La tabella non esiste
IOd_woocommerce_tax_rate_locations: ❌ La tabella non esiste
IOd_woocommerce_shipping_zones: ❌ La tabella non esiste
IOd_woocommerce_shipping_zone_locations: ❌ La tabella non esiste
IOd_woocommerce_shipping_zone_methods: ❌ La tabella non esiste
IOd_woocommerce_payment_tokens: ❌ La tabella non esiste
IOd_woocommerce_payment_tokenmeta: ❌ La tabella non esiste
IOd_woocommerce_log: ❌ La tabella non esiste
iod_atum_order_itemmeta: Dati: 0.00MB + Indice: 0.00MB
iod_atum_order_items: Dati: 0.00MB + Indice: 0.00MB
iod_commentmeta: Dati: 0.00MB + Indice: 0.01MB
iod_comments: Dati: 0.01MB + Indice: 0.01MB
iod_ewwwio_images: Dati: 0.00MB + Indice: 0.00MB
iod_failed_jobs: Dati: 0.00MB + Indice: 0.00MB
iod_fattura_tax: Dati: 0.00MB + Indice: 0.00MB
iod_layerslider: Dati: 0.00MB + Indice: 0.00MB
iod_layerslider_revisions: Dati: 0.00MB + Indice: 0.00MB
iod_links: Dati: 0.00MB + Indice: 0.00MB
iod_mailchimp_carts: Dati: 0.00MB + Indice: 0.00MB
iod_ms_snippets: Dati: 0.00MB + Indice: 0.00MB
iod_options: Dati: 26.65MB + Indice: 2.22MB
iod_postmeta: Dati: 2.73MB + Indice: 1.08MB
iod_posts: Dati: 0.85MB + Indice: 0.13MB
iod_queue: Dati: 0.04MB + Indice: 0.00MB
iod_say_what_strings: Dati: 0.00MB + Indice: 0.00MB
iod_snippets: Dati: 0.00MB + Indice: 0.00MB
iod_termmeta: Dati: 0.02MB + Indice: 0.02MB
iod_terms: Dati: 0.02MB + Indice: 0.04MB
iod_term_relationships: Dati: 0.04MB + Indice: 0.09MB
iod_term_taxonomy: Dati: 0.02MB + Indice: 0.02MB
iod_usermeta: Dati: 0.02MB + Indice: 0.01MB
iod_users: Dati: 0.00MB + Indice: 0.01MB
iod_wcpdf_invoice_number: Dati: 0.00MB + Indice: 0.00MB
iod_wc_download_log: Dati: 0.00MB + Indice: 0.00MB
iod_wc_webhooks: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_api_keys: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_attribute_taxonomies: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_downloadable_product_permissions: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_log: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_order_itemmeta: Dati: 0.01MB + Indice: 0.01MB
iod_woocommerce_order_items: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_payment_tokenmeta: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_payment_tokens: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_sessions: Dati: 0.35MB + Indice: 0.02MB
iod_woocommerce_shipping_zones: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_shipping_zone_locations: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_shipping_zone_methods: Dati: 0.00MB + Indice: 0.00MB
iod_woocommerce_tax_rates: Dati: 0.00MB + Indice: 0.01MB
iod_woocommerce_tax_rate_locations: Dati: 0.00MB + Indice: 0.00MB

### Post Type Counts ###

attachment: 417
customize_changeset: 23
custom_css: 2
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 17
page: 13
post: 6
product: 455
product_variation: 2
revision: 88
shop_coupon: 2
shop_order: 26
testimonial: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Cookie Notice: by dFactory – 1.2.45
Jetpack by WordPress.com: by Automattic – 6.9
WPBakery Page Builder: by Michael M - WPBakery.com – 5.6
Kadence WooCommerce Email Designer: by Kadence Themes – 1.1.3
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Non testato con la versione attiva di WooCommerce
Paga con Bollettino: by Elena Caramanico – 1.0 – Non testato con la versione attiva di WooCommerce
Re-Add Text Justify Button: by Salvatore Cordiano – 0.1.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.4

WooCommerce Blocks: by Automattic – 1.3.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.6
WooCommerce Remove All Products: by Gabriel Reguly – 1.0.6 – Non testato con la versione attiva di WooCommerce
WooCommerce Services: by Automattic – 1.18.0
WooCommerce: by Automattic – 3.5.3
Fattura24: by Fattura24.com – 3.5.3
Logged-in-only: by Ralf Wiechers – 2.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /negozio/
Carrello: #3658 - /carrello/
Cassa: #3659 - /checkout/
Il mio account: #8 - /mio-account/
Termini e condizioni: #3667 - /reso/

### Theme ###

Name: Aurum - Child Theme
Version: 1.0
Author URL: http://laborator.co/
Child Theme: ✔
Parent Theme Name: Aurum
Parent Theme Version: 3.4.2.1
Parent Theme Author URL: https://laborator.co/
WooCommerce Support: ✔

### Templates ###

Overrides: aurum/woocommerce/archive-product.php
aurum/woocommerce/cart/cart-empty.php
aurum/woocommerce/cart/cart-shipping.php
aurum/woocommerce/cart/cart-totals.php
aurum/woocommerce/cart/cross-sells.php
aurum/woocommerce/cart/shipping-calculator.php
aurum/woocommerce/checkout/form-billing.php
aurum/woocommerce/checkout/form-checkout.php
aurum/woocommerce/checkout/form-coupon.php
aurum/woocommerce/checkout/form-login.php
aurum/woocommerce/checkout/form-pay.php
aurum/woocommerce/checkout/form-shipping.php
aurum/woocommerce/checkout/payment-method.php
aurum/woocommerce/checkout/review-order.php
aurum/woocommerce/checkout/thankyou.php
aurum/woocommerce/content-product.php
aurum/woocommerce/global/form-login.php
aurum/woocommerce/loop/orderby.php
aurum/woocommerce/loop/pagination.php
aurum/woocommerce/loop/sale-flash.php
aurum/woocommerce/myaccount/form-edit-account.php
aurum/woocommerce/myaccount/form-edit-address.php
aurum/woocommerce/myaccount/form-login.php
aurum/woocommerce/myaccount/form-lost-password.php
aurum/woocommerce/myaccount/form-reset-password.php
aurum/woocommerce/myaccount/my-address.php
aurum/woocommerce/myaccount/orders.php
aurum/woocommerce/myaccount/view-order.php
aurum/woocommerce/order/form-tracking.php
aurum/woocommerce/order/order-details-item.php
aurum/woocommerce/order/order-details.php
aurum/woocommerce/order/order-downloads.php
aurum/woocommerce/single-product/add-to-cart/variable.php
aurum/woocommerce/single-product/meta.php
aurum/woocommerce/single-product/review.php
aurum/woocommerce/single-product/sale-flash.php
aurum/woocommerce/single-product/tabs/additional-information.php
aurum/woocommerce/single-product/tabs/tabs.php
aurum/woocommerce/single-product/title.php
aurum/woocommerce/single-product-reviews.php

`
</details>

**Comment by rrennick** [comment] 2019-01-21 12:58
I was not able to reproduce this in my install. It looks like something is changing your table prefix from `iod` to `IOd`. I suggest you investigate that first. If you have resolved that and still have the issue, please post your WooCommerce version.

**Comment by checkm94** [comment] 2019-01-21 14:11
You mean that it could be a plugin changing the table prefix? How can I investigate it? I took a look at phpMyAdmin and table names are ok.

**Comment by rrennick** [comment] 2019-01-21 15:35
> I took a look at phpMyAdmin and table names are ok.

All of the tables showing an error in your system status report have the wrong prefix in that report. In PHP strings are case sensitive and matching `IOd_woocommerce_sessions` to `iod_woocommerce_sessions` will fail.

**Comment by rrennick** [comment] 2019-01-21 20:20
Are the tables actually named with the capital letters?

**Comment by checkm94** [comment] 2019-01-22 19:36
I've tried to change the table prefix but suddenly I was unable to access to wp-admin. If I look closer to system status we notice that those `IOd_` missing tables are actually duplicated "lowercase": for instance, a `iod_woocommerce_shipping_zone_locations` does exist, in place of `IOd_woocommerce_shipping_zone_locations`. So, from a practical point of view Woocommerce is working well even without them.

**Comment by rrennick** [comment] 2019-01-23 13:34
> a iod_woocommerce_shipping_zone_locations does exist, in place of IOd_woocommerce_shipping_zone_locations.

It looks like something happened with your database during the upgrade. Do you have a backup of the DB from before the update was applied that you could test with?

**Comment by mikejolley** [comment] 2019-02-01 16:45
I'm unsure if the missing tables are for sure related to the loss of shipping, but thats certainly something to resolve first. WC woulnd't change your database prefix since thats part of your config file.  

I'd suggest renaming tables and the prefix in your config file lowercase to get the status report listing them as detected correctly - work with the host if neccessary.

If the prefix is wrong, WC likely cannot read from the table containing shipping rates and zones.

Closing this for now as it's not related to WC itself, but the hosting environment. Report back if you find anything else though.

Thanks

**Closed by mikejolley** 2019-02-01 16:45 UTC
Labels: status: needs feedback
