### ISSUE TITLE
EMAIL NOTIFICATION FAIL

### ISSUE THREAD

**Issue by woodnlove** [woocommerce/woocommerce#20720] opened 2018-07-06 11:48 UTC
My clients do not get email notifications and I do not get them either. If I try to resend it it does not work. Where is the problem? I have checked settings and there is all ok.

**Comment by Onyx808** [comment] 2018-07-06 20:07
I have the same issue and Im using smtp, the website can send emails just fine, just woo commerce emails are not being sent...

**Comment by Onyx808** [comment] 2018-07-06 21:14
I had custom email templates on my theme, I renamed the /themes/mytheme/woocommerce/emails folder to something else and resent the emails and it worked.

**Comment by woodnlove** [comment] 2018-07-06 23:28
Thank you. I will try.


Pozdrawiam.


Damian Adamiec
www.woodnlove.com
www.facebook.com/woodnloveboxes
office@woodnlove.com
tel: +48 601150060

**Comment by kloon** [comment] 2018-07-09 11:20
Closing as this is not a bug but a support request. In the future, if you have support requests please use the appropriate channels and follow the instructions as per the template before opening the issue, if you did you would have likely found it was your theme or a plugin causing the issue.

**Closed by kloon** 2018-07-09 11:20 UTC

**Comment by woodnlove** [comment] 2018-07-10 10:57
support does not answer.


Pozdrawiam.


Damian Adamiec
www.woodnlove.com
www.facebook.com/woodnloveboxes
office@woodnlove.com
tel: +48 601150060
