### ISSUE TITLE
Birth Year Saved to Company Name Field - Chrome Autofill Conflict?

### ISSUE THREAD

**Issue by gthayer** [woocommerce/woocommerce#21075] opened 2018-08-16 14:36 UTC
**Describe the bug**
I've noticed on my WooCommerce sites `_billing_company` is occasionally being saved as a year, like `1996` or `1978`. While rare, I've seen this on anywhere between 0.5%-1.5% of orders.

I've seen this on pretty much all of my client sites, who are using different plugin and theme combinations. Looking at Analytics, most of these orders are Chrome. My guess is Chromes Autofill is setting the value and customers are not double checking. If a customer has a bad values saved as their company, there is not much to be done, but Birth Year seems like a consistent trend.

**To Reproduce**
I have not actually been able to force the saving of data, but I found the values in my client sites with: `SELECT *  FROM wp_postmeta WHERE meta_key LIKE '_billing_company'  and meta_value REGEXP '^[0-9]+$'`

**Expected behavior**
I would not expect birth year to be saved. Not sure why this is a common trend.

**Comment by thomas-zg** [comment] 2018-08-16 15:14
I'm not shure if it makes sense to handle such a custom validation in Woocommerce core. Why not implement something by using the woocommerce_checkout_process action to fit to your needs?

**Comment by claudiulodro** [comment] 2018-08-16 16:49
[The company name field has the autocomplete attribute "organization"](https://github.com/woocommerce/woocommerce/blob/ec0613ad78f6ae2382eab54baa6bad34278aa917/includes/class-wc-countries.php#L643), which [is the correct attribute for that field](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-organization). If for some reason there were another site that had that autocomplete attribute incorrectly assigned to some sort of year field it's conceivable this issue could happen (e.g. birth date while registering for something). 

I'll leave this open for a while longer in case someone has any extra insight, but I think that is an issue with some fairly popular unknown other site, and not with WooCommerce. :)

**Comment by jacksonwp** [comment] 2018-08-21 15:33
I'm seeing this issue with regularity on multiple installs. We also frequently see the order_comments field populated with address data. It's a shame there's no way to filter the autocomplete value of the checkout inputs.

**Comment by claudiulodro** [comment] 2018-08-21 16:33
@jacksonwp [you can filter them right here](https://github.com/woocommerce/woocommerce/blob/ec0613ad78f6ae2382eab54baa6bad34278aa917/includes/class-wc-countries.php#L705).

I'm closing this issue as it seems to be caused by user error and WooCommerce is working correctly.

**Closed by claudiulodro** 2018-08-21 16:33 UTC
Labels: question

**Comment by jacksonwp** [comment] 2018-08-21 21:11
@claudiulodro my bad, I was referring to [this help doc](https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/) and some other bad info I found Googling. Should have checked the source.

For what it's worth, I don't think it's user error but more a bug with Chrome and how it's matching the autocomplete fields with their form submission history. Just today we had a customer order come in with billing_company set to "Please select:" . As usual when questioned the customer had no idea why that was in that field and had not intentionally entered that text.

**Comment by webdepotet** [comment] 2018-11-13 15:18
This is actually a issue needs to resolved, i get not 1% order, i see it in every 5 order i have - and loss of orders is frequently due to this .....

How to fix it?

**Comment by JLDesigns** [comment] 2019-01-18 20:31
Did anyone find a fix for this? I'm seeing it more and more in my WooCommerce orders. Is there anyway to change the field name so Chrome doesn't autofill the Company Name with the users birthday? Thank you in advance!

**Comment by rrennick** [comment] 2019-01-18 20:37
@JLDesigns You can use the `woocommerce_default_address_fields` to disable autocomplete for address fields.

**Comment by leonwagner** [comment] 2019-02-12 18:28
> You can use the `woocommerce_default_address_fields` to disable autocomplete for address fields.

What does that mean? How would I use this only to suppress the bogus birth year in company name field?

**Comment by leonwagner** [comment] 2019-02-12 18:29
We are seeing this on a lot of orders and in some cases, the customer is really annoyed by it. Not good. We don't want to disable all autofill (because that's not good, either). Just want to prevent a year from appearing in the company name field.
