### ISSUE TITLE
Variation attribute lost

### ISSUE THREAD

**Issue by eedea** [woocommerce/woocommerce#22841] opened 2019-02-24 09:42 UTC
**Describe the bug**
I don't know if it's a bug. I didn't see this in any other woocommerce powered site.
There are some specific variable products in my site which their child products loose their attributes after some random days without any changes.
For example a product has a "size" attribute and two variations: "large" and "small". After some days, in backend, both variations' attributes  changes to "pa_size". in REST API, attributes array of variation child changes to an empty array: []. And in front end, it shows both options but both shows price of the first one!
**To Reproduce**
I couldn't find any specific pattern.

**Screenshots**
![screen shot - - at](https://user-images.githubusercontent.com/26795889/53297602-cae5f100-3835-11e9-929c-fd26be38dea9.png)
![screen shot - - at](https://user-images.githubusercontent.com/26795889/53297603-cae5f100-3835-11e9-8214-d42e283d9e1a.png)

**Expected behavior**
a product variation should hold it's attributes.
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: 5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fa_IR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.23 - توصیه می کنیم از نسخه PHP 7.2 یا بالاتر برای عملکرد و امنیت بیشتر استفاده کنید. چگونه نسخه PHP را بروزرسانی کنیم
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
مجموع اندازه پایگاه داده: 48.85MB
اندازه داده های پایگاه داده: 31.64MB
اندازه داده های شاخص پایگاه داده: 17.21MB
wp_woocommerce_sessions: داده: 1.02MB + شاخص: 0.06MB
wp_woocommerce_api_keys: داده: 0.02MB + شاخص: 0.03MB
wp_woocommerce_attribute_taxonomies: داده: 0.02MB + شاخص: 0.02MB
wp_woocommerce_downloadable_product_permissions: داده: 0.02MB + شاخص: 0.05MB
wp_woocommerce_order_items: داده: 0.02MB + شاخص: 0.02MB
wp_woocommerce_order_itemmeta: داده: 0.06MB + شاخص: 0.03MB
wp_woocommerce_tax_rates: داده: 0.02MB + شاخص: 0.06MB
wp_woocommerce_tax_rate_locations: داده: 0.02MB + شاخص: 0.03MB
wp_woocommerce_shipping_zones: داده: 0.02MB + شاخص: 0.00MB
wp_woocommerce_shipping_zone_locations: داده: 0.02MB + شاخص: 0.03MB
wp_woocommerce_shipping_zone_methods: داده: 0.02MB + شاخص: 0.00MB
wp_woocommerce_payment_tokens: داده: 0.02MB + شاخص: 0.02MB
wp_woocommerce_payment_tokenmeta: داده: 0.02MB + شاخص: 0.03MB
wp_woocommerce_log: داده: 0.02MB + شاخص: 0.02MB
wp_commentmeta: داده: 0.02MB + شاخص: 0.03MB
wp_comments: داده: 0.02MB + شاخص: 0.09MB
wp_digits_blocked_ip: داده: 0.02MB + شاخص: 0.00MB
wp_digits_mobile_otp: داده: 0.02MB + شاخص: 0.00MB
wp_digits_requests_log: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_announcement: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_orders: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_product_map: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_refund: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_shipping_zone_locations: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_shipping_zone_methods: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_vendor_balance: داده: 0.02MB + شاخص: 0.00MB
wp_dokan_withdraw: داده: 0.02MB + شاخص: 0.00MB
wp_duplicator_packages: داده: 0.00MB + شاخص: 0.00MB
wp_ewwwio_images: داده: 0.00MB + شاخص: 0.00MB
wp_gf_addon_feed: داده: 0.00MB + شاخص: 0.00MB
wp_gf_draft_submissions: داده: 0.00MB + شاخص: 0.00MB
wp_gf_entry: داده: 0.00MB + شاخص: 0.00MB
wp_gf_entry_meta: داده: 0.00MB + شاخص: 0.01MB
wp_gf_entry_notes: داده: 0.00MB + شاخص: 0.00MB
wp_gf_form: داده: 0.00MB + شاخص: 0.00MB
wp_gf_form_meta: داده: 0.02MB + شاخص: 0.00MB
wp_gf_form_view: داده: 0.00MB + شاخص: 0.00MB
wp_groups_capability: داده: 0.01MB + شاخص: 0.02MB
wp_groups_group: داده: 0.00MB + شاخص: 0.00MB
wp_groups_group_capability: داده: 0.00MB + شاخص: 0.00MB
wp_groups_user_capability: داده: 0.00MB + شاخص: 0.00MB
wp_groups_user_group: داده: 0.00MB + شاخص: 0.00MB
wp_links: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_custom_fields: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_forms: داده: 0.02MB + شاخص: 0.00MB
wp_mailpoet_log: داده: 0.02MB + شاخص: 0.00MB
wp_mailpoet_mapping_to_external_entities: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_newsletters: داده: 0.02MB + شاخص: 0.00MB
wp_mailpoet_newsletter_links: داده: 0.02MB + شاخص: 0.03MB
wp_mailpoet_newsletter_option: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_newsletter_option_fields: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_newsletter_posts: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_newsletter_segment: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_newsletter_templates: داده: 1.42MB + شاخص: 0.00MB
wp_mailpoet_scheduled_tasks: داده: 0.02MB + شاخص: 0.03MB
wp_mailpoet_scheduled_task_subscribers: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_segments: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_sending_queues: داده: 0.02MB + شاخص: 0.03MB
wp_mailpoet_settings: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_statistics_clicks: داده: 0.02MB + شاخص: 0.05MB
wp_mailpoet_statistics_forms: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_statistics_newsletters: داده: 0.02MB + شاخص: 0.03MB
wp_mailpoet_statistics_opens: داده: 0.02MB + شاخص: 0.05MB
wp_mailpoet_statistics_unsubscribes: داده: 0.02MB + شاخص: 0.05MB
wp_mailpoet_stats_notifications: داده: 0.00MB + شاخص: 0.00MB
wp_mailpoet_subscribers: داده: 0.02MB + شاخص: 0.05MB
wp_mailpoet_subscriber_custom_field: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_subscriber_ips: داده: 0.02MB + شاخص: 0.02MB
wp_mailpoet_subscriber_segment: داده: 0.02MB + شاخص: 0.03MB
wp_options: داده: 3.39MB + شاخص: 1.06MB
wp_postmeta: داده: 17.52MB + شاخص: 12.42MB
wp_posts: داده: 5.08MB + شاخص: 1.73MB
wp_termmeta: داده: 0.09MB + شاخص: 0.11MB
wp_terms: داده: 0.09MB + شاخص: 0.11MB
wp_term_relationships: داده: 1.06MB + شاخص: 0.16MB
wp_term_taxonomy: داده: 0.08MB + شاخص: 0.09MB
wp_usermeta: داده: 0.41MB + شاخص: 0.03MB
wp_users: داده: 0.02MB + شاخص: 0.05MB
wp_wc_download_log: داده: 0.02MB + شاخص: 0.03MB
wp_wc_webhooks: داده: 0.02MB + شاخص: 0.02MB
wp_woocommerce_ir: داده: 0.02MB + شاخص: 0.00MB
wp_wow_fmp: داده: 0.00MB + شاخص: 0.00MB
wp_yith_wcwl: داده: 0.02MB + شاخص: 0.02MB
wp_yith_wcwl_lists: داده: 0.02MB + شاخص: 0.05MB
wp_yoast_seo_links: داده: 0.08MB + شاخص: 0.02MB
wp_yoast_seo_meta: داده: 0.17MB + شاخص: 0.15MB
wp_zegersot_persian: داده: 0.02MB + شاخص: 0.00MB

### Post Type Counts ###

attachment: 1646
attribute_group: 9
gf_live_preview: 1
mailpoet_page: 1
nav_menu_item: 215
option-tree: 1
page: 21
post: 3
product: 758
product_variation: 1494
product-sliders: 1
question_answer: 6
revision: 117
scheduled-action: 3
shop_coupon: 1
shop_order: 22
wp_block: 1
yith_wc_qof_1: 1

### Security ###

Secure connection (HTTPS): ❌
					فروشگاه شما از HTTPS استفاده نمی کند. اطلاعات بیشتر درباره HTTPS و SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (29) ###

گرویتی فرم: توسط rocketgenius – 2.3.2
Disable Real MIME Check: توسط Sergey Biryukov – 1.0
Float Menu Lite: توسط Wow-Company – 3.0.1
Groups: توسط itthinx – 2.5.0
ویژگی های پیشرفته JC WooCommerce: توسط قالب وردپرس آنلاینر – 2.0.7 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
MailPoet 3 (New): توسط میل پوئت – 3.19.2
Max Mega Menu - Pro Addon: توسط Tom Hemsley – 1.7
مگامنو: توسط megamenu.com – 2.5.3.2
گرویتی فرم پارسی: توسط گرویتی فرم پارسی – 2.3.1.3
ووکامرس فارسی: توسط ووکامرس فارسی – 3.5.4
Print Flyers Lite: توسط Togethernet – 1.0 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
raychat: توسط raychat – 1.0.4
Recent Posts Widget With Thumbnails: توسط Martin Stehle – 6.5.0
Woocommerce Groups Discount: توسط eggemplo – 3.2.0 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
Woocommerce Groups by Sales - Light: توسط eggemplo – 1.2 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
WooCommerce Product Add-ons: توسط WooCommerce – 2.9.2 – 3.0.8 در دسترس است. – با نسخه ووکامرس فعال شده شما آزمایش نشده است
Woocommerce Products Per Page: توسط Jeroen Sormani – 1.2.6 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
ووکامرس: توسط اتوماتیک – 3.5.5
سئو Yoast: توسط Team Yoast – 9.6
WP-Persian: توسط Siavash Salemi – 3.2.4 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
YITH WooCommerce Added to Cart Popup Premium: توسط YITHEMES – 1.3.6 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
YITH WooCommerce Ajax Search Premium: توسط YITH – 1.6.5
YITH WooCommerce Compare Premium: توسط YITHEMES – 2.3.1 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
YITH WooCommerce Customize My Account Page: توسط YITH – 2.3.5 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
YITH WooCommerce Multi-step Checkout Premium: توسط YITHEMES – 1.6.5 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
YITH WooCommerce Questions and Answers Premium: توسط YITHEMES – 1.1.29 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
YITH WooCommerce Request A Quote Premium: توسط YITH – 2.1.2
YITH WooCommerce Waiting List Premium: توسط YITHEMES – 1.5.2 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
افزونه علاقه‌مندی ووکامرس: توسط YITH – 2.2.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
inslider_special_offers (inslider_special_offers)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
special_offers (special_offers)

### WC Pages ###

پایگاه فروشگاه: #4 - /shop/
سبد خرید: #5 - /cart/
تسویه حساب: #6 - /checkout/
حساب کاربری: #7 - /my-account/
شرایط و ضوابط: ❌ برگه تنظیم نشده است

### Theme ###

Name: AS-Newkala
Version: 2.0
Author URL: http://amir.eedea.ir
Child Theme: ✔
Parent Theme Name: Newkala
Parent Theme Version: 2.9.9
Parent Theme Author URL: http://newkalatheme.ir
WooCommerce Support: ✔

### Templates ###

Overrides: newkala/woocommerce/archive-product.php
newkala/woocommerce/cart/cart.php
newkala/woocommerce/cart/cross-sells.php
newkala/woocommerce/cart/mini-cart.php
newkala/woocommerce/checkout/review-order.php
newkala/woocommerce/checkout/thankyou.php
newkala/woocommerce/content-product.php
newkala/woocommerce/content-single-product.php
newkala/woocommerce/loop/loop-start.php
newkala/woocommerce/loop/no-products-found.php
newkala/woocommerce/loop/orderby.php
newkala/woocommerce/loop/pagination.php
newkala/woocommerce/loop/sale-flash.php
newkala/woocommerce/myaccount/form-login.php
newkala/woocommerce/myaccount/form-lost-password.php
newkala/woocommerce/product-searchform.php
newkala/woocommerce/single-product/add-to-cart/variable.php نسخه 3.4.1 بروز نیست. نسخه پایه 3.5.5 می باشد
newkala/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
newkala/woocommerce/single-product/meta.php
newkala/woocommerce/single-product/product-attributes.php
newkala/woocommerce/single-product/product-image.php
newkala/woocommerce/single-product/product-thumbnails.php
newkala/woocommerce/single-product/rating.php
newkala/woocommerce/single-product/related.php
newkala/woocommerce/single-product/tabs/additional-information.php
newkala/woocommerce/single-product/tabs/description.php
newkala/woocommerce/single-product/tabs/tabs.php
newkala/woocommerce/single-product/title.php
newkala/woocommerce/single-product/up-sells.php
newkala/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						آموزش چگونگی بروزرسانی قالب های قدیمی
`
</details>

**Comment by mikejolley** [comment] 2019-02-26 12:18
I was not able to replicate this one unfortunetely. I tried with unicode/persian characters in my attributes too in case it was that but they all worked and saved as they should.

I suspect this is a plugin conflict i.e a plugin (or something using the REST API) is updating products and either storing these attributes in the wrong format, or changing their values.

This one will be difficult to diagnose - ideally you'll need to find out what action you take on the site, or what event takes place, that causes the values of the variations to be removed. e.g. did you do an import? Was a product updated via admin? Does a plugin update stock or some other value in bulk?

Once you find out what triggers it, you can disable plugins to find the culprit. I'm afraid I cannot be of much help here because the plugins you're running (YITH/YITHEMES etc) are premium and I don't have access. A developer could inspect the source code if those plugins are required.

Let us know if you find anything. Since I'm unable to reproduce this issue I'm closing this issue.

**Closed by mikejolley** 2019-02-26 12:18 UTC
