### ISSUE TITLE
Unchecking the "Enable shipping calculator on the cart page" option doesn't work

### ISSUE THREAD

**Issue by apmwebdev** [woocommerce/woocommerce#26839] opened 2020-06-22 17:49 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I discovered this bug from a support chat, which is 21857029-hc.

In the shipping options, there is a checkbox labeled "Enable the shipping calculator on the cart page." When checked, it allows the customer to enter a shipping address, and the site will calculate shipping based on that address:
![image](https://user-images.githubusercontent.com/30607075/85318009-e80bed80-b484-11ea-84a3-633df9cf6eba.png)

When unchecked, though, it still shows the shipping calculation, it just prevents you from editing what the address is: 
![image](https://user-images.githubusercontent.com/30607075/85317842-b09d4100-b484-11ea-95b2-18b26f676009.png)

**Expected behavior**
When that setting is unchecked, the shipping calculation shouldn't show up on the cart page at all.

**Actual behavior**
The shipping calculation does show up.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Make sure the "Enable shipping calculator on the cart page" option is checked.
1. Add a product to the cart.
1. Go to the cart page. Note that the shipping calculation is present and the address can be changed.
1. Turn off that setting.
1. Go back to the cart page. Note that the shipping calculation is still present, with the only difference being that the address now cannot be changed.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
I used the troubleshooting mode of the Health Check and Troubleshooting plugin. Only WooCommerce was enabled for plugins, and Twenty Twenty was the theme.

```

### WordPress Environment ###

WordPress address (URL): http://fw2.local
Site address (URL): http://fw2.local
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.7.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Total Database Size: 25.77MB
Database Data Size: 17.90MB
Database Index Size: 7.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.25MB + Index: 0.27MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.13MB + Index: 0.36MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.44MB + Index: 0.77MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.11MB + Index: 0.30MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.02MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 2.38MB + Index: 2.86MB + Engine InnoDB
wp_posts: Data: 1.09MB + Index: 0.14MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wclsi_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wclsi_item_attribute_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wclsi_item_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wclsi_item_e_commerce: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wclsi_item_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wclsi_item_prices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wclsi_item_shops: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 183
aw_workflow: 13
bookable_person: 2
bookable_resource: 2
custom_css: 1
customize_changeset: 2
global_product_addon: 1
nav_menu_item: 7
page: 28
post: 2
product: 101
product_variation: 31
revision: 20
shop_coupon: 5
shop_order: 274
shop_order_refund: 3
shop_subscription: 43
wc_booking: 1
wc_membership_plan: 2
wc_user_membership: 2
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (37) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.3.2
Admin Only Cash Payment Gateway: by  –
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.1.2 – Installed version not tested with active version of WooCommerce 4.2.0
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.5 – Installed version not tested with active version of WooCommerce 4.2.0
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.2.0
AutomateWoo: by WooCommerce – 4.9.5
Bookings Helper: by WooCommerce – 1.0.3 – Installed version not tested with active version of WooCommerce 4.2.0
Code Snippets: by Code Snippets Pro – 2.14.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.5.0
User Switching: by John Blackbourn & contributors – 1.5.4
WooCommerce Blocks: by Automattic – 2.7.0
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.16 (update to version 1.1.17 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Additional Variation Images: by WooCommerce – 1.7.22 (update to version 1.7.23 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.6 (update to version 1.1.7 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.12 (update to version 3.1.13 is available)
WooCommerce Bookings: by WooCommerce – 1.15.20 (update to version 1.15.21 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce EU VAT Number: by WooCommerce – 2.3.19 (update to version 2.3.20 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Memberships: by SkyVerge – 1.17.1 (update to version 1.17.5 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Multilingual: by OnTheGoSystems – 4.7.2 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.34
WooCommerce Product Vendors: by WooCommerce – 2.1.33 (update to version 2.1.34 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Products Compare: by WooCommerce – 1.0.19 (update to version 1.0.20 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce FedEx Shipping: by WooCommerce – 3.4.26 (update to version 3.4.31 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce UPS Shipping: by WooCommerce – 3.2.25 (update to version 3.2.26 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.38 (update to version 4.4.44 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.1 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Subscriptions: by WooCommerce – 3.0.4 (update to version 3.0.5 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.27 (update to version 3.0.28 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0
WP Crontrol: by John Blackbourn & crontributors – 1.8.3
WP Mail Logging: by MailPoet – 1.9.6
WPML String Translation: by OnTheGoSystems – 3.0.2
WPML Translation Management: by OnTheGoSystems – 2.9.1

### Inactive Plugins (33) ###

Jetpack by WordPress.com: by Automattic – 8.5
Loco Translate: by Tim Whitlock – 2.3.4
Mailchimp for WooCommerce: by Mailchimp – 2.4.0 – Installed version not tested with active version of WooCommerce 4.2.0
MailChimp for WooCommerce Memberships: by SkyVerge – 1.0.11 (update to version 1.2.4 is available) – Installed version not tested with active version of WooCommerce 4.2.0
Product Filters for WooCommerce: by WooCommerce – 1.2.0 (update to version 1.2.1 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.36 (update to version 4.1.37 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Advanced Notifications: by WooCommerce – 1.2.23 (update to version 1.2.25 is available) – Installed version not tested with active version of WooCommerce 4.2.0
Woocommerce Bookings Dropdown: by Webby Scots – 1.2.1 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Box Office: by WooCommerce – 1.1.16 (update to version 1.1.25 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Cart Add-Ons: by WooCommerce – 1.5.27 (update to version 1.5.29 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Chained Products: by StoreApps – 2.9.6 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.30 (update to version 1.5.34 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Composite Products: by SomewhereWarm – 6.1.4 (update to version 7.0.3 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.0 (update to version 1.8.1 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Deposits: by WooCommerce – 1.4.18 (update to version 1.5.1 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.15 (update to version 3.1.19 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Force Sells: by WooCommerce – 1.1.21 (update to version 1.1.24 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce LightSpeed POS: by WooCommerce – 1.7.2 (update to version 1.7.8 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.17 (update to version 2.4.18 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Mix and Match: by Kathy Darling – 1.8.0 (update to version 1.9.9 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce One Page Checkout: by Automattic – 1.7.3 (update to version 1.7.6 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Points and Rewards: by WooCommerce – 1.6.28 (update to version 1.6.33 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Pre-Orders: by WooCommerce – 1.5.22 (update to version 1.5.26 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Product Add-ons: by WooCommerce – 3.0.33 (update to version 3.0.34 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Product Bundles: by SomewhereWarm – 6.2.1 (update to version 6.2.5 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Services: by Automattic – 1.23.0 (update to version 1.23.2 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.7 (update to version 2.3.10 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Slack: by WooCommerce – 1.1.16 (update to version 1.2.4 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Smart Coupons: by StoreApps – 4.7.6
WooCommerce Warranty Requests: by WooCommerce – 1.9.11 (update to version 1.9.15 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce WishLists: by Lucas Stark – 2.1.15 (update to version 2.2.0 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Xero Integration: by WooCommerce – 1.7.24 (update to version 1.7.31 is available) – Installed version not tested with active version of WooCommerce 4.2.0
WP-DBManager: by Lester 'GaMerZ' Chan – 2.80.3

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 2
M&M + Subs + Membership Plan:: Members: 1Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No
Sample membership plan:: Members: 1Access method: Product(s) purchaseAccess length: Unlimited Subscription: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://fw2.local
Subscription Statuses: wc-active: 20
wc-expired: 4
wc-pending: 2
wc-on-hold: 8
wc-cancelled: 9

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 18
wc-cancelled: 9
wc-expired: 4
wc-on-hold: 7


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders


### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### Store Catalog PDF Download ###

Template Overrides: 

### Subscriptions Gifting ###

Gifted Subscriptions Count: 1

### Action Scheduler ###

Complete: 288
Oldest: 2020-05-22 23:52:52 +0000
Newest: 2020-06-22 16:49:06 +0000

Pending: 22
Oldest: 2020-06-22 19:11:42 +0000
Newest: 2020-11-25 23:47:28 +0000

```
</details>

**Comment by claudiosanches** [comment] 2020-07-02 19:47
Related to #26876

**Comment by apmwebdev** [comment] 2020-07-03 19:23
Another thread about this here: https://wordpress.org/support/topic/hide-shipping-calculator/

**Comment by fluxpixel** [comment] 2020-07-12 03:16
Im having the same exact problem. any fix for this? Will 4.3 version solve the problem? Im running woocommerce 4.2.2

**Comment by connde** [comment] 2020-10-12 17:29
Hi, any idea of when this will be fixed? Can someone provide a workaround in the meanwhile?

**Comment by vinodglobalstep** [comment] 2021-09-09 16:20
Hi @apmwebdev ,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using WooCommerce 5.6 version.

Here are the screenshots of the results:
![4_1](https://user-images.githubusercontent.com/46351294/132724064-c9d0a1cc-bd7c-47d3-b9da-ab67b2d89aa7.png)

![4_2](https://user-images.githubusercontent.com/46351294/132724081-9438484f-9404-4507-ae44-fb40330a51ef.png)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by ArtyshukPavlo** [comment] 2022-08-20 17:04
Any update here? Bug still present(

**Comment by MrHappyAsh** [comment] 2022-08-26 10:41
Also affected by this bug.

**Comment by joaodante** [comment] 2022-11-15 23:45
5699005-zen

**Comment by vaclavgreif** [comment] 2023-05-23 06:09
Didn't work for me either, I resolved it with the following simple fix:

```
add_action('template_redirect', function() {
	if (is_cart()) {
		add_filter('woocommerce_cart_ready_to_calc_shipping', '__return_false');
	}
});
```

**Comment by sigrundis** [comment] 2023-06-15 11:13
+1 (also affected by this bug). 

I see this is an old thread but with resent activity which might indicate that the bug got introduced again?

**Comment by mikejolley** [comment] 2023-10-25 09:49
Hi everyone,

Thank you for taking the time to report this issue. I think there may be some confusion over what this setting actually does reading the comments here. To clarify how things should work (using the 2 checkboxes in settings):

`Enable the shipping calculator on the cart page` will remove the calculator itself (that is the address form and the "change address" link. It does not remove shipping costs.

`Hide shipping costs until an address is entered` will remove the radio buttons/shipping cost, **unless** the customer already has an address in their session. That could be a returning logged in customer, someone who has already visited checkout, or according to the "Default customer location" setting under general settings.

To hide shipping you'd want to set "Default customer location" to "no location by default", and check the `Hide shipping costs until an address is entered` option. 

From what I can see these settings are working as intended. Changing this behaviour in the shortcode checkout doesn’t fit our current priorities, as our team is currently focused on the Cart and Checkout experience powered by blocks. We'll review this behavior in the blocks experience.

Thanks

**Closed by mikejolley** 2023-10-25 09:49 UTC
Labels: type: bug, priority: low, focus: cart, plugin: woocommerce, team: Rubik
