### ISSUE TITLE
Sell to specific countries api endpoint

### ISSUE THREAD

**Issue by Jonofat** [woocommerce/woocommerce#29754] opened 2021-04-24 14:08 UTC
I have been hunting for this in the API docs but cannot find it. I have selected 3 countries for the "sell to specific countries" field. In a normal WooCommerce setup that would then show in a dropdown on the checkout page for your billing country. Since I am using a frontend framework I can only use the REST API. Does an endpoint for this exist?

**Comment by zhongruige** [comment] 2021-04-28 17:43
Hi @Jonofat,

>  In a normal WooCommerce setup that would then show in a dropdown on the checkout page for your billing country. Since I am using a frontend framework I can only use the REST API. Does an endpoint for this exist?

Great question. Just want to confirm, this is the field you're referring to correct?

<img width="876" alt="Screen Shot 2021-04-28 at 11 36 24 AM" src="https://user-images.githubusercontent.com/71906536/116448162-087ba580-a816-11eb-8f22-39c1e19cefcd.png">

Which then only allows these countries as countries that can be selected as billing countries:

<img width="526" alt="Screen Shot 2021-04-28 at 11 41 42 AM" src="https://user-images.githubusercontent.com/71906536/116448832-c69f2f00-a816-11eb-956c-1be3c0a535b6.png">

If so, yes, we do have an API endpoint that allows updating this. It can be found under the [Settings options](https://woocommerce.github.io/woocommerce-rest-api-docs/#setting-options) section in the WooCommerce API documentation, specifically, [Update a setting option](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-setting-option). In practice, the request will look like this:

`PUT {{base_url}}/wp-json/wc/v3/settings/general/woocommerce_specific_allowed_countries`

With a request body listing the country codes of the countries you which to specify in the `value` field:

```
{
    "value": [
        "FR",
        "GB",
        "US"
    ]
}
```

For example, I used this request to generate the UI changes in the screenshot above. You can make a `GET` request to the following to see the list of allowed country codes:

```
GET {{base_url}}/wp-json/wc/v3/settings/general/woocommerce_specific_allowed_countries
```

Let me know if this helps! Thanks!

**Comment by Jonofat** [comment] 2021-04-28 17:51
Yes, that is the field I am referring to. I don't want to update it using the API, I just want to send a GET request to get the countries so that I can display them in a dropdown on the frontend for a user when they checkout. And because it is just a GET request, I wouldn't want to have to send login credentials or tokens etc. along with the request just to fetch this data. And because it needs to be in a dropdown on the frontend for the user, Ideally the value of the select would be FR, GB, US etc. but the label would be in a more human readable format like "United Kingdom" etc. Not sure if what I am asking is possible?

**Comment by zhongruige** [comment] 2021-04-30 22:38
Thank you for the reply!

Regarding the permissions error, this could be happening due to the permissions assigned to the API key:

<img width="665" alt="Screen Shot 2021-04-28 at 4 02 16 PM" src="https://user-images.githubusercontent.com/71906536/116478388-37584280-a83b-11eb-9b8a-ff823192eb49.png">

It sounds likely this may be happening just in this workflow, that is, if you're trying to access the list without authentication (which the API requires). I just want to make sure that is the case and there aren't other issues we may be seeing here. Let me know if so.

Ultimately it sounds like the ideal would be the same type of endpoint but without authentication. For this we might need to look at enhancing the API to add endpoints that would allow pulling this data without authentication, or alternatively, there could be a custom code solution. In that case, the best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel.

Thanks!

**Comment by AashikP** [comment] 2021-07-31 03:53
Hello @Jonofat ,

As @zhongruige confirmed, you'll see that error if you can't authenticate via API.

I created a test key with just `Read` permission as shown below:

![https://d.pr/i/EDtldv+](https://d.pr/i/EDtldv+)

And then could retrieve the countries list successfully via:  
`/wp-json/wc/v3/settings/general/woocommerce_specific_allowed_countries`

This is my site settings:

![https://d.pr/i/nEzCVX+](https://d.pr/i/nEzCVX+)

Here's how it looks in [Postman tool](postman.com/):

![https://d.pr/i/O4XCs5+](https://d.pr/i/O4XCs5+)

---

I'm closing this issue as we can't replicate it, but feel free to add your comments if we missed something here so that we can further investigate.

**Closed** 2021-07-31 03:53 UTC
Labels: category: can't reproduce, needs feedback
