### ISSUE TITLE
WooCommerce 3.5.3 solve the orders not listed in admin but breaks the Blocks Editor

### ISSUE THREAD

**Issue by fernandotellado** [woocommerce/woocommerce#22279] opened 2018-12-20 17:03 UTC
The new released version 3.5.3 claim to solve the orders issue but breaks the block editor too :(

After the update you'll get this ugly error (in Spanish) if you try to edit or add a new post (blocks editor, no problem with classic editor)

<img src="https://i.imgur.com/meEbxOx.png" />

The error copied from the button is like this one (in a test site, but same error in every site I've updated WooCommerce to 3.5.3:

`TypeError: Cannot read property 'select' of undefined
    at https://testu.sgedu.site/wp-includes/js/dist/editor.min.js:55:271508
    at n.value (https://testu.sgedu.site/wp-includes/js/dist/data.min.js:1:14919)
    at new n (https://testu.sgedu.site/wp-includes/js/dist/data.min.js:1:14614)
    at zf (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:69:258)
    at Mf (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:87:4)
    at ph (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:98:474)
    at eg (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:125:307)
    at fg (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:126:168)
    at wc (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:138:237)
    at fa (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:137:115)`

[The function posted this morning to solve the WordPress 5.0.2 issue](https://core.trac.wordpress.org/ticket/45719) with the orders admin list is still working and doesn't break the blocks editor, but the WooCommerce 3.5.3 update solves the orders not listed in admin, but cause this bug

WooCommerce System Status:

`
### WordPress Environment ###

Home URL: https://testu.sgedu.site
Site URL: https://testu.sgedu.site
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.25 - Recomendamos usar la versión 7.2 o superior de PHP para un mayor rendimiento y seguridad. Cómo actualizar tu versión de PHP
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wpnd_
MaxMind GeoIP Database: ✔
Tamaño total de la base de datos: 3.99MB
Tamaño de los datos de la base de datos: 2.95MB
Tamaño del índice de la base de datos: 1.04MB
wpnd_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB
wpnd_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB
wpnd_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB
wpnd_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.05MB
wpnd_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB
wpnd_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB
wpnd_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB
wpnd_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB
wpnd_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB
wpnd_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB
wpnd_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB
wpnd_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB
wpnd_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB
wpnd_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB
wpnd_commentmeta: Datos: 0.02MB + Índice: 0.03MB
wpnd_comments: Datos: 0.02MB + Índice: 0.09MB
wpnd_links: Datos: 0.02MB + Índice: 0.02MB
wpnd_options: Datos: 2.03MB + Índice: 0.05MB
wpnd_postmeta: Datos: 0.22MB + Índice: 0.17MB
wpnd_posts: Datos: 0.13MB + Índice: 0.06MB
wpnd_termmeta: Datos: 0.02MB + Índice: 0.03MB
wpnd_terms: Datos: 0.02MB + Índice: 0.03MB
wpnd_term_relationships: Datos: 0.02MB + Índice: 0.02MB
wpnd_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB
wpnd_usermeta: Datos: 0.05MB + Índice: 0.03MB
wpnd_users: Datos: 0.02MB + Índice: 0.05MB
wpnd_wc_download_log: Datos: 0.02MB + Índice: 0.03MB
wpnd_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB
wpnd_yoast_seo_links: Datos: 0.02MB + Índice: 0.02MB
wpnd_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 23
custom_css: 2
elementor_library: 1
jetpack_migration: 2
nav_menu_item: 27
page: 11
post: 12
product: 22
product_variation: 4
revision: 35
shop_coupon: 3
shop_order: 1
wpforms: 1
ywcm_message: 3
ywdpd_discount: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

SG Optimizer: por SiteGround – 5.0.10
WooCommerce: por Automattic – 3.5.3
Yoast SEO: por Equipo Yoast – 9.3
YITH Composite Products for WooCommerce Premium: por YITH – 1.1.10

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith-composite (yith-composite)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: #96 - /
Carrito: #78 - /cart/
Finalizar compra: #7 - /checkout/
Mi cuenta: #8 - /my-account/
Términos y condiciones: #2048 - /sobre-mi/

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by rodrigoprimo** [comment] 2018-12-20 18:01
@fernandotellado, as I requested previously (https://github.com/woocommerce/woocommerce/issues/22271#issuecomment-449064071), could you please include everything that is requested in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md)? This should gives us critical information to be able to reproduce and understand the problem that you are reporting (information about your store to understand if this could be caused due to a conflict with another plugin, clear steps to reproduce the problem to make sure that we are trying to reproduce it the right way, and so on).

**Comment by claudiosanches** [comment] 2018-12-20 18:17
I haven't changed anything on the editor, the only thing that we fixed is it: 

https://github.com/woocommerce/woocommerce/pull/22273/commits/ff74ecec864c6d35f466c75f609c3e43475d375e

This is applied only in the orders screen, not on any editor.

**Comment by claudiosanches** [comment] 2018-12-20 18:30
@fernandotellado please we need steps to reproduce, can you please fill an issue with that template: https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md
We just need those steps.

**Comment by rodrigoprimo** [comment] 2018-12-20 18:33
@fernandotellado, besides the steps to reproduce, as @claudiosanches mentioned, the system status report (which is requested in the bug report template) could help as well.

cc @franckadil in case you could provide the same information as you mentioned that this problem is happening to you as well.

Thanks.

**Comment by fernandotellado** [comment] 2018-12-20 18:36
I've just pasted the Woo System status.

The steps are these one (that I did reporte above):

1. Update to WordPress 5.0.2: The admin orders list don't show the orders
2. Update to WooCommerce 3.5.3: The admin orders list show the orders but… 
3. If I try to edit a post (normal post) the editor showes a blank page with an error message (showed above)
4. If I try to add a new post the editor shows the same error

Is a clean WordPress install, for testing purposes, with anything more than WordPress and WooCommerce. It happens in every site (11 at this moment) where I've updated to WP 5.0.2 and Woo 3.5.3.

**Comment by rodrigoprimo** [comment] 2018-12-20 18:38
> I've just pasted the Woo System status.

I deleted my previous comment right after I posted it. I didn't realize that you had edited the issue description to include the system status report. Sorry for the confusion.

**Comment by rodrigoprimo** [comment] 2018-12-20 18:54
I'm sorry but I'm still not able to reproduce this error.

I found the thread below where a few users are reporting the same error that you are getting but the stack track is slightly different: https://wordpress.org/support/topic/gutenberg-error-when-creating-or-editing-posts/

You probably already tried this, but just to confirm do you still get this error if you disable WooCommerce?

**Comment by claudiosanches** [comment] 2018-12-20 18:57
> After I've installed two more plugins, but the result is the same with or without them, and in other installs with another plugins/theme combination.

What plugins?

Because I'm testing a clean install and also I updated one, and no luck to reproduce it...
I also tested changing from en_US to es_ES, sometimes problems can come from translations, but don't seems to be the case too.

**Comment by fernandotellado** [comment] 2018-12-20 19:01
@claudiosanches The plugins are listed in the system status but it's irrelevant, the issue was prior the install 
@rodrigoprimo I'll check the support thread

**Comment by claudiosanches** [comment] 2018-12-20 19:03
@fernandotellado let's try admin access, you can send me on https://claudiosanches.com/contact/

**Comment by dougaitken** [comment] 2018-12-20 19:15
> I can reproduce the error on 2 sites.

@franckadil can you replicate this with only WooCommerce active?

**Comment by fernandotellado** [comment] 2018-12-20 19:37
@claudiosanches I need your email, the contact would be opposite 😄 

https://tellado.es/ (at the end of the page)

**Comment by claudiosanches** [comment] 2018-12-20 19:39
@fernandotellado there is a contact form in the page I sent you.

**Comment by fernandotellado** [comment] 2018-12-20 19:40
Done

**Comment by claudiosanches** [comment] 2018-12-20 20:33
Just an update:

Fernando gave me access to testu.sgedu.site, I tested and works fine, testing on Firefox and Chrome, also other members of WooCommerce team have tested in they own installations, and no one have been able to reproduce this issue.

I'm thinking it might be browser cache, but still not related to WooCommerce.

For now I'm closing it, but I'm able to test for anyone that can present consistent steps to reproduce this issue only with WooCommerce 3.5.3 and WordPress 5.0.2.

**Closed by claudiosanches** 2018-12-20 20:33 UTC
Labels: status: needs feedback

**Comment by franckadil** [comment] 2018-12-21 01:02
Hello, I was able to reproduce this error with WooCommerce activated only, So I can confirm it was linked to WooCommerce. If you've released a newer patch I can test again and will share with you our logs.

**Comment by dougaitken** [comment] 2018-12-21 12:40
Hi @franckadil 

Can you give us some details of the sites you got this error on? We don't see anything posted in this thread. 

If you have everything updated and are still seeing the bug. Please open a new issue with full details. 

Thanks

**Comment by franckadil** [comment] 2018-12-21 13:01
@dougaitken Hi,

Here is the list of the errors we have witnessed:

We had 2 sites including our site with some Javascript slow errors with pages taking to long to long the failing.

And on 3 other sites we had the following error:


`[21-Dec-2018 11:42:24 UTC] WordPress database error Identifier name 'xxxxxx_wp_xxxxxxxxx_woocommerce_downloadable_product_permissions' is too long for query SHOW COLUMNS FROM xxxxxxx_wp_xxxxxxx_woocommerce_downloadable_product_permissions WHERE Field = 'permission_id' made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::create_tables
`
`CREATE TABLE xxxxxx_wp_xxxxxx_woocommerce_downloadable_product_permissions (
  permission_id BIGINT UNSIGNED NOT NULL auto_increment,
  download_id varchar(36) NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  order_key varchar(200) NOT NULL,
  user_email varchar(200) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  downloads_remaining varchar(9) NULL,
  access_granted datetime NOT NULL default '0000-00-00 00:00:00',
  access_expires datetime NULL default null,
  download_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY  (permission_id),
  KEY download_order_key_product (product_id,order_id,order_key(16),download_id),
  KEY download_order_product (download_id,order_id,product_id),
  KEY order_id (order_id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta`


After some investigation we found that all the sites that broke on our part shared a common thing: The subscription extension was activated to receive updates, but users had to manually go in their

1.  WooCommerce > Extensions
2.  then WooCommerce.com Subscriptions tab
3.  and click on the update

The latest version of WooCommerce + Plus Subscriptions + WordPress fixes all the issues we have seen, from the filters not displaying products or subscriptions to the editor being broken to Slow Javascript errors ad finally the database issue shared above.

I have been testing since 3 hours now and I have no issue so far.
