### ISSUE TITLE
My Account Addresses label not displayed when using Arabic language

### ISSUE THREAD

**Issue by mohamedahmedabdelfattah** [woocommerce/woocommerce#27428] opened 2020-08-20 17:03 UTC
**Prerequisites**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The "Addresses" tab label in "My Account" page is not displayed when I use the Arabic language while it should be already translated and was working before.

It`s placeholder "the empty highlighted space in the screenshot" still works and navigates to the correct page as expected.

**Expected behavior**
When using Arabic, the Addresses tab in the My Account page should display it`s Arabic counterpart "العناوين" or even the non translated English label "Addresses"

**Actual behavior**
The Addresses tab in the My Account page is not showing any label while the place holder and the link itself are present and work as expected.

**Steps to reproduce the bug:**
1. Switch the website to 'Arabic' Language from WP general settings
2. Go to 'My Account' page in the website
3. See the error as described

**Screenshots**
![image](https://user-images.githubusercontent.com/2484844/90825647-7f80a600-e339-11ea-9d89-28140b8070e0.png)
![image](https://user-images.githubusercontent.com/2484844/90825663-84ddf080-e339-11ea-8ec8-7f2e7efc96b8.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://test.local
Site address (URL): http://test.local
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ar
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 2.24MB
Database Data Size: 0.87MB
Database Index Size: 1.37MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 8
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.4.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2020-08-20 16:46:51 +0000
Newest: 2020-08-20 16:46:51 +0000

`
```
</details>

**Comment by mohamedahmedabdelfattah** [comment] 2020-08-20 20:58
For testing purposes, I used TranslatePress plugin to insert the Arabic translation for the string and it worked only while using the plugin.

I also tried debugging using the developer console and playing around with the below codes to no avail.

1- code responsible for displaying the label of the menu: wp-content\plugins\woocommerce\templates\myaccount\navigation.php

    <nav class="woocommerce-MyAccount-navigation">
    <ul>
        <?php foreach ( wc_get_account_menu_items() as $endpoint => $label ) : ?>
            <li class="<?php echo wc_get_account_menu_item_classes( $endpoint ); ?>">
                <a href="<?php echo esc_url( wc_get_account_endpoint_url( $endpoint ) ); ?>"><?php echo esc_html( $label ); ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>

<?php do_action( 'woocommerce_after_account_navigation' ); ?>

2- code for the item displayed which if I changed "Addresses" to something else it appears: wp-content\plugins\woocommerce\includes\wc-account-functions.php

        $items = array(
        'dashboard'       => __( 'Dashboard', 'woocommerce' ),
        'orders'          => __( 'Orders', 'woocommerce' ),
        'downloads'       => __( 'Downloads', 'woocommerce' ),
        'edit-address'    => _n( 'Addresses', 'Address', (int) wc_shipping_enabled(), 'woocommerce' ),
        'payment-methods' => __( 'Payment methods', 'woocommerce' ),
        'edit-account'    => __( 'Account details', 'woocommerce' ),
        'customer-logout' => __( 'Logout', 'woocommerce' ),
    );

3- translated strings: wp-content\languages\plugins\woocommerce-ar.po

	#: includes/class-wc-query.php:126
	#: includes/admin/settings/class-wc-settings-advanced.php:284
	#: includes/wc-account-functions.php:102
	msgid "Addresses"
	msgid_plural "Address"
	msgstr[0] "العناوين"
	msgstr[1] ""
	msgstr[2] ""
	msgstr[3] ""
	msgstr[4] ""
	msgstr[5] ""

**Comment by tammullen** [comment] 2020-08-30 22:04
Hi @mohamedahmedabdelfattah 

Thank you for raising this issue and apologies for the delay in replying. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. Translation is managed by teams over at translate.wordpress.org
​
The issue you are having seems to be caused by the Arabic language translation file so would need to be fixed on https://translate.wordpress.org/projects/wp-plugins/woocommerce/

> `msgstr[0] "العناوين"`
> `msgstr[1] ""`

I believe this is happening because msgstr[1] is empty and the plural settings in `woocommerce-ar.po` don't expect it to be empty

for example if you compare it to a word like `category` in `woocommerce-ar.po`
`msgid "Category:"`
`msgid_plural "Categories:"`
`msgstr[0] "التصنيف:"`
`msgstr[1] "التصنيف:"`
`msgstr[2] "التصنيفات:"`
`msgstr[3] "التصنيفات:"`
`msgstr[4] "التصنيفات:"`
`msgstr[5] "التصنيفات:"`

Please contact the translation team https://translate.wordpress.org/projects/wp-plugins/woocommerce/ for further help.

**Closed by tammullen** 2020-08-30 22:04 UTC
Labels: i18n
