### ISSUE TITLE
generated order key too long for posts table password field

### ISSUE THREAD

**Issue by BabelhalSupport** [woocommerce/woocommerce#22619] opened 2019-01-31 10:38 UTC
**No order can be placed**
Using WordPress 5.0.3 and WooCommerce 3.5.4 (both the newest at 2019-01-31) no order can be placed. This bug is caused by 2-3 separate bugs both in WP and WC. The root of the problem is that the `wc_generate_order_key` function generates a string of 22 bytes length, which then is used as a post password. The post password field can only hold 20 characters. That would be not a big deal, the database could easily strip 2 chars, but WordPress tries to be smart (actually it is not) and when running the `$wpdb->insert` function it sees that the data won't fit, and smartly returns false instead of a meaningful error message. Here comes another bug of WooCommerce. In the file _.../wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php_ the `create` function does no error handling at all. Also the inherited class in file _class-wc-order-data-store-cpt.php_ does not do anything about the error. So for WooCommerce the creation of the order silently fails, and it **continues** with saving the order items to order id zero (0). And finally when WooCommerce tries to read again the saved order (id = 0), then is realizes, that there is no order with id 0 in the database, and throws up some non-informative error message.

**Steps to reproduce**
1. Install WordPress and WooCommerce (versions mentioned above)
2. Try to place an order, and see it fail

**Expected behavior**
Placing orders should work.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.
- [x] I spent hours tracking down the bug.
- [x] Confirmed the bug by changing the posts table post_password field size to 22 (after this placing orders works again)

**WordPress Environment**
<details>

### WordPress Environment ###

Home URL: https://hotel.bock.hu
Site URL: https://hotel.bock.hu
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: ✔
WP Memory Limit: 64 MB
WP Debug Mode: –
WP Cron: ✔
Language: hu_HU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.14-1+0~20190113100742.14+stretch~1.gbpd83c69
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB-0+deb9u1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_2_
MaxMind GeoIP Database: ✔
Teljes adatbázis mérete: 43.69MB
Adatbázis adatok mérete: 40.87MB
Adatbázis index mérete: 2.82MB
wp_2_woocommerce_sessions: Adat: 0.05MB + Index: 0.02MB
wp_2_woocommerce_api_keys: Adat: 0.02MB + Index: 0.03MB
wp_2_woocommerce_attribute_taxonomies: Adat: 0.02MB + Index: 0.02MB
wp_2_woocommerce_downloadable_product_permissions: Adat: 0.02MB + Index: 0.05MB
wp_2_woocommerce_order_items: Adat: 0.02MB + Index: 0.02MB
wp_2_woocommerce_order_itemmeta: Adat: 0.14MB + Index: 0.17MB
wp_2_woocommerce_tax_rates: Adat: 0.02MB + Index: 0.06MB
wp_2_woocommerce_tax_rate_locations: Adat: 0.02MB + Index: 0.03MB
wp_2_woocommerce_shipping_zones: Adat: 0.02MB + Index: 0.00MB
wp_2_woocommerce_shipping_zone_locations: Adat: 0.02MB + Index: 0.03MB
wp_2_woocommerce_shipping_zone_methods: Adat: 0.02MB + Index: 0.00MB
wp_2_woocommerce_payment_tokens: Adat: 0.02MB + Index: 0.02MB
wp_2_woocommerce_payment_tokenmeta: Adat: 0.02MB + Index: 0.03MB
wp_2_woocommerce_log: Adat: 0.02MB + Index: 0.02MB
wp_2_cformsdata: Adat: 8.20MB + Index: 1.22MB
wp_2_cformssubmissions: Adat: 0.56MB + Index: 0.11MB
wp_2_commentmeta: Adat: 0.00MB + Index: 0.01MB
wp_2_comments: Adat: 0.02MB + Index: 0.01MB
wp_2_links: Adat: 0.00MB + Index: 0.00MB
wp_2_mappress_maps: Adat: 0.00MB + Index: 0.00MB
wp_2_mappress_posts: Adat: 0.00MB + Index: 0.00MB
wp_2_ngg_album: Adat: 0.00MB + Index: 0.00MB
wp_2_ngg_gallery: Adat: 0.01MB + Index: 0.00MB
wp_2_ngg_pictures: Adat: 0.13MB + Index: 0.01MB
wp_2_options: Adat: 1.31MB + Index: 0.05MB
wp_2_postmeta: Adat: 0.57MB + Index: 0.19MB
wp_2_posts: Adat: 28.70MB + Index: 0.46MB
wp_2_revslider_css: Adat: 0.13MB + Index: 0.02MB
wp_2_revslider_layer_animations: Adat: 0.02MB + Index: 0.02MB
wp_2_revslider_navigations: Adat: 0.02MB + Index: 0.00MB
wp_2_revslider_settings: Adat: 0.00MB + Index: 0.00MB
wp_2_revslider_sliders: Adat: 0.02MB + Index: 0.00MB
wp_2_revslider_slides: Adat: 0.41MB + Index: 0.00MB
wp_2_revslider_static_slides: Adat: 0.02MB + Index: 0.02MB
wp_2_termmeta: Adat: 0.02MB + Index: 0.03MB
wp_2_terms: Adat: 0.00MB + Index: 0.01MB
wp_2_term_relationships: Adat: 0.00MB + Index: 0.01MB
wp_2_term_taxonomy: Adat: 0.00MB + Index: 0.00MB
wp_2_wc_download_log: Adat: 0.02MB + Index: 0.03MB
wp_2_wc_webhooks: Adat: 0.02MB + Index: 0.02MB
wp_2_zaki_like_dislike_comments: Adat: 0.00MB + Index: 0.00MB
wp_blogs: Adat: 0.00MB + Index: 0.00MB
wp_blog_versions: Adat: 0.00MB + Index: 0.00MB
wp_registration_log: Adat: 0.00MB + Index: 0.00MB
wp_signups: Adat: 0.00MB + Index: 0.01MB
wp_site: Adat: 0.00MB + Index: 0.01MB
wp_sitemeta: Adat: 0.20MB + Index: 0.03MB
wp_usermeta: Adat: 0.06MB + Index: 0.04MB
wp_users: Adat: 0.00MB + Index: 0.01MB

### Post Type Counts ###

akciok: 40
attachment: 493
display_type: 7
gift_card: 41
nav_menu_item: 30
ngg_gallery: 1
ngg_pictures: 26
page: 42
post: 153
product: 12
programok: 82
revision: 4675
shop_order: 3
tribe_wooticket: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Akismet Anti-Spam: írta Automattic – 4.1
All In One SEO Pack: írta Michael Torbert – 2.10.1
Bock akciók: írta Bábelhal Webstudio Kft. – 2011.10.4
Bock Booking modul: írta Bábelhal Webstudio Kft. – 2011.2.16
Bock programok: írta Bábelhal Webstudio Kft. – 2016.11.28
Bock borok: írta Bábelhal Webstudio Kft. – 2016.11.28
Black Bar: írta Paul Ryley – 2.1.3
cforms2: írta Oliver Seidel
Bastian Germann – 14.14

Event Tickets Plus: írta Modern Tribe
Inc. – 4.8.1

Event Tickets: írta Modern Tribe
Inc. – 4.8.1

Loco Fordító: írta Tim Whitlock – 2.2.0
MapPress Maps for WordPress: írta Chris Richardson – 2.50.10
qTranslate(-x) Separate Comments: írta Nikola Nikolov – 1.2.3
qTranslate-X: írta qTranslate Team – 3.4.6.8
Redirects: írta Loud Dog – 1.2.1
Slider Revolution: írta ThemePunch – 5.4.8
the iSoft plugin: írta iSoft Bt. – 2013.3.6
TinyMCE Advanced: írta Andrew Ozz – 5.0.0
WooCommerce & qTranslate-X: írta qTranslate Team – 1.3 – Nincsen tesztelve a Woocommerce aktív verziójával
WooCommerce: írta Automattic – 3.5.4
YITH WooCommerce Gift Cards Premium: írta YITH – 2.0.5
NextGEN Gallery: írta Imagely – 3.1.6
WP Multisite Post: írta Leon Doornkamp – 1.1
Weboldal funkciók: írta Bábelhal Webstudio Kft. – 2016.11.28
Google Authenticator: írta Henrik Schack – 0.48
All in One SEO Pack & qTranslate-X: írta qTranslate Team – 1.0
Anti-spam: írta webvitaly – 5.3
EU Cookie Law: írta Alex Moss
Marco Milesi
Peadig
Shane Jones – 3.0.5

Klasszikus szerkesztő: írta WordPress közreműködők – 1.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Webshop főoldal: ❌ Az oldal nincs beállítva
Kosár: ❌ Az oldal nincs beállítva
Pénztár: #6312 - /penztar
A fiókom: ❌ Az oldal nincs beállítva
Általános Szerződési Feltételek: #6343 - /altalanos-szerzodesi-feltetelek

### Theme ###

Name: Bock Hotel
Version: 1.0
Author URL: 
Child Theme: ❌ – Amennyiben a WooCommerce-t egy olyan szülősablonban módosítunk
amelyet nem saját magunk készítettünk
akkor javasoljuk a származtatott sablon használatát. Hogyan készítsünk származtatott sablonokat

WooCommerce Support: ✔

### Templates ###

Overrides: bock/woocommerce/cart/mini-cart.php
bock/woocommerce/checkout/form-checkout.php
bock/woocommerce/checkout/review-order.php
bock/woocommerce/checkout/terms.php
bock/woocommerce/checkout/thankyou.php
bock/woocommerce/content-product.php
bock/woocommerce/content-single-product.php
bock/woocommerce/content-widget-product.php
bock/woocommerce/emails/customer-completed-order.php
bock/woocommerce/emails/customer-on-hold-order.php
bock/woocommerce/emails/email-order-details.php
bock/woocommerce/global/wrapper-end.php
bock/woocommerce/global/wrapper-start.php
bock/woocommerce/loop/loop-end.php
bock/woocommerce/loop/loop-start.php
bock/woocommerce/loop/price.php
bock/woocommerce/order/order-details-customer.php
bock/woocommerce/order/order-details.php
bock/woocommerce/single-product/meta.php
bock/woocommerce/single-product/price.php
bock/woocommerce/single-product/short-description.php
bock/woocommerce/single-product.php

</details>

**Comment by rrennick** [comment] 2019-01-31 12:43
Duplicate of #22603. See my explanation here - https://github.com/woocommerce/woocommerce/issues/22603#issuecomment-459054731

**Closed by rrennick** 2019-01-31 12:43 UTC

**Comment by BabelhalSupport** [comment] 2019-01-31 12:58
Only partially.
When you carefully read my description, you see the part:

> Here comes another bug of WooCommerce. In the file _.../wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php_ the `create` function does no error handling at all. Also the inherited class in file _class-wc-order-data-store-cpt.php_ does not do anything about the error.

This bug is independent of the other one.
