### ISSUE TITLE
Pull Request 27416 fixed in front-end but not in backend

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#27981] opened 2020-10-15 20:08 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
This pull request has correctly fixed the sorting issue of countries in the frontend (cart/checkout) but if you check the same list in the backend, it's not fixed.

**Expected behavior**
Backend sorting list of countries should be fixed like in frontend.

**Actual behavior**
Sorting list is not alphabetical.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
WooCommerce Settings > General > Ship in all countries except...

**Screenshots**
https://sgevcen.tinytake.com/tt/NDczMTA2Ml8xNDk3MDU1Ng

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-10-16 12:39
Hi @gevcen,

Thanks for catching and reporting it! I can indeed confirm that https://github.com/woocommerce/woocommerce/pull/27416 fixed the issue at the front-end but not on the back end. I tested WC 4.6 using French Langage. 

Front-end - correct sorting:

<img width="1295" alt="Screen Shot 2020-10-16 at 8 33 41 AM" src="https://user-images.githubusercontent.com/19143190/96258924-c6ca9200-0f8a-11eb-8bed-aa968bc3b5c9.png">

Back-end - incorrect sorting (countries which names start with the letter with an accent are listed after all the countries which name starts with the letter that doesn't have an accent):

<img width="1057" alt="Screen Shot 2020-10-16 at 8 35 14 AM" src="https://user-images.githubusercontent.com/19143190/96258943-ccc07300-0f8a-11eb-932b-7d773b905c42.png">

<img width="1072" alt="Screen Shot 2020-10-16 at 8 35 30 AM" src="https://user-images.githubusercontent.com/19143190/96258951-d0ec9080-0f8a-11eb-9760-321aad55cf06.png">

Pinging @claudiosan to see if this is something that can be fixed quickly. Otherwise, I am assigning it a `low` priority.

**Comment by swatipawarGS** [comment] 2021-12-13 12:43
Hi @gevcen ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end for French language  using WooCommerce 5.9.0 version , WordPress 5.8.2 version. 

Please find below screenshots for reference :

Frontend : 
![#27981(frontend)](https://user-images.githubusercontent.com/94531721/145778745-4b5ade7a-b74c-4827-82e9-1438619aae22.jpg)


Backend: 

![#27981(Backend)](https://user-images.githubusercontent.com/94531721/145778780-11be034f-3339-440f-acba-4ce02aef5f6a.jpg)


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by barryhughes** [comment] 2024-02-07 03:32
Also unable to replicate (I tried with German, and the list was ordered as expected). Closing.

**Closed by barryhughes** 2024-02-07 03:32 UTC
Labels: type: bug, focus: i18n, priority: normal, plugin: woocommerce, focus: settings, team: Proton
