### ISSUE TITLE
Impossible to finalise the CSV import of my Woocommerce products

### ISSUE THREAD

**Issue by iomminn** [woocommerce/woocommerce#22015] opened 2018-11-21 21:26 UTC
**Describe the bug**
When i import the csv of my product, i cannot finalise it... after mapping of columns, the program never finishes to work, i seems there 's a bug
i already imported a lot of csv, i never had any issue with that

so i tried to export my existing products
and to reimport them
it doesn't work

i tried to re import a csv file created the days before : it worked well

i cannot understand

any informations 👍 
CPU stats |   | CPU STATISTICS OK: user=1.33% system=0.83% iowait=0.03% idle=97.72%
-- | -- | --
ConfigServer Firewall |   | active
Cron daemon |   | active
Exim mail Queue |   | Mailqueue OK - 0 messages on queue
Load |   | OK - load average: 0.37, 0.32, 0.30
Login Failure Daemon |   | active
MySQL service |   | Uptime: 498946 Threads: 3 Questions: 13014379 Slow queries: 0 Opens: 104762 Flush tables: 9 Open tables: 1024 Queries per second avg: 26.083
Ping |   | OK - world-348.fr.planethoster.net: rta 85.118ms, lost 0%
R1SOFT |   | active
Service SSH |   | active
Web server |   | HTTP OK: HTTP/1.1 200 OK - 417 bytes in 0.174 second response time

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://animazing.fr
Site URL: https://animazing.fr
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.23 - Nous recommandons d’utiliser PHP 7.2 ou supérieur pour optimiser les performances et la sécurité. Comment mettre à jour votre version de PHP ?
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wpij_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 31.22MB
Taille de la base de données: 24.51MB
Taille de l’index: 6.71MB
wpij_woocommerce_sessions: Données : 0.04MB + Index: 0.00MB
wpij_woocommerce_api_keys: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_attribute_taxonomies: Données : 0.00MB + Index: 0.01MB
wpij_woocommerce_downloadable_product_permissions: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_order_items: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_order_itemmeta: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_tax_rates: Données : 0.00MB + Index: 0.01MB
wpij_woocommerce_tax_rate_locations: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_shipping_zones: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_shipping_zone_locations: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_shipping_zone_methods: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_payment_tokens: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_payment_tokenmeta: Données : 0.00MB + Index: 0.00MB
wpij_woocommerce_log: Données : 0.00MB + Index: 0.00MB
wpij_aepc_custom_audiences: Données : 0.00MB + Index: 0.00MB
wpij_aepc_logs: Données : 0.12MB + Index: 0.00MB
wpij_commentmeta: Données : 0.00MB + Index: 0.00MB
wpij_comments: Données : 0.00MB + Index: 0.01MB
wpij_duplicator_packages: Données : 0.00MB + Index: 0.00MB
wpij_links: Données : 0.00MB + Index: 0.00MB
wpij_multi_vendor: Données : 0.00MB + Index: 0.00MB
wpij_multi_vendor_submit_application: Données : 0.00MB + Index: 0.00MB
wpij_options: Données : 1.69MB + Index: 0.16MB
wpij_postmeta: Données : 14.56MB + Index: 4.66MB
wpij_posts: Données : 2.86MB + Index: 0.73MB
wpij_redirection_404: Données : 0.13MB + Index: 0.06MB
wpij_redirection_groups: Données : 0.00MB + Index: 0.00MB
wpij_redirection_items: Données : 0.00MB + Index: 0.00MB
wpij_redirection_logs: Données : 0.00MB + Index: 0.00MB
wpij_revslider_css: Données : 0.09MB + Index: 0.00MB
wpij_revslider_layer_animations: Données : 0.00MB + Index: 0.00MB
wpij_revslider_navigations: Données : 0.00MB + Index: 0.00MB
wpij_revslider_sliders: Données : 0.01MB + Index: 0.00MB
wpij_revslider_slides: Données : 0.07MB + Index: 0.00MB
wpij_revslider_static_slides: Données : 0.00MB + Index: 0.00MB
wpij_snp_log: Données : 0.00MB + Index: 0.00MB
wpij_snp_stats: Données : 0.00MB + Index: 0.00MB
wpij_termmeta: Données : 0.07MB + Index: 0.06MB
wpij_terms: Données : 0.01MB + Index: 0.03MB
wpij_term_relationships: Données : 0.11MB + Index: 0.25MB
wpij_term_taxonomy: Données : 0.01MB + Index: 0.01MB
wpij_usermeta: Données : 0.05MB + Index: 0.01MB
wpij_users: Données : 0.00MB + Index: 0.01MB
wpij_wcfm_daily_analysis: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_detailed_analysis: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_enquiries: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_enquiries_meta: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_enquiries_response: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_following_followers: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_orders: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_product_multivendor: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_refund_request: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_reverse_withdrawal: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_reviews: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_reviews_response: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_review_rating_meta: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_shipping_zone_locations: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_shipping_zone_methods: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_store_taxonomies: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_vendor_ledger: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_withdraw_request: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_marketplace_withdraw_request_meta: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_membership_subscription: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_messages: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_messages_modifier: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_messages_stat: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_support: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_support_meta: Données : 0.00MB + Index: 0.00MB
wpij_wcfm_support_response: Données : 0.00MB + Index: 0.00MB
wpij_wc_download_log: Données : 0.00MB + Index: 0.00MB
wpij_wc_webhooks: Données : 0.00MB + Index: 0.00MB
wpij_wfblockediplog: Données : 0.00MB + Index: 0.00MB
wpij_wfblocks7: Données : 0.00MB + Index: 0.00MB
wpij_wfconfig: Données : 1.20MB + Index: 0.01MB
wpij_wfcrawlers: Données : 0.00MB + Index: 0.00MB
wpij_wffilechanges: Données : 0.00MB + Index: 0.00MB
wpij_wffilemods: Données : 1.96MB + Index: 0.40MB
wpij_wfhits: Données : 0.42MB + Index: 0.12MB
wpij_wfhoover: Données : 0.00MB + Index: 0.00MB
wpij_wfissues: Données : 0.01MB + Index: 0.01MB
wpij_wfknownfilelist: Données : 1.03MB + Index: 0.12MB
wpij_wflivetraffichuman: Données : 0.00MB + Index: 0.00MB
wpij_wflocs: Données : 0.00MB + Index: 0.00MB
wpij_wflogins: Données : 0.00MB + Index: 0.00MB
wpij_wfnotifications: Données : 0.00MB + Index: 0.00MB
wpij_wfpendingissues: Données : 0.00MB + Index: 0.00MB
wpij_wfreversecache: Données : 0.00MB + Index: 0.00MB
wpij_wfsnipcache: Données : 0.00MB + Index: 0.00MB
wpij_wfstatus: Données : 0.07MB + Index: 0.03MB
wpij_wftrafficrates: Données : 0.00MB + Index: 0.00MB
wpij_woof_query_cache: Données : 0.00MB + Index: 0.00MB
wpij_yith_wcwl: Données : 0.00MB + Index: 0.00MB
wpij_yith_wcwl_lists: Données : 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 3103
customize_changeset: 94
header_builder: 1
nav_menu_item: 187
page: 20
post: 11
product: 2318
product_variation: 375
revision: 59
seopress_404: 103
snp_popups: 1
um_directory: 1
um_form: 3
woo_faq: 2
wpcf7_contact_form: 1
wr_mapper: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

All In One Schema Rich Snippets: par Brainstorm Force – 1.5.4
Ninja Popups: par ArsCode – 4.5.9
Autoptimize: par Frank Goossens (futtta) – 2.4.1
Beeketing For WooCommerce: par Beeketing – 3.8.0
BJ Lazy Load: par Bjørn Johansen
Aron Tornberg
angrycreative – 1.0.9

Contact Form 7: par Takayuki Miyoshi – 5.0.5
Cookie Notice: par dFactory – 1.2.44
createIT Size Guide Plugin: par createIT – 2.8 – Non testé avec la version active de WooCommerce
Customer Reviews for WooCommerce: par ivole – 3.46
Duplicator: par Snap Creek – 1.2.52
Google XML Sitemaps: par Arne Brachhold – 4.0.9
Éditeur de page: par Michael M - WPBakery.com – 5.5.4
Meta Box Conditional Logic: par Tan Nguyen – 1.3.4
Meta Box: par MetaBox.io – 4.15.7
Socio Multi Vendor: par Fantastic Plugins – 5.6 – Non testé avec la version active de WooCommerce
Nitro Gallery: par WooRockets  – 1.0.4
Nitro Toolkit: par WooRockets Team  – 1.1.11
Perfect WooCommerce Brands: par Alberto de Vera Sevilla – 1.6.5 – Non testé avec la version active de WooCommerce
Pixel Caffeine: par AdEspresso – 2.0.6 – Non testé avec la version active de WooCommerce
PixelYourSite: par PixelYourSite – 5.3.2 – Non testé avec la version active de WooCommerce
Redirection: par John Godley – 3.6.3
Slider Revolution: par ThemePunch – 5.4.8
Ultimate Member: par Ultimate Member – 2.0.31
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 1.15.3

WC Speed Drain Repair: par WP Fix It – 1.2 – Non testé avec la version active de WooCommerce
WooCommerce All Discounts Lite: par ORION – 1.7
WooCommerce Variation Swatches: par Emran Ahmed – 1.0.48
WOOCS - WooCommerce Currency Switcher: par realmag777 – 1.2.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base de la boutique: #18 - /
Panier: #7 - /cart/
Validation de la commande: #8 - /checkout/
Mon compte: #9 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: WR Nitro
Version: 1.6.6
Author URL: http://www.woorockets.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: wr-nitro/woocommerce/archive-product.php
wr-nitro/woocommerce/cart/cart-shipping.php
wr-nitro/woocommerce/cart/cart-totals.php
wr-nitro/woocommerce/cart/cart.php
wr-nitro/woocommerce/cart/cross-sells.php
wr-nitro/woocommerce/cart/mini-cart.php
wr-nitro/woocommerce/cart/shipping-calculator.php
wr-nitro/woocommerce/checkout/form-checkout.php
wr-nitro/woocommerce/checkout/review-order.php
wr-nitro/woocommerce/checkout/thankyou.php
wr-nitro/woocommerce/content-product.php
wr-nitro/woocommerce/content-product_cat.php
wr-nitro/woocommerce/content-single-product.php
wr-nitro/woocommerce/content-widget-product.php
wr-nitro/woocommerce/global/breadcrumb.php
wr-nitro/woocommerce/global/quantity-input.php
wr-nitro/woocommerce/global/wrapper-end.php
wr-nitro/woocommerce/global/wrapper-start.php
wr-nitro/woocommerce/loop/add-to-cart.php
wr-nitro/woocommerce/loop/loop-end.php
wr-nitro/woocommerce/loop/loop-start.php
wr-nitro/woocommerce/loop/orderby.php
wr-nitro/woocommerce/loop/pagination.php
wr-nitro/woocommerce/loop/sale-flash.php
wr-nitro/woocommerce/myaccount/dashboard.php
wr-nitro/woocommerce/myaccount/downloads.php
wr-nitro/woocommerce/myaccount/form-edit-account.php
wr-nitro/woocommerce/myaccount/form-login.php
wr-nitro/woocommerce/myaccount/my-account.php
wr-nitro/woocommerce/myaccount/my-address.php
wr-nitro/woocommerce/myaccount/navigation.php
wr-nitro/woocommerce/myaccount/orders.php
wr-nitro/woocommerce/single-product/add-to-cart/external.php
wr-nitro/woocommerce/single-product/add-to-cart/grouped.php
wr-nitro/woocommerce/single-product/add-to-cart/simple.php
wr-nitro/woocommerce/single-product/add-to-cart/variable.php
wr-nitro/woocommerce/single-product/meta.php
wr-nitro/woocommerce/single-product/price.php
wr-nitro/woocommerce/single-product/product-image.php
wr-nitro/woocommerce/single-product/rating.php
wr-nitro/woocommerce/single-product/related.php
wr-nitro/woocommerce/single-product/sale-flash.php
wr-nitro/woocommerce/single-product/tabs/tabs.php
wr-nitro/woocommerce/single-product/title.php
wr-nitro/woocommerce/single-product/up-sells.php
wr-nitro/woocommerce/single-product-reviews.php

`

**Comment by rodrigoprimo** [comment] 2018-11-23 12:36
Closing as this is likely a duplicate of #21538. We are working on a solution to this problem which should land in WC 3.6 (see #21282). Meanwhile, there is a workaround described here https://github.com/woocommercewoocommerce/issues/21100#issuecomment-414666449

Please provide more details if you believe the issue you are experiencing is different from the ones mentioned in the links above.

**Closed by rodrigoprimo** 2018-11-23 12:36 UTC
