### ISSUE TITLE
Woocommerce Version 4.9.0

### ISSUE THREAD

**Issue by ZabethVanWyk** [woocommerce/woocommerce#28813] opened 2021-01-14 11:12 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Product Quick Edit does not word. The product disappears from the list when "Quick edit" is selected.
Also, I cannot access the "Variations" section on the product page. It just keeps on loading the page. I need to do price increase updates for each product variation, but currently I can get access to that section.
Also unable to move product to Draft option.

**Expected behavior**
I want to have access to, and be able to edit the Variations section of each product.
I want to be able to make use of the Quick Edit option in the product list.

**Actual behavior**
The spinner keeps on loading when the Variations section is selected on the single product page.
The product completely disappears form the product list when Quick Edit is selected.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'Products'
2. Click on 'Quick Edit'
3. See error

1. Go to 'Products'
2. Click on 'any product'
3. Scroll down to and click on 'Variations'

**Screenshots**
![image](https://user-images.githubusercontent.com/39413891/104583048-530f5280-5669-11eb-9b83-dbedad3a1942.png)

![image](https://user-images.githubusercontent.com/39413891/104583085-63bfc880-5669-11eb-8f41-4f3689fa3119.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://reclineronline.co.za
Site address (URL): https://reclineronline.co.za
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.13
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 3500
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB-1:10.4.17+maria~stretch
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 115.13MB
Database Data Size: 90.44MB
Database Index Size: 24.69MB
wp_woocommerce_sessions: Data: 0.23MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.52MB + Index: 1.45MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.52MB + Index: 1.97MB + Engine InnoDB
wp_ac_abandoned_cart_history_lite: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates_lite: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_asre_sales_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.31MB + Index: 0.28MB + Engine InnoDB
wp_db7_forms: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_emd_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gpi_api_error_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gpi_custom_urls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gpi_page_blacklist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gpi_page_reports: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gpi_page_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gpi_summary_snapshots: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mainwp_stream: Data: 1.52MB + Index: 1.00MB + Engine InnoDB
wp_mainwp_stream_meta: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
wp_options: Data: 6.42MB + Index: 0.23MB + Engine InnoDB
wp_postmeta: Data: 6.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wp_rafflepress_contestants: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_rafflepress_entries: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_rafflepress_giveaways: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_rafflepress_polls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 0.67MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_entries: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_entry_fields: Data: 0.27MB + Index: 0.23MB + Engine InnoDB
wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 42.52MB + Index: 0.05MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 7.52MB + Index: 8.03MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.44MB + Index: 0.48MB + Engine InnoDB
wp_wsal_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wapo_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wapo_types: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_yoast_indexable: Data: 0.34MB + Index: 0.28MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1016
blocks: 8
custom_css: 1
emd_form: 1
fpf_fields: 1
nav_menu_item: 40
ni-order-status: 1
oembed_cache: 3
page: 26
product: 31
product_variation: 299
shop_coupon: 9
shop_order: 246
shop_order_refund: 4
wc_order_email: 6
wc_order_status: 12
wcpa_pt_forms: 19
wpcf7_contact_form: 2
wpforms: 4
ywtm_tab: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

Advanced Product Fields for WooCommerce: by StudioWombat – 1.3.4
Agile CRM WooCommerce: by Agile CRM Team – 1.0 – Installed version not tested with active version of WooCommerce 4.0
Checkout Address Sugessions: by Greg Seiler – 1.2.9 – Installed version not tested with active version of WooCommerce 4.0
Contact Form 7: by Takayuki Miyoshi – 5.3.2
Contact Form CFDB7: by Arshid – 1.2.5.3
Delivery Management For Woocommerce: by xpressdelivery.app – 2.0 – Installed version not tested with active version of WooCommerce 4.0
Duplicate Page: by mndpsingh287 – 4.3
Duplicator: by Snap Creek – 1.3.40.1
Facebook for WooCommerce: by Facebook – 2.2.0
GAinWP Google Analytics Integration for WordPress: by IntelligenceWP – 5.4.6
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.14.0
Insert Headers and Footers: by WPBeginner – 1.5.0
MainWP Child Reports: by MainWP – 2.0.6
MainWP Child: by MainWP – 4.1.3.1
Members: by MemberPress – 3.1.3
Nextend Social Login: by Nextendweb – 3.0.26
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.7.2
Ordered Variable Product Report: by CedCommerce – 1.0.6 – Installed version not tested with active version of WooCommerce 4.0
Poptin: by Poptin – 1.2.1
Product Sales Report for WooCommerce: by Potent Plugins – 1.4.10
RafflePress Pro: by RafflePress – 1.4.1
Sales Trends Analysis for WooCommerce: by Infosoft Consultant – 1.9 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce - Show only lowest prices in variable products: by Fernando Tellado – 0.9.25
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.46.24

WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.3.7.1
Sales Report Email for WooCommerce: by zorem – 2.5.9
Woocommerce Custom Product Addons: by Acowebs – 3.9.8
Product Feed PRO for WooCommerce: by AdTribes.io – 9.3.9
Additional Variation Images Gallery for WooCommerce: by Emran Ahmed – 1.2.0
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.5
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.8.4
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.0
WooCommerce Order Status Manager: by SkyVerge – 1.12.0
WooCommerce PayFast Gateway: by WooCommerce – 1.4.17
WooCommerce Google Product Feed: by Ademti Software Ltd. – 9.0.1
WooCommerce: by Automattic – 4.9.0
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO: by Team Yoast – 15.6.2
WP Mail SMTP Pro: by WPForms – 2.5.3
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.6

WP Activity Log for bbPress: by WP White Security – 1.0.2
WP Activity Log for WPForms: by WP White Security – 1.1
WP Activity Log: by WP White Security – 4.1.5.1
Smush: by WPMU DEV – 3.8.2
WP Super Minify: by Dipak C. Gajjar – 1.5.1
WPForms Form Locker: by WPForms – 1.2.3
WPForms Mailchimp: by WPForms – 1.4.2
WPForms Surveys and Polls: by WPForms – 1.6.3
WPForms: by WPForms – 1.6.4.1
YITH WooCommerce Request A Quote Premium: by YITH – 2.4.3
YITH WooCommerce Wishlist: by YITH – 3.0.18

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #22 - /shop/
Cart: #23 - /cart/
Checkout: #24 - /checkout/
My account: #25 - /my-account/
Terms and conditions: #942 - /terms-and-conditions/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.13.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
/usr/www/users/reclixmbbg/wp-content/plugins/woo-variation-gallery/templates/product-images.php
/usr/www/users/reclixmbbg/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php


### WooCommerce Google Product Feed options ###

Google merchant centre product feed: Enabled
Google merchant centre product review feed: -
Bing merchant centre feed: -
Google merchant centre local product inventory feed: -
Google merchant centre local products feed (legacy): -
Google merchant centre product inventory feed (legacy): -
Include variations in feed: Enabled
Send "item group ID": Enabled
Debug key: 553628a1-5a12-4e7a-b662-8de69ecc1cf7

### WooCommerce Google Product Feed fields ###

Product description: Main product description (full preferred) plus variation description.
Availability: Defaults to "in stock".
Brand: Defaults to "Reclineronline".
Manufacturer Part Number (MPN): 
Product Type: Defaults to "Furniture > Chairs > Arm Chairs
Recliners & Sleeper Chairs".

Google Product Category: Defaults to "Furniture > Chairs > Arm Chairs
Recliners & Sleeper Chairs".

Gender: Defaults to "unisex".
Age Group: Defaults to "adult".
Size system: 
Instalment: 

### Action Scheduler ###

Complete: 8,088
Oldest: 2020-12-28 12:50:47 +0000
Newest: 2021-01-14 11:07:39 +0000

Failed: 8
Oldest: 2020-07-08 07:58:26 +0000
Newest: 2020-08-05 08:31:23 +0000

Pending: 9
Oldest: 2021-01-14 11:22:34 +0000
Newest: 2021-01-18 18:40:44 +0000

`
```
</details>

**Comment by mfs-mindsize** [comment] 2021-01-15 21:49
Hi @ZabethVanWyk - What browser are you using? What operating system? Out of curiosity, have you tried a different browser on that OS, does it still happen? 

Note: I'm not suggesting changing browser is a solution :) Only trying to score the problem a little bit more :)

**Comment by tammullen** [comment] 2021-01-18 10:52
Hi @ZabethVanWyk 

Thank you for submitting the issue. However, I can’t reproduce either of the issues you mention using the steps you provided. Everything is working as expected on my end. 

![Screenshot_2021-01-18_at_10_49_16](https://user-images.githubusercontent.com/24649833/104906009-0f735c00-597b-11eb-9b63-43942fe5d6f1.png)
Quick edit is working as expected.

![Screenshot_2021-01-18_at_10_48_51](https://user-images.githubusercontent.com/24649833/104906022-11d5b600-597b-11eb-9820-52d49963ed12.png)
I can also access variations.

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by ZabethVanWyk** [comment] 2021-01-20 06:37
Hi Tam,

Thank you for your reply. I rolled back to all previous versions of plugins
and WP, before the issue happened. The inactive plugins you noticed might
have been while I was also busy troubleshooting, as the issue had to get
resolved ASAP.

Kind regards
Zabeth van WykWeb Designer

*Mobile *+27 (0) 84 684 5947

**Comment by juliaamosova** [comment] 2021-02-27 00:48
Hi @ZabethVanWyk,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-02-27 00:48 UTC
Labels: needs feedback
