### ISSUE TITLE
Fixed price basket coupons applying different amounts

### ISSUE THREAD

**Issue by banksdigital** [woocommerce/woocommerce#24362] opened 2019-08-08 13:43 UTC
**Describe the bug**
Hello, 

Please could someone explain to me how coupons work when products are entered exclusive of tax, woocommerce determines the tax rate to be applied based on country and where products have zero-rated variables.

E.g. In the UK children's products are zero-rated but adult sizes require VAT 20%.  

Product Created
Sizes: 6/7  7/8  M  L
First two sizes are children sizes and are set to be "Zero-rated" and the final two are applicable for all taxes.

The reason for this request is because when I create fixed price discounts via a coupon, I get massively different results depending on what products I have in my cart. Assuming this has something to do with tax.

Test 1
Cart contains two products
1x zero-rated size
1x VAT 20% size

£10 fixed basket discount coupon applied 
Discount = £11

Test 2
Cart contains one product
1x zero-rated size

£10 fixed basket discount coupon applied 
Discount = £10

Test 3
Cart contains one products
1x VAT 20% size

£10 fixed basket discount coupon applied 
Discount = £12

As you can see in three tests we get three different results which considering the coupon is a FIXED £10 discount, it should be £10 no matter what tax is applied. It's £10, no more and no less....£10 fixed price discount means £10.

If we send out a coupon for a £10 fixed price discount our customers see different results.

**Comment by JuanchoPestana** [comment] 2019-08-09 23:40
Hey @banksdigital ,
I took a look at what you mentioned because I thought it was quite interesting...
I have one question... When you say that in each test you get a different discount, do you mean that SPECIFICALLY the discount field marks a different amount? Or, that the TOTAL amount due at the end of each test varies when the discount is applied?

I ask this because from what I could find while experimenting, is that, the tax applied to your scenarios varies because the discount is applied pre-tax calculation, so there's where the numbers get confusing... But not because the coupon is making a different discount in each case. From what I could find, when you apply a coupon in a cart with a taxable item, and a non-taxable item, the discount of the coupon gets split between the two items, and after that discount, the tax is calculated. I haven't managed to calculate HOW the discount is distributed amongst the items in the cart yet, but I'll continue to work on that...

I might be wrong here, but I suspect that this is the cause for confusion in this scenario... Let me know what you think and reply here so that we can work in trying to figure this out!

**Comment by banksdigital** [comment] 2019-08-12 08:30
When you enter a coupon it tells you **"COUPONCODE -£10.00"** within the totals field bottom right. This amount changes as described above.

I understand this is being altered based on taxes to which I can understand to a certain degree in some scenarios, maybe if ALL products were tax exempt etc. However, the case for a £10 fixed price basket discount needs to remain no matter what taxes are included / excluded.

I hope this helps! Thank you very much for your response.

**Comment by rodrigoprimo** [comment] 2019-08-12 18:39
Hi @banksdigital,

You will find more information about how coupons impact tax calculations in this link: https://docs.woocommerce.com/document/coupon-management/#section-8

Coupon discount is applied before tax and the discount amount should not change for fixed cart discount coupons. As far as I can test, this is the current behavior and it is working as expected.

I'm closing this issue for now as there is not enough information in the description to test your case and it doesn't seem that this is a bug in WooCommerce. More likely it is just some misunderstanding of how the discount is applied. If that is not the case, please leave a comment with clear steps on how to reproduce the issue and I will take a second look. We will need the price of the products added to the cart and the total that you are seeing.

Thanks

**Closed by rodrigoprimo** 2019-08-12 18:39 UTC

**Comment by banksdigital** [comment] 2019-08-13 09:10
I'm sorry but I have given step by step instructions above on how to replicate this issue.

The meaning of a FIXED price coupon code is that the price does NOT change.
If I create a £10 fixed basket discount code then the discount should ALWAYS be £10.

Tax calculations should never come into play here.

Add any products to your cart that are more than £10 and of the same setup as described above and you can see the issues. (Zero-rated variation / taxable variation E.g. Size - Kids / Adults sizes)

If I send someone a £10 fixed basket discount code they expect to get £10 off any basket. It shouldn't make any difference if there are products in the cart which are zero-rated or a mixture of taxable and zero-rated / reduced.

£10 fixed price basket discount = £10.....not £11 and not £12.

**Comment by rodrigoprimo** [comment] 2019-08-14 13:14
As far as I can test, the amount of the discount doesn't change. I was not able to reproduce the behavior that you are reporting. That is why I asked for more detailed testing instructions, specifically the price of the products. Screenshots might help as well.

I'm tested with a modified version of one of the sample products from [sample_products.csv](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv). I modified two variations of the product "V-Neck T-Shirt" to cost R$20 each. I set the blue color variation to have a 20% tax and the green color variation to be tax free. I then added the two products to the cart and applied a £10 fixed cart discount coupon. The discount amount was £10 as expected and the order total was £33. Details below:

![Screenshot from 2019-08-14 10-13-43](https://user-images.githubusercontent.com/77215/63023836-5272fb00-be7c-11e9-8c39-4cc835f67186.png)

**Comment by banksdigital** [comment] 2019-08-14 14:13
Hello, what global tax settings have you applied to this store ? Prices need to be entered exclusive of tax.

**Comment by rodrigoprimo** [comment] 2019-08-20 10:40
The option "No, I will enter prices exclusive of tax" was selected when I tested this.

**Comment by urkaGR** [comment] 2022-10-09 14:50
Do you have any solution for a fixed basket discount without any matter how much % taxes the customer has to pay?
We need product price settings in woocommerce without VAT! Problem is that this setting is also used for coupons. So you can't add coupon value including VAT and product price without VAT. But this is needed if you sell in different countries and have printed coupons for redeem because you must print there the value inkluding VAT and do not know in this moment from where the redeem customer will be.
