### ISSUE TITLE
Issue with Woocommerce API Integration

### ISSUE THREAD

**Issue by Ronny0013** [woocommerce/woocommerce#26287] opened 2020-04-25 00:51 UTC
Hello Guys,

We are facing a issue currently with our shipping company using Woocommerce API to update the tracking number on the orders but the orders are losing custom created attributes once the tracking number is added. I am not an experienced programmer but below is the code they are using to update the woocommerce orders:

"meta":[{"key":"flavour","label":"Flavour","value":"Strawberry Custard"},{"key":"add-2-x-nic-shots","label":"Add 2 X Nic Shots","value":"Yes"}]}

Changes to:
"meta":[{"key":"add-2-x-nic-shots","value":"Yes","label":"Add 2 X Nic Shots"}]}

CODE:

string updateOrderResponse = wc.UpdateOrder(53857, order).Result;

order is {"id":53857,"order_number":53857,"created_at":"2020-04-19T14:56:19Z","updated_at":"2020-04-19T14:56:50Z","completed_at":"1970-01-01T00:00:00Z","status":"completed","currency":"GBP","total":15.84,"subtotal":9.16,"total_line_items_quantity":1,"total_tax":1.83,"total_shipping":4.85,"cart_tax":1.83,"shipping_tax":0.00,"total_discount":0.00,"shipping_methods":"DHL Express Delivery","payment_details":{"method_id":"paypal","method_title":"PayPal","paid":true},"billing_address":{"first_name":"Raul","last_name":"Dgra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB","email":"ronny_13@yahoo.co.uk","phone":"079752"},"shipping_address":{"first_name":"Raul","last_name":"Dgra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB"},"note":"","customer_ip":"2a00:23a8:4c0b:eb00:d558:f1cc:f2e3:876c","customer_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","customer_id":0,"view_order_url":"https://ukvapekings.com/my-account/view-order/53857/","line_items":[{"id":177321,"subtotal":9.16,"subtotal_tax":1.83,"total":9.16,"total_tax":1.83,"price":9.16,"quantity":1,"tax_class":"","name":"Fizzy E Liquid 120ml shortfill by Mohawk & Co.","product_id":4249,"sku":"","meta":[{"key":"flavour","label":"Flavour","value":"Strawberry Custard"},{"key":"add-2-x-nic-shots","label":"Add 2 X Nic Shots","value":"Yes"}]}],"shipping_lines":[{"id":177322,"method_id":"flat_rate","method_title":"DHL Express Delivery","total":4.85}],"tax_lines":[{"id":177323,"rate_id":1,"code":"GB-VAT-1","title":"VAT","total":1.83,"compound":false}],"fee_lines":[],"coupon_lines":[],"customer":{"id":0,"email":"ronny_13@yahoo.co.uk","first_name":"Raul","last_name":"Dgra","billing_address":{"first_name":"Raul","last_name":"Dgra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB","email":"ronny_13@yahoo.co.uk","phone":"079702"},"shipping_address":{"first_name":"Raul","last_name":"Dgra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB"}}}

updateOrderResponse is {"id":53857,"order_number":"53857","created_at":"2020-04-19T14:56:19Z","updated_at":"2020-04-19T22:56:19Z","completed_at":"2020-04-19T22:56:19Z","status":"completed","currency":"GBP","total":"16.81","subtotal":"9.16","total_line_items_quantity":1,"total_tax":"2.80","total_shipping":"4.85","cart_tax":"1.83","shipping_tax":"0.97","total_discount":"0.00","shipping_methods":"DHL Express Delivery","payment_details":{"method_id":"paypal","method_title":"PayPal","paid":true},"billing_address":{"first_name":"Raul","last_name":"Dgra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB","email":"ronny_13@yahoo.co.uk","phone":"079502"},"shipping_address":{"first_name":"Raul","last_name":"Dgra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB"},"note":"","customer_ip":"2a00:23a8:4c0b:eb00:d558:f1cc:f2e3:876c","customer_user_agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.163 Safari\/537.36","customer_id":0,"view_order_url":"https:\/\/ukvapekings.com\/my-account\/view-order\/53857\/","line_items":[{"id":177321,"subtotal":"9.16","subtotal_tax":"1.83","total":"9.16","total_tax":"1.83","price":"9.16","quantity":1,"tax_class":"","name":"Fizzy E Liquid 120ml shortfill by Mohawk & Co.","product_id":4249,"sku":"","meta":[{"key":"add-2-x-nic-shots","value":"Yes","label":"Add 2 X Nic Shots"}]}],"shipping_lines":[{"id":177322,"method_id":"flat_rate","method_title":"DHL Express Delivery","total":"4.85"}],"tax_lines":[{"id":177323,"rate_id":1,"code":"GB-VAT-1","title":"VAT","total":"2.80","compound":false}],"fee_lines":[],"coupon_lines":[],"customer":{"id":0,"email":"ronny_13@yahoo.co.uk","first_name":"Raul","last_name":"Dgra","billing_address":{"first_name":"Raul","last_name":"Dgra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB","email":"rahuldhingra_13@yahoo.co.uk","phone":"07975651502"},"shipping_address":{"first_name":"Rahul","last_name":"Dhingra","company":"","address_1":"Vapers Planet","address_2":"Leicester","city":"Leicester","state":"United Kingdom","postcode":"LE1 4AL","country":"GB"}}}

**Comment by claudiosanches** [comment] 2020-04-28 17:21
Hi @Ronny0013,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-04-28 17:21 UTC
