### ISSUE TITLE
woocommerce checkout isssue

### ISSUE THREAD

**Issue by vivelancer** [woocommerce/woocommerce#17990] opened 2017-12-01 18:54 UTC
when click paypal click {proceed to checkout  }

woocommerce error banner

**Comment by claudiulodro** [comment] 2017-12-01 21:47
I need all the information that the issue template asked when you created this issue to be able to determine what the problem is. Without it I can't troubleshoot anything. Feel free to make a new issue with the required information if you want, but I'm closing this one since there is no information I can work with here. You can also try asking on the [support forums](https://wordpress.org/support/plugin/woocommerce) since your problem is almost surely not caused by a bug in WooCommerce but by another plugin, a configuration issue, or some custom code.

**Closed by claudiulodro** 2017-12-01 21:47 UTC
