### ISSUE TITLE
Wordpress / WooCommerce Multisite: Admins can't create users without confirmation email step. Leads to broken in-person and phone order workflows.

### ISSUE THREAD

**Issue by bobteree** [woocommerce/woocommerce#19864] opened 2018-04-25 23:57 UTC
Not sure if this is a bug or not, but this functionality is prohibiting WooCommerce store owners from:

1) Creating users easily (i.e. without requiring email confirmation)
2) Selling items in-person or over the phone

**Issues:**
1. Unlike normal Wordpress/WooCommerce, when you use WooCommerce in Wordpress Multisite, Admins of various sites/stores are NOT able to create a user without requiring the user to confirm their email address via a confirmation email.
2. Workflow implications: Many store owners use WooCommerce to take physical in-store orders as well as orders over the phone. If the customer is physically buying something or calling up a store owner, and they **DO NOT HAVE** a user account setup in WooCommerce (running on Multisite), there is no way to easily take that order and pay for it as that customer doesn't exist. This is a big deal for all of my customers as they have physical and phone presence to sell.
3. Workaround doesn't work: Only multisite "Keymasters" can create new users without the email confirmation requirement. But that is unworkable as my client who runs a store can't call me all the time to create users on the spot. In addition, even when I have created users, a normal store Admin can't pay for that order via the "Customer payment page >" on the order page. It yields an error that says this order cannot be paid for in red text. So even when a "Keymaster" creates a user for an "Admin", the ability for that admin to run through the check-out flow to pay for a phone/physical order does not work. 
4. I believe the inability for an Admin to create users without email confirmation (in Multisite) is related to the inability to pay for those orders as well. Not sure.
----------------------------------------------------------------------
**Solution:**
1. All Admins (in normal Wordpress or Multisite) need to be able to create users/customers without the need for email confirmation. This is mainly to enable WooCommerce to be used for phone and in-person orders where the customer is unknown to the system. Having my client/admin, mimic a brand new customer for the first time and every time is time-consuming and not intuitive. They should be able to create a brand new order for a brand new user directly from the "Add new order" screen( "/wp-admin/post-new.php?post_type=shop_order"). If the user is unknown to the system, and if guest check-out, is selected, a new order should be able to be created by any Admin or Shopkeeper.
2. Assuming new orders can be created with non-existent users successfully, any Admin or Shopkeeper should also be able to pay for that order using the "Customer payment page >" feature.
3. If the user for that new order is unknown by the system, a new user account should be created so that the ship to and bill to information is stored and can then be reused for subsequent orders via the "Customer search" feature on the Add new order page. It should be noted that many of my clients' biggest customers place orders over the phone, so they need to be set up over the phone and then that same info needs to able to be reused in subsequent orders.

I realize this may be a core "Wordpress" feature, but the requirement is very much central to WooCommerce/ecommerce requirements (i.e. phone orders or in person orders for brand new customers). So, perhaps WooCommerce can build off of the Wordpress API to enable the 3 abilities above, namely:

- Create users without email confirmation step directly from the "Add new order" page.
- Pay for those same orders via the "Customer payment page >" feature as all of this needs to occur quickly during a physical or phone order.
- These same users should be created so that their order information (e.g. ship to and bill to information, phone, email) are saved for future phone and in-person orders.

**Comment by bobteree** [comment] 2018-04-25 23:58
![customer-payment-page-link](https://user-images.githubusercontent.com/1479735/39278757-f24391b6-48c2-11e8-9872-4f92f663159e.jpg)

This is screenshot of the "Customer payment page >" feature referenced above.

**Comment by bobteree** [comment] 2018-04-26 00:01
![multisite-admins-dont-have-skip-email-confirm-option](https://user-images.githubusercontent.com/1479735/39278830-4a363900-48c3-11e8-8dcb-d4d7b3c3e2c9.jpg)

Here is the admin feature that only Keymasters have in Multisite. But normal admins in normal Wordpress DO have this ability...to create users without email confirmation.

**Comment by rodrigoprimo** [comment] 2018-04-27 14:50
Thanks for your detailed comments, @bobteree.

> Create users without email confirmation step directly from the "Add new order" page.

As a rule of thumb, WooCommerce shouldn't interfere with the way WordPress multisite handles accounts creation and permissions. I haven't checked, but I would assume that you can solve this with a WP capability plugin. If you feel this is a feature that would benefit a significant number of WC users, please add it to the ideas board (http://ideas.woocommerce.com).

> Pay for those same orders via the "Customer payment page >" feature as all of this needs to occur quickly during a physical or phone order.

AFAIK, paying “as the customer” using the "Customer payment page ->" link is not supported by WC core. WC generates an error when you try to open the link logged in as a user other than the one who "owns" the order. Doing it can lead to bad things like payment cards being saved to admin profile. This is another feature request, and I think it might be already on the ideas board.

We recommend where possible handling the payment using your payment gateways virtual terminal (if they offer this feature) to avoid using WooCommerce checkout to handle this payment.

> These same users should be created so that their order information (e.g. ship to and bill to information, phone, email) are saved for future phone and in-person orders.

Creating accounts automatically is not desirable, especially with things like GDPR coming up which are going to discourage that. Probably worth mentioning, in case you don't know already, that accounts are not required. They could be guest orders.

I will close this issue. Please reopen it if I missed something.

**Closed by rodrigoprimo** 2018-04-27 14:50 UTC

**Comment by bobteree** [comment] 2018-04-27 15:15
1) Will see if there is a plugin so users can be created in multisite.
2) "Customer payment page ->" IS a core WC feature. It is on the main order page. Since it is exposed, I would think that an admin should be able to use that workflow, just like the actual customer. Again, this is all about taking a phone order or in-person order.  I get the issue about the card being saved to an admin account. That needs to be dealt with...But pulling up 100 feet, you can see how a Shop Keeper needs to be able to take a phone or in-person order? That is the "need" here. WooCommerce is terrible at servicing the phone/in-person channel and this needs to be improved. Yes, we can use our payment gateway, but that won't update the Woo order and won't update inventory, financials, et. al. in Woo, which is a must to scale operations. The ability for a Shop Keeper to pay for an order is a must as Shop Keepers can create invoices for customers and a customer might call in their credit card...NOT all customers love the Internet 100%. This is crux of the uber-need. If guest checkout is enabled, why can't "anyone" with the order page link pay for it? There must be some user-centric token that doesn't allow anyone to pay for it. FYI, any admin or shop keeper can pay via the payment link today. It's just the problem regarding the first issue that breaks this.

What is GDPR?

**Comment by rodrigoprimo** [comment] 2018-04-27 18:42
> "Customer payment page ->" IS a core WC feature.

AFAIK the idea of this feature is to provide an easy way for shop managers to copy this link to send it to customers if needed. WC core workflow for payments on manual orders is for the store manager to create a manual order and then email the payment link to the user. It might be possible to improve this workflow to meet your needs using extensions but I'm not the best person to help you with this and this is not the right forum. GitHub is used exclusively to report WC core bugs. If you feel WC core should provide better support for over the phone and in-person orders please share your suggestions using http://ideas.woocommerce.com/.

> FYI, any admin or shop keeper can pay via the payment link today.

Are you able to reproduce this behavior on a clean WC core install? I'm asking because when I tried I got the following error:

"This order cannot be paid for. Please contact us if you need assistance."

Which is generated here:

https://github.com/woocommerce/woocommerce/blob/0660a50e07815547085eb04494aed14fc1e2ac64/includes/shortcodes/class-wc-shortcode-checkout.php#L109

The code checks to see if the user accessing the payment page is the customer who "owns" the order:

https://github.com/woocommerce/woocommerce/blob/f9e45bea91790b799d45ce31b8662805b4a18520/includes/wc-user-functions.php#L294

> What is GDPR?

https://en.wikipedia.org/wiki/General_Data_Protection_Regulation

**Comment by rodrigoprimo** [comment] 2018-04-27 18:46
In case it helps, below is a link that talks about using WooCommerce and Square to run a store that works both online and offline (I can't vouch for it as I never tried this integration):

https://techcrunch.com/2016/07/26/woocommerce-now-works-with-square-to-seamlessly-run-both-online-and-offline-stores/
