### ISSUE TITLE
Adding New Field C P F to BACS Account Details Page - for the Brazilian Maket

### ISSUE THREAD

**Issue by PaulodoPorto** [woocommerce/woocommerce#28084] opened 2020-10-23 22:54 UTC
hi Guys, 
please please please!
Since 3 days i'm looking for a solution for the payment gateway BACS.

`https://docs.woocommerce.com/document/bacs/`

In the brazilian market, it's a must for any Bank Transfer situation, the user that chosse for the gateway BACS, he/she must to use for the transfer a document called **CPF** when the bank transfer occuer between two civil citizens. (Not for corporations).

Since 3 days i'm trying to create a custom field that can meet this great need in the account details form. When a customer/client receives a e-mail with the Bank Account Detailed Information, he/she needs to have the number of this document anyway, otherwise he/she will not be able to make the bank transfer. This is a Must in our country. So please i ask you kindly to create this feature, or even send me the correct Hook to make the magic happens. i've already walked in all forums looking for the answer, but till now i didn't get nothing! That would be very kind of you guys if i can have a answer.
i hussle since 3 days with it.!

**Just to make the life easier to understand, please this is the Account Details Form in the picture:**
`https://docs.woocommerce.com/wp-content/uploads/2012/01/directbanktransfer-setup.png`

i've tried a lot of different Hooks and this is the closest that  i found to make the magic happens...But nothing happens!
```
function pekky_bacs_account_field( $account_fields, $order_id ) {
    $account_fields['test_added' ] = array(
        'label' => 'THIS SHOULD SHOWWW',
         'value' => 'Yup it doessss'
    );
    return $account_fields;
}

add_filter( 'woocommerce_bacs_account_fields', 'pekky_bacs_account_field', 10, 2);

```

Thank you so much for the great Job.
Best Regards
Paulo

**Comment by juliaamosova** [comment] 2020-10-28 21:34
Hi @PaulodoPorto,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-28 21:34 UTC
