### ISSUE TITLE
Attributes not being pulled through correctly on orders

### ISSUE THREAD

**Issue by TradeChem** [woocommerce/woocommerce#21487] opened 2018-10-03 09:38 UTC
**Describe the bug**
Intermittently, the attributes on orders are not being pulled through correctly, with only the first letter of the attribute showing, as follows:

Variation ID: 7448
Fragrances:	
v

Fragrance 2:	
c

Fragrance 3:	
l

Fragrance 4:	
c

Container:	
e

On the majority of orders, it would pull through right, i.e. vanilla, cherry etc, but on a couple we've had to call customers to confirm what fragrances they require.

**Screenshots**
![1](https://user-images.githubusercontent.com/43809946/46402690-63010380-c6f8-11e8-966f-49b7e2943f5f.JPG)
![2](https://user-images.githubusercontent.com/43809946/46402694-64cac700-c6f8-11e8-9fea-a0c8ea49d82b.JPG)

**Expected behavior**
Fragrances to pull through in full!

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://trade-chem.co.uk
Site URL: https://trade-chem.co.uk
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.10
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0+deb7u1-log - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wpim_
MaxMind GeoIP Database: ✔
Total Database Size: 67.14MB
Database Data Size: 53.11MB
Database Index Size: 14.03MB
wpim_woocommerce_sessions: Data: 21.07MB + Index: 1.16MB
wpim_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpim_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpim_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpim_woocommerce_order_items: Data: 0.44MB + Index: 0.25MB
wpim_woocommerce_order_itemmeta: Data: 1.78MB + Index: 1.30MB
wpim_woocommerce_tax_rates: Data: 0.01MB + Index: 0.01MB
wpim_woocommerce_tax_rate_locations: Data: 0.01MB + Index: 0.01MB
wpim_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpim_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpim_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpim_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpim_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpim_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpim_aws_cache: Data: 0.82MB + Index: 0.00MB
wpim_aws_index: Data: 3.06MB + Index: 0.00MB
wpim_commentmeta: Data: 0.33MB + Index: 0.27MB
wpim_comments: Data: 1.41MB + Index: 0.58MB
wpim_duplicator_packages: Data: 0.00MB + Index: 0.00MB
wpim_ff_cache: Data: 0.00MB + Index: 0.00MB
wpim_ff_comments: Data: 0.00MB + Index: 0.00MB
wpim_ff_image_cache: Data: 0.00MB + Index: 0.00MB
wpim_ff_options: Data: 0.00MB + Index: 0.00MB
wpim_ff_posts: Data: 0.09MB + Index: 0.01MB
wpim_ff_post_media: Data: 0.00MB + Index: 0.00MB
wpim_ff_snapshots: Data: 0.00MB + Index: 0.00MB
wpim_ff_streams: Data: 0.00MB + Index: 0.00MB
wpim_ff_streams_sources: Data: 0.00MB + Index: 0.00MB
wpim_links: Data: 0.00MB + Index: 0.00MB
wpim_nextend2_image_storage: Data: 0.02MB + Index: 0.00MB
wpim_nextend2_section_storage: Data: 0.63MB + Index: 0.01MB
wpim_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB
wpim_nextend2_smartslider3_sliders: Data: 0.07MB + Index: 0.00MB
wpim_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB
wpim_nextend2_smartslider3_slides: Data: 0.66MB + Index: 0.00MB
wpim_options: Data: 3.17MB + Index: 0.22MB
wpim_pmxi_files: Data: 0.00MB + Index: 0.00MB
wpim_pmxi_history: Data: 0.00MB + Index: 0.00MB
wpim_pmxi_images: Data: 0.00MB + Index: 0.00MB
wpim_pmxi_imports: Data: 0.03MB + Index: 0.00MB
wpim_pmxi_posts: Data: 0.02MB + Index: 0.02MB
wpim_pmxi_templates: Data: 0.00MB + Index: 0.00MB
wpim_postmeta: Data: 11.95MB + Index: 6.37MB
wpim_posts: Data: 3.74MB + Index: 0.68MB
wpim_termmeta: Data: 0.07MB + Index: 0.06MB
wpim_terms: Data: 0.05MB + Index: 0.11MB
wpim_term_relationships: Data: 0.12MB + Index: 0.31MB
wpim_term_taxonomy: Data: 0.06MB + Index: 0.08MB
wpim_usermeta: Data: 3.22MB + Index: 2.31MB
wpim_users: Data: 0.27MB + Index: 0.26MB
wpim_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpim_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpim_wd_fb_data: Data: 0.00MB + Index: 0.00MB
wpim_wd_fb_info: Data: 0.00MB + Index: 0.00MB
wpim_wd_fb_option: Data: 0.00MB + Index: 0.00MB
wpim_wd_fb_shortcode: Data: 0.00MB + Index: 0.00MB
wpim_wd_fb_theme: Data: 0.01MB + Index: 0.00MB
wpim_wpgdprc_consents: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1244
customize_changeset: 17
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
nav_menu_item: 82
o-discount: 1
page: 16
post: 4
product: 497
product_variation: 1381
revision: 160
shop_coupon: 276
shop_order: 2446
shop_order_refund: 2
sp_wps_shortcodes: 1
woo_discount: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

AH Display Widgets: by Andreas Hecht – 1.0.2
AJAX Login and Registration modal popup: by Maxim K – 1.31
Business WorldPay Gateway for Woocommerce: by MDSDev – 1.4.0 – Not tested with the active version of WooCommerce
Cart2cart: OpenCart to Woocommerce Plugin: by MagneticOne – 2.0.0 – Not tested with the active version of WooCommerce
Cart2Cart: Password Migration: by MagneticOne – 1.1
GDPR Cookie Consent: by WebToffee – 1.6.5
Custom Facebook Feed: by Smash Balloon – 2.7.2
Duplicator: by Snap Creek – 1.2.42
Dynamic Pricing and Discounts for WooCommerce: by xadapter – 3.5.3 – Not tested with the active version of WooCommerce
Export Users to CSV: by Matt Cromwell – 1.1.1
Flow-Flow Lite: by Looks Awesome – 3.0.58
Gantry 5 Framework: by RocketTheme
LLC – 5.4.26

Gratisfaction All-in-One loyalty contests referral program for WooCommerce: by Appsmav – 2.3.4 – Not tested with the active version of WooCommerce
Hide Admin Bar From Front End: by Aftab Husain – 1.0.0
Hide This: by Andrés Villarreal – 1.1.3
IM Facebook Widget: by Igor Mojto – 1.2.0
Jetpack by WordPress.com: by Automattic – 6.4.2
Max Mega Menu: by Tom Hemsley – 2.5
Mobile Contact Bar: by Anna Bansaghi – 2.0.2
Smart Slider 3 Pro: by Nextend – 3.3.6
One Click Order Re-Order: by CedCommerce – 1.1.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
SEO Writing Assistant from SEMrush: by Maxim Korobko – 1.0.0
WooCommerce Cart Count Shortcode: by Pronto Tools – 1.0.4 – Not tested with the active version of WooCommerce
Woo Custom Related Products: by WPCodelibrary – 1.3.1 – Not tested with the active version of WooCommerce
WooCommerce Permalink Manager: by premmerce – 2.1.2
WooCommerce Boost Sales Premium: by Andy Ha (villatheme.com) – 1.3.8.4 – Not tested with the active version of WooCommerce
WooCommerce Print Invoice & Delivery Note: by Tyche Softwares – 4.4.3 – Not tested with the active version of WooCommerce
WooCommerce CardSave Redirect Gateway: by CardSave Online – 2.4 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.3
WooCommerce SagePay Form and SagePay Direct Gateway: by Andrew Benbow – 3.11.2 – 3.12.3 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.9
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.1 – Not tested with the active version of WooCommerce

Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4 – 3.4.5 is available
WooSwipe: by Website Design – 1.1.6.6
WP All Import: by Soflyy – 3.4.9
WP Fastest Cache: by Emre Vona – 0.8.8.4
WP GDPR Compliance: by Van Ons – 1.4.2
WP All Import - User Import Add-On: by Soflyy – 1.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wbs_bundle (wbs_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Helium
Version: 5.4.23
Author URL: http://rockettheme.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: g5_helium/woocommerce/emails/customer-new-account.php

### sagepay ###

MCrypt: ❌ No
OpenSSL: ✔ Yes
OpenSSL Methods: ✔ Yes
PHP Max_Input_Vars: ✔ 5000
`
```
</details>

**Comment by claudiulodro** [comment] 2018-10-03 15:06
Hi there,
I was not able to reproduce this problem on a site running only WooCommerce and no other plugin. It looks to me most likely one of your plugins is modifying the data either when the order is being created or when the order information is being output. I recommend debugging it using [the self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/). If you can determine that the issue is caused by the WooCommerce core plugin and not one of your other active plugins post back and I'll reopen the issue. For now I'm closing this as non-reproducible. Thanks.

**Closed by claudiulodro** 2018-10-03 15:06 UTC
