### ISSUE TITLE
BUY NOW button appearing for only some customers but not working

### ISSUE THREAD

**Issue by Bloggeratlarge** [woocommerce/woocommerce#26504] opened 2020-05-14 00:55 UTC
**Describe the bug**
I have recently installed Woocommerce (actually I had a developer do it). Some customers have sent me screen shots showing a large blue BUY NOW button which sits above the ADD TO CART button. The BUY NOW button does not work and some have realised this and used the ADD TO CART.
I cannot see this BUY NOW button on any browser and neither can my developer.

**To Reproduce**
1. Go to 'https://www.bloggeratlarge.com/product/lucy-lou-beats-the-coronavirus/'
2. Scroll down the page past the description. I only see ADD TO CART.
4. Some customers have 2 buttons.
5. When those customers use BUY NOW they input their credit card details and then get an error message saying payment has not gone through. They can only buy if they use ADD TO CART first.
6. Why can I not see this button?
7. How can I ensure the payment goes through?

**Screenshots**

**Expected behavior**
I'd like to see where to access this button that does not show on my dashboard.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by tammullen** [comment] 2020-05-14 11:14
Hi @Bloggeratlarge 

Thank you for raising the issue. However, I can’t reproduce it on my end.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

It is likely your issue is due to a plugin or a theme that isn't default the WordPress theme, or Storefront.

However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.


**WordPress Environment**
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

**Comment by Bloggeratlarge** [comment] 2020-05-18 22:30
Hi Tam

Thanks for your reply. The thing is I can’t recreate this issue so disabling plugins won’t help me to see whether that fixes it as the BUY NOW button only appears on some customer’s screens. I was wondering if it was a known issue.

I’ll just make sure my plugins are kept updated and hope it somehow resolves itself.

Thanks
Megan
________________

P O Box 11865
Ellerslie
Auckland 1542
New Zealand

Ph: (+64) 021 777 770

www.bloggeratlarge.com
www.travelstore.co.nz
www.freedomroad.co.nz

**Comment by juliaamosova** [comment] 2020-05-20 18:17
Hi @Bloggeratlarge,

Thanks for the additional details. Sorry to hear you can't reproduce it on your end - it is a tricky one indeed. The most common cause of this kind of issue is a theme and plugins conflict. I understand that it is difficult to pinpoint it for you though. 

I can recommend monitoring the situation and work with a customer who experiences it further and find out from them what browser they are using and what kind of computer. You can then try to replicate the same using a service such as [Browserstack](https://www.browserstack.com/) - it is a library of all kinds of devices and operating systems that can be used for testing. 

In the meantime, I am closing this issue since it is not clear how to reproduce it. If you confirm the bug that is reproducible, please open the new issue.

**Closed by juliaamosova** 2020-05-20 18:17 UTC
Labels: can't reproduce, status: needs feedback
