### ISSUE TITLE
Coupons restrictions - exclude categories not working

### ISSUE THREAD

**Issue by smartelements** [woocommerce/woocommerce#26646] opened 2020-05-31 19:48 UTC
Since the update to Woocommerce 4.0.1 the excluded categories are still included with the percentage discount on the checkout page. I need to exclude whole categories from discounts of any kind. Please help. Thank you.

Best regards
Juergen
www.smart-elements.com

**Comment by juliaamosova** [comment] 2020-06-01 18:22
Hi @smartelements,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. I tested in both WooCommerce 4.0.1 and 4.1.1:

I have a dress product that belongs to the category `Dress`:

![dress1](https://user-images.githubusercontent.com/19143190/83440526-14e35c80-a413-11ea-9900-427d45dbdaba.jpg)

I have a coupon `cat-10` that is a Percentage discount of 10 excluding the category `Dress`:

![Screen Shot 2020-06-01 at 2 21 51 PM](https://user-images.githubusercontent.com/19143190/83440647-4a884580-a413-11ea-9359-1ddaa1a19636.png)

![dress2](https://user-images.githubusercontent.com/19143190/83440536-19a81080-a413-11ea-9f99-a3181d5bc9ce.jpg)

If I try to apply coupon `cat-10 on the Cart page, I am getting a message that I can't use that coupon for the `Dress` category as expected:

![dress3](https://user-images.githubusercontent.com/19143190/83440549-1e6cc480-a413-11ea-8627-6f61fcda7f1a.jpg)

Can you please confirm if you have done a theme and plugins conflict?

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-06-08 14:22
Hi @smartelements,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-06-08 14:22 UTC
Labels: can't reproduce, status: needs feedback
