### ISSUE TITLE
Out of stock filter not working

### ISSUE THREAD

**Issue by walkinverse** [woocommerce/woocommerce#23788] opened 2019-05-22 02:53 UTC
please refer to #23471 and #23416

The stock sort is still not working, even after updates.  The problem still persists even with notes the team left.  See images.  Not it shows items are NOT out of stock as out of stock when filtering.  And then some items are out of stock, it does not display.  

Again, same issue.  Previous tickets have a detailed explanation.  But the good news is, this is getting closer.  At least the count matches, but one item is incorrect. 

<img width="537" alt="Screenshot 2019-05-21 19 43 34" src="https://user-images.githubusercontent.com/42853036/58144069-e036a580-7c01-11e9-9e51-512249fcfe69.png">
<img width="497" alt="Screenshot 2019-05-21 19 43 59" src="https://user-images.githubusercontent.com/42853036/58144070-e036a580-7c01-11e9-8823-cf57ad324f0d.png">
<img width="996" alt="Screenshot 2019-05-21 19 44 32" src="https://user-images.githubusercontent.com/42853036/58144071-e036a580-7c01-11e9-9f56-99bb709f6ff8.png">

**Comment by kloon** [comment] 2019-05-22 07:02
@walkinverse can you please complete the template when opening the issue? We ask for that information for a reason, it helps aids us in debugging the issue. The issue was definitely resolved and confirmed by numerous users as being fixed.

Since you omitted to provide your debugging information it is really hard for us to know what the issue might be for you.

The product showing in stock, is that perhaps a variable product? Are some of the variations perhaps out of stock and others not?

Please attach your system status report, test with all plugins disabled and with your theme switched to a default one and we can take it from there.

**Comment by ajayghaghretiya** [comment] 2019-05-24 04:08
@walkinverse It's working fine for me. Checked numerous times but still not getting any issue with that.

It would be nice if you can check your database is updated with the latest version of WooCommerce or not. Upgrade your database and if you still facing the same issue then do provide your system status report and provide steps to reproduce the issue.

Thanks,

**Comment by kloon** [comment] 2019-05-27 09:29
Closing as there is no feedback and after numerous opened issues and requests for more information it just keeps getting ignored. Issue has been fixed and confirmed by numerous users.

@walkinverse please do not open another new issue, you can just comment on a closed one we will respond there if you provide the correct details as requested.

**Closed by kloon** 2019-05-27 09:29 UTC
Labels: status: needs feedback

**Comment by walkinverse** [comment] 2019-05-27 09:45
Sorry, thoughts I replied.  I followed the direction of the last commenter and it seems to have been fixed.

Thank you again for all your support and help!
