### ISSUE TITLE
Automatic purchase mailing error

### ISSUE THREAD

**Issue by rfigueroadiaz** [woocommerce/woocommerce#28634] opened 2020-12-20 00:53 UTC
Hi.

Since December 14, I have not received emails from woocommerce when a sale is made, a cancellation or any action that I have configured. That day from the HOSTING service I received a message saying that I exceeded the PHP email limit and the service was canceled for 24 hours. Today the service is already working correctly, but from woocommerce the emails are still not being sent. I have made changes to the emails, to evaluate if that is a problem, but with no email has it worked again.

Can you help me, please.

Thank you.
My name is Rodrigo

**Comment by juliaamosova** [comment] 2020-12-23 22:28
Hi @rfigueroadiaz,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-12-23 22:28 UTC
