### ISSUE TITLE
Individual reviews (comments) on products are missing key piece of structured data, resulting in single reproducible error

### ISSUE THREAD

**Issue by whereskarlo** [woocommerce/woocommerce#24950] opened 2019-10-31 23:33 UTC
**Describe the bug**
Reviews (which are comments on products) are missing structured data, resulting in errors in the google search console. The specific error states "One of offers or review or aggregateRating should be provided." This error appears on every individual review.

**To Reproduce**
1. Create a WooCommerce product (optional if you have one already)
2. Add a review (optional if you already have a product with review/s)
3. Go to 'https://search.google.com/structured-data/testing-tool'
4. Enter URL for a product with reviews
5. Scroll down to 'Reviews' on the report
6. See specified error

**Screenshots**
![review](https://user-images.githubusercontent.com/2850757/67991731-89b2a600-fc3a-11e9-912f-92416a233aa3.jpg)

Review is each individual review on the product. Since a review is a comment on the product, the comment is missing the type "One of offers or review or aggregateRating should be provided."

![review detail](https://user-images.githubusercontent.com/2850757/67991732-8a4b3c80-fc3a-11e9-92f0-0e848eaf31f6.jpg)

This product has one review, and thus one error for "One of offers or review or aggregateRating should be provided." 

![10 reviews](https://user-images.githubusercontent.com/2850757/67992142-efebf880-fc3b-11e9-9f13-7257d34ef5a3.jpg)

On products with 10 reviews, there are 10 errors. 

![10 review detail](https://user-images.githubusercontent.com/2850757/67992158-fc705100-fc3b-11e9-88bf-24a975bd8966.jpg)

Each comment (review) above is missing the structured data for "One of offers or review or aggregateRating should be provided." 

**Expected behavior**
Each comment (review) on products should have one of offers or review or aggregateRating provided.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://.co
Site address (URL): https://.co
WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.3.10-1+0~20191008.45+debian8~1.gbp365209
PHP Post Max Size: 128 MB
PHP Time Limit: 240
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.27-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: 
MaxMind GeoIP Database: ✔
Total Database Size: 81.35MB
Database Data Size: 51.54MB
Database Index Size: 29.81MB
woocommerce_sessions: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
woocommerce_order_items: Data: 0.42MB + Index: 0.16MB + Engine InnoDB
woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.00MB + Engine InnoDB
woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
be_product_alert_favorites: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
be_product_alert_favorites_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
be_product_alert_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
be_product_alert_signups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
commentmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
comments: Data: 3.52MB + Index: 1.94MB + Engine InnoDB
links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mpsl_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
mpsl_sliders_preview: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
mpsl_slides: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
mpsl_slides_preview: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
options: Data: 5.42MB + Index: 1.36MB + Engine InnoDB
postmeta: Data: 13.52MB + Index: 12.84MB + Engine InnoDB
posts: Data: 6.47MB + Index: 0.92MB + Engine InnoDB
responsive_menu: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
term_relationships: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
usermeta: Data: 6.52MB + Index: 6.75MB + Engine InnoDB
users: Data: 0.33MB + Index: 0.28MB + Engine InnoDB
wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfConfig: Data: 1.23MB + Index: 0.00MB + Engine InnoDB
wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfFileMods: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wfHits: Data: 2.02MB + Index: 0.23MB + Engine InnoDB
wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wfKnownFileList: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfLogins: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfNotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfStatus: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_arr_log: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wrd_discounts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wysija_campaign: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wysija_campaign_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wysija_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wysija_email: Data: 1.76MB + Index: 0.00MB + Engine MyISAM
wysija_email_user_stat: Data: 0.61MB + Index: 0.58MB + Engine MyISAM
wysija_email_user_url: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wysija_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wysija_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wysija_queue: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wysija_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wysija_url: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wysija_url_mail: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wysija_user: Data: 0.28MB + Index: 0.14MB + Engine MyISAM
wysija_user_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wysija_user_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wysija_user_list: Data: 0.04MB + Index: 0.04MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

BTCPay for WooCommerce: by BTCPay – 3.0.9 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Envato Market: by Envato – 2.0.3
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.9
Google XML Sitemaps: by Arne Brachhold – 4.1.0
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.5
Mailgun: by Mailgun – 1.7.1
Merchandiser Extender: by GetBowtied – 1.3.4
Redis Object Cache: by Till Krüss – 1.5.0
WordPress Users & WooCommerce Customers Import Export(BASIC): by WebToffee – 1.3.3
Open Graph and Twitter Card Tags: by Webdados – 2.2.7.1
Advanced Order Export For WooCommerce: by AlgolPlus – 3.0.3
WooCommerce Advanced Bulk Edit: by George Iron – 4.4.4-beta1 – Not tested with the active version of WooCommerce
WooCommerce Advanced Review Reminder: by kodemann.com – 2.2 – Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.6 – Not tested with the active version of WooCommerce
Bolder Fees for WooCommerce: by Bolder Elements – 1.5
WooCommerce Currency Converter: by WooCommerce – 1.6.15
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.14
WooCommerce Review for Discount: by WooCommerce – 1.6.9
WooCommerce Shipping Tracking: by Lagudi Domenico – 23.4 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2
WooCommerce Waitlist: by WooCommerce – 2.1.9
WooCommerce: by Automattic – 3.7.1
Wordfence Security: by Wordfence – 7.4.0

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

object-cache.php: Redis Object Cache Drop-In

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #10 - /buy/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: #134 - /terms-of-use/

### Theme ###

Name: Merchandiser Child
Version: 1.0
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Merchandiser
Parent Theme Version: 1.9.8
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: merchandiser/woocommerce/archive-product.php
merchandiser/woocommerce/cart/cart.php
merchandiser/woocommerce/checkout/form-checkout.php
merchandiser/woocommerce/checkout/form-pay.php
merchandiser/woocommerce/content-product.php
merchandiser/woocommerce/content-product_cat.php
merchandiser/woocommerce/content-single-product.php
merchandiser/woocommerce/loop/loop-end.php
merchandiser/woocommerce/loop/loop-start.php
merchandiser/woocommerce/loop/no-products-found.php
merchandiser/woocommerce/myaccount/form-login.php
merchandiser/woocommerce/product-searchform.php
merchandiser/woocommerce/single-product/product-image.php
merchandiser/woocommerce/single-product/product-thumbnails.php
merchandiser/woocommerce/single-product/rating.php
merchandiser/woocommerce/single-product.php


### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by Cyral** [comment] 2019-11-01 15:39
+1, also affected

Looks like Google recently changed some validation for the structured data: https://support.google.com/webmasters/answer/6211453#rich_result_reports

**Comment by marksda1** [comment] 2019-11-05 20:03
Also having this issue. I allow comments without star rating (star rating disabled). I was trying to figure this one out and I think maybe Google is looking for reviewcount and none is specified. Whatever it is, it's only affecting (so far) products that have reviews (essentially comments). If I use the structured data testing tool on products that have no reviews, I don't get any error.

**Comment by whereskarlo** [comment] 2019-11-05 20:09
I noticed @mikejolley mentioned earlier that a similar problem was resolved. Hopefully it is clear that this issue differs from the previous issue with the same nature that was fixed with an update. @marksda1 I can confirm the error only appears on products with comments (reviews). I have run the structured data testing tool on products without reviews and there are no errors then.

**Comment by marksda1** [comment] 2019-11-05 21:22
I saw there was a Woocommerce update I hadn't installed and I had hoped maybe this was addressed in it. But I've installed and cleared out my cache plugin. I am still getting this same error message.

**Comment by gregbast1994** [comment] 2019-11-07 17:33
+1

4 errors on https://themes.woocommerce.com/storefront/product/flying-ninja/

**Comment by khag7** [comment] 2019-11-08 06:06
Someone please correct me if I'm wrong here, but it appears Google wants all the product structured data to appear inside the review object as well. So instead of just naming the product in the review, they actually want all the AggregatedOffers as well.

**Comment by Zohaib321** [comment] 2019-11-11 21:26
Any ETA on when this issue will be fixed?

**Comment by juliaamosova** [comment] 2019-11-11 21:55
Thank you for reporting @whereskarlo. This is a duplicate of https://github.com/woocommerce/woocommerce/issues/24862 and we have a PR to fix it: https://github.com/woocommerce/woocommerce/pull/24278 - it will be released as soon as possible. 

@khag7 thank you for your PR - I will reference it in https://github.com/woocommerce/woocommerce/pull/24278. 

Closing this issue since it already has a PR in place - please continue to discuss in https://github.com/woocommerce/woocommerce/pull/24278.

**Closed by juliaamosova** 2019-11-11 21:55 UTC

**Comment by claudiosanches** [comment] 2019-11-12 14:15
The correct Pull Request to fix this issue is https://github.com/woocommerce/woocommerce/pull/24278

**Comment by khag7** [comment] 2019-11-12 16:36
Agreed, thank you for setting me straight. I had "a" solution but not "the"solution. I didn't understand that the reviews should've been nested within the product.
