### ISSUE TITLE
Wordpress.org dashboard freezes and can't move boxes or change screen settings

### ISSUE THREAD

**Issue by RYouReadytoOrganize** [woocommerce/woocommerce#22219] opened 2018-12-13 19:41 UTC
WooCommerce plugin freezes my WordPress.org admin dashboard. Can't move boxes or change screen settings. I have disabled all plugins and themes and it is caused by WooCommerce.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.

**Comment by kloon** [comment] 2018-12-14 10:18
I am not able to reproduce this locally with just WooCommerce and a default theme like Twentyseventeen or Storefront.

Can you please test again by disabling all your plugins except WooCommerce and switching your theme to Twentyseventeen or Storefront and then test again. You can then enable the plugins one by one testing inbetween to see which plugin is causing the conflict, then last you can switch your theme back and test again.

It is possible that either your theme or a plugin is causing a conflict with WooCommerce causing the freeze.

I am going to close this issue now, but if you can provide clear steps to reproduce this then I will gladly reopen and continue to take a look, but since I am unable to replicate it with the information you provided there is nothing much I can do.

**Closed by kloon** 2018-12-14 10:18 UTC

**Comment by RYouReadytoOrganize** [comment] 2018-12-14 13:03
To clarify. I already followed these steps completely and WooCommerce is the problem. I also repeated these instructions again and it is not my theme. WooCommerce is hanging up my Dashboard.

Rebecca Phillips

Rebecca Phillips, MSW

ryoureadytoorganize.com

 

 <https://www.ryoureadytoorganize.com/> 

 

My Amazon Store <https://www.amazon.com/shop/ryoureadytoorganize?ref=ac_lc_hm_vp> 

 

 <https://www.facebook.com/ryoureadytoorganize/>     <https://www.instagram.com/ryoureadytoorganize/>    <https://www.pinterest.com/ryoureadytoorganize/>    <https://www.youtube.com/channel/UCPbHByZMs5YgUe78ekUEHMw>
