### ISSUE TITLE
Price doesn´t fit properly when is variable

### ISSUE THREAD

**Issue by eldietista** [woocommerce/woocommerce#24008] opened 2019-06-26 11:34 UTC
I have on my homepage 2 columns, each one with product list.
One of them has a variable price from X to Y.
For that product, margins don´t allow to show the product name properly and content is overlayed over the price.

1. Go to https://www.eldietista.online/
2. Scroll down to "Dietas populares:"
3. See second item on left column:  "Dieta mensual para..."

Attached screenshot

**WordPress Environment**
Using WP 5.2.2. and Woocommerce 3.6.4.

Report:
`
### WordPress Environment ###

WordPress address (URL): https://www.eldietista.online
Site address (URL): https://www.eldietista.online
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.19
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.60-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wvgh3q3z_
MaxMind GeoIP Database: ✔
Tamaño total de la base de datos: 84.72MB
Tamaño de los datos de la base de datos: 76.41MB
Tamaño del índice de la base de datos: 8.31MB
wvgh3q3z_woocommerce_sessions: Datos: 1.02MB + Índice: 0.02MB
wvgh3q3z_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB
wvgh3q3z_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_woocommerce_order_itemmeta: Datos: 0.08MB + Índice: 0.06MB
wvgh3q3z_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB
wvgh3q3z_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_commentmeta: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_comments: Datos: 1.08MB + Índice: 0.83MB
wvgh3q3z_connections: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_address: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_date: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_email: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_link: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_messenger: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_meta: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_phone: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_social: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_terms: Datos: 0.00MB + Índice: 0.01MB
wvgh3q3z_connections_term_meta: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_term_relationships: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_connections_term_taxonomy: Datos: 0.00MB + Índice: 0.00MB
wvgh3q3z_duplicator_packages: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_edd_customers: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_ewwwio_images: Datos: 0.30MB + Índice: 0.27MB
wvgh3q3z_failed_jobs: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_geodir_attachments: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_geodir_countries: Datos: 0.06MB + Índice: 0.00MB
wvgh3q3z_geodir_custom_fields: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_geodir_custom_sort_fields: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_geodir_gd_place_detail: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_geodir_post_icon: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_geodir_post_review: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_hustle_modules: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_hustle_modules_meta: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_itsec_distributed_storage: Datos: 3.02MB + Índice: 0.02MB
wvgh3q3z_itsec_fingerprints: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_itsec_geolocation_cache: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_itsec_lockouts: Datos: 0.02MB + Índice: 0.08MB
wvgh3q3z_itsec_logs: Datos: 6.02MB + Índice: 0.42MB
wvgh3q3z_itsec_temp: Datos: 0.02MB + Índice: 0.06MB
wvgh3q3z_layerslider: Datos: 0.14MB + Índice: 0.00MB
wvgh3q3z_learnpress_question_answermeta: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_links: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_litespeed_img_optm: Datos: 0.02MB + Índice: 0.09MB
wvgh3q3z_litespeed_optimizer: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_magnimeiosreferences: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_ms_snippets: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_options: Datos: 4.39MB + Índice: 1.13MB
wvgh3q3z_postmeta: Datos: 26.03MB + Índice: 2.14MB
wvgh3q3z_posts: Datos: 18.05MB + Índice: 0.48MB
wvgh3q3z_prli_clicks: Datos: 0.05MB + Índice: 0.19MB
wvgh3q3z_prli_groups: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_prli_links: Datos: 0.02MB + Índice: 0.16MB
wvgh3q3z_prli_link_metas: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_queue: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_ratings: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_redirection_404: Datos: 0.02MB + Índice: 0.06MB
wvgh3q3z_redirection_groups: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_redirection_items: Datos: 0.02MB + Índice: 0.08MB
wvgh3q3z_redirection_logs: Datos: 0.02MB + Índice: 0.08MB
wvgh3q3z_responsive_menu: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_snippets: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_termmeta: Datos: 0.05MB + Índice: 0.03MB
wvgh3q3z_terms: Datos: 0.08MB + Índice: 0.09MB
wvgh3q3z_term_relationships: Datos: 0.11MB + Índice: 0.09MB
wvgh3q3z_term_taxonomy: Datos: 0.09MB + Índice: 0.06MB
wvgh3q3z_tm_taskmeta: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_tm_tasks: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_usermeta: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_users: Datos: 0.02MB + Índice: 0.05MB
wvgh3q3z_w3tc_cdn_pathmap: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_w3tc_cdn_queue: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_wc_download_log: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB
wvgh3q3z_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB
wvgh3q3z_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB
wvgh3q3z_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_wfBlockedIPLog: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wfBlocks7: Datos: 0.02MB + Índice: 0.05MB
wvgh3q3z_wfConfig: Datos: 2.25MB + Índice: 0.00MB
wvgh3q3z_wfCrawlers: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wfFileChanges: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wfFileMods: Datos: 7.52MB + Índice: 0.00MB
wvgh3q3z_wfHits: Datos: 1.02MB + Índice: 0.05MB
wvgh3q3z_wfHoover: Datos: 0.47MB + Índice: 0.08MB
wvgh3q3z_wfIssues: Datos: 0.03MB + Índice: 0.06MB
wvgh3q3z_wfKnownFileList: Datos: 2.52MB + Índice: 0.00MB
wvgh3q3z_wfLiveTrafficHuman: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_wfLocs: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wfLogins: Datos: 0.13MB + Índice: 0.03MB
wvgh3q3z_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_wfls_settings: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wfNotifications: Datos: 0.08MB + Índice: 0.00MB
wvgh3q3z_wfPendingIssues: Datos: 0.02MB + Índice: 0.06MB
wvgh3q3z_wfReverseCache: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wfSNIPCache: Datos: 0.02MB + Índice: 0.05MB
wvgh3q3z_wfStatus: Datos: 0.17MB + Índice: 0.13MB
wvgh3q3z_wfTrafficRates: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wpbdp_form_fields: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_wpbdp_listings: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wpbdp_logs: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wpbdp_payments: Datos: 0.02MB + Índice: 0.03MB
wvgh3q3z_wpbdp_plans: Datos: 0.02MB + Índice: 0.00MB
wvgh3q3z_wpml_mails: Datos: 0.03MB + Índice: 0.00MB
wvgh3q3z_yoast_seo_links: Datos: 0.02MB + Índice: 0.02MB
wvgh3q3z_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB

### Post Type Counts ###

amn_mi-lite: 1
attachment: 357
avia_framework_post: 84
download: 1
edd_payment: 2
lp_course: 1
lp_lesson: 10
lp_question: 50
lp_quiz: 1
mc4wp-form: 1
nav_menu_item: 70
oembed_cache: 12
page: 44
popup_theme: 6
post: 35
product: 42
product_variation: 2
revision: 15
saswp: 2
scheduled-action: 1314
schema: 3
shop_coupon: 3
shop_order: 74
tablepress_table: 12
wpbdp_listing: 1
ywsbs_subscription: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Akismet Anti-Spam: por Automattic – 4.1.2
AMP: por Colaboradores con el proyecto AMP – 1.2.0
iThemes Security: por iThemes – 7.4.0
Code Snippets: por Shea Bunge – 2.13.3
Connections Business Directory: por Steven A. Zahm – 8.44.1
Duplicator: por Snap Creek – 1.3.14
Edit Author Slug: por Brandon Allen – 1.6.0
Glue for Yoast SEO & AMP: por Joost de Valk – 0.4.3
Google Analytics Dashboard for WP (GADWP): por ExactMetrics – 5.3.8
Mailchimp for WooCommerce: por Mailchimp – 2.1.15 – No probado con la versión activa de WooCommerce
MailChimp for WordPress: por ibericode – 4.5.2
OneSignal Push Notifications: por OneSignal – 1.17.5
Perfect WooCommerce Brands: por Alberto de Vera Sevilla – 1.7.6
reSmush.it Image Optimizer: por reSmush.it – 0.1.22
Title and Nofollow For Links: por WPKube – 1.07
W3 Total Cache: por Frederick Townes – 0.9.7.5
WooCommerce Admin: por WooCommerce – 0.14.0
WooCommerce Google Analytics Integration: por WooCommerce – 1.4.9
WooCommerce: por Automattic – 3.6.4
Wordfence Security: por Wordfence – 7.3.4
Yoast SEO: por Equipo Yoast – 10.1.3 – No probado con la versión activa de WooCommerce
WP Mail SMTP: por WPForms – 1.4.2
WP-PostRatings: por Lester 'GaMerZ' Chan – 1.86.2
WP SEO Structured Data Schema: por WPSEMPlugins – 2.5.9
YITH WooCommerce Subscription: por YITH – 1.3.3

### Inactive Plugins (9) ###

Accelerated Mobile Pages: por Ahmed Kaludi
Mohammed Kaludi – 0.9.97.60

AMP WooCommerce: por Mohammed Kaludi – 0.4 – No probado con la versión activa de WooCommerce
Custom Product Tabs for WooCommerce: por YIKES
Inc. – 1.6.10

Easy Table of Contents: por Steven A. Zahm – 1.7
PWA for WP: por Magazine3 – 1.1
Super Socializer: por Team Heateor – 7.12.30
WooCommerce Stripe Gateway: por WooCommerce – 4.2.1
WP Rollback: por Impress.org – 1.6
YITH WooCommerce Questions and Answers: por YITH – 1.1.8

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: ❌ Página sin definir
Carrito: #15 - /carro-de-la-compra
Finalizar compra: #16 - /finalizar-compra
Mi cuenta: #17 - /mi-cuenta
Términos y condiciones: #969 - /aviso-legal/condiciones-de-dietas-y-planes-online

### Theme ###

Name: Enfold
Version: 4.5.7
Author URL: https://kriesi.at
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1.306
Oldest: 2019-05-30 11:15:43 +0200
Newest: 2019-06-26 12:41:48 +0200

Pending: 3
Oldest: 2019-06-26 13:41:48 +0200
Newest: 2019-06-27 11:17:18 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 5
Oldest: 2019-05-31 09:35:15 +0200
Newest: 2019-06-16 13:33:56 +0200

![eldietista](https://user-images.githubusercontent.com/52242580/60176583-09f17680-9817-11e9-95b5-3f4725ae113d.gif)

**Comment by rodrigoprimo** [comment] 2019-06-27 14:17
This is likely an issue with your theme, Enfold, and not WooCommerce core. You could try contacting the theme developer or its support forum. Closing this issue for now. Please leave a comment if I missed something and you believe the problem is caused by WooCommerce and I will take a second look. Thanks.

**Closed by rodrigoprimo** 2019-06-27 14:17 UTC
