### ISSUE TITLE
[E2E] Test WooCommerce version upgrades via e2e tests

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#25957] opened 2020-03-17 19:40 UTC
Find a way to automate WooCommerce version upgrades via e2e tests. For example, from 3.6 to 4.0 or from 4.0 to 4.1. Perhaps using Jurrasic Ninja sites or Local by Flywheel.

**Comment by rrennick** [comment] 2021-05-13 18:08
This looks like it's a duplicate of #27881.

**Closed by rrennick** 2021-05-13 18:08 UTC
Labels: category: E2E, category: tools, package: e2e-core-tests, package: e2e-utils
