### ISSUE TITLE
Authorize Webhook URL data

### ISSUE THREAD

**Issue by hanielyassir** [woocommerce/woocommerce#26682] opened 2020-06-03 14:05 UTC
Hello,

I am trying to fetch webhook order creation in my woocommerce instance, the payload message is coming as
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot view this resource.","data":{"status":401},"created_at":"T","updated_at":"T","cancelled_at":"T"}

after some research I found that I can add the delivery URL as follows:

https://username:password@link.com

I tried this and I also tried to create a user in REST API and update the URL as https://user:secret@link.com

but both did not work and after checking the logs of webhooks it was showing that URL is not valid.

Thank you for the support

**Comment by juliaamosova** [comment] 2020-06-03 14:25
Hi @hanielyassir,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-06-03 14:25 UTC
