### ISSUE TITLE
[GlobalStep - 4.1 RC]: Delete option is not available to remove category from Products.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26269] opened 2020-04-23 17:39 UTC
Steps to Reproduce:
1. Create a test site using JN. 
2. Complete initial screens.
3. Add a new product.
4. Add a new category.
5. Observe that to delete category delete option is not available.

Actual Result:
Delete option is not available to remove the category from Products.

Expected Result:
Delete option should be provided to delete a category.

**Comment by claudiosanches** [comment] 2020-05-05 14:23
WooCommerce relies on the WordPress interface, so if you need to manage categories you need to go to Products > Categories, on products there's only a widget help you select and create new categories fast.
Currently we are studying of how to improve our administrative interfaces, so probably it will get improved in the future.

I'm closing since is the expected behavior. Thanks for submitting this report.

**Closed by claudiosanches** 2020-05-05 14:23 UTC
Labels: won't fix
