### ISSUE TITLE
Missing Product Export Data - Woo 4.4.1

### ISSUE THREAD

**Issue by Zedys** [woocommerce/woocommerce#27458] opened 2020-08-24 00:49 UTC
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After updating to Woo 4.4.1, the following issues are present:

When trying to export products from Products > Export > All products (include custom meta), it is only exporting 17/96 products in the store.

If I use the Product CSV Import Export (BASIC) plugin, then it exports all product data.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://samandsage.co.za
Site address (URL): https://samandsage.co.za
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.9
PHP Post Max Size: 1 GB
PHP Time Limit: 1500
PHP Max Input Vars: 2000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-log-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 19.91MB
Database Data Size: 17.01MB
Database Index Size: 2.90MB
wp_woocommerce_sessions: Data: 1.20MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.30MB + Index: 0.17MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.07MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.07MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.11MB + Index: 0.06MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mclean_refs: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_mclean_scan: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 4.87MB + Index: 0.19MB + Engine MyISAM
wp_postmeta: Data: 4.95MB + Index: 1.22MB + Engine MyISAM
wp_posts: Data: 3.18MB + Index: 0.31MB + Engine MyISAM
wp_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_relationships: Data: 0.04MB + Index: 0.09MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.09MB + Index: 0.06MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_w3tc_cdn_pathmap: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gc_activity: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gc_cards: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gpf_google_taxonomy: Data: 0.89MB + Index: 0.00MB + Engine MyISAM
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_indexable: Data: 0.79MB + Index: 0.33MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

attachment: 399
br_notice: 1
custom_css: 1
customize_changeset: 85
nav_menu_item: 206
option-tree: 1
page: 20
post: 10
product: 103
product_variation: 207
revision: 491
shop_coupon: 1506
shop_order: 131
shop_order_refund: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

WooCommerce Custom Related Products Pro: by WPCodelibrary – 1.3.0 – Installed version not tested with active version of WooCommerce 4.4.1
Contact Form 7: by Takayuki Miyoshi – 5.2.1
Duplicate Page: by mndpsingh287 – 4.2
Facebook for WooCommerce: by Facebook – 1.11.4 – Installed version not tested with active version of WooCommerce 4.4.1
Jetpack by WordPress.com: by Automattic – 8.8.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.3.0
North - Required Plugin: by fuelthemes – 1.3.1
WooCommerce Payflex Gateway: by Payflex – 1.9 – Installed version not tested with active version of WooCommerce 4.4.1
Product CSV Import Export (BASIC): by WebToffee – 1.8.2 – Installed version not tested with active version of WooCommerce 4.4.1
Product XML Feeds for WooCommerce Pro: by WPWhale – 1.9.1 – Installed version not tested with active version of WooCommerce 4.4.1
CM Commerce for WooCommerce: by Campaign Monitor – 1.6.0 – Installed version not tested with active version of WooCommerce 4.4.1
Slider Revolution: by ThemePunch – 6.2.22
W3 Total Cache: by BoldGrid – 0.14.4
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.3.9 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Checkout Add-Ons: by SkyVerge – 2.3.0 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Ozow Gateway: by <a href="https://Ozow.com" />Ozow</a> – 1.0.0.0 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Gift Cards: by SomewhereWarm – 1.3.5 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.11 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayFast Gateway: by WooCommerce – 1.4.15 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.6.0
WooCommerce Google Product Feed: by Ademti Software Ltd. – 8.1.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce: by Automattic – 4.4.1
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO: by Team Yoast – 14.8
Smush Pro: by WPMU DEV – 3.6.3
WPMU DEV Dashboard: by WPMU DEV – 4.10.0
YITH WooCommerce Wishlist: by YITH – 3.0.13

### Inactive Plugins (6) ###

Classic Editor: by WordPress Contributors – 1.6
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Media Cleaner: by Jordy Meow – 6.0.3
Product Reviews Import Export (Basic): by WebToffee – 1.3.8 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PDF Invoice: by RightPress – 3.2.1 – Installed version not tested with active version of WooCommerce 4.4.1
WP Maintenance Mode: by Designmodo – 2.2.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #505 - /cart/
Checkout: #7 - /checkout/
My account: #506 - /my-account/
Terms and conditions: #579 - /terms-and-conditions/

### Theme ###

Name: North Child Theme
Version: 1.0.0
Author URL: http://themeforest.net/user/fuelthemes
Child Theme: ✔
Parent Theme Name: North
Parent Theme Version: 5.4.4.2
Parent Theme Author URL: http://themeforest.net/user/fuelthemes
WooCommerce Support: ✔

### Templates ###

Overrides: north-wp/woocommerce/archive-product.php
north-wp/woocommerce/cart/cart-empty.php
north-wp/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 4.4.0
north-wp/woocommerce/checkout/form-checkout.php
north-wp/woocommerce/checkout/form-coupon.php
north-wp/woocommerce/checkout/form-login.php
north-wp/woocommerce/content-product.php
north-wp/woocommerce/content-product_cat.php
north-wp/woocommerce/content-single-product.php
north-wp/woocommerce/global/wrapper-end.php
north-wp/woocommerce/global/wrapper-start.php
north-wp/woocommerce/loop/loop-end.php
north-wp/woocommerce/loop/loop-start.php
north-wp/woocommerce/myaccount/form-login.php
north-wp/woocommerce/myaccount/navigation.php
north-wp/woocommerce/product-searchform.php
north-wp/woocommerce/single-product/add-to-cart/variable.php
north-wp/woocommerce/single-product/product-image.php
north-wp/woocommerce/single-product/product-thumbnails.php
north-wp/woocommerce/single-product/tabs/tabs.php
north-wp/woocommerce/single-product-reviews.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce Google Product Feed fields ###

Product description: Main product description (full preferred) plus variation description.
Availability: Defaults to "in stock".
Brand: Defaults to "Sam & Sage".
Product Type: Pre-populates from product_cat taxonomy.
Google Product Category: Defaults to "Apparel & Accessories > Clothing > Baby & Toddler Clothing".
Gender: Defaults to "unisex".
Age Group: 
Colour: Pre-populates from pa_colour taxonomy.
Size: Pre-populates from pa_size taxonomy.
Size system: 
Bing Category: Defaults to "Baby & Children's Clothing". Pre-populates from product_cat taxonomy.

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No
debug_key: 1a57c9ec-fe8b-4147-a321-bb0600a19ee7

### Gift Cards ###

Database Version: 1.3.5
Loopback Test: ✔
Task Queueing Test: ✔

### Action Scheduler ###

Complete: 560
Oldest: 2020-08-06 17:21:40 +0000
Newest: 2020-08-24 00:19:42 +0000

Pending: 1
Oldest: 2020-08-24 00:34:42 +0000
Newest: 2020-08-24 00:34:42 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-08-24 19:10
Hi @Zedys,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I have 724 products on one of my test sites and all of them were exported using built-in WooCommerce product exporter:

![export](https://user-images.githubusercontent.com/19143190/91085512-8fd7a000-e61b-11ea-80c2-66e205bd3512.jpg)

![export2](https://user-images.githubusercontent.com/19143190/91085520-949c5400-e61b-11ea-86b9-9bc1128e1af8.jpg)

I made sure to select `Yes, export all custom meta` option during export:

![export3](https://user-images.githubusercontent.com/19143190/91085621-be557b00-e61b-11ea-923d-e15c544a3b33.jpg)

Can you please confirm if you tested the export with only WooCommerce activated on the site?

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-09-15 16:42
Hi @Zedys,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-09-15 16:42 UTC
Labels: status: needs feedback
