### ISSUE TITLE
Woocomerce uniqe order item export with total orderd quantity by different customer

### ISSUE THREAD

**Issue by Tamim-ul-hasan** [woocommerce/woocommerce#29581] opened 2021-04-03 11:36 UTC
Anyone, please help me. I need a plugin or code that can export a list of unique products with variations ordered by different customers.
Also, the total quantity of a single product ordered for a period of time (like one day or period like 3 April 2021 to 6 April 2021). 
The attached image illustrates the phenomena. 
A lot of thanks and gratitude in advance.
![Uniqe Oder export (1)](https://user-images.githubusercontent.com/59260169/113477358-105c5a00-94a3-11eb-8b70-55f35d0ac50a.png)

**Comment by zhongruige** [comment] 2021-04-09 19:56
Hi @Tamim-ul-hasan,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code and plugin related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code and plugin questions. I did do a quick search, and you might be able to check this plugin and see if it has the features you're looking for: [Products & Order Export for WooCommerce](https://wordpress.org/plugins/export-woocommerce/). Please contact the author of the plugin directly for further questions.

For custom code related questions, the best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel.

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by zhongruige** 2021-04-09 19:56 UTC
