### ISSUE TITLE
Fatal error... Community Builder Theme, bbPress, Woocommerce

### ISSUE THREAD

**Issue by yungaro** [woocommerce/woocommerce#26916] opened 2020-07-01 03:19 UTC
I have a wordpress website with just a few installed plugins.
This is the message I get when trying to go to the forums page:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function WC_Template_Loader::unsupported_theme_title_filter(), 1 passed in /home1/yungaro/fenix.ml/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /home1/yungaro/fenix.ml/wp-content/plugins/woocommerce/includes/class-wc-template-loader.php:408 Stack trace: #0 /home1/yungaro/fenix.ml/wp-includes/class-wp-hook.php(287): WC_Template_Loader::unsupported_theme_title_filter('Foros') #1 /home1/yungaro/fenix.ml/wp-includes/plugin.php(206): WP_Hook->apply_filters('Foros', Array) #2 /home1/yungaro/fenix.ml/wp-content/plugins/bbpress/includes/core/theme-compat.php(561): apply_filters('the_title', 'Foros') #3 /home1/yungaro/fenix.ml/wp-includes/class-wp-hook.php(287): bbp_template_include_theme_compat('/home1/yungaro/...') #4 /home1/yungaro/fenix.ml/wp-includes/plugin.php(206): WP_Hook->apply_filters('/home1/yungaro/...', Array) #5 /home1/yungaro/fenix.ml/wp-content/plugins/bbpress/includes/core/sub-actions.php(477): apply_filters('bbp_template_in...', in /home1/yungaro/fenix.ml/wp-content/plugins/woocommerce/includes/class-wc-template-loader.php on line 408

the forums page was working ok untill I installed the woocommerce plugin.

This is the website state report

`
### WordPress Environment ###

WordPress address (URL): http://fenix.ml
Site address (URL): http://fenix.ml
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.14 - Recomendamos usar la versión 7.2 o superior de PHP para un mayor rendimiento y seguridad. Cómo actualizar tu versión de PHP
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: wp_
Tamaño total de la base de datos: 0.90MB
Tamaño de los datos de la base de datos: 0.72MB
Tamaño del índice de la base de datos: 0.18MB
wp_woocommerce_sessions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_order_items: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_order_itemmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_actionscheduler_actions: Datos: 0.00MB + Índice: 0.02MB + Motor MyISAM
wp_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_actionscheduler_logs: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_activity: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_bp_activity_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_friends: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_groups: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_groups_groupmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_groups_members: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_invitations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_messages_messages: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_messages_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_messages_notices: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_messages_recipients: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_notifications: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_notifications_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_user_blogs: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_user_blogs_blogmeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_bp_xprofile_data: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_xprofile_fields: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_bp_xprofile_groups: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_bp_xprofile_meta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_commentmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_comments: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_mpp_logs: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_options: Datos: 0.69MB + Índice: 0.04MB + Motor MyISAM
wp_postmeta: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wp_posts: Datos: 0.02MB + Índice: 0.01MB + Motor MyISAM
wp_signups: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_termmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_terms: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_term_relationships: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_term_taxonomy: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_usermeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_users: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_wc_admin_notes: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_admin_note_actions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_category_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_customer_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_download_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_order_coupon_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_order_product_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_order_stats: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_product_meta_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM

### Post Type Counts ###

attachment: 1
bp-email: 15
customize_changeset: 1
forum: 1
nav_menu_item: 12
page: 14
post: 2
revision: 6

### Security ###

Secure connection (HTTPS): ❌
					Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Advanced WordPress Reset: por Younes JFR. – 1.1.0
bbPress: por Los colaboradores de bbPress – 2.6.5
BuddyPress: por La Comunidad de BuddyPress – 6.1.0
MediaPress: por BuddyDev – 1.5.0
WooCommerce: por Automattic – 4.2.2

### Inactive Plugins (33) ###

Admin Menu Editor: por Janis Elsts – 1.9.5
Akismet Anti-Spam: por Automattic – 4.1.6
AutomatorWP: por AutomatorWP – 1.1.4
AutomatorWP - bbPress integration: por AutomatorWP – 1.0.1
AutomatorWP - H5P integration: por AutomatorWP – 1.0.1
AutomatorWP - LearnPress integration: por AutomatorWP – 1.0.0
Bstone Light: por Stack Themes – 1.0.5
BuddyCommerce: por BuddyDev – 1.0.2 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.2
BuddyPress Default Data: por slaFFik – 1.3.0
BuddyPress Emoji: por BuddyDev – 1.0.2
BuddyPress Giphy: por BuddyDev – 1.0.1
BuddyPress Xprofile Custom Field Types: por BuddyDev – 1.1.5
CPT-onomies: Easiest way to create Custom Post Types: por hypestudio,dejanmarkovic,freemius,nytogroup – 1.4.0
Custom Post Type, Tag, Category and Taxonomy Builder: por WP Digits – 1.2.0
Custom post types: por Andrea De Giovine – 2.1.13
EditorsKit: por Jeffrey Carandang – 1.29.1
Gutenberg Blocks - Gutentor Page Builder for Gutenberg: por Gutentor – 2.1.5
Gutenberg Page Builder - Kioken Blocks: por Kioken Theme – 1.3.1
GutenBooster Addons: por Kioken Theme – 1.0.0
Gutenslider — The last WordPress slider you will ever need.: por eedee – 4.0.4
H5P: por Joubel – 1.15.0
Jetpack by WordPress.com: por Automattic – 8.6.1
Kadence Blocks - Gutenberg Page Builder Toolkit: por Kadence WP – 1.8.5
Lazy Blocks: por nK – 2.0.9
LearnPress: por ThimPress – 3.2.7.2
LearnPress - bbPress Integration: por ThimPress – 3.0.3
LearnPress - BuddyPress Integration: por ThimPress – 3.0.5
Pay For Post with WooCommerce: por Pramadillo – 2.5.7 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.2
Simple Page Ordering: por Jake Goldman
10up – 2.3.4

Stackable - Gutenberg Blocks: por Gambit Technologies
Inc – 2.6.1

Wicked Folders: por Wicked Plugins – 2.17.2
WooCommerce Services: por Automattic – 1.23.2
YellowPencil: por WaspThemes – 7.3.1

### Must Use Plugins (1) ###

Endurance Page Cache: por Mike Hansen – 2.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #45 - /tienda/
Carrito: #47 - /carrito/
Finalizar compra: #49 - /finalizar-compra/
Mi cuenta: #51 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Community Builder
Version: 2.0.3
Author URL: https://buddydev.com
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ❌ No declarada

### Templates ###

Overrides: community-builder/woocommerce/loop/pagination.php

### Action Scheduler ###

Completo: 1
Oldest: 2020-07-01 03:09:17 +0000
Newest: 2020-07-01 03:09:17 +0000

`

**Comment by tammullen** [comment] 2020-07-02 12:52
Hi @yungaro 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-07-13 21:45
Hi @yungaro,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-07-13 21:45 UTC
Labels: status: needs feedback
