### ISSUE TITLE
Dismiss X in product gallery allowing click of elements beneath

### ISSUE THREAD

**Issue by Nemi5150** [woocommerce/woocommerce#27643] opened 2020-09-10 16:47 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When you click on the zoom icon on a product page, it launches a zommable image gallery. In the top right corner there is an X to close the gallery. When logged into Wordpress as admin, there is a control in a bar right under this X to edit the admin user. 

When clicking on the X in the upper right it does dismiss the gallery, but it then allows the click of the underlying user icon and the page is redirected to the Wordpress edit user page. 

**Expected behavior**
Clicking the X should dismiss the zoomable gallery, but it should consume the click event and not allow it to propagate to the underlying elements. 

**Actual behavior**
The click even appears to be allowed to transfer to underlying elements. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to a product with multiple image in the gallery while logged in as Wordpress admin
2. Click on the zoom magnifying glass icon in the upper right of the image
3. Click on the X link to dismiss the popup gallery

**Screenshots**
None

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://cs.dev.cc
Site address (URL): https://cs.dev.cc
WC Version: 4.5.1
REST API Version: ✔ 4.5.1
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Win32) OpenSSL/1.1.1a PHP/7.3.1
PHP Version: 7.3.1
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.61.1
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.1
WC Database Prefix: wp_
Total Database Size: 82.73MB
Database Data Size: 63.63MB
Database Index Size: 19.10MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.41MB + Index: 0.30MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.07MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.07MB + Engine MyISAM
wp_auction_bids: Data: 0.55MB + Index: 1.08MB + Engine MyISAM
wp_auction_watchlist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cc_abandoned_checkouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.39MB + Index: 0.45MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_entry: Data: 0.63MB + Index: 0.06MB + Engine MyISAM
wp_gf_entry_meta: Data: 1.16MB + Index: 0.96MB + Engine MyISAM
wp_gf_entry_notes: Data: 0.22MB + Index: 0.07MB + Engine MyISAM
wp_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_meta: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_view: Data: 0.19MB + Index: 0.09MB + Engine MyISAM
wp_layerslider: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_layerslider_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.50MB + Index: 0.17MB + Engine InnoDB
wp_postmeta: Data: 13.52MB + Index: 7.03MB + Engine InnoDB
wp_posts: Data: 7.52MB + Index: 0.72MB + Engine InnoDB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.44MB + Index: 0.80MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_rg_zapier: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_users: Data: 0.25MB + Index: 0.27MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.09MB + Index: 0.09MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_wc_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.07MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 12.13MB + Index: 0.02MB + Engine MyISAM
wp_yoast_indexable: Data: 2.52MB + Index: 0.42MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.17MB + Index: 0.28MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.23MB + Index: 0.23MB + Engine MyISAM

### Post Type Counts ###

attachment: 2055
condition_group: 1
custom_css: 1
envira: 1
fusion_element: 9
fusion_icons: 2
fusion_template: 1
iwp_log: 208
nav_menu_item: 10
ngg_gallery: 79
ngg_pictures: 585
page: 30
post: 35
product: 594
revision: 303
shop_order: 446
shop_order_refund: 3
sidebar: 1
slide: 11
slider_responsive: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Query Monitor: by John Blackbourn – 3.6.4
Gravity Forms: by Gravity Forms – 2.4.20
Constant Contact + WooCommerce: by Constant Contact – 1.3.2 – Installed version not tested with active version of WooCommerce 4.5.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 3.2.5
Error Log Monitor: by Janis Elsts – 1.6.11
Avada Builder: by ThemeFusion – 3.0.2
Avada Core: by ThemeFusion – 5.0.2
Gravity Forms Constant Contact Add-On: by Katz Web Services
Inc. – 3.1.1

Gravity Forms Zapier Add-on: by Gravity Forms – 3.3
IgniteWoo Updater: by IgniteWoo.com – 3.0.2
Post Expirator: by Aaron Axelsen – 2.4.0.1
WooCommerce Auctions Pro: by IgniteWoo.com – 3.6.7 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.2 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Tax Exempt: by IgniteWoo.com – 2.2.6 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce: by Automattic – 4.5.1
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Mail Logging: by MailPoet – 1.9.7
WP Mail SMTP: by WPForms – 2.3.1

### Inactive Plugins (12) ###

10WebAnalytics: by 10Web – 1.2.9
AceIDE: by AceIDE – 2.6.2
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
Nginx Helper: by rtCamp – 2.2.2
Plugins Garbage Collector (Database Cleanup): by Vladimir Garagulya – 0.12
TAO Schedule Update: by TAO Digital – 1.15
User Shortcodes Plus: by Kyle B. Johnson – 2.0.2
Widget Logic: by WPChef – 5.10.4
Widget Options: by Widget Options Team – 3.7.4
Wordfence Security: by Wordfence – 7.4.11
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

YITH Auctions for WooCommerce Premium: by YITH – 1.3.4 – Installed version not tested with active version of WooCommerce 4.5.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (1) ###

WP Rocket exclude dynamic CSS: by WP Rocket team –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
external (external)
grouped (grouped)
ignitewoo_auction (ignitewoo_auction)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #27737 - /shop/
Cart: #27738 - /cart/
Checkout: #27739 - /checkout/
My account: #27740 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 57
Oldest: 2020-08-20 09:10:39 -0500
Newest: 2020-09-10 08:40:46 -0500

````
</details>

**Comment by juliaamosova** [comment] 2020-09-10 20:33
Hi @Nemi5150,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Here is how I have the product set up on the back end:

![product](https://user-images.githubusercontent.com/19143190/92800964-2f6a9180-f383-11ea-97af-02bb9c869455.jpg)

I also made a short video for you to take a look at what I see when I follow your steps (using Twenty Twenty theme as you use):

![](http://g.recordit.co/rNLftmizLX.gif)

Would you please provide screenshots or a short video of what you see. 

I see that you indicated in your report that you tested your site for a theme and plugins conflict, however, I always like to confirm again. 

I see that you have several plugins installed which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by Nemi5150** [comment] 2020-09-10 20:38
You have to test on mobile. you can do that by opening the chrome developer
tools and switching it over to a mobile and then you will have the x in the
toolbar at the top of the page

**Comment by Nemi5150** [comment] 2020-09-10 20:47
Here is a video of  it in action. It is hard to see the cursor, but I click
on the magnifying glass icon, then move up to the X in the upper right.
When I click the X it dismisses the overlay, but also clicks the underlying
user icon.

**Comment by tammullen** [comment] 2020-09-11 08:01
Hi @Nemi5150 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25458. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Closed by tammullen** 2020-09-11 08:01 UTC
Labels: status: needs feedback
