### ISSUE TITLE
e-mail template - header image

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce#19149] opened 2018-02-27 10:56 UTC
There is a bug in the WooCommerce settings for emails. As I installed WC a years ago, I used a email header image located in the uploads folder as header image. Later I changed the image setting with a other image out of my child theme.

This works well up to a WooCommerce update. On every WC update the header image settings is reverted to the old initial image of the upload folder.

e.g. WooCommerce 3.0

Email header image: https://…/wp-content/themes/my-child-theme/assets/images/my_shop_logo_mail.png

Update to WooCommerce 3.3

Email header image: https://…/wp-content/uploads/2017/04/my_logo_508px.png

I can reproduce this on every WC update.

**Comment by rodrigoprimo** [comment] 2018-02-27 14:19
Thanks for your contribution, @Babelfisch.

I tried to reproduce this issue by following the steps below:

- Created a fresh WooCommerce 3.0 install
- In the WP admin, I went to WooCommerce -> Settings -> Emails
- Defined the value of the field "Header image" as an image that I uploaded via the WP media library.
- Tested the header image using the preview email template feature
- Changed the "Header image" to a theme image (`/wp-content/themes/twentyseventeen/assets/images/coffee.jpg`)
- Tested the header image again using the preview email template feature to make sure that the change worked
- Updated WooCommerce to 3.3.3 via wp-admin

I was not able to reproduce the issue that you reported. After following the steps above, the email header image was still set to `/wp-content/themes/twentyseventeen/assets/images/coffee.jpg`. Are you able to reproduce this problem on a clean WC install? I ask this because I wonder if this problem is maybe an issue caused by another plugin or the theme.

The header image is stored by WooCommerce as a WP option called `woocommerce_email_header_image` (https://github.com/woocommerce/woocommerce/blob/52d7d136d60f6c22ad57a23be2c3f74a6cdf56c8/includes/admin/settings/class-wc-settings-emails.php#L92). I don't see anything in WC core code that would store the old value of this option, and so I don't know how WC is restoring this old value during an update.

Please let me know if I'm missing something.

**Comment by mikejolley** [comment] 2018-02-28 11:26
Thanks for investigating. @Babelfisch it's not clear where you're setting the image. As Rodrigo said, the option is not updated after updates. If you're making changes to core template files those changes would however be overwritten.

Feel free to provide more clarity. I'm closing this as non reproducible for now.

**Closed by mikejolley** 2018-02-28 11:26 UTC
Labels: Status: Needs Feedback

**Comment by Babelfisch** [comment] 2018-02-28 11:31
It seams to be a bug in Vendipro theme.

**Comment by FreeSpirit63** [comment] 2019-10-19 04:53
danke... hat geholfen... Thanks all this helpome out....
