### ISSUE TITLE
The return of the "Non-Object Notices in abstract-wc-rest-posts-controller"

### ISSUE THREAD

**Issue by breadadams** [woocommerce/woocommerce#13837] opened 2017-03-29 23:03 UTC
## EXPLANATION OF THE ISSUE

Seem to be facing a _similar_ issue as was closed last year here https://github.com/woocommerce/woocommerce/issues/11192

However a slight change, I'm seeing the notices for lines 710 & 751:

```
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-terms-controller.php on line 710
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-terms-controller.php on line 751
```

## STEPS TO REPRODUCE THE ISSUE

Unfortunately I'm not aware of what I'm actually doing that causes the notices to be displayed. We've got a few custom WP REST API calls that get (amongst others) product data & run orders, but it's all working fine.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://localdomain.dev
Site URL: http://localdomain.dev
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.9
PHP Version: ❌ 5.5.9-1ubuntu4.20 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (2) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.11
WooCommerce: by WooThemes – 2.6.14
WP Migrate DB Pro: by Delicious Brains – 1.7.1
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.7
WP Migrate DB Pro Multisite Tools: by Delicious Brains – 1.1.5
Advanced Custom Fields PRO: by Elliot Condon – 5.5.11
WooCommerce: by WooThemes – 2.6.14
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6

### Settings ###

Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Cart: ❌ Page does not contain the shortcode: [woocommerce_cart]
Checkout: ❌ Page not set
My Account: ❌ Page not set

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: OurThemeName
Version: 1.0.0
Author URL: https://knightdigital.se
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: ourthemename/archive-product.php
ourthemename/single-product.php
ourthemename/taxonomy-product_cat.php 

```

**Comment by claudiosanches** [comment] 2017-03-29 23:41
> Unfortunately I'm not aware of what I'm actually doing that causes the notices to be displayed. We've got a few custom WP REST API calls that get (amongst others) product data & run orders, but it's all working fine.

This make things hard, even because the location of the issue.

See:

https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/abstracts/abstract-wc-rest-terms-controller.php#L680-L688

Note that `get_taxonomy()` return a `WP_Taxonomy` object that always have `hierarchical` and still there is a fallback for when don't have any taxonomy, so for me the message of `Trying to get property of non-object` could come only by custom code or changes. There is nothing that I could do to reproduce this steps and that's why I'm closing, if you have something to help me debug it I can help you, but testing a fresh install, it's all working just fine.

**Closed by claudiosanches** 2017-03-29 23:41 UTC

**Comment by breadadams** [comment] 2017-03-30 18:27
Hey @claudiosanches. Sorry I didn't provide enough details, I've had a bit more time to test it and got some info. So we've got some custom API routes, setup like this:

```
class CustomRoutesForAPI {

	function __construct() {
		add_action( 'rest_api_init', array($this, 'themes_custom_api_hooks') );
	}

	function themes_custom_api_hooks() {
		$nameSpaceV1 = 'customApi/v1';

		register_rest_route( $nameSpaceV1, '/search/', array(
			'methods'		=> 'GET',
			'callback'		=> array($this, 'product_search')
		), false );
	}

	function product_search() {
		return array('test');
	}
}

new CustomRoutesForAPI();
```

Running *just* this gives me the errors I initially posted. Any ideas?

**Comment by claudiosanches** [comment] 2017-03-30 18:33
I just tested your custom endpoint and works just fine.
It's a custom endpoint generated using WordPress code and not WooCommerce code... and still there is nothing that could cause the error that you are reporting, have you read the code that I showed? Just don't make any sense.

**Comment by breadadams** [comment] 2017-03-30 18:49
Yeah I read your reply. I thought maybe something in that snippet was conflicting that I was missing - but I've been testing meanwhile and found the issue.

We're _removing_ the `product_tag` taxonomy, and I was doing so with the `unregister_taxonomy()` function, on the `init` action. This was the offending line.

After changing this to `register_taxonomy( 'product_tag', array() );` (so basically registering it as empty), I've stopped seeing the error.

Sorry for creating an issue over this - slap on the wrist for me and lesson learnt to debug a bit more before crying for help 🙈 😉

**Comment by claudiosanches** [comment] 2017-03-30 18:52
@breadadams no worry, this happens.
