### ISSUE TITLE
Deactivate old WooCommerce Admin version prompt still appearing on one site

### ISSUE THREAD

**Issue by databell** [woocommerce/woocommerce#26715] opened 2020-06-06 16:56 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Login to WordPress
2. Go to WooCommerce --> Dashboard (really anywhere in Woo)
3. Deactivate old WooCommerce Admin version prompt appears and won't go away.

## Expected/actual behavior

I should select Deactivate and the prompt should go away.

This is only happening with one of my client sites (https://perfec-tone.com) which is hosted on a VPS on InMotion Hosting. All plugins up to date. Using Divi which is also up to date.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://perfec-tone.com
Site address (URL): https://perfec-tone.com
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.31
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.32-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Total Database Size: 1231.20MB
Database Data Size: 1129.96MB
Database Index Size: 101.24MB
wp_woocommerce_sessions: Data: 6.88MB + Index: 0.33MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.19MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 4.63MB + Index: 1.33MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 427.52MB + Index: 11.81MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.19MB + Index: 0.10MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.54MB + Index: 0.40MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 20.68MB + Index: 6.90MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 14.47MB + Index: 9.41MB + Engine MyISAM
wp_amazon_accounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_btg: Data: 0.97MB + Index: 0.44MB + Engine MyISAM
wp_amazon_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_feeds: Data: 9.45MB + Index: 0.01MB + Engine MyISAM
wp_amazon_feed_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_feed_tpl_data: Data: 0.82MB + Index: 0.10MB + Engine MyISAM
wp_amazon_feed_tpl_values: Data: 1.50MB + Index: 0.12MB + Engine MyISAM
wp_amazon_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_listings: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_amazon_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_markets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_orders: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
wp_amazon_payment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_profiles: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_reports: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_amazon_shipping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_amazon_stock_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_atum_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_atum_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_atum_product_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_berocket_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwf_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwf_action_claim: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwf_contact: Data: 0.75MB + Index: 1.27MB + Engine MyISAM
wp_bwf_contact_meta: Data: 2.23MB + Index: 0.75MB + Engine MyISAM
wp_bwf_wc_customers: Data: 1.70MB + Index: 0.25MB + Engine MyISAM
wp_commentmeta: Data: 0.29MB + Index: 0.22MB + Engine MyISAM
wp_comments: Data: 28.55MB + Index: 8.86MB + Engine MyISAM
wp_dp_available_categories: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_ewwwio_images: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wp_fca_eoi_activity: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_entry: Data: 0.06MB + Index: 0.01MB + Engine MyISAM
wp_gf_entry_meta: Data: 0.08MB + Index: 0.08MB + Engine MyISAM
wp_gf_entry_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_meta: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_view: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ia_savedcarts: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_inf_infusionsoft_stats: Data: 0.85MB + Index: 0.13MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_oauth_access_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_oauth_authorization_codes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_oauth_jwt: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_oauth_public_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_oauth_refresh_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_oauth_scopes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 10.56MB + Index: 4.04MB + Engine MyISAM
wp_postmeta: Data: 68.12MB + Index: 32.40MB + Engine MyISAM
wp_posts: Data: 6.89MB + Index: 1.72MB + Engine MyISAM
wp_sfa_abandoned_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sf_surveys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sf_survey_questions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sf_survey_results: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sf_survey_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sf_survey_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sf_survey_user_information: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_swift_performance_image_optimizer: Data: 1.93MB + Index: 0.77MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wp_term_relationships: Data: 0.04MB + Index: 0.07MB + Engine MyISAM
wp_term_taxonomy: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_usermeta: Data: 17.25MB + Index: 9.52MB + Engine MyISAM
wp_users: Data: 0.93MB + Index: 1.14MB + Engine MyISAM
wp_vtprd_purchase_log_product: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_vtprd_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wclsi_items: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_wclsi_item_attribute_sets: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wclsi_item_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wclsi_item_e_commerce: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wclsi_item_images: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wclsi_item_prices: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wclsi_item_shops: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.12MB + Index: 0.07MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.96MB + Index: 0.84MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.15MB + Index: 0.25MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 2.41MB + Index: 1.93MB + Engine MyISAM
wp_wc_order_stats: Data: 0.97MB + Index: 0.64MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_points_rewards_user_points: Data: 0.46MB + Index: 0.64MB + Engine MyISAM
wp_wc_points_rewards_user_points_log: Data: 1.06MB + Index: 0.61MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_zapier_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdi_feeds: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdi_themes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfconfig: Data: 0.39MB + Index: 0.01MB + Engine MyISAM
wp_wfco_report_views: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Data: 2.26MB + Index: 0.32MB + Engine MyISAM
wp_wfhits: Data: 0.61MB + Index: 0.11MB + Engine MyISAM
wp_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Data: 1.20MB + Index: 0.14MB + Engine MyISAM
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wflogins: Data: 0.09MB + Index: 0.02MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfocu_event: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
wp_wfocu_event_meta: Data: 0.16MB + Index: 0.06MB + Engine MyISAM
wp_wfocu_session: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Data: 0.07MB + Index: 0.04MB + Engine MyISAM
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gpf_google_taxonomy: Data: 0.89MB + Index: 0.00MB + Engine MyISAM
wp_wpml_mails: Data: 484.90MB + Index: 0.53MB + Engine MyISAM
wp_yoast_indexable: Data: 2.02MB + Index: 0.62MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.52MB + Index: 0.10MB + Engine MyISAM
wp_yoast_seo_meta: Data: 2.05MB + Index: 1.73MB + Engine MyISAM

### Post Type Counts ###

acf: 1
acf-field: 9
acf-field-group: 2
attachment: 397
br_filters_group: 1
br_product_filter: 1
custom_css: 4
et_pb_layout: 10
gift_card: 1
nav_menu_item: 21
page: 63
paypal_transaction: 162
popup: 5
popup_theme: 6
post: 80
product: 18
product_variation: 5
project: 12
revision: 331
shop_coupon: 5783
shop_order: 14340
shop_order_refund: 308
shop_subscription: 18
vtmin-rule: 1
wc_membership_plan: 1
wc_zapier_feed: 2
wcct_countdown: 5
wcs_ruleset: 5
wcst_trigger: 10
wdi_instagram: 1
wfocu_funnel: 1
wfocu_offer: 1
wo_client: 1
xlwcty_thankyou: 1
ywrac_cart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (49) ###

Gravity Forms: by Gravity Forms – 2.4.18
a3rev Dashboard: by a3rev Software – 3.2.3 – Installed version not tested with active version of WooCommerce 4.2.0
Advanced Custom Fields PRO: by Elliot Condon – 5.8.11
AfterShip - WooCommerce Tracking: by AfterShip – 1.9.26 – Installed version not tested with active version of WooCommerce 4.2.0
Schema - All In One Schema Rich Snippets: by Brainstorm Force – 1.6.1
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.7.2 – Installed version not tested with active version of WooCommerce 4.2.0
Before + After Images for Divi: by Aaron Bolton – 1.3.3
Classic Editor: by WordPress Contributors – 1.5
Conditional Shipping for WooCommerce: by Lauri Karisola / WooElements.com – 2.0.4 – Installed version not tested with active version of WooCommerce 4.2.0
DP Portfolio Posts Pro: by DiviPlugins – 4.0.5
Facebook for WooCommerce: by Facebook – 1.11.4
Facebook Reviews Pro: by RichPlugins  – 1.4.4
Gravity Forms - Advanced Conditional Logic: by David Smith – 0.1
GTranslate: by Translate AI Multilingual Solutions – 2.8.54
Intercom: by Intercom – 2.6.4
Mailgun: by Mailgun – 1.7.1
PayPal for WooCommerce: by Angell EYE – 1.5.7 – Installed version not tested with active version of WooCommerce 4.2.0
Popup Maker: by Popup Maker – 1.10.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
ShipBob Express Rates: by ShipBob
Inc. – 1.3.0

WooCommerce Thank You Page - NextMove: by XLPlugins – 1.14.0 – Installed version not tested with active version of WooCommerce 4.2.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.25

Upload Larger Plugins: by David Anderson – 1.4.1
UpStroke: WooCommerce One Click Upsell for PayPal Angell Eye: by WooFunnels – 1.9.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Backorder Manager: by jeffrey-wp – 1.8 – Installed version not tested with active version of WooCommerce 4.2.0
WooСommerce Order Review page 2.0: by Maxim Kaminsky – 2.4.0
WooCommerce Coupon Usage (Premium): by ElliotVS – 3.1.4 – Installed version not tested with active version of WooCommerce 4.2.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.4 – Installed version not tested with active version of WooCommerce 4.2.0
Preview E-mails for WooCommerce: by Digamber Pradhan – 1.6.4 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Address Validation: by SkyVerge – 2.6.4 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Coupon Restrictions: by WooCommerce – 1.8.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.2 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.11 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.5.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.32 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Google Product Feed: by Ademti Software Ltd. – 8.1.1 – Installed version not tested with active version of WooCommerce 4.2.0
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.4 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Shipment Tracking: by WooCommerce – 1.6.23
WooCommerce Shopify Exporter Pro: by omniWP – 1.8.8 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Smart Coupons: by StoreApps – 4.7.5 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Zapier: by OM4 – 2.0.4 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0
UpStroke: WooCommerce One Click Upsells: by buildwoofunnels – 2.1.7 – Installed version not tested with active version of WooCommerce 4.2.0
Yoast SEO: by Team Yoast – 14.2
WP-Dropstream: by Dropstream – 1.1.8
WP Mail Logging: by MailPoet – 1.9.6
WP Rocket: by WP Media – 3.5.2
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.8 – Installed version not tested with active version of WooCommerce 4.2.0

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #1223 - /terms/

### Theme ###

Name: bahamaskin
Version: 1.0.0
Author URL: http://datatv.com/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.4.8
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: bahamaskin/woocommerce/single-product/short-description.php
bahamaskin/woocommerce/single-product/tabs/description.php
bahamaskin/woocommerce/single-product/up-sells.php


### WooCommerce Google Product Feed fields ###

Product description: Main product description (full preferred) plus variation description.
Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Defaults to "Perfec-Tone".
Manufacturer Part Number (MPN): 
Product Type: Defaults to "Health & Beauty > Personal Care > Cosmetics > Skin Care". Pre-populates from product_cat taxonomy.
Google Product Category: Defaults to "Health & Beauty > Personal Care > Cosmetics > Skin Care".
Identifier exists flag: Defaults to "included".

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled

### Address Validation ###

Active Provider: ❌No active provider available

### Action Scheduler ###

Complete: 72,101
Oldest: 2020-05-06 12:57:11 -0400
Newest: 2020-06-06 12:55:50 -0400

Failed: 3
Oldest: 2018-01-27 10:25:57 -0500
Newest: 2019-11-22 11:12:39 -0500

Pending: 6
Oldest: 2020-06-06 13:10:50 -0400
Newest: 2020-06-10 18:20:44 -0400


### WooCommerce Zapier ###

Database Version: ✔ 12
Detailed Logging Enabled: No
Legacy Mode Disabled: ❌ No
SSL: ✔ Yes
REST API Authentication Key(s): ❌ 0
Task History Record Count: ❌ 0
Legacy Cron Tasks: ✔ 0
Active Legacy Feeds: ❌ 2 active Legacy Feed(s) need to be migrated before April 30
2021. Migrate Your Zaps Now

Legacy Feed #1: Woo + Slack
- Trigger: New Order
- Webhook URL: https://hooks.zapier.com/hooks/catch/1693461/s887wy/
Legacy Feed #2: New Order Email
- Trigger: New Order
- Webhook URL: https://hooks.zapier.com/hooks/catch/1693461/s8kh3q/
`
```
</details>

**Comment by juliaamosova** [comment] 2020-08-24 17:49
Hi @databell,

Thanks for reporting and apologies for the delayed response to it! 

Noting that we have a couple more related issues in 4.4.1:

- https://github.com/woocommerce/woocommerce/issues/27463
- https://github.com/woocommerce/woocommerce/issues/27424

There were a few attempts to fix the issue of the notices but it remains present:

- https://github.com/woocommerce/woocommerce/pull/26031
- https://github.com/woocommerce/woocommerce/pull/26500

Assigning this a 4.5 milestone to see if we can fix it sooner rather than later.

**Comment by databell** [comment] 2020-08-24 17:54
Thanks, Julia. I’m noticing the same thing about prompts not disappearing as well for database updates and the notification about coupons since the most recent update.


—
Adam Bell
Design Director/CEO
dataTV
310-691-2410
dzign@datatv.com
https://datatv.com/
Facebook: https://facebook.com/datatv
Twitter: https://twitter.com/dataTV
Instagram: https://instagram.com/datatv 
—
Over 90% of all websites suck.
Join the minority.

**Comment by juliaamosova** [comment] 2020-08-24 17:58
Thanks for your follow-up @databell! 

>Thanks, Julia. I’m noticing the same thing about prompts not disappearing as well for database updates and the notification about coupons since the most recent update.

Yep, the other issues I linked in my previous comment are related to the behavior you are experiencing. We are hoping to fix it once and for all in the upcoming WooCommerce 4.5 version.

**Comment by peterfabian** [comment] 2020-10-29 14:00
Hi, this is a duplicate of #27424. Let's solve if from there. Thx.

**Closed by peterfabian** 2020-10-29 14:00 UTC
Labels: bug, component: notice, priority: high
