### ISSUE TITLE
Shipping tax not calculating correctly

### ISSUE THREAD

**Issue by nuclearape** [woocommerce/woocommerce#14675] opened 2017-04-25 10:59 UTC
### EXPLANATION OF THE ISSUE

Some of our products are taxable and some of our products aren't. When manually adding orders this causes an issue with the shipping tax calculations.

### STEPS TO REPRODUCE THE ISSUE

1. Go to the add new order screen (and ensure a country that is taxable is selceted in the address details)
2. Add a non-taxable product
3. Add a taxable shipping cost
4. Calculate the totals and **notice that no tax has been added to the shipping**
5. Add another taxable product
6. Recalculate the totals and **notice that the tax has been added to the shipping correctly**

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://dev.chucklinggoat.co.uk
Site URL: https://dev.chucklinggoat.co.uk
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #90 - /shop/
Cart: #91 - /shop/cart/
Checkout: #92 - /shop/checkout/
My account: #93 - /shop/my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment] 2017-04-25 11:01
This is a dupe of https://github.com/woocommerce/woocommerce/issues/14674

**Closed by mikejolley** 2017-04-25 11:01 UTC
