### ISSUE TITLE
Using Elementor changes the button text to woocommerce button and text gets set as 0.00 when watching live page

### ISSUE THREAD

**Issue by ccebreros1** [woocommerce/woocommerce#28852] opened 2021-01-19 15:46 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When looking at the elementor builder my buttons' texts are what they should be (pic attached), but on the live version the buttons get replaced for woocommerce buttons and the text changes to $0.00

**Expected behavior**
Buttons should have desired text

**Actual behavior**
If you go to https://allymedlab.com you can see how all button's text are replaced by $0.00
![Screen Shot 2021-01-19 at 8 40 46 AM](https://user-images.githubusercontent.com/17016986/105057688-b6ff9580-5a32-11eb-9905-c240abba00df.png)
![Screen Shot 2021-01-19 at 8 41 20 AM](https://user-images.githubusercontent.com/17016986/105057700-b9fa8600-5a32-11eb-922c-9b9a3352ad6b.png)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to https://allymedlab.com
2. See the error on top

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by ccebreros1** [comment] 2021-01-19 15:58
Found out is duplicated of https://github.com/woocommerce/woocommerce/issues/28848
I have screenshots so I will not close the issue yet in the case they are needed

**Comment by ccebreros1** [comment] 2021-01-19 16:14
I kind of find a workaround for it. I disabled woocommerce, rolled it back to an older version. Rolled back my theme (Astra). Enabled woocommerce and updated it. Updated Astra again

**Comment by RiaanKnoetze** [comment] 2021-01-21 09:05
Reported at: https://wordpress.org/support/topic/all-button-text-become-0-after-updating-woocommerce/

**Comment by zhongruige** [comment] 2021-01-26 21:12
Hi @ccebreros1,

Thank you for taking the time to report this issue. 

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue. For example, from the screenshot that was shared, it looks like the Elementor plugin might still be enabled. I want to confirm if the issue is still occurring with the Elementor plugin disabled.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

Thank you!

**Comment by zhongruige** [comment] 2021-02-16 21:31
Hi @ccebreros1 ,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by zhongruige** 2021-02-16 21:31 UTC
Labels: needs feedback

**Comment by LarissaBrink** [comment] 2021-04-15 09:39
Can somebody tell me what the solution of this problem is? I also have this problem and no matter what I try, I still have the amount instead of the text. I'm getting crazzzzy :S
