### ISSUE TITLE
Bulk deleting product categories shows a "Category not deleted" notice

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce#27831] opened 2020-10-01 10:13 UTC
When bulk deleting product categories from a site with only core WooCommerce, the categories do get deleted, but we also see a "Category not deleted" notice

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When bulk deleting product categories from a site with only core WooCommerce, the categories do get deleted, but we also see a "Category not deleted" notice

**Expected behavior**

No such notice appears once the categories get deleted.

**Actual behavior**

An erroneous notice appears that reads `Category not deleted`, despite the categories getting deleted.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

- Start with a WordPress website, having only core WooCommerce installed
- Create one or more product categories
- Visit the category list at this link: `https://domain.com/wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product`
- Select the categories using the checkbox on the left
- Use the bulk editor dropdown
- Choose `Delete`.
- Click on `Apply`.

**Couple of things to note:**

- Note that using `Delete` button next to the category itself does not show this error.
- I thought selecting all categories might be choosing `Uncategorized` as well (which does not have a checkbox) resulting in this error, but no. Individually selecting one or two categories and deleting them via the dropdown shows this error too.

**Screenshots**

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/18581859/94796427-69680a00-03fc-11eb-91b8-b257a3e3738a.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://ephemeral-arunsathiyawp-20200925.atomicsites.blog
Site address (URL): https://ephemeral-arunsathiyawp-20200925.atomicsites.blog
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.22
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.72.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 10.80MB
Database Data Size: 6.40MB
Database Index Size: 4.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 4.16MB + Index: 3.05MB + Engine InnoDB
wp_posts: Data: 1.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.23MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 347
page: 6
post: 12
product: 1
revision: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.5.2

### Inactive Plugins (11) ###

Akismet Anti-Spam: by Automattic – 4.1.6
AMP: by AMP Project Contributors – 2.0.4
CoBlocks: by GoDaddy – 2.3.2
Crowdsignal Forms: by Automattic – 1.1.1
Gutenberg: by Gutenberg Team – 9.1.0
Jetpack by WordPress.com: by Automattic – 8.9.1
Layout Grid: by Automattic – 1.3
Page Optimize: by Automattic – 0.5.1
WooCommerce Pre-Orders: by WooCommerce – 1.5.28 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Stripe Gateway: by WooCommerce – 4.5.2 – Installed version not tested with active version of WooCommerce 4.5.2
WordPress.com Editing Toolkit: by Automattic – 2.6.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #54 - /shop/
Cart: #55 - /cart/
Checkout: #56 - /checkout/
My account: #57 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2020-09-25 03:45:42 +0000
Newest: 2020-09-25 03:45:42 +0000

Pending: 1
Oldest: 2020-10-01 10:12:30 +0000
Newest: 2020-10-01 10:12:30 +0000

`
```
</details>

**Comment by tammullen** [comment] 2020-10-02 21:51
Hi @arunsathiya 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot 2020-10-02 at 22 49 51](https://user-images.githubusercontent.com/24649833/94972709-d74a2980-0501-11eb-95cd-e165c9b3f8d7.png)
![Screenshot 2020-10-02 at 22 50 11](https://user-images.githubusercontent.com/24649833/94972716-d913ed00-0501-11eb-9937-85d73a674737.png)


​I'm marking it as low as the categories do get deleted so it is just an incorrect notice.

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Closed** 2020-10-24 17:57 UTC
Labels: bug, component: category, priority: low
