### ISSUE TITLE
Shop acrhive-product page reverts to no archive page

### ISSUE THREAD

**Issue by davodavodavo3** [woocommerce/woocommerce#22427] opened 2019-01-12 04:22 UTC
**Describe the bug**
Sometime when move through the pages and return to the archive-product page it's showing broken design page without products. It doesn't happen always, maybe once a day, maybe 3-4 times a day, and it’s not clear why it goes so far as there are no any errors/issues in debug.log file. This can be issue from woocoomerce or my environment, I don't know realy so it can be labled as question and help to other developers. Also I can't find any solution in whole internet about this and I think that real Woocommerce professionals here can give me some quote.

**To Reproduce**
1. Go to https://www.nonameatelier.com/catalog/ and go trought site page and return to catalog page.

It's not a best way to reproduce but it can help. So I open this question as an issue because i think it should bring some errors or something, so developers can fix that himself. I have 3 diferent themes and that issue is on each of them.  In function.php there is written add_theme_support( 'woocommerce' ), right shop page is selected in Woocommerce->Settings->Products Shop page field(it's catalog page).

**Screenshots**
I GET THIS
<img width="2560" alt="2019-01-10 13 33 41" src="https://user-images.githubusercontent.com/10462563/51068991-b8c24180-163f-11e9-8cd3-26fd234b3b7d.png">

**Expected behavior**
BUT IT SHOULD BE LIKE THIS
![screenshot from january 12 2019 7-46 am](https://user-images.githubusercontent.com/10462563/51068994-ce376b80-163f-11e9-96f7-efdc8052021d.png)

Also other pages are opening fine category, checkout and etc. It's happen only on archive-product page.
So can somone help with this, explain why Woocomerce think that it's not an archive page. I create new arhive-product.php in my theme (i create it in right way as in documentation) with all necessary code but it doesn't help.

This is my first introduction to Woocommerce but not in web development, please if someone can give some light at the end of the tunnel, when and why it's revert to non archive-product page.
Can I permanently write some php hook that will set that page to always be a archive product page before Woocomerce will do his job to assign all necessary thing to the page.
Thanks to everyone that will write some helpfull thinks and not closing this and say goodbye to me))

**Comment by rrennick** [comment] 2019-01-15 19:06
If you are reporting a bug here you need to deactivate all your plugins except WooCommerce & switch to the Storefront theme or a default WordPress theme. If you still have the issue then please provide your system status report (WooCommerce -> Status).

**Comment by davodavodavo3** [comment] 2019-01-15 20:03
@rrennick Thank you for your reply. I don't know is this is a Woocomerce issue or issue from some of my plugins or themes so i write that this can be labeled as question. 

Yes I will disable plugins and change theme to default Wordpress theme later to night when we don't have active customers inside web site. @rrennick But what can produce that reverting? Do you have any suggestions in mind? Or for whole picture you need more information?

**Comment by rrennick** [comment] 2019-01-15 20:39
> But what can produce that reverting?

If you revert to just WC & Storefront and are unable to reproduce the problem then your issue is likely a conflict somewhere or a server resource issue. If you are able to reproduce the issue then your system status report may provide some insight.

**Comment by kloon** [comment] 2019-01-16 10:20
As @rrennick pointed out, please test by disabling all plugins and switching your theme to a default one like Storefront or Twentyseventeen.

I am unable to replicate this with either of those themes and no additional plugins so closing this issue. Can reopen if we have steps to replicate this with just WooCommerce and a default theme.

**Closed by kloon** 2019-01-16 10:20 UTC

**Comment by davodavodavo3** [comment] 2019-01-26 13:09
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
