### ISSUE TITLE
Page reloaded everytime on removing product from woocommerce minicart

### ISSUE THREAD

**Issue by santanup789** [woocommerce/woocommerce#26655] opened 2020-06-01 14:31 UTC
I'm facing a serious issue. Don't know it's my fault or a bug.

I used minicart in woocommerce template and made a widget using it. Placed it in header.php

fragements all working till now. But whenever i gave the widget position using css like position:fixed, the remove product function started not to work properly. like page is loading after removing a product from minicart.

How can i solve that issue? Please suggest.

**Comment by tammullen** [comment] 2020-06-01 19:36
Hi @santanup789 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party plugin WooCommerce Minicart. 
​
Please contact the author of the plugin directly for further help.

**Comment by santanup789** [comment] 2020-06-02 04:51
I didn't use woocommerce mini cart shortcode from any third party plugin. Used `woocommerce_mini_cart();` along with fragements. Please correct me if I'm wrong.

**Comment by tammullen** [comment] 2020-06-02 11:03
Hi @santanup789,

Thanks for clarifying. I have reopened the issue.

Can you fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​

**Comment by santanup789** [comment] 2020-06-03 13:55
Thanks for reopened the issue.

I'm working with divi theme, where I used custom ajax add to cart functionality for quickview. For that I used woocommerce minicart shortcode in header file. I just realized that i gave that minicart a position with css like an offcanvas with position fixed css, then remove item in every 'li' is not working. I mean to say page reloaded every time to remove an item from minicart. After removing position css from minicart it's works fine.

**Comment by santanup789** [comment] 2020-06-06 04:41
Hei @tammullen.. I just discovered that making minicart like an offcanvas I used jquery to stopPropagation on minicart. If a comment that line it works fine.

`jQuery(function($) {`
	`$('#et-top-navigation .et-cart-info').attr('href', 'javascript:void(0)');`
	`$('.et-cart-info').on("click", function(e){`
		`$('body').addClass('miniCartOpen');`
		`$('body').append('<div class="minicartOverlayDiv"></div>');`
		`$('.miniCartContainer').addClass('slide_in');`
		`e.stopPropagation();`
	`});`
	`$(".miniCartContainer").on("click", function(event){`
		`//event.stopPropagation();`
	`});`
	`//$(document).on("click", function(event){`
	`$('body').find('.minicartOverlayDiv').on("click", function(event){`
		`$('.minicartOverlayDiv').remove();`
		`$('body').removeClass('miniCartOpen');`
		`$(".miniCartContainer").removeClass('slide_in');`
	`});`
`});`

Is that only for stopPropagation() minicart ajax doesn't work?? Is that an issue or a bug?

**Comment by tammullen** [comment] 2021-03-24 19:59
Hi @santanup789 

Apologies for the delay in replying.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-24 19:59 UTC
Labels: has feedback
