### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by DavidHF** [woocommerce/woocommerce#27072] opened 2020-07-19 10:14 UTC
Just ran the Woo update from WP admin /plugins and it failed miserably.

Fatal error: Uncaught Exception: Invalid data store for admin note. in /home/www/denrigtigemand.dk/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php:127 Stack trace: #0 /home/www/denrigtigemand.dk/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #1 /home/www/denrigtigemand.dk/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #2 /home/www/denrigtigemand.dk/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(109): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct('6') #3 /home/www/denrigtigemand.dk/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name(Array) #4 /home/www/denrigtigemand.dk/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package in /home/www/denrigtigemand.dk/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php on line 127

**Comment by peterfabian** [comment] 2020-07-21 11:02
Hi @DavidHF , 

Apologies for the problem. We've seen this kind of errors when a customer doesn't have privileges to alter the database (some columns are missing), so it seems to be a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/4823 .

We are releasing an update (4.3.1) to make WC more resilient to this error as we speak.

Could you please confirm if you have access to alter database tables (so that we can confirm this caused by the same problem)?

**Comment by DavidHF** [comment] 2020-07-21 15:32
Yes I have (WordPress Admin)



David Fønsbo
Digital Dictator
Søskrænten 34
DK-8260 Viby
Denmark

Tel.: +45 28 94 68 00

LinkedIn:  David Fønsbo <http://dk.linkedin.com/in/leadershipandawareness>
Twitter:    TheMasculineMan <https://twitter.com/TheMasculineMan>
Facebook: DenRigtigeMand <https://www.facebook.com/DenRigtigeMandDK>

www.MakeItCount.dk <http://www.makeitcount.dk/> - SEO & Webdesign


Den tir. 21. jul. 2020 kl. 13.02 skrev Peter Fabian <
notifications@github.com>:

**Comment by peterfabian** [comment] 2020-08-11 12:02
This should be solved now, so closing. Please let us know if the issue persists.

**Closed by peterfabian** 2020-08-11 12:02 UTC
Labels: status: needs feedback
