### ISSUE TITLE
Coupon: override individual use only or add conditional logic

### ISSUE THREAD

**Issue by bowenac** [woocommerce/woocommerce#30001] opened 2021-05-27 14:59 UTC
I have a bunch of coupons that are set to Individual use only, however I have one coupon I would like to allow to be stacked with any coupon and it always has a prefix... 

My thought was I could loop through the coupons used, and if any of the coupons used started with that prefix, allow it to stack... I tried to use `woocommerce_coupon_is_valid` filter but I've been unable to get my logic to work with that, but not sure if that filter actually checks for the individual use... or just if it's valid.

Example: So test1 coupon applied to cart which is set to individual use only, and I try to add the coupon that I want to allow stacking say sttest it won't allow it and will remove it since test1 is set to individual use only and I get the message Sorry, coupon test1 has already been applied and cannot be used in conjunction with other coupons. The `woocommerce_coupon_is_valid` filter seems to only apply to the coupon you're trying to add, not to coupons already applied?

And code snippet of what I thought could work... but this appears to only trigger when trying to add a new coupon, and it uses the coupon you're trying to add.

```
function check_if_stackable_coupon( $valid, $coupon ) {
    if(substr($coupon->code, 0, 2) == 'st'){
        $valid = true;
    }
    return $valid;
}
add_filter( 'woocommerce_coupon_is_valid', 'check_if_stackable_coupon', 99, 2 );
```

I then thought I could then loop through and check each coupon:

```
function check_if_stackable_coupon( $valid, $coupon ) {
    
    //var_dump($coupon->code);

    if(substr($coupon->code, 0, 2) == 'st'){
        $valid = true;
    }

    foreach ( WC()->cart->get_applied_coupons() as $code ) {
        //var_dump($code);
        $maybe_stackable_coupon = new WC_Coupon( $code );
        if(substr($maybe_stackable_coupon->code, 0, 2) == 'st'){
            $valid = true;
        }
    }

    return $valid;
}
add_filter( 'woocommerce_coupon_is_valid', 'check_if_stackable_coupon', 99, 2 );
```

Anyone know how I could solve for this?

**Comment by tammullen** [comment] 2021-06-04 17:29
Hi @bowenac ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-06-04 17:29 UTC

**Comment by tombola** [comment] 2024-03-19 15:33
As feedback, I arrived here from an organic web search looking to learn from the approach demonstrated by the question as well as the answer.

An answer given in a slack channel would not be accessible to that kind of search, and would probably only help one person. Though I understand GitHub issues might not be the right place, siloing learning into slack seems a shame.
