### ISSUE TITLE
Use get_user_locale() instead of get_locale()

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#14361] opened 2017-04-13 19:49 UTC
If a user changes her profile to use a different language from the site settings then when that user is using the site, WooCommerce should load the language pack of that particular language. Ex: Base site language setting is German. User chooses French as her language.

Proposed change would then be changing [this](https://github.com/woocommerce/woocommerce/blob/master/woocommerce.php#L459):

```
$locale = apply_filters( 'plugin_locale', get_locale(), 'woocommerce' );
```

to:

```
$locale = function_exists( 'get_user_locale' ) ? get_user_locale() : get_locale();
$locale = apply_filters( 'plugin_locale', $locale, 'woocommerce' );
```

Or perhaps this should only be true for the admin? Though WooCommerce's language files aren't separated into front/back end.

**Comment by claudiosanches** [comment] 2017-04-17 16:28
This need to be true only in the admin, since this option for select a particular language are available only in the admin.

@mikejolley this is a fix related to WordPress 4.7 and should be fixed in 3.0.4.

**Comment by claudiosanches** [comment] 2017-04-17 16:33
Note that `load_textdomain( 'woocommerce', WP_LANG_DIR . '/woocommerce/woocommerce-' . $locale . '.mo' );` is for load custom translations.

**Closed** 2017-04-18 09:27 UTC
Labels: Status: Needs Review

**Comment by FawadNL** [comment] 2019-05-21 14:36
Hi team,

This issue has appeared again. Woocommerce is not getting the user locale if its in other language than site setting lang.

**Comment by claudiosanches** [comment] 2019-05-21 16:35
@FawadNL not able to reproduce, seems to be working just fine.

**Comment by TimothyBJacobs** [comment] 2019-05-21 17:59
`determine_locale()` should probably be used now to ensure the correct locale is loaded during REST API requests.
