### ISSUE TITLE
Save Custom field using "woocommerce_customer_meta_fields" hook

### ISSUE THREAD

**Issue by Phatza** [woocommerce/woocommerce#19585] opened 2018-03-31 10:58 UTC
Hi there,

I've tried to add custom checkbox field into **_Admin Edit User Profil Page_** using the filter hook "**_woocommerce_customer_meta_fields_**". The field is displayed to the right position and I can update the value 👍.
(I'm using Woocommerce version 3.3.4)

The problem is that after the value's update (0 by default) the custom field disappeared.
The checkbox's field is expecting 0 or 1 as value.
When the value is equal to 0 the field is visible, but when I change the value to 1 it is not.

This is the snippet I've added in my functions.php :
```
add_filter( 'woocommerce_customer_meta_fields', 'filter_woocommerce_customer_meta_fields', 10, 1 );
    function filter_woocommerce_customer_meta_fields( $array ) {

        $array += array(
            'enable_sms_alert' => array(
                'title' => 'Activation de l\'alerte SMS',
                'fields' => array(
                    'enable_sms_alert' => array(
                        'label' => 'Cochez la case pour activer l\'alerte SMS',
                        'description' => 'Si l\'option est activée, vous recevrez des alertes SMS (au numéro renseigner) pour les véhicules présents dans votre Wishlist',
                        'type' => 'checkbox',
                        'class' => 'enable_sms_alert'
                    )
                )
            )
        );
        return $array;
    }
```

I've tried to change the type field to text (number isnt output) and I've noticed that when the value is a string like "Hello World" the field is still visible, but if I change the value to 1 or another number than 0 the field is not displayed anymore.

Any ideas ?

Thanks for your time 😃

Regards

EDITED PART:

I've notice that the hooks arent triggered when I've a custom value different of 0 or "letter string".

**Comment by claudiulodro** [comment] 2018-04-02 17:34
I'm not exactly sure what you're saying, but your code snippet works fine for me:

<img width="1109" alt="screen shot 2018-04-02 at 10 25 29 am" src="https://user-images.githubusercontent.com/7317227/38206862-d3d28a58-3660-11e8-8c04-b576997da392.png">
<img width="1110" alt="screen shot 2018-04-02 at 10 25 41 am" src="https://user-images.githubusercontent.com/7317227/38206864-d3e977a4-3660-11e8-877c-4b1c81671150.png">

I would look through [WC_Admin_Settings](https://github.com/woocommerce/woocommerce/blob/869fb52927b675bd4c200cf3480a8813c9465a28/includes/admin/class-wc-admin-settings.php) to see how it handles checkbox inputs and compare that to the input you're giving it to make sure it's all correct. 

Closing this issue as it's a development support request and not a bug in the core plugin. For future development questions I recommend joining the WooCommerce community Slack using [the form at the bottom of this page](https://woocommerce.com/develop-woocommerce/).

**Closed by claudiulodro** 2018-04-02 17:34 UTC

**Comment by Phatza** [comment] 2018-04-03 09:30
Hi, 

I've made no changes but it seems to works today.. (this could be the april fool ^^).
This error could be produced by my server ?

Sorry for the waste of time.
i'll give a chance to the slack's channel.

Regards
