### ISSUE TITLE
Having trouble setting shipping methods for diferrent countries in Franceeeeeeee

### ISSUE THREAD

**Issue by Wovami** [woocommerce/woocommerce#29515] opened 2021-03-28 06:04 UTC
Hello everyone, the last few days I have been trying to install the shipping methods for my website which went okay. I only ran into one problem. I had a flat rate of €7.5 installed and then went onto the Service point Delivery shipping method. It looks like this: 
![image](https://user-images.githubusercontent.com/65651442/112743687-c0106400-8f99-11eb-8054-82e7a5fd89d0.png. The problem begins when I add the shipping method free shipment, that looked like this: 
![image](https://user-images.githubusercontent.com/65651442/112743722-fe0d8800-8f99-11eb-8f77-248d34795fac.png). The flat rate and the Service point delivery shipping method of 7,5 worked great together. If you order something you can to see the prices good with no problems. Now that I tried to get free shipment from around €90 to work I had one big problem. If I put the free shipping for our products it will deny any other shipping method. I´d like to have a the option to next to the level and introduce an option to have it deliverd to a parcel pro nearby. Unfortunatly now you can only see free shipping and not the option to chose free delivery above an certain amount. 

The namee is Free shipping and servic point delivery from Sendcloud and we would love to be able to send our products everywhere and just let people choose to pick up for free or get delivered to home for free.

Kind regards,

Wouter

**Comment by juliaamosova** [comment] 2021-04-03 18:21
Hi @Wovami,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-04-03 18:21 UTC
