### ISSUE TITLE
No response, even I proved it that it is an issue.

### ISSUE THREAD

**Issue by sandeshjangam** [woocommerce/woocommerce#24181] opened 2019-07-17 09:47 UTC
Reference - https://github.com/woocommerce/woocommerce/issues/24061

Here is a function I called in a plugin

activate_plugin( 'woocommerce/woocommerce.php', '', false, true );

If anything wrong in the above function then please let me know. Because I am sure that it is correct and verified by other developers too.

If you call this function on fresh installation then It will still throw the error.

Just add this code in your function.php on fresh setup and it will throw an error. Make sure you have WooCommerce installed and not activate.

add_action( 'admin_init', function() {
	activate_plugin( 'woocommerce/woocommerce.php', '', false, true );
});

**Comment by itowhid06** [comment] 2019-07-17 14:04
Can't reproduce! Most likely it's a conflict.

**Comment by rodrigoprimo** [comment] 2019-07-17 18:22
Closing as this is not a support forum. If you find out that you are not able to programmatically activate WooCommerce due to a problem in the plugin itself, please let us know, and we will take a look.

> `activate_plugin( 'woocommerce/woocommerce.php', '', false, true );`

I haven't looked carefully into this, but I wonder if there is a reason why you are passing `true` as the fourth parameter? This parameter is used to prevent calling activation hooks and could explain why WooCommerce tables were not created.

**Closed by rodrigoprimo** 2019-07-17 18:22 UTC

**Comment by achchu93** [comment] 2019-09-15 13:58
This cant be labeled as invalid. because this is not happening, only when activating the woocommerce programatically. This happens when you create a new blog on multisite wordpress also. Wordpress tries to load webhooks before the webhooks table being created.

**Comment by rodrigoprimo** [comment] 2019-09-23 13:35
@achchu93, could you please provide more details? What is the error that you are seeing when creating a new site on a multisite install?
