### ISSUE TITLE
after Woocommerce update settings of taxes can´t be edited 

### ISSUE THREAD

**Issue by ibertrix** [woocommerce/woocommerce#20602] opened 2018-06-21 13:18 UTC
I have upgraded to the latest Woocommerce version. Wordpress is 4.9.6. 

I edited taxes settings yesterday. Now I can´t edit those settings. I have dropped the two tables of woocommerce_tax_rates and woocommerce_tax_rate_locations and no error is shown. I have tried recreate those tables from the last mysql dump where those tables were empty and nothing changes. The weird thing is that the rest of settings seem to be editable.

I use innodb, so no repair table can be issued.

**Comment by rodrigoprimo** [comment] 2018-06-22 10:53
Could you please edit the issue description and include all the relevant information requested in the bug report template (https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md)?

To be able to check your report we will need to know the exact steps to reproduce the problem you are describing and also what do you expected to see and what you are actually seeing. Sharing your system status (on the WP admin go to WooCommerce -> System status) also helps to understand what could be causing this issue.

With just the information you provided I can't reproduce the problem. Editing tax options in `wp-admin/admin.php?page=wc-settings&tab=tax` works as expected on my local environment.

**Comment by ibertrix** [comment] 2018-06-22 11:46
What I expect is that the taxes settings get cleared if I reset the aforementioned two tables from woocommerce but still shows the settings I had in the previous version of Woocommerce (just installed one month ago)

**Comment by rodrigoprimo** [comment] 2018-06-22 13:29
If you delete all rows from `wp_woocommerce_tax_rates` and `wp_woocommerce_tax_rate_locations`, no entries should appear in the three tabs that list tax rates. For example, in the Standard tax rates tab: `/wp-admin/admin.php?page=wc-settings&tab=tax&section=standard`

The tax settings (`/wp-admin/admin.php?page=wc-settings&tab=tax`) are not stored in those two tables. They are stored in a few different WP options in the `wp_options` table.

Closing this issue as it doesn't seem to be a WC bug but instead a support question. Please reopen with more details if I misunderstood your report and you believe you found a WC bug. For support you could try the WP forums: https://wordpress.org/support/plugin/woocommerce. Thanks.

**Closed by rodrigoprimo** 2018-06-22 13:29 UTC
Labels: status: needs feedback

**Comment by ibertrix** [comment] 2018-06-22 17:43
Sorry, but I´m reopening this. 

I have installed a fresh Wordpress install. Same theme, no content, same plugins.

Clean install has no entries under /wp-admin/admin.php?page=wc-settings&tab=tax&section=standard

My install has one entry that I don´t really understand where it comes from (I have never configured that section):

CÃ³digo del paÃ­s | CÃ³digo de provincia | CÃ³digo postal | Ciudad | Tarifa % | Nombre del impuesto | Prioridad | Compuesto | EnvÃ­o | Clase de   impuesto
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
ES | SA | 35002 |   | 21 | SA Tax | 1 | 0 | 1 |   |  

Also, which wp_options entries are managed by /wp-admin/admin.php?page=wc-settings&tab=tax ? I think this is key in order to know whether there is an issue inheriting information coming from previous Woocommerce version

**Comment by ibertrix** [comment] 2018-06-22 18:16
ok, I found myself the woocommerce_taxes_* options in wp_options.

I have changed woocommerce_tax_total_display to itemized but in the backend remains as before (total option is shown).

If I remove that entry in wp-options nothing changes.

Definitely there is something wrong.

**Comment by ibertrix** [comment] 2018-06-23 13:52
More information. I have realized that the issue was that enabling "automatic taxes" disable the rest of options under the taxes tab. Not sure if that´s intended but it´s totally confusing.
