### ISSUE TITLE
Bug report the sky is fallign help!

### ISSUE THREAD

**Issue by FreshFarms** [woocommerce/woocommerce#25310] opened 2019-12-24 08:50 UTC
Issues with connection Please help

**Comment by juliaamosova** [comment] 2019-12-24 09:51
Hi @FreshFarms,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only with clear steps to reproduce the issue. 

I am closing this issue as it is incomplete. You also opened 6 more identical issues that have no description which discredits this current issue. 

Other 6 issues opened: 

https://github.com/woocommerce/woocommerce/issues/25304
https://github.com/woocommerce/woocommerce/issues/25305
https://github.com/woocommerce/woocommerce/issues/25306
https://github.com/woocommerce/woocommerce/issues/25307
https://github.com/woocommerce/woocommerce/issues/25308
https://github.com/woocommerce/woocommerce/issues/25309

The issues above will be closed as well due to being incomplete.

**Closed by juliaamosova** 2019-12-24 09:51 UTC
