### ISSUE TITLE
Shopping Cart Update basket Disabled

### ISSUE THREAD

**Issue by JeremaineJohnson** [woocommerce/woocommerce#26463] opened 2020-05-11 22:48 UTC
The shopping cart update basket is disabled and the quantity +/- icon does not update the price. However, when the quantity is typed into the textbox the "update Basket" is enabled.

http://www.syncterfacemedia.com/cart/

![image](https://user-images.githubusercontent.com/39373122/81619614-e4933a00-93e1-11ea-9bb2-ecdd2c48f256.png)

**Comment by juliaamosova** [comment] 2020-05-12 00:29
Hi @JeremaineJohnson,

Thank you for raising the issue. 

Do you have many plugins installed on your site? I see that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by JeremaineJohnson** [comment] 2020-05-12 07:38
Hi Julia,
   
  
  
   
  
  
   Thank you for the quick response. I have downloaded the store front, when I activated it, it replaces my current theme and many of my object are missing. Is there a way to use the storefront theme only for the shop?
   
  
  
   
  
  
   Regards,
   
  
  
   
  
  
   Jeremaine
   
  
  
   On 12 May 2020 at 01:29 Julia Amosova <notifications@github.com> wrote: 
   
   
   
   Hi @JeremaineJohnson,
   Thank you for raising the issue.
   Do you have many plugins installed on your site? I see that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.
   If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-05-12 14:01
Hi @JeremaineJohnson,

Thanks for your follow-up. 

>   Thank you for the quick response. I have downloaded the store front, when I activated it, it replaces my current theme and many of my object are missing. Is there a way to use the storefront theme only for the shop?

There is no way to use Storefront only for the shop but not for the rest of the site. It works like any other theme and applied to the entire site. 

I offered you to try Storefront to see if the issue with `+/-` not working is resolved for you with Storefront. Is it resolved? If so, it means that your current theme is not working as expected in which case I recommend you contacting theme developer and ask them to fix it.

**Comment by JeremaineJohnson** [comment] 2020-05-12 14:06
Hi Julia,

 

Makes sense, yes, the issue was resolved when I used the storefront theme. Thank you very much.

 

I have another issue with I found to be out there also, on the product listing page, there tends to be some misalignment on the page. Very strange. Have you seen this before?  http://www.syncterfacemedia.com/bookstore/page/2/

 




 

Regards,

 

Jeremaine Johnson

Lead Consultant

**Comment by juliaamosova** [comment] 2020-05-12 14:16
>Makes sense, yes, the issue was resolved when I used the storefront theme. Thank you very much.

Great, thanks for confirming. 

>I have another issue with I found to be out there also, on the product listing page, there tends to be some misalignment on the page. Very strange. Have you seen this before?  http://www.syncterfacemedia.com/bookstore/page/2/

This is a separate issue so please open another thread if needed. However, I would check the same - if it displays well in Storefront. 

I am closing this thread since the original issue/question is resolved.

**Closed by juliaamosova** 2020-05-12 14:16 UTC
Labels: status: needs feedback
