### ISSUE TITLE
woocommerce_rest_authentication_error on localhost

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#20815] opened 2018-07-16 12:03 UTC
**Describe the bug**
I get **woocommerce_rest_authentication_error** for all rest api requests on my **localhost** server.
It works just fine on live site and have worked before for localhost on another computer.

The error is a signature mismatch ..

**To Reproduce**
1. Create a GET request to http://localhost:9001/wp-json/wc/v2/system_status using POSTMAN
2. Generate ck_xxx & cs_xxx in woocommerce settings & copy them
3. Select OAuth 1.0 authorization type in postman
4. Paste consumer key & consumer secret into postman authorization fields
5. Select signature method HMAC-SHA1 & send request.

**Screenshots**

**Api Enabled:**
![skjermbilde 2018-07-16 kl 13 55 18](https://user-images.githubusercontent.com/4593184/42757395-3180d316-8900-11e8-8397-a46580bd8ba8.png)

**Key created:**
![skjermbilde 2018-07-16 kl 13 55 30](https://user-images.githubusercontent.com/4593184/42757411-4153a854-8900-11e8-828d-2a36767e9cf9.png)

**Pasted to Postman**
![skjermbilde 2018-07-16 kl 13 56 37](https://user-images.githubusercontent.com/4593184/42757418-4fc1d6ae-8900-11e8-9211-13137be7dac9.png)

**Pretty permalinks enabled:**
![skjermbilde 2018-07-16 kl 14 06 43](https://user-images.githubusercontent.com/4593184/42757798-8f6a8c32-8901-11e8-83e8-0a5370129c40.png)

**Response**
![skjermbilde 2018-07-16 kl 13 58 49](https://user-images.githubusercontent.com/4593184/42757448-7487a31a-8900-11e8-9d8f-d8a33bc31788.png)

Response as Plain text:
```
{
    "code": "woocommerce_rest_authentication_error",
    "message": "Ugyldig signatur - oppgitt signatur samsvarer ikke.",
    "data": {
        "status": 401
    }
}
```

**Plugins activated:**
![skjermbilde 2018-07-16 kl 13 57 03](https://user-images.githubusercontent.com/4593184/42757494-92fc8ba8-8900-11e8-9472-285a195879c0.png)

**Expected behavior**
Should be authorized

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: http://localhost:9001
Site URL: http://localhost:9001
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nb_NO
External object cache: –

### Server Environment ###

Server Info: nginx/1.13.9
PHP Version: 7.1.16 - Vi anbefaler å bruke PHP versjon 7.2 eller nyere for større ytelse og sikkerhet. Hvordan oppgradere PHP til nyere versjon
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
LibreSSL/2.0.20

SUHOSIN Installed: –
MySQL Version: 5.7.22
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: gs_
MaxMind GeoIP Database: ✔
Total database størrelse: 7.35MB
Database data størrelse: 5.47MB
Database indeks størrelse: 1.88MB
gs_woocommerce_sessions: Data: 0.02MB + Indeks: 0.02MB
gs_woocommerce_api_keys: Data: 0.02MB + Indeks: 0.03MB
gs_woocommerce_attribute_taxonomies: Data: 0.02MB + Indeks: 0.02MB
gs_woocommerce_downloadable_product_permissions: Data: 0.02MB + Indeks: 0.05MB
gs_woocommerce_order_items: Data: 0.02MB + Indeks: 0.02MB
gs_woocommerce_order_itemmeta: Data: 0.02MB + Indeks: 0.03MB
gs_woocommerce_tax_rates: Data: 0.02MB + Indeks: 0.06MB
gs_woocommerce_tax_rate_locations: Data: 0.02MB + Indeks: 0.03MB
gs_woocommerce_shipping_zones: Data: 0.02MB + Indeks: 0.00MB
gs_woocommerce_shipping_zone_locations: Data: 0.02MB + Indeks: 0.03MB
gs_woocommerce_shipping_zone_methods: Data: 0.02MB + Indeks: 0.00MB
gs_woocommerce_payment_tokens: Data: 0.02MB + Indeks: 0.02MB
gs_woocommerce_payment_tokenmeta: Data: 0.02MB + Indeks: 0.03MB
gs_woocommerce_log: Data: 0.02MB + Indeks: 0.02MB
gs_commentmeta: Data: 0.02MB + Indeks: 0.03MB
gs_comments: Data: 0.02MB + Indeks: 0.08MB
gs_links: Data: 0.02MB + Indeks: 0.02MB
gs_options: Data: 0.17MB + Indeks: 0.02MB
gs_postmeta: Data: 2.48MB + Indeks: 0.03MB
gs_posts: Data: 1.44MB + Indeks: 0.06MB
gs_termmeta: Data: 0.02MB + Indeks: 0.03MB
gs_terms: Data: 0.02MB + Indeks: 0.03MB
gs_term_relationships: Data: 0.02MB + Indeks: 0.02MB
gs_term_taxonomy: Data: 0.02MB + Indeks: 0.03MB
gs_usermeta: Data: 0.02MB + Indeks: 0.03MB
gs_users: Data: 0.02MB + Indeks: 0.05MB
gs_wc_download_log: Data: 0.02MB + Indeks: 0.03MB
gs_wc_webhooks: Data: 0.02MB + Indeks: 0.02MB
wp_ap_activity: Data: 0.02MB + Indeks: 0.05MB
wp_ap_qameta: Data: 0.02MB + Indeks: 0.00MB
wp_ap_reputations: Data: 0.02MB + Indeks: 0.03MB
wp_ap_subscribers: Data: 0.02MB + Indeks: 0.03MB
wp_ap_views: Data: 0.02MB + Indeks: 0.02MB
wp_ap_votes: Data: 0.02MB + Indeks: 0.02MB
wp_commentmeta: Data: 0.02MB + Indeks: 0.03MB
wp_comments: Data: 0.02MB + Indeks: 0.09MB
wp_links: Data: 0.02MB + Indeks: 0.02MB
wp_options: Data: 0.11MB + Indeks: 0.02MB
wp_postmeta: Data: 0.09MB + Indeks: 0.06MB
wp_posts: Data: 0.06MB + Indeks: 0.06MB
wp_termmeta: Data: 0.02MB + Indeks: 0.03MB
wp_terms: Data: 0.02MB + Indeks: 0.03MB
wp_term_relationships: Data: 0.02MB + Indeks: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Indeks: 0.03MB
wp_usermeta: Data: 0.02MB + Indeks: 0.03MB
wp_users: Data: 0.02MB + Indeks: 0.05MB
wp_wc_download_log: Data: 0.02MB + Indeks: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Indeks: 0.05MB
wp_woocommerce_log: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_sessions: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Indeks: 0.00MB
wp_woocommerce_tax_rates: Data: 0.02MB + Indeks: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Indeks: 0.03MB
wp_wpc_comments_subscription: Data: 0.00MB + Indeks: 0.00MB
wp_wpc_phrases: Data: 0.00MB + Indeks: 0.00MB
wp_wpc_users_voted: Data: 0.00MB + Indeks: 0.01MB

### Post Type Counts ###

acf: 3
acf-field: 10
acf-field-group: 3
attachment: 4
custom_css: 1
globe_faq: 4
nav_menu_item: 4
page: 4
post: 5
revision: 64

### Security ###

Secure connection (HTTPS): ❌
					Butikken din bruker ikke HTTPS. Ler mer om HTTPS og SSL sertifikater.
Hide errors from visitors: ❌Feilmeldinger skal ikke vised til besøkende.

### Active Plugins (1) ###

WooCommerce: av Automattic – 3.4.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Butikkbase: ❌ Side ikke satt
Handlekurv: ❌ Side ikke satt
Til kassen: ❌ Side ikke satt
Min konto: ❌ Side ikke satt
Vilkår og betingelser: ❌ Side ikke satt

### Theme ###

Name: Dev
Version: 1.0
Author URL: https://
Child Theme: ❌ – Hvis du endrer WooCommerce eller et foreldertema du ikke selv har bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ❌ Ikke oppgitt

### Templates ###

Overrides: –
```
</details>

**Comment by steffanhalv** [comment] 2018-07-16 12:12
Example using axios:

```
Request URL: http://localhost:9001/wp-json/wc/sp/v1/actions/discounts?oauth_consumer_key=ck_XXX...51100c11&oauth_nonce=51erx2&oauth_signature=JQrkaktp%2B2BRoVdojOJGTBCuBzc%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1531743038&oauth_version=1.0
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 127.0.0.1:9001
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization, Content-Type
Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Origin: http://localhost:8070
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Cache-Control: no-store, no-cache, must-revalidate
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Date: Mon, 16 Jul 2018 12:10:38 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Link: <http://localhost:9001/wp-json/>; rel="https://api.w.org/"
Pragma: no-cache
Server: nginx/1.13.9
Set-Cookie: PHPSESSID=hq7h79iuqducl1cjks6b4975ep; path=/
Transfer-Encoding: chunked
Vary: Origin
X-Content-Type-Options: nosniff
X-Powered-By: PHP/7.1.16
X-Robots-Tag: noindex
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: nb,no;q=0.9,en;q=0.8,en-US;q=0.7,de;q=0.6,nn;q=0.5,da;q=0.4,es;q=0.3
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:9001
Origin: http://localhost:8070
Pragma: no-cache
Referer: http://localhost:8070/?dev_server=http://localhost:9001&username=haagen_no&password=XXX
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
oauth_consumer_key: ck_XXX...e6c51100c11
oauth_nonce: 51erx2
oauth_signature: JQrkaktp+2BRoVdojOJGTBCuBzc=
oauth_signature_method: HMAC-SHA1
oauth_timestamp: 1531743038
oauth_version: 1.0
```

**Comment by rodrigoprimo** [comment] 2018-07-17 14:14
The WC API works for me on my local environment. On a quick look at the issue description, it seems to me that the problem is that you are selecting "OAuth 1.0" instead of "Basic Auth" as the authentication method (I use Insomnia instead of Postman so the names might be slightly different).

If you have more questions please check the documentation: https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

Closing this issue for now. Please leave a comment if I missed something.

**Closed by rodrigoprimo** 2018-07-17 14:14 UTC

**Comment by steffanhalv** [comment] 2018-07-17 18:22
@rodrigoprimo I think you missunderstood.

Im very into the rest api. Basic auth is not valid for http://, OAuth 1.0 is required.
Basic auth is valid for https yes, but thats not what im asking about.

Please take a look once more. ;)

**Comment by peterfabian** [comment] 2018-07-19 15:29
Hi @steffanhalv 

I wasn't able to reproduce your error:
<img width="1568" alt="oatuh_rest_api" src="https://user-images.githubusercontent.com/2207451/42952042-db3d92ee-8b77-11e8-89d3-6cfde9fa626a.png">

As you maybe saw from the code itself, the following inputs are used to verify signature:
    - consumer secret
    - method (GET)
    - consumer key
    - oauth_nonce
    - oauth_signature_method
    - oauth_timestamp
    - oauth_version

If you have incorrect consumer key, the error message is different, so we can rule that one out. Similarly for oauth_signature_method.

Out of the rest of them, there are not too many that might be mismatched. I would check time on your server vs your local machine. 
Have you tried sending a request with empty timestamp? I guess 10 is not a valid value.
Also, have you tried to disable all plugins except for WooCommerce?

**Comment by steffanhalv** [comment] 2018-07-19 15:38
Thx for comment!

I checked the server time and I think it matched.

I will try debugging with xdebug when I get time and see if I can find whats wrong.

**Comment by peterfabian** [comment] 2018-07-19 15:43
When thinking about it now, might be the port that breaks it?
the URL is also hashed together with the items above and on the server side, it takes the `get_home_url()` result, which uses value of option 'home'... but postman probably (correctly) includes port number when creating the oauth_signature. 

According to the [spec](https://oauth.net/core/1.0/):
> Unless specified, URL scheme and authority MUST be lowercase and include the port number; http default port 80 and https default port 443 MUST be excluded

So maybe this is the problem. Can you maybe confirm this?

**Comment by steffanhalv** [comment] 2018-07-19 16:11
Oh, that could possibly be the error.

I can try changing my hostname to something else without portnumber and see if it works.

Im out of office for now, but I can test tomorrow. If thats the issue perhaps we can replace get_home_url with base url.

**Comment by rodrigoprimo** [comment] 2018-07-19 18:31
> @rodrigoprimo I think you missunderstood.

@steffanhalv, I had misunderstood the issue indeed :)

 Thanks for clarifying it. Good to see that @peterfabian was able to help you.

**Comment by steffanhalv** [comment] 2018-07-20 10:44
@rodrigoprimo @peterfabian 
Finally I found the error.

It was a bad configuration of try_files in nginx:

**WRONG**
` try_files $uri $uri/ /index.php?q=$uri&$args;
`

**CORRECT**
`try_files $uri $uri/ /index.php$is_args$args;
`

After changing that everything works perfectly ^^

**Comment by jesusmariajurado** [comment] 2021-12-09 15:33
The URL to connect must be the same configured in Wordpress > Settings > Site URL
