### ISSUE TITLE
Backorders allowed is not working correctly

### ISSUE THREAD

**Issue by ashraffarag** [woocommerce/woocommerce#25415] opened 2020-01-16 14:41 UTC
**Describe the bug**

We have all our products having value as "0" for "Backorders allowed?" yet we started receiving back orders for out of stock products.

 
**To Reproduce**
1. Go to Products
2. Choose any Variable Product
3. Go to its Variation and expand the variation 
4. Value in Allow backorders? is already set to : Do Not Allow 

**Screenshots**
![Back_Order](https://user-images.githubusercontent.com/59966260/72533837-7d73d780-387e-11ea-9019-705beb3e4179.png)
![Product_1](https://user-images.githubusercontent.com/59966260/72533852-84024f00-387e-11ea-9b54-8b1a805cbd5a.png)
![Product_2](https://user-images.githubusercontent.com/59966260/72533863-8b295d00-387e-11ea-81e8-4554d0f91ef3.png)

**Expected behavior**

No back order get created for out of stock items 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Production
```
`
### WordPress Environment ###

WordPress address (URL): https://nomadstory.com
Site address (URL): https://nomadstory.com
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: ❌ 5.3 - There is a newer version of WordPress available (5.3.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.5
PHP Version: 7.3.4-1+ubuntu16.04.1+deb.sury.org+3
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.6-MariaDB-1:10.4.6+maria~xenial
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 41.45MB
Database Data Size: 25.97MB
Database Index Size: 15.48MB
wp_woocommerce_sessions: Data: 0.31MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 3.02MB + Index: 6.14MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_instagram_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_instagram_tags_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.20MB + Index: 0.19MB + Engine InnoDB
wp_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 8.16MB + Index: 4.05MB + Engine InnoDB
wp_posts: Data: 7.05MB + Index: 3.38MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.03MB + Index: 0.23MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_usermeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woof_query_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_ywcars_messagemeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ywcars_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Gravity Forms: by rocketgenius – 2.4.6.15
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.2

Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 1.9.1
Cookie Notice: by dFactory – 1.2.48
WC Price Filter Compatible with multi currency: by Mustafa Aboulfootuh – 1.0
Designer and Collection Widget: by Mustafa Aboulfootuh – 1.0
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Instagram Shop Feed Extension for WooCommerce: by WebKul – 1.0.0 – Not tested with the active version of WooCommerce
Intercom: by Intercom – 2.6.3
Mailchimp for WooCommerce: by Mailchimp – 2.3 – Not tested with the active version of WooCommerce
Max Mega Menu: by megamenu.com – 2.7.3
WooCommerce Onsale Page: by wpgenie – 1.0.10 – Not tested with the active version of WooCommerce
Product Card Widget: by Mustafa Aboulfootuh – 1.0
PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.169

InXpress Shipping Extension: by InXpress – 3.0.5 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.22.0
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.6
WooCommerce Multi-currency: by TIV.NET INC – 1.16.0 – Not tested with the active version of WooCommerce
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.30 – 4.1.31 is available
WooCommerce Social Login: by SkyVerge – 2.6.5 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.8.0 – 3.8.1 is available
Yoast SEO Premium: by Team Yoast – 12.6.1
WP Mail SMTP: by WPForms – 1.7.1
Yoast SEO: WooCommerce: by Team Yoast – 12.4
YITH Advanced Refund System for WooCommerce Premium: by YITH – 1.1.8

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Jetpack by WordPress.com: by Automattic – 7.9.1
Show Current Template: by JOTAKI Taisuke – 0.3.0
Smush: by WPMU DEV – 3.3.2
WooCommerce Services: by Automattic – 1.22.1 – 1.22.2 is available

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /just-in/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #8166 - /terms-conditions/

### Theme ###

Name: Storefront Nomad Child
Version: 2.5.1
Author URL: https://robustastudio.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.1 – 2.5.3 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-nomad-child/woocommerce/archive-product.php
storefront-nomad-child/woocommerce/cart/cart-totals.php
storefront-nomad-child/woocommerce/cart/cart.php
storefront-nomad-child/woocommerce/cart/mini-cart.php
storefront-nomad-child/woocommerce/cart/proceed-to-checkout-button.php
storefront-nomad-child/woocommerce/checkout/cart-errors.php
storefront-nomad-child/woocommerce/checkout/form-billing.php
storefront-nomad-child/woocommerce/checkout/form-checkout.php
storefront-nomad-child/woocommerce/checkout/form-coupon.php
storefront-nomad-child/woocommerce/checkout/form-shipping.php
storefront-nomad-child/woocommerce/checkout/payment.php
storefront-nomad-child/woocommerce/checkout/review-order.php
storefront-nomad-child/woocommerce/checkout/thankyou.php
storefront-nomad-child/woocommerce/content-single-product.php
storefront-nomad-child/woocommerce/emails/customer-completed-order.php
storefront-nomad-child/woocommerce/emails/customer-new-account.php
storefront-nomad-child/woocommerce/emails/customer-on-hold-order.php
storefront-nomad-child/woocommerce/emails/customer-processing-order.php
storefront-nomad-child/woocommerce/emails/customer-refunded-order.php
storefront-nomad-child/woocommerce/emails/customer-reset-password.php
storefront-nomad-child/woocommerce/emails/email-footer.php
storefront-nomad-child/woocommerce/emails/email-order-details.php
storefront-nomad-child/woocommerce/global/quantity-input.php
storefront-nomad-child/woocommerce/loop/orderby.php
storefront-nomad-child/woocommerce/myaccount/dashboard.php
storefront-nomad-child/woocommerce/myaccount/form-add-payment-method.php
storefront-nomad-child/woocommerce/myaccount/form-edit-account.php
storefront-nomad-child/woocommerce/myaccount/form-edit-address.php
storefront-nomad-child/woocommerce/myaccount/form-login.php
storefront-nomad-child/woocommerce/myaccount/form-lost-password.php
storefront-nomad-child/woocommerce/myaccount/form-reset-password.php
storefront-nomad-child/woocommerce/myaccount/lost-password-confirmation.php
storefront-nomad-child/woocommerce/myaccount/my-address.php
storefront-nomad-child/woocommerce/myaccount/navigation.php
storefront-nomad-child/woocommerce/myaccount/orders.php
storefront-nomad-child/woocommerce/myaccount/payment-methods.php
storefront-nomad-child/woocommerce/myaccount/view-order.php
storefront-nomad-child/woocommerce/notices/error.php
storefront-nomad-child/woocommerce/order/order-details-customer.php
storefront-nomad-child/woocommerce/order/order-details-item.php
storefront-nomad-child/woocommerce/order/order-details.php
storefront-nomad-child/woocommerce/product-searchform.php
storefront-nomad-child/woocommerce/single-product/add-to-cart/simple.php
storefront-nomad-child/woocommerce/single-product/add-to-cart/variable.php
storefront-nomad-child/woocommerce/single-product/product-image.php
storefront-nomad-child/woocommerce/single-product/tabs/tabs.php


### Social Login ###

Facebook: ✔ Available
Twitter: Disabled
Google: ✔ Available
Amazon: Disabled
Linkedin: Disabled
Paypal: Disabled
Instagram: Disabled
Disqus: Disabled
Yahoo: Disabled
Vkontakte: Disabled

### Multi-currency ###

currency_symbol_AED: (AED)
currency_symbol_AUD: $
currency_symbol_BHD: (BHD)
currency_symbol_BRL: R$
currency_symbol_CAD: C$
currency_symbol_CNY: ¥
currency_symbol_EGP: (EGP)
currency_symbol_EUR: €
currency_symbol_GBP: £
currency_symbol_IDR: Rp
currency_symbol_INR: ₹
currency_symbol_JOD: (JOD)
currency_symbol_JPY: ¥
currency_symbol_KWD: (KWD)
currency_symbol_MXN: $
currency_symbol_MYR: RM
currency_symbol_OMR: (OMR)
currency_symbol_QAR: (QAR)
currency_symbol_SAR: (SAR)
currency_symbol_SGD: $
currency_symbol_THB: ฿
currency_symbol_TRY: ₺
currency_symbol_USD: $
currency_symbol_ZAR: R
enabled_currencies: a:1:{i:0;s:3:"USD";}
fee_percent: 0
fixed_rate_AED: 1
fixed_rate_AUD: 1
fixed_rate_BHD: 1
fixed_rate_BRL: 1
fixed_rate_CAD: 1.32
fixed_rate_CNY: 1
fixed_rate_EGP: 17
fixed_rate_EUR: 0.9
fixed_rate_GBP: 1
fixed_rate_IDR: 1
fixed_rate_INR: 1
fixed_rate_JOD: 1
fixed_rate_JPY: 1
fixed_rate_KWD: 1
fixed_rate_MXN: 1
fixed_rate_MYR: 1
fixed_rate_OMR: 1
fixed_rate_QAR: 1
fixed_rate_SAR: 1
fixed_rate_SGD: 1
fixed_rate_THB: 1
fixed_rate_TRY: 1
fixed_rate_ZAR: 1
log_level: error
price_charm: 0
price_format_AED: %2$s %1$s
price_format_AUD: %1$s %2$s
price_format_BHD: %2$s %1$s
price_format_BRL: %1$s %2$s
price_format_CAD: %1$s %2$s
price_format_CNY: %1$s %2$s
price_format_EGP: %2$s %1$s
price_format_EUR: %1$s %2$s
price_format_GBP: %1$s %2$s
price_format_IDR: %1$s %2$s
price_format_INR: %1$s %2$s
price_format_JOD: %2$s %1$s
price_format_JPY: %1$s %2$s
price_format_KWD: %2$s %1$s
price_format_MXN: %1$s %2$s
price_format_MYR: %1$s %2$s
price_format_OMR: %2$s %1$s
price_format_QAR: %2$s %1$s
price_format_SAR: %2$s %1$s
price_format_SGD: %1$s %2$s
price_format_THB: %1$s %2$s
price_format_TRY: %1$s %2$s
price_format_USD: %1$s %2$s
price_format_ZAR: %1$s %2$s
rates: array(168)
rates_provider_id: Currencylayer
rates_retrieval_status: 1
rates_timestamp: 1579141505
round_to: 0.01
version: 1.16.0

### Action Scheduler ###

Complete: 3,183
Oldest: 2019-12-16 14:41:38 +0000
Newest: 2020-01-16 14:39:34 +0000

Pending: 2
Oldest: 2020-01-16 15:05:35 +0000
Newest: 2020-01-16 15:05:35 +0000

Canceled: 82
Oldest: 2019-12-16 20:23:04 +0000
Newest: 2020-01-16 14:01:17 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment] 2020-01-16 19:10
Hi @ashraffarag,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

My settings:

![var1](https://user-images.githubusercontent.com/19143190/72554889-80c58e00-3893-11ea-8e66-073e5aa4c58c.jpg)

Front-end:

![var2](https://user-images.githubusercontent.com/19143190/72554916-891dc900-3893-11ea-9850-a23a12d51ce5.jpg)

I see that you mentioned that you deactivated all the plugins except for WooCommerce. However, I always like to verify that is from your screenshots and System Status Report - it looks like you have many plugins activated which could cause conflict. 

If you haven't done it yet, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by thomas-zg** [comment] 2020-01-22 22:02
Same problem, I made a manual order and I'm adding 8 items of the product. Stock goes to -8 while the backorder is not allowed on the variation.
<img width="265" alt="grafik" src="https://user-images.githubusercontent.com/25877146/72938382-2b91ec80-3d6b-11ea-8e19-a0c9023140a7.png">

<img width="618" alt="grafik" src="https://user-images.githubusercontent.com/25877146/72938429-419fad00-3d6b-11ea-9869-4e347d301d70.png">

**Comment by thomas-zg** [comment] 2020-01-22 22:37
@juliaamosova to reproduce:
1) Setup a variable product, stock is handled on level variation, do not allow backorders and set the stock to 0.
2) Add a manual order, choose the variation with stock 0. The product will be added and the stock will be reduced by the given amount.

There is no check, if backorders are allowed or not. This happens on a clean installation with WC 3.9 and WC Admin 0.24 installed.

<img width="658" alt="grafik" src="https://user-images.githubusercontent.com/25877146/72940921-14093280-3d70-11ea-8a0c-93a116e14314.png">

**Comment by juliaamosova** [comment] 2020-01-28 17:33
@thomas-zg thanks for providing more details. I can reproduce the issue now indeed when placing a manual order:

A variation where stock is managed at the level of the variation with backorders not allowed:

![var1](https://user-images.githubusercontent.com/19143190/73288895-b81d2e80-41f3-11ea-9d1b-ec56464520c1.jpg)

Placing manual order - I can select variation with zero stock and backorders not allowed:

![var2](https://user-images.githubusercontent.com/19143190/73288944-c8cda480-41f3-11ea-8614-98e0c80d7f59.jpg)

Order is created - stock is being reduced:

![var3](https://user-images.githubusercontent.com/19143190/73288995-d71bc080-41f3-11ea-9561-990481fdc055.jpg)

Variation now has a negative stock even though backorders were not allowed:

![var4](https://user-images.githubusercontent.com/19143190/73289031-e569dc80-41f3-11ea-8484-dd4b83903311.jpg)

The author of this issue is saying, however, that it is possible to place orders at the front-end for the products that have zero stock with backorders not allowed. It is different from placing the order manually so these 2 issues seem to be different. Can you please confirm @ashraffarag?

**Comment by juliaamosova** [comment] 2020-01-29 12:41
@thomas-zg I created a separate issue to document the bug you reported: https://github.com/woocommerce/woocommerce/issues/25518.

@ashraffarag, as a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-01-29 12:41 UTC
Labels: can't reproduce, status: needs feedback
