### ISSUE TITLE
Serve Scaled Images Woocommerce product thumbnails problem

### ISSUE THREAD

**Issue by bakoline** [woocommerce/woocommerce#25642] opened 2020-02-12 09:00 UTC
I was trying to fix Gtmetrix “Serve scaled images” problem and here's what happens... 

- Gtmetrix says that my product image thumbnails are scalled via css to 121px
- When I set width 121 from "customizing/woocommerce/product images/" it fixes Gtmetrix problem, but my images on /shop/ catalogue page are blurred.

Screenshot 1: https://imgur.com/a/JGfEwa9
Screenshot 2: https://imgur.com/a/RQhgC0n

I have no idea and couldn't find anything about this issue, how to set product image thumbnail width to 121 and /shop/ catalogue images width to 400

I would appreciate any help

**Comment by claudiosanches** [comment] 2020-02-16 21:42
Hello,

Those are the correct settings for it: https://imgur.com/a/JGfEwa9
The "Thumbnail width" is what you should update if you want to reduce the size of the images in the catalog, if 121 gets blurred maybe is because something did go wrong while generating the new thumbnails or maybe is just too small for your theme, it's impossible to say just by screenshots, there's no way to inspect it.
Anyway, while our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-02-16 21:42 UTC
