### ISSUE TITLE
registering custom endpoints in user area result in 404 in WooCommerce 5.0.0 (works in 4.5.2)

### ISSUE THREAD

**Issue by Thomas-1985** [woocommerce/woocommerce#29245] opened 2021-02-27 18:11 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have a custom plugin that registers custom endpoints in the user area like here:
https://webkul.com/blog/woocommerce-account-custom-endpoint/
In 4.5.2 this works (the endpoints are registered and once i click on it, the page linked to it is loaded. However in 5.0.0 this doesn't work.

**Expected behavior**
I would expect this works exactly like in 4.5.2

**Actual behavior**
-The endpoint is shown in the user area menu with the correct url
-Once i click on it i get the WordPress 404 page
-Flushing the permalinks (settings -> permalinks -> click on save) doesn't work

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Register a custom endpoint in the user area with WooCommerce 4.5.2
2. Verify it works
3. Upgrade to 5.0.0
4. Try clicking the custom endpoint

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able t### WordPress Environment ###

WordPress address (URL): https://wwwtest.mydomain.test
Site address (URL): https://wwwtest.mydomain.test
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: ❌ 5.5.3 - Es ist eine neuere Version von WordPress verfügbar (5.6.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.15
PHP Post Max Size: 100 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.44-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 2690.46MB
Datenbank-Datengröße: 2201.83MB
Datenbank-Indexgröße: 488.63MB
wp_woocommerce_sessions: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Daten: 0.30MB + Index: 0.33MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_duplicator_pro_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_content_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_core_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_flags: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_languages_translations: Daten: 0.10MB + Index: 0.11MB + Engine MyISAM
wp_icl_locale_map: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_message_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_mo_files_domains: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_reminders: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_strings: Daten: 5.80MB + Index: 4.38MB + Engine MyISAM
wp_icl_string_batches: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Daten: 0.07MB + Index: 0.03MB + Engine MyISAM
wp_icl_string_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_translations: Daten: 4.06MB + Index: 2.23MB + Engine MyISAM
wp_icl_string_urls: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Daten: 1.13MB + Index: 0.09MB + Engine MyISAM
wp_icl_translate_job: Daten: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_icl_translations: Daten: 2.50MB + Index: 4.69MB + Engine MyISAM
wp_icl_translation_batches: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translation_downloads: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Daten: 1.73MB + Index: 0.75MB + Engine MyISAM
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_album: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_gallery: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_pictures: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 14.13MB + Index: 0.19MB + Engine InnoDB
wp_pantheon_sessions: Daten: 24.55MB + Index: 31.03MB + Engine InnoDB
wp_postmeta: Daten: 353.89MB + Index: 179.53MB + Engine InnoDB
wp_posts: Daten: 1537.56MB + Index: 23.84MB + Engine InnoDB
wp_statistics_exclusions: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_statistics_search: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_useronline: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_visit: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_stream: Daten: 16.55MB + Index: 20.13MB + Engine InnoDB
wp_stream_meta: Daten: 55.59MB + Index: 76.78MB + Engine InnoDB
wp_termmeta: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 14.55MB + Index: 8.47MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 1.11MB + Index: 0.11MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 1.52MB + Index: 1.16MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Daten: 2.27MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Daten: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Daten: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Daten: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Daten: 1.02MB + Index: 0.33MB + Engine InnoDB
wp_wftrafficrates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woof_query_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfb_cats: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfb_files: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfb_files_id3: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfm_backup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmelon_advbedit_temp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmfs_queue: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmm_subscribers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpsmtp_logs: Daten: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Daten: 0.05MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Daten: 40.08MB + Index: 52.39MB + Engine InnoDB
wp_wps_key: Daten: 4.33MB + Index: 3.34MB + Engine InnoDB
wp_wps_object_term: Daten: 2.17MB + Index: 6.39MB + Engine InnoDB
wp_wps_object_type: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Daten: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wps_user_agent: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wsal_metadata: Daten: 19.05MB + Index: 33.16MB + Engine InnoDB
wp_wsal_occurrences: Daten: 2.02MB + Index: 3.03MB + Engine InnoDB
wp_wsal_options: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_sessions: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Daten: 67.61MB + Index: 29.56MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 0.08MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Daten: 4.50MB + Index: 4.02MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

alora_faq: 8
alora_portfolio: 16
attachment: 41979
custom_css: 1
flamingo_contact: 1241
flamingo_inbound: 1249
ml-slide: 44
ml-slider: 5
nav_menu_item: 80
ngg_gallery: 1
ngg_pictures: 3
oembed_cache: 22
page: 87
post: 6
product: 8504
revision: 1148
slide: 8
theme4press_elastic: 3
wfcm_file_event: 2083
wp-rest-api-log: 81698
wpcf7_contact_form: 4
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (46) ###

WPML Multilingual CMS: von OnTheGoSystems – 4.4.9
Native PHP Sessions for WordPress: von Pantheon – 1.2.1
Honeypot for Contact Form 7: von Nocean – 1.14.1
Contact Form 7: von Takayuki Miyoshi – 5.3.2
Cookie Notice: von dFactory – 1.3.2
Display Posts: von Bill Erickson – 3.0.2
Yoast Duplicate Post: von Enrico Battocchi & Team Yoast – 3.2.6
Duplicator Pro: von Snap Creek – 4.0.2
Duplicator Pro: von Snap Creek – 4.0.2
Envato Market: von Envato – 2.0.6
Flamingo: von Takayuki Miyoshi – 2.2.1
Health Check & Troubleshooting: von Die WordPress.org-Community – 1.4.5
OMGF: von Daan (from Fast FW Press) – 4.2.4
Limit Login Attempts Reloaded: von Limit Login Attempts Reloaded – 2.19.0
Meta Generator and Version Info Remover: von Pankaj Kumar Mondal – 11.0
MetaSlider: von MetaSlider – 3.19.1
PHP native password hash: von Ayesh Karunaratne – 2.1
Shariff Wrapper: von Jan-Peter Lambeck & 3UU – 4.6.5
Stream: von XWP – 3.6.0
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 2.16.46.24

Website File Changes Monitor: von WP White Security – 1.7.0
Widget Shortcode: von Hassan Derakhshandeh – 0.3.5
Woocommerce Category Post Widget: von Nayan Virani – 1.0.2
WooCommerce Advanced Bulk Edit: von George Iron – 4.6.2.3
Germanized für WooCommerce: von vendidero – 3.3.4
WooCommerce Grid/List View: von BeRocket – 3.0.1.6
WooCommerce Multilingual: von OnTheGoSystems – 4.11.2
WooCommerce Product Search: von itthinx – 3.5.0
WOOF - WooCommerce Products Filter: von realmag777 – 2.2.4.2
WooCommerce: von Automattic – 5.0.0
Wordfence Security: von Wordfence – 7.4.14
Yoast SEO: von Team Yoast – 15.5
WP Crontrol: von John Blackbourn & crontributors – 1.9.0
WP File Manager: von mndpsingh287 – 6.9
Force Login: von Kevin Vess – 5.5
WP Maintenance Mode: von Designmodo – 2.3.0
WP Media folder: von Joomunited – 5.2.4
REST API Log: von Pete Nelson – 1.6.8
WP Activity Log: von WP White Security – 4.1.5.1
WP SMTP: von Yehuda Hassine – 1.2.1
WPFront Scroll Top: von Syam Mohan – 2.0.2
WPML String Translation: von OnTheGoSystems – 3.1.7
WPML Translation Management: von OnTheGoSystems – 2.10.5
WPS Hide Login: von WPServeur
NicolasKulka
wpformation – 1.6.1
WordPress Newsletteranmeldung und Newsletterabmeldung fuer SuperWebMailer: von Mirko Boeer – 1.0.2

### Inactive Plugins (5) ###

Disable/Remove Google Fonts: von Fonts Plugin – 1.1.7
WordPress REST API Authentication: von miniOrange – 1.4.1
WP phpMyAdmin: von Puvox.software – 5.0.4.1

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: von  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #24518 - /shop-2/
Warenkorb: ❌ Die Sichtbarkeit der Seite sollte  öffentlich sein
Kasse: ❌ Die Sichtbarkeit der Seite sollte  öffentlich sein
Mein Konto: #2575 - /mein-konto-2/
Allgemeine Geschäftsbedingungen: #6016 - /agb/

### Theme ###

Name: storefront Child
Version: 2.3.3
Author URL: ---
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.8.0 – 3.5.0 ist verfügbar
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/archive-product.php
storefront-child/woocommerce/content-product.php Version 3.4.0 ist veraltet. Die Hauptversion ist 3.6.0
storefront-child/woocommerce/content-single-product.php Version 3.4.0 ist veraltet. Die Hauptversion ist 3.6.0
storefront-child/woocommerce/emails/customer-new-account.php Version 3.5.2 ist veraltet. Die Hauptversion ist 3.7.0
storefront-child/woocommerce/loop/pagination.php
storefront-child/woocommerce/myaccount/dashboard.php Version 2.6.0 ist veraltet. Die Hauptversion ist 4.4.0
storefront-child/woocommerce/product-searchform.php
storefront-child/woocommerce/single-product/product-image.php

Outdated Templates: ❌
					
					
						Erfahren Sie
wie Sie aktualisieren können

### Action Scheduler ###

Abgeschlossen: 877
Oldest: 2021-02-19 12:04:19 +0100
Newest: 2021-02-27 17:03:32 +0100o fully evaluate this issue.
<details>
```

```
</details>

**Comment by claudiosanches** [comment] 2021-04-01 00:24
Hi @Thomas-1985,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end.
I think you had this problem because that tutorial is incomplete and doesn't talk about of using `flush_rewrite_rules()` toi make sure your URL will work, at least generally that's why returns 404, You can see a full example in: https://gist.github.com/claudiosanches/a79f4e3992ae96cb821d3b357834a005

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2021-04-01 00:24 UTC
Labels: needs developer feedback
