### ISSUE TITLE
Spaces in postcode wildcards ignored

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#20580] opened 2018-06-19 19:40 UTC
**Describe the bug**
Appears was previously corrected here: #11154

If postcodes with spaces are added with wildcards, they do not match. It appears they are saved correctly in the database, but the space is removed in the matching process here:
https://github.com/woocommerce/woocommerce/blob/3.4.2/includes/class-wc-shipping-zones.php#L130
https://github.com/woocommerce/woocommerce/blob/3.4.2/includes/data-stores/class-wc-shipping-zone-data-store.php#L222

**To Reproduce**
1. Create a shipping zone with the postcode wildcard `NG1 *`
1. Add item to cart, proceed to checkout.
1. Add postcode `NG1 111` to address, it will not match. 

Related forum thread:
https://wordpress.org/support/topic/free-shipping-not-wokring/

**Comment by claudiulodro** [comment] 2018-06-19 20:48
I was unable to reproduce the issue. When using the [real postcode `NG1 5DJ`](https://www.doogal.co.uk/ShowMap.php?postcode=NG1%205DJ) and UK as the checkout country, the `NG1 *` zone applies successfully.

I can reproduce that `NG1 111` will not match the shipping zone as it [is not a valid postcode format in the UK](https://github.com/woocommerce/woocommerce/blob/07bad6975fbdd057af20f51843154efb4b844008/includes/class-wc-validation.php#L122-L126) (It needs to be of format `{letter}{letter}{#} {#}{letter}{letter}`). 

Trying to apply `NG1 111` in the shipping calculator will output a `Please enter a valid postcode / ZIP.` notice at the top of the screen and refuse to apply the postcode, which may be why it seems that the postcode is not matching. 

It would also not match if e.g. your checkout country was Ukraine as that doesn't allow spaces in postcodes.

Closing this issue as everything seems to be working correctly. :)

**Closed by claudiulodro** 2018-06-19 20:48 UTC

**Comment by jessepearson** [comment] 2018-06-20 11:42
Okay, I understand now why it was not matching. I thought that it would begin to match once the `NG1 ` was entered with anything after that. I did not realize a full, valid postcode needed to be entered, as well. 👍
