### ISSUE TITLE
I can't uncheck "Manage stock?" inside some variations.

### ISSUE THREAD

**Issue by trimal2** [woocommerce/woocommerce#25515] opened 2020-01-29 04:44 UTC
When creating a new product and creating variations for it,
some of them have "manage stock" checked and it can not be changed manually.
This bug appears not in all products.
Most of them can be changed manually, but some SKU that has "Manage stock" checked, can't be updated. After unchecking it manually and saving it remains the same. Nothing changes.

**To Reproduce**
1. Create a new product.
2. Add a few custom attributes.
3. Create all variations.
4. Add prices and SKUs to variations. > "Save Changes"
5. Only the first variation is showing "Manage stock?" unchecked.
6. If I click "Toggle "Manage stock"> Go, it doing the opposite. The first variation has "Manage stock?" checked and all others have it unchecked.

**Comment by juliaamosova** [comment] 2020-01-29 10:55
Hi @trimal2,

Thank you for raising the issue. However, I can’t reproduce it on my end.

Everything is working as expected - please see screencast: https://recordit.co/r9yBeVslQo. 

You haven't provided your System Status report. Do you have many plugins installed on your site? Do you use one of our default themes or a 3rd party theme?  

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by trimal2** [comment] 2020-01-29 21:14
Thank you Julia for your quick response.
I just disabled all plugins except ones that have "WooCommerce" in it's name and changed theme to Storefont but problem still exists.
When disabled everything except this 2 plugins: WooCommerce and WooCommerce Admin, everything went fine. So it's one of woocommerce plugins is causing this issue. I will reenable them one by one and will try to find which one causes this issue. Once will have a result will post it here.
Thanks

**Comment by trimal2** [comment] 2020-01-29 23:56
Thank you very much once again, Julia.
Finally, I've found a faulty plugin: WooCommerce Square (Version 2.0.8)
<img width="1747" alt="Screenshot 2020-01-29 18 24 27" src="https://user-images.githubusercontent.com/7256258/73406524-9cce2400-42c4-11ea-8c5a-b96708d4d8a0.png">
When it's active, there some SKUs which I can't change "Manage Stock?"
But when I deactivate it, everything is working well.
Please see a ScreenCast: https://recordit.co/rBhwb8Wn1O

Below you will find a system report
Please let me know if you will need any additional info to fix this issue.

`
### WordPress Environment ###

WordPress address (URL): https://www.a****x.ca
Site address (URL): https://www.a****x.ca
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.14
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.53.1
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.7.16-10-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: wp_
Total Database Size: 9.29MB
Database Data Size: 7.54MB
Database Index Size: 1.75MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_acl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_blocks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_countries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_lab: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_lab_ip: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_lab_net: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_qmem: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_traffic: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cerber_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cerber_sets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cerber_uss: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.27MB + Engine InnoDB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.13MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 1.47MB + Index: 0.81MB + Engine InnoDB
wp_posts: Data: 3.50MB + Index: 0.25MB + Engine InnoDB
wp_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_square_customers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

attachment: 58
customize_changeset: 1
mc4wp-form: 1
nav_menu_item: 18
nectar_slider: 7
page: 19
polylang_mo: 2
portfolio: 3
post: 16
product: 18
product_variation: 312
revision: 147
scheduled-action: 367
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Admin: by WooCommerce – 0.24.0 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.0.8 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.9.1

### Inactive Plugins (34) ###

Advanced noCaptcha & invisible Captcha: by Shamim Hasan – 5.6 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.1.3
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.4.1

Contact Form 7: by Takayuki Miyoshi – 5.1.6
Drag and Drop Multiple File Upload - Contact Form 7: by Glen Don L. Mongaya – 1.3.2
Duplicate Post: by Enrico Battocchi – 3.2.4
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.1
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Font Awesome: by Font Awesome – 4.0.0-rc13
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.10
Jetpack by WordPress.com: by Automattic – 8.1.1
Mailchimp for WooCommerce: by Mailchimp – 2.3.1 – Not tested with the active version of WooCommerce
MC4WP: Mailchimp for WordPress: by ibericode – 4.7.4
Polylang: by WP SYNTEX – 2.6.9
Safe SVG: by Daryll Doyle – 1.9.8
Salient Core: by ThemeNectar – 1.4
Salient Demo Importer: by ThemeNectar – 1.1
Salient Home Slider: by ThemeNectar – 1.1
Salient Nectar Slider: by ThemeNectar – 1.4
Salient Portfolio: by ThemeNectar – 1.4
Salient Shortcodes: by ThemeNectar – 1.3
Salient Social: by ThemeNectar – 1.1
Salient Widgets: by ThemeNectar – 1.1
Salient WPBakery Page Builder: by Michael M - WPBakery.com | Modified by ThemeNectar – 6.1
Simple Website Redirect: by Micah Wood – 1.2.3
Tawk.to Live Chat: by Tawkto – 0.4.1
Under Construction: by WebFactory Ltd – 3.65
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.17
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
Wordfence Security: by Wordfence – 7.4.5
WP Cerber Security, Antispam & Malware Scan: by Cerber Tech Inc. – 8.5.8
Yoast SEO: by Team Yoast – 12.9.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #12 - /print-studio/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My account: #15 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Action Scheduler ###

Complete: 335
Oldest: 2019-12-30 15:36:01 -0500
Newest: 2020-01-29 18:23:10 -0500

Pending: 3
Oldest: 2020-01-29 19:23:10 -0500
Newest: 2020-01-30 13:33:49 -0500

Cancelled: 29
Oldest: 2020-01-26 16:41:39 -0500
Newest: 2020-01-26 16:41:52 -0500

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by juliaamosova** [comment] 2020-01-30 10:02
@trimal2 thanks for additional testing. Glad you found the plugin causing the issue. 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce Core bugs only. 

According to your testing, the issue you are having seems to be caused by the WooCommerce Square plugin which is one of the products on our marketplace. To get further technical support for it, please contact WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/).

**Closed by juliaamosova** 2020-01-30 10:02 UTC
Labels: can't reproduce

**Comment by treibalen** [comment] 2020-05-06 12:50
@trimal2 just wanted to chime to inform you that the bug you reported is already logged for our dev team working on Square extension. I gave a bit more details here: https://wordpress.org/support/topic/woocommerce-manage-stock-per-variation-broken/

**Comment by trimal2** [comment] 2020-05-06 16:50
Sounds great, thank you for the update.
