### ISSUE TITLE
THIRD PARTY PAYMENT GATEWAY PLUGIN NOT WORKING

### ISSUE THREAD

**Issue by kotobukidevelopers** [woocommerce/woocommerce#27891] opened 2020-10-06 07:36 UTC
The issue is I am creating an order and grabbing the payment link via PHP SDK
the code is this 

```
$response_real = $woocommerce->post('orders', $data_2);
$response = json_decode(json_encode($response_real), true);
$payment_url = "https://host.com/index.php/checkout/order-pay/".$response['id']."/?pay_for_order=true&key=".$response['order_key'];
```

then when I use the third party payment plugin it was returning an "EMPTY CART ERROR"

but when I use paypal it works

**Comment by juliaamosova** [comment] 2020-10-08 21:29
Hi @kotobukidevelopers,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-08 21:29 UTC
