### ISSUE TITLE
woocommerce showing the wrong cart total with the total being less than the subtotal and the shopping cart on mobile is missing

### ISSUE THREAD

**Issue by rongjinggao** [woocommerce/woocommerce#20681] opened 2018-07-02 10:05 UTC
**Describe the bug**
The woocommerce shopping cart is showing wrong total amount, with the total being less than subtotal, and missing on the mobile altogether 

**To Reproduce**
1. Go to '...' www.silkandshine.co.uk
2. Click on '....'produts
3. Scroll down to '....'add to cart
4. See error check the total being wrong
![screen shot 2018-06-30 at 13 14 53](https://user-images.githubusercontent.com/40758020/42158180-54ded666-7e22-11e8-8a5a-7d416b93d0ab.png)
![screen shot 2018-06-30 at 13 14 53](https://user-images.githubusercontent.com/40758020/42158213-69b1f230-7e22-11e8-9979-c192845dc509.png)
![screen shot 2018-06-30 at 13 40 56](https://user-images.githubusercontent.com/40758020/42158221-6eb39770-7e22-11e8-9e32-4f965ec0f080.png)
![screen shot 2018-06-30 at 18 38 09](https://user-images.githubusercontent.com/40758020/42158252-857973ee-7e22-11e8-82b5-26bf5b09e8ba.png)

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiulodro** [comment] 2018-07-03 19:12
Hi there.

It seems that you have a negative cost for your flat rate shipping method (e.g. `-20`). I was able to reproduce that by also testing on your site. Closing this issue as this is not a bug.

Thanks.

**Closed by claudiulodro** 2018-07-03 19:12 UTC

**Comment by rongjinggao** [comment] 2018-07-03 23:23
hi 

thank you for your feedback 

can you explain please？

i just downladed woocommerce software without manually setting any value. 

if this happens it is not intended 

wonder if you can share the solution on how we can put this right 

thank you
katherine

**Comment by claudiulodro** [comment] 2018-07-04 01:09
Go to the Shipping settings in the WooCommerce settings and edit the shipping zone. [Here is some documentation that may help](https://docs.woocommerce.com/document/flat-rate-shipping/). Good luck!

**Comment by rongjinggao** [comment] 2018-07-04 03:08
Thank you!


________________________________
