### ISSUE TITLE
County/State Field Mandatory, But Not?

### ISSUE THREAD

**Issue by Peter-27** [woocommerce/woocommerce#27070] opened 2020-07-18 18:19 UTC
Hello,

The "County (Optional)" field isn't optional as stated. When the user tries to proceed without entering anything, the following error message appears "billing state is a required field".

This could be particularly confusing to the user since the field title says county rather than state.

As a seperate, but related question, is there a way for me to change that pre-written text within the field? I don't like the inconsistency of the title being "county" but the pre-written text displayed as "state".

Many thanks,
Peter.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

![image](https://user-images.githubusercontent.com/68478392/87859254-9b082380-c92b-11ea-90f0-db0295046274.png)

**Comment by tammullen** [comment] 2020-07-22 14:26
Hi @Peter-27 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end.
County is not a required field for the UK
​
<img width="563" alt="Screenshot 2020-07-22 at 15 22 02" src="https://user-images.githubusercontent.com/24649833/88188180-63e98900-cc2f-11ea-9eb6-b17d01de7b33.png">

Please provide us with more details about the issue which may help us to evaluate it further such as the system status report from **WooCommerce > System Status** in WordPress admin.
​
Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by Peter-27** [comment] 2020-07-23 23:58
Hello,

I did attempt to evalute the problem with all plugins deactivated (apart from WooCommerce) and the issue remained.

Let me walk you through how I am triggering the error step-by-step.

1) On my website, www.exploresubic.com, proceed to add something to the cart and then click "proceed to checkout".
2) Fill in all fields with the red star (required fields), which leaves county blank, and hit "place order" (payment method doesn't matter).
3) You should then see the error message appear, rather than progressing to the next screen.

It is worth noting that I have replicated this issue with three users on three computers.

Additionally, is there a way for me to change that pre-written text within the field, or the title? I don't like the inconsistency of the title being "county" but the pre-written text displayed as "state". This could also potentially serve as a workaround solution to the problem.

System status report below, many thanks, Peter.

`
### WordPress Environment ###

WordPress address (URL): https://www.exploresubic.com
Site address (URL): https://www.exploresubic.com
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 0.21.0
Log Directory Writable: ✔
WP Version: ❌ 5.2.7 - There is a newer version of WordPress available (5.4.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.20
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.3
WC Database Prefix: wp_
Total Database Size: 11.92MB
Database Data Size: 10.17MB
Database Index Size: 1.75MB
wp_woocommerce_sessions: Data: 2.35MB + Index: 0.13MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.42MB + Index: 0.11MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.29MB + Index: 0.18MB + Engine MyISAM
wp_byt_accommodation_bookings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_byt_accommodation_vacancies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_byt_car_rental_availabilities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_byt_car_rental_bookings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_byt_cruise_booking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_byt_cruise_schedule: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_byt_tour_booking: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_byt_tour_schedule: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.33MB + Index: 0.25MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_mapping_to_external_entities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_templates: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_segments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_sending_queues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 3.38MB + Index: 0.11MB + Engine MyISAM
wp_postmeta: Data: 0.87MB + Index: 0.37MB + Engine MyISAM
wp_posts: Data: 0.78MB + Index: 0.26MB + Engine MyISAM
wp_rank_math_404_logs: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_rank_math_internal_links: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_internal_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_rank_math_redirections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_redirections_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_sc_analytics: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_revslider_css: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_testing: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_campaign: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url_mail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_accommodation_bookings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_accommodation_vacancies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_car_rental_availabilities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_car_rental_bookings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_cruise_booking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_cruise_schedule: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_tour_booking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_byt_tour_schedule: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_PYJ_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_options: Data: 0.51MB + Index: 0.02MB + Engine MyISAM
_PYJ_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_PYJ_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_PYJ_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_PYJ_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_PYJ_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_PYJ_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 55
custom_css: 2
custom-css-js: 2
customize_changeset: 1
extra_item: 3
mailpoet_page: 1
nav_menu_item: 16
oembed_cache: 1
page: 28
post: 2
product: 4
product_variation: 27
revision: 167
shop_coupon: 1
shop_order: 29
tour: 5
ufaq: 12
user_request: 1
vc_grid_item: 1
wp_block: 1
wpcf7_contact_form: 2
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

a3 Lazy Load: by a3rev Software – 2.3.2 – Installed version not tested with active version of WooCommerce 4.3.0
Async JavaScript: by Frank Goossens (futtta) – 2.20.03.01
Autoptimize: by Frank Goossens (futtta) – 2.6.2
BunnyCDN: by BunnyCDN – 1.0.7
Child Theme Configurator: by Lilaea Media – 2.5.2
Contact Form 7: by Takayuki Miyoshi – 5.1.6
Simple Custom CSS and JS: by SilkyPress.com – 3.32.2
Disable Cart Fragments: by Optimocha – 1.01 – Installed version not tested with active version of WooCommerce 4.3.0
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.3.9.2

Envato Market: by Envato – 2.0.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.11.0
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
MailPoet 3 (New): by MailPoet – 3.46.2
Max Mega Menu: by megamenu.com – 2.7.4
One Click Demo Import: by ProteusThemes – 2.5.2
Slider Revolution: by ThemePunch – 6.1.5
Rank Math SEO: by Rank Math – 1.0.39.2
ShortPixel Image Optimizer: by ShortPixel – 4.16.3
Ultimate FAQ: by Etoile Web Design – 1.8.30 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Admin: by WooCommerce – 0.21.0 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3
WooCommerce: by Automattic – 4.3.0 (update to version 4.3.1 is available)
WP Fastest Cache: by Emre Vona – 0.9.0.4
WP Reset: by WebFactory Ltd – 1.77

### Inactive Plugins (2) ###

Flexible Checkout Fields: by WP Desk – 2.4.13
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.0

### Dropin Plugins (2) ###

db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.0.2
SSO: by Garth Mortensen
Mike Hansen – 0.3


### Settings ###

API Enabled: –
Force SSL: ✔
Currency: PHP (₱)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #312 - /cart/
Checkout: #313 - /checkout/
My account: #314 - /my-account/
Terms and conditions: #322 - /terms-conditions/

### Theme ###

Name: BookYourTravel Child
Version: 8.06.1566042331
Author URL: http://themeforest.net/user/themeenergy
Child Theme: ✔
Parent Theme Name: BookYourTravel
Parent Theme Version: 8.11
Parent Theme Author URL: http://themeforest.net/user/themeenergy
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,125
Oldest: 2020-06-23 00:15:24 +0000
Newest: 2020-07-23 23:34:40 +0000

Pending: 3
Oldest: 2020-07-24 00:34:40 +0000
Newest: 2020-07-24 17:59:56 +0000

`

**Comment by Peter-27** [comment] 2020-08-18 00:40
Hello, still waiting for a response to this please.

**Comment by AdrianKielbasa** [comment] 2020-09-14 17:21
![screen](https://user-images.githubusercontent.com/14923258/93117525-4977dd00-f6bf-11ea-98be-9a5778faf269.png)
I have the same problem. The problem appeared after updating wordpress and woocommerce.

**Comment by GlennMartin1** [comment] 2020-09-21 01:26
Other "required fields" issues: https://github.com/woocommerce/woocommerce/issues/27652 and https://github.com/woocommerce/woocommerce/issues/27521

 possibly related?

**Comment by AdrianKielbasa** [comment] 2020-09-23 16:53
I think this problem is not related issue #27652. I would say, that issue #27521 is related. My problem occurs on the edit billing address page. It doesn't appear on the checkout page

**Comment by Peter-27** [comment] 2020-10-26 16:28
I believe #27521 is related and will continue the conversation there.

**Comment by Peter-27** [comment] 2020-11-02 01:29
@tammullen Hello, any thoughts on this please? Your last response was 22nd July!! 😞

**Comment by Peter-27** [comment] 2020-11-08 17:39
I would like to get this resolved please, I have not had a response since 22nd July. @juliaamosova Maybe you can help as you're also working on #27251 which seems like a similar issue - and @tammullen is no longer engaged for whatever reason.

**Comment by Peter-27** [comment] 2021-01-23 02:49
I am extremely disappointed I am being ignored by the admin team, I am not sure what to do here.

**Comment by tammullen** [comment] 2021-01-26 22:51
Hi @Peter-27 

Sorry for the delay.

I still can't reproduce this. For all product types County is not a required field for the UK and the field itself has the placeholder text of `Select an option..` 

![Screenshot 2021-01-26 at 22 44 20](https://user-images.githubusercontent.com/24649833/105916526-f4fb4b80-6028-11eb-87ab-b334e0cb56e1.png)


You mention that with all plugins deactivated (apart from WooCommerce) the issue remained. Were you using one of the default themes such as [Storefront](https://en-gb.wordpress.org/themes/storefront/)? 

If you are able to reproduce this with a default theme and only WooCommerce active can you provide a screenshot and any other information that could help us evaluate this such as details of the product types in the checkout.

**Comment by Peter-27** [comment] 2021-02-03 21:10
Hi @tammullen,

I will respond in due course, I am currently having an issue with a virus which I need to resolve first before taking this further.

Thanks,
Peter.

**Comment by juliaamosova** [comment] 2021-03-19 23:24
Hi @Peter-27,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-03-19 23:24 UTC
Labels: category: can't reproduce, needs feedback
