### ISSUE TITLE
How to add an Affiliate Tracking ID to Place Orders of external products?

### ISSUE THREAD

**Issue by dirkthewebphoenix** [woocommerce/woocommerce#27716] opened 2020-09-18 19:40 UTC
I am new to Woocommerce.

I wonder about "external product" links not redirecting the browser to the external site with a tracking id inserted in the GET URL. Rather a situation where Woocommerce uses REST API to send the order placement to the external site and gets back a response then displayed to the user who thus never left the Woocommerce-using site.

Is there any usable hook and variable to use in an add_filter() plugin one adds to WordPress to adjust the tracking ID that will enable the external site to pay a commission to the Woocommerce-using WordPress site?

**Comment by juliaamosova** [comment] 2020-09-21 20:34
Hi @dirkthewebphoenix,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-09-21 20:34 UTC

**Comment by dirkthewebphoenix** [comment] 2020-09-22 15:55
Thanks a million for the WooCommerce Community Slack link. :-)

(now I may finally find a way out of the labyrinth)

:-) DtWP
