### ISSUE TITLE
Invoice mail break code

### ISSUE THREAD

**Issue by kiranwizdumb** [woocommerce/woocommerce#20835] opened 2018-07-18 09:12 UTC
Hi,

We have developed a e-comm website using wordpress. However, the emails getting sent after placing an order how code in the sub-total and total section. We have been trying to solve this problem for quite some time but haven't found the solution.

I have attached a screenshot for your reference. 

![1](https://user-images.githubusercontent.com/41287152/42871764-c2d6b0e4-8a98-11e8-8795-5095370aa873.png)

**Comment by claudiosanches** [comment] 2018-07-19 00:12
It's missing a lot of information to be able to reproduce and check if it's a real bug.
Please open this issue again using the this form:

![screenshot from 2018-07-18 21-11-02](https://user-images.githubusercontent.com/1264099/42914160-286f75ea-8acf-11e8-8710-7e0be17d238a.png)

And fill all data there.

Closing since it's not possible to reproduce.

Thanks.

**Closed by claudiosanches** 2018-07-19 00:12 UTC
