### ISSUE TITLE
Set shipping zones not respected in my-account shipping address forms

### ISSUE THREAD

**Issue by dsifford** [woocommerce/woocommerce#25834] opened 2020-03-06 14:16 UTC
**Describe the bug**

We have a store that ships only to the continental US (i.e., excluding Hawaii, Alaska, and the Armed forces states). We set up a shipping zone called `USA, Continental`, in which we hand selected all the states that we _do_ ship to.

However, in the `/my-account/edit-address/shipping` form, the excluded states are still appearing.

Is this a known issue? Did we simply set this up incorrectly?

**To Reproduce**

Set up a clean woo site with a shipping zone as follows:

![image](https://user-images.githubusercontent.com/5240018/76090580-ca745000-5f89-11ea-98d8-3aa28718211a.png)

See that in the `/my-accont/edit-address/shipping` form, excluded states still appear.

![image](https://user-images.githubusercontent.com/5240018/76091033-c5fc6700-5f8a-11ea-865b-da56c6cf893a.png)

**Expected behavior**

Excluded states should not be included.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 3.9.3
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.4.2
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.11-MariaDB-1:10.4.11+maria~bionic
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.9.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #13 - /shop/
Cart: ❌ Page does not contain the shortcode.
Checkout: #15 - /checkout/
My account: #16 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by juliaamosova** [comment] 2020-03-11 18:20
Hi @dsifford,

Thank you for submitting the issue. However, it is not a bug but rather expected behavior. 

The states that you select within the shipping zone don't control what states are available in the dropdown on the checkout page. What controls it is the General settings but there is no option to select the states you want to sell to, only countries:

![set1](https://user-images.githubusercontent.com/19143190/76449064-c7ba9600-63a1-11ea-9c32-e41e258da2a5.jpg)

When it comes to shipping, there is a shipping zone reserved for the locations not covered by any of your shipping zones:

![set2](https://user-images.githubusercontent.com/19143190/76449339-48799200-63a2-11ea-8c53-7a3c45ded4f4.jpg)

If you don't have any shipping methods assigned to that zone like in my case (shown on the screenshot), the user will see a message letting them know that there is no shipping option available for their location. They will also see the notice letting them know that their shipping zone is `Locations not covered by any other zone` if the shipping debug mode is enabled:

![set3](https://user-images.githubusercontent.com/19143190/76449629-cfc70580-63a2-11ea-88d2-53c0abd688de.jpg)

You can enable shipping debug mode here:

![set4](https://user-images.githubusercontent.com/19143190/76449784-0ef55680-63a3-11ea-8e05-0ef803175811.jpg)

What you can also do is add a notice on the checkout page letting users know that you don't ship to certain locations. There a few ways to do that. Here are some examples of both free and paid methods:

- Free: https://flexibleshipping.com/add-shipping-notice-woocommerce-checkout/
- Paid: https://woocommerce.com/products/cart-notices/

I am closing this issue since there is no bug. However, please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-03-11 18:20 UTC
