### ISSUE TITLE
Disable Product Revision when order is made

### ISSUE THREAD

**Issue by ttMino** [woocommerce/woocommerce#25470] opened 2020-01-22 20:03 UTC
Hello,

I’ve ran into an issue that I can’t seem to find a solution for anywhere.

So when there is an order in WooCommerce it reduces the stock of the order products which creates a revision on the actual post.

![wp_issue](https://user-images.githubusercontent.com/43281889/72929659-33916280-3d52-11ea-9ff3-9af44dd7e946.png)
![wp_issue_2](https://user-images.githubusercontent.com/43281889/72929661-3429f900-3d52-11ea-80be-13a8203b6502.png)

Is there any way to disable WooCommercefrom making automatic revisions to products when it automatically reduces the stock?

**Comment by claudiosanches** [comment] 2020-01-23 20:48
Hi @ttMino 

By default we don't set any revision for products, order, or coupons. Seems like you have some customization, or it is done by a 3rd party plugin.

I'm closing since I can't reproduce this error with on WooCommerce installed, and also sounds a bug coming from customization.

**Closed by claudiosanches** 2020-01-23 20:48 UTC
