### ISSUE TITLE
Country and Region not showing in my account Billing and Shipping Address for users 

### ISSUE THREAD

**Issue by sheggietyn** [woocommerce/woocommerce#27335] opened 2020-08-14 11:16 UTC
Please the country form field is not showing on shipping and billing address in my account page for my users, what could be the problem, i have tried out every possible solution but it still not working 

thanks

**Comment by juliaamosova** [comment] 2020-08-14 18:34
Hi @sheggietyn,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-08-14 18:34 UTC
