### ISSUE TITLE
Bug occurs when I enable Gutenberg for products (only for products with comment and created thru classic editor)

### ISSUE THREAD

**Issue by kiber-chaka** [woocommerce/woocommerce#25352] opened 2020-01-03 14:43 UTC
Hi!
There is an error occurs on my website. First I thought than was problem with Yoast Seo, so I asked their support about it. And there is what they answered me:

We had a look at the product edit screen (on the screen you can see, that tabs of Yoast Seo Plugin are empty):

![Selection_404](https://pix.toile-libre.org/upload/original/1578239961.png)

 and found the following error in the browser's console: ReferenceError: **commentsBox is not defined** We temporarily disabled Yoast SEO Premium and confirmed that the error still occurs when our plugin is disabled which means it's not caused by Yoast SEO Premium. However, the error prevents the Yoast metabox from loading properly. As the error details indicate, the error is related to the comments feature. We've been able to reproduce the error in our testing environment by following these steps:

1. Create a product using the classic editor
2. Submit a product review and approve it in the product edit screen
3. Enable Gutenberg for products as explained in [this guide](https://wplook.com/how-to-enamble-gutenberg-for-woocommerce-products/)
4. Edit the product using Gutenberg

We were able to fix the error on our test site by editing the product with the classic editor, sending the existing comment to trash and then switching the editor to Gutenberg. You may want to try this workaround on your website or, alternatively, contact the WooCommerce team and bring this issue to them. They'll be able to investigate this issue further and hopefully find a solution.

**Comment by juliaamosova** [comment] 2020-01-14 22:46
Hi @kiber-chaka,

Thank you for raising the issue. However, Gutenberg for Products had been disabled in WooCommerce since version 3.4 - see https://github.com/woocommerce/woocommerce/issues/20201 for more details. As a result, we currently don't support it. It is up to you if you'd like to use it but we are aware that it doesn't work as expected which is the reason why we disabled it. 

We are still working on enabling Gutenberg to create products but there are no concrete plans we can share at the moment.

I am going to close this bug report since it is related to the feature we don't officially support.

**Closed by juliaamosova** 2020-01-14 22:46 UTC

**Comment by jenkoian** [comment] 2020-01-16 09:36
@kiber-chaka if you add `&classic-editor=1` to your query string, does it work as expected? If so, could be a work around until fixed? We've got the same but believe it is something to do with MultiLingualPress so not 100% sure if the same issue.

**Comment by kiber-chaka** [comment] 2020-01-17 05:21
Hi!
Thank you for your answer!
No, it didn't work around. 
Now I enabling Gutenberg with this code:
```
function wplook_activate_gutenberg_products($can_edit, $post_type){
	if($post_type == 'product' **AND $_GET['guten'] != 1**){
		$can_edit = true;
	}
	
	return $can_edit;
}
add_filter('use_block_editor_for_post_type', 'wplook_activate_gutenberg_products', 10, 2);

```
So it is possible to add **&guten=1**  to query string and it disables Gutenberg and after that it is possible to change content in YoastSeo tabs. May be will help someone.

But it is not very convenient for my client.

**Comment by iggyvanlith** [comment] 2020-05-28 12:06
Another way to work around it seems to be to remove the comments-section. I'm not sure yet of all the implications of it, but to get the editor working again it seems to work.

```php
function wpdocs_remove_product_comments_field() {
    remove_post_type_support( 'product', 'comments' );
  }
  add_action( 'admin_init', 'wpdocs_remove_product_comments_field' );
```

**Comment by kiber-chaka** [comment] 2020-05-28 15:20
Yes, it helped!
Thank you!

**Comment by batonac** [comment] 2020-05-28 18:14
Just for future reference, I can confirm the case and perhaps even clarify the issue:

In my experience, this bug affects all product posts with comments on the frontend, regardless of where/how they originated.

Here’s my list of steps to reproduce:

1. Install Woocommerce on a fresh install of WordPress.
2. Enable Gutenberg with the following code (or equivalent):
`add_filter('use_block_editor_for_post_type', '__return_true');`
3. Create a product, confirm that no errors are registered in the browser console.
4. Comment on the product in the front end, then return to the backend. The following error appears:
```
post.php?post=7&action=edit:589
Uncaught ReferenceError: commentsBox is not defined
    at HTMLDocument.<anonymous> (post.php?post=7&action=edit:589)
    at i (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,underscore,backbone,wp-util,&load[chunk_1]=wp-backbone,media-models,moxiejs,plupload&ver=5.3.2:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,underscore,backbone,wp-util,&load[chunk_1]=wp-backbone,media-models,moxiejs,plupload&ver=5.3.2:2)
    at Function.ready (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,underscore,backbone,wp-util,&load[chunk_1]=wp-backbone,media-models,moxiejs,plupload&ver=5.3.2:2)
    at HTMLDocument.J (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,underscore,backbone,wp-util,&load[chunk_1]=wp-backbone,media-models,moxiejs,plupload&ver=5.3.2:2)
```
The result is that third-party plugins (such as Yoast and RankMath) break on these posts.

I request that you keep this bug open for the following reasons:

1. Issue #20201 references usability issues, not compatibility issues.
2. There's obviously something broken that seemingly should be factored better (regardless).
3. If the block editor is an eventual target, why not keep this open as an active blocking bug?

In our case, we have several sites that are based entirely on block-based management, so enabling them on WooCommerce products was consistent with our overall paradigm. This is the only issue we've experienced with that.
