### ISSUE TITLE
customer-processing-order.php - small mail bug

### ISSUE THREAD

**Issue by tobias992** [woocommerce/woocommerce#29018] opened 2021-02-03 21:12 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The shipping costs not showing correct in customer-processing-order.php mail.

Example before:
normal shipping fee: "5,00 €"
free shipping: "free shipping"

Example now:
normal shipping fee: "5"
free shipping: "0"

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Its very easy. Make an order and look into the processing-order mail.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
All Versions are up-to-date.
</details>

**Comment by juliaamosova** [comment] 2021-02-03 22:01
Hi @tobias992,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Here I have a Flat Rate Fee of $5.00 + tax:

![flat](https://user-images.githubusercontent.com/19143190/106815003-3f8c5180-6641-11eb-802a-9e6efbda138c.jpg)

And here I have Free Shipping:

![free](https://user-images.githubusercontent.com/19143190/106815013-431fd880-6641-11eb-94e7-8dfbc9a61edd.jpg)

It will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment. 

In addition to that, can you please confirm that you tested your site for theme and plugin conflicts? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2021-02-27 00:36
Hi @tobias992,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-02-27 00:36 UTC
Labels: category: can't reproduce, needs feedback
