### ISSUE TITLE
Woocommerce Catalogue ID different from ID shown on FB

### ISSUE THREAD

**Issue by tobiakiode** [woocommerce/woocommerce#28824] opened 2021-01-15 00:58 UTC
Please, I need help; I have an wordpress e-commerce which I have been troubleshooting for days now, because the Catalogue ID on WP appears different from one on facebook. I will be really blessed by your guidance. How can I resolve this, please?
![Screen Shot 2021-01-15 at 01 18 58](https://user-images.githubusercontent.com/6032389/104668356-d5caf880-56cf-11eb-9ff4-98e4bebf9447.png)

**Comment by tammullen** [comment] 2021-01-18 10:44
Hi @tobiakiode 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-01-18 10:44 UTC
