### ISSUE TITLE
WC_Order::set_status and WC_Order::update_status not working – changing to incorrect post_status

### ISSUE THREAD

**Issue by jacobtilly** [woocommerce/woocommerce#28293] opened 2020-11-16 15:29 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When updating order status using the set_status() function, the database is incorrectly updated without the necessary wc-prefix.

The code that I am using is this: 

```
$wcorder = wc_get_order($saorderId);
$result = $wcorder->set_status('processing');
$wcorder->save();

```

**Expected behavior**
I expected the posts database to have the column post_status updated to wp-processing.

**Actual behavior**
The database field post_status updated to just _processing_, ultimately leading to the order not being shown in the wp-admin » woocommerce » orders section.

_Please note that it works fine to change the status using the orders » status through the admin panel-_

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create an order.
2. Update the order's status using WC_Order::set_status() or WC_Order::update_status() (both will give you the same issue)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. (well woocommerce and the plugin that I have built to do the actual update)
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://vrsv.schoolapparel.se
Site address (URL): https://vrsv.schoolapparel.se
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: sv_SE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.34
PHP Post Max Size: 1 GB
PHP Time Limit: 3000
PHP Max Input Vars: 3000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB
Max Upload Size: 15 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wpscap_9_
Total databasstorlek: 2.10MB
Datastorlek för databas: 1.71MB
Indexstorlek för databas: 0.39MB
wpscap_9_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Motor MyISAM
wpscap_9_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_actionscheduler_actions: Data: 0.03MB + Index: 0.03MB + Motor MyISAM
wpscap_9_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_actionscheduler_logs: Data: 0.02MB + Index: 0.02MB + Motor MyISAM
wpscap_9_commentmeta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_comments: Data: 0.01MB + Index: 0.01MB + Motor MyISAM
wpscap_9_links: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_options: Data: 0.87MB + Index: 0.04MB + Motor MyISAM
wpscap_9_postmeta: Data: 0.19MB + Index: 0.08MB + Motor MyISAM
wpscap_9_posts: Data: 0.06MB + Index: 0.02MB + Motor MyISAM
wpscap_9_snippets: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_termmeta: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_terms: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_term_relationships: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_wc_download_log: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_9_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_9_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_blogmeta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_blogs: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_ms_snippets: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_registration_log: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wpscap_signups: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_site: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wpscap_sitemeta: Data: 0.49MB + Index: 0.02MB + Motor MyISAM
wpscap_usermeta: Data: 0.02MB + Index: 0.02MB + Motor MyISAM
wpscap_users: Data: 0.00MB + Index: 0.01MB + Motor MyISAM

### Post Type Counts ###

attachment: 44
customize_changeset: 10
elementor_library: 1
nav_menu_item: 3
page: 7
post: 6
product: 24
product_variation: 33
revision: 9
shop_order: 13
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Felmeddelanden ska inte visas för besökare.

### Active Plugins (11) ###

Flexible Checkout Fields: av WP Desk – 2.7.0 – Den installerade versionen har inte testats med den aktiva versionen av WooCommerce 4.7.0
Printful Integration for WooCommerce: av Printful – 2.1.16 – Den installerade versionen har inte testats med den aktiva versionen av WooCommerce 4.7.0
School Apparel Manual Payments Provider: av Jacob Tilly – 1.0
Variation Swatches for WooCommerce: av Emran Ahmed – 1.1.0 – Den installerade versionen har inte testats med den aktiva versionen av WooCommerce 4.7.0
WooCommerce: av Automattic – 4.7.0
Elementor: av Elementor.com – 3.0.13
Orbit Fox Companion: av Themeisle – 2.10.0
WPForms Lite: av WPForms – 1.6.3.1
NS Cloner - Site Copier: av Never Settle – 4.0.9
Code Snippets: av Code Snippets Pro – 2.14.0
Bambora Online Checkout: av Bambora – 4.4.2 – Den installerade versionen har inte testats med den aktiva versionen av WooCommerce 4.7.0

### Inactive Plugins (5) ###

Akismet Anti-Spam: av Automattic – 4.1.7
Hello Dolly: av Matt Mullenweg – 1.7.2
Modal Window: av Wow-Company – 5.1
WooCommerce PayPal Checkout Gateway: av WooCommerce – 2.1.0 – Den installerade versionen har inte testats med den aktiva versionen av WooCommerce 4.7.0
WooCommerce Stripe Gateway: av WooCommerce – 4.5.3 – Den installerade versionen har inte testats med den aktiva versionen av WooCommerce 4.7.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Butikbas: #6 - /butik/
Varukorg: #7 - /varukorg/
Kassan: #8 - /kassan/
Mitt konto: #9 - /mitt-konto/
Allmänna villkor: ❌ Sida har inte valts

### Theme ###

Name: Hestia
Version: 3.0.6
Author URL: https://themeisle.com
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 101
Oldest: 2020-11-03 16:13:16 +0100
Newest: 2020-11-16 16:22:56 +0100

Pending: 1
Oldest: 2020-11-16 20:48:06 +0100
Newest: 2020-11-16 20:48:06 +0100

`
```
</details>

**Comment by lakshmana** [comment] 2021-08-07 10:40
Hi @tammullen did you finally got it fixed ? Can you share your solutions and findings ?

**Comment by rrennick** [comment] 2021-10-20 17:58
@jacobtilly Based on the limited information in your description this appears to be a duplicate of #28130. As that issue already has discussion and more details, I'll close this issue in favour of it. It would help us investigate the issue if we had a complete code sample that reproduces the issue.

**Closed by rrennick** 2021-10-20 17:58 UTC
Labels: needs developer feedback
