### ISSUE TITLE
Variation field/Tab is not showing up under Product data

### ISSUE THREAD

**Issue by JJHEALTHCARE** [woocommerce/woocommerce#29067] opened 2021-02-09 06:17 UTC
When I add new product and try to add variations, User is unable to find variation field or tab under Product data on Edit Product page. Please see attached screenshot. 

![Screenshot (22)_LI](https://user-images.githubusercontent.com/78783262/107323517-651bbf80-6a74-11eb-8895-b93cf224341c.jpg)

**Comment by JJHEALTHCARE** [comment] 2021-02-09 20:24
Is there any update on this? 

Variation filed/tab use to be there before and now I don't see that field anymore. Please fix this issue asap.

Thanks!

**Comment by tammullen** [comment] 2021-02-11 18:08
Hi @JJHEALTHCARE 

Thank you for raising the issue. However, I can’t reproduce it on my end.
​
![Screenshot 2021-02-11 at 18 07 47](https://user-images.githubusercontent.com/24649833/107679177-26fce680-6c94-11eb-92ee-36bb036d3a65.png)

​
I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by JJHEALTHCARE** [comment] 2021-02-12 22:14
Hi Tam,

Thank you for getting back to me. I actually fixed the issue by just
updating my woocommerce plugin.
Thanks for your help anyways. I guess it's really important to catch when
the updates are available.

Have a great day.

Best regards,

*JJ Healthcare ProductsInspiring Better Health*

**Comment by juliaamosova** [comment] 2021-02-27 00:33
Hi @JJHEALTHCARE,

Thanks for your follow! Great to hear that the issue had been fixed on your end. And you are right indeed - it is best to try to update WooCommerce as soon as the new version is available to stay up to date with changes and bug fixes. 

I am going to close this thread as it is resolved.

**Closed by juliaamosova** 2021-02-27 00:33 UTC
Labels: category: can't reproduce, needs feedback
