### ISSUE TITLE
Importing products cannot be forced to 0

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#19574] opened 2018-03-29 16:44 UTC
Importing existing products to force stock count to 0 does not work.

## Steps to reproduce the issue

1. Create a variation with a stock of 1 and another with a stock of 0
2. Export variations.
![Screenshot](http://cld.wthms.co/ibEAwQ+)
Image Link: http://cld.wthms.co/ibEAwQ

3. Change stock count for each variation from 1 to 0 and 1 to 0 accordingly 
![Screenshot](http://cld.wthms.co/2YERWk+)
Image Link: http://cld.wthms.co/2YERWk
4. Import changes

Also, altered products to stock count of 0 are forced to backorder status:

![Screenshot](http://cld.wthms.co/igNsnM+)
Image Link: http://cld.wthms.co/igNsnM

If you export again the sheet still reads as 0 for `Backorders Allowed` but status will show as backorder for `In Stock?` column.
## Expected/actual behavior

Changes from 0 to 1 worked as expected ( http://cld.wthms.co/ulvetF ) but from 1 to 0 does not have the "Out of Stock" label ( http://cld.wthms.co/lqKXMF ) 

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment] 2018-03-30 18:17
Duplicate of #19485 and fixed in #19504.

**Closed by claudiulodro** 2018-03-30 18:17 UTC
Labels: Invalid / Duplicate
