### ISSUE TITLE
Shipping Destination setting not working

### ISSUE THREAD

**Issue by lock2photo** [woocommerce/woocommerce#25493] opened 2020-01-26 02:48 UTC
When setting the shipping destination option to default to customer billing address, it does not default to billing address only during checkout.  It used to operate where the customer had to check the box "Shipping Address different" before it would open the second set of address fields.

Thanks,
Drew Lockwood
----
`
### WordPress Environment ###

WordPress address (URL): https://www.botpix.com
Site address (URL): https://www.botpix.com
WC Version: 3.9.0
REST API Version: ✔ 1.0.6
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.29 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.48.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.0
WC Database Prefix: wp_
Total Database Size: 235.70MB
Database Data Size: 200.41MB
Database Index Size: 35.29MB
wp_woocommerce_sessions: Data: 0.23MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 1.77MB + Index: 0.88MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 14.30MB + Index: 9.12MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.19MB + Index: 0.15MB + Engine MyISAM
wp_comments: Data: 7.11MB + Index: 2.65MB + Engine MyISAM
wp_duplicator_packages: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_flag_album: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_flag_comments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_flag_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_flag_pictures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_layerslider: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_layerslider_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_maxbuttons_buttons: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_image_storage: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_section_storage: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_slides: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_ngg_album: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_pictures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 3.13MB + Index: 0.16MB + Engine MyISAM
wp_pluginSL_traffic_manager: Data: 0.75MB + Index: 0.09MB + Engine MyISAM
wp_postmeta: Data: 46.97MB + Index: 17.79MB + Engine MyISAM
wp_posts: Data: 13.32MB + Index: 1.47MB + Engine MyISAM
wp_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_terms: Data: 0.05MB + Index: 0.09MB + Engine MyISAM
wp_term_relationships: Data: 0.31MB + Index: 0.55MB + Engine MyISAM
wp_term_taxonomy: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wp_usermeta: Data: 2.66MB + Index: 1.63MB + Engine MyISAM
wp_users: Data: 0.17MB + Index: 0.13MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.16MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpml_mails: Data: 109.00MB + Index: 0.17MB + Engine MyISAM
wp_wpsd_trends: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 3738
avia_framework_post: 10
custom_css: 1
display_type: 7
forum: 1
gal_display_source: 5
global_product_addon: 14
lightbox_library: 7
nav_menu_item: 56
page: 28
portfolio: 44
post: 132
product: 635
product_variation: 1735
revision: 2340
scheduled-action: 8
shop_coupon: 1
shop_order: 9742
shop_order_refund: 159
topic: 2
wc_order_email: 11
wc_order_status: 18
wc_stamps_label: 150

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

bbPress: by The bbPress Contributors – 2.6.3
CategoryTinymce: by Kevin Heath – 3.8.1
Classic Editor: by WordPress Contributors – 1.5
Code Snippets: by Shea Bunge – 2.13.3
Duplicate Post: by Enrico Battocchi – 3.2.4
Easy SwipeBox: by Leonardo Giacone – 1.1.0
Google XML Sitemaps: by Arne Brachhold – 4.1.0
One Click SSL: by Tribulant Software – 1.4.7
PHP Compatibility Checker: by WP Engine – 1.5.0
Post Types Order: by Nsp Code – 1.9.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.2
Simple Image Sizes: by Rahe – 3.2.1
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.22
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.21

WooCommerce Checkout Field Editor: by WooCommerce – 1.5.27 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.7.2
WooCommerce MX Merchant Payments: by Hot Coffey Design – 1.7.3 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.17
WooCommerce Order Status Change Notifier: by WooThemes – 1.1.0 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager: by SkyVerge – 1.11.3
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.21
WooCommerce: by Automattic – 3.9.0
WooDojo: by WooThemes – 1.5.4
WP Mail Logging: by MailPoet – 1.9.5
WP Mail SMTP: by WPForms – 1.8.1
WP Max Submit Protect: by Academe Computing – 1.1.2 – Not tested with the active version of WooCommerce

### Inactive Plugins (12) ###

Disable Gutenberg: by Jeff Starr – 2.0
Duplicator: by Snap Creek – 1.3.24
Easy SMTP: by James Stamford <jstamford75@gmail.com> – 1.0
Per page head: by Erik von Asmuth – 1.4.2
PhotoMosaic for WordPress: by makfak – 2.15.8
Pronamic Google Maps: by Pronamic – 2.3.2
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.8

Responsive Lightbox & Gallery: by dFactory – 2.2.2
Smart Slider 3: by Nextend – 3.3.26
Traffic Manager: by SedLex – 1.4.5
WooCommerce Blocks: by Automattic – 2.5.11 – Not tested with the active version of WooCommerce
WP Rollback: by Impress.org – 1.7.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Propulsion
Version: 4.3
Author URL: http://www.kriesi.at
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 7
Oldest: 2019-12-31 09:10:56 -0600
Newest: 2020-01-23 15:21:06 -0600

Pending: 1
Oldest: 2020-01-28 09:12:05 -0600
Newest: 2020-01-28 09:12:05 -0600

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by juliaamosova** [comment] 2020-01-28 13:05
Hi @lock2photo,

Thank you for submitting the issue. However, I don't fully understand it. 

Everything is working as expected as far as I can tell. 

I have `Shipping destination` set to `Default to customer billing address`:

![ship1](https://user-images.githubusercontent.com/19143190/73266361-aaa17d80-41ce-11ea-836a-0df2fc3a60ef.jpg)

At the checkout, I have shipping destination default to billing address indeed. There is also an option to select different shipping address if needed:

![ship2](https://user-images.githubusercontent.com/19143190/73266425-c6a51f00-41ce-11ea-9b9e-3fd13d4e6a83.jpg)

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by lock2photo** [comment] 2020-01-28 19:13
Thanks for your thorough reply.  This is exactly how our site has been set
for years - Default to billing address.  But recently it was brought to my
attention that despite that setting being correctly checked in the
woocommerce shipping options, when a customer is checking out, the checkbox
that says "Ship to a different address?" is pre-checked forcing the second
set of address fields to be displayed.  What would cause this?  What can I
do to troubleshoot?

*Drew Lockwood *
drew@botpix.com

*Best of Times Photography - *www.botpix.com
2062 South 26th St., Moorhead, MN 56560
Studio 218.512.0373 • Event 218.512.0632

**Comment by apmwebdev** [comment] 2020-01-28 20:24
I've been getting multiple users reporting this issue as well. One ticket is #2664991-zen. This one is helpful because it is a staging site that we have admin credentials for and can clearly reproduce the issue. I went through full conflict testing, and it still was happening for existing users even in barebones mode, although when I created a new user in barebones mode it didn't happen for them.

There is also a forum thread [here](https://wordpress.org/support/topic/ship-to-diffrent-adress-is-pre-checked-since-update/) where five different users are reporting that this started happening after they updated to WooCommerce 3.9.0.

**Comment by apmwebdev** [comment] 2020-01-28 21:46
Another instance of this happening: #16454238-hc

**Comment by tsetend** [comment] 2020-01-29 11:52
Another issue reported on 2669645-zen. Did a full conflict test with Twenty Nineteen and WooCommerce only but the "Ship to different address" is checked in checkout even with shipping destination set as " Default to customer billing address". They mentioned, it happened after the update.

**Comment by claudiosanches** [comment] 2020-01-29 15:03
I'm not able to reproduce it, I have registered a new user and also with a already registered user, and both seems to be working fine.
But the only change that may have caused it is https://github.com/woocommerce/woocommerce/pull/24271

So sounds like those customers have some different on their shipping address and this code is forcing to display it.
I'll check how to simulate it, and how we can improve this code, but if you turn off "Ship to different address" and place an order will prevent from the "Ship to different address" get enabled again.

**Comment by claudiosanches** [comment] 2020-01-29 15:17
@juliaamosova in order to reproduce need to set a shipping address that isn't the same of the billing address.

**Closed** 2020-02-03 17:06 UTC
Labels: bug, has pull request, priority: high

**Comment by lock2photo** [comment] 2020-02-03 20:09
Look I'm not a developer, only the site manager for a small company - the core of wordpress and woocommerce's business model I might add.  I simply followed the link provided at the top of my wordpress site to Github to report a bug as requested.  Which this is a bug... albeit not critical and forcing us out of business as your tags imply.  But a definite bug affecting the checkout experience of my customers.  It seems to me that you have bumped this fix on to the v4.  Is that correct?  

Also, the reference to #25521 focusing on shipping calculation methods, while quite possibly related at the underlying code (but it's well above my capability and understanding) seems to miss the UX point of that little checkbox.  As a customer, I want to type in as little as possible during checkout and look at as simple of a screen as possible.  I will always have to give billing details, but if the product I'm ordering is shipping to the exact same place, I shouldn't have to do or type anything else.  In real world testing over the weekend, customers continued to retype their entire address sequence before ever thinking to un-check that box.  This is simple, the settings option is available in woocommerce and it is simply is not working.  

Will this be fixed, or not?

**Comment by peterfabian** [comment] 2020-02-03 21:47
Hi @lock2photo , thanks for reporting the bug, we've managed to reproduce it and the fix for this issue should be included in the next release.

**Comment by lock2photo** [comment] 2020-02-04 17:16
Thanks for the simple clarity for a lowly end user.  We do appreciate all
the work you guys do.

**Comment by intoto-digital** [comment] 2020-03-11 11:20
We are still seeing this issue on a 3.9.1 WooCommerce webshop and wonder if we need to update to 4.0 to have this fixed or should 3.9.1 have fixed this?

**Comment by juliaamosova** [comment] 2020-03-11 14:23
@intoto-digital yes, the final fix for this issue ended up being a part of 4.0 release: https://github.com/woocommerce/woocommerce/pull/25521.
