### ISSUE TITLE
Tax calculation bug [Different prices display for logged in user and non logged in user]

### ISSUE THREAD

**Issue by sanjeev051996** [woocommerce/woocommerce#30037] opened 2021-06-03 19:45 UTC
1.  to reproduce:
  In the tax config for woocommerce plugin:
  1. select -> Yes, I will enter prices inclusive of tax
  2. select -> Display prices in the shop -> excluding tax
  3. select -> Display prices during basket and checkout -> including tax
  4. set value -> Price display suffix -> "plus 18% GST"

2. Do not login into the woo-commerce store and visit the shop or products page and see the prices displayed. Also check the prices displayed in basket/cart or on checkout page [Notice Tax computation here]

3. Now Login into the store and repeat the step 2.
Corresponding prices are different in step1 and step2 i.e. logged in or not logged in state of user is affecting tax computaion.

Kindly look into the issue and resolve asap.

**Comment by tammullen** [comment] 2021-06-04 16:56
Hi @sanjeev051996 ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [Setting up Taxes in WooCommerece](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#calculate-tax-based-on)
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-06-04 16:56 UTC
