### ISSUE TITLE
wrong default `period` parameter in `sales-report` endpoint

### ISSUE THREAD

**Issue by millerf** [woocommerce/woocommerce#29029] opened 2021-02-04 11:51 UTC
**Describe the bug**
Unlike the [documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-sales-report), default `period` parameter for the `/reports/sales/` endpoint seem to be `day` instead of `week`

**Expected behavior**
```
curl "https://fragile-oystercatcher.jurassic.ninja/wp-json/wc/v3/reports/sales" -u ck_5d38a40ec2cfdc5053e2a705e7871a5de5a37e31:cs_581294f503e584bed5010808b5942245206cd32c
```
and 
```
curl "https://fragile-oystercatcher.jurassic.ninja/wp-json/wc/v3/reports/sales?period=week" -u ck_5d38a40ec2cfdc5053e2a705e7871a5de5a37e31:cs_581294f503e584bed5010808b5942245206cd32c
```
Should return the same results

**Actual behavior**
Omitting `period` will return sales for the day only

**Versions**
Happens in version from `4.5.1` (AFAIK)  till latest `5.0.0-rc.2` (probably is older than that)

**Comment by juliaamosova** [comment] 2021-02-06 17:38
Hi @millerf,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

The [documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-sales-report) indeed reads that the default sales period is `week`:

![docs](https://user-images.githubusercontent.com/19143190/107125428-feca4d80-6877-11eb-95e0-eb15668f1d3f.jpg)

Running `/wp-json/wc/v3/reports/sales` request produces results of today's sales (one day instead of a week):

![day](https://user-images.githubusercontent.com/19143190/107125442-16a1d180-6878-11eb-9855-87d3d0ed1067.jpg)

Running `/wp-json/wc/v3/reports/sales?period=week` produces the results of sales per week as expected (running `/wp-json/wc/v3/reports/sales` should produce the same result):

![week](https://user-images.githubusercontent.com/19143190/107125468-39cc8100-6878-11eb-923e-6197c9d38d7d.jpg)

We’re going to work on solving this issue as soon as possible.

**Comment by roykho** [comment] 2021-02-12 15:42
So I've had a look into this and the fix is not straight forward because this is potentially a breaking change. For the people who has already used this will still be expecting `day` instead of `week`.

Possible solutions:

1. Version it to 4 with new logic to prevent breaking changes.
2. Update documentation to state `day` as the default. This is probably the path of least resistant and does not break anything as people can specify `week` as the period.
3. Proceed to change the behavior which may break for people who is already expecting `day` and also may break for people who are using custom dates because we're expecting `period` parameter to be null before custom dates are factored in. See https://github.com/woocommerce/woocommerce/blob/master/includes/rest-api/Controllers/Version1/class-wc-rest-report-sales-v1-controller.php#L251

I am leaning towards solution 2 for least impact. cc @woocommerce/proton for more suggestions.

**Comment by vedanshujain** [comment] 2021-02-12 17:28
Let's go ahead with solution 2, I believe it is the only feasible solution that we can do now to close this issue.

**Comment by millerf** [comment] 2021-02-12 17:41
> I am leaning towards solution 2 for least impact. cc @woocommerce/proton for more suggestions.

Makes sense. No need to impact anyone for such a small and issue...

**Comment by roykho** [comment] 2021-02-12 20:16
Thanks again for reporting this @millerf - I've created a PR to fix this in our API documentation repo here https://github.com/woocommerce/woocommerce-rest-api-docs/pull/193 I will be closing this issue here for now.

**Closed by roykho** 2021-02-12 20:16 UTC
Labels: category: wc rest api, priority: high, type: bug
