### ISSUE TITLE
No feedback while payment is processing with Twenty Twenty theme

### ISSUE THREAD

**Issue by guicmazeredo** [woocommerce/woocommerce#27656] opened 2020-09-11 11:58 UTC
**Describe the bug**
After clicking on "Place order" button on the checkout page there is no feedback to indicate that the payment is processing. 

**Expected behavior**
After clicking the button I expected to see some overlay and a buffer to make it clear for the user that the transaction is being processed and that they shouldn't click anything and wait why the payment is going through. 

**Actual behavior**
Absolutely nothing happens so the impression is that the "Place order" button is not working. Here is a screencast:

https://d.pr/v/jTHhfk

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

I only tested this with Stripe. I haven't tested with off-site payment gateways.

1. Enable Stripe payment gateway and Twenty Twenty them on the site.
2. Go to 'Shop' page and add an item to the cart
3. Go to the 'Checkout' page
3. Fill in the shipping/billing form and click on 'Place Order'
4. See error (no feedback while the transaction is processing)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://wooselfhostedgui.mystagingwebsite.com
Site address (URL): https://wooselfhostedgui.mystagingwebsite.com
WC Version: 4.5.1
REST API Version: ✔ 4.5.1
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.22
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.72.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 10.10MB
Database Data Size: 5.84MB
Database Index Size: 4.26MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_posts: Data: 0.28MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spin_wheel_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 0.19MB + Index: 0.28MB + Engine InnoDB
wp_wps_key: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 1
attachment: 57
aw_workflow: 1
custom_css: 1
follow_up_email: 1
nav_menu_item: 4
page: 18
post: 1
product: 50
product_variation: 93
revision: 38
shop_coupon: 3
shop_order: 39
shop_order_refund: 3
shop_subscription: 1
wcpf_item: 5
wcpf_project: 1
wc_order_status: 12
wc_pickup_location: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Jetpack by WordPress.com: by Automattic – 8.9
Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.2 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce: by Automattic – 4.5.1

### Inactive Plugins (58) ###

Admin Color Schemes: by WordPress Core Team – 2.3
Akismet Anti-Spam: by Automattic – 4.1.6
AutomateWoo: by WooCommerce – 5.0.0 – Installed version not tested with active version of WooCommerce 4.5.1
Classic Editor: by WordPress Contributors – 1.5
Discounts Per Payment Method on WooCommerce: by Claudio Sanches – 3.1.0 – Installed version not tested with active version of WooCommerce 4.5.1
Follow-Up Emails: by WooCommerce – 4.9.6 (update to version 4.9.7 is available) – Installed version not tested with active version of WooCommerce 4.5.1
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Loco Translate: by Tim Whitlock – 2.3.3
Product Filters for WooCommerce: by WooCommerce – 1.2.1 (update to version 1.2.2 is available) – Installed version not tested with active version of WooCommerce 4.5.1
Request a Quote for WooCommerce: by Addify – 1.4.1 (update to version 1.5.3 is available) – Installed version not tested with active version of WooCommerce 4.5.1
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.5.0
WooCommerce Account Funds: by Themesquad – 2.2.1 (update to version 2.3.1 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.22 (update to version 1.7.24 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.6 (update to version 1.1.7 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce AvaTax: by SkyVerge – 1.10.2 (update to version 1.10.3 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Blocks: by Automattic – 3.2 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Bookings: by WooCommerce – 1.15.17 (update to version 1.15.26 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Brands: by WooCommerce – 1.6.19 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.2.9 (update to version 3.2.11 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Chained Products: by StoreApps – 2.9.6 (update to version 2.9.7 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.33 (update to version 1.5.36 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.7.6 (update to version 1.8.5 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.8.5 (update to version 3.9.0 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.9 (update to version 5.1.1 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Deposits: by WooCommerce – 1.4.20 (update to version 1.5.4 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Distance Rate Shipping: by Automattic – 1.0.20 (update to version 1.0.25 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce EU VAT Number: by WooCommerce – 2.3.21 (update to version 2.3.23 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce FedEx Shipping: by WooCommerce – 3.4.30 (update to version 3.4.32 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.21 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Help Scout: by WooCommerce – 2.4 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Local Pickup Plus: by SkyVerge – 2.8.2 (update to version 2.9.0 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.18 (update to version 2.4.19 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Order Barcodes: by WooCommerce – 1.3.22 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Order Delivery: by Themesquad – 1.6.7 (update to version 1.7.0 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Order Status Manager: by SkyVerge – 1.12.0 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Payment Gateway Based Fees: by InoPlugs – 3.1.10 (update to version 3.1.12 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Payments: by Automattic – 1.0.0 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.36 (update to version 1.6.37 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.9.0 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.30 (update to version 3.0.38 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Product Bundles: by SomewhereWarm – 6.3.3 (update to version 6.3.5 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.35 (update to version 1.10.36 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Product Search: by itthinx – 2.21.0 (update to version 3.1.1 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Royal Mail: by WooCommerce – 2.5.29 (update to version 2.5.31 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Services: by Automattic – 1.23.2 (update to version 1.24.2 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.9 (update to version 2.3.11 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Smart Coupons: by StoreApps – 4.7.5 (update to version 4.8.1 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Square: by WooCommerce – 2.1.4 (update to version 2.2.1 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Subscriptions: by WooCommerce – 3.0.3 (update to version 3.0.7 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.25 (update to version 3.0.29 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce UPS Shipping: by WooCommerce – 3.2.24 (update to version 3.2.28 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.41 (update to version 4.4.47 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.1.1 (update to version 3.1.2 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WP Mail Logging: by MailPoet – 1.9.6
WP Mail SMTP: by WPForms – 2.3.1
WP Rollback: by Impress.org – 1.7.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 236
Oldest: 2020-09-01 10:44:57 +0000
Newest: 2020-09-11 11:56:42 +0000

Pending: 5
Oldest: 2020-09-12 06:00:00 +0000
Newest: 2020-10-02 15:17:30 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-09-11 13:18
Hi @guicmazeredo,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

It doesn't matter what payment gateway is used - the result is the same. I used the `Cash on delivery` payment method in my test. 

Here is what I see in Twenty Twenty (no indication that there is an action in the process after clicking on the `Place order` button):

![](http://g.recordit.co/5GeJv7ZI7a.gif)

And here is what I see in Storefront (there is a running circle indicating that there is an action in the process after clicking on the `Place order` button):

http://g.recordit.co/twMs8zBbPs.gif

At first, it seems that the issue needs to be fixed in Twenty Twenty theme but that theme is a WordPress theme (not WooCommerce) so it is likely that we need to address it on the WooCommerce side of things. 

As far as a priority, usually, we consider this kind of issues to have a `low` priority. However, because Twenty Twenty is a default theme and we agreed that we are going to make sure that customers have the best WooCommerce experience using the default theme, I am giving it a `high` priority.

**Comment by shakil6677** [comment] 2020-09-17 11:36
![a](https://user-images.githubusercontent.com/16381637/93465002-d5257f80-f8f2-11ea-8500-1bdb151babe5.jpg)

**Closed** 2020-11-11 20:53 UTC
Labels: bug, component: checkout, has pull request, priority: high
