### ISSUE TITLE
Discounts off orders above a certain amount

### ISSUE THREAD

**Issue by Hooly0019** [woocommerce/woocommerce#25986] opened 2020-03-20 22:02 UTC
I need to create a product at which the price changes according to the number of units purchased. Ex.
If you buy 12. the price per unit is $ 9.50 = $ 114
If you buy 24. the price per unit is $ 9.00 = $ 216
If you buy 50. the price per unit is $ 8.50 = $ 425. Etc.

How can I make the store show me the price per unit but in the cart show the final or total price?

**Comment by juliaamosova** [comment] 2020-03-23 18:50
Hi @Hooly0019,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a pre-sale support request.

Next time, please contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/) and selecting `pre-sale` option in order to get help with questions like this. 

As a one time exception, I can recommend a plugin called [Dynamic Pricing](https://woocommerce.com/products/dynamic-pricing/) to accomplish what you are looking for. 

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-03-23 18:50 UTC
