### ISSUE TITLE
Woocommerce keeps crashing my website.. 

### ISSUE THREAD

**Issue by Prateekjain2003** [woocommerce/woocommerce#27088] opened 2020-07-21 16:42 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by Prateekjain2003** [comment] 2020-07-21 16:46
`
### WordPress Environment ###

WordPress address (URL): https://www.zippikids.com
Site address (URL): https://www.zippikids.com
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.12
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_t879q315jr_
Total Database Size: 20.72MB
Database Data Size: 18.00MB
Database Index Size: 2.72MB
wp_t879q315jr_woocommerce_sessions: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_t879q315jr_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_t879q315jr_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_t879q315jr_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_ahm_assets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_ahm_download_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_ahm_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_t879q315jr_dlm_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_dlm_order_customer: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_dlm_order_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_dlm_order_transaction: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_dlm_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_download_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_edd_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_edd_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_mnet_ad_paragraph_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_mnet_ad_post_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_mnet_ad_slots: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_mnet_ad_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_mnet_blocked_urls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_mnet_external_ad: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_mnet_log_retry: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_mnet_slot_blocked_urls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_options: Data: 2.47MB + Index: 0.09MB + Engine InnoDB
wp_t879q315jr_postmeta: Data: 2.52MB + Index: 0.42MB + Engine InnoDB
wp_t879q315jr_posts: Data: 9.36MB + Index: 0.38MB + Engine InnoDB
wp_t879q315jr_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_t879q315jr_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_t879q315jr_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_t879q315jr_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_t879q315jr_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_t879q315jr_yoast_indexable: Data: 0.47MB + Index: 0.27MB + Engine InnoDB
wp_t879q315jr_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_t879q315jr_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_t879q315jr_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_t879q315jr_yoast_seo_links: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_t879q315jr_yoast_seo_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 773
custom_css: 1
customize_changeset: 18
dlm_download: 2
dlm_download_version: 2
dlm_product: 1
download: 5
edd_payment: 2
nav_menu_item: 26
oembed_cache: 80
page: 13
post: 97
product: 8
revision: 1573
shop_order: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.6
CoBlocks: by GoDaddy – 2.0.3
Social Media Follow Buttons Bar: by Space X-Chimp – 4.59
WooCommerce: by Automattic – 4.3.0
Yoast SEO: by Team Yoast – 14.6.1
WPForms Lite: by WPForms – 1.6.1

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

object-cache.php: APCu Object Cache

### Must Use Plugins (1) ###

System Plugin: by  – 3.16.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2733 - /shop/
Cart: #2734 - /cart/
Checkout: #2735 - /checkout/
My account: #2736 - /my-account/
Terms and conditions: #2368 - /terms-of-use-agreement/

### Theme ###

Name: Newspaper X
Version: 1.3.1
Author URL: https://colorlib.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 131
Oldest: 2020-06-20 22:55:27 +0530
Newest: 2020-07-21 18:58:12 +0530

Pending: 2
Oldest: 2020-07-22 18:58:12 +0530
Newest: 2020-07-22 18:58:12 +0530

`

**Comment by peterfabian** [comment] 2020-07-22 11:26
Hi @Prateekjain2003

Apologies for the problems. Can you please share a bit more information? Do you see any errors in your browser or in PHP log? Can you please provide steps to reproduce the bug? Thanks!

**Comment by Prateekjain2003** [comment] 2020-07-22 14:11
Hi @peterfabian  Its so random that i am not able to figure out how to recreate it.. the person handling my website said that some process keeps running and takes the website down with it..

**Comment by peterfabian** [comment] 2020-07-23 08:36
> the person handling my website said that some process keeps running and takes the website down with it

Would they be able to identify the process? Can you please get PHP error log in case the process is logging something that could give us some clues on what is causing the problem?

**Comment by Prateekjain2003** [comment] 2020-07-23 17:35
[debug.log](https://github.com/woocommerce/woocommerce/files/4967796/debug.log)

**Comment by Prateekjain2003** [comment] 2020-07-23 18:39
Does the above file help?

**Comment by tammullen** [comment] 2021-03-25 20:10
Hi @Prateekjain2003 

Sorry for the delay in replying.

From the attached log if looks like the problem might be caused by another plugin.

Please make sure you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

If you confirm a bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now as it appears to be a support request. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 20:10 UTC
Labels: has feedback
