### ISSUE TITLE
Ordering by price (asc & desc) not working with grouped products

### ISSUE THREAD

**Issue by gerharddt** [woocommerce/woocommerce#20452] opened 2018-06-08 12:37 UTC
**Describe the bug**
When ordering products by price (low to high and high to low) grouped products just gets lumped at the top of the listing or at the bottom of the listing. They don't seem to be ordered at all when you filter by price.

The example link below is a fresh wordpress installation with a fresh woocommerce installation. It's running the storefront theme and no additional plugins. I only added one grouped product to the example products that comes with the theme and hid the products from catalogue that's included in the group. (Tshirt & Vneck Tshirt) (This mimicks the behaviour on the client site where I found the bug)

**To Reproduce**
1. Go to 'http://stage.ninjasforhire.co.za/storefront_test/shop/?orderby=price'
2. See error
3. Go to: 'http://stage.ninjasforhire.co.za/storefront_test/shop/?orderby=price-desc'

**Expected behavior**
The grouped product needs to be in the listing between other products where the product just before it needs to cost less than cheapest product in the group and the product after it needs to cost more than the cheapest product in the group

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default  WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
default latest wordpress, default latest woocommerce plugin (only plugin), only default storefront theme (latest)
```
`
### WordPress Environment ###

Home URL: http://stage.ninjasforhire.co.za/storefront_test
Site URL: http://stage.ninjasforhire.co.za/storefront_test
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.33-0+deb8u1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 3600
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.35-MariaDB-1~jessie
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.83MB
Database Data Size: 0.98MB
Database Index Size: 0.85MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.38MB + Index: 0.02MB
wp_postmeta: Data: 0.08MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 1
page: 7
post: 2
product: 13
revision: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rodrigoprimo** [comment] 2018-06-08 17:20
Closing this issue as this is the intended behavior and not a bug. Grouped products don't have a price since the customer can select different products to add to cart and that is why they are not ordered in the listing.

> The grouped product needs to be in the listing between other products where the product just before it needs to cost less than cheapest product in the group and the product after it needs to cost more than the cheapest product in the group

cc @mikejolley in case this proposed solution hasn't been considered in the past and is something you think we should explore.

**Comment by gerharddt** [comment] 2018-06-08 18:14
This can't possibly be intended behaviour.. more like a shortfall.. in which case it needs to rectified. 

You can even split it up if you need to. if you filter low to high, it can be based on the cheapest child's price and from high to low the opposite can apply.

The way it's working now is just bad for the end-user. If you want to filter by price all your options needs to be sorted like that, otherwise it renders the entire filter pointless..

**Comment by gerharddt** [comment] 2018-06-09 13:03
@mikejolley In my example above I used a fresh wp and woocommerce and manually added the grouped product. it still doesn't seem to put it anywhere close to the right place. 

I just think the end-user experience is broken the way it is.

**Comment by mikejolley** [comment] 2018-06-11 09:54
Prices are empty so the sync looks broken.

**Comment by mikejolley** [comment] 2018-06-11 10:47
See https://github.com/woocommerce/woocommerce/pull/20482

**Closed by mikejolley** 2018-06-11 10:47 UTC
