### ISSUE TITLE
Manual create order - browser error

### ISSUE THREAD

**Issue by oraclerob** [woocommerce/woocommerce#24357] opened 2019-08-08 10:11 UTC
**Describe the bug**
When  using the order screen to create a new order manually, nothing happens when you press the "Create" button as a browser error occurs.

**An invalid form control with name='post_title' is not focusable.**

**Removing the "required" attribute on "post_title" fixes the issue.**

**To Reproduce**
1. Go to 'Woocommerce->order'
2. 'Fill in order'
3. Click "Create"
4. Order not created, javascript error on all browsers, Chrome/Firefox/Safari

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
5.2
woocommerce 3.6.5 
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
`
### WordPress Environment ###

WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 20 MB
PHP Time Limit: 600
PHP Max Input Vars: 20000
cURL Version: 7.52.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 16.57MB
Database Data Size: 13.97MB
Database Index Size: 2.60MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.31MB + Index: 0.47MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.09MB + Index: 0.05MB
wp_options_bkup: Data: 0.09MB + Index: 0.00MB
wp_postmeta: Data: 1.23MB + Index: 0.36MB
wp_posts: Data: 6.52MB + Index: 0.36MB
wp_posts_bkup: Data: 3.52MB + Index: 0.00MB
wp_siq_sync: Data: 0.02MB + Index: 0.00MB
wp_statistics_exclusions: Data: 0.02MB + Index: 0.03MB
wp_statistics_historical: Data: 0.02MB + Index: 0.05MB
wp_statistics_pages: Data: 0.02MB + Index: 0.08MB
wp_statistics_search: Data: 0.02MB + Index: 0.05MB
wp_statistics_useronline: Data: 0.02MB + Index: 0.00MB
wp_statistics_visit: Data: 0.02MB + Index: 0.02MB
wp_statistics_visitor: Data: 0.02MB + Index: 0.08MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpsc_account: Data: 0.02MB + Index: 0.00MB
wp_wpsc_additional_fields_meta: Data: 0.02MB + Index: 0.00MB
wp_wpsc_categories: Data: 0.02MB + Index: 0.00MB
wp_wpsc_imap: Data: 0.02MB + Index: 0.00MB
wp_wpsc_notifications: Data: 0.05MB + Index: 0.00MB
wp_wpsc_piping_preview: Data: 0.02MB + Index: 0.00MB
wp_wpsc_priority: Data: 0.02MB + Index: 0.00MB
wp_wpsc_reminders: Data: 0.02MB + Index: 0.00MB
wp_wpsc_settings: Data: 0.02MB + Index: 0.00MB
wp_wpsc_status: Data: 0.02MB + Index: 0.00MB
wp_wpsc_templates: Data: 0.02MB + Index: 0.00MB
wp_wpsc_threads: Data: 0.02MB + Index: 0.00MB
wp_wpsc_threads_read: Data: 0.02MB + Index: 0.00MB
wp_wpsc_tickets: Data: 0.02MB + Index: 0.00MB
wp_wpsc_tickets_recurring: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 187
custom_css: 2
is_search_form: 1
nav_menu_item: 4
page: 25
post: 2
postman_sent_mail: 14
product: 1
project: 19
revision: 89
scheduled-action: 692
shop_order: 6
upst_milestone: 37
up_custom_field: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

**Comment by rodrigoprimo** [comment] 2019-08-12 19:22
Hi there,

I was not able to reproduce this issue on a clean WooCommerce install. Creating orders manually in the WordPress admin seems to be working as expected.

Have you tried already disabling all plugins except WooCommerce to rule out plugin conflict? (https://docs.woocommerce.com/document/how-to-test-for-conflicts/)

Could you please provide more details about the JavaScript error? What is the file and line where this error is happening? Where exactly are you removing the `required` attribute from the `post_title` field?

Thanks

**Comment by oraclerob** [comment] 2019-08-13 00:30
I have found where the error is. It is a plugin when activated causes the post_title to become "required".  This is in the /post-new.php?post_type=shop_order file. The plugin is: UpStream Custom Fields. I'll contact the vendor to see why this is occurring.

```
<div id="titlediv">
<div id="titlewrap">
		<label class="" id="title-prompt-text" for="title">Add title</label>
	<input type="text" name="post_title" size="30" value="" id="title" spellcheck="true" autocomplete="off" required>
</div>
```

**Comment by oraclerob** [comment] 2019-08-13 10:30
I've fixed the issue by altering the post_title required attribute in a function hook. I have not been able to find any code by any plugin (including the one I disabled) that alters the post_title input to be required. There is something going on with the metabox cmb functions which I can't understand.

Below is the code implemented to fix the problem, but this is just a workaround as we need to understand what is causing the required attribute to be set.

```
////////////////////////////////////////////////////// 
// Add to the new post screen for any post type
add_action( 'admin_footer-post-new.php', 'wpse_add_required_attr_to_title_field' );

// Add to the post edit screen for any post type
add_action( 'admin_footer-post.php', 'wpse_add_required_attr_to_title_field' );

function wpse_add_required_attr_to_title_field() {
    ?>
    <script>
        jQuery(document).ready(function($){
            $('input[name=post_title]').prop('required',false);
        });
    </script>
    <?php
}
```

**Comment by rodrigoprimo** [comment] 2019-08-14 12:51
Thanks for the clarification, @oraclerob. Closing this issue as the problem is not caused by WooCommerce core.

**Closed by rodrigoprimo** 2019-08-14 12:51 UTC
Labels: status: needs feedback
