### ISSUE TITLE
Checkout reform

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#22682] opened 2019-02-07 18:20 UTC
**The checkout is one of woocommerce's weakest areas.** 

Unchanged since I started using Woo many years ago. It's out of order and is painful to customise. I look at other e-commerce checkout pages to see how they're tackling one of the most important pages on the site. I think at the moment, shopify has a golden standard for the checkout and should be worth bringing up: 

**Questions that need addressing:**

**Why is the coupon a click to drop-down for at the top of the page?** Since when is a coupon the first thing you see in a shop ever? No name, no order.... a coupon.

**Why are all the elements of the checkout non-uniform?** We've got random `h3` elements floating around; hardcoded div classes in the templates etc.

**Why is the whole page in a form?** This is the most legacy part of the page, it's something that stops you from moving the account form or the coupon form.

I'd love to know if the checkout is on the roadmap to be rebuilt, because at the moment, the latest 10 sites form the woo showcase all have the same issues with the checkout.

**Comment by claudiulodro** [comment] 2019-02-07 18:40
Thanks for the feedback. This is a duplicate of https://github.com/woocommerce/woocommerce/issues/10672, and more info about plans is available there.

[A re-approach of the checkout is on the roadmap](https://trello.com/c/VtilWVo4/114-better-checkout-experiences-new-flows), but it will likely not be in the first part of this year.

**Closed by claudiulodro** 2019-02-07 18:40 UTC

**Comment by yratof** [comment] 2019-02-07 18:46
I can see that dialogue for it ended 2-3 years ago?!
