### ISSUE TITLE
Problem Breadcrumbs

### ISSUE THREAD

**Issue by Tecommerce** [woocommerce/woocommerce#26938] opened 2020-07-02 13:55 UTC
Hello,

I have a problem with breadcrumbs.

I have put a product in two categories ( Joints For 25 X 25 Square Tubes and Joints For 20 X 20 Square Tubes).

breadcrumps are always “Home>Square Pipe Couplings 25 X 25>Square Pipe Couplings,….”.

Instead I would like to see, when I enter in the category 20×20 “Home>Square Tubing Joints 20 X 20>Square Tubing Joints 20 X 20>Clamps……

When I enter the 25 “Home>Square Pipe Couplings 25 X 25>Square Pipe Couplings, ..” category.

https://jointmodular.design/c/giunti-2/giunti-per-tubi-quadri-20-x-20/morsetti-reggipiani-ventose-piastrine/

https://jointmodular.design/c/giunti-2/giunti-per-tubi-quadri-25-x-25/morsetti-reggipiani-ventosesupporti-piastrine/

If you click the product “Ventosina Ø 12 per foro da Ø 4.5 mm” in the breadcrumbs always appears the category 25×25 also step from category 20×20.

how can I do that?

Regards

**Comment by tammullen** [comment] 2020-07-02 19:44
Hi @Tecommerce 


While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-07-02 19:44 UTC
