### ISSUE TITLE
Woocommerce rounding issue

### ISSUE THREAD

**Issue by Chavife** [woocommerce/woocommerce#21021] opened 2018-08-09 12:03 UTC
Hello I have really similar bug than issue #20081 which is closed now. But my problems are seem to persist.
So what is my problem... rounding of tax is seem to be be buged. It looks like the problem is in the option of "round tax at subtotal level instead of rounding per line" where I have this option checked. It sometimes happens that on the frontpage i have an +0,01€ at summary. See screenshot at my example.
![image](https://user-images.githubusercontent.com/18663896/43896692-fdfc362e-9bd9-11e8-8876-395393c1a8b3.png)
After and order update (changing status or recalculating the order) this problem fixes and the roudings get to correct values. Looks like something is triggering in the code differently than on the front page calculations.
![image](https://user-images.githubusercontent.com/18663896/43896924-be5ec9ae-9bda-11e8-9a0c-cd8bba8c1b8b.png)

This is not a problem with the shipping.. this rounding problem sometimes happens with products too. See screenshot: 
![image](https://user-images.githubusercontent.com/18663896/43897368-033ed5ae-9bdc-11e8-919a-6d7c61d42696.png)
clearly the **shipping is zero** and it calculates some wierd stuff.

Unchecking the "round tax at subtotal level instead of rounding per line" just alternates the frontpage backend problem around.. it will show the correct price in the front but recalculates it wrong in the backend. **So this is not an option at all**

Was trying to see where is the problem... If i remeber right and i made a good research everything started with the fix of the issue #20081

My tax settings are as follows:
![image](https://user-images.githubusercontent.com/18663896/43897620-ef4295a8-9bdc-11e8-9a93-d337e53629f4.png)
![image](https://user-images.githubusercontent.com/18663896/43897642-00deb292-9bdd-11e8-9dc3-75bc98b6279d.png)

The site is elcigarety.sk so you can try different things but it will recalculate the order to correct values just when it gets an update from the backend.

This is a really bad issue for me.. sometimes the customer pays more by 1 cent than they get in the invoice (invoice is generated when the order is complete).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://elcigarety.sk
Site URL: https://elcigarety.sk
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sk_SK
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.29 - Pre vyšší výkon a bezpečnosť odporúčame používať PHP verziu 7.2 alebo vyššiu. Ako aktualizovať verziu PHP
PHP Post Max Size: 48 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.10
Max Upload Size: 48 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: ec_
Celková veľkosť databázy: 51.77MB
Veľkosť údajov v databáze: 43.48MB
Veľkosť indexu databázy: 8.29MB
ec_woocommerce_sessions: Data: 16.02MB + Index: 0.02MB
ec_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ec_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ec_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
ec_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB
ec_woocommerce_order_itemmeta: Data: 0.44MB + Index: 0.50MB
ec_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ec_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
ec_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ec_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
ec_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ec_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ec_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ec_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ec_aryo_activity_log: Data: 0.13MB + Index: 0.00MB
ec_berocket_termmeta: Data: 0.02MB + Index: 0.00MB
ec_commentmeta: Data: 0.02MB + Index: 0.03MB
ec_comments: Data: 0.19MB + Index: 0.09MB
ec_formmaker: Data: 0.09MB + Index: 0.00MB
ec_formmaker_backup: Data: 1.48MB + Index: 0.00MB
ec_formmaker_blocked: Data: 0.02MB + Index: 0.00MB
ec_formmaker_display_options: Data: 0.02MB + Index: 0.02MB
ec_formmaker_query: Data: 0.02MB + Index: 0.00MB
ec_formmaker_sessions: Data: 0.02MB + Index: 0.00MB
ec_formmaker_submits: Data: 0.02MB + Index: 0.00MB
ec_formmaker_themes: Data: 0.16MB + Index: 0.00MB
ec_formmaker_views: Data: 0.02MB + Index: 0.00MB
ec_gde_profiles: Data: 0.00MB + Index: 0.00MB
ec_gde_secure: Data: 0.00MB + Index: 0.00MB
ec_hugeit_slider_slide: Data: 0.02MB + Index: 0.00MB
ec_hugeit_slider_slider: Data: 0.02MB + Index: 0.00MB
ec_ip_geo_block_cache: Data: 0.02MB + Index: 0.02MB
ec_ip_geo_block_logs: Data: 0.16MB + Index: 0.03MB
ec_ip_geo_block_stat: Data: 0.02MB + Index: 0.00MB
ec_links: Data: 0.02MB + Index: 0.02MB
ec_lockdowns: Data: 0.02MB + Index: 0.00MB
ec_login_fails: Data: 0.08MB + Index: 0.00MB
ec_newsletter: Data: 0.02MB + Index: 0.03MB
ec_newsletter_emails: Data: 0.02MB + Index: 0.00MB
ec_newsletter_sent: Data: 0.02MB + Index: 0.03MB
ec_newsletter_stats: Data: 0.02MB + Index: 0.03MB
ec_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB
ec_options: Data: 4.47MB + Index: 0.17MB
ec_postmeta: Data: 8.52MB + Index: 6.03MB
ec_posts: Data: 10.52MB + Index: 0.64MB
ec_snippets: Data: 0.02MB + Index: 0.00MB
ec_termmeta: Data: 0.06MB + Index: 0.03MB
ec_terms: Data: 0.02MB + Index: 0.03MB
ec_term_relationships: Data: 0.09MB + Index: 0.06MB
ec_term_taxonomy: Data: 0.02MB + Index: 0.03MB
ec_usermeta: Data: 0.02MB + Index: 0.03MB
ec_users: Data: 0.02MB + Index: 0.05MB
ec_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
ec_wc_download_log: Data: 0.02MB + Index: 0.03MB
ec_wc_webhooks: Data: 0.02MB + Index: 0.02MB
ec_weu_subscribers: Data: 0.02MB + Index: 0.00MB
ec_weu_unsubscriber: Data: 0.02MB + Index: 0.00MB
ec_weu_user_notification: Data: 0.02MB + Index: 0.00MB
ec_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB
ec_woof_query_cache: Data: 0.02MB + Index: 0.02MB
ec_yoast_seo_links: Data: 0.08MB + Index: 0.02MB
ec_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

amn_mi-lite: 2
amn_smtp: 1
attachment: 1149
br_labels: 2
custom_css: 1
fmemailverification: 1
form-maker: 1
nav_menu_item: 23
oembed_cache: 7
page: 22
popup: 1
popup_theme: 6
post: 3
product: 357
product_variation: 524
revision: 680
ris_gallery: 1
shop_coupon: 1
shop_order: 142
sidebar: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Age Gate: Phil Baker – 1.5.5
Activity Log: Yakir Sitbon
Maor Chasen
Ariel Klikstein – 2.4.1

České služby pro WordPress: Pavel Hejn – 0.5
Code Snippets: Shea Bunge – 2.10.1.1
Custom Codes: Bilal TAS – 0.3.6
Email Address Encoder: Till Krüss – 1.0.7
Features: WooThemes – 1.5.0
Form Maker Pro: WebDorado Form Builder Team – 2.12.16
Google Analytics for WordPress by MonsterInsights: MonsterInsights – 7.1.0
Google Doc Embedder: Kevin Davis
Dan Lester – 2.6.4

Invisible reCaptcha: Mihai Chelaru – 1.2.1
IP Geo Block: tokkonopapa – 3.0.12
JC Submenu: James Collings – 0.8.4
Login LockDown: Michael VanDeMar – v1.7.1
Max Mega Menu: Tom Hemsley – 2.4.2
PW WooCommerce Bulk Edit: Pimwick
LLC – 2.151

Really Simple SSL: Rogier Lankhorst – 3.0.1
Shipping Icons and Descriptions for WooCommerce: Algoritmika Ltd – 1.1.1 – Nebolo testované s aktívnou verziou WooCommerce
Page Builder by SiteOrigin: SiteOrigin – 2.6.9
SiteOrigin Widgets Bundle: SiteOrigin – 1.11.8
TinyMCE Advanced: Andrew Ozz – 4.7.11
Uber Login Logo: UberWeb – 1.5.1
Under Construction: WebFactory Ltd – 3.05
User Role Editor: Vladimir Garagulya – 4.43
WooCommerce Platba v hotovosti: Marian Kadanka – 1.4.4 – Nebolo testované s aktívnou verziou WooCommerce
WD manager: WebDorado – 1.4.1
WooCommerce Advanced Product Labels: BeRocket – 3.1.4.1 – Nebolo testované s aktívnou verziou WooCommerce
Besteron Buttons Payment Gateway: Besteron – 1.0.8 – Nebolo testované s aktívnou verziou WooCommerce
Woocommerce Cross Sell Products Display: Logicfire – 1.3 – Nebolo testované s aktívnou verziou WooCommerce
WooCommerce Doprava SK: Lukas Hosek – 3.2.3 – Nebolo testované s aktívnou verziou WooCommerce
WooCommerce Extra Charges To Payment Gateway (Standard): hemsingh1 – 1.0.12.9 – Nebolo testované s aktívnou verziou WooCommerce
WooCommerce PayPal Express Checkout Gateway: WooCommerce – 1.5.6
WooCommerce PDF Invoices & Packing Slips: Ewout Fernhout – 2.1.9
WooCommerce PDF Invoices & Packing Slips Premium Templates: Ewout Fernhout – 2.4.1 – Nebolo testované s aktívnou verziou WooCommerce
WooCommerce Products Image Watermark: BeRocket – 2.0.3.8
WooCommerce Flat Rate Box Shipping: WooCommerce – 2.0.5
WooCommerce Stock Manager: Vladislav Musílek – 1.2.6 – Nebolo testované s aktívnou verziou WooCommerce
WooCommerce: Automattic – 3.4.4
WooSidebars: WooThemes – 1.4.3
Yoast SEO: Team Yoast – 7.6.1
WP Mail SMTP: WPForms – 1.2.5
WP Rollback: WordImpress – 1.5.1
Custom Product Tabs for WooCommerce: YIKES
Inc. – 1.6.4 – Nebolo testované s aktívnou verziou WooCommerce


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Slug pre obchod: #4 - /obchod/
Košík: #5 - /nakupny-kosik/
Pokladňa: #6 - /pokladna/
Môj účet: #7 - /my-account/
Všeobecné obchodné podmienky: #981 - /vsetko-o-nakupe/vseobecne-obchodne-podmienky/

### Theme ###

Name: Boutique
Version: 2.0.11 – 2.0.15 je dostupný
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.8 – 2.3.3 je dostupný
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: boutique/woocommerce/emails/customer-completed-order.php
boutique/woocommerce/emails/customer-on-hold-order.php
boutique/woocommerce/emails/customer-processing-order.php
boutique/woocommerce/emails/email-addresses.php
boutique/woocommerce/myaccount/form-edit-account.php verzia 2.6.0 je zastaralá. Verzia jadra je 3.4.0

Outdated Templates: ❌
					
					
						Naučte sa ako aktualizovať
`
```
</details>

**Comment by willgorham** [comment] 2018-08-09 15:56
Rounding at subtotal level seems to be discouraged and might cause issues. See: https://github.com/woocommerce/woocommerce/issues/20440#issuecomment-395812969, https://github.com/woocommerce/woocommerce/issues/18176#issuecomment-351774911, https://github.com/woocommerce/woocommerce/issues/19525#issuecomment-376126732. Sounds like the problem might be in the back-end calculation when this setting is turned off.

**Comment by Chavife** [comment] 2018-08-09 16:26
rounding at subtotal helps in optimizing the tax.. It should calculate a bit less tax like that. That's why it is used.. but it doesn't matter that much.
It should work like so..
All the prices of products will be summed together without the tax and the tax will be added on this final summary.. if I understant this right. In the code what i have seen this option calculates the tax per product AND also in the checksum... But not 100% sure that this is the issue

I would rather remove this option at a price of working calculations. 

For now if i don't have this option enabled the recalculation in the backend will calculate wrong.

**Comment by Chavife** [comment] 2018-08-09 17:08
exactly what I wrote... the functions is rounding per line and ALSO in the checksum

![image](https://user-images.githubusercontent.com/18663896/43913414-3354be42-9c05-11e8-830d-6bc9990e8c16.png)

See this example
This is how the function is rounding now....
product num1 4€ with TAX         3.333333€ without TAX
product num2 3,85€ with TAX    3.208333€ without TAX

order:
product num1 x 2 = 6,666666€ -> rounded to 6.67€
product num2 x 1 = 3,208333€ -> rounded to 3,21€
Together -> 9,88 * 1,2 = 11,856 -> rounded to **11,86€**

HOW IT SHOULD BE:
order:
product num1 x 2 = 6,666666€ (not rounding)
product num2 x 1 = 3,208333€ (not rounding)
Together -> 9,874999 * 1,2 = 11,8499988 -> rounded to **11,85€**

This how it should be is working perfect in the back end but not in the front.
If I turn of the rounding in the checksum than the backend will do bad stuff.. IDK what is happening then there.

**Comment by madeincosmos** [comment] 2018-08-10 13:17
Another case of the same problem in 1338447-zen

**Comment by osiak** [comment] 2018-08-29 09:39
I face similar problem when connecting to an invoicing system and payment gateway where the tax rounding algorithm creates a 0,01 discrepancy and causing an error when issuing an invoice (since the gross value and the paid value differ by 0,01). Here [http://recordit.co/a2SsvF9Oq0](http://recordit.co/a2SsvF9Oq0) you can find a screencast of the rounding problem when changing status from awaiting payment to confirmed.

**Comment by Chavife** [comment] 2018-08-30 09:03
@osiak 
Perfect example for this exact bug. Thank you.

**Comment by lkol** [comment] 2018-10-16 20:03
I noticed similar issue related to shipping taxes. In this case, the issue can be fixed by increasing the precision on how shipping rates are stored to database.

The file that has to be modified is woocommerce/includes/abstracts/abstract-wc-shipping-method.php

add_rate function has to modified the following way:
```

	public function add_rate( $args = array() ) {
                ...
-		$total_cost = wc_format_decimal( $total_cost, wc_get_price_decimals() );
+               $total_cost = wc_format_decimal( $total_cost, wc_get_rounding_precision() );
```

This increases the precision of stored rate from 2 to 4 decimals (wp_woocommerce_order_itemmeta table). When shipping tax is calculated from this value it is eventually rounded as correctly.

**Comment by kazikamuntu05** [comment] 2018-10-17 10:44
Hi i have same issue.
Anyone solved? i have woocommerce 3.4.6 version
previous versions are affected by the bug?

**Comment by zwiesman31** [comment] 2018-10-31 12:44
Another report in 1532647-zen

**Comment by kloon** [comment] 2018-11-01 08:15
Just noting that #21217 is proposed as a possible fix.

**Comment by AashikP** [comment] 2018-11-14 14:07
@kloon I see this one already has a possible fix. Is there an ETA we can forward the user in 1532647-zen?

**Comment by kloon** [comment] 2018-11-20 10:09
See #21217

**Closed by kloon** 2018-11-20 10:09 UTC
Labels: bug, has pull request
