### ISSUE TITLE
Pagination does not apply to categories on the shop page.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#25586] opened 2020-02-05 22:02 UTC
**Describe the bug**
When the Shop page display option is set to Show Categories pagination does not show. The expectation would be for the Rows per page option to also apply to categories as it does for products.

**To Reproduce**
1. Go to **Appearance > Customize > WooCommerce > Product Catalog
2. Choose _Show categories_ for **Shop page display**
![Screenshot](https://d.pr/i/ntM6Tm+)
Screenshot link: https://d.pr/i/ntM6Tm
3. Scroll down to **Rows per page** and assign an amount expecting pagination to show
4. See no pagination

![Screenshot](https://d.pr/i/KCjWRg+)
Screenshot link: https://d.pr/i/KCjWRg

**Expected behavior**
Since **Products per row** works for categories, the expectation would be for the number of rows per page to apply to categories as well.

![Screenshot](https://d.pr/i/2kZXfM+)
Screenshot link: https://d.pr/i/2kZXfM

See #25585 for enhancement suggestions to displaying both rules.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-02-11 11:23
Hi @johndcoy,

Thank you for taking the time reporting this issue. I can reproduce it on my end:

![cat1](https://user-images.githubusercontent.com/19143190/74232355-865e9a00-4cc0-11ea-90df-88dbce70cbfe.jpg)

However, as per discussion in https://github.com/woocommerce/woocommerce/issues/25585, it currently seems to be working as expected and @garymurray proposed to work on mockups. Because of this, I am going to close this issue in favor of https://github.com/woocommerce/woocommerce/issues/25585 which is rightfully marked as an `enhancement`. 

Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-02-11 11:23 UTC
Labels: bug
