### ISSUE TITLE
Mini cart / Cart page pagination 

### ISSUE THREAD

**Issue by codeminelab** [woocommerce/woocommerce#27149] opened 2020-07-28 12:35 UTC
If in cart I have a lot of products (eg. 200), then the cart page and mini cart is really slow.

This is natural, as not pagination exists for these 2 templates, and I get all 200 results.

Is there anyway I could add a pagination in cart.php and mini-cart.php?

This is the line that gets all products in these 2 files:

`...
foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
...`

**Comment by juliaamosova** [comment] 2020-08-13 15:42
Hi @codeminelab,

Apologies for the delayed response here. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-08-13 15:42 UTC
