### ISSUE TITLE
Problem with expired timed offer setting "sale" price instead of "regular"

### ISSUE THREAD

**Issue by Hexaae** [woocommerce/woocommerce#26384] opened 2020-05-05 17:40 UTC
Am I the only one experiencing issues with timed offers like this?
![image](https://user-images.githubusercontent.com/8591462/81098192-50b8fe00-8f09-11ea-9ac2-c884873fd9c6.png)

Once the timed offer expires the price gets reset to "sale" price instead of "regular" price as expected.

**To Reproduce**
1. set timed offer as the pic above for one product
2. wait for the offer to expire

**Expected behavior**
Expected: price should be reset to "regular" price, not to "sale" price, once expired.

**Isolating the problem (mark completed items with an [x]):**
Reproduced the bug on a test local env, with clean first install of WP 5.4.1+PHP 7.3.5+Woocommerce 4.0.1+Storefront default theme.

`
### WordPress Environment ###

WordPress address (URL): http://sss3.local
Site address (URL): http://sss3.local
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.64.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 3.72MB
Database Data Size: 2.32MB
Database Index Size: 1.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ycd_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 1
ycdcountdown: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Jetpack by WordPress.com: by Automattic – 8.5
WooCommerce Services: by Automattic – 1.23.0
WooCommerce: by Automattic – 4.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 5
Oldest: 2020-05-05 16:52:19 +0000
Newest: 2020-05-05 17:16:45 +0000

`

**Comment by juliaamosova** [comment] 2020-05-06 20:31
Hi @Hexaae,

Thank you for submitting the issue. 

WooCommerce uses a system called `WP-CRON` that runs automated actions inside WordPress to schedule sale prices. Sometimes it doesn’t work as expected and that could cause sale prices to not end. 

There is a plugin called [WP Control](https://wordpress.org/plugins/wp-crontrol/) that can show if WP-CRON is functioning well on the site. I would suggest installing it and see if it shows any errors.

This CRON event that triggers the actual pricing changes to the products with scheduled sales is `woocommerce_scheduled_sales`. You can search for it once you install the plugin and see when it runs. It is possible you'd need to adjust its settings to make sure it runs as you want it to have more control over when the sale price should end:

![cron](https://user-images.githubusercontent.com/19143190/81225217-dcd52f00-8fb6-11ea-9c0d-8de45a13556f.jpg)

Could you please try it out and let us know how it goes for you?

**Comment by Hexaae** [comment] 2020-05-06 23:11
Will check it out but I doubt it's a CRON issue: I've reproduced it on 3 different servers, and on local machines with Local by Flywheel. It's not an isolated case...

**Comment by juliaamosova** [comment] 2020-05-14 18:29
Hi @Hexaae,

Have you managed to take a look at your CRON settings?

**Comment by Hexaae** [comment] 2020-05-15 10:58
Hi Julia,
sorry for delay.
I made some tests forcing _woocommerce_scheduled_sales_ update and indeed this seems to be the cause... This mechanism (decent for daily SALES) rises a problem when you have to stop a SALE at the perfect second though... but I'll try to manage that in some way...
I wonder if that was the only possible technical solution to rely on CRON woocommerce_scheduled_sales... Hope you will improve this aspect in the future.

Thank you for your help and hints!

**Comment by Hexaae** [comment] 2020-05-22 18:00
...Wanted to add that my issues above were also caused by a theme issue using built-in Coming Soon mode that for some reason seems to disable WP-CRON too. That's why I was able to reproduce the issue even on local test sites, but it wasn't a WC related issue...
Had just to adjust `woocommerce_scheduled_sales` timing (1 day at default) to solve products not updating prices after discount offers expired.

**Comment by juliaamosova** [comment] 2020-05-22 22:22
Hi @Hexaae,

Thanks for your additional follow-up. This is good to know and hopefully will be helpful to others as well! Glad to hear the issue is resolved on your end. Looks like you are all set. 

I am going to close this issue but please feel free to comment back in case I missed something and we'd take a 2nd look.

**Closed by juliaamosova** 2020-05-22 22:22 UTC
Labels: status: needs feedback
