### ISSUE TITLE
Woocommerce 4.0 not sending emails

### ISSUE THREAD

**Issue by supremekalm** [woocommerce/woocommerce#25917] opened 2020-03-13 18:34 UTC
New orders, cancellations, etc.. Emails are not going to the customers, and not going to the admins neither.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by juliaamosova** [comment] 2020-03-13 18:45
Hi @supremekalm,

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. 

Here are the examples of admin and customer order emails I just received using 4.0 version:

Order email to customer:

![e1](https://user-images.githubusercontent.com/19143190/76650456-13ec0e80-6539-11ea-9895-7433abc267b7.jpg)

Orde email to admin: 

![e2](https://user-images.githubusercontent.com/19143190/76650466-18182c00-6539-11ea-9eb5-2cc9a14f4481.jpg)

Do you use many plugins on your site? Do you use one of our default themes?  

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Here is also a useful [guide on how to troubleshoot issues related to emails](https://docs.woocommerce.com/document/email-faq/) not being sent.

**Comment by juliaamosova** [comment] 2020-03-20 15:13
Hi @supremekalm,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-03-20 15:13 UTC
Labels: can't reproduce, component: email, status: needs feedback
