### ISSUE TITLE
Mobile version bug for product sells

### ISSUE THREAD

**Issue by raininmay** [woocommerce/woocommerce#29259] opened 2021-03-02 07:19 UTC
Hi,

I'm using your template to sell my products online and on a computer this works so good!
But, on the phone the scrolling to next side is missing. This means all my costumers looking from their phone only get to see a very small selection of my products.

(I wish I could send you a screen shot but I hope you get what I mean....)

Please fix this.... Or please help me fix this, if it's something I need to do to make it right.

Kind regards,
Elliot Maj

[https://blog.raininmay.com](url)

**Comment by raininmay** [comment] 2021-03-02 07:23
![IMG_3075](https://user-images.githubusercontent.com/79898260/109612691-68184600-7b30-11eb-9bad-e5cb751d6380.jpg)

Ah, here's a screen shot. And as you can see at the bottom there's no "next side" as shown in the computere version. 


<img width="1029" alt="Skærmbillede 2021-03-02 kl  08 23 08" src="https://user-images.githubusercontent.com/79898260/109612778-87af6e80-7b30-11eb-9e90-5bc3b985060a.png">

**Comment by tammullen** [comment] 2021-03-02 10:08
Hi @raininmay 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
 
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-02 10:08 UTC

**Comment by raininmay** [comment] 2021-03-02 10:49
No.... This is not a support request. 

Your template is missing pages on the mobile version.

**Comment by raininmay** [comment] 2021-03-02 10:51
I can't see how I can fix that your template is missing pages in the mobile version. ??
