### ISSUE TITLE
Where are the default templates in the shop page?

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#27549] opened 2020-09-01 13:48 UTC
Hi

Why are the default theme templates gone in the shop page?

![afbeelding](https://user-images.githubusercontent.com/6078370/91859277-8d53f680-ec6a-11ea-8572-2ccbb5079895.png)

How to enable these?

This is how it looks in the shop page set

![afbeelding](https://user-images.githubusercontent.com/6078370/91859547-e0c64480-ec6a-11ea-904f-e9458dd95ff2.png)

**Comment by mzdebo** [comment] 2020-09-04 13:44
From my understanding WooCommerce doesn't use the default theme templates. You have to declare WooCommerce support for the theme you are using, and then create custom templates in your theme (or child theme). Here are some articles that might help you out. Good luck. 

https://docs.woocommerce.com/document/woocommerce-pages/
https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes
https://docs.woocommerce.com/document/template-structure/
https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/
https://developer.wordpress.org/themes/advanced-topics/child-themes/

**Comment by rodrigoprimo** [comment] 2020-10-22 20:54
Hi @BackuPs,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodrigoprimo** 2020-10-22 20:54 UTC
