### ISSUE TITLE
Draft variable products are showing on reports pages

### ISSUE THREAD

**Issue by Marin-Matosevic** [woocommerce/woocommerce#25716] opened 2020-02-20 09:34 UTC
**Describe the bug**
If the variable product is out of stock and product is in draft status, it still shows up on the report's pages.

**To Reproduce**
1. Go to the products page
2. Find a product with variations
3. Set stock quantity to 0 (on one or more variations)
4. Change product status to draft
5. Go to reports page
6. Click on Stock tab
7. Click on Out of stock sub-tab

**Expected behavior**
There should be only published products and their variations.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress version - 5.3.2
WooCommerce version - 3.9.2
Server - Apache 
PHP -  7.3.7
MySql version - 5.7.26

```
</details>

**Comment by tammullen** [comment] 2020-02-22 18:50
Hi @Marin-Matosevic 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

I set an already published product variation stock to zero.
I checked it appeared in the out of stock report as expected.
I set the product status to draft
It still appeared in the out of stock report.

![Screenshot_2020-02-22_at_18_40_55](https://user-images.githubusercontent.com/24649833/75097521-86ee0f00-55a3-11ea-8d1f-37249a0f66c7.png)


I also tried an already published simple product and set stock to zero.
I checked it appeared in the out of stock report as expected.
I set the product status to draft
It no longer appeared in the out of stock report.

​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by om4csaba** [comment] 2020-10-30 02:21
If you created a variable product and saved as a draft, then create product variations, those variations will be in published status, not draft. I assume this is the cause of why showing in the reports.

**Comment by om4csaba** [comment] 2021-05-26 09:17
Hi, can I ask to elevate the priority of this issue? We have multiple customers of the [WooCommerce Zapier plugin](https://woocommerce.com/products/woocommerce-zapier/
) who suffer from this.

Because the product variations saved as published even the main variable product is in draft state, the `woocommerce_new_product_variation` action called and data sent unexpectedly via webhooks where the `product.created` topic used.

Thanks

**Comment by barryhughes** [comment] 2024-03-07 03:48
The classic or legacy reports have now been deprecated for 4 years, so we'll go ahead and close this issue.

<img width="1123" alt="legacy-reports-notice" src="https://github.com/woocommerce/woocommerce/assets/3594411/0b98e19e-c6bb-41ab-b290-96b0fd5b558f">

Please do give the new Analytics experience a shot and ,if you encounter problems, please feel free to create bug reports or enhancement requests as needed. Thanks!

**Closed by barryhughes** 2024-03-07 03:48 UTC
Labels: type: bug, priority: normal, plugin: woocommerce, team: Proton, focus: legacy reports
