### ISSUE TITLE
Bulk variations and different prices for each variations

### ISSUE THREAD

**Issue by gijdoul** [woocommerce/woocommerce#28047] opened 2020-10-21 18:38 UTC
Hello,
I'm new with Woocommerce and try to upload about 1000 products with all same variations/prices different for each variation but can't figure how to do it with csv in one line.
ex my variation size,"S,M,L" price,"10,20,30" I try a feature for add in bulk the variations it work but prices are missing so need to edit one by one it's not possible thanks for your replys

**Comment by Konamiman** [comment] 2020-10-22 07:51
Hi there,

Please check [our guide on importing product variations](https://docs.woocommerce.com/document/product-csv-import-suite-importing-product-variations/), which includes some example CSV files that may be helpful for you.

That said, please note that GitHub should be treated as a place to report confirmed bugs only, and not for support request. If you need further help please try the following:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)


If you think that you have indeed found a bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by Konamiman** 2020-10-22 07:51 UTC
