### ISSUE TITLE
order by price not work correctly

### ISSUE THREAD

**Issue by Alks** [woocommerce/woocommerce#24006] opened 2019-06-26 07:51 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Alks** [comment] 2019-06-26 07:59
Hi, in our store filter order by price not work correctly, not show correctly ordered products. We use WP 5.2.2 and woocommerce 3.6.4

**Comment by rodrigoprimo** [comment] 2019-06-27 14:12
Please don't just ignore the bug report template. We ask all that information because we need it to be able to determine if the problem is a WooCommerce bug or something else, and also we need it to be able to reproduce it on our local environments.

Closing this issue as there is not enough information in it. Please open another issue answering all the relevant questions on the bug report template and we will take a look. Keep in my that this is not a support forum and should be used exclusively to report WooCommerce core bugs.

**Closed by rodrigoprimo** 2019-06-27 14:12 UTC
