### ISSUE TITLE
Exporting All languages products list as CSV, don't function well

### ISSUE THREAD

**Issue by YMM-ITXI** [woocommerce/woocommerce#29722] opened 2021-04-20 11:57 UTC
There are 66 items available in English, in addition to 20 in Arabic, a total of 86
when trying to export all languages products list, as the attached picture
![image](https://user-images.githubusercontent.com/31727355/115391614-583fe880-a1e8-11eb-9e7b-a805ffabf428.png)

generated file is the English products only 
![image](https://user-images.githubusercontent.com/31727355/115391572-49f1cc80-a1e8-11eb-8e91-76744ceedbff.png)

the Arabic product list shows as
![image](https://user-images.githubusercontent.com/31727355/115391787-87eef080-a1e8-11eb-91e8-1ce6b0bed26c.png)

Kindly review this issue and help us integrate and better utilize of exporting/importing feature

**Comment by juliaamosova** [comment] 2021-04-21 21:21
Hi @YMM-ITXI,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by YMM-ITXI** [comment] 2021-04-22 13:51
Hi @juliaamosova 
I appreciate your prompt response,

I noticed that the conflict is occurring due to duplicate products.
currently I'm not uploading products with SKUs
and when we are using the translation plugin, the generated items are duplicate

therefore exporting products' list is limited to selecting a language first

Do you recommend any solution for maintain products in different languages?

**Comment by tammullen** [comment] 2021-09-08 12:08
Hi @YMM-ITXI 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-09-08 12:08 UTC
Labels: has feedback
