### ISSUE TITLE
Default product sorting - cant change list options

### ISSUE THREAD

**Issue by larzep** [woocommerce/woocommerce#26227] opened 2020-04-21 10:37 UTC
Where will I find the product sorting option? I need to change what the options are however I have looked online and the option to do this doesnt seem available on mine?

<img width="1135" alt="Screenshot 2020-04-21 at 11 36 39" src="https://user-images.githubusercontent.com/23695810/79856536-62a48800-83c4-11ea-9ab7-4cdc510fdacb.png">

**Comment by juliaamosova** [comment] 2020-04-21 13:30
Hi @larzep,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request. Please note that we do not provide technical support here. If you need help in the future, please do one of the following:

- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

As a one time exemption, I am happy to share a link to the documentation for you related to [Sorting products](https://docs.woocommerce.com/document/managing-products/#section-23).

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-04-21 13:30 UTC
