### ISSUE TITLE
Product data options not visible in admin

### ISSUE THREAD

**Issue by CrawlVirus** [woocommerce/woocommerce#30250] opened 2021-07-10 18:09 UTC
![image](https://user-images.githubusercontent.com/65632756/125172557-018aef00-e1d8-11eb-806a-cd263175553a.png)

In Add product Product data option is  not visible.

**Comment by luanlavie** [comment] 2021-07-13 07:50
I have this issue too, I have tried another WordPress version 5.6.4 instead of 5.7.2 but the issue is still there

**Comment by rodelgc** [comment] 2021-07-14 07:05
Hi @CrawlVirus,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. 

The "Product data" section is showing fine on my end using the latest WooCommerce version `5.5.0`:
<img width="624" alt="Screen Shot 2021-07-14 at 2 59 55 PM" src="https://user-images.githubusercontent.com/4509348/125577912-567b354e-6e61-4dae-af1f-a300e7946ad4.png">

There might be a key step or plugin that you need to tell us about so that we could recreate this issue from our end.

Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by CrawlVirus** [comment] 2021-07-16 11:36
Hi @rodelgc,

I am using WordPress version: 5.7.2

Still issue not solved. Please find the details below:

<html>
<body>


WooCommerce pages
--
Shop base: |   | #41 - /shop/
Cart: |   | #42 - /cart/
Checkout: |   | #43 - /checkout/
My account: |   | Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: |   | Page not set


</body>
</html>

**Comment by AashikP** [comment] 2021-07-23 08:43
Hello @CrawlVirus 

This is not something I could replicate on my own test site as well:

![https://d.pr/i/qzdu0Z+](https://d.pr/i/qzdu0Z+)

![https://d.pr/i/78MCRR+](https://d.pr/i/78MCRR+)

It does not look like all the details made through. Can you please get back to us with all the details in the format below:

```
**Describe the bug**  
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**  
Steps to reproduce the behavior:

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Screenshots**  
If applicable, add screenshots to help explain your problem.

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an \[x\]):**

*    I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
*    This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
*    I can reproduce this bug consistently using the steps above.

**WordPress Environment**

You can find it via WooCommerce > Status. Select “Get system report” and then “Copy for support”.  Once you’ve done that, paste it here in your response.
```

**Comment by luanlavie** [comment] 2021-07-25 11:43
Hey @CrawlVirus and @AashikP I've just found out why Product data options are not visible in the admin panel, this issue is caused by a Chrome extension (still I haven't known which one yet), the feature works as intended when you open the edit/add product page in an igconito window. Thank you for your support @rodelgc & @AashikP, I think @CrawlVirus should check this out to make sure everything is still working fine!

**Comment by rodelgc** [comment] 2021-07-28 09:31
Hi @CrawlVirus,

> I am using WordPress version: 5.7.2

I still could not reproduce the issue using WordPress 5.7.2. And unfortunately, we need more details than just the WordPress version. Details such as the Steps to Reproduce and the System Status Report which are included in the template I gave [earlier](https://github.com/woocommerce/woocommerce/issues/30250#issuecomment-879648027).

Also, it appears that this issue is beginning to look like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
﻿
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
﻿
If you confirm the bug, please provide us with clear steps to reproduce it.
﻿
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodelgc** 2021-07-28 09:31 UTC
Labels: has feedback
