### ISSUE TITLE
How to get all shipping costs without session in woocommerce?

### ISSUE THREAD

**Issue by aminmalekzadeh** [woocommerce/woocommerce#26290] opened 2020-04-25 11:38 UTC
Hello guys,
give function cost get_total_shipping() but saved in session, i want without session calculated.
beacuse use for REST_API for application android.
How to get all shipping rates and costs without session in woocommerce?

**Comment by juliaamosova** [comment] 2020-04-28 17:59
Hi @aminmalekzadeh,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-04-28 17:59 UTC
