### ISSUE TITLE
Able to add multiple "Sold individually" products to cart

### ISSUE THREAD

**Issue by quangthien27** [woocommerce/woocommerce#22900] opened 2019-02-28 04:21 UTC
**Describe the bug**
User is able to add to cart with multiple products which are marked "Sold individually"

**To Reproduce**
0. Set up a single product with "Sold individually"
1. Add that product to cart
2. Go to cart and remove that product which is just added, "Undo" link will appear (named screen 1)
3. Open another tab/window (Don't close screen 1) and add that same product again
4. Go back to screen 1 and Click on "Undo" link, 2 products will appear in cart

**Expected behavior**
A clear message should be shown which says "You cannot add another <product name> to cart."

**Isolating the problem (mark completed items with an [x]):**
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment] 2019-03-01 10:49
Tested this on master:

1. Added to cart
2. Went to cart tab 1
3. Opened product page in new tab 2
4. Removed from cart in tab 1
5. Added to cart tab 2
6. Undo in tab 1

I ended up with only the one line item with quantity 1 in my cart. Anything else unique about these products?

**Comment by mikejolley** [comment] 2019-03-04 13:35
If you can provide more details please reopen/reply here. I'm marking this closed as I cannot reproduce the issue.

Thanks

**Closed by mikejolley** 2019-03-04 13:35 UTC
Labels: status: needs feedback
