### ISSUE TITLE
[GlobalStep - 4.1 RC]: Use case 2 failed on MAC as packaging cost calculation is different from the one shown on instruction screenshot.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26283] opened 2020-04-24 16:54 UTC
Steps to Reproduce:
1. Tested on JN multisite and JN site.
2. Complete initial screens.
3. Follow steps of Use case 2 according to "https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions#41".
4. Observe that Use case 2 failed on MAC as packaging cost calculation is different from the one shown on instruction screenshot.

Note: Provided same inputs as mentioned in the use case 2 document.

Actual Result:
Use case 2 failed on MAC as packaging cost calculation is different from the one shown on instruction screenshot.

Expected Result:
Packaging cost calculation should be correct. 

<img width="960" alt="#11" src="https://user-images.githubusercontent.com/41110392/80237417-534e6480-867a-11ea-995e-95ed3953cbac.png">

**Comment by vedanshujain** [comment] 2020-04-27 18:14
I tried reproducing this on my local setup, it seems to be working fine. I am guessing that some setting was missing during the test, closing this issue now, but will keep a close eye on similar bug report to make sure we have not missed anything.

**Closed by vedanshujain** 2020-04-27 18:14 UTC
