### ISSUE TITLE
wp wc product_cat list needs a way to turn off paging

### ISSUE THREAD

**Issue by apb1963** [woocommerce/woocommerce#19549] opened 2018-03-27 18:09 UTC
wp wc product_cat list needs a way to turn off paging (this should be the default) so that ALL categories are listed.

**Comment by mikejolley** [comment] 2018-03-27 18:37
Why are you logging multiple requests about the same thing? Edit your other issue?

**Comment by mikejolley** [comment] 2018-03-27 18:40
Also, you could send a PR for this if you need new functionality :)

**Comment by claudiulodro** [comment] 2018-03-27 19:10
Duplicate of #19547. See my response there.

**Closed by claudiulodro** 2018-03-27 19:10 UTC
