### ISSUE TITLE
WooCommerce Shop/Category Page Layout breaks after update

### ISSUE THREAD

**Issue by Skinessence** [woocommerce/woocommerce#23374] opened 2019-04-18 15:14 UTC
Upgrading WooCommerce version 3.5.8 to 3.6.0/1 breaks layout of main shop/product archive pages.

![wc361](https://user-images.githubusercontent.com/49759038/56371225-0335fa00-61fd-11e9-8d33-6942408b7047.png)
![wc358](https://user-images.githubusercontent.com/49759038/56371260-18ab2400-61fd-11e9-8a01-f28490f820ed.png)

Manually downgrading restores layout (upgrading breaks again).

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://dev.skinessence.be
Site address (URL): https://dev.skinessence.be
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.16
PHP Post Max Size: 1 GB
PHP Time Limit: 900
PHP Max Input Vars: 2000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.22-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.8
WC Database Prefix: wp_
Totale databasegrootte: 264.09MB
Database datagrootte: 161.26MB
Database index grootte: 102.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB
wp_woocommerce_order_itemmeta: Data: 36.56MB + Index: 21.06MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB
wp_ak_404_log: Data: 0.08MB + Index: 0.00MB
wp_bpspro_login_security: Data: 0.02MB + Index: 0.02MB
wp_bpspro_seclog_ignore: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.41MB + Index: 0.47MB
wp_comments: Data: 12.52MB + Index: 10.09MB
wp_cwa: Data: 0.02MB + Index: 0.02MB
wp_duplicator_packages: Data: 0.01MB + Index: 0.00MB
wp_ewwwio_images: Data: 9.52MB + Index: 10.55MB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB
wp_idealcheckout: Data: 0.02MB + Index: 0.00MB
wp_iqblock_logging: Data: 0.17MB + Index: 0.06MB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_logs: Data: 0.02MB + Index: 0.09MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_kiyoh: Data: 0.02MB + Index: 0.02MB
wp_layerslider: Data: 0.09MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_lockdowns: Data: 0.02MB + Index: 0.00MB
wp_login_fails: Data: 0.02MB + Index: 0.00MB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 13.28MB + Index: 0.48MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 0.09MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.31MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.02MB + Index: 0.03MB
wp_pmxi_templates: Data: 0.09MB + Index: 0.00MB
wp_postmeta: Data: 46.58MB + Index: 40.14MB
wp_posts: Data: 20.45MB + Index: 3.67MB
wp_revslider_css: Data: 0.02MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.09MB + Index: 0.00MB
wp_revslider_slides: Data: 0.11MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_rsgiftvoucher: Data: 0.02MB + Index: 0.00MB
wp_rspointexpiry: Data: 0.02MB + Index: 0.00MB
wp_rsrecordpoints: Data: 0.02MB + Index: 0.00MB
wp_rs_expiredpoints_email: Data: 0.02MB + Index: 0.00MB
wp_rs_templates_email: Data: 0.02MB + Index: 0.00MB
wp_social_users: Data: 0.02MB + Index: 0.02MB
wp_sumo_reward_encashing_submitted_data: Data: 0.02MB + Index: 0.00MB
wp_sumo_reward_send_point_submitted_data: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.16MB + Index: 0.16MB
wp_terms: Data: 1.52MB + Index: 0.75MB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB
wp_term_taxonomy: Data: 1.52MB + Index: 0.59MB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 4.52MB + Index: 6.03MB
wp_users: Data: 0.19MB + Index: 0.17MB
wp_wcpdf_invoice_number: Data: 0.11MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_product_meta_lookup: Data: 0.11MB + Index: 0.20MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.17MB + Index: 0.23MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_wpam_actions: Data: 0.02MB + Index: 0.00MB
wp_wpam_affiliates: Data: 0.02MB + Index: 0.00MB
wp_wpam_affiliates_fields: Data: 0.02MB + Index: 0.00MB
wp_wpam_creatives: Data: 0.02MB + Index: 0.00MB
wp_wpam_events: Data: 0.02MB + Index: 0.00MB
wp_wpam_impressions: Data: 0.02MB + Index: 0.00MB
wp_wpam_messages: Data: 0.02MB + Index: 0.00MB
wp_wpam_paypal_logs: Data: 0.02MB + Index: 0.00MB
wp_wpam_tracking_tokens: Data: 0.47MB + Index: 0.00MB
wp_wpam_tracking_tokens_purchase_logs: Data: 0.02MB + Index: 0.00MB
wp_wpam_transactions: Data: 0.05MB + Index: 0.00MB
wp_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB
wp_wsal_metadata: Data: 4.52MB + Index: 3.52MB
wp_wsal_occurrences: Data: 0.30MB + Index: 0.33MB
wp_wsal_options: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.31MB + Index: 0.16MB
wp_yoast_seo_meta: Data: 0.11MB + Index: 0.06MB

### Post Type Counts ###

amn_mi-lite: 3
attachment: 3483
chch-pop-up: 1
condition_group: 8
create-portfolio: 1
custom_css: 3
export_template: 1
flamingo_contact: 30
fp_feed: 1
gfw_report: 3
mc4wp-form: 2
ml-slider: 3
nav_menu_item: 69
page: 85
portfolio-item: 13
post: 25
product: 689
product_variation: 164
revision: 1323
scheduled_export: 2
scheduled-action: 30
shop_coupon: 23
shop_order: 5733
shop_order_refund: 30
sidebar: 11
tablepress_table: 4
vc_grid_item: 10
wafs: 1
wpcf7_contact_form: 3
wpmm_theme: 2
yith_wcps_type: 1
yith-wcbm-badge: 1
yith-wccos-ostatus: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (58) ###

WP Affiliate Manager: door wp.insider
wpaffiliatemgr – 2.6.5

Autoptimize: door Frank Goossens (futtta) – 2.4.4
iThemes Security: door iThemes – 7.3.3
Klassieke editor: door WordPress-bijdragers – 1.4
Contact Form 7: door Takayuki Miyoshi – 5.1.1
WordPress Editorial Calendar: door Colin Vernon
Justin Evans
Joachim Kudish
Mary Vogt
and Zack Grossbart – 3.7.2

Envato Market: door Envato – 2.0.1
Google Analytics for WordPress by MonsterInsights: door MonsterInsights – 7.5.1
Handy Feature Pack: door Themes Zone – 1.0.5
iQ Block Country: door Pascal – 1.2.4
WPBakery Page Builder: door Michael M - WPBakery.com – 5.7
Kirki Toolkit: door Ari Stathopoulos (@aristath) – 3.0.39
Kiyoh Customerreview: door kiyoh – 1.0.16 – Niet getest met de actieve versie van WooCommerce
Loco Translate: door Tim Whitlock – 2.2.2
Mailchimp for WordPress: door ibericode – 4.5.1
Max Mega Menu: door megamenu.com – 2.6
Mollie Payments for WooCommerce: door Mollie – 5.1.6 – Niet getest met de actieve versie van WooCommerce
Ninja Pages: door The WP Ninjas – 1.4.2
Products Purchase Price for Woocommerce: door Softedge – 1.0.4 – Niet getest met de actieve versie van WooCommerce
Really Simple SSL: door Rogier Lankhorst
Mark Wolters – 3.1.5

reSmush.it Image Optimizer: door reSmush.it – 0.1.22
Slider Revolution: door ThemePunch – 5.4.8
SUMO Reward Points: door Fantastic Plugins – 22.5 – Niet getest met de actieve versie van WooCommerce
Sidebar Manager Light: door OTWthemes – 1.15
TablePress: door Tobias Bäthge – 1.9.2
TinyMCE Advanced: door Andrew Ozz – 5.1.0
UpdraftPlus - Backup/Restore: door UpdraftPlus.Com
DavidAnderson – 2.16.12.0

Widget Shortcode: door Hassan Derakhshandeh – 0.3.4
Woocommerce Advanced Bulk Edit: door George Iron – 4.2.5 – Niet getest met de actieve versie van WooCommerce
WooCommerce Extended Coupon Features FREE: door Soft79 – 3.0.5 – Niet getest met de actieve versie van WooCommerce
WooCommerce Custom Product Tabs Lite: door SkyVerge – 1.6.3 – Niet getest met de actieve versie van WooCommerce
WooCommerce EU BTW Assistent: door Aelia – 1.9.8.190327 – Niet getest met de actieve versie van WooCommerce
WooCommerce Nieuw Product Label: door jameskoster – 0.3.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.2.11 – Niet getest met de actieve versie van WooCommerce
WooCommerce PDF Invoices & Packing Slips Professional: door Ewout Fernhout – 1.4.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce PDF Invoices & Packing Slips Premium Templates: door Ewout Fernhout – 2.2.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Product Bundles: door SomewhereWarm – 5.10.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Google Product Feed: door Ademti Software Ltd. – 7.8.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce - Product Importer: door Visser Labs – 1.3.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Sequential Order Numbers: door SkyVerge – 1.8.3 – Niet getest met de actieve versie van WooCommerce
WooCommerce - Store Exporter Deluxe: door Visser Labs – 3.3 – Niet getest met de actieve versie van WooCommerce
WooCommerce Table Rate Shipping: door Bolder Elements – 4.0.3 – Niet getest met de actieve versie van WooCommerce
WooCommerce: door Automattic – 3.6.1
Yoast SEO Premium: door Team Yoast – 6.3.1
WP All Import Pro: door Soflyy – 4.5.5
WP-Cron Control: door Thorsten Ott
Erick Hitter
Automattic – 0.7.1

WP Crontrol: door John Blackbourn & crontributors – 1.7.1
WP Custom Widget area: door Kishor Khambu – 1.2.5
Zedna WP Image Lazy Load: door Radek Mezulanik – 1.6.2.2
WP-Optimize: door David Anderson
Ruhani Rabin
Team Updraft – 2.3.2

WP Security Audit Log: door WP White Security – 3.4.0.1
WP Simple Mail Sender: door Enrique Chavez – 1.0.2
WP Super Cache: door Automattic – 1.6.4
Yoast SEO: WooCommerce: door Team Yoast – 6.3 – Niet getest met de actieve versie van WooCommerce
YITH WooCommerce Ajax Product Filter: door YITH – 3.6.2 – Niet getest met de actieve versie van WooCommerce
YITH WooCommerce Badge Management: door YITH – 1.3.15 – Niet getest met de actieve versie van WooCommerce
YITH WooCommerce Compare: door YITH – 2.3.9 – Niet getest met de actieve versie van WooCommerce
YITH WooCommerce Wishlist: door YITH – 2.2.9 – Niet getest met de actieve versie van WooCommerce

### Inactive Plugins (1) ###

WP All Import - WooCommerce Add-On Pro: door Soflyy – 3.0.6 – Niet getest met de actieve versie van WooCommerce

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #35784 - /shop/
Winkelmand: #5 - /winkelwagen/
Afrekenen: #6 - /afrekenen/
Mijn account: #6631 - /mijn-account/
Algemene voorwaarden: #41881 - /algemene-voorwaarden/

### Theme ###

Name: HandyStore
Version: 5.0.14 (see readme.txt for detailed changelog)
Author URL: http://themes.zone
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: handystore/woocommerce/cart/cart.php versie 3.4.0 is verouderd. De hoofdversie is 3.5.0
handystore/woocommerce/content-product.php versie 3.4.0 is verouderd. De hoofdversie is 3.6.0
handystore/woocommerce/content-widget-product.php versie 3.3.0 is verouderd. De hoofdversie is 3.5.5
handystore/woocommerce/loop/loop-start.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Bundle indicator (is_bundle): 
Condition: Defaults to "new".
Brand: Defaults to "Marius Fabre". Pre-populates from pa_merk taxonomy.
Product Type: Defaults to "Health & Beauty". Pre-populates from product_cat taxonomy.
Google Product Category: Defaults to "Health & Beauty > Personal Care >".
Global Trade Item Number (GTIN): 
Adwords labels: Defaults to "Marius Fabre". Pre-populates from pa_merk taxonomy.
Custom label 0: Defaults to "Marius Fabre". Pre-populates from pa_merk taxonomy.
Custom label 1: Defaults to "Zeep". Pre-populates from pa_groep taxonomy.

### WooCommerce Google Product Feed options ###

Include variations in feed: No
Send item_group_id: No

### Product Bundles ###

Database Version: 5.10.0
Template Overrides: –

### Action Scheduler ###

Complete: 29
Oldest: 2019-04-18 06:33:41 +0200
Newest: 2019-04-18 16:27:09 +0200

Pending: 1
Oldest: 2019-04-25 06:33:41 +0200
Newest: 2019-04-25 06:33:41 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

### Templates ###

Extended logging mode for Store Exporter Deluxe: ✔Inactive Turn on Logging mode
Debugging mode for Store Exporter Deluxe: ✔Inactive Turn on Debugging mode
Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available; ssh2_connect()
ssh2_auth_password()
ssh2_sftp(). Contact your hosting provider.

</details>

**Comment by mikejolley** [comment] 2019-04-18 15:21
@Skinessence can you share a zip of that theme? It's missing classnames but I don't know the cause of the conflict yet without an affected theme.

**Comment by spigotdesign** [comment] 2019-04-18 15:26
I'm having a similar issue with a few of my sites. It's happening due to the removal of a class name - 'product' from each individual product in the list. 

I checked the changelog but didn't see anything specific about this.

**Comment by MauroSLOUPE** [comment] 2019-04-18 15:44
I have the same problem with Bridge theme and Byanca theme. After updating Woocommerce the shop layouts brakes. Also in the single shop page the related items have the same issue.

Downgrading Woocommerce fix the issue.


![FireShot Capture 073 - Shop - Kimmiu - kimmiu com](https://user-images.githubusercontent.com/49759865/56373025-02e73000-61f8-11e9-89da-76bac3faf6b3.png)

**Comment by Skinessence** [comment] 2019-04-18 15:58
> 
> 
> @Skinessence can you share a zip of that theme? It's missing classnames but I don't know the cause of the conflict yet without an affected theme.
Here it is. Thx
[handystore.zip](https://github.com/woocommerce/woocommerce/files/3095202/handystore.zip)

**Comment by Skinessence** [comment] 2019-04-18 16:00
Mistakenly closed. Sorry I'm an newbie

**Comment by jessepearson** [comment] 2019-04-18 16:06
I've seen this a few times today with Porto and Aurum themes.

**Comment by MauroSLOUPE** [comment] 2019-04-18 16:12
> I have the same problem with Bridge theme and Byanca theme. After updating Woocommerce the shop layouts brakes. Also in the single shop page the related items have the same issue.
> 
> Downgrading Woocommerce fix the issue.

Bridge just released an update and is working fine now. Byanca Theme still have the same problem.

**Comment by mikejolley** [comment] 2019-04-18 16:29
Figured it out, patch is here https://github.com/woocommerce/woocommerce/pull/23377 cc @jessepearson @timmyc

**Comment by justintadlock** [comment] 2019-04-18 16:42
This was brought to my attention from a user.  But, one of the main issues I see here is that `wc_get_product_class` is directly calling a core filter hook (`post_class`).  These leaves open the potential for the WC classes to get wiped out or altered.

There are various solutions to address this.  A simple one would be to use a custom filter hook, such as `wc_product_class`.

Another would be to move all of the class-adding logic into a filter on `post_class` and have `wc_get_product_class()` simply return `get_post_class()`.

Yet another solution would be to keep the class-adding login within the function and pass it directly into `get_post_class( $class )` and then return that result.

**Comment by saas786** [comment] 2019-04-18 16:57
> Figured it out, patch is here #23377 cc @jessepearson @timmyc

This doesn't fix the issue. I have patched it onto v3.6.1 but doesn't fix the said issue.

**Comment by mikejolley** [comment] 2019-04-18 17:08
@saas786 it fixes the missing classnames on product divs/list elements. Tested on handystore theme. I don't know what issue you're referring to.

**Comment by mikejolley** [comment] 2019-04-18 17:10
@justintadlock 

Looking at the docblock:

> This method was modified from WordPress's get_post_class() to allow the removal of taxonomies
 * (for performance reasons).

So looks like thats being avoided on purpose. `post_class` is likely there for back compat. Since it was filterable in the same way before 3.6.x, it's probably not the reason this is broken on themes now. The breakage is due to the way it used to use `get_post` (which takes the $post object global into consideration) where the new code did not.

**Comment by saas786** [comment] 2019-04-18 17:11
@mikejolley 

I am referring to 
https://github.com/woocommerce/woocommerce/issues/23374

instead of applying the **post_class** filter at the end of function, why not call

```
	$classes = array_merge( $classes, get_post_class( '', $product->get_id() ) );
```
just before this line / code

https://github.com/woocommerce/woocommerce/blob/fbaaa319dd61b2d845bb593da544a18f34e93757/includes/wc-template-functions.php#L585

??

**Comment by saas786** [comment] 2019-04-18 17:21
I have just tested it on both

3.5.7 & 3.6.1

On 3.5.7 

I see

```
entry entry--4394 entry--type-product entry--status-publish entry--author-george has-post-thumbnail has-excerpt product first instock downloadable virtual purchasable product-type-simple
```

Where with or without your patch I see

```
entry entry--4394 entry--type-product entry--status-publish entry--author-george has-post-thumbnail has-excerpt
```

Where if you add get_post_class like I mentioned earlier,

it gives me this

```
entry entry--4394 entry--type-product entry--status-publish entry--author-george has-post-thumbnail has-excerpt product first instock downloadable virtual purchasable product-type-simple type-product post-4394 status-publish product_cat-shoes ....
```

**Comment by mikejolley** [comment] 2019-04-18 17:28
@saas786 and calling `get_post_class` introduces the bottleneck this function wants to avoid. `get_post_class` does a bunch of loops generating classes for taxonomies and terms which needs to be avoided.

**Comment by saas786** [comment] 2019-04-18 17:33
@mikejolley 

Then I suggest you avoid using "post_class" all together. As its causing issue.

By disabling it, it works fine.

**Comment by justintadlock** [comment] 2019-04-18 17:38
I can absolutely guarantee that directly calling the `post_class` filter hook is going to break with some themes (at least how it's done now).  That's kind of why I'm here. :)

If you really wanted to keep it, an alternative would be to call the `post_class` filter hook **_before_** your plugin adds its custom classes.  Then, just tack on its own classes to that.

**Comment by mikejolley** [comment] 2019-04-18 18:37
@saas786 @justintadlock Thanks for the feedback. Updated the PR to remove `post_class` and introduce a custom filter if needed.

**Comment by saas786** [comment] 2019-04-18 19:25
@mikejolley 

Thanks, better now.

But one strange thing I noticed that loop classes are being applied as well.

Like i noticed "first" class.

And I see on line

https://github.com/woocommerce/woocommerce/blob/7737fc5928636b0fc3f018b319be4896d1d486ec/includes/wc-template-functions.php#L593

```
wc_get_loop_class()
```
is called, which I think only should be called inside loop,

so shouldn't there be any if condition checking if its inside loop?
like $woocommerce_loop? 
or
if ( $GLOBALS['wp_query']->get( 'wc_query' ) ) ?
or
if ( $GLOBALS['wp_query']->is_main_query() ) ?

**Comment by mikejolley** [comment] 2019-04-18 19:38
@saas786 I don't think so. wc_get_loop_class will return nothing if it's not within a loop. I don't want to change this further to introduce other bugs anyway if we can help it - this is how it worked in 3.5.x before issues arose.

**Comment by GrayMediaLtd** [comment] 2019-04-19 05:05
I had this issue (woocommerce classes missing off LIs on my archive page)with my custom built theme that was built off Sage by Roots.io and can confirm that the patch works for me.

**Comment by saas786** [comment] 2019-04-19 11:32
@mikejolley 

I think I confused you.

Current patch works fine. 

Only issue I saw is, even though on single product page, it should only add "single" product classes, but I see its calling **wc_get_loop_class()** function on single products page. Even though its clearly for used on products archive page.

Make sense?

**Comment by kosiew** [comment] 2019-04-20 07:21
@mikejolley,

Customer on #1974358-zen says that the images on the Category pages are too large after the update.
Is it related to this issue?

**Comment by saas786** [comment] 2019-04-20 07:26
@kosiew 
Yes its related to this.

**Comment by jesseihatsu** [comment] 2019-04-23 11:07
I have multiple sites that have issues with this. Most have only issues with missing class names, but one of them is not responding at all due to timeout.

This issue is on archive and single pages that call `post_class()` or `wc_product_class()` function with or without arguments. Removing the function call fixes the issue but of course this means that JS and CSS does not function properly.

The websites that had only missing classes were fixed by adding post id as an argument: `wc_product_class('row', get_the_ID())`

Reverting from 3.6.x to 3.5.8 fixed the issue for timeout.

It is also worth of mentioning that the website facing the timeout issue is using WPML for translations and the issues with `post_class()` affected only some of the language versions of the site but not all.

**Comment by mikejolley** [comment] 2019-04-23 14:35
@saas786 Seems the same thing happens on 3.5 so Im happy to ignore that for this fix.

**Comment by mikejolley** [comment] 2019-04-24 10:23
For the benefit of anyone following along, we ended up needing to keep the `post_class` filter around to avoid breaking some things (tested OceanWP). We've done so in a way that appends rather than filters everything which appears to be working across the themes affected by this issue.

All of that is in https://github.com/woocommerce/woocommerce/pull/23377 - see that issue if there are any additonal comments.

Thanks

**Closed by mikejolley** 2019-04-24 10:23 UTC
Labels: bug, has pull request
