### ISSUE TITLE
[HELP] Woocommerce Orders Missing

### ISSUE THREAD

**Issue by zackgo** [woocommerce/woocommerce#30039] opened 2021-06-04 02:35 UTC
To who may concern

Here's Zack
I am facing an issue that my Woocommerce backend are missing some orders records time to time from 25th May
We have check through our payment system which recorded the full list of orders yet Woocommerce backend has missout some of the orders records which can't be tracked or resolved back

Wonder if there's anyone that can help to solve the issue?

Thank you

**Comment by tammullen** [comment] 2021-06-04 16:28
Hi @zackgo ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-06-04 16:28 UTC
