### ISSUE TITLE
Showing "not in stock" even when product is in stock (simple product)

### ISSUE THREAD

**Issue by MirekHovorka** [woocommerce/woocommerce#21084] opened 2018-08-17 09:15 UTC
**Description:**
In my e-shop, some of my products are showing that they are "out of stock" even when they clearly in stock (see picture below). These items are all simple products.

**Solution:**
I have found solution - in "Inventory" on product page you have to uncheck "Enable stock management on product level", then recheck it again and update product. Item is back "In stock". However this is very annyoing if you have to do this by hand in hundreds of items...

**Screenshot before unchecking (out of stock):**
![obrazek](https://user-images.githubusercontent.com/8246509/44257491-76b9de80-a20c-11e8-9f76-c9b2ff890a65.png)
"Není skladem" means "Out of Stock" (see that number 1 there? It **IS** in stock!).

**Screenshot after rechecking (in stock):**
![obrazek](https://user-images.githubusercontent.com/8246509/44257742-445cb100-a20d-11e8-8125-c4f8ee0c7087.png)
After rechecking, we are back in business...

**Expected behavior**
Simply show "In Stock" when it is appropriate.

It seems to me like a bug. Is there any way to fix this, please? And is there any way to bulk edit all of the items at once and not have to do uncheking/rechecking by hand in the meantime?

Thank you very much.

By the way - WooCommerce rocks! Thank you guys for your great work!

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://nej-technika.cz
Site URL: https://nej-technika.cz/_cms
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.5 - Doporučujeme používat verzi PHP 7.2 nebo vyšší pro nejlepší výkonnost a zabezpečení. Jak aktualizovat verzi PHP
PHP Post Max Size: 32 MB
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.34

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.32-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_ge4agafE_
MaxMind GeoIP Database: ✔
Celková velikost databáze: 15.41MB
Velikost dat databáze: 13.02MB
Velikost indexu databáze: 2.39MB
wp_ge4agafE_woocommerce_sessions: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_woocommerce_api_keys: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_woocommerce_attribute_taxonomies: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_woocommerce_downloadable_product_permissions: Data: 0.02MB + index: 0.05MB
wp_ge4agafE_woocommerce_order_items: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_woocommerce_order_itemmeta: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_woocommerce_tax_rates: Data: 0.02MB + index: 0.06MB
wp_ge4agafE_woocommerce_tax_rate_locations: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_woocommerce_shipping_zones: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_woocommerce_shipping_zone_locations: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_woocommerce_shipping_zone_methods: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_woocommerce_payment_tokens: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_woocommerce_payment_tokenmeta: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_woocommerce_log: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_commentmeta: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_comments: Data: 0.02MB + index: 0.09MB
wp_ge4agafE_duplicator_packages: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_links: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_options: Data: 2.23MB + index: 0.14MB
wp_ge4agafE_postmeta: Data: 2.52MB + index: 0.86MB
wp_ge4agafE_posts: Data: 1.52MB + index: 0.13MB
wp_ge4agafE_smush_dir_images: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_termmeta: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_terms: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_term_relationships: Data: 0.06MB + index: 0.02MB
wp_ge4agafE_term_taxonomy: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_usermeta: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_users: Data: 0.02MB + index: 0.05MB
wp_ge4agafE_wc_download_log: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_wc_webhooks: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_wfBadLeechers: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfBlockedCommentLog: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfBlockedIPLog: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfBlocks7: Data: 0.02MB + index: 0.05MB
wp_ge4agafE_wfConfig: Data: 1.38MB + index: 0.00MB
wp_ge4agafE_wfCrawlers: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfFileChanges: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfFileMods: Data: 2.52MB + index: 0.00MB
wp_ge4agafE_wfHits: Data: 0.13MB + index: 0.05MB
wp_ge4agafE_wfHoover: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_wfIssues: Data: 0.02MB + index: 0.06MB
wp_ge4agafE_wfKnownFileList: Data: 1.52MB + index: 0.00MB
wp_ge4agafE_wfLeechers: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfLiveTrafficHuman: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_wfLocs: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfLogins: Data: 0.02MB + index: 0.03MB
wp_ge4agafE_wfNet404s: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_wfNotifications: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfPendingIssues: Data: 0.02MB + index: 0.06MB
wp_ge4agafE_wfReverseCache: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfScanners: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_wfSNIPCache: Data: 0.02MB + index: 0.05MB
wp_ge4agafE_wfStatus: Data: 0.14MB + index: 0.09MB
wp_ge4agafE_wfVulnScanners: Data: 0.02MB + index: 0.00MB
wp_ge4agafE_yoast_seo_links: Data: 0.02MB + index: 0.02MB
wp_ge4agafE_yoast_seo_meta: Data: 0.08MB + index: 0.00MB

### Post Type Counts ###

attachment: 266
customize_changeset: 10
jetpack_migration: 2
ml-slide: 3
ml-slider: 1
nav_menu_item: 8
page: 9
post: 1
product: 266
revision: 71
soliloquy: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

ManageWP - Worker: o ManageWP – 4.6.2
Query Monitor: o John Blackbourn & contributors – 3.1.0
Adminimize: o Frank Bültge – 1.11.4
Akismet Anti-Spam: o Automattic – 4.0.8
Contact Form 7: o Takayuki Miyoshi – 5.0.3
Debug Bar: o wordpressdotorg – 0.9
Duplicator: o Snap Creek – 1.2.40
Homepage Control: o WooThemes – 2.0.3
Jetpack by WordPress.com: o Automattic – 6.4.2
Loco Translate: o Tim Whitlock – 2.1.5
Regenerate Thumbnails: o Alex Mills (Viper007Bond) – 3.0.2
Storefront Homepage Slider: o Bohumír Hovorka – 1.7
UpdraftPlus - Backup/Restore: o UpdraftPlus.Com
DavidAnderson – 1.14.12

Woocommerce XML Feeds: o Vladislav Musilek – 3.3.9 – Nebylo testováno s aktivní verzí WooCommerce
Booster for WooCommerce: o Algoritmika Ltd – 3.8.0
WooCommerce: o Automattic – 3.4.4
Wordfence Security: o Wordfence – 7.1.10
Yoast SEO: o Tým Yoast  – 8.0
WP-Optimize: o David Anderson
Ruhani Rabin
Team Updraft – 2.2.4

Smush: o WPMU DEV – 2.8.0.1
WP Super Cache: o Automattic – 1.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Obchod: #6 - /obchod/
Košík: #7 - /kosik/
Pokladna: #8 - /pokladna/
Můj účet: #9 - /muj-ucet/
Obchodní podmínky: #77 - /obchodni-podminky/

### Theme ###

Name: Nej-technika.cz
Version: 1.0
Author URL: http://www.mirekhovorka.cz/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.3.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by peterfabian** [comment] 2018-08-17 09:50
Hi Mirek, 

Thanks. You should be able to bulk edit products using the following steps:
1. Go to Products
2. Select products you want to update
3. Select 'Edit' and 
4. Click Apply
5. Change Manage stock? dropdown to Yes/No.
6. Hit Update.
![bulk_edit](https://user-images.githubusercontent.com/2207451/44260072-a91b0a00-a213-11e8-963b-e30998430614.png)

**Comment by kloon** [comment] 2018-08-20 11:06
Did this start happening after upgrading perhaps? It is possible that an upgrade routine did not run that should have. or it could be some sort of plugin/theme conflict. I am not able to reproduce this locally. I assume you also tested this by disabling all plugins except WooCommerce and switched to a default theme like Twentyseventeen or Storefront to test?

Closing as not reproducible, the instructions Peter showed will help you update all the products in bulk.

**Closed by kloon** 2018-08-20 11:06 UTC
