### ISSUE TITLE
PhotoSwipe lightbox "close" triggers elements covered by it on mobiles

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce#25458] opened 2020-01-22 06:47 UTC
**Describe the bug**
On mobile devices, after clicking the magnifier on the main single-product image, clicking the "X" to close the lightbox bubbles to the object being covered by the "X".

If that object is a link, that link is followed.

This issue may only apply to Mobile Chrome, but also happens in the Chrome code inspector when emulating a mobile device.

This is known to the PhotoSwipe developers, and there may already be a fix, so please update that library, if needed.

**To Reproduce**
1. Go to https://pacificsprings.com.au/product/prestige-spring-water-cooler/ on a mobile device or in the emulator
2. Click on the magnifier to open the main image lightbox
3. Click the "X"
4. There will either be no response, or you will get the effects of clicking the phone number link, positioned under the "X", after the lightbox closes

**Expected behavior**
The lightbox should close, and nothing else should happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.
- [x] Others have confirmed this issue separately

**WordPress Environment**
NOTE: The details below are from a site that hasn't been updated to WC3.9.0, but I've tested on sites that have been updated, and the problem is still there.
<details>
```
### WordPress Environment ###

WordPress address (URL): https://pacificsprings.com.au
Site address (URL): https://pacificsprings.com.au
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.13
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.30-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: pswp_
MaxMind GeoIP Database: ✔
Total Database Size: 102.24MB
Database Data Size: 80.96MB
Database Index Size: 21.28MB
pswp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
pswp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pswp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pswp_woocommerce_order_items: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
pswp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
pswp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pswp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pswp_woocommerce_shipping_zone_locations: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
pswp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pswp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pswp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pswp_ac_areas: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
pswp_apto_sort_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pswp_commentmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
pswp_comments: Data: 0.25MB + Index: 0.12MB + Engine MyISAM
pswp_ewwwio_images: Data: 0.65MB + Index: 0.37MB + Engine MyISAM
pswp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pswp_feedmanager_channel: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_feedmanager_country: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_feedmanager_feed_status: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pswp_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pswp_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pswp_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_feedmanager_source: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pswp_itsec_distributed_storage: Data: 26.84MB + Index: 0.00MB + Engine MyISAM
pswp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_itsec_lockouts: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
pswp_itsec_logs: Data: 15.20MB + Index: 0.86MB + Engine MyISAM
pswp_itsec_opaque_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pswp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pswp_iwp_backup_status: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
pswp_iwp_file_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pswp_iwp_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pswp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pswp_options: Data: 1.11MB + Index: 0.09MB + Engine MyISAM
pswp_postmeta: Data: 5.50MB + Index: 2.32MB + Engine MyISAM
pswp_posts: Data: 1.99MB + Index: 0.49MB + Engine MyISAM
pswp_redirection_404: Data: 26.55MB + Index: 15.09MB + Engine InnoDB
pswp_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pswp_redirection_items: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
pswp_redirection_logs: Data: 0.27MB + Index: 0.08MB + Engine MyISAM
pswp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
pswp_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
pswp_term_relationships: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
pswp_term_sorting: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pswp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
pswp_usermeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
pswp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
pswp_vslider: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pswp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pswp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
pswp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
pswp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pswp_yoast_seo_links: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
pswp_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

InfiniteWP - Client: by Revmakx – 1.9.4.5
AddToAny Share Buttons: by AddToAny – 1.7.39
Advanced Admin Search: by Kuroit – 1.1
AJAX Search for WooCommerce: by Damian Góra – 1.6.0
Akismet Anti-Spam: by Automattic – 4.1.3
iThemes Security: by iThemes – 7.6.1
Classic Editor: by WordPress Contributors – 1.5
Honeypot for Contact Form 7: by Nocean – 1.14.1
Contact Form 7: by Takayuki Miyoshi – 5.1.6
EWWW Image Optimizer: by Exactly WWW – 5.1.4
Flamingo: by Takayuki Miyoshi – 2.1.1
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 7.3.5
Custom Extensions and Styles: by Get Business Online Consulting – 2.17
MonsterInsights Pro: by MonsterInsights – 7.10.3
Image Regenerate & Select Crop: by Iulia Cazan – 5.3.2
jQuery Responsive Select Menu: by MIGHTYminnow – 1.5.0
Media File Renamer (Auto Rename): by Jordy Meow – 4.6.5
Redirection: by John Godley – 4.6.2
SMTP Mailer: by naa986 – 1.0.8
Special Recent Posts FREE Edition: by Luca Grandicelli – 2.0.4
Video Thumbnails: by Sutherland Boswell – 2.12.3
Woocommerce Minimum and Maximum Quantity: by Ashok G – 2.0.9 – Not tested with the active version of WooCommerce
WooCommerce Minicart: by Ahmad Shyk – 1.0.4 – Not tested with the active version of WooCommerce
WooCommerce Force Sells: by WooCommerce – 1.1.21
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.23
WooCommerce: by Automattic – 3.8.1 – 3.9.0 is available
Yoast SEO: by Team Yoast – 12.9.1
WP Accessibility: by Joe Dolson – 1.7.0
WP Fastest Cache Premium: by Emre Vona – 1.5.6
WP Fastest Cache: by Emre Vona – 0.9.0.1
WP Product Feed Manager: by Michel Jongbloed – 1.19.0
WP Sitemap Page: by Tony Archambeau – 1.6.2
Yoast SEO: WooCommerce: by Team Yoast – 12.4.1

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

InfiniteWP - Client Loader: by Revmakx –

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #51 - /products/
Cart: #4841 - /cart/
Checkout: #4842 - /checkout/
My account: #4843 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Pacific Springs
Version: 2.0.0
Author URL: https://www.get-business-online.com/about-2/
Child Theme: ✔
Parent Theme Name: Twenty Eleven
Parent Theme Version: 3.3
Parent Theme Author URL: https://en-au.wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2019-12-26 17:15:21 +1000
Newest: 2020-01-16 17:30:27 +1000

Pending: 1
Oldest: 2020-01-23 17:30:27 +1000
Newest: 2020-01-23 17:30:27 +1000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by juliaamosova** [comment] 2020-01-27 13:02
Hi @galbaras,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. Not always but I can sometimes. 

Here is a screencast of the issue on your site: https://cloudup.com/cW4SoIjwlJ0. 

And here is the issue showcasing the bug on my test site - towards the end of the video when I am closing the lightbox, I am also clicking on the Menu which is right there on the screen on the place of X of the lightbox. Sometimes I can reproduce it right from the first try: https://cloudup.com/ciMTwTdj4Fw. 

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by galbaras** [comment] 2020-01-28 00:11
Hi @juliaamosova,

Thank you for taking the time to investigate.

To me, when someone wants to look closely at a product, they are showing buying intent. This is the worst possible time to navigate to another page, open the phone dialer, or take any action other than getting them back to completing their purchase.

How is that low priority?

Also, if Photoswipe itself is fixed already, shouldn't this be an easy win?

**Comment by tammullen** [comment] 2020-03-18 16:41
Just noting when looking at https://github.com/woocommerce/woocommerce/issues/25922 I was also able to reproduce this using Chrome 80 on Android 10. I wasn't able to reproduce it using a reduced or mobile simulated viewport on Desktop Chrome 80 on MacOS.

![SVID_20200316_233437_1 2020-03-16 23_43_08](https://user-images.githubusercontent.com/24649833/76984756-2dc19300-6937-11ea-92b6-f2b2eb3aabd3.gif)

**Comment by galbaras** [comment] 2020-03-18 23:42
I'm using Android 6, but this is still happening on latest Chrome emulation / Window 10, although it's not happening in the Edge mobile emulation.

**Comment by muhammedyagci** [comment] 2020-03-26 18:40
I have same bug. I am waiting for solving

**Comment by lemoatom** [comment] 2020-03-27 01:34
I have same bug. I am waiting for solving

**Comment by KoolPal** [comment] 2020-07-25 15:38
Landed here due to complaints from my customers 🤦‍♂️

**Comment by tammullen** [comment] 2020-09-11 08:02
Related issue in PhotoSwipe repository https://github.com/dimsemenov/PhotoSwipe/issues/1608

**Comment by galbaras** [comment] 2020-10-26 04:51
Perhaps [this fix](https://github.com/andi34/PhotoSwipe/commit/55d031631096cc79cd05ceb37d543512659c733c) can be applied to the version shipped with WooCommerce until it's officially release?

**Comment by kszczygiel96** [comment] 2021-01-29 14:39
In case anyone is still looking for solution here is a hotfix that doesn't require changing the plugin files:
`document.querySelector('.pswp__button--close').addEventListener('pswpTap', function (e)
{
    e.preventDefault();
    e.stopPropagation();
}, true);
`

**Comment by galbaras** [comment] 2021-01-30 02:00
Thanks, @kszczygiel96 . I can confirm this works for me too. In fact, @tammullen , I can confirm that it works on a real mobile phone, not just in the Chrome emulation.

So now we have 2 possible solutions. WooCommerce team, can we get this fixed, please?

BTW, this issue was reported in the PhotoSwipe repository almost a year ago, and likely affects millions of uses worldwide, so I'm not sure I agree with the low priority, particularly considering the ease of providing a solution. Just add the above line of JavaScript and release.

**Closed** 2022-01-10 14:58 UTC
Labels: type: bug, priority: high

**Comment by c062785** [comment] 2022-02-09 12:04
> 

Is there anyway to implement this code non-destructively to Woocommerce? This issue is still NOT resolved... I have code snippets plug in... Thank you!

**Comment by galbaras** [comment] 2022-02-10 00:50
Please start a new issue with a detailed description of what you're experiencing, because it may be specific and/or different.
