### ISSUE TITLE
Stock reservation when order change from on-hold to pending status

### ISSUE THREAD

**Issue by Daniel-MultiSafepay** [woocommerce/woocommerce#29633] opened 2021-04-09 08:26 UTC
**Prerequisites (mark completed items with an [x]):**

- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When an order is created, this action is being fired, which reserve the stock for the minutes defined in the WooCommerce settings: 

https://github.com/woocommerce/woocommerce/blob/trunk/includes/wc-stock-functions.php#L339-L357

As you know, this action prevents another consumer placing an order with the same product, for the minutes defined in the settings to hold the stock while the payment is being processed by the gateway.

Now, let's assume the payment method of the order is bank transfer. The order status immediately will pass from pending payment to on-hold according with this:

https://github.com/woocommerce/woocommerce/blob/trunk/includes/gateways/bacs/class-wc-gateway-bacs.php#L364

The same order status will be assigned to an order, using other gateways which require initially changing the order status to on-hold. This will release the stock reservation and will decrease the stock units of the products purchased.  

https://github.com/woocommerce/woocommerce/blob/trunk/includes/wc-stock-functions.php#L365-L388

Then if for some reason, related with the payment method flow callback, or triggered by an admin action the order status is changed again from on-hold to pending payment. the stock will be increased properly, but there is no stock reservation and no call to wc_reserve_stock_for_order().

At that moment, other consumer could place an order with products, which should be already reserved since the order is on pending payment. We think this is an unexpected behavior. 

**Expected behavior**

If the order status changes from on-hold to pending payment, the stock should be increased, and also reserved again.

**Actual behavior**

When an order change from status to on-hold to pending payment, the stock is not reserved. Other consumer can place an order with the products.

**To Reproduce**

1. Add a product to the cart which have just 1 unit in stock.
2. Create an order, and use bank transfer payment method.
3. After the order is processed, change the order status from on-hold to pending payment.
4. Open another session in Incognito mode, find the same product of the previous order, add it to the cart and process the order. 

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by eopws** [comment] 2021-04-09 10:47
Hello, I've tried to reproduce this bug and got the same error as you. And I've noticed one more thing, if we have placed two orders of same product that has stock quantity = 1 and change both orders statuses first to pending payment and then to complete stock reduces twice, that means after all this operations stock will be -1

**Comment by vedanshujain** [comment] 2021-04-12 14:29
thanks for the report, you are right, looks like we missed this flow when we implemented the reserve stock flow. I am marking this as a bug so we look at this soon-ish.

**Comment by Daniel-MultiSafepay** [comment] 2021-04-14 07:27
Hello @vedanshujain and @eopws.

Thank you both for check and confirm this bug.  I am pretty sure it will be something easy to fix. 
Hopefully we will see progress about this on the next release. 

Thanks.

**Comment by roykho** [comment] 2021-05-04 16:12
Hi @Daniel-MultiSafepay

> If the order status changes from on-hold to pending payment, the stock should be increased, and also reserved again.

So I am just reading your expected behavior here however I think it may be contradicting? Because if you change the status back to `pending` and you're expecting stock to increase again (which it now does) but at the same time want the stock to be reserved, another customer would see the product and would show in stock for them even though if they went through with purchasing, it would then say there isn't enough stock. But that would cause confusion and bad user experience I believe because the shop says one thing but behaves in another.

Perhaps payment gateways should not use `pending` as a holding pattern but just use `on-hold` like how we do with BACS, so this issue becomes moot? What do you think?

**Comment by Daniel-MultiSafepay** [comment] 2021-05-04 17:43
Hello @roykho 

Thanks for checking this report. 


> Because if you change the status back to `pending` and you're expecting stock to increase again (which it now does) but at the same time want the stock to be reserved, another customer would see the product and would show in stock for them even though if they went through with purchasing, it would then say there isn't enough stock.

I don't think so. **This is the expected behavior of the pending status** and is exactly what happens if a customer 1 creates an order and then a customer 2 tries to buy the same product while the customer 1 is paying. Customer 2 should be able to add the product to the cart, and then will see a warning in the cart page.  At the end the order should change again to cancelled after reaching the time-minutes defined in the WooCommerce settings; like any order on pending payment. 

===

Please, consider the following case:

1. A customer initiates an order with a product which stock is 1; in a store who sells unique products, like art. 
2. The customer creates the order using a payment method like bank transfer. The order status at this point is changed to on-hold and the stock is reduced according to the units purchased.
3. The customer receives an email with the data to pay by transfer, and is also offered other options, such as paying with any other payment methods which will process the payment immediately.
4. The customer realizes that he can pay for the order quickly in a safe way and selects a fast method.
5. The PSP detects that the customer has changed the payment method for that order, therefore it sends a notification that the order has now been initialized.
5. At this point the order is returned to the "pending" status. The stock is restored, but it is not reserved again (even when it is evident that there is an order that is alive, in pending status and awaiting notification that the payment has been processed correctly).
6. During the minutes in which the customer is making the payment; another user enters in the store; select the products that are assigned to the previous order and it is possible to finalize the purchase.
7. At the end you have two orders with the same product.

===

Once again, thanks for considering this report.

**Comment by roykho** [comment] 2021-05-04 18:13
> At this point the order is returned to the "pending" status.

This is what I mean about maybe it shouldn't change to `pending` status and keep it as `on-hold` because that is really what it is? `pending` is the state when an order is created by no payment methods have been selected.

And what I describe in my previous comment is that customers will then see in stock product when they can't order it as it is already reserved. What I am saying is if there is only 1 quantity and it is reserved, it shouldn't show 1 quantity available otherwise it is confusing for customers. Because of this, hence I mentioned maybe we should leave it as is and instead have payment gateways not go back into pending.

**Comment by Daniel-MultiSafepay** [comment] 2021-05-04 18:56
The describe case is one of our cases. As you can see; I work for [MultiSafepay](https://www.multisafepay.com). But this is not a feature request. I truly believe this is a bug within WooCommerce.

Is not just the PSP notification the one can turn an on-hold order to pending.  An administrator can do it also from backend and you will find the same situation in which a customer can place an order with a product which should be reserved. Then, if you turn an on-hold order to pending and the stock is restore, why not reserve the stock also; like I said, after all the order is on pending status.

===

Once again, thanks for considering this report.

**Comment by roykho** [comment] 2021-05-11 17:29
Hi @Daniel-MultiSafepay - Just checking to see if you have tried the following. If not, try putting the following code in your theme's functions.php file and see if it works for you.

```
add_action( 'woocommerce_order_status_on-hold_to_pending', 'wc_reserve_stock_for_order' );
add_action( 'woocommerce_order_status_processing_to_pending', 'wc_reserve_stock_for_order' );
add_action( 'woocommerce_order_status_failed_to_pending', 'wc_reserve_stock_for_order' );
add_action( 'woocommerce_order_status_cancelled_to_pending', 'wc_reserve_stock_for_order' );
add_action( 'woocommerce_order_status_completed_to_pending', 'wc_reserve_stock_for_order' );
```

**Comment by barryhughes** [comment] 2021-05-17 18:50
@Daniel-MultiSafepay—thanks for your patience and for all the notes. 

After some discussion, we decided we will not change how this part of the system works. Introducing a change would be relatively high risk (in terms of creating problems for various custom and third party solutions out there) but, beyond that, scenarios where the order status changes from _on hold_ to _pending payment_ are pretty atypical and run counter to the expected flow. 

![Order Status Flow](https://docs.woocommerce.com/wp-content/uploads/2013/05/woocommerce-order-process-diagram.png)

We do understand there may be cases where a payment gateway has reasons to implement a different order status flow, but in those cases they will also need to implement any supporting logic that might be required.

**Closed by barryhughes** 2021-05-17 18:50 UTC
Labels: component: stock, needs developer feedback, priority: high, type: bug
