### ISSUE TITLE
couldn't set object value as meta value for an order through rest api

### ISSUE THREAD

**Issue by jianghaonz** [woocommerce/woocommerce#27320] opened 2020-08-13 10:25 UTC
after upgrade to 4.3.2,  when I use rest API to set meta_data,  I couldn't set an object value as a meta value

400 Bad Request: [{"code":"rest_invalid_param","message":"Invalid parameter: meta_data","data":{"status":400,"params":{"meta_data":"meta_data[0][value] is not of type string,null"}}}]

**Comment by peterfabian** [comment] 2020-08-13 10:48
Thanks for opening the issue and sorry for the problems. This is a duplicate of https://github.com/woocommerce/woocommerce/issues/27282, so closing this one. We're working on a solution in https://github.com/woocommerce/woocommerce/pull/27318 and will release a fix soon.

**Closed by peterfabian** 2020-08-13 10:48 UTC
