### ISSUE TITLE
fallo en la verificacion de dominio de appel pay

### ISSUE THREAD

**Issue by purarosania** [woocommerce/woocommerce#27122] opened 2020-07-24 20:03 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Fallo en la verificacion de dominio de appel pay
**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>
`
### WordPress Environment ###

WordPress address (URL): https://ruzaanilunnai.com
Site address (URL): https://ruzaanilunnai.com
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.20
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1g-fips

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: hin_
Tamaño total de la base de datos: 13.82MB
Tamaño de los datos de la base de datos: 11.46MB
Tamaño del índice de la base de datos: 2.36MB
hin_woocommerce_sessions: Datos: 0.11MB + Índice: 0.02MB + Motor InnoDB
hin_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
hin_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
hin_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
hin_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
hin_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_actionscheduler_actions: Datos: 0.05MB + Índice: 0.11MB + Motor InnoDB
hin_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_cartflows_ca_cart_abandonment: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_cartflows_ca_email_history: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_cartflows_ca_email_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
hin_cartflows_ca_email_templates_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_comments: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
hin_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_options: Datos: 4.02MB + Índice: 0.08MB + Motor InnoDB
hin_postmeta: Datos: 4.19MB + Índice: 0.38MB + Motor InnoDB
hin_posts: Datos: 0.52MB + Índice: 0.20MB + Motor InnoDB
hin_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_term_relationships: Datos: 0.11MB + Índice: 0.06MB + Motor InnoDB
hin_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
hin_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
hin_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
hin_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
hin_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
hin_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
hin_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
hin_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
hin_yoast_indexable: Datos: 1.52MB + Índice: 0.22MB + Motor InnoDB
hin_yoast_indexable_hierarchy: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
hin_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
hin_yoast_seo_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
hin_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 664
custom_css: 2
customize_changeset: 17
elementor_library: 1
elementor-hf: 1
nav_menu_item: 25
page: 11
post: 5
product: 157
revision: 274
shop_coupon: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Starter Templates: por Brainstorm Force – 2.3.2
Elementor: por Elementor.com – 2.9.14
Elementor - Header, Footer & Blocks: por Brainstorm Force
Nikhil Chavan – 1.5.1

SG Optimizer: por SiteGround – 5.6.0
WooCommerce Cart Abandonment Recovery: por CartFlows Inc – 1.2.7 – Versión instalada no está probada con la versión activa de WooCommerce 4.3.1
WooCommerce Stripe Gateway: por WooCommerce – 4.5.0 – Versión instalada no está probada con la versión activa de WooCommerce 4.3.1
WooCommerce: por Automattic – 4.3.1
Yoast SEO: por Equipo Yoast – 14.6.1
WPForms Lite: por WPForms – 1.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #38 - /tienda/
Carrito: #39 - /carrito/
Finalizar compra: #40 - /pagina-de-pago/
Mi cuenta: #41 - /mi-cuenta/
Términos y condiciones: #2494 - /terminos-y-condiciones/

### Theme ###

Name: Astra
Version: 2.4.5
Author URL: https://wpastra.com/about/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Cancelada: 1
Oldest: 2020-07-10 00:49:51 +0000
Newest: 2020-07-10 00:49:51 +0000

Completo: 57
Oldest: 2020-07-10 00:53:52 +0000
Newest: 2020-07-24 04:24:52 +0000

Pendiente: 1
Oldest: 2020-07-25 04:24:52 +0000
Newest: 2020-07-25 04:24:52 +0000

`

**Comment by purarosania** [comment] 2020-07-24 20:10
En los plugins activos de Woocommerce Cart Abandonment recovery  por cartflows y woocommerce stripe gateway  aparecen como versiones instaladas no están probadas con la version activa de woocommerce 4.3.1.
Para mi es un tema complicado porque no tengo conocimientos ni experiencia en desarrollar páginas. agradezco su apoyo

**Comment by tammullen** [comment] 2020-07-24 21:10
Hi @purarosania 

Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

> **Apple pay domain verification failure**
> In the active Woocommerce Cart Abandonment recovery plugins by cartflows and woocommerce stripe gateway they appear as installed versions not tested with the active version of woocommerce 4.3.1.
> For me it is a complicated subject because I have no knowledge or experience in developing pages. Thank you for your support



While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case; 
- There is documentation on Apple Pay here https://docs.woocommerce.com/document/accepting-apple-pay-woocommerce/
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
Label:

**Closed by tammullen** 2020-07-24 21:10 UTC
