### ISSUE TITLE
No sale price comparison done to signal sale status

### ISSUE THREAD

**Issue by arpoodle** [woocommerce/woocommerce#23320] opened 2019-04-16 16:33 UTC
Item is shown as "On Sale" even when price is the same as 'regular price'

Enter the item's normal retail price into both Regular Price and Sale Price.

Items show as being on sale but with no price variance.

WooCommerce should validate that sale price < regular price either on product input/update or product display.

**Comment by rodrigoprimo** [comment] 2019-04-16 19:45
Thanks for your report, @arpoodle. I was not able to reproduce this problem on a clean WC install. When changing the sale price, there is a JS check to force it to be lower than the regular price:

![Screenshot from 2019-04-16 16-34-50](https://user-images.githubusercontent.com/77215/56238813-c683ca80-6065-11e9-962d-0418c82d0ef1.png)

Even if somehow the sale price is set to be the same as the regular price, on a clean WC install, the product shouldn't appear as on sale. The code to determine if a product is on sale checks to see if the regular price is greater than the sale price and not if it is greater or equal to the sale price:

https://github.com/woocommerce/woocommerce/blob/c56d3ede9f40f9d71c5fdeaf5e14f0ff4cb565cb/includes/abstracts/abstract-wc-product.php#L1500

I am closing this issue for now as it doesn't seem to be a problem on WC core. If I missed something, leave a comment, and I will take a second look. Please include in your comment the steps to reproduce the problem on a clean WC install and provide all the information requested in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=).

**Closed by rodrigoprimo** 2019-04-16 19:45 UTC
