### ISSUE TITLE
Product variations are going to draft even after new update.

### ISSUE THREAD

**Issue by rudee24** [woocommerce/woocommerce#27308] opened 2020-08-12 17:06 UTC
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

- When importing products in woo-commerce built-in products importer. I'm importing products as draft and there are variable products with variations as well in the CSV. When I tried importing these products (file contain 1 variable and it's 3 variations).
- After the import has been finished, it says 4 products imported ( that is correct)
- After opening all product, the recently imported product is shown as **out of stock**. 
- When I tried to edit the product, in the variation tabs, no variations are there. 
- Then in the DB I found that the product_variations are also marked as **draft**.

So, I the product variations cannot be marked as draft as there is no way to edit them from admin. I found the code regarding this in the current update but it is not working as expected.

Steps to reproduce the bug:
1. Create a CSV file with variable and it's variations 
2. Set the value to **-1** for published field
3. Import the CSV 
4. Look for product variations in the recently imported product. 

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

WooCommerce version: |   | 4.3.2

**Comment by juliaamosova** [comment] 2020-08-12 20:07
Hi @rudee24,

Thank you for submitting the issue. However, I am not sure I can reproduce it. Also, the steps to reproduce are not very clear. So far, everything seems to be working as expected on my end. 

Steps I am taking:

- I have a variable product on the site which is published and has 2 variations - in stock. 
- I exported my products and changed the status of my variable product from published to draft by editing the value of the parent product in the `Published` column (from `1` to `-1`):

![var](https://user-images.githubusercontent.com/19143190/90062002-fc19e180-dcb4-11ea-9f3e-4b7c551a8a0c.jpg)

- I imported the updated CSV file back to the site and selected `Update existing products` checkbox:

![existing](https://user-images.githubusercontent.com/19143190/90062234-5a46c480-dcb5-11ea-93b8-2eb7044cbe66.jpg)

- After the import was completed, I navigated to All Products view and saw that the product that I edited is now in `Draft` status and also `In stock` as expected:

![draft](https://user-images.githubusercontent.com/19143190/90062377-98dc7f00-dcb5-11ea-87b3-1578e9b30460.jpg)

- Upon opening the product itself, I confirmed that it has attributes and variations intact:

![vars](https://user-images.githubusercontent.com/19143190/90062505-c6c1c380-dcb5-11ea-88b4-944b7a07b9a1.jpg)

If the steps you are taking are different from mine, can you please provide exact steps and more details so that we could reproduce the same and take a look further.

**Comment by Updula** [comment] 2020-08-12 23:22
I can confirm my variations were missed up after updating.

**Comment by rudee24** [comment] 2020-08-13 04:41
You're keeping variations as published(1). Check these screenshots below 
![Screenshot-csv](https://user-images.githubusercontent.com/19970323/90094989-07b8e700-dd4d-11ea-8338-bcd66d2418ef.png)
It is showing 4 products imported ( that is correct)
![Screenshot_20200813_100443](https://user-images.githubusercontent.com/19970323/90095006-11424f00-dd4d-11ea-8017-a85025d40997.png)
But the product is marked as out of stock -
![Screenshot_20200813_100500](https://user-images.githubusercontent.com/19970323/90095045-2e771d80-dd4d-11ea-9bcf-efafee462618.png)
Because there are no variations in it. They all are in drafts, that should not happen, as there is no way to edit or view them now - 
![Screenshot_20200813_100524](https://user-images.githubusercontent.com/19970323/90095083-4babec00-dd4d-11ea-8c84-4918d48a83b6.png)

**Comment by juliaamosova** [comment] 2020-08-13 14:37
Thanks for your follow-up @rudee24. 

The variation doesn't have the status of `Draft`, only the parent product can be in `Draft` therefore, you should only edit the parent product row in the CSV file from `1` to `-1` to make it in `Draft`. The variations should stay as-is. You can see in my comment above that while the product becomes draft, the variations are still there, visible, in stock, and available for editing.

The code reference can be found here:

https://github.com/woocommerce/woocommerce/blob/master/includes/import/abstract-wc-product-importer.php#L254:258

I am closing this thread as there is no bug. However, please feel free to comment back in case I missed something and we'd take another look.

**Closed by juliaamosova** 2020-08-13 14:37 UTC
Labels: status: needs feedback

**Comment by rudee24** [comment] 2020-08-13 14:41
Actually,
I was working on a site and client is uploading products in a bulk and they
are adding that published column in that last.
What they are doing there is rather than visiting each row individually,
they're just setting this column value to -1.
So in that case we can add a restriction in code to overwrite that value as
1 in vase of variations only.

**Comment by rudee24** [comment] 2022-04-13 06:20
I noticed in the code that the patch I suggested has been used but I can't see any credit given.
