### ISSUE TITLE
Customer is not able to pay failed order due to instock error message.

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce#22023] opened 2018-11-23 12:22 UTC
**Describe the bug**
When customer tries pay failed order he gets following error:

> Sorry, we do not have enough "Test product" in stock to fulfill your order (0 available). We apologize for any inconvenience caused.

Here "Test product" has 'Manage stock' option disabled and 'Stock status' = In stock.

**To Reproduce**
1. Add product to card and proceed to checkout.
2. Enter wrong card credentials to force order failure.
3. Than go to pay-order page for failed order.

**Expected behavior**
Customer must be able to pay failed order.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: http://www.cleanwp.com
Site URL: http://www.cleanwp.com
WC Version: 3.5.1
Log Directory Writable: ❌ To allow logging
make /home/stas/www/sites/cleanwp/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.34 (Ubuntu)
PHP Version: 7.1.20-1+ubuntu14.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.33-0ubuntu0.14.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 6.66MB
Database Data Size: 4.99MB
Database Index Size: 1.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
cwpbwg_album: Data: 0.02MB + Index: 0.00MB
cwpbwg_album_gallery: Data: 0.02MB + Index: 0.00MB
cwpbwg_gallery: Data: 0.02MB + Index: 0.00MB
cwpbwg_image: Data: 0.02MB + Index: 0.00MB
cwpbwg_image_comment: Data: 0.02MB + Index: 0.00MB
cwpbwg_image_rate: Data: 0.02MB + Index: 0.00MB
cwpbwg_image_tag: Data: 0.02MB + Index: 0.00MB
cwpbwg_option: Data: 0.02MB + Index: 0.00MB
cwpbwg_shortcode: Data: 0.02MB + Index: 0.00MB
cwpbwg_theme: Data: 0.02MB + Index: 0.00MB
cwpcommentmeta: Data: 0.02MB + Index: 0.03MB
cwpcomments: Data: 0.02MB + Index: 0.08MB
cwpformmaker: Data: 0.09MB + Index: 0.00MB
cwpformmaker_backup: Data: 0.02MB + Index: 0.00MB
cwpformmaker_blocked: Data: 0.02MB + Index: 0.00MB
cwpformmaker_query: Data: 0.02MB + Index: 0.00MB
cwpformmaker_sessions: Data: 0.02MB + Index: 0.00MB
cwpformmaker_submits: Data: 0.02MB + Index: 0.00MB
cwpformmaker_themes: Data: 1.52MB + Index: 0.00MB
cwpformmaker_views: Data: 0.02MB + Index: 0.00MB
cwphuge_itgallery_gallerys: Data: 0.00MB + Index: 0.00MB
cwphuge_itgallery_images: Data: 0.01MB + Index: 0.00MB
cwphuge_itslider_images: Data: 0.00MB + Index: 0.00MB
cwphuge_itslider_params: Data: 0.00MB + Index: 0.00MB
cwphuge_itslider_sliders: Data: 0.00MB + Index: 0.00MB
cwplinks: Data: 0.02MB + Index: 0.02MB
cwpnf_objectmeta: Data: 0.02MB + Index: 0.00MB
cwpnf_objects: Data: 0.02MB + Index: 0.00MB
cwpnf_relationships: Data: 0.02MB + Index: 0.00MB
cwpninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB
cwpninja_forms_fields: Data: 0.02MB + Index: 0.00MB
cwpoptions: Data: 1.06MB + Index: 0.02MB
cwppostmeta: Data: 0.11MB + Index: 0.03MB
cwpposts: Data: 0.17MB + Index: 0.06MB
cwprednao_smart_forms_entry: Data: 0.02MB + Index: 0.00MB
cwprednao_smart_forms_entry_detail: Data: 0.02MB + Index: 0.00MB
cwprednao_smart_forms_table_name: Data: 0.02MB + Index: 0.00MB
cwptermmeta: Data: 0.02MB + Index: 0.03MB
cwpterms: Data: 0.02MB + Index: 0.03MB
cwpterm_relationships: Data: 0.02MB + Index: 0.02MB
cwpterm_taxonomy: Data: 0.02MB + Index: 0.03MB
cwpusermeta: Data: 0.02MB + Index: 0.03MB
cwpusers: Data: 0.02MB + Index: 0.05MB
cwpwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
cwpwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
cwpwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
cwpwoocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
cwpwoocommerce_order_items: Data: 0.02MB + Index: 0.02MB
cwpwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
cwpwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
cwpwoocommerce_sessions: Data: 0.02MB + Index: 0.02MB
cwpwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
cwpwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
cwpwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
cwpwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
cwpwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
cwpwoocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.52MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.1.13
WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by madeincosmos** [comment] 2018-11-27 14:44
Reproduced the same problem with WC 3.5.1 - all orders in Failed status give the out of stock message when stock management is disabled.

![Screenshot](http://cld.wthms.co/aCGnbD+)
Screenshot: http://cld.wthms.co/aCGnbD

**Comment by treibalen** [comment] 2018-11-27 15:15
I see the same on my test site as well (it works if you change status to Pending payment):

![http://cld.wthms.co/qPofhk](http://cld.wthms.co/qPofhk+) 
Full Size: http://cld.wthms.co/qPofhk

**Comment by ahegyes** [comment] 2018-11-28 18:35
The issue is in file "class-wc-shortcode-checkout.php", function "order_pay", line 118:

`// Ensure order items are still stocked if paying for a failed order. Pending orders do not need this check because stock is held.
				if ( ! $order->has_status( 'pending' ) ) {`

The above 'if' makes sense if the stock management function is active, but doesn't otherwise. Therefore, it should also check if "woocommerce_manage_stock" is on :)

**Comment by dougaitken** [comment] 2018-11-30 07:31
Looks like this was fixed in #21849 

* I forced a fail using a Stripe test card
* opened failed order page
* saw error
* updated WooCommerce from `3.5.1` > `3.5.2`
* refreshed Pay Order page, success

Fixed in `3.5.2`

**Closed** 2019-01-15 12:23 UTC
