### ISSUE TITLE
Webhook's secret token is invalid

### ISSUE THREAD

**Issue by elct9620** [woocommerce/woocommerce#21693] opened 2018-10-26 14:52 UTC
**Describe the bug**

I build a service to receive WooCommerce's webhook, but suddenly cannot verify the `X-Wc-Webhook-Signature`, after tracking the reason. It is about some character is unescaped or missing in admin dashboard.

**To Reproduce**
1. Go to Config -> Advance -> Webhook
2. Click on New Webhook
3. Save or update the webhook
4. Use the generated secret token to verify the signature
5. In some case, the verify will be failed. Ex. `&` in the database is `&amp;`, or end with `;` will not display, so we cannot copy the correct secret token

**Expected behavior**
The secret token should generate without some character will be escaped or display the correct character in the dashboard.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

Home URL: http://alfheim.localhost:8080
Site URL: http://alfheim.localhost:8080
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: zh_TW
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.5
PHP Version: 7.2.11
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
LibreSSL/2.0.20

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
總資料庫大小: 2.54MB
資料庫資料大小: 1.41MB
資料庫索引大小: 1.13MB
wp_woocommerce_sessions: 資料: 0.02MB + 索引: 0.02MB
wp_woocommerce_api_keys: 資料: 0.02MB + 索引: 0.03MB
wp_woocommerce_attribute_taxonomies: 資料: 0.02MB + 索引: 0.02MB
wp_woocommerce_downloadable_product_permissions: 資料: 0.02MB + 索引: 0.05MB
wp_woocommerce_order_items: 資料: 0.02MB + 索引: 0.02MB
wp_woocommerce_order_itemmeta: 資料: 0.09MB + 索引: 0.09MB
wp_woocommerce_tax_rates: 資料: 0.02MB + 索引: 0.06MB
wp_woocommerce_tax_rate_locations: 資料: 0.02MB + 索引: 0.03MB
wp_woocommerce_shipping_zones: 資料: 0.02MB + 索引: 0.00MB
wp_woocommerce_shipping_zone_locations: 資料: 0.02MB + 索引: 0.03MB
wp_woocommerce_shipping_zone_methods: 資料: 0.02MB + 索引: 0.00MB
wp_woocommerce_payment_tokens: 資料: 0.02MB + 索引: 0.02MB
wp_woocommerce_payment_tokenmeta: 資料: 0.02MB + 索引: 0.03MB
wp_woocommerce_log: 資料: 0.02MB + 索引: 0.02MB
wp_commentmeta: 資料: 0.02MB + 索引: 0.03MB
wp_comments: 資料: 0.05MB + 索引: 0.09MB
wp_failed_jobs: 資料: 0.02MB + 索引: 0.00MB
wp_links: 資料: 0.02MB + 索引: 0.02MB
wp_mailchimp_carts: 資料: 0.02MB + 索引: 0.00MB
wp_options: 資料: 0.45MB + 索引: 0.02MB
wp_postmeta: 資料: 0.25MB + 索引: 0.25MB
wp_posts: 資料: 0.05MB + 索引: 0.06MB
wp_queue: 資料: 0.02MB + 索引: 0.00MB
wp_termmeta: 資料: 0.02MB + 索引: 0.03MB
wp_terms: 資料: 0.02MB + 索引: 0.03MB
wp_term_relationships: 資料: 0.02MB + 索引: 0.02MB
wp_term_taxonomy: 資料: 0.02MB + 索引: 0.03MB
wp_usermeta: 資料: 0.02MB + 索引: 0.03MB
wp_users: 資料: 0.02MB + 索引: 0.05MB
wp_wc_download_log: 資料: 0.02MB + 索引: 0.03MB
wp_wc_webhooks: 資料: 0.02MB + 索引: 0.02MB

### Post Type Counts ###

page: 5
post: 2
product: 1
scheduled-action: 8
shop_order: 69

### Security ###

Secure connection (HTTPS): ❌
					您的商店沒有使用HTTPS。 詳細了解HTTPS和SSL憑證。
Hide errors from visitors: ❌錯誤消息不應該向訪客顯示。

### Active Plugins (1) ###

Mailchimp for WooCommerce: 由 Mailchimp – 2.1.11 – 尚未與最新版 WooCommerce 進行測試

### Settings ###

API Enabled: –
Force SSL: –
Currency: TWD (NT$)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

商店起點: #4 - /shop/
購物車: #5 - /cart/
結帳: #6 - /checkout/
我的帳號: #7 - /my-account/
服務條款: ❌ 未設定頁面

### Theme ###

Name: Storefront
Version: 2.3.4 – 2.3.5 可用
Author URL: https://woocommerce.com/
Child Theme: ❌ – 如果你要修改 WooCommerce 或一個不是你自己建立的父佈景主題的話，那我們建議使用子佈景主題。請看: 如何建立一個子佈景主題
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by kloon** [comment] 2018-11-20 10:14
Not able to reproduce by following your steps http://cld.wthms.co/XLorFc and http://cld.wthms.co/qj8A4r In both cases you can see characters like & and ; displaying fine.

Closing due to inability and insufficient steps to reproduce. Will gladly reopen when you can confirm you are able to recreate this on a clean install with steps I can follow.

**Closed by kloon** 2018-11-20 10:14 UTC
