### ISSUE TITLE
Import Woocommerce for products with CSV doesn't work.

### ISSUE THREAD

**Issue by Lmannano** [woocommerce/woocommerce#26825] opened 2020-06-19 20:34 UTC
I try to use Import Woocommerce for downloading products. 
But pictures don't download with the links. 
And I have the second error after downloading with Import CSV - the status all products are "out of stock". 
I haden't this problem before. I use Import Woocommerce earlier with this csv-file and all was OK.
Please check this problem

**Comment by juliaamosova** [comment] 2020-06-22 17:28
Hi @Lmannano,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Lmannano** [comment] 2020-06-28 19:05
Hello! Thank you for your answer. 
 
I use wordpress — the latest version. I have the csv-file for import produsts.
 
1. I go to «Wordpress», then I go to «Tools», then I go to «Import», then I go to «Products  WooCommerce (CSV)»
*  I click on «Start Import »
*  After import I scroll down to products on the site
*  I see error — the pictures isn’t showed
The pictures saved in csv-file as URL. Earlier the same file was importing very good. Now I have this problem
  
>Понедельник, 22 июня 2020, 22:28 +05:00 от Julia Amosova <notifications@github.com>:
> 
> 
>Hi  @Lmannano ,
>Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
>Describe the bug
>A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
>To Reproduce
>Steps to reproduce the behavior:
>*  Go to '...'
>*  Click on '....'
>*  Scroll down to '....'
>*  See error
>Screenshots
>If applicable, add screenshots to help explain your problem.
>Expected behavior
>A clear and concise description of what you expected to happen.
>Isolating the problem (mark completed items with an [x]):
>*  I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
>*  This bug happens with a default WordPress theme active, or  Storefront .
>*  I can reproduce this bug consistently using the steps above.
>WordPress Environment ``` Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin. ```
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
_________________________
С наилучшими пожеланиями,
Лиана Маннанова,
e-mail: mannanova_lm@mail.ru,
тел.: 8-917-48-66-555.

**Comment by tammullen** [comment] 2021-03-24 18:24
Hi @Lmannano 

Apologies for the delayed reply.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case; In particular see this section on importing products https://docs.woocommerce.com/document/product-csv-importer-exporter/
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-24 18:24 UTC
Labels: has feedback
