### ISSUE TITLE
Import prices in cents

### ISSUE THREAD

**Issue by julian08100** [woocommerce/woocommerce#28970] opened 2021-01-28 13:30 UTC
Is it possible to import the prices in cents ?

**Comment by zhongruige** [comment] 2021-01-28 23:35
Hi @julian08100,

Thank you for reaching out. If the import tool you're using is the WooCommerce product import tool, you can import prices in cents:

<img width="850" alt="Screen Shot 2021-01-28 at 4 31 49 PM" src="https://user-images.githubusercontent.com/71906536/106211797-8b914f00-6186-11eb-95a4-504e715959a5.png">

Here is the contents of the CSV file I used for the import:

```
ID, Title, Stock, price regular, Price sale
500, Imported Product, 10, 0.99, 0.50
501, Imported Product 1, 5, 3.50, 1.50
```

This is the tool I used:

<img width="400" alt="Screen Shot 2021-01-28 at 4 33 37 PM" src="https://user-images.githubusercontent.com/71906536/106211876-ae236800-6186-11eb-81fc-843d3825b2f1.png">

<img width="792" alt="Screen Shot 2021-01-28 at 4 33 44 PM" src="https://user-images.githubusercontent.com/71906536/106211883-b11e5880-6186-11eb-94cc-bc65100beccf.png">

More information can be found in the documentation here: [https://docs.woocommerce.com/document/product-csv-import-suite-importing-products/](https://docs.woocommerce.com/document/product-csv-import-suite-importing-products/)

Let me know if this helps answer your question!

**Comment by zhongruige** [comment] 2021-01-29 18:57
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. So, I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by zhongruige** 2021-01-29 18:57 UTC
Labels: type: support request
