### ISSUE TITLE
"Use for variations" box unticked when importing products on Woocommerce

### ISSUE THREAD

**Issue by monkeyball1** [woocommerce/woocommerce#26291] opened 2020-04-25 14:14 UTC
Hi guys,

I know this question has been asked before and I've read all the threads I've found but it doesn't seem to fix my problem.

Please see the csv sheet containing the product I'm trying to import: https://docs.google.com/spreadsheets/d/1eb0qIJqvoGbRB1mMbkjb_h6BMUJ3I_rkrGdDZK8iXp4/edit?usp=sharing

The single issue with the import is the fact the "use for variations" box in the attributes section remains unticked, despite multiple fixes I've tried after reading several threads about this particular issue. I can't see what I'm doing wrong. Apparently, it is supposed to be automatically ticket upon import but it's not the case here.

May I add that I've tried exporting a functioning product with attributes and variations, replicated the setup on the csv, and the issue still remains.

Thanks so much in advance for your help!

Monkeyball1

**Comment by claudiosanches** [comment] 2020-04-29 20:40
Hi @monkeyball1,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-04-29 20:40 UTC
