### ISSUE TITLE
state dropdown missing on first checkout visit (appears after reload)

### ISSUE THREAD

**Issue by gingerlime** [woocommerce/woocommerce#21835] opened 2018-11-06 18:27 UTC
**Describe the bug**
The first visit to the checkout page does not show the billing state dropdown. After refreshing the page, the dropdown appears

**To Reproduce**
1. Open in Incognito Window (or clear all cookies, etc)
2. Add product to cart
3. Go to checkout
4. State dropdown does not appear
5. Reload the page without changing anything
6. State dropdown does appear, and also on any further visits or reloads

**Screenshots**
Here's an animated gif. It's my wife's website. It's in Japanese (sorry, I don't understand Japanese either, so it's also hard for me). I installed the storefront theme, just to make sure it's not a theme issue. Normally we're using a different theme however.

![woocommerce-state-missing](https://user-images.githubusercontent.com/524274/48084768-e088c980-e1f8-11e8-970a-be645336083d.gif)

**Expected behavior**
The state dropdown should appear on the first visit consistently.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://tst.frau-vintage.com
Site URL: https://tst.frau-vintage.com
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ja
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 20 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.19.7
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.61-38.13 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 216.61MB
Database Data Size: 134.11MB
Database Index Size: 82.50MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.11MB + Index: 0.05MB
wp_woocommerce_order_itemmeta: Data: 0.41MB + Index: 0.39MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
email_dispatches: Data: 0.02MB + Index: 0.00MB
wp_blc_filters: Data: 0.00MB + Index: 0.00MB
wp_blc_instances: Data: 0.83MB + Index: 0.15MB
wp_blc_links: Data: 3.53MB + Index: 0.48MB
wp_blc_synch: Data: 0.01MB + Index: 0.01MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 9.64MB + Index: 1.13MB
wp_eshop_base_products: Data: 0.00MB + Index: 0.00MB
wp_eshop_countries: Data: 0.00MB + Index: 0.01MB
wp_eshop_discount_codes: Data: 0.00MB + Index: 0.01MB
wp_eshop_downloads: Data: 0.00MB + Index: 0.00MB
wp_eshop_download_orders: Data: 0.00MB + Index: 0.00MB
wp_eshop_emails: Data: 0.00MB + Index: 0.00MB
wp_eshop_option_names: Data: 0.00MB + Index: 0.00MB
wp_eshop_option_sets: Data: 0.00MB + Index: 0.00MB
wp_eshop_orders: Data: 1.04MB + Index: 0.13MB
wp_eshop_order_items: Data: 0.91MB + Index: 0.16MB
wp_eshop_rates: Data: 0.00MB + Index: 0.00MB
wp_eshop_states: Data: 0.01MB + Index: 0.01MB
wp_eshop_stock: Data: 0.04MB + Index: 0.05MB
wp_ewwwio_images: Data: 28.56MB + Index: 33.28MB
wp_ig_caticons: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_litespeed_optimizer: Data: 0.02MB + Index: 0.03MB
wp_nxs_log: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.43MB + Index: 0.52MB
wp_pluginSL_shorturl: Data: 0.06MB + Index: 0.00MB
wp_postmeta: Data: 40.36MB + Index: 6.26MB
wp_posts: Data: 29.14MB + Index: 2.79MB
wp_redirection_404: Data: 3.02MB + Index: 4.92MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.08MB + Index: 0.08MB
wp_redirection_logs: Data: 0.06MB + Index: 0.08MB
wp_relevanssi: Data: 9.58MB + Index: 26.22MB
wp_relevanssi_log: Data: 0.02MB + Index: 0.02MB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.22MB + Index: 0.27MB
wp_terms: Data: 0.18MB + Index: 0.22MB
wp_term_relationships: Data: 1.91MB + Index: 4.17MB
wp_term_taxonomy: Data: 0.11MB + Index: 0.11MB
wp_testimonials: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_view_eshop_orders_with_order_date: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB
wp_yarpp_related_cache: Data: 0.21MB + Index: 0.46MB
wp_yoast_seo_links: Data: 0.16MB + Index: 0.06MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

attachment: 17597
customize_changeset: 2
nav_menu_item: 15
page: 13
post: 394
product: 3564
revision: 4684
shop_coupon: 4
shop_order: 288
shop_order_refund: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Loco Translate: by Tim Whitlock – 2.1.5
SMTP Mailer: by naa986 – 1.0.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.5
WooCommerce Stripe Gateway: by WooCommerce – 4.1.12
WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: JPY (¥)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #7274 - /shop/
Cart: #7275 - /cart/
Checkout: #7276 - /checkout/
My account: #7277 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by gingerlime** [comment] 2018-11-06 18:33
I should also mention that while it might look like a javascript loading issue, as far as I could tell, the HTML options for the countries are missing. 

The billing state input field is set initially like this

```html
<p class="form-row form-row-wide address-field validate-required validate-state" id="billing_state_field" style="display: none"><label for="billing_state" class="">州 / 国&nbsp;<abbr class="required" title="必須">*</abbr></label><span class="woocommerce-input-wrapper"><input type="hidden" class="hidden" name="billing_state" id="billing_state" value="" autocomplete="address-level1" placeholder="" readonly="readonly"></span></p>
```

And after reload like this

```html
<p class="form-row form-row-wide address-field validate-required validate-state" id="billing_state_field" data-priority="66"><label for="billing_state" class="">都道府県&nbsp;<abbr class="required" title="必須">*</abbr></label><span class="woocommerce-input-wrapper"><select name="billing_state" id="billing_state" class="state_select  select2-hidden-accessible" autocomplete="address-level1" data-placeholder="" tabindex="-1" aria-hidden="true">
						<option value="">選択してください…</option><option value="JP01">北海道</option><option value="JP02">青森県</option><option value="JP03">岩手県</option><option value="JP04">宮城県</option><option value="JP05">秋田県</option><option value="JP06">山形県</option><option value="JP07">福島県</option><option value="JP08">茨城県</option><option value="JP09">栃木県</option><option value="JP10">群馬県</option><option value="JP11">埼玉県</option><option value="JP12">千葉県</option><option value="JP13">東京都</option><option value="JP14">神奈川県</option><option value="JP15">新潟県</option><option value="JP16">富山県</option><option value="JP17">石川県</option><option value="JP18">福井県</option><option value="JP19">山梨県</option><option value="JP20">長野県</option><option value="JP21">岐阜県</option><option value="JP22">静岡県</option><option value="JP23">愛知県</option><option value="JP24">三重県</option><option value="JP25">滋賀県</option><option value="JP26">京都府</option><option value="JP27">大阪府</option><option value="JP28">兵庫県</option><option value="JP29">奈良県</option><option value="JP30">和歌山県</option><option value="JP31">鳥取県</option><option value="JP32">島根県</option><option value="JP33">岡山県</option><option value="JP34">広島県</option><option value="JP35">山口県</option><option value="JP36">徳島県</option><option value="JP37">香川県</option><option value="JP38">愛媛県</option><option value="JP39">高知県</option><option value="JP40">福岡県</option><option value="JP41">佐賀県</option><option value="JP42">長崎県</option><option value="JP43">熊本県</option><option value="JP44">大分県</option><option value="JP45">宮崎県</option><option value="JP46">鹿児島県</option><option value="JP47">沖縄県</option></select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 100%;"><span class="selection"><span class="select2-selection select2-selection--single" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-billing_state-container" role="combobox"><span class="select2-selection__rendered" id="select2-billing_state-container" role="textbox" aria-readonly="true"><span class="select2-selection__placeholder"></span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span></span></p>
```

**Comment by natfire** [comment] 2018-11-07 16:21
Same issue here! When I reload the checkout page no matter which browser I use, then the 'State' dropdown works.

**Comment by gingerlime** [comment] 2018-11-07 19:18
I did a git bisect, and I think this commit is the prime suspect 11da1898b83832057b01eec921c5e881c7cdc509

**Comment by gingerlime** [comment] 2018-11-07 19:19
@peterfabian ?

**Comment by Matiasi** [comment] 2018-11-09 02:29
I'm having the same issue. Exactly the same. Tried Twenty Sixteen theme with only Woo, everything updated and the error is recurring. Please solve this, it's a huge conversion killer. I'm losing sales as a lot of people isn't available to checkout. Thanks

**Comment by SebastianPendino** [comment] 2018-11-12 10:52
Workaround here (haven't tested it):
[https://github.com/woocommerce/woocommerce/issues/21790](url)

**Comment by Matiasi** [comment] 2018-11-12 12:17
https://github.com/woocommerce/woocommerce/issues/21790 here you can find a workaround. I tested it in my site and it worked!

**Comment by Matiasi** [comment] 2018-11-12 12:29
> The workaround should fix the state selection, but there's still another problem I reported on [#20640 (comment)](https://github.com/woocommerce/woocommerce/issues/20640#issuecomment-436769304) that it doesn't fix and relates to [e98694b](https://github.com/woocommerce/woocommerce/commit/e98694b8406834ba01bbdb16622e485c81f50115)

Are you referring to the change in the order of the fields? Or is it something else? I don't have that issue.

**Comment by gingerlime** [comment] 2018-11-12 13:03
@Matiasi yes, although I don't expect many people to have this issue... I'm using a plugin that adds a couple of address fields unique to Japan. It works before this change, and also it works ok after refreshing the page, but when you first hit the checkout page, the order of the address fields is messed up :-/

**Comment by peterfabian** [comment] 2018-11-13 15:03
Hi, 

Thanks for reporting. 

I'm having trouble reproducing the issue. I've tried this on WP 4.9.8 with WC 3.5.1, tested with Twenty Sixteen and Storefront themes. Tried testing with `Default customer location` set to either `Shop base address` (for stores located in US and Japan) or `Geolocate`. 

I'm always getting the state as a dropdown, though, so there must be something else at play here. Maybe some setting I'm missing? Would you mind sharing your shipping options and general options?

**Comment by peterfabian** [comment] 2018-11-13 15:10
As this is a duplicate of https://github.com/woocommerce/woocommerce/issues/21790, I'm closing this one. Please follow the progress on the other issue.

**Closed by peterfabian** 2018-11-13 15:10 UTC

**Comment by gingerlime** [comment] 2018-11-13 16:14
@peterfabian sure, happy to share the settings. How/What can I share them with you? My shipping options are set for only one country (Japan), so perhaps that makes a difference? (there's no country selection, but only state selection?)

I just saw that the other problem with the field order was fixed by the plugin author https://wordpress.org/plugins/woocommerce-for-japan/#developers so it boils down to the states dropdown, as described here and #21790. The workaround for #21790 works fine for me for the time being :)

**Comment by peterfabian** [comment] 2018-11-14 09:39
I guess the easiest is maybe to share screenshots of those options relevant to shipping here?

**Comment by gingerlime** [comment] 2018-11-14 12:15
Do these help?

![2018-11-14_716x341_sceenshot](https://user-images.githubusercontent.com/524274/48481890-57345100-e80f-11e8-8f94-694ea70a0622.png)
![2018-11-14_1724x472_sceenshot](https://user-images.githubusercontent.com/524274/48481891-57345100-e80f-11e8-89c4-50000dd02f02.png)

**Comment by natfire** [comment] 2018-11-14 13:10
Hey gingerlime, setting to "Geolocate" worked!! Thank you!!!

**Comment by masterbip** [comment] 2018-11-19 16:43
I am having the same issue here. I have deactivated Select2 Style and Jquery, changed a lot of parameters, test some plugins, and nothing works.

**Comment by jackscoast** [comment] 2020-03-15 15:23
Did anyone get the answer to this? Driving me crazy nothing works and I'm loosing business

**Comment by peterfabian** [comment] 2020-03-17 08:59
Hi @jackscoast , have you tried to resolve potential conflicts with other plugins and your theme? Please open a new issue with steps to reproduce and your system status report so that we can try to reproduce it on our end.
