### ISSUE TITLE
Bug using WooCommerce v4.0.1 + WP 5.4.1 + theme The7 v8.7.1

### ISSUE THREAD

**Issue by julienbraida** [woocommerce/woocommerce#26372] opened 2020-05-04 16:38 UTC
**Describe the bug**
my shop is: shop.julienbraida.com
Frontend: my website works fine, prices are good and my virtual products (eBooks) are well downloaded when I test. 
But, backend, in WP admin panel, in WooCommerce there are 2 bugs I've noticed:
1- there is a message that don't want to go away, something like "The update of the Woocommerce database is complete". When I click "Thank you!" there is a grey page loading with a message saying something like "Action failed. Reload the page and try again". Can't get rid of that message.

2- when I go to my products in WC (admin panel), all the prices are wrong! And when I enter into a product settings to apply modifications, everything is wrong (prices, the downloadable product is not checked, download link to the product is empty etc etc). But front-end the shop works: prices are good and download and by products work etc so weird

I have disable every plugins except woocommerce and the problem still there ... so is it a bug from the update of my WC database?

**To Reproduce**
1. Go to 'WP admin panel on shop.julienbraida.com'
2. Click on 'Products under WooCommerce'
3. See error

**Expected behavior**
To be able to modify all the settings for a specific product

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

`
### WordPress Environment ###

WordPress address (URL): https://shop.julienbraida.com
Site address (URL): https://shop.julienbraida.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.17
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.31-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Taille totale de la base de données: 114.98MB
Taille de la base de données: 88.33MB
Taille de l’index: 26.65MB
wp_woocommerce_sessions: Données : 0.25MB + Index : 0.01MB + Moteur MyISAM
wp_woocommerce_api_keys: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.36MB + Index : 0.84MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.08MB + Index : 0.03MB + Moteur MyISAM
wp_woocommerce_order_itemmeta: Données : 0.42MB + Index : 0.27MB + Moteur MyISAM
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_methods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokenmeta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_woocommerce_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_actionscheduler_actions: Données : 0.05MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_affiliate_wp_affiliatemeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_affiliate_wp_affiliates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_affiliate_wp_creatives: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_affiliate_wp_referrals: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_affiliate_wp_visits: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_aiowps_events: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_aiowps_failed_logins: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_aiowps_global_meta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_aiowps_login_activity: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_aiowps_login_lockdown: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_aiowps_permanent_block: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_ads: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_cron: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_referrals: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_salaries: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_sites: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_spaces: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_stats: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_users: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_bsa_pro_withdrawals: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_circular_countdown_countdowns: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_circular_countdown_playlist: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_circular_countdown_settings: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_cn_social_icon: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur MyISAM
wp_comments: Données : 0.20MB + Index : 0.09MB + Moteur MyISAM
wp_datalist: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_et_bloom_stats: Données : 1.23MB + Index : 0.25MB + Moteur MyISAM
wp_et_social_stats: Données : 0.05MB + Index : 0.01MB + Moteur MyISAM
wp_gCountdown: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_icl_strings: Données : 0.15MB + Index : 0.11MB + Moteur MyISAM
wp_icl_string_translations: Données : 0.12MB + Index : 0.04MB + Moteur MyISAM
wp_layerslider: Données : 0.13MB + Index : 0.00MB + Moteur MyISAM
wp_links: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_litespeed_optimizer: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_nxs_log: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
wp_opanda_leads: Données : 0.16MB + Index : 0.02MB + Moteur InnoDB
wp_opanda_leads_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_opanda_stats_v2: Données : 0.36MB + Index : 0.34MB + Moteur InnoDB
wp_optinskin: Données : 0.16MB + Index : 0.00MB + Moteur MyISAM
wp_options: Données : 3.95MB + Index : 0.34MB + Moteur MyISAM
wp_paypal_products: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_paypal_transactions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_popover_ip_cache: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_postmeta: Données : 33.88MB + Index : 20.93MB + Moteur MyISAM
wp_posts: Données : 0.69MB + Index : 0.18MB + Moteur MyISAM
wp_rac_abandoncart: Données : 0.03MB + Index : 0.00MB + Moteur MyISAM
wp_rac_email_logs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_rac_templates_email: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_revslider_css: Données : 0.16MB + Index : 0.02MB + Moteur InnoDB
wp_revslider_layer_animations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_revslider_navigations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_revslider_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_revslider_sliders: Données : 1.52MB + Index : 0.02MB + Moteur InnoDB
wp_revslider_slides: Données : 6.52MB + Index : 0.02MB + Moteur InnoDB
wp_revslider_static_slides: Données : 0.44MB + Index : 0.02MB + Moteur InnoDB
wp_smart_donations_campaign_table: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_smart_donations_donation_item: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_smart_donations_progress_table: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_smart_donations_transaction_table: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_smush_dir_images: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_snippets: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_so_tracking: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_ssbp_email_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_subscriptio_scheduled_events: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_tcb_api_error_log: Données : 0.58MB + Index : 0.01MB + Moteur MyISAM
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur MyISAM
wp_terms: Données : 0.04MB + Index : 0.08MB + Moteur MyISAM
wp_term_relationships: Données : 0.04MB + Index : 0.08MB + Moteur MyISAM
wp_term_taxonomy: Données : 0.04MB + Index : 0.05MB + Moteur MyISAM
wp_tve_leads_contacts: Données : 0.11MB + Index : 0.02MB + Moteur MyISAM
wp_tve_leads_contact_download: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_tve_leads_event_log: Données : 4.77MB + Index : 0.84MB + Moteur MyISAM
wp_tve_leads_form_variations: Données : 0.15MB + Index : 0.00MB + Moteur MyISAM
wp_tve_leads_group_options: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_tve_leads_saved_group_options: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_tve_leads_split_test: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_tve_leads_split_test_items: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_uap_dashboard_notifications: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_ulp_campaigns: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_ulp_campaign_items: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_ulp_layers: Données : 0.35MB + Index : 0.01MB + Moteur MyISAM
wp_ulp_popups: Données : 0.07MB + Index : 0.00MB + Moteur MyISAM
wp_ulp_subscribers: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_ulp_targets: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_ulp_webfonts: Données : 0.05MB + Index : 0.01MB + Moteur MyISAM
wp_usermeta: Données : 0.37MB + Index : 0.23MB + Moteur MyISAM
wp_users: Données : 0.03MB + Index : 0.04MB + Moteur MyISAM
wp_waiting: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.08MB + Index : 0.06MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.11MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.09MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfBlockedIPLog: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfBlocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wfConfig: Données : 1.34MB + Index : 0.01MB + Moteur MyISAM
wp_wfCrawlers: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfFileChanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfFileMods: Données : 1.78MB + Index : 0.38MB + Moteur MyISAM
wp_wfHits: Données : 0.42MB + Index : 0.08MB + Moteur MyISAM
wp_wfHoover: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfIssues: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
wp_wfKnownFileList: Données : 0.93MB + Index : 0.11MB + Moteur MyISAM
wp_wfLiveTrafficHuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfLocs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfLogins: Données : 0.11MB + Index : 0.03MB + Moteur MyISAM
wp_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfNotifications: Données : 0.02MB + Index : 0.00MB + Moteur MyISAM
wp_wfPendingIssues: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfReverseCache: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfSNIPCache: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfStatus: Données : 0.15MB + Index : 0.06MB + Moteur MyISAM
wp_wfTrafficRates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_recommendations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_session_activity: Données : 24.55MB + Index : 0.00MB + Moteur InnoDB
wp_wpam_actions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_affiliates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_affiliates_fields: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_creatives: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_events: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_impressions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_messages: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_paypal_logs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_tracking_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_tracking_tokens_purchase_logs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpam_transactions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpsb_users: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wp_eStore_cat_prod_rel_tbl: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_cat_tbl: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_coupon_tbl: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_customer_tbl: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_download_links_tbl: Données : 0.22MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_meta_tbl: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_pending_payment_tbl: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_products_meta_tbl: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_sales_tbl: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wp_eStore_save_cart_tbl: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wp_eStore_tbl: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
wp_yith_ywrac_email_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM

### Post Type Counts ###

attachment: 280
custom_css: 1
dhwc_template: 1
dt_benefits: 14
dt_gallery: 6
dt_logos: 3
dt_portfolio: 76
dt_slideshow: 2
dt_team: 1
dt_testimonials: 25
dtwpb_product_tpl: 1
et_pb_layout: 32
inc_popup: 1
leadpages_post: 1
nav_menu_item: 50
opanda-item: 19
page: 6
popup: 13
popup_theme: 4
post: 1
product: 111
product_variation: 8
revision: 59
shop_coupon: 18
shop_order: 575
shop_order_refund: 2
sub_transaction: 169
subscription: 25
tve_form_type: 57
tve_lead_2s_lightbox: 1
tve_lead_asset_group: 2
tve_lead_group: 6
vc_grid_item: 1
wc_product_retailer: 4
ywrac_cart: 1
ywrac_email: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

The7 Ultimate Addons for WPBakery Page Builder: par Brainstorm Force – 3.19.4
Amazon Link Engine: par GeoRiot Networks
Inc. – 1.3.7

Amazon Web Services: par Delicious Brains – 1.0.5
WooCommerce shortcodes for Visual Composer: par Anpsthemes – 1.7.2 – Non testé avec la version active de WooCommerce
Beeketing For WooCommerce: par Beeketing – 3.8.16 – Non testé avec la version active de WooCommerce
Extraits de code: par Code Snippets Pro – 2.14.0
Custom PRODUITS CHOISIS POUR VOUS ♥️ for WooCommerce: par Scott Nelle – 1.3 – Non testé avec la version active de WooCommerce
WooCommerce Single Product Page Builder: par SiteSao Team – 4.2.1 – Non testé avec la version active de WooCommerce
Hyper Cache: par Stefano Lissa – 3.3.9
The7 WPBakery Page Builder: par Michael M - WPBakery.com – 6.1
Layered Popups: par Halfdata
Inc. – 6.64

Loco Translate: par Tim Whitlock – 2.3.3
Monarch Plugin: par Elegant Themes – 1.4.11
Recover Abandoned Cart: par Fantastic Plugins – 14.5.1 – Non testé avec la version active de WooCommerce
Tracking Code Manager: par IntellyWP – 1.12.2
WooCommerce Checkout Field Editor: par WooThemes – 1.4.10 – 1.5.32 est disponible – Non testé avec la version active de WooCommerce
WooCommerce Stripe Gateway: par WooCommerce – 4.3.3
WooCommerce Gift Card: par Isaac Oyelowo – 2.2 – Non testé avec la version active de WooCommerce
WooCommerce Pretty Emails: par MB Création – 1.8.6 – Non testé avec la version active de WooCommerce
WooCommerce: par Automattic – 4.0.1
Wordfence Security: par Wordfence – 7.4.7
WP CDN Rewrite: par Chris Scott
Michael Pretty
Kevin Langley
Sean McCafferty – 0.4.0

### Inactive Plugins (2) ###

Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: par SeedProd – 5.1.0
WPFront Notification Bar: par Syam Mohan – 1.7.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
wbs_bundle (wbs_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la boutique: #994 - /
Panier: #995 - /panier/
Validation de la commande: #996 - /verification/
Mon compte: #997 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: The7
Version: 8.7.1
Author URL: http://dream-theme.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7/woocommerce/content-product.php
dt-the7/woocommerce/content-product_cat.php
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/admin-cancelled-order.php version 2.3.0 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/admin-failed-order.php version 2.5.0 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/admin-new-order.php version 2.0.0 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-completed-order.php version 1.6.4 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-invoice.php version 2.2.0 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-new-account.php version 1.6.4 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-note.php version 1.6.4 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-on-hold-order.php version - est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-processing-order.php version 1.6.4 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-refunded-order.php version 2.4.0 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/customer-reset-password.php version 2.0.0 est obsolète. La version du noyau est 4.0.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/email-addresses.php version 2.2.0 est obsolète. La version du noyau est 3.9.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/email-customer-details.php
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/email-footer.php version 2.0.0 est obsolète. La version du noyau est 3.7.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/email-header.php version 1.0 est obsolète. La version du noyau est 4.0.0
/home/julienbr/shop.julienbraida.com/wp-content/plugins/woocommerce-pretty-emails/emails/email-order-items.php version 2.1.2 est obsolète. La version du noyau est 3.7.0
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/pagination.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### Action Scheduler ###

Terminer: 70
Oldest: 2020-04-16 12:35:36 +0200
Newest: 2020-05-04 17:55:01 +0200

`

**Comment by peterfabian** [comment] 2020-05-05 12:32
Hi, 

> 1- there is a message that don't want to go away, something like "The update of the Woocommerce database is complete". When I click "Thank you!" there is a grey page loading with a message saying something like "Action failed. Reload the page and try again". Can't get rid of that message.

Apologies for this, it seems like the security protection for that message has expired. If you know how to run SQL queries on your db, you can get rid of it by running the following:
```
UPDATE wp_wc_admin_notes SET status='actioned' WHERE name='wc-update-db-reminder';
```

> 2- when I go to my products in WC (admin panel), all the prices are wrong! And when I enter into a product settings to apply modifications, everything is wrong (prices, the downloadable product is not checked, download link to the product is empty etc etc). But front-end the shop works: prices are good and download and by products work etc so weird

This indeed sounds quite strange. I see you tried to disable all the plugins, but saw you also have some caching plugins in the list, could it be the caching is somehow affecting the results? Can you check if the prices in the database are correct? E.g. by running a query 
`SELECT * FROM `wp_postmeta` where post_id = 31 and meta_key LIKE '%price%'` (just replacing 31 with one of your product ids where you see the problem happening)?

**Comment by julienbraida** [comment] 2020-05-05 13:03
Hi Peter, and thanks for your prompt reply, that’s great cause I’m blocked with this issue. I have disabled the caching plugin of course to test but without any results. I can change things on my shop without any problem but when it comes to change in WC, nothing works. E.g. I tried to update a product by changing settings in a product page (price, description, discount, link to the downloadable file etc) and after updating the page, nothing happened. Everything stills the same in front-end … That’s a good point cause everything works and is not broken but I can’t make a change in any of my products!!

Not very convenient. For the SQL queries on my db, I found how to do that! I run the first query to remove the message. It worked.

Then, I ran the query to see the price and the price is the (strange) one shown in the admin panel but not the one running in front-end of my shop … (see screenshot in attachement if it works). The price shown in admin panel is 149.9€ and the right price shown in my shop is 39.95€ … 

( When it will be solved, I have 2 other questions for you to customize my WC. But I want to solve one problem after an other ;)

Tell me if you need access to my website. I’m not a fan of giving access to my website, last time I’ve been hacked and they delete every pages of my products and best posts … :( But if it can help you fix that, I can make an exception 

Thanks again for your help

**Comment by peterfabian** [comment] 2020-05-05 19:27
Hi again, 

it seems to me there is some strange caching going on your front end. When I add anything to the cart (even multiple items) on shop.julienbraida.com, I only see one item in the cart--XTREME MASS WORKOUT. So it seems to me your frontend is cached incorrectly, while your admin shows the same as the database (which should be usually the case, as admin is generally not cached).

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs with steps to reproduce and it seems to me your request would be better suited for our support channels:

- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- otherwise please make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you manage to confirm this is a bug, please provide us with clear steps to reproduce it with only WC plugin active, maybe if you have a staging environment with the same database, it can help pinpoint the problem more easily.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by peterfabian** 2020-05-05 19:27 UTC
Labels: can't reproduce, status: needs feedback
