### ISSUE TITLE
Problem adding bulk pricing in products variation.

### ISSUE THREAD

**Issue by yorgosf** [woocommerce/woocommerce#26246] opened 2020-04-22 18:17 UTC
Hi i try to add bulk change the price in variation product and not working. Example for variable products if you go to Variation section and click ""set regulare price" and then add, the products not get the prices set.

**To Reproduce**
see the video, sometimes add price in all, sometime only in one-two, sometimes not add prices.
https://monosnap.com/direct/QMgRziLnXd9LOOHUPwlnSdCCp0mbo9

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://redzeppelin.gr
Site address (URL): https://redzeppelin.gr
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.17
PHP Post Max Size: 32 MB
PHP Time Limit: 150
PHP Max Input Vars: 5000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.31-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: 1rR6E28fF0_
Total Database Size: 49.31MB
Database Data Size: 42.65MB
Database Index Size: 6.66MB
1rR6E28fF0_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1rR6E28fF0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1rR6E28fF0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_actionscheduler_actions: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
1rR6E28fF0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_actionscheduler_logs: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
1rR6E28fF0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
1rR6E28fF0_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
1rR6E28fF0_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_mailerlite_checkouts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_mailerlite_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_mypos_pending_payments_schedule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_options: Data: 4.36MB + Index: 0.16MB + Engine InnoDB
1rR6E28fF0_postmeta: Data: 13.52MB + Index: 3.80MB + Engine InnoDB
1rR6E28fF0_posts: Data: 15.47MB + Index: 0.50MB + Engine InnoDB
1rR6E28fF0_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1rR6E28fF0_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
1rR6E28fF0_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
1rR6E28fF0_regenerate_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_sliders: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_sliders_bkp: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_slides: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_slides_bkp: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_termmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
1rR6E28fF0_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_term_relationships: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
1rR6E28fF0_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1rR6E28fF0_viva_payment_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1rR6E28fF0_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1rR6E28fF0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1rR6E28fF0_wc_product_meta_lookup: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
1rR6E28fF0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_woodmart_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1rR6E28fF0_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1rR6E28fF0_yith_wcwl_lists: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1rR6E28fF0_yoast_seo_links: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
1rR6E28fF0_yoast_seo_meta: Data: 0.19MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 819
cms_block: 26
custom_css: 1
customize_changeset: 41
jetpack_migration: 2
mc4wp-form: 1
nav_menu_item: 415
oembed_cache: 3
page: 27
post: 4
product: 584
product_variation: 94
revision: 851
shop_order: 1
wcpa_pt_forms: 1
woodmart_sidebar: 1
woodmart_size_guide: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Admin Menu Editor: by Janis Elsts – 1.9.5
All 404 Redirect  to Homepage: by Fakhri Alsadi – 1.19
Contact Form 7: by Takayuki Miyoshi – 5.1.7
Duplicate Menu: by Jonathan Christopher – 0.2.2
Duplicate Post: by Enrico Battocchi – 3.2.4
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.4
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.3.9.3

Enable Gzip Compression: by Moki-Moki Ios – 1.0.3
Facebook for WooCommerce: by Facebook – 1.10.2
Fast Velocity Minify: by Raul Peixoto – 2.8.3
Imagify: by WP Media – 1.9.9
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
Loco Translate: by Tim Whitlock – 2.3.3
LoginPress - Customizing the WordPress Login: by WPBrigade – 1.4.3
Official MailerLite Sign Up Forms: by MailerGroup – 1.4.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Remove Uppercase Accents: by Giorgos Sarigiannidis – 0.5
Reveal IDs: by Oliver Schlöbe – 1.5.4
Slider Revolution: by ThemePunch – 6.2.2
Safe SVG: by Daryll Doyle – 1.9.8
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.3
WooCommerce - MailerLite: by MailerLite – 1.4.7 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 1.0.3
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.20
WooCommerce: by Automattic – 4.0.1
Woodmart Core: by  – 1.0.22
Yoast SEO: by Team Yoast – 13.5
Smart Image Resize PRO: by Nabil Lemsieh – 1.3.9 – Not tested with the active version of WooCommerce
WP Super Cache: by Automattic – 1.7.1
ReCaptcha v2 for Contact Form 7: by IQComputing – 1.2.5

### Inactive Plugins (5) ###

Messenger Customer Chat: by Facebook – 1.4
Redirection: by John Godley – 4.7.1
WooCommerce Extra Charges To Payment Gateway (Standard): by hemsingh1 – 1.0.12.9 – Not tested with the active version of WooCommerce
WooCommerce XML feed for Skroutz & Bestprice: by Enartia – 1.5.0 – Not tested with the active version of WooCommerce
WP Chatbot: by MobileMonkey – 4.5

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wooco (wooco)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #7689 - /%cf%8c%cf%81%ce%bf%ce%b9-%cf%87%cf%81%ce%ae%cf%83%ce%b7%cf%82-checkout/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 4.6.0
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-product_cat.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php


### Action Scheduler ###

Complete: 503
Oldest: 2020-03-22 18:35:33 +0000
Newest: 2020-04-22 17:25:24 +0000

Pending: 1
Oldest: 2020-04-22 18:25:24 +0000
Newest: 2020-04-22 18:25:24 +0000

`
```
</details>

**Comment by yorgosf** [comment] 2020-04-23 05:32
i check all say this issue and looks like there is conflict with OFFICIAL facebook plugins, i think it is impossible to fix this issue from facebook part so i suggest to try and fix it.
"Facebook for WooCommerce"
"Messenger Customer Chat"

**Comment by juliaamosova** [comment] 2020-05-06 18:17
Hi @yorgosf,

Thank you for raising the issue. However, I can’t reproduce it. Everything is working as expected on my end. 

![](http://g.recordit.co/mQ9nsezQMq.gif)

You mentioned that you've done a plugin conflict and determined that [Facebook for WooCommerce](https://woocommerce.com/products/facebook/) plugin is causing the issue. If this is the case, please click on `Get support` button on the [Facebook for WooCommerce](https://woocommerce.com/products/facebook/) plugin product page to report the bug and have it fixed. 

I am closing this issue since there is no bug on the WooCommerce Core side of things. However, please feel free to comment again in case you think I missed something. We'd be happy to take another look.

**Closed by juliaamosova** 2020-05-06 18:17 UTC
