### ISSUE TITLE
Hide and protect woocommerce download link in cloud storage and dl hosts

### ISSUE THREAD

**Issue by chem20** [woocommerce/woocommerce#12977] opened 2017-01-25 12:45 UTC
I use woocommerce and Some of the Products links from cloud storage and download hosting  but when user download the file the direct download link showing in Doawnload Manager and is very bad .downlaod method is Force Downloads Please help me how can l secure cloud and dl  host download link in woocommerce but when i use internal download link in woocommerce the link is protect and dont show

**Comment by chem20** [comment] 2017-01-26 09:58
I have 2 servers. On Server 1 I have a WordPress website. On Server 2 I have large .zip files that I want members from the WordPress site to be able to download.

How do I authenticate these users so that only people that are members of the website can download files from the second server?

Is it possible to use PHP so that only referrers from my domain have access to the files?

Note: The links to download the files are protected on the wordpress site so that non-logged in users are redirected to a join page. However, current and ex-members would still know the directory where the downloads are and could possibly download the files or share the links

**Comment by mikejolley** [comment] 2017-01-26 13:15
If force is not possible, it has to revert to a link to prevent broken links. Remote files cannot always be forced because it's out of WC and your servers control. This is not a bug.

You can look into xsendfile support on server 1 to protect and serve them, or you can use something like Amazon S3 + extension, or you can build something on Server 2 to check permissions (use API? use access token?). This is out of scope for core to handle for you.

**Closed by mikejolley** 2017-01-26 13:15 UTC

**Comment by chem20** [comment] 2017-01-26 13:46
in the xsendfile state  the file on server 2 was protected? and download link dont show?

**Comment by mikejolley** [comment] 2017-01-26 14:01
xsendfile serves downloads from the same server as WC, if supported.

**Comment by chem20** [comment] 2017-01-26 14:10
do you explain the following solution?
`http://stackoverflow.com/questions/10964399/protect-downloads-on-remote-server`

**Comment by mikejolley** [comment] 2017-01-26 14:21
> There are several ways of doing this. The most secure way would be to have some back-end communication between Server 1 & Server 2

His force download example is similar to ours, but it doesn't work well for large files and is not supported on all servers.

**Comment by chem20** [comment] 2019-09-13 13:00
Is there any way  php code that protected the download links of virtual products in Woocommers on the second server?
