### ISSUE TITLE
custom phone validation in billing address under my account addresses tab

### ISSUE THREAD

**Issue by avinash20017** [woocommerce/woocommerce#26776] opened 2020-06-16 04:43 UTC
I use the following code and put in functions.php but it was not working. 

// Limit Woocommerce phone field to 10 digits number
add_action('woocommerce_billing_fields', 'my_custom_field_process');
  
function my_custom__field_process() {

  
    // Check if set, if its not set add an error. This one is only requite for companies
    if ( ! (preg_match('/^[0-9]{10}$/D', $_POST['billing_phone'] ))){
        wc_add_notice( "Incorrect Phone Number! Please enter valid 10 digits phone number"  ,'error' );
    }
}

**Comment by tammullen** [comment] 2020-06-16 09:40
Hi @avinash20017 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it and all the other information in the bug report template so that we can fully evaluate it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
Label:

**Closed by tammullen** 2020-06-16 09:40 UTC

**Comment by KoolPal** [comment] 2020-07-01 06:37
@avinash20017

Try this code instead

```
add_action('woocommerce_checkout_process', 'custom_validate_billing_phone');
function custom_validate_billing_phone() {
    $is_correct = preg_match('/^[6-9]\d{9}$/', $_POST['billing_phone']);
    if ( $_POST['billing_phone'] && !$is_correct) {
        wc_add_notice( __( '<strong>Phone</strong> should be <strong>10 digit Indian Mobile number starting with 6,7,8 or 9</strong>. Please enter a valid Indian Mobile Number.' ), 'error' );
    }
}
```
