### ISSUE TITLE
Out of Stock Visibility only shows 'Out of Stock' on Variables when de-selected

### ISSUE THREAD

**Issue by Zedys** [woocommerce/woocommerce#28003] opened 2020-10-19 12:59 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When 'Out of Stock Visibility' is enabled in the WooCommerce settings, product variation swatches are still selectable with no display showing that a product is out of stock. If 'Out of Stock Visibility' is selected, the swatch/product variation is not hidden and no "Out of Stock" message is displayed.

**Expected behavior**
'Hide out of stock items from catalogue' should hide or grey out variable swatches entirely.

**Actual behavior**
When 'Out of Stock Visibility' is enabled in the WooCommerce settings, product variation swatches are still selectable with no display showing that a product is out of stock. If 'Out of Stock Visibility' is selected, the swatch/product variation is not hidden and no "Out of Stock" message is displayed. Only 'Add to Cart' button is not selectable in both instances.

If 'Hide out of Stock' is deselected, then products which are completely out of stock in all variations, etc. become visible in the catalogue again.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create variable product with swatch selector for variations (this is not a 3rd party plugin, but included in North Theme by FuelThemes)
2. Add variation with stock management enabled for variations (i.e. Size), and ensure quantity is set to 0
3. Enable 'Out of Stock Visibility' in WooCommerce > Settings > Products > Inventory
4. Product variation is still selectable with no text error.
5. Disable 'Out of Stock Visibility' and review product, text 'OUT OF STOCK' is now displayed.

**Screenshots**
**Displaying Out Of Stock Text when Hide Visibility is Deselected**
https://ibb.co/4fj3yjS
https://ibb.co/HP8fCcW

**Hide Visibility of Out of Stock Items Enabled, and no Text Visible**
https://ibb.co/hHHDPJB
https://ibb.co/vYJ7pwM

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

When storefront theme is enabled, only a drop-down option is available for variations. If 'hide out of stock' is enabled, then only the products in-stock are dispalyed. If it is deselected, then it shows 'Out of stock' text.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://xx
Site address (URL): https://xx
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.11
PHP Post Max Size: 1 GB
PHP Time Limit: 1500
PHP Max Input Vars: 2000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 31.45MB
Database Data Size: 25.46MB
Database Index Size: 5.99MB
wp_woocommerce_sessions: Data: 2.30MB + Index: 0.06MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.72MB + Index: 0.41MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 1.65MB + Index: 0.48MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.82MB + Index: 0.58MB + Engine MyISAM
wp_aff_affiliates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aff_affiliates_attributes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aff_affiliates_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aff_hits: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_aff_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_aff_rates_metas: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aff_referrals: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aff_referral_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aff_robots: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aff_uris: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_aff_user_agents: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.21MB + Index: 0.09MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mclean_refs: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_mclean_scan: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 6.08MB + Index: 0.20MB + Engine MyISAM
wp_postmeta: Data: 6.63MB + Index: 2.06MB + Engine MyISAM
wp_posts: Data: 3.63MB + Index: 0.47MB + Engine MyISAM
wp_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_relationships: Data: 0.05MB + Index: 0.10MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.19MB + Index: 0.12MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_w3tc_cdn_pathmap: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.08MB + Engine MyISAM
wp_wc_order_stats: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gc_activity: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_gc_cards: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_gpf_google_taxonomy: Data: 0.89MB + Index: 0.00MB + Engine MyISAM
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Data: 0.26MB + Index: 0.14MB + Engine MyISAM
wp_yith_wcwl_lists: Data: 0.31MB + Index: 0.20MB + Engine MyISAM
wp_yoast_indexable: Data: 1.12MB + Index: 0.49MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

affiliates_banner: 1
attachment: 471
br_notice: 1
custom_css: 1
customize_changeset: 1
nav_menu_item: 206
oembed_cache: 1
option-tree: 1
page: 22
post: 10
product: 111
product_variation: 291
revision: 496
shop_coupon: 2715
shop_order: 
shop_order_refund: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Affiliates Pro: by itthinx – 4.7.0
Classic Editor: by WordPress Contributors – 1.6
Contact Form 7: by Takayuki Miyoshi – 5.2.2
Duplicate Page: by mndpsingh287 – 4.3
Facebook for WooCommerce: by Facebook – 2.0.5
Itthinx Updates: by itthinx – 1.2.0
Jetpack by WordPress.com: by Automattic – 9.0.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.4.1
North - Required Plugin: by fuelthemes – 1.3.2
WooCommerce Payflex Gateway: by Payflex – 1.9 – Installed version not tested with active version of WooCommerce 4.5.2
Product CSV Import Export (BASIC): by WebToffee – 1.8.4
CM Commerce for WooCommerce: by Campaign Monitor – 1.6.0 – Installed version not tested with active version of WooCommerce 4.5.2
Slider Revolution: by ThemePunch – 6.2.23
W3 Total Cache: by BoldGrid – 0.15.1
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.3.9 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Checkout Add-Ons: by SkyVerge – 2.3.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Ozow Gateway: by <a href="https://Ozow.com" />Ozow</a> – 1.0.0.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Gift Cards: by SomewhereWarm – 1.3.5 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.11 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce PayFast Gateway: by WooCommerce – 1.4.15 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.7.0
WooCommerce Google Product Feed: by Ademti Software Ltd. – 8.1.4 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce: by Automattic – 4.5.2 (update to version 4.6.0 is available)
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO: by Team Yoast – 15.1.1
WP Maintenance Mode: by Designmodo – 2.2.4
Smush Pro: by WPMU DEV – 3.7.1
WPMU DEV Dashboard: by WPMU DEV – 4.10.5
YITH WooCommerce Wishlist: by YITH – 3.0.15

### Inactive Plugins (6) ###

Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Media Cleaner: by Jordy Meow – 6.0.8
Product Reviews Import Export (Basic): by WebToffee – 1.3.9 – Installed version not tested with active version of WooCommerce 4.5.2
Product XML Feeds for WooCommerce Pro: by WPWhale – 1.9.5
WooCommerce Custom Related Products Pro: by WPCodelibrary – 1.3.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce PDF Invoice: by RightPress – 3.2.1 – Installed version not tested with active version of WooCommerce 4.5.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #505 - /cart/
Checkout: #7 - /checkout/
My account: #506 - /my-account/
Terms and conditions: #579 - /terms-and-conditions/

### Theme ###

Name: North Child Theme
Version: 1.0.0
Author URL: http://themeforest.net/user/fuelthemes
Child Theme: ✔
Parent Theme Name: North
Parent Theme Version: 5.5.2.1
Parent Theme Author URL: http://themeforest.net/user/fuelthemes
WooCommerce Support: ✔

### Templates ###

Overrides: north-wp/woocommerce/archive-product.php
north-wp/woocommerce/cart/cart-empty.php
north-wp/woocommerce/cart/cart.php
north-wp/woocommerce/checkout/form-checkout.php
north-wp/woocommerce/checkout/form-coupon.php
north-wp/woocommerce/checkout/form-login.php
north-wp/woocommerce/content-product.php
north-wp/woocommerce/content-product_cat.php
north-wp/woocommerce/content-single-product.php
north-wp/woocommerce/global/wrapper-end.php
north-wp/woocommerce/global/wrapper-start.php
north-wp/woocommerce/loop/loop-end.php
north-wp/woocommerce/loop/loop-start.php
north-wp/woocommerce/myaccount/form-login.php
north-wp/woocommerce/myaccount/navigation.php
north-wp/woocommerce/product-searchform.php
north-wp/woocommerce/single-product/add-to-cart/variable.php
north-wp/woocommerce/single-product/product-image.php
north-wp/woocommerce/single-product/product-thumbnails.php
north-wp/woocommerce/single-product/tabs/tabs.php
north-wp/woocommerce/single-product-reviews.php


### WooCommerce Google Product Feed fields ###

Product description: Main product description (full preferred) plus variation description.
Availability: Defaults to "in stock".
Brand: Defaults to "Sam & Sage".
Product Type: Pre-populates from product_cat taxonomy.
Google Product Category: Defaults to "Apparel & Accessories > Clothing > Baby & Toddler Clothing".
Gender: Defaults to "unisex".
Age Group: 
Colour: Pre-populates from pa_colour taxonomy.
Size: Pre-populates from pa_size taxonomy.
Size system: 
Bing Category: Defaults to "Baby & Children's Clothing". Pre-populates from product_cat taxonomy.

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No
debug_key: 1a57c9ec-fe8b-4147-a321-bb0600a19ee7

### Gift Cards ###

Database Version: 1.3.5
Loopback Test: ✔
Task Queueing Test: ✔

### Action Scheduler ###

Complete: 4,623
Oldest: 2020-09-18 12:43:00 +0000
Newest: 2020-10-19 12:38:35 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 2
Oldest: 2020-10-19 12:44:30 +0000
Newest: 2020-10-19 12:53:35 +0000

`
```
</details>

**Comment by tammullen** [comment] 2020-10-22 15:57
Hi @Zedys 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

First of all with a variation with `0` stock and `Hide out of stock items from the catalog` unticked
![Screenshot 2020-10-22 at 16 49 19](https://user-images.githubusercontent.com/24649833/96897487-8e451f80-1486-11eb-9c66-0bcab6800a6f.png)


![Screenshot_2020-10-22_at_16_35_13](https://user-images.githubusercontent.com/24649833/96896943-05c67f00-1486-11eb-88f6-f4775d1f4c69.png)
This is what I see with Storefront theme

![Screenshot 2020-10-22 at 16 41 38](https://user-images.githubusercontent.com/24649833/96897053-2393e400-1486-11eb-9f8e-9a3b73ca06f4.png)
I see the same thing for Twenty Twenty theme

> If 'Hide out of Stock' is deselected, then products which are completely out of stock in all variations, etc. become visible in the catalogue again.

> text 'OUT OF STOCK' is now displayed.

> Add to Cart' button is not selectable

It sounds like you are seeing the same thing with North Theme


Now I will tick `Hide out of stock items from the catalog`

![Screenshot 2020-10-22 at 16 50 49](https://user-images.githubusercontent.com/24649833/96897684-c4829f00-1486-11eb-9d37-8c9619232405.png)
 
![Screenshot_2020-10-22_at_16_34_47](https://user-images.githubusercontent.com/24649833/96897712-cfd5ca80-1486-11eb-823f-e2e805d7e64c.png)
This is what I see with Storefront theme

![Screenshot 2020-10-22 at 16 40 17](https://user-images.githubusercontent.com/24649833/96897762-dbc18c80-1486-11eb-8c60-d037838278e2.png)
I see the same thing for Twenty Twenty theme

> When storefront theme is enabled, only a drop-down option is available for variations. If 'hide out of stock' is enabled, then only the products in-stock are dispalyed.

It sounds like you are seeing the same thing with Storefront Theme

> If 'Out of Stock Visibility' is selected, the swatch/product variation is not hidden and no "Out of Stock" message is displayed. Only 'Add to Cart' button is not selectable in both instances.

However you are not seeing the variation hidden with North Theme

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party theme "North" 
​
Please contact the author of the theme directly for further help. 

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-10-22 15:57 UTC
