### ISSUE TITLE
Variation meta data do not update correctly when modifying attributes

### ISSUE THREAD

**Issue by jimjasson** [woocommerce/woocommerce#24598] opened 2019-09-09 11:15 UTC
**Describe the bug**

If you create a Variable Product with some attributes and 'Any..' variations and then update the attributes by changing their name/values or by adding new ones, the attribute-related meta data of each variation will not update in the database as well. 

**To Reproduce**
1. Create a new Variable Product.
2. Add one new custom attribute, for example _Color_, and add some attributes: https://cl.ly/89afd5e3ff83
3. Add one variation with 'Any..' selected: https://cl.ly/ed1e617362ae.
4. Add a price to this variation. 
5. Save the product. 
6. Navigate to your database and open the `wp_postmeta` table. 
7. Search for all entries with ID equal to the variation ID you previously created.
8. See that the _Color_ attribute shows up as expected: https://cl.ly/defc0edb627e.
9. Navigate back to the Variable Product. 
10. Rename the _Color_ attribute to _Size_ and update its values: https://cl.ly/548134478a4d.
11. Update the Variable Product. 
12. Move back to the database and search again for all entries with ID equal to the variation ID.
13. See that the _Color_ attribute still shows up -- the _Size_ attribute should show up instead.

**Expected behavior**
When the variation attributes are updated in the Variable Product edit page, then the variation meta data should update in the database as well.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WordPress address (URL): http://somewherewarm.test/support
Site address (URL): http://somewherewarm.test/support
WC Version: 3.7.0
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

**Server Environment**

Server Info: nginx/1.13.2
PHP Version: 7.1.6-1~ubuntu16.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18-0ubuntu0.16.04.1
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Database**

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 14.65MB
Database Data Size: 9.46MB
Database Index Size: 5.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.48MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 1.02MB + Index: 0.11MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.19MB + Index: 0.25MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.02MB + Index: 0.08MB
wp_postmeta: Data: 2.17MB + Index: 2.66MB
wp_posts: Data: 0.44MB + Index: 0.17MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

**Post Type Counts**

attachment: 39
custom_css: 1
customize_changeset: 3
nav_menu_item: 5
page: 30
post: 1
product: 75
product_variation: 79
revision: 129
scheduled-action: 109
shop_coupon: 3
shop_order: 195
shop_order_refund: 2

**Security**

Secure connection (HTTPS): ❌
Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

**Active Plugins (2)**

Query Monitor: by John Blackbourn – 3.3.7
WooCommerce: by Automattic – 3.7.0

**Inactive Plugins (0)**

**Dropin Plugins (1)**

db.php: Query Monitor Database Class

**Settings**

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types:
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

**WC Pages**

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page visibility should be public

**Theme**

Name: Storefront
Version: 2.4.3 – 2.5.1 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

**Templates**

Overrides: –

**Action Scheduler**

Complete: 69
Oldest: 2019-08-08 10:40:42 +0000
Newest: 2019-09-07 12:58:08 +0000

Pending: 0
Oldest: -
Newest: -

Canceled: 0
Oldest: -
Newest: -

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by claudiosanches** [comment] 2019-10-01 20:31
> If you create a Variable Product with some attributes and 'Any..' variations and then update the attributes by changing their name/values or by adding new ones, the attribute-related meta data of each variation will not update in the database as well.

It's made by design, we are thinking in ways to improve performance of variable products, so maybe this will get revised soon.
For now I'll close it as `won't fix`, but I'll revise it when we try improve variable products performance.

**Comment by claudiosanches** [comment] 2019-10-01 20:32
Also we are working to create flat tables for products, we could address it there as well.
But as I said, I'll close for now.

**Closed by claudiosanches** 2019-10-01 20:32 UTC
