### ISSUE TITLE
Negative stock when placing two orders at the same time

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce#24782] opened 2019-10-08 13:08 UTC
**Describe the bug**
This was originally described here: https://github.com/woocommerce/woocommerce/issues/22521
This was the supposed fix: https://github.com/woocommerce/woocommerce/pull/22646

I'm opening this to avoid discussion on a closed issue. I do not think this issue has been resolved, but I could be wrong.

I got a report here: https://wordpress.org/support/topic/product-back-order-issue-2/#post-12008452

The difference between this issue and [this issue](https://github.com/woocommerce/woocommerce/issues/22118) is that the current problem revolves around placing multiple orders simultaneously from separate devices or browsers.
When placing these multiple orders, the orders will all go through, resulting in a negative stock, even when backorders are disabled.

**To Reproduce**
1. Disable backorders/negative stock
2. Give the product a stock of `1`
2. Place an order from two separate devices or browsers at the same time
3. See that the stock value is reduced to `-1`

**Expected behavior**
I'm not a developer, so I can't decipher how this should be working. I would assume that there would be some sort of 'queue' for placing orders at the same time, but I don't really know if that something that's even possible.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WP Version: 5.2.3
WC Database Version: 3.7.0
WooCommerce: by Automattic – 3.7.0
```

</details>

**Comment by juliaamosova** [comment] 2019-10-10 12:32
Hi @jrick1229, thanks for reporting the issue on behalf of the customer! 

However, I can't reproduce it. 

I've tried 2 scenarios:
<hr>
1) Placing the order at the same time in 2 different browsers (Chrome & Safari):

Here are the 2 orders about to be placed for the same item which stock is at `1` with backorders not allowed:

![browsers_side_by_side](https://user-images.githubusercontent.com/19143190/66568064-7e4eec00-eb60-11e9-8d45-6d1d855c2039.jpg)

As a result, the order in Chrome went through but I received a message about insufficient stock in Safari:

![order_received_side_by_side](https://user-images.githubusercontent.com/19143190/66568113-9aeb2400-eb60-11e9-93bf-22eb83b81ef7.jpg)
<hr>
2) Next, I placed the order for the same item in Chrome desktop and my Android device:

Mobile device - order is about to be placed:

![mobile_order to be placed](https://user-images.githubusercontent.com/19143190/66568658-d0dcd800-eb61-11e9-8e30-8f4ac826b526.jpg)

Mobile device - order received:

![mobile_order_received](https://user-images.githubusercontent.com/19143190/66568684-dc300380-eb61-11e9-89db-5112a02b01db.jpg)

Desktop Chrome - received a message about insufficient stock:

![desktop_order_didn't_go_through](https://user-images.githubusercontent.com/19143190/66568750-fbc72c00-eb61-11e9-85a9-0d31cf9fe5d9.jpg)

<hr>

The stock was changed to `0` (zero) in both cases on the back-end. 

Are you able to reproduce it yourself?

My testing env:

- WP - 5.2.3
- WC - 3.7.0
- PHP - 7.2.23

**Comment by smartstak** [comment] 2019-10-10 13:42
Hello. 

We also have this issue on our sites.

**Comment by juliaamosova** [comment] 2019-10-11 10:50
@smartstak can you please confirm the following:

- You have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- You can reproduce this bug consistently using the steps above.

Also, please provide us with your System Status Report. You can copy and paste the system status report from **WooCommerce > System Status** section of your site.

**Comment by vedanshujain** [comment] 2019-10-14 20:37
Closing as duplicate #24009 . This has been on my radar to fix for a while now, and I am currently working on a POC. Hopefully, it will be ready and land in the next version.

**Closed by vedanshujain** 2019-10-14 20:37 UTC
Labels: status: needs feedback
