### ISSUE TITLE
In progress order screen remarkably compressed to the point of being completely unreadable

### ISSUE THREAD

**Issue by arooni** [woocommerce/woocommerce#23826] opened 2019-05-28 00:57 UTC
**To Reproduce**
0. Ensure you only have woocommerce and a default theme active.  
0.5 my product name is quite long and I'm sure that's part of it. 
1.Create a few test orders that result in showing pending status. 
2. Click Order status 
3. see the following 

![Screenshot from 2019-05-27 19-44-18](https://user-images.githubusercontent.com/556667/58443676-1f10a380-80b9-11e9-8d1c-22d43a4db0f1.png)

**Screenshots**

**Expected behavior**
Be able to read the order status screen.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.magicpresspass.com
Site address (URL): https://www.magicpresspass.com
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.8
PHP Version: 7.0.33-0ubuntu0.16.04.4 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.26-0ubuntu0.16.04.1
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 17.34MB
Database Data Size: 15.46MB
Database Index Size: 1.88MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_em_modals: Data: 0.02MB + Index: 0.00MB
wp_em_modal_metas: Data: 0.02MB + Index: 0.00MB
wp_em_themes: Data: 0.02MB + Index: 0.00MB
wp_em_theme_metas: Data: 0.02MB + Index: 0.00MB
wp_ewwwio_images: Data: 0.14MB + Index: 0.08MB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB
wp_fca_eoi_activity: Data: 0.02MB + Index: 0.05MB
wp_itsec_distributed_storage: Data: 5.02MB + Index: 0.02MB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_logs: Data: 1.02MB + Index: 0.09MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 6.05MB + Index: 0.08MB
wp_phppc_functions: Data: 0.02MB + Index: 0.02MB
wp_popup_manager: Data: 0.02MB + Index: 0.00MB
wp_popup_manager_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 0.48MB + Index: 0.16MB
wp_posts: Data: 1.52MB + Index: 0.06MB
wp_sp_email_logs: Data: 0.02MB + Index: 0.02MB
wp_stb_styles: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 106
customize_changeset: 1
jetpack_migration: 2
mc4wp-form: 1
page: 14
post: 1
product: 2
revision: 88
scheduled-action: 17
shop_coupon: 4
shop_order: 26
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.3 – 3.6.4 is available

### Inactive Plugins (43) ###

AffiliateWP: by AffiliateWP
LLC – 2.1.15

AffiliateWP - Affiliate Area Shortcodes: by AffiliateWP
LLC – 1.1.7

AffiliateWP - Affiliate Area Tabs: by AffiliateWP – 1.2.7
AffiliateWP - Affiliate Info: by AffiliateWP
LLC – 1.0.5

AffiliateWP - Affiliate Product Rates: by Pippin Williamson and Andrew Munro – 1.0.5.1
AffiliateWP - Allowed Products: by AffiliateWP
LLC – 1.1.2

AffiliateWP - Allow Own Referrals: by AffiliateWP
LLC – 1.0.2

AffiliateWP - Checkout Referrals: by AffiliateWP – 1.0.7
AffiliateWP - Force Pending Referrals: by AffiliateWP – 1.0
AffiliateWP - Leaderboard: by Pippin Williamson and Andrew Munro – 1.0.2
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.5
AffiliateWP - Pushover Notifications: by Chris Klosowski – 1.0.2
AffiliateWP - Show Affiliate Coupons: by AffiliateWP – 1.0.7
AffiliateWP - Sign Up Bonus: by Pippin Williamson and Andrew Munro – 1.1
AffiliateWP - WooCommerce Redirect Affiliates: by AffiliateWP – 1.0 – Not tested with the active version of WooCommerce
Analytify - Google Analytics Dashboard: by Analytify – 2.2.12
Disable Comments: by Samir Shah – 1.9.0
EWWW Image Optimizer: by Exactly WWW – 4.7.4
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.8
Google Tag Manager for Wordpress: by Thomas Geiger – 1.9.2 – Not tested with the active version of WooCommerce
Health Check & Troubleshooting: by The WordPress.org community – 1.3.2
Insert Headers and Footers: by WPBeginner – 1.4.4
iThemes Security: by iThemes – 7.3.3
Kadence Toolkit: by Kadence Themes – 4.9.2
Lazy Load for Videos: by Kevin Weber – 2.7.3
MailChimp Forms by MailMunch: by MailMunch – 3.1.3
Mailchimp for WordPress: by ibericode – 4.5.2
Mailjet for WordPress: by Mailjet SAS – 5.1.0
MainWP Child: by MainWP – 3.5.7
PHP Compatibility Checker: by WP Engine – 1.4.7
Preview E-mails for WooCommerce: by Digamber Pradhan – 1.5.1
Query Monitor: by John Blackbourn – 3.3.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Save with keyboard: by Mattia Trapani (zupolgec)
Ron Valstar (sjeiti) – 3.0.2

Theme Check: by Otto42
pross – 20190208.1

TinyMCE Advanced: by Andrew Ozz – 5.2.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.14

W3 Total Cache: by Frederick Townes – 0.9.7.4
WebP Express: by Bjørn Rosell – 0.13.2
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.1.0
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
wpautop-control: by Rowan Rodrik van der Molen
Jesse Jacobsen <jmatjac@gmail.com>. – 1.6

Yoast SEO: by Team Yoast – 11.2.1 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.6.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #182 - /terms/

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 17
Oldest: 2019-05-17 22:53:17 +0000
Newest: 2019-05-23 23:36:01 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –


Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by arooni** [comment] 2019-05-28 00:58
Viewing the admin interface with brave browser (ad blocker turned off on my site) on Ubuntu 18.04 (screen solution at 1600x900)

**Comment by claudiosanches** [comment] 2019-05-30 15:37
>  0.5 my product name is quite long and I'm sure that's part of it.

How long? Can you give some example?

**Comment by arooni** [comment] 2019-05-30 22:07
@claudiosanches ; sure; the product name was listed as: "Magic Press Pass - Official Website | Save money everyday | Stop paying admission at clubs, museums, events, and more..."

For fun I tried temporarily changing the product name to just "Magic Press Pass" and yet I still see this behavior.  

In addition, it seems the prodcut screen is also messed up in some capacity.

![Screenshot from 2019-05-30 17-07-05](https://user-images.githubusercontent.com/556667/58668059-65564480-82fd-11e9-92f9-8d9ca3a63a29.png)

**Comment by claudiosanches** [comment] 2019-06-02 21:38
Not able to reproduce, seems like is some plugin, maybe one of that is including Analytics and more there, try to disable those columns and see if sort this problem.

But see how works for me:
![Screenshot from 2019-06-02 18-36-38](https://user-images.githubusercontent.com/1264099/58767674-65f11400-8565-11e9-8289-f8f49482d6fe.png)

Please post back if you can provide more details on how to reproduce this issue, in case is really on WooComemrce and not caused by a 3rd party plugin. For now, I’m am closing this as non-reproducable.

**Closed by claudiosanches** 2019-06-02 21:38 UTC
Labels: status: needs feedback

**Comment by claudiosanches** [comment] 2019-06-02 21:40
Also including a screenshot with with less width:
![Screenshot from 2019-06-02 18-39-06](https://user-images.githubusercontent.com/1264099/58767702-bd8f7f80-8565-11e9-9f26-74e2081d7768.png)
