### ISSUE TITLE
User "Display name publicly as" is changed on order

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#15020] opened 2017-05-10 20:37 UTC
When a user of the site completes an order, their First and Last name are changed, but also the "Display name publicly as" setting is changed.

Is this intended behavior?

To replicate

1) User settings, name set to be `joelwills` withe First Name as `Joel Real Name`

![Screenshot](http://joelwills.com/5fStq+)

Link to image: http://joelwills.com/5fStq

2) "Display name publicly as" appears publicly in reviews e.g:

![Screenshot](http://joelwills.com/mvXlG+)

Link to image: http://joelwills.com/mvXlG

3) Make an order. I used the first name `test` and last name `erwre`.

4) In my profile, my first and last name have updated, but also "Display name publicly as" is now changed to the name used in the order rather that the previous setting of username:

![Screenshot](http://joelwills.com/DJfKl+)

Link to image: http://joelwills.com/DJfKl

5) If you then add a new review it then used your new display name. The previous review is unchanged:

![Screenshot](http://joelwills.com/kYseu+)

Link to image: http://joelwills.com/kYseu

This is changing the name without explicit permission, potentially affecting privacy. Is this intended behavior?

The account details of a Customer user role can't change the "Display name publicly as", but other roles can and yet it is changed when making an order. 

Thanks for your input.

573492-zd-woothemes

**Comment by mikejolley** [comment] 2017-05-11 11:12
It's mainly to stop emails being used as display name when checking out without a 'username' field.

**Comment by tempbird** [comment] 2017-05-11 18:08
I'm following this thread and i don't understand why this was changed as it was good before.
Customers may complain about leaking their data. Take an adult site for example.
This makes the function user displayname complete useless.

Do you have any idea when we can expect a fix for this?

**Comment by AnwerAR** [comment] 2017-05-15 23:37
Is it necessary to display user name input fields in billing section if user is already logged in while checking out?

**Comment by Magine** [comment] 2017-05-17 20:45
Have subscribed to this thread. 
Am having the exact same issue and it doesn't make sense. 
My client is definitely not liking this as their customer's display name is the company name. But now after every order the display name changes back to the customers first/last name... This doesn't work for them as the online shop/catalog is for B2B, so the customers are sorted by company name and not first/last name.
Please can this be changed back.

**Comment by JHPBellevue** [comment] 2017-05-18 12:41
We are also struggling with this issue, and we could effectively be leaking personal data.

Has anyone identified a hook or a quickfix one can do to get around it in the short term?

**Comment by tempbird** [comment] 2017-05-22 16:17
Why is there still no feedback?
At least confirm the issue and let us know if you're into it.

Data leaks like this is a violence by law in Europe.

**Comment by mikejolley** [comment] 2017-05-23 08:00
The issue is open. It will be looked at.

**Comment by JHPBellevue** [comment] 2017-05-23 08:10
Until a proper fix or workaround is available, we were able to temporarily fix this by simply commenting out $customer->save() at wp-content/plugins/woocommerce/includes/class-wc-checkout.php:885

This works for our users, YMMV.

**Comment by tempbird** [comment] 2017-05-23 12:55
Hi JHPBellevue, Thank you so much!
Looking forward to have this definitely fixed.

**Comment by Magine** [comment] 2017-05-23 15:14
Tx JHPBellevue. The temporary fix seems to work :)
Tx mikejolley.

**Comment by ryelle** [comment] 2017-05-23 15:45
I'm looking at this now, but for anyone that needs a faster fix, you can disable the customer data update by adding this line to your theme or creating a really simple plugin, rather than editing WooCommerce directly:

```php
add_filter( 'woocommerce_checkout_update_customer_data', '__return_false' );
```

**Closed** 2017-05-24 18:20 UTC
Labels: Good first patch, Question, Release: Minor, Type: Enhancement

**Comment by tempbird** [comment] 2017-06-18 09:38
It's been a couple weeks including an official update but without this being fixed...

Please also note when setting an order to complete status, the username also changes.
For orders with virtual/downloadable items the order gets automaticly a completed status.

Is there a temporary fix for order status set to complete -> do not update customer data?
Thanks in advance.

**Comment by wslover317** [comment] 2017-06-19 07:58
Commenting to follow. I need this fix as well please

**Comment by mikejolley** [comment] 2017-06-19 10:59
> Is there a temporary fix for order status set to complete -> do not update customer data?
Thanks in advance.

@ryelle posted a fix the comment above yours. Please read the entire thread before chiming in, thanks :)
