### ISSUE TITLE
Fatal error after upgrade woocommerce

### ISSUE THREAD

**Issue by tlqmhs** [woocommerce/woocommerce#21676] opened 2018-10-25 16:43 UTC
After upgrade woocommerce, there's a fatal error. Messagecopied and paste here: 
Fatal error: Class 'WC_Integration' not found in /home/coolin6/public_html/myheatsinks.com/store/wp-content/plugins/woocommerce-shipstation-integration/includes/class-wc-shipstation-integration.php on line 10

This make me unable to login to admin dashboard anymore, and can't get Website Status Report to submit a Support Request on woocommerce.com

**Comment by rodrigoprimo** [comment] 2018-10-25 19:59
I was not able to reproduce this issue, but there is a chance I missed something as I'm not familiar with WooCommerce Shipstation. There is another report of the same problem here:

https://wordpress.org/support/topic/php-fatal-error-upon-upgrade-to-woocommerce

I asked the team that maintains this extension to take a look, and I also asked WooCommerce.com support what is the best way for you to get in touch with them since you can't get your status report. I will update this issue when I hear back.

**Comment by tlqmhs** [comment] 2018-10-25 20:19
Found another report under the topic I posted, 
https://wordpress.org/support/topic/fatal-error-after-upgrade-woocommerce/

**Comment by c-shultz** [comment] 2018-10-25 20:46
I was also not able to reproduce the issue.

**Comment by splaquet** [comment] 2018-10-26 02:09
I submitted one of the Fatal Error reports on the WordPress plugin page.  Fortunately, I first activated the plugin on a /dev site. I disabled the plugin to resume working on the site. 

Also worth noting, that line was the *only* error that was posted into the error log. 

Here's some background on my install:
- multisite sub-domain install
- WooGlobalCart
- WooMultiSite

Those are the only non-standard elements I can think of. The rest of the plugins are widely used. I can submit a full list of extensions, if needed.

**Comment by jobthomas** [comment] 2018-10-27 11:34
Another one: 1519116-zen - also wasn't able to reproduce

Tested:

* Used WC3.4.3 and latest version of ShipStation
* Then updated WC to 3.5.0 without problem

**Comment by jobthomas** [comment] 2018-10-29 08:07
@rodrigoprimo and @c-shultz - @splaquet left a good comment here: https://wordpress.org/support/topic/php-fatal-error-upon-upgrade-to-woocommerce/#post-10825090

**Comment by splaquet** [comment] 2018-10-29 16:44
not sure if this is relevant or not… but, i saw that my child theme had out of date woocommerce templates (was actually the parent theme). i went to see which files were outdated and saw several several database warnings, “Table does not exist”. I’m not sure if this is an actual error or an oversight on the update.

So, i went to disable WooCommerce, thinking that network reactivating it would rebuild those missing tables. upon deactivation of WooCommerce, the site crashed again. (due to shipstation not auto-deactivating). I renamed the shipstation plugin folder, got the site back up, reactivated WooCommerce, then reactivated shipstation.

everything was back up and works again, but those table errors are still present in all of my subsites’ WooCommerce status pages.

`Total  Database Size	 		 	 			12.78MB
Database Data Size	 		 	 			11.82MB
Database Index Size	 		 	 			0.96MB
hlmu_4_woocommerce_sessions	 	 			Table does not exist
hlmu_4_woocommerce_api_keys	 	 			Table does not exist
hlmu_4_woocommerce_attribute_taxonomies	 	 Table does not exist
hlmu_4_woocommerce_downloadable_product_permissions	 	 Table does not exist
hlmu_4_woocommerce_order_items	 	 		Table does not exist
hlmu_4_woocommerce_order_itemmeta	 		Data: 0.02MB + Index: 0.03MB
hlmu_4_woocommerce_tax_rates	 	 			Table does not exist
hlmu_4_woocommerce_tax_rate_locations	 	 	Table does not exist
hlmu_4_woocommerce_shipping_zones	 	 	Table does not exist
hlmu_4_woocommerce_shipping_zone_locations	 	 Table does not exist
hlmu_4_woocommerce_shipping_zone_methods	 	 Table does not exist
hlmu_4_woocommerce_payment_tokens	 	 	Table does not exist
hlmu_4_woocommerce_payment_tokenmeta	 	Data: 0.02MB + Index: 0.03MB
hlmu_4_woocommerce_log	 	 				Table does not exist
hlmu_4_commentmeta	 						Data: 0.02MB + Index: 0.03MB
hlmu_4_comments	 							Data: 0.02MB + Index: 0.09MB
hlmu_4_links	 								Data: 0.02MB + Index: 0.02MB
hlmu_4_options	 							Data: 1.11MB + Index: 0.05MB
hlmu_4_postmeta	 							Data: 2.52MB + Index: 0.25MB
hlmu_4_posts	 								Data: 0.23MB + Index: 0.06MB
hlmu_4_termmeta	 							Data: 0.02MB + Index: 0.03MB
hlmu_4_terms	 								Data: 0.02MB + Index: 0.03MB
hlmu_4_term_relationships	 					Data: 0.02MB + Index: 0.02MB
hlmu_4_term_taxonomy	 						Data: 0.02MB + Index: 0.03MB
hlmu_4_woocommerce_bundled_itemmeta	 		Data: 0.02MB + Index: 0.03MB
hlmu_blogs	 								Data: 0.02MB + Index: 0.03MB
hlmu_blog_versions	 						Data: 0.02MB + Index: 0.02MB
hlmu_registration_log	 						Data: 0.02MB + Index: 0.02MB
hlmu_signups	 								Data: 0.02MB + Index: 0.06MB
hlmu_site	 									Data: 0.02MB + Index: 0.02MB
hlmu_sitemeta	 							Data: 7.20MB + Index: 0.03MB
hlmu_usermeta	 							Data: 0.44MB + Index: 0.03MB
hlmu_users	 								Data: 0.02MB + Index: 0.05MB`

![woocommerce_missingtables](https://user-images.githubusercontent.com/6146508/47665653-f6064f80-db77-11e8-9b8a-6d68bdbed8a3.jpg)

**Comment by c-shultz** [comment] 2018-10-29 17:22
@splaquet, thanks for the details. I have raised an issue with the Shipstation extension to deactivate gracefully when WooCommerce is deactivated.

**Comment by claudiosanches** [comment] 2018-11-05 20:06
Closing since sounds like an issue on Shipstation extension.

**Closed by claudiosanches** 2018-11-05 20:06 UTC
