### ISSUE TITLE
Variation Selection of Attributes Not Updating

### ISSUE THREAD

**Issue by t3chlady** [woocommerce/woocommerce#27328] opened 2020-08-13 19:18 UTC
Using a URL similar to this:   https://www.store.com/wp-json/wc/v3/products/9999/variations/1111

And Data in the body:
{
    "attributes": [
        {
            "id": 2,
            "name":"Color",
            "option":"SOFT BEIGE"
        }
    ]
}

Does not populate the array of selected attributes for the variation.  Attributes always comes back empty.
We have been manually selecting the correct attribute in the user interface from the management module in Woo Commerc

  "attributes": [],
    "menu_order": 0,
    "meta_data": [],

What am I missing?  Or doing wrong?

**Comment by t3chlady** [comment] 2020-08-13 19:19
Have tested with PUT and when that failed, tried POST but neither works.

**Comment by tammullen** [comment] 2020-10-22 19:29
Hi @t3chlady 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-10-22 19:29 UTC
