### ISSUE TITLE
Problem with applying coupon to products in cart, when setting products applicable and minimum order value

### ISSUE THREAD

**Issue by rogoszmaciej** [woocommerce/woocommerce#18541] opened 2018-01-19 17:25 UTC
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Create new coupon in WooCommerce
2. Set 100% discount
3. Set no usage limits
4. Set coupon to apply only to 1 product in cart
5. Choose products that coupon i applicable to
6. Set minimum order value to be able to use the coupon
7. No max. order value
8. save

## Expected/actual behavior

When  clients (not registered) try to apply coupon, when their carts are matching requirements they only see warning woocommerce notice: "Mimimum order value for this coupon is xxxUSD".
Funny thing is, when I log in to my admin account, everything works just fine.

The coupon is expected to work regardless someone is logged in...

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://sklep.missplanner.pl
Site URL: https://sklep.missplanner.pl
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.2d

SUHOSIN Installed: ✔
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ❌ Domyślna strefa czasowa to Europe/Warsaw - powinna być UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: mp_
MaxMind GeoIP Database: ✔
Całkowity rozmiar bazy danych: 177.78MB
Rozmiar bazy danych: 148.12MB
Rozmiar indeksu bazy danych: 29.66MB
mp_woocommerce_sessions: Dane: 98.27MB + Indeks: 1.52MB
mp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
mp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
mp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.03MB
mp_woocommerce_order_items: Dane: 1.52MB + Indeks: 0.27MB
mp_woocommerce_order_itemmeta: Dane: 6.52MB + Indeks: 5.03MB
mp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
mp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.05MB
mp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
mp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.05MB
mp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
mp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
mp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
mp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
mp_aiowps_events: Dane: 0.02MB + Indeks: 0.00MB
mp_aiowps_failed_logins: Dane: 0.02MB + Indeks: 0.00MB
mp_aiowps_global_meta: Dane: 0.02MB + Indeks: 0.00MB
mp_aiowps_login_activity: Dane: 0.09MB + Indeks: 0.00MB
mp_aiowps_login_lockdown: Dane: 0.02MB + Indeks: 0.00MB
mp_aiowps_permanent_block: Dane: 0.02MB + Indeks: 0.00MB
mp_commentmeta: Dane: 0.06MB + Indeks: 0.03MB
mp_comments: Dane: 2.52MB + Indeks: 1.44MB
mp_links: Dane: 0.02MB + Indeks: 0.02MB
mp_options: Dane: 14.36MB + Indeks: 1.02MB
mp_postmeta: Dane: 15.30MB + Indeks: 14.91MB
mp_posts: Dane: 6.30MB + Indeks: 0.80MB
mp_termmeta: Dane: 0.02MB + Indeks: 0.03MB
mp_terms: Dane: 0.02MB + Indeks: 0.03MB
mp_term_relationships: Dane: 0.14MB + Indeks: 0.08MB
mp_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB
mp_usermeta: Dane: 2.48MB + Indeks: 4.00MB
mp_users: Dane: 0.16MB + Indeks: 0.14MB

### Post Type Counts ###

allegro_auction: 58
allegro_pricelist: 2
attachment: 434
envira: 1
inspire_invoice: 172
kk_package_template: 1
nav_menu_item: 32
oembed_cache: 1
page: 21
post: 2
product: 173
promocja: 14
revision: 140
safecss: 1
shop_coupon: 11
shop_order: 2733
shop_order_refund: 6
shop_webhook: 1
testimonial: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Advanced Cron Manager: przez underDEV – 2.3.0
All In One WP Security: przez Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.1

Contact Form 7: przez Takayuki Miyoshi – 4.8.1
Facebook for WooCommerce: przez Facebook – 1.3.3 – Nietestowane z używaną wersją WooCommerce
Faktury dla WordPressa: przez WP Desk – 3.7.1
Flexible Shipping PRO: przez WP Desk – 1.5.1
Flexible Shipping: przez WP Desk – 1.9.12
Korporacja Kurierska - Metoda wysyłki: przez Korporacja Kurierska – 2.1.1 – Nietestowane z używaną wersją WooCommerce
P3 (Plugin Performance Profiler): przez GoDaddy.com – 1.5.3.9
Odnawianie miniaturek: przez Alex Mills (Viper007Bond) – 3.0.1
RSS Importer: przez wordpressdotorg – 0.2
User Role Editor: przez Vladimir Garagulya – 4.36.1
WooCommerce Aktywne Płatności: przez WP Desk – 3.1 – Nietestowane z używaną wersją WooCommerce
WooCommerce Allegro: przez WP Desk – 2.2
WooCommerce eNadawca Poczta Polska: przez WP Desk – 1.5.5
WooCommerce Flexible Pricing: przez WP Desk – 1.1 – Nietestowane z używaną wersją WooCommerce
WooCommerce Dotpay: przez WP Desk – 2.3 – Nietestowane z używaną wersją WooCommerce
WooCommerce Paczkomaty InPost: przez WP Desk – 3.1.1 – Nietestowane z używaną wersją WooCommerce
WooCommerce: przez Automattic – 3.2.6
WP Mail SMTP: przez WPForms – 1.2.2
WP Desk Helper: przez WP Desk – 1.3.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-2)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)

### WC Pages ###

Strona sklepu: #4 - /wszystkie-produkty/
Koszyk: #5 - /koszyk/
Zamówienie: #6 - /zamowienia/
Moje konto: #7 - /moje-konto/
Regulamin: #537 - /regulamin-sklepu/

### Theme ###

Name: Miss Planner Official
Version: 1.0.0
Author URL: https://www.rogoszconsulting.pl/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: missplanner-official/archive-product.php
missplanner-official/content-product.php
missplanner-official/single-product.php

`
</details>

**Comment by claudiulodro** [comment] 2018-01-19 21:29
I tested with the following settings:
- 100% off coupon
- $100 minimum spend
- Limit usage to 1 item
- Only applies to Belt ($55) and Sunglasses ($90) items.

And tested while logged out and everything works great. 

1. I see in the system status report you have a bunch of WooCommerce extensions active. Have you confirmed the bug happens on a site with no plugins except WooCommerce by itself? If not, then the problem is likely one of your other plugins.
2. Are you sure the total value of the products is enough to meet the minimum spend for the coupon? :)

Closing this since it can't be reproduced.

**Closed by claudiulodro** 2018-01-19 21:29 UTC

**Comment by cchandra** [comment] 2018-06-21 02:02
Hi I am also having this exact same problem, did anyone find a solution? did you have the wp install on a sub directory?

**Comment by rogoszmaciej** [comment] 2018-06-24 08:55
Hi! Unfortunately I wasn't able to find the solution, if You have any clues, please share, I'll try to look into it on our test install.
Yes, all our installs are on sub directories, no exceptions.
Cheers!

**Comment by andrewmclagan** [comment] 2018-07-20 03:42
We had the same issue, it was caused by [woocommerce-dynamic-pricing](https://github.com/wp-premium/woocommerce-dynamic-pricing) plugin. Update this plugin and it should resolve the issue. Although as the current wordpress plugins are able to cause multiple conflicts (we needs some way to prevent this) it could also be another plugin in your case.
