### ISSUE TITLE
The "updated_postmeta" Wordpress hook does not fire when the "_product_image_gallery" meta is updated (only in some cases)

### ISSUE THREAD

**Issue by VincenzoDiGaetano** [woocommerce/woocommerce#29955] opened 2021-05-21 09:47 UTC
I'm using the Wordpress `updated_postmeta` hook to automatically update product data across my sites when one or more fields are changed from the product edit page in the WooCommerce backend from a "main" site.

All fields are updated correctly except the `_product_image_gallery` meta _(only in some cases)_.

**Prerequisites**

To make sure that the `updated_postmeta` hook is triggered every time one or more fields are updated I used the following code (which sends an email with the updated post meta, for each one). The following code I added it to the **functions.php** of the active theme:

```
add_action( 'updated_postmeta', 'check_updated_post_meta', 10, 4 );
function check_updated_post_meta( $meta_id, $object_id, $meta_key, $_meta_value ) {

    // skip
    if ( $meta_key == '_edit_lock' ) {
        return;
    }

    // only if the post type is "product"
    if ( get_post_type( $object_id ) != 'product' ) {
        return;
    }

    $subject = "Post meta updated: $meta_key - " . date('Y/m/d H:i:s');

    $body  = '<pre>$meta_id: ' . print_r( $meta_id, true ) . '</pre>';
    $body .= '<pre>$object_id: ' . print_r( $object_id, true ) . '</pre>';
    $body .= '<pre>$meta_key: ' . print_r( $meta_key, true ) . '</pre>';
    $body .= '<pre>$_meta_value: ' . print_r( $_meta_value, true ) . '</pre>';

    $headers = array('Content-Type: text/html; charset=UTF-8');
    wp_mail( $to = array( 'your@email.com' ), $subject, $body, $headers );

}
```
**Actual behavior**
 - When the product has no image in the product gallery and one or more images are added from the product edit page in the WooCommerce backend, **the hook `updated_postmeta` does not trigger**.
 - When the product has one or more images in the product gallery and all are removed from the product edit page in the WooCommerce backend, **the hook `updated_postmeta` does not trigger**.
 - When the product has one or more images in the product gallery and from the product edit page in the WooCommerce backend one or more images are modified and/or added in the product gallery, **the hook `updated_postmeta` is triggered**.

**Expected behavior**
The `updated_postmeta` hook should trigger with any action (add, edit, remove) of one or more images in the product gallery.

**Possible cause**
In the file `includes/admin/meta-boxes/class-wc-meta-box-product-images.php`, in the `output()` method it would appear that the `update_post_meta` function is activated only if the `$attachments` array is not empty.

**Question**
To get the ids of the product gallery images every time which alternative hook can I use?

**Comment by zhongruige** [comment] 2021-05-21 20:33
Hi @VincenzoDiGaetano,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment] 2021-06-22 12:44
Hi @VincenzoDiGaetano 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions.

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel.

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

Meanwhile perhaps you can use `https://developer.wordpress.org/reference/hooks/save_post_post-post_type/` instead.

**Closed by roykho** 2021-06-22 12:44 UTC
Labels: needs developer feedback
