### ISSUE TITLE
other older browsers not load analysis.

### ISSUE THREAD

**Issue by neiji-sly** [woocommerce/woocommerce#18238] opened 2017-12-20 01:21 UTC
There is a bug where i try load the content analysis in my mobile phone(I'm using operamini broswer in Nokia c3) Thanks.

**Comment by claudiosanches** [comment] 2017-12-20 17:01
What content analysis?
It's missing a lot of information on this issue.
There is no steps to reproduce and all issue template has been ignored.
Closing since there is no way to reproduce this issue.

**Closed by claudiosanches** 2017-12-20 17:01 UTC
