### ISSUE TITLE
Issue with cheakout from a LearnPress course

### ISSUE THREAD

**Issue by jrcamarillop** [woocommerce/woocommerce#25424] opened 2020-01-20 01:21 UTC
Hi, I have a problem when trying to collect payments from LearnPress. When the client try to proceed to pay, an error is shown to him. This is a link to the error that is shown to the client [image](https://lh3.googleusercontent.com/RRXTjeamVzQwb1-mS79cFcj8d7W9Iyo18fKbzy9lepKhtqJV_cublK7TmnOlpv8H1J7Oiw6VJHiMggUG6W4sxsaPNau21wRa_vGq5U6Y5yFW4RJjZSVJLM0W8274nJamriZYB9D91bhIPuR3f99ot9BfT6gh5XW3WpfAD5pxn8qGxGfI_fqqk727pRggX4DgAUhqfzo7jZ85jrwkvFaAR8oQMhDHqrXlf7_oOzrVrNys_oIbi6LdZq11_aJFQGSXHRuX38GhSCNZFEpIq99xeUo3tP7PiEvDTh2EHvZC6e792_4e7kS58z4N2MgJ78UDlGOBz51mlqsyfHOkofi_xR1qqP8TRbblocr_qbJL9Cfqu74bY8IAIxMtAfyiv_BLbLvzJuWT4TFjlOJMaetQqFviuJiNilc-hL6jjaOjXMDuC6GM9UF5MZgBfq2JL6Ai22JKqoj32JUX0qk1I-Ez2R2iqFM_bWjM0SN0Gma9G53qOaP9iwBcwRnZdX94Y6Q2wRI-Uf7E8Q7lM7soOlYrqPdzRcGktZkNc_CEKS_Gk2WHb4JIB0LSovk4On07uwHusR4wG3vZ3ckiMZIjbBCu6kbGE9Vl6N0VNhno2fkkMDpTje8ZXPz_pVdscQKYCPoAnfaogKhXdDjQxiIMWn5_IffTDwSSsdTHEtVri9c-4zgUhGBiXu5ASwzG=w607-h533-no).

`This is the status report:
### WordPress Environment ###

WordPress address (URL): https://jrcamarillop.com
Site address (URL): https://jrcamarillop.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_CO
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.26
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.30-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 10.93MB
Database Data Size: 8.64MB
Database Index Size: 2.29MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.27MB + Index: 0.36MB + Engine InnoDB
wp_epayco_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_order_itemmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_question_answermeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_question_answers: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_quiz_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_review_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_sections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_section_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_learnpress_user_itemmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learnpress_user_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_optimizer: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.14MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 0.27MB + Engine InnoDB
wp_posts: Data: 2.48MB + Index: 0.33MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

All-in-One WP Migration: by ServMask – 7.14
Elementor: by Elementor.com – 2.8.4
ePayco WooCommerce: by ePayco – 3.5.4 – Not tested with the active version of WooCommerce
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Elementor - Header, Footer & Blocks: by Brainstorm Force
Nikhil Chavan – 1.2.2

Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack by WordPress.com: by Automattic – 8.1
LearnPress - WooCommerce Payment Methods Integration: by ThimPress – 3.1.9 – Not tested with the active version of WooCommerce
LearnPress: by ThimPress – 3.2.6.5
LiteSpeed Cache: by LiteSpeed Technologies – 2.9.9.2
Mailchimp for WooCommerce: by Mailchimp – 2.3.1
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.7

Ultimate Addons for Gutenberg: by Brainstorm Force – 1.14.6
WooCommerce Admin: by WooCommerce – 0.24.0
WooCommerce PayU Latam Payment Gateway: by PayU Latam – 2.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.8.1
Yoast SEO: by Team Yoast – 12.8.1
WPForms Lite: by WPForms – 1.5.8.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #390 - /productos/
Cart: #391 - /carrito/
Checkout: #392 - /pago/
My account: #393 - /mi-cuenta/
Terms and conditions: #1151 - /terminos-y-condiciones/

### Theme ###

Name: Astra
Version: 2.2.1
Author URL: https://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 713
Oldest: 2019-12-19 21:04:56 -0500
Newest: 2020-01-19 20:11:20 -0500

Pending: 1
Oldest: 2020-01-19 21:02:30 -0500
Newest: 2020-01-19 21:02:30 -0500

Canceled: 40
Oldest: 2019-12-23 23:24:52 -0500
Newest: 2020-01-19 20:10:09 -0500

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

**Comment by tammullen** [comment] 2020-01-20 13:59
Hi @jrcamarillop,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

[Review WooCommerce Self-Service Guide](https://href.li/?https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://href.li/?https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://href.li/?https://wordpress.org/support/plugin/woocommerce/)
If you confirm the bug, please provide us with clear steps to reproduce it and any other details we ask for in the [Bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=4-Bug-report.md&title=).

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-01-20 13:59 UTC
