### ISSUE TITLE
Structured Data Error

### ISSUE THREAD

**Issue by bondimedical3** [woocommerce/woocommerce#24940] opened 2019-10-31 03:48 UTC
**Describe the bug**
An error has appeared for products structured data in Google Search Console 

**To Reproduce**
1. Log into Google Search Console
2. View Products tab

**Screenshots**
![Structured Data](https://user-images.githubusercontent.com/10808588/67917686-e63ba400-fbed-11e9-8a39-eaf08bd64759.jpg)

**Expected behavior**
No errors present in GSC

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.andropenis.com.au
Site address (URL): https://www.andropenis.com.au
WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.66.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.27-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.1
WC Database Prefix: wpto_
MaxMind GeoIP Database: ✔
Total Database Size: 9.42MB
Database Data Size: 8.07MB
Database Index Size: 1.35MB
wpto_woocommerce_sessions: Data: 3.84MB + Index: 0.21MB + Engine MyISAM
wpto_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpto_woocommerce_order_itemmeta: Data: 0.10MB + Index: 0.08MB + Engine MyISAM
wpto_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpto_comments: Data: 0.08MB + Index: 0.05MB + Engine MyISAM
wpto_defender_lockout: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_defender_lockout_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_options: Data: 0.90MB + Index: 0.12MB + Engine MyISAM
wpto_postmeta: Data: 0.57MB + Index: 0.33MB + Engine MyISAM
wpto_posts: Data: 1.84MB + Index: 0.07MB + Engine MyISAM
wpto_redirection_404: Data: 0.51MB + Index: 0.25MB + Engine MyISAM
wpto_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_redirection_items: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wpto_redirection_logs: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wpto_ta_link_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_ta_link_clicks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpto_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpto_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_usermeta: Data: 0.15MB + Index: 0.10MB + Engine MyISAM
wpto_users: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpto_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpto_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpto_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_yoast_seo_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpto_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Advanced noCaptcha & invisible Captcha: by Shamim Hasan – 5.5 – Not tested with the active version of WooCommerce
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.4.1

Contact Form 7: by Takayuki Miyoshi – 5.1.4
Google Tag Manager for Wordpress: by Thomas Geiger – 1.10.1 – Not tested with the active version of WooCommerce
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.3.9.1

Woody ad snippets (PHP snippets | Insert PHP): by Will Bontrager Software
LLC 
Webcraftic  – 2.2.9

Jetpack by WordPress.com: by Automattic – 7.8
Humm / Oxipay Payment Gateway: by FlexiGroup – 1.8.3
Redirection: by John Godley – 4.4.2
Storefront Footer Text: by Wooassist – 1.0.1
Conditional Display for Mobile by WonderPlugin: by Magic Hills Pty Ltd – 1.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17
WooCommerce Stripe Gateway: by WooCommerce – 4.3.0
WooCommerce Price Based on Country (Basic): by Oscar Gare – 1.8.14
WooCommerce Shipment Tracking: by WooCommerce – 1.6.16
WooCommerce: by Automattic – 3.7.1
Yoast SEO: by Team Yoast – 12.4
WP Add Custom CSS: by Daniele De Santis – 1.1.5

### Inactive Plugins (1) ###

WooCommerce Square: by WooCommerce – 2.0.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /buy-now/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #150 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Geolocation debug info ###

HTTP_CF_IPCOUNTRY: AU
GEOIP_COUNTRY_CODE: ❌
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: ❌
HTTP_X_FORWARDED_FOR: 58.169.144.95
REMOTE_ADDR: 58.169.144.95
Real external IP: 58.169.144.95
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 1.8.14
Base location: AU:NSW
Base currency: AUD
Price Based On: billing
Shipping: ✔
Test mode: –
Test country: –
Load products price in background: –
Prices entered with tax: –
Calculate tax based on: shipping
Display prices in the shop: excl

### Zone Pricing UK ###

zone_id: uk
name: UK
countries: GB
currency: GBP
exchange_rate: 0.55
disable_tax_adjustment: no

### Zone Pricing Saudi ###

zone_id: saudi
name: Saudi
countries: SA
currency: SAR
exchange_rate: 2.61
disable_tax_adjustment: no

### Zone Pricing US ###

zone_id: us
name: US
countries: US | UM | VI
currency: USD
exchange_rate: 0.70
disable_tax_adjustment: no

### Zone Pricing Canada ###

zone_id: canada
name: Canada
countries: CA
currency: CAD
exchange_rate: .93
disable_tax_adjustment: no

### Zone Pricing Europe ###

zone_id: europe
name: Europe
countries: AD | AL | AT | BA | BE | BG | BY | CH | CY | CZ | DE | DK | EE | ES | FI | FO | FR | GG | GI | GR | HR | HU | IE | IM | IS | IT | JE | LI | LT | LU | LV | MC | MD | ME | MK | MT | NL | NO | PL | PT | RO | RS | SE | SI | SJ | SK | SM | UA | VA
currency: EUR
exchange_rate: 0.62
disable_tax_adjustment: no

### Zone Pricing Israel ###

zone_id: israel
name: Israel
countries: IL
currency: ILS
exchange_rate: 2.51
disable_tax_adjustment: no

### Zone Pricing NZ ###

zone_id: nz
name: NZ
countries: NZ
currency: NZD
exchange_rate: 1.05
disable_tax_adjustment: no

### Zone Pricing UAE ###

zone_id: uae
name: UAE
countries: AE
currency: AED
exchange_rate: 2.56
disable_tax_adjustment: no

### Action Scheduler ###

Complete: 4
Oldest: 2019-10-03 05:55:47 +0000
Newest: 2019-10-24 05:58:31 +0000

Pending: 1
Oldest: 2019-10-31 05:58:32 +0000
Newest: 2019-10-31 05:58:32 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by whereskarlo** [comment] 2019-10-31 23:12
@mikejolley I can confirm this is a reproducible bug. I did some digging with the Structured Data Testing Tool (disabled all plugins except Woocommerce and switched to default theme) and found the culprit.

![review](https://user-images.githubusercontent.com/2850757/67991731-89b2a600-fc3a-11e9-912f-92416a233aa3.jpg)

Review is each individual review on the product. Since a review is a comment on the product, the comment is missing the type "One of offers or review or aggregateRating should be provided."

![review detail](https://user-images.githubusercontent.com/2850757/67991732-8a4b3c80-fc3a-11e9-92f0-0e848eaf31f6.jpg)

This product has one review, and thus one error for "One of offers or review or aggregateRating should be provided." 

![10 reviews](https://user-images.githubusercontent.com/2850757/67992142-efebf880-fc3b-11e9-9f13-7257d34ef5a3.jpg)

On products with 10 reviews, there are 10 errors. 

![10 review detail](https://user-images.githubusercontent.com/2850757/67992158-fc705100-fc3b-11e9-88bf-24a975bd8966.jpg)

Each comment (review) above is missing the structured data for "One of offers or review or aggregateRating should be provided."

**Comment by whereskarlo** [comment] 2019-11-07 18:00
#24950 This is the same error as described in 24950

**Comment by bondimedical3** [comment] 2019-11-08 02:51
Its the same because you plagiarized this report.

**Comment by juliaamosova** [comment] 2019-11-11 21:49
Thank you for reporting the issue @bondimedical3. As stated above, it is a duplicate of https://github.com/woocommerce/woocommerce/issues/24950 and https://github.com/woocommerce/woocommerce/issues/24862. We have a PR in place to fix it: https://github.com/woocommerce/woocommerce/pull/24278 - it will be released as soon as possible. I am closing this issue. Please continue to discuss in the PR: https://github.com/woocommerce/woocommerce/pull/24278.

**Closed by juliaamosova** 2019-11-11 21:49 UTC
