### ISSUE TITLE
CSS fix for WooCommerce emails in `Hebrew` on mobile devices

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce#25076] opened 2019-11-20 12:01 UTC
**Describe the bug**
Emails are not displayed correctly in the Hebrew language:

![https://cld.wthms.co/ok3FWD+](https://cld.wthms.co/ok3FWD+)

**To Reproduce**
1. Check if the default emails are working normally when the site language is set to English
    ![https://cld.wthms.co/8yaM5h+](https://cld.wthms.co/8yaM5h+)
    ![https://cld.wthms.co/I2UHaH+](https://cld.wthms.co/I2UHaH+)
2. Change language to Hebrew, and see that the emails don't fit in the screen on mobile devices
    ![https://cld.wthms.co/wR8JlL+](https://cld.wthms.co/wR8JlL+)
3. Update the translations and then again. No luck:
    ![https://cld.wthms.co/Kx0uLc+](https://cld.wthms.co/Kx0uLc+)
    ![https://cld.wthms.co/ujBcK5+](https://cld.wthms.co/ujBcK5+)
    ![https://cld.wthms.co/2H7C8U+](https://cld.wthms.co/2H7C8U+)

**Expected behavior**
Without any changes to the template, the text should be wrapped, and content formatting should fit within the device screen

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Any

**Comment by juliaamosova** [comment] 2019-11-21 10:11
Thank you for reporting this issue @AashikP. 

I can reproduce it. 

English:
<hr>

![english](https://user-images.githubusercontent.com/19143190/69328427-228b7e80-0c47-11ea-81ed-ed7661bad566.jpg)

Hebrew:
<hr>

![hebrew](https://user-images.githubusercontent.com/19143190/69328453-2b7c5000-0c47-11ea-8eb7-ce1ae4a52c87.jpg)

**Comment by asafmjul** [comment] 2019-11-27 13:49
Hi,

Just wanted to check why it was lowered to low priority?

Our customers can't read our emails on mobile. Assuming it happens for all RTL languages - it effects a lot of people.

Thank,
Asaf

**Comment by asafmjul** [comment] 2019-12-08 09:15
Hi, I also see it is not assigned to any milestone:
![image](https://user-images.githubusercontent.com/50828246/70387259-7c0fdf00-19a3-11ea-8e4f-4f96d99d197e.png)

It was apparently assigned to 3.9.0, but I can't see it there...
https://github.com/woocommerce/woocommerce/milestone/150

**Comment by abdulrahmanAbduatif** [comment] 2019-12-26 06:40
Hello there,

We have been facing the same issue with our Arabic stores. I can see this bug is not assigned yet. Also is there any temporary work around

**Comment by asafmjul** [comment] 2020-01-29 11:43
Hi,

Any updates?

**Comment by mero2online** [comment] 2020-10-29 14:57
I have been facing the same issue and fixed it by editing this form through FTP 

#### 1. Open this directory 
wp-content/plugins/woocommerce/templates/emails

#### 2. Edit email-addresses.php (work for Gmail)
move ` dir="<?php echo is_rtl() ? 'rtl' : 'ltr'; ?>"` one level down
From
```
<div id="wrapper" dir="<?php echo is_rtl() ? 'rtl' : 'ltr'; ?>">
    <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
```
to
```
<div id="wrapper">
    <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" dir="<?php echo is_rtl() ? 'rtl' : 'ltr'; ?>">
```

#### 3. Edit email-addresses.php (work for Yahoo)
Add this to change the table position
```
 </tr>
<tr>
```
From
```
            <br/><?php echo esc_html( $order->get_billing_email() ); ?>
        <?php endif; ?>
    </address>
</td>
```
to
```
            <br/><?php echo esc_html( $order->get_billing_email() ); ?>
        <?php endif; ?>
    </address>
</td>
</tr>
<tr>
```

**Comment by mfs-mindsize** [comment] 2020-12-09 21:59
Does anyone know the status of this? I've tried to reproduce the issue and it looks to me like the text wrapping is not happening for both ltr and rtl. However, I'm not testing the actual emails on a mobile device. I'm using Chrome dev tools mobile simulation.  So perhaps that's a problem in my approach? 

ltr - https://codepen.io/livelearnrepeat/full/yLaaqJK

rtl - https://codepen.io/livelearnrepeat/full/MWjjBjG

**Comment by mfs-mindsize** [comment] 2020-12-16 23:01
@AashikP @juliaamosova - I've done additional digging/discovery. My conclusion is that a couple tables within the email lay have a fixed width of 600. This affects both ltr and rtl. I changed those to use max-width so that on less-wide screens the tables will collapse (instead of being a fixed width). 

In addition, some of the inline CSS is very generous with padding; padding that's a good fit for desktop but on mobile it's excessive. I reduced the padding "tastefully" to make it mobile-friendly but still visually "open" for larger screens. 

For both of these I've worked out a PR that will be submitted soon. Someone on our internal team has to review it first.

**Comment by yaniv691** [comment] 2021-01-21 07:51
@mfs-mindsize can you please share the code you added?

**Comment by yaniv691** [comment] 2021-01-21 11:38
@mero2online's solution works. Of course this needs to be done in a custom template in your child theme so it won't be overridden when you update your theme or Woocommerce. More info on custom templates here: https://docs.woocommerce.com/document/template-structure/

**Comment by mfs-mindsize** [comment] 2021-01-21 18:36
@yaniv691 - The code is being reviewed internally at the agency I work at (Mindsize.com). Once that's ready it'll be submitted as a PR. 

If I remember correctly, after digging it it this was more than a rtl issue. There were other markup+CSS bug(s) in the email template. They were simply easier to see when expecting rtl. I think. It's been over a month :)

**Comment by yaniv691** [comment] 2021-01-22 08:10
@mfs-mindsize, did you try @mero2online's solution? It fixes the bug.

**Comment by mfs-mindsize** [comment] 2021-01-22 14:42
@yaniv691 It solves the issue above, but it does not fix The Bug :)  After digging into it, I noticed there were (other) unlying issues w/ the template and the inline CSS. The Fix required more than simply the above solution.

**Comment by mfs-mindsize** [comment] 2021-01-25 21:49
FYI - PR submitted https://github.com/woocommerce/woocommerce/pull/28934

If anyone would like to review and/or test, please feel free :)

**Comment by vedanshujain** [comment] 2021-02-01 08:15
I have been trying to reproduce the issue, but have not been able to so far. Everything works as expected, I am on WC 4.9.2. 
@mfs-mindsize Can you please provide more details to help me repro the issue:

1. OS system and version of the email client.
2. System status report.

**Comment by yaniv691** [comment] 2021-02-01 11:53
@vedanshujain I've seen this happening on Gmail on Android devices, with Hebrew emails.

**Comment by mfs-mindsize** [comment] 2021-02-01 18:33
@vedanshujain - I read the thread, looked at the code, and found what looked to be things that were incorrect, so I implemented what looked like fixes to me.  

Specifically reproducing aside, perhaps look at code the changes, sans actually being rendered? Something wasn't right.

**Comment by nickelaos** [comment] 2022-09-13 22:21
Confirm, I can reproduce this issue. Thanks @mero2online

**Comment by francoishvz** [comment] 2022-11-01 07:24
37744573-hc

**Comment by symplTech** [comment] 2022-12-04 12:33
This issue is still happening.

**Comment by barryhughes** [comment] 2024-03-07 15:23
- This seems like a near duplicate of https://github.com/woocommerce/woocommerce/issues/31478
- The above issue was closed via https://github.com/woocommerce/woocommerce/pull/36310
- If you still encounter difficulties, please let us know via a new issue.

**Closed by barryhughes** 2024-03-07 15:23 UTC
Labels: type: bug, focus: template, focus: i18n, type: good first issue, priority: high, plugin: woocommerce, Contributor Day - H1 2023, team: Proton
