### ISSUE TITLE
Manual Orders in status of pending Payment Doesn't reduce stock anymore

### ISSUE THREAD

**Issue by diegoabbate** [woocommerce/woocommerce#29108] opened 2021-02-11 21:24 UTC
**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
when I place an order manually, now, with the latest WooCommerce Admin update, the stock is not reduced when the order status is "Pending Payment"

**Expected behavior**
until now when I entered and created an order manually, and the order status was set to "Pending Payment", the product stock was reduced.

**Actual behavior**
when I place an order manually, now, with the latest WooCommerce Admin update, the stock is not reduced when the order status is "Pending Payment"

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. insert a new manual order
2. add products to order
3. select the "pending payment" status of the order
4. create the order
5. See the error: the items in the order are not reduced from the stock

**Comment by tammullen** [comment] 2021-02-12 13:22
Hi @diegoabbate 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end in WooCommerce 5.0, I also checked in earlier versions as well.

Manually created orders with a status of `Pending payment` are not meant to reduce stock. More details here https://docs.woocommerce.com/document/managing-orders/

When I created an order like this stock was only reduced when I changed the status to `Processing`

![screencapture-firm-corncrake-jurassic-ninja-wp-admin-post-php-2021-02-12-12_56_05](https://user-images.githubusercontent.com/24649833/107773025-f0c37380-6d34-11eb-8460-c89ee2199ce4.png)


> ​until now when I entered and created an order manually, and the order status was set to "Pending Payment", the product stock was reduced.

This shouldn't have been the case, can you check if you have any additional plugins which could be affecting inventory.

**Comment by rajhandi88** [comment] 2021-02-25 10:21
I am facing a similar issue in Woocommerce:

Problem: When the order status is changed from Processing to Pending Payment (as for COD Orders), the stock quantity of items in that order increases back in inventory.

What I want: the Pending Payment Order items should be on hold and inventory should be decreased immediately.
Later on, if the COD is successful and order is marked completed then there should be no change in inventory as already the quantity was decreased. But, if I mark the order as cancelled, the inventory should increase back.

**Comment by tammullen** [comment] 2021-09-08 11:46
Hi @diegoabbate ,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

@rajhandi88 if you are still having the issue you describe can you please raise a new issue for it.

**Closed by tammullen** 2021-09-08 11:46 UTC
Labels: has feedback
