### ISSUE TITLE
Woocommerce product searching problem

### ISSUE THREAD

**Issue by rabby696** [woocommerce/woocommerce#21997] opened 2018-11-20 22:33 UTC
For product search on the Woocommerce site, the search result will not come when searching without the complete name of the product. How can I do that?

Regards
Golam Rabbi

**Comment by kloon** [comment] 2018-11-21 07:08
Unable to reproduce http://cld.wthms.co/xZ4WFo Please test with all extensions disabled as well as your theme switched to a default one like Twentyseventeen or Storefront which you should have done prior to creating the issue as per the template provided to you.

Closing as not reproducible.

**Closed by kloon** 2018-11-21 07:08 UTC
