### ISSUE TITLE
Apply some conditional logic on product variations

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#19977] opened 2018-05-05 15:46 UTC
1. Add two custom attributes and use them as variations. Let's call them width and hight.
2. Apply the following values to the attributes:

Width =
280|380|480|580|680|780|880|980|1080|1180|1280|1380|1480|1580|1680|1780|1880|1980|2080|2180|2280|2380|2480|2580|2680|2780|2880|2980

Hight =
280|380|480|580|680|780|880|980|1080|1180|1280|1380|1480|1580|1680|1780|1880|1980|2080

3. Create variations in width and hight where all values are included. Also create a variation where width = 2980 and maximum hight = 1980

https://imgur.com/zzsT0tW

## Expected/actual behavior

When I follow those steps, I see that the variation width = 2980 and hight = 2080 is selectable on the front-end although that combination is not created in the back-end.

https://imgur.com/odbwRD7

I was expecting to see only up to hight = 1980 when width = 2980 was selected. But in this case all possible values are selectable in both drop down lists and WooCommerce promts that the selected value is not valid and not possible to add to cart.

Some conditional logic should have been applied so that only valid values are selectable depending on which attribute was selected first. There is already a possibility to clear the inputs on the front-end if you want to restart the selections.

### WordPress Environment ###

Home URL:
Site URL:
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.5
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
Total databasstorlek: 53.31MB
Datastorlek för databas: 37.03MB
Indexstorlek för databas: 16.28MB
wp_woocommerce_sessions: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_api_keys: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02 MB + Index: 0.05 MB
wp_woocommerce_order_items: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_order_itemmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_tax_rates: Data: 0.02 MB + Index: 0.06 MB
wp_woocommerce_tax_rate_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zones: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_shipping_zone_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zone_methods: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_payment_tokens: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_payment_tokenmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_log: Data: 0.02 MB + Index: 0.02 MB
wp_commentmeta: Data: 0.02 MB + Index: 0.03 MB
wp_comments: Data: 0.02 MB + Index: 0.09 MB
wp_links: Data: 0.02 MB + Index: 0.02 MB
wp_options: Data: 2.06 MB + Index: 0.27 MB
wp_postmeta: Data: 30.23 MB + Index: 11.59 MB
wp_posts: Data: 2.52 MB + Index: 2.14 MB
wp_termmeta: Data: 0.09 MB + Index: 0.11 MB
wp_terms: Data: 0.11 MB + Index: 0.13 MB
wp_term_relationships: Data: 1.19 MB + Index: 1.22 MB
wp_term_taxonomy: Data: 0.14 MB + Index: 0.17 MB
wp_usermeta: Data: 0.02 MB + Index: 0.03 MB
wp_users: Data: 0.02 MB + Index: 0.05 MB
wp_wc_download_log: Data: 0.02 MB + Index: 0.03 MB
wp_wc_webhooks: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_links: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_meta: Data: 0.25 MB + Index: 0.00 MB

### Post Type Counts ###

attachment: 3405
customize_changeset: 4
nav_menu_item: 8
page: 14
post: 2
product: 594
product_variation: 1883
revision: 12
shipping_package: 5
slider: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: av Automattic – 4.0.3
Contact Form 7: av Takayuki Miyoshi – 5.0.1
Kidz Theme Functionality: av ideapark.kz – 1.4.2
Kidz Theme Wishlist: av ideapark.kz – 1.2
Loco Translate: av Tim Whitlock – 2.1.3
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 3.0.2
SVG Support: av Benbodhi – 2.3.15
WooCommerce Advanced Shipping Packages: av WooCommerce – 1.1.4 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Brands: av WooCommerce – 1.6.0 – 1.6.1 finns tillgänglig
WooCommerce Breadcrumb Permalinks: av Captain Theme – 1.1.1 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Stripe Gateway: av WooCommerce – 4.1.2
WooCommerce Measurement Price Calculator: av SkyVerge – 3.13.2 – 3.13.3 finns tillgänglig
WooCommerce Product CSV Import Suite: av WooCommerce – 1.10.17
WooCommerce Sequential Order Numbers Pro: av SkyVerge – 1.12.0
WooCommerce: av Automattic – 3.3.5
Yoast SEO Premium: av Team Yoast – 6.3
Yoast SEO: WooCommerce: av Team Yoast – 6.3 – Inte testat med den aktiva versionen för WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #4 - /sortiment/
Varukorg: #5 - /varukorg/
Kassan: #6 - /kassan/
Mitt konto: #7 - /mitt-konto/
Allmänna villkor: #14 - /kopvillkor/

### Theme ###

Name: Kidz-Child
Version: 1.1
Author URL: http://ideapark.kz
Child Theme: ✔
Parent Theme Name: Kidz
Parent Theme Version: 1.4.8
Parent Theme Author URL: http://ideapark.kz
WooCommerce Support: ✔

### Templates ###

Overrides: kidz/woocommerce/archive-product.php
kidz/woocommerce/cart/cart-empty.php
kidz/woocommerce/cart/cart-shipping.php
kidz/woocommerce/cart/cart-totals.php
kidz/woocommerce/cart/cart.php
kidz/woocommerce/cart/proceed-to-checkout-button.php
kidz/woocommerce/cart/shipping-calculator.php
kidz/woocommerce/checkout/form-billing.php
kidz/woocommerce/checkout/form-checkout.php
kidz/woocommerce/checkout/form-coupon.php
kidz/woocommerce/checkout/form-shipping.php
kidz/woocommerce/checkout/payment-method.php
kidz/woocommerce/checkout/payment.php
kidz/woocommerce/checkout/review-order.php
kidz/woocommerce/checkout/terms.php
kidz/woocommerce/checkout/thankyou.php
kidz/woocommerce/content-product.php
kidz/woocommerce/content-product_cat.php
kidz/woocommerce/content-single-product.php
kidz/woocommerce/global/form-login.php
kidz/woocommerce/global/sidebar.php
kidz/woocommerce/global/wrapper-end.php
kidz/woocommerce/global/wrapper-start.php
kidz/woocommerce/loop/add-to-cart.php
kidz/woocommerce/loop/loop-end.php
kidz/woocommerce/loop/orderby.php
kidz/woocommerce/loop/result-count.php
kidz/woocommerce/loop/sale-flash.php
kidz/woocommerce/myaccount/dashboard.php
kidz/woocommerce/myaccount/downloads.php
kidz/woocommerce/myaccount/form-login.php
kidz/woocommerce/myaccount/my-account.php
kidz/woocommerce/myaccount/my-address.php
kidz/woocommerce/myaccount/navigation.php
kidz/woocommerce/myaccount/orders.php
kidz/woocommerce/order/order-details-customer.php
kidz/woocommerce/product-searchform.php
kidz/woocommerce/single-product/add-to-cart/grouped.php
kidz/woocommerce/single-product/add-to-cart/variable.php
kidz/woocommerce/single-product/product-image.php
kidz/woocommerce/single-product/product-thumbnails.php
kidz/woocommerce/single-product/sale-flash.php
kidz/woocommerce/single-product/tabs/additional-information.php
kidz/woocommerce/single-product/tabs/tabs.php
kidz/woocommerce/single-product/title.php
kidz/woocommerce/single-product.php

**Comment by peterfabian** [comment] 2018-05-07 15:50
Hi, 

If there are less than 30 variations, the availability of those is directly embedded in the form. However, if there are too many variations/combinations, the availability of each variation is checked via an AJAX call when the customer picks all the attributes. So, if like in your case, you want to have >500 variations, this is currently only supported in the way you see it.

I guess you can imagine that if there were 6-7 attributes, finding out which variations are available would mean checking all the combinations of those attributes for one attribute user changed and that could be costly... However, if you have any suggestions how to make this work efficiently, feel free to submit a PR.

Additionally, I think there are extensions that might be able to do this, e.g. you might want to check out https://docs.woocommerce.com/document/woocommerce-gravity-forms-product-addons/

**Comment by rocketeer76** [comment] 2018-05-07 17:07
I understand the situation when you describe it, thanks. Is it common for stores to use 6-7 attributes for variations?!

As I see it on the front end, when I've selected my two attributes the form is locked and can be unlocked/cleared clicking a text under the form. One way to do it is to lock the first attribute and have the clear text appear straight away. If the attributes are locked one at a time at selection, it will save resources checking the other available combinations as you have to clear the form to change any of the earlier selected attributes and start over. This is how I would approach it and have that as an option in the WooCommerce settings to lock attributes for variations at selection.

Gravity Forms Product Addons may work but as I see it you still need a "parent" product before using the addon. I don't think it fits the purpose for this case.

**Comment by mikejolley** [comment] 2018-05-08 14:08
> If the attributes are locked one at a time at selection, it will save resources checking the other available combinations as you have to clear the form to change any of the earlier selected attributes and start over. This is how I would approach it and have that as an option in the WooCommerce settings to lock attributes for variations at selection.

This approach also means to change an earlier choice would require starting over which may not be desirable. I don't think it can work for all use cases :(

The AJAX load for variations > 30 is to prevent the need to load all variations at once. Even with your suggestion, in order to have conditional logic you need to load all variations + attributes and know what combinations work. The client side part is not the problem - it's the PHP side which would have the performance issue if too many were loaded at once.

@peterfabian's suggestion of `woocommerce_ajax_variation_threshold` will help your case. If you do have a very large number of variations, and it makes sense to do so, use addons.

Addons/gravity forms addons allow for more complex logic and work better when the combination of attributes do not need to match a specific SKU. e.g. if the attributes that get selected do not impact stock of the main product.

Closing this out as it's not a bug.

Thanks

**Closed by mikejolley** 2018-05-08 14:08 UTC
Labels: Type: Enhancement

**Comment by allysonsouza** [comment] 2019-01-16 18:46
It would be great to have some conditional logic in variations. If we have something like a "Do Not Apply" option for an attribute dropdown when creating a variation, would be great. And think it can be useful in some cases. At least, would be good to see WooCommerce auto-select the unique available option in dropdown while user is selecting variations.
