### ISSUE TITLE
Woocommerce doesn't function

### ISSUE THREAD

**Issue by newbie-maker** [woocommerce/woocommerce#25952] opened 2020-03-17 16:41 UTC
Hi Everyone,

I'm pretty new at writing codes en developing my own website. Currently I'm working on developing my own webshop through  wordrpess. I am hosting it on Wamp on my computer. I am using the woocommerce extension to create a e-commere. The weird thing is I can look at the products in my store on my website but when I put the product in the basket and click on checkout I get the message that the page is unavailable. I have the same issue with the account page. Can someone help me?
[Cart - Safe State - Google Chrome 2020-03-17 17-39-13.zip](https://github.com/woocommerce/woocommerce/files/4344590/Cart.-.Safe.State.-.Google.Chrome.2020-03-17.17-39-13.zip)

We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by juliaamosova** [comment] 2020-03-19 19:30
Hi @newbie-maker,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

From reading your report, it sounds like you didn't complete Setup Wizard which is when all the pages are being created for WooCommerce to work:

https://docs.woocommerce.com/document/woocommerce-setup-wizard/

You can also try to create default pages via `WooCommerce / Status / Tools`:

![pages](https://user-images.githubusercontent.com/19143190/77107090-86a43080-69f6-11ea-9e53-96d20625c457.jpg)

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-03-19 19:30 UTC
