### ISSUE TITLE
Woo product stock doesn't work on front-end

### ISSUE THREAD

**Issue by crazymiwka** [woocommerce/woocommerce#25393] opened 2020-01-13 09:20 UTC
We have a large online store and recently we began to notice that people are ordering products that we do not have in stock. At first we thought that we had problems with the stock quantity on the site, but then we noticed that for a small number of products stock doesn’t work at all.

For example, when I open a category and see a list of products, then the X product is marked that it is not available. But, if I open this X product, it shows that it is available and can be ordered (and people order). When I check this X product in the admin panel, then there the quantity is displayed correctly (0 - in my case). I tried to change the quantity in the warehouse of this X product to see the changes, but as before - the quantity on the site doesn’t change, and in the admin panel - yes.

![products_list](https://user-images.githubusercontent.com/27347683/72244057-1b08a600-35f6-11ea-945f-cabded37af4f.jpg)

![product](https://user-images.githubusercontent.com/27347683/72244081-265bd180-35f6-11ea-9305-48972ee02d30.jpg)

![product_admin](https://user-images.githubusercontent.com/27347683/72244255-910d0d00-35f6-11ea-8d14-f8e96bff8862.jpg)

![product_admin_expanded](https://user-images.githubusercontent.com/27347683/72244261-95d1c100-35f6-11ea-8db5-8dcafc1f2821.jpg)

Link to website: https://puhelinfix.fi/
Link to category: https://puhelinfix.fi/tuote-osasto/oneplus/oneplus-2/
Link to product: https://puhelinfix.fi/tuote/oneplus-2-naytto/

What could be the problem? Yes, I can remove the old product and create a new one, but we don’t know how many such problematic products we have on our site.

**Comment by juliaamosova** [comment] 2020-01-14 15:40
Hi @crazymiwka,

Thank you for raising the issue! However, I can’t reproduce it on my end.

Do you have any plugins installed? I see that you don’t use one of our default themes.

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-01-21 11:10
Hi @crazymiwka,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-01-21 11:10 UTC
Labels: can't reproduce
