### ISSUE TITLE
Non-Grouped products showing as Grouped in the WP admin

### ISSUE THREAD

**Issue by joshuaiz** [woocommerce/woocommerce#26442] opened 2020-05-10 01:56 UTC
Products that are not Grouped or linked to any other products are showing as 'Grouped' (with an arrow next to the title). See here:

<img width="1498" alt="Screen Shot 2020-05-09 at 4 41 56 PM" src="https://user-images.githubusercontent.com/1096738/81488886-c0462a80-9234-11ea-9e85-c9b149ebb648.png">

These products are Simple Downloadable products and are not Grouped or linked to any other products so they should not be labeled as such. 

Related but different issue here: woocommerce/woocommerce#14507

This is affecting certain queries using `wp-graphql-woocommerce`. I've filed a more specific report in that repo here: 

https://github.com/wp-graphql/wp-graphql-woocommerce/issues/278

1. Go to the Product List in the WP Admin
2. Non-Grouped products are listed as 'Grouped' with an arrow next to the title
3. Try to query these products with WPGraphQL
4. Queries return null

**Expected behavior**
Non-Grouped products should not be listed as Grouped.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 5.4.1
PHP 7.3.2
MySQL 5.6
Using Local by Flywheel
```
`
### WordPress Environment ###

WordPress address (URL): https://vizql.local
Site address (URL): https://vizql.local
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.3.2
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
Total Database Size: 10.69MB
Database Data Size: 5.63MB
Database Index Size: 5.06MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.03MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_as3cf_items: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_ewwwio_images: Data: 0.23MB + Index: 0.22MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.25MB + Index: 0.14MB + Engine InnoDB
wp_oses_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 0.31MB + Index: 0.13MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 25
acf-field-group: 5
artist: 21
attachment: 95
clothing: 8
nav_menu_item: 3
outlets: 16
page: 13
post: 1
product: 230
revision: 99
shop_coupon: 1
shop_order: 81

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (17) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.8.9
WP Offload Media: by Delicious Brains – 2.3.2
EWWW Image Optimizer: by Exactly WWW – 5.3.1
Vizual Artists Custom Post Type: by studio.bio – 1.0
Vizual Clothing: by Joshua Michaels for studio.bio – 0.1.0
Vizual Outlets: by Joshua Michaels for studio.bio – 0.1.0
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.9 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Stripe Gateway: by WooCommerce – 4.3.3 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce: by Automattic – 4.1.0
WP GraphiQL: by WPGraphQL
Digital First Media
Jason Bahl – 1.0.1

WPGraphQL for Advanced Custom Fields: by WPGraphQL
Jason Bahl – 0.3.1

WPGraphQL JWT Authentication: by WPGraphQL
Jason Bahl – 0.4.0

WPGraphQL WooCommerce (WooGraphQL): by kidunot89 – 0.5.0 – Installed version not tested with active version of WooCommerce 4.1.0
WP GraphQL: by WPGraphQL – 0.8.3
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.15
WP Migrate DB Pro: by Delicious Brains – 1.9.10
WP Offload SES Lite: by Delicious Brains – 1.4.1

### Inactive Plugins (14) ###

Admin Columns Pro: by AdminColumns.com – 4.3.8
Admin Columns Pro - Advanced Custom Fields (ACF): by Admin Columns – 2.3.2
Admin Columns Pro - WooCommerce: by Admin Columns – 3.1.3 – Installed version not tested with active version of WooCommerce 4.1.0
Advanced Custom Fields: Theme Code Pro: by hookturn – 2.4.0
Algolia Custom Integration: by  – 1.0.0
Classic Editor: by WordPress Contributors – 1.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
SVG Support: by Benbodhi – 2.3.18
User Role Editor: by Vladimir Garagulya – 4.54
WooCommerce Services: by Automattic – 1.23.0 – Installed version not tested with active version of WooCommerce 4.1.0
WP HTML Mail: by Hannes Etzelstorfer // codemiq – 2.9.4
WP Migrate DB Pro CLI: by Delicious Brains – 1.3.5
WP Migrate DB Pro Theme & Plugin Files: by Delicious Brains – 1.0.5
WP Retina 2x Pro: by Jordy Meow – 5.5.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /store/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 57
Oldest: 2020-04-26 10:56:26 -0500
Newest: 2020-05-09 20:43:43 -0500

`
```
</details>

**Comment by Konamiman** [comment] 2020-05-11 10:52
Hi, thanks for posting the issue.

I understand that you are notifying two different issues here:

1. Non-grouped products show as grouped (with an arrow) in the products list in WP admin.
2. These products aren't included in GraphQL queries.

Unfortunately I haven't been able to reproduce any of the two cases. I see that you have some plugins installed, since you are using Local could you please try to disable them and try again?

**Comment by joshuaiz** [comment] 2020-05-11 20:00
HI @Konamiman,

I've tried disabling all plugins except WooCommerce + WooCommerce Stripe and the problem persists.

I also tried using the default Twentynineteen theme and the issue remains.

All that said, my current live site is still on WC 3.7.0 and has this issue as well although it is not affecting anything with the WC REST API queries so I didn't notice it until working with WPGraphQL on my local site.

If you'd like to take a look, let me know and I can give you admin access to the live site so you can view the issue.

In any event, to resolve for my local site I had to save every product as something other than 'Simple' (I used 'Variable') and then re-save as 'Simple'. This removes the arrow in the product list and GraphQL `products` queries work.

Mind you, that took me the better part of 2 hours with 230 products which was...not awesome.

Before that fix I tried using a bulk editor plugin to save all products as 'Variable' and then back to 'Simple'. That didn't work - the products have to be saved as something other than 'Simple' and then re-saved as 'Simple'.

Thus, even though my particular issue is resolved, it would be great to find a fix in case anyone else comes up against this to save them from having to re-save all of their products.

**Comment by carinapilar** [comment] 2020-05-21 20:31
Had this situation too on #2995219-zd. The workaround mentioned above, of changing the product type to Variable and back to Simple, fixed the problem.

**Comment by tammullen** [comment] 2021-03-24 21:26
Hi @joshuaiz 

As a part of this repository’s maintenance, I am closing this issue as it seems to be resolved. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2021-03-24 21:26 UTC
Labels: has feedback
