### ISSUE TITLE
WooCommerce Intuit Payments Gateway not working

### ISSUE THREAD

**Issue by pakison** [woocommerce/woocommerce#24983] opened 2019-11-05 21:25 UTC
Oath2 connection is not working. The messages say to enter the Intuit Developer login credentials, which I do, but I only get a 'We're sorry' message from Intuit. Here is the beginning of the url string:
https://appcenter.intuit.com/connect/oauth2?client_id=xxxx@orchardvalleyfarms.com&scope=com.intuit.quickbooks.payment&....
Using that, I went to appcenter.intuit.com and logged in successfully with the same credentials as the Developer credentials.
The client has a valid merchant account and has an online account (the Smart start version) and the merchant account has been l linked to that online account.

Still no joy. We're very concerned with the abandonment of oath 1 nearing.

**Comment by juliaamosova** [comment] 2019-11-06 13:11
Hi @pakison,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs specific to the WooCommerce plugin only. 

The issue you reported is related to the WooCommerce Intuit Payments Gateway plugin. In addition to that, the type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* If you are using [Intuit Payments Gateway](https://woocommerce.com/products/intuit-qbms/), you can [open a ticket with its developers](https://woocommerce.com/my-account/create-a-ticket/?canchat=false) and ask them to look at it with you

* If you are using some other extension, contact the developers of that said extension for further help

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-11-06 13:11 UTC
