### ISSUE TITLE
Ошибка с конвертированием валюты

### ISSUE THREAD

**Issue by MrGorlenko** [woocommerce/woocommerce#27680] opened 2020-09-15 19:03 UTC
На сайте настроена WooCommerce - работает везде исправно, кроме одной страницы - https://likekate.ru/product-category/bodysuit. При переходе на страницу через мобильное устройство, показывает цены в долларах, а не в рублях, как на всех остальных страницах, к примеру, на этой: https://likekate.ru/product-category/top. Страницы категорий были проверены - все идентичны, мы предполагаем, что тут однозначно баг в самом WooCommerce. Были бы рады решению проблемы. Спасибо!

**Comment by juliaamosova** [comment] 2020-09-16 13:23
Hi @MrGorlenko,

Thanks for rasing the issue. 

Please note that we reply to bug reports in the English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

Original message translated:

Bug report title:

>Error with currency conversion

Bug report:

>The site is configured with WooCommerce - it works fine everywhere, except for one page - https://likekate.ru/product-category/bodysuit. When you go to the page via a mobile device, it shows prices in dollars, not in rubles, as on all other pages, for example, on this one: https://likekate.ru/product-category/top. The category pages have been checked - everything is identical, we assume that this is definitely a bug in WooCommerce itself. We would be glad to solve the problem. Thank!

<hr>

The number of details you provided is not enough for us to work with and identify what could be going on. 

Please provide us with steps to reproduce the issue on our end. We need to know how your category pages are set-up - step by step instructions for us to recreate your use case. 

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment.

**Comment by tammullen** [comment] 2020-10-02 21:05
Hi @MrGorlenko 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2020-10-02 21:05 UTC
Labels: status: needs feedback
