### ISSUE TITLE
[4.0 beta1] No notification to update database

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce#25686] opened 2020-02-17 11:39 UTC
**Describe the bug**

I see no notification to update the database version even though the WooCommerce is updated to latest version, and the database is still at WooCommerce 3.9.2

**To Reproduce**
1. Install WooCommerce beta tester plugin
2. Switch to version 4.0.0 beta 1
3. Check System Status Report to confirm that even though you're currently on version 4.0 beta 1, the database is still at 3.9.2, with no notification to update the database

**Screenshots**

![https://d.pr/i/CDMaOe+](https://d.pr/i/CDMaOe+)
*If the image does not load, please click this link: https://d.pr/i/CDMaOe*

**Expected behavior**

Prompt an update to the database with the new version

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
ANY.

Tested with AU sites, and my own local installation. 

Please do note that manually updating the database does work, but not everyone would know of this feature:

![https://d.pr/i/JahZiH+](https://d.pr/i/JahZiH+)
*If the image does not load, please click this link: https://d.pr/i/JahZiH*

**Comment by AashikP** [comment] 2020-02-17 11:42
There's also no confirmation of the database update once the update is manually run via **WooCommerce > Status > Tools > Update Database**.

**Comment by LCmry** [comment] 2020-02-17 18:29
Hi @AashikP , I thought this might be too. I found the notice to update the database is hidden under the "Notices" button on the upper right of the WC Admin menu bar. Though I didn't see the Notices button until I went to a page that wasn't **WooCommerce > Dashboard**.

**Comment by peterfabian** [comment] 2020-02-19 13:13
Thanks for reporting, this is a duplicate of https://github.com/woocommerce/woocommerce/issues/25646.

**Closed by peterfabian** 2020-02-19 13:13 UTC
