### ISSUE TITLE
[WC 4.1 beta.2] Incorrect redirect after purchasing product on woo.com

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#26189] opened 2020-04-15 15:50 UTC
Filing this issue on behalf of @denho. Reference: pb22l9-8V-p2#comment-387.

**Describe the bug**

After installing a purchased on Woo.com product via Woo.com installer, I’m redirected to Plugins in WP admin. But when hitting this page, I suddenly get another redirect to Woo Dashboard:

![redirect](https://user-images.githubusercontent.com/19143190/79358357-18785e00-7f0f-11ea-933d-90a29d42ab83.png)

Need to investigate further.

**Comment by tammullen** [comment] 2020-10-22 19:13
Closing as can't reproduce, in WC 4.6.1 after installing a purchased on Woo.com product via Woo.com installer, I’m redirected to Plugins in WP admin and no further redirection takes place

**Comment by haszari** [comment] 2020-11-11 19:03
I have been seeing this on my ephemeral test site. After plugin installs and activates I land on wc-admin main page. Maybe it redirects there if site has incomplete todos in task list?

<img width="1544" alt="Screen Shot 2020-11-11 at 3 39 37 PM" src="https://user-images.githubusercontent.com/4167300/98852932-4a5d9d00-24bd-11eb-96a4-0ece0a1dbdad.png">

Here's the system report:

<details>

```
### WordPress Environment ###

WordPress address (URL): https://ephemeral-haszari-20201109.atomicsites.blog
Site address (URL): https://ephemeral-haszari-20201109.atomicsites.blog
WC Version: 4.6.2
REST API Version: ✔ 4.6.2
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.12
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.2
WC Database Prefix: wp_
Total Database Size: 2.73MB
Database Data Size: 1.24MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 61
customize_changeset: 3
global_product_addon: 2
page: 11
post: 2
product: 43
product_variation: 10
revision: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Jetpack by WordPress.com: by Automattic – 9.0.2
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.26 – Installed version not tested with active version of WooCommerce 4.6.2
WooCommerce Cart Add-Ons: by WooCommerce – 1.15.33
WooCommerce Email Customizer: by WooCommerce – 1.1.18 – Installed version not tested with active version of WooCommerce 4.6.2
WooCommerce One Page Checkout: by Automattic – 1.7.9 – Installed version not tested with active version of WooCommerce 4.6.2
WooCommerce Product Add-ons: by WooCommerce – 3.1.0 – Installed version not tested with active version of WooCommerce 4.6.2
WooCommerce: by Automattic – 4.6.2 (update to version 4.7.0 is available)

### Inactive Plugins (0) ###


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.9.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2020-11-09 02:20:27 +0000
Newest: 2020-11-11 02:38:30 +0000
```

</details>

**Comment by juliaamosova** [comment] 2020-11-11 19:08
Thanks @haszari! I am reopening the issue so that we could take a look further.

**Comment by rrennick** [comment] 2021-08-31 16:20
Closing this as there have been no new reports of this occurring.

**Closed by rrennick** 2021-08-31 16:20 UTC
Labels: category: can't reproduce, has feedback
