### ISSUE TITLE
Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by Kerfred** [woocommerce/woocommerce#21694] opened 2018-10-26 15:41 UTC
**Describe the bug**
Since the last WooCommerce update (3.5.0), I get this notice:
«Notice: Trying to get property of non-object in wp-content/plugins/woocommerce/includes/wc-attribute-functions.php on line 172»
It is because $wc_product_attributes is considered as an array of objects but is initialized as an array of arrays.

**To Reproduce**
In includes/wc-attribute-functions.php on line 172:
`$orderby = $wc_product_attributes[ 'pa_' . $name ]->attribute_orderby;`
$wc_product_attributes[ 'pa_' . $name ] should be an object.

But in includes/import/abstract-wc-product-importer.php on line 675:
`$wc_product_attributes[ wc_attribute_taxonomy_name( $taxonomy->attribute_name ) ] = $taxonomy;`
$taxonomy is not an object but an array. It is set in includes/wc-attribute-functions.php on line 60:
`return (array) array_filter( apply_filters( 'woocommerce_attribute_taxonomies', $attribute_taxonomies ) );`

**Expected behavior**
Make $wc_product_attributes either an array or an object but not use it sometimes as an array and sometimes as an object

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

For information, this issue happens when I migrate a Magento site to WooCommerce with FG Magento to WooCommerce Premium. I am the owner of this plugin. WooCommerce triggers a notice during the import.
Please tell me once this bug is fixed, and if you set it as an array of arrays or as an array of objects. And I'll change my plugin accordingly.

Don't hesitate to ask if you need more informations.

**WordPress Environment**
<details>
````
### WordPress Environment ###

Home URL: http://localhost/test/wordpressimport
Site URL: http://localhost/test/wordpressimport
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.27 (Unix) OpenSSL/1.0.1p PHP/7.1.8
PHP Version: 7.1.8 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 2 GB
PHP Time Limit: 3600
PHP Max Input Vars: 2000
cURL Version: 7.43.0
OpenSSL/1.0.1p

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
Total Database Size: 7.78MB
Database Data Size: 5.75MB
Database Index Size: 2.03MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_fg_redirect: Data: 0.02MB + Index: 0.00MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 0.02MB + Index: 0.06MB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_ngg_album: Data: 0.02MB + Index: 0.02MB
wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB
wp_ngg_pictures: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.52MB + Index: 0.05MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_toolset_associations: Data: 0.02MB + Index: 0.05MB
wp_toolset_post_guid_id: Data: 0.05MB + Index: 0.02MB
wp_toolset_relationships: Data: 0.02MB + Index: 0.08MB
wp_toolset_type_sets: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 1.45MB + Index: 0.44MB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB

### Post Type Counts ###


### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (13) ###

FG Debug: by Frédéric GILLES – 1.1.0
FG Drupal to WordPress Premium: by Frédéric GILLES – 1.65.3
FG Joomla to WordPress Premium: by Frédéric GILLES – 3.46.0
FG Magento to WooCommerce Premium Product Options module: by Frédéric GILLES – 1.1.2 – Not tested with the active version of WooCommerce
FG Magento to WooCommerce Premium: by Frédéric GILLES – 2.57.5 – Not tested with the active version of WooCommerce
FG PrestaShop to WooCommerce Premium: by Frédéric GILLES – 3.42.0 – Not tested with the active version of WooCommerce
FG SPIP to WordPress Premium: by Frédéric GILLES – 2.34.0
FG View Protected Meta: by Frédéric GILLES – 1.3.0
Toolset Types: by OnTheGoSystems – 3.1.2
WooCommerce Product Add-ons: by WooCommerce – 2.9.0 – 3.0.0 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.0
Yoast SEO: by Team Yoast – 9.0.2 – Not tested with the active version of WooCommerce
WP Native Dashboard: by Heiko Rabe – 1.3.12

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: 
Taxonomies: Product Visibility: 

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
````
</details>

**Comment by rodrigoprimo** [comment] 2018-11-01 18:19
I'm not able to reproduce this bug. It seems to me that, in WooCommerce core, the global `$wc_product_attributes` is always an array of objects, and never an array of arrays. By default, `$wpdb->get_results()` returns an array of objects, which seems to be what is happening when the transient `wc_attribute_taxonomies` is set:

https://github.com/woocommerce/woocommerce/blob/2f7f514f1496c2b7c03cd72277ca18e6044d5948/includes/wc-attribute-functions.php#L55

Maybe you have some plugin using the filter `woocommerce_attribute_taxonomies` (https://github.com/woocommerce/woocommerce/blob/2f7f514f1496c2b7c03cd72277ca18e6044d5948/includes/wc-attribute-functions.php#L60)?

Closing this issue for now. Please leave a comment if I missed something, and I will reopen it.

**Closed by rodrigoprimo** 2018-11-01 18:19 UTC

**Comment by Kerfred** [comment] 2018-11-01 18:47
Thank you for this information.
So I think "(array)" should be replaced by "(object)" in
`return (array) array_filter( apply_filters( 'woocommerce_attribute_taxonomies', $attribute_taxonomies ) );`
in includes/wc-attribute-functions.php on line 60.
Does it make sense?

**Comment by Kerfred** [comment] 2018-12-02 09:46
Any update of the fix?

**Comment by rodrigoprimo** [comment] 2018-12-04 16:51
> So I think "(array)" should be replaced by "(object)" in
return (array) array_filter( apply_filters( 'woocommerce_attribute_taxonomies', $attribute_taxonomies ) );
in includes/wc-attribute-functions.php on line 60.
Does it make sense?

I'm sorry, but I don't follow why you are suggesting that we replace `(array)` by `(object)` in includes/wc-attribute-functions.php on line 60. As I mentioned about, `$attribute_taxonomies` is an array (an array of objects to be more precise) and not an object, so casting whatever is returned by the filter to an array seems the correct behavior.

**Comment by Kerfred** [comment] 2018-12-08 05:34
You are right.
Sorry for all. There was no bug.
