### ISSUE TITLE
Uncaught Error: Call to a member function is_block_editor() on nulll

### ISSUE THREAD

**Issue by nmolham-godaddy** [woocommerce/woocommerce#30286] opened 2021-07-15 12:38 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using POS extension and trying to print a receipt, I get this error:
```
Fatal error /woocommerce/includes/admin/class-wc-admin-assets.php. Error message: Uncaught Error: Call to a member function is_block_editor() on null in /woocommerce/includes/admin/class-wc-admin-assets.php:57
```

A simple fix is to add `$screen` `null` check before calling a method on it here https://github.com/woocommerce/woocommerce/blob/release/5.5/includes/admin/class-wc-admin-assets.php#L57
```php
if ( $screen && $screen->is_block_editor() ) {
```

**Comment by vedanshujain** [comment] 2021-07-15 12:56
Duplicate of https://github.com/woocommerce/woocommerce/issues/30281

**Closed by vedanshujain** 2021-07-15 12:56 UTC
