### ISSUE TITLE
Displaying errors in process_admin_options still shows message that settings are saved

### ISSUE THREAD

**Issue by tai-flywire** [woocommerce/woocommerce#29690] opened 2021-04-15 07:57 UTC
I am developing a custom payment gateway and want to implement custom field validation for the settings page.  I overrode the `process_admin_options` method for my gateway subclass which will check if a validation method exists for a given settings field and, if it does, run it.  The validation method will throw an exception if it fails validation.

So far, I am just forcing an exception to test and, if the exception is found, I call `display_errors()` and return false.  I had assumed that returning false would prevent saving the invalid settings and it does, but the problem is, it still shows a message "Your settings have been saved.", alongside my custom error message.  Am I missing a step to suppress this message, or is this a bug?  Thanks in advance and sorry, I'm still a noob as far as PHP goes.

Here is my code:

```
public function process_admin_options() {
    $has_validation_errors = false;
    $this->init_settings();

    $post_data = $this->get_post_data();

    foreach ( $this->get_form_fields() as $key => $field ) {
        if ( 'title' !== $this->get_field_type( $field ) ) {
            try {
                if ( method_exists( $this, 'validate_' . $key ) ) {
                    try {
                        $this->settings[ $key ] = call_user_func(
                            array( $this, 'validate_' . $key ),
                            $this->get_field_value( $key, $field, $post_data )
                         );
                    } catch ( Exception $e ) {
                        $has_validation_errors = true;
                        $this->add_error( $e->getMessage() );
                    }
                } else {
                    $this->settings[ $key ] = $this->get_field_value( $key, $field, $post_data );
                }
            } catch ( Exception $e ) {
                $this->add_error( $e->getMessage() );
            }
        }
    }

    if ( $has_validation_errors ) {
        $this->display_errors();
        return false;
    } else {
        return update_option( $this->get_option_key(), apply_filters( 'woocommerce_settings_api_sanitized_fields_' . $this->id, $this->settings ), 'yes' );
    }
}

protected function validate_field_mapping( $value ): string {
    throw new Exception( "Foobar" );

    return $value;
}
```
![image](https://user-images.githubusercontent.com/39804991/114834274-fb68ba80-9e02-11eb-89c6-431c14c5fe3f.png)

**Comment by tammullen** [comment] 2021-04-17 13:13
Hi @tai-flywire 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-04-17 13:13 UTC
