### ISSUE TITLE
Number of database queries in Woocommerce 4.4.1

### ISSUE THREAD

**Issue by maticluznarow** [woocommerce/woocommerce#27535] opened 2020-08-31 10:06 UTC
**Is your feature request related to a problem? Please describe.**
I just updated from Woocommerce 4.3.3 to 4.4.1 and noticed huge increase of database queries. I am not sure if this is intentional or not but I just wanted to point it out because the site is slower because of that. 

**Describe the solution you'd like**
Lower amount of database queries.

**Describe alternatives you've considered**
/

**Additional context**
Number of queries using Woocommerce 4.3.3.
![image](https://user-images.githubusercontent.com/65150716/91708574-ce241080-eb81-11ea-8d0c-0253699680ed.png)

Number of queries using Woocommerce 4.4.1
![image](https://user-images.githubusercontent.com/65150716/91708754-0fb4bb80-eb82-11ea-8a2f-0931fb60b2c7.png)

**Comment by lkraav** [comment] 2020-08-31 13:53
What page is this on?

You also need to do a set of measurements, not just 1. At any given moment there could be cache priming or similar, and follow up requests would have a lot less queries.

**Comment by maticlu** [comment] 2020-08-31 17:19
You are right. I did more measurements but I did not post them. 

In order to demonstrate the issue I created two separate clean WP 5.5 installs with default TwentyTwenty theme and Query monitor plugin. One website has WC 4.3.3, another 4.4.1. No other plugins. Websites are on the same local server.

I refreshed both websites several times. It is always the same result.

**Shop page**


**Woocommerce 4.3.3** - 66 queries

![image](https://user-images.githubusercontent.com/26632549/91745893-01839100-ebbc-11ea-939c-56cee6f02cea.png)

**Woocommerce 4.4.1** - 206 queries

![image](https://user-images.githubusercontent.com/26632549/91745943-1829e800-ebbc-11ea-9758-3a6295642680.png)


**Category page**

**Woocommerce 4.3.3** -45 queries

![image](https://user-images.githubusercontent.com/26632549/91746174-8078c980-ebbc-11ea-81e9-0b2ab202c461.png)

**Woocommerce 4.4.1** - 97 queries

![image](https://user-images.githubusercontent.com/26632549/91746292-aa31f080-ebbc-11ea-9136-776113099b32.png)


**Average TTFB after 10 page refreshes**

- Woocommerce 4.3.3 = 100ms
- Woocommerce 4.4.1 = 400ms

**Comment by maticluznarow** [comment] 2020-08-31 17:25
You are right. I did more measurements but I did not post them. 

In order to demonstrate the issue I created two separate clean WP 5.5 installs with default TwentyTwenty theme and Query monitor plugin. One website has WC 4.3.3, another 4.4.1. No other plugins. Websites are on the same local server.

I refreshed both websites several times. It is always the same result.

**Shop page**


**Woocommerce 4.3.3** - 66 queries

![image](https://user-images.githubusercontent.com/26632549/91745893-01839100-ebbc-11ea-939c-56cee6f02cea.png)

**Woocommerce 4.4.1** - 206 queries

![image](https://user-images.githubusercontent.com/26632549/91745943-1829e800-ebbc-11ea-9758-3a6295642680.png)


**Category page**

**Woocommerce 4.3.3** -45 queries

![image](https://user-images.githubusercontent.com/26632549/91746174-8078c980-ebbc-11ea-81e9-0b2ab202c461.png)

**Woocommerce 4.4.1** - 97 queries

![image](https://user-images.githubusercontent.com/26632549/91746292-aa31f080-ebbc-11ea-9136-776113099b32.png)


**Average TTFB after 10 page refreshes**

- Woocommerce 4.3.3 = 100ms
- Woocommerce 4.4.1 = 400ms

**Comment by lkraav** [comment] 2020-09-01 06:44
OK, but how about clicking through into the queries list and see what's in there?

**Comment by maticluznarow** [comment] 2020-09-01 08:06
Here are query lists. I am sorry about the look. I just copied table to html file.

Woocommerce 4.3.3 - https://tinyurl.com/y67mekoj
Woocommerce 4.4.1 - https://tinyurl.com/yxjjp764

**Comment by Camilo517** [comment] 2020-09-28 01:04
Any news?

**Comment by rwkyyy** [comment] 2020-10-02 10:36
I'm also seeing this in 4.5.2 (latest)

**Comment by roykho** [comment] 2020-10-27 19:31
Hi @maticluznarow - Thanks for reporting this. However I am not able to reproduce the issue you're seeing. Note that since your testing 4.6 has been released so my tests are against 4.6. I am only seeing at most ~10 queries. In my test, I've dumped all caches between page refreshes for both different versions ( 4.3 and 4.6 ).

Since its been a little while now, can you please check and confirm you're still having this issue with 4.6?

**Comment by Camilo517** [comment] 2020-10-27 23:59
hi @roykho 
Use WooCommerce 4.6.1
Only in the shop page 96 queries
http://prntscr.com/v8akl6

On the product page 87 queries

This is a serious problem

**Comment by roykho** [comment] 2020-10-28 01:31
HI @Camilo517 - so that total count doesn't mean much in of itself. You have to open up the component and see what other plugins are within it. Chances are its not all coming from WooCommerce core.

**Comment by maticluznarow** [comment] 2020-10-28 05:31
> Hi @maticluznarow - Thanks for reporting this. However I am not able to reproduce the issue you're seeing. Note that since your testing 4.6 has been released so my tests are against 4.6. I am only seeing at most ~10 queries. In my test, I've dumped all caches between page refreshes for both different versions ( 4.3 and 4.6 ).
> 
> Since its been a little while now, can you please check and confirm you're still having this issue with 4.6?

Hi, 

I ran some tests and I think the issue is gone. 

My Woocommerce results:

4.3.3
![image](https://user-images.githubusercontent.com/65150716/97396115-b8636b00-18e6-11eb-81da-d366f952cec4.png)

4.4.1
![image](https://user-images.githubusercontent.com/65150716/97396183-d92bc080-18e6-11eb-8c8f-c060a72f822e.png)

4.6.1
![image](https://user-images.githubusercontent.com/65150716/97396231-f19bdb00-18e6-11eb-8314-0b4156ba87a3.png)


@Camilo517 can you confirm this?

**Comment by Camilo517** [comment] 2020-10-28 18:18
@maticluznarow For example in the Shop page I only have two queries from another plugin, the others are all from woocommerce

**Comment by roykho** [comment] 2020-10-30 13:13
Hi @Camilo517 - how many queries are you seeing with version 4.6.1? What is the load time for you?

**Comment by roykho** [comment] 2020-11-09 14:13
So since the original issue is no longer relevant with the latest WC version and there are no other concerns, I will be closing this issue. If there are still other issues in regards to this, feel free to comment back so we can re-evaluate.

**Closed by roykho** 2020-11-09 14:13 UTC
Labels: performance, status: needs feedback
