### ISSUE TITLE
UPDATE button does not respond - no save and refresh action in 'Edit Order' page

### ISSUE THREAD

**Issue by LichtWesenNL** [woocommerce/woocommerce#27921] opened 2020-10-10 12:01 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
the button 'update' (or bijwerken in NL-version) on the 'Edit Order' page from Woocommerce doesn't respond. There is NO action, no refreshing of the page and more worrisome nothing can be saved after editing.

**Expected behavior**
I expect the button to do as it used to, save the edited order (details) and refresh the page.

**Actual behavior**
by clicking the button nothing happens

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
`
### WordPress Environment ###

WordPress address (URL): https://lichtwesenbenelux.com
Site address (URL): https://lichtwesenbenelux.com
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.33
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.46-MariaDB-1~xenial
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Totale databasegrootte: 57.44MB
Database datagrootte: 38.26MB
Database index grootte: 19.18MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.22MB + Index: 0.12MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 1.69MB + Index: 1.16MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_ahm_assets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ahm_download_stats: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ahm_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_st: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_submits: Data: 0.40MB + Index: 0.04MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.30MB + Index: 0.12MB + Engine MyISAM
wp_hustle_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hustle_entries_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_hustle_modules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hustle_modules_meta: Data: 0.19MB + Index: 0.03MB + Engine InnoDB
wp_hustle_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_logs: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mail_bank: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mail_bank_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mail_bank_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_maxbuttons_buttons: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_optins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_optin_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 1.71MB + Index: 0.09MB + Engine MyISAM
wp_popover_ip_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 9.90MB + Index: 2.19MB + Engine MyISAM
wp_posts: Data: 5.03MB + Index: 0.23MB + Engine MyISAM
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_exclusions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_statistics_historical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Data: 6.12MB + Index: 7.27MB + Engine MyISAM
wp_statistics_search: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_useronline: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_statistics_visit: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_statistics_visitor: Data: 8.09MB + Index: 5.30MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.04MB + Index: 0.08MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_testimonial_basics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.26MB + Index: 0.15MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_proforma_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.42MB + Index: 0.39MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.47MB + Index: 0.33MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.17MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 773
custom_css: 1
features: 1
inc_popup: 8
jetpack_migration: 2
logicblock: 4
nav_menu_item: 67
oembed_cache: 10
page: 24
post: 13
postman_sent_mail: 250
product: 444
product_variation: 215
qa_faqs: 7
revision: 36
shop_coupon: 18
shop_order: 626
shop_order_refund: 1
wc_membership_plan: 3
wc_user_membership: 59
wooframework: 44
wpcf7_contact_form: 2
wpdmpro: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

ManageWP - Worker: door GoDaddy – 4.9.7
WooCommerce (nl): door Pronamic – 1.1.7 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
Woo-Add-To-Carts: door LinkFlowUsers – 3.2.0 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
Advanced Custom Facebook Likebox Widget: door Alan Ferdinand – 1.2
All In One WP Security: door Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.4

Black Studio TinyMCE Widget: door Black Studio – 2.6.9
Klassieke editor: door WordPress-bijdragers – 1.6
Contact Form DB: door Michael Simpson – 2.10.29
Contact Form 7: door Takayuki Miyoshi – 5.2.2
Cookie Control: door Civic UK – 2.2
Download Manager: door W3 Eden – 3.1.10
Easy Smooth Scroll Links: door WebFactory Ltd – 2.2
Exclude Pages from Navigation: door Simon Wheatley – 1.92
HubSpot Alles-In-Een Marketing - Formulieren, Popups, Live Chat: door HubSpot – 7.44.6
Limit Login Attempts: door Johan Eenfeldt – 1.7.1
Postman SMTP: door Jason Hendriks – 1.7.2
Q and A FAQ and Knowledge Base for WordPress: door Raygun – 1.0.6.2
WooCommerce Sisow Betaal Opties: door Sisow – 5.5.2 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
Beoordeling: door Kevin Archibald – 4.4.9
User Switching: door John Blackbourn & contributors – 1.5.6
Widget Context: door Kaspars Dambis – 1.3.2
WooCommerce EU VAT Number: door WooCommerce – 2.3.25 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce Memberships: door SkyVerge – 1.19.1
WooCommerce MyParcel: door Richard Perdaan – 4.0.5 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.6.1
WooCommerce PDF Invoices & Packing Slips Professional: door Ewout Fernhout – 2.6.6 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce PDF Invoices & Packing Slips Premium Templates: door Ewout Fernhout – 2.9.9
WooCommerce: door Automattic – 4.5.2
Hustle: door WPMU DEV – 7.3.1
Yoast SEO: door Team Yoast – 15.0
WP Edit: door Josh Lobe – 4.0.4
WP Realtime Sitemap: door Daniel Tweedy – 1.5.7
WP Overnight Sidekick: door Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.2.2

Youtuber: door Roy Tanck – 1.8.2

### Inactive Plugins (11) ###

Header and Footer Scripts: door Digital Liberation – 2.2.1
iThemes Security: door iThemes – 7.8.0
Jetpack by WordPress.com: door Automattic – 9.0.2
WooCommerce Helper: door WooCommerce – 1.7.2 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2 – Netwerk geactiveerd
WooDojo: door WooThemes – 1.5.4
WP Clone by WP Academy: door WP Academy – 2.2.10
WP Date Remover: door Omar – 1.0
WP Mail SMTP: door WPForms – 2.4.0
WP Mail SMTP Plugin by Mail Bank: door Tech Banker – 4.0.12
WP Maintenance Mode: door Designmodo – 2.2.4
WP Statistics: door VeronaLabs – 12.6.13

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #30 - /winkel/
Winkelmand: #31 - /winkelwagen/
Afrekenen: #32 - /afrekenen/
Mijn account: #33 - /mijn-account/
Algemene voorwaarden: #1535 - /algemene-leveringsvoorwaarden/

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 3
GH USA:: Members: 0Access method: Manual assignment onlyAccess length: Unlimited ❌ The plan contains a rule to restrict all Producten to non-members
GH Nederland:: Members: 40Access method: Manual assignment onlyAccess length: Unlimited ❌ The plan contains a rule to restrict all Producten to non-members
GH België:: Members: 19Access method: Manual assignment onlyAccess length: Unlimited ❌ The plan contains a rule to restrict all Producten to non-members

### Action Scheduler ###

Afgerond: 261
Oldest: 2020-09-10 09:26:23 +0200
Newest: 2020-10-10 13:54:26 +0200

In afwachting: 1
Oldest: 2020-10-15 12:39:52 +0200
Newest: 2020-10-15 12:39:52 +0200

`
</details>

**Comment by juliaamosova** [comment] 2020-10-22 20:28
Hi @LichtWesenNL,

Apologies for the delayed response. 

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. I tested using WooCommerce 4.6.1. Please see the video below:

http://g.recordit.co/NoHu7TRONZ.gif

Can you please confirm if this is still an issue for you? If so, am I missing any steps to reproduce the issue?

**Comment by LichtWesenNL** [comment] 2020-10-23 07:35
Hi Julia,

thanks for reaching out. It’s no longer a problem.. Even with the 4.6.0 it only took 2 days to disapear ‘by itself’. 
I don’t know what caused it, but I’m glad it went away!

I now updated to 4.6.1 and am really glad everything works as ‘usual’ .

Thanks again,
infinite love,

Erica

p.s. breng iets moois in de wereld; deel je glimlach - elk moment, elke dag!
p.p.s. I LOVE YOU

Erica Hooft - 
LichtWesen Nederland


Volg je ons al op Facebook? www.facebook.com/lichtwesennederland
Kijk (ook zonder te registreren) naar interessante informatie die regelmatig geplaatst word! En als je daar dan toch bent, vergeet dan niet een ‘vind ik leuk’ achter te laten.


www.lichtwesennederland.nl
erica@lichtwesennederland.nl

**Comment by juliaamosova** [comment] 2020-10-23 13:33
Hi @LichtWesenNL,

Thanks for your follow-up! It sounds like a caching issue to me - maybe a caching plugin or some kind of a serve caching that could cause it. In any case, I am glad to hear that the issue is resolved.

I'll go ahead and close it but feel free to comment on it again in case I missed something and we'd take another look.

**Closed by juliaamosova** 2020-10-23 13:33 UTC
Labels: can't reproduce, status: needs feedback
