### ISSUE TITLE
Admin Orders : All Orders

### ISSUE THREAD

**Issue by NouvelleChambreClaire** [woocommerce/woocommerce#26509] opened 2020-05-14 13:58 UTC
The Tab : "All Orders" doesn't display any order after the las Wordpress' update. I have to click other tabs to see each status.

![image](https://user-images.githubusercontent.com/65350975/81943319-82ae1c80-95fb-11ea-94a7-02cf60c7fe37.png)

**Comment by juliaamosova** [comment] 2020-05-14 14:58
Hi @NouvelleChambreClaire,

Thank you for raising the issue.

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-05-21 14:00
Hi @NouvelleChambreClaire,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-05-21 14:00 UTC
Labels: status: needs feedback

**Comment by NouvelleChambreClaire** [comment] 2020-05-21 15:14
Hi Julia, 
I didn't try to desactivate some plugins and changing the storefront. I'm not webmaster this is not my cup of tea. I only handle the data about the products and the customers.
I'll now manage the customers data one by one and not with a view of all as before, until your new update....
But thanks for your response.

**Comment by juliaamosova** [comment] 2020-05-21 15:19
Hi @NouvelleChambreClaire, thanks for your follow-up. It is possible that the update won't fix the issue for you since we didn't work on that area to fix anything, to begin with. 

It is recommended that you perform a theme or plugin conflict to see what is causing the issue. Of course, it is always better to do it on the staging site (not the live site). You can find a handy guide by visiting [How to Test for Plugin and Theme Conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) which will, hopefully, empower you to do it yourself without hiring anyone.
