### ISSUE TITLE
Variable product edit bug

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#24098] opened 2019-07-08 10:49 UTC
I saw today with wc 3.6.5 at editing a variable product in tab variations with more then 20 variations that if I click on next button for moving to page 2 of variations I was asked to save before leaving this page. But I did not change anything, was only viewing and moving around.

**Comment by claudiosanches** [comment] 2019-08-01 20:07
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried the same and it appeared to work correctly.

> But I did not change anything, was only viewing and moving around.

Not sure what do you mean about "moving around", like if just navigation, or moving variations from the positions, because if you move any will enable the "Save Button".
Anyway if the "Save Button" is enabled, and asking to save before move, it's because some change has been made there, there's a script that watches for changes in that content.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-08-01 20:07 UTC
