### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function WC_Install::run_update_callback(), 0 passed in /app/wp-includes/class-wp-hook.php on line 286 and exactly 1 expected in /app/wp-content/plugins/woocommerce/includes/class-wc-install.php:190

### ISSUE THREAD

**Issue by javadev** [woocommerce/woocommerce#24593] opened 2019-09-08 09:23 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Update woocommerce with version 3.7, start database update. There is error in application console.

**To Reproduce**
1. Go to woocommerce admin page
2. Click on Update database
3. See error in console

```
2019-09-08T09:18:19.692116+00:00 app[web.1]: [08-Sep-2019 09:18:19 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Install::run_update_callback(), 0 passed in /app/wp-includes/class-wp-hook.php on line 286 and exactly 1 expected in /app/wp-content/plugins/woocommerce/includes/class-wc-install.php:190
2019-09-08T09:18:19.692123+00:00 app[web.1]: Stack trace:
2019-09-08T09:18:19.692254+00:00 app[web.1]: #0 /app/wp-includes/class-wp-hook.php(286): WC_Install::run_update_callback()
2019-09-08T09:18:19.692416+00:00 app[web.1]: #1 /app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
2019-09-08T09:18:19.692514+00:00 app[web.1]: #2 /app/wp-includes/plugin.php(531): WP_Hook->do_action(Array)
2019-09-08T09:18:19.692778+00:00 app[web.1]: #3 /app/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php(22): do_action_ref_array('woocommerce_run...', Array)
2019-09-08T09:18:19.693033+00:00 app[web.1]: #4 /app/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php(59): ActionScheduler_Action->execute()
2019-09-08T09:18:19.693323+00:00 app[web.1]: #5 /app/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php(80): ActionScheduler_Abstract_QueueRunner->process_action('138')
2019-09-08T09:18:19.693502+00:00 app[web.1]: #6 /app/wp-content/plugins/woocommer in /app/wp-content/plugins/woocommerce/includes/class-wc-install.php on line 190
```

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by javadev** [comment] 2019-09-13 20:46
👋

**Comment by javadev** [comment] 2019-09-18 06:34
🙄

**Comment by javadev** [comment] 2019-09-22 02:39
👋

**Comment by rodrigoprimo** [comment] 2019-09-24 14:17
@rrennick this issue seems related to Action Scheduler. Could you please take a look or point me to who can if you are not maintaining AS anymore?

On a quick search, I found two other reports of the same problem:

https://wordpress.org/support/topic/failed-migration-4/
https://wordpress.org/support/topic/woocommerce-database-update-running-since-6-hours/#post-11864572

**Comment by rrennick** [comment] 2019-09-24 17:21
@rodrigoprimo I'll have a look.

**Comment by rrennick** [comment] 2019-09-24 19:01
@rodrigoprimo I wasn't able to reproduce this. There must be some other condition that is needed to create the issue. The first of the 2 support threads would have been 3.6.X so it wouldn't be anything specific to the 3.7.0 update functions.

**Comment by javadev** [comment] 2019-09-24 22:01
You may check.my repository. https://github.com/php4dev/heroku-wordpress

**Comment by rodrigoprimo** [comment] 2019-09-26 14:19
@javadev are you able to reproduce this problem on an environment other than a Heroku app using the repository that you mentioned above? I'm asking since @rrennick was not able to reproduce this issue, so I'm wondering if it might be something specific to your environment. Thanks.

**Comment by javadev** [comment] 2019-09-26 15:07
I have only heroku and postgres.

**Comment by rodrigoprimo** [comment] 2019-09-30 17:45
I will close this issue as we were not able to reproduce it, but we will keep an eye out in case we get other reports similar to this one. Please leave a comment if you can reproduce this problem outside of your environment or if you discover more information that might explain what is causing the problem.

> postgres

I don't think this is related to the problem, but thought it was worth mentioning that Postgres is not officially supported by WooCommerce.

**Closed by rodrigoprimo** 2019-09-30 17:45 UTC
Labels: status: needs feedback

**Comment by khag7** [comment] 2019-11-06 01:01
Not sure if its bad practice to post in a closed issue but its related so here goes...

Two different plugins making use of the WC Action Scheduler are failing with this error.

https://github.com/woocommerce/woocommerce-admin/issues/3169
https://github.com/mailchimp/mc-woocommerce/issues/509

I'm unable to determine if its the WC Action Scheduler failing or if each of those plugins have an issue independently that's causing the same error. Or if there's some entirely different culprit unrelated to WC or to either of those plugins. Just thought I'd post it here as a sort of cross reference.
