### ISSUE TITLE
configure terms in attributes not working good

### ISSUE THREAD

**Issue by alkarradi** [woocommerce/woocommerce#25590] opened 2020-02-06 12:51 UTC
**Describe the bug**
when adding new attributes term then clicking add a loading icon appear next to the button but the term did not appear and when refreshing the page the term will appear in the terms

**To Reproduce**
1. Go to 'attributes'
2. if there is any attributes Click on 'Configure terms' or add new attributes and click Configure terms
3. Add new term and click add the loading icon will appear without adding the term 

**Screenshots**
![Image of Yaktocat](https://dentalmall.online/wp-content/uploads/2020/02/11.png)
**Expected behavior**

**WordPress Environment**
<details>

WordPress environment
--
WordPress address (URL): |   | https://dentalmall.online
Site address (URL): |   | https://dentalmall.online
WooCommerce version: |   | 3.9.1
WooCommerce REST API package: |   | 1.0.7 /home/u954277354/domains/dentalmall.online/public_html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
Log directory writable: |   | /home/u954277354/domains/dentalmall.online/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.3.2
WordPress multisite: |   | –
WordPress memory limit: |   | 1 GB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –
</details>

**Comment by juliaamosova** [comment] 2020-02-10 16:12
Hi @alkarradi,

Thank you for raising the issue. However, I can’t reproduce it on my end.

Here I am about to configure terms of `Type of Clothe` attribute:

![attr1](https://user-images.githubusercontent.com/19143190/74167269-ea7d5180-4c1f-11ea-95ea-5caec5102840.jpg)

And here is a gif showing that I can successfully add a term:

![](http://g.recordit.co/SJ3bWfdVPi.gif)

Do you have many plugins installed on your site? Do you use one of our default themes? 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-02-17 16:04
Hi @alkarradi,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-02-17 16:04 UTC
Labels: can't reproduce, status: needs feedback
