### ISSUE TITLE
Clear field "X" button not working on Admin edit order page

### ISSUE THREAD

**Issue by rockeypjb** [woocommerce/woocommerce#27263] opened 2020-08-07 18:18 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
While on the edit order page (when manually creating a new order or editing an existing order). The clear field "X" button on the select2 fields does not work. For example: trying to clear the "customer" field. Note that if I use an html inspector and increase the z-index of .select2-selection__clear I can then click the button. 

**Expected behavior**
"X" button should clear field

**Actual behavior**
"X" button is not clickable, therefore field is not cleared.  

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Dashboard>Woocommerce>Orders>Add Order
2. Click on Add Item>Add Product then add any product from your store
3. On the Add Products popup try to click on the "X" button on the far right of the drop down to clear the field
4. "X" does not work

- Same result if Customer field is populated and needs to be cleared.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
</details>

**Comment by juliaamosova** [comment] 2020-08-07 20:07
Hi @rockeypjb,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25427. We are closing your issue in favor of the previously submitted. 

Note that the issue had been fixed in https://github.com/woocommerce/woocommerce/pull/26202. The fix will be included in the upcoming WooCommerce 4.4 release. 

I confirmed that the issue is resolved by testing with WooCommerce 4.4 rc1:

![](http://g.recordit.co/GfSNeUgaeX.gif)

**Closed by juliaamosova** 2020-08-07 20:07 UTC
