### ISSUE TITLE
Woocommerce New Orders Emails Not Being Sent to Customers or To Me

### ISSUE THREAD

**Issue by yumyumtv1223** [woocommerce/woocommerce#16269] opened 2017-07-26 16:56 UTC
Hi,

Woocommerce New Orders Emails are Not Being Sent to Customers or To Me - I also tried to manually send emails to customers from Orders dashboard but this does not work either.

Please can this be fixed ... this looks very bad to customers.

Thanks for your help.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment] 2017-07-26 17:06
It's missing a lot of information on this issue, not filled any information and because of it I'm marking as invalid. Not to mention that I can't reproduce it using your "steps to reproduce the issue".
You should try check if your server is sending any email, there is a few plugins that you can check to test it.

**Closed by claudiosanches** 2017-07-26 17:06 UTC
