### ISSUE TITLE
Order says CANCELLED when it actually was processed via Paypal

### ISSUE THREAD

**Issue by licksnlove** [woocommerce/woocommerce#14899] opened 2017-05-05 15:33 UTC
### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</`
### WordPress Environment ###

Home URL: http://www.licksnlove.com
Site URL: http://www.licksnlove.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_09f5wtyzpw_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (22) ###

Akismet Anti-Spam: by Automattic – 3.3
All in one Favicon: by Arne Franken – 4.6
Custom Facebook Feed: by Smash Balloon – 2.4.5
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.10
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.7
Instagram Feed: by Smash Balloon – 1.4.8
Jetpack by WordPress.com: by Automattic – 4.8.2
MailChimp for WordPress: by ibericode – 4.1.1
Go Daddy Quick Setup: by GoDaddy.com
LLC – 1.06

Rotating Tweets (Twitter widget & shortcode): by Martin Tod – 1.9
ShareThis: by The ShareThis Team – 7.8
WooMedia WooCommerce USPS: by WooMedia Inc. – 2.2.5
Tumblr Crosspostr: by Meitar Moscovitz  – 0.9.0
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce Customizer: by SkyVerge – 2.4.0
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce - Table Rates: by WP Ronin – 1.6.0
WooCommerce: by Automattic – 3.0.3 – 3.0.5 is available
Yoast SEO: by Team Yoast – 4.6
WP LinkedIn: by Claude Vedovini – 2.5.4
WP Store Locator: by Tijmen Smit – 2.2.7
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Orangy
Version: 1.3
Author URL: http://themety.weebly.com/
Child Theme: ✔
Parent Theme Name: Twenty Twelve
Parent Theme Version: 2.2
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`>

**Comment by claudiulodro** [comment] 2017-05-05 18:28
We haven't had any other reports of this happening. Can you give me some more info? Steps to reproduce? Does it happen every time? Anything unusual in the order notes?

**Comment by claudiosanches** [comment] 2017-05-05 22:23
Need to setup the IPN: https://docs.woocommerce.com/document/paypal-standard/
If order is canceled is because your server is not receiving the PayPal IPN deny PayPal requests. ModSecurity and CloudFlare could be configured to deny external requests.
Closing since is not an issue with WooCommerce.

**Closed by claudiosanches** 2017-05-05 22:23 UTC
Labels: Status: Needs Author Reply / Changes

**Comment by snappytots** [comment] 2017-06-01 15:08
This exact thing is happening to me and I have been searching for help on this topic. I will try your suggestion.

**Comment by snappytots** [comment] 2017-06-01 15:09
...and i don't see how this is not an issue with woocommerce since it was working just fine before YOUR update.

**Comment by mikejolley** [comment] 2017-06-01 15:14
@snappytots there are lots of potential causes such as conflicts with plugins not updated with 3.0.x support. I suggest you test those before assuming it's a core bug (because a core bug would affect all users, not just a handful).

**Comment by zitzilin** [comment] 2017-06-07 23:07
For the past tow weeks all my paypal order have been cancelled even do the money was processed.
What am I suppose to do?

**Comment by mikejolley** [comment] 2017-06-08 09:34
Read the doc Claudio posted ^

**Comment by snappytots** [comment] 2017-06-08 13:43
Zitzilin go to Woocommerce, settings, inventory and make sure the "hold stock" is empty. This finally fixed mine.

**Comment by mikejolley** [comment] 2017-06-08 14:30
Thats not a fix, it's a workaround. You still need IPN to update your orders from pending (unpaid) to processing.

**Comment by snappytots** [comment] 2017-06-08 14:36
I change it to complete anyway so I don't care about that. I'm just
thankful they aren't being canceled.



[image: Snappy Tots] <http://shop.snappy-tots.com>
Heidi Yates  | Quirky Designer and Blogger
Snappy Tots | http://snappy-tots.com

[image: WebsiteGB] <http://shop.snappy-tots.com>   [image: email]
<heidi@snappy-tots.com>    [image: Facebook button]
<http://www.facebook.com/snappytots>  [image: Twitter button]
<http://www.twitter.com/snappytots>
email signature from companysig.com <http://www.companysig.com>
<http://www.companysig.com>

**Comment by mikejolley** [comment] 2017-06-08 15:48
Maybe look into PDT in our docs. It changes order status when the user returns to your site then.
