### ISSUE TITLE
401 error while creating order

### ISSUE THREAD

**Issue by ColorsSoftwarePvtLtd** [woocommerce/woocommerce#19505] opened 2018-03-23 11:04 UTC
I am creating order from iOS app but getting 401 error can not view the resource.When i see backend order created successfully.I used "Basic auth with consumer_key and consumer_secret" in headers.

I also tried as query parameters like 
**wp-json/wc/v2/orders?query_string_auth=true&consumer_key=ck_e9a6ed5e3261235f7a78230eb0a8a49693420&consumer_secret=cs_7d3c9f90fef71b92192112342fcdc95e61789ec63**

still i got same error.

 I do not understand how it is working in postman with out any error message.

Please help me.I struck in this from last one month

**Comment by mikejolley** [comment] 2018-03-23 11:42
> I do not understand how it is working in postman with out any error message.

If it's working in postman (or following https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API) it's not an API problem. The issue must be in the code/library you're using to make the request from iOS.

Ensure you're using `https` if sending keys over querystring. See https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https Not sure why `query_string_auth` is in your request. Thats not needed either.

You can use the slack community or forums if you need some advice from other users. Since this is working with postman, and we cannot reproduce, it doesn't appear to be a WC Rest API bug so I'm closing this issue.

**Closed by mikejolley** 2018-03-23 11:42 UTC

**Comment by ColorsSoftwarePvtLtd** [comment] 2018-03-23 13:00
Working in postman only when I pass keys in headers with basic authorization.
For below scenario, not working in post man also
 https://www.colorssoftware.co.uk/wp-json/wc/v2/orders?query_string_auth=true&consumer_key=ck_e9a225e326f8d5f3597a78230eb0a8a49693420&consumer_secret=cs_7d3c9f90fef71b921921fcer6fac95e61789ec63

getting  error
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot view this resource.",
    "data": {
        "status": 401
    }
}
![screen shot 2018-03-23 at 6 28 42 pm](https://user-images.githubusercontent.com/26897312/37830458-467c6966-2ec8-11e8-8066-89c63ce44f70.png)

**Comment by mikejolley** [comment] 2018-03-23 14:11
@ColorsSoftwarePvtLtd You may want to change those keys, this is not private...!

Why are you including `query_string_auth`?

**Comment by ColorsSoftwarePvtLtd** [comment] 2018-03-24 06:40
I removed **query_string_auth** from query parameter and  i had tried on post man, got same error.

Please help me to find out the problem

**Comment by mikejolley** [comment] 2018-03-24 09:27
Ensure the key was created by a user with read permission and go through the wiki doc.
