### ISSUE TITLE
Allow override of WC_Gateway_Paypal_IPN_Handler or just validate_currency and validate_amount

### ISSUE THREAD

**Issue by isvaljek** [woocommerce/woocommerce#29927] opened 2021-05-17 12:32 UTC
**Is your feature request related to a problem? Please describe.**
PayPal doesn't accept HRK currency. We do dynamic conversion before POST-ing to PayPal. PayPal's IPN notifies our server but with the currency that's different from the wc_order one, we get an error and the order status goes to on-hold.

**Describe the solution you'd like**
A way to override WC_Gateway_Paypal_IPN_Handler or just a way to shortcircuit currency and amount check. Maybe even a way to store payment currency along currency in wc_order, and to have PayPal gateway check that.

**Describe alternatives you've considered**
I sniffed around your code, but couldn't find a way to override any of this.

**Additional context**
Other people have this issue too:
https://stackoverflow.com/questions/30765934/validation-error-paypal-currencies-do-not-match-in-woocommerce/30877839#30877839

**Comment by zhongruige** [comment] 2021-05-18 16:27
Hi @isvaljek,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment] 2021-06-22 12:41
Hi @isvaljek 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions.

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel.

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

Meanwhile have you thought about extending the class? This way you can override the behavior of the IPN?

**Closed by roykho** 2021-06-22 12:41 UTC
Labels: needs developer feedback
