### ISSUE TITLE
Duplicate Categories 

### ISSUE THREAD

**Issue by JDSTIGER** [woocommerce/woocommerce#14861] opened 2017-05-03 20:48 UTC
### EXPLANATION OF THE ISSUE
Category dupes when adding products to it, if I try to remove the duplicate it removes both of them.

### STEPS TO REPRODUCE THE ISSUE
Add products to category using the "Bulk edit option" 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiulodro** [comment] 2017-05-04 15:21
I'm unable to reproduce this. Does this still happen with all other plugins turned off?

**Comment by JDSTIGER** [comment] 2017-05-04 17:45
@claudiulodro Hello, yea, it seems to only do it to parent categories.

**Comment by claudiosanches** [comment] 2017-05-04 21:08
Does luck like an issue with WooCommerce, since WooCommerce just use WordPress taxonomy system for it.
And I'm not able to reproduce too, maybe some plugin that you are using or your theme.
But there is no enough details to reproduce it, so I'm closing it. Thanks.

**Closed by claudiosanches** 2017-05-04 21:08 UTC

**Comment by benjaminthedev** [comment] 2017-05-06 11:16
I am totally getting this issue too and not sure how to fix it!

**Comment by JDSTIGER** [comment] 2017-05-07 03:48
@benjaminthedev  What plugins are you using, if I have it too it will most likely be the issue.

**Comment by soundshape** [comment] 2017-05-08 02:23
After updating to Woocommerce 3.0.5, some WooCommerce product categories (main & sub, but not all) are diplaying as duplicates on both admin and store sides of the site. I checked the wp_taxonomy table, and there is only one entry per product category. Trying to delete the duplicates with WP admin will delete the single wp_taxonomy entry leaving no category. This is clearly a parsing error caused by WooCommerce.  WC product categories tab display 50 categories by manual count, while the count displays '40 items', yet mySQL wp_taxomony table lists 39 entries with product_cat taxonomy.

Disabling all plugins except WooCommerce 3.0.5 made no difference.

Rolling back WooCommerce to 3.0.4 then 3.03 then 3.0.2 then 3.0.1 made no difference.

Deleting WooCommerce then installing 3.0.5 from WP repository made no difference.

Changing the active theme to StoreFront made no difference.

WP blog post categories taxonomies are uneffected and do not display as duplicates.

System Status
WC version: 3.0.5
WP version: 4.74
PHP version: 5.5.35

**Comment by JDSTIGER** [comment] 2017-05-08 18:58
@claudiulodro  @claudiosanches  Read above.

**Comment by JDSTIGER** [comment] 2017-05-18 18:40
Looks like they dont care >:(

**Comment by jessepearson** [comment] 2017-05-19 17:59
@JDSTIGER @benjaminthedev 
I tested this with the branch in #15182 and it corrected the issue. Thanks @soundshape for submitting a ticket and providing a copy of your site to test with, we wouldn't have been able to replicate this and fix it without your assistance.
