### ISSUE TITLE
CSV import fails for 'virtual' products

### ISSUE THREAD

**Issue by paulcee** [woocommerce/woocommerce#24109] opened 2019-07-09 15:21 UTC
I have generated some CSV files and am trying to import them into WooCommerce.

Take a look at the "Product CSV Import Schema" documented here:
https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema
It says that "Type" (the product type) can be any of the following:
simple, variable, grouped, external, variation, virtual, downloadable

I can successfully import "simple" products, but whenever I use "virtual" in that field, the import fails with "invalid product type". The attached file is an example that generates the error (I have removed the client's image URLs etc.).

[csv_virtual_bug.csv.txt](https://github.com/woocommerce/woocommerce/files/3373663/csv_virtual_bug.csv.txt)

Is this a bug in the importer or in the documentation? Any fix or workaround please?

**Comment by paulcee** [comment] 2019-07-10 14:31
I have noticed that when you add products manually (via Dashboard), the dropdown "Product data" list offers "Simple product", "Grouped product", "External/affiliate product" and "Variable product". It does not offer either Virtual or Downloadable: both of these are separate check-boxes.

So perhaps it's the case that you cannot specify "virtual" alone in an import, but must combine it with an item from the list: e.g. "simple, virtual"?  If so, then more clarity in the docs would be nice.

**Comment by rodrigoprimo** [comment] 2019-07-17 17:04
I was not able to reproduce this issue on a clean WooCommerce core install using the file that you provided. I had to edit the file to remove the "Images" column as they point to invalid URLs. But after doing that, the four products were successfully imported.

Are you able to reproduce this issue on a clean WooCommerce core install?

Closing this issue for now. Please leave a comment with more information if I missed something.

**Closed by rodrigoprimo** 2019-07-17 17:04 UTC
