### ISSUE TITLE
Purchased "store item" showing up as a pop-up on website with customers information.

### ISSUE THREAD

**Issue by talentedpen** [woocommerce/woocommerce#27998] opened 2020-10-17 02:07 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
- After purchasing a downloadable item from the store and confirming the purchase, a pop-up window to the bottom left of the screen shows up with the last item purchased by the customer and their mailing information. No matter what page I go to on my site the same pop-up window shows up 1-3 minutes after the pages loads. I am unable to remove the image even after clicking the "x" indicator to close the window. It reappears after 5-10 seconds and repeats on every page.

**Expected behavior**
- I expected the purchase to go through and return back to the home page without a pop-up window showing last purchaser and their personal information.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 
As I have previously stated a pop-up window is showing the last purchase and the purchaser's personal information for anyone else to see. Please see the attached photos.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'store'
2. Click on 'Paratus Assessments - The Complete Guidebook'
3. Scroll down to 'After completing the transaction go to Homepage and pop-up will show on the bottom left corner of page'

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>
`
### WordPress Environment ###

WordPress address (URL): https://paratusassessments.com
Site address (URL): https://paratusassessments.com
WC Version: 4.6.0
REST API Version: ✔ 4.6.0
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.1
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.11
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.0
WC Database Prefix: _0U5_
Total Database Size: 48.25MB
Database Data Size: 44.32MB
Database Index Size: 3.93MB
_0U5_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_0U5_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_actionscheduler_actions: Data: 0.09MB + Index: 0.04MB + Engine MyISAM
staging__0U5_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_actionscheduler_logs: Data: 0.06MB + Index: 0.05MB + Engine MyISAM
staging__0U5_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_mlw_qm_audit_trail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_mlw_questions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_mlw_quizzes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_mlw_results: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_options: Data: 8.10MB + Index: 0.09MB + Engine MyISAM
staging__0U5_platinumseometa: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
staging__0U5_pms_member_subscriptionmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_pms_member_subscriptions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_pms_paymentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_pms_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_postmeta: Data: 5.52MB + Index: 0.34MB + Engine MyISAM
staging__0U5_posts: Data: 0.97MB + Index: 0.08MB + Engine MyISAM
staging__0U5_psp_404_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
staging__0U5_psp_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
staging__0U5_psp_redirections_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
staging__0U5_tempmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
staging__0U5_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
<img width="1641" alt="Screen Shot 2020-10-16 at 5 56 55 PM" src="https://user-images.githubusercontent.com/73005640/96325928-484d0f00-0fe1-11eb-9be3-3e2d2e5af37b.png">
staging__0U5_trp_gettext_en_us: Data: 0.52MB + Index: 0.63MB + Engine InnoDB
staging__0U5_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
staging__0U5_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
staging__0U5_um_metadata: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
staging__0U5_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wc_product_meta_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
staging__0U5_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
staging__0U5_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_sessions: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging__0U5_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wpforms_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wpforms_entry_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wpforms_entry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging__0U5_wpforms_tasks_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
staging__0U5_yoast_indexable: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
staging__0U5_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
staging__0U5_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
staging__0U5_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
staging__0U5_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
_0U5_actionscheduler_actions: Data: 0.23MB + Index: 0.09MB + Engine MyISAM
_0U5_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_actionscheduler_logs: Data: 0.13MB + Index: 0.10MB + Engine MyISAM
_0U5_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_mlw_qm_audit_trail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_mlw_questions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_mlw_quizzes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_mlw_results: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_options: Data: 20.03MB + Index: 0.27MB + Engine MyISAM
_0U5_platinumseometa: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_0U5_pms_member_subscriptionmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_pms_member_subscriptions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_pms_paymentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_pms_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_postmeta: Data: 5.74MB + Index: 0.42MB + Engine MyISAM
_0U5_posts: Data: 1.19MB + Index: 0.11MB + Engine MyISAM
_0U5_psp_404_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_0U5_psp_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_0U5_psp_redirections_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_0U5_tempmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_0U5_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_trp_gettext_en_us: Data: 0.45MB + Index: 0.52MB + Engine InnoDB
_0U5_trp_original_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_0U5_trp_original_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_0U5_um_metadata: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_usermeta: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
_0U5_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
_0U5_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wc_product_meta_lookup: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
_0U5_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_0U5_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wpforms_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wpforms_entry_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_0U5_wpforms_entry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyI
<img width="1680" alt="Screen Shot 2020-10-16 at 6 57 54 PM" src="https://user-images.githubusercontent.com/73005640/96325998-d7f2bd80-0fe1-11eb-952e-ccd7b7da8c31.png">
<img width="1680" alt="Screen Shot 2020-10-16 at 6 57 54 PM" src="https://user-images.githubusercontent.com/73005640/96326092-a9c1ad80-0fe2-11eb-8153-cf70268537f1.png">
<img width="1680" alt="Screen Shot 2020-10-16 at 7 04 52 PM" src="https://user-images.githubusercontent.com/73005640/96326095-b3e3ac00-0fe2-11eb-9b19-aa5a28ecab4d.png">
<img width="1680" alt="Screen Shot 2020-10-16 at 7 05 17 PM" src="https://user-images.githubusercontent.com/73005640/96326097-b9d98d00-0fe2-11eb-9dd0-1f9b6b381e9e.png">
<img width="1680" alt="Screen Shot 2020-10-16 at 7 05 38 PM" src="https://user-images.githubusercontent.com/73005640/96326103-c52cb880-0fe2-11eb-8f4e-296b237bea73.png">

SAM
_0U5_wpforms_tasks_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
_0U5_yoast_indexable: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
_0U5_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_0U5_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_0U5_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_0U5_yoast_seo_links: Data: 0.16MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

attachment: 151
customize_changeset: 3
elementor_library: 12
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
language_switcher: 2
nav_menu_item: 18
oembed_cache: 6
page: 26
pms-subscription: 2
post: 5
product: 9
product_variation: 254
qmn_log: 11
qsm_quiz: 1
revision: 222
shop_coupon: 1
shop_order: 7
um_directory: 1
um_form: 3
wpforms: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

404page - your smart custom 404 error page: by Peter Raschendorfer – 11.2.6
Akismet Anti-Spam: by Automattic – 4.1.6
Bluehost: by Bluehost – 2.3
Elementor Pro: by Elementor.com – 3.0.5
Elementor: by Elementor.com – 3.0.11
Facebook for WooCommerce: by Facebook – 2.0.5 – Installed version not tested with active version of WooCommerce 4.6.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.12.3
HT Mega - Absolute Addons for Elementor Page Builder: by HasThemes – 1.4.7
Jetpack by WordPress.com: by Automattic – 9.0.2
Google Ads & Marketing by Kliken: by Kliken – 1.0.5 – Installed version not tested with active version of WooCommerce 4.6.0
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.6.0
Official Facebook Pixel: by Facebook – 2.2.0
OptinMonster API: by OptinMonster Team – 1.9.17 – Installed version not tested with active version of WooCommerce 4.6.0
Paid Member Subscriptions: by Cozmoslabs – 2.2.1 – Installed version not tested with active version of WooCommerce 4.6.0
Printful Integration for WooCommerce: by Printful – 2.1.16
Surveymonkey Button: by hintsolutions – 1.1
Ultimate Member: by Ultimate Member – 2.1.11
WooCommerce Stripe Gateway: by WooCommerce – 4.5.3 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Payments: by Automattic – 1.6.0
WooCommerce Shipping & Tax: by Automattic – 1.25.0 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce: by Automattic – 4.6.0
Yoast SEO: by Team Yoast – 15.1.1
WP File Manager: by mndpsingh287 – 6.9
WPForms Custom Captcha: by WPForms – 1.3.0
WPForms Surveys and Polls: by WPForms – 1.6.2
WPForms: by WPForms – 1.6.3

### Inactive Plugins (4) ###

Platinum SEO Pack: by Techblissonline.com (Rajesh) – 2.2.0
Profile Builder: by Cozmoslabs – 3.2.9
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 1.8.4 – Installed version not tested with active version of WooCommerce 4.6.0

WP Shopify: by WP Shopify – 3.5.0

### Dropin Plugins (2) ###

db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (2) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2457 - /shop/
Cart: #779 - /cart/
Checkout: #780 - /checkout/
My account: #781 - /my-account/
Terms and conditions: #789 - /home/terms-conditions/

### Theme ###

Name: Consulting
Version: 1.2.16
Author URL: https://www.thinkupthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 342
Oldest: 2020-10-11 16:19:35 -0700
Newest: 2020-10-16 18:01:11 -0700

Failed: 4
Oldest: 2020-07-14 13:14:35 -0700
Newest: 2020-08-04 09:28:10 -0700

Pending: 2
Oldest: 2020-10-17 15:23:20 -0700
Newest: 2020-10-22 03:18:10 -0700

`

**Comment by tammullen** [comment] 2020-10-19 09:58
Hi @talentedpen 

Thank you for raising the issue. 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
https://docs.woocommerce.com/document/how-to-test-for-conflicts/
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-10-29 18:19
Hi @tammullen,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-10-29 18:19 UTC
Labels: status: needs feedback
