### ISSUE TITLE
Urgent: Firefox & Chrome didn’t send any data. - ERR_EMPTY_RESPONSE + video + only WC + WP

### ISSUE THREAD

**Issue by lordspace** [woocommerce/woocommerce#27283] opened 2020-08-11 12:33 UTC
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
I have turned on/off WP debugging and apache conf.
SSLCompression        off
SSLSessionCache none
enabled all kinds of debugging and still nothing.

**Describe the bug**
The WP site doesn't load at all in chrome or firefox.
WooCommerce is activated with a WP 2019 theme

**Expected behavior**
The page to load

**Actual behavior**
When I access the page from the browser shows this error.

![image](https://user-images.githubusercontent.com/137558/89895471-89413580-dbe4-11ea-97e2-221e18ae698f.png)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

here's a video: https://youtu.be/l5AjSNaDDFw

Here's a showing that when I turn on or off WC it crashes the site.
https://youtu.be/IPJ94jxV6XI

Steps to reproduce the bug:

My developer initially followed these steps but after WC started crashing I've removed all the extra plugins and themes and set the theme to be WP 2019 and it still crashes.

Installed WP Ocean theme.
Installed required WP Ocean Extra plugin.
Installed required Elementor.
Installed required WooCommerce.

**Screenshots**
already shared two videos

**Isolating the problem (mark completed items with an [x]):**
n/a

**It's really interesting that when I access the site like this I get partial output and then it gets interrupted.**
curl -vvv 'https://orb-design2.eu1.wpsandbox.org/'

I am wondering if it has to do with content-length ?

**WordPress Environment**
OS:     Linux 4.15.0-69-generic #78-Ubuntu SMP Wed Nov 6 11:30:24 UTC 2019 x86_64
Shell:  /bin/false
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.8
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/vhosts/...../site/orb-design2.eu1.wpsandbox.org/htdocs
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0

**lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**apachectl -M**
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_itk_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 proxy_module (shared)
 proxy_html_module (shared)
 proxy_http_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 unique_id_module (shared)
 xml2enc_module (shared)

**php -v**
PHP 7.4.8 (cli) (built: Jul 13 2020 16:45:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies

**Comment by juliaamosova** [comment] 2020-08-11 14:34
Hi @lordspace,

Thanks for raising the issue. However, there is very little for us to work with in order for us to understand what could be going on. Are there any errors in the error log that may shed the light on what could be happening?

**Comment by lordspace** [comment] 2020-08-11 14:53
Hi,

The WP debug log has only stuff related to wp-cli.
https://orb-design2.eu1.wpsandbox.org/wp-content/debug.txt

debugging is enabled
```
define( 'WP_DEBUG_LOG', true ); // qs
define( 'WP_DEBUG_DISPLAY', true ); // qs
define( 'WP_DEBUG', true ); // qs
```

These are other php logs
https://orb-design2.eu1.wpsandbox.org/wp-content/php.txt


The apache logs only contain the usual stuff

**Comment by lordspace** [comment] 2020-08-11 14:57
I have turned off the mod deflate in apache. The admin area loads now but the public side is still partially rendered.
I can't view the source of the page at all

![image](https://user-images.githubusercontent.com/137558/89913135-07f59d00-dbfc-11ea-9d51-817f77287c59.png)

**Comment by lordspace** [comment] 2020-08-11 14:59
the chrome console shows this:
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

does WooCommerce try to compress the output?

**Comment by lordspace** [comment] 2020-08-11 15:04
Since the admin area loaded here's the WC system log

### WordPress Environment ###

WordPress address (URL): https://orb-design2.eu1.wpsandbox.org
Site address (URL): https://orb-design2.eu1.wpsandbox.org
WC Version: 4.3.2
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.4.8
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.44-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.2
WC Database Prefix: x_58c90ee3_
Total Database Size: 9.55MB
Database Data Size: 5.04MB
Database Index Size: 4.51MB
x_58c90ee3_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
x_58c90ee3_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
x_58c90ee3_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
x_58c90ee3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
x_58c90ee3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
x_58c90ee3_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_actionscheduler_logs: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
x_58c90ee3_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
x_58c90ee3_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_options: Data: 1.05MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_postmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
x_58c90ee3_posts: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
x_58c90ee3_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
x_58c90ee3_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
x_58c90ee3_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
x_58c90ee3_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
x_58c90ee3_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
x_58c90ee3_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
x_58c90ee3_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
x_58c90ee3_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
x_58c90ee3_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
x_58c90ee3_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 63
custom_css: 2
elementor_library: 2
nav_menu_item: 61
oceanwp_library: 1
page: 11
post: 7
product: 12
product_variation: 2
revision: 1
shop_order: 351

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.3.2

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

sandbox.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #1035 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 356
Oldest: 2020-08-10 08:48:51 +0000
Newest: 2020-08-11 12:17:09 +0000

**Comment by lordspace** [comment] 2020-08-11 15:09
Increased the php memory to 512MB and still the same error.

**Comment by tammullen** [comment] 2021-03-25 20:38
Hi @lordspace 

Sorry for the delay in replying.

Unfortunately it is very hard to determine what could be happening here. Although you have tried with only WooCommerce active it appears like the messages in the debug log are related to Ocean Extra plugin.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 20:38 UTC
Labels: has feedback
