### ISSUE TITLE
PHP errors with version 7.2 and WPEngine hosting

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#22404] opened 2019-01-10 00:41 UTC
**Describe the bug**
Quality Monitor shows PHP warnings specific to WooCommerce files.
`Parameter 1 to wp_default_scripts() expected to be a reference, value given`

**To Reproduce activate**
WordPress 5.0.3.
WooCommerce 3.5.3

**Screenshots**
![Screenshot](http://cld.wthms.co/aeTptI+)
Screenshot link: http://cld.wthms.co/aeTptI

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://mightymorphin.wpengine.com
Site URL: https://mightymorphin.wpengine.com
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.12-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.6.42-84.2-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.51MB
Database Data Size: 2.64MB
Database Index Size: 0.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.03MB + Index: 0.05MB
wp_postmeta: Data: 0.08MB + Index: 0.03MB
wp_posts: Data: 0.03MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 3
jetpack_migration: 2
page: 9
post: 2
product: 12
product_variation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn & contributors – 3.2.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.6
WooCommerce Services: by Automattic – 1.18.0
WooCommerce Square: by WooCommerce – 1.0.34
WooCommerce: by Automattic – 3.5.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by BlackWireKevin** [comment] 2019-01-10 00:52
Having this issue as well

**Comment by rrennick** [comment] 2019-01-10 13:55
@johndcoy Can you tell us what screen you are on when those warnings are logged?

**Comment by BlackWireKevin** [comment] 2019-01-10 16:50
> @johndcoy Can you tell us what screen you are on when those warnings are logged?

I see these warnings on every single page click. Both the front end and back end of the site.

**Comment by rrennick** [comment] 2019-01-10 18:34
If you search this repository (upper left) you will find that the only reference to `wp_default_scripts` is this issue. You'll need to get more details from WP Engine on these warnings.

**Comment by kloon** [comment] 2019-01-16 10:18
I know WPEngine does a lot with scripts on their platform so it is likely that they are intercepting scripts and concatenating them perhaps, which they perhaps do something wrong with ending up with this error.

I am not able to reproduce this locally on a PHP 7.2 install. Would be great if you can follow up with WPEngine and post details here on the findings.

Closing for now, but can reopen if we have steps to replicate this on a clean install.

**Closed by kloon** 2019-01-16 10:18 UTC
Labels: bug, status: needs feedback
