### ISSUE TITLE
Forcing relative https scheme for remote images

### ISSUE THREAD

**Issue by dima-stefantsov** [woocommerce/woocommerce#16748] opened 2017-09-07 17:51 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Override image url using one of default filters, let's say 'woocommerce_placeholder_img_src'
2. Make it be an external image with http:// scheme. For example http://imageprovider.ru/imgsrc.jpg
3. Have it displayed on a https://test.com site

## Expected/actual behavior

When I follow those steps, I see...
Instead of http://imageprovider.ru/imgsrc.jpg which I set, I see //imageprovider.ru/imgsrc.jpg , since it's on https site, it acts as https link, which is unavailable for imageprovider.ru , result: no image displayed.

I was expecting to see...
an image. Browser developer console will show unsafe content warning, but image will still be displayed.

I was also expecting to see a filter to override this relative replace. Here is two options, first is better, second is ok:
1st:
```
return apply_filters( 'woocommerce_product_image_relative', true ) ? str_replace( array( 'https://', 'http://' ), '//', $image ) : $image;
```

2nd:
```
$image = str_replace( array( 'https://', 'http://' ), '//', $image );
return apply_filters( 'woocommerce_product_image', $image, $size, $attr, $placeholder );
```

But my pull request and issue I started is closed with comments by @mikejolley , trying to explain I don't need it. I don't need to have images displayed. I don't need to be able to filter image url.

Every time I try to communicate with woocommerce github, mikejolley appears, closes my topics, tells me I don't need it. This is not the first time. Previously I thought he is The Woocommerce, it is just this hostile to any ideas. But just now I have seen @claudiulodro http://4.stefantsov.com/s/2017.09.07_20.39.13_an8en36q.png here and understood mikejolley is just my bad luck, there are people here who could Understand. This is not lost. I will speak and people will listen.

User, me, should have control over image urls. Before mikejolley commit https://github.com/woocommerce/woocommerce/commit/e7fb89be5fc6b89dff3506ebdd618ab436a9b062 woocommerce  gave such freedom. Now it is lost. Forceful str_replace is applied **AFTER** all filters.
This is not right. Please let me decide what my image url will be. I think it's common sense. It does not need proving. Mikejolley maybe not okay with that because it's his commit that was bad, that broke my sites, and he tries to prove wrong.

Is it not obvious developers should have control over image urls?
**Then please help me.**

I've spent about 5 minutes writing code to fix this nuisance, and many hours trying to prove the common sense of "urls should be able to be modified as developer wants".

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://test.local
Site URL: https://test.local
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache/2.4.20 (Win64) OpenSSL/1.0.2h PHP/7.0.8
PHP Version: 7.0.8
PHP Post Max Size: 1 GB
PHP Time Limit: 0
PHP Max Input Vars: 2500
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.15
Max Upload Size: 10 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Cyr to Lat enhanced: by Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.5

Disable Emojis: by Ryan Hellyer – 1.7
Widget Logic: by wpchefgadget
alanft – 5.8.2

WooCommerce Show Attributes: by Isabel Castillo – 1.6.2
WooCommerce: by Automattic – 3.1.2
Yoast SEO: by Team Yoast – 5.3.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: RUB ( руб.)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront Child
Version: 6
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8 – 2.2.5 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/single-product\add-to-cart\simple.php
storefront-child/woocommerce/single-product\price.php
storefront-child/woocommerce/single-product\tabs\description.php

`
</details>

**Comment by dima-stefantsov** [comment] 2017-09-07 17:56
It's really hurtful experience to communicate on woocommerce github.

- "Let me modify image urls the way I want them".
- "Nop, you don't need it, CLOSED".
...
...
???
...
=((

**Comment by claudiulodro** [comment] 2017-09-07 19:06
Duplicate of #16746 so I have to close this. We'll investigate a good solution further and this issue will be linked from #16746.

**Closed by claudiulodro** 2017-09-07 19:06 UTC
