### ISSUE TITLE
Refund not showing Fee amount

### ISSUE THREAD

**Issue by matty0501** [woocommerce/woocommerce#24642] opened 2019-09-16 13:56 UTC
**Describe the bug**
If I have an order with a fee, and refund the fee, the amount of tax refunded for that fee is showing, but the non-tax amount refunded is not showing.

For instance, I have a fee of £10 on an order. On this fee, I refund £5 + £1 tax (total of £6 refund). The £1 refund for the tax shows for the fee on the order, but the £5 refunded does not. This can be seen in the screenshots below.

If I try to get meta from the refund object regarding the refunded fee, the 'total' shows as 0, whilst the 'total_tax' is showing the correct amount of tax refunded:
```
foreach ( $refund->get_fees() as $fee ){
	
	echo $fee->get_total(); //Returns 0, not -5 as would be expected
	echo $fee->get_total_tax(); //Returns -1, which is as expected
	
}
```

**Screenshots**
![Refund 1](https://user-images.githubusercontent.com/17788098/64963408-1b37a580-d891-11e9-828a-d3022b47a49c.png)
![Refund 2](https://user-images.githubusercontent.com/17788098/64963417-2094f000-d891-11e9-9ed3-4a5ea80523e4.png)

**Expected behavior**
I would expect that the refund amount would show for the fee excluding tax as well as for the fee tax, as it does for all other order items (like products and shipping).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.
I discovered this on my production site. I have then replicated the behaviour on a staging site that is running the default Twenty Nineteen theme with only WooCommerce installed.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://157.245.37.33
Site address (URL): http://157.245.37.33
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.19-0ubuntu0.18.04.2
PHP Post Max Size: 16 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.27-0ubuntu0.18.04.1
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.66MB
Database Data Size: 1.69MB
Database Index Size: 0.97MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.08MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.7.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /
Basket: #7 - /basket/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://en-gb.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-09-14 12:52:12 +0100
Newest: 2019-09-14 12:52:12 +0100

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by MichaelBengtsson** [comment] 2019-10-21 13:23
We are having issues with this error as well, it seems like the change done with the 3.6.0 release is causing this. 

This commit seems to be the issue: 9529d6eee72510b1422d6e1a6d8d02b7a315acab
The removal of line 1470.
`$item->set_total( $amount );`

**Comment by rodrigoprimo** [comment] 2020-03-09 20:25
I'm not able to reproduce this problem on a store running WooCommerce 3.9.3. Here are the steps that I followed to try to reproduce it:

- I placed an order for a product that costs $55 in a store configured to charge 20% in taxes.
- Edited the order in the admin and added a $10 fee (plus $2 in taxes).
- Refunded $5 of the fee and $1 of the tax. Confirmed that WooCommerce displays the refunded amount for both the fee and the tax:

![Screenshot from 2020-03-09 17-18-18](https://user-images.githubusercontent.com/77215/76253804-18a77e80-622a-11ea-976a-55fc7f6672dd.png)

Maybe this problem was fixed in a recent version? I'm closing this issue for now, but please leave a comment if you are still experiencing it, and I will take a second look. Thanks.

**Closed by rodrigoprimo** 2020-03-09 20:25 UTC
Labels: bug, priority: high
