### ISSUE TITLE
[3.5] image placeholder doesn't adjust to custom aspect ratio

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce#21705] opened 2018-10-26 21:48 UTC
### Describe the bug
WC 3.5 was to introduce a new feature to make the image placeholder match the custom ratio. See https://github.com/woocommerce/woocommerce/pull/20644. However, it appears this feature is entirely nonfunctional.

### To Reproduce
1. Setup a site with dummy data, **and also** with a product without an assigned image.
2. Go to Customizer > WooCommerce > Product Images
3. Choose "Custom" and set it to 4:3 (example).
4. Save.
5. Go to Shop (front-end). You will note that images are 4:3, but the placeholder remains square.

Same bug regardless whether custom placeholder is set in Settings.

### Expected behavior
The placeholder should match the custom ratio set in the Customizer.

### Isolating the problem (mark completed items with an [x]):
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://testingwp123.wpengine.com
Site URL: https://testingwp123.wpengine.com
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.11-2+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0h

SUHOSIN Installed: –
MySQL Version: 5.7.23-23-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
Total Database Size: 3.11MB
Database Data Size: 2.08MB
Database Index Size: 1.03MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.23MB + Index: 0.06MB
wp_postmeta: Data: 0.17MB + Index: 0.14MB
wp_posts: Data: 0.11MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 27
custom_css: 1
customize_changeset: 2
nav_menu_item: 3
page: 8
post: 11
product: 18
product_variation: 7
revision: 1
wp_block: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

ManageWP - Worker: by ManageWP – 4.6.3
Storefront Powerpack: by WooCommerce – 1.4.12
WooCommerce: by Automattic – 3.5.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #51 - /shop/
Cart: #52 - /cart/
Checkout: #53 - /checkout/
My account: #54 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Homestore
Version: 2.0.26
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.3.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: homestore/woocommerce/single-product/title.php
`
</details>

**Comment by rodrigoprimo** [comment] 2018-10-30 14:35
I was able to reproduce this issue. Here is a screenshot of the shop page and the placeholder image is not respecting the custom aspect ratio:

![screenshot from 2018-10-30 11-32-39](https://user-images.githubusercontent.com/77215/47725717-d0407f80-dc37-11e8-80fb-1364d5c15b1a.png)

**Comment by claudiulodro** [comment] 2018-11-20 19:10
This only seems to affect the default placeholder image. 

If you set a placeholder image by attachment ID in the WC settings it gets resized correctly. 

If you set a placeholder image by URL in the WC settings it will not get resized, and this is expected behavior. WordPress has no way to generate cropped images from an image URL.

**Comment by GlennMartin1** [comment] 2018-11-20 19:22
> If you set a placeholder image by attachment ID in the WC settings it gets resized correctly.

Incorrect. I tried this again right now. I can confirm that (1) **default** and (2) **custom by attachment ID** - these BOTH do **not** resize to the aspect ratio set in the Customizer.

I understand that **custom set by URL** will not resize.

**Comment by GlennMartin1** [comment] 2018-11-20 19:48
> If you set a placeholder image by attachment ID in the WC settings it gets resized correctly.

After more testing:
(1) (BUG) **default image placeholder** does **not** resize
(2) **attachment ID placeholder** does resize under certain conditions *
(3) **URL to placeholder** does not work (as expected)

`*` **attachment ID placeholder** does resize **only if** the image aspect ratio is taller (more square) than what is set in the Customizer. However, (BUG) if the image aspect ratio is shorter (more rectangular) than what is set in the Customizer, it does not compensate by adding space above/below.

**Comment by mikejolley** [comment] 2019-01-14 11:24
`woocommerce_placeholder_image` setting is created on install/update. If the setting in product settings is inadvertably removed or changed to a non-image, this resize logic cannot work. An attachment is needed.

> (1) (BUG) default image placeholder does not resize

Not a bug. If the setting is missing, the default fallback cannot resize - it's not an attachment. Matches older versions of WC.

> (3) URL to placeholder does not work (as expected)

No where in the UI does it state that images or placeholders will be resized. External images by URL will work the same as the default image placeholder - no resizing is possible without an attachment.  Again, UI makes no mention of resizing so using the size the user provides makes sense (I'd expect a user using this setting to provide an image which fits with their other image aspect ratios).

> (2) attachment ID placeholder does resize under certain conditions *

This is potentially the only issue to look at. 

> if the image aspect ratio is shorter (more rectangular) than what is set in the Customizer, it does not compensate by adding space above/below.

Not sure if WP can do that but I'll take a look. Of course, also resolvable by customising the placeholder image.

**Comment by mikejolley** [comment] 2019-01-14 14:01
Fixed in https://github.com/woocommerce/woocommerce/pull/22443

**Closed by mikejolley** 2019-01-14 14:01 UTC
Labels: bug
