### ISSUE TITLE
Product Image Fail to assign

### ISSUE THREAD

**Issue by lehmann45** [woocommerce/woocommerce#18260] opened 2017-12-21 16:46 UTC
When I try to assign the image of the product it does not load it, it seems that the path with the image folder was lost. In the gallery I see a gray box, change the image and does not assign it to the product.
The gallery works well, if I add 5 images to the gallery of the product, load them without problem.

Everything was fine, until I updated to version 3.2.6

Can someone help me?

![image](https://user-images.githubusercontent.com/12647191/34268376-0e1bba92-e646-11e7-9d80-f52aab5f38bd.png)

![image](https://user-images.githubusercontent.com/12647191/34268519-a3f33b44-e646-11e7-9e8d-e98c4368c50e.png)

![image](https://user-images.githubusercontent.com/12647191/34268605-fec18a3a-e646-11e7-94b9-70c6212fc243.png)

**Comment by claudiosanches** [comment] 2017-12-21 19:43
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried upload images to products, and it appeared to work correctly.

It could be some plugin that you have installed.

Please post back if you can provide more details on how to reproduce this issue. Since you ignored the issue template, there is no way to have any idea of what is happing. For now, I’m am closing this as non-reproducable.

Thanks

**Closed by claudiosanches** 2017-12-21 19:43 UTC

**Comment by claudiulodro** [comment] 2017-12-21 19:47
It looks like the problem is in the WordPress media library since it's not showing up in there. That's not something we control with WooCommerce. (WP 4.9 was released the same day as WC 3.2.6 is probably causing an issue with one of your plugins)

**Comment by dspixel** [comment] 2018-01-03 11:02
Try to deactivate the "WooCommerce PayPal Express Checkout Gateway" plugin.
