### ISSUE TITLE
Creating product variations for more than 4 attributes with 12 values each fails

### ISSUE THREAD

**Issue by chromechris** [woocommerce/woocommerce#25683] opened 2020-02-17 01:46 UTC
**Describe the bug**
When I try creating all product variations from one product with more than 4 attributes (5, 6, 7 etc) with 12 values for each attribute, I get a never-ending loading graphic that never ends, and not even 1 variation is created.

**To Reproduce**
1. Create 5 product attributes with 12 values in each attribute for a certain product in the Products functionality of WooCommerce
**Screenshots**
![Screenshot_2020-02-16 Edit Product ‹ Products ‹ Civil Concrete LLC — WooCommerce](https://user-images.githubusercontent.com/16638698/74616938-ca4e0680-50e7-11ea-9ac0-1b94ab8be059.png)

**Expected behavior**
Loading graphic will run forever, and no variations will be created.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated all other plugins and confirmed this bug occurs when only WooCommerce plugin is active. Done through Tools-->"Site Health" Plugin-->Troubleshooting-->Enable Troubleshooting Mode
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). Done through Tools-->"Site Health" Plugin-->Troubleshooting-->Enable Troubleshooting Mode
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://civilconcretellc.com
Site address (URL): https://civilconcretellc.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.27
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.44-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: cvlcnrtllc
Total Database Size: 16.66MB
Database Data Size: 15.21MB
Database Index Size: 1.45MB
cvlcnrtllcwoocommerce_sessions: Data: 0.92MB + Index: 0.06MB + Engine MyISAM
cvlcnrtllcwoocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwoocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllccleantalk_sessions: Data: 0.08MB + Index: 0.05MB + Engine MyISAM
cvlcnrtllccleantalk_sfw: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllccleantalk_sfw_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllccleantalk_spamscan_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllccommentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cvlcnrtllccomments: Data: 0.22MB + Index: 0.16MB + Engine MyISAM
cvlcnrtllclinks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcmailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcmailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcmp_timetable_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcoptions: Data: 3.96MB + Index: 0.38MB + Engine MyISAM
cvlcnrtllcpostmeta: Data: 8.11MB + Index: 0.42MB + Engine MyISAM
cvlcnrtllcposts: Data: 1.88MB + Index: 0.24MB + Engine MyISAM
cvlcnrtllctermmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cvlcnrtllcterms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cvlcnrtllcterm_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
cvlcnrtllcterm_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cvlcnrtllcusermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
cvlcnrtllcusers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cvlcnrtllcwc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cvlcnrtllcwc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
cvlcnrtllcwc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cvlcnrtllcwc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 250
cherry-services: 13
customize_changeset: 28
elementor_library: 1
jet-menu: 5
mp-column: 7
mp-event: 9
nav_menu_item: 68
page: 22
post: 11
product: 5
product_variation: 52
projects: 12
revision: 161
scheduled-action: 796
team: 8
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

All-in-One WP Migration: by ServMask – 7.16
Booked Add-On: Calendar Feeds: by Boxy Studio – 1.1.6
Booked Add-On: Front-End Agents: by Boxy Studio – 1.1.16
Booked Add-On: WooCommerce Payments: by Boxy Studio – 1.5.3 – Not tested with the active version of WooCommerce
Booked: by Boxy Studio – 2.2.5
Cherry Projects: by Cherry Team – 1.2.15
Cherry Services List: by Zemez – 1.4.7
Cherry Sidebars: by Zemez – 1.1.3
Cherry Team Members: by Zemez – 1.4.6
Anti-Spam by CleanTalk: by СleanTalk  – 5.133
Contact Form 7: by Takayuki Miyoshi – 5.1.6
Elementor: by Elementor.com – 2.8.5
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Health Check & Troubleshooting: by The WordPress.org community – 1.4.2
Jet Data Importer: by Zemez – 1.2.2
JetElements For Elementor: by Crocoblock – 2.2.6
JetMenu: by Crocoblock – 1.5.15
Jet Plugins Wizard: by Zemez – 1.2.2
JetTabs For Elementor: by Crocoblock – 2.1.1
Jetpack by WordPress.com: by Automattic – 8.1.1
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 7.18.81
Mailchimp for WooCommerce: by Mailchimp – 2.3.1 – Not tested with the active version of WooCommerce
Timetable and Event Schedule: by MotoPress – 2.3.4
W3 Total Cache: by BoldGrid – 0.13.0
Woo Category Base Permalink Fixer: by MasterNs – 2.3 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.25.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.19
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3
WooCommerce: by Automattic – 3.9.2

### Inactive Plugins (1) ###

Improved Product Options for WooCommerce: by 7VX LLC
USA CA – 4.9.5 – Not tested with the active version of WooCommerce


### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8128 - /shop/
Cart: #8129 - /cart/
Checkout: #8130 - /checkout/
My account: #8131 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Careex
Version: 1.0
Author URL: https://zemez.io/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 795
Oldest: 2020-01-26 20:52:14 +0000
Newest: 2020-02-17 01:23:14 +0000

Pending: 1
Oldest: 2020-02-17 02:23:15 +0000
Newest: 2020-02-17 02:23:15 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by chromechris** [comment] 2020-02-19 02:29
Downgraded the PHP version on my WordPress server to 5.6, and trigerred the action that creates the error that I keep getting as described in this issue, and my error log jotted down the following:

`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 86 bytes) in /home/techxwbh/civilconcretellc.com/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1252`

There is no way that attempting to allocate 86 bytes is too much for my server to handle. I can't seem to find out what the issue is. the code in line '1252' is the the following code portion of the `wc-core-functions.php` file:

`	// Loop over the 2D array of indexes and generate all combinations.
	foreach ( $indexes as $key => $values ) {
		// When result is empty, fill with the values of the first looped array.
		if ( empty( $results ) ) {
			foreach ( $values as $value ) {
				$results[] = array( $key => $value );
			}
		} else {
			// Second and subsequent input sub-array merging.
			foreach ( $results as $result_key => $result ) {
				foreach ( $values as $value ) {
					// If the key is not set, we can set it.
					if ( ! isset( $results[ $result_key ][ $key ] ) ) {
						$results[ $result_key ][ $key ] = $value;
					} else {
						// If the key is set, we can add a new combination to the results array.
						$new_combination         = $results[ $result_key ];
						$new_combination[ $key ] = $value;
						$results[]               = $new_combination;
					}
				}
			}
		}
	}`

I'm not sure what the issue is, tbh.

**Comment by tammullen** [comment] 2020-02-20 23:20
Hi @chromechris 

Thank you for submitting the issue. 

If I understand your issue correctly after setting you the 5 attributes with 12 values each you have attempted to use the "Create variations from all attributes" option. Due to the number of attributes and values you created this could result in tens of thousands of variations (I believe it would be 95,040 variations!). There is a warning when you do this that only 50 variations can be generated at a time.

![Screenshot_2020-02-20_at_22_42_01](https://user-images.githubusercontent.com/24649833/74988869-e4b11880-5436-11ea-9dba-d7aa6c56277e.png)

I suggest adding just the variations you require one at a time instead of using the "Create variations from all attributes" option.

To help you troubleshoot the issue you are having, I also recommend doing the following:

Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case such as [the Variable Product documentation](https://docs.woocommerce.com/document/variable-product/)
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-02-20 23:20 UTC

**Comment by chromechris** [comment] 2020-02-24 15:54
So the variations are permutations, and not combinations, correct?

**Comment by usmandevelop480** [comment] 2021-10-13 08:50
Hi, if this topic is still open I,m having the same issue I have 12 attributes all of them are having more then 10 values and I want to add all attributes to a single product and have been doing this for 7 days but no luck I also increase max value per run from 50 to more but no luck.
