### ISSUE TITLE
Stock is not held when a PayPal Standard order is Pending Payment

### ISSUE THREAD

**Issue by battouly** [woocommerce/woocommerce#30348] opened 2021-07-25 20:57 UTC
**Describe the bug**

I’ve set the stock of a product to 1, added it to cart, placed an order with PayPal Standard but didn’t actually pay, now I see that the order status is “pending payment” (no notes/stock reduction) but, opening it in an incognito window lets me add it to the Cart still.

Hold stock is set for 3 minutes, but it doesn’t sound like it’s doing anything to avoid double purchase while the order status is “Pending payment” with PayPal Standard?

**Expected behavior**

Stock should be reduced when a PayPal Standard order is Pending Payment.

**Actual behavior**

Pending Payment doesn't reduce stock with PayPal Standard as payment gateway.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add a product with 1 stock
2. Add to Cart, go through Checkout with PayPal Standard, but don't complete payment
3. Notice the Pending Payment order is created
4. Visit the product page from a different browser - It is still possible to add the item to the cart

**Screenshots**

![Markup 2021-07-11 at 15 32 20](https://user-images.githubusercontent.com/13640239/126913251-f8b18187-d989-4d69-ae48-34b80646e1aa.png)

![Markup 2021-07-11 at 15 28 23](https://user-images.githubusercontent.com/13640239/126913254-efcd8cc2-4afd-42a3-86d1-97f6c879060f.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by vbelolapotkov** [comment] 2023-09-12 10:39
@woocommerce/quark  could you please check the relevance and prioritize this?

**Comment by rrennick** [comment] 2023-10-13 09:34
This is a duplicate of #31551. I'll close this as a duplicate. Follow that issue for updates.

**Closed by rrennick** 2023-10-13 09:34 UTC
Labels: type: bug, priority: high, focus: paypal, focus: payment [team:Proton], focus: stock [team:Proton], plugin: woocommerce, team: Transact
