### ISSUE TITLE
shipping_methods api not returning shipping rate in woocommerce rest api

### ISSUE THREAD

**Issue by kishanbharda** [woocommerce/woocommerce#27899] opened 2020-10-07 10:17 UTC
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

I used woocommerce rest api for my mobile app. To create an order I have to use [/wp-json/wc/v3/orders](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order), in that api I have to pass order detail. On of order detail is shipping. I have to pass shipping method, it's title and total cost of shipping. To do that I have fetched shipping detail using [shipping_methods](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-shipping-methods) api. It returning me array of methods with it's `id`, `title` and `description`. But it does not returning the rate of the shipping. So from where I can get shipping rate, so I can pass it to order.

**Expected behavior**
`shipping_methods` api should return shipping rate.

**Actual behavior**
`shipping_methods` api not returning shipping rate.

**Steps to reproduce the bug**
Call api `shipping_methods` with your secret key and secret password. 

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2021-01-21 19:34
Hi @kishanbharda ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rrennick** 2021-01-21 19:34 UTC
