### ISSUE TITLE
Sort by Price issue

### ISSUE THREAD

**Issue by voaooo** [woocommerce/woocommerce#13567] opened 2017-03-13 13:46 UTC
issue: When selecting the sorting options in Woocommerce -> Settings -> Display -> Default Product sorting -> Sort By Price (ASC or DSC), there is problem with all the variation products.

It sorts randomly and not taking into account the products lowest price so the sorting looks out of sync and users won’t know this.

Is there a way to sort the products low to high/high to low and use the variable products lowest price when sorting?

link: https://www.wanderercider.com/shop/?orderby=price

**Comment by mikejolley** [comment] 2017-03-13 16:56
Seems to be resolved in the next major update/master. After save, all variation prices are stored under the parent, so any sorting will consider all child values.

**Closed by mikejolley** 2017-03-13 16:56 UTC

**Comment by voaooo** [comment] 2017-04-08 16:52
Hello,
have updated my woocommerce to 3.0.1 but the issue still exist.  please assist?
my page here:
[http://bit.ly/2octiPt](url)

**Comment by zalexzperez** [comment] 2021-02-24 15:29
Well, it's 2021 and I'm having this problem and it's driving me nuts!

I just created a new Wordpress local site just make sure the issue was not caused by other plugins, themes or configs: installed Woocommerce and created two variable products. 

When sorting by price from low to high, the lowest price from the variable product is considered. **Cool**.
When sorting from high to low, the HIGHEST price from the variable product is considered. **Not cool**. Especially if you're not displaying the price range to customers, so they read "From X price" and it turns out cheaper products show up first sometimes when using the aforementioned sorting option.

I'm attaching a screenshot of the test site: 

![image](https://user-images.githubusercontent.com/38706594/109023770-5ad90280-76bd-11eb-9291-9ea562e15e82.png)

But the issue is present even on live demo sites, for instance the Flatsome demo page shown here: https://flatsome3.uxthemes.com/product-category/booking/ 

![image](https://user-images.githubusercontent.com/38706594/109023846-6debd280-76bd-11eb-905f-fe3f59afd544.png)
