### ISSUE TITLE
Out of stock threshold doesn't work properly when stock level is above the threshold - it allows all remaining stock to be purchased

### ISSUE THREAD

**Issue by MayKato** [woocommerce/woocommerce#29411] opened 2021-03-17 16:59 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Out of stock threshold doesn't work properly when stock level is above the threshold - when out of stock threshold is set to 2 (for example) and a particular product stock is 5, customers can still purchase 5.

**Expected behavior**
Customer should only be able to buy 3 (5-2)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Set out of stock threshold to 2 under WooCommerce > Settings > Products > Inventory
2. Go to a product, check "manage stock" and set stock quantity to 5.
3. Go to the single product page (front end) and try to add 5 to cart

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WC Version: 5.1.0
WP Version: 5.7

**Comment by juliaamosova** [comment] 2021-03-21 20:32
Hi @MayKato,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I can order 5 items as suggested in your steps to reproduce the issue instead of 3. 

However, I am slightly confused at the description of the `Out of stock threshold` - it suggests that it is possibly expected that 5 items can be ordered on the items that are in stock:

<img width="550" alt="in_stock" src="https://user-images.githubusercontent.com/19143190/111919992-e6e30d80-8a62-11eb-8926-7460958004ce.png">

I'll give this bug a `high` priority for now. However, it will be great if one of the Core developers could confirm the expected behavior.

**Comment by vedanshujain** [comment] 2021-03-22 08:52
It's intentional to allow the shoppers to complete the purchase even if the remaining stock is below the threshold is actually intentional. This is because if we have a setting for displaying remaining stock to the shoppers in the product page, so for shops where out of stock threshold is set, and if they are also displaying remaining stock to customers, it would be a very bad user experience for customers to not allow the order to complete when there is clearly stock available. 

This setting is intended only as kind of a buffer for merchants where they get notified and put the product on out-of-stock till they acquire more stock. 

I am closing the issue since we won't be able to fix it because of the reasoning specified above. That said, if you have more questions/feedback/suggestions, feel free to reply back and we will re-open the issue and discuss.

**Closed by vedanshujain** 2021-03-22 08:52 UTC
Labels: component: stock, priority: high, type: bug

**Comment by derMrEagle** [comment] 2021-03-22 09:27
Good day -

thank you for that explanation.

Maybe this option should come with a secondary option - out of stock threshold - not included in sellable stock. 
for now I created a duplication of all my products - and put them as a hidden item with 2 stock items each. And added them to a own category to overcome this issue… 
Hope that one day a out of stock feature will be available where this stock is not sellable. We use these stock items to manage guarantees - should there be a comeback on a product.
Can’t find other plugins that would help with this - any suggestions welcome.

**Comment by k3v1np** [comment] 2022-04-27 12:32
If your not displaying the stock amount then one should not be able to purchase stock below the out of stock threshold amount and even if you are showing the stock amount you should show the stock amount minus the out of stock threshold amount.  I think this option needs a little work to be more useful.  The setting being used as "kind of a buffer" is not super helpful for a merchant.

**Comment by adumont-tokilab** [comment] 2023-09-26 01:29
If it could help someone, my solution was to override the "global/quantity-input.php" template and change the "max" attribute of the input "number" minus the value of the "woocommerce_notify_no_stock_amount" option.

It does not prevent someone from changing it manually in the inspector but it keeps you from messing with the stock quantity programmatically.

**Comment by dredumont** [comment] 2023-09-26 01:31
If it could help someone, my solution was to override the "global/quantity-input.php" template and change the "max" attribute of the input "number" minus the value of the "woocommerce_notify_no_stock_amount" option.

It does not prevent someone from changing it manually in the inspector but it keeps you from messing with the stock quantity programmatically.
