### ISSUE TITLE
[WP 5.5] Variations fields formatting is broken in WP 5.5

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27326] opened 2020-08-13 17:27 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

The variations field formatting is broken in WordPress 5.5. 

**Here is how it looks in WordPress 5.4.2 + WooCommerce 4.3.2** - note the 3 lines icon, the arrow, and the Remove button are aligned on the right side of the variation row:

![before](https://user-images.githubusercontent.com/19143190/90166402-309aa580-dd68-11ea-8a52-78dbb7d77e72.jpg)

**And here is how it looks in WordPress 5.5 + WooCommerce 4.3.2** - note the 3 lines icon and the Remove button are on the right side of the variation row, the arrow is on the left - they are not aligned and the variation row is increased in height:

![after](https://user-images.githubusercontent.com/19143190/90166461-490ac000-dd68-11ea-9aec-1d1893082fc1.jpg)

**Expected behavior**

I expected the variations rows to be formatted the same when using WordPress 5.5 as they look in WordPress 5.4.2. 

**Steps to reproduce the bug:**

Steps to reproduce the bug:

1. Create a variable product and check the formatting of the variations rows in WP 5.4.2 + WC 4.3.2 - expected formatting. 
2. Create a variable product and check the formatting of the variations rows in WP 5.5 + WC 4.3.2 - wrong formatting.

**Screenshots**

See above. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-08-13 17:29
I am giving this issue `high` priority because the process of creating a variable product is very generic and many users encounter it and currently the layout looks a bit broken.

**Comment by tammullen** [comment] 2020-08-25 16:13
Just noting that this occurs for attributes as well (see https://github.com/woocommerce/woocommerce/issues/27477 for screenshots).
I also found that the attributes toggle is collapsing the entire product data section instead of just the individual attribute.

**Comment by rodrigoprimo** [comment] 2020-09-03 21:15
Just documenting here that I started investigating this problem. It is caused by this change in WordPress core:

https://github.com/WordPress/WordPress/commit/22d0cd6c963d4ac0e203f7423294c15fb2e5d45a#diff-fc8970b78a0739bd367f17c3a8e552e6L1993

Related ticket:

https://core.trac.wordpress.org/ticket/39074

Basically, we are relying on WordPress core CSS on our own elements and core changed. A quick fix, for now, is to include `float: right;` to the WooCommerce CSS rule for `.handlediv`. I will work on this tomorrow. In the future, we might want to explore not relying on WP CSS for this element (and others) as it could break again.

Checking the ticket, I noticed a report of another problem caused by this change in WooCommerce:

https://core.trac.wordpress.org/ticket/39074#comment:87

We should probably fix it as well. I will take a look as soon as possible.

**Comment by rodrigoprimo** [comment] 2020-09-04 13:14
I just opened a PR to fix the problem described in this issue (#27590). Ignore my comment above regarding the other problem reported in the core ticket. The CSS on my dev environment was outdated so I missed that the problem was already fixed in another PR (#27173).

**Closed** 2020-09-08 16:10 UTC
Labels: bug, component: variation, priority: high
