### ISSUE TITLE
[2.7] jQuery Zoom is called multiple times on variable products

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#13014] opened 2017-01-27 23:50 UTC
Nothing dramatical, but it could be a good idea to have it fixed for the future. I can't unfortunately offer a fix but only describe the problem.

On first load and for variable products, the zoom feature is called and added twice, due to 1) the 'woocommerce_init_gallery' trigger as a result of the 'check_variations' trigger in add-to-cart-variation.js and 2) the wc_product_gallery.init() of single-product.js.

Further, on every click on "clear" or "reset_variations" a new zoom image is added on the top of the at least two active zoom images for the picture.
![zoom](https://cloud.githubusercontent.com/assets/25102786/22391778/94fd689e-e4f3-11e6-9170-7b8a46fa5fdf.jpeg)

**Comment by WPprodigy** [comment] 2017-01-31 06:29
This seems to be resolved with https://github.com/jackmoore/zoom/pull/85 applied. 

CC @jackmoore

**Comment by jackmoore** [comment] 2017-01-31 19:54
Sorry about that.  I overlooked that ticket, but I think it's a duplicate of https://github.com/jackmoore/zoom/issues/83 which was resolved.  I checked the assets in woocommerce and they just need to update to the current version (using Zoom 1.7.15, fixed in 1.7.16).

**Comment by WPprodigy** [comment] 2017-02-01 04:44
Tested with 1.7.16, can confirm that is solves this. Thanks!

**Closed** 2017-02-01 08:48 UTC
