### ISSUE TITLE
Digital Product Download Link Problem

### ISSUE THREAD

**Issue by gitconner** [woocommerce/woocommerce#24712] opened 2019-09-28 10:54 UTC
First I write in German:
Digitale Produkte, also Sachen zum Runterladen funktionieren nicht, wenn die Emailadresse des Kunden untypisch aufgebaut ist: Bsp.    wootest@tm.in-ulm.de

Dann funktioniert der Link in der Bestellmail nicht, sondern leitet nur weiter zum Shop.

Now i Ì try in english:  
Downloadable Products need al Link for Download. This Link goes via Email to Client. But when the Client-Emailadress is not regular, exmpl.  wootest@tm.in-ulm.de  then the link seems broken, no download instead forward to shop.  I guess reason is the dot in the the domainname?

**Comment by rodrigoprimo** [comment] 2019-09-30 19:59
I was not able to reproduce this problem. To confirm I understood it correctly, here are the detailed steps that I took to test:

1. Created a new customer account and set the e-mail address to wootest@tm.in-ulm.de
2. Placed a new order for a digital product using the new customer account
3. Logged in as the new customer, I went to the page "Downloads" under "My Account" and clicked on the link to download the product that I just purchased. I was able to sucesfully download the product. Below is the link that was generated on my local environment to download the product:

```
http://wc.test/?download_file=23&order=wc_order_YkAiSazBM8caX&email=customer1%40vvv.test&key=fda9cc9f-9a8e-4079-9b86-9bd93b249a04
```

I'm closing this issue as non-reproducible. Please leave a comment if I missed something and I will take a second look. Thanks.

**Closed by rodrigoprimo** 2019-09-30 19:59 UTC

**Comment by gitconner** [comment] 2019-10-01 13:38
Hello,
one thing is, you tryed for clients they have to login, but i tryed without login. Just sell, pay, download. And in this way it is not working. I mean not working as a email looks like the example. In regular emails is the download still working. I checked the public email wootest@tm.in-ulm.de for your testing link, but may you deleteted this? Please try again for clients they habve not to register the shop, just buy, pay, download and an email like wootest@tm.in-ulm.de.
thx

**Comment by rodrigoprimo** [comment] 2019-10-02 19:33
I had indeed tried with a logged in user. I just tested again as an anonymous user and the link in the e-mail worked as well. I used the `wootest@tm.in-ulm.de` email address. 

> I checked the public email wootest@tm.in-ulm.de for your testing link, but may you deleteted this?

The link that I provided is a link that only works on my local machine. I shared it just so that you could check the parameters to see if there was something different in the link that you were getting and not for you to click on it. I should have been more explicit about this in my first comment.

Here is the link to download the file in the last test that I did as a anonymous user in case it helps:

```
http://wc.test/?download_file=23&order=wc_order_lIDVqMEt6F4aq&uid=a14ffa6c13a841b5c88fe31ef107652e8246bd5169d30855429acd50d4fd8ac5&key=fda9cc9f-9a8e-4079-9b86-9bd93b249a04
```

I'm afraid there is not much I can do to help you as so far this doesn't seem to be a WooCommerce bug and this is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

**Comment by gitconner** [comment] 2019-10-03 22:27
This is the link that clients recieved  by the problememail (Only Domain is for securityreason modified)

http://xyz.abc/w2/?download_file%20&order=wc_order_3WEeCLUlTLMeR&uid=01fc9f1c03a19aefd5d3332ef4be04a256027f44e5edae40bfcb877209171475&key=910ff508-1679-4d66-8bd7-1680750cc38b

This Link is not working and has en diffenrence to yours in this part: 

/?download_file=23&order=wc_order

But what i sayed, from same System/Woocomerce to an regular emailadress, the link looks like so: (and is still working)

http://xyz.abc/w2/?download_file=20&order=wc_order_Ab1lZ0uMUR8XQ&uid=40959a843d5aa67ba347e13835ac8ac809fbedc5cc681c50baebc2768ed6a3fb&key=910ff508-1679-4d66-8bd7-1680750cc38b

So, the question is, where was the corruptlink produced?

The other thing is, when i check orders in adminarea, the is a field, where is anoounced as customer-download-link, and so i shoud mean ich could send this link to client, because is costumer-link. But, is not, because this link in adminarea is also an other link includes the emailadress unencoded.

Is it not possible, that you can try a real test, not local?

thx.

**Comment by rodrigoprimo** [comment] 2019-10-04 13:43
I'm afraid I won't be able to help you further. As I said in the comment above, I suggest you try one of the support channels to see if someone can help you debug what is causing this problem in your environment. If it turns out to be a problem in WooCommerce core, which doesn't seem to be the case but that could change, please leave another comment with more information on how to reproduce the problem and I will take a look.
