### ISSUE TITLE
URL Params get lost when combined with `add-to-cart`

### ISSUE THREAD

**Issue by aseifert** [woocommerce/woocommerce#12116] opened 2016-10-18 08:28 UTC
## EXPLANATION OF THE ISSUE

Hi everybody,

I wanted to build a link that automatically adds a product to cart and goes to checkout. I found a way to do this, which is to use the `add-to-cart` url parameter. Using this method, I crafted a link and added Google Analytics campaign params, so that I could track visitors. Visits via the add-to-cart link show up as “direct” in Google Analytics (so no source/medium info) and won’t get tracked by the campaign.

This is the link I crafted: https://www.seifertverlag.at/checkout/?add-to-cart=1953&utm_source=test&utm_medium=test

Is this a bug or am I doing something wrong here? Is there a workaround so I can get both the auto-checkout AND the campaign tracking to work?

Thanks,
Alex

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://www.seifertverlag.at
Site URL: https://www.seifertverlag.at
WC Version: 2.6.4
Log Directory Writable: ❌ Um Protokollierung (Logging) zu ermöglichen
muss /www/htdocs/w00f9927/seifertverlag.at/wp-content/uploads/wc-logs/ schreibbar sein
oder definiere die Variable WC_LOG_DIR.

WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.25-nmm1
PHP Post Max Size: 200 MB
PHP Time Limit: 600
PHP Max Input Vars: 3000
cURL Version: 7.22.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (14) ###

BackWPup: von Inpsyde GmbH – 3.3.4
Better Search Replace: von Delicious Brains – 1.2.10
Edit Author Slug: von Brandon Allen – 1.2.1
Kraken Image Optimizer: von Karim Salman – 2.6.2
Search by Algolia – Instant & Relevant results: von Algolia – 1.3.0
Social Warfare: von Warfare Plugins – 2.0.7
Types - Complete Solution for Custom Fields and Types: von OnTheGoSystems – 1.6.6.3
W3 Total Cache: von Frederick Townes – 0.9.5.1
WooCommerce Deutsch (de_DE): von David Decker - DECKERWEB.de – 3.2.0
WooCommerce Google Analytics Integration: von WooThemes – 1.4.0
WooCommerce: von WooThemes – 2.6.4
Yoast SEO: von Team Yoast – 3.7.0
WP-Optimize: von Ruhani Rabin – 1.9.1
Acunetix WP Security: von Acunetix – 4.0.5

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #6 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /kassa/
Mein Konto: #9 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Hamburg Child Alex
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Hamburg
Parent Theme Version: 1.3.3
Parent Theme Author URL: https://marketpress.de/
WooCommerce Support: ✔

### Templates ###

Overrides: hamburg/woocommerce/archive-product.php Version - ist veraltet. Die Hauptversion ist 2.0.0
hamburg/woocommerce/cart/cart-totals.php Version - ist veraltet. Die Hauptversion ist 2.3.6
hamburg/woocommerce/cart/cart.php Version - ist veraltet. Die Hauptversion ist 2.3.8
hamburg/woocommerce/cart/cross-sells.php Version - ist veraltet. Die Hauptversion ist 1.6.4
hamburg/woocommerce/cart/mini-cart.php Version - ist veraltet. Die Hauptversion ist 2.5.0
hamburg/woocommerce/checkout/form-shipping.php Version - ist veraltet. Die Hauptversion ist 2.2.0
hamburg/woocommerce/checkout/payment.php Version - ist veraltet. Die Hauptversion ist 2.5.0
hamburg/woocommerce/content-product.php Version - ist veraltet. Die Hauptversion ist 2.6.1
hamburg/woocommerce/content-product_cat.php Version - ist veraltet. Die Hauptversion ist 2.6.1
hamburg-child-alex/woocommerce/content-single-product.php Version - ist veraltet. Die Hauptversion ist 1.6.4
hamburg/woocommerce/content-widget-product.php Version - ist veraltet. Die Hauptversion ist 2.5.0
hamburg/woocommerce/emails/email-order-items.php Version - ist veraltet. Die Hauptversion ist 2.1.2
hamburg/woocommerce/emails/plain/email-order-items.php Version - ist veraltet. Die Hauptversion ist 2.1.2
hamburg/woocommerce/global/wrapper-end.php Version - ist veraltet. Die Hauptversion ist 1.6.4
hamburg/woocommerce/global/wrapper-start.php Version - ist veraltet. Die Hauptversion ist 1.6.4
hamburg/woocommerce/loop/loop-end.php Version - ist veraltet. Die Hauptversion ist 2.0.0
hamburg/woocommerce/loop/loop-start.php Version - ist veraltet. Die Hauptversion ist 2.0.0
hamburg/woocommerce/loop/no-products-found.php Version - ist veraltet. Die Hauptversion ist 2.0.0
hamburg/woocommerce/loop/pagination.php Version - ist veraltet. Die Hauptversion ist 2.2.2
hamburg/woocommerce/loop/rating.php Version - ist veraltet. Die Hauptversion ist 2.0.0
hamburg/woocommerce/loop/result-count.php Version - ist veraltet. Die Hauptversion ist 2.0.0
hamburg/woocommerce/order/order-details.php Version - ist veraltet. Die Hauptversion ist 2.6.0
hamburg-child-alex/woocommerce/single-product/meta.php Version - ist veraltet. Die Hauptversion ist 1.6.4
hamburg/woocommerce/single-product/price.php Version - ist veraltet. Die Hauptversion ist 2.4.9
hamburg/woocommerce/single-product/related.php Version - ist veraltet. Die Hauptversion ist 1.6.4
hamburg/woocommerce/single-product/review.php Version - ist veraltet. Die Hauptversion ist 2.6.0
hamburg/woocommerce/single-product/tabs/tabs.php Version - ist veraltet. Die Hauptversion ist 2.4.0
hamburg/woocommerce/single-product/up-sells.php Version - ist veraltet. Die Hauptversion ist 1.6.4
hamburg/woocommerce/single-product.php Version - ist veraltet. Die Hauptversion ist 1.6.4

: Erfahre
wie du veraltete Templates aktualisierst

`
```

**Comment by mikejolley** [comment] 2016-10-18 11:12
I cannot comment on why this endpoint would be affected specifically (it could be that WP is doing a redirect, or it could be the redirect triggered by WooCommerce after the add to cart is performed), however this comment lists some common reasons:

https://moz.com/community/q/google-analytics-shows-most-referrers-as-direct-what-are-some-better-tools#reply_246053 

I did notice the link you provided changes on click (redirected) so thats likely the reason here.

I don't however see how this would be a 'bug' unless add to cart itself were broken. Closing as this is not a bug with WC core code.

**Closed by mikejolley** 2016-10-18 11:12 UTC
