### ISSUE TITLE
Either "offers", "review", or "aggregateRating" should be specified

### ISSUE THREAD

**Issue by Zohaib321** [woocommerce/woocommerce#24982] opened 2019-11-05 20:24 UTC
Google error "Either "offers", "review", or "aggregateRating" should be specified" is back.

**Comment by juliaamosova** [comment] 2019-11-06 13:05
This is a duplicate of https://github.com/woocommerce/woocommerce/issues/24950 - please continue to discuss there.

**Closed by juliaamosova** 2019-11-06 13:05 UTC
