### ISSUE TITLE
WooCommerce login and membership code

### ISSUE THREAD

**Issue by HassaN0152** [woocommerce/woocommerce#28876] opened 2021-01-21 06:54 UTC
Hello good time
I gave the link to enter and join so that the user can enter the login or membership page normally
like this :
`<a href="../my-account"> Login / Register </a>`

But I am looking for a PHP code to do this itself, and if the user had logged in to the account, instead of logging in / registering, for example, click View profile or ...
What WordPress or WooCommerce code should I use?

Translated by Google

**Comment by lsinger** [comment] 2021-01-21 14:26
Hi @HassaN0152,
﻿
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
﻿
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
﻿
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
﻿
If you confirm the bug, please provide us with clear steps to reproduce it.
﻿
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by lsinger** 2021-01-21 14:26 UTC
