### ISSUE TITLE
Product Importer: CSV Files Get Deleted after uploading

### ISSUE THREAD

**Issue by harishankerr** [woocommerce/woocommerce#25407] opened 2020-01-15 17:56 UTC
**Describe the bug**
After importing products to a site using the built-in CSV Importer, the CSV file gets automatically deleted from the uploads folder as well as the media library within 24 hours. Additionally, while the CSV file was uploaded, it shows up only in the grid view and the not in the list view.

**To Reproduce**
1. Import products to the site using the [built-in CSV Importer/Exporter](https://docs.woocommerce.com/document/product-csv-importer-exporter/)
  1. Go to **Products > Import**
  2. Upload a filled CSV file based on the [sample CSV file](https://github.com/woocommerce/woocommerce/tree/master/sample-data). You can either use it to create new products, or to update new products.
2. After uploading, go to **Media > Library**, and check the grid view. You wouldn't find the CSV file there:
![https://d.pr/i/wNOgHR](https://d.pr/i/wNOgHR+) 
Full Size: https://d.pr/i/wNOgHR
However, upon switching to the list view, you should be able to find the CSV file in the list view:
![https://d.pr/i/loaoBk](https://d.pr/i/loaoBk+) 
Full Size: https://d.pr/i/loaoBk
**This is the first problem.**
3. Next, navigate to the site's uploads folder: **/wp-content/uploads/2020/01**. You should be able to view the CSV file in that folder.
4. Leave it for at least 24 hours and check again. You will find that the uploaded CSV file is now missing. You won't be able to find it in the media library as well.
**This is the second and the main problem.**

**Expected behavior**
Uploaded files, including the CSV files should be present both in the uploads folder, as well as in the media library. The obvious benefit of this is that the merchant will be able to get an 'audit log' (of when the uploads took place, or when the changes were made).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://wootest.test
Site address (URL): https://wootest.test
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.9
PHP Version: 7.1.25 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.7.25
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 67.16MB
Database Data Size: 36.41MB
Database Index Size: 30.75MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_comments: Data: 0.20MB + Index: 0.25MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 20.52MB + Index: 18.06MB + Engine InnoDB
wp_posts: Data: 3.50MB + Index: 0.23MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.23MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 1.52MB + Index: 1.69MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_recommendations: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_session_activity: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 4.52MB + Index: 7.55MB + Engine InnoDB
wp_wps_key: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (79) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Code Snippets: by Shea Bunge – 2.13.3
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 8.1
Loco Translate: by Tim Whitlock – 2.3.1
Mailchimp for WooCommerce: by Mailchimp – 2.3 – Not tested with the active version of WooCommerce
Sensei LMS: by Automattic – 2.3.0
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Homepage Contact Section: by WooCommerce – 1.0.5
Storefront Mega Menus: by WooCommerce – 1.6.2 – Not tested with the active version of WooCommerce
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.4.15
Storefront Product Hero: by WooThemes – 1.2.13
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Sticky Add to Cart: by WooThemes – 1.1.9
TablePress: by Tobias Bäthge – 1.9.2
User Role Editor: by Vladimir Garagulya – 4.52.2
WooCommerce Blocks: by Automattic – 2.5.10
Woo Subscriptions Variation Lifetime/Onetime Purchase: by Logicfire – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce 360° Image: by WooCommerce – 1.1.11
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.11
WooCommerce Advanced Notifications: by WooCommerce – 1.2.18
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.6 – Not tested with the active version of WooCommerce
WooCommerce Amazon and eBay Integration: by Codisto – 1.3.32 – Not tested with the active version of WooCommerce
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.10 – Not tested with the active version of WooCommerce
WooCommerce Bookings Availability: by WooCommerce – 1.1.5
WooCommerce Bookings: by WooCommerce – 1.15.5
WooCommerce Box Office: by WooCommerce – 1.1.13 – Not tested with the active version of WooCommerce
WooCommerce Brands: by WooCommerce – 1.6.11
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.23 – Not tested with the active version of WooCommerce
WooCommerce Composite Products: by SomewhereWarm – 3.15.2 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.9
WooCommerce Currency Converter: by WooCommerce – 1.6.13 – Not tested with the active version of WooCommerce
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.6
WooCommerce Deposits: by WooCommerce – 1.4.15
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13 – Not tested with the active version of WooCommerce
WooCommerce EU VAT Number: by WooCommerce – 2.3.14 – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.8.20
WooCommerce Force Sells: by WooCommerce – 1.1.20 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.3.6
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.16 – Not tested with the active version of WooCommerce
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.3 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.2.5 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.14.1 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.12.4 – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.12
WooCommerce One Page Checkout: by Automattic – 1.7.0 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager: by SkyVerge – 1.10.2 – Not tested with the active version of WooCommerce
WooCommerce Photography: by WooCommerce – 1.0.17 – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.26
WooCommerce Pre-Orders: by WooCommerce – 1.5.17 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.20
WooCommerce Product Bundles: by SomewhereWarm – 5.9.2 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.30
WooCommerce Product Vendors: by WooCommerce – 2.1.21 – Not tested with the active version of WooCommerce
WooCommerce Quick View: by WooCommerce – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce Recommendation Engine: by Lucas Stark – 3.2.0 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.2
WooCommerce Shipment Tracking: by WooCommerce – 1.6.12 – Not tested with the active version of WooCommerce
WooCommerce FedEx Shipping: by WooCommerce – 3.4.17 – Not tested with the active version of WooCommerce
WooCommerce Local Pickup Plus: by SkyVerge – 2.5.1 – Not tested with the active version of WooCommerce
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.6 – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.2 – Not tested with the active version of WooCommerce
WooCommerce Stamps.com API integration: by WooCommerce – 1.3.10 – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.21 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.0.7 – 2.0.8 is available
WooCommerce Subscribe All The Things: by SomewhereWarm – 2.1.5 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Automattic – 2.6.5
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15 – Not tested with the active version of WooCommerce
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.12 – Not tested with the active version of WooCommerce
WooCommerce Warranty Requests: by WooCommerce – 1.8.13 – Not tested with the active version of WooCommerce
WooCommerce Xero Integration: by WooCommerce – 1.7.16 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.8.1
WordPress Importer: by wordpressdotorg – 0.6.4
WP CLI Login Command Server: by Evan Mattson – 1.2
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Rollback: by Impress.org – 1.7.0

### Inactive Plugins (14) ###

Classic Editor: by WordPress Contributors – 1.5
W3 Total Cache: by Frederick Townes – 0.10.1
WooCommerce All Products For Subscriptions: by SomewhereWarm – 2.4.2 – Not tested with the active version of WooCommerce
WooCommerce Bookings: by WooCommerce – 1.15.2 – Not tested with the active version of WooCommerce
WooCommerce Bookings: by WooCommerce – 1.15.2 – Not tested with the active version of WooCommerce
WooCommerce Bookings: by WooCommerce – 1.15.2 – Not tested with the active version of WooCommerce
WooCommerce Cart Add-Ons: by WooCommerce – 1.5.20 – Not tested with the active version of WooCommerce
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Product Search: by itthinx – 2.12.3 – Not tested with the active version of WooCommerce
WooCommerce Splash Popup: by WooCommerce – 1.2.11
WooCommerce UPS Shipping: by WooCommerce – 3.2.14 – Not tested with the active version of WooCommerce
WP2Static: by Leon Stafford – 6.6.7
WP Super Cache: by Automattic – 1.7.0
Yoast SEO: by Team Yoast – 12.4 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/.DS_Store
storefront/woocommerce/emails/customer-new-account.php


### Memberships ###

Restriction mode:: Hide content only
Public content:: Products: 1 item
Excluded from discounts:: –
Membership plans:: 1
Free:: Members: 1Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No

### Subscriptions ###

WCS_DEBUG: ❌ Yes
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://wootest.test
Subscription Statuses: wc-active: 1
wc-on-hold: 6

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Check payments: wc-on-hold: 1
Stripe: wc-active: 1
wc-on-hold: 5


### Payment Gateway Support ###

Direct bank transfer: products
Check payments: products
PayPal Checkout: products
refunds
subscriptions
subscription_cancellation
subscription_reactivation
subscription_suspension
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

Purchase Order: products

### Composite Products ###

Database Version: 3.15.2
Template Overrides: –

### Product Bundles ###

Database Version: 5.9.2
Template Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 2
Custom formats: 0
Next export: Not scheduled

### Local Pickup Plus ###

Status: Disabled
Geocoding: –
Pickup Locations: 0
Pickup Appointments: –
Pickup Location Tax: –
Checkout Display: Pickup selection mode: per item

### Action Scheduler ###

Complete: 0
Oldest: 2019-11-02 07:03:34 +0000
Newest: 2020-01-13 12:07:25 +0000

Pending: 11
Oldest: 2020-01-13 12:08:55 +0000
Newest: 2020-01-15 07:55:02 +0000

Canceled: 78
Oldest: 2019-12-12 13:51:34 +0000
Newest: 2020-12-31 21:30:00 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by rynaldos** [comment] 2020-01-16 18:25
The cleanup seems to be the intended behavior: https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/admin/importers/class-wc-product-csv-importer-controller.php#L322

**Comment by juliaamosova** [comment] 2020-01-16 21:16
Hi @harishankerr,

Thank you for reporting the issue and providing clear steps to reproduce it. 

Regarding the fact that CSV file appears in the list view in the Media Library but not in the grid view - this is not a WooCommerce but WordPress issue. 

Regarding the fact that the CSV file gets deleted after 24 hours passed - this is intentional as @rynaldos mentioned. There is an issue with keeping the CSV file in the public directory. I am looking for a more comprehensive explanation and will comment back here as soon as I get it. But please do know that this is not a bug.

**Comment by juliaamosova** [comment] 2020-01-17 10:27
Additional comments on the reason why it is problematic to keep the product import CSV file in the Media Library for more than 24h - there is a security concern as someone potentially may download that CSV file that contains links to paid downloadable products/files, private/hidden products and so on. To avoid that, the product import CSV file gets deleting in 24h after uploading. 

If you'd like to open a ticket related to the fact that CSV file is being displayed in the list format in the Media Library but not in the grid, you can do so here: https://core.trac.wordpress.org/

I am going to close this issue as it is not a bug we can fix in WooCommerce.

**Closed by juliaamosova** 2020-01-17 10:27 UTC
Labels: question, wordpress

**Comment by harishankerr** [comment] 2020-01-18 18:41
Thanks for the feedback, and the suggestions @juliaamosova and @rynaldos! This is super-helpful, and I appreciate it a lot.
