### ISSUE TITLE
custom css classes for forms input and sidebar

### ISSUE THREAD

**Issue by realrecordzLab** [woocommerce/woocommerce#25422] opened 2020-01-17 18:45 UTC
We started use woocommerce and we need to integrate it with a custom theme that is using bootstrap 4. After reading the documentations we started to modify the templatesby using the hooks and by overriding all the default templates. What we are not able to do is to style the forms, we need to add the bs4 classes to the inputs fields and to the labels, but we didn't found any documentation or hooks about this. Also the sidebar are displayed In the wrong place and will not fit our needings, nor docs about we found. 

Can anyone help with these two modification with a suggestion about what hooks to use and what file we need to modify for the sidebar and forms?

**Comment by tammullen** [comment] 2020-01-22 13:56
Hi @realrecordzLab,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

[Review WooCommerce Self-Service Guide](https://href.li/?https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://href.li/?https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://href.li/?https://wordpress.org/support/plugin/woocommerce/)
If you confirm the bug, please provide us with clear steps to reproduce it and any other details we ask for in the [Bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=4-Bug-report.md&title=).

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-01-22 13:56 UTC

**Comment by realrecordzLab** [comment] 2020-01-23 10:06
Ok, thanks for the help. Very unhelpful!

Il giorno mer 22 gen 2020 alle ore 14:56 Tam Mullen <
notifications@github.com> ha scritto:
