### ISSUE TITLE
Zone without region selected not working logically - bug.

### ISSUE THREAD

**Issue by hitendrachopda-multidots** [woocommerce/woocommerce#25090] opened 2019-11-21 05:32 UTC
**Describe the bug**
I have created one zone and added the twp postcode of the United State.
By mistake, I have selected the country India and added the Zipcode of US and a flat rate is displaying.
Click below link to review the video demo in which we can see the bug.

**To Reproduce**
1. Created one zone and added the twp postcode of the United State.
2. Add one shipping method like flat rate
3. Add product and go to the cart page.
4. Select a country like India and add the United State zip code and the flat rate will be there.
5. See error.

**Screenshots**
1. Zone settings: https://ibb.co/wYVkb1F
2. Issue on cart page: https://ibb.co/fYY6pdW

**Expected behavior**
Once India selected then, this should not display the flat rate or region must mandatory field.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress address (URL): http://thedotstorepro.local
Site address (URL): http://thedotstorepro.local
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.38MB
Database Data Size: 2.05MB
Database Index Size: 1.33MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfp_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfp_questions_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfp_wizard: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

WooODT Lite: by ByConsole – 2.1.4 – Not tested with the active version of WooCommerce
WooCommerce Conditional Product Fees for Checkout Premium: by Multidots – 3.1
WooCommerce: by Automattic – 3.8.0

### Inactive Plugins (12) ###

Advanced Flat Rate Shipping For WooCommerce Premium: by Multidots – 3.6.1
Advanced Product Size Charts for WooCommerce Premium: by Thedotstore – 2.0.1 – Not tested with the active version of WooCommerce
Advance Ecommerce Tracking Premium: by Multidots – 1.5.2 – Not tested with the active version of WooCommerce
Advance Menu Manager Premium: by Multidots – 1.7.5
Mass Pages/Posts Creator Premium: by dots – 1.5.1
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.10 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.22.0
Woocommerce Blocker Premium: by Thedotstore – 1.7.1 – Not tested with the active version of WooCommerce
Woocommerce Category Banner Management Premium: by multidots – 1.4.8 – Not tested with the active version of WooCommerce
Woocommerce Notifier (Premium): by Multidots – 1.5.1 – Not tested with the active version of WooCommerce
WooCommerce Product Attachment Premium: by Multidots – 1.4.1 – Not tested with the active version of WooCommerce
WooCommerce Product Finder Premium: by Multidots – 1.2.5 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #17 - /
Cart: #18 - /cart/
Checkout: #19 - /checkout/
My account: #20 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 16
Oldest: 2019-11-13 04:55:38 +0000
Newest: 2019-11-20 06:40:18 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 1
Oldest: 2019-11-19 08:50:26 +0000
Newest: 2019-11-19 08:50:26 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

**Comment by juliaamosova** [comment] 2019-11-21 12:29
Thank you for reporting the issue @hitendrachopda-multidots. 

I can reproduce it. 

Following the steps provided in the report, I set up the following shipping zones:

![zones](https://user-images.githubusercontent.com/19143190/69337939-034a1c80-0c5a-11ea-9d97-b4279426f119.jpg)

If you enter just the country details (India in our case) in the cart, you get a correct shipping rate of £77:

![india](https://user-images.githubusercontent.com/19143190/69337924-fb8a7800-0c59-11ea-87c3-1f2effbc1e12.jpg)

If you also enter US zip code (33131 in our case), the shipping rate changes to £55:

![zipcode](https://user-images.githubusercontent.com/19143190/69338007-25dc3580-0c5a-11ea-816c-dd080ca5a46a.jpg)

I further was able to place an order with shipping country India but US zip code with the shipping cost of £55 which is meant for the US:

![order](https://user-images.githubusercontent.com/19143190/69338060-43a99a80-0c5a-11ea-87ad-8617eda551ba.jpg)

I think we need to check whether the zip code entered during checkout is a valid zip code for the country selected in order to avoid it.

**Comment by hitendrachopda-multidots** [comment] 2019-11-22 04:14
Thank you @juliaamosova for the reply.

Yes, you are correct. 

We need to check whether the zip code entered during checkout is a valid zip code for the country selected in order to avoid it.

Thank you,

**Comment by juliaamosova** [comment] 2019-11-26 16:34
@hitendrachopda-multidots on the 2nd look, I see that there is a misconfiguration issue actually and not a bug. 

When setting up the shipping zone by zip codes, it is still needed to specify the country to which zip code belongs (in our example, it is the United States but it is the same for any other country):

![us](https://user-images.githubusercontent.com/19143190/69653054-80b2ca00-106a-11ea-9adc-32ada17f3c3e.jpg)

Shipping Zone match at the front-end is done by the country so it is important to specify it. 

I am closing this issue since this is not a bug.

**Closed by juliaamosova** 2019-11-26 16:34 UTC

**Comment by hitendrachopda-multidots** [comment] 2019-11-28 04:50
Hello @juliaamosova,

Thanks for the update.

If possible then, we can add required validation on the Zone regions field to avoid this type of user-generated error.

Thanks,
