### ISSUE TITLE
row and column in The all product page have overlapped

### ISSUE THREAD

**Issue by mammono** [woocommerce/woocommerce#24744] opened 2019-10-02 08:06 UTC
in all product page of woocommerce row and column of product was overlapped. what should i do?

https://www.pinterest.com/pin/789537378407199376/

**Comment by vedanshujain** [comment] 2019-10-02 08:27
I cannot reproduce from my end.  Is this still happening for you? Please also Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

Also, see if disabling other plugins then WooCoomerce helps with the issue. I am closing this, but please comment back if this is still happening and I will reopen.

**Closed by vedanshujain** 2019-10-02 08:27 UTC
