### ISSUE TITLE
Export to CSV under Reporting does not work.

### ISSUE THREAD

**Issue by j2cqueline** [woocommerce/woocommerce#26160] opened 2020-04-10 20:28 UTC
Export to CSV under Reporting does not work.

**Comment by juliaamosova** [comment] 2020-04-10 20:42
Hi @j2cqueline,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by j2cqueline** [comment] 2020-04-10 21:24
![Capture](https://user-images.githubusercontent.com/63475532/79024147-ed6cc380-7b36-11ea-94be-137827a607f5.PNG)

There is no way to reproduce the issue... The button "Export CSV" doesn't work.

**Comment by j2cqueline** [comment] 2020-04-13 22:43
Can anyone help me?

**Comment by tammullen** [comment] 2020-04-16 21:43
Hi @j2cqueline 

Thank you for reporting the issue. This is intended behaviour of the Export CSV button until a product is selected. See here https://docs.woocommerce.com/document/reports/#section-3 for more details on selecting a product to report upon. 

This issue had also been reported previously as a suggested enhancement here https://github.com/woocommerce/woocommerce/issues/26062. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Closed by tammullen** 2020-04-16 21:43 UTC
Labels: status: needs feedback
