### ISSUE TITLE
Paying for pending orders from 'pay now' link results in new order creation in some circumstances

### ISSUE THREAD

**Issue by NickGreen** [woocommerce/woocommerce#20332] opened 2018-05-31 20:08 UTC
https://a8c.slack.com/archives/C07414X4N/p1526940004000241
Conversation with Lucas Stark indicating there is a bug in core. I would love to get some thoughts on this.

**Describe the bug**
There seems to be a problem when users are paying for pending orders when the cart item has additional data attached to it from extensions. The cart hashes don't match, and we aren't sure why. Paying for that order results in a new order being created, which will create a new subscription if the original order was a renewal order.

**To Reproduce**

One way to reproduce: load up WC Subscriptions, Dynamic Pricing (WooCommerce Dynamic Pricing & Discounts has the exact same issue.)

1. Checkout with subscription product
2. Select PayPal, then close the tab once you get to PP
3. This creates a pending order and pending subscription
4. Click the "customer payment" link from the order
5. Check out fully (with any method)
6. See that there is now a second order and second subscription created

This seems to happen with any plugin that adds additional data to the cart item. WC changes the hash, so a new order is created, rather than paying for the old one.

**Expected behavior**
A new order should not be created. In the above example, if the cart hash matched, the original order is paid for correctly, and a second subscription will also not be created.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Possibly related block of code**
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L297

**Comment by mikejolley** [comment] 2018-06-01 15:38
@NickGreen I don't think those test instructions work.

You'll notice after going to PayPal your cart is still populated. Thats why it creates another order if you try to checkout again.

Step 3.5 should be empty your cart.

If you then try the payment link you'll see a cart empty error. WooCommerce, for regular orders, uses a special Pay page for this. Subscriptions doesn't - it sends the user to checkout. This functionality appears broken. Can you check?

Regarding hashes, if you do go again via checkout, the hash comparison will be done again. This is a security measure. The hash is based on order total and the cart items. If subscriptions populates the cart is a different way to how it was before, hash mismatch will occur. If we could somehow get a dump of `WC()->cart->get_cart_for_session()` before and after hitting 'pay' when using subscriptions it may tell us what needs to happen. Either ignoring certain keys, or standardising that response somehow. 

But I can't test that whilst pay is broken. I tested using subscriptions master from github.

cc @thenbrent

**Comment by thenbrent** [comment] 2018-06-05 04:41
@mikejolley based on the above, I think you can close this one for now.

I'm going to wager something is being set incorrectly or at least, differently, in the cart items or maybe totals by Subscriptions or Dynamic pricing. If that's the case, it's not a bug in WC and instead, needs to be fixed in one of those plugins.

**Comment by mikejolley** [comment] 2018-06-05 09:15
Ok @thenbrent - please let me know if that logic needs adjustment, e.g. sorting values before comparison. I'm not sure if thats the issue or not as I couldn't get this working in testing :)

Cheers

**Closed by mikejolley** 2018-06-05 09:15 UTC
Labels: status: needs feedback
