### ISSUE TITLE
woocommerce_cart_needs_payment filter breaks in 4.7.0

### ISSUE THREAD

**Issue by bhubbard** [woocommerce/woocommerce#28232] opened 2020-11-10 23:16 UTC
With WooCommerce 4.7.0 it looks like it breaks the following filter:

```add_filter('woocommerce_cart_needs_payment', '__return_false');```

What would be the new proper way to verify a store doesn't require payments for orders?

**Comment by NitinPrakash** [comment] 2020-11-12 08:07
Facing Same issue

**Comment by bonysoft** [comment] 2020-11-12 08:13
Seems like it's 

`add_filter( 'woocommerce_order_needs_payment', '__return_false' );`

now.

**Comment by mjmarley** [comment] 2020-11-12 19:55
@bonysoft We gave that a shot and it didn't work. It worked for you?

**Comment by bonysoft** [comment] 2020-11-12 20:52
@mjmarley For me it did, checkout error is gone.

I retraced the path of issue #27893 leading to this [commit](https://github.com/woocommerce/woocommerce/commit/537ec5d0e966ecb106eb3ab687fc41c2fce17561). They've replaced cart payment condition to [order level](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-order.html#source-view.1497), which applies _woocommerce_order_needs_payment_ filter,

**Comment by contemplate** [comment] 2020-11-13 20:07
Wonder if this is related to this issue here people have started to see with Smart Coupons of 100% value:
https://wordpress.org/support/topic/error-processing-checkout-please-try-again-after-100-discount-2/

Following along.

**Comment by claudiosanches** [comment] 2020-11-13 20:34
Hello @bhubbard,

While fixing other bug we had to change the logic to use the Order Object instead the Cart, so now you should use `woocommerce_order_needs_payment` filter.

**Comment by juliaamosova** [comment] 2020-11-13 20:38
Hi @bhubbard,

It looks like the issue is resolved in this thread so I am going to ahead and close it. However, please feel free to comment back in case I missed something. We'd be happy to take another look.

**Comment by claudiosanches** [comment] 2020-11-13 21:01
I started a Pull Request to keep it backwards compatible, but please note that while I'm making it backwards compatible no one should use the cart object on that part of the checkout since isn't reliable and 3rd party extensions should use the order object, and `woocommerce_order_needs_payment` filter.

**Closed** 2020-11-19 02:20 UTC
Labels: has pull request
