### ISSUE TITLE
Debug log error found when updating database via Update WooCommerce Database button

### ISSUE THREAD

**Issue by apeksha10** [woocommerce/woocommerce#25892] opened 2020-03-12 08:02 UTC
**Describe the bug**
Found debug log error when upgrading WooCommerce database after upgrading from 3.9.3 version to 4.0.0 version.

**To Reproduce**
1. Update from WC 3.9.3 to WC 4.0
2. Click on Update WooCommerce Database button
3. Some errors appear in debug log.

Attaching the debug log file for reference. 
[debug.log](https://github.com/woocommerce/woocommerce/files/4322972/debug.log)

**WordPress Environment**
<details>

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress5.1
Site address (URL): http://localhost/wordpress5.1
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 1,000 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.2
PHP Version: 7.2.2
PHP Post Max Size: 750 MB
PHP Time Limit: 5000
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.30-MariaDB
Max Upload Size: 750 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_
Total Database Size: 4.17MB
Database Data Size: 2.53MB
Database Index Size: 1.64MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ac_abandoned_cart_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_link_clicked_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_opened_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_booking_block_price_attribute_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_booking_block_price_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_booking_fixed_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_booking_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_booking_order_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 7
bkap_booking: 4
faq: 6
page: 10
portfolio: 8
post: 2
product: 2
revision: 51
shop_order: 24
testimonials: 6

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce: by Automattic – 4.0.0
WP SMTP: by BoLiQuan – 1.1.9

### Inactive Plugins (33) ###

Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.5 – Not tested with the active version of WooCommerce
Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 8.5.0 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.1.1
Arconix FAQ: by Tyche Softwares – 1.8.3
Arconix Portfolio Gallery: by John Gardner – 1.5.0
Arconix Shortcodes: by Tyche Softwares – 2.1.6
Arconix Testimonials: by John Gardner – 1.3.1
Booking & Appointment Plugin for WooCommerce: by Tyche Softwares – 4.13.1 – Not tested with the active version of WooCommerce
Call for Price for WooCommerce Pro: by Tyche Softwares – 3.2.4 – Not tested with the active version of WooCommerce
Currency per Product for WooCommerce Pro: by Tyche Softwares – 1.4.5 – Not tested with the active version of WooCommerce
Custom Order Numbers for WooCommerce Pro: by Tyche Softwares – 1.2.4 – Not tested with the active version of WooCommerce
Custom Order Status for WooCommerce Pro: by Tyche Softwares – 1.4.5 – Not tested with the active version of WooCommerce
Deposits For WooCommerce: by Tyche Softwares – 1.7 – Not tested with the active version of WooCommerce
Hello Dolly: by Matt Mullenweg – 1.7.1
Jetpack by WordPress.com: by Automattic – 7.0.1
Klarna Checkout for WooCommerce: by Krokedil – 1.10.4 – Not tested with the active version of WooCommerce
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.8.1 – Not tested with the active version of WooCommerce
Order Delivery Date Pro for WooCommerce: by Tyche Softwares – 9.13.1 – Not tested with the active version of WooCommerce
Page Builder by SiteOrigin: by SiteOrigin – 2.10.6
Payment Gateway Based Fees and Discounts for WooCommerce Pro: by Tyche Softwares – 2.6 – Not tested with the active version of WooCommerce
Price based on User Role for WooCommerce Pro: by Tyche Softwares – 1.2.1 – Not tested with the active version of WooCommerce
Product Delivery Date for WooCommerce - Lite: by Tyche Softwares – 1.9 – Not tested with the active version of WooCommerce
Product Delivery Date Pro for WooCommerce: by Tyche Softwares – 3.1 – Not tested with the active version of WooCommerce
Product Input Fields for WooCommerce: by Tyche Softwares – 1.2.5 – Not tested with the active version of WooCommerce
Product Input Fields for WooCommerce Pro: by Tyche Softwares – 1.3 – Not tested with the active version of WooCommerce
Query Monitor: by John Blackbourn – 3.3.2
SiteOrigin Widgets Bundle: by SiteOrigin – 1.15.7
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.9 – 1.6.20 is available – Not tested with the active version of WooCommerce
WooCommerce Print Invoice & Delivery Note: by Tyche Softwares – 4.5.3 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.18.0 – 1.22.4 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Automattic – 2.6.1 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Compatibility Addon: by Tyche Softwares – 1.2 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.3 – 2.5.5 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-02-18 06:24:44 +0000
Newest: 2020-02-18 06:24:44 +0000

Complete: 25
Oldest: 2020-02-18 06:24:46 +0000
Newest: 2020-03-12 07:56:17 +0000

`
</details>

**Comment by peterfabian** [comment] 2020-03-12 09:59
Thanks for reporting, @apeksha10 !

This seems to be a duplicate of https://github.com/woocommerce/woocommerce/issues/25876. We already have a PR to fix this and will include it in the next update.

**Closed by peterfabian** 2020-03-12 09:59 UTC

**Comment by apeksha10** [comment] 2020-12-31 10:16
Thank you @peterfabian,

Yes. It seems a duplicate issue
