### ISSUE TITLE
Cart shipping calculator showing wrong address

### ISSUE THREAD

**Issue by allysonsouza** [woocommerce/woocommerce#22241] opened 2018-12-16 21:55 UTC
**Describe the bug**
When user changes the zip code in shipping cart calculator, the address, more specifically the street/avenue don't change, even the available methods and zipcode changes, looking strange for users, that will see an address that doesn't match with zip code.

**To Reproduce**
1. Logged in with and user with address registered, go to the cart (after add some product)
2. Click on change address, and fill in with some country/state/zip code
3. Click on update
4. The same address user have saved will be displayed, with the new zip code filled

**Expected behavior**
It's expected that, if it's not possible to display the new complete address, the already saved one was not displayed and just the new state/city/zip-code

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://comidaboa.delivery
Site URL: https://comidaboa.delivery
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - Há uma nova versão do WordPress disponível (5.0.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.0.32-0ubuntu0.16.04.1 - Nós recomendamos o uso do PHP versão 7.2 ou superior para maior performance e segurança. Como atualizar a versão do seu PHP
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-1~xenial
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Tamanho total do banco de dados: 69.65MB
Tamanho dos dados do banco de dados: 52.21MB
Tamanho do índice do banco de dado: 17.44MB
wp_woocommerce_sessions: Dados: 1.02MB + Índices: 0.02MB
wp_woocommerce_api_keys: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índices: 0.02MB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índices: 0.05MB
wp_woocommerce_order_items: Dados: 1.52MB + Índices: 0.20MB
wp_woocommerce_order_itemmeta: Dados: 6.52MB + Índices: 5.03MB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índices: 0.06MB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índices: 0.00MB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índices: 0.00MB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índices: 0.02MB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_log: Dados: 0.02MB + Índices: 0.02MB
wp_aepc_custom_audiences: Dados: 0.02MB + Índices: 0.00MB
wp_aepc_logs: Dados: 1.52MB + Índices: 0.00MB
wp_aryo_activity_log: Dados: 1.25MB + Índices: 0.00MB
wp_commentmeta: Dados: 0.02MB + Índices: 0.03MB
wp_comments: Dados: 2.52MB + Índices: 1.02MB
wp_correios_postcodes: Dados: 0.02MB + Índices: 0.02MB
wp_iwp_backup_status: Dados: 0.02MB + Índices: 0.00MB
wp_iwp_file_list: Dados: 0.02MB + Índices: 0.02MB
wp_links: Dados: 0.02MB + Índices: 0.02MB
wp_litespeed_img_optm: Dados: 0.02MB + Índices: 0.09MB
wp_litespeed_optimizer: Dados: 0.02MB + Índices: 0.03MB
wp_options: Dados: 1.25MB + Índices: 0.11MB
wp_pmxe_exports: Dados: 0.03MB + Índices: 0.00MB
wp_pmxe_google_cats: Dados: 0.39MB + Índices: 0.00MB
wp_pmxe_posts: Dados: 0.02MB + Índices: 0.00MB
wp_pmxe_templates: Dados: 0.02MB + Índices: 0.00MB
wp_pmxi_files: Dados: 0.02MB + Índices: 0.00MB
wp_pmxi_history: Dados: 0.02MB + Índices: 0.00MB
wp_pmxi_images: Dados: 0.02MB + Índices: 0.00MB
wp_pmxi_imports: Dados: 0.05MB + Índices: 0.00MB
wp_pmxi_posts: Dados: 0.02MB + Índices: 0.03MB
wp_pmxi_templates: Dados: 0.03MB + Índices: 0.00MB
wp_postmeta: Dados: 7.52MB + Índices: 6.03MB
wp_posts: Dados: 1.52MB + Índices: 0.38MB
wp_sp_email_logs: Dados: 0.02MB + Índices: 0.03MB
wp_termmeta: Dados: 0.02MB + Índices: 0.03MB
wp_terms: Dados: 0.02MB + Índices: 0.03MB
wp_term_relationships: Dados: 0.09MB + Índices: 0.06MB
wp_term_taxonomy: Dados: 0.05MB + Índices: 0.03MB
wp_usermeta: Dados: 3.48MB + Índices: 3.75MB
wp_users: Dados: 0.11MB + Índices: 0.08MB
wp_wc_download_log: Dados: 0.02MB + Índices: 0.03MB
wp_wc_webhooks: Dados: 0.02MB + Índices: 0.02MB
wp_wpml_mails: Dados: 22.52MB + Índices: 0.00MB
wp_yoast_seo_links: Dados: 0.17MB + Índices: 0.06MB
wp_yoast_seo_meta: Dados: 0.05MB + Índices: 0.00MB

### Post Type Counts ###

attachment: 226
custom_css: 1
customize_changeset: 3
elementor_library: 18
modo-de-preparo: 1
nav_menu_item: 24
page: 14
post: 8
product: 114
revision: 179
shop_coupon: 15
shop_order: 897
shop_order_refund: 30

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

InfiniteWP - Client: por Revmakx – 1.8.6
Registro de Atividades: por Activity Log Team – 2.5.1
CMB2: por Equipe CMB2 – 2.5.1
Comida Boa Core: por Haste – 0.0.1
Duplicate Post: por Enrico Battocchi – 3.2.2
Dynamic Visibility for Elementor: por Dynamic.ooo – 1.1.0
Elementor Pro: por Elementor.com – 2.2.4
Elementor: por Elementor.com – 2.3.4
Envato Market: por Envato – 2.0.1
Export Users to CSV: por Matt Cromwell – 1.1.1
Health Check & Troubleshooting: por A comunidade do WordPress.org – 1.2.3
Heartbeat Control: por Jeff Matson – 1.2.5
Jet Elements For Elementor: por Zemez – 1.14.6
JetTricks: por Zemez – 1.1.5
Tradução (Loco): por Tim Whitlock – 2.2.0
Nginx Helper: por rtCamp – 2.0.1
Pixel Caffeine: por AdEspresso – 2.0.6 – Não testado com a versão ativa do WooCommerce
ShortPixel Image Optimizer: por ShortPixel – 4.12.1
SparkPost: por SparkPost – 3.2.0
User Role Editor: por Vladimir Garagulya – 4.47
View Admin As: por Jory Hogeveen – 1.8.3
WooCommerce Print Invoice & Delivery Note: por Tyche Softwares – 4.4.7 – Não testado com a versão ativa do WooCommerce
WooCommerce Domination: por Claudio Sanches – 1.1.6 – Não testado com a versão ativa do WooCommerce
WooCommerce Expand Tabs: por Diana Burduja – 1.8 – Não testado com a versão ativa do WooCommerce
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.1 – Não testado com a versão ativa do WooCommerce
Integração do Google Analytics com o WooCommerce: por WooCommerce – 1.4.7
WooCommerce Mix and Match: por Kathy Darling – 1.3.2 – 1.3.4 está disponível – Não testado com a versão ativa do WooCommerce
WooCommerce Pagar.me: por Pagar.me
Claudio Sanches – 2.0.12 – Não testado com a versão ativa do WooCommerce

WooCommerce PagSeguro: por Claudio Sanches – 2.13.1 – Não testado com a versão ativa do WooCommerce
WooCommerce: por Automattic – 3.5.2
Yoast SEO: por Equipe da Yoast – 9.2.1
WP All Export: por Soflyy – 1.2.2
WP All Import: por Soflyy – 3.4.9
WP Mail Logging: por Christian Zöller – 1.8.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
mix-and-match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base da loja: #5 - /cardapio/
Carrinho: #6 - /carrinho/
Finalizar compra: #7 - /finalizar-compra/
Minha conta: #8 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Comida Boa
Version: 1.0.0
Author URL: https://hastedesign.com.br
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: comidaboa/woocommerce/archive-product.php
comidaboa/woocommerce/global/form-login.php
comidaboa/woocommerce/myaccount/form-login.php
comidaboa/woocommerce/product-searchform.php


### Mix and Match Products ###

Template Overrides: comidaboa/woocommerce/single-product/add-to-cart/mnm-add-to-cart-wrap.php
```
</details>

**Comment by rrennick** [comment] 2018-12-17 14:07
The shipping rate calculations are based on region and/or zip codes. That's why those update. While in some ways this suggestion seems intuitive, clearing the address fields when a customer has just corrected a typo in their zip code would probably have a negative impact on cart abandonment rate.

**Comment by allysonsouza** [comment] 2018-12-19 14:20
Sorry @rrennick, I'm not sure if I understand. When I'm logged in, and reach cart for the first time, the calculator will have the estimate for my account saved address - ok, that's fine and what's expected. But when I try to figure how it will cost to be shipped for other address, filing calculator with other city, state, postcode, when I hit the update button the page still displays my account address, despite the shipping methods and rates are updated, I expect to see the address of postcode I inserted, not my account address.

**Comment by rrennick** [comment] 2018-12-19 15:08
> when I hit the update button the page still displays my account address

Do you have page caching running on your site?

**Comment by rrennick** [comment] 2018-12-19 19:51
I'm not able to reproduce this in my dev install.

**Comment by mikejolley** [comment] 2019-01-15 16:53
The mix of account and session data is fixed in https://github.com/woocommerce/woocommerce/pull/22392

**Closed by mikejolley** 2019-01-15 16:53 UTC
