### ISSUE TITLE
Automatically issued Attachment-ID conflicts with Product-ID / SKU

### ISSUE THREAD

**Issue by FAL-Italy** [woocommerce/woocommerce#26788] opened 2020-06-17 09:05 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Added many thousands products to my site from CSV, using the import function;
2. Some of the added products (about 1%) did not show the supplied image in the list, but they showed it if the page of the single product is opened;
3. Attached manually the missing images (some hundreds of them)  to the related products, thus restoring desired behaviour; (those images, I discovered later, were given an Attachment-ID on which I have no control)
4. Adding another load of new products, some of them are not imported because "their ID is already present", and if I try to update the same items, the import function cannot update any of them because "their ID conflicts with the ID of another non-product object". I could find that those non-product objects are the images I attached manually, which were given an attachment-ID that happens to be equal to the SKU (and to the ID as well) of one of the products I need to add.

## Expected/actual behavior
If the attachment-ID were prefixed with a user-changeable code, defaulting for example to "ATT", there would be no conflict.

When I follow those steps, I see...
I can't add those products to my site, and I would like not to erase all of the attachments, add the products and reattach all images.

I was expecting to see...
No conflict... I would like to add products with their IDs equal to their SKU, and to attach images with non-conflicting IDs.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.gpecsrl.it/negozio-online-componenti-elettronici
Site address (URL): https://www.gpecsrl.it/negozio-online-componenti-elettronici
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: ❌ 5.3.4 - È disponibile una versione più recente di WordPress (5.4.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.26
PHP Post Max Size: 30 MB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.29-32-log
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_
Dimensione totale database: 223.13MB
Dimensione dati database: 128.87MB
Dimensione indice database: 94.26MB
wp_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_order_itemmeta: Dati: 0.05MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_actions: Dati: 0.13MB + indice: 0.14MB + motore InnoDB
wp_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_logs: Dati: 0.09MB + indice: 0.09MB + motore InnoDB
wp_atum_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_atum_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_atum_product_data: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_dopbsp_api_keys: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_availability: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_dopbsp_availability_no: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_dopbsp_availability_price: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_dopbsp_calendars: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wp_dopbsp_coupons: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_days: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_dopbsp_discounts: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_discounts_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_discounts_items_rules: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_emails: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_emails_translation: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_dopbsp_extras: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_extras_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_extras_groups_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_fees: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_forms: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_forms_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_forms_select_options: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_languages: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_dopbsp_locations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_models: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_reservations: Dati: 0.02MB + indice: 0.14MB + motore InnoDB
wp_dopbsp_rules: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_searches: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_settings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_settings_calendar: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_dopbsp_settings_notifications: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_dopbsp_settings_payment: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_dopbsp_settings_search: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_dopbsp_smses: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_dopbsp_smses_translation: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_dopbsp_translation_en: Dati: 0.33MB + indice: 0.17MB + motore InnoDB
wp_dopbsp_woocommerce: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_mailchimp_carts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_mailchimp_jobs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_options: Dati: 4.14MB + indice: 2.06MB + motore InnoDB
wp_postmeta: Dati: 91.23MB + indice: 68.19MB + motore InnoDB
wp_posts: Dati: 13.41MB + indice: 8.94MB + motore InnoDB
wp_termmeta: Dati: 0.11MB + indice: 0.13MB + motore InnoDB
wp_terms: Dati: 0.09MB + indice: 0.09MB + motore InnoDB
wp_term_relationships: Dati: 14.53MB + indice: 6.52MB + motore InnoDB
wp_term_taxonomy: Dati: 0.11MB + indice: 0.13MB + motore InnoDB
wp_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 3.27MB + indice: 5.63MB + motore InnoDB
wp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 13989
custom_css: 1
feedback: 6
nav_menu_item: 16
page: 17
post: 84
product: 17927
revision: 157
shop_order: 16

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

AJAX Search for WooCommerce: by Damian Góra – 1.6.2 – Non testato con la versione attiva di WooCommerce
Facebook for WooCommerce: by Facebook – 1.10.1
Jetpack by WordPress.com: by Automattic – 8.3
My Custom Functions: by Space X-Chimp – 4.41
Minimum Maximum quantity & Minimum Order amount for WooCommerce: by PI Websolution – 1.3.9 – Non testato con la versione attiva di WooCommerce
Postepay Gateway per Woocommerce: by Martino Stenta – 5.1 – Non testato con la versione attiva di WooCommerce
Product CSV Import Export (BASIC): by WebToffee – 1.7.5 – Non testato con la versione attiva di WooCommerce
WooCommerce Admin: by WooCommerce – 1.0.0 – Non testato con la versione attiva di WooCommerce
WooCommerce Checkout Manager: by QuadLayers – 4.9.5 – Non testato con la versione attiva di WooCommerce
WooCommerce Services: by Automattic – 1.22.4 – 1.23.2 è disponibile
WooCommerce: by Automattic – 4.0.0 – 4.2.0 è disponibile

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Mailchimp for WooCommerce: by Mailchimp – 2.3.4 – Non testato con la versione attiva di WooCommerce
VarkTech Minimum Purchase for WooCommerce: by Vark – 1.09.91.1 – Non testato con la versione attiva di WooCommerce
WooCommerce P.IVA e Codice Fiscale per Italia: by dot4all – 2.1.9 – Non testato con la versione attiva di WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /negozio/
Carrello: #187 - /test-carrello/
Cassa: #202 - /test-cassa/
Il mio account: #9 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Storefront
Version: 2.5.5 – 2.5.7 è disponibile
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/customer-on-hold-order.php

### Action Scheduler ###

Completato: 308
Oldest: 2020-05-17 13:47:25 +0200
Newest: 2020-06-16 15:30:41 +0200

In attesa: 1
Oldest: 2020-06-17 15:30:41 +0200
Newest: 2020-06-17 15:30:41 +0200

`
```
</details>

**Comment by tammullen** [comment] 2020-06-17 12:27
Hi @FAL-Italy 

Thank you for submitting the issue. However I notice you are using a plugin [Product Import Export for Woo](https://en-gb.wordpress.org/plugins/product-import-export-for-woo/) on your site.

Can you clarify where you are performing the import so we can understand if you are using the import functionality of WooCommerce or if you are using this plugin.

I would  also suggest testing your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by FAL-Italy** [comment] 2020-06-17 21:31
Yes, I'm using that plugin, but the problem happens when I attach **manually** an image to my product. When I use the plugin, it works as expected, and the images imported (thousands of them) did not cause any conflict.
I don't know what's the difference between this plugin and the default import functionality, I'm a beginner with WP and Woo, and I just happened to "inherit" this site. As to the theme, I only use the Storefront theme.

**Comment by FAL-Italy** [comment] 2020-06-23 15:22
Yes, I'm using that plugin, but the problem happens when I attach **manually** an image to my product. When I use the plugin, it works as expected, and the images imported (thousands of them) did not cause any conflict.
I don't know what's the difference between this plugin and the default import functionality, I'm a beginner with WP and Woo, and I just happened to "inherit" this site. As to the theme, I only use the Storefront theme.

**Comment by tammullen** [comment] 2021-03-24 19:05
Hi @FAL-Italy 

Apologies for the delayed reply.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case; In particular see this section on importing products https://docs.woocommerce.com/document/product-csv-importer-exporter/
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-24 19:05 UTC
Labels: has feedback
