### ISSUE TITLE
Client ordered from Woocomerce and Woocomerce displayed wrong order details. Only tax is calculated but the cost is displayed as zero!

### ISSUE THREAD

**Issue by mzlataric** [woocommerce/woocommerce#19385] opened 2018-03-13 13:41 UTC
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ]X I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Woocomerce is working great. But! On one order where buyer on shop exceeded wait time woocomerce calculated wrong cost of order. It displays cost as zero but it calculated the good tax. Also the right amount was charged from credit card of buyer. 
2. We need to reset ? the invoice for our accounting and finance of the state  because the displayed cost was not the cost that was charged
3. How can we do it? We need to correct the invoice to right amount. So once more. Only tax was calculated and cost is displayed as zero even though the right amount was charged from the credit card.
4. Bug only appeared once.  So the problem is how can we reset the amounts displayed on invoice to match the amount that was charged to client?

SCREENSHOT
https://www.dropbox.com/s/auzs0yy4qr26j59/dani.png?dl=0

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

WordPress environment
--
Home URL: |   | http://makeup.reviderm.hr
Site URL: |   | http://makeup.reviderm.hr
WC version: |   | 3.3.3
Log directory writable: |   | /home/reviderm/makeup/wp-content/uploads/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | hr

Server info: |   | Apache
-- | -- | --
PHP version: |   | 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP post max size: |   | 20 MB
PHP time limit: |   | 0
PHP max input vars: |   | 5000
cURL version: |   | 7.54.0, OpenSSL/1.0.2k
SUHOSIN installed: |   |  
MySQL version: |   | 5.6.39
Max upload size: |   | 20 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |  



```
</details>

**Comment by mikejolley** [comment] 2018-03-13 14:22
> On one order where buyer on shop exceeded wait time 

What do you mean by that?

Also need to see if you're running extensions and what.

**Comment by mzlataric** [comment] 2018-03-13 15:32
There were no extensions. Woocomerce was up and running. We got 10 orders that day. And only one had false information on it. As you can see in the picture. And the error we received from woocomerce was that the wait time was exceeded when client was giving (payment information). They waited 2 hours before they pressed the button pay so we assumed that that has generated the error.

do  you need permission to access our woocomerce?

I can not explain it in words that is why I have uploaded picture of the error where you can see that the cost of products was zero but the correct tax was applied. I can not find answer anywhere online for it.

**Comment by mikejolley** [comment] 2018-03-13 18:08
Please don't give misinformation here - I can see you're using an extension/plugin because it has a meta box.

Provide the full status report.

**Comment by mzlataric** [comment] 2018-03-13 22:03
What are you talking about, what misinformation? I am telling you about the problem, you are swinging around the question with more questions and no answers. What metabox from Yoast SEO ?  It was always on when other 10 successful purchases were made as well as one that malfunctioned. And the one that malfunctioned is causing the problems to whole company.

And what do you need from what kind of status report? I don`t understand. Please state clearly so I can give you what you need.

**Comment by mikejolley** [comment] 2018-03-13 22:49
First off, this is a place to report bugs with core, not solicit technical support. Thats why we ask that you go through the "Isolating the problem" steps (you did not) and provide "Steps to reproduce the issue" anyone can try on their own install (not the case here either). 

Second I asked if you had other extensions active, which you say you don't but clearly in this screenshot you have a PDF extension active because I can see the meta box https://www.dropbox.com/s/auzs0yy4qr26j59/dani.png?dl=0

> And what do you need from what kind of status report? I don`t understand. Please state clearly so I can give you what you need.

The new issue page already lists everything it needs https://github.com/woocommerce/woocommerce/issues/new:

> Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

You did not do this or show what plugins/themes are active (this is included in the report).

>  you are swinging around the question with more questions and no answers

No one can give you answers without details about the issue. If you want someone to look at the issue directly and log into admin to take a look, I suggest you use the helpdesk instead. We cannot do that here and we certainly cannot debug issues on your site.

Thanks

**Comment by mikejolley** [comment] 2018-03-15 11:42
Closing this due to lack of updates. Feel free to reach out to the helpdesk if you need some assistance. Thanks.

**Closed by mikejolley** 2018-03-15 11:42 UTC
Labels: Status: Needs Feedback
