### ISSUE TITLE
Remove cart item and updating cart doesnt work after update woocommerce not found

### ISSUE THREAD

**Issue by Woohurk** [woocommerce/woocommerce#27677] opened 2020-09-15 15:11 UTC
After the last update i suddenly am unable to delete / remove items from the cart and also can not update cart and price after amount change. 
![Schermafbeelding 2020-09-15 om 16 32 48](https://user-images.githubusercontent.com/71337038/93229038-71764780-f776-11ea-9e8d-c557e518cdd8.png)
![Schermafbeelding 2020-09-15 om 16 50 18](https://user-images.githubusercontent.com/71337038/93229048-73d8a180-f776-11ea-984a-febb7200798d.png)
![Schermafbeelding 2020-09-15 om 16 50 22](https://user-images.githubusercontent.com/71337038/93229050-74713800-f776-11ea-8f1e-e9d72f70188b.png)

### WordPress Environment ###

WordPress address (URL): https://www.wijnkado.nl
Site address (URL): https://www.wijnkado.nl
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.22
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wpjd_
Totale databasegrootte: 30.04MB
Database datagrootte: 26.07MB
Database index grootte: 3.97MB
wpjd_woocommerce_sessions: Data: 6.02MB + Index: 1.02MB + Engine InnoDB
wpjd_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpjd_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpjd_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wpjd_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpjd_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wpjd_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_actionscheduler_logs: Data: 0.28MB + Index: 0.22MB + Engine InnoDB
wpjd_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wpjd_ewwwio_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_litespeed_cssjs: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
wpjd_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_options: Data: 8.03MB + Index: 0.13MB + Engine InnoDB
wpjd_postmeta: Data: 1.42MB + Index: 0.64MB + Engine InnoDB
wpjd_posts: Data: 8.08MB + Index: 0.22MB + Engine InnoDB
wpjd_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_css: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpjd_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpjd_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpjd_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpjd_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpjd_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpjd_yoast_indexable: Data: 0.25MB + Index: 0.19MB + Engine InnoDB
wpjd_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpjd_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpjd_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpjd_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 100
custom_css: 1
nav_menu_item: 6
oembed_cache: 2
page: 13
post: 2
postman_sent_mail: 206
product: 45
revision: 159
shop_order: 305
shop_order_refund: 1
slide: 3
uni_cpo_option: 1
wcpa_pt_forms: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

All 404 Redirect  to Homepage: door Fakhri Alsadi – 1.20
Contact Form 7: door Takayuki Miyoshi – 5.2.2
Dupliceer pagina: door mndpsingh287 – 4.3
Enhanced E-commerce for Woocommerce store: door Tatvic – 2.3.5 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
EWWW Image Optimizer: door Exactly WWW – 5.7.0
Avada Builder: door ThemeFusion – 3.0.2
Avada Core: door Thema opties – 5.0.2
LiteSpeed Cache: door LiteSpeed Technologies – 3.4.2
Loco Translate: door Tim Whitlock – 2.4.3
Mailchimp voor WooCommerce: door Mailchimp – 2.4.5 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
Mollie-betalingen voor WooCommerce: door Mollie – 5.8.3
Post SMTP: door Yehuda Hassine – 2.0.15
Really Simple SSL: door Really Simple Plugins – 3.3.5
WooCommerce: door Automattic – 4.5.2
Yoast SEO: door Team Yoast – 14.9 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2

### Inactive Plugins (1) ###

WooCommerce Extra Product Options Pro: door ThemeHigh – 2.4.2 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Winkelbasis: #7 - /winkel/
Winkelmand: #8 - /winkelmand/
Afrekenen: #9 - /afrekenen/
Mijn account: #10 - /mijn-account/
Algemene voorwaarden: #3 - /privacy-verklaring/

### Theme ###

Name: Avada
Version: 7.0.2
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Action Scheduler ###

Afgerond: 162
Oldest: 2020-08-17 08:25:59 +0000
Newest: 2020-09-15 15:06:18 +0000

In afwachting: 1
Oldest: 2020-09-15 15:07:18 +0000
Newest: 2020-09-15 15:07:18 +0000

`

**Comment by juliaamosova** [comment] 2020-09-15 15:24
Hi @Woohurk,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Updating the cart and removing items from the cart is working as expected on my end using WooCommerce 4.5.2. 

Below is a gif documenting my experience (I am using our default Storefront theme):

![](http://g.recordit.co/Vw6lUoSuuz.gif)

>and also can not update price after amount change.

It is not clear what it means, can you please clarify?

As far as the cart issue, I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by Woohurk** [comment] 2020-09-15 15:35
I solved it. A cacheing plugin did some kind of thing to the JS files. Back upped and now works fine again. Im sorry for haveing reported it. Because deleting the plugins didnt change a thing but replacing the back up did. Now wil check step by step to optimize the page speed and try to exclude the woocommerce files.

**Closed** 2020-09-15 15:35 UTC
Labels: can't reproduce, status: needs feedback

**Comment by juliaamosova** [comment] 2020-09-15 15:42
Thanks for letting us know @Woohurk. Glad to know the issue is fixed on your end.
