### ISSUE TITLE
All Products Disappear from my Woo Commerce Shop Page w/ Storefront Theme

### ISSUE THREAD

**Issue by railroadGH** [woocommerce/woocommerce#25238] opened 2019-12-15 11:20 UTC
Hi,

Very often all of my products disappear from my Woo Commerce Shop page on my website therailroadpress.com until I go to my dashboard and click on Woo Commerce. It happens almost every day. I've copied my status report below. My email is info@therailroadpress.com. Thank you very much for your help!

James

`
### WordPress Environment ###

WordPress address (URL): https://therailroadpress.com
Site address (URL): https://therailroadpress.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.25
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: _D0H_
MaxMind GeoIP Database: ✔
Total Database Size: 32.82MB
Database Data Size: 31.61MB
Database Index Size: 1.21MB
_D0H_woocommerce_sessions: Data: 6.27MB + Index: 0.31MB + Engine MyISAM
_D0H_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_D0H_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_D0H_comments: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
_D0H_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_options: Data: 2.04MB + Index: 0.11MB + Engine MyISAM
_D0H_postmeta: Data: 11.71MB + Index: 0.22MB + Engine MyISAM
_D0H_posts: Data: 11.28MB + Index: 0.08MB + Engine MyISAM
_D0H_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_termmeta: Data: 0.06MB + Index: 0.05MB + Engine MyISAM
_D0H_terms: Data: 0.06MB + Index: 0.10MB + Engine MyISAM
_D0H_term_relationships: Data: 0.09MB + Index: 0.21MB + Engine MyISAM
_D0H_term_taxonomy: Data: 0.07MB + Index: 0.05MB + Engine MyISAM
_D0H_UPCP_Catalogues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Catalogue_Items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Custom_Fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Fields_Meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Item_Images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_SubCategories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Tagged_Items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Tag_Groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_UPCP_Videos: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_D0H_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_D0H_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_D0H_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_D0H_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_D0H_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Elementor: by Elementor.com – 2.8.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.1
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 8.0
Mailchimp for WooCommerce: by Mailchimp – 2.3 – Not tested with the active version of WooCommerce
Make Builder: by The Theme Foundry – 1.1.8
MOJO Marketplace: by Mike Hansen – 1.4.5
OptinMonster API: by OptinMonster Team – 1.9.5
WooCommerce Auto Category Thumbnails: by Shellbot – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Services: by Automattic – 1.22.2
WooCommerce: by Automattic – 3.8.1
WPForms Lite: by WPForms – 1.5.7

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Product Catalog: by Etoile Web Design – 4.4.18
Tiled Galleries Carousel Without Jetpack: by Raja CRN – 3.0

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 1.5
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #64 - /shop/
Cart: #65 - /cart/
Checkout: #66 - /checkout/
My account: #67 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2019-11-21 10:31:31 +0000
Newest: 2019-12-12 10:46:55 +0000

Pending: 2
Oldest: 2019-12-19 10:46:56 +0000
Newest: 2019-12-19 10:46:57 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by juliaamosova** [comment] 2019-12-16 10:11
Hi there @railroadGH,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed** 2019-12-16 10:11 UTC

**Comment by railroadGH** [comment] 2019-12-16 17:32
Hi Julia,

Thank you for your timely and detailed response! I will follow your  
instructions and see what I can do.

James


Quoting Julia Amosova <notifications@github.com>:
