### ISSUE TITLE
403 ajax cart errors while logging in during checkout and cannot logout.

### ISSUE THREAD

**Issue by boethius** [woocommerce/woocommerce#22044] opened 2018-11-26 15:27 UTC
**Describe the bug**
Two symptoms. 
1. Logging in via the "Existing Customer? Click here..." causes 403 ajax errors.
2. If you try to logout via the account, user just gets redirected back to the same page with `_wp_nonce` still showing.

**To Reproduce**
1. Go to Skincode.com and create account & clear cookies.
2. Add a product to the cart.
3. Proceed to checkout, payment works fine (no 403s)
4. Scroll back up and log in using the inline form.
5. Scroll back down and the payment option is disabled (after some moments.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.
- [x] Logging in using Account > Login or /wp-admin/ does not produce this problem.
- [x] This issue occurs also when CloudFlare is bypassed (I accessed the site directly).
- [x] I have tried several cookie domain configurations to no avail.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: https://skincode.com
Site URL: https://skincode.com
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.32-0ubuntu0.16.04.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.24-0ubuntu0.16.04.1
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 34.84MB
Database Data Size: 27.40MB
Database Index Size: 7.44MB
wp_woocommerce_sessions: ❌ Table does not exist
wp_woocommerce_api_keys: ❌ Table does not exist
wp_woocommerce_attribute_taxonomies: ❌ Table does not exist
wp_woocommerce_downloadable_product_permissions: ❌ Table does not exist
wp_woocommerce_order_items: ❌ Table does not exist
wp_woocommerce_order_itemmeta: Data: 0.71MB + Index: 0.47MB
wp_woocommerce_tax_rates: ❌ Table does not exist
wp_woocommerce_tax_rate_locations: ❌ Table does not exist
wp_woocommerce_shipping_zones: ❌ Table does not exist
wp_woocommerce_shipping_zone_locations: ❌ Table does not exist
wp_woocommerce_shipping_zone_methods: ❌ Table does not exist
wp_woocommerce_payment_tokens: ❌ Table does not exist
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: ❌ Table does not exist
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.25MB + Index: 0.14MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 4.68MB + Index: 0.13MB
wp_postmeta: Data: 11.57MB + Index: 2.87MB
wp_posts: Data: 3.93MB + Index: 0.44MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_signups: Data: 0.16MB + Index: 0.23MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 1.02MB + Index: 0.03MB
wp_termmeta: Data: 0.03MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.04MB
wp_term_relationships: Data: 0.10MB + Index: 0.22MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 4.39MB + Index: 2.24MB
wp_users: Data: 0.33MB + Index: 0.32MB
wp_woocommerce_bundled_itemmeta: Data: 0.09MB + Index: 0.13MB

### Post Type Counts ###

amn_exact-metrics: 1
analysis-question: 17
attachment: 1820
avia_framework_post: 7
location: 67
mb_woc_wheel: 4
meta-box: 2
module: 19
nav_menu_item: 369
oembed_cache: 2
page: 135
portfolio: 1
post: 110
postman_sent_mail: 250
product: 338
revision: 410
shop_coupon: 414
shop_order: 447
shop_order_refund: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Gravity Forms: by rocketgenius – 2.3.6
API KEY for Google Maps: by GeoDirectory – 1.2.0
Facebook for WooCommerce: by Facebook – 1.4.2 – Not tested with the active version of WooCommerce
Gravity Forms Multilingual: by OnTheGoSystems – 1.3.17
Gravity Forms MailChimp Add-On: by rocketgenius – 4.4
iubenda Cookie Solution for GDPR: by iubenda – 1.15.3
WP Optin Wheel Pro: by StudioWombat – 3.0.9 – Not tested with the active version of WooCommerce
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Not tested with the active version of WooCommerce
MB Settings Page: by MetaBox.io – 1.3.4
Meta Box Group: by MetaBox.io – 1.2.17
Redirection: by John Godley – 3.6.3
Slider Revolution Backup Add-on: by ThemePunch – 1.0.2
SendGrid: by SendGrid – 1.11.8
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.1.2 – 4.6.0 is available – Not tested with the active version of WooCommerce
WooCommerce Export Customer Email: by MH Mithu – 1.3 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1855 - /products/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #1089 - /terms-and-condition/

### Theme ###

Name: Skincode
Version: 1.0 (3.4.5)
Author URL: http://boethius.ch
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.4.1
Parent Theme Author URL: https://kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: skincode/woocommerce/emails/admin-cancelled-order.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/admin-new-order.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/customer-completed-order.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/customer-invoice.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/customer-new-account.php version 1.6.4 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/customer-note.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/customer-processing-order.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/customer-refunded-order.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/customer-reset-password.php version 2.0.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/email-addresses.php version 2.4.0 is out of date. The core version is 3.2.1
skincode/woocommerce/emails/email-footer.php
skincode/woocommerce/emails/email-header.php
skincode/woocommerce/emails/email-order-items.php version 2.1.2 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/email-styles.php version 2.3.0 is out of date. The core version is 3.3.0
skincode/woocommerce/emails/plain/admin-cancelled-order.php version 2.3.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/admin-new-order.php version 2.3.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/customer-completed-order.php version 2.3.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/customer-invoice.php version 2.2.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/customer-new-account.php version 2.0.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/customer-note.php version 2.3.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/customer-processing-order.php version 2.3.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/customer-refunded-order.php version 2.4.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/customer-reset-password.php version 2.3.0 is out of date. The core version is 3.5.0
skincode/woocommerce/emails/plain/email-addresses.php version 2.2.0 is out of date. The core version is 3.4.0
skincode/woocommerce/emails/plain/email-order-items.php version 2.1.2 is out of date. The core version is 3.2.0

Outdated Templates: ❌
					
					
						Learn how to update

### Customer/Order CSV Export ###

Order Export Format: default
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
</details>

Thanks!

**Comment by boethius** [comment] 2018-11-29 08:45
Do let me know when you begin testing, I have had to disable the inline login as that seems to be the only way a user get's caught in this error.

**Comment by rrennick** [comment] 2019-01-15 19:38
@boethius Can you provide details on reproducing this issue in a development/staging install?

**Comment by mikejolley** [comment] 2019-02-01 16:41
I'm not getting this on my own installs. Login is working.

Since this issue report does not give us enough information to reproduce on a clean install I'm going to close it - it is most likely a conflict with either something you have installed, or your web hosting (which I notice is reporting missing tables in your status report!). Please investigate that and go through the prerequsitite steps listed on the new issue form.

If you want someone to login and look at your install, you'll need to go via the helpdesk since we cannot take care of that on GitHub (it's public).

Thanks

**Closed by mikejolley** 2019-02-01 16:41 UTC
Labels: status: needs feedback
