### ISSUE TITLE
Woo Commerce attributes not showing up in front end after update this week

### ISSUE THREAD

**Issue by zinctwentyone** [woocommerce/woocommerce#22843] opened 2019-02-24 19:15 UTC
**Describe the bug**
Updated wordpress and woo commerce yesterday and my size attributes were cut in half, deleted those and created new size attributes and now nothing shows. However Color does show up. 

Have deleted all plugins including ppom custom fields which was stopping the ability of updating variations originally. 

Changed var to 5000 no help, deleted woo commerce and reinstalled no help, contacted theme devs and was told to try wordpress basic theme, did and no help. 
Raised memory no help.

**Comment by zinctwentyone** [comment] 2019-02-24 19:16
Also I installed plug in fix by Mike Jolley in another issue similar to mine, no help.

**Comment by zinctwentyone** [comment] 2019-02-25 03:35
I found a manual work around for my site since its only like 10 products. It has 3 attributes and after the update 2 were working and the first one size was no longer working which stopped sales cold the entire weekend. 

I was able to go into the variations link and unlike its normal operation where the variations will say any size, any color and any font color and you click update variations and it works. This time it didn't work so instead I manually updated in each product all sizes. So it was size xs to any color and any font color, s to any color and any font color and so on which ended up working. 

If I had 50 plus products on the next update and the same thing happened again, this would be too much work for each update.

**Comment by mikejolley** [comment] 2019-02-26 12:38
I'm afraid there isn't much we can do to investigate this without more details and steps to reproduce a bug. The new issue form (https://github.com/woocommerce/woocommerce/issues/new/choose) lists prerequsistes e.g. testing with extensionds disabled and providing system status report, which are missing from this issue.

It sounds like the variation/attribute data was corrupted by something however I don't know which version you updated from, what the attributes were, and whether extensions/theme on your site could be responsible for updating those values wrongly.

In the past, issues like this have been caused by special characters in attribute names, however, it's been a while since those have resurfaced and as far as I'm aware, the last minor fix release did not touch this logic, and neither did 5.1.

If you can provide more details please go ahead but for now I'm marking this issue closed as it lacks detail.

Thanks

**Closed by mikejolley** 2019-02-26 12:38 UTC
