### ISSUE TITLE
Add-to-cart not working for guest users

### ISSUE THREAD

**Issue by pfac** [woocommerce/woocommerce#25211] opened 2019-12-11 02:43 UTC
**Describe the bug**
`wp_woocommerce_session` is not being set when adding a product to the cart if the user is not signed in. Consequently, the shopping cart remains empty.

If the user is signed in, everything works normally.

Issue persists in all languages with the guest user, and works as intended in all languages with authenticated users.

I can see the session is being properly inserted in the database for guest users. Found [an answer on StackOverflow](https://stackoverflow.com/a/37696310) stating it could be related to a bad database migration, but the session ID is auto-incrementing correctly and everything seems to be fine.

This shop was migrated from an older (neglected) server to Namecheap's EasyWP using [All-in-One WP Migration](https://wordpress.org/plugins/all-in-one-wp-migration/). So far with no flaws.

Both Wordpress and all plugins are now up-to-date, and from what I was able to see there's nothing interfering with WooCommerce normal operation.

Changed theme wondering if it could be anything weird in the presentation layer, but the issue persists. Also discarding other plugin interference by deactivating all other plugins and confirming the problem persists.

Checked past issues here on GitHub like #3769 (for which I cleared all cache, issue remains) and #7506 (disabled AJAX in config, issue remains) with no luck.

**To Reproduce**
1. Go to https://3oceans-43eba0.ingress-alpha.easywp.com/en/loja/iii-oceans-polo-5/
2. Select `M` for size (_Tamanho_)
3. Click on _Add to basket_
4. Success notification `“III Oceans Polo” has been added to your basket.` is shown
3. Click on _View basket_
4. See message `Your basket is currently empty.`

**Screenshots**
Don't believe it will help.

**Expected behavior**
Expected basket to contain 1 item _III Oceans Polo_ of the selected size.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
### WordPress Environment ###

WordPress address (URL): https://3oceans-43eba0.ingress-alpha.easywp.com
Site address (URL): https://3oceans-43eba0.ingress-alpha.easywp.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_PT
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.14.2
PHP Version: 7.3.0
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.61.1
LibreSSL/2.0.0

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Tamanho total da base de dados: 36.59MB
Tamanho dos dados da base de dados: 24.86MB
Tamanho do índice da base de dados: 11.73MB
wp_woocommerce_sessions: Dados: 0.06MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.13MB + Índice: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_woocommerce_log: Dados: 0.00MB + Índice: 0.00MB + Engine MyISAM
wp_90e5ddf4d6_commentmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_90e5ddf4d6_comments: Dados: 0.02MB + Índice: 0.08MB + Engine InnoDB
wp_90e5ddf4d6_links: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_90e5ddf4d6_options: Dados: 0.03MB + Índice: 0.02MB + Engine InnoDB
wp_90e5ddf4d6_postmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_90e5ddf4d6_posts: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_90e5ddf4d6_termmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_90e5ddf4d6_terms: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_90e5ddf4d6_term_relationships: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_90e5ddf4d6_term_taxonomy: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_90e5ddf4d6_usermeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_90e5ddf4d6_users: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_cimy_uef_data: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_cimy_uef_fields: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_cimy_uef_wp_fields: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_commentmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_comments: Dados: 0.11MB + Índice: 0.11MB + Engine InnoDB
wp_easypay_notifications: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_easypay_notifications_2: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_easypay_transaction_keys: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_fmera_fields: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_fmera_meta: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_icl_content_status: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_core_status: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_flags: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_languages: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Dados: 0.19MB + Índice: 0.11MB + Engine InnoDB
wp_icl_locale_map: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_icl_message_status: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_icl_node: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_icl_reminders: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_icl_strings: Dados: 2.52MB + Índice: 1.98MB + Engine InnoDB
wp_icl_string_pages: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_string_positions: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_string_status: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_string_translations: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_string_urls: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_translate: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_translate_job: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_icl_translations: Dados: 0.05MB + Índice: 0.06MB + Engine InnoDB
wp_icl_translation_batches: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_icl_translation_status: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_links: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_options: Dados: 1.50MB + Índice: 0.06MB + Engine InnoDB
wp_postmeta: Dados: 9.52MB + Índice: 6.03MB + Engine InnoDB
wp_posts: Dados: 3.52MB + Índice: 0.61MB + Engine InnoDB
wp_responsive_menu_pro: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_rg_form: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_rg_form_meta: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_rg_form_view: Dados: 0.11MB + Índice: 0.11MB + Engine InnoDB
wp_rg_incomplete_submissions: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_rg_lead: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_rg_lead_detail_long: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_smush_dir_images: Dados: 0.00MB + Índice: 0.00MB + Engine MyISAM
wp_sp_email_logs: Dados: 0.00MB + Índice: 0.00MB + Engine MyISAM
wp_termmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_terms: Dados: 0.05MB + Índice: 0.03MB + Engine InnoDB
wp_term_relationships: Dados: 0.11MB + Índice: 0.08MB + Engine InnoDB
wp_term_taxonomy: Dados: 0.06MB + Índice: 0.03MB + Engine InnoDB
wp_usermeta: Dados: 0.05MB + Índice: 0.03MB + Engine InnoDB
wp_users: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_wc_download_log: Dados: 0.00MB + Índice: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Dados: 0.11MB + Índice: 0.30MB + Engine InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_wc_webhooks: Dados: 0.00MB + Índice: 0.00MB + Engine MyISAM
wp_wfblockediplog: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wfblocks7: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_wfconfig: Dados: 0.45MB + Índice: 0.00MB + Engine InnoDB
wp_wfcrawlers: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wffilechanges: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wffilemods: Dados: 2.52MB + Índice: 0.00MB + Engine InnoDB
wp_wfhits: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_wfhoover: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_wfissues: Dados: 0.05MB + Índice: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Dados: 1.52MB + Índice: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_wflocs: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wflogins: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_wfls_settings: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wfnotifications: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wfpendingissues: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_wfreversecache: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wfsnipcache: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_wfstatus: Dados: 0.13MB + Índice: 0.09MB + Engine InnoDB
wp_wftrafficrates: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wpfm_backup: Dados: 0.00MB + Índice: 0.00MB + Engine MyISAM
wp_wplc_chat_msgs: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wplc_chat_sessions: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wplc_offline_messages: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wplc_webhooks: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_campaign: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_campaign_list: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_custom_field: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_email: Dados: 0.08MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_email_user_stat: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_email_user_url: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_form: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_list: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_queue: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_wysija_url: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_url_mail: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_user: Dados: 0.08MB + Índice: 0.02MB + Engine InnoDB
wp_wysija_user_field: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_user_history: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wysija_user_list: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Dados: 0.01MB + Índice: 0.00MB + Engine MyISAM
wp_yoast_seo_meta: Dados: 0.02MB + Índice: 0.03MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Polylang: por WP SYNTEX – 2.6.7
WooCommerce: por Automattic – 3.8.1
Wordfence Security: por Wordfence – 7.4.2

### Inactive Plugins (24) ###

Cookie Notice: por dFactory – 1.2.48
Disable Blog: por Joshua Nelson – 0.4.6
Gravity Forms: por rocketgenius – 2.1.2
Loco Translate: por Tim Whitlock – 2.3.1
Maintenance: por WP Maintenance – 3.85
MetaSlider: por Team Updraft – 3.15.3
NIF (Num. de Contribuinte Português) for WooCommerce: por Webdados – 4.2.3
Optimus: por KeyCDN – 1.6.0
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 3.1.2
Smush: por WPMU DEV – 3.3.2
Social Icons Widget by WPZOOM: por WPZOOM – 3.4.1
SVG Support: por Benbodhi – 2.3.15
The SEO Framework: por The SEO Framework Team – 4.0.4
WC - APG Free Shipping: por Art Project Group – 2.4.0.5
WC - APG Weight Shipping: por Art Project Group – 2.3.1.4
WC Secondary Product Thumbnail: por Hendy Tarnando – 1.3.2 – Não testado com a versão activa do WooCommerce
WooCommerce Availability Scheduler: por Lagudi Domenico – 6.3 – Não testado com a versão activa do WooCommerce
WooCommerce Bulk Edit Product Variations: por matterico_themes – 2.6 – Não testado com a versão activa do WooCommerce
WooCommerce Easypay Gateway Cartao de Credito: por Easypay – 2.00 – Não testado com a versão activa do WooCommerce
WooCommerce Easypay Gateway MBWay: por Easypay – 2.00 – Não testado com a versão activa do WooCommerce
WooCommerce Easypay Gateway MultiBanco: por Easypay – 2.00 – Não testado com a versão activa do WooCommerce
WP File Manager: por mndpsingh287 – 5.5
WP Mail Logging: por MailPoet – 1.9.5
Yoast SEO: por Team Yoast – 12.6.2

### Dropin Plugins (1) ###

object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (1) ###

EasyWP Plugin: por Namecheap
Inc. – 0.4.8


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: dgfw_gift (dgfw_gift)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Página da Loja: #3066 - /en/shop-en/
Carrinho: #2892 - /en/shopping-cart/
Finalizar compras: #5342 - /en/checkout/
Minha conta: #5351 - /en/account/
Termos e condições: #3122 - /en/terms-and-conditions/

### Theme ###

Name: Twenty Twenty
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – Se estiver a modificar o tema do WooCommerce ou um tema principal que não construiu pessoalmente
recomendamos o uso de um tema dependente. Veja: Como criar um tema dependente

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 19
Oldest: 2019-11-24 01:16:07 +0000
Newest: 2019-11-24 01:16:24 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```

</details>

**Comment by juliaamosova** [comment] 2019-12-12 16:59
@pfac I can see the issue on your site but I can't reproduce it on any of my tests sites. The issue is likely related to your specific setup and the history of migration. 

There is a good article that explains [how to troubleshoot empty cart issues](https://businessbloomer.com/woocommerce-solving-cart-empty-issue/) - I recommend you try to take the steps listed there. 

If this won't help, you'd likely need to create a new site and import your products there. You can use the built-in WooCommerce Export / Import feature to do that. 

Other than that, I recommend doing the following:

* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-12-12 16:59 UTC

**Comment by pfac** [comment] 2019-12-14 14:46
Confirmed with the `wordpress:5.3.1-php7.3` Docker image.Exported from this store, imported in the Docker image, add to cart by guests works.

No idea what the hell is happening here, but I guess I'll have to drop this.

Thanks anyway :+1:
