### ISSUE TITLE
Исчезла кнопка ОБНОВИТЬ в закладке Товары Добавить

### ISSUE THREAD

**Issue by elenvaleeva** [woocommerce/woocommerce#27380] opened 2020-08-18 14:37 UTC
Добавление Товаров в магазин. Исчезла кнопка ОБНОВИТЬ и вся верхняя часть 

![image](https://user-images.githubusercontent.com/69858012/90526709-28889e80-e18a-11ea-9a66-812634d471c3.png)

Сейчас добавить товар в магазин не получается соответственно

**Comment by juliaamosova** [comment] 2020-08-18 18:03
Hi @elenvaleeva,

Please note that we reply to bug reports in the English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

>Adding Products to the store. The UPDATE button and the entire upper part disappeared

>Now it is impossible to add a product to the store, respectively

I am sorry to hear about the trouble. Can you please confirm what version of WooCommerce and WordPress are you using? This bug had been fixed in WooCommerce 4.3.2 if you are using WordPress 5.5.

**Comment by juliaamosova** [comment] 2020-08-18 18:31
@elenvaleeva, It is highly likely that the issue you are having is caused by one of the 3rd party plugins on your site if you are using WooCommerce 4.3.2 and above and the issue is present. 
​
WordPress 5.5 removed a javascript file called jQuery migrate that some of your plugins might have relied on, so until they update, you might want to use [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper) plugin to include the javascript files in the meantime. 

I also recommend you conflict test your site. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Once you know which plugin is causing the issue, deactivate it if possible and contact the author of the plugin directly for further help on when they plan to update their plugins.

**Comment by tammullen** [comment] 2020-08-28 10:38
Hi @elenvaleeva 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2020-08-28 10:38 UTC
Labels: status: needs feedback
