### ISSUE TITLE
Rounded amount subtotal with 0,01 cent added on order-received page

### ISSUE THREAD

**Issue by antoine4269ww** [woocommerce/woocommerce#23694] opened 2019-05-13 19:48 UTC
Hi

I encounter a rounded subtotal problem on the order reception and the invoice PDF. Some 0,01 cent is added to the subtotal amount.
The subtotal amount is always correct while processing the order. After payment, the page shown contains randomly some 0,01€ added and sometines not (the order details page shown).

I run a fresh WP site with last Woocommerce 362 and I’ve checked all the modification since 2019/01 on Github and these mods are in the Woocommerce files. This problem had been reported then fixed but, in my case, still occurs.
The real error happens on a production site so I wanted to test the case on a test website.

Here’s the screenshot of an order with the problem.
https://i.imgur.com/qaf6Bb0.png

In Woocommerce, I enter my prices products with VAT (20%).
Currency:€ , Currency symbol: right , Decimals positions: 2 decimals
https://imgur.com/FxnxGyK
My VAT is rounded per line (if I tick by subtotal, it's worse).

Could you replicate this case, and tell me more about it please.
I have 3 products: 1 product at 7,50€ VAT of 20% included + 1 product at 7€ VAT of 20% included + 1 product at 25€ VAT of 20% included.
So subtotal = 39,50€ and total = 39,50€ (I apply free shipping)

Has somebody an idea of these errors ?
Thanks
Patrick

**Comment by antoine4269ww** [comment] 2019-05-16 07:06
Hi,
Has someone already met this case ?
Thanks

**Comment by kloon** [comment] 2019-05-22 07:38
Hi, could you please attach your system status report and also complete the template you were asked to complete when you opened up the issue? Did you test with all plugins disabled and your theme switched to a default one like Twentseventeen?

**Comment by antoine4269ww** [comment] 2019-05-22 09:25
**Describe the bug**
I encounter a rounded subtotal problem on the order reception and the invoice PDF. Some 0,01 cent is added to the subtotal amount.
The subtotal amount is always correct while processing the order. After payment, the page shown contains randomly some 0,01€ added to the subtotal amount and sometines not.

I run a fresh WP site with last Woocommerce 363 and I’ve checked all the modification since 2019/01 on Github and these mods are in the Woocommerce files. This problem had been reported then fixed but, in my case, still occurs.
The real error happens on a production site so I wanted to test the case on a test website and the error also diaplays.
Here’s the screenshot of an order with the problem.
https://i.imgur.com/qaf6Bb0.png
In Woocommerce, I enter my prices products with VAT (20%).
Currency:€ , Currency symbol: right , Decimals positions: 2 decimals
https://imgur.com/FxnxGyK
My VAT is rounded per line (if I tick by subtotal, it's worse).
Woocommerce > Settings > General tab : Activate the VAT -> yes

**To Reproduce**
Steps to reproduce the behavior:
1. Go to http://www.siteswsc.biz/wp511savon/produit/baume/ and click the button 'Ajouter au panier' button (add to cart)
2. Go to http://www.siteswsc.biz/wp511savon/produit/cremeux-de-karite/ and click the button 'Ajouter au panier' button (add to cart)
3. Go to http://www.siteswsc.biz/wp511savon/produit/savon-liquide-natuire/ choose the 250ml option from Contenance dropdown menu, and add the product to the cart
4. Go to the cart (http://www.siteswsc.biz/wp511savon/panier/), check it the 3 products all well added, the total mount shows be 39,50€ VAT included which is correct
5. On the Cart page (http://www.siteswsc.biz/wp511savon/panier/), click the 'Valider la commande' blue button to validate the order
6. Then, you are leaded to http://www.siteswsc.biz/wp511savon/commande/
6. For the Client Details, enter Name: whatever name, First Name: whatever First name, Country: France, Address1: 174 Route de Cubelle, Zip code: 42380, City: Merle Leignec, Phone: 0477502723, Email: your email address, then click to Accept the TOS, then click the blue button 'Commander'
7. See error on the the displayed page http://www.siteswsc.biz/wp511savon/commande/order-received/order-number/xxx/xxx that displays, the table under the words 'Détails de la commande', the subtotal (sous-total line) displays 39,51€ and it should display 39,50€

**Screenshots**
See above the screenshots

**Expected behavior**
On the the displayed page order-received, the subtotal displays 39,51€ and it should display 39,50€

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, the WP Theme Twenty Nineteen
- [x] I can reproduce this bug consistently using the steps above. Yes with the products with the prices indicated in the **To reproduce** step, I can reproduce the case, but the probleme is random, with other prices it could be correct or not.

**WordPress Environment**
<details>
Environnement WordPress
Adresse (URL) de WordPress : 		http://www.siteswsc.biz/wp511savon
Adresse du site (URL) : 		http://www.siteswsc.biz/wp511savon
Version de WooCommerce: 		3.6.3
Dossier journaux enregistrable: 		/home2/siteswsc/public_html/wp511savon/wp-content/uploads/wc-logs/
Version de WordPress : 		5.2.1	
WordPress multisite : 		–
Limite de mémoire de WordPress: 		256 MB	
Mode de débogage de WordPress : 		–
Cron de WordPress : 		
Langue: 		fr_FR
Cache d’objet externe : 		–
Environnement serveur
Info serveur : 		LiteSpeed
Version PHP : 		7.1.29 - Nous recommandons d’utiliser PHP 7.2 ou supérieur pour optimiser les performances et la sécurité. Comment mettre à jour votre version de PHP ?	
Poids Max Post PHP : 		8 MB
Limite d’exécution PHP : 		30
PHP Max Input Vars : 		1000
Version de cURL : 		7.62.0, OpenSSL/1.0.2k
SUHOSIN installé : 		–
Version MySQL : 		5.7.26	
Taille maximale de téléversement : 		2 MB
Le fuseau horaire par défaut est UTC : 		
fsockopen/cURL : 		
SoapClient : 		Votre serveur n’a pas la classe SoapClient activée - certaines extensions de passerelle utilisant SOAP peuvent ne pas fonctionner correctement.	
DOMDocument : 		
GZip : 		
Chaînes multi-octets : 		Votre serveur ne supporte pas la fonction mbstring - celle-ci est obligatoire pour un meilleur encodage des caractères. Certaines alternatives seront utilisées pour cela.	
Remote post : 		
Remote get : 		
Base de données
Version de la base de données WooCommerce : 		3.6.3
Préfixe de base de données : 	  	wpsavon_	
Base de données GeoIP de MaxMind : 		/homezzzz/siteswsc/public_html/wp511savon/wp-content/uploads/GeoLite2-Country.mmdb
Taille totale de la base de données 	  	6.44MB
Taille de la base de données 	  	5.60MB
Taille de l’index 	  	0.84MB
wpsavon_woocommerce_sessions 	  	Données : 0.02MB + Index: 0.00MB
wpsavon_woocommerce_api_keys 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_attribute_taxonomies 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_downloadable_product_permissions 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_order_items 	  	Données : 0.03MB + Index: 0.02MB
wpsavon_woocommerce_order_itemmeta 	  	Données : 0.21MB + Index: 0.15MB
wpsavon_woocommerce_tax_rates 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_woocommerce_tax_rate_locations 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_shipping_zones 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_shipping_zone_locations 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_shipping_zone_methods 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_payment_tokens 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_payment_tokenmeta 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_woocommerce_log 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_advps_optionset 	  	Données : 0.02MB + Index: 0.00MB
wpsavon_advps_thumbnail 	  	Données : 0.02MB + Index: 0.00MB
wpsavon_apexnb_subscriber 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_aws_cache 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_aws_index 	  	Données : 0.03MB + Index: 0.00MB
wpsavon_bw_pricing_items 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_commentmeta 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_comments 	  	Données : 0.08MB + Index: 0.04MB
wpsavon_edn_subscriber 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_emc_addresses 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_emc_categories 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_emc_dimensions 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_emc_operators 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_emc_operators_authorized_contents 	  	Données : 0.01MB + Index: 0.01MB
wpsavon_emc_pricing 	  	Données : 0.01MB + Index: 0.01MB
wpsavon_emc_services 	  	Données : 0.05MB + Index: 0.00MB
wpsavon_failed_jobs 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_links 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailchimp_carts 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_custom_fields 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_forms 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_log 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_mapping_to_external_entities 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_newsletters 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_newsletter_links 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_newsletter_option 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_newsletter_option_fields 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_mailpoet_newsletter_posts 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_newsletter_segment 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_newsletter_templates 	  	Données : 0.60MB + Index: 0.00MB
wpsavon_mailpoet_scheduled_tasks 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_mailpoet_scheduled_task_subscribers 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_segments 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_sending_queues 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_settings 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_statistics_clicks 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_statistics_forms 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_statistics_newsletters 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_statistics_opens 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_statistics_unsubscribes 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_subscribers 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_mailpoet_subscriber_custom_field 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_subscriber_ips 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_mailpoet_subscriber_segment 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_nm_personalized 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_options 	  	Données : 1.64MB + Index: 0.08MB
wpsavon_postmeta 	  	Données : 0.76MB + Index: 0.35MB
wpsavon_posts 	  	Données : 2.11MB + Index: 0.06MB
wpsavon_queue 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_termmeta 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_terms 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_term_relationships 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_term_taxonomy 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_usermeta 	  	Données : 0.01MB + Index: 0.01MB
wpsavon_users 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_vtprd_purchase_log 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_vtprd_purchase_log_product 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_vtprd_purchase_log_product_rule 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wcpdf_invoice_number 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wc_download_log 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wc_product_meta_lookup 	  	Données : 0.00MB + Index: 0.01MB
wpsavon_wc_webhooks 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wpgdprc_access_requests 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wpgdprc_consents 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wpgdprc_delete_requests 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wpgdprc_log 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wplnst_scans 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wplnst_scans_objects 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wplnst_urls 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wplnst_urls_locations 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wplnst_urls_locations_att 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_wplnst_urls_status 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_yith_wapo_groups 	  	Données : 0.00MB + Index: 0.00MB
wpsavon_yith_wapo_types 	  	Données : 0.00MB + Index: 0.00MB
Nombre de types d'article
attachment 	  	34
custom_css 	  	2
customize_changeset 	  	4
ditty_news_ticker 	  	1
et_pb_layout 	  	6
gs-logo-slider 	  	5
mailpoet_page 	  	1
nav_menu_item 	  	8
page 	  	12
post 	  	10
product 	  	14
product_variation 	  	30
pw_bogo 	  	1
revision 	  	223
scheduled-action 	  	19
shop_coupon 	  	1
shop_order 	  	117
sp_wps_shortcodes 	  	1
tt_font_control 	  	1
user_request 	  	1
vtprd-rule 	  	1
wcct_countdown 	  	1
wpcf7_contact_form 	  	1
yith-wcbm-badge 	  	3
Sécurité
Connexion sécurisée (HTTPS) : 		Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Cacher les erreurs aux visiteurs 		
Extensions actives (2)
Classic Editor 	  	par Contributeurs et contributrices WordPress – 1.5
WooCommerce 	  	par Automattic – 3.6.3
Extensions inactives (35)
Akismet Anti-Spam 	  	par Automattic – 4.1.2
Boxtal 	  	par Boxtale – 2.2.2 – Non testé avec la version active de WooCommerce	
Boxtal Connect 	  	par API Boxtal – 1.1.7 – Non testé avec la version active de WooCommerce	
Contact Form 7 	  	par Takayuki Miyoshi – 5.1.3
Coupon Box for WooCommerce 	  	par VillaTheme – 2.0.0.8 – Non testé avec la version active de WooCommerce	
Divi BodyCommerce 	  	par Divi Engine – 3.1.9 – Non testé avec la version active de WooCommerce	
Duplicate Page 	  	par mndpsingh287 – 3.5
Easy Google Fonts 	  	par Titanium Themes – 1.4.4
Google Customer Reviews for WooCommerce 	  	par eCreations – 2.6.12 – Non testé avec la version active de WooCommerce	
Loco Translate 	  	par Tim Whitlock – 2.2.2
Maintenance 	  	par fruitfulcode – 3.6.1
Reveal IDs 	  	par Oliver Schlöbe – 1.5.3
WooCommerce Bulk Discount 	  	par Rene Puchinger – 2.4.5 – Non testé avec la version active de WooCommerce	
WooCommerce Coupon Shortcodes 	  	par itthinx – 1.10.0
WooCommerce Direct Checkout 	  	par QuadLayers – 2.1.1 – Non testé avec la version active de WooCommerce	
WooCommerce Email Inquiry & Cart Options LITE 	  	par a3rev Software – 2.2.3
WooCommerce Extender 	  	par PentagonPromotions – 0.3.1 – Non testé avec la version active de WooCommerce	
WooCommerce Fixed Quantity 	  	par Habibillah – 1.2.7 – Non testé avec la version active de WooCommerce	
Woocommerce Gift Wrapper 	  	par Little Package – 3.0.4 – Non testé avec la version active de WooCommerce	
WooCommerce PDF Invoices 	  	par Bas Elbers – 3.0.4
WooCommerce PDF Invoices & Packing Slips 	  	par Ewout Fernhout – 2.2.12
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels(Basic) 	  	par WebToffee – 2.4.7 – Non testé avec la version active de WooCommerce	
WooCommerce Product Slider 	  	par ShapedPlugin – 2.1.11 – Non testé avec la version active de WooCommerce	
WooCommerce Services 	  	par Automattic – 1.20.0
WooCommerce Simply Order Export 	  	par Ankit Gade – 3.0.11 – Non testé avec la version active de WooCommerce	
WooCommerce Stripe Gateway 	  	par WooCommerce – 4.1.16
WordPress Users & WooCommerce Customers Import Export(BASIC) 	  	par WebToffee – 1.2.8
WPB Instagram Gallery Slider and Grid 	  	par WpBean – 1.0.3
WP Broken Link Status Checker 	  	par Pau Iglesias, SeedPlugins – 1.0.6
WPB WooCommerce Product slider 	  	par wpbean – 2.0.7.2
WPB WooCommerce Related Products Slider 	  	par wpbean – 1.09 – Non testé avec la version active de WooCommerce	
WP Clone by WP Academy 	  	par WP Academy – 2.2.4
WP GDPR Compliance 	  	par Van Ons – 1.5.2
YITH WooCommerce Quick View 	  	par YITH – 1.3.9
YouTube Channel 	  	par Aleksandar Urošević – 3.0.11.7
Extensions recommandées (1)
ET Support Center :: Must-Use Plugins Autoloader 	  	par Elegant Themes –
Réglages
API activée : 		–
Forcer le SSL : 		–
Devise 		EUR (€)
Position de la devise 		right
Séparateur milliers 		
Séparateur décimal 		,
Nombre de décimales 		2
Taxonomies : types de produits 		external (external), grouped (grouped), simple (simple), variable (variable), woosb (woosb)
Taxonomies : visibilité produit 		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Connecté à WooCommerce.com : 		–
Pages WooCommerce
Base de la boutique:		#26 - /boutique/
Panier:		#27 - /panier/
Validation de la commande:		#28 - /commande/
Mon compte:		#29 - /mon-compte/
Conditions générales de vente et d’utilisation:		La visibilité de la page doit être publique
Thème
Nom: 		Twenty Nineteen
Version: 		1.4
URL de l’auteur : 		https://wordpress.org/
Thème enfant : 		– Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement, nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant	
Supporte WooCommerce: 		
Modèles HTML
Remplacements : 	  	–
Action Scheduler
Action Status 	  	Count 	Oldest Scheduled Date 	Newest Scheduled Date
Complete	 	18	2019-04-21 11:23:45 +0200	2019-05-20 14:44:05 +0200
Pending	 	1	2019-05-27 14:44:05 +0200	2019-05-27 14:44:05 +0200
Canceled	 	0	–	–
In-progress	 	0	–	–
Failed	 	0	–	–
</details>

**Comment by aovivo2000** [comment] 2019-05-28 14:31
I can state the exact same issue that I have been discussing here for a while (I guess this happened after WC 3.6.0): https://wordpress.org/support/topic/after-update-3-6-2-subtotal-is-displayed-wrong-in-corfirmation-email/

**Comment by sque89** [comment] 2019-06-03 11:24
I am experiencing the same issue with Woocommerce 3.6.4

**Comment by aovivo2000** [comment] 2019-06-16 15:05
Hi @dougaitken , I am new to this process, so what happens next? Is this being reviewed and if so, will there be a fix in a future release? thanks!

**Comment by wpuser17** [comment] 2019-06-17 10:19
Experiencing this subtotal rounding problem after upgrading to 3.6.4 from 3.5.4. This same subtotal rounding issue popped up in a woocommerce release last year and was fixed.

**Comment by dougaitken** [comment] 2019-06-18 12:37
@aovivo2000 I added the wrong label to the issue. It will be looked into by the developers in turn and you'll be notified here of any update in the issue.

**Comment by aovivo2000** [comment] 2019-06-18 13:40
@dougaitken  sounds good - thanks!

**Comment by joelschmid91** [comment] 2019-06-22 05:21
I assume this is the same Issue? In my case the subtotal has 0.01 cent deducted and not added?
<img width="524" alt="Screenshot 2019-06-22 at 07 20 21" src="https://user-images.githubusercontent.com/20297204/59959788-442ce200-94be-11e9-95f7-ff39f92a051e.png">

**Comment by afnineone** [comment] 2019-06-24 10:05
<img width="532" alt="Bildschirmfoto 2019-06-24 um 11 51 01" src="https://user-images.githubusercontent.com/52157725/60010607-64a09c00-9678-11e9-86d8-d600f8e51321.png">
Same issue here, also with WooCommerce 3.6.4.

**Comment by tcltd** [comment] 2019-06-24 11:59
1 cent might not seem like much - but its causing my customer to get annoyed and is clearly a bug; this is costing a lot of money in customer service and time to resolve silly rounding issues; is it being worked on?

**Comment by TMG74** [comment] 2019-06-28 07:22
It's not always 1 cent/pence. I have had errors up to 4 pence. As well as the order received page, it occurs on the invoice which uses the same info.

![Incorrect subtotal by 4p](https://user-images.githubusercontent.com/52311753/60324878-d7ae5900-997d-11e9-94ae-dfdac7db8751.jpg)

**Comment by aovivo2000** [comment] 2019-07-03 08:14
I looked at the changelog of WC 3.6.5. from this morning and I couldnt find any change in "tax rounding improvements" - so I guess the patch for issue has been bypassed?! what does this mean now?

**Comment by ibrahimonder** [comment] 2019-07-05 16:48
I am having the same issues! Woocommerce combining with woocommerce subscriptions. Now every new customer is having a monthly subscription of 10.01 euro while the product itself is 10.00. This is very annoying and I can't find a way around it.

**Comment by TMG74** [comment] 2019-07-09 12:42
The author of the Woocommerce PDF Invoices & Packing Slips provided me with a filter to remove the offending subtotal from WooCommerce. The code is below - add to the functions.php file of your child theme. It works on both the sale confirmation screen and the Invoice which is generated but does not appear to affect any of the pages where the subtotal is correct which must use a different variable. Not sure if it will help with the subscriptions issue but might be worth a try. At least this appears to be an interim solution until WooCommerce is corrected.


add_filter( 'woocommerce_get_order_item_totals', 'adjust_woocommerce_get_order_item_totals' );

function adjust_woocommerce_get_order_item_totals( $totals ) {
  unset($totals['cart_subtotal']  );
  return $totals;
}

**Comment by CraftyRobert** [comment] 2019-07-15 09:49
We are having the same issue and have so far been unable to find a solution.

We were just directed to https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce but the issue doesn't seem to be about how taxes are calculated as the subtotal is correct before the order is completed and it is correct on the dashboard but in customer invoices and emails it's wrong.

I know it's not necessarily a critical error, it does cause some confusion and makes VAT invoices incorrect for our customers.

**Comment by wpuser17** [comment] 2019-08-01 00:46
Any progress with this?

Can't move to 3.6.x until this is fixed as the impact to customers is too significant with incorrect subtotals on the order and invoices.

Thought about hiding subtotal with a filter but when this does get fixed and the filter is removed the customer will still have a incorrect subtotal in the order history of orders processed while this bug exists.

I'm sure this bug is more wide spread than the several people who have reported it. The rounding issue doesn't happen on every order and seems to be worse on multiple item orders as it can compound.

Something has changed from 3.5.4 to 3.6.x to introduce this.

**Comment by vedanshujain** [comment] 2019-08-02 14:23
Issue reported by @antoine4269ww should be fixed by #24024 which is included in latest 3.7 RC release, when setting "Round tax at subtotal level, instead of rounding per line" is ticked.

I am guessing several other reports here will be fixed as well, but can you please help us by confirming if that's the case? See [this post for how to test on RC2](https://woocommerce.wordpress.com/2019/08/02/woocommerce-3-7-rc2/).

I am closing this issue, but will reopen if/when anyone reports that this is still happening. Please also include what all tax slabs, product prices and shipping costs(if any) are there when this issue happen so that we can reproduce. Thanks.

**Closed by vedanshujain** 2019-08-02 14:23 UTC
Labels: bug

**Comment by ibrahimonder** [comment] 2019-08-02 15:46
I have had almost the same problem/issue with rounding of 1 cent. But for some reason, new orders placed are working good again without any rounding problems. I've tried to contact woocommerce since I bought a license for support but they're telling me I should tell you guys here on github. What's the deal with bying a license then.. anyhow.

My issue was as follow:

People are buying a subscription on my website for 10 euro. They're seeing that they need to pay 10 euro at check-out. For some reason when they are paying by iDeal, 10,01 has been paid. In subscriptions overview, I also see that the subscription is now enabled and charged for an amount of 10,01 per month instead of 10,00. 

This had been the problem for a few weeks for some reason. New subscribers have the wrong amount now. Since a week or so new subscribers are however getting the right amount of 10,00 again when checking out. I can't tell how or why this problem occurred.

**Comment by vedanshujain** [comment] 2019-08-02 17:32
Hi @ibrahimonder Can you tell me what tax rate you use? And if 10EUR is product cost inclusive of taxes, or does it include some other fees as well. This would help me try to reproduce on my end and confirm that this is fixed in newer version. 

Also please copy and paste the system status report from **WooCommerce > System Status** .

Changing subscription amount for existing customers is something that support would be able to help you though.

**Comment by wpuser17** [comment] 2019-08-03 01:43
@vedanshujain 
Thanks for the update, i did some testing with 3.7.0 RC2.

Before upgrading to 3.7.0 RC2 (using 3.5.4) i noticed if i enabled round tax at subtotal level it actually under rounded e.g 279.99 vs 280.01 with this setting unticked.

After upgrading to 3.7.0 RC2 (and leaving round tax at subtotal level unticked) the problem still occurs with the over rounding 280.01, it doesn't show it on the order confirmation, but appears in the email, pdf and order history.

If using 3.7.0 RC2 and ticking round tax at subtotal level it appears to fix all problems. This worked in email, pdf and order history and also fixed any incorrect previous orders in the order history page.

Have done thorough testing with placing 20 + orders and it seems this is the fix - Upgrade to 3.7.0 RC2 and tick round tax at subtotal level.

Do you know when 3.7.0 is going to be released?

**Comment by antoine4269ww** [comment] 2019-08-03 16:12
Hi,

I've tested with WOOCOMMERCE 3.7.0 RC2 and the same problem still occurs. Below all me details to try to replicate the case.

WOOCOMMERCE SETTINGS > General Tab
Activate computing and cost of taxes : YES (ticked)

WOOCOMMERCE SETTINGS > TAX
VAT Option: YES (ticked) I'll enter the prices with TVA (all taxes included)
The last field, Displaying Sums of VAT: as a unique total
VAT Rate is: 20%

PRODUCTS PRICES
1- 7,50€ (VAT of 20% included of course)
2- 25€ (VAT of 20% included of course)
3- 7€ (VAT of 20% included of course)

SHIPPING COSTS: Shipping is free

In the back-office > Orders , the total VAT is good and the global total is OK: 39,50€

Only the screenshot below has problems: 39,51€ instead of 39,50€
It's always the page dispayed after payment.

Of course, the invoice generated by the WooCommerce PDF Invoices & Packing Slips plugin displays with 39,51€ which is wrong.

https://i.imgur.com/nH3Yqvg.png

Cheers

**Comment by wpuser17** [comment] 2019-08-04 04:41
@antoine4269ww 
Did you try 3.7.0 RC2 with **Round tax at subtotal level, instead of rounding per line** ticked?

https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#prettyPhoto/1/

I had the same problem on 3.7.0 RC2 until I also ticked this setting.

The fix seems to require the following 2 settings to be enabled to work -

Enable settings:
a. Round at subtotal
b. Prices are inclusive of taxes

**Comment by antoine4269ww** [comment] 2019-08-04 12:10
Hi,
I've activated:
a. Round at subtotal
b. My prices already included VAT

I've tested the this time it's OK. There is no 0.01 rounded amount above or below the amount.
Also, the PDF invoice generated with WooCommerce PDF Invoices & Packing Slips plugin is OK.

So, for me, it"s working.
Patrick

**Comment by vedanshujain** [comment] 2019-08-05 08:14
Thanks everyone for help with testing this out. We are still testing out RC2, and hopefully release 3.7 on 12 August, unless a major bug surfaces.

**Comment by abrockmann** [comment] 2019-08-07 11:55
Hi, 

for me it seems not the case. When I round at subtotal the subtotal is fine but the total is now wrong. 

It misses one cent. 

I am using WC 3.7 RC2

No other plugins activated. 

@antoine4269ww did you check the total on your store?

**Comment by antoine4269ww** [comment] 2019-08-07 14:24
Hi,
I've done a test again and yes the sub-total and total are the same.
Check here : https://i.imgur.com/ilEGFt6.png

Cheers

**Comment by abrockmann** [comment] 2019-08-08 09:55
Thank you for checking that Patrick.

**Comment by vedanshujain** [comment] 2019-08-09 11:54
@abrockmann Can you tell us more details, and paste in a system status report from  WooCommerce > System Status? This will help us in reproducing the error.

FWIW I tried with two product worth 5 and 6.5% tax like you mentioned in the support and it worked fine for me. See:

<img width="324" alt="Screenshot 2019-08-09 at 5 23 31 PM" src="https://user-images.githubusercontent.com/7571618/62777223-7b853b80-baca-11e9-84cf-789b123e1517.png">

**Comment by abrockmann** [comment] 2019-08-11 13:47
@vedanshujain Thank you for looking into this again for me, I tried it again and it looks indeed fixed. I am not sure what changed but you can mark this done and I will report again if this error surfaces again.

**Comment by TMG74** [comment] 2019-09-08 17:24
Well it's not entirely fixed from my point of view. If I have "Round tax at subtotal level, instead of rounding per line" ticked then the subtotal and totals are consistent and correct. If I don't have "Round tax at subtotal level, instead of rounding per line" ticked then the subtotals and totals are still consistent but are incorrect. Below is a screen shot where you can see that the actual totals should be £78.18 but are showing as £78.21. (box not ticked example)

<img width="610" alt="Screen Shot 2019-09-08 at 17 48 18" src="https://user-images.githubusercontent.com/52311753/64491812-7dc2ed00-d264-11e9-84c0-a5bb1c3e4478.png">

In theory no issue as I just tick "Round tax at subtotal level, instead of rounding per line". 

BUT... that's ok until you get to the order confirmation screen which appears to still be rounding at a different level. See the screen print below where the total of the "Choose your own beers & ciders" should be £55.83. The fact the "Round tax at subtotal level......." box is checked does not seem to be being applied on the order confirmation screen. The subtotals and totals are correct but the products are showing the totals that they would have shown in the basket and at the checkout if the 'Round tax at subtotal...." boxed **had not been ticked**. i.e. they are wrong. Total up the contents in the "Choose your own beers & ciders" pack to see for yourself. It should equal £55.83.

<img width="919" alt="Screen Shot 2019-09-08 at 18 06 42" src="https://user-images.githubusercontent.com/52311753/64491930-cf1fac00-d265-11e9-9903-ea37ccb3e980.png">

**Comment by tcltd** [comment] 2019-09-08 18:18
im still having the same issue too - 
<img width="345" alt="Screenshot 2019-09-08 at 19 16 43" src="https://user-images.githubusercontent.com/11043217/64492586-4b69bd80-d26d-11e9-91c8-a75c2ca9774f.png">
nothing changed from the recent updates;
prices are all inclusive of VAT

**Comment by DanielMarklund** [comment] 2019-10-11 13:29
I'm still experiencing this issue. I'm on WooCommerce 3.7.0. Previous version was something before 3.6.0 where I did not have this issue.

I've tried the checking and uncheckning the "Rounding: Round tax at subtotal level, instead of rounding per line" at WooCommerce > Settings > Tax:

**When checked:**
- Cart & checkout shows the correct order total (136.50).
- Payment gateway gets the correct order total (136.50).
- When at the order received page, the total is shown as 136.49 – which is incorrect.
- The order view in WP-admin shows the total as 136.49.
- On order status change, it recalculates the total to 136.50, which is correct but our ERP has already synced the order with the wrong total.

**When unchecked:**
- Cart & checkout shows the correct order total (136.50).
- Payment gateway gets the correct order total (136.50).
- When at the order received page, the total is shown as 136.50.
- The order view in WP-admin shows the total as 136.50.
- When our ERP picks up the order, it gets the order with the correct 136.50.
- On order status change, it recalculates the total to 136.51, which is incorrect. This is also displayed to the customer.

**Comment by vedanshujain** [comment] 2019-10-22 11:04
@DanielMarklund @TMG74 We are tracking the issue for incorrect subtotal in order confirmation page in #24540. Let's continue the discussion there because these are two separate issues and this thread is already pretty long. I can repro the reported bug and hopefully will fix it soon. 

@tcltd can you please post with more details with tax settings (tax rates, whether you are rounding at subtotal etc) so that we reproduce the bug?
