### ISSUE TITLE
Duplicated variable products don't return product variations in search results when searching by SKU in admin

### ISSUE THREAD

**Issue by orangutangle** [woocommerce/woocommerce#29394] opened 2021-03-16 10:04 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The product variations of a variable product which has been created by duplicating another product will not be returned by the search_products function in class-wc-product-data-store-cpt.php when searching by SKU. This occurs when the original product has an SKU set on the parent product, and blank SKUs set on the variations.

This occurs because the fallback search in search_products uses the following subquery:

```
OR ( wc_product_meta_lookup.sku = "" AND parent_wc_product_meta_lookup.sku LIKE '%{{ search term }}%' )
```

in other words, the variations will only be returned in the results if the sku in the wc_product_meta_lookup table is an empty string.

However, duplicated products have stopped cloning postmeta records where _sku = '' in some recent release. This means that the record added to the _wc_product_meta_lookup table has sku = NULL, not sku = '', and it no longer matches the sub query in the fallback search.

**Expected behavior**
The duplicated product should be searchable by SKU in the same way as the original product, namely the variations of a variable product should be returned as results.

**Actual behavior**
A variable product which has been duplicated doesn't appear in results when searching for its SKU in the admin search.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Products > Add new product
2. Set the product type to Variable.
3. Add some attributes and generate some product variations, setting a price for each.
4. Set an SKU in the Inventory tab only.
5. Save the product.
6. Go to WooCommerce > Orders > Add order.
7. Click Add items > Add products.
8. Enter the SKU of your product in the Select2 box.
9. You should see the parent product and all the variations returned in the results.
10. Now go to Products > All Products.
11. Click on the Duplicate product link of your new product in the product list.
12. Set a new SKU in the Inventory tab of the duplicated product and save it.
13. Go to WooCommerce > Orders > Add order.
14. Click Add items > Add products.
15. Enter the SKU of your product in the Select2 box.
16. You should see no matches in the results.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://dev.soniceditions.com
Site address (URL): https://dev.soniceditions.com
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.24-0ubuntu0.18.04.7
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.47-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: suk_
Total Database Size: 781.57MB
Database Data Size: 447.60MB
Database Index Size: 333.97MB
suk_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
suk_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_woocommerce_order_items: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
suk_woocommerce_order_itemmeta: Data: 14.55MB + Index: 13.03MB + Engine InnoDB
suk_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
suk_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_actionscheduler_actions: Data: 1.02MB + Index: 0.42MB + Engine InnoDB
suk_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_actionscheduler_logs: Data: 1.02MB + Index: 0.20MB + Engine InnoDB
suk_ac_abandoned_cart_history: Data: 0.19MB + Index: 0.02MB + Engine InnoDB
suk_ac_atc_rules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_ac_email_templates: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
suk_ac_guest_abandoned_cart_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_ac_link_clicked_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_ac_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_ac_opened_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_ac_sent_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_ac_statistics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_comments: Data: 7.52MB + Index: 9.09MB + Engine InnoDB
suk_cpf_custom_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_cp_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_options: Data: 21.42MB + Index: 3.64MB + Engine InnoDB
suk_pmxe_exports: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
suk_pmxe_posts: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
suk_pmxe_templates: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
suk_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_pmxi_imports: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
suk_pmxi_posts: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
suk_pmxi_templates: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
suk_postmeta: Data: 228.78MB + Index: 235.66MB + Engine InnoDB
suk_posts: Data: 47.58MB + Index: 22.94MB + Engine InnoDB
suk_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_redirection_items: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
suk_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_simple_subscription_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_simple_subscription_popup_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_sonic_edition_counts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_sonic_partner_prices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_termmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
suk_terms: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
suk_term_relationships: Data: 15.55MB + Index: 5.45MB + Engine InnoDB
suk_term_taxonomy: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
suk_usermeta: Data: 6.52MB + Index: 6.00MB + Engine InnoDB
suk_users: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
suk_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wc_customer_lookup: Data: 0.33MB + Index: 0.25MB + Engine InnoDB
suk_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_wc_order_coupon_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
suk_wc_order_product_lookup: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
suk_wc_order_stats: Data: 0.38MB + Index: 0.41MB + Engine InnoDB
suk_wc_order_tax_lookup: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
suk_wc_product_meta_lookup: Data: 9.34MB + Index: 17.61MB + Engine InnoDB
suk_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_wfConfig: Data: 1.25MB + Index: 0.00MB + Engine InnoDB
suk_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wfFileMods: Data: 15.55MB + Index: 0.00MB + Engine InnoDB
suk_wfHits: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
suk_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_wfIssues: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
suk_wfKnownFileList: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
suk_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wfLogins: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
suk_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
suk_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_wfStatus: Data: 1.02MB + Index: 0.09MB + Engine InnoDB
suk_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_woocommerce_adyencw_cc: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
suk_woocommerce_adyencw_documents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_woocommerce_adyencw_ecc: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_woocommerce_adyencw_schema_version: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_woocommerce_adyencw_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_woocommerce_adyencw_transactions: Data: 20.34MB + Index: 0.00MB + Engine InnoDB
suk_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_woocommerce_exported_csv_items: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
suk_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_ycd_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_yoast_indexable: Data: 12.52MB + Index: 10.58MB + Engine InnoDB
suk_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
suk_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_yoast_primary_term: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
suk_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
suk_yoast_seo_meta: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
suk_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_zbs_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_automation_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
suk_zbs_contacts: Data: 0.34MB + Index: 0.13MB + Engine InnoDB
suk_zbs_customfields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
suk_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
suk_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
suk_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_externalsources: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
suk_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
suk_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_logs: Data: 0.28MB + Index: 0.06MB + Engine InnoDB
suk_zbs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
suk_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_tags_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
suk_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
suk_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB

### Post Type Counts ###

acf-field: 167
acf-field-group: 21
attachment: 6510
nav_menu_item: 59
oembed_cache: 14
page: 32
popup: 5
popup_theme: 8
post: 820
postman_sent_mail: 50
press_posts: 111
product: 3929
product_variation: 58298
quality_promise: 4
revision: 2506
shop_coupon: 461
shop_order: 5299
shop_order_refund: 1
wishlist: 23427
ycdcountdown: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.9.0
Aelia Shipping Pricing for Currency Switcher: by Aelia – 1.3.18.210128
Campaign Monitor Ajax Forms: by Lee Willis – 1.5.0
Classic Editor: by WordPress Contributors – 1.6
Column Shortcodes: by Codepress – 1.0.1
Delete Expired Transients: by WebAware – 2.0.7
Disable Comments: by WPDeveloper – 2.1.0
Intuitive Custom Post Order: by hijiri – 3.1.2.1
Members: by MemberPress – 3.1.4
Metorik Helper: by Metorik – 1.5.0
Modified order filters: by Menno van Hout – 1.0
WooCommerce Nosto Tagging: by Nosto Solutions Ltd – 1.1.1
Popup Maker - Advanced Targeting Conditions: by WP Popup Maker – 1.4.6
Popup Maker: by Popup Maker – 1.16.0
Post SMTP: by Yehuda Hassine – 2.0.22
Radio Buttons for Taxonomies: by helgatheviking – 2.2.3
Redirection: by John Godley – 5.0.1
Show Current Template: by JOTAKI Taisuke – 0.4.4
Temporary Login Without Password: by StoreApps – 1.6.9
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.49

Aelia Foundation Classes for WooCommerce: by Aelia – 2.1.4.210208
Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 8.10.1
Aelia Currency Switcher for WooCommerce: by Aelia – 4.9.14.210215
Woocommerce Alphbetical Search: by Magnigenie – 1.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.1
WooCommerce Prices by Country: by Aelia – 1.11.7.210304
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.41
WooCommerce Smart Coupons: by StoreApps – 4.17.5
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2.1
Aelia Tax Display by Country for WooCommerce: by Aelia – 1.12.2.200127
WooCommerce Variation Swatches and Photos: by Lucas Stark – 1.6.8 (update to version 3.1.3 is available)
WooCommerce WishLists: by Element Stark – 2.2.4
WooCommerce: by Automattic – 5.1.0
WooCommerce AdyenCw: by customweb GmbH – 4.0.42
Wordfence Security: by Wordfence – 7.4.14
Yoast SEO: by Team Yoast – 15.9.2
WP Crontrol: by John Blackbourn & contributors – 1.10.0
WP Hotjar: by Thiago Guimarães – 0.0.3
WP Rocket | Disable Cache Clearing: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.8.6
YITH Purchased Column for WooCommerce: by YITHEMES – 1.1.7
Jetpack CRM: by Automattic – 4.0.14

### Inactive Plugins (9) ###

Agile CRM WooCommerce: by Agile CRM Team – 1.0
Autoptimize: by Frank Goossens (futtta) – 2.8.1
Maintenance Mode: by Lukas Juhas – 2.4.3
Query Monitor: by John Blackbourn – 3.6.7
SendGrid: by SendGrid – 1.11.8
Sonic Editions Add reCAPTCHA to Forms: by Robin Hislop – 1.0
Taxonomy Switcher: by WebDevStudios – 1.0.3
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.1
WooCommerce Product Feed for Google, Awin, Shareasale, Bing and More: by ExportFeed.com – 3.2.5.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #588 - /gallery
Basket: #5 - /basket
Checkout: #6 - /checkout
My account: #728 - /my-account
Terms and conditions: #749 - /terms-conditions

### Theme ###

Name: FoundationPress
Version: 5.5.2
Author URL: http://olefredrik.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: soniceditions/woocommerce/archive-product.php
soniceditions/woocommerce/cart/cart-empty.php
soniceditions/woocommerce/cart/cart-item-data.php
soniceditions/woocommerce/cart/cart-totals.php
soniceditions/woocommerce/cart/cart.php
soniceditions/woocommerce/checkout/form-billing.php
soniceditions/woocommerce/checkout/form-checkout.php
soniceditions/woocommerce/checkout/form-coupon.php
soniceditions/woocommerce/checkout/form-shipping.php
soniceditions/woocommerce/checkout/payment.php
soniceditions/woocommerce/checkout/review-order.php
soniceditions/woocommerce/checkout/terms.php
soniceditions/woocommerce/checkout/thankyou.php
soniceditions/woocommerce/content-product-cat.php
soniceditions/woocommerce/content-product.php
soniceditions/woocommerce/content-single-product.php
soniceditions/woocommerce/content-widget-product.php
soniceditions/woocommerce/emails/admin-cancelled-order.php
soniceditions/woocommerce/emails/admin-failed-order.php
soniceditions/woocommerce/emails/admin-new-order.php
soniceditions/woocommerce/emails/customer-completed-order.php
soniceditions/woocommerce/emails/customer-invoice.php
soniceditions/woocommerce/emails/customer-new-account.php
soniceditions/woocommerce/emails/customer-note.php
soniceditions/woocommerce/emails/customer-processing-order.php
soniceditions/woocommerce/emails/customer-refunded-order.php
soniceditions/woocommerce/emails/customer-reset-password.php
soniceditions/woocommerce/emails/email-addresses.php
soniceditions/woocommerce/emails/email-customer-details.php
soniceditions/woocommerce/emails/email-footer.php
soniceditions/woocommerce/emails/email-header.php
soniceditions/woocommerce/emails/email-order-details.php
soniceditions/woocommerce/emails/email-order-items.php
soniceditions/woocommerce/emails/email-styles.php
soniceditions/woocommerce/global/wrapper-end.php
soniceditions/woocommerce/global/wrapper-start.php
soniceditions/woocommerce/loop/loop-end.php
soniceditions/woocommerce/loop/loop-start.php
soniceditions/woocommerce/loop/pagination.php
soniceditions/woocommerce/myaccount/my-account.php
soniceditions/woocommerce/myaccount/my-orders.php
soniceditions/woocommerce/order/order-details-customer.php
soniceditions/woocommerce/order/order-details-item.php
soniceditions/woocommerce/order/order-details.php
soniceditions/woocommerce/single-product/add-to-cart/variable.php
soniceditions/woocommerce/single-product/meta.php
soniceditions/woocommerce/single-product/product-image.php
soniceditions/woocommerce/single-product/related.php
soniceditions/woocommerce/single-product/short-description.php
soniceditions/woocommerce/single-product/title.php
soniceditions/woocommerce/single-product/up-sells.php
soniceditions/woocommerce/single-product.php


### Action Scheduler ###

Complete: 1,182
Oldest: 2021-02-13 10:13:06 +0000
Newest: 2021-03-16 09:50:26 +0000

Pending: 1
Oldest: 2021-03-16 10:05:26 +0000
Newest: 2021-03-16 10:05:26 +0000


### Status report information ###

Generated at: 2021-03-16 09:59:54 +00:00
````
</details>

**Comment by juliaamosova** [comment] 2021-03-21 21:35
Hi @orangutangle,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Note that during the following step:

>9. You should see the parent product and all the variations returned in the results.

I did not see the parent product. Only variations as expected. 

>12. Set a new SKU in the Inventory tab of the duplicated product and save it.

I did not need to enter SKU as the modified SKU was already present. 

Here is a screen recording demonstrating my experience:

https://user-images.githubusercontent.com/19143190/111921503-552bce00-8a6b-11eb-808a-c84208ad7ece.mov

And here is me searching by SKU - I can find both the original product and duplicate product by SKU:

https://user-images.githubusercontent.com/19143190/111921549-90c69800-8a6b-11eb-81c3-2fabc0373972.mov

You indicated that you troubleshot your site for a theme and plugins conflict. However, would you please confirm that you indeed did it?

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by orangutangle** [comment] 2021-03-22 14:47
Huh. I had changed themes and disabled plugins but I just tried reproducing the issue on a clean install and I couldn't, so I must have missed something. 

The problem on my configuration is caused by sku = NULL in wp_wc_product_meta_lookup table. I noticed that there are also lots of empty postmeta records in the database, i.e. each product variation has an entry with meta_key = '_sku' and meta_value = ''. In the clean install, the product variations have no postmeta entry for meta_key = '_sku', so these empty records should not be there and may be left over from a failed database update or import.

I tried an experiment on the clean install. I created an empty postmeta entry for a product variation:
```
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (<variation_id>, '_sku', '');
```

Then I ran the Regenerate Product Lookup Tables tool.

Voila! All the sku values in wp_wc_product_meta_lookup are set to NULL, except for the entry for variation_id, which is an empty string. Now I can no longer search by SKU.

So this issue is actually caused by how wc_update_product_lookup_tables handles empty postmeta records.

**Comment by orangutangle** [comment] 2021-03-22 17:03
I solved my issue by:

1. Clearing empty _sku entries from the postmeta table, since they are no longer used since #22773:
```
SELECT * FROM wp_postmeta WHERE post_id IN (SELECT ID from wp_posts WHERE post_type = 'product_variation') AND meta_key = '_sku' AND meta_value = ''
```
2. Running the Regenerate Product Lookup Tables tool.
3. Fixing the erroneous sku = NULL values in the wp_wc_product_meta_lookup table:
```
UPDATE wp_wc_product_meta_lookup SET sku = '' WHERE sku IS NULL
```

Now search by SKU works.

But there is a problem with wc_update_product_lookup_tables - perhaps the issue should be renamed?

**Comment by tammullen** [comment] 2021-09-08 11:59
Hi @orangutangle 

Can you create a new issue for your problem with wc_update_product_lookup_tables if you suspect there is a bug.

> I had changed themes and disabled plugins but I just tried reproducing the issue on a clean install and I couldn't


I'm closing this issue for now as the original problem appears to have been resolved.

**Closed by tammullen** 2021-09-08 11:59 UTC
Labels: category: can't reproduce, has feedback
