### ISSUE TITLE
How to apply discount without coupon and without using negative fees

### ISSUE THREAD

**Issue by paulocoghi** [woocommerce/woocommerce#27460] opened 2020-08-24 11:04 UTC
**Is your feature request related to a problem? Please describe.**
When searching for ways to apply a discount on cart without using coupons, I only find solutions based on the Fee API, applying negative fees, which is discouraged by Woocommerce.

**Describe the solution you'd like**
Is there a function that can be used to apply a discount on the total cart price, without using coupons and without using negative fees?

I want to develop a WooCommerce action that define a cart discount based on the total number of products on cart.

For example: 1 product -> 0% discount, 2 produtcs -> 10% discount, 3+ produtcs -> 25% discount.

But all first page results on Google point to solutions based on negative fees through Fee API.

**Comment by paulocoghi** [comment] 2020-08-24 11:12
I saw @mikejolley response here https://github.com/woocommerce/woocommerce/issues/13224#issuecomment-280636165 explaining to _use discounts instead if possible_, but I can't find it without references to coupons on WooCommerce API, for example here: https://woocommerce.github.io/code-reference/classes/WC-Cart.html

**Comment by juliaamosova** [comment] 2020-08-24 19:19
Hi @paulocoghi,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

Please also note that there is a plugin called `Dynamic Pricing` that does what you are looking for:

https://woocommerce.com/products/dynamic-pricing/

**Closed by juliaamosova** 2020-08-24 19:19 UTC

**Comment by paulocoghi** [comment] 2020-08-24 22:25
Thanks for you reply, @juliaamosova. I apologize for the confusion.

I am not asking for custom code. Instead I'm developing (myself) a custom code which applies discounts on WooCommerce carts, and I'm just trying to follow @mikejolley's recommendations for good practice about discounts without negative fees (and without coupons).

The problem is that I am not finding on docs the "discount" functions mentioned by him, without references to coupons. So my question was more like a "feature request" in case there were no such functions.

That's it :)

Just a feedback. Since the focus of Woocommerce issues on GitHub is for bug fixing, it would be interesting to remove the other issue categories (including feature request) that appear when creating a new one, as in the figure below, so new users will understand that this is not the right place for feature requests:

![woocommerce-issues](https://user-images.githubusercontent.com/378397/91101316-2a94a680-e63d-11ea-8b2f-6613c917a801.png)


Thanks again :)
