### ISSUE TITLE
wc-ajax=update_order_review 503 Can't find the solution for this problem! Please help..

### ISSUE THREAD

**Issue by RichardSchouw** [woocommerce/woocommerce#22547] opened 2019-01-24 09:53 UTC
Hi guys,

I am creating a website where you can make a reservation for an Escape Game and pay for it. Now i am having problems with the Checkout screen. I can make a couple of reservations without any problems but after a few the Checkout page keeps loading and console gives me this error below. Also i am seeing multiple products on the checkout page even when i am entering different customer details etc.

Strange fact is that my friend who is on another computer at a different place can keep making reservations without a single problem... 

I already deactivated a lot of plugins that could be the problem, i tried it incognito in Chrome, deleted my cache.. Problem keeps occurring. It's driving me crazy and the developer of the theme i am using is trying to help but it takes forever to respond on my messages. Been struggling with this for over a week now.

POST https://legenda-basilicae.nl/?wc-ajax=update_order_review 503
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
update_checkout_action @ checkout.min.js?ver=3.5.3:1
setTimeout (async)
update_checkout @ checkout.min.js?ver=3.5.3:1
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
trigger @ jquery.js?ver=1.12.4:3
a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2
(anonymous) @ jquery.js?ver=1.12.4:3
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
trigger @ jquery.js?ver=1.12.4:3
init_checkout @ checkout.min.js?ver=3.5.3:1
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
trigger @ jquery.js?ver=1.12.4:3
a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2
(anonymous) @ jquery.js?ver=1.12.4:3
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
trigger @ jquery.js?ver=1.12.4:3
init @ checkout.min.js?ver=3.5.3:1
(anonymous) @ checkout.min.js?ver=3.5.3:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2

**Comment by RichardSchouw** [comment] 2019-01-24 10:03
`
### WordPress Environment ###

Home URL: https://legenda-basilicae.nl
Site URL: https://legenda-basilicae.nl
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Unix)
PHP Version: 7.2.10
PHP Post Max Size: 76 MB
PHP Time Limit: 120
PHP Max Input Vars: 4000
cURL Version: 7.50.3
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.42-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ De MaxMind GeoIP Database bestaat niet - Geolocation zal niet werken. Je kunt het handmatig downloaden en installeren vanaf https://dev.maxmind.com/geoip/geoip2/geolite2/ naar het pad: . Scrol naar beneden naar "Downloads" en download het bestand "MaxMind DB binary
gzipped" naast "GeoLite2 Country". Vergeet GeoLite2-Country_xxxxxxxx.tar.gz niet te decomprimeren en alleen het GeoLite2-Country.mmdb bestand te uploaden.

Totale databasegrootte: 5.45MB
Database datagrootte: 4.18MB
Database index grootte: 1.27MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.06MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.08MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.14MB + Index: 0.06MB
wp_postmeta: Data: 0.44MB + Index: 0.36MB
wp_posts: Data: 1.41MB + Index: 0.06MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB
wp_revslider_slides: Data: 0.03MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.03MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 42
booked_appointments: 44
customize_changeset: 5
nav_menu_item: 5
page: 13
post: 6
product: 12
revision: 92
room: 5
shop_coupon: 3
shop_order: 64
testimonial: 2
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Redux Framework: door Team Redux – 3.6.15
Booked Add-On: Calendar Feeds: door Boxy Studio – 1.1.5
Booked Add-On: Front-End Agents: door Boxy Studio – 1.1.15
Booked Add-On: WooCommerce Payments: door Boxy Studio – 1.5.1 – Niet getest met de actieve versie van WooCommerce
Booked: door Boxy Studio – 2.2.3
Klassieke editor: door WordPress-bijdragers – 1.3
CMB2 RGBa Colorpicker: door Jay Wood – 0.2.0
Contact Form 7: door Takayuki Miyoshi – 5.1.1
WPBakery Page Builder: door Michael M - WPBakery.com – 5.6
Mollie Payments for WooCommerce: door Mollie – 5.0.7
Slider Revolution: door ThemePunch – 5.4.8.1
ThemeCube Core: door themecube – 1.1
WooCommerce: door Automattic – 3.5.4
WordPress Importeerder: door wordpressdotorg – 0.6.4
WP File Manager: door mndpsingh287 – 4.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #490 - /shop/
Winkelmand: #491 - /winkelmand/
Afrekenen: #492 - /afrekenen/
Mijn account: #493 - /my-account/
Algemene voorwaarden: #592 - /algemene-voorwaarden/

### Theme ###

Name: Escape
Version: 1.1
Author URL: http://themeforest.net/user/themecube
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by rrennick** [comment] 2019-01-24 14:32
Github is for reporting bugs, requesting enhancements, etc. Since you have WooCommerce support, you should contact them to see if they can narrow down the issue.

I'll close this. If you or support are able to identify an issue where we can reproduce the problem in a development install, please re-open.

**Closed by rrennick** 2019-01-24 14:32 UTC
