### ISSUE TITLE
[possible bug] hide coupon notification

### ISSUE THREAD

**Issue by lenamtl** [woocommerce/woocommerce#30098] opened 2021-06-14 17:36 UTC
Hi,
I'm not sure if this is a bug or maybe error on the documentation page
https://woocommerce.github.io/code-reference/classes/WC-Coupon.html#toc

I want to hide Added and Deleted / Not valid coupon notification.

My case is that when a product is added it add another product to the cart (no discount) so I don't want to display the notification. 

I use this code and this is working fine to hide the added coupon with success
```
add_filter('woocommerce_coupon_message', function($msg, $msg_code, $coupon) {    
 if ('COUPON_CODE' === $coupon->get_code() && 200 === $msg_code) {        
     $msg = '';    
 }     return $msg;  }, 20, 3);
```

If I removed the product related to the code I can see the notification that the code is no longuer valid.
I'm not sure if the related code is 101 I have tried also 100, 110,201 with no luck.
```
add_filter('woocommerce_coupon_message', function($msg, $msg_code, $coupon) {    
 if ('COUPON_CODE' === $coupon->get_code() && 101 === $msg_code) {        
     $msg = '';    
 }     return $msg;  }, 20, 3);
```

If this is not possible or a bug, can someone share a code to hide all coupon notification?

I would suggest to add the possibility to display or not notification globally or the best would be per promo

**Comment by juliaamosova** [comment] 2021-06-18 16:24
Hi @lenamtl,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment] 2021-07-12 17:49
Hi @lenamtl,

While our goal is to address all the issues reported in this repository, this issue tracker is primarily a place to report bugs.

The type of issue you submitted looks like a custom code related question and it is not clear that there is an actual problem or bug in our code. Perhaps you could do some more troubleshooting (for instance, you could temporarily remove the check against `$msg_code` from your `if` condition but add a breakpoint, or make use of logging, to see what it is actually set to...and refine things from there)? 

Beyond that, the best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it. I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by barryhughes** 2021-07-12 17:49 UTC
Labels: needs developer feedback

**Comment by lenamtl** [comment] 2021-07-20 13:06
Hi,

I already provide an example.
You can easily reproduce the problem as it is not using custom code.
The only code reference that work is code 200.

So for me this is a bug, why other error code are not working...

I found a temporary fix using another method to hide some coupon notification but it required to do that per coupon name not per coupon reference so it take a lot more code to hide the notification in some case.

If you says that is not a bug could you provide a test case so I can see how it could work?

**Comment by barryhughes** [comment] 2021-07-20 15:52
> So for me this is a bug

Not knowing how to do something does not make it a bug :-) 

You may wish to try using the `woocommerce_coupon_error` hook. Remember, you can always seek help with custom code via [WooCommerce Community Slack](https://woocommerce.com/community-slack/), which is a much better place for this sort of topic. You may also be interested in our [hooks reference](https://woocommerce.github.io/code-reference/hooks/hooks.html).

Good luck with the project!

**Comment by davidzonagrafica** [comment] 2023-01-26 08:16
I have this bug, and it is terrible because the final web users see it all the time when they are managing their sales. 😞

<img width="821" alt="oocommerce_coupon_error" src="https://user-images.githubusercontent.com/91727708/214787270-3a2d01ff-3bc0-4626-8e09-3084b978f81a.png">

**Comment by Douwe-Outlawz** [comment] 2023-03-28 09:22
> If this is not possible or a bug, can someone share a code to hide all coupon notification?

add_filter( 'woocommerce_coupon_message', 'remove_coupon_message' );
add_filter( 'woocommerce_coupon_error', 'remove_coupon_message' );

function remove_coupon_message() {
    return;
}
