### ISSUE TITLE
Default Shipping destination not change

### ISSUE THREAD

**Issue by sabbir268** [woocommerce/woocommerce#24955] opened 2019-11-01 19:08 UTC
I'm trying to change the default Shipping destination, there have three options but it not updated when select rest two else the last one.

**Comment by juliaamosova** [comment] 2019-11-05 14:54
Hi @sabbir268,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs specific to the WooCommerce plugin. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue and fill out the rest of the bug template details. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-11-05 14:54 UTC
Labels: can't reproduce
