### ISSUE TITLE
500 Internal Sever Error after activating woocommerce.

### ISSUE THREAD

**Issue by hirushacooray** [woocommerce/woocommerce#19873] opened 2018-04-26 12:28 UTC
Hi,

I ran into a problem with woocommerce. When I activated the woocommerce plugin, I get the 500 internal server error. I have checked the server error log. Below is the error from the log.

**End of script output before headers: index.php**

Also, I have activated a WordPress default theme to check if woocommerce conflicts with the theme. but got the same 500 error.

Woocommerce version is 3.3.5

Any help will be highly appreciated.
Thanks

**Comment by claudiulodro** [comment] 2018-04-26 21:05
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried  and it appeared to work correctly. To properly investigate this we need the system status report and all of that other information that is asked when you created this issue.

I'm going to close this issue since we can't reproduce it. If you want to open a new one with all the information and the system status report we can take another look.

**Closed by claudiulodro** 2018-04-26 21:05 UTC

**Comment by hirushacooray** [comment] 2018-04-27 09:29
Hi,

I'm sorry for that. The problem is I can't get a system report. whenever I activated the woocommerce, site go down. Is there any other way to generate a system report?

Thanks

**Comment by claudiulodro** [comment] 2018-04-27 13:37
Oh right. That makes sense.  Do you have any other plugins active? Those are the most common sources of problems. If you have other plugins you can try deactivating them and then activating WooCommerce to see if the problem still happens. 

Another possibility is a [problem with your development environment or hosting](https://forum.phalconphp.com/discussion/16831/500-internal-server-error-end-of-script-output-before-headers). I can't really help you troubleshoot that if that is what the issue is. That seems to be the most common source of `End of script output before headers` errors.

**Comment by hirushacooray** [comment] 2018-04-27 14:17
Hi,

Thanks for replying. I'll try that out.

Thanks
