### ISSUE TITLE
Woo using "0 in stock" and "Out of stock" for Different Variations of Same Product

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#19789] opened 2018-04-19 15:39 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. See https://frankmorrow.com/shop/lined-banding-1-1532-wide/
2. Select Steel, 0.020 - and then select Brass, 0.020. 
3. Read stock status

## Expected/actual behavior

When I follow those steps, I see...

Inconsistent naming of the no stock condition. Steel shows "0 in stock" while Brass shows "Out of Stock". Both variations have the exact same stock data/config in the admin.

I was expecting to see...

Consistent naming - either 0 in stock or Out of Stock

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment] 2018-04-19 15:55
They are not the same. I can see in the source code:

`&quot;stock in-stock\&quot;&gt;0 in stock&lt;\/p&gt;`

The variation with 0 stock is 'in stock', 'out of stock'. 

Stock statuses only change when the stock level changes, which leads me to believe this is another issue with your CSV imports (reading https://github.com/woocommerce/woocommerce/issues/19647).

Therefore is is a problem with the data. There is more weirdness if you try to change variation on that page to one which is not for sale (notice pops up).

> We've implemented a workaround that basically forces the UPDATE action whenever someone visits any "out of stock" product.

This worries me.

> Merely clicking UPDATE in admin on product's page w/o changing anything corrects the incorrect OUT OF STOCK messaging in both areas.

This is the same issue here.

It's definitely related to your CSV imports. You won't be able to replicate this with manually input products, and I also doubt you'll be able to replicate this with the built in CSV import because it uses the CRUD system whereas the old suite does not.

"Steps to reproduce the issue" needs to explain how **we** can reproduce the issue on another install of our own. Simply pointing us to a page isn't enough to deal with this .

I suggest you use the helpdesk for this and provide the CSV file you're using to update these variations. The old suite gives you much more freedom to set invalid combinations, for example, using the CSV import suite you're able to set 0 stock qty, yet set 'in-stock' status. This is what I expect has happened here. WooCommerce won't fix this for you; it's just presenting the data it's been given via your CSVs.

Thanks

**Closed by mikejolley** 2018-04-19 15:55 UTC

**Comment by co50** [comment] 2018-04-19 16:04
Mike - as you know, new versions of WooCommerce do not provide the in-stock/out-of-stock drop down in the back-end (unless that's also a bug and those drop-downs are still supposed to be there? So you're looking at this from a dev point of view. From an end user point of view, the stock settings in the admin are exactly the same for both items. 

Two questions here  - perhaps Woo is taking the approach of 'who cares' at this point because the built-in importer is eventually going to be the only one...but at this moment, why isn't it the core WooCommerce's job to ensure the data its CSV Import Suite plugin feeds it is formatted properly? The fact that it allows this to happen points to a bug in Woo....no sanity check here. Am I wrong?

Second, is the built-in importer now on the same level of CSV Import Suite? I'd much prefer to use a more idiot proof importer as long as the column headings and data formats are the same. We've been reluctant to switch because I understood the built-in importer did not support every column that CSV Import Suite does....

**Comment by mikejolley** [comment] 2018-04-19 16:12
@co50 Correct the switching is done when a product is saved - CSV import suite doesn't use the more modern saving mechanism, it just sets meta.

> perhaps Woo is taking the approach of 'who cares' at this point because the built-in importer is eventually going to be the only one...but at this moment, why isn't it the core WooCommerce's job to ensure the data its CSV Import Suite plugin feeds it is formatted properly?

Quite simply, core cannot intercept what plugins do when when use post meta directly. Thats why the CRUD system was introduced and thats also what the new importer uses.

> The fact that it allows this to happen points to a bug in Woo....no sanity check here.

The sanity check would have to go in CSV importer.

> Second, is the built-in importer now on the same level of CSV Import Suite?

Apples and oranges. The new one is not supposed to be a drop in replacement for the old. It has a new CSV format, one we hope is simpler to use. I don't know what data you're trying to import.

**Comment by co50** [comment] 2018-04-19 20:18
WOW, this is a lot better setup! You guys should really push CSV Import Suite folks to migrate over. This new one makes large sites with variations much easier to manage.

Question - CSV Import Suite had a function we could use to speed up the number of products it processed at once. This new importer takes about 10x longer to process the CSV than the old one (FYI its 17k rows). Is there any sort of way to speed it up on a high-powered VPS?

**Comment by mikejolley** [comment] 2018-04-20 10:03
`woocommerce_product_import_batch_size` defaults to 30

**Comment by co50** [comment] 2018-04-20 14:46
Thanks Mike....does it follow the same syntax as the CSV Importer one? I used:

add_filter( 'woocommerce_product_import_batch_size', create_function( '', 'return 120;' ) );

Also, new importer instructions are unclear on dealing with commas in fields such as categories. I enclosed the category that had a comma in quotes and it still interpreted each comma as a new category and broke it up. 

What is the proper syntax for a category field that reads:

"Medallions, Rosettes, & Ornaments", "Medallions, Rosettes, & Ornaments" > "Tiffany, Box Legs & Ornaments" (placing items into both parent and child categories)

**Comment by co50** [comment] 2018-04-20 15:53
Thanks for confirming usage of the filter. Commas though are a mess....

Both this:

"Medallions, Rosettes, & Ornaments", "Medallions, Rosettes, & Ornaments" > "Tiffany, Box Legs & Ornaments"

and this:

"Medallions, Rosettes, & Ornaments", "Medallions, Rosettes, & Ornaments > Tiffany, Box Legs & Ornaments"

...result in the quotes being ignored and Woo simply breaks up everything after a comma.

After importing using either example above, if I go to the product in question, it is listed as being in these 5 categories (shown exactly as listed):

"Medallions
"Tiffany
& Ornaments"
Box Legs & Ornaments
Rosettes

Using LibreOffice, UTF-8, Separated by Comma, Text delimiter: "

**Comment by co50** [comment] 2018-04-20 19:13
Should I create a new Issue regarding the comma problem since this Issue is both closed and originally created for something else?

**Comment by willgorham** [comment] 2018-04-20 21:01
This might help: https://github.com/woocommerce/woocommerce/issues/16192#issuecomment-379837839 Doesn't seem like simple quote-wrapping is working (though I haven't tested myself).

**Comment by co50** [comment] 2018-04-20 21:07
Thanks. Yeah I've tried multiple variations of quote wrapping. Woo ignores it. I'll try the escape char method, but ugggh, what a pain to change all these categories now.

Still would like to hear Mike's take since the instructions on the Importer docs make no mention of escape characters, quotes don't seem to work at all, and one of the goals for the new importer was to make it easier than CSV Import Suite - but that plugin requires no escaping OR quotes. It uses pipes as same-field separators. Unsure why they went the comma route for a CSV file - asking for conflicts that way.

**Comment by mikejolley** [comment] 2018-04-23 17:03
I'll need to update docs. Did escaping with backslash work?

> It uses pipes as same-field separators

Pipes aren't user friendly and some foreign keyboards lack the pipe character.
