### ISSUE TITLE
Query variation by attribute and term ID returns empty result

### ISSUE THREAD

**Issue by scottopolis** [woocommerce/woocommerce#21700] opened 2018-10-26 19:19 UTC
**Describe the bug**

I am trying to query a variation by attribute and term ID, and I get an empty array.

**To Reproduce**

1. Using Woo sample data, I query the Hoodie variation with a color of red : https://appdev.local/wp-json/wc/v3/products/1758/variations?attribute=pa_color&attribute_term=229

I get an empty array: https://cl.ly/168e5e5db3d3

Confirmation of correct attribute term ID: https://cl.ly/a5e70eaa4d43

Confirmation that this variation exists: https://cl.ly/5fc495273c31

I am using WC 3.5.0, I tried with both v2 and v3 endpoints, same results.

**Expected behavior**

I expect 1 variation result.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```

WordPress environment
--
Home URL: |   | http://appdev.local
Site URL: |   | http://appdev.local
WooCommerce version: |   | 3.5.0
Log directory writable: |   | /app/public/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by rodrigoprimo** [comment] 2018-10-30 14:21
I was able to reproduce this issue. Filtering products by attribute work for me and return a list of matched products:

```
https://wc.test/wp-json/wc/v3/products/?attribute=pa_color&attribute_term=32
```

But, as reported, filtering product variations by attribute doesn't work and returns an empty list:

```
https://wc.test/wp-json/wc/v3/products/90/variations?attribute=pa_color&attribute_term=32
```

cc @claudiosanches

**Comment by rrennick** [comment] 2019-01-07 16:57
The reason that `https://wc.test/wp-json/wc/v3/products/90/variations?attribute=pa_color&attribute_term=32` returns an empty array is that the attribute term is assigned to the product not the variation. However, the following does not work either

`https://wc.test/wp-json/wc/v3/products/90?attribute=pa_color&attribute_term=32`

**Comment by rrennick** [comment] 2019-01-08 14:49
I did some more testing with this and the filter that worked for me was

`https://wc.test/wp-json/wc/v3/products/90/variations?attribute=color&term=32`

**Comment by mikejolley** [comment] 2019-01-14 15:40
I suspect @rrennick you saw the full list of variations, not the filtered list. `attribute` `color` would not match against a valid attribute (`pa_color`) so would be ignored.

Logic is here https://github.com/woocommerce/woocommerce/blame/aa8caacf9c10afc81e29bc363926630203af0825/includes/api/class-wc-rest-product-variations-controller.php#L794

This is of course broken in API v2 because the terms are not assigned to variations, only to parents. Looking at the blame it looks to have been pasted from the products class so was likely added in err. Since variation schema is inherited from parent, thats why it's in the docs but broken.

It probably makes more sense to remove those items from the docs, and remove the broken code, so it's not misleading. If such a feature is needed, it would also make more sense to support normalised attribute naming e.g. `color` `blue` rather than mess with terms.

I'll chat with @claudiosanches about fixing the docs.

**Comment by rrennick** [comment] 2019-01-14 15:48
> you saw the full list of variations, not the filtered list.

I tested with a different product & confirmed this.

**Comment by scottopolis** [comment] 2019-01-14 16:30
@mikejolley if I understand your comment correctly, it is not possible to query a variation by the attribute in v3?

**Comment by mikejolley** [comment] 2019-01-14 16:36
@scottopolis Correct, it's not possible. Variations do not get assigned taxonomy terms like products do.

**Comment by claudiosanches** [comment] 2019-01-14 18:43
Seems like just copy and paste, I'll remove that code for now.

**Closed** 2019-01-16 17:41 UTC
Labels: api, has pull request
