### ISSUE TITLE
[GlobalStep - WooCommerce 5.1 Beta 1] Discount calculations for price with inclusive taxes fail for Coupons added to order from the admin. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29158] opened 2021-02-17 16:47 UTC
## Bug Description:
Discount calculations for price with inclusive taxes fail for Coupons added to order from the admin. 

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version 88.0.4324.104) (64-bit)
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard.
1. Add Some products.
1. Go to WooCommerce->Settings->Tax.
1. Select "Yes, I will enter price inclusive of tax" option for Price entered with tax.
1. Click on Standard Tax rates and set any tax rate  for a specific country other than your shop base address.
1. Add a coupon (Say:10%) and add a product for a price (Say 242).
1. Complete an order for this product as a guest user with address diferent from your shop address.
1. Open this order in the admin view, set the order status to Pending Payment and update.
1. Add a Created Coupon at step 8 (10%) to a Order.
1. Observe that discount calculations for price with inclusive taxes fail for Coupons added to order from the admin. 

## Actual Result:
Discount calculations for price with inclusive taxes fail for Coupons added to order from the admin. 

## Expected Result:
Coupons added to order from the admin, should calculate discounts as per the price inclusive of taxes.

## Screenshot:

![#29158_1](https://user-images.githubusercontent.com/41110392/108237843-51581380-716e-11eb-97e5-881f756ad65d.png)

![#29158_2](https://user-images.githubusercontent.com/41110392/108237893-5f0d9900-716e-11eb-8dea-482f27539022.png)

![#29158_3](https://user-images.githubusercontent.com/41110392/108237932-69c82e00-716e-11eb-9b12-c596d32631c1.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://productive-katipo.jurassic.ninja
Site address (URL): https://productive-katipo.jurassic.ninja
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.1
Log Directory Writable: ✔
WP Version: 5.7-beta3-50369
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.15
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 3.63MB
Database Data Size: 2.14MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 4
page: 10
post: 2
product: 23
product_variation: 9
revision: 3
shop_coupon: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Query Monitor: by John Blackbourn – 3.6.7
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.1
Facebook for WooCommerce: by Facebook – 2.3.0
Gutenberg: by Gutenberg Team – 9.9.3
Jetpack by WordPress.com: by Automattic – 9.4
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
Mollie Payments for WooCommerce: by Mollie – 6.1.0
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce PayPal Payments: by WooCommerce – 1.1.0
WooCommerce: by Automattic – 5.1.0-beta.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.1.0

WP Crontrol: by John Blackbourn & crontributors – 1.9.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 16
Oldest: 2021-02-17 08:35:02 +0000
Newest: 2021-02-17 16:23:29 +0000


### Status report information ###

Generated at: 2021-02-17 16:26:29 +00:00
`
```
</details>

**Comment by roykho** [comment] 2021-02-17 18:01
Hi @gglobalstep - is this not the same issue as the one here? https://github.com/woocommerce/woocommerce/issues/27814

**Comment by gglobalstep** [comment] 2021-02-18 10:06
> Hi @gglobalstep - is this not the same issue as the one here? #27814

Yes, it is the same but as per discussion with the team on slack(@juliaamosova ), we have created the new issue.

**Comment by juliaamosova** [comment] 2021-02-19 17:27
Thanks for finding https://github.com/woocommerce/woocommerce/issues/27814 @roykho and thanks for confirming it is the same issue @gglobalstep.

Because it is a duplicate of https://github.com/woocommerce/woocommerce/issues/27814, I'll go ahead and close this thread. Thanks for reporting @gglobalstep!

**Closed by juliaamosova** 2021-02-19 17:27 UTC
Labels: Bug
