### ISSUE TITLE
PHP warning when boolean used as second parameter of array_key_exists

### ISSUE THREAD

**Issue by skunkbad** [woocommerce/woocommerce#22176] opened 2018-12-08 14:06 UTC
File is **/includes/admin/helper/class-wc-helper-options.php**

PHP warnings in error.log show that array_key_exists is expecting an array as its second parameter, but WordPress's get_option function is returning a boolean false, and false is being used as the second parameter.

I can reproduce any time I log in and visit /wp-admin.

Since get_option can return false and skip applying the default provided, one needs to check for false before trying to use it as an array. It's not good enough to simply provide "array()" as the second parameter of get_option and think you're done.

How to fix:
```
    public static function get( $key, $default = false ) {
	    $options = get_option( self::$option_name, array() );
	    if ( is_array($options) && array_key_exists( $key, $options ) ) {
		    return $options[ $key ];
	    }
    
	    return $default;
    }
```

This is the current version of WooCommerce with WordPress 4.9.8 on a Ubuntu server running PHP 7.2.12.

**Comment by kloon** [comment] 2018-12-10 09:21
Not able to recreate this issue. Please test with all plugins disabled except WooCommerce and your theme switched to a default one like Twentyseventeen or Storefront.

As @rrennick said, if the $options is not an array it will not continue to evaluate the second part of the statement, my guess is you have some sort of conflict with a plugin or theme.

Closing, will gladly reopen when you can provide steps to replicate this on a clean install with just WooCommerce and a default theme.

**Closed by kloon** 2018-12-10 09:21 UTC

**Comment by skunkbad** [comment] 2018-12-13 22:55
@kloon, how often does a person use WooCommerce with all plugins disabled and only one of a handful of themes? It doesn't harm WooCommerce in any way to do what I proposed.

@kloon and @rrennick, I don't need a lesson on how PHP works. Of course if $options is not an array it would not continue to evaluate. That's the point.

The whole ecosystem of WP / WC + themes and plugins is a crap storm made mostly by amateur developers. Whatever ... it's your code, I guess.

**Comment by kloon** [comment] 2018-12-14 06:41
> how often does a person use WooCommerce with all plugins disabled and only one of a handful of themes

Not much but that is how we find conflicting or offending code, once you have that determined you can work from there to fix the issue. But you already know this right since you do not need lessons on how PHP and I presume any other programming language works right. Debugging 101.

> The whole ecosystem of WP / WC + themes and plugins is a crap storm made mostly by amateur developers. Whatever ... it's your code, I guess.

Thanks for the insult I guess. These so-called "amateurs" you speak of are doing this at their own cost on their own time, you probably know this since you seem to know it all, but Ron (rrennick) does not work for WooCommerce or Automattic but another company and he debugs issues and do fixes on a daily basis.

He and the company he works for has no obligation to do this or having to put up with remarks such as yours, heck, not even I have to so please take them somewhere else, perhaps where the pro developers hang out.

Not sure what your issue is, I clearly stated that I will reopen this issue when you can provide steps to replicate this. If you know the issue is with a plugin or theme then tell us, you omitted to complete the template we ask you to when opening a bug report so we are left in the dark making things difficult to debug, but I guess pro developers like yourself do not need to debug issues, you just know.

**Comment by chriseverson** [comment] 2019-01-07 22:13
Just wanted to chime in here real quick for anyone else that encounters this issue in the future. 

In my case, this was being caused by having corrupt serialized data in the `woocommerce_helper_data` option value. In my case this was caused by a domain name change, but your mileage may vary.
