### ISSUE TITLE
Missing Grouping Products option under Linked Products Tabs

### ISSUE THREAD

**Issue by erdivyang10** [woocommerce/woocommerce#15026] opened 2017-05-11 11:50 UTC
Hello
We have installed woocommerce version 3.0.4. While adding new product of type “simple” we are unable to find the “Grouping Products” option in the Linked Products Tab. We are unable to associate a simple product with a group product. In older version of woocommerce “Grouped Products” option was available through which we were able to search and associate a group product with current simple product.

You can see in screenshot. On previous version, grouping tab is available but in updated version 3.0.4 that is missing.
![grouping-missing](https://cloud.githubusercontent.com/assets/20810705/25947665/0bb0212c-366e-11e7-8340-de7faa3f4385.png)

Please assist.

**Comment by mikejolley** [comment] 2017-05-11 11:53
This is a duplicate of https://github.com/woocommerce/woocommerce/issues/15024

As I said, it's an option on the GROUPED product as of 3.0 **because products can be within multiple groups.** Look at the grouped product's linked product tab.

**Closed by mikejolley** 2017-05-11 11:53 UTC

**Comment by kampiamodikuesto** [comment] 2018-02-15 22:57
it's not confortable to link simple product from grouped product, if we have sevaral simple product we have to write each of them. Before it was easy use drop-down group menu from simple product. now if a product must me linkable to multiple group why not do this association from sample product?
