### ISSUE TITLE
[GlobalStep] For Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29216] opened 2021-02-24 16:04 UTC
## Bug Description:
For Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend.

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version 88.0.4324.104) (64-bit)
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard.
1. Go to frontend
1. Click/View on any "product".
1. Observe that for Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend.

## Actual Result:
For Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend.

## Expected Result:
For Twenty Twenty- One theme "PayPal" payment button should display correctly on the frontend..

## Screenshot:
![#29216_1](https://user-images.githubusercontent.com/41110392/109032329-8a9eff00-76eb-11eb-9337-a0d58571acd0.png)
![#29216_2](https://user-images.githubusercontent.com/41110392/109032344-925ea380-76eb-11eb-891a-cecb6ec068cb.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2021-02-26 21:29
Hi @gglobalstep,

Thank you for reporting the issue. It seems to be caused by the [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) plugin is being developed in another repository: https://github.com/woocommerce/woocommerce-paypal-payments. 

I am going to move your bug report there so that the right team could take a look further.

**Comment by juliaamosova** [comment] 2021-02-26 21:29
I am also adding a bit more details to this issue:

- The following testing instructions have been followed in order to encounter the issue: https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.1#enhancement-use-the-new-paypal-payments-plugin-for-onboarding-6261

**Comment by juliaamosova** [comment] 2021-02-26 21:36
For some reason, I am not able to transfer the issue to PayPal Payments repository so I created the new issue there instead: https://github.com/woocommerce/woocommerce-paypal-payments/issues/129. 

Because of this, I am closing this issue here.

**Closed by juliaamosova** 2021-02-26 21:36 UTC
