### ISSUE TITLE
Adding a Custom Field to BACS Account Details Page

### ISSUE THREAD

**Issue by PaulodoPorto** [woocommerce/woocommerce#28083] opened 2020-10-23 22:30 UTC
Please guys,

1° i'm trying to create a custom field to **BACS Account Details Form** page **(Admin Area)**, so can i display in my thankyou page and the same time send per e-mail.

2° i'm following what those article says, but i think i'm doing something not correct
```
https://docs.wpdebuglog.com/plugin/woocommerce/4.0.0/filter/woocommerce_bacs_account_fields/
http://hookr.io/plugins/woocommerce/3.0.6/filters/woocommerce_bacs_account_fields/#
```

This script is one of my thousand tries:

```
function pekky_bacs_account_field( $account_fields, $order_id ) {
    $account_fields['test_added' ] = array(
        'label' => 'THIS SHOULD SHOWWW',
         'value' => 'Yup it doessss'
    );
    return $account_fields;
}

add_filter( 'woocommerce_bacs_account_fields', 'pekky_bacs_account_field', 10, 2);
```
When i run this script, i don't get any result (new field in the account details form) and also i don't receive any error message in the debug.log file.

What am i doing wrong plese?
Gratitude!

**Comment by juliaamosova** [comment] 2020-10-28 21:35
Hi @PaulodoPorto,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-28 21:35 UTC

**Comment by lexuanphat** [comment] 2023-06-10 07:15
Hi @PaulodoPorto, have you found the solution yet? now i have the same problem as you
