### ISSUE TITLE
 Products tab seems to be broken

### ISSUE THREAD

**Issue by ChristopheMediane** [woocommerce/woocommerce#25764] opened 2020-02-26 12:39 UTC
Hi everyone
**Describe the bug**
My command tab doesn't show the commands. I can see the commands of the month but not the older one. 

**Screenshots**
Screenshots attached to make myself clear !
![WC-1](https://user-images.githubusercontent.com/61502309/75345627-5f49c000-589d-11ea-9e35-5fb9fceab42f.jpg)
![WC-2](https://user-images.githubusercontent.com/61502309/75345630-5fe25680-589d-11ea-901f-b2e57aa318c1.jpg)
![WC-3](https://user-images.githubusercontent.com/61502309/75345632-5fe25680-589d-11ea-9bd7-28d77a24dade.jpg)

**WordPress Environment**
WordPress 5.3.2/ Twenty Seventeen Theme.<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
Do you really need all of it ? Sorry pardon my french...

`
### WordPress Environment ###

WordPress address (URL): https://medianeartetcom.eu
Site address (URL): https://medianeartetcom.eu
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.14
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.28-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
Taille totale de la base de données: 47.28MB
Taille de la base de données: 39.68MB
Taille de l’index: 7.60MB
wp_woocommerce_sessions: Données : 9.02MB + Index : 0.16MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.47MB + Index : 0.28MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_aff_affiliates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_aff_affiliates_users: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_aff_hits: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_aff_referrals: Données : 0.02MB + Index : 0.14MB + Moteur InnoDB
wp_aff_referral_items: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_aff_robots: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_aff_uris: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_aff_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bp_user_blogs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bp_user_blogs_blogmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_comments: Données : 1.52MB + Index : 0.56MB + Moteur InnoDB
wp_failed_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_followup_coupons: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_followup_coupon_logs: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_followup_customers: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_followup_customer_carts: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_followup_customer_notes: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_followup_customer_orders: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_followup_email_excludes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_followup_email_logs: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_followup_email_orders: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_followup_email_tracking: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_followup_followup_history: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_followup_order_categories: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_followup_order_items: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_followup_subscribers: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_followup_subscribers_to_lists: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_followup_subscriber_lists: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_huge_it_videogallery_params: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailchimp_carts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_options: Données : 4.31MB + Index : 0.17MB + Moteur InnoDB
wp_pc_users: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_pc_user_meta: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_pms_member_subscriptionmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_pms_paymentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_postmeta: Données : 10.52MB + Index : 3.03MB + Moteur InnoDB
wp_posts: Données : 11.52MB + Index : 0.50MB + Moteur InnoDB
wp_queue: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_signups: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_skrill_transaction_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.11MB + Index : 0.13MB + Moteur InnoDB
wp_term_relationships: Données : 0.20MB + Index : 0.09MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.13MB + Index : 0.14MB + Moteur InnoDB
wp_tm_taskmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_tm_tasks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_usermeta: Données : 0.44MB + Index : 0.39MB + Moteur InnoDB
wp_users: Données : 0.05MB + Index : 0.05MB + Moteur InnoDB
wp_user_registration_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_vimeography_gallery: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_vimeography_gallery_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_vimeography_pro_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wcsc_error_logs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wcsc_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_email_notify: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woo_wallet_transactions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woo_wallet_transaction_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB

### Post Type Counts ###

acf: 1
attachment: 870
bne_testimonials: 32
carousel: 2
condition_group: 1
cuar_log_event: 2
cuar_private_file: 1
cuar_private_page: 1
customize_changeset: 23
custom_css: 1
cycloneslider: 1
easyimageslider: 1
employees: 8
flagallery: 1
flatfolio: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
ms_communication: 8
ms_membership: 2
nav_menu_item: 274
options: 1
page: 53
polylang_mo: 3
post: 203
post_grid: 13
product: 14
product_variation: 28
projects: 3
restriction: 1
revision: 892
ris_gallery: 3
rttpg: 1
safecss: 1
sa_slider: 1
scheduled-action: 35
services: 14
shop_coupon: 52
shop_order: 200
sidebar_instance: 1
slick_slider: 3
soliloquy: 2
sp_wp_carousel: 1
testimonial: 2
testimonials: 16
testimonial_sc: 1
user_registration: 1
wc_zapier_feed: 11
woocustomemails: 1
wp-types-group: 7
wpcf7_contact_form: 50
wpforms: 1
wpmm_theme: 1
wpws_page: 2
wswebinars: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Polylang Pro: par WP SYNTEX – 2.6.10
Advanced noCaptcha & invisible Captcha: par Shamim Hasan – 5.6 – Non testé avec la version active de WooCommerce
Black Studio TinyMCE Widget: par Black Studio – 2.6.9
Classic Editor: par Contributeurs et contributrices WordPress – 1.5
Contact Form 7 Captcha Pro: par 247wd – 0.0.1
Contact Form 7: par Takayuki Miyoshi – 5.1.6
WooCommerce Coupon Generator: par Jeroen Sormani – 1.1.0 – Non testé avec la version active de WooCommerce
Facebook Pixel: par Facebook – 1.7.7
Gratisfaction- Loyalty Rewards Referral Birthday and Giveaway Program: par Appsmav – 3.7.3
Header and Footer Scripts: par Digital Liberation – 2.1.1
Kadence WooCommerce Email Designer: par Kadence WP – 1.3.12
Max Mega Menu - Pro Addon: par megamenu.com – 2.0.1
Max Mega Menu: par megamenu.com – 2.7.4
Polylang for WooCommerce: par Frédéric Demarle – 1.3.2
Post Grid: par PickPlugins – 3.2.18 – Non testé avec la version active de WooCommerce
Really Simple SSL: par Rogier Lankhorst
Mark Wolters – 3.2.9

Restreindre l’accès utilisateur: par Joachim Jensen – 1.2.1
SiteOrigin Page Builder: par SiteOrigin – 2.10.14
Vimeography Theme: Journey: par Dave Kiss – 2.0.6
Vimeography Pro: par Dave Kiss – 2.0.2
Vimeography: par Dave Kiss – 2.1
WooCommerce Menu Cart: par Jeremiah Prummer
Ewout Fernhout – 2.7.7

WooCommerce: par Automattic – 3.9.2
WP-Cron Status Checker: par Webhead LLC – 1.2
WP-Cron Status Checker: par Webhead LLC – 1.2
WP-Optimize - Clean, Compress, Cache: par David Anderson
Ruhani Rabin
équipe Updraft – 3.0.16


### Inactive Plugins (5) ###

Polylang Pro: par WP SYNTEX – 2.6.8
Temporary Login Without Password: par StoreApps – 1.6.0
User Registration: par WPEverest – 1.8.1
Very Simple Meta Description: par Guido – 5.6
WooCommerce Zapier Integration: par OM4 – 1.9.6 – Non testé avec la version active de WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la boutique: #8585 - /panier/
Panier: #8585 - /panier/
Validation de la commande: #8586 - /commande/
Mon compte: #8587 - /mon-compte/
Conditions générales de vente et d’utilisation: #8864 - /conditions-generales-de-vente-a-distance/

### Theme ###

Name: Twenty Seventeen
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WC Pages Translations ###

Base de la boutique: ❌ Traductions manquantes : English
Deutsch

Panier: ❌ Traductions manquantes : English
Deutsch

Valider la commander: ❌ Traductions manquantes : English
Deutsch

Mon compte: ❌ Traductions manquantes : English
Deutsch


### Action Scheduler ###

Terminer: 34
Oldest: 2020-01-26 14:04:44 +0000
Newest: 2020-02-25 14:53:11 +0000

En attente: 1
Oldest: 2020-02-26 14:53:11 +0000
Newest: 2020-02-26 14:53:11 +0000

Annulé: 0
Oldest: –
Newest: –

En cours: 0
Oldest: –
Newest: –

Échoué: 0
Oldest: –
Newest: –

`


```
</details>

**Comment by juliaamosova** [comment] 2020-02-26 18:36
Hi @ChristopheMediane,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

All Orders view:

![all1](https://user-images.githubusercontent.com/19143190/75375760-bef39b80-589c-11ea-976a-67e5e8f2bfbb.jpg)

Pending payment orders view:

![all2](https://user-images.githubusercontent.com/19143190/75375773-c61aa980-589c-11ea-8551-75fceef8f904.jpg)

Pending payments in February 2020 view:

![all3](https://user-images.githubusercontent.com/19143190/75375779-cca92100-589c-11ea-9a4e-e9a781ee50c2.jpg)

Hi {username},

Thank you for raising the issue. However, I can’t reproduce it on my end.

{list the steps you took and share screenshots showing that everything is working as expected}

I see that you have several plugins installed which could cause an issue. Please test your site for plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce. Then test again.

If the issue is resolved with all plugins deactivated, it means that one of your plugins is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by ChristopheMediane** [comment] 2020-02-27 09:29
Hi Julia
Thanks a lot !
I just tried to deactivate all my plugins and everything went back on WC. 
So I reactivated each of my plugins, one by one, and I found the one which messed everything up ! Polylang for WooCommerce !
I'll email them to have their feedback. 
And will send up an update here as soon as I have informations. 
Thanks
Christophe

**Comment by juliaamosova** [comment] 2020-02-27 14:06
Hi @ChristopheMediane,

Thanks for testing and good news about finding the plugin that was causing the issue. It is highly likely that the issue will need to be fixed on the plugin side of things so I am going to close this issue for now. 

Please feel free to comment on it in case there will be a comment from the developers of the Polylang for WooCommerce that something is to be done on our end. We’d be happy to take another look.

**Closed by juliaamosova** 2020-02-27 14:06 UTC
Labels: status: needs feedback

**Comment by ChristopheMediane** [comment] 2020-02-28 10:48
Hi Julia
I had an answer from PolyLang. I just had to  set the admin language filter in the top bar on "Show all languages" as shown in the attached screenshot and it worked perfectly

If this could help anyone in the future !

![orders](https://user-images.githubusercontent.com/61502309/75542461-29811480-5a20-11ea-9b83-9c9caaa99560.png)

**Comment by ChristopheMediane** [comment] 2020-02-28 10:48
Thanks for your help !

**Comment by juliaamosova** [comment] 2020-02-28 13:55
@ChristopheMediane great to know that you figured out how to fix it. And thanks for posting here - it may indeed help someone :)
