### ISSUE TITLE
Proper CDN support for WooCommerce

### ISSUE THREAD

**Issue by lucasRolff** [woocommerce/woocommerce#12477] opened 2016-11-28 08:33 UTC
## EXPLANATION OF THE ISSUE

In WooCommerce 2.6.4 (and others), whenever using plugins such as WP Super Cache, W3 Total Cache or any other plugin that supports sending css/js/fonts/images over CDN, this generally works except for some core files of WooCommerce.

The issue exists in following file (and line):

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-frontend-scripts.php#L156

`$assets_path` uses the [plugin_url](https://github.com/woocommerce/woocommerce/blob/master/woocommerce.php#L448-L450) function from WooCommerce itself to get the current URL for the asset, which underneath uses the WordPress function `plugins_url`.

This means whenever you want to use CDN, it will work for every asset on a site (that are included according to the WordPress standard way of doing it), but it won't work for WooCommerce core files, such as `jquery.cookie.min.js`, `add-to-cart.min.js`, `jquery.blockUI.min.js`, `woocommerce.min.js`, some CSS files etc.

This means you have a bunch of files that doesn't utilize CDN when it should, increasing load on origin (Assuming people use Apache which a lot of shared hosts do), and hurts performance for people far away from the origin server.

## STEPS TO REPRODUCE THE ISSUE

Run a Webshop with WooCommerce, and install any plugin such as WP Super Cache, W3 Total Cache, or similar with CDN enabled.

## SYSTEM STATUS REPORT

N/A

**Comment by mikejolley** [comment] 2016-11-28 10:11
> that are included according to the WordPress standard way of doing it

What method are you expecting here if not plugins_urls? The scripts are registered though wp_enqueue_/wp_register functions which is correct.

**Comment by lucasRolff** [comment] 2016-11-28 10:26
Well, if you were following the standard way of doing stuff, you wouldn't have to use a custom function (Read `WC()->plugin_url()` )

```
$assets_path          = str_replace( array( 'http:', 'https:' ), '', WC()->plugin_url() ) . '/assets/';
```

If you did register / enqueue scripts correctly, then those plugins such as WP Super Cache, W3 Total Cache, or any other plugin rewriting the wp_enqueue_style and wp_enqueue_script would pick it up - this doesn't happen for WooCommerce core files, but happens for a bunch of WooCommerce plugins

A normal way would be to using `plugins_url( 'assets/js/frontend/woocommerce.min.js', __FILE__ )` in the `$src` part of wp_enqueue_/wp_register

**Comment by mikejolley** [comment] 2016-11-28 11:37
Will need to check if plugins_url supports protocol relative URLs to see if it's viable or not. On quick scan though I don't see W3TC using the plugins_url filter so I'm not sure why that would matter.

**Comment by lucasRolff** [comment] 2016-11-28 11:45
All I know is that plugins using `WC()->plugin_url()` uses the domain to load the file - where any other plugin doing a normal 

```php
plugins_url( 'assets/js/frontend/woocommerce.min.js', __FILE__ )
```

Will end up with actually getting loaded via the defined URL in *any* caching plugin - all caching plugins giving the same behaviour - everything but WooCommerce core files doesn't work - so clearly has to do with the (odd) way WooCommerce enqueues the files when there's even a function in WP core doing exactly what would be needed. It's like putting lines of code for no reason.

**Comment by mikejolley** [comment] 2016-12-06 10:49
See #12521

**Comment by emilstahl** [comment] 2017-04-02 21:33
@mikejolley It is almost four months since this was merged. When are this fix gonna be pushed to the release in the WordPress Plugin Directory?

**Comment by claudiosanches** [comment] 2017-04-03 02:53
@emilstahl April 4, WooCommerce 3.0.
Just keep an eye on: https://woocommerce.wordpress.com/2017/03/24/woocommerce-3-0-0-rc2/
Best way to know when the next release is coming.

**Comment by emilstahl** [comment] 2017-04-05 10:46
@claudiosanches We updated, but this is not fixed?
![screen shot 2017-04-05 at 12 45 43](https://cloud.githubusercontent.com/assets/3885790/24702178/f024c8cc-19fd-11e7-91ea-88b37d9a5e08.png)

**Comment by claudiosanches** [comment] 2017-04-05 18:01
@emilstahl have you not tested before update?
You asked when it's the next release, and it's now included into 3.0.
You can check more details about the change in https://github.com/woocommerce/woocommerce/pull/12521

**Comment by lucasRolff** [comment] 2017-04-05 19:26
@claudiosanches - the "fix" that has been made doesn't solve anything, because of your `str_replace` of `http` and `https` in your get_asset_url: https://github.com/woocommerce/woocommerce/blob/59c28497368d45329bf9012ce7a50dd5f36779ba/includes/class-wc-frontend-scripts.php#L97-L99

What is the exact reason of making it protocol relative?

`get_asset_url` should be as as `return plugins_url( $path, WC_PLUGIN_FILE );`

**Comment by claudiosanches** [comment] 2017-04-05 19:37
@lucasRolff 

> What is the exact reason of making it protocol relative?

Avoit HTTPS errors trying to load non-HTTPS.

**Comment by lucasRolff** [comment] 2017-04-05 19:42
@claudiosanches 

> Avoid HTTPS errors trying to load non-HTTPS.

Since plugins_url uses `WP_PLUGIN_URL` constant, which uses `WP_CONTENT_URL` constant, which is whatever is defined in `get_option('siteurl')`

In case siteurl is wrong (containing https) - the site wouldn't be working in first place.

You're not fixing anything with doing a str_replace, when you're relying on a core function that gets the siteurl from the database.

**Comment by claudiosanches** [comment] 2017-04-05 19:45
@lucasRolff You can have only the cart and checkout pages under HTTPS and for it you don't need to set HTTPS into `get_option('siteurl')`.

**Comment by lucasRolff** [comment] 2017-04-05 19:47
@claudiosanches read my `update` part of the comment

**Comment by claudiosanches** [comment] 2017-04-05 19:56
@lucasRolff and your CDN don't works under HTTPS? or the problem is when goes to non-HTTPS?

**Comment by lucasRolff** [comment] 2017-04-05 20:03
@claudiosanches - my CDN works perfectly under HTTPS - the issue is that when you do the `str_replace` it will cause a result such as `//mywebsite.com/wp-content/plugins/woocommerce` - majority of the caching plugins or CDN Rewrite plugins rewrite `siteurl` (with http and https) - if you change it, and put nothing, then a bunch of famous plugins (Such as WP Super Cache maintained by Automattic), will not be able to rewrite.

The whole problem is that WooCommerce, as one of the only (big) plugins, mess with linking statics in a "normal" way.

**Comment by claudiosanches** [comment] 2017-04-05 20:24
Reopening it but leaving for 3.1.0 or maybe 4.0.0.

**Comment by lucasRolff** [comment] 2017-04-05 20:29
Hopefully it won't be as from 2.0.0 to 3.0.0 - which took about 4 years 👍 
So I hope 3.1.0 ^_^

**Comment by emilstahl** [comment] 2017-05-11 09:34
Can we get an ETA?  3.1.0 or 4.0.0?

**Comment by mikejolley** [comment] 2017-06-29 16:37
Let's add a filter to https://github.com/woocommerce/woocommerce/blob/59c28497368d45329bf9012ce7a50dd5f36779ba/includes/class-wc-frontend-scripts.php#L98 to let these folks change if they like.

**Comment by mikejolley** [comment] 2017-06-30 10:07
See https://github.com/woocommerce/woocommerce/pull/15888 This will allow you to filter the path to use an absolute URL if you prefer. We need to keep them protocol relative for wider compatibility.

**Closed by mikejolley** 2017-06-30 10:07 UTC
Labels: Type: Bug

**Comment by jonathannz** [comment] 2017-07-01 02:40
Perhaps my insufficient technical knowledge on this matter has me thinking the wrong way about it. Excuse me if that's the case. 

Here's what comes to mind, after reading this discussion...

What I see emilstahl  and lucasRolff pointing out is exactly what I wish to point out. Namely, that when using a plugin on Wordpress to implement CDN url rewrites, pretty much the ONLY files that do not load from the CDN are various files from Woocommerce core. 

In my case, these are:

```
/woocommerce/assets/css/
.... woocommerce-layout.css
.... woocommerce-smallscreen.css
.... woocommerce.css
/woocommerce/assets/js/
.. /frontend/..
.... cart-fragments.min.js
.... woocommerce.min.js
.. /jquery-blockui/
....jquery-blockUI.min.js
../js-cookie/..
....js.cookie.min.js
```

And then all product images also load from local site, not the CDN.

I am not sure why mikeholley and claudiosanches have gone to such lengths to contest this assertion made by the OP and others. 

Why is Woocommerce one of the few plugins needing "to keep them [urls] protocol relative for wider compatibility."? I have tested sites with over 100 different plugins, and many themes, and all seem to comply with some basic Wordpress standard which results in their assets loading from a CDN when made to do so, with and without HTTPS enforced.

It seems fairly obvious to me that this issue is caused by something specific to the way in which WC is coded, and that if most other plugins (including all but one WC related plug-in I've tested, our of about 30) all manage to behave as expected when a CDN is implemented, then it should be relatively easy for WC to do the them. Or is there something exception about the functionality of WC that excludes it from normal Wordpress plug-in behaviour as far as URL structure and CDN implementation goes?

This issue, which seems like a relatively important one to me, was brought up by lucasRolff 7 months ago. I beg to question, what's being done about it?

Thank you for your efforts on making WC the great system it is.

**Comment by mikejolley** [comment] 2017-07-01 10:06
It's different because we have to force certain pages to HTTPS e.g checkout. To support SSL by proxy we use protocol relative URLs.

**Comment by lucasRolff** [comment] 2017-07-01 17:58
> It's different because we have to force certain pages to HTTPS e.g checkout. To support SSL by proxy we use protocol relative URLs.

You could use //domain.com/woocommerce/assets/css/woocommerce-layout.css

That serves both purposes, it will load over https and http - depending on the page you're on.

Also, using forcing certain pages to HTTPS as an excuse isn't exactly valid - because *if* relative URLs was required for this - majority of plugins wouldn't work with WooCommerce and "force SSL" for checkout.

You can enqueue files like normal people do (which by default are relative by the way), but when other plugins such as WP Super Cache hooks into WordPress it rewrites these exact enqueued files - except WooCommerce because WooCommerce feels they have a special requirement "requirement" of **forcing** things to being relative, despite it's actually not required (Other plugins doesn't break, so yours wouldn't do it either, unless you're doing something very wrong).

But hey, at least 7 months of work resulted in a single line of code being changed to add a filter so we can undo the bad code that WooCommerce decides to make.

It's "good enough" to make other plugins work (now we just have to ask other plugin developers to handle WooCommerce "logic"), but it's really not an ideal way to do it 👎

Just fix the code :-) It would be nicer.

**Comment by mikejolley** [comment] 2017-07-01 19:15
Erm....we do do that. That's why this issue exists. Some CDN plugins won't deal with those URLs.

**Comment by mikejolley** [comment] 2017-07-01 19:16
Btw you're quite welcome to submit a pull request if you feel you can handle it better. :)

**Comment by mikejolley** [comment] 2017-07-01 19:23
And that's not to brush you off btw. You clearly feel you know a better way of doing things so show us; submit some code or a PR and I'll take a look. If it doesn't break backwards compatibility or SSL by proxy it can be included.

**Comment by lucasRolff** [comment] 2017-07-01 19:29
> Btw you're quite welcome to submit a pull request if you feel you can handle it better. :)

I'm by no means a developer, but I might end up paying someone to make the pull request, just so WooCommerce can work like other plugins, and not having to have this "unique" issue that only WooCommerce seem to experience.

What I find weird is that every other plugin just works when they use the very default `wp_enqueue_style` and `wp_enqueue_scripts`.

But whatever, I rather submit a pull request to a few of the CDN rewrite tools, just to make use of the new filter, and then update the description on every plugin to say: "[NEW!!!!] Now compatible with WooCommerce"

**Comment by lucasRolff** [comment] 2017-07-01 19:53
Removing the str_replace:

```
--- class-wc-frontend-scripts-old.php	2017-07-01 21:50:06.188507508 +0200
+++ class-wc-frontend-scripts.php	2017-07-01 21:50:11.513507972 +0200
@@ -95,7 +95,7 @@
 	 * @param string $path
 	 */
 	private static function get_asset_url( $path ) {
-		return str_replace( array( 'http:', 'https:' ), '', plugins_url( $path, WC_PLUGIN_FILE ) );
+		return plugins_url( $path, WC_PLUGIN_FILE );
 	}

 	/**
```

On a basic WooCommerce site with `Force secure checkout` checked in the backend renders following result:

Cart with http:

```
$ curl -v -Lsi http://woocommerce.domain.com/cart/ | grep woocommerce-layout.css
*   Trying 192.168.1.8...
* Connected to woocommerce.domain.com (192.168.1.8) port 80 (#0)
> GET /cart/ HTTP/1.1
> Host: woocommerce.domain.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Sat, 01 Jul 2017 19:48:33 GMT
< Server: Apache
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Link: <https://woocommerce.domain.com/wp-json/>; rel="https://api.w.org/"
< Vary: Accept-Encoding,User-Agent
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<
{ [1095 bytes data]
<link rel='stylesheet' id='woocommerce-layout-css'  href='http://woocommerce.domain.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=3.0.7' type='text/css' media='all' />
* Connection #0 to host woocommerce.domain.com left intact
```

Cart with https:
```
$ curl -v -Lsi https://woocommerce.domain.com/cart/ | grep woocommerce-layout.css
*   Trying 192.168.1.8...
* Connected to woocommerce.domain.com (192.168.1.8) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
} [106 bytes data]
* TLSv1.0 (IN), TLS handshake, Server hello (2):
{ [85 bytes data]
* TLSv1.0 (IN), TLS handshake, Certificate (11):
{ [2526 bytes data]
* TLSv1.0 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
} [262 bytes data]
* TLSv1.0 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.0 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.0 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.0 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.0 / AES256-SHA
* Server certificate:
* 	 subject: CN=woocommerce.domain.com
* 	 start date: 2017-05-31 14:00:00 GMT
* 	 expire date: 2017-08-29 14:00:00 GMT
* 	 subjectAltName: woocommerce.domain.com matched
* 	 issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
* 	 SSL certificate verify ok.
> GET /cart/ HTTP/1.1
> Host: woocommerce.domain.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Sat, 01 Jul 2017 19:48:39 GMT
< Server: Apache
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Link: <https://woocommerce.domain.com/wp-json/>; rel="https://api.w.org/"
< Vary: Accept-Encoding,User-Agent
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<
{ [6 bytes data]
<link rel='stylesheet' id='woocommerce-layout-css'  href='https://woocommerce.domain.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=3.0.7' type='text/css' media='all' />
* Connection #0 to host woocommerce.domain.com left intact
```

Checkout with http (causing a redirect):
```
$ curl -v -Lsi http://woocommerce.domain.com/checkout/ | grep woocommerce-layout.css
*   Trying 192.168.1.8...
* Connected to woocommerce.domain.com (192.168.1.8) port 80 (#0)
> GET /checkout/ HTTP/1.1
> Host: woocommerce.domain.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Sat, 01 Jul 2017 19:48:50 GMT
< Server: Apache
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Location: https://woocommerce.domain.com/checkout/
< Vary: User-Agent
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host woocommerce.domain.com left intact
* Issue another request to this URL: 'https://woocommerce.domain.com/checkout/'
* Found bundle for host woocommerce.domain.com: 0x10031f560
*   Trying 192.168.1.8...
* Connected to woocommerce.domain.com (192.168.1.8) port 443 (#1)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
} [106 bytes data]
* TLSv1.0 (IN), TLS handshake, Server hello (2):
{ [85 bytes data]
* TLSv1.0 (IN), TLS handshake, Certificate (11):
{ [2526 bytes data]
* TLSv1.0 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
} [262 bytes data]
* TLSv1.0 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.0 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.0 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.0 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.0 / AES256-SHA
* Server certificate:
* 	 subject: CN=woocommerce.domain.com
* 	 start date: 2017-05-31 14:00:00 GMT
* 	 expire date: 2017-08-29 14:00:00 GMT
* 	 subjectAltName: woocommerce.domain.com matched
* 	 issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
* 	 SSL certificate verify ok.
> GET /checkout/ HTTP/1.1
> Host: woocommerce.domain.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Sat, 01 Jul 2017 19:48:50 GMT
< Server: Apache
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Location: https://woocommerce.domain.com/sample-page/
< Vary: User-Agent
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #1 to host woocommerce.domain.com left intact
* Issue another request to this URL: 'https://woocommerce.domain.com/sample-page/'
* Found bundle for host woocommerce.domain.com: 0x10031f560
* Re-using existing connection! (#1) with host woocommerce.domain.com
* Connected to woocommerce.domain.com (192.168.1.8) port 443 (#1)
> GET /sample-page/ HTTP/1.1
> Host: woocommerce.domain.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sat, 01 Jul 2017 19:48:50 GMT
< Server: Apache
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< X-Pingback: https://woocommerce.domain.com/xmlrpc.php
< Link: <https://woocommerce.domain.com/wp-json/>; rel="https://api.w.org/", <https://woocommerce.domain.com/?p=2>; rel=shortlink
< Vary: Accept-Encoding,User-Agent
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<
{ [6 bytes data]
<link rel='stylesheet' id='woocommerce-layout-css'  href='https://woocommerce.domain.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=3.0.7' type='text/css' media='all' />
* Connection #1 to host woocommerce.domain.com left intact
```

**Comment by lucasRolff** [comment] 2017-07-01 19:55
Meaning the str_replace is redundant and should just get removed.
WordPress handles the http / https just fine - using http on http pages, and https on https pages.

Aka no reason to strip out `http:` or `https:` from the link.

**Comment by mikejolley** [comment] 2017-07-03 13:55
I'm going to make this change for 3.2. If it causes other issues, I'll cc you in to fill you inbox with pings :)
