### ISSUE TITLE
[GlobalStep - WooCommerce 4.9][Mac] "Number of items per page" field appears truncated for Pagination section on "Plugins->Screen Options" page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28815] opened 2021-01-14 14:19 UTC
## Bug Description:
"Number of items per page" field appears truncated for Pagination section on "Plugins->Screen Options" page.

## Environment:
Mac 10.15.7 (19H114)
Safari: v13.1.1 (14609.2.9.1.3)
macOS High Sierra v10.13.6
Safari: v13.1.2(13609.3.5.1.5)
Chrome: v85.0.4183.83
                
 
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Go to Plugins.
1. Click on "Screen Options".
1. Observe that for Pagination section "Number of items per page" field appears truncated on "Plugins->Screen Options" page.

## Actual Result:
"Number of items per page" field appears truncated for Pagination section on "Plugins->Screen Options" page.
 
## Expected Result:
"Number of items per page" field should appear properly for Pagination section on "Plugins->Screen Options" page.

## Video:

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2021-01-21 17:58
Duplicate of #28816.

**Closed by rrennick** 2021-01-21 17:58 UTC
