### ISSUE TITLE
Duplicate Queries

### ISSUE THREAD

**Issue by Alphabc** [woocommerce/woocommerce#25046] opened 2019-11-15 05:15 UTC
**Describe the bug**
Hi,
Writing this after discussion with support:

I'm hosted on Pressidium, and while looking for potential performances issues, we discovered that there were some duplicate queries, even on website homepage where I have no product, except the menu cart widget.
it is in class-wc-shipping-zone-data-store.php
the method might be called within a loop?
Maybe it is necessary for your scripts...
Just sending to you as I thought it could be nice to optimize ;-)

Here they are:

SELECT method_id, method_order, instance_id, is_enabled
FROM XXX_woocommerce_shipping_zone_methods
WHERE zone_id = 1 4 wpdb->get_results
4 calls
wpdb->get_results
4 calls
SELECT method_id, method_order, instance_id, is_enabled
FROM XXX_woocommerce_shipping_zone_methods
WHERE zone_id = 2 4 wpdb->get_results
4 calls
wpdb->get_results
4 calls
SELECT method_id, method_order, instance_id, is_enabled
FROM XXX_woocommerce_shipping_zone_methods
WHERE zone_id = 3 4 wpdb->get_results
4 calls
wpdb->get_results
4 calls
SELECT method_id, method_order, instance_id, is_enabled
FROM XXX_woocommerce_shipping_zone_methods
WHERE zone_id = 4 4 wpdb->get_results
4 calls
wpdb->get_results
4 calls
SELECT method_id, method_order, instance_id, is_enabled
FROM XXX_woocommerce_shipping_zone_methods
WHERE zone_id = 0 4 wpdb->get_results
4 calls
wpdb->get_results
4 calls

Easier to understand with the screenshot
![image](https://user-images.githubusercontent.com/24738945/68918231-4ca4f280-07a8-11ea-93bb-db4cb5cb084a.png)

I understand there are 5 queries, depending on the zones, but each of them is called 4 times, end this on every page of the website.

Thx!

Guillaume

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WP 5.2.4, Elementor Pro, Astra Pro, WooCommerce & some plugins, all in last version (I can send you in PM the status)
```
</details>

**Comment by Alphabc** [comment] 2020-01-14 03:51
Hi,
Any news on this one please?
Thx

**Comment by fxfancher** [comment] 2020-03-04 06:03
yes. this issue happening for me too

**Comment by hulst88** [comment] 2020-04-19 21:05
Same issue here, even lots off duplicated query's on Order details page
About 10 duplicated all related to this wc_shipping_zone stuff

**Comment by hulst88** [comment] 2020-04-19 21:06
![image](https://user-images.githubusercontent.com/39407562/79699862-59b39980-8292-11ea-88a9-0c110a92ccb1.png)
This is the first couple

**Comment by Camilo517** [comment] 2020-08-06 00:42
Any news?

**Comment by mfs-mindsize** [comment] 2021-02-01 22:23
@hulst88 @fxfancher @Alphabc @Camilo517 

I'd like to look into this but can't reproduce it. That said, I'm working off a clean / minimal install + config of WC. Can any of you elaborate on what you have setup in terms of (I presume) Shipping Zones? 

Anything that can get me on the same page with the rest of you would be a big help.

**Comment by hulst88** [comment] 2021-02-02 11:44
I checked and with the latest woocommerce and wordpress version the duplicated queries are removed.
At least when I check backend and frontend mainpage

**Comment by Camilo517** [comment] 2021-02-02 13:01
No, there are still duplicate queries
For example:
```
SELECT option_value
FROM 69gwsr_options
WHERE option_name = '_transient_timeout_wc_onboarding_themes'
LIMIT 1
```

**Comment by mfs-mindsize** [comment] 2021-02-02 19:48
@Camilo517  - Understood. But can you elaborate on what shipping zones you have set up? And anything else that might be relevant? As mentioned above, I can't reproduce it either. But I suspect it's due to the fact I'm working with a clean initial install and not much else in terms of WC settings.

**Comment by barryhughes** [comment] 2021-05-03 21:43
I can't seem to replicate this.

@hulst88 I am interested in that last set of traces you shared, as I see `WC_Gateway_Alg_Custom_Template` referenced in there (that's not our code: I believe it comes from a third party plugin called Conditional Payment Gateways). Do you experience the same problem without that plugin? I just want to be absolutely sure this isn't triggered by other packages before we continue to evaluate. 

Similarly, if others here are using that plugin (or indeed have other third party plugins in place that might be impacting), please try deactivating and then re-testing to see if the issue clears.

**Comment by hulst88** [comment] 2021-05-04 06:12
> I can't seem to replicate this.
> 
> @hulst88 I am interested in that last set of traces you shared, as I see `WC_Gateway_Alg_Custom_Template` referenced in there (that's not our code: I believe it comes from a third party plugin called Conditional Payment Gateways). Do you experience the same problem without that plugin? I just want to be absolutely sure this isn't triggered by other packages before we continue to evaluate.
> 
> Similarly, if others here are using that plugin (or indeed have other third party plugins in place that might be impacting), please try deactivating and then re-testing to see if the issue clears.

Let me check later today. For long  time i have disabled the query monitor.
But I had no plugin running for my knowledge but I do apply a gateway discount in snippet code.

Will let you know tonight

**Comment by hulst88** [comment] 2021-05-12 14:27
@barryhughes when I disabled plugin called "Custom Payment Gateways for WooCommerce Pro" the duplicated queries are gone. I will let them know. Thank you.

**Comment by barryhughes** [comment] 2021-05-12 15:23
I'm happy that solved things :-)

Given that and since it doesn't seem possible to replicate in a clean, up-to-date environment I will go ahead and close this issue. 

If it is still a problem for anyone, though, and if you are certain it is not the result of interference from another component (whether that is a theme or a plugin) then do feel free to create a new issue: you can always link back to this one if helpful and we will take a fresh look.

Thanks!

**Closed by barryhughes** 2021-05-12 15:23 UTC
Labels: category: performance, has feedback
