### ISSUE TITLE
Empty output woocommerce_catalog_ordering

### ISSUE THREAD

**Issue by Ruslan-Promo** [woocommerce/woocommerce#19590] opened 2018-04-02 08:06 UTC
After updating 3.3.4, the sort woocommerce_catalog_ordering is not displayed

**Comment by claudiulodro** [comment] 2018-04-02 17:45
You haven't provided any of the information the form asked when creating this issue. This information is important because we cannot reproduce or investigate the problem without it. For reference here it is again:

<details>










## Prerequisites



- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue



1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem



- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
</details>

I'm going to close this issue as non-reproducible. You can open a new issue with all the information we need to investigate the problem once you have it. Thanks.

**Closed by claudiulodro** 2018-04-02 17:45 UTC
