### ISSUE TITLE
Custom sorting not working

### ISSUE THREAD

**Issue by GreatLakesBreeze** [woocommerce/woocommerce#22437] opened 2019-01-14 02:41 UTC
I have been trying to sort some products, but for whatever reason, the sorting doesnt work. I ahve read all I could find but many of the questions are several years old. By now this kind of thing should have been fixed or a decent manual could be available, but I havent found any. 

Anyway, here is my problem, I want to order the items below in my order, but system takes over and orders the size it want:

1 oz Glass Roll On
1 oz Plastic Refill Bottle ( Pure Oil )
1/3 oz Roll On
16 oz Plastic Refill Bottle
2 oz Plastic Refill Bottle ( Pure Oil )
4 oz Plastic Refill Bottle ( Pure Oil )
8 oz Plastic Refill Bottle ( Pure Oil )

The options are available by using radio buttons add ons. I have marked each variation menu according to my preference but its not helping. 
I want the 1/3 to be on top and 16 to be the last one.

**Comment by kloon** [comment] 2019-01-14 06:58
While this is custom functionality and not part of WooCommerce core it would help a lot if you could post the code you are using to achieve the custom sorting. Looking at the results you posted it is clear that the sorting is happening as text.

You will need something that can convert the fraction to decimal and then sort based on the decimal value which should order it correctly.

Closing this as it is custom code and not a bug with WooCommerce.

**Closed by kloon** 2019-01-14 06:58 UTC
