### ISSUE TITLE
Parent product meta data isn't correctly posted after a variation is edited

### ISSUE THREAD

**Issue by Archvist** [woocommerce/woocommerce#27049] opened 2020-07-16 12:36 UTC
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When editing product variations parent product data is not posted and unsets/resets parent product metadata values. 

I've created an additional metadata number field that applies to a parent product and it's variations. If the metadata value for the parent item (not variation) is equal to 50, you then edit the weight (or any attribute) of a variation and update the product. Not using the save changes button. Then the parent meta field is not posted therefore returns 0 and unsets the value. 

**Expected behavior**
I expect that parent product metadata value which exists and is currently set is posted when a product is updated. 

**Actual behavior**
Only the variation data is posted therefore the parent meta value saved is unset. Even if this parent value is updated and you edit a variation it unsets the value.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new meta value for products and variations (I created a number text input)
2. Add a value to the parent product and store this value
3. Make an edit to a product variation and update the product (not save changes)
4. Parent product meta value is now reset

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment] 2020-10-22 22:28
Hi @Archvist,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it, the steps you provided aren't enough.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-10-22 22:28 UTC
