### ISSUE TITLE
[GlobalStep - 4.1 beta 1] Regular Price on website is different from the one updated in the dashboard while creating a product. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26141] opened 2020-04-09 16:39 UTC
**Step to Reproduce:**
1. Open "XXX".
2. Login using username: XXX; Password: XXX.
3. Click on "Add Product".
4. Enter some value say Rs. 71.5.
5. Publish the product.
6. Click on View button.
7. Observe that Rs. 65 is displayed instead of Rs. 71.5.

**Actual Result:**
Regular Price on website is different from the one updated in the dashboard while creating a product. 

**Expected Result:**
Regular prices should be displayed on store also.
![17](https://user-images.githubusercontent.com/41110392/78918945-ccf92680-7aae-11ea-81ac-ee5493762571.png)

**Comment by juliaamosova** [comment] 2020-04-10 20:56
Hi @gglobalstep,

Thank you for filing the issue! 

Note that this repository is public, therefore, please don't provide details of the site login here for security reasons - even if it is a test site. I reducted the details you provided in the issue. 

As far as the issue itself, you see the price difference due to how tax settings are configured:

![tax](https://user-images.githubusercontent.com/19143190/79022403-d08ebb00-7b4b-11ea-894b-4b18753c38b6.jpg)

If you change the fields `Display prices in the shop` and `Display prices during cart and checkout` to `Including tax`, the price will match between the back-end and the front-end. You can read more about tax setup in [Setting up Taxes in WooCommerce](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/) documentation. 

I am closing this issue as it is not a bug but rather tax misconfiguration.

**Closed by juliaamosova** 2020-04-10 20:56 UTC
