### ISSUE TITLE
Cannot create product with type "auction" via REST API 

### ISSUE THREAD

**Issue by Binzinz** [woocommerce/woocommerce#29823] opened 2021-05-04 12:42 UTC
Custom product type (here Auction) are not recognised by the API for product creation via Curl.
example:
```
curl -X POST https://example.com/wp-json/wc/v3/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{"type":"auction","name":"MNO_LA1","short_description":"Dell Optiplex E6330","description":"Desktop E6330\nHarddrive: 500GB\nRAM: 8GB"}'
```

Result:
```
{"code":"rest_invalid_param","message":"Invalid parameter(s): type","data":{"status":400,"params":{"type":"type is not one of simple, grouped, external and variable."},"details":{"type":{"code":"rest_not_in_enum","message":"type is not one of simple, grouped, external and variable.","data":null}}}}
```

WooCommerce version: |   | 5.2.2
WooCommerce REST API package: |   | 5.2.2 /var/www/html/wp-content/plugins/woocommerce/includes
WooCommerce Blocks package: |   | 4.7.2 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler package: |   | 3.1.6 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin package: |   | 2.1.5 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin
Log directory writable: |   | /var/www/html/wp-content/uploads/sites/214/wc-logs/
WordPress version: |   | 5.7.1
WordPress memory limit: |   | 256 MB
Language: |   | en_GB

Server info: |   | Apache
PHP version: |   | 7.2.24-0ubuntu0.18.04.7
PHP post max size: |   | 20 MB
PHP time limit: |   | 30
PHP max input vars: |   | 1000
cURL version: |   | 7.58.0, OpenSSL/1.1.1
MySQL version: |   | 5.7.33-0ubuntu0.18.04.1
Max upload size: |   | 20 MB

WooCommerce database version: |   | 5.2.2
Database prefix |   | wp_214_
Total Database Size |   | 17.75MB
Database Data Size |   | 12.16MB
Database Index Size |   | 5.59MB

Auctions for WooCommerce |   | by WPInstitut – 1.5

**Comment by yehudah** [comment] 2021-05-07 05:53
You should ask the plugin developer to support that: "Auctions for WooCommerce"

**Comment by tammullen** [comment] 2021-05-09 10:45
Hi @Binzinz 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party plugin Auctions for WooCommerce. 
​
Please contact the author of the plugin directly for further help.   I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-05-09 10:45 UTC

**Comment by Binzinz** [comment] 2021-05-10 09:02
tHello, I think the issue is more global. You cannot create product via REST API with a custom product type (no matter which).
That's annoying for auction, but also for book, food, furniture, etc..

**Comment by Binzinz** [comment] 2021-05-10 14:17
I think this guy has the same issue than me, with another kind of custom product: https://stackoverflow.com/questions/64593311/woocommerce-add-product-api-rejects-add-product-for-custom-product-that-appears
