### ISSUE TITLE
add_to_cart not working with variable products

### ISSUE THREAD

**Issue by BlackJack7878** [woocommerce/woocommerce#28213] opened 2020-11-08 10:52 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Expected behavior**
Add product to cart

**Actual behavior**
Error message "Texture and Cap Size are required fields"

**Describe the bug**
I've this function
`WC()->cart->add_to_cart($product_id, $quantity, $variation_id, $variation, $cart_item_data)`
Where all arguments are defined and being used, but product can't be added to cart. The problem is with those "Any Texture" and "Any Cap Size" options. If I define a texture and cap size then it will work ok, but if I use "any texture/cap size" it won't work. 
![image](https://user-images.githubusercontent.com/9917289/98462855-e63a9080-21bf-11eb-9e89-ca70d8190c3a.png)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create variable product with 2-3 attributes (used for variations)
2. Create variations with 1-2 "Any [attribute name]" options
3. Try to add it using add_to_cart() function

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Important notice**
Everything works fine on woocommerce 4.0.1 but after I updated it stoped working, so I downgraded again to 4.0.1

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://upgradeboutique.com
Site address (URL): https://upgradeboutique.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.23
PHP Post Max Size: 128 MB
PHP Time Limit: 400
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.2
WC Database Prefix: wpmf_
Total Database Size: 96.69MB
Database Data Size: 79.02MB
Database Index Size: 17.67MB
wpmf_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wpmf_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmf_woocommerce_order_items: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wpmf_woocommerce_order_itemmeta: Data: 5.03MB + Index: 1.97MB + Engine InnoDB
wpmf_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmf_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_actionscheduler_actions: Data: 2.02MB + Index: 0.86MB + Engine InnoDB
wpmf_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_actionscheduler_logs: Data: 1.23MB + Index: 0.59MB + Engine InnoDB
wpmf_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpmf_csp3_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_email_log: Data: 32.52MB + Index: 0.00MB + Engine InnoDB
wpmf_email_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_options: Data: 3.08MB + Index: 1.13MB + Engine InnoDB
wpmf_postmeta: Data: 8.33MB + Index: 7.70MB + Engine InnoDB
wpmf_posts: Data: 2.34MB + Index: 0.52MB + Engine InnoDB
wpmf_rio_process_queue: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wpmf_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_shipment_batch_process: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_usermeta: Data: 15.39MB + Index: 2.95MB + Engine InnoDB
wpmf_users: Data: 0.23MB + Index: 0.23MB + Engine InnoDB
wpmf_user_visits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wpmf_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmf_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_wc_product_meta_lookup: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wpmf_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_weu_group27: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_weu_sent_email: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpmf_weu_smtp_conf: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_weu_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_weu_unsubscriber: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_weu_user_notification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmf_wfconfig: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wpmf_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wffilemods: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpmf_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmf_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmf_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpmf_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmf_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmf_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmf_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmf_wfstatus: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpmf_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_woo_shipment_status_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmf_woo_shippment_provider: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpmf_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_offline_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 466
acf-field-group: 14
attachment: 822
bookable_resource: 8
custom_css: 1
customize_changeset: 2
gallery: 34
nav_menu_item: 25
page: 20
post: 2
product: 23
product_variation: 696
revision: 238
seedprod: 1
shop_coupon: 51
shop_order: 502
shop_order_refund: 28
wc_booking: 305
wpcf7_contact_form: 2
ywar_reviews: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Advanced Access Manager: by Vasyl Martyniuk <vasyl@vasyltech.com> – 6.7.1
Advanced Custom Fields PRO: by Elliot Condon – 5.8.3
Advanced Custom Fields: Table Field: by Johann Heyne – 1.3.10
All-in-One WP Migration Unlimited Extension: by ServMask – 2.37
All-in-One WP Migration: by ServMask – 7.29
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.0.8.3
Contact Form 7: by Takayuki Miyoshi – 5.3
Duplicate Page: by mndpsingh287 – 4.3
Email Log: by Sudar – 2.4.3
Facebook for WooCommerce: by Facebook – 2.1.4
Jetpack by WordPress.com: by Automattic – 9.0.2
SOGO Add Script Header Footer: by orenhav (SOGO) – 3.9
Qty Increment Buttons for WooCommerce: by taisho – 2.7.5
Really Simple SSL: by Really Simple Plugins – 3.3.5
Webcraftic Robin image optimizer: by Webcraftic  – 1.4.6
Sales Analytics: by Oleg Velgun – 1.0.0
Say What?: by Lee Willis – 1.9.6
User Role Editor: by Vladimir Garagulya – 4.56.1
Advanced Shipment Tracking for WooCommerce: by zorem – 3.1.4
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.4
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.6
Preview E-mails for WooCommerce: by Digamber Pradhan – 1.6.6
Product Gallery Slider for WooCommerce: by codeixer – 2.0.4
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.3
WooCommerce Shipping & Tax: by Automattic – 1.25.1
WooCommerce: by Automattic – 4.0.1 – 4.6.2 is available
WP Email Users: by techspawn1 – 1.6.9
WP File Manager: by mndpsingh287 – 6.9
WP Rollback: by Impress.org – 1.7.1
WP User Avatar: by ProfilePress – 2.2.7
YITH WooCommerce Advanced Reviews: by YITH – 1.4.8

### Inactive Plugins (17) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Automatic Invoice Generation for Remaining Balance on Appointments: by Aleksandr Levashov – 1.0.0
Contact Form 7 Extension For Mailchimp: by Renzo Johnson – 0.5.28
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Hello Dolly: by Matt Mullenweg – 1.7.2
Post SMTP: by Yehuda Hassine – 2.0.15
Store Hours Manager for WooCommerce: by BizSwoop a CPF Concepts
LLC Brand – 4.0.13

WooCommerce Addon Uploads_: by Dhruvin Shah – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce Bookings_: by WooCommerce – 1.15.0 – 1.15.29 is available – Not tested with the active version of WooCommerce
WooCommerce Cart Expiration: by Liquid Web – 0.2.0 – Not tested with the active version of WooCommerce
WooCommerce Cash On Pickup: by Marian Kadanka – 1.5 – Not tested with the active version of WooCommerce
WooCommerce Composite Products: by SomewhereWarm – 4.1.0 – 7.1.1 is available – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.2.4
Wordfence Security: by Wordfence – 7.4.12
WordPress Importer: by wordpressdotorg – 0.7
WordPress Starter: by SiteGround – 1.0.4
WP Mail SMTP: by WPForms – 2.5.1

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.6.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
external (external)
grouped (grouped)
phive_booking (phive_booking)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #278 - /shop/
Cart: #279 - /cart/
Checkout: #280 - /checkout/
My account: #281 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Upgrade
Version: 1.0
Author URL: http://Upwork
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: Upgrade/woocommerce/cart/cart-empty.php
Upgrade/woocommerce/cart/cart-totals.php
Upgrade/woocommerce/cart/cart.php version 3.5.0 is out of date. The core version is 3.8.0
Upgrade/woocommerce/cart/proceed-to-checkout-button.php
Upgrade/woocommerce/cart/shipping-calculator.php version 3.5.0 is out of date. The core version is 4.0.0
Upgrade/woocommerce/checkout/form-billing.php
Upgrade/woocommerce/checkout/form-checkout.php
Upgrade/woocommerce/checkout/form-coupon.php
Upgrade/woocommerce/checkout/form-shipping.php
Upgrade/woocommerce/checkout/payment.php
Upgrade/woocommerce/checkout/review-order.php version 3.3.0 is out of date. The core version is 3.8.0
Upgrade/woocommerce/checkout/thankyou.php version 3.2.0 is out of date. The core version is 3.7.0
Upgrade/woocommerce/content-single-product.php
Upgrade/woocommerce/emails/customer-invoice.php
Upgrade/woocommerce/emails/email-addresses.php version 3.5.4 is out of date. The core version is 3.9.0
Upgrade/woocommerce/emails/email-order-details.php
Upgrade/woocommerce/emails/email-order-items.php
Upgrade/woocommerce/loop/add-to-cart.php
Upgrade/woocommerce/myaccount/dashboard.php
Upgrade/woocommerce/myaccount/form-edit-account.php
Upgrade/woocommerce/myaccount/form-edit-address.php
Upgrade/woocommerce/myaccount/form-login.php
Upgrade/woocommerce/myaccount/form-lost-password.php
Upgrade/woocommerce/myaccount/form-reset-password.php
Upgrade/woocommerce/myaccount/my-account.php
Upgrade/woocommerce/myaccount/my-address.php
Upgrade/woocommerce/myaccount/my-orders.php
Upgrade/woocommerce/myaccount/navigation.php
Upgrade/woocommerce/myaccount/orders.php version 3.2.0 is out of date. The core version is 3.7.0
Upgrade/woocommerce/notices/notice.php version 3.5.0 is out of date. The core version is 3.9.0
Upgrade/woocommerce/order/order-details-item.php
Upgrade/woocommerce/order/order-details.php
Upgrade/woocommerce/single-product/add-to-cart/simple.php
Upgrade/woocommerce/single-product/add-to-cart/variable.php
Upgrade/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Upgrade/woocommerce/single-product/add-to-cart/variation.php
Upgrade/woocommerce/single-product/price.php
/home/selftaug/public_html/theupgradesalons.com/wp-content/plugins/yith-woocommerce-advanced-reviews//templates/ywar-rating.php
Upgrade/woocommerce/single-product/related.php version 3.0.0 is out of date. The core version is 3.9.0
Upgrade/woocommerce/single-product/tabs/additional-information.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 3,866
Oldest: 2020-10-08 11:08:31 +0000
Newest: 2020-11-08 10:45:49 +0000

Failed: 8
Oldest: –
Newest: –

Pending: 3
Oldest: 2020-11-08 10:57:42 +0000
Newest: 2020-11-12 22:52:00 +0000

`
```
</details>

**Comment by addedlovely** [comment] 2020-11-14 13:03
Am also trying to add a specific variation to the cart, using an ?add-to-cart=<< variation ID >> link - with one attribute set to 'any'. And am receiving the same validation message.

**Comment by BlackJack7878** [comment] 2021-02-12 16:20
Bump, still have this issue in 5.0.0

**Comment by addedlovely** [comment] 2021-02-12 16:53
Likewise, dug a bit deeper - and have correctted the link I'm using to add to the basket, as follows for an taxonomy attribute called finish
?add-to-cart=<< parent id >>&variation_id=<< variation id >>&attribute_pa_finish=any

This returns an error, Invalid value posted for Finish.

Issue seems to be here in the add_to_cart function:
https://github.com/woocommerce/woocommerce/blob/f9a02d1029a1db9e7f7f6a43e0e7185420a94bb7/includes/class-wc-cart.php#L1040

'Filter out 'any' variations, which are empty, as they need to be explicitly specified while adding to cart.' - Surely that's not intended, as the attribute is set to 'any' - would read that to be mean it can be 'any' of the options, not explicitly specified?

**Comment by barryhughes** [comment] 2021-05-05 23:05
Thanks for taking the time to share these details.

I'd love to clarify a few things first of all, as so far I'm unable to replicate the problem—which may simply be because I've misunderstood part of the report. In an effort to promote clarity, let's suppose we're working with a variable product called Coffee (product ID 1), with two variable attributes as follows:

| Strength | Grind |
| --- | --- |
| Mild | Coarse |
| Strong | Fine |

Let's also suppose we have two variations to begin with:

| Variation ID | Strength | Grind |
| --- | --- | --- |
| 2 | Any | Coarse |
| 3 | Any | Fine | 

> `// Filter out 'any' variations, which are empty, as they need to be explicitly specified while adding to cart.`
>
> Surely that's not intended, as the attribute is set to 'any'. I would read that to be mean the attribute can be 'any' of the options, not explicitly specified?

Building on my example, let's imagine variation 2 (any coarse coffee) is being added to the cart. In relation to this comment, we're removing 'any' (at runtime, this is actually an empty string) because we need to fill that value with the _specific strength of coffee_ being ordered...otherwise we won't know what to actually ship to the customer. 

> I've this function `WC()->cart->add_to_cart(...)` where all arguments are defined and being used, but product can't be added to cart. 

So would it be possible to get an example of the call you are making based on my relatively simple coffee product (unless it's too simple to see the problem)? In my testing, for instance, this works:

```php
// Product:         Quantity:    Variation:
// #1 ('Coffee')    1            2 ('Any Coarse Coffee')
WC()->cart->add_to_cart( 1, 1, 2, [
    'attribute_strength' => 'Mild',
    'attribute_grind'    => 'Coarse',
] );
```

On the other hand, the following example will fail with the same *"(Attribute) is a required field"* error you mentioned (similarly so if I don't pass an array at all), but in this case the failure is expected:

```php
WC()->cart->add_to_cart( 1, 1, 2, [
    'attribute_strength' => '',
    'attribute_grind'    => '',
] );
```

If I can get a more specific example of what you're doing, it will be easier to assess if what you're describing is a bug or is actually expected behavior. Thanks!

**Comment by BlackJack7878** [comment] 2021-05-06 10:00
@barryhughes hello and thanks for your feedback!

Could you try this:

```
WC()->cart->add_to_cart( 1, 1, 2, [
    'attribute_strength' => '',
    'attribute_grind'    => 'Coarse',
] );
```

So one of attributes is defined and another is not defined/any

**Comment by BlackJack7878** [comment] 2021-05-06 10:22
Actually one moment, I'll recheck it

**Comment by BlackJack7878** [comment] 2021-05-06 10:30
Actually it's similar to this, but I'm receiving error

```
WC()->cart->add_to_cart( 1, 1, 2, [
    'attribute_strength' => 'Mild',
    'attribute_grind'    => 'Coarse',
] );
```

**Comment by BlackJack7878** [comment] 2021-05-06 10:35
Could you try adding product not via variation attributes array but with variation id?

My code:

`WC()->cart->add_to_cart( $_POST['product_id'], $_POST['quantity'], $variation_id,  $_POST['data'], array());`

**Comment by addedlovely** [comment] 2021-05-06 11:24
@barryhughes to add some context. In my use case - the product is a paint, has the attribute size ( 'sample', 'l litre', '5 litres' ), finish ('matt', 'gloss' ) and colour ( 'red', 'blue', 'green' ). Sample isn't in a specific finish, so the variation has size = sample, colour = red and finish = any.

It's then never possible to add the 'sample' variation to the cart. Instead, i've created a new 'sample' finish as a workaround. 

If it's not possible to add a variation that has an attribute set to 'any' then surely it has no function to display it as an option in the admin interface?

**Comment by barryhughes** [comment] 2021-05-06 17:55
@addedlovely ... gotcha, that's useful context. So I think perhaps there is an misunderstanding about how this is intended to work.

| Variant | Colour | Size | Finish |
| --- | --- | --- | --- |
| A ('Blue Sampler') | Blue | Sample | Any |
| B ('Red Sampler') | Red | Sample | Any |

Purely an example, of course, your setup may be a little different, but anyway the above gives us two variants: a red sampler and a blue sampler. What's important to note is that the use of 'any' doesn't mean the customer doesn't have to select a finish: it means they can (and must) select the finish they want.

In other words, we can't add either of those variants to the cart without specifying a valid finish (matt or gloss). This is intentional, though I see now it's not what you were hoping for. If I'm understanding correctly you are seeking an option like _'No need for customer to specify'_ or _'Merchant will decide'_ ... is that correct? 

If so, I think your current workaround is probably a solid way to solve this and, if you wanted to, you could improve on it via some customization work (I'm afraid we can't help with that directly, though) to hide your 'sample' finish except in the cases where it actually makes sense.

Beyond that, if you feel strongly that the functionality you are seeking belongs in WooCommerce core, you could consider submitting a feature request or upvoting a suitable existing request on our [Ideas Board](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=36092).

I hope this clarifies things and since it sounds very much like this is a case of a feature being misunderstood rather than a bug, I'll go ahead and close this issue.

**Closed by barryhughes** 2021-05-06 17:55 UTC
Labels: has feedback

**Comment by BlackJack7878** [comment] 2021-05-06 19:12
I understood, my issue was with attribute key naming in array, mine was "strength" while it has to be "attribute_strength". Hope this will help someone!

**Comment by ghanshyam1994** [comment] 2023-06-23 06:36
$pa_koostis_value = get_post_meta($parent_product_id, '_product_attributes', true);
foreach($pa_koostis_value as &$value){
	if($value['is_variation'] === 1){
		$value['is_variation'] = 0;						
	}
}
update_post_meta( $parent_product_id, '_product_attributes', json_encode($pa_koostis_value) );	



for simple product I don't know why woo commerce  set it to is_variation 1 but some attributes are required set 

![image](https://github.com/woocommerce/woocommerce/assets/17923790/3bf2f6ce-814d-4728-8d57-c3c190e8e14b)


then we need to set it is_variation = "0" 

after that it's working fine

**Comment by epnb** [comment] 2024-03-05 13:58
would be nice to add a filter in add_to_cart allowing disabling the validation
