### ISSUE TITLE
Saved Checkbox Value lost after Update and Visting Other Admin Pages 

### ISSUE THREAD

**Issue by Njengah** [woocommerce/woocommerce#27454] opened 2020-08-22 22:16 UTC
https://github.com/woocommerce/woocommerce/blob/9b9ebc396a13bf1cd2a0e2b44743809cb884beac/includes/admin/wc-admin-functions.php#L159
I have this issue and have tested it several times with the same results. I am using woocommerce_update_options( ) to save which works as is should for all field types.  The checkbox loses the saved value after navigating away from the WooCommerce admin pages. 

`            'test_checkbox' => array(
                'name'     =>  __( 'Enable', 'text-domain' ),
                'type'     =>  'checkbox',
                'desc'     =>  __('Some desc', 'text-domain' ),
                'id'       =>  'some_id_example',
                'class'    =>  'example_class'
            ), 
`

I am using the admin_init hook for the update. I can't find out the reason why it keeps losing the saved value for only the checkbox other fields are ok. I also can't find any good documentation on the same.

**Comment by rodrigoprimo** [comment] 2020-10-22 17:37
Hi @Njengah,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodrigoprimo** 2020-10-22 17:37 UTC
Labels: support request
