### ISSUE TITLE
[REST API] Product stock update changes special sales price dates

### ISSUE THREAD

**Issue by ismailfakirsharespine** [woocommerce/woocommerce#19785] opened 2018-04-19 09:49 UTC
## Steps to reproduce the issue

1. PUT http://BASE_URL/wc-api/v3/products/[PRODUCT_ID]? with the following data:

**{"product":{"stock_quantity":"2280","managing_stock":true}}**

## Expected/actual behavior

When I follow those steps, Changes the special sales dates one day earlier as follows:

Date for special price: START-END

2018-04-20 to 2018-04-25

**TO**

2018-04-19 to 2018-04-24

 **I was expecting to see, no change in special sales dates.**

![image](https://user-images.githubusercontent.com/38524793/38984516-270311a2-43c7-11e8-9123-1c8cb3d79cc6.png)

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://rabatttestwetail.wetail.shop
Site URL: http://rabatttestwetail.wetail.shop
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.29-1~dotdeb+8.1
PHP Post Max Size: 10 MB
PHP Time Limit: 600
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total databasstorlek: 32.55MB
Datastorlek för databas: 31.35MB
Indexstorlek för databas: 1.20MB
wp_woocommerce_sessions: Data: 0.05 MB + Index: 0.02 MB
wp_woocommerce_api_keys: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02 MB + Index: 0.05 MB
wp_woocommerce_order_items: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_order_itemmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_tax_rates: Data: 0.02 MB + Index: 0.06 MB
wp_woocommerce_tax_rate_locations: Data: 0.02 MB + Index: 0.05 MB
wp_woocommerce_shipping_zones: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_shipping_zone_locations: Data: 0.02 MB + Index: 0.05 MB
wp_woocommerce_shipping_zone_methods: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_payment_tokens: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_payment_tokenmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_log: Data: 0.02 MB + Index: 0.02 MB
wp_commentmeta: Data: 0.06 MB + Index: 0.03 MB
wp_comments: Data: 0.02 MB + Index: 0.09 MB
wp_links: Data: 0.02 MB + Index: 0.02 MB
wp_options: Data: 0.42 MB + Index: 0.05 MB
wp_pmxe_exports: Data: 0.11 MB + Index: 0.00 MB
wp_pmxe_google_cats: Data: 0.39 MB + Index: 0.00 MB
wp_pmxe_posts: Data: 0.02 MB + Index: 0.00 MB
wp_pmxe_templates: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_files: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_history: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_imports: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_posts: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_templates: Data: 0.02 MB + Index: 0.00 MB
wp_postmeta: Data: 27.20 MB + Index: 0.27 MB
wp_posts: Data: 2.52 MB + Index: 0.13 MB
wp_termmeta: Data: 0.02 MB + Index: 0.03 MB
wp_terms: Data: 0.02 MB + Index: 0.03 MB
wp_term_relationships: Data: 0.02 MB + Index: 0.02 MB
wp_term_taxonomy: Data: 0.02 MB + Index: 0.03 MB
wp_usermeta: Data: 0.02 MB + Index: 0.03 MB
wp_users: Data: 0.02 MB + Index: 0.05 MB
wp_yoast_seo_links: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_meta: Data: 0.02 MB + Index: 0.00 MB

### Post Type Counts ###

attachment: 156
fl-builder-template: 15
nav_menu_item: 9
page: 36
post: 1
product: 31
product_variation: 4
revision: 374

### Security ###

Secure connection (HTTPS): ❌Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Klarna Gateway: av WooCommerce – 2.3.1 – 2.5.11 finns tillgänglig – Inte testat med den aktiva versionen för WooCommerce
Yoast SEO: av Team Yoast – 5.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Butikbas: #4 - /shop
Varukorg: #5 - /varukorg
Kassan: #6 - /kassa
Mitt konto: #7 - /mitt-konto
Allmänna villkor: ❌ Sida har inte valts

### Theme ###

Name: Wetail Child Theme
Version: 1.0
Author URL: http://www.wetail.io
Child Theme: ✔
Parent Theme Name: Beaver Builder Theme
Parent Theme Version: 1.6.2
Parent Theme Author URL: http://www.wpbeaverbuilder.com/?utm_medium=bb-pro&utm_source=bb-theme&utm_campaign=themes-admin-page
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: Checkout URL not set
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Villkorssida: Du behöver ange en villkorssida i WooCommerce inställningar eller i Klarna Checkout inställningar för att aktivera Klarna Checkout.
`
```
</details>

**Comment by ismailfakirsharespine** [comment] 2018-04-19 09:55
Tested with WooCommerce 2.5.x, but can not reproduce the issue

**Comment by peterfabian** [comment] 2018-04-19 12:08
Hi, 

When I tried to reproduce this problem, the PUT request does not seem to change the Sale price dates. 
I see you're using WooCommerce 3.2.1. Have you tried to check if this still happens with the latest WooCommerce version (preferably if you have a test site or a staging environment)?

**Comment by claudiosanches** [comment] 2018-04-19 14:12
Probably caused by some plugin or even already fixed on newer versions, so better to update your installation.
I'm not able to reproduce it on 3.3.5.

**Closed by claudiosanches** 2018-04-19 14:12 UTC
