### ISSUE TITLE
[GlobalStep - 4.1 beta 1]“Setup Tax” screen is different from the one mentioned on GitHub document i.e., instead of “Connect” button “Configure” button is displayed

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26128] opened 2020-04-08 17:08 UTC
**Steps to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on "Setup Tax".
4. Observe that "Configure" button is displayed instead of "Connect" button.

**Actual Result:**
“Setup Tax” screen is different from the one mentioned on GitHub document i.e., instead of “Connect” button “Configure” button is displayed

**Expected Result:**
As per the document "Connect" button should be displayed instead of configure.
![10  Setup Tax Rate_Actual](https://user-images.githubusercontent.com/41110392/78812795-9b6a5780-79e9-11ea-8412-0bad9cb7e92d.png)
![10  Setup Tax Rate_Expected](https://user-images.githubusercontent.com/41110392/78812806-9e654800-79e9-11ea-8a39-2ed48787e0e0.png)

**Comment by juliaamosova** [comment] 2020-04-14 19:37
Hi @gglobalstep,

Thanks for raising this issue! You are seeing `Configure` button instead of `Connect` because likely during onboarding wizard, you skipped the installation of WooCommerce Services in the section below:

![services](https://user-images.githubusercontent.com/19143190/79266427-8f591c80-7e65-11ea-98a5-d8f701a7e5a9.jpeg)

- If the user clicks on `Yes please!`, WooCommerce Services is being installed and they see the `Connect` button in the Tax Setup task;
- If the user clicks on `No thanks`, WooCommerce Services is not being installed and they see the `Configure` button in the Tax Setup task. 

Closing this issue as there seems to be no bug but rather expected behavior described.

**Closed by juliaamosova** 2020-04-14 19:37 UTC
