### ISSUE TITLE
Cannot delete customer via WP-CLI. wp wc customer delete 

### ISSUE THREAD

**Issue by lordspace** [woocommerce/woocommerce#29824] opened 2021-05-04 13:47 UTC
I have tried deleting a customer by passing email and id and got different messages.
WP v5.7.1 / woocommerce v5.2.2

wp wc customer delete 'some@email.com' --user=some_admin_user
Error: No route was found matching the URL and request method. {"status":404}

wp wc customer delete 24279 --user=some_admin_user
Error: Customers do not support trashing. {"status":501}

OS:     Linux 5.9.6-x86_64-linode139 #1 SMP Thu Nov 5 14:45:39 EST 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.8
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/example.com
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0

**Comment by tammullen** [comment] 2021-05-09 10:37
Hi @lordspace   

Please see: https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Commands#wc-customer-delete-id or run `wp wc customer delete --help`  
You need to add `--force`   to the command
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-05-09 10:37 UTC
