### ISSUE TITLE
Closing gallery triggers link behind

### ISSUE THREAD

**Issue by fkoomek** [woocommerce/woocommerce#25922] opened 2020-03-14 01:48 UTC
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.open gallery of a product and close it on mobile device (I have android) 
2. You have to have link directly behind the closing button, see a video

## Expected/actual behavior

When I follow those steps, closing gallery triggers the link behind. It doesnt happen every time, but often. There is something wrong in photoswipe.js. After update of Woocommerce I always replace it with an older version of that file. I use photoswipe. js from version 3.6.. With it, this problem never shows. 
https://www.liberlapidum.com/cs/svid_20200314_013029_1/

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment
Woocommerce 4.0.
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by tammullen** [comment] 2020-03-16 23:49
Hi @fkoomek 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end using Chrome 80 on Android 10. I wasn't able to reproduce it using a reduced or mobile simulated viewport on Desktop Chrome 80 on MacOS.
​
![SVID_20200316_233437_1 2020-03-16 23_43_08](https://user-images.githubusercontent.com/24649833/76808659-4ff4cd00-67e0-11ea-9c74-40ab132bddd8.gif)


We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by tammullen** [comment] 2020-03-18 16:39
Hi @fkoomek 

Thank you for reporting the issue. However, I have discovered this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25458. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Closed by tammullen** 2020-03-18 16:39 UTC
Labels: bug, component: product, priority: low
