### ISSUE TITLE
Customer Order details not showing in confirmation email

### ISSUE THREAD

**Issue by add2kittyadmin** [woocommerce/woocommerce#20598] opened 2018-06-21 08:03 UTC
When customers receive the email confirming their order the boxes to do not contain their order details only the email and order number shows.

Is their a known bug?

![image](https://user-images.githubusercontent.com/40454577/41705780-f09d48de-7531-11e8-966c-09a57bcc117a.png)

Thanks for your help..

**Comment by claudiulodro** [comment] 2018-06-21 17:45
It looks like the email properly rendered all the information, as the dynamic border boxes are present in the correct size and the email fully rendered all the areas where they should be. Can you please check your email color settings and verify you do not have `#FFFFFF` set as the "Body text color"? That's what it looks like the issue is to me.

<img width="756" alt="screen shot 2018-06-21 at 10 41 24 am" src="https://user-images.githubusercontent.com/7317227/41735917-d890f804-753f-11e8-8975-4ba541daa3a7.png">

**Comment by claudiosanches** [comment] 2018-06-22 17:20
Closing since seems like a customization issue, and not an issue by default on WooCommerce.
There is also missing a lot of information to make anyone able to reproduce this issue.

**Closed by claudiosanches** 2018-06-22 17:20 UTC
Labels: status: needs feedback
