### ISSUE TITLE
WooCommerce Order API always creates empty orders 

### ISSUE THREAD

**Issue by fiazhussain43** [woocommerce/woocommerce#28691] opened 2020-12-30 13:44 UTC
Create order postman
{
"order": {
"payment_details": {
"method_id": "bacs",
"method_title": "Direct Bank Transfer",
"paid": true
},
"billing_address": {
"first_name": "John",
"last_name": "Doe",
"address_1": "969 Market",
"address_2": "",
"city": "San Francisco",
"state": "CA",
"postcode": "94103",
"country": "US",
"email": "john.doe@example.com",
"phone": "(555) 555-5555"
},
"shipping_address": {
"first_name": "John",
"last_name": "Doe",
"address_1": "969 Market",
"address_2": "",
"city": "San Francisco",
"state": "CA",
"postcode": "94103",
"country": "US"
},
"customer_id": 10,
"line_items": [
{
"product_id": 4050,
"quantity": 1,
"meta_data": {
"key": "_wpml_media_has_media"
}
}
],
"shipping_lines": [
{
"method_id": "flat_rate",
"method_title": "Flat Rate",
"total": "10.00"
}
]
}
}

Reponse:

{
"id": 6094,
"parent_id": 0,
"number": "6094",
"order_key": "wc_order_uJn3m36KW8vy4",
"created_via": "rest-api",
"version": "4.8.0",
"status": "pending",
"currency": "CHF",
"date_created": "2020-12-30T13:36:51",
"date_created_gmt": "2020-12-30T13:36:51",
"date_modified": "2020-12-30T13:36:51",
"date_modified_gmt": "2020-12-30T13:36:51",
"discount_total": "0.00",
"discount_tax": "0.00",
"shipping_total": "0.00",
"shipping_tax": "0.00",
"cart_tax": "0.00",
"total": "0.00",
"total_tax": "0.00",
"prices_include_tax": false,
"customer_id": 0,
"customer_ip_address": "",
"customer_user_agent": "",
"customer_note": "",
"billing": {
"first_name": "",
"last_name": "",
"company": "",
"address_1": "",
"address_2": "",
"city": "",
"state": "",
"postcode": "",
"country": "",
"email": "",
"phone": ""
},
"shipping": {
"first_name": "",
"last_name": "",
"company": "",
"address_1": "",
"address_2": "",
"city": "",
"state": "",
"postcode": "",
"country": ""
},
"payment_method": "",
"payment_method_title": "",
"transaction_id": "",
"date_paid": null,
"date_paid_gmt": null,
"date_completed": null,
"date_completed_gmt": null,
"cart_hash": "",
"meta_data": [
{
"id": 23486,
"key": "mailchimp_woocommerce_campaign_id",
"value": ""
},
{
"id": 23487,
"key": "mailchimp_woocommerce_landing_site",
"value": ""
}
],
"line_items": [],
"tax_lines": [],
"shipping_lines": [],
"fee_lines": [],
"coupon_lines": [],
"refunds": [],
"iconic_delivery_meta": {
"date": "",
"timeslot": "",
"timestamp": ""
},
"currency_symbol": "CHF",
"_links": {
"self": [
{
"href": "https://freshbrainstudio.com/restaurant/en/wp-json/wc/v3/orders/6094"
}
],
"collection": [
{
"href": "https://freshbrainstudio.com/restaurant/en/wp-json/wc/v3/orders"
}
]
}
}

**Comment by juliaamosova** [comment] 2020-12-30 17:01
Hi @fiazhussain43,

Thanks for reporting the issue. However, I can't reproduce it - everything is working as expected on my end. 

As per our ["Create order" WC REST API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order), I was able to create an order with the correct response.

My POST request and response + order created on the site:

![api1](https://user-images.githubusercontent.com/19143190/103368760-5b2a9800-4a96-11eb-82f0-2d04599cd845.jpg)

By default, the order is created for a Guest user.

From your example request, it looks like you want to be able to create an order attached to a specific customer. In which case, you'd need to specify `customer_id` at the beginning of your request. 

Here is how it should be done:

```
{
  "customer_id": 2,
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "set_paid": true,
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  },
  "line_items": [
    {
      "product_id": 93,
      "quantity": 2
    },
    {
      "product_id": 22,
      "variation_id": 23,
      "quantity": 1
    }
  ],
  "shipping_lines": [
    {
      "method_id": "flat_rate",
      "method_title": "Flat Rate",
      "total": "10.00"
    }
  ]
}
```

As a result, the response will look as follows:

```
{
    "id": 91,
    "parent_id": 0,
    "status": "processing",
    "currency": "USD",
    "version": "4.9.0",
    "prices_include_tax": true,
    "date_created": "2020-12-30T16:51:11",
    "date_modified": "2020-12-30T16:51:11",
    "discount_total": "0.00",
    "discount_tax": "0.00",
    "shipping_total": "10.00",
    "shipping_tax": "0.00",
    "cart_tax": "0.00",
    "total": "35.00",
    "total_tax": "0.00",
    "customer_id": 2,
    "order_key": "wc_order_lnZGioeqTDWc0",
    "billing": {
        "first_name": "John",
        "last_name": "Doe",
        "company": "",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "US",
        "email": "john.doe@example.com",
        "phone": "(555) 555-5555"
    },
    "shipping": {
        "first_name": "John",
        "last_name": "Doe",
        "company": "",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "US"
    },
    "payment_method": "bacs",
    "payment_method_title": "Direct Bank Transfer",
    "transaction_id": "",
    "customer_ip_address": "",
    "customer_user_agent": "",
    "created_via": "rest-api",
    "customer_note": "",
    "date_completed": null,
    "date_paid": "2020-12-30T16:51:11",
    "cart_hash": "",
    "number": "91",
    "meta_data": [],
    "line_items": [
        {
            "id": 17,
            "name": "",
            "product_id": 0,
            "variation_id": 0,
            "quantity": 2,
            "tax_class": "",
            "subtotal": "0.00",
            "subtotal_tax": "0.00",
            "total": "0.00",
            "total_tax": "0.00",
            "taxes": [],
            "meta_data": [],
            "sku": null,
            "price": 0,
            "parent_name": null,
            "bundled_by": "",
            "bundled_item_title": "",
            "bundled_items": []
        },
        {
            "id": 18,
            "name": "Long Sleeve Tee",
            "product_id": 23,
            "variation_id": 0,
            "quantity": 1,
            "tax_class": "",
            "subtotal": "25.00",
            "subtotal_tax": "0.00",
            "total": "25.00",
            "total_tax": "0.00",
            "taxes": [],
            "meta_data": [
                {
                    "id": 146,
                    "key": "_reduced_stock",
                    "value": "1",
                    "display_key": "_reduced_stock",
                    "display_value": "1"
                }
            ],
            "sku": "woo-long-sleeve-tee",
            "price": 25,
            "parent_name": null,
            "bundled_by": "",
            "bundled_item_title": "",
            "bundled_items": []
        }
    ],
    "tax_lines": [],
    "shipping_lines": [
        {
            "id": 19,
            "method_title": "Flat Rate",
            "method_id": "flat_rate",
            "instance_id": "",
            "total": "10.00",
            "total_tax": "0.00",
            "taxes": [],
            "meta_data": []
        }
    ],
    "fee_lines": [],
    "coupon_lines": [],
    "date_created_gmt": "2020-12-30T16:51:11",
    "date_modified_gmt": "2020-12-30T16:51:11",
    "date_completed_gmt": null,
    "date_paid_gmt": "2020-12-30T16:51:11",
    "currency_symbol": "$",
    "_links": {
        "self": [
            {
                "href": "https://eventual-salmon.xxx/wp-json/wc/v3/orders/91"
            }
        ],
        "collection": [
            {
                "href": "https://eventual-salmon.xxx/wp-json/wc/v3/orders"
            }
        ],
        "customer": [
            {
                "href": "https://eventual-salmon.xxx/wp-json/wc/v3/customers/2"
            }
        ]
    }
}
``` 

And here I've got the order created on the site assigned to the customer as per my request:

![api2](https://user-images.githubusercontent.com/19143190/103368877-b8bee480-4a96-11eb-8e4e-32ef3ccb8799.jpg)

Please try as I suggested and let us know how it goes.

**Comment by juliaamosova** [comment] 2021-01-10 21:38
Hi @fiazhussain43,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-01-10 21:38 UTC
Labels: needs feedback

**Comment by prashantds** [comment] 2022-11-18 13:02
When i create order by API then instance_id is blank please suggest.

![instance_id](https://user-images.githubusercontent.com/2160987/202711303-2eed7a4e-a8b0-4153-8df2-627a31cf9d18.png)
