### ISSUE TITLE
small picture problem

### ISSUE THREAD

**Issue by axcar95** [woocommerce/woocommerce#24091] opened 2019-07-07 13:19 UTC
when ı open my shop page one of my products picture is bigger than the rest of them in mobile it cause a lot of empty space. ı tried the small picture options. ıt didnt apply in the real page.
![4 4 kırpılmış](https://user-images.githubusercontent.com/48660460/60768970-f07fe280-a0d2-11e9-920d-660d2bea17dc.jpg)
![kırpılmamış](https://user-images.githubusercontent.com/48660460/60768976-09889380-a0d3-11e9-8772-8991b3ffee77.jpg)

**Comment by baljindersingh88** [comment] 2019-07-14 16:15
I think you need to apply the same dimensions to this image, like others. Can you share url?

**Comment by claudiosanches** [comment] 2019-07-16 18:39
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried set the same settings than you and it appeared to work correctly.

It could be your theme. You could try contact your theme's author to fix it.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Comment by claudiosanches** [comment] 2019-07-16 18:40
Also tagging this issue as `invalid`, since the issue template has been removed.

**Closed by claudiosanches** 2019-07-16 18:39 UTC
