### ISSUE TITLE
Only products with stock management on product level enabled appear in Reports >> Stock >> Out Of Stock

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#26254] opened 2020-04-23 09:00 UTC
**Describe the bug**
Only products with stock management on product level enabled appear in WooCommerce >> Reports >> Stock >> Out Of Stock.

If stock management on product level is disabled and the stock level is set to "out of stock" - the product will not appear in WooCommerce >> Reports >> Stock >> Out Of Stock.

**To Reproduce**
1. Create a simple product and disable stock management at a product level.
2. Go to WooCommerce >> Reports >> Stock >> Out Of Stock.
3. The product is not in the report.
4. Enable stock management at a product level.
5. The product is in the report now.

**Screenshots**

<img width="1125" alt="Screenshot 2020-04-23 at 10 50 24" src="https://user-images.githubusercontent.com/13084901/80080205-95c85200-8551-11ea-99aa-ad26cdb49d51.png">

<img width="1594" alt="Screenshot 2020-04-23 at 10 52 28" src="https://user-images.githubusercontent.com/13084901/80080232-9e208d00-8551-11ea-81dc-72bb64db4be9.png">

**Expected behavior**
I'd expect out of stock products with stock management disabled on a product level to appear in WooCommerce >> Reports >> Stock >> Out Of Stock

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
```
</details>

**Comment by juliaamosova** [comment] 2020-04-24 21:11
Hi @grigorijurasov,

Thank you for submitting the issue. While I can reproduce it, the legacy Reports section of WooCommerce will likely be deprecated at some point. 

Therefore, we won't be working on fixing this functionality as it works in the WooCommerce Admin Analytics section:

![st1](https://user-images.githubusercontent.com/19143190/80257125-38fe9180-864e-11ea-9558-24f6ad9a2298.jpg)

![st2](https://user-images.githubusercontent.com/19143190/80257136-3c921880-864e-11ea-90d0-51d872d7310d.jpg)

I am adding a `won't fix` label to this issue. Sorry! I hope the reason behind it is understandable.

**Closed** 2020-04-24 21:11 UTC
Labels: won't fix
