### ISSUE TITLE
Shipping and Invoice form error in My Account 

### ISSUE THREAD

**Issue by FranckCapoweb** [woocommerce/woocommerce#30019] opened 2021-06-02 11:39 UTC
**Prerequisites (mark completed items with an [x]):**
- [✔️] I have have carried out troubleshooting steps and I believe I have found a bug.
- [✔️] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The customer can't update this shipping and invoice address throught "My Account" page.

**Expected behavior**

**Actual behavior**
There is an error 500 during process and the form doesn't show.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to the website and log-in or create an account
2. Go to "My Account" page and pick an address
3. Try to edit one

`PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/domain.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php:2694\nStack trace:\n#0 /var/www/despratsaintverny.fr/wp-content/themes/theme-name/woocommerce/myaccount/form-edit-address.php(44): woocommerce_form_field('shipping_state', Array, '')\n`

`PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/domain.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php:2737\nStack trace:\n#0 /var/www/despratsaintverny.fr/wp-content/themes/theme-name/woocommerce/myaccount/form-edit-address.php(44): woocommerce_form_field('shipping_state', Array, '')\n`

**Isolating the problem (mark completed items with an [x]):**
- [  ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [  ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [✔️] I can reproduce this bug consistently using the steps above.

### FIX
Edit line 2694 in /wp-content/plugins/woocommerce/includes/wc-template-functions.php like this :

**Before** ❌ 

> if ( $args['required'] ) {
>                         $args['class'][] = 'validate-required';

**After** ✔️ 

> if ( $args['required'] ) {
>                         **$args['class']   = array();**
>                         $args['class'][] = 'validate-required';

And line 2737 like this :

**Before** ❌ 

> foreach ( $args['validate'] as $validate ) {
>                                 $args['class'][] = 'validate-' . $validate;

**After** ✔️ 

> foreach ( $args['validate'] as $validate ) {
>                                 $args['class'] = array();
>                                 $args['class'][] = 'validate-' . $validate;

<details>
### WordPress Environment ###

WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 1 Go
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.28-1+0~20210503.84+debian10~1.gbp6819da
PHP Post Max Size: 128 Mo
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.10-MariaDB-1:10.5.10+maria~buster
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
</details>

**Comment by tammullen** [comment] 2021-06-02 11:45
Hi @FranckCapoweb 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

![Screenshot 2021-06-02 at 12 44 05](https://user-images.githubusercontent.com/24649833/120474641-58630480-c3a0-11eb-9e40-be7a558d04b7.png)

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by FranckCapoweb** [comment] 2021-06-02 12:03
Ok, i juste try to deactivate all plugins and always the same error.

I tried to copy the woocommerce/myaccount/form-edit-address.php original file in my child theme but always the same.

I think the problem come from the theme (Argenta)

**Comment by AashikP** [comment] 2021-06-17 11:30
Hello @FranckCapoweb,

Thank you for clarifying that the issue comes from the theme, and recommendation on making the type check.

My understanding is that since [WooCommerce stores address as an array](https://github.com/woocommerce/woocommerce/blob/release/5.4/includes/class-wc-customer.php#L18), and the [default value is expected to be an array](https://github.com/woocommerce/woocommerce/blob/trunk/includes/wc-template-functions.php#L2669), the theme should pass an array as well.

Considering that, I'm closing this report for now. However, please feel free to add a comment if we're missing anything here.

**Closed by AashikP** 2021-06-17 11:30 UTC
Labels: category: can't reproduce, has feedback
