### ISSUE TITLE
No way to enter Credit Card Number 

### ISSUE THREAD

**Issue by phillipswdc** [woocommerce/woocommerce#19351] opened 2018-03-10 17:10 UTC
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
```
function outputcheckout(){

	echo do_shortcode('[woocommerce_checkout]');

	die();

};

add_action('wp_ajax_nopriv_outputcheckout', 'outputcheckout');

$.post(
ajax_url,
pdata,
function (result) {
//alert(result);
$('#checkout-wrap').html(result);
return;
}); // end post


```

This loads the checkout to the div but there is no way to enter credit card info when I look at source instead of the normal form element s I see the following...

```
<div id="stripe-card-element" style="background:#fff;padding:0 1em;border:1px solid #ddd;margin:5px 0;padding:10px 5px;">
					<!-- a Stripe Element will be inserted here. -->
</div>
```

Is this a bug?

**Comment by mikejolley** [comment] 2018-03-10 20:13
Not a bug, but something that won't be supported. The method above will mean you're a) missing require checkout javascript and b) not running said javascript once the html is output via your custom code once loaded via ajax. That element is added by the Stripe gateway's scripts.

**Closed by mikejolley** 2018-03-10 20:13 UTC

**Comment by phillipswdc** [comment] 2018-03-11 02:31
Thanks Mike!!

I actually came to that conclusion which made me wish I had a rewind button to undo the question!! Thank you for taking the time though I appreciate it!
