### ISSUE TITLE
3.0 Sort by Price issue

### ISSUE THREAD

**Issue by stefan-media90** [woocommerce/woocommerce#14633] opened 2017-04-24 05:24 UTC
Hello, when selecting the sorting options in Woocommerce -> Settings -> Display -> Default Product sorting -> Sort By Price (ASC or DSC), there is problem with all the variation products.

http://shop.roofexpert.ro/magazin/

Prices not sort ok in admin and front, works only if I always update the variables after publishing a new product. This problem has occurred since the update to 3.0. I tried to disable the modules and the theme but no change. All products are added manually, not imported.

<img src="https://cloud.githubusercontent.com/assets/27854916/25275350/8320f2ee-269d-11e7-990b-e53b0bbbd2bb.png" alt=""/>

Please help me. Thank you!

**Comment by mikejolley** [comment] 2017-04-24 15:07
Dupe of https://github.com/woocommerce/woocommerce/issues/14150#issuecomment-295795777 - investigating that - reply there.

**Closed by mikejolley** 2017-04-24 15:07 UTC
