### ISSUE TITLE
Too few arguments in class-wc-report-customer-list.php

### ISSUE THREAD

**Issue by BenBaudart** [woocommerce/woocommerce#28189] opened 2020-11-04 18:28 UTC
Hi there,

I have the the following error:
**Warning: sprintf(): Too few arguments in /home/----hidden----/www/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-customer-list.php on line 56**

It appears as I use the "link previous orders" function (actions button) in the WooCommerce / Reports / Customer page at /wp-admin/admin.php?page=wc-reports&tab=customers 

The function always works but the message always appears (wether there are old orders for this user or not).
Any idea?

Thank you

`
### WordPress Environment ###

WC Version: 4.6.1
REST API Version: ✔ 4.6.1
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.20
PHP Post Max Size: 130 MB
PHP Time Limit: 300
PHP Max Input Vars: 16000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.50-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.1
WC Database Prefix: mod411_
Total Database Size: 46.79MB
Database Data Size: 32.18MB
Database Index Size: 14.61MB
mod411_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
mod411_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod411_woocommerce_order_items: Data: 0.25MB + Index: 0.09MB + Engine InnoDB
mod411_woocommerce_order_itemmeta: Data: 2.52MB + Index: 2.97MB + Engine InnoDB
mod411_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod411_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_actionscheduler_actions: Data: 0.30MB + Index: 0.19MB + Engine InnoDB
mod411_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_actionscheduler_logs: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
mod411_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_comments: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
mod411_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_mailjet_wc_abandoned_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_mailjet_wc_abandoned_cart_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_mailjet_wc_guests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_options: Data: 4.05MB + Index: 1.64MB + Engine InnoDB
mod411_postmeta: Data: 4.44MB + Index: 5.80MB + Engine InnoDB
mod411_posts: Data: 8.03MB + Index: 0.36MB + Engine InnoDB
mod411_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
mod411_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod411_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
mod411_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_wc_order_product_lookup: Data: 0.31MB + Index: 0.34MB + Engine InnoDB
mod411_wc_order_stats: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
mod411_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
mod411_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod411_wfconfig: Data: 1.28MB + Index: 0.00MB + Engine InnoDB
mod411_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wffilemods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
mod411_wfhits: Data: 2.02MB + Index: 0.39MB + Engine InnoDB
mod411_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod411_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
mod411_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wflogins: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
mod411_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod411_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod411_wfstatus: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
mod411_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_yith_wcdn_desktop_notification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod411_yoast_indexable: Data: 0.33MB + Index: 0.41MB + Engine InnoDB
mod411_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod411_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod411_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod411_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 101
custom_css: 2
customize_changeset: 2
et_body_layout: 2
et_pb_layout: 7
et_template: 3
et_theme_builder: 1
flamingo_contact: 42
flamingo_inbound: 38
nav_menu_item: 15
oembed_cache: 2
page: 14
post: 2
product: 36
product_variation: 5
revision: 482
shop_coupon: 4
shop_order: 952
shop_order_refund: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Contact Form 7: by Takayuki Miyoshi – 5.3
Cookie Notice: by dFactory – 1.3.2
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.2.10 – Installed version not tested with active version of WooCommerce 4.6.1
Disable Comments: by WPDeveloper – 1.11.0
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.4.1

Mailjet for WordPress: by Mailjet SAS – 5.2.4
Really Simple SSL: by Really Simple Plugins – 3.3.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.34

WooCommerce Stripe Gateway: by WooCommerce – 4.5.3 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.24 – Installed version not tested with active version of WooCommerce 4.6.1
Woocommerce Kiekebich: by Ben Baudart – 0.3 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce: by Automattic – 4.6.1
Wordfence Security: by Wordfence – 7.4.12
Yoast SEO: by Team Yoast – 15.2.1
WPS Hide Login: by WPServeur
NicolasKulka
tabrisrp – 1.5.7

### Inactive Plugins (2) ###

Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.0.8.4
Flamingo: by Takayuki Miyoshi – 2.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #345 - /order/
Cart: #346 - /basket/
Checkout: #347 - /order-validation/
My account: #348 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: KKB - Divi Child
Version: 1.0.78
Author URL: https://johndoe.be
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.6.6
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 694
Oldest: 2020-10-04 20:19:15 +0200
Newest: 2020-11-04 18:52:09 +0100

Pending: 1
Oldest: 2020-11-04 19:25:11 +0100
Newest: 2020-11-04 19:25:11 +0100
`

**Comment by tammullen** [comment] 2020-11-04 21:29
Hi @BenBaudart 
​
Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 
​
- Made sure "Allow customers to place orders without an account" and "Allow customers to create an account during checkout" are ticked in WooCommerce > Settings > Accounts
- Bought a product using a new email, but made sure it's was a Guest Checkout 
- Bought another product using that same email, this time checked "Create an account" at Checkout
- Went to WooCommerce > Reports > Customers > Customer List
- Clicked the "Link Previous Orders" button:
​- Saw PHP warning 

![Screenshot_2020-11-04_at_21_08_53](https://user-images.githubusercontent.com/24649833/98169799-d6cbf680-1ee4-11eb-8748-3980d16d8e3f.png)
![Screenshot_2020-11-04_at_21_09_06](https://user-images.githubusercontent.com/24649833/98169804-d92e5080-1ee4-11eb-9d68-3d0d11b8933d.png)



We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by BenBaudart** [comment] 2020-11-04 22:26
Hi @tammullen 

Thanks for the quick reply! Always happy to contribute ;)

- FYI: On my end, warning is displayed in page, I guess it's related to a server / php config.
- `<div class="updated">` also appears empty.

Low priority indeed!

![ss-woo](https://user-images.githubusercontent.com/1891484/98174389-1a2e6100-1ef5-11eb-9807-d9f95b228182.jpg)

**Comment by pacmanito** [comment] 2021-10-15 11:38
The issue is still here, I just got the same warning in my log.

**Comment by galbaras** [comment] 2022-10-30 23:28
This may be low priority, but it sure seems like an easy fix. [Line 56](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/reports/class-wc-report-customer-list.php#L56) should have the second instance of `$linked` as an argument to `sprintf()`, not `esc_html()`:

`echo '<div class="updated"><p>' . sprintf( esc_html( _n( '%s previous order linked', '%s previous orders linked', $linked, 'woocommerce' ) ), $linked ) . '</p></div>';`

**Comment by pacmanito** [comment] 2023-01-11 22:41
Why on Earth this was not fixed in years? There's one closing bracket in the wrong place and that's all. Devs are too busy developing new interface which does not have that option at all?

**Comment by galbaras** [comment] 2023-01-11 23:05
Likely because there isn't a menu item for this report anymore...

**Comment by pacmanito** [comment] 2023-01-11 23:09
@galbaras yep, that's what I thought as well. They are planning to remove it completely. But there's no replacement for orders linking in the new interface!

**Comment by galbaras** [comment] 2023-01-11 23:20
The WooCommerce team works in mysterious ways sometimes. As for linking, see https://github.com/woocommerce/woocommerce/issues/29138#issuecomment-1301290552

**Comment by barryhughes** [comment] 2024-01-19 00:49
As noted earlier, this particular reporting functionality has been deprecated and has been replaced:

> There is a new and better Analytics section available for users running WordPress 5.3+. Head on over to the [WooCommerce Analytics](#/wp-admin/admin.php?page=wc-admin&path=/analytics/overview) or learn more about the new experience in the [WooCommerce Analytics documentation](https://woo.com/document/woocommerce-analytics/).

In light of which, I'm afraid this is not a priority for us. We'd be receptive to a community pull request, but otherwise do not plan on working in this area.

> But there's no replacement for orders linking in the new interface!

If it has not already been proposed, definitely feel free to raise an [enhancement request](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=type%3A+enhancement%2Cstatus%3A+awaiting+triage&projects=&template=2-enhancement.yml&title=%5BEnhancement%5D%3A+) for this. You can also submit feature requests [over here](https://woo.com/feature-requests/woocommerce/).

**Closed by barryhughes** 2024-01-19 00:49 UTC
Labels: type: bug, priority: normal, plugin: woocommerce, team: Proton, focus: legacy reports
