### ISSUE TITLE
New Order e-mail notification to admin issue

### ISSUE THREAD

**Issue by tanerf82** [woocommerce/woocommerce#25048] opened 2019-11-15 13:45 UTC
When new order placed by customer, "new order notification email to admin" is not triggered.

`
### WordPress Environment ###

WordPress address (URL): https://www.deuxlapins.com.tr
Site address (URL): https://www.deuxlapins.com.tr
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.11
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 14000
cURL Version: 7.66.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.20-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Comment by juliaamosova** [comment] 2019-11-15 17:12
Hi @tanerf82,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. So far I was not able to reproduce the issue. 

Moreover, the type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-11-15 17:12 UTC
