### ISSUE TITLE
WooCommerce databse error when activating it programatically

### ISSUE THREAD

**Issue by sandeshjangam** [woocommerce/woocommerce#24061] opened 2019-07-03 06:38 UTC
```
[07-Jun-2019 12:07:27 UTC] WordPress database error Table 'wp_cf.wp_wc_webhooks' doesn't exist for query SELECT webhook_id
				FROM wp_wc_webhooks
				WHERE 1=1
				AND `status` = 'active'
				ORDER BY webhook_id DESC made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WooCommerce->init, WooCommerce->load_webhooks, wc_load_webhooks, WC_Data_Store->__call, WC_Webhook_Data_Store->get_webhooks_ids, WC_Webhook_Data_Store->search_webhooks
[07-Jun-2019 12:07:28 UTC] WordPress database error Table 'wp_cf.wp_woocommerce_attribute_taxonomies' doesn't exist for query SELECT * FROM wp_woocommerce_attribute_taxonomies WHERE attribute_name != '' ORDER BY attribute_name ASC; made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Post_Types::register_taxonomies, wc_get_attribute_taxonomies

```

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Sample plugin zip - https://cl.ly/82c6c7663728

Here are steps to reproduce -

1. Install and Activate the given sample plugin.
2. Go to Settings->Woo Install Demo
3. Click on Install Woo Ajax
4. It will automatically show you alert once the plugin is activated ( Console will show you process ).
5. Refresh the page after an alert.
6. Now go to debug log you will see an error.

I hope this information enough to reproduce the issue.

Note -
 - Do this on a fresh installation
 - Enable debug log constants before testing.

## Expected/actual behavior

When I follow those steps, I see...

```
[07-Jun-2019 12:07:27 UTC] WordPress database error Table 'wp_cf.wp_wc_webhooks' doesn't exist for query SELECT webhook_id
				FROM wp_wc_webhooks
				WHERE 1=1
				AND `status` = 'active'
				ORDER BY webhook_id DESC made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WooCommerce->init, WooCommerce->load_webhooks, wc_load_webhooks, WC_Data_Store->__call, WC_Webhook_Data_Store->get_webhooks_ids, WC_Webhook_Data_Store->search_webhooks
[07-Jun-2019 12:07:28 UTC] WordPress database error Table 'wp_cf.wp_woocommerce_attribute_taxonomies' doesn't exist for query SELECT * FROM wp_woocommerce_attribute_taxonomies WHERE attribute_name != '' ORDER BY attribute_name ASC; made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Post_Types::register_taxonomies, wc_get_attribute_taxonomies
```

I was expecting to see...

Ideally, it should not throw an error.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment] 2019-07-03 09:22
Duplicate of #23882 

It is clear from the error that the table is missing, meaning the WooCommerce install routine likely never ran. We cannot debug plugins for you that is not WooCommerce core.

Ensure you have the table present in your database, tables are created when WooCommerce is installed or updated. The query in question is fired on init when woocommerce is loaded. You will have that error even when not doing ajax requests.

I am closing this issue as I am not able to replicate this locally with just WooCommerce, please do some troubleshooting of your own and if you can provide details on how to replicate this with just WooCommerce then I will gladly reopen, but it is clear this is pointing to missing tables indicating the WooCommerce install routine never ran.

**Closed by kloon** 2019-07-03 09:22 UTC

**Comment by sandeshjangam** [comment] 2019-07-03 10:02
@kloon 

`activate_plugin` is a WordPress function. It is a core function of WordPress. WooCommerce should support this.

That sample plugin I wrote for you to reproduce it in an easy way. You should keep it open before my reply. I hope you are able to support it.

**Comment by sandeshjangam** [comment] 2019-07-03 10:06
`activate_plugin` function is used in the plugin. That is the reason it throwing an error. Can you still say that it is not an issue?

THis is how used in plugin `activate_plugin( 'woocommerce/woocommerce.php', '', false, true );`

**Comment by kloon** [comment] 2019-07-03 10:09
@sandeshjangam I am well aware it is a WordPress function and WooCommerce follows the rules for defining an activation method as per https://github.com/woocommerce/woocommerce/blob/master/includes/class-woocommerce.php#L179

In that activation hook, we call the install method which installs the tables. So whatever you are doing in your plugin is not right as it is not calling the activation method we register per the link above.

**Comment by sandeshjangam** [comment] 2019-07-03 11:21
@kloon 
Here is a function I called in a plugin 

`activate_plugin( 'woocommerce/woocommerce.php', '', false, true );`

If anything wrong in the above function then please let me know. Because I am sure that it is correct and verified by other developers too.

If you call this function on fresh installation then It will still throw the error.

Just add this code in your function.php on fresh setup and it will throw an error. Make sure you have WooCommerce installed and not activate.

```
add_action( 'admin_init', function() {
	activate_plugin( 'woocommerce/woocommerce.php', '', false, true );
});
```
