### ISSUE TITLE
Apply coupon when all products are on sale

### ISSUE THREAD

**Issue by dokker** [woocommerce/woocommerce#27029] opened 2020-07-13 13:27 UTC
I cannot apply coupons with "Exclude sale items" setting when the cart only has items on sale. (It works as intended I know)
I need to apply other things in this case too. 

Can I somehow accept the coupon in this situation? Of course don't want any discount in this case, just accept the coupon. 

Is there any way to ignore E_WC_COUPON_NOT_APPLICABLE error?

**Comment by juliaamosova** [comment] 2020-07-13 20:30
Hi @dokker,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-07-13 20:30 UTC
