### ISSUE TITLE
Variation products export missing its attributes

### ISSUE THREAD

**Issue by levkany** [woocommerce/woocommerce#29204] opened 2021-02-23 17:23 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When exporting the products using the build in feature the product's related variations are not being attached to it

**Expected behavior**
The export list should be sorted by default with the variation product above and below it all it's related variations.
i noticed that if the list is not sorted like i mentioned above by default, the attributes will be empty.

**Actual behavior**
The variation product attributes are not being added to the product

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Export all the products with the default settings
2. Import into a new website with non matching product ids
3. Edit some variation product
4. see that no attributes are to be found in that product

**Screenshots**

The default sort of the export untouched
[https://imgur.com/0vXmrS2](url)

the expected default export (have been modified to allow the non matching ids of the variation product attributes to be attached to it)
[https://imgur.com/A1p2CHM](url)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2021-02-26 23:41
Hi @levkany,

Thank you for submitting the issue. However, I believe, that everything is working as expected. 

Variations need to be imported in 2 steps. Please see the docs here for how to do it: [Converting existing simple product to variable product](https://docs.woocommerce.com/document/product-csv-importer-exporter/#section-7).  The use case is slightly different but starting from step 9, it should apply to your case. 

Please let me know if I missed something and I will take another look.

**Comment by levkany** [comment] 2021-03-08 19:22
hii, sorry for the late response but i should've mentioned that i dont use the addon plugin, i am using the build in importer and exporter.

All the product types are imported successfully including the variations of a variable product, but..
It only import all the variations properly when the variations rows are located right after its "parent" variable product, for more clearance, i hope the images i attached in the the first post will help

thanks.

**Comment by swatipawarGS** [comment] 2021-11-26 13:57
Hi @levkany ,


Thank you for the updates information. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version and WordPress 5.8.2 version.


Please find below  screencast for reference :


https://user-images.githubusercontent.com/94531721/143584890-ec4f5fde-5dce-4a28-a69f-360756e0fa8a.mp4



Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by levkany** [comment] 2021-11-28 07:14
hi @swatipawarGS, thank you very much!
another thing which is for some reason specific to the hebrew, language is that if the attributes names are written in hebrew characters, the import will never import the variations.

for example: "sizeof" which was written in hebrew: "גודל".
if i bulk change the "גודל" to "sizeof" it will work, but otherwise, it won't.

thank you very much! and i love your plugin

**Comment by swatipawarGS** [comment] 2021-11-30 15:14
Hi @levkany ,

Thank you for providing an updated scenario. We are unable to reproduce the issue on our end for Hebrew language using WooCommerce 5.9.0 version.

Please find below screencast for reference :


https://user-images.githubusercontent.com/94531721/144013909-328c684f-0a78-4c4d-8441-a934d85b00aa.mp4


Please provide us more detailed steps and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by rrennick** [comment] 2023-10-13 07:55
This looks like a duplicate of #40274. See https://github.com/woocommerce/woocommerce/issues/40274#issuecomment-1737944120 for an explanation.

**Closed by rrennick** 2023-10-13 07:55 UTC
Labels: priority: low, focus: csv import/export [team:Proton], focus: variation [team:Proton], focus: documentation, plugin: woocommerce
