### ISSUE TITLE
Send admin emails for cancelled_to_* orders if status changed from pending

### ISSUE THREAD

**Issue by progcode** [woocommerce/woocommerce#21691] opened 2018-10-26 12:17 UTC
**Describe the bug**
Woocommerce currently not sending emails for admin users from cancelled orders, if status changed from pending to cancelled

**To Reproduce**
1. Create a new order with credit card payment (IPN)
2. Do NOT finish the payment
3. Waiting for status changing to cancelled from pending
4. It will be send an email from cancelled order - NOT WORKING

**Expected behavior**
**Hooked WC() functions:**

`add_filter( 'woocommerce_email_recipient_new_order', 'custom_email_notify', 10, 2 );
add_filter( 'woocommerce_email_recipient_cancelled_order', 'custom_email_notify', 10, 2 );
add_filter( 'woocommerce_email_recipient_failed_order', 'custom_email_notify', 10, 2 );`

**Comment by kloon** [comment] 2018-10-29 13:21
This is intended behavior, see the hooks it fires on here https://github.com/woocommerce/woocommerce/blob/07351d5e11f8d5dfc3620577ec5fe3128e704e81/includes/emails/class-wc-email-cancelled-order.php#L43-L44

Technically when an order is in pending status it has not been placed, placed orders will either be in on-hold which means it is pending payment confirmation, or processing, which means it has been paid and awaits being processed, pending orders does not even reserve stock.

Closing this as a won't fix. You should be able to attach an email to the pending to cancelled transition with some custom code if you really want this functionality.

**Closed by kloon** 2018-10-29 13:21 UTC
