### ISSUE TITLE
problem setup wizard woo commerce

### ISSUE THREAD

**Issue by lafouine12** [woocommerce/woocommerce#16926] opened 2017-09-25 16:11 UTC
When i launch setup wizard there is a bug. 

403 Forbidden

Permission denied. Our sentries tell us that you should not be here.

Website owner? If you think you have reached this message in error, please contact support.

I tried to relaunch, unistall, re install but nothing work.
I have bug. 

Permission denied. Our sentries tell us that you should not be here.
Website owner? If you think you have reached this message in error, please contact support.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment] 2017-09-25 16:57
No luck to reproduce this issue, sounds like related to your web host or maybe some plugin that you have installed.
I'm closing since the issue template is empty and there is no way to reproduce it.
Thanks.

**Closed by claudiosanches** 2017-09-25 16:57 UTC
