### ISSUE TITLE
Woocommerce Product - Sort by Price issue

### ISSUE THREAD

**Issue by alitezcan** [woocommerce/woocommerce#24183] opened 2019-07-17 12:58 UTC
When selecting the sorting options in Shop Page Sort By Price (ASC or DSC), there is problem with all the variation products.

The products are not sorted properly.

https://tekerleklisandalyefiyatlari.com/urunler/
![hata](https://user-images.githubusercontent.com/52821847/61377258-8540c800-a8ab-11e9-966d-316f3bf02e6b.PNG)

Please help me and fix error :(

**Comment by rodrigoprimo** [comment] 2019-07-17 18:31
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If you believe your problem is happening due to a bug in WooCommerce core, please provide the steps to reproduce the issue on a clean WooCommerce core install (to rule out conflicts with other plugins). In this particular case, a CSV file with the products shown in the screenshot is enough for us to import it on our local installs and try to recreate the same problem you are describing. Closing this issue for now, but I will reopen it once we get the requested information. Thanks.

**Closed by rodrigoprimo** 2019-07-17 18:31 UTC
