### ISSUE TITLE
URGENT - Incorrect Stock Management - URGENT

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#27757] opened 2020-09-23 11:52 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Stocks quantities are not changed when adding or deleting products on an order via the backend. the only way to do it is to create an order, dont save it and leave the status as "pending", add the products, and then save the order. All other ways fail, like creating an order, change the status to "processing", save the order, add a produt - No stock changes happen.
#26642 Changed the way it functions but i dont think this beahavior is intended.

**Expected behavior**
When adding or deleting products via the admin page stock quantities should change if the order status is one that manages stocks (on-hold, processing, completed). If the stock changes when the order is saved or when the additions/deletions are made is irrelevant for this bug reporting.

**Actual behavior**
Stock quantities are never changed when an admin adds or deletes products from an order, regardless of order status, unless in the way i described earlier.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create an Order via the admin page
2. Change the order status to processing, on-hold or completed
3. Click "Save Order"
4. Add a product to the order, stock quantities do not change.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

This is a full nightmare, we will be forced to close our store to correct the stock.
If we try to create an order and save it first, additions or deletions do not change the stock.
If a client, after it orders something, asks us to add a product before shipping, stock changes are not reflected.
I can list a lot of other use cases.

**Comment by vedanshujain** [comment] 2020-09-23 13:19
Closing as its duplicate of #27445, but I was already working on this today and should have a fix soon.

**Closed by vedanshujain** 2020-09-23 13:19 UTC

**Comment by negapo** [comment] 2020-09-23 13:35
@vedanshujain  thanks, this has a tremendous impact on a live store, could you please tell me in what version this was introduced so we can track all erros in the stock?
