### ISSUE TITLE
Only billing postcode is formatted

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#21300] opened 2018-09-08 08:02 UTC
**Describe the bug**
Placing an order _without filling in the shipping_ postcode, using a lowercase postcode, results in a billing postcode that is formatted (removed spaces and all uppercase), but the shipping postcode is left the same as it was entered.

**To Reproduce**
1. Go through checkout
2. Enter only a billing address (I used country: Netherlands, with postcode: **1000 aa**)
3. Place order
4. Resulting order now has 1000AA for the billing address and 1000 aa for the shipping address

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment] 2018-09-10 08:19
@Spreeuw I am not able to reproduce this using the master branch version of WooCommerce. Each time I enter a code such as 8000 aa it gets converted to 8000AA in both billing and shipping address fields http://cld.wthms.co/wyNGqg

Can you try with a master branch copy of WooCommerce or alternatively test with all plugin deactivated and your theme switched to a default one like Twenty Seventeen. I noticed you did say you tested with all plugins deactivated and Storefront but you did not attach your system status report.

In order to further investigate this I will need to have steps that is replicable on my development environment, as it stands now I am not getting the same results and it is working as it should.

Closing, can reopen if there are steps to recreate this on the master branch copy of WooCommerce.

**Closed by kloon** 2018-09-10 08:19 UTC

**Comment by Spreeuw** [comment] 2018-09-10 09:46
Thanks @kloon. I was testing with 3.4.5 release version - this issue appears to be fixed in master indeed!
