### ISSUE TITLE
Getting 401 error placing order via REST API

### ISSUE THREAD

**Issue by Jonofat** [woocommerce/woocommerce#29710] opened 2021-04-17 14:45 UTC
I have generated my consumer key and secret in the WordPress backend and am attaching it to my post request but I still get a 401 error when trying to place the order.

Here is an example

```
   const data = {
      payment_method: "bacs",
      payment_method_title: "Direct Bank Transfer",
      set_paid: true,
      billing: {
        first_name: "Joe",
        last_name: "Soap",
        address_1: "969 Market",
        address_2: "",
        city: "San Francisco",
        state: "CA",
        postcode: "94103",
        country: "US",
        email: "joe@gmail.com",
        phone: "(555) 555-5555",
      },
      shipping: {
        first_name: "Joe",
        last_name: "Soap",
        address_1: "969 Market",
        address_2: "",
        city: "San Francisco",
        state: "CA",
        postcode: "94103",
        country: "US",
      },
      line_items: [
        {
          product_id: 130,
          quantity: 2,
        },
        {
          product_id: 128,
          quantity: 1,
        },
      ],
      shipping_lines: [
        {
          method_id: "flat_rate",
          method_title: "Flat Rate",
          total: "10.00",
        },
      ],
    };

    const response = await axios.post(
      `http://localhost:8888/myapi/wp-json/wc/v3/orders?consumer_key=ck_xxxxxxxx&consumer_secret=cs_xxxxxxx`,
      data
    );
    console.log(response);
```

**Comment by zhongruige** [comment] 2021-04-26 17:43
Hi @Jonofat,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

1. I created a fresh install of WooCommerce 5.2.2 on WordPress 5.7.1
2. I created an API key with read/write permissions
3. I submitted a [Create order](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order) `POST` which went through successfully:

<img width="1018" alt="Screen Shot 2021-04-26 at 11 40 29 AM" src="https://user-images.githubusercontent.com/71906536/116126974-814af800-a684-11eb-89a1-c818ffe02449.png">

Please provide us with more details about the issue which may help us to evaluate it further. 

1. What permissions did you assign to the API key? For example, a `read` permission will return an unauthorized for a `POST` or any other similar `write` endpoint.

<img width="685" alt="Screen Shot 2021-04-26 at 11 39 09 AM" src="https://user-images.githubusercontent.com/71906536/116126843-595b9480-a684-11eb-81bd-fa88f9be65e4.png">

Thank you!

**Comment by Jonofat** [comment] 2021-04-26 17:45
Thanks for your response. I think it was because I was doing on localhost using http. When I used a live server with https it worked. Is there an easy way to get it to work with localhost and http?

**Comment by zhongruige** [comment] 2021-04-26 21:30
I just tested this locally and it worked as expected. I did some research and I have seen some discussion around this issue, for example some folks have needed to added an override to their `.htaccess` file, like so: https://stackoverflow.com/questions/62173852/woocommerce-rest-api-not-working-401-unauthorised

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization}]
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```

Do you also get the same error with basic auth for authorization as well as using the query string auth params when running against localhost?

**Comment by zhongruige** [comment] 2021-05-21 20:59
Hi @Jonofat,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by zhongruige** 2021-05-21 20:59 UTC
Labels: category: can't reproduce, has feedback
