### ISSUE TITLE
WooCommerce 3.6.1 Database Upgrade Causes Duplicate Stripe Charges on WooCommere Subscriptions

### ISSUE THREAD

**Issue by High-Altitude-5280** [woocommerce/woocommerce#23409] opened 2019-04-20 18:41 UTC
**Describe the bug**
WooCommerce 3.6.1 caused us many problems on our production site. It was not stable, we rolled back to WooCommerce version 3.5.7. However, after processing the database upgrade required for WooCommerce 3.6.1 on 4-18-19. After this db upgrade, downgrading back to WooCommerce 3.5.7 now causes all existing WooCommerce Subscription renewals to become duplicated in Stripe. We are using the native Stripe WC Payment Gateway.

Stripe is double charging our subscription renewals for every customer. In the stripe dashboard. Each subscription renewal is associated with two order numbers (for the duplicate charges). The first order number is a valid WooCommerce Order Number. The second associated order number is bogus. There is no record of this order number in WooCommerce nor is there any record of the double billing in WooCommerce. The only record of the double billing we have is within the Stripe Dashboard.

**Steps to Reproduce**
Unfortunately, the only way to see this is to wait for live renewals to be processed by WooCommerce. I have not yet discovered a way to manually reproduce this issue. Time must lapse even on a test order. We must wait for the scheduled renewal to actually occur within WooCommerce.

**Isolating the problem (mark completed items with an [x]):**
- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
5.1.1
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```

### WordPress Environment ###

Home URL: https://www.url-has-been-removed-for-security.com
Site URL: https://www.url-has-been-removed-for-security.com
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.32-78.1-56-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: kMwFsHNn_
Total Database Size: 388.76MB
Database Data Size: 283.59MB
Database Index Size: 105.17MB
kMwFsHNn_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB
kMwFsHNn_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_woocommerce_downloadable_product_permissions: Data: 4.52MB + Index: 12.09MB
kMwFsHNn_woocommerce_order_items: Data: 0.44MB + Index: 0.22MB
kMwFsHNn_woocommerce_order_itemmeta: Data: 5.52MB + Index: 7.03MB
kMwFsHNn_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
kMwFsHNn_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
kMwFsHNn_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
kMwFsHNn_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_woocommerce_payment_tokens: Data: 0.08MB + Index: 0.02MB
kMwFsHNn_woocommerce_payment_tokenmeta: Data: 0.16MB + Index: 0.17MB
kMwFsHNn_woocommerce_log: Data: 0.02MB + Index: 0.02MB
copy_wc_download_log: Data: 0.34MB + Index: 0.34MB
kMwFsHNn_ac_warning_messages: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_commentmeta: Data: 0.19MB + Index: 0.22MB
kMwFsHNn_comments: Data: 8.52MB + Index: 12.13MB
kMwFsHNn_failed_jobs: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_followup_coupons: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_followup_coupon_logs: Data: 1.52MB + Index: 0.36MB
kMwFsHNn_followup_customers: Data: 0.13MB + Index: 0.23MB
kMwFsHNn_followup_customer_carts: Data: 0.30MB + Index: 0.16MB
kMwFsHNn_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_followup_customer_orders: Data: 0.11MB + Index: 0.08MB
kMwFsHNn_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
kMwFsHNn_followup_email_logs: Data: 5.52MB + Index: 5.55MB
kMwFsHNn_followup_email_orders: Data: 87.59MB + Index: 5.72MB
kMwFsHNn_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_followup_email_tracking: Data: 2.52MB + Index: 5.19MB
kMwFsHNn_followup_followup_history: Data: 66.56MB + Index: 0.75MB
kMwFsHNn_followup_order_categories: Data: 0.19MB + Index: 0.30MB
kMwFsHNn_followup_order_items: Data: 0.19MB + Index: 0.34MB
kMwFsHNn_followup_subscribers: Data: 0.09MB + Index: 0.11MB
kMwFsHNn_followup_subscribers_to_lists: Data: 0.13MB + Index: 0.14MB
kMwFsHNn_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_gaplus_login: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_gf_addon_feed: Data: 0.05MB + Index: 0.02MB
kMwFsHNn_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_gf_entry: Data: 0.06MB + Index: 0.03MB
kMwFsHNn_gf_entry_meta: Data: 0.14MB + Index: 0.22MB
kMwFsHNn_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_gf_form: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_gf_form_meta: Data: 0.27MB + Index: 0.00MB
kMwFsHNn_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_gf_form_view: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_itlt_download_logs: Data: 0.06MB + Index: 0.00MB
kMwFsHNn_ld_notifications_delayed_emails: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_learndash_user_activity: Data: 0.06MB + Index: 0.13MB
kMwFsHNn_learndash_user_activity_meta: Data: 0.17MB + Index: 0.20MB
kMwFsHNn_links: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_mcc_synced_posts_relationships: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_mm_conversation: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_mm_status: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_options: Data: 6.52MB + Index: 0.28MB
kMwFsHNn_p2p: Data: 0.02MB + Index: 0.05MB
kMwFsHNn_p2pmeta: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_pdf_stamped_files_tbl: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_pdf_stamping: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_pdf_stamping_temp: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_pmpro_membership_levelmeta: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_popover_ip_cache: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_postmeta: Data: 64.56MB + Index: 30.11MB
kMwFsHNn_posts: Data: 6.52MB + Index: 3.81MB
kMwFsHNn_queue: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_rg_form: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_rg_form_meta: Data: 0.05MB + Index: 0.00MB
kMwFsHNn_rg_form_view: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_rg_lead: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
kMwFsHNn_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
kMwFsHNn_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_site: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_smack_statistics: Data: 0.22MB + Index: 0.00MB
kMwFsHNn_sm_sync: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_temp_woocommerce_downloadable_product_permissions: Data: 4.52MB + Index: 9.58MB
kMwFsHNn_termmeta: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_terms: Data: 0.16MB + Index: 0.17MB
kMwFsHNn_term_relationships: Data: 0.27MB + Index: 0.22MB
kMwFsHNn_term_taxonomy: Data: 0.14MB + Index: 0.19MB
kMwFsHNn_usermeta: Data: 7.52MB + Index: 7.03MB
kMwFsHNn_users: Data: 0.20MB + Index: 0.25MB
kMwFsHNn_user_activity: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_user_activity_log: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_w3dev_banned_logins: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_w3dev_logins_stats: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_w3dev_login_details: Data: 0.13MB + Index: 0.00MB
kMwFsHNn_w3dev_ubu_events: Data: 0.05MB + Index: 0.00MB
kMwFsHNn_wcs_payment_retries: Data: 0.30MB + Index: 0.05MB
kMwFsHNn_wc_download_log: Data: 0.36MB + Index: 0.39MB
kMwFsHNn_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
kMwFsHNn_wc_webhooks: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB
kMwFsHNn_wp_pro_quiz_category: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_wp_pro_quiz_form: Data: 0.02MB + Index: 0.02MB
kMwFsHNn_wp_pro_quiz_lock: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_wp_pro_quiz_master: Data: 0.06MB + Index: 0.00MB
kMwFsHNn_wp_pro_quiz_prerequisite: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_wp_pro_quiz_question: Data: 1.52MB + Index: 0.03MB
kMwFsHNn_wp_pro_quiz_statistic: Data: 0.08MB + Index: 0.00MB
kMwFsHNn_wp_pro_quiz_statistic_ref: Data: 0.02MB + Index: 0.03MB
kMwFsHNn_wp_pro_quiz_template: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_wp_pro_quiz_toplist: Data: 0.02MB + Index: 0.00MB
kMwFsHNn_yoast_seo_links: Data: 0.14MB + Index: 0.05MB
kMwFsHNn_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB

### Post Type Counts ###

achievement-type: 1
aiosrs-schema: 2
amn_exact-metrics: 1
astra_adv_header: 1
astra-advanced-hook: 1
attachment: 304
badgeos-log-entry: 391
bsf-sidebar: 1
canned-response: 18
custom_css: 6
customize_changeset: 8
et_pb_layout: 29
fl-builder-template: 36
follow_up_email: 23
gpages: 5
ht_kb: 19
ld-notification: 4
ld-slack-rbm-feed: 5
nav_menu_item: 19
oembed_cache: 9
page: 33
post: 5
product: 25
product_variation: 10
quiz: 35
revision: 86
scheduled-action: 2187
sfwd-certificates: 1
sfwd-courses: 10
sfwd-lessons: 22
sfwd-question: 174
sfwd-quiz: 32
sfwd-topic: 47
shop_coupon: 4057
shop_order: 2302
shop_order_refund: 14
shop_subscription: 1199
ticket_note: 50
wc_membership_plan: 2
wc_user_membership: 1
wpass_status: 4
zerobs_invoice: 1888
zerobs_quo_template: 1
zerobs_transaction: 1888

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

Gravity Forms: by rocketgenius – 2.4.8
Astra Pro: by Brainstorm Force – 1.8.1
Beaver Builder Plugin (Pro Version): by The Beaver Builder Team – 2.2.2.5
Ultimate Addons for Beaver Builder: by Brainstorm Force – 1.16.4
Removed-For-Security-Reasons Custom Functions: by Removed For Security and Privacy Reasons IT | Developed by: – 2.0
Removed-For-Security-Reasons eBook PDF Stamper: by Removed For Security and Privacy Reasons IT | Developed by:  – 1.0 – Not tested with the active version of WooCommerce
Google Apps Login Premium: by Dan Lester – 3.2.1
Google Profile Avatars: by Dan Lester – 1.4
Gravity Forms Help Scout Add-On: by rocketgenius – 1.5
Gravity Forms Polls Add-On: by Rocketgenius – 3.2
Gravity Forms Slack Add-On: by rocketgenius – 1.8
Gravity Forms Survey Add-On: by rocketgenius – 3.3
LearnDash Course Grid: by LearnDash – 1.5.2
LearnDash LMS - Notifications: by LearnDash – 1.3.0
LearnDash ProPanel: by LearnDash – 2.1.3
LearnDash - Slack: by Real Big Plugins – 1.2.4
LearnDash WooCommerce Integration: by LearnDash – 1.5.0 – Not tested with the active version of WooCommerce
reSmush.it Image Optimizer: by reSmush.it – 0.1.22
Safe SVG: by Daryll Doyle – 1.9.3
SendGrid: by SendGrid – 1.11.8
LearnDash LMS: by LearnDash – 2.6.5
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 2.1.0
Tracking Code Manager: by IntellyWP – 1.11.9
Uncanny LearnDash Toolkit: by Uncanny Owl – 3.0.2
Uncanny LearnDash Toolkit Pro: by Uncanny Owl – 3.1
Removed-For-Security-Reasons WooCommerce Digital Media Tracker: by Removed For Security and Privacy Reasons IT | Developed by:  – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Featured Video: by David Towoju (Figarts) – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by cxThemes – 3.23
Follow-Up Emails: by WooCommerce – 4.8.10
WooCommerce Stripe Gateway: by WooCommerce – 4.1.15
WooCommerce Google Analytics Pro: by SkyVerge – 1.7.1
WooCommerce HelpScout User Data Sync: by  – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Help Scout: by WooCommerce – 1.3.11
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.8.6
WooCommerce Product Reviews Pro: by SkyVerge – 1.12.3
WooCommerce Slack: by WooCommerce – 1.1.11
WooCommerce Smart Coupons: by StoreApps – 4.0.3
WooCommerce Social Login: by SkyVerge – 2.6.3
WooCommerce Subscriptions: by Prospress Inc. – 2.5.3
WooCommerce Xero Integration: by WooCommerce – 1.7.16
WooCommerce: by Automattic – 3.5.7 – 3.6.1 is available
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO Premium: by Team Yoast – 11.0
WP Retina 2x Pro: by Jordy Meow – 5.5.4
Yoast SEO: WooCommerce: by Team Yoast – 11.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3466 - /products/
Cart: #1368 - /cart/
Checkout: #1370 - /checkout/
My account: #1372 - /learner-profile/
Terms and conditions: #29169 - /online-store-tos/

### Theme ###

Name: Removed For Security and Privacy Reasons
Ltd. Corporate

Version: 1.0
Author URL: https://www.url-has-been-removed-for-security.com
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 1.8.1
Parent Theme Author URL: https://wpastra.com/about/
WooCommerce Support: ✔

### Templates ###

Overrides: /Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-cancelled-order.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-failed-order.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-new-order.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-completed-order.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-invoice.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-new-account.php version 3.5.0 is out of date. The core version is 3.5.2
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-note.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-on-hold-order.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-processing-order.php version 3.5.0 is out of date. The core version is 3.5.4
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-refunded-order.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-reset-password.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-addresses.php version 3.2.1 is out of date. The core version is 3.5.4
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-customer-details.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-downloads.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-footer.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-header.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-order-details.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-order-items.php
/Removed-For-Security-Reasons-www/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-styles.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce Google Product Feed fields ###

Product description: Variation description only
fallback to main description (full preferred).

Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Defaults to "Removed-For-Security-Reasons".
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: Pre-populates from product_cat taxonomy.
Global Trade Item Number (GTIN): 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.url-has-been-removed-for-security.com
Subscription Statuses: wc-active: 388
wc-pending-cancel: 50
wc-on-hold: 1
wc-cancelled: 760

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Colorado

### Subscriptions by Payment Gateway ###

other: wc-active: 2
wc-cancelled: 11
wc-pending-cancel: 2
wc-active: 17
wc-cancelled: 509
wc-pending-cancel: 5

Stripe: wc-active: 369
wc-cancelled: 240
wc-on-hold: 1
wc-pending-cancel: 43

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

### Social Login ###

Facebook: ✔ Available
Twitter: Disabled
Google: ✔ Available
Amazon: ✔ Available
Linkedin: Disabled
Paypal: Disabled
Instagram: Disabled
Disqus: Disabled
Yahoo: Disabled
Vkontakte: Disabled

### Action Scheduler ###

Complete: 950
Oldest: 2019-03-20 12:43:22 -0600
Newest: 2019-04-20 12:15:11 -0600

Pending: 1,135
Oldest: 2019-04-20 23:45:03 -0600
Newest: 2099-11-07 10:19:10 -0700

Canceled: 101
Oldest: 2019-04-14 12:06:27 -0600
Newest: 2020-04-18 18:43:27 -0600

In-progress: 0
Oldest: –
Newest: –

Failed: 1
Oldest: 2019-04-19 15:17:36 -0600
Newest: 2019-04-19 15:17:36 -0600
```

**Comment by rrennick** [comment] 2019-04-22 13:06
In the future, I would strongly recommend that you take a full database backup before applying an update. If you need to roll back to the previous version, restore the backup before rolling back WooCommerce or WC extensions.

For the issues with your subscriptions, you can contact WCS support through https://woocommerce.com/contact-us/. 

Can you provide detail for the original issues you had with WC 3.6.1?

**Comment by mikejolley** [comment] 2019-04-24 10:42
There were some reports of some email plugins throwing errors during checkout leading to duplicate orders which could be similar to this reported issue. The only way to know for certain would be to test this without those plugins active (I see a few in the report above). Checking the PHP error logs or WC > Tools > Logs for errors would help confirm this.

I'd suggest doing what @rrennick suggested above; please log an issue via the helpdesk (https://woocommerce.com/contact-us/) so we can assist in identifying the source of the double charges and see those error logs. We won't be able to request access via Github because this is public.

If there are specific 3.6 problems beyond those charges that have not yet been addressed, please submit a new issue with the full details and steps to reproduce.

Marking this one closed as this needs to go via the help desk.

Thanks

**Closed by mikejolley** 2019-04-24 10:42 UTC
Labels: status: needs feedback
