### ISSUE TITLE
I have issue with uploading image and change image on woocomerce category 

### ISSUE THREAD

**Issue by deshrajthakur** [woocommerce/woocommerce#27725] opened 2020-09-21 04:00 UTC
I am unable to click on the upload button after clicking on that button nothing happens 

media-models.min.js?ver=5.5.1:2 Uncaught TypeError: Cannot read property 'defaults' of undefined
    at Object.wp.media (media-models.min.js?ver=5.5.1:2)
    at HTMLButtonElement.<anonymous> (edit-tags.php?taxonomy=product_cat&post_type=product:444)
    at HTMLDocument.dispatch (load-scripts.php?c=0&load[chunk_0]=jquery-core,utils&ver=5.5.1:3)
    at HTMLDocument.r.handle (load-scripts.php?c=0&load[chunk_0]=jquery-core,utils&ver=5.5.1:3)
wp.media @ media-models.min.js?ver=5.5.1:2
(anonymous) @ edit-tags.php?taxonomy=product_cat&post_type=product:444
dispatch @ load-scripts.php?c=0&load[chunk_0]=jquery-core,utils&ver=5.5.1:3
r.handle @ load-scripts.php?c=0&load[chunk_0]=jquery-core,utils&ver=5.5.1:3

**Comment by juliaamosova** [comment] 2020-09-21 20:24
Hi @deshrajthakur,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-09-21 20:24 UTC
