### ISSUE TITLE
Product Background Custom 

### ISSUE THREAD

**Issue by Filipadc** [woocommerce/woocommerce#26872] opened 2020-06-25 16:56 UTC
Hi guys, i need your help in product page for woocommerce.
So i need that the user be able to change the color of background, like in the image that a post.

Is there anyone that can help me on this?

![vinil-color-background](https://user-images.githubusercontent.com/67432999/85764037-2582ac00-b70d-11ea-904f-9a5e13e54583.png)

![vinil-color-background_1](https://user-images.githubusercontent.com/67432999/85764029-23b8e880-b70d-11ea-8567-8c40589b6012.png)

**Comment by juliaamosova** [comment] 2020-06-25 18:14
Hi @Filipadc,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed** 2020-06-25 18:14 UTC
