### ISSUE TITLE
Why related products orderby can't change?

### ISSUE THREAD

**Issue by bilalmalkoc** [woocommerce/woocommerce#26464] opened 2020-05-11 23:28 UTC
I am trying to replace random ordering with post__in. So i tried this filters.

This filter doesn't work.
```
function filter_one( $args ) {
	$args[ 'orderby' ] = 'post__in';

	return $args;
}

add_filter( 'woocommerce_output_related_products_args', 'filter_one' );
```

So i created a new query for related posts, but doesn't work too.
```
function filter_two( $related_posts, $product_id, $args ) {
	$custom_products = get_post_meta( $product_id, 'related_products', true );

	if ( empty( $custom_products ) ) {
		return $related_posts;
	}

	$related_posts = get_posts( array(
		'post_type'      => 'product',
		'post_status'    => 'publish',
		'fields'         => 'ids',
		'posts_per_page' => -1,
		'exclude'        => array( $product_id ),
		'post__in'       => $custom_products,
                'orderby'       => 'post__in',
	) );

	return $related_posts;
}

add_filter( 'woocommerce_related_products', 'filter_two', 10, 3 );
```

This is not a good way but doesn't worok too.
```
function filter_three( $q ) {
	$q->set( 'orderby', 'post__in' );
}

add_action( 'woocommerce_product_query', 'wh_related_products_args' );
```

And tried override `woocommerce_related_products` function but doesn't work too.

Finaly, i tried disable random ordering, but again does't work. And i wonder what is purpose of this filter?
`add_filter( 'woocommerce_product_related_posts_shuffle', '__return_false' );`

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://royalgreen.local
Site address (URL): https://royalgreen.local
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.64.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
Toplam veritabanı boyutu: 20.72MB
Veritabanı veri boyutu: 16.68MB
Veritabanı indis boyutu: 4.04MB
wp_woocommerce_sessions: Veriler: 0.01 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_api_keys: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_attribute_taxonomies: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_downloadable_product_permissions: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_order_items: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_order_itemmeta: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_tax_rates: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_tax_rate_locations: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_shipping_zones: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_shipping_zone_locations: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_shipping_zone_methods: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_payment_tokens: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_payment_tokenmeta: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_woocommerce_log: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_actionscheduler_actions: Veriler: 0.01 MB + Dizin: 0.02 MB + Motor MyISAM
wp_actionscheduler_claims: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_actionscheduler_groups: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
wp_actionscheduler_logs: Veriler: 0.01 MB + Dizin: 0.01 MB + Motor MyISAM
wp_commentmeta: Veriler: 0.15 MB + Dizin: 0.14 MB + Motor MyISAM
wp_comments: Veriler: 1.25 MB + Dizin: 0.45 MB + Motor MyISAM
wp_links: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_options: Veriler: 0.13 MB + Dizin: 0.03 MB + Motor MyISAM
wp_postmeta: Veriler: 9.59 MB + Dizin: 2.47 MB + Motor MyISAM
wp_posts: Veriler: 5.28 MB + Dizin: 0.48 MB + Motor MyISAM
wp_term_relationships: Veriler: 0.07 MB + Dizin: 0.13 MB + Motor MyISAM
wp_term_taxonomy: Veriler: 0.06 MB + Dizin: 0.05 MB + Motor MyISAM
wp_termmeta: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor MyISAM
wp_terms: Veriler: 0.07 MB + Dizin: 0.14 MB + Motor MyISAM
wp_usermeta: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor MyISAM
wp_users: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
wp_wc_admin_note_actions: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_admin_notes: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_category_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_customer_lookup: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
wp_wc_download_log: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_order_coupon_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_order_product_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_order_stats: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_order_tax_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
wp_wc_product_meta_lookup: Veriler: 0.01 MB + Dizin: 0.03 MB + Motor MyISAM
wp_wc_tax_rate_classes: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
wp_wc_webhooks: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM

### Post Type Counts ###

attachment: 1500
nav_menu_item: 70
page: 22
post: 1041
product: 181
product_variation: 2
revision: 5
shop_coupon: 6
shop_order: 1063
shop_order_refund: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Hata mesajları ziyaretçilere gösterilmemelidir.

### Active Plugins (4) ###

AJAX Thumbnail Rebuild: (junkcoder
ristoniinemets) – 1.13

Loco Çeviri: (Tim Whitlock) – 2.3.3
Product Filter for WooCommerce: (7VX LLC
USA CA) – 7.2.9 – Yüklü versiyon WooCommerce 4.1.0 aktif versiyonu ile test edilmemiştir

WooCommerce: (Automattic) – 4.1.0

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

Local by Flywheel Live Link Helper: (Flywheel) – 1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Mağaza giriş sayfası: #6 - /magaza/
Sepet sayfası: #7 - /sepet/
Ödeme sayfası: #8 - /odeme/
Hesabım sayfası: #9 - /hesabim/
Şartlar ve koşullar: ❌ Sayfa ayarlanmamış

### Theme ###

Name: Royal Green
Version: 1.0.0
Author URL: https://wpuzman.com.tr/
Child Theme: ❌ – WooCommerce'i kendinizin oluşturmadığı ana bir temada düzenliyorsanız
yardımcı bir tema kullanmanızı öneririz. Bkz.: Nasıl yardımcı tema oluşturulur?

WooCommerce Support: ✔

### Templates ###

Overrides: royalgreen/woocommerce/cart\mini-cart.php
royalgreen/woocommerce/content-product.php
royalgreen/woocommerce/loop\add-to-cart.php
royalgreen/woocommerce/loop\loop-end.php
royalgreen/woocommerce/loop\loop-start.php
royalgreen/woocommerce/loop\orderby.php
royalgreen/woocommerce/loop\price.php
royalgreen/woocommerce/loop\sale-flash.php
royalgreen/woocommerce/single-product\add-to-cart\simple.php
royalgreen/woocommerce/single-product\add-to-cart\variable.php
royalgreen/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php
royalgreen/woocommerce/single-product\add-to-cart\variation.php
royalgreen/woocommerce/single-product-reviews.php


### Action Scheduler ###

İptal edildi: 1
Oldest: 2020-04-14 10:16:42 +0000
Newest: 2020-04-14 10:16:42 +0000

Tamamla: 31
Oldest: 2020-04-14 10:16:17 +0000
Newest: 2020-05-08 18:27:48 +0000

`
```
</details>

**Comment by Konamiman** [comment] 2020-05-12 08:01
Hi @bilalmalkoc,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

That said, it looks like you might be misunderstanding the meaning of `post__in`. This keyword isn't intended for results ordering, but to query for specific posts when using WP_Query (see here: https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters). Your first example (the `woocommerce_output_related_products_args` filter) works fine if you use `ID` instead of `post__in`, for example.

I am closing this issue for now as it doesn't really seem to be a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by Konamiman** 2020-05-12 08:01 UTC

**Comment by bilalmalkoc** [comment] 2020-05-12 10:06
`'orderby' => 'ID'` corrects ids with smaller numbers (1500, 1400, 1300, ...) And i don't understand why `post__in` should not work. [It](https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters) says :

> Preserve post ID order given in the post__in

And i set 'post__in' => array( __my_post_ids__ ) already.

**Comment by Konamiman** [comment] 2020-05-12 13:33
Hi @bilalmalkoc,

Sorry about the confussion, `post__in` is indeed a valid value for `orderby` when using `WP_Query`.

However, regarding the ordering of related products, that's what I have found.

1. When using the StoreFront theme, `'woocommerce_output_related_products_args'` needs to be assigned a higher priority (as in: `add_filter( 'woocommerce_output_related_products_args', 'my_filter', 999 )`), because otherwise there's another instance of the filter that will remove the `orderby` argument. I don't know if that happens too with the theme that you are using, but I tell you for reference.

2. The order of the product ids is ultimately determined by the `wc_products_array_orderby` function, which runs after `wc_get_related_products` (which is the one that triggers the `woocommerce_related_products` filter). This function accepts only the following values for the orderby argument: `title`, `id`, `date`, `modified`, `menu_order` and `price` (plus `none` as a special case to not modify the original ordering). Any other value will cause the products to be shuffled. Thus, `post__in` won't work when specified in the `woocommerce_output_related_products_args` filter.

3. `woocommerce_product_related_posts_shuffle` runs late in the process, it isn't working for you because by the time that filter runs the product ids have already been shuffled because of what I explained in 2.

I hope that this information is helpful for you, please ask again if something isn't clear.

**Comment by bilalmalkoc** [comment] 2020-05-12 14:27
Thank you for details. Yes i tried filter with `'orderby' => 'ID'` and it works, but not works for `'post__in`'. As i understand there is no way for order by `post__in`.

**Comment by galbaras** [comment] 2020-05-14 03:41
@bilalmalkoc Ordering by `post__in` makes no sense. It's just part of the `where` clause to choose specific posts, not an output column, so you can't order by it.

**Comment by gsim** [comment] 2021-03-03 10:09
@gabaras, I understand what you mean by 'it makes no sense' in the context, but it makes perfect sense in what is wanted, i.e. a way to sort the outpud my a fixed array of id's. It's proving to be rather challenging.

**Comment by galbaras** [comment] 2021-03-04 01:50
If I understand this correctly, the aim is to sort the output according to a predefined sequence of IDs.

For this purpose, you can do this:

1. Reorder your products - this can be done separately by category/tag/attribute
2. Make sure your shop uses the default sorting method (custom ordering + name) - this is done in the customizer
3. Order query your output by `menu_order`

**Comment by gsim** [comment] 2021-03-04 04:41
"Reorder your products - this can be done separately by category/tag/attribute". Yes that is my intention.
After much googling it was only this thread that helped me get something working by doing 2 things.

1. add_filter( 'woocommerce_product_related_posts_shuffle', '__return_false' );
2. Returning the sequence I wanted in the 'woocommerce_related_products' filter.

My understanding of that though it the loop is still running first, which is a waste of time (albeit minimal). That is why I replied to the thread, it would have been just peachy if you could have specified the 'post__in' argument for the sort order in the args. I appreciate it is not a bug though.

**Comment by galbaras** [comment] 2021-03-04 06:38
Again, `posts__in` is a literal list of values, not a column, so it can't be used for ordering the output. The respective column name is `ID`, and we want ordering by `menu_order`.

Didn't know about `woocommerce_product_related_posts_shuffle`. Good catch. This should be a setting, though, because some people don't know PHP.

**Comment by rrennick** [comment] 2021-03-04 18:06
> Again, posts__in is a literal list of values, not a column, so it can't be used for ordering the output. 

Support was added for this. See https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters

**Comment by galbaras** [comment] 2021-03-04 23:03
I stand corrected.

This was closed as a support request, but maybe it isn't? Maybe it's a WordPress bug, though. Has anyone used `post__in` ordering successfully?

**Comment by gsim** [comment] 2021-03-05 06:08
WP_Query does indeed  work with 'post__in' as the 'orderby', and an array of id's as the 'order'. However the 'woocommerce_related_products' filters does not.
This is because you are correct @galbaras , the function 'wc_products_array_orderby' which is called does not have the option of 'post__in' so it defaults to shuffle.

**Comment by galbaras** [comment] 2021-03-05 06:53
Looking at the code again, `filter_one()` in the initial post by @bilalmalkoc should also set `$args['post__in']` to a list of IDs. That should make it work without all the other filters. It's just not enough to change the `orderby` field.

**Comment by gsim** [comment] 2021-03-05 06:57
I did try that, but to no avail. It just gets ignored and sticks to the shuffle.

**Comment by galbaras** [comment] 2021-03-05 07:07
Didn't you say that in combination with a `woocommerce_product_related_posts_shuffle` filter, it worked for you?

**Comment by gsim** [comment] 2021-03-05 07:12
Yes, but I do my own sorting (by another array) in the 'woocommerce_related_products' filter and set the order to 'none' in the 'woocommerce_output_related_products_args' filter. I only set it to 'none' to avoid an unessary usort on the array in 'wc_products_array_orderby'.

**Comment by gsim** [comment] 2021-03-05 07:24
add_filter('woocommerce_output_related_products_args',array($this,'related_products_args'),10,1);
add_filter( 'woocommerce_product_related_posts_shuffle', '__return_false',1 );
function related_products_args($args) {
	$args['orderby']='none';
	return $args;
}
function exclude_related_products($related_products,$product_id,$args) {
	// Sort $related_products by array of predefined id's here.
	return array_diff( $related_products, $args['excluded_ids']);
}

**Comment by gsim** [comment] 2021-03-05 10:08
Ok, let me try that again. This is working as per my final requirement. It's basically just a costom sorting scheme, with specified products from an array in get_options, then randomly adding the rest to the array. i.e. If I want 2 items to show first, in order, I save an array of both id's in update_option.

It is running in a class, hence the calls to $this.

```
function __construct()
{
	add_filter('woocommerce_output_related_products_args',array($this,'related_products_args'),10,1);
	add_filter( 'woocommerce_product_related_posts_shuffle', function(){return false;} );
}
function related_products_args($args)
{
	$args['orderby']='none';
	$args['order']='asc';
	return $args;
}
function exclude_related_products($related_products,$product_id,$args)
{
	$related_products=array_diff($related_products,$args['excluded_ids']);
	shuffle($related_products);
	$showfirst=explode(",",get_option('related_productsordering_meta'));
	$final1=array_diff($related_products,$showfirst);
	$final2=array_merge(array_values($showfirst),array_values($final1));
	return $final2;
}
```
