### ISSUE TITLE
Getting fatal error when calling wc_get_order inside wc_order_statuses filter callback

### ISSUE THREAD

**Issue by smuddin** [woocommerce/woocommerce#13891] opened 2017-04-04 09:10 UTC
## EXPLANATION OF THE ISSUE

I'm using `WC  3.0.0-rc.2` with `WP 4.7.3`.

I'm getting a fatal error, when I try to call `wc_get_order` method inside `wc_order_statuses` filter callback.
`Fatal error:  Maximum function nesting level of '256' reached, aborting!`

In my investigation I've seen it's happening because, WC calls `wc_get_order_statuses` function when `wc_get_order` called. Which eventually falls into an infinite function call loop.

## STEPS TO REPRODUCE THE ISSUE

The following snippet can be used to reproduced the issue.

```
add_filter( 'wc_order_statuses', 'my_filter_wc_order_statuses' );
function my_filter_wc_order_statuses( $order_statuses ) {
	
	$id = 1; // replace with a valid order id
	wc_get_order( $id );
	
	return $order_statuses;
}

$statuses = array( 'wc-pending', 'wc-complete' );
apply_filters( 'wc_order_statuses', $statuses );
```

**Comment by mikejolley** [comment] 2017-04-04 10:27
Confirmed, however beyond removing filters I don't see much room to resolve this. 

I'm puzzled why you'd even ever want to do this though - `wc_order_statuses` has no specific order context. Loading orders within that seems completely pointless.

**Comment by mikejolley** [comment] 2017-04-04 10:56
Tracing it back, the list of valid order statuses is used when an order is read/constructed and the `set_status` method is used. This ensures a read order has a valid status and keeps the data valid.

The filter is needed to add custom statuses. It should not be used to do order reading since it should be independent. Use case: adding a new 'shipped' status.

As such, removing this code which does the validation, or the filter which allows new statuses to be added, is not really an option. I've added a docblock stating where it gets used. 

@claudiosanches do you agree this is #wontfix?

**Comment by mikejolley** [comment] 2017-04-04 11:02
@claudiosanches Alternatively, we can do . no validation until object_read is true. So first read will use whatever value is in the DB.

**Comment by smuddin** [comment] 2017-04-04 11:17
Agree on your point that, it's pointless to load order on that `wc_order_statuses` filter callback. The filter was not intended to do that.

The problem is that, we are using [woocommerce-gateway-klarna](https://github.com/woocommerce/woocommerce-gateway-klarna) plugin. Which had a [similar](https://github.com/woocommerce/woocommerce-gateway-klarna/blob/2.3.2/classes/class-klarna-checkout.php#LC310) method as my given snippet. I think, this is more of a WC issue than the plugin's issue. And also feel that WC should not produce a fatal error on runtime.

Fortunately enough, Klarna plugin author [decided not to use the filter](https://github.com/woocommerce/woocommerce-gateway-klarna/blob/v2.3.3/classes/class-klarna-checkout.php#LC198) to avoid the fatal error in their latest update.

**Comment by mikejolley** [comment] 2017-04-04 11:27
I see, yes that does look like a hack tbh - it's just kicking in on certain screens. A better way would be to detect the screen first, THEN add a filter if needed.

**Comment by mikejolley** [comment] 2017-04-04 11:40
This is the workaround https://github.com/woocommerce/woocommerce/pull/13894

Not sure if we should however, I prefer to validate at all times.. @claudiosanches

**Comment by smuddin** [comment] 2017-04-04 11:46
The workaround does solve the issue 👍

**Closed** 2017-04-04 11:50 UTC

**Comment by mateusneves** [comment] 2019-02-01 19:56
Same problem for me.

**Comment by mateusneves** [comment] 2019-02-01 20:16
My solution is use get_post_meta($order_id)

**Comment by claudiosanches** [comment] 2019-02-04 18:21
@mateusneves for orders this will only cause problems in the future, better prefer our CRUD methods for do it.

**Comment by mateusneves** [comment] 2019-02-05 10:37
> @mateusneves for orders this will only cause problems in the future, better prefer our CRUD methods for do it.

@claudiosanches thaks for the tip, i'm will do that
