### ISSUE TITLE
[GlobalStep - PHP 8 + WooCommerce 4.8 RC 1] "Fatal Error" page is displayed upon creating order from backend with Zero product quantity.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28472] opened 2020-12-02 17:13 UTC
## Bug Description:
"Fatal Error" page is displayed upon creating order from backend with Zero product quantity.

## Environment:
Windows 10, macOS Catalina: v10.15.7 (19H15)
Browser: Chrome(Version 86.0.4240.75 (64-bit))
                 Firefox(Version 82.0)(64-bit)
                 Safari(Version 14.0)(15610.1.28.1.9, 15610)

## Steps To Reproduce:
1. Go to Test site "https://ephemeral-jamosova-20201201.atomicsites.blog/"
1. Sign In with valid credentials.
1. Go to "WooCommerce->Orders"
1. Click on "Add Order"
1. Click on "Add items" button.
1. Add any of the product with zero quantity.
1. Click on "Create" button.
1. Observe that "Fatal Error" page is displayed.

## Actual Result:
"Fatal Error" page is displayed upon creating order from backend with Zero product quantity.

## Expected Result:
Validation error message should be display for creating order from backend with Zero product quantity.

## Artifacts:
[#28472.zip](https://github.com/woocommerce/woocommerce/files/5630900/28472.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://ephemeral-jamosova-20201201.atomicsites.blog
Site address (URL): https://ephemeral-jamosova-20201201.atomicsites.blog
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.2
Log Directory Writable: ✔
WP Version: 5.6-RC1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.0
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 4.70MB
Database Data Size: 2.82MB
Database Index Size: 1.88MB
wp_woocommerce_sessions: Data: 0.19MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.09MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.34MB + Index: 0.36MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 28
customize_changeset: 2
nav_menu_item: 5
page: 7
post: 2
product: 46
product_variation: 90
shop_coupon: 2
shop_order: 30
shop_subscription: 3
wc_membership_plan: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Query Monitor: by John Blackbourn – 3.6.5
Akismet Anti-Spam: by Automattic – 4.1.7
Code Snippets: by Code Snippets Pro – 2.14.0
Creative Mail by Constant Contact: by Constant Contact – 1.2.2 – Installed version not tested with active version of WooCommerce 4.0
Facebook for WooCommerce: by Facebook – 2.2.0
Jetpack by WordPress.com: by Automattic – 9.2
Google Ads & Marketing by Kliken: by Kliken – 1.0.6
Mailchimp for WooCommerce: by Mailchimp – 2.4.7
WooCommerce Bookings: by WooCommerce – 1.15.31
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5
WooCommerce Memberships: by SkyVerge – 1.19.2
WooCommerce Payments: by Automattic – 1.7.0
WooCommerce Product Add-ons: by WooCommerce – 3.2.0
WooCommerce Product Bundles: by SomewhereWarm – 6.6.0
WooCommerce Shipping & Tax: by Automattic – 1.25.3
WooCommerce Subscriptions: by WooCommerce – 3.0.11
WooCommerce: by Automattic – 4.8.0-rc.1

### Inactive Plugins (1) ###

Gutenberg: by Gutenberg Team – 9.4.1

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.0.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: ❌ No published plans

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://ephemeral-jamosova-20201201.atomicsites.blog
Subscription Statuses: wc-active: 3
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 3

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Check payments: products
Cash on delivery: products
PayPal Standard: subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_delayed_change
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ✔ Yes
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders


### Product Bundles ###

Database Version: 6.6.0
Loopback Test: ✔
Template Overrides: –

### Action Scheduler ###

Complete: 94
Oldest: 2020-12-01 19:12:03 +0000
Newest: 2020-12-02 16:41:10 +0000

Pending: 6
Oldest: 2020-12-03 09:57:33 +0000
Newest: 2020-12-03 11:18:09 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-12-02 20:20
Thanks for reporting the issue @gglobalstep! 

It seems that the issue is being caused by WooCommerce Services. I got the following details by email as an Admin of the site:

```
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, WooCommerce Shipping & Tax.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.6-RC1
Current theme: Twenty Twenty-One (version 1.0.0)
Current plugin: WooCommerce Shipping & Tax (version 1.25.3)
PHP version 8.0.0

Error Details
=============
An error of type E_ERROR was caused in line 674 of the file /srv/htdocs/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php. Error message: Uncaught DivisionByZeroError: Division by zero in /srv/htdocs/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php:674
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php(450): WC_Connect_TaxJar_Integration->get_backend_line_items(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(289): WC_Connect_TaxJar_Integration->calculate_backend_totals(214)
#2 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/wc-admin-functions.php(259): do_action('woocommerce_bef...', 214, Array)
#5 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-items.php(54): wc_save_order_items(214, Array)
#6 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(289): WC_Meta_Box_Order_Items::save(214)
#7 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#8 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#9 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(220): do_action('woocommerce_pro...', 214, Object(WP_Post))
#10 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(289): WC_Admin_Meta_Boxes->save_meta_boxes(214, Object(WP_Post))
#11 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#12 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#13 /srv/htdocs/__wp__/wp-includes/post.php(4308): do_action('save_post', 214, Object(WP_Post), true)
#14 /srv/htdocs/__wp__/wp-includes/post.php(4410): wp_insert_post(Array, false, true)
#15 /srv/htdocs/__wp__/wp-admin/includes/post.php(419): wp_update_post(Array)
#16 /srv/htdocs/__wp__/wp-admin/post.php(227): edit_post()
#17 {main}
  thrown

**Comment by tammullen** [comment] 2020-12-02 22:31
Confirming that I found the error no longer appeared after deactivating WooCommerce Shipping & Tax.

**Comment by tammullen** [comment] 2020-12-03 14:31
Closing as this seems related to WooCommerce Shipping & Tax. Created an issue for it in the WooCommerce Services repo
https://github.com/Automattic/woocommerce-services/issues/2274

**Closed by tammullen** 2020-12-03 14:31 UTC
