### ISSUE TITLE
Variable Product: Default Form Values is not matching with the most exact variation. First match is considered.

### ISSUE THREAD

**Issue by asumaran** [woocommerce/woocommerce#29726] opened 2021-04-21 03:25 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

First of all I have the following attributes defined:

<img src="https://user-images.githubusercontent.com/1025173/115490018-dcaf5d00-a222-11eb-8e88-78a83d95a187.png" width="538"/>

My variable product has the following variations:

<img src="https://user-images.githubusercontent.com/1025173/115490586-fe5d1400-a223-11eb-9fc5-a0cfb0d0df0d.png" width="533"/>

```
Regular Price for the "medium - Any color" variation is: $15.00
Regular Price for the "medium - green" is: $25.00
```

When creating a Variable product with the variations like above and also selecting values for "Default Form Values" the **amount** displayed to the user on the **Product's Page** is incorrect.

If there's an exact variation defined that matches with the exact values picked for "Default Form Values" that variation should be considered over "Any {attribute name}...". 

**Expected behavior**
Amount should be `$25.00` since "Default Form Values" is defined to "medium - green".

**Actual behavior**
Amount is `$15.00` because is taking the Regular Price from the "medium - Any color" variation.

**Steps to reproduce the bug**

With only WooCommerce installed:
- Create a variable product with the attributes mentioned above.
- Go to product's page and you'll see the price displayed belongs to the "Medium - Any color" variation even though there's a price for the "medium - green" variation.
<img src="https://user-images.githubusercontent.com/1025173/115491588-d8387380-a225-11eb-94bd-bfbaaf254e40.png" width="343" />

I can confirm the first occurrence is considered first if we move the "medium - green" variation to the top. The amount on the product's page is correct.

<img src="https://user-images.githubusercontent.com/1025173/115492104-c0adba80-a226-11eb-9070-2f6fc175ebb0.png" width="572" />

<img src="https://user-images.githubusercontent.com/1025173/115492189-ef2b9580-a226-11eb-9e2e-37e667c96f7d.png" width="343"/>

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>

```
### WordPress Environment ###

WordPress address (URL): https://ephemeral-asumaran-20210421.atomicsites.blog
Site address (URL): https://ephemeral-asumaran-20210421.atomicsites.blog
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 4.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.16
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.75.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: wp_
Total Database Size: 2.39MB
Database Data Size: 1.01MB
Database Index Size: 1.38MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 3
product_variation: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Jetpack by WordPress.com: by Automattic – 9.6.1
WooCommerce: by Automattic – 5.2.2

### Inactive Plugins (0) ###


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2021-04-21 02:29:49 +0000
Newest: 2021-04-21 02:42:47 +0000


### Status report information ###

Generated at: 2021-04-21 03:18:05 +00:00
```

</details>

**Comment by zhongruige** [comment] 2021-04-29 20:16
Hi @asumaran,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. I tested the above on:

* WordPress 5.7.1
* WooCommerce 5.2.2

Replication steps

* I set up my WooCommerce site and imported the default products, which included the following attributes:

<img width="895" alt="Screen Shot 2021-04-29 at 2 10 49 PM" src="https://user-images.githubusercontent.com/71906536/116612390-b8bfdb80-a8f4-11eb-8fce-8cc02bdfb6c5.png">

* I then created a new variable product with the Color and Size attributes, and created variations for them. I set the default values to Green / Medium and adding two variations, one with the default configuration with a price of `$25.00` and the other with a configuration of Green / Any Size set to `$15.00`.

<img width="832" alt="Screen Shot 2021-04-29 at 2 13 30 PM" src="https://user-images.githubusercontent.com/71906536/116612696-181deb80-a8f5-11eb-980f-8d26c0b2f09e.png">

* When visiting the product page, the default price shown was `$15.00` and not `$25.00` as it should be:

<img width="1585" alt="Screen Shot 2021-04-29 at 2 09 09 PM" src="https://user-images.githubusercontent.com/71906536/116612777-2b30bb80-a8f5-11eb-878f-5dc712660526.png">

* However, when changing the order of the variations to put the default value first, the correct price was shown:

<img width="1204" alt="Screen Shot 2021-04-29 at 2 15 13 PM" src="https://user-images.githubusercontent.com/71906536/116612926-54e9e280-a8f5-11eb-945c-a7cace127391.png">

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by dechov** [comment] 2021-04-30 21:40
Assuming the current ("first match") behavior isn't already intended, it may be worth determining more precisely what the intended behavior ought to be – is it just that "exact" matches should take precedence over "inexact" ones, or that more exact matches should take precedence over less exact ones? And for matches of equal exactness ("any color + medium" vs. "green + any size") should it still fall back on order of variations list?

**Comment by rrennick** [comment] 2023-11-14 20:47
This is effectively a duplicate of #33588. Closing to continue the disucssion on that issue.

**Closed by rrennick** 2023-11-14 20:47 UTC
Labels: type: bug, priority: high, focus: variation [team:Proton], plugin: woocommerce
