### ISSUE TITLE
All sorts off issues after last update,

### ISSUE THREAD

**Issue by EasyCompZLD** [woocommerce/woocommerce#26882] opened 2020-06-26 10:23 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Since the last update;

1. Shopping cart stays empty after adding a product to it (logged out users only)

**Expected behavior**
1. The shopping cart should always add products even when people are logged out.

**Actual behavior**
The shopping cart stays empty 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Go to https://easycompzeeland.nl/winkel and try to add some random product to your cart.
Find out that it says empty cart. if you go to the basket. 

Then create a account, do the same steps and you'll be fine.

**Screenshots**
https://easycompzeeland.nl/media/2020/06/Wooissueooo.mov ( Screen capture even better then a shot)

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>
``
### WordPress Environment ###

WordPress address (URL): https://easycompzeeland.nl
Site address (URL): https://easycompzeeland.nl
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.3.8
PHP Post Max Size: 1 GB
PHP Time Limit: 1200
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.26-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: eczv5_
Totale databasegrootte: 72.45MB
Database datagrootte: 57.12MB
Database index grootte: 15.33MB
eczv5_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
eczv5_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eczv5_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eczv5_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_actionscheduler_actions: Data: 2.02MB + Index: 0.75MB + Engine InnoDB
eczv5_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_actionscheduler_logs: Data: 1.30MB + Index: 0.39MB + Engine InnoDB
eczv5_adsw_ali_meta: Data: 0.19MB + Index: 0.03MB + Engine InnoDB
eczv5_bounced_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_comments: Data: 0.03MB + Index: 0.09MB + Engine InnoDB
eczv5_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
eczv5_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_newsletters: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
eczv5_mailpoet_newsletter_links: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
eczv5_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
eczv5_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
eczv5_mailpoet_scheduled_task_subscribers: Data: 0.28MB + Index: 0.11MB + Engine InnoDB
eczv5_mailpoet_segments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_sending_queues: Data: 3.52MB + Index: 0.03MB + Engine InnoDB
eczv5_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eczv5_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_statistics_newsletters: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
eczv5_mailpoet_statistics_opens: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
eczv5_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eczv5_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eczv5_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_mailpoet_subscribers: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
eczv5_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_options: Data: 6.05MB + Index: 0.23MB + Engine InnoDB
eczv5_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_postmeta: Data: 19.50MB + Index: 8.84MB + Engine InnoDB
eczv5_posts: Data: 12.28MB + Index: 0.84MB + Engine InnoDB
eczv5_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_slides: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
eczv5_terms: Data: 0.28MB + Index: 0.31MB + Engine InnoDB
eczv5_term_relationships: Data: 0.34MB + Index: 0.17MB + Engine InnoDB
eczv5_term_taxonomy: Data: 0.30MB + Index: 0.34MB + Engine InnoDB
eczv5_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
eczv5_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eczv5_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eczv5_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eczv5_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eczv5_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_wc_product_meta_lookup: Data: 0.20MB + Index: 0.48MB + Engine InnoDB
eczv5_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_wpml_mails: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
eczv5_yoast_indexable: Data: 3.52MB + Index: 0.50MB + Engine InnoDB
eczv5_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
eczv5_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eczv5_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eczv5_yoast_seo_links: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
eczv5_yoast_seo_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
user_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1711
booked_appointments: 14
custom_css: 2
customize_changeset: 1
flamingo_contact: 9
flamingo_inbound: 12
mailpoet_page: 1
mc4wp-form: 2
nav_menu_item: 164
oembed_cache: 1
page: 29
portfolio: 22
post: 52
product: 200
product_variation: 1628
revision: 317
services: 19
shop_coupon: 1
shop_order: 9
staticblocks: 2
templatera: 2
vc_grid_item: 25
wpcf7_contact_form: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

WP Hide & Security Enhancer: door Nsp Code – 1.6.0.4
Add-on Contact Form 7 - Mailpoet 3: door Tikweb – 1.3.13
Booked Add-On: Calendar Feeds: door Boxy Studio – 1.1.6
Booked Add-On: Front-End Agents: door Boxy Studio – 1.1.16
Booked Add-On: WooCommerce Payments: door Boxy Studio – 1.5.3 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
Geboekt: door EasyComp Zeeland – 2.3.0 mod 1.0 by templines
Bounce handler mailpoet: door Tikweb – 1.3.20
Contact Form 7: door Takayuki Miyoshi – 5.1.9
Dropship Me: door Vitaly Kukin – 1.0.3.8
e-Boekhouden.nl: door e-Boekhouden.nl – 1.9.3
E-mail Templates: door Damian Logghe – 1.3.1.2
Envato Market: door Envato – 2.0.3
Facebook for WooCommerce: door Facebook – 1.11.4 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
Flamingo: door Takayuki Miyoshi – 2.1.1
Font Icons Loader: door Templines – 2.1 Kaswara mod 23.05.2018
Imagify: door WP Media – 1.9.10
Jetpack door WordPress.com: door Automattic – 8.6.1
WPBakery Page Builder: door Michael M - WPBakery.com – 6.2.0
Kaswara Modern VC Addons: door Templines – 2.1 | Mod 3.8
MailPoet 3 Premium (New): door MailPoet – 3.0.87
MailPoet 3 (New): door MailPoet – 3.47.6
Meta Box: door MetaBox.io – 5.3.1
Mollie Payments for WooCommerce: door Mollie – 5.6.1 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
Nav Menu Roles: door Kathy Darling – 1.10.1
One Click Demo Import: door ProteusThemes – 2.5.2
Permalink Manager Pro: door Maciej Bis – 2.2.8.3 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
Post Types Order: door Nsp Code – 1.9.4.3
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 3.1.3
Slider Revolution: door ThemePunch – 6.1.5
Simple Page Ordering: door Jake Goldman
10up – 2.3.4

Category Order and Taxonomy Terms Order: door Nsp-Code – 1.5.7.2
Theme Plugins: door Templines – 1.0
YellowPencil Pro: door WaspThemes – 7.2.7
WooCommerce iZettle Integration: door BjornTech – 5.0.3 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
WooCommerce Service Fee: door BjornTech – 1.15.1 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
WooCommerce - Sociaal inloggen: door WPWeb – 1.8.8 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
WooCommerce Services: door Automattic – 1.23.2 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
WooCommerce Shipping Tracking: door Lagudi Domenico – 17.5 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
WooCommerce: door Automattic – 4.2.2
WordPress Importer: door wordpressdotorg – 0.7
Yoast SEO Premium: door Team Yoast – 14.1
WP Admin Theme CD: door Martin Jost – 1.6
WP All Import: door Soflyy – 3.5.3
WP Social Post And Widget: door Qamar Sheeraz – 1.5
WP Mail Logging: door MailPoet – 1.9.6
WP Rocket: door WP Media – 3.5.1
WP Tab Widget: door MyThemeShop – 1.2.10
Yoast SEO: Local: door Team Yoast and Arjan Snaterse – 12.7
Yoast SEO: News: door Team Yoast – 12.4.1
Yoast SEO: WooCommerce: door Team Yoast – 12.6.1 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
YITH WooCommerce Customize My Account Page: door YITH – 2.6.2 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2

### Inactive Plugins (15) ###

Advanced Custom Fields Multilingual: door OnTheGoSystems – 1.6.1
Akismet Anti-Spam: door Automattic – 4.1.6
Contact Form 7 Multilingual: door OnTheGoSystems – 1.0.1
Multilingual Tools: door WPML Compatibility Team – 1.2
WooCommerce Gateways Country Limiter: door OnTheGoSystems – 1.4 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
WooCommerce Multilingual: door OnTheGoSystems – 4.9.0 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.2.2
WPML All Import: door OnTheGoSystems – 2.1.1
WPML CMS Nav: door OnTheGoSystems – 1.5.2
WPML Media: door OnTheGoSystems – 2.5.5
WPML Multilingual CMS: door OnTheGoSystems – 4.3.11
WPML Page Builders: door OnTheGoSystems – 1.1.3
WPML Sticky Links: door OnTheGoSystems – 1.5.0
WPML String Translation: door OnTheGoSystems – 3.0.7
WPML Translation Management: door OnTheGoSystems – 2.9.5
Yoast SEO Multilingual: door OnTheGoSystems – 1.0.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

wp-hide-loader.php: door  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Winkelbasis: ❌ Pagina niet ingesteld
Winkelmand: #14891 - /winkelmand/
Afrekenen: #14894 - /afrekenen/
Mijn account: #14896 - /klant-pagina
Algemene voorwaarden: #7 - /algemene-voorwaarden

### Theme ###

Name: fixar
Version: 1.0
Author URL: http://templines.com
Child Theme: ✔
Parent Theme Name: Fixar
Parent Theme Version: 1.3.0
Parent Theme Author URL: http://easycompzeeland.nl
WooCommerce Support: ✔

### Templates ###

Archive Template: Jouw thema heeft een woocommerce.php bestand. Je zal het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: fixar/woocommerce/content-product.php
fixar-child/woocommerce/emails/admin-failed-order.php
fixar-child/woocommerce/emails/customer-on-hold-order.php
fixar/woocommerce/product-searchform.php

### Action Scheduler ###

Afgerond: 2.694
Oldest: 2020-06-12 20:56:48 +0200
Newest: 2020-06-26 12:13:55 +0200

Mislukt: 7
Oldest: –
Newest: –

In afwachting: 1
Oldest: 2020-06-26 12:28:55 +0200
Newest: 2020-06-26 12:28:55 +0200

``

**Comment by tammullen** [comment] 2020-06-30 22:39
Hi @EasyCompZLD 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 
​
I was able to add items to Cart on both your store and my own test store while not logged in.

<img width="846" alt="Screenshot 2020-06-30 at 20 31 18" src="https://user-images.githubusercontent.com/24649833/86169133-0fac2700-bb11-11ea-9562-d1493a8b09ae.png">
<img width="1268" alt="Screenshot 2020-06-30 at 20 30 09" src="https://user-images.githubusercontent.com/24649833/86169135-10dd5400-bb11-11ea-9d43-f9953a04c471.png">

![Screenshot 2020-06-30 at 23 15 06](https://user-images.githubusercontent.com/24649833/86183883-e5676300-bb2a-11ea-8a84-1e3cd0f8c0b4.png)

![Screenshot 2020-06-30 at 23 15 27](https://user-images.githubusercontent.com/24649833/86183886-e8faea00-bb2a-11ea-8b14-4a1fa0da3de7.png)



Please provide us with more details about the issue which may help us to evaluate it further. 
​

**Comment by EasyCompZLD** [comment] 2020-06-30 23:38
Hi there,

We fixed it by removing the cookie url setting from the wp-config file. For some reason it doesn’t like wpml combined with a static cookie adres. 

Regards, 

Met vriendelijke groet, 

	
S.A.C. Abdel Nasser | Algemeen Directeur
T: +31 (0)85 785 10 11
E: Shaady@EasyCompZeeland.nl | W: https://EasyCompZeeland.nl
	
De inhoud van dit bericht is alleen bestemd voor de geadresseerde en kan vertrouwelijke of persoonlijke informatie bevatten. Als u dit bericht onbedoeld heeft ontvangen verzoeken wij u het te vernietigen en de klantenservice, of de medewerker van EasyComp Zeeland direct te informeren. Het is niet toegestaan om een bericht dat niet voor u bestemd is te vermenigvuldigen dan wel te verspreiden. Aan dit bericht inclusief de bijlagen kunnen geen rechten ontleend worden, tenzij schriftelijk anders wordt overeengekomen. EasyComp Zeeland, aanvaardt geen enkele aansprakelijkheid voor schade en/of kosten die voortvloeien uit onvolledige en/of foutieve informatie in e-mailberichten.

**Comment by juliaamosova** [comment] 2020-07-06 21:12
Hi @EasyCompZLD,

Thanks for your follow-up and more details. It looks like the issue is likely on the WPML side of things hence I am closing this thread. Please feel free to comment back in case I missed something.

**Closed by juliaamosova** 2020-07-06 21:12 UTC
Labels: can't reproduce, status: needs feedback
