### ISSUE TITLE
Out of stock grouped product shows Add to Cart button

### ISSUE THREAD

**Issue by haywirephoenix** [woocommerce/woocommerce#27401] opened 2020-08-19 11:41 UTC
**Current:** Grouped product single page still displays Add to Cart button when all products out of stock

**Intended:** Add to Cart button is disabled or hidden

**To reproduce:**
1. Create a Grouped Product, add linked products
2. Set all linked products inventory to Out of Stock
3. Add to Cart button still displays beneath list. Clicking it displays the notification "Please choose a product to add to your cart…"
4. Manually setting the grouped product to Out of Stock doesn't disable the button

**Comment by tammullen** [comment] 2020-08-20 10:57
Hi @haywirephoenix 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot 2020-08-20 at 11 54 34](https://user-images.githubusercontent.com/24649833/90762010-33534880-e2dc-11ea-9db7-8ecdaf503748.png)

Add to cart should be hidden like it is for other product types when they are out of stock.​

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by haydenw** [comment] 2020-12-02 07:41
Hi, this has been fixed along with duplicate issue #27710.

**Comment by roykho** [comment] 2020-12-02 13:56
Closed via https://github.com/woocommerce/woocommerce/pull/28169/commits/ab0ede4603c8e24d9ed04fc2e6fb6ebb40f7a1cc

**Closed by roykho** 2020-12-02 13:56 UTC
Labels: bug, component: product, has pull request, priority: low
