### ISSUE TITLE
Checkout Validation Error (Chrome)

### ISSUE THREAD

**Issue by svenhutchinson** [woocommerce/woocommerce#17404] opened 2017-10-27 08:43 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Checkout on Chrome whilst logged out.
2. Look at First Name field before doing anything (i.e clicking on it)
3. It goes red upon loading the checkout page.

## Expected/actual behavior

When I follow those steps, I see...

![http://cld.wthms.co/qh3Fjj](http://cld.wthms.co/qh3Fjj+) 
Full Size: http://cld.wthms.co/qh3Fjj

I was expecting to see...

![http://cld.wthms.co/TdegVV](http://cld.wthms.co/TdegVV+) 
Full Size: http://cld.wthms.co/TdegVV

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://sventesting.mystagingwebsite.com
Site URL: https://sventesting.mystagingwebsite.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.24
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.56.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.02MB
Database Data Size: 1.08MB
Database Index Size: 0.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.33MB + Index: 0.05MB
wp_postmeta: Data: 0.17MB + Index: 0.11MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 57
customize_changeset: 6
nav_menu_item: 3
page: 6
post: 1
product: 41
product_variation: 6
shop_coupon: 1
shop_order: 7
wc_membership_plan: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment] 2017-10-27 10:55
Hey @svenhutchinson 

Checked this on chrome as you said and can see what is happening (sort of). 

1. When the checkout page loads, focus is given to the first field (you'll notice the cursor flashing in there - I cannot screenshot this).

2. When you click anywhere else, or use the keyboard to tab out, the field loses focus.

3. When fields lose focus, validation is ran. This is a required field so it gets the red styling to indicate it's required.

Thats it :) Looks valid to me. Let me know if I missed something. I tested on several themes and all acted this way.

**Comment by hoffepoffe** [comment] 2017-10-27 13:02
I'm the one who reported this issue, and I think @mikejolley misunderstood it. Of course it turns red if you tab away from the field. The problem is however that it turns red automatically on pageload, without tabbing away (or similar) from the field.

**Comment by mikejolley** [comment] 2017-10-27 14:15
Example URL? As I said, on my example sites it gets focus initially. I didn't click on the field myself.

**Comment by svenhutchinson** [comment] 2017-10-27 14:16
WordPress Environment Details  : 
https://sventesting.mystagingwebsite.com

**Comment by hoffepoffe** [comment] 2017-10-27 14:21
The problem is not getting focus or not (it gets focus, as expected). The problem is that the first name field is outlined red=incorrect when the page has loaded, before the user has clicked och pressed anything. This should of course only happen when the user tabs och clicks away from a mandatory field.

**Comment by svenhutchinson** [comment] 2017-10-27 14:21
Here it is : http://cld.wthms.co/1ACl9L

(as you see it auto-validates as wrong without doing anything on that page)

Doesn't do this in Safari.

**Comment by mikejolley** [comment] 2017-10-27 14:38
@svenhutchinson I see it on yours. Can you stick master/3.2.2 on there for me? This site is running 3.2.0 which is the only diff I can see.

I assume nothing else is installed?

On my install the focus goes to first name and it stays focussed.

On yours, no focus.

**Comment by svenhutchinson** [comment] 2017-10-27 14:50
I was using the one from github 3.3-dev : http://cld.wthms.co/SiTy5A.   Only Storefront and WC installed.

Here it is with the 3.2.2 : http://cld.wthms.co/BlYlOi.  Only Storefront and WC installed.

Sadly it's still doing it.  http://cld.wthms.co/f5R0Cd
(checked it is latest version of Chrome 62.0.3202.75 )

**Comment by mikejolley** [comment] 2017-10-27 15:25
Might be the country and selectWoo dropdowns. Let me check.

**Comment by mikejolley** [comment] 2017-10-27 15:26
Odd, it's intermittent on both.

**Comment by mikejolley** [comment] 2017-10-27 17:01
Should be resolved in https://github.com/woocommerce/woocommerce/pull/17416

**Closed by mikejolley** 2017-10-27 17:01 UTC
Labels: Type: Bug
