### ISSUE TITLE
Woocommerce Vat field

### ISSUE THREAD

**Issue by e-booz** [woocommerce/woocommerce#29165] opened 2021-02-18 12:03 UTC
Good evening, I have a problem with the VAT field of the plugin of Woocommerce, in practice it does not accept VAT codes and my customers cannot place orders, what can I do?
In the settings, the VAT field cannot be changed as it is no longer displayed.

<img width="933" alt="Schermata 2021-02-18 alle 12 58 45" src="https://user-images.githubusercontent.com/79259201/108354098-48585800-71e9-11eb-8c27-1eb6fe7164ca.png">
<img width="1098" alt="Schermata 2021-02-18 alle 13 02 26" src="https://user-images.githubusercontent.com/79259201/108354396-ab49ef00-71e9-11eb-9f46-9a36eca44e7e.png">

**Comment by zhongruige** [comment] 2021-02-18 20:30
Hi @e-booz,

Hope you are doing well. Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

Thank you!

**Comment by e-booz** [comment] 2021-02-19 09:31
`
### WordPress Environment ###

WordPress address (URL): https://www.e-booz.com
Site address (URL): https://www.e-booz.com
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.1
Log Directory Writable: ✔
WP Version: 5.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.33
PHP Post Max Size: 30 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp4c_
Dimensione totale database: 35.44MB
Dimensione dati database: 27.81MB
Dimensione indice database: 7.63MB
wp4c_woocommerce_sessions: Dati: 2.02MB + indice: 0.02MB + motore InnoDB
wp4c_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp4c_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_woocommerce_order_itemmeta: Dati: 0.14MB + indice: 0.16MB + motore InnoDB
wp4c_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp4c_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_actionscheduler_actions: Dati: 2.02MB + indice: 0.73MB + motore InnoDB
wp4c_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_actionscheduler_logs: Dati: 1.02MB + indice: 0.44MB + motore InnoDB
wp4c_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_comments: Dati: 0.09MB + indice: 0.09MB + motore InnoDB
wp4c_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_options: Dati: 6.02MB + indice: 0.56MB + motore InnoDB
wp4c_pmxi_files: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_pmxi_hash: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_pmxi_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_pmxi_images: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_pmxi_imports: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_pmxi_posts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_pmxi_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_postmeta: Dati: 4.06MB + indice: 0.58MB + motore InnoDB
wp4c_posts: Dati: 1.19MB + indice: 0.06MB + motore InnoDB
wp4c_robogallery_cache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_tm_taskmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_tm_tasks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_usermeta: Dati: 0.33MB + indice: 0.30MB + motore InnoDB
wp4c_users: Dati: 0.05MB + indice: 0.05MB + motore InnoDB
wp4c_wc_admin_notes: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp4c_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp4c_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp4c_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_wt_iew_action_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_wt_iew_cron: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_wt_iew_ftp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_wt_iew_mapping_template: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp4c_yoast_indexable: Dati: 0.16MB + indice: 0.11MB + motore InnoDB
wp4c_yoast_indexable_hierarchy: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp4c_yoast_migrations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp4c_yoast_primary_term: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_yoast_seo_links: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp4c_yoast_seo_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgh_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgh_comments: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wpgh_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgh_options: Dati: 0.03MB + indice: 0.02MB + motore InnoDB
wpgh_postmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgh_posts: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpgh_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgh_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgh_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgh_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgh_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgh_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpgo_actionscheduler_actions: Dati: 0.28MB + indice: 0.17MB + motore InnoDB
wpgo_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_actionscheduler_logs: Dati: 0.16MB + indice: 0.13MB + motore InnoDB
wpgo_booking: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_bookingdates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_cmplz_cookiebanners: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_cmplz_cookies: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_cmplz_services: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wpgo_em_bookings: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpgo_em_events: Dati: 0.02MB + indice: 0.14MB + motore InnoDB
wpgo_em_locations: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wpgo_em_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_em_tickets: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_em_tickets_bookings: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_options: Dati: 2.02MB + indice: 0.25MB + motore InnoDB
wpgo_postmeta: Dati: 4.25MB + indice: 0.14MB + motore InnoDB
wpgo_posts: Dati: 1.11MB + indice: 0.06MB + motore InnoDB
wpgo_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_terms: Dati: 0.13MB + indice: 0.16MB + motore InnoDB
wpgo_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_term_taxonomy: Dati: 0.17MB + indice: 0.17MB + motore InnoDB
wpgo_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpgo_wc_admin_notes: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpgo_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpgo_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wpgo_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpgo_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpgo_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpgo_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpgo_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpgo_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wppf_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wppf_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wppf_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wppf_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wppf_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wppf_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wppf_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wppf_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wppf_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wppf_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wppf_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wppf_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wppf_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wppf_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wppf_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wppf_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wppf_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wppf_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB

### Post Type Counts ###

attachment: 77
elementor_library: 2
nav_menu_item: 10
oembed_cache: 9
page: 25
popup: 1
popup_theme: 10
post: 1
product: 8
product_variation: 3
revision: 22
robo_gallery_table: 9
shop_coupon: 21
shop_order: 100
shop_order_refund: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

VaultPress: by Automattic – 2.1.4
Akismet Anti-Spam: by Automattic – 4.1.8
All-in-One WP Migration: by ServMask – 7.36
Click to Chat: by HoliThemes – 3.2.6
Contact Form 7: by Takayuki Miyoshi – 5.3.2
GDPR Cookie Consent: by WebToffee – 2.0.0
Custom Order Numbers per WooCommerce: by Tyche Softwares – 1.2.12
Display PHP Version: by David Gwyer – 1.5
Elementor: by Elementor.com – 3.1.1
Enhanced Media Library: by wpUXsolutions – 2.8.2
Export Media Library: by Mass Edge Inc. – 3.0.1
Facebook for WooCommerce: by Facebook – 2.3.0
Futurio Extra: by FuturioWP – 1.4.3
Futurio PRO: by FuturioWP – 1.5.0
Google XML Sitemaps: by Auctollo – 4.1.1
GTranslate: by Translate AI Multilingual Solutions – 2.8.61
Jetpack by WordPress.com: by Automattic – 9.4
Popup Maker: by Popup Maker – 1.15.0
Robo Gallery: by RoboSoft – 3.0.2
Robo Gallery Key: by RoboSoft – 1.5
WordPress Users & WooCommerce Customers Import Export(BASIC): by WebToffee – 2.0.6
WC Exporter for Danea - Premium: by ilGhera – 1.3.4
WC Importer for Danea: by ilGhera – 1.1.2
Checkout Manager for WooCommerce: by QuadLayers – 5.3.5
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.25
WooCommerce Stripe Gateway: by WooCommerce – 4.8.0
WooCommerce: by Automattic – 5.1.0-beta.1
Yoast SEO: by Team Yoast – 15.8
WP All Import: by Soflyy – 3.5.6
WP Stripe Checkout: by naa986 – 1.1.7

### Inactive Plugins (2) ###

Product CSV Import Export (BASIC): by WebToffee – 1.8.9
WooCommerce Checkout Manager PRO: by QuadLayers – 1.3.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #3019 - /shop/
Carrello: #3021 - /carrello/
Pagamento: #3028 - /check-out/
Il mio account: #3023 - /account/
Termini e condizioni: #3026 - /termini-e-condizioni/

### Theme ###

Name: Futurio
Version: 1.4.0
Author URL: https://futuriowp.com/about/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Archive Template: Il tuo tema ha il file woocommerce.php
non potrai sovrascrivere il template personalizzato woocommerce/archive-product.php poiché woocommerce.php ha priorità su archive-product.php. Questo serve a prevenire problemi di visualizzazione.

Overrides: –

### Action Scheduler ###

Complete: 2.840
Oldest: 2021-01-19 09:45:17 +0000
Newest: 2021-02-19 09:15:44 +0000

Pending: 1
Oldest: 2021-02-19 09:30:44 +0000
Newest: 2021-02-19 09:30:44 +0000


### Status report information ###

Generated at: 2021-02-19 09:29:44 +00:00
`

**Comment by tammullen** [comment] 2021-03-25 22:28
Hi @e-booz 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2021-04-02 19:16
Hi @e-booz,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-04-02 19:16 UTC
Labels: needs feedback
