### ISSUE TITLE
Image Regeneration Leads to Critical PHP Error, Corrupt Media Library

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#23495] opened 2019-04-24 20:24 UTC
**Describe the bug**
Woo's image regeneration feature introduced in 3.3 has had an ongoing issue where after 15-20 thumbnails regenerated, the page becomes filled with a non-descript PHP error and the Media library now has multiple entries for each image with the additional entries having no thumbnail (just gray box).

The bug was discovered running CSV Import Suite but is not related to imports or that plugin, as the bug only occurs during image regen, which can be run w/o CSV Import Suite and causes the same issue. 

While we do not know what causes this issue and realize it's not affecting everyone, we've spent 48 hours with our web host ruling out anything on their end. Additionally, we have an extremely well-resourced VPS with specs that far exceed Woo's requirements. We have no image-related plugins running. This issue occurs on multiple stores we manage, all using different themes. We've seen numerous reports of this bug online but no defined fix for it.

The workaround to this issue is to upload new product images via FTP, disable Woo's thumbnail regen using the recommended function, run an import, image regen doesn't happen but products are properly 'attached' to their main image, and then run Force Regenerate Thumbnails plugin, which works just fine. This leads us to believe the issue lies with the mechanism Woo uses for thumbnail regen.

**To Reproduce**
1. Add new images to the store via FTP or the Media library.
2. Force Woo to Regenerate thumbnails, either via CSV Import Suite or using the WooCommerce Tool option of the same
3. Error begins occurring after roughly 15-20 images.

**Screenshots**
https://youtu.be/XeYQKrm5Z8Y

**Expected behavior**
Image thumbnails should regenerate without incident and the Media Library should appear unchanged as thumbnails of existing images should not add new entries to the library.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://mcgreevygroup.com
Site address (URL): https://mcgreevygroup.com
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.4
PHP Post Max Size: 32 MB
PHP Time Limit: 210
PHP Max Input Vars: 30000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.7
WC Database Prefix: wpa4_
MaxMind GeoIP Database: ✔
Total Database Size: 42.70MB
Database Data Size: 32.46MB
Database Index Size: 10.24MB
wpa4_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wpa4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpa4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpa4_woocommerce_order_items: Data: 0.09MB + Index: 0.02MB
wpa4_woocommerce_order_itemmeta: Data: 0.44MB + Index: 0.34MB
wpa4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpa4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpa4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpa4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpa4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpa4_commentmeta: Data: 0.02MB + Index: 0.03MB
wpa4_comments: Data: 0.20MB + Index: 0.28MB
wpa4_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wpa4_gf_entry: Data: 0.06MB + Index: 0.03MB
wpa4_gf_entry_meta: Data: 0.09MB + Index: 0.09MB
wpa4_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wpa4_gf_form: Data: 0.02MB + Index: 0.00MB
wpa4_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wpa4_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wpa4_gf_form_view: Data: 0.05MB + Index: 0.03MB
wpa4_imagify_files: Data: 0.02MB + Index: 0.08MB
wpa4_imagify_folders: Data: 0.02MB + Index: 0.03MB
wpa4_links: Data: 0.02MB + Index: 0.02MB
wpa4_options: Data: 3.19MB + Index: 0.09MB
wpa4_postmeta: Data: 20.02MB + Index: 7.31MB
wpa4_posts: Data: 5.41MB + Index: 0.47MB
wpa4_rg_form: Data: 0.02MB + Index: 0.00MB
wpa4_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wpa4_rg_form_view: Data: 0.02MB + Index: 0.03MB
wpa4_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wpa4_rg_lead: Data: 0.02MB + Index: 0.03MB
wpa4_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wpa4_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wpa4_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wpa4_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wpa4_termmeta: Data: 0.02MB + Index: 0.03MB
wpa4_terms: Data: 0.02MB + Index: 0.03MB
wpa4_term_relationships: Data: 0.08MB + Index: 0.06MB
wpa4_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpa4_translations: Data: 0.44MB + Index: 0.13MB
wpa4_translations_log: Data: 0.02MB + Index: 0.02MB
wpa4_usermeta: Data: 0.30MB + Index: 0.23MB
wpa4_users: Data: 0.02MB + Index: 0.05MB
wpa4_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpa4_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wpa4_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wpa4_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpa4_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wpa4_woos_search_trends: Data: 0.05MB + Index: 0.02MB
wpa4_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpa4_yoast_seo_meta: Data: 0.22MB + Index: 0.00MB

### Post Type Counts ###

attachment: 306
cs_footer: 1
cs_header: 2
cs_template: 2
global_product_addon: 7
log-update: 15
nav_menu_item: 59
page: 12
plugins-inventory: 52
postman_sent_mail: 250
product: 181
product_variation: 963
scheduled-action: 3
shipping_package: 2
shop_order: 282
shop_order_refund: 21

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

ManageWP - Worker: by GoDaddy – 4.7.7
Gravity Forms: by rocketgenius – 2.4.6.15
Admin Menu Editor Pro: by Janis Elsts – 2.6.3
Akismet Anti-Spam: by Automattic – 4.1.1
Classic Editor: by WordPress Contributors – 1.4
Webcraftic Disable Admin Notices Individually: by Webcraftic  – 1.0.6
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Invisible reCaptcha: by Mihai Chelaru – 1.2.3
Mobile Address Bar Changer: by Anshul Labs – 3.0
My Custom Functions: by Space X-Chimp – 4.38
Post SMTP: by Yehuda Hassine – 1.9.8
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.1.5

Hide SEO Bloat: by SO WP – 3.10.0
Woo Checkout Editor: by Themeco – 2.2.0 – Not tested with the active version of WooCommerce
Tracking Code Manager: by IntellyWP – 1.11.9 – Not tested with the active version of WooCommerce
Transposh Translation Filter: by Team Transposh – 1.0.4
Ultimate Branding: by WPMU DEV – 1.9.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.12.24

WC Password Strength Settings: by Daniel Santoro – 2.0.2 – Not tested with the active version of WooCommerce
Woo Search Box: by Guaven Labs – 2.1.1 – Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping Packages: by WooCommerce – 1.1.4 – Not tested with the active version of WooCommerce
WooCommerce Auto Category Thumbnails: by Shellbot – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Brands: by WooCommerce – 1.6.7 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.2
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by WooCommerce – 1.1.9 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce Google Analytics Pro: by SkyVerge – 1.7.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.10 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.21 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.12 – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.21 – Not tested with the active version of WooCommerce
WooCommerce Tab Manager: by SkyVerge – 1.10.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.14 – Not tested with the active version of WooCommerce
WooCommerce Warranty Requests: by WooCommerce – 1.8.13 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.1
Yoast SEO: by Team Yoast – 11.0 – Not tested with the active version of WooCommerce
WordPress Updates Log: by Sofiane.A – 1.0.1
WP Rocket: by WP Media – 3.3.1.1
Yoast SEO: WooCommerce: by Team Yoast – 10.0 – Not tested with the active version of WooCommerce
YITH WooCommerce Customize My Account Page: by YITH – 2.5.8

### Inactive Plugins (1) ###

Imagify: by WP Media – 1.8.4.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: by ManageWP –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #101 - /shop/
Cart: #2198 - /cart/
Checkout: #2196 - /checkout/
My account: #2199 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Pro
Version: 2.5.5
Author URL: http://theme.co/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: pro/woocommerce/cart/cross-sells.php
pro/woocommerce/loop/loop-end.php
pro/woocommerce/loop/loop-start.php
pro/woocommerce/loop/pagination.php
pro/woocommerce/notices/error.php
pro/woocommerce/notices/notice.php
pro/woocommerce/notices/success.php
pro/woocommerce/single-product/related.php
pro/woocommerce/single-product/tabs/tabs.php
pro/woocommerce/single-product/up-sells.php
pro/woocommerce/single-product-reviews.php version 3.5.0 is out of date. The core version is 3.6.0

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 2
Oldest: 2019-04-17 17:11:44 +0000
Newest: 2019-04-24 17:15:54 +0000

Pending: 1
Oldest: 2019-05-01 17:15:54 +0000
Newest: 2019-05-01 17:15:54 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

</details>

**Comment by claudiosanches** [comment] 2019-04-25 04:15
I was able to reproduce using Product CSV Suite. 

> Error begins occurring after roughly 15-20 images.

I tried with less images too, with only 3 this happens for me.

We'll investigate and include a patch in the next release, thank you for let us know about it and give us a complete report about, very helpful, thank you!

**Comment by claudiosanches** [comment] 2019-04-30 00:09
>Force Woo to Regenerate thumbnails, either via CSV Import Suite or using the WooCommerce Tool option of the same

I tested with WooCommerce's built importer, and WordPress XML importer, but is working just fine, seems like this issue is with Product CSV Suite, since happens in every time I try to import.

Can you check again with the WooCommerce's built importer?
What is the error in the output?

Also, may you try enable WP debug mode. To enable you can add this to your `wp-config.php`:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );
```

This configuration will output all PHP errors into `wp-content/debug.log`, so we can check for any error that may happens while importing.

**Comment by co50** [comment] 2019-04-30 12:46
I cannot check with the built in importer because it would require a completely different import file to build out. But I can tell you that while I didn't get any visual error onscreen, the Media library got corrupted the same way if I import with CSV Import Suite, but leave image rebuild off, and then manually rebuild thumbnails using the built-in WooCommerce tool (found under Woo > Tools menu). So it can't be totally related to CSV Import Suite because the rebuild process used outside of Suite causes the same issue. It just doesn't show all those lines of nonsense while it's working because it's supposed to be a background process.

**Comment by claudiosanches** [comment] 2019-04-30 18:38
> I cannot check with the built in importer because it would require a completely different import file to build out. 

Not really, since we already scan for Product CSV Suite fields.

> the Media library got corrupted the same way if I import with CSV Import Suite, but leave image rebuild off, and then manually rebuild thumbnails using the built-in WooCommerce tool (found under Woo > Tools menu)

Seems like Product CSV Suite is registering images incorrect, that's why this tool causes the same problem.

**Comment by kloon** [comment] 2019-05-02 12:40
Closing this issue as it can only be replicated via the CSV Import Suite extension. The developers are aware of it and working on a fix from their side.

**Closed by kloon** 2019-05-02 12:40 UTC
Labels: bug, status: needs feedback
