### ISSUE TITLE
3.5.0 makes the WP REST API excruciatingly slow or returns a 504 gateway timeout

### ISSUE THREAD

**Issue by arjendejong12** [woocommerce/woocommerce#21634] opened 2018-10-23 19:40 UTC
**Describe the bug**
The REST API of WordPress runs very slow or simply times out after installing the latest version (3.5.0) and upgrading the database. The weird thing is that the WooCommerce REST API is not affected by this; it works fast and normal as you would expect. This is not true for the default WordPress REST API endpoints like posts and pages. Disabling the WooCommerce plugin fixes the slow loading times and time outs. Reverting back to 3.4.7 also fixes this.

**To Reproduce**
1. Install latest WooCommerce version and upgrade database.
2. Make a request to for example wp-json/wp/v2/posts
3. Notice the slow loading times or time outs.

**Expected behavior**
All REST API endpoints should work normally and fast.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://www.101bhv.nl
Site URL: https://www.101bhv.nl
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.1.20-1+0~20180725103315.2+stretch~1.gbpd5b650 - We raden je aan om PHP-versie 7.2 of hoger te gebruiken voor betere prestaties en beveiliging. Hoe je PHP-versie bijwerken
PHP Post Max Size: 25 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.18-MariaDB-10.2.18+maria~stretch
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Totale databasegrootte: 34.56MB
Database datagrootte: 20.13MB
Database index grootte: 14.43MB
wp_woocommerce_sessions: ❌ Tabel bestaat niet
wp_woocommerce_api_keys: ❌ Tabel bestaat niet
wp_woocommerce_attribute_taxonomies: ❌ Tabel bestaat niet
wp_woocommerce_downloadable_product_permissions: ❌ Tabel bestaat niet
wp_woocommerce_order_items: ❌ Tabel bestaat niet
wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.00MB
wp_woocommerce_tax_rates: ❌ Tabel bestaat niet
wp_woocommerce_tax_rate_locations: ❌ Tabel bestaat niet
wp_woocommerce_shipping_zones: ❌ Tabel bestaat niet
wp_woocommerce_shipping_zone_locations: ❌ Tabel bestaat niet
wp_woocommerce_shipping_zone_methods: ❌ Tabel bestaat niet
wp_woocommerce_payment_tokens: ❌ Tabel bestaat niet
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: ❌ Tabel bestaat niet
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.30MB + Index: 0.34MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 4.16MB + Index: 1.05MB
wp_postmeta: Data: 8.48MB + Index: 8.31MB
wp_posts: Data: 2.52MB + Index: 0.66MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 0.19MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 1.50MB + Index: 0.63MB
wp_users: Data: 0.05MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 215
acf-field-group: 13
agenda: 2
attachment: 214
cursussen: 13
klantbeoordelingen: 8
locaties: 22
nav_menu_item: 10
oembed_cache: 2
page: 55
post: 171
product: 12
revision: 347
services: 1
shop_order: 1171
veelgestelde_vragen: 22

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Gravity Forms: door rocketgenius – 2.3.5
JSON Basic Authentication: door WordPress API Team – 0.1
ACF to REST API: door Aires Gonçalves – 3.1.0
Advanced Custom Fields PRO: door Elliot Condon – 5.7.7
Attachment Pages Redirect: door Samuel Aguilera – 1.1
Blogger Importer: door wordpressdotorg – 0.9
Cache All External Scripts: door Gerrit de Heij – 0.7
Custom Post Type UI: door WebDevStudios – 1.6.0
Disable Cart Fragments: door LittleBizzy – 1.1.3 – Niet getest met de actieve versie van WooCommerce
Disable Comments: door Samir Shah – 1.8.0
Duplicator: door Snap Creek – 1.3.1.0
MonsterInsights - eCommerce Addon: door MonsterInsights Team – 7.0.12
MonsterInsights Pro: door MonsterInsights – 7.2.0
HTML Page Sitemap: door  – 1.3.2
Onderhoudsmodus: door Lukas Juhas – 2.4.3
Max Mega Menu: door megamenu.com – 2.5.2
MonsterInsights - EU Compliance: door MonsterInsights Team – 1.0.5
MonsterInsights - Google Optimize Addon: door MonsterInsights Team – 1.1.2
Product Sales Report for WooCommerce: door Potent Plugins – 1.4.8 – Niet getest met de actieve versie van WooCommerce
Redirection: door John Godley – 3.5
Scripts-To-Footer: door Joshua David Nelson – 0.6.3
SearchWP LIKE Terms: door SearchWP
LLC – 2.4.6

SearchWP Live Ajax Search: door Jonathan Christopher – 1.3.1
SearchWP: door SearchWP
LLC – 2.9.16

SVG Support: door Benbodhi – 2.3.15
WooCommerce: door Automattic – 3.5.0
Yoast SEO: door Team Yoast – 9.0.1 – Niet getest met de actieve versie van WooCommerce
WP All Export: door Soflyy – 1.2.1
WP BrowserUpdate: door Marco Steinbrecher – 3.0.3
WP Mail Logging: door Christian Zöller – 1.8.5
WP Rocket: door WP Media – 3.1.4
WP SEO HTML Sitemap: door Magna Technology
LLC – 0.9.6

Smush: door WPMU DEV – 2.8.1
WP-Sweep: door Lester 'GaMerZ' Chan – 1.0.12
WP Migrate DB: door Delicious Brains – 1.0.4
ManageWP - Worker: door ManageWP – 4.6.2
Multisite User Sync: door Shamim – 1.2
Duplicator: door Snap Creek – 1.3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #97 - /winkel/
Winkelmand: #98 - /winkelmand/
Afrekenen: #99 - /afrekenen/
Mijn account: #100 - /mijn-account/
Algemene voorwaarden: #34 - /algemene-voorwaarden/

### Theme ###

Name: MS Recept
Version: 2.0
Author URL: http://www.mediasoep.nl
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Archive Template: Jouw thema heeft een woocommerce.php bestand. Je zal het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: 101bhv/woocommerce/emails/customer-invoice.php versie 3.3.0 is verouderd. De hoofdversie is 3.5.0
101bhv/woocommerce/emails/email-addresses.php
101bhv/woocommerce/emails/email-footer.php
101bhv/woocommerce/emails/email-header.php
101bhv/woocommerce/emails/email-order-details.php
101bhv/woocommerce/emails/email-styles.php
101bhv/woocommerce/myaccount/dashboard.php
101bhv/woocommerce/myaccount/my-orders.php
101bhv/woocommerce/myaccount/orders.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten
`
```
</details>

**Comment by claudiosanches** [comment] 2018-10-23 23:05
Not able to reproduce following the steps you said, also there is some tables with the message "Tabel bestaat niet" not sure the correct translation for it, but seems like those tables are missing... Right?

**Comment by arjendejong12** [comment] 2018-10-23 23:17
Yes, it says table does not exist in Dutch. the funny thing is, the status report in the reverted version (3.4.7) does say that these tables exist.

**Comment by rodrigoprimo** [comment] 2018-10-24 12:53
I was not able to reproduce this as well. I tested on a local copy of WooCommerce.com and a request to `wp-json/wp/v2/posts` took about the same time when the site was running WooCommerce 3.4 and when it was running WooCommerce 3.5.

**Comment by kloon** [comment] 2018-10-29 07:16
Closing, if we have steps to reproduce we can reopen and investigate further.

**Closed by kloon** 2018-10-29 07:16 UTC

**Comment by arjendejong12** [comment] 2018-10-29 09:13
I think it has something to do with with [PR #20011](https://github.com/woocommerce/woocommerce/pull/20011).  When updated to 3.5.0, the php_slow.log shows this when I navigate to any page: 
```
[29-Oct-2018 09:45:43]  [pool wordpress] pid 8245
script_filename = /srv/www/public_html/index.php
[0x00007f1600616dc0] curl_exec() /srv/www/public_html/wp-includes/Requests/Transport/cURL.php:162
[0x00007f1600616d00] request() /srv/www/public_html/wp-includes/class-requests.php:379
[0x00007f1600616c00] request() /srv/www/public_html/wp-includes/class-http.php:370
[0x00007f1600616a70] request() /srv/www/public_html/wp-includes/class-http.php:589
[0x00007f16006169d0] post() /srv/www/public_html/wp-includes/http.php:187
[0x00007f1600616940] wp_remote_post() /srv/www/public_html/wp-content/plugins/wp-smushit/lib/class-wp-smush.php:786
[0x00007f16006167d0] _post() /srv/www/public_html/wp-content/plugins/wp-smushit/lib/class-wp-smush.php:312
[0x00007f16006166c0] do_smushit() /srv/www/public_html/wp-content/plugins/wp-smushit/lib/class-wp-smush.php:509
[0x00007f1600616430] resize_from_meta_data() /srv/www/public_html/wp-content/plugins/wp-smushit/lib/class-wp-smush.php:730
[0x00007f1600616300] smush_image() /srv/www/public_html/wp-includes/class-wp-hook.php:286
[0x00007f1600616220] apply_filters() /srv/www/public_html/wp-includes/plugin.php:203
[0x00007f1600616150] apply_filters() /srv/www/public_html/wp-includes/post.php:5222
[0x00007f16006160b0] wp_update_attachment_metadata() /srv/www/public_html/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php:366
[0x00007f1600615f40] resize_and_return_image() /srv/www/public_html/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php:228
[0x00007f1600615e20] maybe_resize_image() /srv/www/public_html/wp-includes/class-wp-hook.php:286
[0x00007f1600615d40] apply_filters() /srv/www/public_html/wp-includes/plugin.php:203
[0x00007f1600615c50] apply_filters() /srv/www/public_html/wp-includes/media.php:851
[0x00007f1600615b40] wp_get_attachment_image_src() /srv/www/public_html/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php:3537
[0x00007f16006159f0] acf_get_attachment() /srv/www/public_html/wp-content/plugins/advanced-custom-fields-pro/includes/fields/class-acf-field-image.php:348
[0x00007f1600615920] format_value() /srv/www/public_html/wp-includes/class-wp-hook.php:286
```
Disabling WP Smush speeds up the API request a lot, but it still takes a few seconds longer than when I'm on version WC 3.4.7.

**Comment by kloon** [comment] 2018-10-29 09:20
The image regeneration will definitely not fire on each page load, it happens in a event queue and will only fire if you change your theme or update from a certain version of WooCommerce, once it is done running it will not run again.

That said if you think it is the cause then you can disable it with the following filter `add_filter( 'woocommerce_background_image_regeneration', '__return_false' );`

**Comment by arjendejong12** [comment] 2018-10-29 17:52
I found that when I edit line 39 of `class-wc-regenerate-images.php` back to 
```
// Resize WooCommerce images on the fly when browsing site through customizer as to showcase image setting changes in real time.
if ( is_customize_preview() ) {
    add_filter( 'wp_get_attachment_image_src', array( __CLASS__, 'maybe_resize_image' ), 10, 4);
}
```
the API returns to being fast again. It leads me to think I have some corrupted images, but I don't see anything strange in the media library.

**Comment by loicparent** [comment] 2018-11-05 12:55
_Hi @arjendejong12,_

I encounter the same issue.
Thanks for the fix. It Works fine for me too.

**Comment by arjendejong12** [comment] 2018-11-05 12:58
Good to hear I'm not the only one experiencing this.

**Comment by Ewoud** [comment] 2018-11-14 18:53
Same issue here. I am not technical but Siteground confirmed the issue that the plugin is creating massive cpu usage

**Comment by nosilver4u** [comment] 2018-11-16 06:03
Question for the WC devs: what would be the best way to detect that a WC thumbnail regen is running in the background? I need to implement a way to prevent EWWW IO from repeatedly calling the dispatch() method in our own Background/Async classes, but I'm not sure the best way to detect the WC thumbnail regen process.

**Comment by kloon** [comment] 2018-11-16 06:43
You can check the options table for any entries where the option_name starts with `'wp_' . get_current_blog_id() . '_wc_regenerate_images_batch_%'` Might be a bit different for MS, but have a look at the WP_Background_Process::is_queue_empty method to see how it looks up for running batches.

**Comment by nosilver4u** [comment] 2018-11-16 19:57
For anyone experiencing this problem that has EWWW IO installed, you can download the fixes from https://github.com/nosilver4u/ewww-image-optimizer/archive/master.zip
From what I can see, there's not actually any bugs in the WooCommerce process, just in other plugins that hook into wp_generate_attachment_metadata(), like EWWW IO, WP Smush, and possibly others.
