### ISSUE TITLE
Add to cart wrong quantity

### ISSUE THREAD

**Issue by coralienyr** [woocommerce/woocommerce#26425] opened 2020-05-08 13:59 UTC
Hello
I'm trying to install the last update of woocommerce. I have the last version of wordpress. I use Astra Theme (with pro extension).
When I go to the product list page and use the + and - buttons to change the quantity, when I click on the 'Add to cart' button, it always adds 1 quantity (even if I clicked 3 times on the + button). I found the solution by adding
`r['quantity'] = a.parent().find(o('.input-text.qty.text')).val()`
just before 
`o(document.body) .trigger("adding_to_cart", [a, r]), t.data.addToCartHandler.addRequest`

do you know the problem? how can i fix it without having any impact with the next update

**Comment by juliaamosova** [comment] 2020-05-08 15:09
Hi @coralienyr,

Thank you for raising the issue. It looks like there may be a theme or a plugin conflict on your site. 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by helgatheviking** [comment] 2020-05-08 15:34
@coralienyr WooCommerce doesn't support quantity inputs in the loop by default, so the onus is on the theme that's adding this feature to handle it. Or you could add it from your child theme. I wrote this for someone else last week and it might be something you can adapt.

```


function kia_add_quantity_to_loop() {
	global $product;
	if( $product instanceof WC_Product && $product->supports( 'ajax_add_to_cart' ) ) {
		woocommerce_quantity_input();
	}
	
}
add_action( 'woocommerce_after_shop_loop_item', 'kia_add_quantity_to_loop', 9 );

function kia_print_quantity_footer_scripts() {

	if( did_action( 'woocommerce_after_shop_loop' ) ) {
		?>
		<script type="text/javascript">
			jQuery( document ).ready(function($) {
				$('.product .qty').on('change', function() { 
					$(this).closest( '.quantity' ).next( 'a' ).attr( 'data-quantity', $(this).val() );
					console.log( $(this).closest( '.quantity' ).next( 'a' ).attr('data-quantity') );
				});
			});
		</script>
<?php }
}
add_action( 'wp_print_footer_scripts', 'kia_print_quantity_footer_scripts' );
```

**Comment by coralienyr** [comment] 2020-05-08 16:08
> function kia_add_quantity_to_loop() {
> 	global $product;
> 	if( $product instanceof WC_Product && $product->supports( 'ajax_add_to_cart' ) ) {
> 		woocommerce_quantity_input();
> 	}
> 	
> }
> add_action( 'woocommerce_after_shop_loop_item', 'kia_add_quantity_to_loop', 9 );
> 
> function kia_print_quantity_footer_scripts() {
> 
> 	if( did_action( 'woocommerce_after_shop_loop' ) ) {
> 		?>
> 		<script type="text/javascript">
> 			jQuery( document ).ready(function($) {
> 				$('.product .qty').on('change', function() { 
> 					$(this).closest( '.quantity' ).next( 'a' ).attr( 'data-quantity', $(this).val() );
> 					console.log( $(this).closest( '.quantity' ).next( 'a' ).attr('data-quantity') );
> 				});
> 			});
> 		</script>
> <?php }
> }
> add_action( 'wp_print_footer_scripts', 'kia_print_quantity_footer_scripts' );

@helgatheviking thank you it works

**Comment by juliaamosova** [comment] 2020-05-08 16:28
Thanks @helgatheviking! I misunderstood the issue and should have verified it, my bad. @coralienyr glad that it works for you.

I am closing this issue since it is resolved. However, please comment again in case I missed something and we'll take another look.

**Closed by juliaamosova** 2020-05-08 16:28 UTC
Labels: status: needs feedback
