### ISSUE TITLE
Products dissapear from Featured products shortcode when you update any product

### ISSUE THREAD

**Issue by ravimartins** [woocommerce/woocommerce#15421] opened 2017-06-02 15:51 UTC
### EXPLANATION OF THE ISSUE

I have a homepage with 3 shortcodes (recent_products, featured_products and sale_products). When i update any product of my store, recent_products shortcode remains the same, but featured_products and sale_products products dissapear.

However, if i remain only one shortcode in this page, they keep showing up even if i update any product.

### STEPS TO REPRODUCE THE ISSUE

1. Add the 3 mentioned shortcode in a same page
2. Add some products as featured and on sale
3. After that, try to update any update (price, visibility... anything).
4. Go to page and don't see those products

### SYSTEM STATUS

<details>
```
Ambiente do WordPress
URL da página inicial:		https://lumisemijoias.com.br
URL do site:		https://lumisemijoias.com.br
Versão do WooCommerce:		3.0.7
Diretório gravável de registros:		 /opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wc-logs/
Versão do WordPress:		4.7.5
WordPress Multisite:		–
Limite de memória do WordPress:		256 MB
Modo de depuração do WordPress:		–
CRON do WordPress:		
Idioma:		pt_BR
Ambiente do servidor
Informações do servidor:		Apache
Versão do PHP:		7.0.13
Tamanho máximo para post no PHP:		40 MB
Limite de tempo do PHP:		120
Máximo de entrada de variáveis (max input vars) do PHP:		1000
Versão do cURL:		7.45.0, OpenSSL/1.0.2j
SUHOSIN instalado:		–
Versão do MySQL:		5.7.17
Tamanho máximo de upload:		40 MB
O fuso horário padrão é UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Requisição remota do tipo POST:		
Requisição remota do tipo GET:		
Banco de dados
Versão do banco de dados do WooCommerce:		3.0.7
Prefixo do banco de dados	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Banco de dados GeoIP da MaxMind.:		 /opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/GeoIP.dat
Segurança
Conexão segura (HTTPS):		
Esconder erros para visitantes		
Plugins ativados (27)
Akismet Anti-Spam	 	por Automattic – 3.3.2
WP Offload S3 Lite	 	por Delicious Brains – 1.1.6
Amazon Web Services	 	por Delicious Brains – 1.0.2
Autoptimize	 	por Frank Goossens (futtta) – 2.1.0
Contact Form 7	 	por Takayuki Miyoshi – 4.8
GP Premium	 	por Tom Usborne – 1.3
Instagram Feed	 	por Smash Balloon – 1.4.9
Ionicons Official	 	por Ionic – 1.0.0
Jetpack por WordPress.com	 	por Automattic – 4.9
Tradução (Loco)	 	por Tim Whitlock – 2.0.14
Regenerate Thumbnails	 	por Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution	 	por ThemePunch – 5.3.0.2
Page Builder da SiteOrigin	 	por SiteOrigin – 2.5.4
SiteOrigin Widgets Bundle	 	por SiteOrigin – 1.9.1
SSL Insecure Content Fixer	 	por WebAware – 2.4.0
SumoMe	 	por SumoMe – 1.26
Toggle The Title	 	por Avner Komarow – 1.4
Widgets for SiteOrigin	 	por wpinked – 1.3.3
WooCommerce Advanced Free Shipping	 	por Jeroen Sormani – 1.1.1
WooCommerce Correios	 	por Claudio Sanches – 3.4.1
WooCommerce Extra Checkout Fields for Brazil	 	por Claudio Sanches – 3.6.0
WooCommerce Menu Cart	 	por Jeremiah Prummer, Ewout Fernhout – 2.6.0
WooCommerce PagSeguro	 	por Claudio Sanches – 2.12.5
WooCommerce	 	por Automattic – 3.0.7
WP-Mail-SMTP	 	por Callum Macdonald – 0.10.1
WP SES	 	por Sylvain Deaure – 0.7.0
YITH WooCommerce Zoom Magnifier	 	por YITHEMES – 1.2.29
Configurações
API habilitada:		
Forçar SSL:		
Moeda		BRL (R$)
Posição da moeda		left
Separador de milhares		.
Separador decimal		,
Número de casas decimais		2
Taxonomias: Tipos de produto		external (external), grouped (grouped), simple (simple), subscription (subscription), variable (variable), variable subscription (variable-subscription)
Taxonomias: Visibilidade de produto		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Páginas do WooCommerce
Base da loja:		 Página não definida
Carrinho:		#7 - /carrinho/
Finalizar compra:		#8 - /finalizar-compra/
Minha conta:		#9 - /minha-conta/
Tema
Nome:		Lumi GP
Versão:		0.1
URL do autor:		http://edge22.com
Tema filho:		
Nome do tema pai:		GeneratePress
Versão do tema pai:		1.3.46
URL do autor do tema pai:		https://tomusborne.com
Suporte do WooCommerce:		
Modelos
Substituições:	 	–

```
</details>

**Comment by mikejolley** [comment] 2017-06-02 17:54
This means the cache is being updated and no products are matching. This could mean the products were not created properly (perhaps imported?) and so on save, the data is corrected and they are no longer on sale/visible/featured.

It's not happening here - and the combination of shortcodes makes no difference. I suspect if you used just one shortcode the products would still vanish once corrected.

**Comment by mikejolley** [comment] 2017-06-05 09:49
Closing as I'm not able to reproduce with the given steps on a clean install.

**Closed by mikejolley** 2017-06-05 09:49 UTC
