### ISSUE TITLE
BUG wrong Flat Rate - Flat Rate of the first zone with assinged flat rate in region zone list is always taken.

### ISSUE THREAD

**Issue by Arn2014** [woocommerce/woocommerce#26757] opened 2020-06-12 08:13 UTC
**Describe the bug**
In checkout when shipping costs are Flat Rate the rate stays the same even if i change zone and in my case country. I have set different Flat Rates per zone/country. 

Possible cause of the wrong rate:
1: system ALWAYS takes first Flat Rate found in country zone list. 

**To Reproduce**
1. Go to a product and make a test order
2. Go to checkout and fill out a test address in  a different country than your matched zone
3. change the country and address 
3. Look at the shipping Flat Rate, it stays the same 
(backend shipping zone setup has different Flat Rates for different countries..)
4: Look at the rate, and than change the ordered zone list in the backend, so that a different Country with set Flat Rate is at the first position..

5. See error: shipping cost - flat rate does not match rate set to different countries
it always matches the first Flat Rate that it finds in the country/zone list. In other words the Flat Rate of the No. One position in the zone list.

**Expected behavior**
flat rate should change per set zone / country

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://demo.mytestenvitonment.de
Site address (URL): https://demo.mytestenvitonment.de
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

</details>

Hope there is a fix soon..

Thnx

**Comment by tammullen** [comment] 2020-06-12 10:53
Hi @Arn2014 

Thank you for submitting the issue. To help us to evaluate it further can you provide us with details of the all shipping zones you have setup and examples of the countries you are trying with.
A customer will match only with one zone. The shipping zones match from top to bottom in the list and I am trying to determine if one of the zones you have setup is matching to your example address before the zone you intended to match.

**Comment by Arn2014** [comment] 2020-06-12 12:14
Hi Teammullen,
I,ve made some screenshots of the setup of zone liste and the first two zones/countries in the zone list a switch between both in list order reveals the Flat Rate issue..

![Screenshot 2020-06-12 at 14 02 49](https://user-images.githubusercontent.com/7666164/84501182-5519c900-acb6-11ea-94e9-2bd3fd1f73af.png)
![Screenshot 2020-06-12 at 14 03 20](https://user-images.githubusercontent.com/7666164/84501200-5e0a9a80-acb6-11ea-803a-846a1f1b7b4c.png)
![Screenshot 2020-06-12 at 14 03 31](https://user-images.githubusercontent.com/7666164/84501220-6531a880-acb6-11ea-9fd6-8c8c2095fd64.png)

second country Germany / Deutschland
![Screenshot 2020-06-12 at 14 04 06](https://user-images.githubusercontent.com/7666164/84501315-97430a80-acb6-11ea-8546-7736460f612b.png)
![Screenshot 2020-06-12 at 14 04 17](https://user-images.githubusercontent.com/7666164/84501405-c5284f00-acb6-11ea-8380-cf0097471248.png)
![Screenshot 2020-06-12 at 14 04 26](https://user-images.githubusercontent.com/7666164/84501416-c9ed0300-acb6-11ea-915f-a5dd8bf74a33.png)

hope this can help you further in making a test/dev setup..

Best Arn

**Comment by Arn2014** [comment] 2020-06-12 12:16
with this above setup flat rate is always Flat Rate of Belgien (Belgium) because that is on the first position of the zone list..

**Comment by Arn2014** [comment] 2020-07-17 09:46
Please give me some feedback, issue is still present

**Comment by tammullen** [comment] 2021-03-25 20:06
Hi @Arn2014 

Sorry for the delay in replying. This is because for each of your shipping zones you have not selected a Zone Region. 
Please see: https://docs.woocommerce.com/document/setting-up-shipping-zones/

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 20:06 UTC
Labels: has feedback
