### ISSUE TITLE
show "in stock" OR (out_of_stock AND backorder allowed) products at the first of list

### ISSUE THREAD

**Issue by saeed74** [woocommerce/woocommerce#25341] opened 2019-12-31 11:02 UTC
function below in **functions.php** do the job for show "in stock" products at the first of list (in cat and tag pages):
```

<?php
class iWC_Orderby_Stock_Status
{
    public function __construct()
    {
        // Check if WooCommerce is active
        if (in_array('woocommerce/woocommerce.php', apply_filters('active_plugins', get_option('active_plugins')))) {
            add_filter('posts_clauses', array($this, 'order_by_stock_status'), 2000);
        }
    }
    public function order_by_stock_status($posts_clauses)
    {
        global $wpdb;
        if (is_woocommerce() && (is_shop() || is_product_category() || is_product_tag())) {
            $posts_clauses['join'] .= " INNER JOIN $wpdb->postmeta istockstatus ON ($wpdb->posts.ID = istockstatus.post_id) ";
            $posts_clauses['orderby'] = " istockstatus.meta_value ASC, " . $posts_clauses['orderby'];
            $posts_clauses['where'] = " AND istockstatus.meta_key = '_stock_status' AND istockstatus.meta_value <> '' " . $posts_clauses['where'];
        }
        return $posts_clauses;
    }
}
new iWC_Orderby_Stock_Status;
?>


```
above code showing out of stock "backorder not allowed" and "backorder allowed" products also at the end of list.
BUT I want "out of stock - backorder allowed" products be just like "in_stock" products.
I want backorder allowed products consider as instock products so show at first of list. 

(for example order by price in category list. so "in stock" and "back order allowed" products will order by price at first of list and "not in stock no backorder" products show at the end of list.)

**Comment by juliaamosova** [comment] 2020-01-15 11:17
Hi @saeed74,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a dev support request.

I recommend you make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/) to see if others can help with providing the right code snippet for what you are trying to accomplish. 

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-01-15 11:17 UTC

**Comment by sajjee68** [comment] 2022-03-09 12:07
hi when using this code get the below notice on single product page:
"Trying to get property 'post_type' of non-object"
