### ISSUE TITLE
extra_rules_top doesn't use pagination_base at main shop page

### ISSUE THREAD

**Issue by odie2** [woocommerce/woocommerce#24871] opened 2019-10-19 08:06 UTC
**Describe the bug**
I am using custom plugin for translating `pagination_base`, `search_base` and `author_base` from `$wp_rewrite` into page language (Polish in my case). I put main shop page under `/sklep/` and noticed navigation there doesn't work (when it is fine at categories). Simply `/sklep/strona/3/` wasn't attached to any URL rewrite as of static `$wp_rewrite->extra_rules_top['sklep/page/([0-9]{1,})/?$']`.

**To Reproduce**
1. Change `$wp_rewrite->pagination_base = 'somethingElseThanPage'`
2. You can not access pages >= 2 on main shop page.

**Expected behavior**
The rule `$wp_rewrite->extra_rules_top['sklep/page/([0-9]{1,})/?$']` is using `$wp_rewrite->pagination_base`.

**Temporary solution**
```
if ( isset( $wp_rewrite->extra_rules_top['sklep/page/([0-9]{1,})/?$'] ) ) {
	$wp_rewrite->extra_rules_top['sklep/'. $wp_rewrite->pagination_base .'/([0-9]{1,})/?$'] = $wp_rewrite->extra_rules_top['sklep/page/([0-9]{1,})/?$'];
	unset( $wp_rewrite->extra_rules_top['sklep/page/([0-9]{1,})/?$'] );
}
```

**Comment by claudiosanches** [comment] 2019-10-24 07:38
Please be more detailed in your steps to reproduce, not enough steps for me to reproduce it.
Like I have no idea when you are changing the `pagination_base`, is on init? After WooCommerce is initialized? When?

**Comment by odie2** [comment] 2019-10-24 12:31
Sorry, forgot mention action.

`add_action( 'init', 'maciej_url_base', 100 );`

Worthy mentioning is also that `pagination_base` is finely changed on categories, search etc. Just main page is wrong.

**Comment by claudiosanches** [comment] 2019-10-25 11:50
Have you tried with a different priority? Like using `5`?

**Comment by odie2** [comment] 2019-10-28 09:34
When using lower than 11, it won't change base anywhere - both links in pagination and entered pages. All stays original.

When using 11+ all links are fine, but the bug still occurs, entering main shop page with changed url will result in empty page. Other paginated listings are fine.

**Comment by tammullen** [comment] 2021-03-25 19:55
Hi @odie2 ,

Sorry for the delay in replying.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 19:55 UTC
Labels: has feedback

**Comment by robizzt** [comment] 2021-06-09 08:08
@odie2 

Great idea for solution. I just changed it a little bit, so it gets automatically shop slug, insted of writing it directly in code.

```
		$shop_slug = get_post_field('post_name', get_option('woocommerce_shop_page_id'));
		if (isset($wp_rewrite->extra_rules_top[$shop_slug.'/page/([0-9]{1,})/?$'])) {
			$wp_rewrite->extra_rules_top[$shop_slug.'/'.$wp_rewrite->pagination_base .'/([0-9]{1,})/?$'] = $wp_rewrite->extra_rules_top[$shop_slug.'/page/([0-9]{1,})/?$'];
			unset($wp_rewrite->extra_rules_top[$shop_slug.'/page/([0-9]{1,})/?$']);
		}
```
