### ISSUE TITLE
Order Progress and Product Screen Formatting Errors on Chrome so they become unreadable (but not on firefox)

### ISSUE THREAD

**Issue by arooni** [woocommerce/woocommerce#25780] opened 2020-02-27 23:56 UTC
**Describe the bug**
Originally opened issue #23826 but dev couldn't reproduce.  Hoping to provide more info this time as this bug pretty much makes woocommerce unusable for me.
**To Reproduce**
0.  Ensure you're running latest woocommerce + wordpress versions
1. Disable all plugins except for woocommerce
2. Login to order status screen using Chrome on ubuntu Version 80.0.3987.122 (Official Build) (64-bit).  By the way Firefox 72.0.2 (64-bit) renders this screen just fine.  Thinking that this might be a chrome plugin issue, I opened the page on an incognito window (with no extensions enabled) and it still did the same thing.
3. See garbled text to the point of being completely unusable. 
4. Go to products screen.  See garbled text but it is still usable.  

I think I figured out what the issue is.  There is a css class that is called 'widefat.'  When it is removed, the page looks like the last screenshot.  When it is not it looks like the rest.  What's weird is that firefox can display the page iwth widefat enabled and it looks fine.   

**Screenshots**
![Screenshot from 2020-02-27 17-53-17](https://user-images.githubusercontent.com/556667/75497520-1a4f8780-598a-11ea-8d02-9088207d388c.png)
![Screenshot from 2020-02-27 17-17-42](https://user-images.githubusercontent.com/556667/75497433-d8bedc80-5989-11ea-86e2-babadf168a8d.png)
![Screenshot from 2020-02-27 18-03-09](https://user-images.githubusercontent.com/556667/75497956-74048180-598b-11ea-8dc6-de27d4f5c18e.png)
![Screenshot from 2020-02-27 18-11-15](https://user-images.githubusercontent.com/556667/75498400-ae225300-598c-11ea-92f7-3351b733bc1e.png)
![Screenshot from 2020-02-27 18-14-32](https://user-images.githubusercontent.com/556667/75498580-2a1c9b00-598d-11ea-9ac8-efd1dd079430.png)
![Screenshot from 2020-02-27 18-15-11](https://user-images.githubusercontent.com/556667/75498590-2f79e580-598d-11ea-8b59-b82ce9ce529b.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```

System report
```
`
### WordPress Environment ###

WordPress address (URL): https://www.magicpresspass.com
Site address (URL): https://www.magicpresspass.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.8
PHP Version: 7.0.33-0ubuntu0.16.04.12 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.29-0ubuntu0.16.04.1
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
Total Database Size: 16.29MB
Database Data Size: 14.34MB
Database Index Size: 1.95MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB + Engine
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_em_modals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_em_modal_metas: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_em_themes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_em_theme_metas: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fca_eoi_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 5.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailjet_wc_abandoned_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailjet_wc_abandoned_cart_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailjet_wc_guests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.05MB + Index: 0.16MB + Engine InnoDB
wp_phppc_functions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_popup_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_popup_manager_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 0.44MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 1.45MB + Index: 0.06MB + Engine InnoDB
wp_sp_email_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stb_styles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 106
jetpack_migration: 2
mc4wp-form: 1
page: 14
post: 1
product: 2
revision: 88
scheduled-action: 1
shop_coupon: 4
shop_order: 14
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.9.2

### Inactive Plugins (42) ###

AffiliateWP: by AffiliateWP
LLC – 2.1.15

AffiliateWP - Affiliate Area Shortcodes: by AffiliateWP
LLC – 1.1.7

AffiliateWP - Affiliate Area Tabs: by Sandhills Development
LLC – 1.2.8

AffiliateWP - Affiliate Info: by AffiliateWP
LLC – 1.0.5

AffiliateWP - Affiliate Product Rates: by Pippin Williamson and Andrew Munro – 1.0.5.1
AffiliateWP - Allowed Products: by AffiliateWP
LLC – 1.1.2

AffiliateWP - Allow Own Referrals: by AffiliateWP
LLC – 1.0.2

AffiliateWP - Checkout Referrals: by Sandhills Development
LLC – 1.0.8

AffiliateWP - Force Pending Referrals: by AffiliateWP – 1.0
AffiliateWP - Leaderboard: by Pippin Williamson and Andrew Munro – 1.0.2
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.5
AffiliateWP - Pushover Notifications: by Chris Klosowski – 1.0.2
AffiliateWP - Show Affiliate Coupons: by AffiliateWP – 1.0.7
AffiliateWP - Sign Up Bonus: by Pippin Williamson and Andrew Munro – 1.1
AffiliateWP - WooCommerce Redirect Affiliates: by AffiliateWP – 1.0 – Not tested with the active version of WooCommerce
Analytify - Google Analytics Dashboard: by Analytify – 3.0.0
Disable Comments: by Samir Shah – 1.10.2
EWWW Image Optimizer: by Exactly WWW – 5.2.1
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 6.0.2
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.2 – Not tested with the active version of WooCommerce
Health Check & Troubleshooting: by The WordPress.org community – 1.4.2
Insert Headers and Footers: by WPBeginner – 1.4.5
iThemes Security: by iThemes – 7.6.1
Kadence Toolkit: by Kadence WP – 4.9.5
Lazy Load for Videos: by Kevin Weber – 2.8.6
MailChimp Forms by MailMunch: by MailMunch – 3.1.4
Mailjet for WordPress: by Mailjet SAS – 5.2.1
MainWP Child: by MainWP – 4.0.7
MC4WP: Mailchimp for WordPress: by ibericode – 4.7.5
PHP Compatibility Checker: by WP Engine – 1.5.0
Preview E-mails for WooCommerce: by Digamber Pradhan – 1.6.3
Query Monitor: by John Blackbourn – 3.5.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Save with keyboard: by Mattia Trapani (zupolgec)
Ron Valstar (sjeiti) – 3.0.2

Theme Check: by Otto42
pross – 20190801.1

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.22

W3 Total Cache: by BoldGrid – 0.13.1
WebP Express: by Bjørn Rosell – 0.17.3
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.1.2 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.2
wpautop-control: by Rowan Rodrik van der Molen
Jesse Jacobsen <jmatjac@gmail.com>. – 1.6

Yoast SEO: by Team Yoast – 13.1

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.6.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #182 - /terms/

### Theme ###

Name: Virtue Child
Version: 2.6.0
Author URL: http://kadencethemes.com/
Child Theme: ✔
Parent Theme Name: Virtue
Parent Theme Version: 3.3.9
Parent Theme Author URL: https://kadencewp.com/
WooCommerce Support: ✔

### Templates ###

Overrides: virtue/woocommerce/archive-product.php
virtue/woocommerce/content-product.php
virtue/woocommerce/content-product_cat.php
virtue/woocommerce/content-single-product.php
virtue-child/woocommerce/emails/customer-processing-order.php
virtue/woocommerce/loop/loop-end.php
virtue/woocommerce/loop/loop-start.php
virtue/woocommerce/loop/price.php
virtue/woocommerce/loop/rating.php
virtue/woocommerce/loop/sale-flash.php
virtue/woocommerce/single-product/add-to-cart/external.php
virtue/woocommerce/single-product/add-to-cart/grouped.php
virtue/woocommerce/single-product/add-to-cart/simple.php
virtue/woocommerce/single-product/add-to-cart/variable.php
virtue/woocommerce/single-product/price.php
virtue/woocommerce/single-product/product-image.php
virtue/woocommerce/single-product/product-thumbnails.php
virtue/woocommerce/single-product/sale-flash.php
virtue-child/woocommerce/single-product.php
virtue/woocommerce/taxonomy-product_cat.php
virtue/woocommerce/taxonomy-product_tag.php


### Action Scheduler ###

Complete: 1
Oldest: 2020-02-27 23:16:24 +0000
Newest: 2020-02-27 23:16:24 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

```
</details>

**Comment by juliaamosova** [comment] 2020-02-28 15:59
Hi @arooni 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

All Products view:

<img width="1440" alt="Screen Shot 2020-02-28 at 10 49 35 AM" src="https://user-images.githubusercontent.com/19143190/75563767-e3748280-5a18-11ea-962c-2c9eb52a4353.png">

All Orders view:

![orders](https://user-images.githubusercontent.com/19143190/75563821-fbe49d00-5a18-11ea-885a-1b7cee9013bc.jpg)

I want to say it is caused by the 3rd party plugin but you mentioned that you tested with only WooCommervce active. 

Do you have a chance to try to reproduce it on a brand new install? Perhaps a local test site will work. 

On my end, I have many test sites and they all look as expected (with different combinations of plugins). I tested with Chrome 80.

**Comment by juliaamosova** [comment] 2020-03-10 21:28
Noting here that I saw something similar on my end today:

<img width="1440" alt="Screen Shot 2020-03-10 at 4 15 30 PM" src="https://user-images.githubusercontent.com/19143190/76360939-55d84300-62f4-11ea-8c28-367f8f300bd3.png">

<img width="1439" alt="Screen Shot 2020-03-10 at 4 15 45 PM" src="https://user-images.githubusercontent.com/19143190/76360952-5a9cf700-62f4-11ea-9acf-fc6aafaf4eae.png">

On my site, it was caused by a combination of [WooCommerce Wholesale Prices](https://wordpress.org/plugins/woocommerce-wholesale-prices/) and [Facebook for WooCommerce](https://docs.woocommerce.com/document/facebook-for-woocommerce/) plugins. As soon as I deactivated them, everything went back to normal.

**Comment by juliaamosova** [comment] 2020-03-20 16:50
@arooni I am going to close this issue as it can be easily reproduced. I will keep an eye on it though so please add comments in case you find something useful related to it.

**Closed by juliaamosova** 2020-03-20 16:50 UTC
Labels: can't reproduce, status: needs feedback
