### ISSUE TITLE
 Product variable does not update when ordering

### ISSUE THREAD

**Issue by Dodieza** [woocommerce/woocommerce#27938] opened 2020-10-13 07:21 UTC
Hello,
Since updating WooCommerce, I have a bug with updating inventory.
When my customer purchases a variable product, the stock does not update in the inventory.
It works for a simple product but not for a variable product.
I have to do it by hand for each item during each order. 
Can someone help me please ?
Thank you

**Comment by juliaamosova** [comment] 2020-12-04 20:54
Hi @Dodieza,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. 

Please specify if you have stock enabled on the parent level or on the variation itself?

**Parent level:**

![parent](https://user-images.githubusercontent.com/19143190/101213823-ffacec00-3648-11eb-8ba5-86614a18bba7.jpg)

**Variation:**

![child](https://user-images.githubusercontent.com/19143190/101213830-0471a000-3649-11eb-9002-d306df47bce7.jpg)

Please provide us with the information requested so we could take a look further.

**Comment by Dodieza** [comment] 2020-12-04 21:11
The stock is on the variable itself not the parent level.
It was the same before the big update of this year and it worked perfectly.
I dont understand why its a problem now.
I dont have this problem with a sample product.

Thank you




Le ven. 4 déc. 2020 à 21:55, Julia Amosova <notifications@github.com> a
écrit :

**Comment by tammullen** [comment] 2021-03-25 21:58
Hi @Dodieza 

The number of details you provided is not enough for us to work with and identify what could be going on.

Please provide us with steps to reproduce the issue on our end. 

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by juliaamosova** [comment] 2021-04-02 19:22
Hi @Dodieza,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-04-02 19:22 UTC
Labels: needs feedback
