### ISSUE TITLE
Checkout is Slow

### ISSUE THREAD

**Issue by jonata221** [woocommerce/woocommerce#26808] opened 2020-06-18 12:47 UTC
the finalization of the purchase is taking from 15 to 20 seconds, I contacted my hosting and they will notify me that they are seeing an error logboek from the website "database deadlocks".
Deze logs zijn te vinden in de map op je SFTP-account,  /logs/on-shop.nl-error.log. Every day gets its own error log, up to 7 days back.

they believe that this is generating conflict and making the checkout takes 15 to 20 seconds

they advised me to contact WordPress and / or WooCommerce support and share the error log

**Comment by tammullen** [comment] 2020-06-18 14:48
Hi @jonata221 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​

If you confirm the bug, please provide us with clear steps to reproduce it, all the other information we ask for in the bug template as well as any error details.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-06-18 14:48 UTC
