### ISSUE TITLE
Customer can check out although mandatory field "Country" is not given

### ISSUE THREAD

**Issue by gwegner** [woocommerce/woocommerce#27521] opened 2020-08-29 13:06 UTC
Tested with 4.4.1
A customer can check out even if he omits the mandatory field "Country".

**Describe the bug**
Put a product in the cart, checkout. Enter all data just leave the Country field blank.
There will be no error and the order goes through, although no country is provided and "Country" is marked as mandatory field with an asterisk.

**Expected behavior**
An error message should appear, making clear that "Country" is a mandatory field.

**Actual behavior**
The order goes though, in the backend the Country fields for Shipping and Billing Address will have the entry "default". 
Any invoice gets the wrong "default" string also which violates tax laws in many countries.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Make an order
2. Leave Country blank
3. Submit the order
4. Check the backend.

**WordPress Environment**
<details>
### WordPress Environment ###

WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.21
PHP Post Max Size: 200 MB
PHP Time Limit: 900
PHP Max Input Vars: 20000
cURL Version: 7.61.1
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_lrt_
Total Database Size: 1056.11MB
Database Data Size: 803.13MB
Database Index Size: 252.98MB
wp_lrt_woocommerce_sessions: Data: 4.02MB + Index: 0.13MB + Engine InnoDB
wp_lrt_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_woocommerce_downloadable_product_permissions: Data: 1.49MB + Index: 1.50MB + Engine MyISAM
wp_lrt_woocommerce_order_items: Data: 3.21MB + Index: 1.57MB + Engine MyISAM
wp_lrt_woocommerce_order_itemmeta: Data: 21.59MB + Index: 13.67MB + Engine MyISAM
wp_lrt_woocommerce_tax_rates: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_lrt_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lrt_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_actionscheduler_actions: Data: 0.45MB + Index: 0.50MB + Engine InnoDB
wp_lrt_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_actionscheduler_logs: Data: 0.36MB + Index: 0.23MB + Engine InnoDB
wp_lrt_affiliates_banners_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_clickthroughs_tbl: Data: 38.12MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_leads_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_payouts_tbl: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_relations_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_sales_tbl: Data: 0.27MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_tbl: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_lrt_affiliates_user_link_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_commentmeta: Data: 31.34MB + Index: 16.78MB + Engine MyISAM
wp_lrt_comments: Data: 131.80MB + Index: 23.24MB + Engine MyISAM
wp_lrt_dlm_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_dlm_order_customer: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_dlm_order_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_dlm_order_transaction: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_dlm_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_download_log: Data: 192.73MB + Index: 20.55MB + Engine InnoDB
wp_lrt_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_icl_languages_translations: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_lrt_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_strings: Data: 5.52MB + Index: 6.89MB + Engine InnoDB
wp_lrt_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_string_pages: Data: 5.52MB + Index: 7.03MB + Engine InnoDB
wp_lrt_icl_string_positions: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_lrt_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_string_translations: Data: 3.52MB + Index: 1.89MB + Engine InnoDB
wp_lrt_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_translate: Data: 7.52MB + Index: 0.09MB + Engine InnoDB
wp_lrt_icl_translate_job: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_translations: Data: 7.52MB + Index: 14.06MB + Engine InnoDB
wp_lrt_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_translation_status: Data: 2.52MB + Index: 0.02MB + Engine InnoDB
wp_lrt_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_newsletter: Data: 4.52MB + Index: 1.75MB + Engine InnoDB
wp_lrt_newsletter_emails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_newsletter_sent: Data: 9.86MB + Index: 14.80MB + Engine MyISAM
wp_lrt_newsletter_stats: Data: 40.55MB + Index: 16.03MB + Engine InnoDB
wp_lrt_newsletter_user_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_options: Data: 6.66MB + Index: 0.15MB + Engine MyISAM
wp_lrt_postmeta: Data: 178.67MB + Index: 68.05MB + Engine MyISAM
wp_lrt_posts: Data: 26.31MB + Index: 3.08MB + Engine MyISAM
wp_lrt_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lrt_term_relationships: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_lrt_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lrt_usermeta: Data: 38.80MB + Index: 22.11MB + Engine MyISAM
wp_lrt_users: Data: 1.91MB + Index: 1.61MB + Engine MyISAM
wp_lrt_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wcpdf_proforma_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_customer_lookup: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_lrt_wc_download_log: Data: 0.34MB + Index: 0.27MB + Engine InnoDB
wp_lrt_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_lrt_wc_order_product_lookup: Data: 5.52MB + Index: 6.06MB + Engine InnoDB
wp_lrt_wc_order_stats: Data: 5.52MB + Index: 4.55MB + Engine InnoDB
wp_lrt_wc_order_tax_lookup: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_lrt_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_lrt_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfBlockedIPLog: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_wfConfig: Data: 2.23MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfFileMods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfHits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_lrt_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfIssues: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_lrt_wfKnownFileList: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfLogins: Data: 0.39MB + Index: 0.13MB + Engine InnoDB
wp_lrt_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfNotifications: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_lrt_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_wfStatus: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_lrt_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_yoast_indexable: Data: 2.52MB + Index: 0.70MB + Engine InnoDB
wp_lrt_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_yoast_seo_links: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_lrt_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 814
dlm_download: 23
dlm_download_version: 143
nav_menu_item: 44
oembed_cache: 93
page: 111
post: 82
product: 39
revision: 2484
shop_coupon: 67
shop_order: 37776
shop_order_refund: 366
user_request: 2
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.3.19
Yoast SEO Multilingual: by OnTheGoSystems – 1.2.2
Affiliates WooCommerce Advanced Integration: by Tips and Tricks HQ – 1.8 – Installed version not tested with active version of WooCommerce 4.4.1
AMP: by AMP Project Contributors – 2.0.0
Antispam Bee: by pluginkollektiv – 2.9.2
Classic Editor: by WordPress Contributors – 1.6
CMS Tree Page View: by Jon Christopher – 1.6.1
Configure SMTP: by Scott Reilly – 3.1
Contact Form 7: by Takayuki Miyoshi – 5.2.2
Content Anchor Links: by Roland Barker
xnau webdesign – 1.6.2

Download Monitor: by Never5 – 4.4.3
Facebook Like Thumbnail: by Ashfame – 0.4
Geolocation IP Detection: by Yellow Tree (Benjamin Pick) – 3.1.1
gw News Widget: by Gunther Wegner – 1.0
Lazy Load for Videos: by Kevin Weber – 2.8.7
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Newsletter - Addons Manager: by The Newsletter Team – 1.1.3
Newsletter - Feed by Mail: by The Newsletter Team – 4.1.1
Newsletter - Reports and Retargeting: by The Newsletter Team – 4.3.7
Newsletter: by Stefano Lissa & The Newsletter Team – 6.8.7
Quick Page/Post Redirect Plugin: by anadnet – 5.2.0
Rel Nofollow Checkbox: by Fabio Santos – 1.1.5
Replace Content Image Size: by Pau Iglesias
Blogestudio – 1.2.1

Responsive Lightbox & Gallery: by dFactory – 2.2.3.1
Simple Image Sizes: by Rahe – 3.2.1
PayPal PLUS for WooCommerce: by Inpsyde GmbH – 2.2.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.5 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Email Validation: by Hugh Lashbrooke – 2.1.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce EU VAT Compliance (Premium): by David Anderson – 1.14.13 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Multi Currency Premium: by VillaTheme – 2.1.9.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Multilingual: by OnTheGoSystems – 4.10.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.6.0
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 2.6.5
WooCommerce: by Automattic – 4.4.1
Wordfence Security: by Wordfence – 7.4.11
WordPress Post Tabs: by Internet Techies
Tejaswini Deshpande – 1.6.3

WP Affiliate Platform: by Tips and Tricks HQ
Ruhul Amin – 6.2.4

WPML Media: by OnTheGoSystems – 2.5.6
WPML String Translation: by OnTheGoSystems – 3.0.14
WPML Translation Management: by OnTheGoSystems – 2.9.11
WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.2.1

WPS Hide Login: by WPServeur
NicolasKulka
tabrisrp – 1.5.6

### Inactive Plugins (3) ###

Shariff Wrapper: by Jan-Peter Lambeck & 3UU – 4.6.5
WP Staging: by WP-Staging – 2.7.5
Yoast SEO: by Team Yoast – 14.8.1

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #1233 - /products/
Cart: #1244 - /cart/
Checkout: #1245 - /checkout/
My account: #1246 - /my-account/
Terms and conditions: #346 - /eula/

### Theme ###

Name: lrt-woo
Version: 1.1
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

### Action Scheduler ###

Complete: 1,663
Oldest: 2020-07-29 17:21:57 +0200
Newest: 2020-08-29 14:56:33 +0200

Pending: 1
Oldest: 2020-09-03 09:18:00 +0200
Newest: 2020-09-03 09:18:00 +0200
</details>

**Comment by DavidAnderson684** [comment] 2020-08-29 13:25
This happens for me too, specifically for the "billing country" field. ("Shipping country" is still required - an error results if it is not present).

**Comment by thuautp** [comment] 2020-09-07 07:23
Also seen in this forum thread: https://wordpress.org/support/topic/country-field-is-not-validated-customers-leave-it-blank/

**Comment by bernattorras** [comment] 2020-09-07 12:21
3294665-zen

**Comment by GlennMartin1** [comment] 2020-09-21 01:14
Related?: https://github.com/woocommerce/woocommerce/issues/27652

**Comment by tharsheblows** [comment] 2020-09-29 14:11
I'm pretty sure this is due to changing the value of the "Select a country" option from an empty string to the string "default": https://github.com/woocommerce/woocommerce/commit/9faee1d909f81dd027e5ddc1e46a7abff9c0921d 

This affects the logic here: https://github.com/woocommerce/woocommerce/blob/73deab28a5535ff049f61c5529e186b8837352f2/includes/class-wc-checkout.php#L210  (the empty check fails and I think `current` is returning an unexpected value)

**Comment by AlexandreAcyba** [comment] 2020-10-13 12:29
We're having the same issue here. 
Would be nice if it can be fixed in one of the upcoming releases ;-)

**Comment by juliaamosova** [comment] 2020-10-22 20:02
Hi @gwegner,

Apologies for the delayed response here. 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested using WooCommerce 4.6.1. Please see gif below:

![](http://g.recordit.co/q7EegUMQdg.gif)

Can you please confirm if you are still experiencing the issue? If so, am I missing any steps in my testing?

**Comment by tharsheblows** [comment] 2020-10-25 08:25
Hi @juliaamosova -- The issue is that the country field can no longer be required and go through that validation step as it will always have a value, not the fact that "default" works correctly in some payment gateways (it does not in others). [A brief description of the required attribute for inputs is here.](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required)

The expected behaviour is shown by the missing street address in this screengrab. "Street address" is required and pops ups an error notice saying "Billing Street address is a required field" when the field is empty and the form is submitted. The country is _also_ a required field in this example but does not throw an error correctly because the value is not empty, it is now set to "default" – [this was changed in this commit](https://github.com/woocommerce/woocommerce/commit/9faee1d909f81dd027e5ddc1e46a7abff9c0921d)

<img width="933" alt="Screenshot 2020-10-25 at 08 14 28" src="https://user-images.githubusercontent.com/1530368/97102086-7514bc80-169a-11eb-8154-a59a685f98c6.png">

**Comment by AlexandreAcyba** [comment] 2020-10-26 13:29
+1 for @tharsheblows answer. We're experiencing the exact same situation here ;-)

**Comment by Peter-27** [comment] 2020-10-26 16:27
I also have the exact same issue which I raised on #27070 back in July. Disappointed to see no solution yet. @juliaamosova

**Comment by gwegner** [comment] 2020-10-26 16:37
+1

**Comment by juliaamosova** [comment] 2020-10-30 19:29
@tharsheblows thanks for your detailed follow-up. The way I see this issue is that the error message is incorrect if the customer didn't fill out the country:

- Currently, it throws: `Unfortunately we do not ship to default. Please enter an alternative shipping address`.
- Instead, it should be: `Country/region field is a required field`.

Is it correct?

I was still not able to check out if I don't select the country.

**Comment by oceanbeat** [comment] 2020-11-01 10:34
I have the same issue and posted in the Woocommerce support forum 2 months ago (see link above by thuautp).
It’s super annoying this issue still has not been fixed. 
@juliaamosova Please note this issue **only occurs for VIRTUAL products**! Has this ever been looked into?
I’ve tested it and when I set a product to a normal / non virtual product I actually get the error message „we don’t ship to default“. **For virtual / downloadable products customers still are able to leave the country field blank and can checkout without any error message being display**. DESPITE the fact it is marked as mandatory field.

I know the country might not seem relevant for virtual products because nothing is being shipped but it is essential for accurate tax calculation that a country is selected when a purchase is being made.

**Comment by webdesign-steyrer** [comment] 2020-11-01 23:17
I have the same issue! Although in a bit different way… When I select the default billing country entry(select a country) I’m getting the error message Sorry we’re not shipping to ‘default’! Now when I check “different shipping address” and the second form for the shipping address pops up, I have to set a country BUT the billing country is not validated anymore… This is a huge problem, as I need the country in billing address for tax calculations… so if a user sets a shipping country but no billing country, he is ordering tax free!

**Comment by smazur** [comment] 2020-11-02 10:57
+1

Customer get following error message:
```
Unfortunately we do not ship to default. Please enter an alternative shipping address.
```
 Also the country field has no error highlight against to other required fields.

**Comment by tharsheblows** [comment] 2020-11-07 12:27
Would it be possible to get @JohnTendik to look at ticket? (Asking because he just committed something to checkout.js where he can see the issue.) The issue is that the country field in checkout is this:

```
<p class="form-row form-row-wide address-field update_totals_on_change validate-required" id="billing_country_field" data-priority="40">
  <label for="billing_country" class="">Country / Region&nbsp;<abbr class="required" title="required">*</abbr></label>
  <span class="woocommerce-input-wrapper">
    <select name="billing_country" id="billing_country" class="country_to_state country_select select2-hidden-accessible" autocomplete="country" tabindex="-1" aria-hidden="true">
      <option value="default">Select a country / region…</option>
      [list of countries deleted]
    </select>
  </span>
  [select2 bits and noscript deleted]
</p>```

The validate-required class on this should trigger the validation check in https://github.com/woocommerce/woocommerce/blame/master/assets/js/frontend/checkout.js

but because it's not an empty string, it's not triggering it.

Some payment gateways and some tax calculations are relying on this validation and not doing a check of their own. [The value of the default country option selected was changed from an empty string to "default" in this commit.](https://github.com/woocommerce/woocommerce/commit/9faee1d909f81dd027e5ddc1e46a7abff9c0921d)

**Comment by tharsheblows** [comment] 2020-11-07 13:42
Sorry, I think I'm wrong on checkout.js! At least sometimes. It's something which is affected by the change of the billing country select on the checkout page having the default value be the string "default" rather than an empty string.

**Comment by JohnTendik** [comment] 2020-11-07 17:33
I can take a look but I don't think this relates to the changes I made in checkout.js :) The sounds and smells like its because the field has a default value now which is "default". I don't think the validator checks the value against country names, that would be inefficient. I think we can probably test this by changing one of the values in the drop down to something random. It will pass validation because there is a  value in the country field, but that value just doesn't map to an actual usable value. We have some choices on how we want to approach this fix.

**Comment by tharsheblows** [comment] 2020-11-07 17:48
@JohnTendik I'm so sorry, I didn't meant to imply that it was caused by anything you did! Yikes! 😬 I didn't think that at all. 

I was trying to find someone who would understand the issue (and you do! thank you 😊) and thought you would because you were in checkout.js (which it doesn't really touch does it, if you skip it, it doesn't trigger the event?). It was a hacky and not great way of getting someone to look at this who might understand what might be happening.

**Comment by vendidero** [comment] 2020-11-23 12:49
I've just faced the same issue (missing or "default" billing country for virtual products). You might want to use the following snippet to fix the issue (until Woo provides a fix): https://gist.github.com/vendidero/c2b1be3ff2060fbb4ef69eb47d674980

**Comment by giannis-koulouris** [comment] 2020-11-25 08:59
@vendidero 's solution worked for me, but we still need a fix from wc.

**Comment by oceanbeat** [comment] 2020-11-30 18:01
Solution from @vendidero worked for me (thanks for your effort!) – but not in every case.
Maybe this is an issue with my theme (Flatsome)? On my checkout page when you select the Country dropdown it looks like this:

https://s20.directupload.net/images/201130/b2bz2b8f.png

First line: "Land" = country
Second Line: "Land auswählen" = select country

When a user does not actively select anything at all and leaves the selector on the very first entry ("country") the snipped by @vendidewo works and they get an error message. 
BUT when they simply select the second line "Select country" the order os being placed without a country actually being selected. 
Obviously this second entry works as a "country" and I've had several orders  that had "default" als country.

Is there a workaround to remove this second line?

**Comment by juliaamosova** [comment] 2020-12-04 21:34
Thanks, everyone for your input on this issue! 

>@juliaamosova Please note this issue only occurs for VIRTUAL products! Has this ever been looked into?
I’ve tested it and when I set a product to a normal / non virtual product I actually get the error message „we don’t ship to default“. For virtual / downloadable products customers still are able to leave the country field blank and can checkout without any error message being displayes. DESPITE the fact it is marked as mandatory field.

>I know the country might not seem relevant for virtual products because nothing is being shipped but it is essential for accurate tax calculation that a country is selected when a purchase is being made.

As suggested by @oceanbeat, I tried to checkout the virtual product without the country being selected and I indeed was able to do that. On the back end, the country field shows as `default` which shouldn't be. The country should be a mandatory field even for virtual products since the address that is being requested is the billing one:

![default](https://user-images.githubusercontent.com/19143190/101216879-4bae5f80-364e-11eb-8295-444bc277447a.jpg)

If the product is physical, there is no way to check out without the country being entered but the error message shown is incorrect:

- Currently, it throws: `Unfortunately we do not ship to default. Please enter an alternative shipping address.`
- Instead, it should be: `Country/region field is a required field.`

![](http://g.recordit.co/Hv1Jt6o2iW.gif)

I am assigning this a `high` priority and 4.9 milestone.

**Comment by webdesign-steyrer** [comment] 2020-12-05 06:42
I'm having a similar issue... as soon as I set a delivery address, it doesn't matter if I set a billing country. So customers can order without setting a billing country. Which leads to customers being able to order without paying taxes as the billing country field is used for tax calculation... doesn't matter if it is a virtual product or not... is anyone having the same issue? Is there a separate thread somewhere?

**Comment by vedanshujain** [comment] 2020-12-21 09:09
Reopening based on https://github.com/woocommerce/woocommerce/pull/28543#issuecomment-747400562

**Comment by peterfabian** [comment] 2021-01-04 19:49
Do we plan to change this further before 4.9? Or to revert the linked PR?

**Comment by Konamiman** [comment] 2021-01-18 14:35
I've been testing based on the comment @vedanshujain mentioned and indeed it looks like more validation is needed. Example, add the following to simulate an incorrect/tampered checkout form:

```php
if(array_key_exists('billing_country', $_POST))  $_POST['billing_country'] = 'XX';
```

You'll then be able to create an order whose country is "XX", and as such it will appear in the orders list.

**Comment by Konamiman** [comment] 2021-01-19 09:58
Assigning to myself since I have created https://github.com/woocommerce/woocommerce/pull/28849.

**Comment by vedanshujain** [comment] 2021-02-10 08:24
Marking with `impact: high` label as the fix affects checkout flow.

**Closed** 2021-02-11 13:29 UTC
Labels: category: release highlight, component: checkout, impact: high, priority: high, type: bug
