### ISSUE TITLE
The product image become small when I active the child theme, but it works fine on staging, anyonw know what's the issue and how to fix it?

### ISSUE THREAD

**Issue by Neal86** [woocommerce/woocommerce#30083] opened 2021-06-10 18:09 UTC
The product image becomes small when I active the child theme(http://i.prntscr.com/IVUnlQGsS2a7gALa4_onTw.png), and it can't be fixed by change back to the parent theme. But it works fine on staging, anyone knows what's the issue and how to fix it?

**Comment by simplysaru** [comment] 2021-06-11 13:40
@Neal86 this doesn't seem like an issue or a bug related to WooCommerce Core. It seems more like an issue on your site. These questions are better addressed in the [forums](https://wordpress.org/support/plugin/woocommerce/).

**Comment by juliaamosova** [comment] 2021-06-18 17:20
Hi @Neal86,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-06-18 17:20 UTC
