### ISSUE TITLE
API wp-json 302 redirect to login

### ISSUE THREAD

**Issue by csychester** [woocommerce/woocommerce#24138] opened 2019-07-12 13:34 UTC
Hi,

Im having an issue where intermittently my API GET requests are coming back with a 302 found response, resaving permalinks seems to solve the issue for a short time but not always but it occurs again after a short time.

Im using IIS so any redirects would be written it web.config and this never changes and htaccess is obviously not in use.

Ive tried deactivating all plugins except Woocomerce but the issue sill occurs.

attempts it via postman when the application is receiving a 302, resolves to wp-login
 
Could anyone shed some light on the issue or have had experience with similar?

Thanks

**Comment by claudiosanches** [comment] 2019-07-15 14:52
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried make requests to `wp-json` and it appeared to work correctly.

Also this issue doesn't sounds related to WooCommerce, since `wp-json` is a WordPress endpoint, not related or controlled by WooCommerce. Sounds like the problem is your server setup on IIS. 

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-07-15 14:52 UTC

**Comment by nhayling** [comment] 2022-10-26 18:17
@claudiosanches you do realize that the woocommerce REST API uses "wp-json" in their endpoints, right? 

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

But, I am also having a similar issue here...

**Comment by ghost** [comment] 2023-05-01 15:53
@csychester We ended up changing the permalinks within the wordpress settings and this solved the issue for us.
