### ISSUE TITLE
A coupon with unlimited usage per user cannot be added to a manually created order for Guests

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#24041] opened 2019-07-01 16:01 UTC
**Describe the bug**
A coupon with unlimited usage per user cannot be added to a manually created order for Guests.

**To Reproduce**
1. Create a coupon with no restrictions at all:

![https://cld.wthms.co/bRBxDR](https://cld.wthms.co/bRBxDR+) 
Full Size: https://cld.wthms.co/bRBxDR

![https://cld.wthms.co/IQ1Xu2](https://cld.wthms.co/IQ1Xu2+) 
Full Size: https://cld.wthms.co/IQ1Xu2

![https://cld.wthms.co/CPcLon](https://cld.wthms.co/CPcLon+) 
Full Size: https://cld.wthms.co/CPcLon

2. Try to add it to a manually created order for Guest user:

![https://cld.wthms.co/u3PfPA](https://cld.wthms.co/u3PfPA+) 
Full Size: https://cld.wthms.co/u3PfPA

You'll receive the `Coupon usage limit has been reached.` error.

- If you create an order on site, it works:

![https://cld.wthms.co/hheeFD](https://cld.wthms.co/hheeFD+) 
Full Size: https://cld.wthms.co/hheeFD

- If you change **Usage limit per user** to something (I changed it from _unlimited_ to 10), it works:

![https://cld.wthms.co/PkNHDH](https://cld.wthms.co/PkNHDH+) 
Full Size: https://cld.wthms.co/PkNHDH

![https://cld.wthms.co/p0inVG](https://cld.wthms.co/p0inVG+) 
Full Size: https://cld.wthms.co/p0inVG 

- If you change your user on manual order to an existing user, it works.

**Expected behavior**
I expect to be able apply coupons for manual orders for Guest user since there is no restriction set _per user_ in the coupon settings.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://.mystagingwebsite.com
Site address (URL): https://.mystagingwebsite.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.19
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.65.0
OpenSSL/1.1.0j

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.31-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
Total Database Size: 13.49MB
Database Data Size: 8.82MB
Database Index Size: 4.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.17MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.20MB + Index: 0.22MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.05MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.13MB + Index: 0.09MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.16MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.06MB + Index: 0.06MB
wp_postmeta: Data: 1.50MB + Index: 1.95MB
wp_posts: Data: 0.42MB + Index: 0.27MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_exported_csv_items: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_exported_xml_items: Data: 0.13MB + Index: 0.02MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB

### Post Type Counts ###

attachment: 6
bookable_person: 3
bookable_resource: 11
customize_changeset: 3
event_ticket: 1
follow_up_email: 13
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 2
page: 25
post: 3
product: 77
product_variation: 253
revision: 60
scheduled-action: 295
shop_coupon: 8
shop_order: 132
shop_order_refund: 6
shop_subscription: 4
tribe_events: 2
tribe_wooticket: 7
warranty_request: 1
wbcr-snippets: 5
wc_booking: 21
wc_membership_plan: 1
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce: by Automattic – 3.6.4

### Inactive Plugins (81) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Classic Editor: by WordPress Contributors – 1.5
Event Tickets: by Modern Tribe
Inc. – 4.10.1.2

Event Tickets Plus: by Modern Tribe
Inc. – 4.10.1.3

Facebook for WooCommerce: by Facebook – 1.9.12 – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.8.10
Gutenberg: by Gutenberg Team – 4.4.0
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 7.4.1
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 1.6.4 – Not tested with the active version of WooCommerce

Loco Translate: by Tim Whitlock – 2.2.2
Say What?: by Lee Willis – 1.9.1
SIP Cookie Check for WooCommerce: by ShopitPress <hello@shopitpress.com> – 1.0.2 – Not tested with the active version of WooCommerce
Storefront Blog Customiser: by WooCommerce – 1.2.5
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Mega Menus: by WooCommerce – 1.6.2 – Not tested with the active version of WooCommerce
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.4.15
Storefront Pricing Tables: by WooCommerce – 1.1.0
Storefront Reviews: by WooCommerce – 1.0.5 – Not tested with the active version of WooCommerce
The Events Calendar: by Modern Tribe
Inc. – 4.8.2

WooCommerce - ShipStation Integration: by WooCommerce – 4.1.28
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.6 – 1.1.8 is available
WooCommerce Admin: by WooCommerce – 0.12.0
WooCommerce Advanced Notifications: by WooCommerce – 1.2.15 – Not tested with the active version of WooCommerce
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.10.1
WooCommerce Bookings: by WooCommerce – 1.14.4
WooCommerce Box Office: by WooCommerce – 1.1.12
WooCommerce Brands: by WooCommerce – 1.6.8
WooCommerce Bulk Variations: by Lucas Stark – 1.6.5
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.18
WooCommerce Composite Products: by SomewhereWarm – 3.15.2 – Not tested with the active version of WooCommerce
WooCommerce Currency Converter: by WooCommerce – 1.6.13
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.6.3
WooCommerce Customer/Order XML Export Suite: by SkyVerge – 2.5.1
WooCommerce Deposits: by WooCommerce – 1.4.12
WooCommerce Disability VAT Exemption: by WooCommerce – 1.3.6 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by WooCommerce – 1.1.10
WooCommerce EU VAT Number: by WooCommerce – 2.3.13
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.20
WooCommerce FedEx Shipping: by WooCommerce – 3.4.13 – Not tested with the active version of WooCommerce
WooCommerce Gutenberg Products Block: by Automattic – 1.1.2 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.12.4 – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.6
WooCommerce Multi-currency: by TIV.NET INC – 1.16.0
WooCommerce PayFast Gateway: by WooCommerce – 1.4.12
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.14 – 1.6.15 is available
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.2.4 – 2.2.5 is available – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Andrew Benbow – 4.3.4 – Not tested with the active version of WooCommerce
WooCommerce Photography: by WooCommerce – 1.0.17
WooCommerce Points and Rewards: by WooCommerce – 1.6.21
WooCommerce Pre-Orders: by WooCommerce – 1.5.12 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.11
WooCommerce Product Bundles: by SomewhereWarm – 5.10.2
WooCommerce Product Bundles - Bulk Discounts: by SomewhereWarm – 1.1.0
WooCommerce Product Bundles - Min/Max Items: by SomewhereWarm – 1.3.5
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.20 – Not tested with the active version of WooCommerce
WooCommerce Product Enquiry Form: by WooCommerce – 1.2.7 – Not tested with the active version of WooCommerce
WooCommerce Product Filters: by WooCommerce – 1.0.8 – Not tested with the active version of WooCommerce
WooCommerce Product Vendors: by WooCommerce – 2.1.17
WooCommerce Royal Mail: by WooCommerce – 2.5.16
WooCommerce Services: by Automattic – 1.20.0 – 1.21.0 is available
WooCommerce Shipping Per Product v2: by WooCommerce – 2.2.15 – Not tested with the active version of WooCommerce
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.8
WooCommerce Square: by WooCommerce – 1.0.37
WooCommerce Store Credit: by WooCommerce – 2.4.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.2.0
WooCommerce Subscribe All the Things: by Prospress Inc. – 2.1.0-beta.2 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.5.6
WooCommerce Subscriptions Gifting: by Prospress Inc. – 2.0.2 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15
WooCommerce UPS Shipping: by WooCommerce – 3.2.14 – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.21 – Not tested with the active version of WooCommerce
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.12
WooCommerce Warranty Requests: by WooCommerce – 1.8.13 – Not tested with the active version of WooCommerce
Woody ad snippets (PHP snippets | Insert PHP): by Will Bontrager Software
LLC <will@willmaster.com>
Webcraftic <wordpress.webraftic@gmail.com> – 2.2.3

WooSlider: by WooThemes – 2.4.2
WooSlider - WooCommerce Products Slideshow: by WooThemes – 1.0.12 – Not tested with the active version of WooCommerce
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Mail Logging: by Christian Zöller – 1.9.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #512 - /wooslider-page/

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 218
Oldest: 2019-06-03 12:38:51 +0000
Newest: 2019-07-01 15:47:38 +0000

Pending: 7
Oldest: 2019-07-01 15:59:49 +0000
Newest: 2019-07-23 16:40:04 +0000

Canceled: 67
Oldest: 2019-06-05 13:04:42 +0000
Newest: 2019-07-01 15:44:55 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 3
Oldest: 2019-06-15 16:33:17 +0000
Newest: 2019-07-01 15:54:54 +0000

`
```
</details>

**Comment by malviyaritesh** [comment] 2019-07-03 04:08
Already fixed in #23851.

**Comment by rodrigoprimo** [comment] 2019-07-18 18:14
@treibalen I was not able to reproduce this issue. Are you still able to reproduce it?

Here is a screencast of the steps that I took to try to recreate the problem reported here: https://cloudup.com/cwfq73eRIp1

Did I miss something?

@malviyaritesh I don't think this problem is related to #23851 as I was not able to reproduce it even running a version older than 3.6.5 (which is the first version that shipped with the fix that you mentioned).

**Comment by malviyaritesh** [comment] 2019-07-19 03:20
@rodrigoprimo After checking out to `3.6.4`, I was able to successfully reproduce it. Please note as mentioned in https://github.com/woocommerce/woocommerce/issues/23836#issue-449449511 the issue is not present in `3.6.3`. 
This has been fixed in `3.6.5`. Let me know if you need help to reproduce it.

**Comment by treibalen** [comment] 2019-07-19 12:38
@rodrigoprimo @malviyaritesh I can't reproduce it with `3.6.5`, only with `3.6.4`. So I guess it's resolved indeed 🎉

**Comment by rodrigoprimo** [comment] 2019-07-19 12:51
Thanks for the confirmation.

**Closed by rodrigoprimo** 2019-07-19 12:51 UTC
Labels: status: needs feedback
