### ISSUE TITLE
Tax displayed wrongly after changing from a Tax-zone to Non-tax zone.

### ISSUE THREAD

**Issue by Auph** [woocommerce/woocommerce#19521] opened 2018-03-25 23:55 UTC
Our current setup:

- Force shipping to customer billing address
- Tax of 7% is charged for Singapore
- No tax for all other countries

At the checkout page, when toggling from Singapore to another non-tax country, tax is still shown.
Tax only disappears after toggling to another non-tax country for the second time.

Replicated this 10 times in a row, and it's causing us to overcharge overseas customers.

URL: https://simplyfunko.com

**Comment by mikejolley** [comment] 2018-03-26 11:35
I think you have some other issues on this site.

> You cannot add that amount of "Funko Pop! Marvel 71: Age of Ultron – Rampaging Hulk" to the cart because there is not enough stock (0 remaining).

Yet it's marked in stock. Data or extension issue?

As for the reported bug, I tested locally with this setup and changing country changed tax every time. Note; the billing fields all need to be filled in for the tax to recalculate. 

Another setting which can affect this is the "Calculate tax based on" setting in WC > Settings > Taxes. Ensure this is not set to 'shop base' as this would ignore addresses.

You did not share status report so I don't know if you're using a tax plugin. You also didn't confirm this happens with only WooCommerce core active so we cannot rule out extension conflict.

Since I cannot reproduce this with the given instructions I cannot confirm a bug and will close this. If you want to provide better instructions please go ahead - you can see the steps we ask you perform and details we require on https://github.com/woocommerce/woocommerce/issues/new 

Alternatively, log a support ticket on the helpdesk if you want someone to login and look for you. They may still request that you exclude extensions however.

Thanks

**Closed by mikejolley** 2018-03-26 11:35 UTC

**Comment by mikejolley** [comment] 2018-03-26 19:35
I see you created https://github.com/woocommerce/woocommerce/issues/19532. 

If you have anything to add or comment on, reply to this issue. Logging the same request again is not helpful.

> Alternatively, log a support ticket on the helpdesk if you want someone to login and look for you

**Comment by Auph** [comment] 2018-03-26 19:38
Apologies. I was under the impression that you wanted me to repost it in a proper format. In any case, that was a rather complete thread. Shouldn't you close this instead?

**Comment by mikejolley** [comment] 2018-03-26 19:38
@Auph 

> wc_pickup_location

I notice references to pickup location in your log. Are you using local pickup or similar shipping methods?

THOSE will apply base taxes regardless of customer location. See https://docs.woocommerce.com/document/local-pickup/#section-6

**Comment by Auph** [comment] 2018-03-26 19:40
@mikejolley Hi Mike, 

Local Pick up is only available for Singapore, not for any other countries. The problem lies with the tax being calculated after changing from Singapore to another country.

**Comment by Auph** [comment] 2018-03-26 19:42
I have enabled the site for you to try replicate the error using the same method as described in #19532

**Comment by mikejolley** [comment] 2018-03-26 19:43
As I said, I cannot add things to cart. Says there is no stock - products have not been imported properly. 

> Local Pick up is only available for Singapore, not for any other countries

Still sounds like local pickup might be selected. Turn it off and re-rest?

**Comment by Auph** [comment] 2018-03-27 00:05
Hi @mikejolley - yes that sounds like a bug to me. I turned off Local Pick Up for Singapore, and changed it to Flat Rate and renamed it to Local Pick Up, and the error doesn't appear anymore.

It seems like this only happens when Local Pick Up is enabled.

**Comment by mikejolley** [comment] 2018-03-27 09:45
@Auph So back to my earlier point, when local pickup is selected it uses the tax rate of the base country. It sounds like non-singapore people are still using local pickup instead of an alternative shipping method. Do you have others setup?

**Comment by Auph** [comment] 2018-03-28 02:04
Hi Mike, that's not true. The only country with Local Pickup selected is Singapore. I'm happy to clone the site for your team to replicate and play around in a separate environment. 

Thanks

**Comment by mikejolley** [comment] 2018-03-28 09:49
>  The only country with Local Pickup selected is Singapore

My question is what other methods are enabled and what was selected when you chose another country?
