### ISSUE TITLE
مشکل بعداز بروزرسانی یک محصول

### ISSUE THREAD

**Issue by abdolluhparviz** [woocommerce/woocommerce#25278] opened 2019-12-20 12:16 UTC
سلام وقت بخیر
من عنوان یکی از محصولاتم رو اشتباه نوشتم و تازه متوجه شدم ، الان می خواستم تغییر بدم که هر کار می کنم بعداز زدن دکمه بروزرسانی خطای 
برگه مورد نظر پیدا نشد
نمایش داده میشه. بقیه محصولات میرم تغییرات میدم هیچ خطایی نمیده و به راحتی بروزرسانی میشه

ممنون میشم راهنمایی کنید

**Comment by tammullen** [comment] 2019-12-20 13:21
Issue Translation (From Persian using Google Translate)
<hr>
*Title*: #25278 Problem after updating a product

*Issue Description*:
Hi there I mispronounced the title of one of my products and just realized, now I wanted to change what I do every time I click on the update button error message not found. Other changes in my products I will make no changes and will be easily updated Thanks for the help

**Comment by tammullen** [comment] 2019-12-20 14:00
Hi @abdolluhparviz! Thanks for raising an issue. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm if you have found a bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue.

To help you troubleshoot the issue you are having, I recommend doing the following:

Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by tammullen** 2019-12-20 14:00 UTC
