### ISSUE TITLE
Issue with sales offer date time not respecting custom settings

### ISSUE THREAD

**Issue by stefanos82** [woocommerce/woocommerce#26347] opened 2020-04-30 19:45 UTC
**Describe the bug**
I have set my Timezone to UTC+3 and my product sales offers expire at UTC time, not in UTC+3.

**Screenshots**
Settings > General

![image](https://user-images.githubusercontent.com/1777466/80751016-b7b56c00-8b31-11ea-8715-61cad41a54d2.png)

My product info

![image](https://user-images.githubusercontent.com/1777466/80751064-cc91ff80-8b31-11ea-88eb-7741b3a3f523.png)

The product output

![image](https://user-images.githubusercontent.com/1777466/80751157-fc410780-8b31-11ea-8b91-ac9dae2bfecb.png)

**Expected behavior**
It should have been `...23:59:59 UTC+3`

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

![image](https://user-images.githubusercontent.com/1777466/80752126-aa997c80-8b33-11ea-9b03-eb15178f6cf2.png)

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://mydemo.local
Site address (URL): https://mydemo.local
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.4.5
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 3.62MB
Database Data Size: 2.13MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 42
customize_changeset: 16
nav_menu_item: 17
page: 14
post: 12
product: 18
product_variation: 7
revision: 24
shop_order: 2
wcct_countdown: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

Dokimi: by stefanos82 – 0.1
Show Current Template: by JOTAKI Taisuke – 0.3.3
Simply Show Hooks: by Stuart O'Brien
cxThemes – 1.2.1

Theme Check: by Otto42
pross – 20190801.1

Theme Sniffer: by WPTRT – 1.1.3
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.3
WooCommerce: by Automattic – 4.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: MyDemo Local
Version: 1.0
Author URL: https://mydemo.local/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 15
Oldest: 2020-04-01 23:01:13 +0000
Newest: 2020-04-30 15:29:39 +0000

</details>

**Comment by tammullen** [comment] 2020-05-01 19:29
Hi @stefanos82 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. The notice `Offer valid until X` is not something offered by default in WooCommerce.

Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-05-01 19:29 UTC
Labels: can't reproduce

**Comment by stefanos82** [comment] 2020-05-01 19:58
@tammullen I never said anything about custom code or plugin causes the problem; the code was added to verify the problematic UTC output.

In case you are interested, here's the code added:

```php
function dokimi_custom_price_html( $price, $product )
{
    global $post;
    
    $sales_price_to = get_post_meta($post->ID, '_sale_price_dates_to', true);
    
    if ( is_single() && $sales_price_to != "" ) {
        $sales_price_date_to = date( "Y, j M H:i:s e", $sales_price_to );
        return str_replace( '</ins>', ' </ins> <b>(Offer valid until '.$sales_price_date_to.')</b>', $price );
    } else {
        return apply_filters( 'woocommerce_get_price', $price );
    }
}
add_filter( 'woocommerce_get_price_html', 'dokimi_custom_price_html', 100, 2 );
```
Copy this code either in a theme's `functions.php` or in a custom plugin of yours and do the following steps:

- modify your Timezone to something different than UTC
- set a scheduled sales offer of your choice
- view the edited product to see the debugging output
