### ISSUE TITLE
Some hook to override shipping tax class in a similar way to woocommerce_product_get_tax_class

### ISSUE THREAD

**Issue by carazo** [woocommerce/woocommerce#26081] opened 2020-04-05 12:08 UTC
I have deloped some filter to override tax class for different users. In Spain there is a special tax for some customerrs called "Recargo de equivalencia)". I can apply for them a different tax class for products and variations without problem.

But when I try to do it with shipping I cannot find how to do it.

I am able to override tax price of package rates, but this is not so correct because it mantain the tax class.

So the new tax quantity is correct but it does not correspond to the correct tax class.

Maybe I think you  could include something like:

`$shipping_tax_class = apply_filters( 'woocommerce_shipping_get_tax_class'. get_option( 'woocommerce_shipping_tax_class' ) );`

Into calculate_taxes function in the class abstract-wc-order.php.

If you have any other solution or suggestion, please let me know, I would be really appreciated.

**Comment by jonathansadowski** [comment] 2020-05-18 00:35
Hi @carazo,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by jonathansadowski** 2020-05-18 00:35 UTC

**Comment by carazo** [comment] 2020-05-18 07:41
Sorry this is not a support request.

We suggest to include this new filter:

$shipping_tax_class = apply_filters( 'woocommerce_shipping_get_tax_class'. get_option( 'woocommerce_shipping_tax_class' ) );

In your plugin in order to make possible situations like I mentions before.

**Comment by arentsen** [comment] 2025-01-03 11:08
Hi @carazo, did they include this new filter? Or else, were you able to find a solution? I am trying to change the shipping tax class for certain user groups, so we can apply the equivalencia on the shipping costs as well. But right now, it only applies the 21% even though I used this ancient plugin to use the extended VAT setting including RE: https://wordpress.org/support/plugin/woo-recargo-de-equivalencia/

If I change it manually in the Woocommerce tax settings, it works correctly. But it should not be applied for all users of course.

**Comment by carazo** [comment] 2025-01-04 08:17
No, they didn't include it. You can easily try to find it in the source code, and you won't find it.

You should use another methods to achieve your goal.

**Comment by arentsen** [comment] 2025-01-06 08:17
Ok, thanks for letting me know.

**Comment by arentsen** [comment] 2025-01-09 09:50
Since the shipping costs are fixed anyway, I have added the 21% VAT manually:

```
add_action( 'woocommerce_cart_calculate_fees', 'add_shipping_fee' );

function add_shipping_fee( $cart ) {
	if ( wc_current_user_has_role( 'cliente-re' ) AND floatval(WC()->cart->subtotal_ex_tax) < 120 ) {
		$cart->add_fee( 'R.E. 5,2% (envío)', 0.365 );
	}
} 
```

**Comment by carazo** [comment] 2025-01-09 09:51
Yes, but this is not a fee. This a tax.

**Comment by arentsen** [comment] 2025-01-09 10:07
It does not matter, since we do our book keeping and invoicing separately from Wordpress anyway. It's just that they can pay the right amount when they pay online.

**Comment by carazo** [comment] 2025-01-09 10:09
Ok but for my case this is not a solution.

Thanks anyway.

**Comment by arentsen** [comment] 2025-01-21 10:20
I found a solution, using the Recargo de Equivalencia plugin and adding this code:

```
function yourname_fix_shipping_tax( $taxes, $price, $rates) {
    foreach ( get_option('woocommerce_re_roles', array()) as $role ) {
        if ( current_user_can( $role ) ) {  
            $taxes_re = WC_Tax::get_rates_for_tax_class( 'iva-normal-con-re' );
            $taxes = array();
            foreach ( $taxes_re as $tax_class ) { 
                $taxes[$tax_class->tax_rate_id] =  $price*floatval($tax_class->tax_rate)/100;
            }
            break;
        }  
    }     
   return $taxes;
  
 }
add_filter( 'woocommerce_calc_shipping_tax', 'yourname_fix_shipping_tax',10,3);
```

Thanks to [Juan Carlos Nava Morffe](https://es.stackoverflow.com/questions/350543/el-problema-de-woocommerce-y-los-recargos-de-equivalencia-en-espa%C3%B1a)
