### ISSUE TITLE
no way to to change product prices now

### ISSUE THREAD

**Issue by herb4theburbs** [woocommerce/woocommerce#23513] opened 2019-04-25 14:05 UTC
**Describe the bug**
I had no problem with the prices for the products before I loaded the floating cart.  Now I can't find my prices anywhere. I have to update them, because the shipping doesn't work and the only thing I can do is offer free shipping.  

**To Reproduce**
1. Go to  product
2. Click on  any product
3. Scroll down to where you set the price and the sale price
4. See error its not there

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rodrigoprimo** [comment] 2019-04-25 17:42
This issue tracker is used exclusively for WooCommerce core bugs. From the description, it seems that you are having a problem with a plugin that provides a floating cart? If that is the case, I recommend you try the plugin support forums.

Closing this issue for now. Please leave a comment with more information and a copy of your status report, if I missed something and you believe the problem you are having is caused by WooCommerce core.

**Closed by rodrigoprimo** 2019-04-25 17:42 UTC
