### ISSUE TITLE
WooCommerce Shipping Zones Bug

### ISSUE THREAD

**Issue by jarman1** [woocommerce/woocommerce#23874] opened 2019-06-06 10:43 UTC
**Describe the bug**
I have two shipping zones set up both with different costs for delivery.  In zone one I have a about 2k postcodes in the format of AB* AC* etc.

At some point in the list on zone one I a have a some postcodes that go from PH1* etc going up to PH15*.

Then in zone two I have postcodes that continue PH16* up to PH40* or something similar.

When a customer orders and puts in their postcode which should be covered by zone two for example PH22 xxx, they are only being charge the zone one price?

I don't have just PH* in either zone list.

I am doing something wrong or is this a bug in Woocommerce?

**Comment by claudiosanches** [comment] 2019-06-06 13:04
It's missing several information from this bug report, almost all the template has been removed. Can you please fill all the information? Also including screenshots?

<pre>
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

</pre>

If you prefer, you can close this issue and open again using https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=

Thanks.

**Comment by jarman1** [comment] 2019-06-06 13:33
**To Reproduce**
Create two shipping zones ( i.e zone 1 and zone 2) in WooCommerce shipping settings.
Set a different flat rate fee for each zone and make them taxable.
Make the the regions for the zones UK
Add the following postcodes, to zone 1:
PH1*
PH2*
PH3*
PH4*
PH6*
PH7*
PH8*
PH9*
PH10*
PH11*
PH12*
PH13*
PH14*
PH15*
PH16* 

Add the following postcodes to zone 2:

PH17*
PH18*
PH19*
PH20*
PH21*
PH22*
PH23*
PH24*
PH25*
PH26*
PH30*
PH31*
PH32*
PH33*
PH34*
PH35*
PH36*
PH37*
PH38*
PH39*
PH40*
PH41*
PH42*
PH43*
PH44*
PH49*

Put an order through on the woocommerce site. Go to basket and basket totals, then calculate shipping. Add a dummy post code for zone 2 e.g PH22 XYZ then click calculate.

Woocommerce is charging the fee for zone 1 and not zone 2 which should be different ( my case zone 1 is 5.99 ex vat and zone 2 is 22.99 ex VAT).


**Screenshots**
N/A

**Expected behavior**
Woocommerce should be charging the flat rate fee for zone 2 is postcode is covered by that zone e.g PH22 xyz should be covered by wildcard PH22*.

**Isolating the problem (mark completed items with an [x]):**
I have deleted all postcodes starting with PH in zone one and the calculator assigns the correct fee. ( remember I don't have just a PH* or PH. All the post codes in zone 1 are PH1* etc additionally then is no PH22*.

**WordPress Environment**

Latest version of Wordpress and woocommerce, Using DIVI theme by elegant themes.

Thanks for your help

**Comment by claudiosanches** [comment] 2019-06-06 14:54
Can you please introduce a screenshot?

**Comment by jarman1** [comment] 2019-06-06 15:18
![Screenshot 2019-06-06 16 12 01](https://user-images.githubusercontent.com/51442501/59044774-a8249900-8876-11e9-8b00-1fb6700ec9bd.png)
![Screenshot 2019-06-06 16 12 48](https://user-images.githubusercontent.com/51442501/59044775-a8249900-8876-11e9-9cf5-4b1273bcd393.png)
![Screenshot 2019-06-06 16 13 00](https://user-images.githubusercontent.com/51442501/59044776-a8249900-8876-11e9-8d89-718dcd10332a.png)
![Screenshot 2019-06-06 16 15 57](https://user-images.githubusercontent.com/51442501/59044780-a955c600-8876-11e9-8bac-2bc573e14916.png)
![Screenshot 2019-06-06 16 17 18](https://user-images.githubusercontent.com/51442501/59044784-aa86f300-8876-11e9-8cdf-7ccabf685bb1.png)

**Comment by claudiosanches** [comment] 2019-06-07 14:12
I need a screenshot from your shipping zones configuration, I need to check the order you are setting those shipping zones. Thanks.

**Comment by jarman1** [comment] 2019-06-10 11:24
![Screenshot 2019-06-10 12 21 43](https://user-images.githubusercontent.com/51442501/59192517-96930800-8b7a-11e9-9f33-2b653043826b.png)

As requested. Thanks Claudio :)

**Comment by jarman1** [comment] 2019-06-27 15:16
Any news on this?

Thanks

**Comment by claudiosanches** [comment] 2019-08-01 21:02
@jarman1 please sorry for the delay.

> When a customer orders and puts in their postcode which should be covered by zone two for example PH22 xxx, they are only being charge the zone one price?

Sorry to not have noticed it before, but note that `PH22 xxx` matches with `PH2*` in zone one.

For zone one will need to be more specific, not sure what should be all the matches available, but based in your examples, sounds like you don't need anything from `PH1*` to `PH9*`, since should be covered by your another shipping zones.

**Comment by claudiosanches** [comment] 2019-08-01 21:03
Also this may work if you try to move this first shipping zone to last one, so will be tested against all other shipping zones before coming to this one that is more flexible.

**Closed by claudiosanches** 2019-08-01 21:02 UTC
Labels: status: needs review
