### ISSUE TITLE
Customer New Order Email is not Sending when create account is chosen at checkout

### ISSUE THREAD

**Issue by kiwiot** [woocommerce/woocommerce#24783] opened 2019-10-08 13:13 UTC
**Describe the bug**
New order email is not being delivered to a new customer when an account is created on checkout.

I have spent numerous hours trying to track this one down with various Email debugging tools and the best I can get is that PHPMailer is throwing an error "data not accepted."

If I create and order and an account at the same time with "new account" email enabled it does not send the user a confirmation of the order. However if I disable new account email the email shows up. The same created account has no issue placing an order and getting a new order email the next time around

Note this only ever happens when an account is being created at the same time as the order being placed. The triggers for the email are all firing correctly, its just faulting within PHPMailer. 

**To Reproduce**
1. Set up WC to allow user/pass to be chosen and account create account on checkout.
2. checkout creating a user/pass at the time of checkout
3. Only 2 emails are being sent.

Notes - I have have tested with stripe charge payment, stripe authorize and "send check"

I have also tested on a completely new install of the latest WP and WC and no other plugins. At a loss as to why this is happening. tested locally and on a WPE install with no extra plugins

**Expected behavior**
3 emails - 1 new order to admin, 1 for new account, 1 for order to the customer about the new order

**WordPress Environment**
<details>
```

WooCommerce version: |   | 3.7.0
WooCommerce REST API package: |   | 1.0.2 /var/www/html/public_html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
Log directory writable: |   | /var/www/html/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.3
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   |  
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

Server info: |   | nginx/1.9.15
-- | -- | --
PHP version: |   | 7.1.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP post max size: |   | 64 MB
PHP time limit: |   | 30
PHP max input vars: |   | 10000
cURL version: |   | 7.64.0, OpenSSL/1.1.1c

```
</details>

**Comment by juliaamosova** [comment] 2019-10-11 11:39
Hi @kiwiot, thanks for reporting the issue! However, I can't reproduce it on my end. 

I followed the steps you provided to reproduce the issue, and I am getting all the 3 emails:
<hr>
On a hosted site:
<hr>

- 1 new order to admin:

![new_order_admin](https://user-images.githubusercontent.com/19143190/66647128-f29c9480-ec1f-11e9-86e2-628b51fcdb40.jpg)

- 1 for new account + 1 for order to the customer letting them know about the new order:

![new_order_client](https://user-images.githubusercontent.com/19143190/66647160-0b0caf00-ec20-11e9-8204-bf97fb1f153c.jpg)
<hr>
On a local install:
<hr>

- 1 new order to admin:

![local_admin](https://user-images.githubusercontent.com/19143190/66648391-51afd880-ec23-11e9-9fad-8cb6351fb994.jpg)

- 1 for new account + 1 for order to the customer letting them know about the new order:

![local_client](https://user-images.githubusercontent.com/19143190/66648406-596f7d00-ec23-11e9-84e3-21a6c2c71101.jpg)

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs. 

The type of issue you submitted doesn't qualify as a `bug report` just yet. The issue may or may not reveal a bug once more troubleshooting is done. It seems that you already went through the steps of isolating the issue by making sure it persists with only WooCommerce and default theme activated. 

To help you troubleshoot further, I recommend doing the following:

* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-10-11 11:39 UTC
