### ISSUE TITLE
Import variable produt : can't check automaticaly on CSV import "Used for variations"

### ISSUE THREAD

**Issue by vilm725** [woocommerce/woocommerce#26380] opened 2020-05-05 13:40 UTC
**Describe the bug**
Hi everyone 👋🏼

Sorry but I've the sam problem ... The list of variations is empty and "Used for variations" is not set for the attribute 😡🔥 I have filled in the right attributes with the right values :

![img](https://user-images.githubusercontent.com/64069744/81070553-ae3a5400-8ee3-11ea-84e3-b9771fe61cc5.png)

Blue : variable product
White : variation product

Please, have you solved this problem ? If someone has found a solution, can they contact me?

**To Reproduce**

Create CSV from scratch --> Import CSV (with native WooCommerce Product Importer). I do not export products from another site.

1. I filled the CSV (coma separate) with some products (format: UTF-8) with Google Sheets (**no export from another site**)
2. Run the WooCommerce Product Importer
3. Upload CSV

Link of CSV : https://docs.google.com/spreadsheets/d/1jIwa8cStNeccPuDmmwTDJbUF9x1WeI7a-uYhYpCl7s8/edit?usp=sharing

**Screenshots**
Screenshots of the problem :
![variation-product](https://user-images.githubusercontent.com/64069744/81072128-fb1f2a00-8ee5-11ea-944a-6f24801a1b4f.png)
 "Used for variations" is not check

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://3v12gablsu.preview.infomaniak.website
Site address (URL): https://3v12gablsu.preview.infomaniak.website
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 640 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.5
PHP Post Max Size: 300 MB
PHP Time Limit: 60
PHP Max Input Vars: 3000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.27-log
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_500754_
Taille totale de la base de données: 12.78MB
Taille de la base de données: 9.79MB
Taille de l’index: 2.99MB
wp_500754_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_500754_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_500754_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_500754_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_500754_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_500754_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_b2s_posts: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_500754_b2s_posts_drafts: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_b2s_posts_favorites: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_b2s_posts_network_details: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_b2s_posts_sched_details: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_b2s_user: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_500754_b2s_user_contact: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_b2s_user_network_settings: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_cf7dbplugin_st: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_cf7dbplugin_submits: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_500754_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_options: Données : 2.09MB + Index : 0.06MB + Moteur InnoDB
wp_500754_postmeta: Données : 2.52MB + Index : 0.30MB + Moteur InnoDB
wp_500754_posts: Données : 0.19MB + Index : 0.06MB + Moteur InnoDB
wp_500754_rank_math_404_logs: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_500754_rank_math_internal_links: Données : 0.03MB + Index : 0.01MB + Moteur MyISAM
wp_500754_rank_math_internal_meta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_rank_math_redirections: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_rank_math_redirections_cache: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_rank_math_sc_analytics: Données : 0.03MB + Index : 0.03MB + Moteur MyISAM
wp_500754_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_tm_taskmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_tm_tasks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_trp_dictionary_fr_fr_en_us: Données : 0.05MB + Index : 0.05MB + Moteur InnoDB
wp_500754_trp_gettext_en_us: Données : 0.11MB + Index : 0.13MB + Moteur InnoDB
wp_500754_trp_gettext_fr_fr: Données : 0.50MB + Index : 0.47MB + Moteur InnoDB
wp_500754_trp_original_meta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_500754_trp_original_strings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_500754_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_500754_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_500754_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_500754_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_500754_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_500754_wc_product_meta_lookup: Données : 0.06MB + Index : 0.09MB + Moteur InnoDB
wp_500754_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_wfblockediplog: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wfblocks7: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wfconfig: Données : 0.42MB + Index : 0.01MB + Moteur MyISAM
wp_500754_wfcrawlers: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wffilechanges: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wffilemods: Données : 1.81MB + Index : 0.29MB + Moteur MyISAM
wp_500754_wfhits: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wfhoover: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wfissues: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
wp_500754_wfknownfilelist: Données : 0.90MB + Index : 0.12MB + Moteur MyISAM
wp_500754_wflivetraffichuman: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wflocs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wflogins: Données : 0.04MB + Index : 0.01MB + Moteur MyISAM
wp_500754_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_500754_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_500754_wfnotifications: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wfpendingissues: Données : 0.10MB + Index : 0.02MB + Moteur MyISAM
wp_500754_wfreversecache: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wfsnipcache: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_500754_wfstatus: Données : 0.08MB + Index : 0.04MB + Moteur MyISAM
wp_500754_wftrafficrates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM

### Post Type Counts ###

attachment: 90
elementor_library: 20
jet-menu: 3
language_switcher: 3
nav_menu_item: 34
oembed_cache: 1
page: 9
post: 3
product: 39
product_variation: 15
revision: 34

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

All-in-One WP Migration File Extension: par ServMask
Inc. – 1.6

All-in-One WP Migration: par ServMask – 7.21
Duplicate Post: par Enrico Battocchi – 3.2.4
Elementor Pro: par Elementor.com – 2.9.3
Elementor: par Elementor.com – 2.9.8
Popup Trigger URL for Elementor Pro: par Thème WordPress Suki – 1.0.3
Product CSV Import Export (BASIC): par WebToffee – 1.7.8
Rank Math SEO: par Rank Math – 1.0.42.3
TranslatePress - Multilingual: par Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 1.7.2 – Non testé avec la version active de WooCommerce

W3 Total Cache: par BoldGrid – 0.13.3
Multi Currency for WooCommerce: par VillaTheme – 2.1.4.4
WooCommerce: par Automattic – 4.0.1
WordPress Importer: par wordpressdotorg – 0.7
Worth The Read: par Well Done Marketing – 1.6
WP Menu Custom Fields: par rtCamp – 1.0.1
WP-Optimize - Clean, Compress, Cache: par David Anderson
Ruhani Rabin
équipe Updraft – 3.0.19


### Inactive Plugins (3) ###

Elements Plus!: par The CSSIgniter Team – 2.14.0
Wordfence Security: par Wordfence – 7.4.7
WPS Hide Login: par WPServeur
NicolasKulka
tabrisrp – 1.5.6


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: db.php

### Must Use Plugins (2) ###

1&1 Product Subdomain: par 1&1 – 1.1.0
Local by Flywheel Relative URL (for Live Links): par Flywheel – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #340 - /boutique/
Panier: #341 - /panier/
Validation de la commande: #342 - /commande/
Mon compte: #343 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: OceanWP
Version: 1.8.2
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php


### Action Scheduler ###

Terminer: 38
Oldest: 2020-04-10 07:22:07 +0200
Newest: 2020-05-05 12:18:38 +0200

`
```

</details>

**Comment by juliaamosova** [comment] 2020-05-06 20:15
Hi @vilm725,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

What I did to test is the following:

- I have a site A
- I have a site B
- I did product export from site A and got the CSV file from it
- I imported the CSV file with products I got from site A to site B
- Attributes were marked as `Used for variations`on site B (as they are on site A):

![Screen Shot 2020-05-06 at 4 13 48 PM](https://user-images.githubusercontent.com/19143190/81223830-abf3fa80-8fb4-11ea-94e0-2b00866f53b2.png)

I am not sure if you've done the same steps from your description though. Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by vilm725** [comment] 2020-05-06 21:20
Hi and thank you for you response !😃

> What I did to test is the following:
I have a site A
I have a site B
I did product export from site A and got the CSV file from it
I imported the CSV file with products I got from site A to site B
Attributes were marked as Used for variationson site B (as they are on site A):
> 
I do exactly the same test, just I don't export the product in Site B, I directly filed the CSV file.

My test step by step :
1. I filled the CSV with some products (format: UTF-8)
2. I export the CSV (coma separate)
3. I upload the CSV

The import work perfectly, you can see the screenshot :
![import-perfect](https://user-images.githubusercontent.com/64069744/81228595-9c91a300-8fee-11ea-94b8-d8c6f2611569.jpeg)

But the variation is not check, and therefore **the variations of my products don't work** because ... The "Used for variations" isn't checked 😑The craziest thing is that my csv is, i think, flawless ...

@juliaamosova Have you discover an error in my CSV ? ( https://docs.google.com/spreadsheets/d/1jIwa8cStNeccPuDmmwTDJbUF9x1WeI7a-uYhYpCl7s8/edit?usp=sharing )

I would like to add something very important to me : **the import worked before the update** ... I've test in local (Local By Flywheel1) and in my test vps online ( https://3v12gablsu.preview.infomaniak.website )

**Comment by vilm725** [comment] 2020-05-15 11:01
I solved my import problem and import 150 products with this CSV, in this link : [https://drive.google.com/file/d/1uSVS3PyMMEsKTEAvEEH3MYg-diFWNW9Y/view?usp=sharing](https://drive.google.com/file/d/1uSVS3PyMMEsKTEAvEEH3MYg-diFWNW9Y/view?usp=sharing)

If you have any question with the csv, don't hesitate and post you csv in google drive if you want help

**Comment by juliaamosova** [comment] 2020-05-22 22:13
Hi @vilm725,

Thanks for your follow-up. Indeed, your CSV file was missing mapping of the variations to the parent product. 

The issue is fixed by you by adding SKU to the `Parent` column. Showing `Before` and `After` here in case it is helpful to someone else. 

**Before:**

![sku1](https://user-images.githubusercontent.com/19143190/82713032-9ee33680-9c57-11ea-95d7-51d598d9cc67.jpg)

![sku2](https://user-images.githubusercontent.com/19143190/82713037-a3a7ea80-9c57-11ea-8f7f-b067031903e0.jpg)

**After:**

![sku3](https://user-images.githubusercontent.com/19143190/82713050-a99dcb80-9c57-11ea-8af6-7c06cc23a47e.jpg)

I am closing this issue since there was no bug discovered.

**Closed by juliaamosova** 2020-05-22 22:13 UTC
Labels: can't reproduce, status: needs feedback

**Comment by andyefth** [comment] 2020-10-05 06:51
Hi all,

I hope everyone is well & healthy.

I am facing the same issue; I have followed the above suggestions, but haven't been able to resolve.
The steps I follow are:

1. I export a csv with the variable products from e-Shop #A (_[see worksheet Exported from e-Shop #A](https://docs.google.com/spreadsheets/d/1A__5kaTusBLtwddg8qpEtXnDUqGSo30oyINshGUulAw/edit#gid=1372965291)_).

2. I copy this exported csv on a new worksheet (_[see worksheet Imported to e-Shop #A](https://docs.google.com/spreadsheets/d/1A__5kaTusBLtwddg8qpEtXnDUqGSo30oyINshGUulAw/edit#gid=0)_), and replace only the values of **SKU** (col.C), **Name** (col.D) and **Parent** (col.AF), to create new variable products. I also delete all **ID**’s (col.A).

3. I, then, import the csv with the new products back in e-Shop #A.

Since all columns – except from the ones mentioned above – remain exactly the same, I would expect to see the new variable products also in the same format. However, on the new products, the "_Used for variations_” box is not automatically checked (see screenshots below). And since this box is unchecked, the different variations also do not have any stock (hence the "_Out of stock_").

![Screenshot 1](https://user-images.githubusercontent.com/3518148/95048106-ebec1480-06ef-11eb-8f3e-e54300f82918.png)
![Screenshot 2](https://user-images.githubusercontent.com/3518148/95048110-ef7f9b80-06ef-11eb-8e63-9ea2022d79d2.png)

Am I missing something?
Could you, please, check & advise?

Thank you very much for your valuable time.

**Comment by ivanovevgeny** [comment] 2020-10-07 11:13
I [win](https://github.com/woocommerce/woocommerce/issues/19645#issuecomment-704863112)!

**Comment by ATACKLETARTS** [comment] 2020-12-11 13:37
Same issue.  There was posts with same problem back from two years ago with no support...

**Comment by AngeloLazzari** [comment] 2021-01-19 12:05
Sam issue here, with last WP and WC versions,.... :(((

**Comment by geoffreyarce** [comment] 2021-10-25 22:29
Following documentation here: https://docs.woocommerce.com/document/product-csv-importer-exporter/
Its pointed out that this happens and does not specify that it gets fixed... Is this a known issue?

**Comment by KovaZg** [comment] 2021-11-24 11:32
Hey guys, I just had same issue, and I solved it and it all works, no need to do as @geoffreyarce docs, no need to double import. 
I made my own CSV combined with sample from woocommerce and one from github. Ended up with mixture.
I had issue with variations and quotes etc, made CSV in Excel, then opened in Notepad, long story short, I used google sheet to make and download CSV, and after that move all works.

My example is here:
`<html>
<body>
Type | SKU | Name | Published | Visibility in catalog | In stock? | Stock | regular_price | sale_price | weight | length | width | height | Categories | images | Parent | Attribute 1 name | Attribute 1 value(s) | Attribute 1 visible | Attribute 1 global | Attribute 2 name | Attribute 2 value(s) | Attribute 2 visible | Attribute 2 global

variable | 12345 | PRODUCT NAME | 1 | visible | 1 |   | 50 |   |   |   |   |   | CATEGORY| PATHTOIMAGE |   | Color| Blue, Navy Blue | 1 | 0 | Size | XS,S,M,L,XL,XXL | 1 | 0

variation | 12346 | PRODUCT NAME - VARIATION COLOR - XS | 1 | visible | 1 |   | 50 |   |   |   |   |   | CATEGORY | PATHTOIMAGE | 12345 | Color| Blue| 1 | 0 | Size| XS | 1 | 0

</body>
</html>
</body>
</html>`

Imported all products, images, and variations, all working from first!

**Comment by Natnie** [comment] 2022-03-03 08:43
I have just encountered this issue and it's shut down my entire shop as it's done it on like half my stock and I don't know which it's done it on until I check... I have over 800 products, this is a nightmare.
WHY is there not a toggle column for this like there is for visibility?? Seems like a pretty major oversight to me.

**Comment by nisiwi** [comment] 2023-03-16 15:55
A fix mentioned here might help
https://github.com/woocommerce/woocommerce/issues/19645
