### ISSUE TITLE
Using the [woocommerce_cart] shortcode twice with ajax cause dublication on removing item

### ISSUE THREAD

**Issue by noackmedia** [woocommerce/woocommerce#26653] opened 2020-06-01 12:28 UTC
**Describe the bug**
If you are using the woocommerce_cart twice on a page (for example to display it on two different positions with conditional display) and using the ajax-function to add and remove items there is an issue at removing.
When removing an item, the whole cart-layout gets dublicated. When adding an item its no problem, the existing layouts just updates, but on removing it dublicates. When removing then again its dublicates again to 4 copies and so on.

Was not able to find a causing function while i stucxk on addd and remove using the same function to update the wc fragment.

**To Reproduce**
1. using woocommerce ajax
2. use [woocommerce_cart] twice on a page
3. add some products to the cart
4. go to that page and remove one item form one of the carts

**Screenshots**
![cart1](https://user-images.githubusercontent.com/66230148/83408934-bf5b7f80-a413-11ea-8eb1-54eb265a9170.png)
![cart2](https://user-images.githubusercontent.com/66230148/83408940-c2567000-a413-11ea-874b-8e265109fcfe.png)

**Expected behavior**
The cart should just reload/refresh without dublicating like on adding a product

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.33-nmm1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.28-nmm1-log
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Total Database Size: 0.47MB
Database Data Size: 0.32MB
Database Index Size: 0.15MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.30MB + Index: 0.03MB + Engine MyISAM
wp_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_posts: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 1
customize_changeset: 2
nav_menu_item: 4
page: 6
post: 2
product: 2
revision: 6

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.1.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #13 - /shop/
Cart: #6 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2020-06-01 13:56:31 +0200
Newest: 2020-06-01 13:58:51 +0200
```
</details>

**Comment by juliaamosova** [comment] 2020-06-01 19:38
Hi @noackmedia,

Thanks for raising the issue. Can you please specify how do you replicate the first step exactly? 

>using woocommerce ajax

Also noting here that we haven't been doing a lot of work around shortcodes lately due to the fact they are soon likely to be fully replaced by WooCommerce Blocks. We are now testing the Cart and Checkout blocks for example: 

https://woocommerce.wordpress.com/2020/05/27/available-for-testing-a-block-based-woocommerce-cart-and-checkout/. 

Noting it here in order to set expectations. Even if the shortcodes bug is confirmed, it is likely we won't give it a high priority due to the blocks work that is coming to replace it.

**Comment by noackmedia** [comment] 2020-06-01 20:49
Hi @juliaamosova,
with "using woocommerce ajax" i meant this:
wp-admin -> WooCommerce -> Settings -> Products -> Enable AJAX add to cart buttons on archives 

I understand that Blocks is the future here. But for now i dont want to use beta features for a client and i think it needs a bit time until its finally released?

Thanks for clearing that out. I might then using one cart with js to repositioning it instead of two carts with conditional display.

**Comment by tammullen** [comment] 2021-03-24 20:02
Hi @noackmedia 

Apologies for delay in replying.

It looks like this issue is resolved so I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-24 20:02 UTC
Labels: has feedback
