### ISSUE TITLE
Woocommerce / AJAX - Add Variant 500 Internal Server get_variant_attributes --> get_variant_default_attributes 

### ISSUE THREAD

**Issue by ardiri** [woocommerce/woocommerce#22039] opened 2018-11-26 07:04 UTC
**Describe the bug**
seems there was a chance to a method name in the abstract product class that wasn't tested

**To Reproduce**
change product to variable, attempt to add a variant - 500 internal server error. check logs; see issue with unknown method call to get_variant_attributes() in class-wc-ajax.php

**Expected behavior**
should work; not crash. after changing to get_variant_default_attributes() problem solved.

**Fix**
lines 388 and 676 - change get_variant_attributes to get_variant_default_attributes

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2018-11-26 13:21
I'm not able to reproduce this. Can you provide more detailed steps to reproduce the error?

**Comment by ardiri** [comment] 2018-11-26 15:10
i was at a client today who had this issue; the fix is what i needed to apply.

**Comment by rrennick** [comment] 2018-11-26 20:13
The code change looks reasonable but I will only do PRs for fixes where I can reproduce the problem. If you provide more info & I'm able to reproduce I'll be happy to do a PR with your fix.

**Comment by rrennick** [comment] 2018-11-27 14:37
> more of a courteous contribution than an official one :)

That's great 💯 If you encounter it again can you take notes & pass those along.

**Comment by rrennick** [comment] 2019-01-07 20:37
Closing this for now. If you encounter it again please re-open with details for reproducing the issue.

**Closed by rrennick** 2019-01-07 20:37 UTC
