### ISSUE TITLE
#26260 Fix break Filtering widget

### ISSUE THREAD

**Issue by TheGranadilla** [woocommerce/woocommerce#27606] opened 2020-09-07 14:25 UTC
Since 4.4, filtering widget isn't working with product attributes on my website.
EVERY plugin desactivated, and switched to Twenty Sixteen.

4.5.0-rc.3 tested, filters not working.
4.4.1 : Not working
4.4 : Not working
4.3.3 : Working
4.3.0 : working

—————
4.4 Changelog :
* Fix – The filtering widget now works as expected with variable products, displaying those products for which visible variations are available. #26260

Well, I believe something wrong been made here.

https://wordpress.org/support/topic/product-attribute-filtering-widget-not-working/#post-13372103

**UPDATE**
Already reported #27519

**Comment by pgamaster** [comment] 2020-09-07 19:20
+1 same stuff my store is simply broken now, random filtering options show, no size filtering

**Comment by mixalisen** [comment] 2020-09-09 06:51
Same here. I just installed the new 4.5.0 version and still doesn't work. They didn't fix it...

**Comment by juliaamosova** [comment] 2020-09-09 13:20
Hi @TheGranadilla, @pgamaster, @mixalisen,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27419. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

We are aware that the issue is not resolved in WC 4.5. Apologies for that! We are working on releasing WC 4.5.1 as soon as possible to revert all the changes we made since WC 4.4 so that it would work again as it did in WC 4.3.

**Closed by juliaamosova** 2020-09-09 13:20 UTC

**Comment by mixalisen** [comment] 2020-09-09 14:57
Hi Julia,
thanks for letting us know...!!
