### ISSUE TITLE
Grouped products are missing min/max prices in product lookup tables.

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce#23779] opened 2019-05-21 12:24 UTC
**Describe the bug**
Grouped products have both min_price and max_price set to NULL. This makes them stand out when sorting products by price either in WP Admin or on the frontend.

**To Reproduce**
1. Create a grouped product that consists of several standard products,
2. Make sure the lookup table exists and is filled in correctly,
3. In WP Admin > Products > All Products try sorting products by price ASC.
4. Observe the grouped product stands out:

![Screenshot](https://cld.wthms.co/AYbtAw+)
Screenshot: https://cld.wthms.co/AYbtAw

**Screenshots**
Db record for the affected product:

![Screenshot](https://cld.wthms.co/EuDXK5+)
Screenshot: https://cld.wthms.co/EuDXK5

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
### WordPress Environment ###

WordPress address (URL): http://woostore.local
Site address (URL): http://woostore.local
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.1.7 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.38.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 26.71MB
Database Data Size: 18.09MB
Database Index Size: 8.62MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.30MB + Index: 0.31MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 1.02MB + Index: 0.50MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.08MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.36MB + Index: 0.09MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.05MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.02MB + Index: 0.05MB
wp_postmeta: Data: 3.20MB + Index: 4.11MB
wp_posts: Data: 1.06MB + Index: 0.27MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 1.52MB + Index: 1.84MB
wp_users: Data: 0.08MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpml_mails: Data: 7.52MB + Index: 0.00MB
wp_wrd_discounts: Data: 0.02MB + Index: 0.02MB
wp_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 26
follow_up_email: 3
page: 8
post: 2
product: 29
product_variation: 7
revision: 2
scheduled-action: 263
shop_coupon: 2
shop_order: 109
shop_subscription: 394
tribe_events: 2
tribe_rsvp_attendees: 2
tribe_rsvp_tickets: 1
tribe_venue: 1
tribe_wooticket: 3
wc_membership_plan: 2
wc_user_membership: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.1
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce: by Automattic – 3.6.3

### Inactive Plugins (22) ###

Auto Add or Renew Membership for WooCommerce: by Maria Gorska – 1.0.0 – Not tested with the active version of WooCommerce
Event Tickets: by Modern Tribe
Inc. – 4.7.3.1

Event Tickets Plus: by Modern Tribe
Inc. – 4.7.3

Follow-Up Emails: by WooCommerce – 4.7.4 – Not tested with the active version of WooCommerce
Loco Translate: by Tim Whitlock – 2.1.3
Sensei: by WooCommerce – 1.9.19
Stop Emails: by Sal Ferrarello – 1.2.0
The Events Calendar: by Modern Tribe
Inc. – 4.6.18

W3 Total Cache: by Frederick Townes – 0.9.6
WooCommerce Bookings: by WooCommerce – 1.14.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.9 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.10.1 – Not tested with the active version of WooCommerce
WooCommerce One Page Checkout: by Prospress Inc. – 1.5.3 – Not tested with the active version of WooCommerce
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.1.1 – 2.2.4 is available – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.18
WooCommerce Points and Rewards Fix Individual Coupons: by Maciej Krawczyk – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Product Vendors: by WooCommerce – 2.1.4 – Not tested with the active version of WooCommerce
WooCommerce Review for Discount: by WooCommerce – 1.6.5 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.3.2 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.0-beta – Not tested with the active version of WooCommerce
WooCommerce Xero Integration: by WooCommerce – 1.7.16
WP Mail Logging: by Christian Zöller – 1.8.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4 – 2.2 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 248
Oldest: 2019-04-12 15:53:17 +0000
Newest: 2019-05-21 12:14:23 +0000

Pending: 13
Oldest: 2019-07-17 12:57:12 +0000
Newest: 9600-07-20 15:56:40 +0000

Canceled: 2
Oldest: 2019-05-22 12:05:05 +0000
Newest: 2019-05-22 12:05:05 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```

</details>

**Comment by vedanshujain** [comment] 2019-08-21 14:46
I am not able to reproduce this with the steps provided above on the latest master. I tried with grouping standard products, as well as grouped and variable products but no luck in reproducing the issue. 
Maybe this was fixed in a new release? @madeincosmos is this still happening for you?

**Comment by rodrigoprimo** [comment] 2019-10-01 20:36
Closing due to lack of feedback. Please leave a comment if you are still able to reproduce this issue and we will take another look.

**Closed by rodrigoprimo** 2019-10-01 20:36 UTC
Labels: status: needs feedback
