### ISSUE TITLE
[GlobalStep] Product Stocks fails to update on Analytics->Products screen.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#30180] opened 2021-06-11 15:50 UTC
## Bug Description:
When the product stocks are updated from "Edit Product" screen, the stocks fails to update on Analytics->Products screen.

## Environment:
Woocommerce Version : WooCommerce 5.4.1
WordPress version: (v5.7.2)
WooCommerce Admin: v2.4.0 Beta 1.

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Install and activate WooCommerce Admin 2.4.1 beta 1 plugin.
1. Complete the OBW setup.
1. Add some Products.
1. Purchase any product from the frontend.
1. Go to the Edit product screen.
1. Enable the Manage stock option and set the product quantity.
1. Now go to Analytics->Products.
1. Observe that the product stocks fails to update.

## Actual Result:
Product Stocks fails to update on Analytics->Products screen.

## Expected Result:
Product Stocks should get update on Analytics->Products screen.

## Video:

https://user-images.githubusercontent.com/41110392/121714185-3897b300-cafb-11eb-9419-982581efac09.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WordPress address (URL): https://confident-crawdad.jurassic.ninja
Site address (URL): https://confident-crawdad.jurassic.ninja
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.4.0-beta.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Total Database Size: 9.16MB
Database Data Size: 6.57MB
Database Index Size: 2.59MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.17MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
mailpoet_page: 1
page: 6
post: 2
product: 21
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Facebook for WooCommerce: by Facebook – 2.6.0
Google Listings and Ads: by WooCommerce – 1.0.0
Jetpack: by Automattic – 9.8.1
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
MailPoet 3 (New): by MailPoet – 3.63.0
WooCommerce Admin: by WooCommerce – 2.4.0-beta.1
WooCommerce Shipping & Tax: by WooCommerce – 1.25.13
WooCommerce: by Automattic – 5.4.1
WP Crontrol: by John Blackbourn & crontributors – 1.10.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: woocommerce/woocommerce-admin#6 - /shop/
Cart: woocommerce/woocommerce-admin#7 - /cart/
Checkout: woocommerce/woocommerce-admin#8 - /checkout/
My account: woocommerce/woocommerce-admin#9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 47
Oldest: 2021-06-11 10:47:51 +0000
Newest: 2021-06-11 14:15:12 +0000

### Status report information ###

Generated at: 2021-06-11 15:05:00 +00:00
`

</details>

**Comment by tammullen** [comment] 2021-07-02 14:07
Thanks @moon0326 for transferring the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look.

**Comment by ObliviousHarmony** [comment] 2021-08-05 20:02
Greetings @moon0326,

In reviewing this issue, I'm wondering whether or not it _is_ a caching issue in WooCommerce Admin as per @ilyasfoo's comment. Generally speaking, all save operations [pass through the Product data store](https://github.com/woocommerce/woocommerce/blob/aa939f6081d8513701e5156047b1d3f5ec1ce4df/includes/data-stores/class-wc-product-data-store-cpt.php#L639-L639). This updates the lookup table, including the stock, so we technically shouldn't see any problems here.

Since it was indicated that clearing the analytics cache resulted in the correct data being returned, this doesn't seem like a Core problem. Can you confirm @moon0326?

**Comment by moon0326** [comment] 2021-08-05 22:20
> Greetings @moon0326,
> 
> In reviewing this issue, I'm wondering whether or not it _is_ a caching issue in WooCommerce Admin as per @ilyasfoo's comment. Generally speaking, all save operations [pass through the Product data store](https://github.com/woocommerce/woocommerce/blob/aa939f6081d8513701e5156047b1d3f5ec1ce4df/includes/data-stores/class-wc-product-data-store-cpt.php#L639-L639). This updates the lookup table, including the stock, so we technically shouldn't see any problems here.
> 
> Since it was indicated that clearing the analytics cache resulted in the correct data being returned, this doesn't seem like a Core problem. Can you confirm @moon0326?

Hello ✋ Thank you for reviewing it. I'll test it further soon.

**Comment by moon0326** [comment] 2021-08-16 02:39
not stale. I totally forgot about testing it further. I'll make sure to test it this week.

**Comment by moon0326** [comment] 2021-08-19 22:16
> Greetings @moon0326,
> 
> In reviewing this issue, I'm wondering whether or not it _is_ a caching issue in WooCommerce Admin as per @ilyasfoo's comment. Generally speaking, all save operations [pass through the Product data store](https://github.com/woocommerce/woocommerce/blob/aa939f6081d8513701e5156047b1d3f5ec1ce4df/includes/data-stores/class-wc-product-data-store-cpt.php#L639-L639). This updates the lookup table, including the stock, so we technically shouldn't see any problems here.
> 
> Since it was indicated that clearing the analytics cache resulted in the correct data being returned, this doesn't seem like a Core problem. Can you confirm @moon0326?

@ObliviousHarmony Sorry for the delay in response. You were correct that it's WC Admin related issue. I confirmed `stock` column in `wc_product_meta_lookup` updates correctly.

Clearing transient fixed the problem.

I think we need to adjust [cache time](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/Cache.php#L73) or find a way to expire the transient dynamically.

I'm gonna move this back to WCA repository.

**Comment by moon0326** [comment] 2021-08-19 22:17
Issue moved to [woocommerce/woocommerce-admin #7540](https://github.com/woocommerce/woocommerce-admin/issues/7540) via [**ZenHub**](https://www.zenhub.com/)

**Closed by moon0326** 2021-08-19 22:17 UTC
Labels: has feedback
