### ISSUE TITLE
how to add multiple accounts for multiple countries?

### ISSUE THREAD

**Issue by narulasrinivas** [woocommerce/woocommerce#29071] opened 2021-02-09 14:29 UTC
Hi Team,

We started using woocommerce for our site and we're planning to to take payment across the globe. As a part of requirement, I want to know how to achieve multiple paypal accounts in different currencies. Based on currency selection, I want to send the payment to that related country.

Please let us know if this is achievable. If yes, please give us some pointers to implement on our site.

Happy Coding!!

**Comment by tammullen** [comment] 2021-02-11 17:28
Hi @narulasrinivas 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-02-11 17:28 UTC
