### ISSUE TITLE
after update to 4.5.0 I get the message - You have installed a development version of WooCommerce which requires files to be built and minified. From the plugin directory, run grunt assets to build and minify assets. Or you can download a pre-built version of the plugin from the WordPress.org repository or by visiting the releases page in the GitHub repository.

### ISSUE THREAD

**Issue by cadonovan** [woocommerce/woocommerce#27619] opened 2020-09-09 05:06 UTC
After auto-update, I get the message in my dashboard:

You have installed a development version of WooCommerce which requires files to be built and minified. From the plugin directory, run grunt assets to build and minify assets. Or you can download a pre-built version of the plugin from the WordPress.org repository or by visiting the releases page in the GitHub repository.

Craig

**Comment by juliaamosova** [comment] 2020-09-09 12:54
Hi @cadonovan,

Thank you for submitting the issue. However, I couldn't reproduce it. 

Can you please provide a bit more details? Have you ever used a development version of WooCommerce on your site? Have you updated WooCommerce from the previous version which was 4.4.1? Or from some other version?

**Comment by peterfabian** [comment] 2020-09-09 12:55
Hi @cadonovan, 

Based on the message it seems like the auto-update might have failed to extract all the files properly. Would you be able to  re-apply the update, either by uploading [the zip package](https://downloads.wordpress.org/plugin/woocommerce.4.5.0.zip) [through the WP admin](https://wordpress.org/support/article/managing-plugins/#manual-upload-via-wordpress-admin) manually or [via FTP](https://wordpress.org/support/article/managing-plugins/#manual-plugin-installation)? Thanks!

**Comment by cadonovan** [comment] 2020-09-09 12:56
Hi.
I never used a development version. My site did an auto-update from the
previous version which was working fine.

**Comment by cadonovan** [comment] 2020-09-09 12:58
I restored the previous version from backup and will try to update it
again. If it does not work I will try your suggestion.
Thanks
Craig

**Comment by cadonovan** [comment] 2020-09-09 13:22
My restore to previous version then apply update again has worked ok.
Thanks for your help.
Craig

**Comment by juliaamosova** [comment] 2020-09-09 13:56
Thanks for letting us know @cadonovan. Glad to hear it is now resolved for you. 

I am closing this thread as it seems to be non-bug but we'll keep monitoring to see if we'd get more of these reported in which case we'd need to investigate further.

**Closed by juliaamosova** 2020-09-09 13:56 UTC
Labels: status: needs feedback

**Comment by cadonovan** [comment] 2020-09-09 13:57
ThanksCraig Sent from Mail for Windows 10 From: Julia AmosovaSent: Wednesday, 9 September 2020 21:56To: woocommerce/woocommerceCc: cadonovan; MentionSubject: Re: [woocommerce/woocommerce] after update to 4.5.0 I get the message - You have installed a development version of WooCommerce which requires files to be built and minified. From the plugin directory, run grunt assets to build and minify assets. Or you can download a pre-built version of the plugin from the WordPress.org repository or by visiting the releases page in the GitHub repository. (#27619) Thanks for letting us know @cadonovan. Glad to hear it is now resolved for you.I am closing this thread as it seems to be non-bug but we'll keep monitoring to see if we'd get more of these reported in which case we'd need to investigate further.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
