### ISSUE TITLE
Free Shipping not selected as default when eligible

### ISSUE THREAD

**Issue by gahsto** [woocommerce/woocommerce#25508] opened 2020-01-28 19:46 UTC
@claudiosanches it is an issue.
As you can see below I have it configured as suggested, yet the cart does not update with free shipping selected. It works if I meet the conditions when adding the first product, but if I 'Continue Shopping' without initially meeting the condition then add products afterward to meet it, it doesn't change. Please advise.
![73206808-9b102f00-4111-11ea-80d8-b4b3af11ed5e](https://user-images.githubusercontent.com/38016279/73299333-fd823180-41dc-11ea-8bab-5b9ca3c65771.png)

**Comment by juliaamosova** [comment] 2020-01-30 16:13
Hi @gahsto,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported. Everything is working as expected on my end. 

Here I have `Free Shipping` listed as the top option among shipping methods in the US shipping zone:

![Screen Shot 2020-01-30 at 2 55 04 PM](https://user-images.githubusercontent.com/19143190/73467106-bdf14c00-437a-11ea-9be4-bdc0c49bc4cb.png)

My `Free Shipping` has a condition to be available only when there is a minimum order amount of $100:

![Screen Shot 2020-01-30 at 2 55 12 PM](https://user-images.githubusercontent.com/19143190/73467154-d6f9fd00-437a-11ea-8c2b-0c0fbea5e114.png)

And here is the screencast showing that when I add 1 product to the cart, `Free Shipping` is not available but when I increase the order amount to $100 by increasing the number of products in the cart, I get `Free Shipping` available and it is automatically selected:

![](http://g.recordit.co/AML5wr2Jlv.gif)

Do you have many plugins installed on your site? I see that you don’t use one of our default themes as well. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-02-05 10:16
Hi @gahsto,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-02-05 10:16 UTC
Labels: can't reproduce, status: needs feedback
