### ISSUE TITLE
External product URL bad modification {dot}

### ISSUE THREAD

**Issue by catioooo** [woocommerce/woocommerce#23518] opened 2019-04-25 19:55 UTC
i**ncludes/wc-template-functions.php** is responsible in line 710 for very poor url address modification. 

External product url is changing to https://www{dot}url{dot}tld/

**Comment by rodrigoprimo** [comment] 2019-04-26 15:00
Thanks for your report, @catioooo. Could you please provide all the details requested in the [bug template report](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=)?

I was not able to reproduce the problem you reported. In my testing, I can't see how `wc_query_string_form_fields()` could alter the external product URL.

I did notice though that it can modify the value of the query string parameters. If the external product URL is, for example, `https://www.url.tld/?param1=foo.bar` the hidden input for `param1` is wrongly crea23196ted with `foo{dot}bar`. This problem was introduced by PR #23196, and we will work on a fix.

**Comment by rodrigoprimo** [comment] 2019-04-26 17:35
See #23535. Closing this issue now as I believe the PR that I created will fix the problem that you described. If that is not the case, please leave details on how to reproduce the problem as described in my comment above, and I will take a second look.

**Closed by rodrigoprimo** 2019-04-26 17:35 UTC
Labels: status: needs feedback

**Comment by dammark98** [comment] 2019-05-13 10:47
Hi. I have this exact problem with my woocommerce affiliate website. When can i expect the problem will be fixed? In the next woocommerce update or?

**Comment by rodrigoprimo** [comment] 2019-05-13 15:06
@dammark98, #23535 will be included in the next WooCommerce release. If you would like to test this fix, you can manually apply the changes shown here: https://github.com/woocommerce/woocommerce/pull/23535/files#diff-65760bf45f136dba5d546afa2c8b7ee9

**Comment by dammark98** [comment] 2019-05-13 20:23
@rodrigoprimo Great! When will the next WooCommerce release come do you think? :)

**Comment by rodrigoprimo** [comment] 2019-05-15 17:17
@dammark98 we are aiming for tomorrow or early next week. This could change depending on several factors, but it shouldn't take long for the next release which will be 3.6.3.
