### ISSUE TITLE
Sending emails with custom order status

### ISSUE THREAD

**Issue by yaesci** [woocommerce/woocommerce#19540] opened 2018-03-27 11:26 UTC
We've created the new order status 'Versendet'.

```
<?php
/*
Plugin Name: Versandstatus: Versendet
Plugin URI: https://monkeypepper.ch/
Description: Zusätzlicher WooCommerce Versandstatus "Versendet"
Version: 1.0
Author: Yacine Djerrah
Author URI: https://monkeypepper.ch/
License: GPLv2
*/

function register_awaiting_shipment_order_status() {
    register_post_status( 'wc-awaiting-shipment', array(
        'label'                     => 'Versendet',
        'public'                    => true,
        'exclude_from_search'       => false,
        'show_in_admin_all_list'    => true,
        'show_in_admin_status_list' => true,
        'label_count'               => _n_noop( 'Versendet <span class="count">(%s)</span>', 'Versendet <span class="count">(%s)</span>' )
    ) );
}
add_action( 'init', 'register_awaiting_shipment_order_status' );

// Add to list of WC Order statuses
function add_awaiting_shipment_to_order_statuses( $order_statuses ) {

    $new_order_statuses = array();

    // add new order status after processing
    foreach ( $order_statuses as $key => $status ) {

        $new_order_statuses[ $key ] = $status;

        if ( 'wc-on-hold' === $key ) {
            $new_order_statuses['wc-awaiting-shipment'] = 'Versendet';
        }
    }

    return $new_order_statuses;
}
add_filter( 'wc_order_statuses', 'add_awaiting_shipment_to_order_statuses' );
?>
```

This works fine so far, the order status shows up in the backend and can be selected.
Now my issue: I want to send the following custom e-mail, when I change an order to this new order status. I've tried the following:

```
<?php
/**
 * Plugin Name: WooCommerce Email zum Versandstatus "Versendet"
 * Plugin URI: https://monkeypepper.ch/
 * Description: Email-Versands zu zusätzlichem WooCommerce Versandstatus "Versendet"
 * Version: 0.1
 * Author: Yacine Djerrah
 * Author URI: https://monkeypepper.ch/
 * License: GPLv2
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 *  Add a custom email to the list of emails WooCommerce should load
 *
 * @since 0.1
 * @param array $email_classes available email classes
 * @return array filtered available email classes
 */
function add_expedited_order_woocommerce_email( $email_classes ) {

	// include our custom email class
	require_once( 'includes/class-wc-expedited-order-email.php' );

	// add the email class to the list of email classes that WooCommerce loads
	$email_classes['WC_Expedited_Order_Email'] = new WC_Expedited_Order_Email();

	return $email_classes;

}
add_filter( 'woocommerce_email_classes', 'add_expedited_order_woocommerce_email' );
```

And its corresponding class, where I guess the solution should be (Wrong trigger?) :

```
<?php

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * A custom Expedited Order WooCommerce Email class
 *
 * @since 0.1
 * @extends \WC_Email
 */
class WC_Expedited_Order_Email extends WC_Email {


	/**
	 * Set email defaults
	 *
	 * @since 0.1
	 */
	public function __construct() {

		// set ID, this simply needs to be a unique name
		$this->id = 'wc_expedited_order';

		// this is the title in WooCommerce Email settings
		$this->title = 'Bestellung versendet';

		// this is the description in WooCommerce email settings
		$this->description = 'Email wird versendet sobald Versandstatus "Versendet" gewählt wurde.';

		// these are the default heading and subject lines that can be overridden using the settings
		$this->heading = 'Bestellung wurde versendet';
		$this->subject = 'Bestellung wurde versendet';

		// these define the locations of the templates that this email should use, we'll just use the new order template since this email is similar
		$this->template_html  = 'emails/admin-new-order.php';
		$this->template_plain = 'emails/plain/admin-new-order.php';
		
		// Trigger
		add_action( 'woocommerce_order_status_pending_to_awaiting_shipment', array( $this, 'trigger' ) );
		
		function example6287_order_status_changed( $id, $old_status, $new_status ) {
    // Do stuff
}

add_action( 'woocommerce_order_status_changed', 'example6287_order_status_changed', 10, 3 );

		// Call parent constructor to load any other defaults not explicity defined here
		parent::__construct();

		// this sets the recipient to the settings defined below in init_form_fields()
		$this->recipient = $this->get_option( 'recipient' );

		// if none was entered, just use the WP admin email as a fallback
		if ( ! $this->recipient )
			$this->recipient = get_option( 'admin_email' );
	}


	/**
	 * Determine if the email should actually be sent and setup email merge variables
	 *
	 * @since 0.1
	 * @param int $order_id
	 */
	public function trigger( $order_id ) {

		// bail if no order ID is present
		if ( ! $order_id )
			return;

		// setup order object
		$this->object = new WC_Order( $order_id );


		// replace variables in the subject/headings
		$this->find[] = '{order_date}';
		$this->replace[] = date_i18n( woocommerce_date_format(), strtotime( $this->object->order_date ) );

		$this->find[] = '{order_number}';
		$this->replace[] = $this->object->get_order_number();

		if ( ! $this->is_enabled() || ! $this->get_recipient() )
			return;

		// woohoo, send the email!
		$this->send( $this->get_recipient(), $this->get_subject(), $this->get_content(), $this->get_headers(), $this->get_attachments() );
	}


	/**
	 * get_content_html function.
	 *
	 * @since 0.1
	 * @return string
	 */
	public function get_content_html() {
		ob_start();
		woocommerce_get_template( $this->template_html, array(
			'order'         => $this->object,
			'email_heading' => $this->get_heading()
		) );
		return ob_get_clean();
	}


	/**
	 * get_content_plain function.
	 *
	 * @since 0.1
	 * @return string
	 */
	public function get_content_plain() {
		ob_start();
		woocommerce_get_template( $this->template_plain, array(
			'order'         => $this->object,
			'email_heading' => $this->get_heading()
		) );
		return ob_get_clean();
	}


	/**
	 * Initialize Settings Form Fields
	 *
	 * @since 2.0
	 */
	public function init_form_fields() {

		$this->form_fields = array(
			'enabled'    => array(
				'title'   => 'Aktivieren/Deaktivieren',
				'type'    => 'checkbox',
				'label'   => 'Email aktivieren',
				'default' => 'yes'
			),
			'recipient'  => array(
				'title'       => 'Empfänger',
				'type'        => 'text',
				'description' => sprintf( 'Gib die Empfänger hier ein (Kommagetrennt). Standardmässiger Versand nach <code>%s</code>.', esc_attr( get_option( 'admin_email' ) ) ),
				'placeholder' => '',
				'default'     => ''
			),
			'subject'    => array(
				'title'       => 'Betreff',
				'type'        => 'text',
				'description' => sprintf( 'Betreff der Mail definieren. Leer lassen um Standard Betreff zu verwenden: <code>%s</code>.', $this->subject ),
				'placeholder' => '',
				'default'     => ''
			),
			'heading'    => array(
				'title'       => 'Email Kopfzeile/Header',
				'type'        => 'text',
				'description' => sprintf( __( 'Hier wird der Mail Header definiert. Leer lassen für Standard Header: <code>%s</code>.' ), $this->heading ),
				'placeholder' => '',
				'default'     => ''
			),
			'email_type' => array(
				'title'       => 'Email Format',
				'type'        => 'select',
				'description' => 'Wähle das Format zum Versenden der Email.',
				'default'     => 'html',
				'class'       => 'email_type',
				'options'     => array(
					'plain'	    => __( 'Plain text', 'woocommerce' ),
					'html' 	    => __( 'HTML', 'woocommerce' ),
					'multipart' => __( 'Multipart', 'woocommerce' ),
				)
			)
		);
	}


} // end \WC_Expedited_Order_Email class
```

**Comment by claudiulodro** [comment] 2018-03-27 18:46
Without going through every single line, I think you're on the right track. The missing step is most likely [hooking into the transactional mailer for the status changes](https://github.com/woocommerce/woocommerce/blob/d4ef90bf9143601da1c29d388d2c82eed2312c3d/includes/class-wc-emails.php#L77) and adding the new status transitions you want to send emails for.

Closing this issue because this is a coding support question and not a bug. I recommend joining the WooCommerce developer slack channel for these sorts of questions using [the invite at the bottom of the page](https://woocommerce.com/develop-woocommerce/).

**Closed by claudiulodro** 2018-03-27 18:46 UTC
