### ISSUE TITLE
Gravity form product image gallery not showing on product page.

### ISSUE THREAD

**Issue by alianjum14** [woocommerce/woocommerce#27322] opened 2020-08-13 12:43 UTC
I have created a woo-commerce frontend product submission form by gravity form plugin. When I uploaded everything is working fine except product gallery images not showing on the product page. I have used _product_image_gallery filed to upload the product images and uploading without any error but not showing on the product page can anyone help me to sort out this advance thanks.

**Comment by juliaamosova** [comment] 2020-08-13 14:04
Hi @alianjum14,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the Gravity Forms plugin which is not one of our products. To get further technical support for it, please contact the Gravity Forms support team [here](https://www.gravityforms.com/support/). 

I am closing this thread as it is not WooCommerce core related.

**Closed by juliaamosova** 2020-08-13 14:04 UTC
