### ISSUE TITLE
Products Setting Tab Missing

### ISSUE THREAD

**Issue by INDEPENDENTENTERPRISE1** [woocommerce/woocommerce#29317] opened 2021-03-10 03:25 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

I cannot access p
[WooCommerce settings ‹ IDFD — WordPress.pdf](https://github.com/woocommerce/woocommerce/files/6112956/WooCommerce.settings.IDFD.WordPress.pdf)

`
### WordPress Environment ###

WordPress address (URL): http://independentfurnituredesigns.com
Site address (URL): http://independentfurnituredesigns.com
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.1
Log Directory Writable: ❌ To allow logging
make /home/o9sq1y6kuuxo/public_html/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: ❌ 5.6.2 - There is a newer version of WordPress available (5.7)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.23
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.6.49-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 7.94MB
Database Data Size: 6.64MB
Database Index Size: 1.30MB
wp_woocommerce_sessions: Data: 0.48MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_ce4wp_abandoned_checkout: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.12MB + Index: 0.19MB + Engine MyISAM
wp_postmeta: Data: 1.93MB + Index: 0.39MB + Engine MyISAM
wp_posts: Data: 1.29MB + Index: 0.16MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 0.55MB + Index: 0.13MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.03MB + Index: 0.11MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.12MB + Index: 0.06MB + Engine MyISAM

### Post Type Counts ###

attachment: 869
coblocks_pattern: 2
customize_changeset: 71
elementor_library: 1
nav_menu_item: 23
page: 18
post: 2
product: 288
revision: 121
shop_order: 14
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (22) ###

CoBlocks: by GoDaddy – 2.8.2
Contact Form 7: by Takayuki Miyoshi – 5.4
Creative Mail by Constant Contact: by Constant Contact – 1.3.3
Elementor: by Elementor.com – 3.1.3
Facebook for WooCommerce: by Facebook – 2.3.2
Jetpack by WordPress.com: by Automattic – 9.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.20.3
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
Salert: by WPoperation – 1.1.7
Snap Finance: by Snap Finance – 1.0.13
SpiceBox: by Spicethemes – 1.3.3
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.7.4
Ultra Companion: by WPoperation – 1.1.5
Woo Title Limit: by Dima W. – 2.0.1
WooCommerce Amazon Pay: by WooCommerce – 1.13.1
WooCommerce PayPal Payments: by WooCommerce – 1.2.1
WooCommerce Shipping & Tax: by Automattic – 1.25.8
WooCommerce: by Automattic – 5.1.0-rc.1 (update to version 5.1.0 is available)
Yoast SEO: by Team Yoast – 15.9.1
WPOP Elementor Addons: by WPoperation – 1.1.5
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.7.7

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Hello Dolly: by Matt Mullenweg – 1.7.2
Product Options and Price Calculation Formulas for WooCommerce – Uni CPO: by MooMoo Agency – 4.9.9.1
Unique Headers: by Ryan Hellyer – 1.7.12

### Must Use Plugins (1) ###

installatron_hide_status_test.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
Taxonomies: Product Visibility: outofstock (outofstock)
featured (featured)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #34 - /?page_id=34
Cart: #36 - /?page_id=36
Checkout: #37 - /?page_id=37
My account: #35 - /?page_id=35
Terms and conditions: #3 - /?page_id=3

### Theme ###

Name: Homestore
Version: 2.0.33
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 3.5.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: homestore/woocommerce/single-product/title.php

### Action Scheduler ###

Complete: 51
Oldest: 2021-02-25 13:20:00 +0000
Newest: 2021-03-02 21:34:36 +0000

### Status report information ###

Generated at: 2021-03-10 03:06:02 +00:00
`

**Comment by INDEPENDENTENTERPRISE1** [comment] 2021-03-10 03:26
[WooCommerce settings ‹ IDFD — WordPress.pdf](https://github.com/woocommerce/woocommerce/files/6112961/WooCommerce.settings.IDFD.WordPress.pdf)

**Comment by INDEPENDENTENTERPRISE1** [comment] 2021-03-10 03:30
WooCommerce - Products- Settings Button Missing

**Comment by INDEPENDENTENTERPRISE1** [comment] 2021-03-10 18:56
Hi,

Thank you for your response, Under the Product tab,  it is supposed to be 4
selections

General-Setting-Inventory-Downloadable Products

My Selection only has 3 Tabs

General-Inventory-Downloadable Products

My Settings tab is missing. And I cant change category sizes

Please help me, thank you

**Comment by INDEPENDENTENTERPRISE1** [comment] 2021-03-10 20:48
Thank you, I did that but my products still won't switch to the bottom on
my products page. I wanted to add categories to the top on the page on my
shop page, but it won't switch it around

**Comment by tammullen** [comment] 2021-03-25 22:41
Hi @INDEPENDENTENTERPRISE1 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 22:41 UTC
Labels: has feedback
