### ISSUE TITLE
Email notifications not working with multiple emails

### ISSUE THREAD

**Issue by rkhoury82** [woocommerce/woocommerce#27266] opened 2020-08-09 10:38 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When sending Email notifications for New Order, Cancelled Order & Failed Order using multiple email address and separating by a comma does not work as expected.

- it seems if 1 of the email is the WordPress Admin email address it wont send it to that email and in some cases it wont send to either address. 
If the Admin email is on its own it works as expected. 

**Expected behavior**
Emails are sent to both email address

**Actual behavior**

My testing on my production site and another clean install show that either 1 of 2 behaviors.  
- The email is not delivered to any of the email addresses set in settings
- The email is sent to only to the email that is not the Administration Email Address of Wordpress.

I have confirmed the email are not stuck in Junk or Quarantine  - The email did NOT make it to the server
I have confirmed this is not a SMTP error by checking the logs - The email did NOT make it to the SMTP server

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Go to 'woocommerce -> settings -> email'
2. Click on 'New order notification '
3. Add two email address in Recipient(s) 
[a]- Try 1 as the wordpress admin email + 1 other
[b]- Try only the admin email address
[c]- Try un related email address
4. Send test "new order" notification on the above scenarios

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-08-13 18:45
Hi @rkhoury82,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

I've tried the cases you suggested:

<hr>

**Case 1: 1 admin email + 2 non-admin emails:**

I set up 3 email addresses to receive new order notification email:

![3emails](https://user-images.githubusercontent.com/19143190/90172586-3e085d80-dd71-11ea-8277-d1b2bb93d3e7.jpg)

Next, I placed a new order on the site and confirmed that all 3 email addresses received the new order email notification:

![email1](https://user-images.githubusercontent.com/19143190/90173005-c5ee6780-dd71-11ea-8b7f-c42f36871b73.jpg)

![email2](https://user-images.githubusercontent.com/19143190/90173017-c8e95800-dd71-11ea-990d-44327fa93e19.jpg)

![email3](https://user-images.githubusercontent.com/19143190/90173025-cc7cdf00-dd71-11ea-8b14-2a34efada0a0.jpg)

<hr>

**Case 2: 1 admin email:**

I set up 1 admin email addresses to receive new order notification email:

![2email](https://user-images.githubusercontent.com/19143190/90173225-2087c380-dd72-11ea-9c30-c7299f80b69a.jpg)

Next, I placed a new order on the site and confirmed that 1 admin email addresses received the new order email notification:

![email11](https://user-images.githubusercontent.com/19143190/90173514-8aa06880-dd72-11ea-8cbc-bb8411a1214a.jpg)

<hr>

**Case 3: 1 non-admin email:**

I set up 1 non-admin email addresses to receive new order notification email:

![email22](https://user-images.githubusercontent.com/19143190/90173652-c9ceb980-dd72-11ea-8641-70ebf609c8d5.jpg)

Next, I placed a new order on the site and confirmed that 1 non-admin email addresses received the new order email notification:

![email4](https://user-images.githubusercontent.com/19143190/90173833-05698380-dd73-11ea-981d-5246de471041.jpg)

<hr>

WooCommerce, and most plugins sending email, send mail by using the `wp_mail()` function that is a core function of WordPress.

In most cases, if email is not being sent/received, then the issue is not with WooCommerce itself, but with the core email function on your web host. Read on for solutions to common issues.

https://docs.woocommerce.com/document/email-faq/

We won't be able to troubleshoot this further with you as we don't consider this to be a bug. 

Alternatively, you can also do one of the following:

- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-08-13 18:45 UTC

**Comment by bozzmedia** [comment] 2020-10-12 21:16
I realize this is closed but I wanted to share I am also experiencing this issue recently. Multiple emails come out with \n in the recipient list.  ("tech@example.com,\n name@example.com,\n anothername@example.com")  This has only presented as an issue after recent Woo updates.

Additionally, the default emoji "Congratulations on the sale. [clap emoji]" was causing new order notification emails to not process or send email. Removing the emoji helped, but I can't figure out the issue with parsing multiple emails. @juliaamosova did you ever find resolution to the multiple senders issue? Thanks.

**Comment by injamulhaque535** [comment] 2020-10-16 15:53
I am unable to add more than three emails in this woocommerce email setting separated by a comma.
When I add more than three emails then wordpress is stopped sending emails to all emails.
Do you have any solution for adding more than three emails in the woocommerce for getting order notification email etc?

**Comment by fabienrodrigues** [comment] 2021-02-01 11:12
@injamulhaque535, @rkhoury82, did you get a solution ?
It seems that I have same trouble since the last update of Woocommerce.
I have 5 recipients for the new order notification. According to my client, it worked well before.

**Comment by bozzmedia** [comment] 2021-02-01 21:24
In our case the hosting provider has blacklisted our mail sending so only some mail was getting through. Definitely install a mail logging plugin to figure out what's going on and then check with your provider. Other than that you can try switching your mail delivery provider or setting up a proper smtp account for mail routing. Good luck.

**Comment by aureliendebord** [comment] 2021-03-03 08:06
Same problem here: I have three emails, the email for a new order is only sent to the first email.
I have installed the plugin Log emails to check that. No log for the second and the third recipient. So the email function is not trigerred.
This problem occurs some weeks ago, it is maybe related to a previous update.

**Comment by tammullen** [comment] 2021-03-08 19:17
Hi @fabienrodrigues @bozzmedia @aureliendebord 

See: https://github.com/woocommerce/woocommerce/issues/29107

If any of you are using WPML there is a known issue that can affect emails.

**Comment by lorenzoAWD** [comment] 2021-03-12 11:43
Problem solved with new version of WPML
https://wpml.org/forums/topic/woocommerce-multilingual-conflict-with-woocommerce-new-order-email/
