### ISSUE TITLE
Backorders are set to 'not allowed' but stock goes to -1 when customers ordering at the same time 

### ISSUE THREAD

**Issue by Lippiun** [woocommerce/woocommerce#22521] opened 2019-01-22 12:00 UTC
Hello,

I've created a single product with the stock quantity set to 5 and backorders 'not allowed'. I tested the checkout process using two separate computers, both logged in as separate users and both adding 3 of the same product into the cart. I then clicked 'Proceed to checkout' at the same time on both computers and the order went through on both of them with x3 quantity. I then checked my orders screen in the admin section and the product now has a stock of -1. 

Why is this happening? Surely if backorders aren't allowed it should alert one of the customers before they proceed to checkout? Otherwise, I will now have to manually refund one of the orders and deciding which one to refund is impossible as they both ordered at the same time.

**Comment by rrennick** [comment] 2019-01-22 12:41
What is your hold stock setting (Settings->Products->Inventory)?

**Comment by Lippiun** [comment] 2019-01-22 13:01
Hi rrennick, the hold stock setting is set to 60 minutes

**Comment by rrennick** [comment] 2019-01-22 14:03
@Lippiun Thanks for the quick followup.

> Surely if backorders aren't allowed it should alert one of the customers before they proceed to checkout?

The items are removed from inventory when the order is created during the checkout process. What allows this to happen if the first customer is still processing payment when the second starts processing payment the stock is still available for the second customer. 

I'll leave this open for feedback from one of the other core devs but I'm not sure there is anything that can be done in core to completely eliminate conditions where this might occur.

You could try https://wordpress.org/plugins/woocommerce-cart-stock-reducer/ to hold the stock while it's in the cart.

**Comment by mikejolley** [comment] 2019-02-04 15:55
Duplicate of https://github.com/woocommerce/woocommerce/issues/22118

**Closed by mikejolley** 2019-02-04 15:55 UTC
Labels: status: needs feedback
