### ISSUE TITLE
Declined Card Error Message is not shown on checkout page.

### ISSUE THREAD

**Issue by mukhthar** [woocommerce/woocommerce#22054] opened 2018-11-27 06:36 UTC
**Describe the bug**
When a customer uses a declined card for payment, An error message should be there to make aware  the customer that the card is declined. When I used a declined card for payment after submission of card its redirected to the checkout page and the error message in cart-error.php was shown.
Screenshot of Checkout page: http://prntscr.com/lng0vl
The default error message is shown in /cart page. But customer retries to do the payment unaware of card decline and they are confused about the cart error message.
Screenshot of cart page:http://prntscr.com/lng0vl
**To Reproduce**
1. Checkout an order with a declined credit card
2. The default cart-error.php error message is shown on the checkout page.
3. Navigate to cart page, our expected error message is on cart page.

**Screenshots**
Screenshot of Checkout page: http://prntscr.com/lng0vl
Screenshot of cart page:http://prntscr.com/lng0vl
**Expected behavior**
The Error message shown on the cart page is expected to be on the checkout page, which will make the customer aware that the card is declined.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://wordpress-151096-474718.cloudwaysapps.com
Site URL: http://wordpress-151096-474718.cloudwaysapps.com
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.20-1+0~20180910100430.3+jessie~1.gbp17c613 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 80 MB
PHP Time Limit: 8500
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 128.73MB
Database Data Size: 69.43MB
Database Index Size: 59.30MB
wp_woocommerce_sessions: Data: 2.52MB + Index: 0.05MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.45MB
wp_woocommerce_order_itemmeta: Data: 7.52MB + Index: 9.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
sib_model_contact: Data: 0.02MB + Index: 0.00MB
sib_model_country: Data: 0.02MB + Index: 0.00MB
smackuci_events: Data: 0.02MB + Index: 0.00MB
smackuci_history: Data: 0.02MB + Index: 0.00MB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wp_automatewoo_abandoned_carts: Data: 0.13MB + Index: 0.08MB
wp_automatewoo_customers: Data: 0.27MB + Index: 0.50MB
wp_automatewoo_guests: Data: 0.31MB + Index: 0.28MB
wp_automatewoo_guest_meta: Data: 1.52MB + Index: 1.98MB
wp_automatewoo_logs: Data: 0.22MB + Index: 0.41MB
wp_automatewoo_log_meta: Data: 1.52MB + Index: 3.03MB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.06MB
wp_commentmeta: Data: 0.36MB + Index: 0.36MB
wp_comments: Data: 6.52MB + Index: 8.08MB
wp_cp_calculated_fields_form_discount_codes: Data: 0.02MB + Index: 0.00MB
wp_cp_calculated_fields_form_posts: Data: 0.02MB + Index: 0.00MB
wp_cp_calculated_fields_form_revision: Data: 0.02MB + Index: 0.00MB
wp_cp_calculated_fields_form_settings: Data: 0.02MB + Index: 0.00MB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB
wp_et_bloom_stats: Data: 0.02MB + Index: 0.00MB
wp_et_social_stats: Data: 0.02MB + Index: 0.00MB
wp_ewwwio_images: Data: 0.45MB + Index: 0.45MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_formmaker: Data: 0.08MB + Index: 0.00MB
wp_formmaker_backup: Data: 0.08MB + Index: 0.00MB
wp_formmaker_blocked: Data: 0.02MB + Index: 0.00MB
wp_formmaker_display_options: Data: 0.02MB + Index: 0.02MB
wp_formmaker_groups: Data: 0.02MB + Index: 0.00MB
wp_formmaker_query: Data: 0.02MB + Index: 0.00MB
wp_formmaker_sessions: Data: 0.02MB + Index: 0.00MB
wp_formmaker_submits: Data: 0.45MB + Index: 0.00MB
wp_formmaker_themes: Data: 0.14MB + Index: 0.00MB
wp_formmaker_views: Data: 0.02MB + Index: 0.00MB
wp_hidemysiteSecure: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.19MB + Index: 0.00MB
wp_options: Data: 1.52MB + Index: 0.08MB
wp_postmeta: Data: 22.56MB + Index: 27.09MB
wp_posts: Data: 16.52MB + Index: 1.45MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_ultimate_csv_importer_log_values: Data: 0.02MB + Index: 0.00MB
wp_ultimate_csv_importer_manageshortcodes: Data: 0.02MB + Index: 0.00MB
wp_ultimate_csv_importer_shortcodes_statusrel: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 3.52MB + Index: 5.03MB
wp_users: Data: 0.19MB + Index: 0.17MB
wp_wcpdf_invoice_number: Data: 0.11MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

acf: 5
attachment: 416
aw_workflow: 4
custom_css: 3
customize_changeset: 15
et_pb_layout: 7
fmemailverification: 1
form-maker: 1
nav_menu_item: 32
page: 38
post: 9
product: 110
product_variation: 1829
revision: 617
shipping_package: 3
shop_coupon: 81
shop_order: 4064
shop_order_refund: 146

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

PayPal for WooCommerce: by Angell EYE – 1.5.3
WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)


### WC Pages ###

Shop base: #42 - /products-list/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by hannahswain** [comment] 2018-11-27 10:03
The behavior of how cards are handled is managed by the payment gateway, in this case 'PayPal for WooCommerce: by Angell EYE – 1.5.3'  You'll want to have a chat with the Angell EYE team.

If you'd like to confirm, try the Stripe plugin (the sandbox is easy to set up) and see what happens when you check out. 
https://wordpress.org/plugins/woocommerce-gateway-stripe/

**Comment by Nigelje** [comment] 2018-11-27 23:58
I can confirm the same issue happens with braintree. A failed card payment directs to cart-errors.php. As the wc_print_notices() has been removed and the error text changed. This leads to a very confusing situation for the customer. There is no indication that it's an issue with the card and the error text will make the customer thinks its a site issue.

**Comment by sandrodz** [comment] 2018-11-28 06:46
this is a duplicate of #22048

**Comment by jjcoffee** [comment] 2018-12-11 16:04
I can confirm that this happens with Stripe too, see this issue https://github.com/woocommerce/woocommerce/issues/21861

The issue is with checkout reload, i.e. if ajax is turned off, or if new users are auto-created at checkout (thus mandating a reload). I've identified the probable root cause to be the removal of wc_print_notices() here https://github.com/woocommerce/woocommerce/commit/efe06cb14752bdfe2c18274783eac221cbeea5ff#diff-e0339102757f25bb408b014dbef0ee41L221 
On reload the checkout has nowhere to output errors, since errors aren't output or cleared, it defaults to redirecting to the (rather unhelpful!) cart-errors.php

**Comment by mikejolley** [comment] 2019-01-10 14:49
Will be fixed in https://github.com/woocommerce/woocommerce/pull/22337

**Closed by mikejolley** 2019-01-10 14:49 UTC
