### ISSUE TITLE
select2: Wrong top position when a toolbar is active

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce#28996] opened 2021-02-02 01:39 UTC
When a toolbar is active on the site, select2 element calculates a wrong top position. As a result, it covers select element. The issue is gone when a toolbar is disabled on the site (_Users > Profile > Show Toolbar when viewing site_).

The issue happens on Checkout and My Account pages. It's possible that other sections/pages that use select2 have the same problem.

**Screenshots:**

Active toolbar:

![Select2 issue](https://snipboard.io/JqnZtW.jpg)

Inactive toolbar:

![Select2 issue](https://snipboard.io/AP5a8y.jpg)

WordPress: **v5.7-alpha-50026**
WooCommerce: **v4.9.2**
Storefront (theme): **v3.4.0**

**Comment by siliconforks** [comment] 2021-02-03 03:07
It seems that this issue is caused by the WordPress upgrade to jQuery 3.

If I revert to jQuery 1.12.4 (e.g., using the [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin), the problem disappears.

**Comment by juliaamosova** [comment] 2021-02-03 21:34
Hi @dashkevych,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

With toolbar active:

![with](https://user-images.githubusercontent.com/19143190/106812375-92fca080-663d-11eb-8466-c1c35cb69e9c.jpg)

Without toolbar:

![without](https://user-images.githubusercontent.com/19143190/106812389-9728be00-663d-11eb-9c4d-5d3efe79e173.jpg)

Noting also that I can reproduce this with WordPress 5.6 + WooCommerce 4.9.2.

**Comment by roykho** [comment] 2021-03-17 12:40
Closed via #29397

**Comment by afagard** [comment] 2021-09-09 05:45
@roykho Still seeing the issue in WordPress 5.8.1 and Woo 5.6.0. Whenever admin bar is active select2 gets all wonky as demonstrated above. I literally thought I was going insane when styling, until I disabled every plugin and went to a standard theme and then had the epiphany to google the issue. 

Obviously not that big of a deal for regular customers.

**Comment by roykho** [comment] 2021-09-09 12:49
Yeah somehow the fix got overwritten by this PR here https://github.com/woocommerce/woocommerce/pull/29706

**Closed** 2021-09-10 12:32 UTC
Labels: type: bug, priority: high, component: checkout

**Comment by PhilMakower** [comment] 2022-08-12 09:35
https://github.com/woocommerce/selectWoo/issues/41#issuecomment-1212904598

Commenting here since this actually relates to WooCommerce itself

I have come across the same issue on some pages in WordPress v6.0.1 and WooCommerce 6.8.0.
There is no longer "admin-bar" class added to BODY when the admin bar appears, so the above styles don't help!
select2.full.js?ver=4.0.3-wc.6.8.0 does NOT contain the attachBody fixes from https://github.com/woocommerce/selectWoo/pull/49/files
Applying these 2 changes fixes the issue.

**Comment by barryhughes** [comment] 2022-08-12 15:35
Hi @PhilMakower,

It appears to work when I test it on a page with the admin bar—but perhaps I need to look on a specific page to see the problem?  Since this issue was closed, it would be best to [create a fresh issue](https://github.com/woocommerce/woocommerce/issues/new/choose) and include steps-to-replicate so the team can re-evaluate.

Thanks!

*Edit: I see https://github.com/woocommerce/woocommerce/issues/34304 was already created: some steps to replicate (with details such as which page this can be seen on) could still be helpful.*
