### ISSUE TITLE
Thumbnails Size Not Accurate on Ver 3.6.1

### ISSUE THREAD

**Issue by malihamannanss** [woocommerce/woocommerce#23369] opened 2019-04-18 12:06 UTC
Updating the plugin to its latest version 3.6.1 has caused the thumbnails to not show up properly. The sizes are showing differently for different products, even though they're all the same size and set to show at a certain ratio. Had to rollback to 3.5.8. Please see screenshot. (Correct size is the rectangular size).

![screencapture-thesideblogger-shop-2019-04-18-06_02_12](https://user-images.githubusercontent.com/30187474/56359893-1a92ca00-61a0-11e9-8253-8fc8cc339c26.png)

**Comment by mikejolley** [comment] 2019-04-18 12:27
After updates, particular from themes, if the config changes then thumbnails may be regenerated. At which point a notice appears in admin.  Until this finishes, thumbnails may not appear correctly sized. As you've rolled back, this now won't happen.

Also to note, if the images are uploaded smaller than the target dimensions (e.g. too short or too narrow) no resize will occur. This logic was fixed in 3.6 to prevent images being resized on every request. If you're seeing slow shop page loading times on 3.5.8, you're affected.

I don't think we can do much here without more information anyhow, or an example site running 3.6.

**Comment by PaulKaan** [comment] 2019-04-18 12:39
I am having the same issue. How can I check if the regen is finished?

**Comment by mikejolley** [comment] 2019-04-18 12:50
@PaulKaan on what page? I don't see odd thumbnails there.

Not the database update, there is a separate notice when thumbnails are being regenerated. and that only affects products, not other post types.

**Comment by PaulKaan** [comment] 2019-04-18 12:53
The thumbnails should be 3 across and larger when there are 3 and 2 across and even larger when there are only two on desktop https://wined.dmctest.com.au/special-offers/roagna-pushing-the-boundaries-the-2013s-are-coming/

I haven't received a notice about thumbnail regen should I Woocommerce > Status > Tools and regen there?

**Comment by mikejolley** [comment] 2019-04-18 12:56
@PaulKaan Those inline galleries don't appear to have anything to do with WooCommerce and are using standard thumbnail sizing in Settings > Media.

**Comment by PaulKaan** [comment] 2019-04-18 12:58
Strange I've rolled back to Woocommerce 3.5.8 and it fixes all the issues and go back to 3.6.1 and they come back.

All of our product page customisation has been lost too.

**Comment by mikejolley** [comment] 2019-04-18 13:06
@PaulKaan it won't help, I can see in the source it's using `gallery-size-thumbnail` which is not a WooCommerce image size. Assuming we're looking at the same thing here..

**Comment by PaulKaan** [comment] 2019-04-18 13:08
Given the page I directed you to we will be looking at the same thing. Odd that the update impacted it, even on blog posts.

**Comment by mikejolley** [comment] 2019-04-18 14:06
@malihamannanss Do you have a staging site to run 3.6 on so we can view the shop page? Can you add your status report?

**Comment by PaulKaan** [comment] 2019-04-18 14:18
Yes the staging site is https://wined.dmctest.com.au/ it's running 3.6.1 it's a bit messy been playing with an affiliate wp solution I can give you access if it would help

**Comment by PaulKaan** [comment] 2019-04-18 14:19
Status Report:

`
### WordPress Environment ###

WordPress address (URL): https://wined.dmctest.com.au
Site address (URL): https://wined.dmctest.com.au
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.17
PHP Post Max Size: 20 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
cURL Version: 7.64.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔ 4 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔ 0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔ Create a new google contact and add to Wine Decoded Customers Group
Zapier Feed #1 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/ffoylv/
Zapier Feed #1 Trigger: ✔ New Customer
Zapier Feed #1 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/ffoylv/.
Zapier Feed #2 Name: ✔ Payment is received send SMS
Zapier Feed #2 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/ffoe7j/
Zapier Feed #2 Trigger: ✔ New Order Status Change
Zapier Feed #2 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/ffoe7j/.
Zapier Feed #3 Name: ✔ New Order add to list
Zapier Feed #3 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/ffovu4/
Zapier Feed #3 Trigger: ✔ New Order
Zapier Feed #3 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/ffovu4/.
Zapier Feed #4 Name: ✔ Add Customers to Group
Zapier Feed #4 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/aywc1u/
Zapier Feed #4 Trigger: ✔ New Customer
Zapier Feed #4 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/aywc1u/.

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
Total Database Size: 148.38MB
Database Data Size: 115.63MB
Database Index Size: 32.75MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 1.03MB + Index: 1.06MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 1.52MB + Index: 2.11MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_affiliatemeta: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_affiliates: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_creatives: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_customermeta: Data: 0.00MB + Index: 0.01MB
wp_affiliate_wp_customers: Data: 0.00MB + Index: 0.01MB
wp_affiliate_wp_payouts: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_referrals: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_rest_consumers: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_visits: Data: 0.00MB + Index: 0.00MB
wp_affwp_zapier_logs: Data: 0.01MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 1.02MB + Index: 0.09MB
wp_ewwwio_images: Data: 5.52MB + Index: 6.06MB
wp_ewwwio_queue: Data: 0.00MB + Index: 0.00MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.00MB + Index: 0.00MB
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB
wp_gf_entry: Data: 0.07MB + Index: 0.01MB
wp_gf_entry_meta: Data: 0.40MB + Index: 0.27MB
wp_gf_entry_notes: Data: 0.00MB + Index: 0.00MB
wp_gf_form: Data: 0.01MB + Index: 0.00MB
wp_gf_form_meta: Data: 1.90MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB
wp_gf_form_view: Data: 1.47MB + Index: 0.67MB
wp_glossary_related: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 60.44MB + Index: 0.11MB
wp_postmeta: Data: 21.52MB + Index: 17.92MB
wp_posts: Data: 13.34MB + Index: 1.97MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_rcp_discounts: Data: 0.00MB + Index: 0.00MB
wp_rcp_payments: Data: 0.00MB + Index: 0.00MB
wp_rcp_payment_meta: Data: 0.00MB + Index: 0.00MB
wp_rcp_subscription_level_meta: Data: 0.00MB + Index: 0.00MB
wp_redirection_404: Data: 1.25MB + Index: 0.29MB
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB
wp_redirection_items: Data: 0.00MB + Index: 0.02MB
wp_redirection_logs: Data: 0.01MB + Index: 0.01MB
wp_restrict_content_pro: Data: 0.00MB + Index: 0.00MB
wp_rg_form: Data: 0.00MB + Index: 0.00MB
wp_rg_form_meta: Data: 1.00MB + Index: 0.00MB
wp_rg_form_view: Data: 0.48MB + Index: 0.22MB
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB
wp_rg_lead: Data: 0.03MB + Index: 0.01MB
wp_rg_lead_detail: Data: 0.08MB + Index: 0.12MB
wp_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.07MB + Index: 0.02MB
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
wp_say_what_available_strings: Data: 0.45MB + Index: 0.00MB
wp_say_what_strings: Data: 0.01MB + Index: 0.00MB
wp_say_what_wildcards: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.16MB + Index: 0.20MB
wp_terms: Data: 0.11MB + Index: 0.13MB
wp_term_relationships: Data: 0.48MB + Index: 0.44MB
wp_term_taxonomy: Data: 0.20MB + Index: 0.16MB
wp_usermeta: Data: 1.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.10MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_bundled_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.01MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.61MB + Index: 0.11MB
wp_yoast_seo_meta: Data: 0.18MB + Index: 0.19MB

### Post Type Counts ###

acf-field: 147
acf-field-group: 25
attachment: 3043
course: 1
dmc_slider: 1
dmc-offer: 119
dmc-slider: 1
glossary: 47
jetpack-testimonial: 7
lesson: 6
nav_menu_item: 45
oembed_cache: 172
page: 37
post: 113
product: 853
product_variation: 267
quiz: 6
revision: 6
scheduled-action: 147
shop_coupon: 27
shop_order: 18
wc_membership_plan: 3
wc_user_membership: 356
wc_zapier_feed: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (52) ###

Query Monitor: by John Blackbourn – 3.3.4
VaultPress: by Automattic – 1.9.10
Gravity Forms: by rocketgenius – 2.4.8
CM Tooltip Glossary Ecommerce: by CreativeMindsSolutions – 3.8.13
Admin Columns Pro - Advanced Custom Fields (ACF): by Admin Columns – 2.5.2
Admin Columns Pro - WooCommerce: by Admin Columns – 3.3.2 – Not tested with the active version of WooCommerce
Advanced Custom Fields: Gravityforms Add-on: by Danny van Holten – 1.2.1
Advanced Custom Fields: Smart Button: by Gilles Goetsch – 1.0.0
Advanced Custom Fields: Theme Code Pro: by hookturn – 2.3.0
Admin Columns Pro: by AdminColumns.com – 4.5.7
Advanced Custom Fields PRO: by Elliot Condon – 5.7.13
AffiliateWP - Lifetime Commissions: by AffiliateWP – 1.3.2
AffiliateWP: by AffiliateWP
LLC – 2.2.15

AffiliateWP - Affiliate Area Shortcodes: by AffiliateWP
LLC – 1.1.7

AffiliateWP - Affiliate Area Tabs: by AffiliateWP – 1.2.7
AffiliateWP - Force Pending Referrals: by AffiliateWP – 1.0
AffiliateWP - REST API Extended: by AffiliateWP
LLC – 1.0.4

AffiliateWP - Signup Referrals: by Pippin Williamson and Andrew Munro – 1.0.2
AffiliateWP - Store Credit: by AffiliateWP
LLC – 2.3.2

Akismet Anti-Spam: by Automattic – 4.1.1
Classic Editor: by WordPress Contributors – 1.4
Debug: by SoniNow Team – 1.8
EWWW Image Optimizer: by Exactly WWW – 4.7.2
Force Strong Passwords: by Jason Cosper – 1.8.0
Gravity Forms MailChimp Add-On: by rocketgenius – 4.6
Jetpack by WordPress.com: by Automattic – 7.2.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
Post Duplicator: by Metaphor Creations – 2.20
Redirection: by John Godley – 4.2.3
Reduce stock of manual orders for WooCommerce: by Claudio Sanches – 2.0.0 – Not tested with the active version of WooCommerce
Say What? Pro: by Lee Willis – 2.3.0
Sensei: by Automattic – 2.0.0-beta.2
Simple Custom Post Order: by Colorlib – 2.4.3
WC Variations Ajax Fix: by Travis Buck – 1.4
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.18
WooCommerce Cost of Goods: by SkyVerge – 2.8.2
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.15 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.9
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.8 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.13.0
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.6
WooCommerce Mix and Match: by Kathy Darling – 1.5.0
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.6.3
WooCommerce Product Add-ons: by WooCommerce – 3.0.11
WooCommerce Smart Coupons: by StoreApps – 4.0.3 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.11 – Not tested with the active version of WooCommerce
WooCommerce Zapier Integration: by OM4 – 1.8.3
WooCommerce: by Automattic – 3.6.1
WP Max Submit Protect: by Academe Computing – 1.1.2 – Not tested with the active version of WooCommerce
Wined Mix and Match: by Oscar Gare – 1.2.0

### Inactive Plugins (32) ###

AffiliateWP - Affiliate Dashboard Sharing: by AffiliateWP – 1.1.6
AffiliateWP - Affiliate Forms For Gravity Forms: by AffiliateWP
LLC – 1.0.17

AffiliateWP - Affiliate Landing Pages: by AffiliateWP
LLC – 1.0.2

AffiliateWP - Affiliate Product Rates: by Pippin Williamson and Andrew Munro – 1.0.4
AffiliateWP - Custom Affiliate Slugs: by Pippin Williamson and Andrew Munro – 1.0.2
AffiliateWP - Limit Referrals set to 2 by Paul Kaan: by Andrew Munro
Sumobi – 1.0

AffiliateWP - Show Affiliate Coupons: by AffiliateWP – 1.0.7
AffiliateWP - Tiered Rates: by AffiliateWP – 1.1.2
AffiliateWP - Zapier - Automated Tasks: by AffiliateWP – 1.1.2
AffiliateWP Mailchimp Add-on: by Tunbosun Ayinla – 1.2.0
CM Tooltip Glossary Custom Taxonomies: by CreativeMindsSolutions – 1.0.3
Debug Bar: by wordpressdotorg – 1.0
Google Universal Analytics: by Audrius Dobilinskas – 2.4.3
MailChimp For WooCommerce (Wine Decoded FIX): by Phil Kurth – 0.1 – Not tested with the active version of WooCommerce
Metorik Helper: by Metorik – 1.1.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.0
Sensei: by WooCommerce – 1.9.17
Sensei Content Drip: by WooThemes – 1.0.8
Sensei Course Progress: by WooThemes – 1.0.6
Sensei Media Attachments: by WooThemes – 1.0.0
Wine Decoded | HoneyBadger Integration: by Phil Kurth –
WooCommerce Blocks: by Automattic – 1.4.0 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.8.6
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.11
WooCommerce Product Bundles: by SomewhereWarm – 5.8.0 – Not tested with the active version of WooCommerce
WooCommerce Shippit: by Shippit Pty Ltd – 1.4.7 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.5 – Not tested with the active version of WooCommerce
WP Migrate DB Pro: by Delicious Brains – 1.9.5
WP Migrate DB Pro Theme & Plugin Files: by Delicious Brains – 1.0.5
WP Rocket: by WP Media – 3.2.6
WP Thumb: by Human Made Limited – 0.10
Yoast SEO: by Team Yoast – 11.0 – Not tested with the active version of WooCommerce

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (2) ###

load.php: by  –
ManageWP - Worker Loader: by GoDaddy –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #25 - /terms-conditions/

### Theme ###

Name: Grunterie
Version: 5.0.0
Author URL: http://georgespake.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: wined/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.6.0
wined/woocommerce/content-single-product.php version 3.4.0 is out of date. The core version is 3.6.0
wined/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.3.0
wined/woocommerce/loop/loop-end.php
wined/woocommerce/loop/loop-start.php
wined/woocommerce/single-product/add-to-cart/simple.php version 3.0.0 is out of date. The core version is 3.4.0
wined/woocommerce/single-product/price.php

Outdated Templates: ❌
					
					
						Learn how to update

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 3
The MEGA List for those who applied for the 2013 Produttori Cru Offer:: Members: 21Access method: Manual assignment onlyAccess length: Unlimited
Wine Decoded Wine Bites Subscription:: Members: 2Access method: Manual assignment onlyAccess length: Unlimited
Free for all our Wine Decoded Members:: Members: 333Access method: User account registrationAccess length: Unlimited

### Mix and Match Products ###

Template Overrides: –

### Action Scheduler ###

Complete: 146
Oldest: 2019-03-24 14:54:28 +1100
Newest: 2019-04-18 22:44:17 +1000

Pending: 1
Oldest: 2019-04-25 12:31:38 +1000
Newest: 2019-04-25 12:31:38 +1000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by PaulKaan** [comment] 2019-04-18 14:23
I'll be getting the Dev Team to check the changelog for 3.6 against our work and look at template file changes, deprecated functions and methods.

**Comment by PaulKaan** [comment] 2019-04-18 14:25
This is an example product page on staging https://wined.dmctest.com.au/product/cos-cerasuolo-di-vittoria-classico-2015/

This is how it looks on live woocommerce 3.5.8 (and on staging when rolled back to 3.5.8)

https://winedecoded.com.au/product/cos-cerasuolo-di-vittoria-classico-2015/

**Comment by mikejolley** [comment] 2019-04-18 14:36
@PaulKaan looks like yours is caused by missing class names http://take.ms/RojQ3

Find your single-product template if it's part of your theme and share what code is there.

**Comment by PaulKaan** [comment] 2019-04-18 14:42
Thanks @mikejolley I'll have to get my Dev's to do that. They wisely apply some limitations to my access. We'll maintain 3.5.8 on live and come back to you to confirm.

**Comment by mikejolley** [comment] 2019-04-18 14:58
@PaulKaan ok. FWIW core outputs classes like this `<?php wc_product_class( '', $product ); ?>`. And classes are ran through the 'post_class' filter. So I'm thinking either ^ that code is missing, or something is filtering out all classes via the filter.

This is off-topic though, the OP posted an issue about thumbnail sizes, not missing post classes.

**Comment by malihamannanss** [comment] 2019-04-18 15:06
@mikejolley here it is: https://staging2.thesideblogger.com/shop/

**Comment by mikejolley** [comment] 2019-04-18 15:16
@malihamannanss In the customizer, WooCommerce > Product Images, what does your setup look like there?  I wonder if it's hard cropping to 400x400 on purpose.

**Comment by mikejolley** [comment] 2019-04-18 15:25
@malihamannanss on this staging site, if you go to WooCommerce > Status > Tools and click "Regenerate shop thumbnails", when that finishes see if the thumbs change. I don't know if maybe some images are missing so it's falling back to what exists (400x400).

**Comment by malihamannanss** [comment] 2019-04-18 15:30
OK, so, that didn't do anything, but in the customizer, I unchecked the "custom" ratio and checked "uncropped" instead, and everything is looking perfect!

**Comment by mikejolley** [comment] 2019-04-18 15:40
@malihamannanss just so I can look into this as a possible issue anyway, to confirm you were using 'custom' ratio of 91:70, and what were the dimensions of the original images? (both those working and those not working)

**Comment by malihamannanss** [comment] 2019-04-18 15:51
**All original product images are 1820px by 1400px.**

BEFORE:
In the customizer, "Main Image Width" and "Thumbnail Width" were set to 1200px (so that cropping will create images no less than 1200px wide). "Thumbnail Cropping" was set to "Custom" with a ratio of 91:70 - to imitate 1820x1400.

NOW:
In the customizer, "Main Image Width" and "Thumbnail Width" are still set to 1200px, but under the "Thumbnail Cropping", the option is now "uncropped".

Here's what the customizer settings look like now:
![Customize- Products-All-Hidden - The Side Blogger 4-18-2019 9-43-40 AM](https://user-images.githubusercontent.com/30187474/56374006-7ae53400-61bf-11e9-89d0-23b4d9814069.png)

**Comment by mikejolley** [comment] 2019-04-18 16:03
@malihamannanss oddly mine are resizing ok. I notice some are jpg and some are png however- is there a pattern between those which didn't resize and filetype?

**Comment by malihamannanss** [comment] 2019-04-18 16:08
Just compared and looks like while all the photos that were properly cropping maintaining the aspect ratio were all PNG type, some of the ones that were hard-cropping to 400x400px were also PNG...

So, no, the file type had nothing to do with it.

**Comment by mikejolley** [comment] 2019-04-18 17:32
Ok. In my own tests, all images seem to be regenerating to the correct sizes using aspect ratios. Since the uncropped setting worked for you I think we can close this but if you want to share access to staging where this is broken so we can do proper debugging, I'd be happy to try that next week (if so please create a ticket on the helpdesk and reference this issue so they can assign to me https://woocommerce.com/contact-us/)

Thanks 👍

**Closed by mikejolley** 2019-04-18 17:32 UTC
Labels: status: needs feedback
