### ISSUE TITLE
Wrong Api

### ISSUE THREAD

**Issue by hovozaroyan** [woocommerce/woocommerce#27479] opened 2020-08-25 16:20 UTC
Hey,

You have very good product, but very very bad api.

Could you please explain me how  multiple different plugins can work with this hook http://prntscr.com/u5ory0 . Let's say all plugins want to modify  the product title in archive page,all of them will have to do echo? the result will be 3 title in the page and similiar all hooks(20-30) http://prntscr.com/u5ot8q. It means multiply different plugins never can work with your plugin or they have to write a ton of hacks,which is also doesn't give any guarantee that it will work.

FYI: To fix it you just need to call filter on that actions.

**Comment by tammullen** [comment] 2020-08-26 16:34
Hi @hovozaroyan 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

If this is a bug report can you fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

*Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
A clear and concise description of what the bug is. 

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate issues. 
Without this report we won't be able to fully evaluate this issue.

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it into the issue.

**Comment by hovozaroyan** [comment] 2020-08-26 17:07
Hey @tammullen ,

Please explain me how to override the product title in archive page using your api?

If it's impossible to do, only using your hooks, doesn't it mean, that is bug?

Example: Let's say we have plugin "A" and "B"

1. Plugin "A"  want to override the product title html and has this code:

remove_action( 'woocommerce_shop_loop_item_title', 'woocommerce_template_loop_product_title', 10 );
add_action('woocommerce_shop_loop_item_title',function(){
echo '<a href="linkA">'.get_the_title().'</a>';
});


2. Plugin "B"  want to override the product title html and has this code:

remove_action( 'woocommerce_shop_loop_item_title', 'woocommerce_template_loop_product_title', 10 );
add_action('woocommerce_shop_loop_item_title',function(){
echo '<a href="linkB">'.get_the_title().'</a>';
});

The result will be 2 title. 

Please tell me how they will work together?

**Comment by tammullen** [comment] 2021-03-25 20:53
Hi @hovozaroyan 

Sorry for the delay in replying

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 20:53 UTC
Labels: has feedback
