### ISSUE TITLE
Shop_manager role 

### ISSUE THREAD

**Issue by thesiteowner** [woocommerce/woocommerce#29062] opened 2021-02-08 21:39 UTC
Hello, I have the latest version of woocommerce.
I add my worker to new sites and in one of them, he is able to add product and see all features in the Screen Options tab, on the other website he has the same role as Shop Manager but he can press on Screen Options and he is not able to see a short description of a product!
Where is the problem can I know?

**Comment by tammullen** [comment] 2021-02-11 18:02
Hi @thesiteowner 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-02-11 18:02 UTC
