### ISSUE TITLE
Available stock not purchasable when On-Hold to Pending Payment

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce#26652] opened 2020-06-01 10:49 UTC
**Describe the bug**

When changing an order status from On-Hold to Pending, the stock will be restocked but the quantity isn't reflected on the front-end of the site and unable to be purchased.

I'm unsure how to better title this to capture this better so I'll walk through the flow.

**To Reproduce**
1. Have a product with stock management enabled. Set stock as 10
2. Enable the BACS payment gateway
3. Purchase a number of the product via that payment gateway, such as 3
4. See stock of product is 7 on front-end and back-end
5. Check order and note stock shows reduced as expected `Stock levels reduced: Belt (woo-belt) 10→7`
6. Update order to Pending Payment
7. Note stock increase `Stock levels increased: Belt (woo-belt) 7→10`
8. Confirm stock is showing as 10 on product on front-end and back-end
9. Try to add more stock than the inital order made available, i.e `8`.
10. Notice error: `Sorry, we do not have enough "Belt" in stock to fulfill your order (7 available). We apologise for any inconvenience caused.`
11. There are zero Scheduled Actions - until the `woocommerce_cancel_unpaid_orders` Cron event is run or the order is moved to Failed / Cancelled - the replenished stock from this original order won't be fully available.

**Screenshots**

Gif showing this in action - https://d.pr/i/EAGbkQ

**Expected behavior**

Stock status should be reflected across the site. If the stock level is 10, 10 should be available to be purchased.

I've looked through some existing issues and found some related but not identical
#22644
#24528

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://core.doug.press
Site address (URL): https://core.doug.press
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.6
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.70.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Total Database Size: 5.11MB
Database Data Size: 3.55MB
Database Index Size: 1.56MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.38MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 0.42MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 50
custom_css: 2
customize_changeset: 6
global_product_addon: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
nav_menu_item: 7
page: 13
post: 3
product: 29
product_variation: 12
revision: 49
shop_coupon: 2
shop_order: 24

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Blocks: by Automattic – 2.6.0 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce: by Automattic – 4.1.1
WP Mail Logging: by MailPoet – 1.9.6

### Inactive Plugins (10) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Classic Editor: by WordPress Contributors – 1.5
Disable Emails: by WebAware – 1.6.3
Gutenberg: by Gutenberg Team – 8.1.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 8.5
Site Kit by Google: by Google – 1.8.1
WooCommerce Admin: by WooCommerce – 1.1.3
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.1.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 44
Oldest: 2020-05-06 10:22:35 +0000
Newest: 2020-06-01 10:21:45 +0000

Pending: 1
Oldest: 2020-06-02 09:07:09 +0000
Newest: 2020-06-02 09:07:09 +0000

```
</details>

**Comment by tammullen** [comment] 2020-06-01 19:26
​Hi @dougaitken 
Thank you for raising the issue! 
I can’t seem to reproduce the issue using the steps you provided in 4.1.1 or 4.2 RC.2
![Screenshot 2020-06-01 at 20 07 39](https://user-images.githubusercontent.com/24649833/83445821-9b189680-a445-11ea-837b-398540988616.png)
I saw the notes & inventory update like in your example 
![Screenshot 2020-06-01 at 20 07 00](https://user-images.githubusercontent.com/24649833/83445831-9eac1d80-a445-11ea-92f5-293f661fd960.png)
But I was able to make a purchase ok with no errors when trying the higher amount

> Try to add more stock than the inital order made available, i.e 8. 


![Screenshot 2020-06-01 at 20 15 19](https://user-images.githubusercontent.com/24649833/83446078-082c2c00-a446-11ea-9126-c9eb7154b702.png)

FWIW I didn't have a Hold stock time specified. Did you have this set?

**Comment by dougaitken** [comment] 2020-06-02 05:34
Interesting! 

Yes, I have 60 minutes for that, so since you have it blank, the stock is never held, which I guess points to the cause of what is happening to the initial stock.

**Comment by RichBurgie** [comment] 2020-06-17 10:25
​Hi @dougaitken

Has there been any movement here?

Regards
Richard

**Comment by dougaitken** [comment] 2020-06-17 10:39
No movement yet @RichBurgie - can you confirm what your “Hold Stock” is set to? I believe the cause has specific requirements as @tammullen mentioned he couldn’t replicate when Hold Stock was blank

**Comment by RichBurgie** [comment] 2020-06-17 10:45
Hold stock is set to 30. As you correctly say, I would image that is hold stock is not set, stock doesn't get affected so this issue is a not triggered.

**Comment by dougaitken** [comment] 2020-06-19 14:26
@tammullen Can you retest with hold stock minutes defined, please? Thanks

**Comment by juliaamosova** [comment] 2020-10-14 22:11
Hi @dougaitken,

Apologies for the delayed response here. I retested this with the `Hold stock (minutes)` set to 30 and I indeed could reproduce the issue. I made a gif to document what I saw after I placed an initial order for 3 items:

http://g.recordit.co/kVkj3eJbML.gif

This seems like a high priority issue to me as it affects placing an order using BACS and has to do with inventory - both could be common flows for WooCommerce merchants. 

We’re going to work on this issue as soon as possible.

**Comment by roykho** [comment] 2020-11-13 14:14
Hmm, I am not so sure this is an issue? If I am reading this correctly, it is by design? Because if you have "hold stock" time limit set, then it means any pending orders ( unpaid orders ) will still hold the stock for X amount of time ( whatever is set in the setting ). So even if you flip "on-hold" to "pending", that "hold stock" time limit is still in effect so will hold the stock until expired.

Or am I missing something?

**Comment by peterfabian** [comment] 2020-11-13 16:08
I agree that it probably works as intended, but I also think our 'hold stock' feature is making people confused. 

Maybe we should add some ways to surface this info to shop admins? 

E.g. the note
> Note stock increase Stock levels increased: Belt (woo-belt) 7→10
could also say that the 3 items are held for X minutes for the payment

...and the stock level in _product edit_ screen could show how many items are held temporarily, etc. Maybe we can check with folks from design?

**Comment by vedanshujain** [comment] 2021-02-15 14:18
I am closing the issue based on above comments, and have opened another one which scopes tracking held stocks and surfacing that information to merchant in https://github.com/woocommerce/woocommerce/issues/29132

**Closed by vedanshujain** 2021-02-15 14:18 UTC
Labels: component: payment, component: stock, priority: high, type: bug
