### ISSUE TITLE
billing_first_name and billing_last_name not saved during checkout process

### ISSUE THREAD

**Issue by elliottcoe** [woocommerce/woocommerce#19464] opened 2018-03-20 10:36 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a billing form which has billing_first_name and billing_last_name as an option.
2. When submitting the billing form it does a get request to /checkout/?page=pay and then the billing address information is posted to an Ajax endpoint where the information is saved, this endpoint doesn't save billing name.
3. When you process your payment, billing_first_name  and billing_last_name are empty so it shows validation errors.
4. I expect to see first_name and last_name populated in the wp_woocommerce_sessions but it isn't.
5. How do I get it to populate billing_first_name and billing_last_name?

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment] 2018-03-20 16:18
The pay page does not update addresses or process fields. It assumes the order already contains all address information. This will not change until the checkout process is redesigned in #10672

Also, pay page is not ajax powered by default so this is also custom (?).

This would have to be handled entirely by custom code (get values from form fields, handle and save somewhere when the form is processed).

Closing as this is not a bug - it's just not supported functionality.

Thanks

**Closed by mikejolley** 2018-03-20 16:18 UTC

**Comment by leup** [comment] 2018-04-19 12:09
I had some king of similar issues and I ended to add a hook to save theses fields myself like this:

https://gist.github.com/leup/c35c0930b13d18697d266fa7a4f6d3b9

Not sure if this is the right way to do it properly.
