### ISSUE TITLE
Stock status is incorrect when variations have stock

### ISSUE THREAD

**Issue by dejury** [woocommerce/woocommerce#26086] opened 2020-04-06 14:57 UTC
**Describe the bug**
I think this covers the bugreport #26071 which is incomplete.

I am currently working on a new woocommerce webshop which fills the products using the REST API. All products have variations, with stock managed on variation level. Backorders are possible if the stock is 0 for certain products.

When I login into the Woocommerce backend, the product overview is showing incorrect stock_status in some cases. For example when I have a product with 10 sizes, only 1 size is available. The status is "Out of stock". When I try to edit the product and click on Update (without changing a thing) the stock_status is right afterwards, it shows "In stock". The product still shows up in the "Out of stock filter". See screenshot attached.

So in my opinion, there is something wrong in updating the stock statuses. I can't figure out where it is going wrong, it seems that manually updating via product edit page is not even fixing the complete issue.

**To Reproduce**
1. Go to Products (backend)
2. See the overview, some products have "Out of stock"
3. Edit out of stock product by just clicking "Update" button
4. In overview, stock status is right, but it still shows up when you filter on "Out of stock" products.

**Screenshots**
![product_overview](https://user-images.githubusercontent.com/16034333/78572092-4da5f180-7827-11ea-8e69-775e15c449bc.png)

**Expected behavior**
Show the right stock status.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): xxx
Site address (URL): xxx
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (IUS) OpenSSL/1.0.2k-fips
PHP Version: 7.2.27
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.12-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: eK6U2e_
Totale databasegrootte: 308.95MB
Database datagrootte: 205.66MB
Database index grootte: 103.29MB
eK6U2e_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eK6U2e_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eK6U2e_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
eK6U2e_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
eK6U2e_ajaxsearchpro: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_ajaxsearchpro_priorities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_ajaxsearchpro_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_asp_index: Data: 42.58MB + Index: 45.75MB + Engine InnoDB
eK6U2e_asp_synonyms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
eK6U2e_itsec_distributed_storage: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
eK6U2e_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_itsec_lockouts: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
eK6U2e_itsec_logs: Data: 3.52MB + Index: 2.63MB + Engine InnoDB
eK6U2e_itsec_temp: Data: 0.48MB + Index: 0.83MB + Engine InnoDB
eK6U2e_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nextend2_smartslider3_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nextend2_smartslider3_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_action_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_field_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_form_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_object_meta: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_nf3_upgrades: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
eK6U2e_options: Data: 10.06MB + Index: 1.14MB + Engine InnoDB
eK6U2e_postmeta: Data: 103.61MB + Index: 38.92MB + Engine InnoDB
eK6U2e_posts: Data: 22.50MB + Index: 4.84MB + Engine InnoDB
eK6U2e_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
eK6U2e_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_revslider_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
eK6U2e_revslider_slides: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
eK6U2e_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_termmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
eK6U2e_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_term_relationships: Data: 4.52MB + Index: 2.52MB + Engine InnoDB
eK6U2e_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_usermeta: Data: 1.14MB + Index: 0.06MB + Engine InnoDB
eK6U2e_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eK6U2e_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eK6U2e_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eK6U2e_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_wc_product_meta_lookup: Data: 2.42MB + Index: 4.80MB + Engine InnoDB
eK6U2e_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_woocommerce_gzd_dhl_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_gzd_dhl_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_gzd_shipmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_gzd_shipments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_gzd_shipment_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_woocommerce_gzd_shipment_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eK6U2e_woocommerce_gzd_shipping_provider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eK6U2e_woocommerce_gzd_shipping_providermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eK6U2e_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eK6U2e_yoast_seo_links: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
eK6U2e_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 422
br_labels: 5
cmm4e_menu: 14
cmm4e_menu_location: 1
cmm4e_menu_theme: 3
custom_css: 3
customize_changeset: 4
elementor_font: 1
elementor_library: 23
nav_menu_item: 151
oembed_cache: 7
page: 76
post: 27
product: 1529
product_variation: 12981
revision: 1590
shop_coupon: 1
shop_order: 12
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: door Automattic – 4.0.1

### Inactive Plugins (42) ###

301 Redirects: door WebFactory Ltd – 2.45
Advanced AJAX Product Filters for WooCommerce: door BeRocket – 1.4.2.2
Advanced Custom Fields: door Elliot Condon – 5.8.9
AJAX Search for WooCommerce: door Damian Góra – 1.6.3
Ajax Search Pro: door Ernest Marcinko – 4.17.6
Akismet Anti-Spam: door Automattic – 4.1.4
Application Passwords: door George Stephanis – 0.1.1
Breadcrumb NavXT: door John Havlik – 6.4.0
Classic Editor: door WordPress Contributors – 1.5
Clever Mega Menu Pro for Elementor: door CleverSoft – 1.0.6
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: door SeedProd – 5.1.0
Cookie Notice: door dFactory – 1.2.51
Custom Product Tabs for WooCommerce: door YIKES
Inc. – 1.7.1

DHL for WooCommerce: door DHL – 1.6.8
Display Posts: door Bill Erickson – 3.0.2
Duplicate Page: door mndpsingh287 – 4.2
Elementor: door Elementor.com – 2.9.7
Elementor Pro: door Elementor.com – 2.8.4
F&J webcreation Login Screen: door F&J webcreation – 1.1.1
Germanized for WooCommerce: door Vendidero – 3.1.4
Google Tag Manager for Wordpress: door Thomas Geiger – 1.11.4
iThemes Security Pro: door iThemes – 5.9.5
Kirki Customizer Framework: door Ari Stathopoulos (@aristath) – 3.1.1
Klarna Checkout for WooCommerce: door Krokedil – 2.0.8
Klarna Order Management for WooCommerce: door klarna
krokedil – 1.3.0 – Niet getest met de actieve versie van WooCommerce

Loco Translate: door Tim Whitlock – 2.3.2
Ninja Forms: door Saturday Drive – 3.4.24.1
Slider Revolution: door ThemePunch – 5.4.8.3
SVG Support: door Benbodhi – 2.3.18
Transients Manager: door Pippin Williamson – 1.8
Widget CSS Classes: door C.M. Kendrick – 1.5.4
xxx: door X6 – 1.0.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Advanced Product Labels: door BeRocket – 1.1.16.4
WooCommerce Blocks: door Automattic – 2.5.15
WooCommerce Load More Products: door BeRocket – 1.1.7
WooCommerce PayPal Checkout Gateway: door WooCommerce – 1.6.20 – Niet getest met de actieve versie van WooCommerce
WooCommerce Services: door Automattic – 1.22.5
WP Media folder: door Joomunited – 4.8.2
WP Rocket: door WP Media – 3.5.2
WP SEO Structured Data Schema: door WPSEMPlugins – 2.6.12
Yoast SEO: door Team Yoast – 13.4.1
Yoast SEO Premium: door Team Yoast – 13.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

Bedrock Autoloader: door Roots – 1.0.0
Disallow Indexing: door Roots – 1.0.0
Register Theme Directory: door Roots – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Winkelbasis: #7 - /shop/
Winkelmand: #8 - /shoppingcart/
Afrekenen: #9 - /checkout/
Mijn account: #10 - /my-account/
Algemene voorwaarden: #90795 - /terms/

### Theme ###

Name: xxx
Version: 1.0.0
Author URL: https://www.x6.nl
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: xxx/resources/views/woocommerce/archive-product.blade.php
xxx/resources/views/woocommerce/cart/cart.blade.php
xxx/resources/views/woocommerce/checkout/form-checkout.blade.php
xxx/resources/views/woocommerce/content-product.blade.php
xxx/resources/views/woocommerce/loop/orderby.blade.php
xxx/resources/views/woocommerce/loop/sale-flash.blade.php
xxx/resources/views/woocommerce/single-product/add-to-cart/variation.blade.php
xxx/resources/views/woocommerce/single-product/product-attributes.blade.php
xxx/resources/views/woocommerce/single-product/product-image.blade.php versie - is verouderd. De hoofdversie is 3.5.1
xxx/resources/views/woocommerce/single-product/tabs/tabs.blade.php
xxx/resources/views/woocommerce/single-product/up-sells.blade.php
xxx/resources/views/woocommerce/single-product.blade.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Action Scheduler ###

Afgerond: 168
Oldest: 2020-03-06 15:34:59 +0000
Newest: 2020-04-06 14:52:13 +0000

In afwachting: 2
Oldest: 2020-04-10 16:55:00 +0000
Newest: 2020-04-10 16:55:00 +0000

`
```
</details>

**Comment by mickaelperrin** [comment] 2020-04-17 13:36
@dejury Ensure that you have regenerated the meta lookup cache : 

WooCommerce > Status > Tools > Product lookup tables

or 

```
wp wc tool run regenerate_product_lookup_tables --user=ANY_ADMIN_USER_ID
```

**Comment by juliaamosova** [comment] 2020-05-14 21:51
Hi @dejury,

Apologies for the delayed response here! I followed the steps you provided but could not reproduce the issue (using WooCommerce 4.2 beta):

See gif: https://recordit.co/Splsr6RAoG

Are you still experiencing this issue?

**Comment by mickaelperrin** [comment] 2020-05-15 08:20
@juliaamosova We experienced this issue recently after a woocommerce upgrade.

It looks like the new lookup tables had run out of sync. Changes were not reflected in that table.

By running a cache clear of the lookup table everything went fine.

**Comment by vedanshujain** [comment] 2020-05-22 14:13
>  I can't figure out where it is going wrong, it seems that manually updating via product edit page is not even fixing the complete issue.

It looks like you came across this issue while updating manually on the site: #25843. Basically if you update the stock status of a variable product, it will be changed for all its variations as well which looks like is what you faced. 

We are also improving filters for variable products in #26260 as a response to #25524.

I am closing this issue because it looks like you were able to resolve by updating the lookup table, and the original issue is already reported and being worked upon. That said, feel free to comment back if this needs additional discussion and we will re-open and re-investigate, or you can also join the discussion in any of the above-linked issues/PRs.

**Closed by vedanshujain** 2020-05-22 14:13 UTC
Labels: status: needs feedback

**Comment by msgloucester** [comment] 2021-05-05 12:15
I don't know if this is exactly the same issue, but I'm experiencing this discrepancy with just simple products. The discrepancy in my case has the following cause: the dashboard correctly reports all low stock products, but the filtered view of low stock products (which you see if you click on the dashboard's indicator) under-reports low stock products because it fails to include products whose stock is low because a low stock threshold for that individual product has been set, which is lower than the site-wide default threshold. This happens with Woocommerce 5.2.2 both with and without the plugin Woocommerce Admin active (which I thought could influence the reporting).

My site's specific example: My site-wide threshold is 10. I have set the threshold to 1 for two products, whose actual stock levels are 2 and 3 (i.e., less than the site-wide default of 10). Dashboard reports two low-stock products. Clicking into that dashboard widget, zero low-stock products are shown (this is correct). If I change stock levels of one/both products to numbers above 10, the dashboard reports 1/0 low stock products.
