### ISSUE TITLE
I cannot add any new products or edit any of my existing products on my website?  I get a 500 Internal server Error

### ISSUE THREAD

**Issue by naturallyfit** [woocommerce/woocommerce#26473] opened 2020-05-12 20:10 UTC
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by juliaamosova** [comment] 2020-05-12 21:16
Hi @naturallyfit,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

In addition to the above, I recommend you contact your hosting company and have them take a look. They will also be able to provide you with the server error log that should help understand what caused the issue. 

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-05-12 21:16 UTC

**Comment by galbaras** [comment] 2020-05-14 03:33
A 500 error should be seen in error_log or wp-admin/error_log.

If you've just updated WooCommerce, there may have been a problem with the installation, so try re-uploading WooCommerce via FTP.

**Comment by naturallyfit** [comment] 2020-05-14 18:05
ok great! thank you. i appreciate you getting back with me.
