### ISSUE TITLE
Number of purchased items is zero in reports in 3.5.0-rc.2

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#21597] opened 2018-10-17 04:49 UTC
**Describe the bug**
If a product is selling with a decimal amount, the number of purchased item will not be counted.

**To Reproduce**
1. Create an order with a product and set the amount < 1 like 0.5
2. Open the sales by date report
3. The items purchased field is 0

**Screenshots**
<img width="1080" alt="grafik" src="https://user-images.githubusercontent.com/25877146/47062820-8340c000-d1d8-11e8-884f-ea78982e92c3.png">

**Expected behavior**
The items purchased field should reflect the number of items regardless of the amount.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

Startseiten-URL.: https://beta.firewoodshop.ch
Seiten-URL.: https://beta.firewoodshop.ch
WooCommerce Version.: 3.5.0
Protokoll-Verzeichnis: /home/zuegerpi/www/beta.firewoodshop.ch/wp-content/uploads/wc-logs/
Ist das Protokoll-Verzeichnis beschreibbar?: yes
WordPress Version.: 4.9.8
Ist es eine WordPress Multisite?: no
WordPress Speicher-Limit.: 536870912
Ist der WordPress Debug Modus aktiviert?: yes
Sind WordPress Cron Jobs aktiviert?: yes
WordPress Sprache.: de_CH
External object cache: no
Server Info.: Apache/2.4
PHP Version.: 7.2.11
PHP max. post Grösse.: 16777216
PHP max. Ausführungszeit.: 30
PHP max input vars.: 1000
cURL Version.: 7.61.1, OpenSSL/1.0.2p
Ist SUHOSIN installiert?: no
Maximale Uploadgrösse.: 16777216
MySQL Version.: 5.5.5
MySQL-Versions-String.: 5.5.5-10.1.35-MariaDB
Standard-Zeitzone.: UTC
Ist fsockopen/cURL aktiviert?: yes
Ist die SoapClient Klasse aktiviert?: yes
Ist die DomDocument Klasse aktiviert?: yes
Ist GZip aktiviert?: yes
Ist mbstring aktiviert?: yes
Remote POST erfolgreich?: yes
Remote-POST Antwort.: 200
Remote GET erfolgreich?: yes
Remote-GET Antwort.: 200

### Plugins ###

WooCommerce Advanced Product Labels: by BeRocket - 1.1.11 - Not tested with the active version of WooCommerce
Classic Editor: by WordPress Contributors - 0.4 - 
Contact Form 7: by Takayuki Miyoshi - 5.0.4 - 
Disable Emails: by WebAware - 1.3.0 - 
Email Address Encoder: by Till Krüss - 1.0.7 - 
WooCommerce Delivery Slots by Iconic: by Iconic - 1.7.12 - Not tested with the active version of WooCommerce
Limit Login Attempts Reloaded: by wpchefgadget - 2.7.1 - 
Storefront Powerpack: by WooCommerce - 1.4.12 - 
WooCommerce Custom Invoice BACS Gateway: by Thomas Zueger - 1.0.4 - Not tested with the active version of WooCommerce
WooCommerce Round Numbers: by Thomas Zueger - 1.2 - Not tested with the active version of WooCommerce
WooCommerce Shop Helper: by Thomas Zueger - 1.2 - Not tested with the active version of WooCommerce
User Switching: by John Blackbourn &amp; contributors - 1.4.0 - 
WooCommerce Dynamic Pricing &amp; Discounts: by RightPress - 2.2.8 - Not tested with the active version of WooCommerce
Mindestbestellmenge: by Morning Train Technologies ApS - 2.3.0 - Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani - 2.2.1 - Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping Zones: by Jeroen Sormani - 1.1.2 - Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping: by Jeroen Sormani - 1.0.14 - Not tested with the active version of WooCommerce
WooCommerce Beta Tester: by WooCommerce - 2.0.0 - Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce - 4.1.10 - Not tested with the active version of WooCommerce
WooCommerce PDF Invoices &amp; Packing Slips: by Ewout Fernhout - 2.2.1 - Not tested with the active version of WooCommerce
WooCommerce PDF Invoices &amp; Packing Slips Premium Templates: by Ewout Fernhout - 2.5.7 - Not tested with the active version of WooCommerce
WooCommerce TM Extra Product Options: by themeComplete - 4.6.9.4 - Not tested with the active version of WooCommerce
WooCommerce: by Automattic - 3.5.0-rc.2 - 
REST API Log: by Pete Nelson - 1.6.5 - 

### Theme ###

Name: Storefront Child Theme
Version: 1.0
Author URL: http://woothemes.com
Child Theme: YesParent theme name: Storefront
Parent theme version: 2.3.4
Parent theme author URL: https://woocommerce.com/

WooCommerce Support: Yes

</details>

**Comment by rodrigoprimo** [comment] 2018-10-18 11:35
I was not able to reproduce this issue. Using the sample products, I set "T-Shirt with Logo" price to 0.5:

![screenshot from 2018-10-18 08-27-08](https://user-images.githubusercontent.com/77215/47151601-97f08700-d2b0-11e8-8b09-b6f901f096bd.png)

Then I placed an order for this product:

![screenshot from 2018-10-18 08-29-21](https://user-images.githubusercontent.com/77215/47151396-03862480-d2b0-11e8-8ccd-b92cbea2f71a.png)

The sales by date report display the correct number of items purchased (the order that I placed for this test is the only order placed today):

![screenshot from 2018-10-18 08-31-28](https://user-images.githubusercontent.com/77215/47151591-8ad39800-d2b0-11e8-8636-4d9d5a6ffdb3.png)

Did I miss something? Are you able to reproduce this issue when only WooCommerce is active to rule out the possibility of conflicts with other plugins?

**Comment by claudiulodro** [comment] 2018-10-18 18:01
I believe the issue is around partial product quantities, which is not an official supported core feature.

**Comment by rodrigoprimo** [comment] 2018-10-19 13:11
You are probably right, @clauduilodro. On a clean WC install, I can't set a partial produc quantity. Closing this issue as it doesn't seem to be something supported by core. @thomas-zg please provide more details if we missed something.

**Closed by rodrigoprimo** 2018-10-19 13:11 UTC
Labels: status: needs feedback

**Comment by thomas-zg** [comment] 2018-10-19 17:51
Any plans to support partial product quantities by core? Tried on a clean install and can confirm that partial product quantity can't set.

**Comment by claudiulodro** [comment] 2018-10-19 18:05
Fractional quantities won't be supported as part of core. This is the domain of extensions (and there are extensions already available that add this support). See http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3089452-fractional-partial-quantities
