### ISSUE TITLE
Rounding is off in manual orders

### ISSUE THREAD

**Issue by thuautp** [woocommerce/woocommerce#25748] opened 2020-02-25 09:18 UTC
**Describe the bug**

When adding items to a manual order that are tax excluded, with option `Round tax at subtotal level, instead of rounding per line` checked, total amount is off by 1 cent while it shows the correct amount for a normal order on the site.

**To Reproduce**
1. Settings: 2dp, `Round tax at subtotal level, instead of rounding per line` checked and price entered excluding tax:
<img width="753" alt="Screen Shot 2020-02-25 at 4 13 49 PM" src="https://user-images.githubusercontent.com/13119409/75232534-fb19f400-57e9-11ea-8d04-a6682c95adec.png">
<img width="418" alt="Screen Shot 2020-02-25 at 4 13 55 PM" src="https://user-images.githubusercontent.com/13119409/75232537-fc4b2100-57e9-11ea-8c22-a2a58fae1cc4.png">

2. Add these items to a manual order:

<img width="799" alt="Screen Shot 2020-02-25 at 4 14 23 PM" src="https://user-images.githubusercontent.com/13119409/75232562-066d1f80-57ea-11ea-98d6-03206153528f.png">

3. See that the total is $40.36, while it's $40.3535, which should be rounded up to $40.35

<img width="327" alt="Screen Shot 2020-02-25 at 4 14 32 PM" src="https://user-images.githubusercontent.com/13119409/75232636-23095780-57ea-11ea-87ca-a803af474ed0.png">

4. Place a test order by adding these items to cart and check out
5. See that the total amount from the order is $40.35, which is what it should be:

<img width="824" alt="Screen Shot 2020-02-25 at 4 14 43 PM" src="https://user-images.githubusercontent.com/13119409/75232722-4cc27e80-57ea-11ea-9aa6-80a571fc8812.png">

**Expected behavior**
The total in the manual order is $40.36, while it's $40.3535, which should be rounded up to $40.35 as seen in the normal order

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-02-25 14:16
Hi @thuautp,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end with WC 4.0 beta1. 

**Tax Settings:**

<img width="682" alt="Screen Shot 2020-02-25 at 9 08 38 AM" src="https://user-images.githubusercontent.com/19143190/75254577-93928300-57ae-11ea-8cd8-34b119690c63.png">

**Standard Tax Rate - 21% (applied to shipping as well):**

<img width="1437" alt="Screen Shot 2020-02-25 at 9 08 50 AM" src="https://user-images.githubusercontent.com/19143190/75254627-a0af7200-57ae-11ea-87fd-e71dc63b523d.png">

**Manual Order - $40.36:**

![manual](https://user-images.githubusercontent.com/19143190/75254952-2af7d600-57af-11ea-8d67-4191fde8ef0f.jpg)

**Order placed on the site - cart - $40.35:**

![cart](https://user-images.githubusercontent.com/19143190/75254998-41059680-57af-11ea-8e01-89c02c18c627.jpg)

**Order placed on the site - Thank you page - $40.35:**

![thankyoupage](https://user-images.githubusercontent.com/19143190/75255049-55e22a00-57af-11ea-9e35-8e6c7ec5e210.jpg)

**Order placed on the site - wc-admin - $40.35:**

![backend](https://user-images.githubusercontent.com/19143190/75255068-5ed2fb80-57af-11ea-936c-fad099b8af9d.jpg)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by vedanshujain** [comment] 2020-04-06 19:23
Fixed via #25800

**Closed by vedanshujain** 2020-04-06 19:23 UTC
Labels: bug, component: calculation, component: tax, has pull request, priority: high
