### ISSUE TITLE
Missing Attributes/Variations Problem

### ISSUE THREAD

**Issue by lifekings89** [woocommerce/woocommerce#21338] opened 2018-09-12 21:00 UTC
**Describe the bug**
I have a woo commerce store. I have lots of products where my attributes and variations were created for products and they have been perfectly fine after being published.

However, recently, I have noticed that once a product gets edited, and re published again, some attributes and variations vanish. It can be very random but in the attributes section - the attributes are missing. However, in variations, you can see they existed before.

**To Reproduce**
1. Go to '.WooCommerce, Products.'
2. Click on '..Create a Variable Product, add the attributes and variations, fill in the details as if it was a real plugin. Then publish the product. Then use a different browser or private browsing, and find that product, and re-edit the item. Then click publish. Then re open the product.
3. Scroll down to '..Attributes.. You will see that they are either completely missing or some attributes are missing'. If you go to variations, you will see the original variations are there, but the attributes are missing.

**Expected behavior**
What should happen is that all the attributes and variations should remain.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Latest version

**Comment by BernardoLima** [comment] 2018-10-24 23:53
Same here.. could devs take a look on this?
Thanks!

**Comment by manwenick** [comment] 2018-10-29 17:58
Hello there, I have the same problem after update to 3.5.0
I also can reproduce with the same steps as @lifekings89 has mentioned above.
Theme: OceanWP

**Comment by GlennMartin1** [comment] 2018-11-03 12:53
Exact same issue here, except I am unable to confirm if this is only since 3.5.

In fact, 5 months ago it was an issue for this user:
https://wordpress.org/support/topic/product-attributes-disappeared/

For me, it was remedied by the tip given by in that thread where it says:
> Solution is to add new random attribute in products > attributes and after I have done that all my old attributes and variations were back.

Clearly a WC bug somewhere.

**Comment by GlennMartin1** [comment] 2018-11-03 17:30
@lifekings89 
As I mentioned, I found a remedy, and I explained how. The underlying bug exists, not sure how to reproduce.

I have never edited any theme files. I use **Storefront**, with the Woo child-theme **Homestore**.

Homestore has one template override out of the box: `homestore/woocommerce/single-product/title.php`

**Comment by lifekings89** [comment] 2018-11-03 20:06
Yes I managed to find a fix overall for the issue by resetting anything which changes a function file in any of the templates

That gets around the issue of adding your own extra attribute

**Comment by GlennMartin1** [comment] 2018-11-03 20:09
@lifekings89
Meaning, it's probably my child theme to blame?

**Comment by lifekings89** [comment] 2018-11-03 21:19
Potentially - disable the child theme and see if it’s still there on the standard theme

**Comment by kloon** [comment] 2018-11-15 10:52
Please test properly by disabling all plugins, even official ones, except WooCommerce and switch your theme to Twentyseventeen.

As it stands now I am unable to replicate this on a standard WooCommerce install with Twentyseventeen so will be closing. If anyone can provide detailed steps to reproduce this then please provide it and I will gladly reopen the issue for further investigation.

**Closed by kloon** 2018-11-15 10:52 UTC
