### ISSUE TITLE
Add a separate price for the category / product

### ISSUE THREAD

**Issue by duongnhatvu2811** [woocommerce/woocommerce#28999] opened 2021-02-02 08:41 UTC
I need a plugin or code that may charge a separate fee per category

Example: I sell souvenirs. There are 2 types of product: 1 is pre-packaged product, and 2 is selected and packaged product. So I want "Selected and Packaged Products" to be added with a price tag of $ 10 for a souvenir pack.

So what should I do?

**Comment by EdithAllison** [comment] 2021-02-02 15:36
I recommend you check out "Variable product types". So you'd have 1 parent product; with 2 variations; each with its own stock, price and SKU. See [https://docs.woocommerce.com/document/variable-product/](https://docs.woocommerce.com/document/variable-product/)

**Comment by duongnhatvu2811** [comment] 2021-02-02 16:16
Sorry, I have been thinking about this issue, but I want to add the price of the money each time the customer orders (4 items into a gift box), not the price of each item.
Looks like you were mistaken, because the individual product instead of choosing 4 items gets one gift box, I want to charge an extra $ 10 for packaging.

**Comment by duongnhatvu2811** [comment] 2021-02-02 16:20
Here is the example I need
![Uploading E2D34D58-1725-472A-A350-4DF29F93408A.jpeg…]()

**Comment by juliaamosova** [comment] 2021-02-03 21:24
Hi @duongnhatvu2811,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request/pre-sale question which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-02-03 21:24 UTC
