### ISSUE TITLE
Emoji in "Additional content" field makes it impossible to save changes to WooCommerce emails

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce#24397] opened 2019-08-13 19:26 UTC
**Describe the bug**
Emojis in the "Additional Content" field of a WooCommerce email interfere with updating the email's other fields.

**To Reproduce**
1. Go to **WooCommerce > Settings > Emails > New Order Email**
2. Add text including the emoji  🙌to the "Additional Content" field
3. Save email
4. Change email recipient, save email. **It will appear that the change saved correctly.**
5. Refresh page... recipient will no longer reflect change from step 4

**Screenshots**

![image](https://user-images.githubusercontent.com/20285748/62970703-15582b80-bdde-11e9-994c-ef8f1b3ba20a.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment] 2019-08-16 07:40
Duplicate of #24405. Let's continue discussions there.

Please see tests in that issues, currently unable to replicate that.

**Closed by kloon** 2019-08-16 07:40 UTC
Labels: bug
