### ISSUE TITLE
Cart amount on every button of the site

### ISSUE THREAD

**Issue by robincolbert** [woocommerce/woocommerce#28848] opened 2021-01-19 09:48 UTC
Hello,

I am encountering an issue with my wordpress site, and especially the woocommerce plugin (I did a troubleshoot).

As you can see on the home page or the other pages, every button changes to the cart amount : https://yuman-fit.com/

I can't find the way to correct this new bug.

Does someone know how to find a solution to this issue ?

Best regards,
Robin COLBERT

**Comment by Appelsappel** [comment] 2021-01-19 11:44
I have the same problem

**Comment by ccebreros1** [comment] 2021-01-19 15:59
Me too! I open a ticket and found this issue after. I have some extra info in case that works. Hopefully, they can fix that soon

**Comment by ccebreros1** [comment] 2021-01-19 16:14
I kind of find a workaround for it. I disabled woocommerce, rolled it back to an older version. Rolled back my theme (Astra). Enabled woocommerce and updated it. Updated Astra again

**Comment by zhongruige** [comment] 2021-01-26 21:15
Hi @robincolbert and @Appelsappel,

Closing this as a duplicate of https://github.com/woocommerce/woocommerce/issues/28852

If I can get the same details as requested in https://github.com/woocommerce/woocommerce/issues/28852#issuecomment-767830971 it will help us further troubleshoot. Please post on https://github.com/woocommerce/woocommerce/issues/28852 with those details and we will follow up.

Thanks!

**Closed by zhongruige** 2021-01-26 21:15 UTC
