### ISSUE TITLE
the product gallery is not showing in my woocommerce store

### ISSUE THREAD

**Issue by mokhtarbensaid** [woocommerce/woocommerce#24923] opened 2019-10-29 11:13 UTC
H
![4](https://user-images.githubusercontent.com/38160000/67761971-a4232e80-fa44-11e9-84f6-b9e3d9088cb3.JPG)
![1](https://user-images.githubusercontent.com/38160000/67761974-a4bbc500-fa44-11e9-907b-462be3a3255b.JPG)
![2](https://user-images.githubusercontent.com/38160000/67761975-a4bbc500-fa44-11e9-931d-130995d2b02c.JPG)
![3](https://user-images.githubusercontent.com/38160000/67761976-a4bbc500-fa44-11e9-9062-f81c4a06ba73.JPG)

i 
Help me please i have a problem:
the product gallery is not showing in my woocommerce store https://elitegift.sa 
like the pictures attached

**Comment by mokhtarbensaid** [comment] 2019-10-29 11:15
@mikejolley

**Comment by kloon** [comment] 2019-10-30 13:10
Hi @mokhtarbensaid, you have not completed the system status report or any of the questions that were requested so that makes it difficult for us to assist.

That said, from your screenshots I can clearly see you are using a non-default WooCommerce theme which is overriding the product templates with their own and thus the issue is most likely with your theme.

I suggest you test by disabling all plugins except WooCommerce and then switch your theme to a default one like Twentyseventeen and test again.

I am closing this issue as I am not able to reproduce this but will gladly reopen if you can provide details that are reproducible on a site with just WooCommerce and a default theme.

**Closed by kloon** 2019-10-30 13:10 UTC
