### ISSUE TITLE
Large TM Symbol Next to Shipping Class on Order Emails 

### ISSUE THREAD

**Issue by BeyondMeasureMarket** [woocommerce/woocommerce#25473] opened 2020-01-23 12:18 UTC
There’s a large “TM” on Woo Comemrce Email confirmations in the shipping category.

It says the shipping class and then has a massive “TM” right after it. I have no idea how to remove that.

Here is a link to see an image of the TM I am referring to:

https://ibb.co/RNczkfF

**Comment by claudiosanches** [comment] 2020-01-23 20:12
Hi @BeyondMeasureMarket,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Also it seems like that this issue come from the shipping method that you select, probably better talk with the author/company responsible for the USPS to change it, or maybe you can edit method label/name and remove the `™` symbol.

I'm closing this issue since it seems like the problem is the symbol getting to big in your email client.

**Closed by claudiosanches** 2020-01-23 20:12 UTC

**Comment by agraddy** [comment] 2022-02-01 22:58
If you end up at this issue from searching like me, here are a few links that better explain what is going on and how to resolve it:
https://github.com/woocommerce/woocommerce/issues/17823
https://stackoverflow.com/questions/55905026/tm-symbol-image-instead-of-unicode-special-character-in-woocommerce-emails/55907688
