### ISSUE TITLE
Woocommerce 3.2.1 shipping validation not working

### ISSUE THREAD

**Issue by itsSilver** [woocommerce/woocommerce#17420] opened 2017-10-27 17:42 UTC
Hi there, i updated from 2.6.4 to 3.2.1 and im having an issue with shipping fields . Im runing woocomerce in a booking system and i developed my own payment gateway show is neccesary for that gateway to validate shipping adres , if user is the card holder than the shipping should be the same if not then he will add cardholders information . On website it shows the vields for shipping but when i click to pay with my payment gateway it does not deliver them . it only works if i click force shipping to be as billing address on shipping options , does anyone know how to fix this issue?

**Comment by claudiulodro** [comment] 2017-10-27 20:08
I would try [the forums](https://wordpress.org/support/plugin/woocommerce). There were a lot of changes in 3.0, so most likely your custom gateway is not fully compatible with the latest version of WooCommerce.

Closing this issue because it's not a bug in the core WooCommerce plugin.

**Closed by claudiulodro** 2017-10-27 20:08 UTC

**Comment by itsSilver** [comment] 2017-10-27 22:18
yeah i know that is not a bug but i needed to know how to validate shipping values from shipping_form
