### ISSUE TITLE
I can't adjust number of data in pignation

### ISSUE THREAD

**Issue by remothai** [woocommerce/woocommerce#27353] opened 2020-08-17 13:23 UTC
the default value is 20 numbers of attribute to be shown but I tried adjusting many times but it never changed

**Comment by tammullen** [comment] 2020-08-17 15:58
Hi @remothai 

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​
Label:

**Comment by remothai** [comment] 2020-08-18 03:40
I want to sort product attributes customly but I can't. The pagination,
under the screen option is fixed at 20 items per page.

[image: image.png]
I tried several times putting in more number and less number it didn't
work. I'm not a coder so I don't know where exactly I can get the code to
be reviewed. Please suggest.

ขอบคุณครับ,
*พิชัย*
ฝ่ายขายโรงงาน
*บริษัท ก.เจริญฮาร์ดแวร์ จำกัด*
ผู้จำหน่าย สินค้าหมุนเวียน สกรู และฮาร์ดแวร์ทุกชนิด
 080-582-2929, 02-706-6485 (จ.-ส.)

**Comment by tammullen** [comment] 2021-03-25 20:48
Hi @remothai 

Sorry for the delay in replying

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 20:48 UTC
Labels: has feedback
