### ISSUE TITLE
Can't update the database version

### ISSUE THREAD

**Issue by otpabu** [woocommerce/woocommerce#22477] opened 2019-01-16 10:29 UTC
**Describe the bug**
I'm using WooCommerce 3.5.3, but I've noticed that the database version is still 3.4.7, so I went to WooCommerce -> Status -> Tools and clicked on the button to update the database. It said that the update would be scheduled to be executed in the background, but nothing happened. After a few days and several attempts, the database version is still 3.4.7. There are no scheduled actions anywhere and no logs whatsoever. I'm not sure if this is a bug, or just an issue with my site. If it's just me, can someone provide the SQL query to manually update the database? Thank you.

**To Reproduce**
1. Go to WooCommerce -> Status -> Tools.
2. Click on the button to update the database.
3. A message will be shown, saying that the update will be scheduled to be executed in the background.
4. Nothing happens.

**Expected behavior**
Clicking on the button should immediately update the database.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://www.ottavianobiella.it
Site URL: https://www.ottavianobiella.it
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: ❌ 4.9.8 - È disponibile una versione più recente di WordPress (5.0.3)
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.10-0ubuntu0.18.04.1
PHP Post Max Size: 2 GB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.7.24-0ubuntu0.18.04.1
Max Upload Size: 1.000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.7
WC Database Prefix: ottavianobiella_
Dimensione totale database: 269.71MB
Dimensione dati database: 205.34MB
Dimensione indice database: 64.37MB
ottavianobiella_woocommerce_sessions: Dati: 88.61MB + Indice: 2.52MB
ottavianobiella_woocommerce_api_keys: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_attribute_taxonomies: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_woocommerce_downloadable_product_permissions: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_woocommerce_order_items: Dati: 1.52MB + Indice: 0.31MB
ottavianobiella_woocommerce_order_itemmeta: Dati: 7.52MB + Indice: 6.03MB
ottavianobiella_woocommerce_tax_rates: Dati: 0.02MB + Indice: 0.06MB
ottavianobiella_woocommerce_tax_rate_locations: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_shipping_zones: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_woocommerce_shipping_zone_locations: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_shipping_zone_methods: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_woocommerce_payment_tokens: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_woocommerce_payment_tokenmeta: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_log: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_apto_sort_list: Dati: 0.39MB + Indice: 0.17MB
ottavianobiella_commentmeta: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_comments: Dati: 2.52MB + Indice: 1.36MB
ottavianobiella_ewwwio_images: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_failed_jobs: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_hustle_modules: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_hustle_modules_meta: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_links: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_mailchimp_carts: Dati: 0.28MB + Indice: 0.00MB
ottavianobiella_ms_snippets: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_ngg_album: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_ngg_gallery: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_ngg_pictures: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_offline_giftcard: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_options: Dati: 2.52MB + Indice: 0.36MB
ottavianobiella_pimwick_gift_card: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_pimwick_gift_card_activity: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_postmeta: Dati: 57.58MB + Indice: 30.11MB
ottavianobiella_posts: Dati: 15.52MB + Indice: 3.94MB
ottavianobiella_prli_clicks: Dati: 5.52MB + Indice: 7.91MB
ottavianobiella_prli_groups: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_prli_links: Dati: 0.08MB + Indice: 0.16MB
ottavianobiella_prli_link_metas: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_pum_subscribers: Dati: 0.02MB + Indice: 0.06MB
ottavianobiella_queue: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_sfa_abandoned_carts: Dati: 4.52MB + Indice: 0.00MB
ottavianobiella_snippets: Dati: 0.25MB + Indice: 0.00MB
ottavianobiella_social_users: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_termmeta: Dati: 0.09MB + Indice: 0.11MB
ottavianobiella_terms: Dati: 0.05MB + Indice: 0.03MB
ottavianobiella_term_relationships: Dati: 2.52MB + Indice: 1.52MB
ottavianobiella_term_taxonomy: Dati: 0.17MB + Indice: 0.03MB
ottavianobiella_usermeta: Dati: 9.52MB + Indice: 8.03MB
ottavianobiella_users: Dati: 1.52MB + Indice: 0.42MB
ottavianobiella_wc_download_log: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_wc_webhooks: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_wfBadLeechers: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfBlockedCommentLog: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfBlockedIPLog: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfBlocks7: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_wfConfig: Dati: 0.06MB + Indice: 0.00MB
ottavianobiella_wfCrawlers: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfFileChanges: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfFileMods: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfHits: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_wfHoover: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_wfIssues: Dati: 0.02MB + Indice: 0.06MB
ottavianobiella_wfKnownFileList: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfLeechers: Dati: 2.52MB + Indice: 0.00MB
ottavianobiella_wfLiveTrafficHuman: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_wfLocs: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfLogins: Dati: 0.09MB + Indice: 0.03MB
ottavianobiella_wfNotifications: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfPendingIssues: Dati: 0.02MB + Indice: 0.06MB
ottavianobiella_wfReverseCache: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfScanners: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfSNIPCache: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_wfStatus: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_wfTrafficRates: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfVulnScanners: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_woos_search_analytics: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_woos_search_trends: Dati: 0.16MB + Indice: 0.11MB
ottavianobiella_yith_wcwl: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_yith_wcwl_lists: Dati: 0.05MB + Indice: 0.05MB
ottavianobiella_yoast_seo_links: Dati: 0.27MB + Indice: 0.08MB
ottavianobiella_yoast_seo_meta: Dati: 0.41MB + Indice: 0.00MB

### Post Type Counts ###

apto_sort: 112
attachment: 9746
custom_css: 1
featured_item: 8
giftcard: 1
mc4wp-form: 1
ml-slide: 64
ml-slider: 5
nav_menu_item: 169
ngg_gallery: 9
ngg_pictures: 200
oembed_cache: 145
page: 38
popup: 1
popup_theme: 1
post: 56
product: 6443
product_variation: 5
shop_coupon: 34
shop_order: 3996
shop_order_refund: 2
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Query Monitor: by John Blackbourn & contributors – 3.2.2
Advanced Post Types Order: by Nsp Code – 4.0.9.8
Autoptimize: by Frank Goossens (futtta) – 2.4.4
Better Plugin Compatibility Control: by Oliver Schlöbe – 5.0.0
Cache Enabler: by KeyCDN – 1.3.2
Change Quantity on Checkout for WooCommerce: by Bhavik Kiri – 1.0 – Non testato con la versione attiva di WooCommerce
Code Snippets: by Shea Bunge – 2.13.0
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.50
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Cookie Notice: by dFactory – 1.2.45
Custom Order Status for WooCommerce: by Tyche Softwares – 1.4.6
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.1.6
Envato Market: by Envato – 2.0.1
Feedaty: by Zoorate – 3.0.1 – Non testato con la versione attiva di WooCommerce
FG PrestaShop to WooCommerce Premium: by Frédéric GILLES – 3.39.0 – Non testato con la versione attiva di WooCommerce
Gestpay for WooCommerce: by Axerve (Gruppo Banca Sella) – 20181129
Tradurre con Loco: by Tim Whitlock – 2.2.0
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Non testato con la versione attiva di WooCommerce
MailChimp per Wordpress: by ibericode – 4.3.3
MetaSlider: by Team Updraft – 3.10.3
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.7.0
Popup Maker: by WP Popup Maker – 1.7.30
WooCommerce Product Filter: by Mihajlovic Nenad – 6.6.4
Pretty Links: by Blair Williams – 2.1.7
Tawk.to Live Chat: by Tawkto – 0.3.5
Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.5.1
WC Exporter for Danea - Premium: by ilGhera – 1.1.5
WC Importer for Danea - Premium: by ilGhera – 1.0.2
WooCommerce Product Feed Pro: by WebAppick – 2.2.27 – Non testato con la versione attiva di WooCommerce
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.3.0
Woocommerce Email Verification: by XLPlugins – 3.2.0 – Non testato con la versione attiva di WooCommerce
Woo Preview Emails: by Digamber Pradhan – 1.5.0
Woo Search Box: by Guaven Labs – 2.0.8 – Non testato con la versione attiva di WooCommerce
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.0.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.6
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.14
WooCommerce Ultimate Gift Card: by makewebbetter  – 2.5.1
WooCommerce: by Automattic – 3.5.3
Wordfence Security: by Wordfence – 7.1.20
Yoast SEO: by Team Yoast – 9.4
WP Mail SMTP: by WPForms – 1.4.1
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.0
YITH WooCommerce Wishlist: by YITH – 2.2.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)
wgm_gift_card (wgm_gift_card)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #134 - /negozio/
Carrello: #133 - /carrello/
Cassa: #132 - /cassa/
Il mio account: #131 - /account/
Termini e condizioni: #20 - /condizioni-di-vendita/

### Theme ###

Name: Ottaviano
Version: 1.0
Author URL: https://www.ottavianobiella.it
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.7.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
```
</details>

**Comment by peterfabian** [comment] 2019-01-21 12:12
Hi, 

I've tried this on a clean WP 4.9.8. installation with WC 3.4.7 and then updated to WC 3.5.3 and all went smoothly, so I could not reproduce this, but I've tried on a new site with just a handful of products and orders.

I assume you already tried to upgrade the database with all plugins except for WooCommerce disabled? I would say that is the preferred way, if you haven't tried that already.

Also, have you tried to enable debugging on your WordPress installation? Especially to enable `WP_DEBUG` and `WP_DEBUG_LOG`.

However, there are only a few database commands that are executed to go from 3.4.7 to 3.5.3, so if you want to go down this route, you can see them when you look into `includes/class-wc-install.php`: 
https://github.com/woocommerce/woocommerce/blob/7f78cc3acc102b8d54da813402a379da13f2070b/includes/class-wc-install.php#L116-L122

Then you can look up those functions in `includes/wc-update-functions.php`.

Essentially, there are 3 queries you should run (if I haven't missed anything):

```
UPDATE {$wpdb->prefix}comments JOIN {$wpdb->prefix}posts ON {$wpdb->prefix}posts.ID = {$wpdb->prefix}comments.comment_post_ID AND ( {$wpdb->prefix}posts.post_type = 'product' OR {$wpdb->prefix}posts.post_type = 'product_variation' ) SET {$wpdb->prefix}comments.comment_type = 'review' WHERE {$wpdb->prefix}comments.comment_type = ''
```

If this one returns any results:
```
SELECT CONSTRAINT_NAME
		FROM information_schema.TABLE_CONSTRAINTS
		WHERE CONSTRAINT_SCHEMA = '{$wpdb->dbname}'
		AND CONSTRAINT_NAME = 'fk_wc_download_log_permission_id'
		AND CONSTRAINT_TYPE = 'FOREIGN KEY'
		AND TABLE_NAME = '{$wpdb->prefix}wc_download_log'
```
then you should run this one 
```
ALTER TABLE {$wpdb->prefix}wc_download_log DROP FOREIGN KEY fk_wc_download_log_permission_id
```

```
UPDATE {$wpdb->prefix}options SET {$wpdb->prefix}options.option_value = '3.5.3' WHERE {$wpdb->prefix}options.option_key = 'woocommerce_db_version'
```

I will close this issue for now, but if you manage to find out where the problem was (either via using `WP_DEBUG` or via other means), please let us know.

**Closed by peterfabian** 2019-01-21 12:12 UTC

**Comment by otpabu** [comment] 2019-01-31 14:13
@peterfabian Hi again. Just to let you know, I've enabled WP_DEBUG and WP_DEBUG_LOG and tried updating the database with only StoreFront and WooCommerce enabled. Nothing happened, and there's nothing in the logs nor in scheduled actions. I guess I'll just run the queries you provided.
