### ISSUE TITLE
Downloadable products of HTML files not visible after purchase

### ISSUE THREAD

**Issue by CaldwellYSR** [woocommerce/woocommerce#28325] opened 2020-11-17 19:27 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
`$product->get_downloads()` when logged in as an Administrator returns ` array(1) [WC_Product_Download]` which is correct but when logged in as a Customer the same call with the same products returns `array(0)` This is causing a user with a Customer account to not be able to download any products on orders they have made. This behavior occurs when the downloadable file is an HTML file.

**Expected behavior**
When a Customer purchases a Virtual/Downloadable product they should be able to see downloads. `$product->get_downloads()` should return the an array of downloadable products no matter the logged in user role.

**Actual behavior**
Customer accounts that purchase our product are not able to download anything. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Go to https://products-store.staging2.horseracingnation.com/product/rossi-picks/
2. Select a Race Date and Track, then click Add to Cart
3. Go through checkout process with Test Sandbox Stripe payment gateway.
4. Observe that no downloads are ever shown either on account page, email, or my-account downloads page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://products-store.staging2.horseracingnation.com
Site address (URL): https://products-store.staging2.horseracingnation.com
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.14
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.18
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 8.44MB
Database Data Size: 6.41MB
Database Index Size: 2.03MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.13MB + Index: 0.50MB + Engine InnoDB
wp_posts: Data: 0.31MB + Index: 0.19MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 522
customize_changeset: 12
nav_menu_item: 6
page: 8
post: 3
product: 4
product_variation: 189
revision: 11
shop_order: 25
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (10) ###

JSON Basic Authentication: by WordPress API Team – 0.1
ActiveCampaign for WooCommerce: by ActiveCampaign – 1.2.13 – Installed version not tested with active version of WooCommerce 4.7.0
Advanced Custom Fields: by Elliot Condon – 5.9.3
Astra Pro: by Brainstorm Force – 2.7.1
Site Kit by Google: by Google – 1.20.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Select Multiple Attributes: by  – 0.0.1 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce: by Automattic – 4.7.0
WP Mail SMTP: by WPForms – 2.5.1
WP Post Page Clone: by Gaurang Sondagar – 1.1

### Inactive Plugins (1) ###

AWS for WordPress: by AWS Labs
WP Engine – 4.2.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 2.6.0
Author URL: https://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 67
Oldest: 2020-10-19 11:50:16 -0400
Newest: 2020-11-16 13:10:17 -0500

`
</details>

**Comment by CaldwellYSR** [comment] 2020-11-17 19:57
Just to be certain I was clear. When we run through the test checkout project with an administrator account the whole flow goes as expected. We can see downloads available in all the places they should be. It only doesn't work for Customer users.

**Comment by CaldwellYSR** [comment] 2020-11-18 20:15
UPDATE:

After some digging and some help from a coworker I believe we have found the issue. We were trying to use HTML files as our downloadable products. The download process works as expected for `.jpg` and `.pdf` files but silently fails for `.html` files.

**Comment by rrennick** [comment] 2021-10-20 18:06
@CaldwellYSR Thanks for creating the issue. This seems to be a duplicate of #28410. As you have submitted a pull request for that issue, I'll close this one as a duplicate.

**Closed by rrennick** 2021-10-20 18:06 UTC
Labels: needs developer feedback

**Comment by CaldwellYSR** [comment] 2021-10-20 18:36
> @CaldwellYSR Thanks for creating the issue. This seems to be a duplicate of #28410. As you have submitted a pull request for that issue, I'll close this one as a duplicate.

These issues aren't even related to one another much less duplicates. I ended up finding a fix for this which involved adding `$allowed_mime_types["htm|html"] = "text/html";` to the `woocommerce_downloadable_file_allowed_mime_types` filter.
