### ISSUE TITLE
is product does not work on single product page.

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#29141] opened 2021-02-16 09:19 UTC
Hi

if i add this to the functions.php

			if (is_product()){
				echo '--------------------------------------> i am a product';
			} else echo '--------------------------------------> i am no product';

in the f.e. 20-21 theme and goto the single product page i get   echo '--------------------------------------> i am no product';

why is it returning no product. I thought is_product should be true on the single product page. What am i missing here?

**Comment by vedanshujain** [comment] 2021-07-29 11:28
Hi @BackuPs , thanks for opening the issue. Generally we don't provide support for custom request like this and use GH only for reproducible bug tracking.

But since we are here, generally these issues happen when:
1. You are calling `is_product` before global `$wp_query` variable is set. In this case, there will be warning log somewhere if warnings are enabled.
2. Plugin/Theme conflict.

I am closing this issue for repo maintenance, but feel free to reply back in case I have missed something and this can be reproduced.

**Closed by vedanshujain** 2021-07-29 11:28 UTC
Labels: needs developer feedback
