### ISSUE TITLE
Packages Text Domain don't change to woocommerce

### ISSUE THREAD

**Issue by RicherYang** [woocommerce/woocommerce#24669] opened 2019-09-24 06:01 UTC
**Describe the bug**
Packages Text Domain don't change to woocommerce.

In WooCommerce version 3.7.0. All of the text domain in **woocommerce-blocks** package is "woo-gutenberg-products-block", don't change to woocommerce.

**Isolating the problem (mark completed items with an [x]):**
- [*] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [*] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by RicherYang** [comment] 2019-09-25 00:42
like file https://plugins.trac.wordpress.org/browser/woocommerce/tags/3.7.0/packages/woocommerce-blocks/assets/js/index.js
the text domain is still 'woo-gutenberg-products-block'

**Comment by RicherYang** [comment] 2019-09-25 00:48
the block create from woocommerce all use english.

One of block " Hand-picked Products " is translated
https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/zh-tw/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8175746&filters%5Btranslation_id%5D=65034902

![圖片](https://user-images.githubusercontent.com/3900767/65560313-b8b96600-df70-11e9-85bc-1ff9610ed97f.png)

**Comment by rodrigoprimo** [comment] 2019-09-26 15:09
Thanks for the example, @RicherYang.

There seems to be a bug indeed in the script that we use to replace the text domain name. It is only replacing the text domain for PHP files, and I believe it should include JS files as well:
https://github.com/woocommerce/woocommerce/blob/master/bin/package-update.sh#L32-L33

I haven't tested, but I believe that the command that we are using to replace the text domain has another problem and it won't work if the text domain is not in the same line as the previous parameter. This due to the regular expression looking for a comma and space before the text domain. For example, I believe that the following won't be affected by the current command, and it should:

```
esc_html__(
    'Your installation of the WooCommerce Blocks feature plugin is incomplete. Please run %1$s within the %2$s directory.',
   'woo-gutenberg-products-block'
),
```

@woocommerce/isotope is someone from your team available to take a look into this since @mikejolley is AFK?

**Comment by nerrad** [comment] 2019-09-26 16:08
Hmm... I'm trying to get up to speed here, but I'm not sure we _should_ be replacing `woo-gutenberg-products-block` with `woocommerce` in the included packages.  If I look at the `languages` folder in my local install of the WooCommerce plugin downloaded from wp.org.  I see `*.json` files for the `woo-gutenberg-products-block` domain.

So for `js` at least, I think the problem here is that where `wp_set_script_translations` is invoked for the blocks, the domain is changed to `woocommerce` from `woo-gutenberg-products-block` and that means it's looking for `woocommerce` prefixed json files instead of `woo-gutenberg-products-block` prefixed json files when resolving the translations.

I'm still testing this though because I think there _may_ be a bug in WordPress core (I don't think the generated md5 hashes account for package includes like this).

**Comment by rodrigoprimo** [comment] 2019-09-26 17:49
Thanks for looking into this, @nerrad. Just to clarify, I assumed that the text domain on the JS files should be the same as the text domain on the PHP files. I'm not sure about that so it is possible that you are right and the problem is that we are changing the domain when calling `wp_set_script_translations()`.

I haven't had a chance yet to look deeply into WP i18n in JS files since the `__()` family of functions was added to the client-side of WP.

**Comment by nerrad** [comment] 2019-09-26 18:06
So to clarify:

- we should still do text domain replacement in php (which will allow language packs from `woocommerce` to serve translations php side).

For javascript (I think) we have a couple options:

1. Replace domain in all js files to `woocommerce` (which means any translations for the blocks plugin on wp.org will get ignored, and translations will only get served from wp.org for `woocommerce`). 
2. Leave the javascript domain as `woo-gutenberg-products-block` in the javascript and just make sure any calls to `wp_set_script_translations` in php for the blocks use `woo-gutenberg-products-block` instead of `woocommerce`.

The second option doesn't appear to be working for me right now because of an assumption I think WordPress core makes when generating the hash lookup for `json` files returned by language packs.

The first option is probably best, but the second option will probably get translations up quicker (via the language packs all ready prepped for the blocks plugin).

I'm working on seeing if I can get a poc working for the second option.

**Closed** 2019-09-30 13:00 UTC
Labels: bug, priority: high
