### ISSUE TITLE
'sold individually' setting is ignored in cart.php

### ISSUE THREAD

**Issue by derhulm** [woocommerce/woocommerce#14023] opened 2017-04-06 10:53 UTC
### EXPLANATION OF THE ISSUE

Products that are sold individually echo an input that is editable in the cart
I had this happen site running WordPress 4.7.3 and updating WooCommerce 2.6.x to 3.0.0 with no other plugins and the WordPress Twenty Sixteen theme.

### STEPS TO REPRODUCE THE ISSUE

1. Create a new variation product
2.  Check the 'Sold individually' checkbox
3.  Set up a test attribute
4.  Set the variations up with prices
5.  View the front end and you can see that you can add more than 1 product. (BUG)
6. Add one product to the cart.
7. View the cart.
8. See that you can edit the quantity. (BUG)

I also tested a simple product. Same Bug appears here

### SYSTEM STATUS

<details>
WordPress environment
Home URL: 		http://xxx
Site URL: 		http://xxx
WC version: 		3.0.0
Log directory writable: 		C:\xxx/wp-content/uploads/wc-logs/
WP version: 		4.7.3
WP multisite: 		–
WP memory limit: 		256 MB
WP debug mode: 		–
WP cron: 		
Sprache: 		de_DE
Server environment
Server info: 		Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14
PHP version: 		5.6.14
PHP post max size: 		8 MB
PHP time limit: 		30
PHP max input vars: 		1000
cURL version: 		7.42.1, OpenSSL/1.0.2d
SUHOSIN installed: 		–
Max upload size: 		8 MB
Default timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte string: 		
Remote post: 		
Remote get: 		
Datenbank
WC database version: 		3.0.0
Database prefix 	  	xxx_	
woocommerce_sessions 	  	
woocommerce_api_keys 	  	
woocommerce_attribute_taxonomies 	  	
woocommerce_downloadable_product_permissions 	  	
woocommerce_order_items 	  	
woocommerce_order_itemmeta 	  	
woocommerce_tax_rates 	  	
woocommerce_tax_rate_locations 	  	
woocommerce_shipping_zones 	  	
woocommerce_shipping_zone_locations 	  	
woocommerce_shipping_zone_methods 	  	
woocommerce_payment_tokens 	  	
woocommerce_payment_tokenmeta 	  	
MaxMind GeoIP database: 		The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: C:\xxx/wp-content/uploads/GeoIP.dat. Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Security
Secure connection (HTTPS): 		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors 		
Active plugins (1)
WooCommerce 	  	von Automattic – 3.0.0
Einstellungen
API enabled: 		
SSL erzwingen: 		–
Währung 		CHF (CHF)
Currency position 		left_space
Thousand separator 		,
Decimal separator 		.
Number of decimals 		2
Taxonomies: Product types 		external (external), grouped (grouped), simple (simple), variable (variable)
WC pages
Shop base:		#5 - /
Warenkorb:		#6 - /warenkorb/
Kasse:		#7 - /kasse/
My account:		#8 - /mein-konto/
Theme
Name: 		Twenty Sixteen
Version: 		1.3
URL des Autors: 		https://de.wordpress.org/
Child theme: 		– Wenn du WooCommerce mit einem Theme, das du nicht selbst entwickelt hast, an eigene Bedürfnisse anpasst, dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)
WooCommerce support: 		
Templates
Überschrieben: 	  	–
</details>

**Comment by mikejolley** [comment] 2017-04-06 11:05
![2017-04-06 at 11 48](https://cloud.githubusercontent.com/assets/90977/24751388/552cf97e-1ac1-11e7-94d9-779efc4311f8.png)

**Comment by mikejolley** [comment] 2017-04-06 11:34
Did the same with a variable product - same result. No qty field is shown on product page nor checkout. 

I cannot replicate - @claudiosanches can you? If not this can be closed. Perhaps the template files on this install were changed or not updated, since that controls this.

**Comment by hamidpeya** [comment] 2017-04-06 12:02
Facing the same issue. Currently selling digital products which are configured to sell individually under both "Simple and Variable" product settings. After updating to 3.0 qty box has start appearing on single product page as well as on cart page where it should not.

**Comment by mikejolley** [comment] 2017-04-06 12:06
@hamidpeya 

> porto/woocommerce/global/quantity-input.php

Delete that file in your theme and see if it corrects.

**Comment by hamidpeya** [comment] 2017-04-06 12:11
@mikejolley didn't work. Qty box still showing up.

**Comment by mikejolley** [comment] 2017-04-06 12:17
Tried another theme? Disabled other plugins? 

I'm not seeing the same as you -something is not standard.

**Comment by hamidpeya** [comment] 2017-04-06 12:26
@mikejolley Yeah tried again by deactivating plugins and changing theme. Qty box is specifically showing up on variable products and not on standard products. Please check on variable products. If it is still not showing up on your end then please try with virtual and downloadable selected.

**Comment by mikejolley** [comment] 2017-04-06 13:02
The other template file is cart.php. This one actually outputs a '1' if sold individually.

**Comment by mikejolley** [comment] 2017-04-06 13:13
@hamidpeya https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cart.php#L105

**Comment by hamidpeya** [comment] 2017-04-06 13:15
Yeah but qty box is showing up on single product as well as on cart page and qty is changeable on both pages.

**Comment by hamidpeya** [comment] 2017-04-06 13:18
Let me check by re-updating the cart.php template. But i don't think it will also make Qty box disappear on single product page.

**Comment by mikejolley** [comment] 2017-04-06 13:22
Single uses that template I said about before. I've tested all product types so I think it's a template override. The logic in that template file changed.

**Comment by hamidpeya** [comment] 2017-04-06 13:33
Sorry if i am misunderstanding it, but in this case it should work perfectly on another theme "Twenty Sixteen" with all plugins disabled except Woocommerce.

**Comment by mikejolley** [comment] 2017-04-06 13:42
Which my screenshot demonstrates. Plugins can change template files. And I'm not ruling out that the ones in core (on your install) have not been modified.

**Comment by mikejolley** [comment] 2017-04-06 14:02
Gonna need access or something - cannot replicate at all. I'm on WordPress slack if anyone else is.

**Comment by hamidpeya** [comment] 2017-04-06 14:09
Okay i just install fresh WP and WC and created a variable product with 2 variations. Select to be sold individually. Qty box still visible on single product page with ability to change Qty. I can give you access to this fresh install but don't know how to make a private reply.

http://urdunovels.com.pk/product/test-variable-product/

**Comment by mikejolley** [comment] 2017-04-06 14:12
https://dl.dropboxusercontent.com/s/n3pk7sl4k1rexse/2017-04-06%20at%2015.12.png

This says it's not sold individually.

**Comment by hamidpeya** [comment] 2017-04-06 14:17
But i have checked the option to sold individually.

http://prntscr.com/et6qlo

**Comment by mikejolley** [comment] 2017-04-06 14:32
It's not seeing it. This is the code in the variation class:

```
// Use the parent sold_individually settings since variations don't have a user-facing way to set sold_individually.
		$product->set_sold_individually( get_post_meta( $product->get_parent_id(), '_sold_individually', true ) );
```

I reads from the parent.

**Comment by hamidpeya** [comment] 2017-04-06 14:35
So, what's the solution? Should we wait for fix on next update?

**Comment by mikejolley** [comment] 2017-04-06 14:46
How can I fix something I cannot reproduce :p The problem is your variations are not sold individually. So either it's not set at parent level, or it cannot be read. I need access. WP Slack. mikejolley

**Comment by mikejolley** [comment] 2017-04-06 14:59
Or you can email. Email on my profile page https://github.com/mikejolley

**Comment by hamidpeya** [comment] 2017-04-06 15:03
Email sent.

**Comment by claudiulodro** [comment] 2017-04-06 15:20
@hamidpeya can you try with the latest master branch from GitHub?

This code @mikejolley referenced: 
```
// Use the parent sold_individually settings since variations don't have a user-facing way to set sold_individually.
$product->set_sold_individually( get_post_meta( $product->get_parent_id(), '_sold_individually', true ) );
```
was added after the release for 3.0.1, and should fix the problem.

**Comment by mikejolley** [comment] 2017-04-06 15:22
@claudiulodro just realised. Master is fixed.

https://github.com/woocommerce/woocommerce/commit/f250cac8d1535ff208df85c955ace82f337d22e4

Will be in 3.0.1

**Closed by mikejolley** 2017-04-06 15:22 UTC

**Comment by hamidpeya** [comment] 2017-04-06 15:36
Yeah that fix works :) But there is still 1 minor issue. If these is no variation selected by default then it will show Qty box until you select any variation.

1) http://prntscr.com/et7t3e
2) http://prntscr.com/et7te8
3) http://prntscr.com/et7to1 (After selecting a variation Qty box disappears)

**Comment by mikejolley** [comment] 2017-04-06 15:42
Maybe you didn't apply the entire fix. Thats working here in master.

**Comment by hamidpeya** [comment] 2017-04-06 15:47
Yeah i just updated " includes/data-stores/class-wc-product-variation-data-store-cpt.php" by adding [this](https://github.com/woocommerce/woocommerce/commit/f250cac8d1535ff208df85c955ace82f337d22e4#diff-1c21163ea1dd16dc3e34f8b3ede74fdc)

Is there anything else i need to update?

**Comment by benjaminloeffel** [comment] 2017-04-07 07:23
I can confirm that the issue on "cart.php" has been resolved, however the template file "variation-add-to-car-button.php" still causes the quantity field to be displayed on the single product page.

**Comment by patecoding** [comment] 2017-05-03 11:54
How I can raise "sell individual" from default 1 to 4 ?
