### ISSUE TITLE
Using new WC_Product_Variation($productID) changes the products title.

### ISSUE THREAD

**Issue by MarkHaynes** [woocommerce/woocommerce#25383] opened 2020-01-10 13:00 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product Variable or Simple name it.
2. Execute the following - $product = new WC_Product_Variation($ID_OF_Product);

## Expected/actual behaviour

When I follow those steps, I see...
The title of the product changes to the title of the page or (no title).

I was expecting to see...

If not a variation a false. 

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

WordPress address (URL): http://haynzee.co.uk/wp/woocommerce
Site address (URL): http://haynzee.co.uk/wp/woocommerce
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.13
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.30-MariaDB
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_2_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 0.85MB
Database Data Size: 0.69MB
Database Index Size: 0.16MB
wp_2_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_options: Data: 0.60MB + Index: 0.03MB + Engine MyISAM
wp_2_postmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_2_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_2_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blogmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_blogs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_registration_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_signups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_site: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_sitemeta: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Jetpack by WordPress.com: by Automattic – 8.0
WooCommerce Admin: by WooCommerce – 0.24.0
WooCommerce Services: by Automattic – 1.22.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: http://stuartduff.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2020-01-10 12:10:14 +0000
Newest: 2020-01-10 12:10:14 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by claudiosanches** [comment] 2020-01-15 20:51
Duplicate of #24956

**Closed by claudiosanches** 2020-01-15 20:51 UTC
