### ISSUE TITLE
Woocommerce product data section not showing

### ISSUE THREAD

**Issue by marcopi1234** [woocommerce/woocommerce#28509] opened 2020-12-07 02:42 UTC
I have installed Woocomerce version 4.7.1. The Problem is that Product data section doesn't show when adding a new product. I already tried disabling all plugins and used twenty twenty theme to rule out any conflicts, but problem persists. I believe its a bug in woocommerce. See attached screenshots. Please help...

![image](https://user-images.githubusercontent.com/60905397/101303128-5e21c800-380b-11eb-97e2-36b5f585b275.png)

![image](https://user-images.githubusercontent.com/60905397/101303174-742f8880-380b-11eb-87f3-e5fee1884c6d.png)

![image](https://user-images.githubusercontent.com/60905397/101303191-7d205a00-380b-11eb-890d-ea6a1efc1aee.png)

**Comment by juliaamosova** [comment] 2020-12-12 20:48
Hi @marcopi1234,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Please see gif below. I tested using both WooCommerce 4.7.1 and 4.8 which is the latest version. The vide is taken using 4.8 version:

![](http://g.recordit.co/rzGwlPdPJR.gif)

Looking at your screenshots, I see that you are using a 3rd party editor which could be the cause of the issue. 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-12-23 22:46
Hi @marcopi1234,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-12-23 22:46 UTC
Labels: category: can't reproduce, needs feedback
