### ISSUE TITLE
Error saving action: Database error. 

### ISSUE THREAD

**Issue by rachnawasnik** [woocommerce/woocommerce#28746] opened 2021-01-07 12:20 UTC
Hello All ,

I am facing issue on checkout page. When I click placeorder button, "Error saving action : Database error"  is shown. I have attached the Screenshot and System Report. 

Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'add product in cart.'
2. Click on ' Add to cart button when you click place order button.'
3. Scroll to 'top error is shown  ..'

**Screenshots**
Below is the scrrenshot given

![20210107_172629(2)](https://user-images.githubusercontent.com/16858006/103891525-0202da00-5110-11eb-8dbf-dcfa997af879.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://brainwork.co.in/anwarco
Site address (URL): http://brainwork.co.in/anwarco
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: ❌ 5.5.3 - There is a newer version of WordPress available (5.6)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.32
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 180.36MB
Database Data Size: 137.32MB
Database Index Size: 43.04MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 61.59MB + Index: 32.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 1.52MB + Index: 1.03MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.27MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mcisoe_suppliers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 49.55MB + Index: 5.03MB + Engine InnoDB
wp_posts: Data: 12.52MB + Index: 0.97MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_usermeta: Data: 1.50MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_user_registration_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 1.44MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.34MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woo_shippment_provider: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wplc_actions_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_sessions: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_departments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_quick_responses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_vendors_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_vendors_commissions_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 5178
ct_size_guide: 2
customize_changeset: 2
elementor_library: 23
gallery: 45
jobpost: 1
jobpost_applicants: 1
mc4wp-form: 1
nav_menu_item: 491
page: 21
post: 20
product: 1774
product_variation: 3
revision: 370
shop_order: 7
user_registration: 1
wpcf7_contact_form: 6

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (35) ###

Redux: by Redux.io + Dovy Paukstys – 4.1.24
WPML Multilingual CMS: by OnTheGoSystems – 4.4.8
Appmaker – Convert WooCommerce to Android & iOS Native Mobile Apps: by Appmaker – 1.32.0
Contact Form 7: by Takayuki Miyoshi – 5.3
createIT Size Guide Plugin: by createIT – 3.6
Elementor: by Elementor.com – 3.0.13
Jetpack by WordPress.com: by Automattic – 9.0.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.2.0
KiteStudio Core: by KiteStudio – 1.6
KiteStudio Pro Tools: by KiteStudio – 1.2.4
Mailchimp for WooCommerce: by Mailchimp – 2.4.7
WordPress Mass Email to users: by I Thirteen Web Solution – 1.1.4
Members: by MemberPress – 3.1.3
One Click Order Re-Order: by CedCommerce – 1.1.5
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.7.1
Slider Revolution: by ThemePunch – 6.2.22
Simple Job Board: by PressTigers – 2.9.1
Slate Admin Theme: by Ryan Sommers – 1.2.3
Supplier Order Email: by MCI Desarrollo – 1.1.9
User Registration: by WPEverest – 1.8.8
WooCommerce Address Book: by Hall Internet Marketing – 1.7.5
Advanced Shipment Tracking for WooCommerce: by zorem – 3.1.5
Return Refund and Exchange for Woocommerce: by MakeWebBetter – 3.0.3
All Currencies for WooCommerce: by WP Wham – 2.3.8
WooCommerce Hesabe Payment Gateway: by HesabeTeam – 2.0 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Shipping & Tax: by Automattic – 1.25.1 (update to version 1.25.4 is available)
WooCommerce: by Automattic – 4.8.0
WordPress Importer: by wordpressdotorg – 0.7
3CX Live Chat: by 3CX – 9.1.0
WPML String Translation: by OnTheGoSystems – 3.1.6
WPML Translation Management: by OnTheGoSystems – 2.10.4
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.7.6

YITH WooCommerce Compare: by YITH – 2.4.2
YITH WooCommerce Multi Vendor: by YITH – 3.7.0
YITH WooCommerce Wishlist: by YITH – 3.0.15

### Inactive Plugins (6) ###

Advanced Woo Search: by ILLID – 2.14
Akismet Anti-Spam: by Automattic – 4.1.6
Hello Dolly: by Matt Mullenweg – 1.7.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.1
Really Simple SSL: by Really Simple Plugins – 3.3.5
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.3.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: KWD (KWD)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop
Cart: #1291 - /cart-2
Checkout: #1292 - /checkout-2
My account: #1293 - /my-account-2
Terms and conditions: #3863 - /terms-of-use

### Theme ###

Name: pinkmart Child
Version: 1.0
Author URL: http://www.kitestudio.co
Child Theme: ✔
Parent Theme Name: pinkmart
Parent Theme Version: 2.8
Parent Theme Author URL: http://kitestudio.co/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: pinkmart/woocommerce/cart/cart-empty.php
pinkmart/woocommerce/cart/cart-shipping.php
pinkmart/woocommerce/cart/cart.php
pinkmart/woocommerce/cart/cross-sells.php
pinkmart/woocommerce/cart/mini-cart.php
pinkmart/woocommerce/checkout/form-billing.php
pinkmart/woocommerce/checkout/form-checkout.php
pinkmart/woocommerce/checkout/form-login.php
pinkmart/woocommerce/checkout/form-shipping.php
pinkmart/woocommerce/content-product.php
pinkmart/woocommerce/content-single-product.php
pinkmart/woocommerce/content-widget-product.php
pinkmart/woocommerce/global/breadcrumb.php
pinkmart/woocommerce/global/form-login.php
pinkmart/woocommerce/loop/add-to-cart.php
pinkmart/woocommerce/loop/loop-end.php
pinkmart/woocommerce/loop/loop-start.php
pinkmart/woocommerce/loop/no-products-found.php
pinkmart/woocommerce/myaccount/form-login.php
pinkmart/woocommerce/myaccount/navigation.php
pinkmart/woocommerce/product-searchform.php
pinkmart/woocommerce/single-product/add-to-cart/variable.php
pinkmart/woocommerce/single-product/meta.php
pinkmart/woocommerce/single-product/price.php
pinkmart/woocommerce/single-product/product-image.php
pinkmart/woocommerce/single-product/product-thumbnails.php
pinkmart/woocommerce/single-product/rating.php
pinkmart/woocommerce/single-product/related.php
pinkmart/woocommerce/single-product/tabs/tabs.php
pinkmart/woocommerce/single-product/up-sells.php
pinkmart/woocommerce/single-product-reviews.php
pinkmart/woocommerce/content-product_cat.php version 2.6.1 is out of date. The core version is 4.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### All Currencies Settings ###

WooCommerce All Currencies: yes
Add country currencies: yes
Add crypto currencies: yes
You will need All Currencies for WooCommerce Pro plugin to change currency symbol.: 
Use currency code as symbol: yes
Hide currency symbol on frontend: no
[AED] UAE dirham: 
[AFN] Afghan afghani: 
[ALL] Albanian lek: 
[AMD] Armenian dram: 
[ANG] Netherlands Antillean gulden: 
[AOA] Angolan kwanza: 
[ARS] Argentine peso: 
[AUD] Australian dollar: 
[AWG] Aruban florin: 
[AZN] Azerbaijani manat: 
[BAM] Bosnia and Herzegovina konvertibilna marka: 
[BBD] Barbadian dollar: 
[BDT] Bangladeshi taka: 
[BGN] Bulgarian lev: 
[BHD] Bahraini dinar: 
[BIF] Burundi franc: 
[BND] Brunei dollar: 
[BOB] Bolivian boliviano: 
[BRL] Brazilian real: 
[BSD] Bahamian dollar: 
[BTN] Bhutanese ngultrum: 
[BWP] Botswana pula: 
[BYR] Belarusian ruble: 
[BZD] Belize dollar: 
[CAD] Canadian dollar: 
[CDF] Congolese franc: 
[CHF] Swiss franc: 
[CLP] Chilean peso: 
[CNY] Chinese renminbi: 
[COP] Colombian peso: 
[CRC] Costa Rican colon: 
[CUC] Cuban peso: 
[CVE] Cape Verdean escudo: 
[CZK] Czech koruna: 
[DJF] Djiboutian franc: 
[DKK] Danish krone: 
[DOP] Dominican peso: 
[DZD] Algerian dinar: 
[EEK] Estonian kroon: 
[EGP] Egyptian pound: 
[ERN] Eritrean nakfa: 
[ETB] Ethiopian birr: 
[EUR] European euro: 
[FJD] Fijian dollar: 
[FKP] Falkland Islands pound: 
[GBP] British pound: 
[GEL] Georgian lari: 
[GHS] Ghanaian cedi: 
[GIP] Gibraltar pound: 
[GMD] Gambian dalasi: 
[GNF] Guinean franc: 
[GQE] Central African CFA franc: 
[GTQ] Guatemalan quetzal: 
[GYD] Guyanese dollar: 
[HKD] Hong Kong dollar: 
[HNL] Honduran lempira: 
[HRK] Croatian kuna: 
[HTG] Haitian gourde: 
[HUF] Hungarian forint: 
[IDR] Indonesian rupiah: 
[ILS] Israeli new sheqel: 
[INR] Indian rupee: 
[IQD] Iraqi dinar: 
[IRR] Iranian rial: 
[ISK] Icelandic krona: 
[JMD] Jamaican dollar: 
[JOD] Jordanian dinar: 
[JPY] Japanese yen: 
[KES] Kenyan shilling: 
[KGS] Kyrgyzstani som: 
[KHR] Cambodian riel: 
[KIP] Lao kip: 
[KMF] Comorian franc: 
[KPW] North Korean won: 
[KRW] South Korean won: 
[KWD] Kuwaiti dinar: 
[KYD] Cayman Islands dollar: 
[KZT] Kazakhstani tenge: 
[LBP] Lebanese lira: 
[LKR] Sri Lankan rupee: 
[LRD] Liberian dollar: 
[LSL] Lesotho loti: 
[LTL] Lithuanian litas: 
[LVL] Latvian lats: 
[LYD] Libyan dinar: 
[MAD] Moroccan dirham: 
[MDL] Moldovan leu: 
[MGA] Malagasy ariary: 
[MKD] Macedonian denar: 
[MMK] Myanma kyat: 
[MNT] Mongolian tugrik: 
[MOP] Macanese pataca: 
[MRO] Mauritanian ouguiya: 
[MUR] Mauritian rupee: 
[MVR] Maldivian rufiyaa: 
[MWK] Malawian kwacha: 
[MXN] Mexican peso: 
[MYR] Malaysian ringgit: 
[MZM] Mozambican metical: 
[NAD] Namibian dollar: 
[NGN] Nigerian naira: 
[NIO] Nicaraguan cordoba: 
[NOK] Norwegian krone: 
[NPR] Nepalese rupee: 
[NZD] New Zealand dollar: 
[OMR] Omani rial: 
[PAB] Panamanian balboa: 
[PEN] Peruvian nuevo sol: 
[PGK] Papua New Guinean kina: 
[PHP] Philippine peso: 
[PKR] Pakistani rupee: 
[PLN] Polish zloty: 
[PYG] Paraguayan guarani: 
[QAR] Qatari riyal: 
[RMB] Chinese Yuan: 
[RON] Romanian leu: 
[RSD] Serbian dinar: 
[RUB] Russian ruble: 
[RWF] Rwandan franc: 
[SAR] Saudi riyal: 
[SBD] Solomon Islands dollar: 
[SCR] Seychellois rupee: 
[SDG] Sudanese pound: 
[SEK] Swedish krona: 
[SGD] Singapore dollar: 
[SHP] Saint Helena pound: 
[SKK] Slovak koruna: 
[SLL] Sierra Leonean leone: 
[SOS] Somali shilling: 
[SRD] Surinamese dollar: 
[STD] Sao Tome and Principe dobra: 
[SYP] Syrian pound: 
[SZL] Swazi lilangeni: 
[THB] Thai baht: 
[TJS] Tajikistani somoni: 
[TMM] Turkmen manat: 
[TND] Tunisian dinar: 
[TOP] Paanga: 
[TRY] Turkish new lira: 
[TTD] Trinidad and Tobago dollar: 
[TWD] New Taiwan dollar: 
[TZS] Tanzanian shilling: 
[UAH] Ukrainian hryvnia: 
[UGX] Ugandan shilling: 
[USD] United States dollar: 
[UYU] Uruguayan peso: 
[UZS] Uzbekistani som: 
[VEF] Venezuelan bolivar: 
[VND] Vietnamese dong: 
[VUV] Vanuatu vatu: 
[WST] Samoan tala: 
[XAF] Central African CFA franc: 
[XCD] East Caribbean dollar: 
[XDR] Special Drawing Rights: 
[XOF] West African CFA franc: 
[XPF] CFP franc: 
[YER] Yemeni rial: 
[ZAR] South African rand: 
[ZMK] Zambian kwacha: 
[ZWD] Zimbabwean dollar: 
[ADA] Cardano: 
[AUR] Auroracoin: 
[BNB] Binance Coin: 
[BTC] Bitcoin: 
[BCH] Bitcoin Cash: 
[BTK] Bitcoin Token: 
[BCC] BitConnect: 
[KOI] Coinye: 
[XDN] DigitalNote: 
[DRGN] Dragonchain: 
[EMC] Emercoin: 
[EOS] EOS: 
[ETH] Ethereum: 
[ETC] Ethereum Classic: 
[FMC] Freemasoncoin: 
[GRC] Gridcoin: 
[HT] Huobi Token: 
[IOT] IOTA: 
[LTC] Litecoin: 
[MARS] Marscoin: 
[MZC] MazaCoin: 
[XMR] Monero: 
[NMC] Namecoin: 
[XEM] NEM: 
[NXT] Nxt: 
[MSC] Omni: 
[PAC] PACcoin: 
[PPC] Peercoin: 
[POT] PotCoin: 
[XPM] Primecoin: 
[XRP] Ripple: 
[SIL] SixEleven: 
[SMART] SmartCash: 
[AMP] Synereo AMP: 
[TIT] Titcoin: 
[UBQ] Ubiq: 
[USDT] Tether: 
[VTC] Vertcoin: 
[XLM] Stellar: 
[ZEC] Zcash: 
Enable/Disable: 
Total custom currencies: 
Custom currency #1: 
Name (optional): 
Symbol (optional): 

### Action Scheduler ###

Canceled: 10
Oldest: 2020-12-25 17:25:14 +0000
Newest: 2020-12-25 17:48:36 +0000

Complete: 3,520
Oldest: 2020-12-16 10:15:12 +0000
Newest: 2021-01-02 06:53:05 +0000

Pending: 10
Oldest: 2021-01-02 06:53:05 +0000
Newest: 2021-01-02 06:53:05 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2021-01-10 22:04
Hi @rachnawasnik,

Thank you for raising the issue. It is a duplicate of another issue that you submitted https://github.com/woocommerce/woocommerce/issues/28733. Since this issue has a screenshot, I will close https://github.com/woocommerce/woocommerce/issues/28733 in favor of this one. 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by tammullen** [comment] 2021-01-18 11:01
Hi @rachnawasnik 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2021-01-18 11:01 UTC
Labels: needs feedback
