### ISSUE TITLE
Variation before set stock hook lock?

### ISSUE THREAD

**Issue by tanasi** [woocommerce/woocommerce#29924] opened 2021-05-17 09:29 UTC
Hi, 

I am getting some inconsistent results when using the woocommerce_variation_before_set_stock hook. Well, it looks like it only works the first time or when executing from a different product. 

The following code creates a custom field (Previous stock status) on product level and when a variation stock change happens it keeps the current timestamp.

Steps to recreate:
- Create 2 variable products e.g. Product A with ID 1536 and Product B with ID 1222.
- Change the stock on a variation on Product with ID 1536 and hit save. Nothing is saved on custom field. (In fact it only saves the first time).
- In code manually set the product id e.g. 1536.
- Now change the stock on a variation from a different product e.g. with ID 1222 and hit save. Then on product with ID 1536 and custom stock status field i get the current timestamp.
Any ideas on why I get this behavior? Is there any type of "lock" that I need to be aware? Is this normal or is there an issue?

```
function egn_previous_stock_status_field()
{
	$args = array(
		'type' => 'text',
		'id' => 'previous_stock_status',
		'label' => __('Previous stock status', 'flatsome'),
		'class' => 'egn-stock-field',
		'desc_tip' => true,
		'description' => __('Previous stock status', 'flatsome'),
	);
	woocommerce_wp_text_input($args);
}
add_action('woocommerce_product_options_general_product_data', 'egn_previous_stock_status_field');



//Saves previous stock status for variable products
function save_previous_variation_stock_status()
{
		update_post_meta('1536', 'previous_stock_status', time());
}
//Hook that runs on before stock change
add_action( 'woocommerce_variation_before_set_stock','save_previous_variation_stock_status' );

```

- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment] 2021-08-09 19:34
Hi @tanasi 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by roykho** 2021-08-09 19:34 UTC
Labels: needs developer feedback
