### ISSUE TITLE
Country-Select JS breaks custom wrapper within billing-fields container

### ISSUE THREAD

**Issue by dennisheiden** [woocommerce/woocommerce#29522] opened 2021-03-29 13:25 UTC
_Tested on WooCommerce 4.6 and 5.1._

**What did I do?**
Overwriting the template in form-billing.php like this:

(somehow github is not displaying my code snippet correctly so here is a screenshot)

![image](https://user-images.githubusercontent.com/25924499/112844375-f5a17400-90a3-11eb-9f6b-3e13fe2b659c.png)

`<?php
		$fields = $checkout->get_checkout_fields( 'billing' );
		$required_fields = array();
		$optional_fields = array();
		
		foreach( $fields as $key => $field){
		    if( empty($field['required']) === true){ // false & null & 0
			    $optional_fields[$key] =  $field;
            }else{
			    $required_fields[$key] =  $field;
            }
        }
	   
        $i = 0;

        foreach( $required_fields as $key => $field){
	       woocommerce_form_field( $key, $field, $checkout->get_value( $key ) );
        }
        
        echo '<div style="background:red">';
        foreach( $optional_fields as $key => $field){
	        woocommerce_form_field( $key, $field, $checkout->get_value( $key ) );
        }
        echo "</div>";

		?>`

**Goal**
All optional fields should be wrapped by a div container with a red background.

**Current state**
Div container is empty and all optional fields are outside of the container.

**Details**
This issue **occurs only when the billing country field is displayed** in the checkout form. This might be an issue with the country-select.js script. As far as I could see that script manipulates the DOM of the form in a way which breaks further wrapping within the woocommerce-billing-fields container.

If you rename "woocommerce-billing-fields" this doesn't happen. (just another hint that this is caused by the script)

**Comment by vedanshujain** [comment] 2021-04-05 14:11
@dennisheiden we use [selectWoo](https://github.com/woocommerce/selectWoo) which is a fork for select2 for rendering select fields. [its rendered in an overlay so this expected behavior](https://github.com/woocommerce/woocommerce/blob/trunk/assets/js/frontend/country-select.js#L63), if you want to customize it, you can take a look at  select2 documentation.

I am closing this issue since we use GH to handle bugs and won't be able to support customization requests.

**Closed by vedanshujain** 2021-04-05 14:11 UTC
Labels: needs developer feedback

**Comment by dennisheiden** [comment] 2021-04-06 09:40
Hi vedanshujain,

I have anticipated something like this and I can understand your answer.
I just think that the implementation should be reviewed because a JS manipulation of DOM in frontend which is breaking any customization of the form, achieved through legit template overwrites / using WC hooks, shouldn't be accepted as default behavior. IMHO (or at least there should be an opt-out option for that)

If I'm finding the time, I will look into the lib and do further testing and might be able to come up with a better solution.

Thanks.

**Comment by dennisheiden** [comment] 2021-05-05 14:13
Ok, for everybody who might find this via Google, this is the solution based on a answer on stackexchange [https://wordpress.stackexchange.com/a/338984](https://wordpress.stackexchange.com/a/338984):

1. Add a filter to remove form-row from the field markup, this class is used to reshuffle the fields after a checkout change.
```
add_filter( 'woocommerce_form_field', 'change_woocommerce_field_markup', 10, 4 );

public function change_woocommerce_field_markup($field, $key, $args, $value){
	if($args['required'] === false){
		$field = str_replace('form-row', '', $field);
	}
		  
       return $field;
}
```
2. Add the .form-row class to your custom wrapper div
