### ISSUE TITLE
Product ORDERS section - bug/glitch

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#21276] opened 2018-09-04 21:35 UTC
Hi everyone. Thank you for taking the time to look over & assist with my issue(s). Basically, I have had this issue with WooCommerce for the past several months. I have been HOPING that with every new release of WooCommerce through updates, that this issue would resolve itself on its own. However, that is simply NOT the case.

The bug resides within the PRODUCTS ORDER section of WooCommerce. Every time that I load this section of WC, loading takes abnormally long for some reason & when I finally manage to gain access, I am only able to see roughly 3-5% of my total/processing orders. In other words, I currently have around 60 processing/current orders. When I load this section of WC, I am only able to see 4 or 5 orders out of the full amount of 60 that are processing.

Furthermore, when I attempt to open the 2nd or 3rd page of total orders PROCESSING, I have to wait a very long time until I am presented with a BLANK PAGE for some reason. I have researched the internet & github for others having the same issue but none present themselves as odd as my particular case.

If there is someone or anyone that can hopefully guide me in the correct direction to resolve, I would be greatly appreciative. Thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/24295896/45059055-9f453380-b068-11e8-90c4-fc300680169a.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

`
**### WordPress Environment ###**

Home URL: https://dreamesper.com
Site URL: https://dreamesper.com
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32-78.0-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_akyx8yatq1_
MaxMind GeoIP Database: ✔
Total Database Size: 66.38MB
Database Data Size: 64.12MB
Database Index Size: 2.26MB
wp_akyx8yatq1_woocommerce_sessions: Data: 8.02MB + Index: 0.02MB
wp_akyx8yatq1_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_order_items: Data: 0.03MB + Index: 0.02MB
wp_akyx8yatq1_woocommerce_order_itemmeta: Data: 0.18MB + Index: 0.15MB
wp_akyx8yatq1_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_akyx8yatq1_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_akyx8yatq1_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_akyx8yatq1_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_groups: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_linkmeta: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_schedule: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_stats: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_stats_archive: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_tracker: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_transactions: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_apct_testimonial_detail: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bluesnap_supported_currencies: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_activity: Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_bp_activity_meta: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_notifications: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_notifications_meta: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_xprofile_data: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_xprofile_fields: Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_bp_xprofile_groups: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_xprofile_meta: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_commentmeta: Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_comments: Data: 0.17MB + Index: 0.10MB
wp_akyx8yatq1_EWD_OTP_Customers: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Custom_Fields: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Fields_Meta: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Orders: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Order_Statuses: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Sales_Reps: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_links: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_litespeed_img_optm: Data: 0.00MB + Index: 0.02MB
wp_akyx8yatq1_litespeed_optimizer: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_mollie_pending_payment: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_coupon: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_post_collection: Data: 0.01MB + Index: 0.04MB
wp_akyx8yatq1_msdb_post_data: Data: 0.20MB + Index: 0.02MB
wp_akyx8yatq1_msdb_product_discount: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_purchase: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_shopping_cart: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_store_discount: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_options: Data: 3.31MB + Index: 0.09MB
wp_akyx8yatq1_postmeta: Data: 50.57MB + Index: 0.94MB
wp_akyx8yatq1_posts: Data: 1.09MB + Index: 0.41MB
wp_akyx8yatq1_rich_web_photo_slider_instal: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_photo_slider_manager: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect1: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect10: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect10_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect1_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect2: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect2_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect3: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect3_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect4: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect4_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect5: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect5_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect6: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect6_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect7: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect7_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect8: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect8_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect9: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect9_loader: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effects_data: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_font_family: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_id: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_signups: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_termmeta: Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_terms: Data: 0.01MB + Index: 0.02MB
wp_akyx8yatq1_term_relationships: Data: 0.10MB + Index: 0.20MB
wp_akyx8yatq1_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_usermeta: Data: 0.02MB + Index: 0.02MB
wp_akyx8yatq1_users: Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_vw_lsrooms: Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_vw_lwsessions: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_vw_sessions: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_wplc_webhooks: Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_yoast_seo_links: Data: 0.01MB + Index: 0.00MB
wp_akyx8yatq1_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

al_product: 26
amn_exact-metrics: 1
attachment: 1830
audioplayer: 1
bp-email: 16
carousels: 1
channel: 1
jetpack_migration: 2
ms_collection: 18
ms_song: 1585
nav_menu_item: 8
oembed_cache: 13
owl-carousel: 1
page: 16
post: 1
product: 92
product_variation: 4
revision: 121
shop_order: 252
shop_order_refund: 75
slick_slider: 1
tf_shop_slider: 1
wafs: 2
wcps: 1
woocarousel: 1
wpsc_cart_orders: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Akismet Anti-Spam: by Automattic – 4.0.8
PayPal Express Checkout for WooCommerce: by wpgateways – 3.0.3 – Not tested with the active version of WooCommerce
Fast Velocity Minify: by Raul Peixoto – 2.3.5
Google Analytics Dashboard for WP (GADWP): by ExactMetrics team – 5.3.3
Kirki Toolkit: by Aristeides Stathopoulos – 3.0.33
Music Store: by CodePeople – 5.0.100
Simple Cache: by Taylor Lovett – 1.6.4
WooCommerce Shipment Tracking Basic: by PluginHive – 1.0.10 – Not tested with the active version of WooCommerce
WooCommerce Beta Tester: by WooCommerce – 2.0.0 – Not tested with the active version of WooCommerce
Woocommerce Products Slider: by pickplugins – 1.12.21 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.15.1 – Not tested with the active version of WooCommerce
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0 – Not tested with the active version of WooCommerce

WooCommerce: by Automattic – 3.4.5
YITH WooCommerce Quick View: by YITHEMES – 1.3.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: by YITHEMES – 2.2.3 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /shop/checkout/
My account: #8 - /my-account/
Terms and conditions: #717 - /return-policy/

### Theme ###

Name: StoreVilla
Version: 1.2.9
Author URL: https://accesspressthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storevilla/woocommerce/global/quantity-input.php
`

**Comment by kloon** [comment] 2018-09-05 12:37
Can you test this by disable all plugins except WooCommerce and also switching your theme to Storefront or Twenty Seventeen temporarily? You can then enable plugins one by one testing inbetween and then eventually switching your theme back to find the offending plugin.

Also check your PHP Error Log as blank screen usually mean a PHP error occurred, you should be able to get the error log from your hosting provider.

**Comment by dreamesper** [comment] 2018-09-05 14:40
Okay, thanks for your input. I am checking with my hosting provider now in order to rectify the PHP issue; none of your other methods for disabling/enabling plugins has worked, unfortunately.

**Comment by claudiulodro** [comment] 2018-09-11 18:39
Where it cuts off right after the checkbox in your screenshot there is a fatal error of some sort happening. Likely sources of this error are your YITH plugins, your shipment tracking plugin (which seems to be years out of date), or any other plugins you have that may do things on the orders screen. Updating those plugins to the latest versions or deactivating them may solve your issues.

Without the fatal error from the logs we can't really investigate this any further or provide additional insight. If you are able to get the specific error happening from your host, post back, I can reopen the issue, and we can investigate further. For now I am closing this issue as non-reproducible since it does not happen on a standard WooCommerce installation with no other plugins.

**Closed by claudiulodro** 2018-09-11 18:39 UTC
Labels: status: needs feedback
