### ISSUE TITLE
Tax always include, but also without Tax ^^Woocommece

### ISSUE THREAD

**Issue by MarcNitsche** [woocommerce/woocommerce#30419] opened 2021-08-04 11:57 UTC
This conversation has ran on long enough, especially as we have a solution in core now for keeping the prices as-is. See https://github.com/woothemes/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#prices-including-tax---experimental-behavior

_Originally posted by @mikejolley in https://github.com/woocommerce/woocommerce/issues/4131#issuecomment-216783027_

Hi,

I really like this solution, but I have still one problem left. When we ship to switzerland from germany the have to pay their own tax, so we have to ship it without tax. When i use the code in child theme the customer to switzerland pay the same price, but without tax and so they "have to pay the tax double". Is it possible to show the "germany net" price for all third countries like switzerland?

**Comment by juliaamosova** [comment] 2021-08-06 14:53
Hi @MarcNitsche,

Thank you for rising the issue! 

>I really like this solution, but I have still one problem left. When we ship to switzerland from germany the have to pay their own tax, so we have to ship it without tax. When i use the code in child theme the customer to switzerland pay the same price, but without tax and so they "have to pay the tax double". Is it possible to show the "germany net" price for all third countries like Switzerland?

This information is not enough for us to adequately help you. We will need the full details of your tax settings in order to try to replicate the issue and help you further here. 

The details we are looking for are below:

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by MarcNitsche** [comment] 2021-08-09 06:39
Hi,

thank you for your answer. I think it's not a bug... I think it is currently not planned.

Furthermore, I used this in my child theme:

`add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' );`

And it works well, but also for Switzerland and so the customer from Switzerland have to pay the full costs without tax.

From Germany 100€ incl 19% tax (19€)
From Austria 100€ incl 20% tax (20€)
From Switzerland 100€ incl 0% tac (0€)

But if a customer orders from Switzerland, they have also pay tax to Switzerland. So I wish, I could give customers for countries outside the EU (without or with 0% tax setting in woocommerce) the products exclude the German 19%.

So a customer from Switzerland or US should pay just 81€ (100€ - 19% German tax).

Does that helps for a solution?

**Comment by tammullen** [comment] 2021-09-08 12:23
Hi @MarcNitsche ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-09-08 12:23 UTC
Labels: has feedback

**Comment by MarcNitsche** [comment] 2021-09-08 13:35
Hi @tammullen 

it a bug comes from the developed method here: https://github.com/woothemes/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#prices-including-tax---experimental-behavior
