### ISSUE TITLE
Erroneus stating "Product published" on Add New product and Publishing with no input meta data

### ISSUE THREAD

**Issue by MainioMooses** [woocommerce/woocommerce#22671] opened 2019-02-06 08:13 UTC
**Describe the bug**
Creating a new product, inputting nothing into the product metaboxes and then pressing publish brings up a green notification saying "Product published. View Product". However, the product does not get published or saved in any way visible to the backend and the "View product" link is a 404.

**To Reproduce**
1. Go to Products
2. Click on Add new
3. Publish product without adding any info
4. You get notified of success with "Product published" and "View product"
5. No product has actually been saved or published
6. "View product"-link is thus a 404 link.

**Expected behavior**
A warning stating that you must enter a product name (or the product must have an url slug).

**Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://suunnittele.fi/372586728
Site URL: https://suunnittele.fi/372586728
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.14
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.63.0
OpenSSL/1.1.0j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.90MB
Database Data Size: 3.42MB
Database Index Size: 1.48MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_et_bloom_stats: Data: 0.02MB + Index: 0.00MB
wp_et_social_stats: Data: 0.02MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_maksuturva_queue: Data: 0.02MB + Index: 0.00MB
wp_maksuturva_status_query_log: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.09MB + Index: 0.05MB
wp_postmeta: Data: 0.05MB + Index: 0.03MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB
wp_wfconfig: Data: 0.06MB + Index: 0.00MB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB
wp_wfhits: Data: 0.02MB + Index: 0.05MB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB
wp_wfissues: Data: 0.02MB + Index: 0.06MB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB
wp_wflocs: Data: 0.02MB + Index: 0.00MB
wp_wflogins: Data: 0.02MB + Index: 0.03MB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3
custom_css: 1
customize_changeset: 5
gp_elements: 3
nav_menu_item: 6
page: 6
post: 2
product: 5
revision: 14
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Gravity Forms: by rocketgenius – 2.4.5
All-in-One WP Migration File Extension: by ServMask
Inc. – 1.3

All-in-One WP Migration Unlimited Extension: by ServMask – 2.25
All-in-One WP Migration: by ServMask – 6.84
Bloom: by Elegant Themes – 1.3.8
Classic Editor: by WordPress Contributors – 1.4
Disable Comments: by Samir Shah – 1.8.0
GP Premium: by Tom Usborne – 1.7.7
Gravity Forms MailChimp Add-On: by rocketgenius – 4.5
Monarch Plugin: by Elegant Themes – 1.4.10
WooCommerce Pakettikauppa: by Seravo – 1.1.8 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.4
WooCommerce Maksuturva Payment Gateway: by Maksuturva Group Oy – 2.0.5 – Not tested with the active version of WooCommerce
Force Login: by Kevin Vess – 5.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #77 - /kauppa/
Cart: #79 - /ostoskori/
Checkout: #81 - /kassa/
My account: #83 - /oma-tili/
Terms and conditions: ❌ Page not set

### Theme ###

Name: GeneratePress Child
Version: 2.1.4.1539336875
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 2.2.2
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rrennick** [comment] 2019-02-06 13:29
> * I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
>  This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

You need to be able to reproduce your issue while doing both of the above. Following the steps outlined work in my install. I am closing this issue. Please re-open if you have steps to reproduce an issue with publishing a product.

**Comment by rrennick** [comment] 2019-02-06 13:34
Sorry, re-opening this as the product does disappear if it has no title.

**Comment by peterfabian** [comment] 2019-02-07 12:07
This seems to be a standard WP behaviour, though. Using classic editor, new Post behaves the same. 
As you can see in the discussion in https://core.trac.wordpress.org/ticket/17115, it's still not resolved in core. I guess we can't really change it unless we hack around the WP core. JS solutions have their drawbacks, too. 
If you want, you can filter `post_updated_messages` to change the message to a notice saying some fields are required (that won't prevent WP from creating autodraft, though).

**Closed by peterfabian** 2019-02-07 12:07 UTC
