### ISSUE TITLE
[GlobalStep WooCommerce – 4.4 Beta 1] The user is able to see “Out of Stock” products which has no price assigned and “Hide out of stock item from the catalog” option is enabled.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#27178] opened 2020-07-30 11:01 UTC
## Bug Description:
The user is able to see “Out of Stock” products which has no price assigned and the “Hide out of stock item from the catalog” option is enabled.

## Environment:
**Windows 10, Mac**
Browser: Chrome(Version 83.0.4103.61 (64-bit))
                 Firefox(Version 77.0.1)(64-bit)
                 Safari(Version 13.1.1)

## Steps to Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins.
1. Complete the Onboarding Wizard.
1. Create few products whose status is “Out of stock” and no price assigned
1. Go to WooCommerce -> Settings -> Products -> Inventory.
1. Enable “Hide out of stock items from the catalog" option.
1. Save changes.

**Scenario 1:** 
1. Go to the frontend of the site.
1. Observe that the user is still able to see "Out of Stock" products.

**Scenario 2:** 
1. Create a page.
1. Add "All Products Block" and "Filter by Attribute" block.
1. Preview the page or publish the page.
1. Observe that the user is still able to see "Out of Stock" products.

## Actual Result:
The user is able to see “Out of Stock” products which has no price assigned and “Hide out of stock item from the catalog” option is enabled.

## Expected Result:
Upon enabling the “Hide out of stock items from the catalog" option user should not be able to see "Out of Stock" products.

## Artifacts:
[#27178.zip](https://github.com/woocommerce/woocommerce/files/5000800/27178.zip)

## Products Exported:
[#27178_wc-product-export-30-7-2020-1596119452941.zip](https://github.com/woocommerce/woocommerce/files/5001835/27178_wc-product-export-30-7-2020-1596119452941.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://misty-swordfish.jurassic.ninja
Site address (URL): https://misty-swordfish.jurassic.ninja
WC Version: 4.4.0
REST API Version: ✔ 1.0.11
WC Blocks Version: ✔ 3.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0-beta.2
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.8
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.31-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Total Database Size: 4.11MB
Database Data Size: 2.55MB
Database Index Size: 1.56MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.45MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 9
post: 2
product: 44
product_variation: 32
revision: 7
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Query Monitor: by John Blackbourn – 3.6.1
Companion Plugin: by Osk – 1.17
Facebook for WooCommerce: by Facebook – 1.11.4 – Installed version not tested with active version of WooCommerce 4.4.0
Jetpack by WordPress.com: by Automattic – 8.7.1
Google Ads for WooCommerce: by Kliken – 1.0.4 – Installed version not tested with active version of WooCommerce 4.4.0
Mailchimp for WooCommerce: by Mailchimp – 2.4.3 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Services: by Automattic – 1.23.2 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce: by Automattic – 4.4.0-beta.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 9
Oldest: 2020-07-30 06:31:33 +0000
Newest: 2020-07-30 08:59:18 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-07-31 22:52
Hi @gglobalstep,

Thanks for raising the issue. However, there are several things going on here:

>Scenario 1:
>Go to the frontend of the site.
>Observe that the user is still able to see "Out of Stock" products.

I logged in to the site where you tested and provided the video from and confirm that the issue is related to the variable product that has variations with no prices. I filed a separate bug for this issue: https://github.com/woocommerce/woocommerce/issues/27192. 

>Scenario 2:
>Create a page.
>Add "All Products Block" and "Filter by Attribute" block.
>Preview the page or publish the page.
>Observe that the user is still able to see "Out of Stock" products.

This is a valid bug indeed. I filed a separate bug in the blocks repository: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2950. 

Because this issue has 2 separate bugs in 2 different repositories now filed, I am closing it here.

**Closed by juliaamosova** 2020-07-31 22:52 UTC
