### ISSUE TITLE
Adding something to the cart causes "rest_cookie_invalid_nonce 403" error.

### ISSUE THREAD

**Issue by yunusbayraktaroglu** [woocommerce/woocommerce#25437] opened 2020-01-20 23:41 UTC
**Describe the bug**
Adding something to the cart causes rest_cookie_invalid_nonce 403 error.

I'm installing WooCommerce to a fresh default theme(Twenty nineteen). Then I'm creating a page named reviews that includes WooCommerce all reviews gutenberg block.  

In a browser that has not visited the site before (without cookies, not logged in), the reviews page is displayed without any problems. If I go to the store afterwards and add anything to the cart and return to the reviews page again, I get the the "code":"rest_cookie_invalid_nonce" 403 warning in the console.

**To Reproduce**
1. Create a page with WooCommerce all reviews gutenberg block
2. See the page with as a visitor.
3. Go to shop and add something to the cart 
4. Return the reviews page
4. You are not able to see reviews again. See error on console.

**Screenshots**

**Expected behavior**
Adding something to the cart does not cause rest_cookie_invalid_nonce 403 error

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
5.3.2
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR
External object cache: –

**Comment by claudiosanches** [comment] 2020-01-24 22:06
> In a browser that has not visited the site before (without cookies, not logged in), the reviews page is displayed without any problems. If I go to the store afterwards and add anything to the cart and return to the reviews page again, I get the the "code":"rest_cookie_invalid_nonce" 403 warning in the console.

It makes sense, it suppose to invalidate the cookie, since the session there's something in the cart, and it's not more user 0.
Sounds like it's getting save on cache the nonce for the request, that's why it's getting this error, but you need to fresh it after some product is on the cart.

**Comment by yunusbayraktaroglu** [comment] 2020-01-24 22:32
Isn't it a bug?

Which cookie do we need to renew using which hook? Can you give some detail?

**Comment by hybridwebdev** [comment] 2020-04-23 23:37
Any reason why this was closed? I too am experiencing this. It's absolutely a bug. If you insist it's NOT a bug, how would you suggest getting around this?

To clarify, it's occuring when a user is not logged in. If they have nothing in the cart, the first time you try and add an item you'll get the  "rest_cookie_invalid_nonce" error. However, the item IS actually added. Subsequent visits after an item has been added adding items will work just fine. It seems that on initial visit, the cart is somehow not initialized properly. Once the user has a cart (which is created the first time they add an item) the cart is properly initialized and this error no longer occurs.

So again, this issue is definitely NOT closed as it's absolutely a bug. Again, if you do not consider this to be a "bug" then please suggest a way to fix the issue.

Just saying "it's not a bug, you're just doing it wrong" in horribly broken english won't magically fix this. Please do your job and offer proper support for your product.

**Comment by hybridwebdev** [comment] 2020-04-23 23:43
> Isn't it a bug?
> 
> Which cookie do we need to renew using which hook? Can you give some detail?
DI

> Isn't it a bug?
> 
> Which cookie do we need to renew using which hook? Can you give some detail?

Hey, so turns out this might be applicable

https://github.com/woocommerce/woocommerce/issues/24241

It solved the issue for me.

**Comment by yunusbayraktaroglu** [comment] 2020-04-24 14:02
I solved the problem by writing my own all reviews function that don't need REST api

**Comment by kminderhout** [comment] 2020-07-06 01:32
See this issue thread for more information. [https://github.com/woocommerce/woocommerce/issues/23682](url) This is expected behavior and if you add items to cart via REST API then you will need to pass the new nonce back in the response and update it on the page if you want to do something before reloading.

**Comment by hybridwebdev** [comment] 2020-09-19 06:15
Welp, looks like this has been totally broken again in 4.3. Is the WC dev team doing this intentionally, or are they really this incompetent? You cannot just remove functionality like this and then tell people "Use our endpoint nub", that is a piss poor response. 

I seriously LOVE spending hours of my life trying to find a work around for stupidity.

**Comment by michaeltieso** [comment] 2020-10-05 19:34
> Seriously considering starting a class action lawsuit against the developers.

lol

**Comment by hybridwebdev** [comment] 2020-10-05 22:40
> > Seriously considering starting a class action lawsuit against the developers.
> 
> lol

Why lol? You think it's okay that with every new release, they break peoples sites?

**Comment by claudiosanches** [comment] 2021-04-01 00:04
Duplicated of #23682

**Closed by claudiosanches** 2021-04-01 00:04 UTC
