### ISSUE TITLE
Fatal error on deleting a user or a subsite

### ISSUE THREAD

**Issue by christofervas** [woocommerce/woocommerce#30266] opened 2021-07-13 13:14 UTC
In a clean multisite installation with WooCommerce 5.5 activated only on main site I get the following fatal error when I try to delete a user or a subsite:

`Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Table 'xxx.xxx_actionscheduler_actions' doesn't exist in /xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 /home/cu in /xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44`

**Comment by vedanshujain** [comment] 2021-07-13 13:22
Possible duplicate of https://github.com/woocommerce/woocommerce-admin/issues/7141

**Comment by rodelgc** [comment] 2021-07-14 08:27
Hi @christofervas,

Thank you for reporting the issue. However, this issue had been reported previously [here](https://github.com/woocommerce/woocommerce-admin/issues/7141). We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Closed by rodelgc** 2021-07-14 08:27 UTC
