### ISSUE TITLE
Save variation issue could not be saved

### ISSUE THREAD

**Issue by zstran95** [woocommerce/woocommerce#25972] opened 2020-03-19 06:27 UTC
**Describe the bug**
I cannot create a new variation product that disappears on its own and does not save it

**To Reproduce** **Screenshots**
1. Go to https://imgur.com/FTGcXtp
2. Click on https://imgur.com/IKTcCDk
3. See error : https://imgur.com/uOgw86F
https://imgur.com/wqR10xL

**Expected behavior**
When I created a variation product, the product was not saved and displayed virtually impossible to save

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 912 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: vi
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.5
PHP Version: 7.3.15
PHP Post Max Size: 5 GB
PHP Time Limit: 512
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB
Max Upload Size: 5 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_02f1bd5_
Kích thước tổng dữ liệu: 120.73MB
Kích thước cơ sở dữ liệu: 96.33MB
Kích thước chỉ mục dữ liệu: 24.40MB
wp_02f1bd5_woocommerce_sessions: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
wp_02f1bd5_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_02f1bd5_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_02f1bd5_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_02f1bd5_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_actionscheduler_actions: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
wp_02f1bd5_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_actionscheduler_logs: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_02f1bd5_arcontactus: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_arcontactus_callback: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_arcontactus_prompt: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_02f1bd5_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_masterslider_options: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_masterslider_sliders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_options: Data: 22.55MB + Index: 5.02MB + Engine InnoDB
wp_02f1bd5_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_pmxi_images: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_pmxi_posts: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_postmeta: Data: 17.55MB + Index: 13.03MB + Engine InnoDB
wp_02f1bd5_posts: Data: 11.52MB + Index: 2.66MB + Engine InnoDB
wp_02f1bd5_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_term_relationships: Data: 0.52MB + Index: 0.47MB + Engine InnoDB
wp_02f1bd5_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_usermeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_02f1bd5_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_02f1bd5_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wc_customer_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_02f1bd5_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_02f1bd5_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_wc_product_meta_lookup: Data: 0.48MB + Index: 0.91MB + Engine InnoDB
wp_02f1bd5_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_02f1bd5_wfconfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wffilemods: Data: 24.58MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wfhits: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_02f1bd5_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_02f1bd5_wfknownfilelist: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_02f1bd5_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_02f1bd5_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_02f1bd5_wfstatus: Data: 0.33MB + Index: 0.19MB + Engine InnoDB
wp_02f1bd5_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_woodmart_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_02f1bd5_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_yoast_seo_links: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_02f1bd5_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 4219
cms_block: 3
customize_changeset: 2
nav_menu_item: 12
page: 21
portfolio: 1
post: 20
product: 2412
product_variation: 2918
revision: 20
shop_order: 246

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Thông báo lỗi không nên được hiển thị với khách ghé thăm.

### Active Plugins (22) ###

Advanced Access Manager: bởi Vasyl Martyniuk <vasyl@vasyltech.com> – 6.4.1
Contact Us all-in-one button: bởi Areama – 1.7.7
Easy Theme and Plugin Upgrades: bởi Chris Jean – 2.0.1
WPBakery Page Builder: bởi Michael M - WPBakery.com – 6.1
Loco Translate: bởi Tim Whitlock – 2.3.1
Master Slider Pro: bởi averta – 3.2.14
Cổng thanh toán MOMO: bởi Lê Văn Toản – 1.0.1 – Chưa kiểm tra với phiên bản hiện tại của WooCommerce
Perfect WooCommerce Brands: bởi QuadLayers – 1.8.0
UpdraftPlus - Backup/Restore: bởi UpdraftPlus.Com
DavidAnderson – 2.16.22.24

WooCommerce VTC Gateway: bởi toanld – 2.0 – Chưa kiểm tra với phiên bản hiện tại của WooCommerce
Checkout Field Editor for WooCommerce: bởi ThemeHigh – 1.4.1 – Chưa kiểm tra với phiên bản hiện tại của WooCommerce
Variation Swatches for WooCommerce - Pro: bởi Emran Ahmed – 1.0.43 – Chưa kiểm tra với phiên bản hiện tại của WooCommerce
Variation Swatches for WooCommerce: bởi Emran Ahmed – 1.0.77
WooCommerce Email Customizer: bởi cxThemes – 3.33 – Chưa kiểm tra với phiên bản hiện tại của WooCommerce
WooCommerce Google Product Feed: bởi Ademti Software Ltd. – 8.1.0
WooCommerce: bởi Automattic – 4.0.0
Woodmart Core: bởi  – 1.0.21
Wordfence Security PREMIUM: bởi Wordfence – 7.4.6
Yoast SEO Premium: bởi Đội nhóm Yoast – 13.2
Dobby: bởi Thorsten Frommen – 1.3.0
WP Mail SMTP: bởi WPForms – 1.8.1
WP Rocket: bởi WP Media – 3.5.0.4

### Inactive Plugins (1) ###

Media Cleaner Pro: bởi Jordy Meow – 5.6.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: VND (₫)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop mặc định: #9 - /cua-hang/
Giỏ hàng: #10 - /gio-hang/
Thanh toán: #11 - /thanh-toan/
Tài khoản: #12 - /tai-khoan/
Quy định và Điều kiện: ❌ Trang chưa được đặt

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 4.5.2
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-product_cat.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/admin-cancelled-order.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/admin-failed-order.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/admin-new-order.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-completed-order.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-invoice.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-new-account.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-note.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-on-hold-order.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-processing-order.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-refunded-order.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-reset-password.php phiên bản 3.7.0 đã lỗi thời. Phiên bản chính là 4.0.0
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-addresses.php phiên bản 3.5.4 đã lỗi thời. Phiên bản chính là 3.9.0
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-customer-details.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-downloads.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-footer.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-header.php phiên bản 2.4.0 đã lỗi thời. Phiên bản chính là 4.0.0
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-order-details.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-order-items.php
/home/nuochoarosa.com/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-styles.php phiên bản 3.3.0 đã lỗi thời. Phiên bản chính là 4.0.0
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php phiên bản 3.6.0 đã lỗi thời. Phiên bản chính là 4.0.0
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php phiên bản 3.4.0 đã lỗi thời. Phiên bản chính là 4.0.0
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Tìm hiểu làm thế nào để cập nhật

### WooCommerce Google Product Feed fields ###

Product description: Main product description only (short preferred.)
Availability: Defaults to "in stock".
Brand: Pre-populates from pwb-brand taxonomy.
Manufacturer Part Number (MPN): 
Product Type: Pre-populates from product_cat taxonomy.
Google Product Category: 
Unit pricing measure: Pre-populates from pa_size taxonomy.

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled

### Action Scheduler ###

Hoàn tất: 626
Oldest: 2020-03-13 10:04:06 -0700
Newest: 2020-03-16 05:27:59 -0700

`
</details>

**Comment by peterfabian** [comment] 2020-03-19 10:17
Hi @zstran95 , you attached the same picture 3x, so we can't see the error, unfortunately. Please update your report.

**Comment by zstran95** [comment] 2020-03-19 13:52
> Xin chào @ zstran95 , cảm ơn bạn đã báo cáo lại cho chúng tôi.
> Tuy nhiên, thật không may, bạn đã đính kèm cùng một hình ảnh 3x, vì vậy chúng tôi không thể thấy lỗi. Vui lòng cập nhật báo cáo của bạn.

**To Reproduce** **Screenshots**
Steps to reproduce the behavior:
1. Go to https://imgur.com/FTGcXtp
2. Click on https://imgur.com/IKTcCDk
3. See error : https://imgur.com/uOgw86F
https://imgur.com/wqR10xL

I have updated it :-D

**Comment by juliaamosova** [comment] 2020-03-19 17:40
Hi @zstran95,

Thank you for following-up on the issue. However, I can’t reproduce it on my end. Everything is working as expected and I can successfully create a variable product. 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by zstran95** [comment] 2020-03-20 02:03
> Xin chào @ zstran95 ,
> 
> Cảm ơn bạn đã theo dõi về vấn đề này. Tuy nhiên, tôi không thể sao chép nó vào cuối của tôi. Mọi thứ đều hoạt động như mong đợi và tôi có thể tạo thành công một sản phẩm khác nhau.
> 
> Tôi thấy rằng bạn đã cài đặt một số plugin và bạn không sử dụng một trong những chủ đề mặc định của chúng tôi có thể gây ra sự cố. Vui lòng kiểm tra trang web của bạn để tìm xung đột chủ đề và plugin. Để làm điều đó, bạn cần hủy kích hoạt tất cả các plugin ngoại trừ WooC Commerce và chuyển đổi chủ đề mặc định như  [Storefront](https://en-gb.wordpress.org/themes/storefront/) . Sau đó kiểm tra lại.
> 
> Nếu sự cố được giải quyết với chủ đề mặc định và tất cả các plugin bị vô hiệu hóa, điều đó có nghĩa là một trong các plugin hoặc chủ đề của bạn đang gây ra sự cố. Sau đó, bạn sẽ cần kích hoạt từng cái một và kiểm tra mỗi khi bạn làm điều đó để tìm ra plugin nào gây ra sự cố.

I have tried all the deletion of the plugin leaving only the product and am still unable to add variants

**Comment by juliaamosova** [comment] 2020-03-20 14:57
>I have tried all the deletion of the plugin leaving only the product and am still unable to add variants

@zstran95 are there any error messages in the error logs or browser console?

**Comment by zstran95** [comment] 2020-03-20 15:16
> > I have tried all the deletion of the plugin leaving only the product and am still unable to add variants
> 
> @zstran95 are there any error messages in the error logs or browser console?

I don't see any message, I have installed and exported the product through a new site. The status is still with the product variant.

**Comment by juliaamosova** [comment] 2020-03-20 16:21
@zstran95 we just released WooCommerce 4.0.1 where we reverted the change related to how variations are being saved: https://github.com/woocommerce/woocommerce/pull/25950. Can you please update to 4.0.1 and let us know if the issue is resolved for you?

**Comment by zstran95** [comment] 2020-03-22 17:40
> @zstran95 we just released WooCommerce 4.0.1 where we reverted the change related to how variations are being saved: #25950. Can you please update to 4.0.1 and let us know if the issue is resolved for you?

I tried on the Apache server the bed as the error is solved but there seems to be an error on nginx

**Comment by juliaamosova** [comment] 2020-03-30 13:41
@zstran95 can you please try a brand new install on nginx with only WooCommerce activated?

**Comment by juliaamosova** [comment] 2020-04-06 18:59
Hi @zstran95,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-04-06 18:59 UTC
Labels: can't reproduce, status: needs feedback
