### ISSUE TITLE
Change processing email if COD

### ISSUE THREAD

**Issue by tmblog** [woocommerce/woocommerce#21742] opened 2018-10-29 19:09 UTC
**Is your feature request related to a problem? Please describe.**
I think there is a similar request but I am not entirely sure it is the same, so I'll post.

The processing email has a default email heading and title, which suggests payment has been received, the content of the email is also a little vague. E.g. _Just to let you know your payment has been confirmed._
Now of course saying that payment has received in the email subject when the user chose COD is extremely troublesome, this is entirely false because how could they have paid when it is Cash On Delivery. This email is perfect and suited more for checking out with an online payment gateway such as Stripe or PayPal.

**Describe the solution you'd like**
If it is COD then the email subject should be along the lines of: **Thank you for your order**.
And the heading should be: **Order received.**
The content should be inline with above e.g. thank you for your order we are processing it, you have chosen to pay with Cash on collection. Optional: _We will notify you when your order has been dispatched._
**Describe alternatives you've considered**
I am going into each site, I manage around 20+ and manually changing the title and subject to what I have suggested above without changing the email body because it applies to Stripe/PayPal etc.
**Additional context**
Customers could potentially say here's my proof that I have paid, depending on jurisdiction they might be right in the eyes of trading standards (long shot I know but people do try it). We already had one customer showing us the email just to bring to our attention not to argue they'd paid :-)
I dont mind changing the headings and subject manually on all 20+ sites (am doing anyway) but because it doesn't fit both payment methods (COD & PayPal/Stripe) it is a little vague.

I hope others can see and vote on this so we can find a midlle ground!

**Comment by jobthomas** [comment] 2018-11-13 12:40
Another report of this issue is mentioned here: https://wordpress.org/support/topic/email-problem-on-woocommerce/

**Comment by petko** [comment] 2018-11-19 22:34
Yes, that's a big problem for us too. And even if we change the subject line/email heading, the body text still says "your payment has been confirmed", making things even more confusing..

**Comment by heArt-coder** [comment] 2018-11-23 16:01
Yes customers want to be sure that there payment was successful but it creates a problem with COD.

Things like "We will notify you when your order has been dispatched" is dangerious since core woocommerce doesn't do that. Most shop owners doesn't use any shipment tracking method.

The main sentence here must be simple enough without putting shop owners into weird position.

 This exemple should work:
"Just to let you know &mdash; your order #%s has been confirmed, and now being processed:"

This sentence simple enough. Appropriate for every kind of payment methods. Both customers that payed and will pay on delivery can be sure that there order was successful and being processed.

**Comment by heArt-coder** [comment] 2018-11-23 16:11
Just checked the previous version 1.6.4 and wow... developers did amazing job to better it. "Just to let you know" feels warmer but that "payment" word caused us too much trouble.

**Comment by mklusak** [comment] 2018-11-26 12:19
This is serious issue for our websites, too! I have to replace this WC email template with my edited file on every website ... it's not possible to inform customers that they already paid when they clearly did not.

**Comment by janeng424** [comment] 2018-12-05 07:10
Same problem here

**Comment by EdithAllison** [comment] 2018-12-20 21:38
Another vote for changing text to remove references to payment. The shops I handle use bank transfer as well as payment on collection, neither should reference a received payment as it confuses customers and creates uncertainty over the payment status of an order.

**Comment by mikejolley** [comment] 2019-01-08 16:14
Duplicate of https://github.com/woocommerce/woocommerce/issues/22037

**Closed by mikejolley** 2019-01-08 16:14 UTC
Labels: bug

**Comment by brandtashley** [comment] 2019-05-02 00:24
Is there any resolve to this WC issue? I can't even see where to edit the email template that goes out. I only have one website with WooCommerce, so if i can edit the email template I'll be very grateful. >>  Subject: Payment received for your order
<img width="668" alt="Screen Shot 2019-05-02 at 12 22 46 PM" src="https://user-images.githubusercontent.com/50187339/57051331-22d92200-6cd5-11e9-9121-5c1525212c60.png">
