### ISSUE TITLE
Woocommerce Slack is constantly querying API for available groups

### ISSUE THREAD

**Issue by dangoriaynov** [woocommerce/woocommerce#29450] opened 2021-03-20 18:32 UTC
Woocommerce Slack plugin is constantly making querying to the Slack API to get the groups created.
However when no groups are created - then empty value is stored in the DB. This is causing another calls to be made to Slack API (up to 20 API calls for 1 page navigation)
Keep in mind that groups functionality is limited to Slack Premium accounts only.

This is the actual code making API calls - it assigns empty value to the variable $all_groups and stores it in the DB.
Next call to the same method triggers API call again (since $all_groups is empty)
**includes/class-wcslack-settings.php**
```
	public function available_channels() {
		$wcslack_api = new WC_Slack_API();

		$wrapper     = $this->wrapper();
		$api_key     = $wrapper['api_key'];
		$connection  = $this->test_client_connection();

		if ( $api_key && $connection ) {
			$all_channels = get_transient( 'wcslack_all_channels' ) ?: array();
			$all_groups   = get_transient( 'wcslack_all_groups' )   ?: array();
...
			if ( empty( $all_groups ) ) {
				$all_groups = (array) $wcslack_api->all_groups( $api_key );
				set_transient( 'wcslack_all_groups', $all_groups, 86400 );
			}
...
```

To see this issue you could simply do the following:
1. install "Query Monitor" plugin
2. open any page in the site you are examining
3. see the HTTP API Calls section

Expected - this section has only few requests
Actual - there are 10-20 calls to Slack API to _https://slack.com/api/groups.list_ , see: https://ibb.co/Zf1JK3M

Possible options to fix this:
 - make groups API call check optional (if such option is selected by user)
 - make groups API call only for the Premium Slack accounts (since Free accounts doesn't have it anyway)

**Comment by tammullen** [comment] 2021-03-22 21:27
Hi @dangoriaynov 

Thanks for raising this.   
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
The issue you are having seems to be caused by the WooCommerce Slack plugin which is one of the paid products on our marketplace. 

I have checked and the issue you are having has already been raised as a bug in the private WooCommerce Slack repository. I have added your report there.

If you need to get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

I am closing this issue for now as it not a WooCommerece bug.

**Closed by tammullen** 2021-03-22 21:27 UTC
