### ISSUE TITLE
Admin product list sort by price

### ISSUE THREAD

**Issue by alexcroox** [woocommerce/woocommerce#16708] opened 2017-09-05 08:18 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Visit WP Admin > WooCommerce > Products
2. Click price column to order by price

## Expected/actual behavior

When I follow those steps, I see the products in a random order, not ordered by price

I was expecting to see the list of products in descending or ascending price order

![ss](https://cl.ly/mK7F/Screen%20Shot%202017-09-05%20at%2009.15.18.png)

**Comment by mikejolley** [comment] 2017-09-05 08:21
@alexcroox Ruled out conflicts? Also missing status report. I'm guessing it's a plugin conflict because this is working my side no issue.

**Comment by mikejolley** [comment] 2017-09-06 09:58
Feel free to reply back once you've narrowed it down and followed the steps on the issue form. I'm closing this for now as non-reproducible.

**Closed by mikejolley** 2017-09-06 09:58 UTC
Labels: Status: Needs Author Reply / Changes
