### ISSUE TITLE
Automatewoo cannot send email due to emogrify

### ISSUE THREAD

**Issue by taonergy** [woocommerce/woocommerce#26223] opened 2020-04-20 18:30 UTC
Hi there, my automatewoo cannot send email to customers due to emogrify errors. It's okay if I send plain text but if I chose to send HTML email then it has this issues showed up in logs

Unexpected shutdown: PHP Fatal error Uncaught Error: Call to undefined method Pelago\Emogrifier::disableInvisibleNodeRemoval() in /home/miliunlo/public_html/wp-content/plugins/automatewoo/includes/mailer.php:479 Stack trace: #0 /home/miliunlo/public_html/wp-content/plugins/automatewoo/includes/mailer.php(257): AutomateWoo\Mailer->emogrify('\n

**Comment by juliaamosova** [comment] 2020-04-20 21:33
Hi @taonergy,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the AutomateWoo plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/). 

One of our tech support engineers will be able to confirm the bug with you and file it with the correct team. They will then be able to provide you updates on when it will be fixed. This is not something that we can do here or move the issue to the AutomateWoo repository (it is not public). Thank you for understanding.

**Closed by juliaamosova** 2020-04-20 21:33 UTC
