### ISSUE TITLE
Category thumbnail not saved

### ISSUE THREAD

**Issue by realrecordzLab** [woocommerce/woocommerce#25658] opened 2020-02-13 13:08 UTC
I'm having trouble while I try to select a category thumbnail image. 

After I select the image I want to use and click save, the image will not be displayed. This problem will occur only for certain images, I have successfully added one image that is  118x90 pixel and another one that is 150x90px, others images will be not added and I don't know why. 

Here is a screen of what I see after saving to apply the thumbnail. It's like no image is selected.
![scr-0](https://user-images.githubusercontent.com/51746386/74438326-328fb480-4e6a-11ea-989c-8db66ef684a9.jpeg)

I'm using the last version of woocommerce and the thumbnail settings is 150x150pixel. The problem will occur also if I use hi-res images of 1080x1080pixel

I found this line inside the woocommerce log

``` 
CRITICAL Maximum execution time of 30 seconds exceeded in /Users/account/Sites/mysite/wp-includes/class-wp-image-editor-imagick.php alla riga 363
```

**Comment by tammullen** [comment] 2020-02-19 01:13
Hi @realrecordzLab 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-02-19 01:13 UTC
