### ISSUE TITLE
Botão de comprar não aparece em baixo do produto 

### ISSUE THREAD

**Issue by beacsantana** [woocommerce/woocommerce#28050] opened 2020-10-21 21:44 UTC
O botão de comprar não aparece em baixo do produto, já pesquisei em todos os lugares e não achei 
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>
![eddeded](https://user-images.githubusercontent.com/73258408/96790529-53cb7c00-13cd-11eb-83fc-721f5f3a6331.jpg)

**Comment by Konamiman** [comment] 2020-10-22 07:39
_Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back._

Hi there. It looks like you are requesting support rather than notifying a bug. Please do one of the following:

- Check if our [Self-Service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) helps you on finding the cause of the issue.
- If not, check out our [How to Get Help guide](https://docs.woocommerce.com/document/how-to-get-help/) where you can find more information, as well as instructions on how to open a support ticket.

I'm closing this issue for now. If none of the above helps, please contact us again providing more information (Expected/actual behavior, Steps to reproduce, WordPress environment... as described in the issue template) so that we can try and troubleshoot the issue. Thank you!

**Closed by Konamiman** 2020-10-22 07:39 UTC
