### ISSUE TITLE
List product categories using REST API version 3

### ISSUE THREAD

**Issue by mahdiyazdani** [woocommerce/woocommerce#22103] opened 2018-12-02 17:19 UTC
I’m trying to list product categories with sending a public request to REST API version 3, but somehow it doesn’t work as expected! I was wondering if someone can help me with this?

Request path: `http://localhost:8888/wp-json/wc-pb/v3/products/categories`

**Comment by rrennick** [comment] 2018-12-03 15:41
The documentation is at http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories

**Comment by claudiosanches** [comment] 2018-12-20 13:43
Hi there, thanks for posting. I wasn’t able to replicate this issue since there is no details or steps to reproduce.

I'm testing and works just fine, as always.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks

**Closed by claudiosanches** 2018-12-20 13:43 UTC
