### ISSUE TITLE
Documentation on how to set up a development environment needs to be updated

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#29362] opened 2021-03-12 12:41 UTC
I believe that the wiki page that documents how to set up a development environment needs to be updated: https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment

It tells people to run `npm run build` to generate assets, but since https://github.com/woocommerce/woocommerce/pull/27312, this command generates a .zip file instead of compiling assets (cc @claudiosanches). I think that after that PR those configuring a dev env should run `npm run build:core`.

I'm unsure if running `npm run build:packages` is a required step as well and should be included in the documentation (cc @rrennick).

**Comment by rrennick** [comment] 2021-03-12 13:18
> I'm unsure if running npm run build:packages is a required step as well and should be included in the documentation

When you are doing the initial set up `npm install` runs `npm run build:packages`. If any of the local E2E packages has its build files then the build is skipped for that package.

**Comment by rodrigoprimo** [comment] 2021-03-12 13:39
Thanks for the clarification, @rrennick. I guess that just replacing `npm run build` with `npm run build:core` might be enough.

**Comment by rrennick** [comment] 2021-03-12 14:35
See also #26953.

**Comment by helgatheviking** [comment] 2021-07-02 02:04
potentially related: #27494

**Comment by helgatheviking** [comment] 2021-10-20 16:03
`composer install` and `npm run build` no longer exist so now how to we build this? would be very helpful to have start up instruction in the readme.md. 

Edited: to clarify, they _do_ exist in the repo's `plugins/woocommerce` folder, which I needed to symlink into my `wp-content/plugins` folder. Another bit that probably should be added to the readme docu as you can't clone this folder directly into the `wp-content/plugins` folder and have it function as a regular plugin without some trickery.

**Comment by haszari** [comment] 2022-05-02 22:32
Also noting [the docs for setting up wp-env](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#configure-a-local-wordpress-instance-with-wp-env) could be clearer. 

Specifically, there's no `.wp-env.json` or any wp-env config in the repo. This is fine, but it's not clear in the docs, because it mentions defaults: `You can create .wp-env.override.json file and override the default configuration values.`. 

I think it would be a good idea to document the recommended way to set up wp-env with the woocommerce source mapped as a plugin. Also it's worth explaining if anything needs to be built before the plugin will be recognised by WordPress. Also it's helpful to present the steps in recommended order. In the current docs, cloning the repo comes after starting an environment, which I wouldn't recommend. For example, something like this:

0. Install required dependencies (npm, composer, nx and pnpm installed globally). 
1. Clone woocommerce repo.
2. Build the plugin and assets.
3. Start a WordPress environment with the plugin mapped. 

Once I've got my env up and running I'm happy to document my steps :)

**Comment by haszari** [comment] 2022-05-02 23:47
I just noticed there are at least two different docs:

https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#configure-a-local-wordpress-instance-with-wp-env

https://github.com/woocommerce/woocommerce/blob/trunk/DEVELOPMENT.md

I suggest deleting one of these and focus on improving one canonical doc.

**Comment by haszari** [comment] 2022-05-02 23:49
Here's my recommended zero-to-running docs:

### Install developer tooling

- Install `npm` LTS version.
- Install `composer`.
- Install nx globally: `sudo npm install -g nx`.
- Install pnpm globally: `sudo npm install -g pnpm`.
    
    

Side note: I saw an error about my pnpm version being too new, so I installed specific version: `sudo npm install -g pnpm@6.24.2`

Outcome: npm LTS is installed, nx and pnpm are installed globally and can be run from command line.

### Clone repository and build

- Clone this repo
- Switch directory to the `plugins/woocommerce` subfolder. ***Note that this repo does not have the WordPress plugin or the primary build scripts in the repo root.***
    - `cd ./plugins/woocommerce`
- Install npm dependencies: `pnpm install`.
- Install composer dependencies: `pnpm nx composer-install woocommerce`
- Build 1: `pnpm nx build woocommerce`
- Build 2: `pnpm nx build woocommerce-legacy-assets` or `pnpm nx build-watch woocommerce`

Outcome: WooCommerce is built, can be loaded as a plugin.

Note: the plugin is not at repo root. It's at `./plugins/woocommerce` which is unusual for a WordPress plugin, so it's worth documenting this.

### Launch a WordPress environment with plugin
- Launch default wp-env from `./plugins/woocommerce`: `wp-env start`.

Optional: customise the wp-env config with `.wp-env.override.json`, e.g. change ports or map other plugin code.

Outcome: should have WordPress running at http://localhost:8888/ and can log in with `admin` `password`.

<details>
My old comment when I was confused :)

~~I'm doing this with wp-env, so these are my steps.~~

- ~~Ensure wp-env, docker, and docker-compose are installed and available.~~
- ~~Make a wp-env config file or override. The only essential step is mapping the WooCommerce plugin:~~

```
{
	"plugins": [
		"./plugins/woocommerce"
	]
}
```

~~Side note: this could be in `.wp-env.json` or `.wp-env.override.json`. I recommend adding `.wp-env.json` to `.gitignore` unless there is a plan to have a built in wp-env config.~~
</details>

### Activate and onboard WooCommerce

- Log in to admin in dev env, e.g. [http://localhost:8888/wp-admin/](http://localhost:8888/wp-admin/plugins) `admin` `password` (wp-env defaults).
- Ensure the plugin is activated: [http://localhost:8888/wp-admin/plugins.php](http://localhost:8888/wp-admin/plugins.php)
- Trigger onboarding wizard and set up WooCommerce: [http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard](http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard)

**Comment by haszari** [comment] 2022-05-03 01:25
Update: I see now [there is a wp-env config in `./plugins/woocommerce`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/.wp-env.json). Now the docs about `.wp-env.override.json` make sense to me :)

**Comment by helgatheviking** [comment] 2022-06-09 19:42
@haszari's instructions for "building" the plugin should be on a `readme.md` in the woocommerce plugin folder!!

**Comment by helgatheviking** [comment] 2022-06-10 13:00
Looks like those instructions are already out of date as of yesterday... 
https://github.com/woocommerce/woocommerce/commit/b7931409f2a553bea765f0fda421f182c58d8e4b

**Comment by lsinger** [comment] 2022-06-10 13:41
We really need instructions that are as simple as those by @haszari, and they need to be easily accessible in a prominent place, like @helgatheviking mentions. 

That could be in the Wiki with a link in the README or it could be in the README directly or in the CONTRIBUTING or something similar. FWIW, the Wiki has the issue that it's hard for the community to contribute improvements, so if we can put this into a Markdown file in the repo somewhere I'd prefer that. 

Not sure if @ObliviousHarmony's changes in b793140 already include all instructions needed? I haven't immediately found anything for generating assets, but maybe that's magicked away now?

**Comment by helgatheviking** [comment] 2022-06-10 13:43
I still vote `readme.md` directly as it is immediately visible when you visit the repo!

**Comment by ObliviousHarmony** [comment] 2022-06-10 19:09
We've made these kinds of tooling changes with the intention of making it easier for many developers to work on different projects within the monorepo. Tools like `pnpm` increase the speed of installing dependencies while tools like `turbo` include extensive caching to avoid rebuilding code that hasn't changed. At this point it should be very easy to get started with development here, but, I'd love to understand what kinds of improvements we should be making.

It would be great to start a move towards in-repository documentation. I'd like to see every code change that influences documentation be paired with a corresponding documentation update. This would prevent drift and make it easier for us to maintain. It also opens the door for external contributors to provide documentation improvements as needed.

For now though, please let me know if the new top-level `README.md` file serves as a better getting started guide.

**Comment by haszari** [comment] 2022-06-12 20:03
> Not sure if @ObliviousHarmony's changes in https://github.com/woocommerce/woocommerce/commit/b7931409f2a553bea765f0fda421f182c58d8e4b already include all instructions needed? I haven't immediately found anything for generating assets, but maybe that's magicked away now?

> https://github.com/woocommerce/woocommerce/pull/33079/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

From a brief look at the changes [in that PR](https://github.com/woocommerce/woocommerce/pull/33079), there's still no clear steps documented for starting from nothing and getting WooCommerce built and running.

- DEVELOPMENT.md still recommends starting wp-env before building WooCommerce
- README.md has some specific steps but it's not clear, and there's a lot of background documentation advocating or explaining why we use certain tools

**Comment by ObliviousHarmony** [comment] 2022-06-13 20:33
@haszari Would you prefer if the `DEVELOPMENT.md` had more of the content and explanations from the current `README.md` and the `README.md` contained very specific commands to run to start developing with no additional context? That might make it easier to jump right into without being concerned about how the repository actually works.

I see that we also need to revamp the `DEVELOPMENT.md` as well. We should probably link to this from the Wiki's page on setting up a development environment.

Any other thoughts on changes to the documentation? I am planning to replace the `pnpm exec turbo` references with `pnpm -- turbo` since that's fewer characters and a bit more ergonomically sound.

**Comment by haszari** [comment] 2022-06-13 20:41
> Would you prefer if the DEVELOPMENT.md had more of the content and explanations from the current README.md and the README.md contained very specific commands to run to start developing with no additional context? That might make it easier to jump right into without being concerned about how the repository actually works.

Yes, I would love that approach @ObliviousHarmony  🙌  E.g. so `Readme` is like:

- Welcome to the WooCommerce code repo [very brief product intro]
- Here's how to build and run this code [terse but bulletproof steps]
- To find out more … [links out to detail and `development.md` etc]

**Comment by haszari** [comment] 2022-06-13 20:44
> Note: the plugin is not at repo root. It's at ./plugins/woocommerce which is unusual for a WordPress plugin, so it's worth documenting this.

I think that detail should be in the readme, as it's confusing/surprising to the uninitiated. The step-by-step will help make that clear but I think it's important to loudly mention this.

**Comment by ObliviousHarmony** [comment] 2022-06-13 20:55
@haszari This is actually documented near the top of the readme. Under the section about the structure of the repository. Do you think that's notable enough? With less text in the readme it might feel less hidden among the walls of information :D

**Comment by helgatheviking** [comment] 2022-06-14 01:19
>It would be great to start a move towards in-repository documentation.

@ObliviousHarmony  I think that's key. This feels like the 3rd system of build tools in my recent memory... and they always feel extra difficult for me as a rule. It might just be trying to run them in WSL, though that's been a large improvement over running them in Windows itself (b/c that never worked! :) )

I would still like to see plugin-level package building... especially asset building instructions included in the plugin folder readme... https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce 

For example, If I am working on a CSS style tweak to WooCommerce itself, I would like to regenerate the WooCommerce core stylesheets without needing to regen the entire mono-repo assets. So something on the plugin page that already assumes I have the mono-repo installed and symlinked... and a link back to the root readme for more on set up if that's not the case?

**Comment by ObliviousHarmony** [comment] 2022-06-15 00:26
Thanks for the feedback @helgatheviking. I've gone ahead and submitted a pull request to further expand on our documentation. While there's certainly more to write, this should be a good step in the right direction. I intentionally left out documentation on building specific components of WooCommerce Core because the names of those packages are awaiting a PR to update them.

For now, you can build the CSS assets using: `pnpm -- turbo run build --filter='woocommerce-legacy-assets'`.

Once we've landed that pull request I'll leave a comment here letting you know what the new name is. I'll also add some documentation about that to the `README.md` in `plugins/woocommerce`.

**Comment by helgatheviking** [comment] 2022-06-15 01:07
Nice start @ObliviousHarmony ! Kudos. What if there was a package.json script that existed as a shortcode for whatever the actual assets generating script is? `npm run do_assets_now` that always stays the same no matter what the actual script becomes? Would something like that be possible? And ideally, something uniform across the plugins.

**Comment by ObliviousHarmony** [comment] 2022-06-15 22:38
> What if there was a package.json script that existed as a shortcode for whatever the actual assets generating script is?

I've gotten this feedback a few times now, but, I'd really like to avoid it. Ultimately `turbo` commands only run the underlying script in the `package.json` file. We're going to look at actually preventing `build`, `lint`, and `test`  commands from being executed using `pnpm run` to avoid mistakes where someone might run `pnpm build` in `plugins/woocommerce` and end up with a non-functioning plugin. `turbo` builds and caches all of the dependencies and is always going to be the correct choice here.

> This feels like the 3rd system of build tools in my recent memory... and they always feel extra difficult for me as a rule.

Would you say that this is the root cause of your request? I'll admit, there has been a lot of volatility since the work to merge `woocommerce/woocommerce-admin` into this repository began. We've gone through a couple of iterations to reach this point, but, I don't believe there will be any more substantial changes.

In the long term, I would like to see all of our repository commands fall under `turbo` so that there's a single command to operate on the repository.

**Comment by helgatheviking** [comment] 2022-06-15 22:44
I'm sure that's part of it. And it's part of the pain of working on bleeding edge where I usually like to be so I can send PRs from time to time. I will be glad for this to stabilize, but I am probably never going to remember: 

`pnpm -- turbo run build --filter='woocommerce-legacy-assets'`

I still think a shortcut could be handy here. Something you can run from any plugin that will call the correct script for that plugin. but i like the idea of preventing people (read ME) from running a script that will result in a non-functioning plugin. :)

**Comment by ObliviousHarmony** [comment] 2022-06-15 23:52
For what it's worth @helgatheviking, you can technically just use `pnpm -- turbo run build`. Outside of just dependency compilation, a big part of the benefit is the fact that it caches output. If you run it once and then make a change in the `plugins/woocommerce/legacy` assets, then run it again, it will _only rebuild the assets_. Say you rebase and other things change too, it'll only rebuild those packages that have changed.

**Closed** 2022-06-16 04:55 UTC
Labels: needs: documentation, plugin: woocommerce

**Comment by ObliviousHarmony** [comment] 2022-06-16 18:55
@helgatheviking Against `trunk`, you should now use `pnpm -- turbo run build --filter='woocommerce/client/legacy'. :D

**Comment by helgatheviking** [comment] 2022-06-17 12:06
@ObliviousHarmony I am _never_ going to remember that :) could that be in the readme.md? ... or are you sure there couldn't be a shortcut for that? ex `npm run assets` and that maps to the full task?

**Comment by helgatheviking** [comment] 2022-06-17 12:17
ps - for those not using `pnpm -- wp-env start` i think the docu could mention needing to symlink the plugin folder into wp-content/plugins

**Comment by ObliviousHarmony** [comment] 2022-06-17 20:14
@helgatheviking I don't expect anyone to remember it that isn't working with it daily 😄 

> could that be in the readme.md?

Once #33460 gets merged I'm going to be expanding `plugins/woocommerce/README.md` with additional content about build these sub-components.

> are you sure there couldn't be a shortcut for that?

The suggestion I've made elsewhere is to set up a Bash alias! Then you can have whatever command suits your personal taste and not worry about the internals. Ultimately, I'd like to move away from running `pnpm run` commands at all. Once Turborepo supports running arbitrary commands, we won't allow it anymore. It's too easy to run `pnpm run build` or such and end up with a broken package.

> for those not using pnpm -- wp-env start i think the docu could mention needing to symlink the plugin folder into wp-content/plugins

Hmm, do you think those with the inclination to symlink folders into `wp-content/plugins` might know to do so from the plugin folder as opposed to the entire repository? I recognize things may be obvious to some but not so for others, and that's fine, I'm just wondering where on the spectrum I am here. Is this possibly just because you had already created a symlink prior to the monorepo and suddenly it broke everything for you?

**Comment by ObliviousHarmony** [comment] 2022-06-17 22:33
@helgatheviking I shipped [some more documentation about this](https://github.com/woocommerce/woocommerce/pull/33507), hope that helps too!

**Comment by haszari** [comment] 2022-06-19 20:45
> The suggestion I've made elsewhere is to set up a Bash alias!

Strong recommendation to have a specific list of documented and supported commands to use. Flexibility is great but anyone should be able to follow the instructions and build specific parts or the whole thing with known and supported standard commands. 

If everyone who works on this project has the same bash aliases set up, these should be promoted to a named script or command in the repo IMO.

**Comment by helgatheviking** [comment] 2022-06-20 15:19
Great! I was just helping someone in the community slack who is stuck on the symlink part... so I would love to see that mentioned. And I still hope you'll reconsider a couple shortcuts for the big ticket items like generating assets.

**Comment by ObliviousHarmony** [comment] 2022-08-05 18:15
Some good news for you @helgatheviking,

We've updated our infrastructure so that `turbo` commands are abstracted and don't need to be remembered anymore. You can now run `pnpm run build` from `plugins/woocommerce` and it will take care of everything for you. You can also run it from `plugins/woocommerce/client/legacy`. There are also some advanced usages documented, but, those are optional.

**Comment by helgatheviking** [comment] 2022-08-05 20:06
@ObliviousHarmony nice!! I did figure out how to write a bash script just for this, but in typical fashion still ran into problems yesterday with a fatal error due to missing file. 🤷🏻‍♀️ Will check again on Monday.

**Comment by helgatheviking** [comment] 2022-08-10 16:57
@ObliviousHarmony nice!! I did figure out how to write a bash script just for this, but in typical fashion still ran into problems yesterday with a fatal error due to missing file. 🤷🏻‍♀️

Let me try this new approach
