### ISSUE TITLE
Rest API does not process DELETE webhook requests

### ISSUE THREAD

**Issue by smurf9852** [woocommerce/woocommerce#23511] opened 2019-04-25 13:44 UTC
When doing DELETE /wp-json/wc/v2/webhooks/5?force=true request in Postman on my website, it accepts it as 200 OK.
When i do a GET on /webhooks/, it has disappeared from the list, however when i do a GET on webhook 5 it still shows it, should expect a 404?
In REST API Log, it did register as a accepted DELETE request.

**Comment by rodrigoprimo** [comment] 2019-04-25 14:14
I was not able to reproduce this problem on my local environment running the latest version of WC. After deleting the webhook using `DELETE /wp-json/wc/v2/webhooks/3?force=true`, I confirmed that the webhook was deleted by checking it is not included when I do `GET /wp-json/wc/v2/webhooks/` and also when I go to the webhooks admin page (`/wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks`).

If I call `GET /wp-json/wc/v2/webhooks/3` I get a 400 Bad Request as expected:

```
{
  "code": "woocommerce_rest_shop_webhook_invalid_id",
  "message": "ID is invalid.",
  "data": {
    "status": 400
  }
}
```

Are you able to reproduce this problem on a clean WC install? Could you please share your system status report as requested in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=)?

**Comment by smurf9852** [comment] 2019-04-25 14:29
@rodrigoprimo thank you for your reply!
I did the same as you, creating a clean WP on subdomain, and now indeed it was deleted as it should.
Does this mean it is a plugin problem? 
Let me know what i can do.
Here is my System Status Report

### WordPress Environment ###

WordPress address (URL): https://usb-c-adapters.nl
Site address (URL): https://usb-c-adapters.nl
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.4
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
Totale databasegrootte: 48.85MB
Database datagrootte: 33.86MB
Database index grootte: 14.99MB
wp_woocommerce_sessions: Data: 0.22MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.25MB + Index: 0.09MB
wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB
wp_atum_product_data: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 2.52MB + Index: 1.17MB
wp_feedmanager_channel: Data: 0.02MB + Index: 0.03MB
wp_feedmanager_country: Data: 0.02MB + Index: 0.03MB
wp_feedmanager_feed_status: Data: 0.02MB + Index: 0.98MB
wp_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB
wp_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB
wp_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB
wp_feedmanager_source: Data: 0.02MB + Index: 0.98MB
wp_icwp_wpsf_audit_trail: Data: 0.06MB + Index: 0.00MB
wp_icwp_wpsf_ip_lists: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_reporting: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_sessions: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_spambot_comments_filter: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_statistics: Data: 0.02MB + Index: 0.00MB
wp_imagify_files: Data: 0.11MB + Index: 0.13MB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_loginizer_logs: Data: 0.00MB + Index: 0.01MB
wp_mdf_query_cache: Data: 0.02MB + Index: 0.02MB
wp_mdf_stat_buffer: Data: 0.02MB + Index: 0.00MB
wp_mdf_stat_tmp: Data: 0.02MB + Index: 0.00MB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.52MB + Index: 0.13MB
wp_podsrel: Data: 0.02MB + Index: 0.06MB
wp_postmeta: Data: 12.52MB + Index: 5.03MB
wp_posts: Data: 2.52MB + Index: 1.19MB
wp_redirection_404: Data: 1.42MB + Index: 0.47MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB
wp_redirection_logs: Data: 0.08MB + Index: 0.08MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.08MB + Index: 0.00MB
wp_revslider_slides: Data: 0.41MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.03MB
wp_snp_log: Data: 0.02MB + Index: 0.00MB
wp_snp_stats: Data: 0.02MB + Index: 0.05MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.33MB + Index: 0.25MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wp_wcpdf_invoice_number: Data: 0.06MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_webwinkelkeur_invite_error: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woof_query_cache: Data: 0.02MB + Index: 0.00MB
wp_woof_stat_buffer: Data: 0.02MB + Index: 0.00MB
wp_woof_stat_tmp: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 7.52MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.19MB + Index: 0.06MB
wp_yoast_seo_meta: Data: 0.14MB + Index: 0.00MB

### Post Type Counts ###

attachment: 776
customize_changeset: 10
header_builder: 3
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 72
nelioab_local_exp: 1
oembed_cache: 4
page: 51
popup: 3
popup_theme: 6
post: 22
product: 52
product_variation: 22
revision: 47
scheduled-action: 372
shop_order: 1078
shop_order_refund: 51
snp_popups: 1
tm_global_cp: 1
vc_settings_preset: 2
wcct_countdown: 3
wp-rest-api-log: 53
wpb_gutenberg_param: 1
_pods_pod: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

WooCommerce (nl): door Pronamic – 1.1.7 – Niet getest met de actieve versie van WooCommerce
Akismet Anti-Spam: door Automattic – 4.1.1
ATUM Inventory Management for WooCommerce: door Stock Management Labs™ – 1.5.7.4 – Niet getest met de actieve versie van WooCommerce
Autoptimize: door Frank Goossens (futtta) – 2.5.0
Beeketing For WooCommerce: door Beeketing – 3.8.8 – Niet getest met de actieve versie van WooCommerce
Klassieke editor: door WordPress-bijdragers – 1.4
Duplicate Post: door Enrico Battocchi – 3.2.2
Google Tag Manager for Wordpress: door Thomas Geiger – 1.9.2 – Niet getest met de actieve versie van WooCommerce
Enable Media Replace: door ShortPixel – 3.2.9
Imagify: door WP Media – 1.8.4.1
WPBakery Page Builder: door Michael M - WPBakery.com – 5.7
Loginizer: door Raj Kothari – 1.4.1
Mollie Payments for WooCommerce: door Mollie – 5.1.6
Nitro Toolkit: door WooRockets Team  – 1.1.8
Nofollow for External Link: door Alex Jose (Ginger Codes) – 2.0
Popup Maker: door WP Popup Maker – 1.8.5
Redirection: door John Godley – 4.2.3
Redis Object Cache: door Till Krüss – 1.4.1
Simple Sitemap: door David Gwyer – 2.9
WooCommerce NL Postcode Checker: door Ewout Fernhout – 2.0.17 – Niet getest met de actieve versie van WooCommerce
WebwinkelKeur: door Albert Peschar – 1.6.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce MyParcel: door Richard Perdaan – 3.1.4 – Niet getest met de actieve versie van WooCommerce
WooCommerce Print Bestellijst: door Ewout Fernhout – 1.5.9 – Niet getest met de actieve versie van WooCommerce
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.2.12
WooCommerce Product Bundles: door SomewhereWarm – 5.10.0
WOOF - WooCommerce Products Filter: door realmag777 – 2.2.2.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce TM Extra Product Options: door themeComplete – 4.6.9.4 – Niet getest met de actieve versie van WooCommerce
WooCommerce: door Automattic – 3.6.2
Yoast SEO: door Team Yoast – 11.0 – Niet getest met de actieve versie van WooCommerce
WP Mail SMTP: door WPForms – 1.4.2
WP Product Feed Manager: door Michel Jongbloed – 1.13.1 – Niet getest met de actieve versie van WooCommerce
REST API Log: door Pete Nelson – 1.6.7
WP Rocket: door WP Media – 3.3.1.1
WR Live Search: door WooRockets  – 1.0.9 – Niet getest met de actieve versie van WooCommerce

### Inactive Plugins (6) ###

JSON Basic Authentication: door WordPress API Team – 0.1
Product Feed PRO for WooCommerce: door AdTribes.io – 5.4.2
Slider Revolution: door ThemePunch – 5.4.8.3
WooCommerce Buy One Get One Free: door Oscar Gare – 1.1.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce DYMO Print: door WP Fortune – 5.0.6 – Niet getest met de actieve versie van WooCommerce
WP Overnight Sidekick: door Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.0.4


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Redis Object Cache Drop-In

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #10 - /shop/
Winkelmand: #11 - /cart/
Afrekenen: #12 - /checkout/
Mijn account: #13 - /my-account/
Algemene voorwaarden: #750 - /algemene-voorwaarden/

### Theme ###

Name: WR Nitro Child
Version: 1.0.0
Author URL: http://www.woorockets.com/
Child Theme: ✔
Parent Theme Name: WR Nitro
Parent Theme Version: 1.6.8
Parent Theme Author URL: http://www.woorockets.com/
WooCommerce Support: ✔

### Templates ###

Overrides: wr-nitro/woocommerce/archive-product.php
/home/deb116105/domains/usb-c-adapters.nl/public_html/wp-content/plugins/woocommerce-tm-extra-product-options/templates/cart/cart-item-data.php
wr-nitro/woocommerce/cart/cart-shipping.php versie 3.5.0 is verouderd. De hoofdversie is 3.6.0
wr-nitro/woocommerce/cart/cart-totals.php
wr-nitro/woocommerce/cart/cart.php
wr-nitro/woocommerce/cart/cross-sells.php
wr-nitro/woocommerce/cart/mini-cart.php
wr-nitro/woocommerce/cart/shipping-calculator.php
wr-nitro/woocommerce/checkout/form-checkout.php
wr-nitro/woocommerce/checkout/review-order.php
wr-nitro/woocommerce/checkout/thankyou.php
wr-nitro/woocommerce/content-product.php versie 3.4.0 is verouderd. De hoofdversie is 3.6.0
wr-nitro/woocommerce/content-product_cat.php
wr-nitro/woocommerce/content-single-product.php versie 3.4.0 is verouderd. De hoofdversie is 3.6.0
wr-nitro/woocommerce/content-widget-product.php versie 3.5.2 is verouderd. De hoofdversie is 3.5.5
wr-nitro/woocommerce/global/breadcrumb.php
wr-nitro/woocommerce/global/quantity-input.php versie 3.4.0 is verouderd. De hoofdversie is 3.6.0
wr-nitro/woocommerce/global/wrapper-end.php
wr-nitro/woocommerce/global/wrapper-start.php
wr-nitro/woocommerce/loop/add-to-cart.php
wr-nitro/woocommerce/loop/loop-end.php
wr-nitro/woocommerce/loop/loop-start.php
wr-nitro/woocommerce/loop/orderby.php versie 3.3.0 is verouderd. De hoofdversie is 3.6.0
wr-nitro/woocommerce/loop/pagination.php
wr-nitro/woocommerce/loop/sale-flash.php
wr-nitro/woocommerce/myaccount/dashboard.php
wr-nitro/woocommerce/myaccount/downloads.php
wr-nitro/woocommerce/myaccount/form-edit-account.php
wr-nitro/woocommerce/myaccount/form-login.php versie 3.5.0 is verouderd. De hoofdversie is 3.6.0
wr-nitro/woocommerce/myaccount/my-account.php
wr-nitro/woocommerce/myaccount/my-address.php
wr-nitro/woocommerce/myaccount/navigation.php
wr-nitro/woocommerce/myaccount/orders.php
wr-nitro/woocommerce/single-product/add-to-cart/external.php
wr-nitro/woocommerce/single-product/add-to-cart/grouped.php
wr-nitro/woocommerce/single-product/add-to-cart/simple.php
wr-nitro/woocommerce/single-product/add-to-cart/variable.php versie 3.4.1 is verouderd. De hoofdversie is 3.5.5
wr-nitro/woocommerce/single-product/meta.php
wr-nitro/woocommerce/single-product/price.php
wr-nitro/woocommerce/single-product/product-image.php
wr-nitro/woocommerce/single-product/rating.php versie 3.1.0 is verouderd. De hoofdversie is 3.6.0
wr-nitro/woocommerce/single-product/related.php
wr-nitro/woocommerce/single-product/sale-flash.php
wr-nitro/woocommerce/single-product/tabs/tabs.php
wr-nitro/woocommerce/single-product/title.php
wr-nitro/woocommerce/single-product/up-sells.php
wr-nitro/woocommerce/single-product-reviews.php versie 3.5.0 is verouderd. De hoofdversie is 3.6.0

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Product Bundles ###

Database Version: 5.10.0
Template Overrides: –

### Action Scheduler ###

Complete: 371
Oldest: 2019-03-25 15:33:14 +0000
Newest: 2019-04-25 14:24:13 +0000

Pending: 1
Oldest: 2019-05-01 13:33:14 +0000
Newest: 2019-05-01 13:33:14 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

**Comment by smurf9852** [comment] 2019-04-25 14:51
By deactivating and testing plugins one by one, i found the plugin Redis Object Caching to be the cause (or one of the causes, if i find more later). Without it, the deletion does work, with it, it doesnt.
Do you have an idea why this is, and is there a way for me to fix this? Because Redis makes everything so nice and fast :)

**Comment by claudiosanches** [comment] 2019-04-25 15:34
@smurf9852 for what you are reporting, sounds like the object is deleted, but still in cache on Redis, probably you need to purge this cache.
I'll close this issue, since it ins't an issue on WooCommerce.
Thanks for let you knows about it.

**Closed by claudiosanches** 2019-04-25 15:34 UTC
Labels: status: needs feedback
