### ISSUE TITLE
Coupon with both Products and Product Categories restriction doesn't work

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#24288] opened 2019-08-01 15:05 UTC
**Describe the bug**
A coupon with both Products and Product Categories restrictions gives the following error in cart: `Sorry, this coupon is not applicable to selected products.`

**To Reproduce**
1. Create the following coupon:

![https://cld.wthms.co/ABIW7V](https://cld.wthms.co/ABIW7V+) 
Full Size: https://cld.wthms.co/ABIW7V

(Discount type or Coupon expiry date doesn't matter)

![https://cld.wthms.co/xItanx](https://cld.wthms.co/xItanx+) 
Full Size: https://cld.wthms.co/xItanx

Make sure to include both Products and Product Categories restriction.

2. Add a product which should work with the coupon to cart and add this coupon:

![https://cld.wthms.co/2QpQz8](https://cld.wthms.co/2QpQz8+) 
Full Size: https://cld.wthms.co/2QpQz8

As soon as you keep only **one** of the restrictions - either Products or Product Categories, it will work:

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
[x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
[x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
[x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://iamwoocakes.mystagingwebsite.com
Site address (URL): https://iamwoocakes.mystagingwebsite.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.20
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.65.3
OpenSSL/1.1.0k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.31-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
Total Database Size: 13.52MB
Database Data Size: 8.85MB
Database Index Size: 4.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.17MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.20MB + Index: 0.22MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.05MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.14MB + Index: 0.09MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.16MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.06MB + Index: 0.06MB
wp_postmeta: Data: 1.50MB + Index: 1.95MB
wp_posts: Data: 0.41MB + Index: 0.27MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_exported_csv_items: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_exported_xml_items: Data: 0.13MB + Index: 0.02MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB
wp_xyz_ips_short_code: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 16
bookable_person: 3
bookable_resource: 14
customize_changeset: 1
event_ticket: 1
follow_up_email: 15
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 4
page: 27
post: 3
product: 95
product_variation: 255
revision: 72
scheduled-action: 290
shop_coupon: 10
shop_order: 154
shop_order_refund: 15
shop_subscription: 5
tribe_events: 2
tribe_wooticket: 7
warranty_request: 1
wbcr-snippets: 7
wc_booking: 23
wc_membership_plan: 1
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

WooCommerce: by Automattic – 3.6.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #512 - /wooslider-page/

### Theme ###

Name: Storefront
Version: 2.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 236
Oldest: 2019-07-01 15:36:28 +0000
Newest: 2019-08-01 15:01:52 +0000

Pending: 6
Oldest: 2019-08-01 16:01:52 +0000
Newest: 2019-08-24 08:27:24 +0000

Canceled: 45
Oldest: 2019-07-04 13:29:41 +0000
Newest: 2019-07-19 12:41:56 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 3
Oldest: 2019-06-15 16:33:17 +0000
Newest: 2019-07-01 15:54:54 +0000

`
```
</details>

**Comment by malviyaritesh** [comment] 2019-08-02 06:31
The above coupon restriction error is only produced if in restriction setting, the product doesn't fall into any of the restricted product categories.

For e.g. if your coupon is restricted to both clothing product (set in restriction Product dropdown) and cloth product category (set in restriction Product categories dropdown) with some other category. Now, if you add that clothing product (specifically product which was added in restriction dropdown), then the coupon will be applied successfully as both product and product categories are available in cart.

However, if you try to add coupon with a product which is not from any of restricted product category then it will fail. Similarly while if product in cart falls into one of the restricted product categories but isn't one from restricted product ids then the coupon will also fail to add.

In short for coupon to be applied while both product ids and product categories are used for restriction, then the logic is as following, as I noticed from behavior (not seen source):
```
(product1 OR product2 OR product3) AND (category1 OR category2 OR category3)
```
And I think it is working as [documented](https://docs.woocommerce.com/document/coupon-management/#section-3):

> - Products – Products that the coupon will be applied to, or that need to be in the cart in order for the fixed or percentage discount to be applied.
> - Product categories – Product categories that the coupon will be applied to, or that need to be in the cart in order for the fixed or percentage discount to be applied.

So above **AND** logic for coupon restriction on product and product categories isn't bug. But we can modify/enhance (if desired) it to follow **OR** logic. The feedback from members should help for final decision on this.

**Comment by claudiosanches** [comment] 2019-08-02 17:11
> As soon as you keep only one of the restrictions - either Products or Product Categories, it will work:

@treibalen this product belong to one of both of those categories?

**Comment by treibalen** [comment] 2019-08-20 16:46
Hi @claudiosanches,

No, my product doesn't belong to the restricted categories.

> However, if you try to add coupon with a product which is not from any of restricted product category then it will fail. Similarly while if product in cart falls into one of the restricted product categories but isn't one from restricted product ids then the coupon will also fail to add.

@malviyaritesh, I'm struggling with figuring out what would be a use case for that. Why a product in the product restriction should necessarily belong to the restricted category? If I want to list products there, I'd just list products only, not their categories too.

Example from a chat with customer I had: in their store they wanted a coupon to be applied for two specific categories and also one more product which doesn't belong to these categories. The customer had to list all products of both categories manually in the restricted product list.

> (product1 OR product2 OR product3) AND (category1 OR category2 OR category3)

I might be missing something but I think having **OR** logic gives more flexibility to the customer and I was sure that this is how it works, but then I stumbled into this :)

**Comment by cesarcgfg** [comment] 2019-12-17 03:47
> I might be missing something but I think having OR logic gives more flexibility to the customer and I was sure that this is how it works, but then I stumbled into this :)

I agree. 
I have the same problem, one of my clients wanted a coupon to be applied for one category and two specific products that does not belong to these category.

Hopefully this issue becomes and enhancement, please :)

Meanwhile, is there any way to modify this behaviour via functions.php?

Regards

**Comment by juliaamosova** [comment] 2020-01-17 18:02
Hi @treibalen,

Thanks for raising this issue! I can reproduce the same on my end:

- I created the following coupon:

![201](https://user-images.githubusercontent.com/19143190/72634010-9c8f6980-3951-11ea-8142-1cb5ef24e606.jpg)

- With the following Usage Restrictions:

![202](https://user-images.githubusercontent.com/19143190/72634041-ac0eb280-3951-11ea-9de0-c7fdea2574c7.jpg)

- My `Product 63` that needs to be in the cart in order for the coupon to work doesn't belong to the 2 categories (`Albums` & `Clothe`) specified to be in the cart as well in order for the coupon to work:

![203](https://user-images.githubusercontent.com/19143190/72634297-2e977200-3952-11ea-9007-6731d192ce8f.jpg)

- Added product to the cart and applied coupon. Got an error message saying that `Sorry, this coupon is not applicable to selected products.`:

![305](https://user-images.githubusercontent.com/19143190/72634420-7ae2b200-3952-11ea-90f6-5bc5635c227a.jpg)

- Can successfully apply a coupon if I remove product categories from usage restrictions in coupon's settings:

![206](https://user-images.githubusercontent.com/19143190/72634636-d876fe80-3952-11ea-8171-574204e5a958.jpg)

![07](https://user-images.githubusercontent.com/19143190/72634648-de6cdf80-3952-11ea-8ea4-a43b280cec89.jpg)

I see that we check for the validation of the coupon in regards to products and products categories in 2 separate functions:

- Ensure coupon is valid for products in the list is valid or throw exception:

https://github.com/woocommerce/woocommerce/blob/85a077b939b44500fc01b68d34e711117545f586/includes/class-wc-discounts.php#L704

- Ensure coupon is valid for product categories in the list is valid or throw exception:

https://github.com/woocommerce/woocommerce/blob/85a077b939b44500fc01b68d34e711117545f586/includes/class-wc-discounts.php#L731

But we don't check if either or one of these valid, the coupon is valid. Perhaps we can add the function to check that but I am not sure what effect it may have on plugins that potentially use the coupon's usage restrictions functionality as-is.

**Comment by juliaamosova** [comment] 2020-01-17 20:05
We are going to leave this issue open for now with label `question` which means as a team, we are going to evaluate it at some point over time. The concerns are related to the 3rd party plugins that may rely on the existing functionality as-is. 

In the meantime, the workaround could be creating 2 separate coupons: 

- one coupon to restrict products;
- another coupon to restrict categories.

**Comment by daschenbrener** [comment] 2020-04-01 23:05
Im seeing this issue on my site right now as well.
i cannot seem to get any restriction to work at all.

**Comment by AashikP** [comment] 2021-02-03 03:44
Another report in 3700380-zen

**Comment by claudiosanches** [comment] 2021-03-03 20:34
Those fields aren't designed to work "check product IDs **OR** categories", those works like "check product IDs **AND** categories".
For this issue probably will be better to remove the product from that coupon and create some new category and include that to the coupon as well, so you don't get issues like that.
Sounds like we should better document it.

**Comment by rrennick** [comment] 2023-11-14 19:45
I'll close this as a duplicate of #31360.

**Closed by rrennick** 2023-11-14 19:45 UTC
Labels: focus: coupon [team:Proton], needs: documentation, plugin: woocommerce
