### ISSUE TITLE
Credit card expiration date "/" missing and cannot be added for mobile iphones

### ISSUE THREAD

**Issue by gzpcme** [woocommerce/woocommerce#27204] opened 2020-08-03 02:03 UTC
Woocommerce 4.2.2
Checkout page
Credit card Expiration Date field

Phone keyboard set to "tel" in code with no way to add "/" in expiration date field.
"/" is not automatically added after first 2 digits are typed.

"Expiration date invalid" error prevents charge from being sent to gateway.
Nobody can check out using iphones since they cannot add the "/" character.

Line 72 of woocommerce/includes/gateways/class-wc-payment-gateway-cc.php has type="tel" for expiration date field, and it cannot be removed

**Comment by juliaamosova** [comment] 2020-08-03 14:16
Hi @gzpcme,

Thanks for raising the issue. Can you please provide the details on the payment gateway you use? I've tried with Stripe on my Android phone so far and everything is working as expected. 

Additionally, can you please confirm that you have done theme and plugins conflict? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by gzpcme** [comment] 2020-08-03 14:47
I think it is an iphone issue.

The “tel” keyboard does not have a “/” key option

The gateway is Elavon Converge.

 

Thanks, 
GZ

**Comment by gzpcme** [comment] 2020-08-03 15:04
Shouldn't the keyboard be "numeric" instead of "tel" for the expiration date?  That keyboard has a "/".

**Comment by juliaamosova** [comment] 2020-08-03 17:06
Hi @gzpcme,

Thanks for your follow-up. I further tested on my iPhone6S and confirm that the `/` in the credit card expiration field comes up automatically as soon as the month is entered. I made a screen recording to document that:

https://cloudup.com/c5VERJJuUEv

Note that I tested with Stripe but the behavior should be the same for any payment gateway. 

I think the issue is either with your theme or the payment gateway itself. As I previously wrote, please test your site for theme and plugins conflict to find out what is causing the issue exactly.

**Comment by juliaamosova** [comment] 2020-08-10 14:00
Hi @gzpcme,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-08-10 14:00 UTC
Labels: status: needs feedback
