### ISSUE TITLE
WC Reports different data on screen and in CSV file

### ISSUE THREAD

**Issue by grey-rsi** [woocommerce/woocommerce#19488] opened 2018-03-22 10:42 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate

## Steps to reproduce the issue

1. go to WC->Reports->Orders
2. export to CSV file
3. you will get different numbers 

Also another issue that Gross sales - shipping and taxes not equal to Net Sales

## Expected/actual behavior

I was expecting to see the same numbers in CSV file + correct value of Gross and Net sales

## Isolating the problem

- [x] I can reproduce this bug consistently using the steps above

![image](https://user-images.githubusercontent.com/8124964/37765786-dbc1aabe-2dcd-11e8-9a03-7f20ecd15f62.png)

![image](https://user-images.githubusercontent.com/8124964/37766043-794b5faa-2dce-11e8-9693-6d37c6e23401.png)

**Comment by mikejolley** [comment] 2018-03-22 17:10
This can be caused by data discrepancies for things like refunds.

- The totals on the left are calculated from the sum of `order total`. This is adjusted for all refunds.
- The totals in the CSV where it lists item counts are calculated from individual orders - line item refunds.

If one/some of the orders have been refunded at order level but not a line level, this can make the report in the chart mismatch the grand total. The grand total will be your truthful value.

Unfortunately there is no way to make these match if refunds have not been made on line items (at least not without hurting performance on already slow reports). If you narrow your data set you may be able to identify which order is affecting the report and correct it. And basically just ensure line items get refunded, rather than refunding amounts at order level.

I hope this makes sense.

The good news is a consistent reports API is on our roadmap this year so we hope to mitigate at least the appearance of this issue. This will be part of https://github.com/woocommerce/woocommerce/issues/13094 and the v3 Rest API.

Thanks

**Closed by mikejolley** 2018-03-22 17:10 UTC

**Comment by grey-rsi** [comment] 2018-03-23 06:09
@mikejolley Thanks for the feedback!
