### ISSUE TITLE
Edit Account Won't Work with Email as Display Name and no other fields

### ISSUE THREAD

**Issue by curtismchale** [woocommerce/woocommerce#26389] opened 2020-05-05 21:22 UTC
If a user is added (say by an admin) without a first name or last name then their email is set as the default display name. This means that they can't edit their own data on their My Account->Account Details page because their display name is set to their email address. They can't even add their first/last name so that they could change their display name in this scenario without bugging the site admins about it.

**To Reproduce**
1. Add WP user with first/last name and have email set as display name
2. Go to My Account->Account Details and try to edit any fields
3. Get error and no fields saved so you can't even change your display name

**Screenshots**
![woocommerce-no-account-edit](https://user-images.githubusercontent.com/74561/81117007-3bc57600-8edb-11ea-9b31-044f7a444c56.gif)

**Expected behavior**
If name fields present bypass the check for is_email in `class-wc-form-handler.php` on line 244 to save the form and then set the display name for the user to something that's deemed safe.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://calosha.prov.sfndesign.ca
Site address (URL): http://calosha.prov.sfndesign.ca
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.1.0
Log Directory Writable: ✔
WP Version: ❌ 5.4 - There is a newer version of WordPress available (5.4.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix) OpenSSL/1.1.1
PHP Version: 7.3.17
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.30-0ubuntu0.18.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 265.00MB
Database Data Size: 192.43MB
Database Index Size: 72.57MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_01258b330e_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_01258b330e_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_01258b330e_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_01258b330e_options: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
wp_01258b330e_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_01258b330e_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_01258b330e_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_01258b330e_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_01258b330e_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_01258b330e_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_01258b330e_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_01258b330e_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.42MB + Index: 0.30MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.16MB + Index: 0.44MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.42MB + Index: 0.13MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.42MB + Index: 0.70MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 3.02MB + Index: 0.11MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.42MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 12.52MB + Index: 13.03MB + Engine InnoDB
wp_posts: Data: 10.52MB + Index: 1.02MB + Engine InnoDB
wp_rcp_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcp_payments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_rcp_payment_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcp_subscription_level_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_relevanssi: Data: 21.58MB + Index: 43.17MB + Engine InnoDB
wp_relevanssi_log: Data: 0.42MB + Index: 0.17MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_restrict_content_pro: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_view: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead: Data: 0.22MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.20MB + Index: 0.48MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_term_taxonomy: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_ualp_user_activity: Data: 122.66MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 4.52MB + Index: 6.03MB + Engine InnoDB
wp_users: Data: 0.31MB + Index: 0.28MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xyz_ihs_short_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.18MB + Index: 0.16MB + Engine MyISAM

### Post Type Counts ###

acf: 1
acf-field: 236
acf-field-group: 9
article: 666
attachment: 1461
aw_workflow: 7
case: 311
esv: 114
flash-report: 20
leadpages_post: 3
nav_menu_item: 30
news-digest: 23
page: 43
post: 2
product: 14
regulatory: 1
revision: 11
shop_coupon: 10
shop_order: 43
shop_subscription: 128
stc: 1
tablepress_table: 52
top50: 1
visualizer: 6
wc_membership_plan: 1
wc_memberships_team: 118
wc_user_membership: 1619

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (57) ###

Gravity Forms: by rocketgenius – 2.4.17
No Injury Days: by Providence Publications – 1.0
Share Buttons by AddThis: by The AddThis Team – 6.2.6
Advanced Custom Fields PRO: by Elliot Condon – 5.8.9
All-in-One WP Migration: by ServMask – 7.20
BE Subpages Widget: by Bill Erickson – 1.7
iThemes Security: by iThemes – 7.7.1
Classic Editor: by WordPress Contributors – 1.5
Custom Post Type UI: by WebDevStudios – 1.7.4
Custom Post Type Widgets: by thingsym – 1.2.1
Gravity Forms Webhooks Add-On: by rocketgenius – 1.2
If Menu - Visibility control for menu items: by Layered – 0.16.1
Image Widget: by Modern Tribe
Inc. – 4.4.7

Insert HTML Snippet: by xyzscripts.com – 1.3.1
Leadpages Connector: by Leadpages – 2.3.9
Linkedin Badge by Pixelpillow: by Milan van Bruggen – 1.0
Maintenance Mode: by Michael Wöhrer – 5.4
People Lists: by Gagan Sandhu 
Enej Bajgoric 
CTLT DEV
UBC – 1.3.10

prettyPhoto Media: by binaryhideout – 1.4
Prov Pubs - Add To Cart Redirect: by SFNdesign
Curtis McHale – 1.0

Prov Pubs - Custom Search: by SFNdesign
Curtis McHale – 1.0

Prov Pubs - Admin UI customizations: by SFNdesign
Curtis McHale – 1.0

Prov - Product Landing Page: by SFNdesign
Curtis McHale – 1.0

Prov Pubs - Custom Team Columns: by SFNdesign
Curtis McHale – 1.0

Prov Pubs - Send to Lyris: by SFNdesign
Curtis McHale – 1.0

Prov - User Fields: by SFNdesign
Curtis McHale – 1.0

Prov Pubs - User Logging: by SFNdesign
Curtis McHale – 1.0

Recent Posts Widget Extended: by Satrya – 0.9.9.7
Relevanssi: by Mikko Saari – 4.7.2.1
Remove Dashboard Access: by Drew Jaynes (DrewAPicture) – 1.1.3
Restricted Site Access: by Jake Goldman
10up
Oomph – 7.2.0

SFN Dark Mode: by SFNdesign
Curtis McHale – 1.0

Shortcodes Ultimate: by Vladimir Anokhin – 5.8.1
Spam Honey Pot: by Matthew Turland – 1.0.0
TablePress: by Tobias Bäthge – 1.11
TinyMCE Advanced: by Andrew Ozz – 5.4.0
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.6.1

User Activity Log: by Solwin Infotech – 1.4.3
User Role Editor: by Vladimir Garagulya – 4.53.1
Visualizer: Tables and Charts for WordPress: by Themeisle – 3.4.2
WooCommerce Admin: by WooCommerce – 1.1.0
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.8 – Not tested with the active version of WooCommerce
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.16 – Not tested with the active version of WooCommerce
WooCommerce Hide Zero Orders: by Shop Plugins – 1.0.0 – Not tested with the active version of WooCommerce
Teams for WooCommerce Memberships: by SkyVerge – 1.2.3 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.17.0 – Not tested with the active version of WooCommerce
WooCommerce Subscription Downloads: by WooCommerce – 1.1.22 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by WooCommerce – 3.0.1 – Not tested with the active version of WooCommerce
Prov Pubs - WC Teams Metaboxes: by SFNdesign
Curtis McHale – 1.0

WooCommerce: by Automattic – 4.0.1 – 4.1.0 is available
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO Premium: by Team Yoast – 14.0.1
WP Media Category Management: by DeBAAT  – 1.9.4
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.15
WP Migrate DB Pro: by Delicious Brains – 1.9.10
WP-SMTP-MAIL-CONFIG: by TakeCare Solutions & Services – 0.1.0
Yoast SEO: News: by Team Yoast – 12.4.1

### Inactive Plugins (9) ###

Advanced Custom Fields: by Elliot Condon – 5.8.9
AutomateWoo: by WooCommerce – 4.8.2 – Not tested with the active version of WooCommerce
Blog Time: by Scott Reilly – 3.6.1
Query Monitor: by John Blackbourn – 3.5.2
WooCommerce Email Test: by RaiserWeb – 2.3 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.20
WooCommerce PDF Invoices: by Bas Elbers – 3.0.11 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.23.0
WooCommerce Stripe Gateway: by WooCommerce – 4.3.3

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #3213 - /shop/
Cart: #3214 - /cart/
Checkout: #3215 - /checkout/
My account: #3216 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: CAL-OSHA Reporter
Version: 1.7.2
Author URL: http://www.darcydesign.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: Articles: 7 itemsPages: 2 items
Excluded from discounts:: –
Membership plans:: 1
premium-subscriber:: Members: 1619Access method: Product(s) purchaseAccess length: Unlimited Subscription: No No access-granting products are purchasable❌ The plan contains a rule to restrict all Articles to non-members❌ The plan contains a rule to restrict all Posts to non-members❌ The plan contains a rule to restrict all Cases to non-members

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: https://www.cal-osha.com
Subscription Statuses: wc-active: 123
wc-on-hold: 5

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Indiana

### Payment Gateway Support ###

Check payments: products
PayPal Pro: products
refunds


### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 0
Next export: Not scheduled

### Action Scheduler ###

Canceled: 230
Oldest: 2020-04-06 23:00:00 -0700
Newest: 2021-06-21 00:00:00 -0700

Complete: 373
Oldest: 2020-04-04 15:08:50 -0700
Newest: 2020-05-05 14:06:09 -0700

Pending: 1,986
Oldest: 2020-05-05 23:05:42 -0700
Newest: 2022-12-04 00:45:57 -0800

`
```
</details>

**Comment by juliaamosova** [comment] 2020-05-06 20:47
Hi @curtismchale,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

Here is how I created a `Customer` type of user as an admin:

![Screen Shot 2020-05-06 at 4 44 14 PM](https://user-images.githubusercontent.com/19143190/81226503-f2e3ef00-8fb8-11ea-8c98-ba76860f951c.png)

Here I am logged in as that customer and adding First and Last names successfully:

![](http://g.recordit.co/HQQM0ZqQMd.gif)

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-05-13 14:47
Hi @curtismchale,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-05-13 14:47 UTC
Labels: can't reproduce, status: needs feedback
