### ISSUE TITLE
Product price disappears after sorting

### ISSUE THREAD

**Issue by Niels1307** [woocommerce/woocommerce#27536] opened 2020-08-31 10:11 UTC
I use the divi theme in combination with the Woocommerce plugin. I have an issue with the sorting functionality on my shop pages. When the shop page is opened for the first time, everything is displayed correctly. When I sort product by newest, some products seem to loose their variations. E.g., the price disappears on the shop page and also the price is not visible in the products database. 

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After sorting the product. some products do not show the prices and cannot be ordered.

**Expected behavior**
Sorting should work without this issue.

**Actual behavior**
After re-ordering productes, the price disappears on the shop page. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to https://pakhuis1920.nl/product-categorie/heren/
2. Click on 'Sorteer op populariteit' and then 'Sorteren op nieuwste'
3. Scroll down to below
4. See some products with no price**
5. Click on that product and it seems that the variations disappeared
** It might be needed to repeat step 2, since the issue is not always consistent

**Screenshots**
![image](https://user-images.githubusercontent.com/70513327/91709215-b8631b00-eb82-11ea-9f5e-8c8b5316f960.png)

After sorting products a couple of times:

![image](https://user-images.githubusercontent.com/70513327/91709259-c87afa80-eb82-11ea-9ca9-531963b209db.png)

The prices are also disappeared in the product database:
![image](https://user-images.githubusercontent.com/70513327/91709316-dd578e00-eb82-11ea-83e7-9b034b0873ef.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Niels1307** [comment] 2020-09-03 09:29
Hello? Can nobody help me?

**Comment by tammullen** [comment] 2020-10-22 14:20
Hi @Niels1307, sorry for the delay in replying.

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by juliaamosova** [comment] 2020-10-29 18:28
Hi @Niels1307,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-10-29 18:28 UTC
Labels: status: needs feedback
