### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Automattic\WooCommerce\Container' not found

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#27608] opened 2020-09-07 18:28 UTC
This is a pretty intricate issue, but feels like something that needs to be addressed in some way.

When the WC core plugin is activated via the traditional plugins UI, this error does not occur. But if the plugin is loaded a different way, such as [`wpcom_vip_load_plugin()`](https://github.com/Automattic/vip-go-mu-plugins/blob/fc3f19d2301bdd20f9d3af3ccba3ae66c8cd9bde/vip-helpers/vip-utils.php#L1001-L1013), then you end up with this fatal.

So if WooCommerce is not in the active_plugins option, this WC-specific autoloader is not loaded up in Jetpack because it isn't aware WC exists. See `woocommerce/vendor/jetpack-autoloader/autoload_functions.php` line 98 and  [find_latest_autoloader()](https://github.com/Automattic/jetpack/blob/606fb098154b0a1853daa73e56d51e197b8d22c0/packages/autoloader/src/class-autoloader-handler.php#L58) / [get_all_active_plugins_paths()](https://github.com/Automattic/jetpack/blob/606fb098154b0a1853daa73e56d51e197b8d22c0/packages/autoloader/src/class-plugins-handler.php#L14-L27
)

At a minimum, it's pretty unfortunate that WooCommerce will error out this early from a dependency issue related to Jetpack: https://github.com/woocommerce/woocommerce/blob/master/woocommerce.php#L38

**Comment by peterfabian** [comment] 2020-09-09 12:59
cc @ObliviousHarmony @Konamiman

**Comment by ObliviousHarmony** [comment] 2020-09-09 23:38
After debugging this with @WPprodigy it seems the problem is VIP's population of `active_plugins`. When Jetpack loads as an mu-plugin it doesn't know that WooCommerce exists, but when WooCommerce loads as a client plugin, it sees itself in the active plugin list and doesn't reset the autoloader.

@kbrown9 What do you think about this? While we might be able to find a VIP filter I wonder if we should consider caching the active plugin list and busting the autoloader if it changes?

**Comment by kbrown9** [comment] 2020-09-10 03:16
> After debugging this with @WPprodigy it seems the problem is VIP's population of active_plugins. When Jetpack loads as an mu-plugin it doesn't know that WooCommerce exists, but when WooCommerce loads as a client plugin, it sees itself in the active plugin list and doesn't reset the autoloader.

If I understand correctly, VIP changes the active_plugins list after the mu plugins have been loaded. Is that correct?

@kbrown9 What do you think about this? While we might be able to find a VIP filter I wonder if we should consider caching the active plugin list and busting the autoloader if it changes?

Caching the active plugin list and busting the autoloader if it changes sounds like a reasonable approach to me.

**Comment by ObliviousHarmony** [comment] 2020-09-10 15:33
> If I understand correctly, VIP changes the active_plugins list after the mu plugins have been loaded. Is that correct?

Yep!

> Caching the active plugin list and busting the autoloader if it changes sounds like a reasonable approach to me.

Alright, I'll work on a PR for that this week!

**Comment by n3f** [comment] 2020-09-25 18:03
We're seeing this issue on WPCOM as well.  I haven't tested the fix that @ObliviousHarmony merged yet, but I was a little confused looking at the code.  From what I understand the jetpack autoloader doesn't load the classes it tracks until [the `plugins_loaded` action](https://github.com/Automattic/jetpack-autoloader).  However, the woocommerce.php file is clearly calling a loaded class (`new Automattic\WooCommerce\Container()`) before that hook has even fired.

Am I missing something?

**Comment by ObliviousHarmony** [comment] 2020-09-25 19:34
> Am I missing something?

Ah, looks like that line in the README.md is out of date! The 2.x release of the Jetpack autoloader does not have this limitation and bootstraps itself with the latest versions of packages by scanning plugin directories.

**Comment by kbrown9** [comment] 2020-09-25 20:24
Sorry about that! The README was updated with the v2.x release, but that line was missed. I’ll open a PR to fix it.

**Closed** 2020-12-08 17:34 UTC
Labels: bug, has pull request, priority: high

**Comment by Ilyagurm** [comment] 2021-02-06 08:15
Hello @ObliviousHarmony and team, the very same is happening to more and more sites (based on latest threads on the wordpress WC forums), as well as ours. This happens every day once or twice, the site goes completely down with a fatal error.

`Fatal error: Uncaught Error: Class ‘Automattic\WooCommerce\Container’ not found in /home/workhomesecrets/public_html/wp-content/plugins/woocommerce/woocommerce.php:38 Stack trace: #0 /home/workhomesecrets/public_html/wp-settings.php(388): include_once() #1 /home/workhomesecrets/public_html/wp-config.php(95): require_once(‘/home/workhomes…’) #2 /home/workhomesecrets/public_html/wp-load.php(37): require_once(‘/home/workhomes…’) #3 /home/workhomesecrets/public_html/wp-blog-header.php(13): require_once(‘/home/workhomes…’) #4 /home/workhomesecrets/public_html/index.php(17): require(‘/home/workhomes…’) #5 {main} thrown in /home/workhomesecrets/public_html/wp-content/plugins/woocommerce/woocommerce.php on line 38`

The site is 'mission critical', I lost thousands of dollars so far due to this, since we're generating 10-50 sales/hour, and I just **can't** have it going down.. I tried a plugin/theme conflict test and disabling of woocommerce plugin + Woocommerce subscriptions was the only thing to solve it (neither of them on their own though). Rolling back also didn't help.. I'd appreciate help here.

System info:

`### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 2100
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/workhomesecrets/public_html
wordpress_size: 2.47 GB (2656591242 bytes)
uploads_path: /home/workhomesecrets/public_html/wp-content/uploads
uploads_size: 277.29 MB (290756070 bytes)
themes_path: /home/workhomesecrets/public_html/wp-content/themes
themes_size: 29.40 MB (30823003 bytes)
plugins_path: /home/workhomesecrets/public_html/wp-content/plugins
plugins_size: 249.06 MB (261161555 bytes)
database_size: 92.78 MB (97292058 bytes)
total_size: 3.11 GB (3336623928 bytes)

### wp-active-theme ###

name: TheGem (thegem)
version: 4.6.0
author: Codex Themes.
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, automatic-feed-links, woocommerce, title-tag, menus, html5, post-formats, featured-content, editor-styles, editor-style, widgets
theme_path: /home/workhomesecrets/public_html/wp-content/themes/thegem
auto_update: Disabled

### wp-themes-inactive (4) ###

Twenty Nineteen: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 2.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.6, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (33) ###

Advanced Order Export For WooCommerce (Pro): version: 3.1.7, author: AlgolPlus, Auto-updates disabled
AudioIgniter: version: 1.6.3, author: The CSSIgniter Team, Auto-updates disabled
Classic Editor: version: 1.6, author: WordPress Contributors, Auto-updates disabled
Code Snippets: version: 2.14.0, author: Code Snippets Pro, Auto-updates disabled
Contact Form 7: version: 5.3.2, author: Takayuki Miyoshi, Auto-updates disabled
Duplicate Page: version: 4.3, author: mndpsingh287, Auto-updates disabled
Forminator: version: 1.14.7, author: WPMU DEV (latest version: 1.14.8), Auto-updates disabled
Header Footer Code Manager: version: 1.1.8, author: 99robots, Auto-updates disabled
Kadence WooCommerce Email Designer: version: 1.4.4, author: Kadence WP, Auto-updates disabled
Nelio A/B Testing: version: 5.0.15, author: Nelio Software, Auto-updates disabled
Really Simple SSL: version: 4.0.7, author: Really Simple Plugins, Auto-updates disabled
Slider Revolution: version: 6.3.6, author: ThemePunch, Auto-updates disabled
TheGem Blocks: version: 1.0.2, author: Codex Themes, Auto-updates disabled
TheGem Demo Import (for WPBackery): version: 4.6.0, author: Codex Themes, Auto-updates disabled
TheGem Theme Elements (for WPBakery): version: 4.6.0, author: Codex Themes, Auto-updates disabled
UpdraftPlus – Backup/Restore: version: 1.16.47, author: UpdraftPlus.Com, DavidAnderson, Auto-updates disabled
UpStroke: WooCommerce One Click Upsells: version: 2.2.9, author: buildwoofunnels, Auto-updates disabled
UpStroke PowerPack: version: 1.6.0, author: WooFunnels, Auto-updates disabled
WooCommerce: version: 4.9.2, author: Automattic, Auto-updates disabled
WooCommerce Authorize.Net Gateway: version: 3.4.0, author: SkyVerge, Auto-updates disabled
WooCommerce Cart Abandonment Recovery: version: 1.2.9, author: CartFlows Inc, Auto-updates disabled
WooCommerce Conversion Tracking: version: 2.0.8, author: weDevs, Auto-updates disabled
WooCommerce Google Analytics Integration: version: 1.5.1, author: WooCommerce, Auto-updates disabled
WooCommerce Shipment Tracking: version: 1.6.26, author: WooCommerce, Auto-updates disabled
WooCommerce Subscriptions: version: 3.0.12, author: WooCommerce, Auto-updates disabled
WooCommerce Zapier: version: 2.0.7, author: OM4, Auto-updates disabled
Wordfence Security: version: 7.4.14, author: Wordfence, Auto-updates disabled
Wordpress Page Widgets: version: 3.9, author: CodeAndMore, Auto-updates disabled
WP-Members: version: 3.3.8, author: Chad Butler, Auto-updates disabled
WPBakery Page Builder: version: 6.5.0, author: Michael M – WPBakery.com, Auto-updates disabled
WP Rollback: version: 1.7.1, author: Impress.org, Auto-updates disabled
WPZAP (Fly your WooCommerce leads to Zapier): version: 2.5, author: Ankur Vishwakarma, Auto-updates disabled
Yoast SEO: version: 15.7, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (1) ###

Duplicator Pro: version: 4.0.1.2, author: Snap Creek, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-1062.4.2.vz7.116.7.kh1 x86_64
httpd_software: LiteSpeed
php_version: 7.2.34 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.74.0 OpenSSL/1.1.1i
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.33
client_version: mysqlnd 5.0.12-dev – 20150407 – $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/workhomesecrets/public_html/wp-content
WP_PLUGIN_DIR: /home/workhomesecrets/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable`

I also am attaching a screenshot of the error woocommerce subscriptions gives, if only Woocommerce is disabled during the error's occurence:
<img width="1780" alt="subscriptions" src="https://user-images.githubusercontent.com/44416140/107112964-b7ce5f00-685b-11eb-89e7-e6fbbb0eea57.png">

Thank you..

**Comment by Ilyagurm** [comment] 2021-02-06 15:11
Following up here that adding [the snippet here](https://github.com/Automattic/jetpack/pull/17174) to the mu plugins folder, didn't help. This is frustrating

**Comment by kbrown9** [comment] 2021-02-08 14:38
Hi @Ilyagurm  - Does your error log contain any PHP warnings or notices that occur before the fatal error? The warnings/notices could help us identify the cause of your site's error.

**Comment by Ilyagurm** [comment] 2021-02-08 14:54
@kbrown9 I had to hire a developer sos during the weekend to handle this Woocommerce error. He solved it, here's a quote of how:

1. I've set a default version for
$jetpack_autoloader_latest_version global
2. I've set a default array with a path for
$jetpack_autoloader_cached_plugin_paths global

declaring these two globals, will prevent jetpack-autoloader to re-initialize a new instance

3. I've used a filter to return a default array for get_transient('jetpack_autoloader_plugin_paths');
without reading it from database.
The error started from this, the option is saved on database as serialized but I believe it failed to unserialize data when the error happened.

I'm attaching a code txt file as well. 

I hope you consider implementing this on the next version, since for the business I'm handling, this costs a significant amount of lost revenue.. Thanks anyway.

[autoloader-testing.txt](https://github.com/woocommerce/woocommerce/files/5944438/autoloader-testing.txt)

**Comment by kbrown9** [comment] 2021-02-08 18:55
Thanks for the details @Ilyagurm!

> The error started from this, the option is saved on database as serialized but I believe it failed to unserialize data when the error happened.

We've merged [this PR](https://github.com/Automattic/jetpack/pull/18682), which will detect this situation before it causes an error. The PR is scheduled to be included in WooCommerce 5.0.
