### ISSUE TITLE
Schedule time is wrong

### ISSUE THREAD

**Issue by firstlove87** [woocommerce/woocommerce#19948] opened 2018-05-03 09:30 UTC
Dear Author,
When i check product which has schedule, there is a problem here. When i choose Timezone settings ( exp: UTC+7 or Ho Chi Minh ), the return time return to a day ago. 
Example:
When i choose date on schedule is: **2018-05-03** and save. When i print it on frontend, it shows **2018/05/02 17:00:00** . I think it must show **2018/05/03 7:00:00**

This is important issue, plz check.

Thanks!

**Comment by mikejolley** [comment] 2018-05-03 10:48
Hi,

Post scheduling is something controlled by WordPress, not WooCommerce. The date you set is for your local timezone. This is stored in `post_date`. UTC time is stored in `post_date_gmt`.

I don't know how you're outputting this on the frontend but how you do so will control what timezone is used. Without seeing the code you're using I cannot suggest what the issue is, but this doesn't sound like a WooCommerce problem, and you have not given details enough steps for me to confirm if it is or is not.

Feel free to reply back if you can present more details. For now I'm marking this as invalid.

Thanks

**Closed by mikejolley** 2018-05-03 10:48 UTC

**Comment by firstlove87** [comment] 2018-05-03 15:40
Dear sir,
I'm sorry. But i'm talking about schedule on Sale price date you can see this screenshot http://prntscr.com/jd9uz2
Function which i used to print the date is: date( 'Y/m/d H:i:s' ). Example: When i choose timezone on settings amin is: UTC+7 and set date is: 2018-05-03 . I get value of that metabox is: **1525280400** and value print on frontend is : 2018/05/02 17:00:00
Plz let me know why is it.

Thanks!

**Comment by mikejolley** [comment] 2018-05-03 15:42
We store in UTC. If you output it, you must convert back to your timezone.

**Comment by firstlove87** [comment] 2018-05-04 10:25
Dear sir,
I see, but when you store it on admin, it convert to time with timezone settings. I use a code:
 $time =get_post_meta( $product->get_id(), '_sale_price_date_to', true ); 
echo date( 'Y/m/d H:i:s', $time );
The value after print as i talked on the last comment. You can check with TimeZone settings on admin.

Thanks!
