### ISSUE TITLE
PUT PRODUCTS DOES NOT UPDATE

### ISSUE THREAD

**Issue by iurycardoso** [woocommerce/woocommerce#27776] opened 2020-09-24 18:08 UTC
**Versão do Woocommerce:** 4.5.2
---------
I made the PUT through the postman where it returns "status: 200 ok", but does not update the object.

I searched the issues but found nothing related.

- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
execute the put according to documentation:
[Woocommerce API DOC](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product)
trying to change regular_price to 24.00, it returns "status 200" but does not change the value

**Expected behavior**
You should change the value of regular_price when json_response returns with status 200

**Actual behavior**
Does not change the value of regular_price when json_response returns with status 200

**Steps to reproduce the bug**
just follow the official documentation and execute the put method on the postman as shown.
[Woocommerce API DOC](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product)

**Screenshots**

![Captura de tela 2020-09-24 150432](https://user-images.githubusercontent.com/33526377/94182386-4c20c200-fe77-11ea-973a-10bd211eba65.png)

**Comment by rodrigoprimo** [comment] 2020-10-22 21:02
Hi @iurycardoso,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodrigoprimo** 2020-10-22 21:02 UTC
