### ISSUE TITLE
Single product page - images not showing after switching to  CDN

### ISSUE THREAD

**Issue by aleksicbre** [woocommerce/woocommerce#18804] opened 2018-02-04 16:02 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. I have WooCommerce 3.2.6.
2. Using WP Super Cache (which I already have), I added CDN.
3. Single Product Image do not show after CDN set-up: http://prntscr.com/i9zoy0

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://steamshopsrbija.com
Site URL: https://steamshopsrbija.com
WC Version: 3.2.2
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.33
PHP Post Max Size: 192 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.0.2m

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.2
WC Database Prefix: wpqd_
MaxMind GeoIP Database: ✔
Total Database Size: 8.91MB
Database Data Size: 6.93MB
Database Index Size: 1.98MB
wpqd_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
wpqd_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpqd_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_order_items: Data: 0.02MB + Index: 0.01MB
wpqd_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.10MB
wpqd_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wpqd_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpqd_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpqd_aws_index: Data: 0.45MB + Index: 0.00MB
wpqd_cashback: Data: 0.02MB + Index: 0.00MB
wpqd_commentmeta: Data: 0.02MB + Index: 0.03MB
wpqd_comments: Data: 0.15MB + Index: 0.07MB
wpqd_ewwwio_images: Data: 0.29MB + Index: 0.13MB
wpqd_gamipress_logs: Data: 0.02MB + Index: 0.02MB
wpqd_gamipress_logs_meta: Data: 0.02MB + Index: 0.03MB
wpqd_gamipress_user_earnings: Data: 0.02MB + Index: 0.03MB
wpqd_links: Data: 0.00MB + Index: 0.00MB
wpqd_options: Data: 0.88MB + Index: 0.18MB
wpqd_p2p: Data: 0.02MB + Index: 0.05MB
wpqd_p2pmeta: Data: 0.02MB + Index: 0.03MB
wpqd_postmeta: Data: 0.94MB + Index: 0.54MB
wpqd_posts: Data: 0.62MB + Index: 0.06MB
wpqd_say_what_strings: Data: 0.01MB + Index: 0.00MB
wpqd_termmeta: Data: 0.00MB + Index: 0.01MB
wpqd_terms: Data: 0.00MB + Index: 0.01MB
wpqd_term_relationships: Data: 0.00MB + Index: 0.01MB
wpqd_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpqd_ualp_user_activity: Data: 0.00MB + Index: 0.00MB
wpqd_uji_counter: Data: 0.00MB + Index: 0.00MB
wpqd_uji_subscriptions: Data: 0.00MB + Index: 0.00MB
wpqd_usermeta: Data: 0.22MB + Index: 0.12MB
wpqd_users: Data: 0.02MB + Index: 0.03MB
wpqd_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wpqd_wfBlockedIPLog: Data: 0.01MB + Index: 0.01MB
wpqd_wfBlocks: Data: 0.00MB + Index: 0.00MB
wpqd_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wpqd_wfConfig: Data: 0.23MB + Index: 0.01MB
wpqd_wfCrawlers: Data: 0.01MB + Index: 0.00MB
wpqd_wfFileMods: Data: 1.07MB + Index: 0.21MB
wpqd_wfHits: Data: 0.37MB + Index: 0.08MB
wpqd_wfHoover: Data: 0.00MB + Index: 0.00MB
wpqd_wfIssues: Data: 0.00MB + Index: 0.00MB
wpqd_wfKnownFileList: Data: 0.58MB + Index: 0.07MB
wpqd_wfLeechers: Data: 0.01MB + Index: 0.02MB
wpqd_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wpqd_wfLocs: Data: 0.00MB + Index: 0.00MB
wpqd_wfLogins: Data: 0.02MB + Index: 0.01MB
wpqd_wfNet404s: Data: 0.00MB + Index: 0.00MB
wpqd_wfNotifications: Data: 0.00MB + Index: 0.00MB
wpqd_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wpqd_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wpqd_wfScanners: Data: 0.02MB + Index: 0.03MB
wpqd_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wpqd_wfStatus: Data: 0.07MB + Index: 0.04MB
wpqd_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wpqd_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wpqd_wpam_actions: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_affiliates: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_affiliates_fields: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_creatives: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_events: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_impressions: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_messages: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_paypal_logs: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_tracking_tokens: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_tracking_tokens_purchase_logs: Data: 0.02MB + Index: 0.00MB
wpqd_wpam_transactions: Data: 0.02MB + Index: 0.00MB
wpqd_wpml_mails: Data: 0.43MB + Index: 0.00MB
wpqd_wpsp_agent_settings: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_attachments: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_canned_reply: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_catagories: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_custom_fields: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_custom_priority: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_custom_status: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_faq: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_faq_catagories: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_panel_custom_menu: Data: 0.00MB + Index: 0.00MB
wpqd_wpsp_ticket: Data: 0.00MB + Index: 0.02MB
wpqd_wpsp_ticket_thread: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

amn_smtp: 1
attachment: 124
custom_css: 1
customize_changeset: 4
et_pb_layout: 7
gamipress-log: 2
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 9
page: 20
points-award: 2
points-type: 1
post: 1
product: 53
product_variation: 25
revision: 11
shop_coupon: 21
shop_order: 206
shop_order_refund: 2
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Page Speed Optimization for SEO: by PageSpeed.pro – 2.9.8
Autoptimize: by Frank Goossens (futtta) – 2.3.2
Customer Reviews for WooCommerce: by ivole – 3.19
EWWW Image Optimizer: by Shane Bishop – 4.0.6
Jetpack by WordPress.com: by Automattic – 5.7.1
MoceanSMS WooCommerce: by Micro Ocean Technologies – 1.0.4 – Not tested with the active version of WooCommerce
Say What?: by Lee Willis – 1.9.1
Speed Booster Pack: by Macho Themes – 3.6.1
Tawk.to Live Chat: by Tawkto – 0.3.4
WooCommerce Thank You Page - NextMove Lite: by XLPlugins – 2.1.1
Booster for WooCommerce: by Algoritmika Ltd – 3.3.0
WooCommerce Quick Buy: by Varun Sridharan – 1.8 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.2 – 3.2.6 is available
WP Mail SMTP: by WPForms – 1.2.4
WP Super Cache: by Automattic – 1.5.9
WP-Sweep: by Lester 'GaMerZ' Chan – 1.0.12

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: RSD (RSD)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: simple (simple)
variable (variable)

Taxonomies: Product Visibility: featured (featured)
outofstock (outofstock)
rated-5 (rated-5)

### WC Pages ###

Shop base: #45 - /
Cart: #40 - /korpa/
Checkout: #41 - /narucivanje/
My account: #42 - /moj-nalog/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi
Version: 3.0.100
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Divi/woocommerce/emails/customer-completed-order.php
Divi/woocommerce/emails/customer-new-account.php
Divi/woocommerce/emails/customer-note.php
Divi/woocommerce/emails/customer-on-hold-order.php
Divi/woocommerce/emails/customer-processing-order.php

`
</details>

**Comment by GlennMartin1** [comment] 2018-02-04 17:24
Your system report says you're running 3.2.2, not the present 3.2.6. 

Upgrade to WC 3.2.6. Check if the problemis resolved. 

If not, disable all plugins to demonstrate if it still happens with WC only. If the problem is resolved with only WC activated, it's not a WC core issue. 

Isolate it to the which plugin causes it (which you're saying is WP Super Cache). If that's in fact the problem, take up the issue with their support channels.

**Closed** 2018-02-04 20:11 UTC
Labels: Invalid / Duplicate

**Comment by aleksicbre** [comment] 2018-02-04 23:00
I updated. But how can I test it without WC when problem IS on WC.?!

**Comment by GlennMartin1** [comment] 2018-02-04 23:39
You cannot test with WooCommerce deactivated. 

Keep WooCommerce activated throughout this process. 

Deactivate all the other plugins. 

If problem is resolved in that context, then WooCommerce is not the issue. 

Then activate one plugin at a time, and test for the problem after each plugin activation until you can isolate which plugin causes the issue. That plugin that causes the issue is the one you must seek support from.
