### ISSUE TITLE
Draft post set as shop page causes trouble

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#24136] opened 2019-07-12 11:23 UTC
**Describe the bug**
ref: p9F6qB-3wL-p2

TL;DR: Setting draft page as a shop page causes weird effects. We can notify the user or add a warning to the system status report about this or solve this in some nice way?

**Comment by anjamray** [comment] 2019-07-15 14:12
لمادا عندما غيرت قالب موقعي وبعد التغيرات اصبح موقعي لا يعمل 
مكررة مكررة من #

**Comment by anjamray** [comment] 2019-07-15 14:15
![Screenshot_2019-07-15-10-41-37-62](https://user-images.githubusercontent.com/52838923/61222795-51329f00-a713-11e9-8072-528c22f9a605.png)

**Comment by juliaamosova** [comment] 2020-01-17 16:04
Hi @peterfabian,

Thanks for filing this issue. I am going over older bugs without assigned priority hence the late comment here. 

I see that if you assign a page which is in draft to be the shop page, the shop page looks empty (tested with 3.8.1):

![shop1](https://user-images.githubusercontent.com/19143190/72626512-c4c39c00-3942-11ea-9926-1e2372267ade.jpg)

![shop2](https://user-images.githubusercontent.com/19143190/72626523-ca20e680-3942-11ea-8076-974cef846d30.jpg)

I wonder if we should exclude pages that are in draft from the list of pages available to be set as a `shop` page. 

In any case, this seems like a `low priority` issue to me - hence assigning it to this issue.

**Comment by juliaamosova** [comment] 2020-01-17 16:19
Hi @anjamray,

Note that we reply here in English language only. I translated your message using [Google Translate](https://translate.google.com/). You can do the same translating my message back to Arabic.

>لمادا عندما غيرت قالب موقعي وبعد التغيرات اصبح موقعي لا يعمل
مكررة مكررة من #

Translation from Arabic:

>Why when I changed my site template and after the changes my site became not working
Duplicate duplicate of # 

It is not clear from your message what you are referring to. It also doesn't look like it is related to the original issue reported here. 

If you think your issue is related to the issue reported here, please confirm it. 

If not, please open a separate issue and provide us with more details about it.

**Comment by Knyazevich** [comment] 2020-10-06 02:45
Checking this one.

**Closed** 2020-10-07 17:12 UTC
Labels: bug, priority: low
