### ISSUE TITLE
Order Update WebHook triggers before woocommerce_order_action_wc_CUSTOM action

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#26861] opened 2020-06-24 20:59 UTC
Hi, dont know if this is a bug, but any custom order action will run after the order update webhook so any changes made to the order will be saved but the webhook will not reflect those changes. An example:

`function manage_actions( $actions ) {
   $actions['wc_my_custom_action'] = 'My Custom Action';
   return $actions;
}
add_action( 'woocommerce_order_actions', 'manage_actions');

function custom_action_function( $order ) {
    update_post_meta( $order->id, 'Custom_Meta', 'Value' );
}
add_action( 'woocommerce_order_action_my_custom_action', 'custom_action_function' );`

Set up a OrderUpdate WebHook and run this custom action from the order admin, the meta data will be saved to the order but the webhook payload will not show it.
Can anyone suggest a way to reflect the changes made into the webhook? thanks

**Comment by claudiosanches** [comment] 2020-06-25 19:39
Hi @negapo,

> Hi, dont know if this is a bug, but any custom order action will run after the order update webhook so any changes made to the order will be saved but the webhook will not reflect those changes. An example:

In fact any order action runs after webhooks are triggered, see:

https://github.com/woocommerce/woocommerce/blob/8332410939b8b96fc959445d8571e76651bda8a3/includes/admin/class-wc-admin-meta-boxes.php#L42-L55

Webhooks will get fired on `WC_Meta_Box_Order_Data::save`, so not even WooCommerce's default order actions will run after.

I am closing this issue for now because it's an expected behavior for order actions. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-06-25 19:39 UTC

**Comment by negapo** [comment] 2020-06-25 20:03
Thanks for the reply @claudiosanches, but why, I can see that is the coded behavior, but is there any rational?
If you add/remove/modify meta data via the API the WebHook will be triggered, if you add/remove/modify meta data via the order admin, no WebHook will be triggered, if you change any data via actions a WebHook will be triggered before the actions run and data changes from the actions will not be reflected.

There is no consistency on the behavior of order update webhooks, but worse, nobody thought properly about what those webhooks are used. Order updates webhooks are used to inform other systems of changes in orders, if they do not reflect all changes (like adding/deleting/modifying meta data) then they aren't reliable and become useless.

**Comment by negapo** [comment] 2020-06-26 13:07
The rational for this to work is simple, anything that changes the WebHook Payload (the json) should trigger a event, this is the only way the WebHook can be used with confidence and be a true alternative to the Request/Response logic of the API, being very similar to a Push API. Whats the point of a WebHook that triggers only on some changes and on others doesn't?

The argument will most likely be that the postmeta is stored on another table but on the logic side of things an order is and order, no matter where some information is stored on the DB. And although no other users has complained about this you cannot develop a good product only based on what most users demand, you have to lay down a good logic and working base, and this kind of basic functions are indeed important because this is the way Woo can be expanded to work in a multi app environment.
