### ISSUE TITLE
Import Products: Product custom metadata is not updated instead added as new metadata.

### ISSUE THREAD

**Issue by 5um17** [woocommerce/woocommerce#25783] opened 2020-02-28 12:44 UTC
**Describe the bug**
When a product has meta key name like `_price_USD` and updated using CSV file with WC import feature then all of the data is updated except this meta value. Instead of updating the value in this key a new key is added with updated value e.g `_price_usd`.

As you can see WC is not updating the existing meta key because of uppercase string in the key name.

The issue is reported in [WPML forum](https://wpml.org/forums/topic/every-time-i-update-the-turkish-lira-it-creates-another-column/). WPML store the custom price of the product in metadata and the key name is constructed using a combination of original key + uppercase currency code.

The problem is originated from [this pull request](https://github.com/woocommerce/woocommerce/pull/16843) 

**To Reproduce**
1. Add a product meta with key name e.g.  `custom_PRICE`
2. Export the product with meta key to CSV file 
3. Import the CSV file and update the product 
4. Meta value is not updated instead a new meta key is added with name `custom_price`

**Expected behavior**
We should be able to update the product meta value.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.
</details>

**Comment by vedanshujain** [comment] 2020-05-14 13:37
normalizing (converting to lower case) column headers is by design to minimize column mismatching in general. For example, when someone accidentally change a case in column name (or if gets changed in a locale).

However, as a workaround, if you need to map a column name that is not normalized, I would recommend using filter `woocommerce_csv_product_import_mapped_columns` to fetch that column name and change it back to what you want. 

I am closing this issue but will reopen if there is intereset from other folks as well to revisit this decision.

**Closed by vedanshujain** 2020-05-14 13:37 UTC
