### ISSUE TITLE
Bug: When using `get_page_link( wc_get_page_id ())` on a non-registered WC page, such as the Shop, the load times get exponentially bigger.

### ISSUE THREAD

**Issue by redlagoon** [woocommerce/woocommerce#20679] opened 2018-07-01 20:48 UTC
**Describe the bug**
When using the snippet:

`esc_url( get_page_link( wc_get_page_id( 'shop' ) ) );`

To retrieve the shop page, but the shop page hasn't been assigned to anything, as such:

`get_option( 'woocommerce_shop_page_id' )` fails -

The whole execution of the process gets messed up and it gets stuck, resulting in incredibly bad load times.

**To Reproduce**
*. You must put the first line that retrives the shop page link somewhere. I'm using mine in a cart view.
1. Go to `wp_options`, delete the value for `woocommerce_shop_page_id`, it should be a number.
2. Remove that value, set it to NULL.
3. Reload your page. You should now see a way bigger load time.

**Expected behavior**
It should graciously fall and return nothing if nothing is found, instead, it slows everything down.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Addtional Notes**
I've tested this backwards, by adding the Shop page's ID to the `woocommerce_shop_page_id` option itself, by hand. It now loads perfectly. Again, removing it results in very bad load times.

**WordPress Environment**
WP 4.9.6
PHP 7.2
```
### WordPress Environment ###

Home URL: http://127.0.0.1/wordpress
Site URL: http://127.0.0.1/wordpress
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.3
PHP Version: 7.2.3
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.31-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.68MB
Database Data Size: 1.81MB
Database Index Size: 0.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.13MB + Index: 0.02MB
wp_postmeta: Data: 0.09MB + Index: 0.06MB
wp_posts: Data: 0.09MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 36
customize_changeset: 27
elementor_library: 2
nav_menu_item: 13
page: 20
post: 13
revision: 37

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Elementor: by Elementor.com – 2.0.16
Jetpack by WordPress.com: by Automattic – 6.2.1
Reset WP: by Nikunj Soni – 1.2
WooCommerce: by Automattic – 3.4.2 – 3.4.3 is available

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: #802 - /cart/
Checkout: #803 - /checkout/
My account: #804 - /my-account/
Terms and conditions: #2 - /sample-page/

### Theme ###

Name: Amaranth
Version: – 0 is available
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: amaranth/Framework/Sprout/Integrations/Woo/archive-product.php version 3.3.0 is out of date. The core version is 3.4.0
amaranth/Framework/Sprout/Integrations/Woo/cart\cart.php version 3.3.0 is out of date. The core version is 3.4.0
amaranth/Framework/Sprout/Integrations/Woo/checkout\form-checkout.php
amaranth/Framework/Sprout/Integrations/Woo/content-product.php version 3.0.0 is out of date. The core version is 3.4.0
amaranth/Framework/Sprout/Integrations/Woo/content-single-product.php version 3.0.0 is out of date. The core version is 3.4.0
amaranth/Framework/Sprout/Integrations/Woo/loop\loop-start.php
amaranth/Framework/Sprout/Integrations/Woo/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

</details>
```

**Comment by rodrigoprimo** [comment] 2018-07-03 14:10
I was not able to reproduce the issue you described. Here is what I did to test on a clean WC core site (master branch) running Storefront and WP 4.9.6:

- Deleted the option `woocommerce_shop_page_id`
- Added this code `echo esc_url( get_page_link( wc_get_page_id( 'shop' ) ) );` to the top of `templates/cart/cart.php` right after the call to `do_action( 'woocommerce_before_cart' );`.
- Opened the cart page on the browser and compared page load time, memory usage, query execution time and the number of database queries executed using [Query Monitor](https://wordpress.org/plugins/query-monitor/) when the code above is present and when it is not. There was no significant difference in the four metrics that I checked.

[wc_get_page_id()](https://github.com/woocommerce/woocommerce/blob/f7baef9938deaad039037f6287b6ad24162d97f2/includes/wc-page-functions.php#L41) checks if the option exists and if not returns `-1`. Passing `-1` to `get_page_link()` generates the following PHP notice:

```
PHP Notice:  Trying to get property of non-object in /vagrant/www/wccore/htdocs/wp-includes/link-template.php on line 317
```

I opened a WP ticket to address this: https://core.trac.wordpress.org/ticket/44497

I see in your status report that your site has a few plugins active, is running WC 3.4.2 and is using a theme other than Storefront or a default WP theme. Could you please see if you can reproduce this issue running WC master branch, with all other plugins deactivated and using either Storefront or one of the WP default themes?

**Comment by claudiulodro** [comment] 2018-07-03 18:43
Hi there.

I also wasn't able to reproduce the issue. I had the same performance with and without the shop page ID option present. All `wc_get_page_id` does is check/return an option value, so performance of it should be the same whether or not the option exists. Performance degradation could be happening because of your custom theme with outdated templates or because of the page-builder plugin you are using. I recommend testing without those active and seeing what sorts of results you get.

I'm going to close this issue as non-reproducible. Thanks.

**Closed by claudiulodro** 2018-07-03 18:43 UTC
Labels: status: needs feedback
