### ISSUE TITLE
Checkout coupon notification layout issue with flex layout

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#28948] opened 2021-01-26 22:24 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
In the checkout screen, if you remove a coupon you get a notice that the coupon has been removed. If you then click on "click here to enter your code", the coupon form layout is disturbed by the removal notice that is still there.

**Expected behavior**
a cleaner layout, either the notice is above/below the form, or removed when the coupon form is revealed

**Actual behavior**
The removal notice is smashed in between the coupon input and the apply coupon button

![image](https://user-images.githubusercontent.com/507025/105913622-59e38100-5fea-11eb-909c-0113acaea6f7.png)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add a product to the cart. Add a coupon.
2. Go to checkout
3. Remove coupon
4. Click link for "click here to enter your code" 

**Screenshots**

here's a recording with the Twenty Twenty theme:

![Screen Recording 2021-01-26 at 10 25 55 39 AM](https://user-images.githubusercontent.com/507025/105913320-e0e42980-5fe9-11eb-91c7-6b49820e8956.gif)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment] 2021-01-26 23:48
Hi @helgatheviking,

Thank you for taking the time to report this issue and providing thorough replication steps (including the video)! I was able to replicate the bug on my end using the Twenty Twenty theme:

<img width="1435" alt="Screen Shot 2021-01-26 at 4 38 09 PM" src="https://user-images.githubusercontent.com/71906536/105921081-a54f5c80-5ff5-11eb-9d59-b3b5da4a4d56.png">

I also checked to make sure this wasn't affecting the new theme, Twenty Twenty One:

<img width="1460" alt="Screen Shot 2021-01-26 at 4 37 48 PM" src="https://user-images.githubusercontent.com/71906536/105921176-c152fe00-5ff5-11eb-8ae7-cc9cf01d880d.png">

While the new default theme is Twenty Twenty One, we likely should fix it soonish as many people may still use Twenty Twenty on their sites and this bug is indeed annoying. It appears this issue was reported on https://github.com/woocommerce/woocommerce/issues/28422 previously, so I will close this as duplicate of that issue. You can follow the issue there and feel free to share any other details.

Thank you!

**Closed by zhongruige** 2021-01-26 23:48 UTC

**Comment by helgatheviking** [comment] 2021-01-27 17:19
Sorry for the duplicate. I ran a cursory search and missed that one.

**Comment by zhongruige** [comment] 2021-01-27 17:27
> Sorry for the duplicate. I ran a cursory search and missed that one.

No worries at all! Thank you for taking the time to report the issue :)
