### ISSUE TITLE
attributes not working in 4.3

### ISSUE THREAD

**Issue by caribouman** [woocommerce/woocommerce#27076] opened 2020-07-20 08:32 UTC
**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
when i pass to 4.3, on my single item page, i can t add product to cart. it tells me that i have no selected attributes.

**Expected behavior**
it has to see i have all attributes selected

**Actual behavior**
i roll back to 4.2.2 and it works again

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to single page
2. Click on attributes to select value
3. add to cart 
4. message appears that say i didn t select attributes

**Screenshots**

https://www.sergent-tobogo.com/tee-shirt/bella-ciao-la-casa-de-papel/

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by peterfabian** [comment] 2020-07-22 11:48
Hi @caribouman,

Thanks for reporting. I can't seem to reproduce this with WooCommerce core (and also with Variation Swatches plugin). Can you please add more information on how to reproduce the problem? Are there any other plugins running on your site that might be interfering?

**Comment by DamienMLBW** [comment] 2020-07-28 16:18
I have the same problem and I have found some query errors in my error_log : 
```
[28-Jul-2020 12:34:41 UTC] WordPress database error Table 'muralunique_db.a' doesn't exist for query SELECT a.action_id FROM  a WHERE a.hook='woo_sc_generate_coupon_csv' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, wpseo_init, WPSEO_Ryte->__construct, WPSEO_Ryte->maybe_add_weekly_schedule, wp_get_schedules, apply_filters('cron_schedules'), WP_Hook->apply_filters, WC_SC_Background_Coupon_Importer->modify_action_scheduler_default_interval, WC_SC_Background_Coupon_Importer->is_process_running, ActionScheduler_DBStore->find_action
[28-Jul-2020 12:34:41 UTC] WordPress database error Table 'muralunique_db.a' doesn't exist for query SELECT a.action_id FROM  a WHERE a.hook='woo_sc_import_coupons_from_csv' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, wpseo_init, WPSEO_Ryte->__construct, WPSEO_Ryte->maybe_add_weekly_schedule, wp_get_schedules, apply_filters('cron_schedules'), WP_Hook->apply_filters, WC_SC_Background_Coupon_Importer->modify_action_scheduler_default_interval, WC_SC_Background_Coupon_Importer->is_process_running, ActionScheduler_DBStore->find_action
```

It's like a table name is missing in the query. I have deleted and reinstalled the latest version of WooCommerce Smart Coupons. Seems no new errors in the log for now but I'm not sure if it's linked with this problem.


@caribouman do you have WooCommerce Smart Coupons installed on your website ?

**Comment by caribouman** [comment] 2020-07-28 19:42
Hi, no i don t have Woocommerce smart coupons and also i don t have variation swatches plugin, i use a woocommerce 2.1 template for variation that i modify , for now i didn t have problem when i upgrade....i have to make a copy of my production site and upgrade again to 4.3 to test again...if i have new info i will publish here zhen i ll have time to test

**Comment by juliaamosova** [comment] 2020-08-05 21:00
Hi @caribouman, please let us know if the issue still present for you and if you can provide more details? It will also be great if you could make sure to test for a theme and plugins conflict in case the error is still there. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-08-13 13:47
Hi @caribouman,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-08-13 13:47 UTC
Labels: status: needs feedback

**Comment by caribouman** [comment] 2020-09-23 21:24
hi i put my website in dev mode and i have the problem again,

http://dev.sergent-tobogo.com/tee-shirt/make-fun-not-war/

impossible to validate variation, it makes like no variation is selected
i have input, i see there was not data-attribute_name to my input field but even when i add it with this it doesn t work

one thing  i see this hidden input field
<input type="hidden" name="variation_id" class="variation_id" value="">

and is not populated by changing variation

so you have an idea of javascript change in your process of validate field???

thanks
