### ISSUE TITLE
The "edit" link is missing from admin panel at the top of the page when on a shop page.

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce#29203] opened 2021-02-23 16:15 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The "edit" link/button is missing from the admin panel at the top of the page when on a shop page. It is there on other pages like home page or even product page.

**Expected behavior**
I'd expect to see that link on the shop page too.

**Actual behavior**
It's not there.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to the shop page.
2. Go to the home page and a product page in new tabs.
3. Compare

**Screenshots**
Shop page:

<img width="1357" alt="Screenshot 2021-02-23 at 17 13 31" src="https://user-images.githubusercontent.com/13084901/108872538-8d6df700-75fa-11eb-8f6c-6fc0f9e11f5c.png">

Home page:

<img width="1318" alt="Screenshot 2021-02-23 at 17 13 44" src="https://user-images.githubusercontent.com/13084901/108872546-91017e00-75fa-11eb-99b7-f9c7cf3116d9.png">

Product page:

<img width="1355" alt="Screenshot 2021-02-23 at 17 14 01" src="https://user-images.githubusercontent.com/13084901/108872570-95c63200-75fa-11eb-9eb0-19c746a4ed60.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2021-02-23 20:19
Hi @grig-23,

Thanks for highlighting this issue! I can reproduce it. I wonder if there is a reason behind the Shop page not having the edit option in the admin bar. I am adding the `needs developer feedback` label here to see if the current behavior is expected or not.

**Comment by barryhughes** [comment] 2021-04-26 22:57
Great observation!

The [shop page](https://docs.woocommerce.com/document/woocommerce-pages/#section-4) is something of a special case. It's more of a placeholder than anything else, and we use it to display the main products archive. Conceptually, it's closest in nature to a custom post type archive (for which we also would not see an _Edit Post_ link).

I would also point out here that, at least by default, any content you add to the shop page will not actually be displayed (in that regard, it's a little different from shortcode-powered views such as the Cart or My Account pages) so I'd imagine that—in most cases—having an _Edit Page_ link in the admin toolbar would be pretty redundant.

With that said, I'd love to understand more about why you want this?

**Comment by barryhughes** [comment] 2021-05-10 17:24
Edited my last remark, my local testing was a little flawed. 

The reason the link does not display in the admin bar is the same, though: the link doesn't appear because the main WP query is for a post type archive rather than a page. But, as we can see from other issues like 29723 there is definitely a desire to edit and add things to the page.

**Comment by grig-23** [comment] 2021-06-03 15:12
Sorry for the delay here!

I forgot to mention that it was reported in 3748975-zen and it's just something that would be convenient for this user :) Perhaps their workflows include such editing and it would save them a few seconds here and there.

I've shared alternative ways of achieving the same result.

**Comment by peterfabian** [comment] 2021-10-13 13:20
As this one has a workaround and later on shop page will probably be taken over by blocks, I'm closing this issue. Please feel free to comment if you disagree.

**Closed by peterfabian** 2021-10-13 13:20 UTC
Labels: type: bug, priority: low

**Comment by sybrew** [comment] 2023-11-15 14:14
It still hasn't been (and probably never will be) taken over by blocks; regardless, I think this omission is still confusing. 

After all, it's a post acting like a post type archive (this is fine), and the post metadata is still effective for it (this is also fine). A way to navigate to edit those quickly would be welcome.

**Comment by nerrad** [comment] 2023-11-16 14:15
The Shop (in the context of block themes) **can be navigated** to directly:
![CleanShot 2023-11-16 at 09 13 27](https://github.com/woocommerce/woocommerce/assets/1429108/f0a8c7a2-badc-4f1f-8180-a3cb06d695b8)

> It still hasn't been (and probably never will be) taken over by blocks; 

Classic themes don't use blocks (they can if they want though). But block themes _do_ provide block powered views by default now for Woo.
