### ISSUE TITLE
Bug - Cannot checkout on the website - credit card doesnt work.

### ISSUE THREAD

**Issue by courtneyogren** [woocommerce/woocommerce#26820] opened 2020-06-18 23:52 UTC
"Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements."

This is what our website says when a customer attempts to checkout. Can you help at all with this problem?? I cannot figure out how to fix it.

**Comment by mischasigtermans** [comment] 2020-06-19 06:51
Same issue here on one of our shops. We’re trying to debug this. I’ll post our findings.

Any others facing this issue?

**Comment by juliaamosova** [comment] 2020-06-22 17:20
Hi @courtneyogren,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-06-22 17:20 UTC
