### ISSUE TITLE
delete endpoint is not working using postman

### ISSUE THREAD

**Issue by rahman973** [woocommerce/woocommerce#24932] opened 2019-10-30 11:23 UTC
Hello,
        I'm facing and getting some error in delete endpoint using any of the base either products or orders. the delete endpoint is not working using the POSTMAN and is throwing error either after using force=true.
all other endpoints like GET, POST both are working fine.
`/wp-json/wc/v3/products/9?force=true`

**Comment by kloon** [comment] 2019-10-30 13:33
Hi @rahman973 I just tested this with the latest version of WooCommerce and products delete fine without using the force param.

![](https://cld.wthms.co/QjmLuX+)

I suggest you check you are using the correct API credentials and that they are setup with read/write permissions, and also check the user tied to the API credentials have permissions to delete products.

Closing as I am not able to reproduce.

**Closed by kloon** 2019-10-30 13:33 UTC

**Comment by rahman973** [comment] 2019-10-30 13:41
Hi Friend, but it is not working in my case. File is attached.
My API has both READ and WRITE permissions allowed. Can you tell me if there are different permissions for deleting 

Regards
From Abdul Rahman
