### ISSUE TITLE
No such source: 'src_1GJQgnHmxRNggSKxn4Rb9P4D' 

### ISSUE THREAD

**Issue by TruGator** [woocommerce/woocommerce#30190] opened 2021-06-30 20:21 UTC
Issue occurs when going through the purchase process. After submitting the credit card information and submitting. The error message given is: No such source: 'src_1GJQgnHmxRNggSKxn4Rb9P4D'.  What is the resolution for this issue?

![No such code](https://user-images.githubusercontent.com/86745323/124026004-c22df880-d9b6-11eb-827e-5c7d58bacb4a.png)

**Comment by tammullen** [comment] 2021-06-30 22:33
Hi @TruGator ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it and the other information we ask for in our bug report template.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-06-30 22:33 UTC
