### ISSUE TITLE
Product Catalog - Not showing BUT counting hidden products

### ISSUE THREAD

**Issue by gntoum** [woocommerce/woocommerce#24333] opened 2019-08-06 07:26 UTC
**Describe the bug**
Lets say for example, we have a product category with 100 products, and then we decide to edit 4-5 of them (or more), and change the visibility product, from "Store and Search Results" to "Hidden". When you see the category page (in front end), lets say we have a pagination of 15 products per page (the number doesn't affects something). When i have hidden products then from page 3-4 or later i can see that there are not showing 15 products (as it should be) but there are some empty spaces. 

I guess that for some reason these hidden products are still counted on counter on product listing.

**To Reproduce**
1. Create 50 or more product (or an existing eshop)
2. Make 5 or more products "hidden" from "Catalog and Search"
3. Go to product page, and change pages (go to 2,3,4,5 etc)
4. See empty spaces instead of products

**Screenshots**
I have set up to show 18 products per page
https://prnt.sc/oox16s

**Expected behavior**
Expected to see 18 (or the number i have set) products in every page on category view. 
I tried this and on clean setup with the latest WP & WC

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://staging.soundstar.gr
Site address (URL): https://staging.soundstar.gr
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6
PHP Version: 7.3.4
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Ο διακομιστής σας δεν έχει την κατηγορία SoapClient ενεργοποιημένη - μερικές υπηρεσίες πληρωμής που χρησιμοποιούν το SOAP μπορεί να μη λειτουργήσουν όπως αναμένεται.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
Συνολικό μέγεθος βάσης δεδομένων: 567.71MB
Μέγεθος βάσης δεδομένων: 384.14MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 183.57MB
wp_woocommerce_sessions: Δεδομένα: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Δεδομένα: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Δεδομένα: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Δεδομένα: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Δεδομένα: 1.52MB + Index: 0.13MB
wp_woocommerce_order_itemmeta: Δεδομένα: 3.52MB + Index: 3.03MB
wp_woocommerce_tax_rates: Δεδομένα: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Δεδομένα: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Δεδομένα: 0.02MB + Index: 0.02MB
woof_query_cache: Δεδομένα: 0.02MB + Index: 0.00MB
wp_commentmeta: Δεδομένα: 0.02MB + Index: 0.03MB
wp_comments: Δεδομένα: 9.52MB + Index: 9.09MB
wp_crf_entries: Δεδομένα: 0.02MB + Index: 0.00MB
wp_crf_fields: Δεδομένα: 0.02MB + Index: 0.00MB
wp_crf_forms: Δεδομένα: 0.02MB + Index: 0.00MB
wp_crf_option: Δεδομένα: 0.02MB + Index: 0.00MB
wp_crf_stats: Δεδομένα: 0.02MB + Index: 0.00MB
wp_crf_submissions: Δεδομένα: 0.02MB + Index: 0.00MB
wp_et_bloom_stats: Δεδομένα: 0.02MB + Index: 0.00MB
wp_et_social_stats: Δεδομένα: 0.08MB + Index: 0.00MB
wp_ewwwio_images: Δεδομένα: 7.52MB + Index: 5.03MB
wp_ewwwio_queue: Δεδομένα: 1.52MB + Index: 0.38MB
wp_failed_jobs: Δεδομένα: 0.03MB + Index: 0.00MB
wp_icl_content_status: Δεδομένα: 0.02MB + Index: 0.02MB
wp_icl_core_status: Δεδομένα: 0.02MB + Index: 0.02MB
wp_icl_flags: Δεδομένα: 0.02MB + Index: 0.02MB
wp_icl_languages: Δεδομένα: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Δεδομένα: 0.19MB + Index: 0.09MB
wp_icl_locale_map: Δεδομένα: 0.02MB + Index: 0.00MB
wp_icl_message_status: Δεδομένα: 0.02MB + Index: 0.03MB
wp_icl_mo_files_domains: Δεδομένα: 0.02MB + Index: 0.02MB
wp_icl_node: Δεδομένα: 0.02MB + Index: 0.00MB
wp_icl_reminders: Δεδομένα: 0.02MB + Index: 0.00MB
wp_icl_strings: Δεδομένα: 15.52MB + Index: 9.06MB
wp_icl_string_packages: Δεδομένα: 0.02MB + Index: 0.00MB
wp_icl_string_pages: Δεδομένα: 56.59MB + Index: 60.19MB
wp_icl_string_positions: Δεδομένα: 0.02MB + Index: 0.02MB
wp_icl_string_status: Δεδομένα: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Δεδομένα: 3.52MB + Index: 1.52MB
wp_icl_string_urls: Δεδομένα: 0.08MB + Index: 0.08MB
wp_icl_translate: Δεδομένα: 16.52MB + Index: 1.52MB
wp_icl_translate_job: Δεδομένα: 0.34MB + Index: 0.09MB
wp_icl_translations: Δεδομένα: 7.52MB + Index: 16.06MB
wp_icl_translation_batches: Δεδομένα: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Δεδομένα: 27.55MB + Index: 1.52MB
wp_links: Δεδομένα: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Δεδομένα: 0.05MB + Index: 0.00MB
wp_options: Δεδομένα: 10.50MB + Index: 0.34MB
wp_pmxe_exports: Δεδομένα: 0.38MB + Index: 0.00MB
wp_pmxe_google_cats: Δεδομένα: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Δεδομένα: 4.52MB + Index: 0.00MB
wp_pmxe_templates: Δεδομένα: 0.02MB + Index: 0.00MB
wp_pmxi_files: Δεδομένα: 0.02MB + Index: 0.00MB
wp_pmxi_history: Δεδομένα: 0.02MB + Index: 0.00MB
wp_pmxi_images: Δεδομένα: 0.47MB + Index: 0.00MB
wp_pmxi_imports: Δεδομένα: 2.52MB + Index: 0.00MB
wp_pmxi_posts: Δεδομένα: 4.52MB + Index: 0.00MB
wp_pmxi_templates: Δεδομένα: 0.27MB + Index: 0.00MB
wp_popover_ip_cache: Δεδομένα: 0.02MB + Index: 0.02MB
wp_postmeta: Δεδομένα: 136.69MB + Index: 54.17MB
wp_posts: Δεδομένα: 29.64MB + Index: 8.61MB
wp_queue: Δεδομένα: 0.00MB + Index: 0.00MB
wp_revslider_css: Δεδομένα: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Δεδομένα: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Δεδομένα: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Δεδομένα: 0.13MB + Index: 0.00MB
wp_revslider_slides: Δεδομένα: 0.47MB + Index: 0.00MB
wp_revslider_static_slides: Δεδομένα: 0.11MB + Index: 0.00MB
wp_termmeta: Δεδομένα: 1.52MB + Index: 0.73MB
wp_terms: Δεδομένα: 1.52MB + Index: 0.77MB
wp_term_relationships: Δεδομένα: 3.52MB + Index: 2.52MB
wp_term_taxonomy: Δεδομένα: 1.52MB + Index: 0.83MB
wp_tm_taskmeta: Δεδομένα: 0.02MB + Index: 0.03MB
wp_tm_tasks: Δεδομένα: 0.02MB + Index: 0.02MB
wp_usermeta: Δεδομένα: 5.52MB + Index: 4.03MB
wp_users: Δεδομένα: 0.22MB + Index: 0.20MB
wp_wc_admin_notes: Δεδομένα: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Δεδομένα: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Δεδομένα: 0.13MB + Index: 0.11MB
wp_wc_download_log: Δεδομένα: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Δεδομένα: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Δεδομένα: 0.34MB + Index: 0.33MB
wp_wc_order_stats: Δεδομένα: 0.47MB + Index: 0.34MB
wp_wc_order_tax_lookup: Δεδομένα: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Δεδομένα: 0.47MB + Index: 0.75MB
wp_wc_webhooks: Δεδομένα: 0.02MB + Index: 0.02MB
wp_wfBlockedIPLog: Δεδομένα: 0.05MB + Index: 0.03MB
wp_wfBlocks7: Δεδομένα: 0.02MB + Index: 0.05MB
wp_wfConfig: Δεδομένα: 0.45MB + Index: 0.01MB
wp_wfCrawlers: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wfFileChanges: Δεδομένα: 0.02MB + Index: 0.00MB
wp_wfFileMods: Δεδομένα: 3.17MB + Index: 0.64MB
wp_wfHits: Δεδομένα: 0.47MB + Index: 0.08MB
wp_wfHoover: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wfIssues: Δεδομένα: 0.02MB + Index: 0.01MB
wp_wfKnownFileList: Δεδομένα: 1.68MB + Index: 0.20MB
wp_wfLiveTrafficHuman: Δεδομένα: 0.02MB + Index: 0.02MB
wp_wfLocs: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wfLogins: Δεδομένα: 0.12MB + Index: 0.03MB
wp_wfls_2fa_secrets: Δεδομένα: 0.02MB + Index: 0.02MB
wp_wfls_settings: Δεδομένα: 0.02MB + Index: 0.00MB
wp_wfNotifications: Δεδομένα: 0.01MB + Index: 0.00MB
wp_wfPendingIssues: Δεδομένα: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wfSNIPCache: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wfStatus: Δεδομένα: 0.08MB + Index: 0.04MB
wp_wfTrafficRates: Δεδομένα: 0.02MB + Index: 0.00MB
wp_wm_excludeds: Δεδομένα: 0.02MB + Index: 0.02MB
wp_wm_maps: Δεδομένα: 0.02MB + Index: 0.00MB
wp_wpc_comments_subscription: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wpc_phrases: Δεδομένα: 0.00MB + Index: 0.01MB
wp_wpc_users_voted: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wpml_mails: Δεδομένα: 16.52MB + Index: 0.00MB
wp_wpsite_background_takeover_stats: Δεδομένα: 0.02MB + Index: 0.00MB
wp_wpsite_takeover_ads: Δεδομένα: 0.02MB + Index: 0.00MB
wp_wpsite_takeover_ad_groups: Δεδομένα: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Δεδομένα: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Δεδομένα: 0.05MB + Index: 0.05MB
wp_yoast_seo_links: Δεδομένα: 0.31MB + Index: 0.09MB
wp_yoast_seo_meta: Δεδομένα: 2.52MB + Index: 0.00MB

### Post Type Counts ###

attachment: 98096
basel_sidebar: 1
basel_slide: 2
cms_block: 8
condition_group: 1
cwginstocknotifier: 1
dgd_scrollbox: 2
easingslider: 1
et_pb_layout: 32
mc4wp-form: 3
mgmlp_media_folder: 281
nav_menu_item: 1230
oembed_cache: 3
page: 69
portfolio: 3
post: 1
product: 4717
quantity-rule: 1
restriction: 1
revision: 30
scheduled-action: 897
shop_coupon: 2
shop_order: 7256
vc_settings_preset: 1
wcps: 1
wpcf7_contact_form: 2
wysijap: 1
xox-carousel-slider: 1
yith_popup: 1
yith_wcps_type: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (65) ###

WPML Multilingual CMS: από τον/την OnTheGoSystems – 4.2.7.1
Redux Framework: από τον/την Team Redux – 3.6.15
Advanced noCaptcha & invisible Captcha: από τον/την Shamim Hasan – 5.5 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
XTEMOS Post Types plugin: από τον/την  – 1.9
Bellows Accordion Menu: από τον/την SevenSpark – 1.2.1
Catalog Xls Exporter - Social Mind: από τον/την SocialMind – 2.0.3 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Cloudflare: από τον/την John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.3

Contact Form 7: από τον/την Takayuki Miyoshi – 5.1.3
Content Control: από τον/την Jungle Plugins – 1.1.0
EWWW Image Optimizer: από τον/την Exactly WWW – 4.8.1
Export Users to CSV: από τον/την Matt Cromwell – 1.1.1
Extra User Details: από τον/την Vadym Khukhrianskyi – 0.4.3.1
Fast Velocity Minify: από τον/την Raul Peixoto – 2.7.3
Google Analyticator: από τον/την SumoMe – 6.5.4
Heartbeat Control by WP Rocket: από τον/την WP Rocket – 1.2.5
Jarvis: από τον/την The Web Development Group
David Everett
Joan Piedra
Kurtis Shaner
Doug Axelrod – 1.0.4

WPBakery Page Builder: από τον/την Michael M - WPBakery.com – 6.0.3
Mailchimp for WooCommerce: από τον/την Mailchimp – 2.1.17
Members: από τον/την Justin Tadlock – 2.2.0
Member Since: από τον/την WPBeginner – 1.0
Meta Box: από τον/την MetaBox.io – 5.0.1
Nav Menu Roles: από τον/την Kathy Darling – 1.9.3
New User Approve: από τον/την Josh Harrison – 1.7.6
Notely: από τον/την Michael Ott – 1.5.1
OneSignal Push Notifications: από τον/την OneSignal – 1.17.8
Really Simple SSL: από τον/την Rogier Lankhorst
Mark Wolters – 3.2.3

Recently Registered: από τον/την Mika Epstein – 3.4.3
Redux Vendor Support: από τον/την Team Redux – 1.0.1
Remove Dashboard Access: από τον/την Drew Jaynes (DrewAPicture) – 1.1.3
Restricted Site Access: από τον/την Jake Goldman
10up
Oomph – 7.1.0

Simple Feed Customizer: από τον/την Agbonghama Collins – 1.2.1
Tidio Chat: από τον/την Tidio Ltd. – 3.5.0
Tracking Code Manager: από τον/την IntellyWP – 1.12.0
User Notes: από τον/την Cartpauj – 1.0.1
Proxy Cache Purge: από τον/την Mika Epstein – 4.8.1
WooCommerce Bulk Order Form Pro: από τον/την Ewout Fernhout
Varun Sridharan
Jeremiah Prummer – 3.0.4 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce

WooCommerce Dynamic Pricing & Discounts: από τον/την RightPress – 2.3.3
Widget Logic: από τον/την WPChef – 5.10.4
Premmerce Customers Manager for WooCommerce: από τον/την premmerce – 1.1.10
WooCommerce Enhanced Ecommerce Analytics Integration with Conversion Tracking: από τον/την Thedotstore – 2.3 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Woo Payment Discounts: από τον/την WPCodelibrary – 1.1.3
WooCommerce Admin: από τον/την WooCommerce – 0.15.0
WooCommerce Attributes Menu Manager: από τον/την Varun Sridharan – 0.8 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
WooCommerce Bulk Order Form: από τον/την Ewout Fernhout
Varun Sridharan
Jeremiah Prummer – 7 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce

WooCommerce Advanced Product Quantities: από τον/την WP BackOffice – 2.1.9 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Πολυγλωσσικό WooCommerce: από τον/την OnTheGoSystems – 4.6.5
WooCommerce Product Filter: από τον/την Farhad Ahmadi – 2.8.0 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Woocommerce Products Per Page: από τον/την Jeroen Sormani – 1.2.6 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
WooCommerce: από τον/την Automattic – 3.6.4 – Η έκδοση 3.6.5 είναι διαθέσιμη
Wordfence Security: από τον/την Wordfence – 7.3.6
Yoast SEO: από τον/την Team Yoast – 11.7 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
WP All Export: από τον/την Soflyy – 1.2.4
WP All Import Pro: από τον/την Soflyy – 4.5.7
WP-DBManager: από τον/την Lester 'GaMerZ' Chan – 2.79.2
WP Disable: από τον/την optimisation.io - jody nesbitt – 1.5.21
WP-ShowHide: από τον/την Lester 'GaMerZ' Chan – 1.04
WP All Import - WooCommerce Add-On Pro: από τον/την Soflyy – 3.0.8
WPML All Import: από τον/την OnTheGoSystems – 2.1.1
WPML CMS Nav: από τον/την OnTheGoSystems – 1.5.2
WPML Media: από τον/την OnTheGoSystems – 2.5.2
WPML Sticky Links: από τον/την OnTheGoSystems – 1.5.0
WPML String Translation: από τον/την OnTheGoSystems – 2.10.5.1
WPML Translation Management: από τον/την OnTheGoSystems – 2.8.6.2
Yoast SEO: WooCommerce: από τον/την Η ομάδα του Yoast – 9.2 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Λίστα Επιθυμιών YITH WooCommerce: από τον/την YITH – 2.2.12

### Inactive Plugins (16) ###

Better WordPress Minify: από τον/την Khang Minh – 1.3.3
CMB2: από τον/την CMB2 team – 2.6.0
Eyes Only: User Access Shortcode: από τον/την Thom Stark – 1.8.2
Facebook for WooCommerce: από τον/την Facebook – 1.9.15 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Mailchimp for WordPress: από τον/την ibericode – 4.5.3
MailChimp for WordPress Multilingual: από τον/την OnTheGoSystems – 0.0.3
MailChimp User Sync: από τον/την ibericode – 1.7.7
Page Restrict: από τον/την Matt Martz & Andy Stratton – 2.2.9
Restrict User Access: από τον/την Joachim Jensen – 1.1.2
Schedule Tags: από τον/την zetamatic – 0.1
Slider Revolution: από τον/την ThemePunch – 6.0.2
User Menus: από τον/την Jungle Plugins – 1.1.3
WooCommerce Blocks: από τον/την Automattic – 2.2.1
WordPress Importer: από τον/την wordpressdotorg – 0.6.4
WP-Optimize - Clean, Compress, Cache: από τον/την David Anderson
Ruhani Rabin
Team Updraft – 3.0.7

WPS Hide Login: από τον/την Remy Perona for WPServeur – 1.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
simple (simple-en)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-en)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-en)
featured (featured)
featured (featured-en)
outofstock (outofstock)
outofstock (outofstock-en)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Βάση καταστήματος: #10 - /shop/
Καλάθι: #11 - /cart/
Ταμείο: #12 - /oloklirosi-parangelias/
Ο λογαριασμός μου: #13 - /o-logariasmos-mou/
Όροι και Προϋποθέσεις: #1133 - /terms-of-service/

### Theme ###

Name: Basel Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Basel
Parent Theme Version: 4.8.1
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: basel/woocommerce/archive-product.php
basel-child/woocommerce/cart/cart.php έκδοση 3.4.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.0
basel/woocommerce/cart/cross-sells.php
basel/woocommerce/cart/mini-cart.php
basel/woocommerce/checkout/form-checkout.php
basel/woocommerce/content-product.php
basel/woocommerce/content-product_cat.php
basel-child/woocommerce/content-single-product.php
basel/woocommerce/content-widget-product.php
basel-child/woocommerce/emails/admin-new-order.php έκδοση 2.5.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.0
basel-child/woocommerce/emails/customer-completed-order.php έκδοση 2.5.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.0
basel-child/woocommerce/emails/customer-new-account.php έκδοση 1.6.4 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.2
basel-child/woocommerce/emails/customer-on-hold-order.php έκδοση 2.5.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.0
basel-child/woocommerce/emails/customer-processing-order.php έκδοση 2.5.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.4
basel-child/woocommerce/emails/customer-reset-password.php έκδοση 2.0.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.0
basel-child/woocommerce/emails/email-order-items.php έκδοση 3.4.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.5.0
basel-child/woocommerce/emails/email-styles.php
basel/woocommerce/global/breadcrumb.php
basel/woocommerce/global/form-login.php
basel/woocommerce/global/quantity-input.php
basel/woocommerce/loop/loop-end.php
basel/woocommerce/loop/loop-start.php
basel/woocommerce/loop/no-products-found.php
basel/woocommerce/loop/orderby.php
basel/woocommerce/loop/pagination.php
basel-child/woocommerce/loop/price.php
basel/woocommerce/loop/sale-flash.php
basel/woocommerce/myaccount/form-login.php
basel/woocommerce/myaccount/navigation.php
basel/woocommerce/product-searchform.php
basel-child/woocommerce/single-product/add-to-cart/simple.php
basel/woocommerce/single-product/add-to-cart/variable.php
basel-child/woocommerce/single-product/meta.php
basel-child/woocommerce/single-product/price.php
basel/woocommerce/single-product/product-image.php
basel/woocommerce/single-product/product-thumbnails.php
basel/woocommerce/single-product/related.php
basel/woocommerce/single-product/sale-flash.php
basel-child/woocommerce/single-product/tabs/description.php
basel/woocommerce/single-product/tabs/tabs.php
basel/woocommerce/single-product/title.php
basel/woocommerce/single-product/up-sells.php
basel/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Μάθετε πως να κάνετε ενημέρωση

### Action Scheduler ###

Complete: 894
Oldest: 2019-07-04 15:33:43 +0300
Newest: 2019-08-06 10:08:53 +0300

Pending: 2
Oldest: 2019-08-06 10:27:40 +0300
Newest: 2019-08-06 11:08:54 +0300

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by rodrigoprimo** [comment] 2019-08-07 20:28
Hi there,

I was not able to reproduce this issue on a clean WooCommerce install using Storefront. When I set a few products as hidden, they are correctly removed from the categories page and no empty spaces are displayed.

I noticed that the screenshot shows that you are using a custom theme. We don't provide support for custom themes. I suggest you contact the theme author or try another theme to see if it fixes the problem.

Closing this issue for now as it doesn't seem to be a bug in WooCommerce core. Please leave a comment if I missed something and I will take a second look.

Thanks

**Closed by rodrigoprimo** 2019-08-07 20:28 UTC
