### ISSUE TITLE
 [GlobalStep - WooCommerce 4.8 + WPB 3.9] "Oops! That page can’t be found" is displayed upon tapping Privacy Policy linktext on Checkout Page

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28616] opened 2020-12-17 15:30 UTC
## Bug Description:
"Oops! That page can’t be found" is displayed upon tapping Privacy Policy linktext on Checkout Page

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version  87.0.4280.88 (64-bit))
                 Firefox(Version 83.0)(64-bit)
                 Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Assuming Products are added and Pages are created with All Products block.
1. Go to front end and add a product to cart
1. Click on "Checkout" button
1. Click on "Privacy Policy" link text
1. Observe that "Oops! That page can’t be found" is displayed upon tapping Privacy Policy linktext on Checkout Page

**Note:** 
Following was observed for this issue:-
-For Test Site-Exisiting User-It is working 
-Rest for all new users and guest users on New and Test Site it fails to work

## Actual Result:
"Oops! That page can’t be found" is displayed upon tapping Privacy Policy linktext on Checkout Page

## Expected Result:
 Privacy Policy link text should properly navigate user to its respective page.

## Artifacts:
[#28616.zip](https://github.com/woocommerce/woocommerce/files/5710426/28616.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-12-23 22:10
Hi @gglobalstep,

Thanks for reporting the issue! I can reproduce it on my end. 

>-For Test Site-Exisiting User-It is working
-Rest for all new users and guest users on New and Test Site it fails to work

I confirm that the Privacy Policy links works for logged in users but doesn't work for guest users (not logged in). Please see gifs below confirming both cases.

Logged in user - Privacy Policy link works:

![](http://g.recordit.co/55YVqp575h.gif)

Guest user - Privacy Policy link doesn't work:

![](http://g.recordit.co/7sFPVy7kfB.gif)

I also confirmed that it is not specific to 4.9 (the issue is present in 4.8 as well) therefore I am not assigning it a 4.9 milestone. 

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment] 2023-06-19 18:33
The current implementation of the checkout block does not have a link to the privacy policy.

**Closed by rrennick** 2023-06-19 18:33 UTC
Labels: type: bug, priority: low, focus: checkout [team:Proton], plugin: woocommerce
