### ISSUE TITLE
Variable products can be added with ajax to a shopping cart without choosing a variant

### ISSUE THREAD

**Issue by Marenu** [woocommerce/woocommerce#25116] opened 2019-11-26 15:36 UTC
**Describe the bug**
Variable products can be added with ajax to a shopping cart without choosing a variant

**To Reproduce**
Add a Variable Product with some variants (we have two variants)
Activate AJAX Shopping Card
Go to the product site
Click the disabled "Add to Card" Button
Confirm the Alert Message
After confirming the item will be added to the shopping cart

**Expected behavior**
Nothing should be added

We use WooCommerce 3.8.0 and WooCommerce Multilingual 4.7.4

**Comment by thomas-zg** [comment] 2019-11-26 15:52
I did the same, but after the message, the product wouldn't be added to the cart. WooCommerce 3.8 as well, Storefront theme.
Did you already try to disable all plugins except WooCommerce and repeat the test?

**Comment by Marenu** [comment] 2019-11-27 08:16
Unfortunately, I do not get any time for it, sorry :(

**Comment by juliaamosova** [comment] 2019-11-27 12:13
Thank you opening the issue @Marenu. However, it is not clear how to reproduce it. 

>Activate AJAX Shopping Card

Is it a plugin or an option that you can activate within WooCommerce?:

![ajax](https://user-images.githubusercontent.com/19143190/69722415-fc665280-110e-11ea-88fb-547da5e5bc76.jpg)

>Did you already try to disable all plugins except WooCommerce and repeat the test?

Thank you for jumping it and suggesting it @thomas-zg. @Marenu if you'd like us to work on this issue further, plugins and themes conflict will need to be done. Otherwise, we will be closing this issue especially if we can't reproduce it on our end. 

Please proceed with the theme and plugins conflict test and provide us with clear instructions on how to reproduce the issue as well as screenshots showing the error.

**Comment by juliaamosova** [comment] 2019-12-03 14:31
@Marenu I am closing this issue due to inactivity. Feel free to reopen it if you'd like us to take another look.

**Closed by juliaamosova** 2019-12-03 14:31 UTC
Labels: can't reproduce
