### ISSUE TITLE
Tax total is off based on number of decimals

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#24084] opened 2019-07-06 07:01 UTC
**Describe the bug**

2158195-zen

Number of decimals: 0
Tax: 10%

Order total is 270 (no tax). Logically, the tax total would be 27, which is what the user gets, but, on the order admin and frontend the item tax values are shown without decimals, and if you sum them the total is 25 instead of 27. This leads to misunderstandings because the total is 2$ more expensive than what they expected:

![](http://d.wedj.at/4JHinC+)
**Image Link**: http://d.wedj.at/4JHinC+

Settings the decimals back to 2 shows the correct tax values and the total now makes sense:

![](http://d.wedj.at/MwGXVt+)
**Image Link**: http://d.wedj.at/MwGXVt+

**To Reproduce**
1. Set number of decimals to 0
2. Create an order from admin with taxes including decimal values
3. Add 10%  tax rate to the order

**Expected behavior**
Not sure if this has to be considered a bug or not. The system is working as expected, but the fact that it does not show the decimals in the totals is misleading. Should it calculate based on the fact that there are no decimals (so total being 25 instead of 27), or show the decimals regardless of the settings for taxes?

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://test.nicola.blog
Site address (URL): https://test.nicola.blog
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.19
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wpu9_
MaxMind GeoIP Database: ✔
Total Database Size: 4.28MB
Database Data Size: 3.09MB
Database Index Size: 1.19MB
wpu9_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wpu9_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpu9_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpu9_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpu9_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpu9_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpu9_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpu9_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpu9_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpu9_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpu9_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpu9_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpu9_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpu9_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpu9_commentmeta: Data: 0.02MB + Index: 0.03MB
wpu9_comments: Data: 0.02MB + Index: 0.09MB
wpu9_links: Data: 0.02MB + Index: 0.02MB
wpu9_options: Data: 1.03MB + Index: 0.05MB
wpu9_postmeta: Data: 1.11MB + Index: 0.20MB
wpu9_posts: Data: 0.23MB + Index: 0.06MB
wpu9_termmeta: Data: 0.02MB + Index: 0.03MB
wpu9_terms: Data: 0.02MB + Index: 0.03MB
wpu9_term_relationships: Data: 0.02MB + Index: 0.02MB
wpu9_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpu9_usermeta: Data: 0.02MB + Index: 0.03MB
wpu9_users: Data: 0.02MB + Index: 0.05MB
wpu9_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wpu9_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wpu9_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wpu9_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wpu9_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpu9_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wpu9_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpu9_wpml_mails: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

attachment: 151
feedback: 5
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 5
page: 11
post: 52
product: 21
product_variation: 8
revision: 23
scheduled-action: 1
shop_order: 6
wc_booking: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Debug Bar: by wordpressdotorg – 1.0
Jetpack by WordPress.com: by Automattic – 7.5.1
Storefront Powerpack: by WooCommerce – 1.4.15
WooCommerce Bookings: by WooCommerce – 1.14.1
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.2.5
WooCommerce Stripe Gateway: by WooCommerce – 4.2.2
WooCommerce Product Add-ons: by WooCommerce – 3.0.11
WooCommerce: by Automattic – 3.6.5
WordPress Importer: by wordpressdotorg – 0.6.4
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Mail Logging: by Christian Zöller – 1.9.1

### Inactive Plugins (4) ###

WooCommerce Product Vendors: by WooCommerce – 2.1.16
WooCommerce Services: by Automattic – 1.21.0
WooCommerce Square: by WooCommerce – 1.0.37 – 1.0.38 is available
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.11 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2490 - /shop/
Cart: #376 - /cart-2/
Checkout: #377 - /checkout-2/
My account: #378 - /my-account-2/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.0 – 2.5.1 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Braintree (Credit Card) ###

Environment: Sandbox
Tokenization Enabled: –
Debug Mode: Display at Checkout & Log

### Action Scheduler ###

Complete: 0
Oldest: 2019-07-01 08:06:25 +0300
Newest: 2019-07-01 08:06:25 +0300

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by vedanshujain** [comment] 2019-09-03 15:30
@SiR-DanieL If you uncheck the setting `Round tax at subtotal level, instead of rounding per line ` in WooCommerce -> Settings -> Tax, then all the items should be rounded at the item level in which case expected and displayed total will match. If that setting is checked, then I guess the system is working as expected because we are rounding at the subtotal level.

Closing this issue now but will re-open if this setting is already unchecked, in which case we would need to investigate more.

**Comment by SiR-DanieL** [comment] 2019-09-04 05:30
I checked on my test site and that option is not selected

![](http://d.wedj.at/BTvkWB+)
**Image Link**: http://d.wedj.at/BTvkWB+

**Comment by juliaamosova** [comment] 2020-01-17 11:49
Hi @SiR-DanieL @vedanshujain,

I've been going over older bugs to triage as a part of the repo maintenance and came across this issue.

I tested it extensively with the following Tax Settings (same as in the original bug report):

![Screen Shot 2020-01-17 at 11 42 23 AM](https://user-images.githubusercontent.com/19143190/72610110-78fefb80-391e-11ea-930c-387d712fa94a.png)

I tested with both decimals set to 0 and 2 and the following WooCommerce versions:

- 3.6.5 (the version which was used in the bug report)
- 3.8.1 (current stable)
- 3.9 rc3 (latest RC)

In all the 3 versions the taxes are calculated the same on my end but different from what @SiR-DanieL reported. 

**With decimals set to `0`:**

Total tax comes up as $28:

![0](https://user-images.githubusercontent.com/19143190/72610330-f6c30700-391e-11ea-8bcc-fba0ad374067.jpg)

**With decimals set to `2`:**

Total tax comes up as $27:

![2](https://user-images.githubusercontent.com/19143190/72610339-fcb8e800-391e-11ea-8ff9-c98392e0c40a.jpg)

In both cases, the tax is calculated correctly in the context of the decimal settings but they are different depending on the decimal settings. 

I am not sure the total tax should be different but also if "we make tax to be the same in each case", I am not sure what is the correct way to display individual product's tax in order to make the calculation right.

**Comment by vedanshujain** [comment] 2020-01-20 11:46
@juliaamosova @SiR-DanieL I am also getting same results as Julia. 

We provide an option to make either subtotal tax accurate or individual line item tax total accurate via the option `Round tax at subtotal level, instead of rounding per line` in `WooCommerce -> Settings -> Tax`. 

For egs, when I enable rounding at subtotal, I get accurate tax of $27 even when decimals are set to 0:

![Screenshot 2020-01-20 at 5 16 02 PM](https://user-images.githubusercontent.com/7571618/72724164-947d3700-3ba8-11ea-8324-a4bac94a3e56.png)

**Comment by juliaamosova** [comment] 2020-01-20 17:21
@vedanshujain thanks for additional testing! 

I tested with decimals zero `0` using WC 3.9 rc-3:

I am getting the same results as you get if I enable `Round tax at subtotal level, instead of rounding per line` in `WooCommerce -> Settings -> Tax.` The total tax displayed is $27. My only issue with it is that 6 + 5 + 5 + 5 + 7 = 28 (not 27 as it gets displayed). 

![27](https://user-images.githubusercontent.com/19143190/72745764-6861b600-3ba8-11ea-96e5-49ba0ea2ba6c.jpg)

If I uncheck the box next to `Round tax at subtotal level, instead of rounding per line` in `WooCommerce -> Settings -> Tax.`, the total tax is $28. And the calculation is correct: 6 + 5 + 5 + 5 + 7 = 28:

![28](https://user-images.githubusercontent.com/19143190/72746041-05bcea00-3ba9-11ea-96dd-af54bb26ce40.jpg)

I don't know if there is a win here.

**Comment by vedanshujain** [comment] 2020-02-06 13:41
Closing in favor #23916 , root cause for both issues are same and they both will be addressed by one fix.

**Closed by vedanshujain** 2020-02-06 13:41 UTC
Labels: question
