### ISSUE TITLE
Change attribute name to more than 28 chars and attribute results in 404 page

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#25725] opened 2020-02-21 10:37 UTC
I have created a attribute name "test" with slug "test". Created Taxonomy within with name "testentry". Submitted attribute to product. Checked if attribute / taxonomy can be viewed /called in frontend. It works.

Now wnet back to attribute and changed name to longer than 28 chars. At saving I get a error that attribute name can not be longer than 28 chars. Attribute name is reset by WC back to before saved name. Change name of attribute to name shorter 28 chars and save.

Afterthan taxonomy of this this attribute can not any longer be called in frontend. Get always a 404 page.

**Comment by juliaamosova** [comment] 2020-02-24 22:20
Hi @ajgw,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported. Everything is working as expected on my end. Unless I took the wrong steps. Documenting below what I did:

1) Created an attributed called `test` and added `testentry` term to it:

![test1](https://user-images.githubusercontent.com/19143190/75196287-ab73f380-5729-11ea-9d0e-b20a035741d8.jpg)

2) Added attribute to the product and could view it:

![test2](https://user-images.githubusercontent.com/19143190/75196314-b9297900-5729-11ea-8996-79a33c05b65d.jpg)

3) Went back to the `Attributes` section and updated the attribute to something that is longer than 28 characters - was able to save it:

![test3](https://user-images.githubusercontent.com/19143190/75196375-d52d1a80-5729-11ea-9bc0-8ae2cb4a44d0.jpg)

4) Could view the product at the front-end:

![test4](https://user-images.githubusercontent.com/19143190/75196393-dfe7af80-5729-11ea-961c-72b029eb04dd.jpg)
 
Would you please confirm if these are the steps you took or am I missing something?

**Comment by ajgw** [comment] 2020-02-25 16:01
Well I tested it again. No other plugins except WC active. Now I had this bugs:

1. Created attribute "test2" with archive active and sorting by name
2. Created taxonomy "my taxonomy" in there
3. Created new product and save attribute with term in there
4. View product in frontend and click on term (which is linked) and get a 404 page. https://stage.dekuenst.de/test2/my-taxonomy/ can not found.

5. Went back to attribute and changed name to "test-two"
6. View product and click on term. Now I get that archive page.

7. Went back to attribute and changed name and slug to more than 28 chars.
8. Get error that slug can not be more than 28 chars. See image.
9. Save again. Slug is not resetted to last saved slug with less than 28 chars.
10. Well, you are right. Oh wonder, now I am able to call taxonomy term in frontend. Maybe it is related to a plugin which hooks in to there? I will test again.

But numbers are not allowed in attributes? I didn't saw this before.
![Bildschirmfoto 2020-02-25 um 16 56 42](https://user-images.githubusercontent.com/3390880/75264919-6c5ca580-57f0-11ea-8232-2dcddf8352c3.png)

**Comment by tammullen** [comment] 2021-03-25 19:53
Hi @ajgw 

Apologies for the delay in replying

The number of details you provided is not enough for us to work with and identify what could be going on.

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by ajgw** [comment] 2021-03-25 20:01
Hi Tam, I had that trouble but that was over a year ago. I don‘t know if bug exist in last version of wc. Sorry, but it is a bit late. Thanks. 


Adrian Wackernah

Atelier An der Mühle 
---
Phone 0151 2404 3961
An der Mühle 45
27570 Bremerhaven
https://atelier-an-der-muehle.de

**Comment by tammullen** [comment] 2021-03-26 12:43
Thanks @ajgw for the update, I'll close this for now but feel free to raise a new bug if you encounter something in the future.

**Closed by tammullen** 2021-03-26 12:43 UTC
Labels: needs feedback
