### ISSUE TITLE
Display attribute slug with attribute name in backend dropdown

### ISSUE THREAD

**Issue by lenamtl** [woocommerce/woocommerce#29476] opened 2021-03-24 13:14 UTC
Hi,

I have around 50 attributes called "Color" with different slug.
That would be very helpful to be able to see the attribute name + slug when adding the attribute to the product (in the admin backend)
As there are 50 color attribute into the list, it may be hard to find the appropriate one.
That is probably not something not commun but that could be an option to display it or not as it is possible to have multiple attribute that have the same name.

This is easy to do in PHP, I guess this can be easy to implement in WOO add product.
I'm new to WOO so if there is a quick way to implement this I would appreciate a snippet code.

Thanks

**Comment by tammullen** [comment] 2021-03-26 14:25
Hi @lenamtl 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-26 14:25 UTC
