### ISSUE TITLE
Error at checkout

### ISSUE THREAD

**Issue by simdanonline** [woocommerce/woocommerce#24872] opened 2019-10-19 14:46 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_update_order_review'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::update_order_review, woocommerce_order_review, wc_get_template, include('/plugins/woocommerce/templates/checkout/review-order.php'), do_action('woocommerce_review_order_before_cart_contents'), WP_Hook->do_action, WP_Hook->apply_filters, WC_CSP_Restrict_Payment_Gateways->excluded_payment_gateways_notice, WC_CSP_Restrict_Payment_Gateways->validate_checkout, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:45:54 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_update_order_review'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::update_order_review, woocommerce_order_review, wc_get_template, include('/plugins/woocommerce/templates/checkout/review-order.php'), do_action('woocommerce_review_order_before_cart_contents'), WP_Hook->do_action, WP_Hook->apply_filters, WC_CSP_Restrict_Shipping_Methods->excluded_shipping_methods_notice, WC_CSP_Restrict_Shipping_Methods->validate_checkout, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:45:54 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_update_order_review'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::update_order_review, woocommerce_order_review, wc_get_template, include('/plugins/woocommerce/templates/checkout/review-order.php'), do_action('woocommerce_review_order_before_cart_contents'), WP_Hook->do_action, WP_Hook->apply_filters, WC_CSP_Restrict_Shipping_Countries->excluded_country_notice, WC_CSP_Restrict_Shipping_Countries->check_restriction, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:45:54 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_update_order_review'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::update_order_review, woocommerce_checkout_payment, WC_Payment_Gateways->get_available_payment_gateways, apply_filters('woocommerce_available_payment_gateways'), WP_Hook->apply_filters, WC_CSP_Restrict_Payment_Gateways->exclude_payment_gateways, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:46:05 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->update_session, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, apply_filters('woocommerce_package_rates'), WP_Hook->apply_filters, WC_CSP_Restrict_Shipping_Methods->exclude_package_shipping_methods, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:46:05 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->validate_checkout, WC_Payment_Gateways->get_available_payment_gateways, apply_filters('woocommerce_available_payment_gateways'), WP_Hook->apply_filters, WC_CSP_Restrict_Payment_Gateways->exclude_payment_gateways, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:46:05 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->validate_checkout, do_action('woocommerce_after_checkout_validation'), WP_Hook->do_action, WP_Hook->apply_filters, WC_CSP_Restrictions->validate_checkout, WC_CSP_Restrict_Payment_Gateways->validate_checkout, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:46:05 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->validate_checkout, do_action('woocommerce_after_checkout_validation'), WP_Hook->do_action, WP_Hook->apply_filters, WC_CSP_Restrictions->validate_checkout, WC_CSP_Restrict_Shipping_Methods->validate_checkout, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:46:05 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->validate_checkout, do_action('woocommerce_after_checkout_validation'), WP_Hook->do_action, WP_Hook->apply_filters, WC_CSP_Restrictions->validate_checkout, WC_CSP_Restrict_Shipping_Countries->validate_checkout, WC_CSP_Restrict_Shipping_Countries->check_restriction, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:46:08 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->create_order, WC_Payment_Gateways->get_available_payment_gateways, apply_filters('woocommerce_available_payment_gateways'), WP_Hook->apply_filters, WC_CSP_Restrict_Payment_Gateways->exclude_payment_gateways, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[19-Oct-2019 08:46:14 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Payment_Gateways->get_available_payment_gateways, apply_filters('woocommerce_available_payment_gateways'), WP_Hook->apply_filters, WC_CSP_Restrict_Payment_Gateways->exclude_payment_gateways, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
```
</details>

**Comment by JohnTendik** [comment] 2019-10-19 16:48
```
WC_CSP_Restrictions->validate_checkout, WC_CSP_Restrict_Shipping_Countries->validate_checkout, WC_CSP_Restrict_Shipping_Countries->check_restriction, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
```

Does not seem like the issue is with WooCommerce. This is an error generated by a third party plugin.

**Comment by simdanonline** [comment] 2019-10-19 16:54
What plugin could that be?

**Comment by JohnTendik** [comment] 2019-10-19 16:55
'WC_CSP_Restrictions', so my guess is `Customer Specific Pricing for WooCommerce (CSP) plugin`

**Comment by simdanonline** [comment] 2019-10-19 16:58
I use woocommerce conditional payment and shipping extension.
Could it be it?

**Comment by JohnTendik** [comment] 2019-10-19 17:00
Yep, that's probably the one

**Comment by simdanonline** [comment] 2019-10-19 17:02
Do you suggest I delete it?

**Comment by JohnTendik** [comment] 2019-10-19 17:06
Is it outdated? I would try updating it first. 

If its already on the latest version, then I'd raise an ticket with the plugin developers.

**Comment by simdanonline** [comment] 2019-10-19 17:08
Okay thanks

**Comment by claudiosanches** [comment] 2019-10-23 21:54
Closing since it isn't a bug on WooCommerce, as @JohnTendik said, this issue comes from a 3rd party plugin.
Also, next time please fill all the issue template, this helps us a lot debugging things.

**Closed by claudiosanches** 2019-10-23 21:54 UTC
