### ISSUE TITLE
Orders placed with shipping address different from billing not displaying shipping address in different areas of WooCommerce

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce#26617] opened 2020-05-27 14:18 UTC
**Describe the bug**
When manually creating an order with both a billing and shipping address, only the billing address is visible in the order on the My Account page.

**To Reproduce**
1. Manually create an order, include both billing and shipping address (billing address not necessary)
2. After updated, navigate to the 'Orders' tab on the My Account page
3. Scroll down and see that only 'Billing Address' is visible: https://d.pr/i/zeuVRd

**Screenshots**
Order: https://d.pr/i/JRiBvX
Orders page: https://d.pr/i/zeuVRd

**Expected behavior**
If the 'Shipping Address' is filled in during order creation, it should be visible in the order on the My Account page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional Details**

Originally thought to be just a Subscriptions issue, asked to open issue here: https://github.com/woocommerce/woocommerce-subscriptions/issues/3695

The issue seems to be with `wc_ship_to_billing_address_only()` here: https://github.com/woocommerce/woocommerce/blob/master/templates/order/order-details-customer.php#L20
When removed, the 'Shipping Address' is displayed as expected.

**Comment by jrick1229** [comment] 2020-05-27 14:22
Reported in: 3007565-zen

**Comment by juliaamosova** [comment] 2020-05-27 14:49
Hi @jrick1229,

Thanks for reporting! I could reproduce it but not only with manual orders but with orders placed directly by customers on the site. 

The shipping address is not being displayed in the following areas of WooCommerce:

- My Account / Orders / Order view
- Thank you for your order page
- Email received by the customer after the order had been placed
- Email received by the store owner after the order had been placed

Screenshots below:

Order placed by the customer on the site has a billing address (Miami) and shipping address (New York):

![a1](https://user-images.githubusercontent.com/19143190/83035310-49b47580-a007-11ea-9928-75e1fd291e83.jpg)

- My Account / Orders / Order view:

![a2](https://user-images.githubusercontent.com/19143190/83035350-5507a100-a007-11ea-9535-5c5ffd58516e.jpg)

- Thank you for your order page:

![a3](https://user-images.githubusercontent.com/19143190/83035373-5df87280-a007-11ea-97f0-6d11c7b772f8.jpg)

- Email received by the customer after the order had been placed:

![a5](https://user-images.githubusercontent.com/19143190/83035411-6a7ccb00-a007-11ea-870b-d890701ff585.jpg)

- Email received by the store owner after the order had been placed:

![a4](https://user-images.githubusercontent.com/19143190/83035439-749ec980-a007-11ea-9b04-225ab3538584.jpg)

I tested all the way up to WC 3.7 and it didn't work there as well. I am making it a `high` priority as I think this is a pretty basic flow that should work. 

Also, I am changing the title of the issue to reflect that it happens not only on manual orders but on all orders.

**Comment by jrick1229** [comment] 2020-05-27 15:04
@juliaamosova - Thanks! Just to note, if manually creating the order, the shipping address does not need to differ from the billing address. From what I could tell, it seems that even if the addresses match when manually creating the order, they are still assumed to be different.

**Comment by peterfabian** [comment] 2020-07-15 14:07
Hi, 

looking at the code now, the shipping address is only displayed if:
- Shipping destination is NOT set to Force shipping to the customer billing address, and
- Shipping method is set to sth else than `Local pickup`

If removing `wc_ship_to_billing_address_only()` call helps, I think it means that `Shipping destination` is set to `Force shipping to the customer billing address`. There is no filter in the function and it directly compares the value of option `woocommerce_ship_to_destination` to `billing_only`, so I don't think there could be something else at play.

![Screenshot 2020-07-15 at 15 46 28](https://user-images.githubusercontent.com/2207451/87554941-101df380-c6b5-11ea-8cf4-b960cffb1a29.png)


Please see how this works for me and let me know if it works for you differently:
https://www.youtube.com/watch?v=Zsa5hQi7YVs

**Comment by juliaamosova** [comment] 2020-08-06 21:33
@peterfabian thanks for investigating here. I confirm that the shipping address is not visible only if:

- Shipping destination is NOT set to Force shipping to the customer billing address, and
- Shipping method is set to sth else than Local pickup

Which makes sense to me. I tested both creating the order manually and at the front end. 

Screenshots in my [comment above](https://github.com/woocommerce/woocommerce/issues/26617#issuecomment-634713185) show no shipping address because my shipping method is `Local Pickup` - it is translated to Russian on the screenshots (was testing translations). 

All and all, it looks like there is nothing else for us to do here and we should leave the way it works as-is. What do you think @jrick1229?

**Comment by KoolPal** [comment] 2020-08-07 05:34
@juliaamosova @peterfabian Is there some filter / code snippet which can be used to FORCE display of Shipping Address in ALL circumstances?

Thanks

**Comment by tammullen** [comment] 2020-10-21 16:09
Adding this is still occuring for manually created orders in 4.7 but not for orders placed on front end.

The Shipping Details are not appearing for manual orders on

- Confirmation after Shopper's Payment Page
- Order Details in Shopper's My Account
- Shopper's Order Email
- Merchant's New Order Email
- Order Preview for Merchant in All Orders Screen

![Screenshot 2020-10-21 at 16 48 17](https://user-images.githubusercontent.com/24649833/96746232-e0bb0900-13be-11eb-8260-d222fd2d99ee.png)

![Screenshot_2020-10-21_at_16_50_05](https://user-images.githubusercontent.com/24649833/96746271-e9134400-13be-11eb-8a33-69ad63eb705e.png)

![Screenshot_2020-10-21_at_16_49_18](https://user-images.githubusercontent.com/24649833/96746324-f7616000-13be-11eb-94ce-63b3d61f31d7.png)

![Screenshot_2020-10-21_at_17_03_08](https://user-images.githubusercontent.com/24649833/96747012-b61d8000-13bf-11eb-9f82-5b5292265f80.png)

![Screenshot_2020-10-21_at_17_07_33](https://user-images.githubusercontent.com/24649833/96747315-085ea100-13c0-11eb-97b0-3cad1a15ccb1.png)


![Screenshot_2020-10-21_at_16_49_31](https://user-images.githubusercontent.com/24649833/96746349-fdefd780-13be-11eb-93c8-bdd9c6006736.png)

![Screenshot_2020-10-21_at_16_49_51](https://user-images.githubusercontent.com/24649833/96746374-047e4f00-13bf-11eb-9072-6b837febb5da.png)

![Screenshot_2020-10-21_at_16_48_44](https://user-images.githubusercontent.com/24649833/96746408-0e07b700-13bf-11eb-9ec6-42ec19db52b5.png)

![Screenshot_2020-10-21_at_16_48_55](https://user-images.githubusercontent.com/24649833/96746435-13fd9800-13bf-11eb-95bb-984785743e6a.png)

![Screenshot_2020-10-21_at_16_49_39](https://user-images.githubusercontent.com/24649833/96746457-195ae280-13bf-11eb-864a-5d2f02967075.png)

![Screenshot_2020-10-21_at_17_02_50](https://user-images.githubusercontent.com/24649833/96747041-bb7aca80-13bf-11eb-9435-bbd62376d21a.png)

![Screenshot_2020-10-21_at_17_06_31](https://user-images.githubusercontent.com/24649833/96747366-18768080-13c0-11eb-8f15-f1945442831b.png)

**Comment by rodrigoprimo** [comment] 2020-12-05 17:53
> Adding this is still occuring for manually created orders in 4.7 but not for orders placed on front end.

@tammullen, when manually creating an order in wp-admin, did you add a shipping item to select the shipping method? This is required for WooCommerce to consider that the order will be shipped and to show the shipping details in the places that you mentioned. Just adding a shipping address is not enough.

Everything seems to be working as expected to me if I add a shipping item when manually creating an order and thus I suggest we close this issue. What do you think @tammullen and @juliaamosova?

**Comment by vedanshujain** [comment] 2021-02-15 14:07
Closing the issue based on above comments. But please feel free to comment back in case I have missed something and this issue still needs further discussion.

**Closed by vedanshujain** 2021-02-15 14:07 UTC
Labels: component: shipping, has feedback, priority: high, type: bug

**Comment by jenniNCA** [comment] 2023-05-16 08:44
Hi, I'm finding this issue with subscriptions renewals and because the shipping info isn't being correctly filled on invoices it's not sending orders to my postage provider so I have to manually create shipping labels, The Shipping info appears as in the above screenshots but not in preview - is there a way to force shipping info to always be displayed? Thanks
