### ISSUE TITLE
infinite loop with do_shortcode

### ISSUE THREAD

**Issue by Victorlerner** [woocommerce/woocommerce#22785] opened 2019-02-20 17:59 UTC
**Describe the bug**

in file \woocommerce\includes\class-wc-structured-data.php
I found  bug in this code 
line 114
```
	$markup['description'] = wpautop( do_shortcode( $product->get_short_description() ? $product->get_short_description() : $product->get_description() ) );
		$markup['sku']         = $product->get_sku();


```
if you make product via WP shortcodes, and in this shortcode you will be use this 

`<?php do_action( 'woocommerce_single_product_summary' ); ?>
`
 and use the_content() to do_shortcode() this you will get an infinite loop.
so you need to remove do_shortcode from this line code 

**Screenshots**
http://prntscr.com/mnskzd

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
last version
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment] 2019-02-26 13:00
The steps to reproduce an issue are unclear. I don't see an issue with that line:

- structured data does not generate for shortcodes
- running do_shortcode is required because `get_short_description` does not formatting

To test, I added a product_page shortcode to a regular page. No infinite loop occured.

If you can provide better instructions for reproducing this please go ahead. In the meantime, I'm marking this as closed/invalid.

**Closed by mikejolley** 2019-02-26 13:00 UTC

**Comment by Victorlerner** [comment] 2019-02-28 08:37
in woocommerce\content-single-product.php put this code 

```
<?php
/**
 * The template for displaying product content in the single-product.php template
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/content-single-product.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see     https://docs.woocommerce.com/document/template-structure/
 * @package WooCommerce/Templates
 * @version 3.4.0
 */

defined( 'ABSPATH' ) || exit;
global $product;
?>

<div class="container">
	<?php do_action( 'woocommerce_before_single_product' );
	?>
</div>


<div class="pr-vi">
	<?php

	the_content(get_the_ID());


	?>
</div>


<div class="holder">
    <div class="container">
        <?php  woocommerce_output_related_products(); ?>
    </div>
</div>


<?php do_action( 'woocommerce_after_single_product' ); ?>

```

now make the new shortcode 

```
add_shortcode( 'single_product', 'single_product_function' );

function goodwin_single_product_function( $atts ) {
	$atts = shortcode_atts(
		array(
			'title' => '',
			'css' => '',
			'items' => '',
			'section_id' => '',
			'promo' => '',

		), $atts
	);
	$css_class = apply_filters( VC_SHORTCODE_CUSTOM_CSS_FILTER_TAG, vc_shortcode_custom_css_class( $atts['css'], ' ' ), '', $atts );

	ob_start();
	?>

					<?php do_action( 'woocommerce_single_product_summary' ); ?>
				


	<?php
	return ob_get_clean();
}



```
now in product page delete short_description.
must be $product->get_short_description()  == false

then it will work  do_shortcode(  $product->get_description());
and now you will get infinite loop  

```
$markup['description'] = wpautop( do_shortcode( $product->get_short_description() ? $product->get_short_description() : **$product->get_description()** ) );
		$markup['sku']         = $product->get_sku();

```
This is a very critical mistake when themes are made based on shortcodes.

**Comment by mikejolley** [comment] 2019-02-28 09:33
It's still not clear. e.g. you're saying `$product->get_description()` causes it - does it contain shortcodes in the content in your use case?

**Comment by Victorlerner** [comment] 2019-02-28 10:13
in your code if 
` $product->get_short_description() == false 
` then you run this code
` do_shortcode($product->get_description()) 
`
so clear Product short description 
http://prntscr.com/mr9fn6

and in description put this shortcode
http://prntscr.com/mr9g0p
[single_product]

and you will see this bug

**Comment by Victorlerner** [comment] 2019-02-28 10:19
you need to add a new product to get this bug 
and here you can see php log
https://pastecode.xyz/view/66cffaec

**Comment by Victorlerner** [comment] 2019-02-28 10:22
PHP Fatal error:  Maximum function nesting level of '256' reached,

**Comment by mikejolley** [comment] 2019-02-28 12:05
Ok but this bug is not due to WooCommerce. This bug is because you're including that description within your custom shortcode which in turn calls description. Descriptionception. Products within products. Surely thats the problem here? Why would you show a product within a product like that?

**Comment by Victorlerner** [comment] 2019-02-28 12:50
I'm telling you what you need to be able to make a **single product from shortcodes.**
and you just need to delete in file \woocommerce\includes\class-wc-structured-data.php
do_shortcode 

like this 

```
$markup['description'] = wpautop( ( $product->get_short_description() ? $product->get_short_description() : $product->get_description() ) );
		$markup['sku']         = $product->get_sku();
```

this is a very big bug in WooCommerce


With this bug, you can not create professional themes that are built on shortcodes

**Comment by mikejolley** [comment] 2019-02-28 13:14
**This is not a solution because users who need shortcodes to render there will see breakage.**

**Comment by Victorlerner** [comment] 2019-02-28 13:18
you need to find another way.
but there should not be an infinite loop.
and follow the codex WordPress they use the_content()  in single.php and don't do hardcode

**Comment by mikejolley** [comment] 2019-02-28 13:36
the_content() also calls do_shortcode which would also break from your usage above.

**Comment by Victorlerner** [comment] 2019-02-28 19:09
Mark this as bugs and find a solution that will suit everyone.
and code in 
\woocommerce\includes\class-wc-structured-data.php does not have logic. a programmer can use the_content() in any file instead of that dumb code.

as well as an option to make a filter through which I could disable the execution of this code

**Comment by mikejolley** [comment] 2019-03-01 10:07
> and follow the codex WordPress they use the_content() in single.php and don't do hardcode

My point is, even if this was done, in your use case you would see infinite loop. This is a design flaw in your shortcode!

**Comment by Victorlerner** [comment] 2019-03-01 12:56
once again I’m talking, developers do all theme, so give them the option to turn it off.
can just add there variable $disable_do_shortcode = false;
Then I can via functions.php and add_filter make this variable true

**Comment by mikejolley** [comment] 2019-03-01 18:08
Or deregister your shortcode before calling the content?

**Comment by Victorlerner** [comment] 2019-03-01 19:04
I have already said what needs to be doneю now we use for this hack

**Comment by mikejolley** [comment] 2019-03-04 13:32
Adding a niche argument like that is also hacky.

The issue is the way you're handling the shortcodes. You're calling an action that itself runs shortcodes, so of course there is an infinite loop. This would be the case if calling `the_content()` manually, even without using WooCommerce.

The shortcode is flawed. There are workarounds you can add to your shortcode callback to prevent the loop. The main one being to deregister your shortcode at the top of your function, and re-register it at the bottom of your function. That will prevent just your shortcode being called infinitely.

**Comment by Victorlerner** [comment] 2019-03-04 16:21
it doesn't work. if I don't need this feature, why can't I disable it? you must do WP 'filter' for this and all

**Comment by mikejolley** [comment] 2019-03-04 16:22
Why not submit a PR for what you're looking for? If it's not a total hack we can consider it.

As I said however, the usage you describe is flawed and would fail with any type of content which already contains shortcodes.

**Comment by soft79** [comment] 2019-03-08 20:18
@Victorlerner, what result do you expect from [single_product] in your example? And what is the use case?
