### ISSUE TITLE
WOO 3.6.5 HAVE A ERROR TO IMPORT CSV. In Woo 3.6.4 work correctly.

### ISSUE THREAD

**Issue by Uranolibros** [woocommerce/woocommerce#24126] opened 2019-07-11 12:29 UTC
Greetings team. I wanted to inform, that after updating Woo 3.6.5. The importer of CSV or TXT. It fails, it does not load correctly and it does not go to the next step, which is to review the fields to be imported. Instead I did a rollback to Woo 3.6.4, and it works properly for me. AFTER VIEWING YOUR FIXED, I HAVE SEEN THAT YOU HAVE TOUCHED, THE PART OF IMPORT CSV. I hope this problem can be solved.

### WordPress Environment ###

WordPress address (URL): https://www.libreriaurano.com
Site address (URL): https://www.libreriaurano.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

Examples pictures
1) https://drive.google.com/open?id=1rco7yt9g2lVfwwHZioqzYzwFR5s96r6L
2) https://drive.google.com/open?id=1QAil3L_rtLd1SLrFzLzW0WsqrT-Winzq
3) https://drive.google.com/open?id=1Rlp9we7sW-20TzX22nv4jC5CdeW2InZ0

Thx, and see you soon. :-)

**Comment by rodrigoprimo** [comment] 2019-07-17 17:30
Hi, I was not able to reproduce this issue. The importer is working on my local WooCommerce install using the [sample_products.csv](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv) file.

Closing this issue for now. If you are still experiencing this issue, could you please share the file that you are trying to import and the exact error that you are getting? Thanks.

**Closed by rodrigoprimo** 2019-07-17 17:30 UTC
