### ISSUE TITLE
Confirmation of order email to site not right (3.3.5)

### ISSUE THREAD

**Issue by chocoladeverkopers** [woocommerce/woocommerce#19991] opened 2018-05-07 20:10 UTC
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ 0] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Upgrade to 3.3.5
2. Order. 
3. Check confirmation email to owner (customer email is fine)

I tried to disable as many plugins as i could and reproduce. However i'm working on a live site and haven't got the time to make a copy on which i can do good tests (reproduce steps, disable all, go back to old version) so i couldnt actually do proper testing, i could do if needed in the next days.

## Expected/actual behavior

When I follow those steps, I see... After update to 3.3.5 Email confirmation subject send to website owner is as follows "[{site_title}] Nieuwe bestelling ({order_number}) – {order_date}" . Confirmations to customers are per usual "[Chocoladeverkopers] Nieuwe bestelling (2794) – 7 mei 2018"

I was expecting to see...Email confirmation subject as follows "[Chocoladeverkopers] Nieuwe bestelling (2794) – 7 mei 2018"

## Isolating the problem

- [ 0] This bug happens with only WooCommerce plugin active 
- [0 ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

Could not deactive all plugins on my live website. Could test if needed in next days.

## WordPress Environment

<details>

4.9.5
--
```
`
### WordPress Environment ###

Home URL: https://chocoladeverkopers.nl
Site URL: https://chocoladeverkopers.nl/chocolade
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.16
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
Totale databasegrootte: 136.62MB
Database datagrootte: 108.01MB
Database index grootte: 28.61MB
wp_woocommerce_sessions: Data: 34.14MB + Index: 0.25MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.23MB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 4.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.08MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_aws_index: Data: 5.50MB + Index: 0.00MB
wp_chained_choices: Data: 0.02MB + Index: 0.00MB
wp_chained_completed: Data: 0.02MB + Index: 0.00MB
wp_chained_questions: Data: 0.02MB + Index: 0.00MB
wp_chained_quizzes: Data: 0.02MB + Index: 0.00MB
wp_chained_results: Data: 0.02MB + Index: 0.00MB
wp_chained_user_answers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 2.52MB + Index: 1.69MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.09MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 4.52MB + Index: 6.55MB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB
wp_icl_string_pages: Data: 2.52MB + Index: 1.52MB
wp_icl_string_positions: Data: 0.48MB + Index: 0.13MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 2.52MB + Index: 0.48MB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 1.52MB + Index: 0.06MB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp_icl_translations: Data: 0.41MB + Index: 0.81MB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Data: 1.52MB + Index: 0.06MB
wp_icwp_wpsf_ip_lists: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_reporting: Data: 0.05MB + Index: 0.00MB
wp_icwp_wpsf_sessions: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_statistics: Data: 0.02MB + Index: 0.00MB
wp_idealcheckout: Data: 0.25MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 5.38MB + Index: 0.41MB
wp_postmeta: Data: 15.55MB + Index: 8.03MB
wp_posts: Data: 19.52MB + Index: 2.36MB
wp_responsive_menu: Data: 0.02MB + Index: 0.00MB
wp_sm_advanced_search_temp: Data: 0.13MB + Index: 0.00MB
wp_termmeta: Data: 0.06MB + Index: 0.06MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.27MB + Index: 0.16MB
wp_term_taxonomy: Data: 0.17MB + Index: 0.03MB
wp_usermeta: Data: 2.52MB + Index: 0.83MB
wp_users: Data: 0.08MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_webwinkelkeur_invite_error: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.17MB + Index: 0.06MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

amn_mi-lite: 1
attachment: 2208
custom_css: 2
customize_changeset: 12
ditty_news_ticker: 5
mc4wp-form: 2
nav_menu_item: 118
oembed_cache: 5
page: 62
post: 120
product: 634
product_variation: 15
revision: 2675
shop_coupon: 37
shop_order: 1642
shop_order_refund: 35
sidebar: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Schildbeveiliging: door One Dollar Plugin – 6.6.8
WPML Multilingual CMS: door OnTheGoSystems – 3.9.4
Advanced Woo Search: door ILLID – 1.40
Breadcrumb NavXT: door John Havlik – 6.0.4
Contact Form 7: door Takayuki Miyoshi – 5.0.1
Cookie Law Info: door Richard Ashby – 1.5.3
Custom Facebook Feed: door Smash Balloon – 2.5.1
Custom Related Products for WooCommerce: door Scott Nelle – 1.3 – Niet getest met de actieve versie van WooCommerce
Enhanced E-commerce for Woocommerce store: door Tatvic – 2.0.1 – Niet getest met de actieve versie van WooCommerce
Limit Login Attempts: door Johan Eenfeldt – 1.7.1
MailChimp for WordPress: door ibericode – 4.2
Mollie Payments for WooCommerce: door Mollie – 2.9.0
Optimus: door KeyCDN – 1.4.9
OTF Regenerate Thumbnails: door Benjamin Intal - Gambit Technologies Inc – 0.3
Responsive menu: door Peter Featherstone – 3.1.13
WC Restore the Purchased Items Column in Orders Page: door Rynaldo Stoltz – 1.2
Simple 301 Redirects: door Scott Nellé – 1.07
Page Builder by SiteOrigin: door SiteOrigin – 2.4.24
Smart Manager: door StoreApps – 3.16.1
Comprimeer JPEG & PNG afbeeldingen: door TinyPNG – 2.2.6
W3 Total Cache: door Frederick Townes – 0.9.7
WooCommerce Waitlist: door XootiX – 1.4 – Niet getest met de actieve versie van WooCommerce
Fietskoeriers.nl: door Fietskoeriers.nl – 1.1.5 – Niet getest met de actieve versie van WooCommerce
WebwinkelKeur: door Albert Peschar – 1.6.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Cart Tab: door jameskoster – 0.5.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Colors: door WooThemes – 1.0.7 – Niet getest met de actieve versie van WooCommerce
WooCommerce Multilingual: door OnTheGoSystems – 4.2.10
WooCommerce MyParcel: door Richard Perdaan – 2.4.11 – Niet getest met de actieve versie van WooCommerce
WooCommerce Sequential Order Numbers: door SkyVerge – 1.8.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce: door Automattic – 3.3.5
WooSidebars: door WooThemes – 1.4.3
Yoast SEO: door Team Yoast – 7.2
WPML Media: door OnTheGoSystems – 2.2.3
WPML String Translation: door OnTheGoSystems – 2.7.3
WPML Translation Management: door OnTheGoSystems – 2.5.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-en)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #7247 - /chocolade/
Winkelmand: #350 - /winkelmand/
Afrekenen: #352 - /checkout/
Mijn account: #354 - /my-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Estore Child
Version: 1.0
Author URL: http://themegrill.com
Child Theme: ✔
Parent Theme Name: eStore
Parent Theme Version: 1.2.4 – 1.2.5 is beschikbaar
Parent Theme Author URL: https://www.themegrill.com
WooCommerce Support: ✔

### Templates ###

Overrides: estore/woocommerce/archive-product.php
estore/woocommerce/cart/cart-totals.php
estore/woocommerce/cart/cross-sells.php
estore/woocommerce/checkout/form-billing.php
estore/woocommerce/checkout/form-checkout.php
estore/woocommerce/checkout/form-login.php
estore/woocommerce/content-product.php
estore/woocommerce/content-single-product.php
estore/woocommerce/global/wrapper-end.php
estore/woocommerce/global/wrapper-start.php
estore/woocommerce/loop/add-to-cart.php
estore/woocommerce/loop/price.php
estore/woocommerce/loop/rating.php
estore/woocommerce/single-product/price.php
estore/woocommerce/single-product/related.php
estore/woocommerce/single-product.php
estore/woocommerce/taxonomy-product_cat.php

`
```
</details>

**Comment by claudiosanches** [comment] 2018-05-07 21:13
I couldn't have any success following the steps to reproduce this issue, every time works just fine.
Probably related to some plugin or customization on your store.
Closing since not it's not possible to reproduce with only WooCommerce installed.

**Closed by claudiosanches** 2018-05-07 21:13 UTC
