### ISSUE TITLE
[products category="category-1, category-2"] shortcode only shows products from the first category

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#24626] opened 2019-09-12 22:33 UTC
**Describe the bug**
A shortcode like [products category="category-1, category-2"] only shows products from the first category. 

In this support document it is indicated that such shortcode can have `category` as an attribute: "Comma separated list of category slugs."

https://docs.woocommerce.com/document/woocommerce-shortcodes/#display-product-attributes

But comma separating multiple categories doesn't work, categories starting the second one are ignored.

A workaround is to use the `products by category` shortcode:

![Screenshot](https://cld.wthms.co/rc0PNq+)
Screenshot direct link: https://cld.wthms.co/rc0PNq

**To Reproduce**
1. Create two product categories with products in them, category-1 and category-2 for example.
2. Use shortcode [products category="category-1, category-2"] on a page.
3. Only products from the first category will be displayed.

**Screenshots**

![Screenshot](https://cld.wthms.co/7Nqv6I+)
Screenshot direct link: https://cld.wthms.co/7Nqv6I

**Expected behavior**
Products from all comma separated categories should show up according to the documentation.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://x.mystagingwebsite.com
Site address (URL): https://x.mystagingwebsite.com
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.22
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.65.3
OpenSSL/1.1.0k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 36.28MB
Database Data Size: 23.97MB
Database Index Size: 12.31MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.45MB + Index: 0.42MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
$table: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpstg0_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpstg0_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg0_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_geodir_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_geodir_countries: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpstg0_geodir_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_geodir_custom_sort_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_geodir_gd_place_detail: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_geodir_post_icon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_geodir_post_review: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_options: Data: 0.41MB + Index: 0.06MB + Engine InnoDB
wpstg0_postmeta: Data: 1.52MB + Index: 0.81MB + Engine InnoDB
wpstg0_posts: Data: 0.34MB + Index: 0.06MB + Engine InnoDB
wpstg0_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpstg0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bp_activity: Data: 0.02MB + Index: 0.16MB + Engine InnoDB
wp_bp_activity_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.42MB + Index: 0.47MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_geodir_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_geodir_countries: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_geodir_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_geodir_custom_sort_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_geodir_gd_place_detail: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_geodir_post_icon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_geodir_post_review: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.39MB + Index: 0.19MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 5.52MB + Index: 4.03MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 0.44MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_am_api_activation: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_am_api_resource: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_am_associated_api_key: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_am_secure_hash: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 0.17MB + Index: 0.30MB + Engine InnoDB
wp_wps_key: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Jetpack by WordPress.com: by Automattic – 7.7.1
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0

### Inactive Plugins (0) ###

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
deposit (deposit)
external (external)
grouped (grouped)
mix-and-match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #211383 - /shop-2/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #156 - /gd-info/

### Theme ###

Name: Bistro
Version: 1.0.12
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 229
Oldest: 2019-08-13 10:02:04 +0000
Newest: 2019-09-12 22:13:01 +0000

Pending: 5
Oldest: 2019-09-12 23:13:01 +0000
Newest: 2019-09-16 08:49:01 +0000

Canceled: 6
Oldest: 2019-08-20 07:15:43 +0000
Newest: 2019-09-09 06:44:41 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 20
Oldest: 2018-09-24 12:52:03 +0000
Newest: 2019-05-20 16:11:11 +0000

`
```
</details>

**Comment by akshaya-rane** [comment] 2019-10-20 18:29
This Bug is not reproducible.

**Comment by claudiosanches** [comment] 2019-10-25 15:20
Not able to reproduce this issue, also the `[product_category]` is the same thing as using `[products category=""]`, but the first one should be removed one day from WooCommerce.
Closing since is working with WooCommerce 3.8.

**Closed by claudiosanches** 2019-10-25 15:20 UTC
Labels: bug, priority: low

**Comment by bjornweb** [comment] 2020-05-21 07:52
Maybe not the right place, but I had exactly the same problem.
In my case the plugin "WooCommerce Product Search" is causing this behavior... It's hard to find because WOO does product_query caching, so make sure you change the shortcode categories after disabling plugins and test again.

The problem
Plugin "WooCommerce Product Search" adds the first category as an extra separate 'tax_query'.
With 'relation' set to 'AND' only products from the first category are returned.

Not very happy with this plugin ATM.....
