### ISSUE TITLE
Product Data is only showing the general table, does not change when clicking on the left tabs 

### ISSUE THREAD

**Issue by Jon-Rojas** [woocommerce/woocommerce#28228] opened 2020-11-10 17:04 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I would like to update the prices for my products

**Expected behavior**
If i click on the left tabs, I expect the middle part to change to configure my product

**Actual behavior**
If I click on the left tabs, it stays the same. Is there anyone that can help

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**
If you click on tabs, nothing in the middle changes

![image](https://user-images.githubusercontent.com/64081527/98706322-b79df080-234c-11eb-9e1a-d5d70baadc8d.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-11-13 19:13
Hi @Jon-Rojas,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested using WooCommerce 4.7:

![](http://g.recordit.co/6UdlUtB2yJ.gif)

Can you please confirm if you tested your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by tammullen** [comment] 2020-11-23 12:41
Hi @Jon-Rojas 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2020-11-23 12:41 UTC
Labels: can't reproduce, status: needs feedback
