### ISSUE TITLE
Problema na página minha conta no woocommerce (erro 404)

### ISSUE THREAD

**Issue by Mylaine-programadora** [woocommerce/woocommerce#27501] opened 2020-08-27 11:41 UTC
Bom dia!

Estou com um problema na página minha conta no woocommerce, acontece que o link está encaminhando para uma página não existente.

Ao invés de aparecer /minha-conta aparece /?page-id7 (que não existe)

Verifiquei o código e está correto o encaminhamento.

Todos os plugins estão atualizados e são compatíveis.

**Comment by tammullen** [comment] 2020-08-27 19:11
Hi @Mylaine-programadora 

Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

> Good Morning!
> 
> I have a problem with my account page on woocommerce, it happens that the link is leading to a non-existent page.
> 
> Instead of appearing / my-account appears /? Page-id7 (which does not exist)
> 
> I checked the code and the routing is correct.
> 
> All plugins are up to date and compatible.
> 


While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Can you check your page settings in WooCommerce > Settings > Advanced. 
More info on that is here https://docs.woocommerce.com/document/configuring-woocommerce-settings/#section-24​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-08-27 19:11 UTC
