### ISSUE TITLE
Shipping Wildcards not fully inclusive when used in a range

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#27015] opened 2020-07-10 17:51 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using shipping restriction wildcards in combination of a range, the upper limit of the range does not accept wildcard values other than `0`.

**Expected behavior**
You should be able to pass any valid character for the wildcard, even if that puts you at the top of the range.

**Actual behavior**
You will only match the range if you pass `0` in the position of the wildcard at the top of your range.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Set up a shipping zone with a zip code restriction
2. Set the zip code restriction to be `123*...456*`
3. At checkout enter in `4567`
4. Note that you do not match the shipping zone
5. Enter in the zipcode `4560`
6. Note that you now match the shipping zone

**Screenshots**

Shipping zone Settings:

![](https://d.pr/i/FesoaU+)
Image Link: https://d.pr/i/FesoaU

Checkout page when using a `0` as your wildcard digit

![](https://d.pr/i/67a1S3+)
Image Link: https://d.pr/i/67a1S3

Checkout page when using any other character as your wildcard digit

![](https://d.pr/i/Hgz8ms+)
Image Link: https://d.pr/i/Hgz8ms

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://wcstax.mystagingwebsite.com
Site address (URL): https://wcstax.mystagingwebsite.com
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.19
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.70.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Total Database Size: 2.93MB
Database Data Size: 1.46MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_email_log: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.33MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
customize_changeset: 1
page: 8
post: 1
product: 18
product_variation: 11
revision: 8
shop_order: 4
wcpf_item: 7
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.3.0

### Inactive Plugins (10) ###

Akismet Anti-Spam: by Automattic – 4.1.6
ARI Adminer: by ARI Soft – 1.2.3
Email Log: by Sudar – 2.3.2
Jetpack by WordPress.com: by Automattic – 8.7
Product Filters for WooCommerce: by WooCommerce – 1.2.1 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Bankart Payment Gateway Extension: by Bankart – 1.7.3.1 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.19 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Pre-Orders: by WooCommerce – 1.5.26 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Services: by Automattic – 1.23.2 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.7 (update to version 2.5.8 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 24
Oldest: 2020-06-10 15:26:28 +0000
Newest: 2020-07-10 17:50:43 +0000

Pending: 1
Oldest: 2020-07-11 17:26:05 +0000
Newest: 2020-07-11 17:26:05 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-07-15 21:56
Hi @FreshPhil,

Thank you for taking the time to report this bug and providing clear steps to reproduce, we really appreciate your help. I am getting the same results using the steps to replicate you provided. 

It seems a `low` priority bug to me and rather an edge-case. However, please feel free to correct me and we can evaluate the priority further. 

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by aheckler** [comment] 2021-07-25 15:02
User in 30802784-hc ran into this. Their UK zone was restricted like so: `KW15*...KW17*`, but that meant anything starting with `KW17` would not match when it should. Workaround for this is to just duplicate the last post code on its own line, like so:

```
KW15*...KW17*
KW17*
```

This lets it match as well, until this bug is fixed.

**Comment by spadeshoe** [comment] 2022-04-10 11:18
@aheckler Thanks for the workaround. I had the same issue with US zip codes. Copying the last number in the range to a new line worked. Additional, only one * is required even for a 5 digit zip codes. This seems strange, but ** does not work on single line, but it works in a range. ie: in 376**...379**, 376** would work, but 242** would fail. 

242*
307*
373*...374*
374*
376*...379*
379*
407*...409*
409*
417*...418*
418*
425*...426*
426*

Thank y'all for the hard work on WooCommerce!

**Comment by jvwrx** [comment] 2023-05-02 07:14
Experiencing this issue as well when trying to allow customers to enter their address in the USPS' "ZIP+4" format.

For example, in my zone region it seems like `90000*...93599*` should match both my zip code _92703_ and the +4 version _92703-4822_ but it only matches _92703-4822_. In order to catch both my range needs to be:

`90000*...93599*`
`93599*`

**Comment by rrennick** [comment] 2023-10-30 22:49
> For example, in my zone region it seems like 90000*...93599* should match both my zip code 92703 and the +4 version 92703-4822 but it only matches 92703-4822.

The description below the `zone regions` field iis:

> Postal codes containing wildcards (e.g. CB23*) or fully numeric ranges (e.g. 90210...99000) are also supported.

The key word there is `OR`. Wildcards in ranges is not supported. For example, the way to do the above is

```
90000...93599
90000-0000...93599-9999
```

Closing this as a question.

**Closed by rrennick** 2023-10-30 22:49 UTC
Labels: type: bug, priority: low, focus: shipping [team:Escargot], plugin: woocommerce
