### ISSUE TITLE
Lock the same day for all products woocommerce booking

### ISSUE THREAD

**Issue by ronnyvm35** [woocommerce/woocommerce#30316] opened 2021-07-19 21:42 UTC
Saludos, ¿alguno sabe como bloquear un dia en el calendario para todos los productos en woocommerce-booking?
la empresa solo puede brindar un evento(productos) al día, pero la plataforma permite reservar multiples eventos(productos) para el mismo día

Greetings, does anyone know how to block a day in the calendar for all products in woocommerce-booking?
the company can only provide one event (products) per day, but the platform allows multiple events (products) to be booked for the same day
![2021-07-19_15-11-04](https://user-images.githubusercontent.com/24706438/126231283-8c64982f-8396-4e67-a965-1fbf878ef6d1.png)

**Comment by tammullen** [comment] 2021-07-20 10:20
Hi @ronnyvm35 ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-07-20 10:20 UTC
