### ISSUE TITLE
Orders w/ Custom Statuses not Showing in Admin > Orders

### ISSUE THREAD

**Issue by jamacon36** [woocommerce/woocommerce#26203] opened 2020-04-16 20:41 UTC
Using a fresh install of WooCommerce 4.0.1 on WordPress 5.4 (just updated from 5.3) with a custom theme I've created a set of custom order statuses with `register_post_status`. 

In wp_admin I am seeing orders with default statuses but none with my custom statuses. However, orders with custom statuses are being counted towards the `All` value:
<img width="952" alt="Screen Shot 2020-04-16 at 4 27 02 PM" src="https://user-images.githubusercontent.com/4700339/79503671-8dc35c00-7fff-11ea-84a2-2059a776adcd.png">

As well as appearing in reports:
<img width="952" alt="Screen Shot 2020-04-16 at 4 33 58 PM" src="https://user-images.githubusercontent.com/4700339/79504114-4ab5b880-8000-11ea-9317-fcecd246b393.png">

Clicking into the order detail from the report yields a working order detail with the following notice:
```
Notice:  map_meta_cap was called incorrectly.
The post status quote-requested is not registered, so it may not be reliable
to check the capability "read_post" against a post with that status... 
```

I've added a set of custom order statuses with the following code:
```php
class Storefront
{
  // Make & Add order status to array custom_order_statuses
  function make_order_status($name, $comesafter, $editable = false) {
    $status =  new \StdClass;
    $status->name = $name;
    $slug = str_replace(' ', '-', $name);
    $slug = strtolower($slug);
    $status->slug = 'wc-' . $slug;
    $status->preceeded_by = $comesafter;
    $status->editable = $editable;

    $this->custom_order_statuses[] = $status;
  }

  // Create Order statuses in WC
  function add_custom_order_statuses_to_wc() {
    $statuses = $this->custom_order_statuses;
    foreach($statuses as $status) {
      $args = array(
        'label' => _x( $status->name, 'Order status', 'textdomain' ),
        'public' => true,
        'exclude_from_search' => false,
        'show_in_admin_all_list' => true,
        'show_in_admin_status_list' => true,
        'label_count' => _n_noop($status->name . '<span class="count">(%s)</span>', $status->name . '<span class="count">(%s)</span>')
      );

      register_post_status($status->slug, $args);
    }
  }

  // Add custom order statuses to Admin Order Menu
  function add_custom_order_statuses_to_menu($order_statuses) {
    $new_order_statuses = array();
    
    // Run through order statuses
    foreach ($order_statuses as $key => $status) {
      $new_order_statuses[$key] = $status;
      if (!empty($this->custom_order_statuses)) {
        foreach($this->custom_order_statuses as $new_status) {
          if ($new_status->preceeded_by == $key) {
            $new_order_statuses[$new_status->slug] = $new_status->name;
          }
        }
      }
    }

    return $new_order_statuses;
  }

  // Make Custom Order Statuses Editable
  function check_status_editable ($editable, $order) {
    if (!empty($this->custom_order_statuses)) {
      foreach ($this->custom_order_statuses as $status) {
        if ($status->editable && 'wc-' . $order->get_status() == $status->slug) {
          $editable = true;
        }
      }
    }
    return $editable;
  }

// More code...

function __construct() {
    $this->custom_order_statuses = [];
    $this->make_order_status('Quote Requested', 'wc-pending', true);
    $this->make_order_status('Quote Sent', 'wc-processing', true);

    add_action('init', [$this, 'add_custom_order_statuses_to_wc']);
    add_filter('wc_order_statuses', [$this, 'add_custom_order_statuses_to_menu']);
    add_filter('wc_order_is_editable', [$this, 'check_status_editable'], 10, 2);
  }
}
```
In `functions.php`
```php
new Storefront();
```

I'd expect and have seen orders with custom statuses to appear here in the past.

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] I can reproduce this bug consistently using the steps above.

Any ideas?

**Comment by jamacon36** [comment] 2020-04-21 13:12
Update with system report: 

```
### WordPress Environment ###

WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ❌ To allow logging
make /opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 5.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.14
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.18
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 49.93MB
Database Data Size: 35.38MB
Database Index Size: 14.55MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.27MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.27MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 8.50MB + Index: 0.23MB + Engine InnoDB
wp_postmeta: Data: 15.52MB + Index: 8.03MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 1.25MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_term_taxonomy: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_termmeta: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_terms: Data: 1.52MB + Index: 0.98MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.42MB + Index: 0.56MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wrc_caches: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wrc_relations: Data: 0.05MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

acf-field: 103
acf-field-group: 13
attachment: 1269
distributor: 34
nav_menu_item: 18
page: 23
post: 85
product: 355
product_variation: 3345
revision: 107
shop_coupon: 1
shop_order: 42

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

S3 Uploads: by Human Made Limited – 2.1.0-RC2
ACF to REST API: by Aires Gonçalves – 3.2.0
Advanced Custom Fields PRO: by Elliot Condon – 5.8.9
Classic Editor: by WordPress Contributors – 1.5
Deploy with NetlifyPress: by Nahid Ferdous Mohit – 1.1.0
WP Sheet Editor - WooCommerce Products (Premium): by WP Sheet Editor – 1.4.2
WooCommerce USA ePay Gateway: by WooThemes / SkyVerge – 1.7.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 4.0.1
WordPress Importer: by wordpressdotorg – 0.7
WP Mail SMTP: by WPForms – 1.9.0
WP REST Cache: by Acato – 2020.1.1

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

WP REST Cache - Must-Use Plugin: by Richard Korthuis - Acato – 2018.2.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #11 - /shop-products/
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 621
Oldest: 2020-03-21 09:25:56 -0400
Newest: 2020-04-21 09:10:20 -0400

Pending: 2
Oldest: 2020-04-21 10:10:20 -0400
Newest: 2020-09-13 08:53:12 -0400

```
Thanks!

**Comment by juliaamosova** [comment] 2020-05-06 19:32
Hi @jamacon36,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

Alternatively, we have an extension that allows creating custom order statuses: [https://woocommerce.com/products/woocommerce-order-status-manager/](WooCommerce Order Status Manager).

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Comment by PaulCityhopper** [comment] 2021-01-08 15:19
This isnt custom related. Why do you close this issue if its still there?
A Plugin for just a simple thing like a order status? LOL!

**Comment by PaulCityhopper** [comment] 2021-01-08 16:51
I found out that...

on register_post_status (only for WooCommerce!)

**Works Not**
wc-shipment-back-to-client
wc-waiting-repair-shipment
wc-wait-repair-shipment
wc-wait-repairshipment
wc-waitrepairshipment
wc-repair-shipment
wc-shipment-back-to-client

**Works**
wc-repair-shipment
wc-quo-shipment
wc-client-shipment
wc-repair-processing
wc-repair-done
wc-waiting-answer
wc-test
wc-paid

**Comment by juliaamosova** [comment] 2021-01-08 18:27
Reopening this issue so we could take a look further.

**Comment by Konamiman** [comment] 2021-01-21 10:59
Hi @jamacon36, thanks for your report. I haven't been able to reproduce the issue on my end, I'm using your example code verbatim and that's what I get after I change the status of two of the existing orders in my local setup:

![image](https://user-images.githubusercontent.com/937723/105341837-de479580-5bdf-11eb-8e1a-3385af4dd2c6.png)

The total count is correct as well since it was already the same number before I altered the orders.

This is a quite old report (sorry for the late reply by the way) and quite a few versions of WooCommerce have been relased meanwhile. Could you please confirm if you are still experiencing the issue with the most recent version?

**Comment by ArnoutPullen** [comment] 2021-03-02 17:59
I had the same issue with version 4.2 and just upgraded to 5.0 and after running the database update it was visible again!

**Comment by juliaamosova** [comment] 2021-03-19 23:25
Hi @jamacon36,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-03-19 23:25 UTC
Labels: needs feedback

**Comment by alisamie97** [comment] 2021-11-05 08:05
im having the issue. i copied all your code. but i think its a database problem. am i right?
