### ISSUE TITLE
Composer package `woocommerce/woocommerce` fails to install

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/woocommerce#28399] opened 2020-11-25 04:22 UTC
@Konamiman

- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Composer package `woocommerce/woocommerce` fails to install

**Expected behavior**
Have WC installed.

**Actual behavior**

```
$ composer --version
Composer version 1.10.16 2020-10-24 09:55:59

$ composer require woocommerce/woocommerce:4.7.0
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing automattic/jetpack-autoloader (v2.2.0): Loading from cache
  - Installing composer/installers (v1.7.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing league/container (3.3.3): Loading from cache
  - Installing woocommerce/woocommerce-blocks (v3.6.0): Loading from cache
  - Installing woocommerce/woocommerce-admin (1.6.3): Loading from cache
  - Installing woocommerce/action-scheduler (3.1.6): Loading from cache
  - Installing symfony/css-selector (v5.1.8): Loading from cache
  - Installing pelago/emogrifier (v3.1.0): Loading from cache
  - Installing maxmind-db/reader (v1.6.0): Loading from cache
  - Installing automattic/jetpack-constants (v1.5.0): Loading from cache
  - Installing woocommerce/woocommerce (4.7.0): Loading from cache
maxmind-db/reader suggests installing ext-bcmath (bcmath or gmp is required for decoding larger integers with the pure PHP decoder)
maxmind-db/reader suggests installing ext-maxminddb (A C-based database decoder that provides significantly faster lookups)
Writing lock file
Generating autoload files

Installation failed, deleting ./composer.json.


  [RuntimeException]
  Could not scan for classes inside "/home/viktor/src/MyPackages/php-stubs/woo-test/wp-content/plugins/woocommerce/vendor/league/container" which does not appear to be a file nor a folder


require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. `composer require woocommerce/woocommerce:4.7.0`
1. See the error message: `Could not scan for classes inside "./wp-content/plugins/woocommerce/vendor/league/container" which does not appear to be a file nor a folder`

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by szepeviktor** [comment] 2020-11-25 04:23
My diagnosis shows: the Mozart-way of putting libs under WC namespace is in master but not in tag `4.7.*`.

**Comment by szepeviktor** [comment] 2020-11-25 04:26
@claudiosanches Could it be a release problem?

**Comment by samholguin** [comment] 2020-11-25 11:14
Same issue

**Comment by Konamiman** [comment] 2020-11-25 11:20
Hi, this is a known problem caused by the reintroduction of the dependency injection container and the changing of its namespace via a `prefix-vendor-namespaces.sh` script in 4.7. This issue will disappear with the release of 4.9 thanks to https://github.com/woocommerce/woocommerce/pull/28147.

**Comment by rrennick** [comment] 2020-11-25 18:24
@Konamiman Can we close this as addressed in #28147 ?

**Comment by szepeviktor** [comment] 2020-11-25 18:46
...addressed but not actually released ❕

**Comment by claudiosanches** [comment] 2020-11-25 18:49
Hello @szepeviktor 

> Diagnosis shows: the Mozart-way of putting libs under WC namespace is in master but not in tags 4.7.*.

Yes, because this fix is planned for 4.9.

**Comment by szepeviktor** [comment] 2020-11-25 18:58
This is issue is about _will_.

I think talking does not help.
As of the current state of WC 4.7 and 4.8 releases on Packagist will be broken.

> Could not scan for classes inside "./wp-content/plugins/woocommerce/vendor/league/container" which does not appear to be a file nor a folder

**Comment by AlexP11223** [comment] 2020-12-02 14:55
duplicates https://github.com/woocommerce/woocommerce/issues/28320

**Closed** 2020-12-02 16:16 UTC
Labels: status: needs developer feedback

**Comment by janpjens** [comment] 2020-12-07 08:55
Any possibility for an interim release to patch this so packagist version is not broken, or is 4.9 the next installable version via composer, @claudiosanches?
