### ISSUE TITLE
Fatal error after change of thumbnail setting

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#18589] opened 2018-01-25 08:59 UTC
After I changed thumbnail setting of product images to leave to original sizes in background a cronjob started and after few minutes whole server stopped responding. Support at provider had to restart cron process before all my domains were back online.

In fatal-errors log of WC I do find only this line few times

`2018-01-23T19:19:48+00:00 CRITICAL Maximum execution time of 30 seconds exceeded`

Errorlog of server wrote this down:

`[Wed Jan 24 18:45:33 2018] [error] [client xx] FastCGI: server "/usr/share/cgi-fpm/xx/php70-fpm" stderr: PHP message: PHP Fatal error: Maximum execution time of 30 seconds exceeded in /www/htdocs/xx/stage.mydomain.de/wp-includes/class-wp-image-editor-imagick.php on line 342, referer: https://stage.mydomain.de/wp-cron.php?doing_wp_cron=1516815924.0091989040374755859375
[Wed Jan 24 19:01:09 2018] [error] [client xx] FastCGI: comm with server "/usr/share/cgi-fpm/xx/php70-fpm" aborted: idle timeout (600 sec), referer: https://stage.mydomain.de/wp-admin/admin.php?page=wc-settings&tab=germanized`

I am a bit lost. WP 4.9.2, WC 3.3 RC1, few WC extensions activated. It seems that image regenerating in background with cron stops whole server responding. I am not able to solve this as I am not aware if this is a server configuration issue or a WC issue.

**Comment by SorinGFS** [comment] 2018-01-25 10:13
@ajgw Yep, I think they forgot that woocommerce is a plugin, not a theme! There are so many scenarios where this chage will be in conflict with the theme or even with some image processing plugins. In your particular case I think disabling imagick extension from php will "solve" the problem

**Comment by mikejolley** [comment] 2018-01-25 11:24
@SorinGFS This really isn't helpful.

**Comment by kloon** [comment] 2018-01-25 12:05
@ajgw From the looks it seems the issue is not caused by a WooCommerce function but a WordPress core one. It seems the issue happens when this function is called withing WordPress https://github.com/WordPress/WordPress/blob/4.9.2/wp-includes/class-wp-image-editor-imagick.php#L288, more specifically when it tries to run the sampleimage function https://github.com/WordPress/WordPress/blob/4.9.2/wp-includes/class-wp-image-editor-imagick.php#L342

It would be helpful for us to look into this further if we can perhaps get a proper traceroute, your host should be able to enable that for you. And also if we can get details about your hosting provider so we can try and recreate this.

Have you tried to upload a featured image on a post to see if you run into any issue there as that uses the same functionality we use?

**Comment by ajgw** [comment] 2018-01-25 12:15
@kloon Please understand that I am not willing to test this on my rented server anymore, as the whole server – all domains on my dedicated & managed server stopped responding after that. I had uninstall WC 3.3 RC1 and support had to restart cron process for getting my domains up and run.

My hoster is all-inkl.com in germany. They are very helpful.

They answered me about this issue: they were able to mark the wp-cron.php as reason and they found, that this process ran out of max execution time but without finishing it. Instead the queue was left open which results in a never ending job. Process was new started til all slots were in use.

**Comment by kloon** [comment] 2018-01-25 12:25
The queues are driven by the wp cron, default behaviour is that when a timeout is detected it will continue processing the where it got terminated in a new run.

Also the main queue will spawn seperate jobs for each image in batches of 10 I believe, you will never have more than 10 jobs running at the same time.

Digging a bit deeper it may seem that you might have an extraordinary large image somewhere in your library and that is taking too long to process when the sampling is done through WordPress core.

I appreciate that you have come here to open up an issue but we will definitely need more debugging since we are unable to recreate the issue on our end.

**Comment by adrianlbs** [comment] 2018-01-25 13:14
+1 / Same goes here, same error, we just couldn't figure out yet if it's a certain image that breaks it or something like that. We are currently monitoring the server and will get back if we have some insight.

**Comment by kloon** [comment] 2018-01-25 13:17
Thanks @adrianlbs, can you perhaps post your logs for the image-resize log? Can be found under WooCommerce->System Status->logs and selecting the image-resize log option, from there we should be able to which image did not complete.

Also on which hosting provider are you and what plan so we can try and recreate this and patch.

**Comment by ajgw** [comment] 2018-01-25 13:17
@kloon 
I have checked which Image could be the reason: 270 images as jpgs are uploaded, the largest size is 198.8 kB. All of them have rights of 644. Only one PNG file is there which is site logo and transparent.

Few Images have very long names: 
bremerhaven-am-schlepperanleger-2014-adrian-j-g-wackernah-000505.jpg
which expands after thumbnailcreation to 
bremerhaven-am-schlepperanleger-nassplatte-2014-adrian-j-g-wackernah-000506-150x150.jpg

Server runs PHP 7.0.25-nmm1, WP Memory Limit: 256 MB

What else do you need?

**Comment by ajgw** [comment] 2018-01-25 13:19
Perhaps, checking how many images are recreated yesterday as server stops responding happens: 203 images and all have same date and time: 01-24-2018 @ 18:50

**Comment by adrianlbs** [comment] 2018-01-25 13:34
@kloon I cannot replicate it right now so the WooCommerce logs are clean, but I can share what I am seeing in the log viewer from a few days ago [log.txt](https://github.com/woocommerce/woocommerce/files/1664133/log.txt).

We're on MediaTemple's VPS Hosting, DV W/SSDS (CENTOS 7) - LEVEL 1.

**Comment by kloon** [comment] 2018-01-25 13:36
OK thanks, will try and investigate a bit and see what I can come up with to remedy this.

**Comment by mikejolley** [comment] 2018-01-25 15:07
@adrianlbs @ajgw Testing https://github.com/woocommerce/woocommerce/pull/18597 would be welcome.

**Comment by adrianlbs** [comment] 2018-01-25 15:16
OK, sure.

**Comment by kloon** [comment] 2018-01-26 12:06
Mike and I did a bunch of testing and troubleshooting, and also discovered https://core.trac.wordpress.org/ticket/36534

It seems this issue is related to a bug in certain versions of ImageMagick and OpenMP and there is not much we can do to resolve this apart from setting an evironment variable, which is not always supported by all hosts.

We are also busy working on making the background processing library a bit smarter as when it timed out, it basically re-queued all the tasks in a batch which was causing an infinite loop.

**Comment by mikejolley** [comment] 2018-01-26 15:10
See https://github.com/woocommerce/woocommerce/pull/18604

**Closed by mikejolley** 2018-01-26 15:10 UTC
Labels: Status: Needs Author Feedback, Status: has-pr

**Comment by mikejolley** [comment] 2018-01-26 19:08
Rc2 has a patch to split the requests up  and avoid timeouts.

**Comment by ajgw** [comment] 2018-01-26 19:09
Thanks Mike – I will test it again.
