### ISSUE TITLE
Variable Products No Longer Showing In Stock Quantity on WP-ADMIN

### ISSUE THREAD

**Issue by joanne-21** [woocommerce/woocommerce#29853] opened 2021-05-07 10:07 UTC
May I know is there a code to show the stock quantity for products that have variation in admin site?
The stock quantity for products that do not have variation is shown.

**Comment by tammullen** [comment] 2021-05-09 10:25
Hi @joanne-21 
For a variable product with manage stock enabled for it’s variations showing a single stock level would be misleading as some could be negative, some positive, some managed, and some unmanaged etc. This is why it isn’t displayed here. (It is displayed if you choose to only manage stock at a product level).

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-05-09 10:25 UTC
