### ISSUE TITLE
Woocommerce slowdown with many attributes

### ISSUE THREAD

**Issue by coolos17** [woocommerce/woocommerce#20262] opened 2018-05-27 10:14 UTC
**Describe the bug**
If shop has many product attributes it's became unresponsive. 

For one of my client I created shop based on WC with around 5000 of products and many product attributes (around 30-50 per product). Shop was very slow and unresponsive (tested on many webhosts including dedicated servers and local servers). TTFB response time was huge, around 20s in product categories in default storefront theme.

I fix this performance problem by adding filter:
`add_filter( 'woocommerce_attribute_taxonomies', 'remove_slowdowns_caused_by_taxonomies', 10, 1);
function remove_slowdowns_caused_by_taxonomies($attribute_taxonomies){
return array();
}
`

**To Reproduce**
add around 3000-4000 products with many attributes (around 30-50 per product) 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Please fix this in the next releases

**Comment by mikejolley** [comment] 2018-05-29 10:29
The snippet above just disables attribute taxonomies. Thats not a fix - it will break the taxonomy system.

**Comment by coolos17** [comment] 2018-05-30 07:46
@kloon I am using woocommerce products attributes as global attributes, but not add them from admin panel, I added this from my code (I need global attributes to filter products).

About object cache you mean APC or Memcached module? I have Memcached on my server installed and this not change anything on clean Wordpress + Woocommerce instalation. I used even w3total cache, but this not solved my performance issues (I tried different configurations with database and object caching).

I have question, this cached taxonomies in the database are stored in the "_transient_wc_attribute_taxonomies" key in the wp_options table right? I have this value fully filled. Column "value" is defined as longtext and serilized data has only 656322 characters, so this not should be a problem.

@mikejolley yes, I know this, this is simple fix to only improve performance but this not solve my problem. I have in this function more logic and page is usable but I know this is not a good solution, thats why I am writing here :)

**Comment by mikejolley** [comment] 2018-06-04 11:39
@coolos17 Can you provide is with an export of your products so we can test them directly?

**Comment by RistoNiinemets** [comment] 2018-06-10 17:17
I can confirm this issue. With my case there are 15 000 simple products with up to 80 attributes per product (generally about 30) and all of them are taxonomies, as every attribute (potentially) could be used for filtering. All of the products are being imported from external sources continuously.

I've been fighting with the performance issue and found out that, 

1) post_class() function in WP slows things really down, as it tries to add all post related taxonomies as classes.
2) For postmeta or termmeta, each product is constructed and read_attributes() is called, which reads product attributes in. I've implemented a custom product data store, which reads in the attributes only on the products single view:
```php
class WC_My_Custom_Product_Data_Store extends WC_Product_Data_Store_CPT implements WC_Object_Data_Store_Interface, WC_Product_Data_Store_Interface
{
	protected function read_attributes( &$product )
	{
		if ( ! is_admin() && is_singular( 'product' ) && get_the_ID() == $product->get_id() )
		{
			parent::read_attributes( $product );
		}
	}
}
```
So far I haven't found any side-effects. Also disabling termmeta and postmeta cache update when it was possible.

**Comment by henriquemattos** [comment] 2018-06-11 11:52
My case is very similar if not the same reported by @coolos17. I have around 900+ products each with around ~35 attributes/variations. The website is just an ecommmerce, no blog/posts and only 8 pages. The `wp_posts` table gets around 45.000+ records and the `wp_postmeta` around 2.2 million+.

I also have the same experience of around ~20 seconds for each request being processed by the webserver (including SQL queries).

I currently have a db.t2.medium in AWS RDS with MariaDB (it was MySQL but I wanted to give MariaDB a try and solve this issue but same performance persists) and a c5.large in AWS EC2. Content is cached using W3 Total Cache using a cache.t2.small in AWS ElastiCache and static/media is dropped from CloudFront+S3.

My last resource at this moment is to try the fix suggested pointed by @RistoNiinemets in Slack in [here](https://core.trac.wordpress.org/ticket/33885) and [here](https://mariadb.atlassian.net/browse/MDEV-8872) which recommends that we change the `meta_key` length from 255 to *191*, the same size used for the index key.

I shall update once I get this tested properly.

Kindly regards,
Henrique Mattos

**Comment by rodrigoprimo** [comment] 2018-06-13 19:13
> TTFB response time was huge, around 20s in product categories in default storefront theme.

@coolos17, I'm assuming the majority of the 20 seconds were spent in the database. If that is the case, could you please share the slowest queries and the time they took to execute (cc @henriquemattos as you also mentioned slow page load time)? You can get this information in MySQL slow query log or using the WP plugin query-monitor.

As Mike mentioned, could you please share an export of your products so we can test them directly (cc @RistoNiinemets and @henriquemattos as you mentioned you experienced similar problems in a WC install with a significant number of products and attributes)? It is better to debug this kind of issues with real data. On a quick look, I wasn't able to identify exactly where is the issue that you are having.

If you don't feel comfortable sharing your products publicly, you can send it to us via e-mail (our e-mails can be found in our GitHub profiles).

> I have question, this cached taxonomies in the database are stored in the "_transient_wc_attribute_taxonomies" key in the wp_options table right?

WordPress will use `wp_options` to store transients only if an external object cache is not configured. So, if your install is storing the transient `wc_attribute_taxonomies` in `wp_options` that is a sign that Memcached is not available on your server or WP is not configured to use it. Could you please check? For sites with a lot of data and/or heavy traffic, an external object cache is fundamental.

> post_class() function in WP slows things really down, as it tries to add all post related taxonomies as classes.

@RistoNiinemets, this is a known issue, and https://github.com/woocommerce/woocommerce/pull/19639, which is part of WC 3.4.0, fixed it. You might have to update your templates to use `wc_get_product_class()` or `wc_product_class()` instead of `post_class()`. Please let me know if the problem persists or if it is not related to the problem described in the PR that I mentioned.

> @rodrigoprimo Do you think these could be lazy loaded?

@mikejolley, not sure if I understand exactly what you mean and, anyway, I prefer to wait until I have a better understanding of what is the issue before trying potential solutions. I suggest we wait to see if we can get a product export of one of the installs where this issue is happening to test.

**Comment by coolos17** [comment] 2018-06-13 21:21
@mikejolley ok I will export data from the webshop.

@rodrigoprimo  nope, as I remember, MySQL queries takes around one second - long but as I said TTFB was around 20s.

About memcached, it's working properly on the server, but I not configured it with wordpress/woocommerce natively - only in the W3TC plugin, but this not solved my problem

**Comment by henriquemattos** [comment] 2018-06-14 12:11
Hi, @rodrigoprimo . Thanks for the opportunity but I lost the client. They (extremely impressive) moved to another hosting and to Magento. I do still have their database export files but I'm not allowed to share it anymore. I'm sorry. 

But lately I realized that although they had 900+ products with ~35 attributes/variations, they also had around 100 completed orders per month (maybe around 180 general orders) which also generates a lot of meta data in _postmeta_. Although the performance issue existed in single product page, the database was not only about products but also orders and meta data in general.

I hope I can provide more (or useful) information, but the database export I will be in debt. Sorry.

Kindly regards,
Henrique Mattos

**Comment by rodrigoprimo** [comment] 2018-06-14 20:37
@RistoNiinemets kindly shared a copy of his database (thanks again!) and I imported it into my local environment. Below I will share what I have found so far in case anyone has any ideas or suggestions.

After playing a bit with @RistoNiinemets' database, I created a new database, imported WC sample products and added 2000 product attributes using the code below:

```
$ wp shell
>>> global $wpdb
>>> $i = 1;
>>> while ( $i <= 2000 ) {
    $wpdb->insert(
        $wpdb->prefix . 'woocommerce_attribute_taxonomies',
        array( 'attribute_label' => 'test' . $i, 'attribute_name' => 'test' . $i, 'attribute_type' => 'select', 'attribute_orderby' => 'menu_order', 'attribute_public'  => 1 ),
        array( '%s', '%s', '%s', '%s', '%d' )
    );
    $i++;
}
>>> do_action( 'woocommerce_flush_rewrite_rules' );
>>> delete_transient( 'wc_attribute_taxonomies' );
```

With 2000 product attributes, the performance of my test site was severely impacted. Using the shop page as an example, the page generation time jumped from 0.6s to 2.6s and memory peak usage jumped from 8MB to 34MB. Database query time and the number of queries executed was not significantly impacted by this change.

Enabling an external object cache had no effect in decreasing generation time or memory usage (I used Memcached and the [Simple Cache](https://wordpress.org/plugins/simple-cache/) plugin to test).

I then used Xdebug profiling and Kcachegrind to check where PHP was spending time load to the shop page. About 50% of the page generation time was spent inside `WC_Post_Types::register_taxonomies()`, specifically in this loop: https://github.com/woocommerce/woocommerce/blob/0599c06b20a6fd38547588d25f2e3c43a6d4503a/includes/class-wc-post-types.php#L200

This code is executed in every single WP page to register all taxonomies that WC uses including product attributes. On a first look, I'm not sure what we could do to improve this part of the code.

Another 25% of the page generation time, was spent inside [WC_Query::get_layered_nav_chosen_attributes()](https://github.com/woocommerce/woocommerce/blob/f356269e6fd2e53b1d803d5e7cd146151be68049/includes/class-wc-query.php#L758). I haven't had much time to investigate this part yet, but we might be able to improve the logic of this method and get rid of the loop over all product attributes.

The remaining 25% look like "normal" WP and WC routines. I will discuss with @mikejolley what do to next.

>  I do still have their database export files but I'm not allowed to share it anymore. I'm sorry.

No worries, @henriquemattos. Thanks anyway.

**Comment by rodrigoprimo** [comment] 2018-06-15 10:57
@mikejolley suggested that I tested registering the same number of taxonomies outside of WooCommerce on a clean WordPress install. I added the code below adapted from `WC_Post_Types::register_taxonomies()` to `wp-content/themes/twentyseventeen/functions.php` and got similar results. Database query time and the number of queries is not affected, but page generation time jumped from 0.6s to 5.5s and memory peak usage jumped from 23MB to 42MB. Next I will see if there is something in WP that we can disable or improve and if not I'm afraid we might have to close this as won't fix and document. Please let me know if you have other suggestions.

```
add_action( 'init', function() {
	$permalinks['attribute_rewrite_slug'] = '';

	foreach ( range( 1, 2000 ) as $i ) {
		$name = "test{$i}";

		if ( $name ) {
			$attribute_public = 1;
			$label            = $name;
			$taxonomy_data    = array(
				'hierarchical'          => false,
				'update_count_callback' => '_update_post_term_count',
				'labels'                => array(
					/* translators: %s: attribute name */
					'name'              => sprintf( _x( 'Product %s', 'Product Attribute', 'woocommerce' ), $label ),
					'singular_name'     => $label,
					/* translators: %s: attribute name */
					'search_items'      => sprintf( __( 'Search %s', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'all_items'         => sprintf( __( 'All %s', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'parent_item'       => sprintf( __( 'Parent %s', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'parent_item_colon' => sprintf( __( 'Parent %s:', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'edit_item'         => sprintf( __( 'Edit %s', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'update_item'       => sprintf( __( 'Update %s', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'add_new_item'      => sprintf( __( 'Add new %s', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'new_item_name'     => sprintf( __( 'New %s', 'woocommerce' ), $label ),
					/* translators: %s: attribute name */
					'not_found'         => sprintf( __( 'No &quot;%s&quot; found', 'woocommerce' ), $label ),
				),
				'show_ui'               => true,
				'show_in_quick_edit'    => false,
				'show_in_menu'          => false,
				'meta_box_cb'           => false,
				'query_var'             => 1 === $attribute_public,
				'rewrite'               => false,
				'sort'                  => false,
				'public'                => 1 === $attribute_public,
				'show_in_nav_menus'     => 1 === $attribute_public && apply_filters( 'woocommerce_attribute_show_in_nav_menus', false, $name ),
				'capabilities'          => array(
					'manage_terms' => 'manage_product_terms',
					'edit_terms'   => 'edit_product_terms',
					'delete_terms' => 'delete_product_terms',
					'assign_terms' => 'assign_product_terms',
				),
			);

			if ( 1 === $attribute_public && sanitize_title( $name ) ) {
				$taxonomy_data['rewrite'] = array(
					'slug'         => trailingslashit( $permalinks['attribute_rewrite_slug'] ) . sanitize_title( $name ),
					'with_front'   => false,
					'hierarchical' => true,
				);
			}

			register_taxonomy( $name, apply_filters( "woocommerce_taxonomy_objects_{$name}", array( 'product' ) ), apply_filters( "woocommerce_taxonomy_args_{$name}", $taxonomy_data ) );
		}
	}
} );
```

**Comment by rodrigoprimo** [comment] 2018-06-15 17:53
PR #20549 should reduce the slowdown when running a WC store with a significant number of product attributes. It changes WC_Query::get_layered_nav_chosen_attributes() to stop looping over all product attributes. But it doesn't address the main issue that I have identified which is registering all product attributes in `WC_Post_Types::register_taxonomies()`. I'm not sure if there is anything with can do to improve this part of the code and I'm open to suggestions.

**Comment by mikejolley** [comment] 2018-06-28 13:47
https://github.com/woocommerce/woocommerce/pull/20549 has been merged for 3.5. It will provide some improvements.

@rodrigoprimo if the other slowdown is caused by WP, we should close - we cannot optimise WP taxonomies in WC.

**Comment by mikejolley** [comment] 2018-06-29 10:19
For anyone finding this, if you do find this try to use global taxonomies only for attributes which span multiple product types. e.g. a good example would be size or color. Lots of products will have same attributes.

If it's something specific to a single product, sticking to custom text attributes will be faster. Those do not use WordPress taxonomies and thus won't cause slowdown when they are registered.

**Closed by mikejolley** 2018-06-29 10:19 UTC
Labels: performance, status: needs feedback

**Comment by noamtahan** [comment] 2018-11-14 13:45
@mikejolley Hi,
I have problem to create product with variation of all attributes,
Its very very slowly.
Can I send you access to my site?
Thanks a Lot.

**Comment by hirschgeweyh** [comment] 2019-11-27 08:22
> @rodrigoprimo Do you think these could be lazy loaded?

No, because the taxonomies and classes must be loaded before anything else to compile the HTML. Lazy Load is perfect for images but not for such cases.

**Comment by Bodrosh** [comment] 2020-11-27 12:41
@rodrigoprimo, coolos17 Hello, haven't you found a solution to this download problem? Code in class-wc-post-types.php slows down a site with many taxonomies (with created global attributes ), both backend and frontend (it loads on many pages, if not all):
`$attribute_taxonomies  = wc_get_attribute_taxonomies();
foreach ( $attribute_taxonomies as $tax ) {
          register_taxonomy( $name, apply_filters( "woocommerce_taxonomy_objects_{$name}", array( 'product' ) ), apply_filters( "woocommerce_taxonomy_args_{$name}", $taxonomy_data ) );
}`

**Comment by immunity20** [comment] 2020-11-29 12:27
Same problem here.
eshop with ~ 6.5K products and ~ 140products ( 1 product has ~ 5-10 product_attributes)
I use the global attributes? (the one that woocommerce has in products -> attributes).
An attribute is added in each product by attributes_options tab.

VPN with dedicated 16vCPUs 64GB RAM gets waiting time (TTFB) of 10-20secs when there are around 30-35 unique users.
Most of the lag i think it is created when the users visit archive pages (where the filters are presented / use of product attributes for filtering)

Mysql MariaDB with InnoDB, Nginx with cache (used sqltuner recommendations -> defragment tables etc)

Ram usage ~ 4GB the rest 60GB are free :S
When I had it on dedicated vCPU the CPU usage was reaching 400%[100% * 4 vCPUs] although at 16vCPU it reaches 800-1000% [100% * 8-10 vCPUs]

Of course the problem is on mySQL side. During 30-35 unique visitors I get too many slow queries log  with 4-20secs for response TTFB) probably because some queries blocks the others.

What I found out when I enabled Redis was that it improved the situation (now the website would be "usable" although still some 2-3 secs TTFB in some cases) but overall ~ 800ms TTFB. **RAM usage still 4GB**. **CPU usage ~reduced **.

Of course the problem is not fixed having 16vCPU 64GB RAM machine to serve 30-50 concurrent unique users is not the best :S
probably needs better mysql configurate but for sure there is something about the woocommerce. I look other similar eshop sites on the same industry perform muych

**Hard disk usage (SSD/nvme) Reduced tremendously**

![VPS_graphs](https://user-images.githubusercontent.com/17274326/100541808-fb4e9080-324e-11eb-8b7b-3b93288087f2.PNG)


`# Query_time: 4.489504  Lock_time: 0.000028  Rows_sent: 0  Rows_examined: 1
SET timestamp=1606402934;
DELETE FROM wp_term_relationships WHERE object_id = 16458 AND term_taxonomy_id IN ('2081');`

or a bigger one (which i think is one of the queries that creates the delay / overload)
<details><summary>queries with insert of a string TOOOOOO LOOONGGG and 20+secs query_time</summary>

# Thread_id: 813  Schema: QC_hit: No
# Query_time: 4.811242  Lock_time: 1.798966  Rows_sent: 0  Rows_examined: 0
SET timestamp=1606399652;
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('**a 100 pages long string)**' WHERE `option_name` = '_transient_wc_layered_nav_counts_pa_litourgia-apovarou';
# Time: 201126 16:07:37
# Thread_id: 770  Schema: QC_hit: No
# Query_time: 27.786439  Lock_time: 0.000077  Rows_sent: 2  Rows_examined: 47230
SET timestamp=1606399657;
SELECT DISTINCT p1.post_id FROM wp_postmeta p1 WHERE p1.meta_value LIKE '%blablabla_customer_name%' AND p1.meta_key IN ('_billing_address_index','_shipping_address_index','_billing_last_name','_billing_email');
</details>

**Comment by gelinger777** [comment] 2022-01-21 17:10
my fellow has a  similar problem with variations . he has 300 Products which then make arround 3000 attributes. Page load is about 12seconds on homepage....

**Comment by DanielCyran** [comment] 2023-11-01 17:56
Please provide a solution to this problem because the number of attributes should not impact the store's speed. 
    https://github.com/woocommerce/woocommerce/issues/41169

**Comment by henriquemattos** [comment] 2023-11-01 18:25
@DanielCyran, please feel free to provide a Pull Request for review and test. This is open source software, you are welcome to provide a solution if you have any.


> Please provide a solution to this problem because the number of attributes should not impact the store's speed. 
> 
>     https://github.com/woocommerce/woocommerce/issues/41169
