### ISSUE TITLE
Bulk edit stock management issue

### ISSUE THREAD

**Issue by CharlieLivingston** [woocommerce/woocommerce#23525] opened 2019-04-26 11:34 UTC
When trying to set products via bulk edit to have a stock quantity of 1 sets the product to have a stock quantity of 0 (i.e. out of stock).

1. Select 1 or more products via bulk edit
2. Set In Stock? to Yes
3. Manage Stock - Yes
4. Stock Quantity - Change to 1

One or more of the covers will now be set to out of stock instead of 1. 

Workaround: first time you do this products will be set to of stock, quantity 0, second time you do it they will be out of stock, quantity 1, third time they will show correctly as in stock, quantity 1. 

What should happen is that when you bulk edit and set the stock quantity to 1, it should be set as stock quantity 1 and in stock. 

This happens with WooCommerce 3.6.2 and WordPress 5.1.1

Storefront theme 2.4.5

**Comment by mikejolley** [comment] 2019-04-26 12:36
Hi, this appears to be a duplicate of https://github.com/woocommerce/woocommerce/issues/23388

**Closed by mikejolley** 2019-04-26 12:36 UTC
