### ISSUE TITLE
Wrong shipping tax class assigned

### ISSUE THREAD

**Issue by Holu8** [woocommerce/woocommerce#25223] opened 2019-12-12 20:14 UTC
**Describe the bug**
Using the default shipping tax class: “based on cart items” setting it charges the lowest tax rate when there are multiple products in the cart with different tax rates.

**To Reproduce**
1. Set shipping tax class to "Shipping tax class based on cart items"
2. Make order with multiple products with different tax rate (e.g. 10% and 24%)
3. Check order in admin menu

**Screenshot**
<a href="https://ibb.co/P62DLTb"><img src="https://i.ibb.co/VqFw1Hh/wrong-shipping-tax-added.png" alt="wrong-shipping-tax-added" border="0"></a>

**Expected behavior**
It should charge by the highest tax rate of products that are in the cart.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2019-12-13 15:09
Thanks for raising the issue @Holu8. I can reproduce it on my end, however, I am not sure that the highest tax rate should be applied to shipping either. 

To document my process:

- I created 3 tax classes at different rates with tax applied to shipping in each class

**Standard:**

![tax1](https://user-images.githubusercontent.com/19143190/70809510-cd600a00-1db9-11ea-83cf-5c963d83d1ef.jpg)

**Reduced:**

![tax2](https://user-images.githubusercontent.com/19143190/70809559-eec0f600-1db9-11ea-8940-5b1ad9a82e39.jpg)

**Zero:**

![tax3](https://user-images.githubusercontent.com/19143190/70809581-fed8d580-1db9-11ea-8abd-d0c2a248b35c.jpg)

- I created a `Flat Rate` shipping method for the US shipping zone and assigned a shipping rate of $10:

![tax5](https://user-images.githubusercontent.com/19143190/70809698-3cd5f980-1dba-11ea-91f5-b6c81a3e51e3.jpg)

- I created 3 products and assigned different tax rates I created in step 1 to each product;

- I placed an order for the 3 products with Flat Rate shipping;

- As a result, I got the lowest tax class rate applied to shipping despite the fact that 2 other products also had shipping marked as to be applied tax rate to yet the highest rates were not applied:

![tax4](https://user-images.githubusercontent.com/19143190/70809798-7444a600-1dba-11ea-9215-a1e7d9171ca2.jpg)

**Comment by Holu8** [comment] 2019-12-13 22:38
Thank you @juliaamosova for detailed explenation of the problem.

The thing is, apparently before 3.8.0 it worked the way, I explained it should (or how I expect it to work). Also this is huge bug, because according to laws in my country (and believe whole EU), you should charge shipping tax by the highest tax rate of products you have in "cart".

**Screenshot before updating to 3.8.0**
<a href="https://ibb.co/Jj4tWfY"><img src="https://i.ibb.co/whXgZ9n/before-3-8-0.png" alt="before-3-8-0" border="0"></a>

**Screenshot after updating to 3.8.0**
<a href="https://ibb.co/W3WTvF2"><img src="https://i.ibb.co/DbDqfkR/after-3-8-0.png" alt="after-3-8-0" border="0"></a>

**Comment by juliaamosova** [comment] 2019-12-16 10:19
@Holu8 I tested with WooCommerce 3.7.1 on my end and the results were the same as with 3.8 and up - the lower tax rate was applied to shipping. I made a screencast to document that:

https://recordit.co/RmSicXNEWa

Could it be that you've used some 3rd party plugin that manipulates the way tax is applied to shipping?

**Comment by Holu8** [comment] 2019-12-16 13:00
@juliaamosova I am sure, that it was part of Woocoommerce before and this option worked like that. Even independent guides suggest that: https://jeroensormani.com/guide-shipping-taxes-woocommerce/#shipping-tax-class

I have posted two screenshots, where exactly it changed. But this is huge problem as it doesn't charge the highest, but lowest, tax.

**Comment by Holu8** [comment] 2019-12-22 13:00
Why is this issue still labeled: needs feedback?

**Comment by juliaamosova** [comment] 2020-01-17 14:34
Hi @Holu8,

Apologies for the delayed response. I finally figured out what was the issue. I am now getting the highest tax rate applied to shipping on my end using the latest WooCommerce version 3.8.1. 

The answer can be found here in the code:

https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/class-wc-tax.php#L577

In the case of multiple tax rates in the order, the tax will be applied as follows:

> If multiple classes are found, use the first one found unless a standard rate item is found. This will be the first listed in the 'additional tax class' section.

What it means is that:

- If you have a product with the `Standard` rate in the order, it will be used for the shipping regardless if this rate is high or low;
- If you don't have a product with the `Standard` rate in the order, then the first rate found in the `Additional tax class` section will be used for shipping.

The goal is to make sure that your highest rate is listed the first in the `Additional tax class` section if you don't use the `Standard` class. 

Here is my setup to showcase it visually:

I utilize the `Standard` class but instead have `Tax A`, `Tax B`, `Tax C`. Note that it is not possible to delete the `Standard` tax rate but you can leave it empty and it will be ignored:

![tax1](https://user-images.githubusercontent.com/19143190/72619665-b327c780-3935-11ea-9d21-8539f9b9113c.jpg)

`Standard` rate is empty:

![Screen Shot 2020-01-17 at 2 25 08 PM](https://user-images.githubusercontent.com/19143190/72619687-c2a71080-3935-11ea-9040-0cbcd8d7eafa.png)

`Tax A` (24%) - the highest rate listed the first:

![Screen Shot 2020-01-17 at 2 25 17 PM](https://user-images.githubusercontent.com/19143190/72619728-d5b9e080-3935-11ea-82ab-549b38a7f4e3.png)

`Tax B` (14%):

![Screen Shot 2020-01-17 at 2 25 28 PM](https://user-images.githubusercontent.com/19143190/72619751-e0747580-3935-11ea-842e-8018c40b0979.png)

`Tax C` (10%):

![Screen Shot 2020-01-17 at 2 25 43 PM](https://user-images.githubusercontent.com/19143190/72619762-e9654700-3935-11ea-9f6f-d8dc99bd53fc.png)

As a result, I am getting the highest tax rate applied to the shipping in the order with multiple tax rates assigned to products:

![tax2](https://user-images.githubusercontent.com/19143190/72619882-29c4c500-3936-11ea-9b5b-21aca6dcb2a4.jpg)

Can you please test the same and let us know if it works for you as I described? I will then update our documentation with the details of the correct setup: 

https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-5

**Comment by juliaamosova** [comment] 2020-01-28 14:54
Hi @Holu8,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

Also please note that we updated the documentation to reflect the correct setup if someone wants the highest tax rate to be applied to shipping on the order with multiple tax rates:

https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-5

**Closed by juliaamosova** 2020-01-28 14:54 UTC
Labels: status: needs feedback

**Comment by Holu8** [comment] 2020-02-02 21:06
Hi @juliaamosova,
I am really sorry for late response, renaming classes means deleting them, then assigning products again to the classes. For this purpose I had to set up test server and try it there to prevent possible problems, which required some time.
You were right, the taxes now work correctly, thank you for updating docs & searching for solution.

**Comment by juliaamosova** [comment] 2020-02-03 10:16
@Holu8 no worries at all and thanks for your follow-up! I am glad the issue is now resolved.
