### ISSUE TITLE
SVG image not supported while adding product category 

### ISSUE THREAD

**Issue by maheshpatidar** [woocommerce/woocommerce#25374] opened 2020-01-08 11:45 UTC
**Issue**
While creating new product category, adding a thumbnail of type SVG doesn't work. It does not show a message even. 
when inspected the jQuery code , I found that it looks for the thumbnail sizes which is not available in case of SVG.
```
var attachment           = file_frame.state().get( 'selection' ).first().toJSON();
var attachment_thumbnail = attachment.sizes.thumbnail || attachment.sizes.full;
jQuery( '#product_cat_thumbnail_id' ).val( attachment.id );
jQuery( '#product_cat_thumbnail' ).find( 'img' ).attr( 'src', attachment_thumbnail.url );
jQuery( '.remove_image_button' ).show();
```

**Steps to reproduce the behavior:**
1. Go to 'Dashboard->Products->Categories->Add New Category'
2. Click on 'Add/Upload Image'
3. Select one of the SVG image from Media gallery or upload from local computer
4. It will neither show selected image nor any error message

**Screenshot**
<img width="612" alt="Screenshot 2020-01-08 at 5 11 28 PM" src="https://user-images.githubusercontent.com/19227368/71975440-f6997c00-3239-11ea-8e6c-ac51829ca0b2.png">

**Expected behavior**
SVG image should be selected and uploaded once click on Add new category

**Isolating the problem:**
- [x] I have enabled the SVG upload and it is working while adding post and page.
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost/woostore
Site address (URL): http://localhost/woostore
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) OpenSSL/1.0.2s PHP/7.1.30 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 7.1.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.15-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 2.59MB
Database Data Size: 1.61MB
Database Index Size: 0.98MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.03MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: woo-store
Version: 1.0.0
Author URL: http://underscores.me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2020-01-08 08:00:57 +0000
Newest: 2020-01-08 08:00:57 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment] 2020-01-14 21:28
Hi @maheshpatidar,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. 

The first thing to note is that SVG images are not supported by WordPress by default. You'd get an error message if you try to drag SVG image to the Media Library area:

![svg1](https://user-images.githubusercontent.com/19143190/72383693-e0952b00-3713-11ea-837b-3cc06cb0919c.jpg)

If you try to upload, it will be greyed out which is an indicator that it can't be used:

![svg2](https://user-images.githubusercontent.com/19143190/72383730-f7d41880-3713-11ea-9f8e-d9ef413351dc.jpg)

There is a plugin available, however, which enables SVG images support in WordPress:

https://en-gb.wordpress.org/plugins/svg-support/

I've tried it and was able to successfully upload SVG image to the product category:

![svg3](https://user-images.githubusercontent.com/19143190/72383959-70d37000-3714-11ea-97a6-c90057805608.jpg)

![svg4](https://user-images.githubusercontent.com/19143190/72383972-7761e780-3714-11ea-973b-0f4d710b2312.jpg)

![svg5](https://user-images.githubusercontent.com/19143190/72383983-7df05f00-3714-11ea-918c-8fd29f80330a.jpg)

If you are having an issue, it is likely due to the SVG images support plugin you are using. 

I am closing this issue since it is not directly related to WooCommerce. However, if you think I missed something, feel free to comment back and I will take a second look.

**Closed by juliaamosova** 2020-01-14 21:28 UTC
