### ISSUE TITLE
Add coupon to existing order & role permission

### ISSUE THREAD

**Issue by lenamtl** [woocommerce/woocommerce#30253] opened 2021-07-11 16:04 UTC
Hi,

I'm looking for information about role permission that allows to **add a coupon code** to **an existing order**.
Even shop manager cannot do that.
I'm creating a custom role and I cannot found the information.

I'm looking for this information for more than a week with no luck.

**Comment by rodelgc** [comment] 2021-07-14 07:24
Hi @lenamtl,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by rodelgc** 2021-07-14 07:24 UTC
