### ISSUE TITLE
Translate does not work.

### ISSUE THREAD

**Issue by davutkara** [woocommerce/woocommerce#21378] opened 2018-09-18 11:07 UTC
**Describe the bug**
Translate does not work for templates/checkout/form-login.php:32

**To Reproduce**
Translate has inserted the po-file, but it is still not working.
```
#: templates/checkout/form-login.php:32
msgid "If you have shopped with us before, please enter your details below. If you are a new customer, please proceed to the Billing &amp; Shipping section."
msgstr "Bizimle önceden alışveriş yaptıysanız, lütfen aşağıdaki kutulara bilgilerinizi giriniz. Yeni bir müşteriyseniz, lütfen Faturalama ve Gönderim bölümüne devam ediniz."
```
The others are okey, but translating the line is not working. &\amp; can be cause of the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/10008440/45683272-ba757000-bb4b-11e8-9a8e-075761fcad74.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: ??
Site URL: ??
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.30-0ubuntu0.16.04.1 - Daha iyi performans ve daha gelişmiş güvenlik için PHP'nin 7.2 veya daha yeni bir sürümünü kullanmanız önerilir. PHP sürümünüz nasıl güncellenir?
PHP Post Max Size: 16 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.23-0ubuntu0.16.04.1
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Toplam veritabanı boyutu: 95.00MB
Veritabanı veri boyutu: 62.66MB
Veritabanı indis boyutu: 32.34MB
wp_woocommerce_sessions: Veri: 0.02MB + İndis: 0.02MB
wp_woocommerce_api_keys: Veri: 0.02MB + İndis: 0.03MB
wp_woocommerce_attribute_taxonomies: Veri: 0.02MB + İndis: 0.02MB
wp_woocommerce_downloadable_product_permissions: Veri: 0.02MB + İndis: 0.05MB
wp_woocommerce_order_items: Veri: 0.14MB + İndis: 0.06MB
wp_woocommerce_order_itemmeta: Veri: 1.52MB + İndis: 1.86MB
wp_woocommerce_tax_rates: Veri: 0.02MB + İndis: 0.06MB
wp_woocommerce_tax_rate_locations: Veri: 0.02MB + İndis: 0.03MB
wp_woocommerce_shipping_zones: Veri: 0.02MB + İndis: 0.00MB
wp_woocommerce_shipping_zone_locations: Veri: 0.02MB + İndis: 0.03MB
wp_woocommerce_shipping_zone_methods: Veri: 0.02MB + İndis: 0.00MB
wp_woocommerce_payment_tokens: Veri: 0.02MB + İndis: 0.02MB
wp_woocommerce_payment_tokenmeta: Veri: 0.02MB + İndis: 0.03MB
wp_woocommerce_log: Veri: 0.02MB + İndis: 0.02MB
wp_commentmeta: Veri: 0.02MB + İndis: 0.03MB
wp_comments: Veri: 0.33MB + İndis: 0.38MB
wp_failed_jobs: Veri: 0.02MB + İndis: 0.00MB
wp_iyzico_card: Veri: 0.02MB + İndis: 0.00MB
wp_iyzico_order: Veri: 0.02MB + İndis: 0.00MB
wp_links: Veri: 0.02MB + İndis: 0.02MB
wp_mailchimp_carts: Veri: 0.02MB + İndis: 0.00MB
wp_options: Veri: 1.05MB + İndis: 0.05MB
wp_postmeta: Veri: 5.52MB + İndis: 7.03MB
wp_posts: Veri: 1.52MB + İndis: 0.36MB
wp_queue: Veri: 0.02MB + İndis: 0.00MB
wp_termmeta: Veri: 0.02MB + İndis: 0.03MB
wp_terms: Veri: 0.02MB + İndis: 0.03MB
wp_term_relationships: Veri: 0.02MB + İndis: 0.02MB
wp_term_taxonomy: Veri: 0.02MB + İndis: 0.03MB
wp_usermeta: Veri: 50.56MB + İndis: 21.06MB
wp_users: Veri: 1.52MB + İndis: 1.02MB
wp_wc_download_log: Veri: 0.02MB + İndis: 0.03MB
wp_wc_webhooks: Veri: 0.02MB + İndis: 0.02MB

### Post Type Counts ###

attachment: 53
nav_menu_item: 6
page: 19
post: 2
product: 39
revision: 16
shop_order: 1737

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

CloudFlare Flexible SSL: (iControlWP) – 1.2.2
All-in-One WP Migration: (ServMask) – 6.76
JSON Basic Authentication: (WordPress API Team) – 0.1
iyzico WooCommerce: (iyzico) – 1.0.5 – WooCommerce’in etkin sürümüyle test edilmemiştir
MailChimp for WooCommerce: (MailChimp) – 2.1.9 – WooCommerce’in etkin sürümüyle test edilmemiştir
WordPress Users & WooCommerce Customers Import Export(BASIC): (WebToffee) – 1.1.6
WooCommerce Smart COD: (Stratos Vetsos) – 1.4.9.4 – WooCommerce’in etkin sürümüyle test edilmemiştir
Woo Checkout Field Editor Pro: (ThemeHiGH) – 1.2.7
Advanced Order Export For WooCommerce: (AlgolPlus) – 1.5.6
WooCommerce PayPal Checkout Gateway: (WooCommerce) – 1.6.3
WooCommerce: (Automattic) – 3.4.5
WordPress aktarıcısı: (wordpressdotorg) – 0.6.4
WooCommerce Multi-Step Checkout: (SilkyPress) – 1.12

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Mağaza giriş sayfası: #5 - /magaza/
Sepet sayfası: #6 - /sepet/
Ödeme sayfası: #7 - /odeme/
Hesabım sayfası: #8 - /hesabim/
Şartlar ve koşullar: ❌ Sayfa ayarlanmamış

### Theme ###

Name: Storefront - DersNette
Version: 1
Author URL: http://davutkara.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.3.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rodrigoprimo** [comment] 2018-09-25 14:06
I'm not able to reproduce this issue. On a clean WooCommerce core install using Storefront, if I set my site language to Turkish the string you mentioned is displayed in Turkish:

![screenshot from 2018-09-25 11-03-36](https://user-images.githubusercontent.com/77215/46019621-e4caae80-c0b2-11e8-9081-712b44d0638d.png)

Closing this for now, but please provide more details if I missed something and I will reopen. Maybe your theme overrides this template and uses a slightly different string?

**Closed by rodrigoprimo** 2018-09-25 14:06 UTC
