### ISSUE TITLE
init_form_fields does not create fields on the woo payment options page

### ISSUE THREAD

**Issue by clinton2111** [woocommerce/woocommerce#28138] opened 2020-10-29 12:53 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have been trying to create a custom payment gateway. tried to add fields in the init_form_fields() function for API keys and such but the fields do not show up on the admin panel under the woo commerce > payments >manage payments area

**Expected behavior**
Checkboxes and other form inputs should be visible

**Actual behavior**
No Form Input fields

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'woocommerce > settings'
2. Click on 'Custom payment method > manage'
3. No form fields

**Screenshots**
![image](https://user-images.githubusercontent.com/3950377/97575296-f60ae580-1a05-11eb-953b-694e416f96cf.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### Code
<pre>
if ( ! in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
	return;
}

require 'vendor/autoload.php';
require 'inc/logger.php';

ini_set( 'error_log', plugin_dir_path( __FILE__ ) . '/logs/debug.log' );

add_action( 'plugins_loaded', 'alrahji_payment_init', 11 );

function alrahji_payment_init() {
	if ( class_exists( 'WC_Payment_Gateway', false ) ) {
		try {
			class WC_Alrajhi_Payment_Gateway extends WC_Payment_Gateway {

				public function __construct() {

					$this->id                 = 'Al Rajhi Payment';
					$this->icon               = apply_filters( 'al-rajhi-icon', plugins_url() . '/assets/alrajhilogo.jpg' );
					$this->has_fields         = false;
					$this->method_title       = __( 'Al Rajhi Payment', 'al-rajhi' );
					$this->method_description = __( 'Al Rajhi Payment System', 'al-rajhi' );
					$this->init_form_fields();
					$this->init_settings();

				}

				public function init_form_fields() {
					$this->form_fields = apply_filters( 'al_rajhi_pay_fields', array(
						'enabled' => array(
							'title' => __( 'Enabled/Disabled', 'al-rajhi' ),
							'label' => __( 'Enable Al Rajhi Gateway', 'al-rajhi' ),
							'type'    => 'checkbox',
							'default' => 'no'
						),
						'title' => array(
							'title' => __( 'Payment Gateway', 'al-rajhi' ),
							'description' => __( 'Add a new title', 'al-rajhi' ),
							'type'    => 'text',
							'default' => __( 'Payment Gateway', 'al-rajhi' )
						)
					) );

				}
			}
		} catch ( Exception $e ) {
			write_log( $e->getMessage() );
		}

	}
}

add_filter( 'woocommerce_payment_gateways', 'add_alrajhi_payment_gateway' );

function add_alrajhi_payment_gateway( $gateways ) {
	$gateways[] = 'WC_Alrajhi_Payment_Gateway';

	return $gateways;

</pre>

**WordPress Environment**
<details>
```
`

### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost/wordpress
WC Version: 4.6.1
REST API Version: ✔ 4.6.1
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.10
PHP Version: 7.4.10
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.14-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ❌ Default timezone is Asia/Dubai - it should be UTC
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.1
WC Database Prefix: wp_
Total Database Size: 3.80MB
Database Data Size: 2.09MB
Database Index Size: 1.71MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 6
post: 2
product: 18
product_variation: 7
shop_order: 4
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Alrajhi Payment Gateway: by Clinton D – 1.0
WooCommerce: by Automattic – 4.6.1
WP Mail SMTP: by WPForms – 2.5.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: AED (د.إ)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Basket: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty Child
Version: 1.0.0
Author URL: https://elicus.com
Child Theme: ✔
Parent Theme Name: Twenty Twenty
Parent Theme Version: 1.5
Parent Theme Author URL: https://en-gb.wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentytwenty-child/woocommerce/myaccount\form-login.php

### Action Scheduler ###

Complete: 52
Oldest: 2020-10-25 12:02:57 +0000
Newest: 2020-10-29 11:49:09 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-10-29 18:38
Hi @clinton2111,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-29 18:38 UTC
