### ISSUE TITLE
The loopback request to your site failed

### ISSUE THREAD

**Issue by bulgaru** [woocommerce/woocommerce#20561] opened 2018-06-18 13:35 UTC
**Describe the bug**
When enabling Woocommerce, Health Check reports the following error: The loopback request to your site failed. Moreover, plugin editor stops working afterwards due to this issue.

**To Reproduce**
1. Install a clean WP instance
2. Install Wocommerce & Health Check plugins
3. Verify Health Check.

**Expected behavior**
Plugin editor should be working.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://www.toupgrade.ro
Site URL: http://www.toupgrade.ro
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ro_RO
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.6-1+ubuntu17.10.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.0.2n

SUHOSIN Installed: –
MySQL Version: 5.7.22-0ubuntu18.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: toupgrade_
MaxMind GeoIP Database: ✔
Total Database Size: 2.81MB
Database Data Size: 1.92MB
Database Index Size: 0.89MB
toupgrade_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
toupgrade_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
toupgrade_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
toupgrade_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
toupgrade_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
toupgrade_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
toupgrade_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
toupgrade_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
toupgrade_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
toupgrade_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
toupgrade_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
toupgrade_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
toupgrade_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
toupgrade_woocommerce_log: Data: 0.02MB + Index: 0.02MB
toupgrade_commentmeta: Data: 0.02MB + Index: 0.03MB
toupgrade_comments: Data: 0.02MB + Index: 0.08MB
toupgrade_links: Data: 0.02MB + Index: 0.02MB
toupgrade_options: Data: 1.09MB + Index: 0.05MB
toupgrade_postmeta: Data: 0.02MB + Index: 0.03MB
toupgrade_posts: Data: 0.27MB + Index: 0.06MB
toupgrade_termmeta: Data: 0.02MB + Index: 0.03MB
toupgrade_terms: Data: 0.02MB + Index: 0.03MB
toupgrade_term_relationships: Data: 0.02MB + Index: 0.02MB
toupgrade_term_taxonomy: Data: 0.02MB + Index: 0.03MB
toupgrade_usermeta: Data: 0.02MB + Index: 0.03MB
toupgrade_users: Data: 0.02MB + Index: 0.05MB
toupgrade_wc_download_log: Data: 0.02MB + Index: 0.03MB
toupgrade_wc_webhooks: Data: 0.02MB + Index: 0.02MB
toupgrade_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
toupgrade_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 265
acf-field-group: 46
flamingo_contact: 3
jetpack_migration: 2
nav_menu_item: 21
page: 6
post: 3
revision: 8
tribe_events: 5
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (27) ###

Admin Menu Editor: by Janis Elsts – 1.8.4
Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
Akismet Anti-Spam: by Automattic – 4.0.7
All-in-One WP Migration: by ServMask – 6.70
Autoptimize: by Frank Goossens (futtta) – 2.3.4
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.2

Contact Form 7: by Takayuki Miyoshi – 5.0.2
Cyr to Lat enhanced: by Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.5

Event Tickets Plus: by Modern Tribe
Inc. – 4.7.3

Event Tickets: by Modern Tribe
Inc. – 4.7.3.1

The Events Calendar PRO: by Modern Tribe
Inc. – 4.4.27

Flamingo: by Takayuki Miyoshi – 1.8
Health Check: by The WordPress.org community – 1.1.0
ImageMagick Engine: by Brand Manual – 1.5.2
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
Max Mega Menu: by Tom Hemsley – 2.4.2
Members: by Justin Tadlock – 2.1.0
Nav Menu Roles: by Kathy Darling – 1.9.2
Site Offline: by Chandra Shekhar Sahu – 1.2.6
Social Login Lite For WooCommerce: by phoeniixx – 1.5.2 – Not tested with the active version of WooCommerce
The Events Calendar: Filter Bar: by Modern Tribe
Inc. – 4.5.6

The Events Calendar: by Modern Tribe
Inc. – 4.6.18

Cookie Consent: by Catapult_Themes – 2.3.11
WooCommerce: by Automattic – 3.4.2
Yoast SEO: by Team Yoast – 7.6.1
WP Mail SMTP: by WPForms – 1.2.5
WP Sitemap Page: by Tony Archambeau – 1.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: ToUpgrade by b-sensus
Version: 1.0.0
Author URL: http://www.bsensus.md
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: yoo_master2_wp/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
yoo_master2_wp/woocommerce/cart/mini-cart.php version 3.2.0 is out of date. The core version is 3.3.0
yoo_master2_wp/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.4.0
yoo_master2_wp/woocommerce/content-product_cat.php
yoo_master2_wp/woocommerce/content-widget-product.php version 2.5.0 is out of date. The core version is 3.3.0
yoo_master2_wp/woocommerce/global/quantity-input.php version 3.2.0 is out of date. The core version is 3.4.0
yoo_master2_wp/woocommerce/loop/add-to-cart.php version 3.0.0 is out of date. The core version is 3.3.0
yoo_master2_wp/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
yoo_master2_wp/woocommerce/loop/price.php
yoo_master2_wp/woocommerce/loop/sale-flash.php
yoo_master2_wp/woocommerce/single-product/meta.php
yoo_master2_wp/woocommerce/single-product/sale-flash.php
yoo_master2_wp/woocommerce/single-product/tabs/tabs.php

Outdated Templates: ❌
					
					
						Learn how to update
`
</details>

**Comment by mikejolley** [comment] 2018-06-19 11:05
I didn't encounter this one with those 2 active; loopback is working.

![health check wordpress wordpress 2018-06-19 12-01-56](https://user-images.githubusercontent.com/90977/41593623-9fe0bc2a-73b8-11e8-9d4c-cee56c752e43.png)

The loopback check itself is simply a remote post to your admin URL. WooCommerce actually makes use of that so if it's failing that can cause issues with background processing and things such as that. It doesn't appear that WooCommerce itself breaks this loopback because I'd see the same issue locally.

I'd suggest only enabling WooCommerce, Health Check, and a default WordPress theme and repeating the test. After this, check the WP DEBUG LOG and log in WooCommerce > System Status > Logs called fatal-errors and see if anything is there. 

For debug log see https://codex.wordpress.org/Debugging_in_WordPress

If there is a connection error which is preventing the loop back from working, it will be logged in the WP debug log, or perhaps the PHP error log on your server. This should give you some clues as to what is causing it. It could simply be a memory limit error or timeout.

Closing this for now as non reproducible, but if you find anything feel free to comment back.

Thanks

**Closed by mikejolley** 2018-06-19 11:05 UTC

**Comment by bulgaru** [comment] 2018-06-19 12:29
You are correct and I was wrong. Turns out - I had 3 different plugins (all WC related) causing the issue:

- WooCommerce AJAX Products Filter (premium version) by BeRocket
- TM WooCommerce Compare & Wishlist by JetImpex
- Social Login Lite For WooCommerce by phoeniixx

Therefore when disabling WC all 3 got inactive and the issue disappeared. Sorry for bothering.
