### ISSUE TITLE
"Downloads remaining" count in customer orders does not get updated

### ISSUE THREAD

**Issue by GoranRista** [woocommerce/woocommerce#28470] opened 2020-12-02 16:29 UTC
- [ x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When a download limit is set for a product, it does not get updated in users' orders when they subsequently download the product. The number in the "Downloads remaining" field stays the same as set in the product.

**Expected behavior**
This number should decrease with every subsequent download by a customer.

**Actual behavior**
"Downloads remaining" does not change.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a digital product.
2. Add a file and set download limit to 2
3. Create order and add that product to the order. Complete the order.
4. See the "Downloads remaining" section displaying "2".
5. Go to "My Account" front end and download the product two times.
6. Go back to the order details (admin), refresh it, and look at the "Downloads remaining". It still shows "2".

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://library.gorangrooves.com
Site address (URL): https://library.gorangrooves.com
WC Version: 4.7.1
REST API Version: ✔ 4.7.1
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.13
PHP Post Max Size: 24 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.47-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.1
WC Database Prefix: qaNlPQ_
Total Database Size: 19.84MB
Database Data Size: 17.62MB
Database Index Size: 2.22MB
qaNlPQ_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_actionscheduler_actions: Data: 1.42MB + Index: 0.48MB + Engine InnoDB
qaNlPQ_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_actionscheduler_logs: Data: 0.33MB + Index: 0.23MB + Engine InnoDB
qaNlPQ_ac_abandoned_cart_history_lite: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_ac_email_templates_lite: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_ac_guest_abandoned_cart_history_lite: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_ac_sent_history_lite: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_bv_ip_store: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_cfs_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_cfs_values: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
qaNlPQ_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_eg_grids: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_eg_item_elements: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_eg_item_skins: Data: 0.62MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_eg_navigation_skins: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
qaNlPQ_itsec_distributed_storage: Data: 3.05MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_itsec_lockouts: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_itsec_logs: Data: 0.52MB + Index: 0.05MB + Engine MyISAM
qaNlPQ_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_itsec_temp: Data: 0.21MB + Index: 0.21MB + Engine MyISAM
qaNlPQ_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_options: Data: 4.51MB + Index: 0.09MB + Engine MyISAM
qaNlPQ_postmeta: Data: 0.32MB + Index: 0.13MB + Engine MyISAM
qaNlPQ_posts: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
qaNlPQ_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_tinvwl_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_tinvwl_lists: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_usermeta: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
qaNlPQ_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
qaNlPQ_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
qaNlPQ_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
qaNlPQ_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
qaNlPQ_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
qaNlPQ_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
qaNlPQ_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
qaNlPQ_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfBadLeechers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfBlocks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfConfig: Data: 0.23MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfFileMods: Data: 1.29MB + Index: 0.20MB + Engine MyISAM
qaNlPQ_wfHits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfKnownFileList: Data: 0.65MB + Index: 0.09MB + Engine MyISAM
qaNlPQ_wfLeechers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfLockedOut: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfLogins: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfNet404s: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfNotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfScanners: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfStatus: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
qaNlPQ_wfThrottleLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wfVulnScanners: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_woochimp_scheduled_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qaNlPQ_wpml_mails: Data: 3.50MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wptao_events: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
qaNlPQ_wptao_events_meta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
qaNlPQ_wptao_events_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wptao_fingerprints: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wptao_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qaNlPQ_wptao_users_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qaNlPQ_wptao_users_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 68
cfs: 10
custom_css: 2
nav_menu_item: 11
page: 15
post: 3
product: 19
shop_coupon: 2
shop_order: 11
vc_grid_item: 1
vc_settings_preset: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Adaptive Images for WordPress: by Nevma – 0.6.68
AJAX Search for WooCommerce: by Damian Góra – 1.8.0 – Installed version not tested with active version of WooCommerce 4.7.1
All-in-One WP Migration Unlimited Extension: by ServMask – 2.37
All-in-One WP Migration: by ServMask – 7.31
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.4

Angell EYE Updater: by Angell EYE – 2.0.16
MalCare - Pro: by MalCare – 4.36
Change Case: by Michael Aronoff – 2.0.3
Custom Ajax By JO: by  –
Custom Field Suite: by Matt Gibbs – 2.6
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 3.2.6
Email Encoder - Protect Email Addresses: by Ironikus – 2.1.0
Essential Grid: by ThemePunch – 3.0.9
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.19
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
jQuery Updater: by Ramoonus – 3.5.1.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.4.2
Kaswara Modern VC Addons: by SayenThemes – 3.0.1
PayPal for WooCommerce: by Angell EYE – 2.4.6
Safe SVG: by Daryll Doyle – 1.9.9
TI WooCommerce Wishlist: by TemplateInvaders – 1.22.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.41

WavePlayer: by Luigi Pulcini – 2.4.4
Woocommerce Add to cart Ajax for variable products: by Rishi Mehta - Rcreators Websolutions – 2.0 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce: by Automattic – 4.7.1
WP Mail SMTP: by WPForms – 2.5.1

### Inactive Plugins (1) ###

Woo Custom Downloads: by Goran Grooves – 2.1.1 – Installed version not tested with active version of WooCommerce 4.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #351 - /cart/
Checkout: #352 - /checkout/
My account: #353 - /my-account/
Terms and conditions: #1472 - /terms-and-conditions/

### Theme ###

Name: G Library
Version: 1.0.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Library/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
Library/woocommerce/auth/footer.php
Library/woocommerce/auth/form-grant-access.php version 2.4.0 is out of date. The core version is 4.3.0
Library/woocommerce/auth/form-login.php version 2.4.0 is out of date. The core version is 3.4.0
Library/woocommerce/auth/header.php
Library/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.5.0
Library/woocommerce/cart/cart-item-data.php
Library/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.6.0
Library/woocommerce/cart/cart-totals.php
Library/woocommerce/cart/cart.php version 3.0.0 is out of date. The core version is 3.8.0
Library/woocommerce/cart/cross-sells.php version 3.0.0 is out of date. The core version is 4.4.0
Library/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/cart/proceed-to-checkout-button.php
Library/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 4.0.0
Library/woocommerce/checkout/cart-errors.php version 2.4.0 is out of date. The core version is 3.5.0
Library/woocommerce/checkout/form-billing.php version 3.0.0 is out of date. The core version is 3.6.0
Library/woocommerce/checkout/form-checkout.php version 2.3.0 is out of date. The core version is 3.5.0
Library/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.4.4
Library/woocommerce/checkout/form-login.php version 2.0.0 is out of date. The core version is 3.8.0
Library/woocommerce/checkout/form-pay.php version 2.5.0 is out of date. The core version is 3.4.0
Library/woocommerce/checkout/form-shipping.php version 3.0.0 is out of date. The core version is 3.6.0
Library/woocommerce/checkout/payment-method.php version 2.3.0 is out of date. The core version is 3.5.0
Library/woocommerce/checkout/payment.php version 2.5.0 is out of date. The core version is 3.5.3
Library/woocommerce/checkout/review-order.php version 2.3.0 is out of date. The core version is 3.8.0
Library/woocommerce/checkout/terms.php version 2.5.0 is out of date. The core version is 3.4.0
Library/woocommerce/checkout/thankyou.php version 3.0.0 is out of date. The core version is 3.7.0
Library/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.6.0
Library/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.6.0
Library/woocommerce/content-widget-product.php version 2.5.0 is out of date. The core version is 3.5.5
Library/woocommerce/emails/admin-cancelled-order.php version 2.5.0 is out of date. The core version is 4.1.0
Library/woocommerce/emails/admin-failed-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/admin-new-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-completed-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-invoice.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-new-account.php version 1.6.4 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-note.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-on-hold-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-processing-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-refunded-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/customer-reset-password.php version 2.0.0 is out of date. The core version is 4.0.0
Library/woocommerce/emails/email-addresses.php version 3.0.0 is out of date. The core version is 3.9.0
Library/woocommerce/emails/email-customer-details.php
Library/woocommerce/emails/email-footer.php version 2.3.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/email-header.php version 2.4.0 is out of date. The core version is 4.0.0
Library/woocommerce/emails/email-order-details.php version 3.0.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/email-order-items.php version 3.4.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/email-styles.php version 2.3.0 is out of date. The core version is 4.0.0
Library/woocommerce/emails/plain/admin-cancelled-order.php version 2.5.0 is out of date. The core version is 4.1.0
Library/woocommerce/emails/plain/admin-failed-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/admin-new-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-completed-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-invoice.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-new-account.php version 2.0.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-note.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-on-hold-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-processing-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-refunded-order.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/customer-reset-password.php version 2.3.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/email-addresses.php version 2.2.0 is out of date. The core version is 3.4.0
Library/woocommerce/emails/plain/email-customer-details.php version 2.5.0 is out of date. The core version is 3.4.0
Library/woocommerce/emails/plain/email-order-details.php version 2.5.0 is out of date. The core version is 3.7.0
Library/woocommerce/emails/plain/email-order-items.php version 3.0.0 is out of date. The core version is 3.7.0
Library/woocommerce/global/breadcrumb.php
Library/woocommerce/global/form-login.php version 2.1.0 is out of date. The core version is 3.6.0
Library/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 4.0.0
Library/woocommerce/global/sidebar.php
Library/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
Library/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
Library/woocommerce/loop/add-to-cart.php version 3.0.0 is out of date. The core version is 3.3.0
Library/woocommerce/loop/loop-end.php
Library/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
Library/woocommerce/loop/no-products-found.php
Library/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.6.0
Library/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
Library/woocommerce/loop/price.php
Library/woocommerce/loop/rating.php version 3.0.0 is out of date. The core version is 3.6.0
Library/woocommerce/loop/result-count.php version 3.0.0 is out of date. The core version is 3.7.0
Library/woocommerce/loop/sale-flash.php
Library/woocommerce/myaccount/dashboard.php version 2.6.0 is out of date. The core version is 4.4.0
Library/woocommerce/myaccount/downloads.php version 3.0.0 is out of date. The core version is 3.2.0
Library/woocommerce/myaccount/form-add-payment-method.php version 3.0.0 is out of date. The core version is 4.3.0
Library/woocommerce/myaccount/form-edit-account.php version 2.6.0 is out of date. The core version is 3.5.0
Library/woocommerce/myaccount/form-edit-address.php version 3.0.0 is out of date. The core version is 3.6.0
Library/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 4.1.0
Library/woocommerce/myaccount/form-lost-password.php version 3.0.0 is out of date. The core version is 3.5.2
Library/woocommerce/myaccount/form-reset-password.php version 3.0.0 is out of date. The core version is 3.5.5
Library/woocommerce/myaccount/lost-password-confirmation.php version 2.6.0 is out of date. The core version is 3.9.0
Library/woocommerce/myaccount/my-account.php version 2.6.0 is out of date. The core version is 3.5.0
Library/woocommerce/myaccount/my-address.php
Library/woocommerce/myaccount/my-downloads.php
Library/woocommerce/myaccount/my-orders.php
Library/woocommerce/myaccount/navigation.php
Library/woocommerce/myaccount/orders.php version 3.0.0 is out of date. The core version is 3.7.0
Library/woocommerce/myaccount/payment-methods.php
Library/woocommerce/myaccount/view-order.php
Library/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.9.0
Library/woocommerce/notices/notice.php version 1.6.4 is out of date. The core version is 3.9.0
Library/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.9.0
Library/woocommerce/order/order-again.php
Library/woocommerce/order/order-details-customer.php version 3.0.0 is out of date. The core version is 3.4.4
Library/woocommerce/order/order-details.php version 3.0.0 is out of date. The core version is 4.6.0
Library/woocommerce/product-searchform.php version 2.5.0 is out of date. The core version is 3.3.0
Library/woocommerce/single-product/add-to-cart/external.php version 2.1.0 is out of date. The core version is 3.4.0
Library/woocommerce/single-product/add-to-cart/grouped.php version 3.0.6 is out of date. The core version is 4.0.0
Library/woocommerce/single-product/add-to-cart/simple.php version 3.0.0 is out of date. The core version is 3.4.0
Library/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.5.5
Library/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.0.0 is out of date. The core version is 3.4.0
Library/woocommerce/single-product/add-to-cart/variation.php
Library/woocommerce/single-product/meta.php
Library/woocommerce/single-product/photoswipe.php
Library/woocommerce/single-product/price.php
Library/woocommerce/single-product/product-attributes.php version 3.0.0 is out of date. The core version is 3.6.0
Library/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.5.1
Library/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.5.1
Library/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.6.0
Library/woocommerce/single-product/related.php version 3.0.0 is out of date. The core version is 3.9.0
Library/woocommerce/single-product/review-meta.php version 3.0.0 is out of date. The core version is 3.4.0
Library/woocommerce/single-product/review-rating.php version 3.0.0 is out of date. The core version is 3.6.0
Library/woocommerce/single-product/review.php
Library/woocommerce/single-product/sale-flash.php
Library/woocommerce/single-product/share.php version 1.6.4 is out of date. The core version is 3.5.0
Library/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
Library/woocommerce/single-product/stock.php
Library/woocommerce/single-product/tabs/additional-information.php
Library/woocommerce/single-product/tabs/description.php
Library/woocommerce/single-product/tabs/tabs.php version 2.4.0 is out of date. The core version is 3.8.0
Library/woocommerce/single-product/title.php
Library/woocommerce/single-product/up-sells.php
Library/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 4.3.0
Library/woocommerce/single-product.php
Library/woocommerce/content-product_cat.php version 2.6.1 is out of date. The core version is 4.7.0
Library/woocommerce/taxonomy-product_cat.php version 1.6.4 is out of date. The core version is 4.7.0
Library/woocommerce/taxonomy-product_tag.php version 1.6.4 is out of date. The core version is 4.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,427
Oldest: 2020-11-01 19:50:47 -0500
Newest: 2020-12-02 11:19:19 -0500

Pending: 3
Oldest: 2020-12-02 11:25:28 -0500
Newest: 2020-12-02 11:34:19 -0500

`
```
</details>

**Comment by juliaamosova** [comment] 2020-12-04 18:49
Hi @GoranRista,

Thank you for taking the time to report this issue. However, I am not sure I can reproduce it. 

I made a video documenting my experience. I have a product with 2 downloadable files (called `Album`) where each has 1 download available and I have another product (called `downloadable`) with 1 downloadable file that has a limit of 2. In the video, I start from the moment where I just downloaded all the files (total of 3) and about to refresh the page to see if the count at the front end will get updated. And it does. I then navigate back to the product page in WP admin where I set the downloadable limit - and it is in fact still 2 since you set it for all products - it will not be reduced after customers will be downloading the file:

http://g.recordit.co/VKx1FRNSys.gif

I then navigated to the order page and saw in the `Downloadable product permissions` section there is an indication that each file had been downloaded once which is correct. There is no `Downloads remaining` section on the order page. So I am not sure if I am in the right place. Would you please clarify?

![downloads](https://user-images.githubusercontent.com/19143190/101202483-527da800-3637-11eb-90c5-5f42ddb14c9b.jpg)

**Comment by GoranRista** [comment] 2020-12-08 01:39
Hi Julia,
Thanks for looking into it.
To see the Downloads remaining, you need to click on one of the downloadable products (in the red rectangle area you have above) in order to open the drop-down options. Please see the following screenshot.

![Downloads Remaining](https://user-images.githubusercontent.com/70727701/101427086-3b0b1d00-38cc-11eb-8311-1d33e79b757c.png)

**Comment by tammullen** [comment] 2021-03-25 21:56
Hi @GoranRista 

Sorry for the delay in replying

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by zhongruige** [comment] 2021-04-08 19:53
Hi @GoranRista,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by zhongruige** 2021-04-08 19:53 UTC
Labels: needs feedback
