### ISSUE TITLE
System Status > WP Memory Limit inaccurate

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#13702] opened 2017-03-22 08:50 UTC
## EXPLANATION OF THE ISSUE

The WP Memory Limit shown under _WooCommerce > System Status > WP Memory Limit_ is often not the actual WP Memory Limit. I've had several clients over the past year(s) that referred to the WooCommerce System Status page for their memory limit, when their PHP errors actually showed a lower limit that corresponded to the WP Memory Limit.

## STEPS TO REPRODUCE THE ISSUE

Enter a low value for the WP Memory Limit on a system that has a higher PHP memory limit, for example:
``` php
define('WP_MEMORY_LIMIT', '40M');
```
on a system with 256M set in PHP.
The highest value is what [will be shown](https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/includes/api/class-wc-rest-system-status-controller.php#L496-L499).

I guess it depends on the PHP/Server configuration which memory limit will be used, and the thinking here would be that the highest value is the correct one. This does however not hold true for all setups, I have seen setups where PHP fataled on the WP_MEMORY_LIMIT where the actual available memory and the PHP Memory Limit were both higher and the issue was resolved by increasing the WP_MEMORY_LIMIT.

## PROPOSED SOLUTION

I am not entirely certain whether the WP_MEMORY_LIMIT is always followed, but I do know that the PHP Memory Limit doesn't either. I would propose to put _both_ in the report instead of [always taking the highest](https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/includes/api/class-wc-rest-system-status-controller.php#L496-L499).

e.g.:

> WP Memory Limit:		40 MB
> PHP Memory Limit:		256 MB

**Comment by mikejolley** [comment] 2017-03-22 10:38
WordPress sets the limit to WP_MEMORY_LIMIT if it can do so and if it is higher than php memory: https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/default-constants.php#L34-L59

We pull the system value if available or WP_MEMORY_LIMIT if not. This is the most accurate we can be.

> when their PHP errors actually showed a lower limit that corresponded to the WP Memory Limit.

This is a server issue. e.g. caused by setting limits in php.ini files under directories as one example. This is out of scope for our system status.

**Closed by mikejolley** 2017-03-22 10:38 UTC

**Comment by Spreeuw** [comment] 2017-03-22 10:55
Why not print both though? The use of the System Status is to detect problems. Even when this is a server issue, that may help in determining the source of an issue, which I thought is what the System Status was supposed to aid...

**Comment by mikejolley** [comment] 2017-03-22 11:03
Printing both adds to the confusion - in most cases the value should accurate unless you/the host has added custom ini files as suggested. Errors like you describe ("when their PHP errors actually showed a lower limit that corresponded to the WP Memory Limit.") cannot be detected anyway.

**Comment by Spreeuw** [comment] 2017-03-22 11:13
Not too sure about that. I've seen this in multiple instances (on my own sites no problems - it works as advertised), and increasing the WP Memory Limit solved the issue.

If the PHP Memory Limit is higher than the WP Memory limit, the response could be "try to increase your WP Memory limit to match your PHP Memory Limit".
