### ISSUE TITLE
"From" email does not reflect in emails sent to customers

### ISSUE THREAD

**Issue by MDHeshop** [woocommerce/woocommerce#28150] opened 2020-10-30 18:23 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Entered a custom "From" email in the Email settings page, but they do not reflect in the emails sent out by WooCommerce

**Expected behavior**
Emails sent out will be using the "From" address
<img width="660" alt="Screenshot 2020-10-31 at 02 10 24" src="https://user-images.githubusercontent.com/73715807/97742725-a28cba80-1b1f-11eb-83bd-ba8e967252a5.png">

**Actual behavior**
Emails received do not use the "From" address, but rather the account login address
<img width="231" alt="Screenshot 2020-10-31 at 02 12 45" src="https://user-images.githubusercontent.com/73715807/97742806-c4863d00-1b1f-11eb-888f-837b0559597f.png">
 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Settings
2. Click on Emails
3. Scroll down to "From" Address
4. See error - changes are not put into effect

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-12-29 22:58
Hi @MDHeshop,

Apologies for the delayed response! 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

![e1](https://user-images.githubusercontent.com/19143190/103319257-2ae3ea80-49ff-11eb-9bd5-b20f03ae2409.jpg)

![e2](https://user-images.githubusercontent.com/19143190/103319258-2e777180-49ff-11eb-8ea0-88d12456eca6.jpg)

Would you please confirm if the issue is present for you in WooCommerce 4.8?

Also, please make sure to test your site for theme and plugins conflict to eliminate any issues t that could be caused by 3rd party products. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2021-01-10 21:39
Hi @MDHeshop,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-01-10 21:39 UTC
Labels: category: can't reproduce, needs feedback
