### ISSUE TITLE
[GlobalStep][FireFox] Text from "Reason for refund" field appears in "Refund amount" field when the user tries to do partial refund. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29949] opened 2021-05-20 15:44 UTC
## Bug Description:
Text from "Reason for refund (optional)" field appears in the "Refund amount" field when the user tries to do partial refund for the second time.

## Environment:
Woocommerce Version : WooCommerce 5.4 Beta and 5.3
WordPress version: (v5.7)

PC:
Windows 10
Firefox(Version 88.0.1)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard.
1. Add few products to the website.
1. Create a order.
1. Navigate to WooCommerce->Orders.
1. Now click on the order link which you want to refund.
1. Scroll down and click on the "Refund" button to show Refund menu.
1. Select the Quantity, enter the partial Refund amount, add Reason for refund and click on the refund button.
1. Again click on the "Refund" button.
1. Observe that the text from "Reason for refund (optional)" field appears in the "Refund amount" field.

## Actual Result:
Text from "Reason for refund" field appears in "Refund amount" field when the user tries to do partial refund. 

## Expected Result:
Text from "Reason for refund (optional)" field should not appear in the "Refund amount" field.

## Video:

https://user-images.githubusercontent.com/41110392/119009144-76983000-b9b0-11eb-8261-f496c5e7e2cd.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
`
### WordPress Environment ###

WordPress address (URL): https://uncomfortable-iguana.jurassic.ninja
Site address (URL): https://uncomfortable-iguana.jurassic.ninja
WC Version: 5.4.0
REST API Version: ✔ 5.4.0
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.0
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.0
WC Database Prefix: wp_
Total Database Size: 5.03MB
Database Data Size: 3.36MB
Database Index Size: 1.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
customize_changeset: 5
page: 6
post: 2
product: 18
product_variation: 7
shop_order: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Google Listings and Ads: by WooCommerce – 0.5.6
Gutenberg: by Gutenberg Team – 10.6.1
Jetpack by WordPress.com: by Automattic – 9.7
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Payments: by Automattic – 2.4.0
WooCommerce: by Automattic – 5.4.0-beta.1
Test jQuery Updates: by The WordPress Team – 2.0.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 18
Oldest: 2021-05-19 07:15:45 +0000
Newest: 2021-05-20 09:47:55 +0000

### Status report information ###

Generated at: 2021-05-20 16:19:47 +00:00
`
</details>

**Comment by zhongruige** [comment] 2021-05-20 20:55
Hi @gglobalstep,

Thank you for reporting the issue. This particular issue is being caused by the WooCommerce Payments plugin. For example, I followed this flow on an account with just WooCommerce installed and the refund reason did not show in the field:

<img width="1226" alt="Screen Shot 2021-05-20 at 2 50 39 PM" src="https://user-images.githubusercontent.com/71906536/119047550-4aae8780-b97b-11eb-9759-ae767877f3b0.png">

However, this issue surfaced on an install with both WooCommerce and WooCommerce Payments:

<img width="1234" alt="Screen Shot 2021-05-20 at 2 53 28 PM" src="https://user-images.githubusercontent.com/71906536/119047603-5e59ee00-b97b-11eb-9fe6-24f44e93d3d2.png">

I am going to move your bug report there so that the right team could take a look further.

**Comment by zhongruige** [comment] 2021-05-20 20:57
Unfortunately I wasn't able to move the issue over, so I just re-created it there: https://github.com/Automattic/woocommerce-payments/issues/1877

As a result I will close this issue and we'll follow up on it on the new one.

**Comment by leonardola** [comment] 2021-09-24 14:00
Hi there. @malithsen [tested this issue](https://github.com/Automattic/woocommerce-payments/issues/1877#issuecomment-925891768) disabling WC Payments and could reproduce the bug. But only using firefox. 

> Hi @zhongruige @shendy-a8c I think this is related to Firefox remembering the input field state, which also happens to persist across page refreshes

> On Firefox with WooCommerce Payments deactivated,

> Reproducible when

> Immediately expanding the "Refund" section after making a refund
> Refreshing the page after making a refund
> Not reproducible

> Navigating away from edit order page after a refund and coming back
> On past refunds
> Adding an autocomplete=off attribute here should prevent Firefox from attempting to autofill [this field](https://github.com/woocommerce/woocommerce/blob/trunk/includes/admin/meta-boxes/views/html-order-items.php#L336).

I could also replicate what Malith said. Adding autocomplete=off fixed the problem on firefox

Can you please check that, so we can fix the problem in the correct repository? 

I am also closing the issue on Automattic/woocommerce-payments repository

**Comment by tammullen** [comment] 2021-10-01 12:42
Thank you @leonardola  for taking the time to confirm this bug, we really appreciate your help. 

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment] 2023-06-19 21:33
This issue no longer occurs. It's possible this was an issue in Firefox.

**Closed by rrennick** 2023-06-19 21:33 UTC
Labels: type: bug, priority: low, focus: refund [team:Proton], plugin: woocommerce
