### ISSUE TITLE
Woocommerce.3.6.2 Install Error

### ISSUE THREAD

**Issue by tvrwb** [woocommerce/woocommerce#23540] opened 2019-04-28 00:30 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Appearance
2.Themes
3.Add New
4.Upload Theme - woocommerce.3.6.2.zip
5.Install Now

## Expected/actual behavior

When I follow those steps, I see... "The package could not be installed" 

I was expecting to see... "Success"

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment WordPress 5.1.1 - Storefront Theme installed

<details>
Installing Theme from uploaded file: woocommerce.3.6.2.zip
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme installation failed.
</details>

**Comment by willgorham** [comment] 2019-04-28 03:29
Woocommerce is not a theme, it is a plugin. You need to install it under Plugins > Add New.

**Comment by dougaitken** [comment] 2019-04-28 15:43
Closing as the comment above identifies the cause of the error

**Closed by dougaitken** 2019-04-28 15:43 UTC
Labels: invalid
