### ISSUE TITLE
Json ID attribute for products Rich Snippets testing tool Error

### ISSUE THREAD

**Issue by globalee** [woocommerce/woocommerce#16292] opened 2017-07-29 04:09 UTC
@mikejolley  

Rich snippets testing tool gives an error on product markup
![error](https://user-images.githubusercontent.com/108716/28741991-5815775c-741b-11e7-9c23-7c13b51ce482.png)

for my site 

https://www.mineralstate.co.uk/hair-analysis-test/

modifying the class-wc-structured-data.php

adding a # to the 
`		$markup['@id']   = get_permalink( $product->get_id())."#";
		$markup['url']   = get_permalink( $product->get_id());`

lines 194 and 195

and

`		$markup['url']             = home_url()."#";
`
line  332 

and the error dissapears when tested, but review snippet has dissapeared from google search results..
is this a google rich snipets testing tool error or woocomerce?
cheers 
im a noob)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. load my url https://www.mineralstate.co.uk/hair-analysis-test/ in to https://search.google.com/structured-data/testing-tool
2. click on product
3. observe error

## Expected/actual behavior

When I follow those steps, I see... rich snippet data for product

I was expecting to see... no errors

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://www.mineralstate.co.uk
Site URL: https://www.mineralstate.co.uk
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.26 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.41.0
OpenSSL/1.0.2a

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: xx_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Academic Blogger's Toolkit: by Derek P Sifford – 4.10.0
Black Studio TinyMCE Widget: by Black Studio – 2.3.2
Comet Cache: by WebSharks
Inc. – 170220

Contact Form 7: by Takayuki Miyoshi – 4.8.1
Custom Permalinks: by Michael Tyson – 0.9.3
Google Tag Manager for Wordpress: by Thomas Geiger – 1.6.1
Easy WP SMTP: by wpecommerce – 1.2.5
Heartbeat Control: by Jeff Matson – 1.0.3
Per page head: by Erik von Asmuth – 1.4.2
Q2W3 Fixed Widget: by Max Bond – 5.0.4
SEO Ultimate: by SEO Design Solutions – 7.6.5.9
Page Builder by SiteOrigin: by SiteOrigin – 2.5.9
SiteOrigin Widgets Bundle: by SiteOrigin – 1.9.5
Speed Booster Pack: by SpeedWorks – 3.4
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce WorldPay Gateway: by Add On Enterprises (Andrew Benbow) – 3.6.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.0.4
WooCommerce: by Automattic – 3.1.1
Wordfence Security: by Wordfence – 6.3.15
Yoast SEO: by Team Yoast – 5.1
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP YouTube Lyte: by Frank Goossens (futtta) – 1.6.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Basket: #26 - /cart/
Checkout: #27 - /checkout/
My account: #28 - /my-account/

### Theme ###

Name: 
Version: 1.0.0
Author URL: http://www.kadencethemes.com/
Child Theme: ✔
Parent Theme Name: Virtue - Premium
Parent Theme Version: 4.2.5
Parent Theme Author URL: https://www.kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: virtue_premium/woocommerce/archive-product.php
virtue_premium/woocommerce/content-product.php
virtue_premium/woocommerce/content-product_cat.php
virtue_premium/woocommerce/content-single-product.php
virtue_premium/woocommerce/loop/loop-end.php
virtue_premium/woocommerce/loop/loop-start.php
virtue_premium/woocommerce/loop/rating.php
virtue_premium/woocommerce/loop/sale-flash.php
virtue_premium/product-searchform.php
virtue_premium/woocommerce/single-product/add-to-cart/external.php
virtue_premium/woocommerce/single-product/add-to-cart/grouped.php
virtue_premium/woocommerce/single-product/add-to-cart/simple.php
virtue_premium/woocommerce/single-product/add-to-cart/variable.php
virtue_premium/woocommerce/single-product/product-image.php
virtue_premium/woocommerce/single-product/product-thumbnails.php
virtue_premium/woocommerce/single-product/related.php
virtue_premium/woocommerce/single-product/sale-flash.php
virtue_premium/woocommerce/single-product/title.php
virtue_premium/woocommerce/single-product/up-sells.php
virtue_premium/woocommerce/single-product.php
virtue_premium/woocommerce/taxonomy-product_cat.php
virtue_premium/woocommerce/taxonomy-product_tag.php
```
</details>

**Comment by opportus** [comment] 2017-07-29 08:02
Hello @globalee, does the error appear also when you test one of your product categories with the default jsonLD?

**Comment by opportus** [comment] 2017-07-29 08:15
As debug information...

- The test on product categories with default jsonLD doesn't show any error.
- Adding a `#` at the end of the `@id` value on single products, doesn't throw any error anymore and everything seems fine.

**Comment by globalee** [comment] 2017-07-29 11:52
When you take the source and paste directly in to the code box and test everything works no error. (without the #)

so cannot assertain if its only an error when you fetch with URL (in rich snippets testing tool)

Ive removed the # as there is no way to modify the file and put in child theme, you had to change the main file.

Also **this product page has error** https://www.mineralstate.co.uk/vitamin-c-plus/

**But preview is available**, whereas in the **other URL that HAS reviews**

![error1](https://user-images.githubusercontent.com/108716/28744611-6befca48-745c-11e7-9ed8-1a66e13a89bb.png)


**But preview is not available** 

![error2](https://user-images.githubusercontent.com/108716/28744620-974bdc72-745c-11e7-825b-fb54b4bbebc6.png)

So still sure....

**Comment by SensicalCat** [comment] 2017-07-30 10:25
ok, it is funky monkey.
For a product page;

I can confirm this same issue with SDTT on my site when fetching URL.
"is not a known valid target type for the identifier property."

I can confirm that copy/paste rendered page does not produce error.

additionally, I have found the following does not create error.
1. removing esc slashes.
2. using # at the end of url.
3. removing trailing slash.
4. adding the postID at the end of URI @id.

**Comment by kiranin1989** [comment] 2017-07-30 14:12
Confirm, I am having the same issue on my website.
What is the exact solution? just adding # as suggested by users above?
Or is there more perfect/permanent code fix for this issue?

**Comment by opportus** [comment] 2017-07-31 09:29
Looks like this is a SDTT bug:
https://productforums.google.com/forum/#!topic/webmasters/-zTFLScuciA

**Comment by opportus** [comment] 2017-07-31 14:37
Hi @SensicalCat,

Actually, removing escaped slashes valids the SD only when you apply this change via the SDTT. Applying this change directly in code still won't valid the SD. In fact, even putting some kind of invalid SD via the SDTT editor box, then submitting it, will valid your SD. This is for sure a SDTT bug.

Looks like the SDTT doesn't valid `@id` values with a trailing slash. Not sure this is the behavior Google wants...

**Comment by globalee** [comment] 2017-08-01 15:18
@opportus
Hi, I enabled breadcrumbs it did not fix the issue with preview being enabled in GRSTT.
(NB:have removed breadcrums no as it did ot fix issue)

[https://www.mineralstate.co.uk/hair-analysis-test/](url)
1. single product
2. multiple reviews
3. no preview enabled in GRSTT

Vs
[https://www.mineralstate.co.uk/para-pack-formula-b/](url)
1. single product
2. no reviews
3. preview enabled in GRSTT

regards

**Comment by opportus** [comment] 2017-08-01 15:40
@globalee, pretty hard for me to help you...

First, you have multiple plugins succeptible to interfer with the WC SD output...
And second, since the Google Structured Data Testing Tool seems pretty unreliable at the moment, I'm not sure **its** missing "Preview" button is the responsability of WC...

**Comment by globalee** [comment] 2017-08-01 15:55
Ok but my star rating from google rich snippets dissapeard from google at the same time, hence why I think its woocomerce?

**Comment by mikejolley** [comment] 2017-08-03 07:07
Seems to be the testing tool. I think the schema itself is fine.

**Closed by mikejolley** 2017-08-03 07:07 UTC
