### ISSUE TITLE
Subtotal Calculation Incorrect 

### ISSUE THREAD

**Issue by Novy85** [woocommerce/woocommerce#29908] opened 2021-05-14 15:18 UTC
**Prerequisites` (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Subtotal calculation is incorrect and so the order total is wrong, when there is more than one product.

- I set the rounding to subtotal level
- Price entered inclusive taxes 
- Add a tax rate of 22%
- Show total taxes by object
- 2 decimals to shows in frontend
- Products have 2 decimals also in backend

Like in the screen attached my example is of a product that costs €13,63 (11,17 without taxes).

- Add 9 of these products in the cart
- Subtotal is 100,55 and IVA 22,12, instead of 100,53 and IVA 22,12

Moreover, the more products you add, the more wrong the calculation will result.

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

![Cattura](https://user-images.githubusercontent.com/6589859/118291823-49dba880-b4d8-11eb-860c-a11e98cfe1dc.PNG)

### WordPress Environment ###
<details>
WordPress address (URL): https://www.eaglemegastore.it
Site address (URL): https://www.eaglemegastore.it
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.16
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.28-MariaDB-cll-lve
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wpen_
Dimensione totale database: 4327.01MB
Dimensione dati database: 4215.70MB
Dimensione indice database: 111.31MB
wpen_woocommerce_sessions: Dati: 4050.64MB + indice: 72.84MB + motore MyISAM
wpen_woocommerce_api_keys: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_attribute_taxonomies: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_downloadable_product_permissions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_order_items: Dati: 0.03MB + indice: 0.02MB + motore MyISAM
wpen_woocommerce_order_itemmeta: Dati: 0.18MB + indice: 0.12MB + motore MyISAM
wpen_woocommerce_tax_rates: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_woocommerce_tax_rate_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_shipping_zones: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_shipping_zone_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_shipping_zone_methods: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_payment_tokens: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_payment_tokenmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_woocommerce_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
mofluidadmin_android: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mofluidadmin_details: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mofluidadmin_iphone: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mofluidpayment: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mofluidpush_settings: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mofluid_build_accounts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpen_actionscheduler_actions: Dati: 0.35MB + indice: 0.14MB + motore MyISAM
wpen_actionscheduler_claims: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_actionscheduler_groups: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_actionscheduler_logs: Dati: 0.21MB + indice: 0.15MB + motore MyISAM
wpen_adtribes_my_conversions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_aws_cache: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_album: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_album_gallery: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_gallery: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_image: Dati: 0.05MB + indice: 0.00MB + motore MyISAM
wpen_bwg_image_comment: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_image_rate: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_image_tag: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_shortcode: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_bwg_theme: Dati: 0.04MB + indice: 0.00MB + motore MyISAM
wpen_cf_forms: Dati: 0.02MB + indice: 0.00MB + motore MyISAM
wpen_cf_form_entries: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_cf_form_entry_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_cf_form_entry_values: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_cf_pro_messages: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_cf_tracking: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_cf_tracking_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_commentmeta: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_comments: Dati: 0.12MB + indice: 0.06MB + motore MyISAM
wpen_ddp_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_es_deliverreport: Dati: 0.40MB + indice: 0.04MB + motore MyISAM
wpen_es_emaillist: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpen_es_notification: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_es_sentdetails: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpen_es_subscriber_ips: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_es_templatetable: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_fs_page_builder: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpen_fs_page_builder_items: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpen_fs_sliders: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_fs_slides: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_gdpr_cc_options: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpen_gglcptch_allowlist: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpen_ig_actions: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wpen_ig_blocked_emails: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ig_campaigns: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ig_contactmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpen_ig_contacts: Dati: 0.26MB + indice: 0.02MB + motore MyISAM
wpen_ig_contacts_ips: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ig_forms: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ig_links: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpen_ig_lists: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ig_lists_contacts: Dati: 0.09MB + indice: 0.03MB + motore MyISAM
wpen_ig_mailing_queue: Dati: 0.02MB + indice: 0.00MB + motore MyISAM
wpen_ig_queue: Dati: 0.02MB + indice: 0.13MB + motore InnoDB
wpen_ig_sending_queue: Dati: 0.67MB + indice: 0.08MB + motore MyISAM
wpen_links: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_litespeed_img_optm: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ms_snippets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nextend2_image_storage: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nextend2_section_storage: Dati: 0.02MB + indice: 0.01MB + motore MyISAM
wpen_nextend2_smartslider3_generators: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nextend2_smartslider3_sliders: Dati: 0.03MB + indice: 0.00MB + motore MyISAM
wpen_nextend2_smartslider3_sliders_xref: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nextend2_smartslider3_slides: Dati: 0.03MB + indice: 0.01MB + motore MyISAM
wpen_nf3_actions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_action_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_chunks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_field_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_forms: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_form_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_objects: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_object_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_relationships: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_nf3_upgrades: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpen_onclick_popup_plugin: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_options: Dati: 7.22MB + indice: 0.50MB + motore MyISAM
wpen_pmxe_exports: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_pmxe_google_cats: Dati: 0.26MB + indice: 0.05MB + motore MyISAM
wpen_pmxe_posts: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_pmxe_templates: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_pmxi_files: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_pmxi_hash: Dati: 1.12MB + indice: 1.09MB + motore MyISAM
wpen_pmxi_history: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_pmxi_images: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpen_pmxi_imports: Dati: 0.17MB + indice: 0.00MB + motore MyISAM
wpen_pmxi_posts: Dati: 1.45MB + indice: 0.19MB + motore MyISAM
wpen_pmxi_templates: Dati: 0.58MB + indice: 0.00MB + motore MyISAM
wpen_postmeta: Dati: 117.19MB + indice: 23.06MB + motore MyISAM
wpen_posts: Dati: 25.94MB + indice: 4.97MB + motore MyISAM
wpen_ps_exclude: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ps_postmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ps_posts: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_ps_product_sku: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_revslider_css: Dati: 0.09MB + indice: 0.00MB + motore MyISAM
wpen_revslider_layer_animations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_revslider_navigations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_revslider_sliders: Dati: 0.06MB + indice: 0.00MB + motore MyISAM
wpen_revslider_slides: Dati: 0.09MB + indice: 0.00MB + motore MyISAM
wpen_revslider_static_slides: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_say_what_strings: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_snippets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_termmeta: Dati: 0.06MB + indice: 0.06MB + motore MyISAM
wpen_terms: Dati: 0.01MB + indice: 0.03MB + motore MyISAM
wpen_term_relationships: Dati: 1.24MB + indice: 2.59MB + motore MyISAM
wpen_term_taxonomy: Dati: 0.01MB + indice: 0.02MB + motore MyISAM
wpen_ucare_logs: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpen_usermeta: Dati: 0.21MB + indice: 0.11MB + motore MyISAM
wpen_users: Dati: 0.01MB + indice: 0.02MB + motore MyISAM
wpen_wcpdf_invoice_number: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wcpdf_receipt_number: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wc_admin_notes: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpen_wc_admin_note_actions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wc_category_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wc_customer_lookup: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_wc_download_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wc_order_coupon_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wc_order_product_lookup: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_wc_order_stats: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_wc_order_tax_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wc_product_meta_lookup: Dati: 0.73MB + indice: 0.85MB + motore MyISAM
wpen_wc_reserved_stock: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wc_tax_rate_classes: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_wc_webhooks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfBadLeechers: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfBlockedCommentLog: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfBlockedIPLog: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfBlocks7: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfConfig: Dati: 0.02MB + indice: 0.01MB + motore MyISAM
wpen_wfCrawlers: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wpen_wfFileChanges: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfFileMods: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfHits: Dati: 0.81MB + indice: 0.21MB + motore MyISAM
wpen_wfHoover: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfIssues: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfKnownFileList: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfLeechers: Dati: 0.02MB + indice: 0.02MB + motore MyISAM
wpen_wfLiveTrafficHuman: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfLocs: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfLogins: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfNotifications: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfPendingIssues: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfReverseCache: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfScanners: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_wfSNIPCache: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfStatus: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wfVulnScanners: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wotv_woo_track_info: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpbackitup_job_control: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpbackitup_job_items: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpbackitup_job_tasks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpmailsmtp_tasks_meta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpen_wpmcleaner: Dati: 0.06MB + indice: 0.01MB + motore MyISAM
wpen_wpsp_agent_assign_data: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_agent_settings: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_attachments: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_canned_reply: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_catagories: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_custom_fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_custom_priority: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_custom_status: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_faq: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_faq_catagories: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_panel_custom_menu: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_support_menu: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_ticket: Dati: 0.00MB + indice: 0.02MB + motore MyISAM
wpen_wpsp_ticket_form_order: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_ticket_list_order: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_wpsp_ticket_thread: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_wpsp_users: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_yith_wcwl: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_yith_wcwl_lists: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_yoast_indexable: Dati: 0.39MB + indice: 0.11MB + motore MyISAM
wpen_yoast_indexable_hierarchy: Dati: 0.02MB + indice: 0.06MB + motore MyISAM
wpen_yoast_migrations: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpen_yoast_primary_term: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpen_yoast_seo_links: Dati: 0.74MB + indice: 0.20MB + motore MyISAM
wpen_yoast_seo_meta: Dati: 3.68MB + indice: 3.11MB + motore MyISAM

### Post Type Counts ###

attachment: 47735
bwg_album: 1
bwg_gallery: 1
customize_changeset: 11
custom_css: 2
email_template: 6
es_template: 2
ml-slider: 1
nav_menu_item: 31
nf_sub: 5
option-tree: 1
page: 34
popup: 1
popup_theme: 6
post: 2
postman_sent_mail: 250
product: 7999
revision: 37
shop_coupon: 2
shop_order: 147
shop_order_refund: 6
termpopup: 1
turbo-sidebar-cpt: 2
wcps: 1
woo_discount: 1
wpcf7_contact_form: 1
wpmm_theme: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.3.0

### Inactive Plugins (42) ###

AddToAny Share Buttons: by AddToAny – 1.7.44
Advanced Database Cleaner: by Younes JFR. – 3.0.0
Akismet Anti-Spam: by Automattic – 4.1.9
Anti-Spambot Email Shortcode: by Robert Peake – 1.1.6
Classic Editor: by WordPress Contributors – 1.6
Contact Form 7: by Takayuki Miyoshi – 5.4.1
Dash Notifier: by LiteSpeed Technologies – 1.2
Email Address Encoder: by Till Krüss – 1.0.22
Featured Image from URL (FIFU) Premium: by fifu.app – 5.0.9
GDPR Cookie Compliance (CCPA, PIPEDA ready): by Moove Agency – 4.5.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.17.0
Google XML Sitemaps: by Auctollo – 4.1.1
LiteSpeed Cache: by LiteSpeed Technologies – 3.6.4
Orders Tracking for WooCommerce: by VillaTheme – 1.1.8.5
reCaptcha by BestWebSoft: by BestWebSoft – 1.61
Simple Registration for WooCommerce: by Astoundify – 1.5.3
Slider Revolution: by ThemePunch – 5.2.6
Smart Slider 3: by Nextend – 3.4.1.17
WC Speed Drain Repair: by WP Fix It – 1.3
Widgets On Pages: by Todd Halfpenny – 1.5.0
WooCommerce Category Images Modification: by Ashfame – 0.1.2
WooCommerce Italian Add-on Plus: by laboratorio d'Avanguardia – 0.7.2.32
WooCommerce My Account Widget: by PEP – 0.6.6
WooCommerce Pay for Payment: by Karolína Vyskočilová – 2.0.18
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.8.3
WooCommerce PDF Invoices & Packing Slips dompdf 0.8.3: by Ewout Fernhout – 1.0.0
WooCommerce Tree Table Rate Shipping: by tablerateshipping.com – 1.17.2
Woofluid: by Ebizon – 1.0
WP Add Custom CSS: by Daniele De Santis – 1.1.6
WP All Import - User Import Add-On Pro: by Soflyy – 1.1.5
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.2.5
WP All Import Pro: by Soflyy – 4.6.5
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
WP Content Copy Protection & No Right Click (premium): by wp-buy – 9.5
WP Mail SMTP: by WPForms – 2.8.0
Wp Presscart Android: by Ebizon – 1.0
Wp Presscart Iphone: by Ebizon – 1.0
Wp Presscart menu: by Ebizon – 1.0
XML for Google Merchant Center: by Maxim Glazunov – 2.2.3
YITH WooCommerce Wishlist: by YITH – 3.0.11
Yoast SEO: by Team Yoast – 16.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: db.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /negozio/
Carrello: #5 - /carrello/
Pagamento: #6 - /checkout/
Il mio account: #7 - /mio-account/
Termini e condizioni: #78 - /informativa-sulla-privacy/

### Theme ###

Name: Storefront
Version: 3.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completato: 1.210
Oldest: 2021-04-26 10:10:54 +0200
Newest: 2021-05-14 17:13:16 +0200

### Status report information ###

Generated at: 2021-05-14 17:14:30 +02:00
`
```
</details>

**Comment by zhongruige** [comment] 2021-05-18 21:51
Hi @Novy85,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. I tested on the following:

* WooCommerce 5.3.0
* WordPress 5.7.2

Replication steps

* I imported the default products and set up a fresh install of WooCommerce
* I configured the following in my Tax settings:

<img width="702" alt="Screen Shot 2021-05-18 at 3 31 58 PM" src="https://user-images.githubusercontent.com/71906536/118727642-4dc93c80-b7f0-11eb-84e5-3661c1f121c3.png">

* Then I set a tax rate of 22%:

<img width="1548" alt="Screen Shot 2021-05-18 at 3 32 35 PM" src="https://user-images.githubusercontent.com/71906536/118727672-5ae62b80-b7f0-11eb-8a91-526c5a52a0e4.png">

* I then placed an order for a product and verified the rounding is incorrect. For example, in this screenshot, it shows `132,79€` in the total column, when it should only be `132,75€` (14,75 * 9).

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by Novy85** [comment] 2021-05-19 09:56
@zhongruige really thank you for your interest and reply.

**Comment by Novy85** [comment] 2021-07-08 10:19
Any update of the issue?

**Comment by wpnetninjas** [comment] 2021-07-12 22:34
@mikejolley Can we please get an update on this tax rounding issue?

**Comment by wpnetninjas** [comment] 2021-07-12 23:00
The issue in our case was not actually the tax rounding, but the decimal display for WooCommerce cart totals. The issue was resolved via the following function

add_filter( 'wc_get_price_decimals', 'change_prices_decimals', 20, 1 );
function change_prices_decimals( $decimals ){
    if( is_cart() || is_checkout() )
        $decimals = 2;
    return $decimals;
}

**Comment by Novy85** [comment] 2021-07-13 08:43
> The issue in our case was not actually the tax rounding, but the decimal display for WooCommerce cart totals. The issue was resolved via the following function
> 
> add_filter( 'wc_get_price_decimals', 'change_prices_decimals', 20, 1 );
> function change_prices_decimals( $decimals ){
> if( is_cart() || is_checkout() )
> $decimals = 2;
> return $decimals;
> }

I'm happy you find a solution, I hope that also my issue could be resolved.

**Comment by peterfabian** [comment] 2021-10-18 16:06
Related: p7bje6-3ef-p2
and
https://github.com/woocommerce/woocommerce/issues/27026#issuecomment-738913704

**Comment by peterfabian** [comment] 2021-10-18 16:11
1. Write a documentation post explaining what works and what doesn't
2. Update the settings to display a link to the doc when settings are 'incorrect'

**Comment by lenamtl** [comment] 2021-10-20 17:54
Hi

@wpnetninjas
Could you share how to display subtotal before taxes, does this value is saved in DB?
https://github.com/woocommerce/woocommerce/issues/29908#issuecomment-852715896

**Comment by vedanshujain** [comment] 2021-12-06 10:40
@Novy85 This is happening because rounding is done at subtotal level, instead of at unit level, so technically price before tax is not 11.17, but instead 11.172131. You are seeing this inconsistency because in the admin view, we always display price before tax and they are rounded for display convenience.

This is generally correct for accounting purposes (although you should consult an accountant professional anyway for your local area rules), as long as prices are displayed to customers including taxes as well. For example, I configured my test shop with your rules and see accurate calculations on frontend from the customer's point of view:

<img width="356" alt="Screenshot 2021-12-06 at 3 49 41 PM" src="https://user-images.githubusercontent.com/7571618/144829095-ad443e01-6216-47da-8048-7aa5447273b1.png">

If we round at unit level here, then the customer would see a total of 122.65 which is different from 13.63 x 9. So as you can see calculations behind the scenes are correct based on the settings.

That said, if you'd like accurate calculations in the backend as well, you can enter prices excluding taxes. In this case, it would also be recommended to display prices in the shop excluding taxes as well.

I am closing this issue for repository maintenance and there is nothing for us to do for now, but feel free to reply back with further comments and we will re-open.

**Closed by vedanshujain** 2021-12-06 10:40 UTC
Labels: type: bug, priority: high, component: order

**Comment by rigaleb** [comment] 2022-03-16 18:24
@vedanshujain Hello!
I'm confused in regards to how the tax is calculated. Let s say I enter the prices excluding tax and also display them excluding tax and then display the tax at the bottom. In the backend, how exactly is the tax calculated? for the whole subtotal or for each line and then added all up and then rounded? It's very importamt because it matters how my invoicing software reads the order details. Thanks.

**Comment by curtbeck** [comment] 2022-07-14 09:49
Hello, we have the same problem with rounding taxes (gross price per unit) for unit and not totals. Is there any solution that solves the problem (plugin or code snippet)? That issue is around !!!5 years old!!!, what a shame.

Thanks for any help.
