### ISSUE TITLE
Percatnge Discount on page

### ISSUE THREAD

**Issue by mukesh24932** [woocommerce/woocommerce#30215] opened 2021-07-05 03:28 UTC
how to create a page where show 50% product- or 40 % products default woo-commerce support onsale products only also no use tag is hard to me, I won't create a page with a shortcode where show products who discount with a percentage

**Comment by juliaamosova** [comment] 2021-07-09 17:54
Hi @mukesh24932,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-07-09 17:54 UTC
