### ISSUE TITLE
Download Permissions not generated for variable products

### ISSUE THREAD

**Issue by DrMTR** [woocommerce/woocommerce#20738] opened 2018-07-10 07:37 UTC
**Describe the bug**
I have set variable product that have download permissions on some of it. File is regularry set for each downloadeble variation. When checkout, just get something like this:

https://i.imgur.com/gc8pVZC.png?1

**To Reproduce**
1. Set "Variable Product" into Woocommerce
2. On Variation tick "Downloadable" ( https://i.imgur.com/dbCjhYT.png?1 )
3. Set File for download (in my case Dropbox external file)
4. Place the same error for selected variation that set before. No download link included into order or mail.

**NOTE: This issue is present JUST for variable product, for Single Product download links are send just fine.**

**Screenshots**
Included into Description before.

**Expected behavior**
Expect to get download link into mail to customer.
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

WordPress environment
--
Home URL: |   | https://www.yearofthedurian.com
Site URL: |   | https://www.yearofthedurian.com
WooCommerce version: |   | 3.4.3
Log directory writable: |   | /home/yearofu1/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.7
WordPress multisite: |   | –
WordPress memory limit: |   | 768 MB
WordPress debug mode: |   |  
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

Server environment
--
Server info: |   | Apache
PHP version: |   | 7.2.5
PHP post max size: |   | 128 MB
PHP time limit: |   | 120
PHP max input vars: |   | 1000
cURL version: |   | 7.59.0, OpenSSL/1.0.2k
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.36-82.1-log
Max upload size: |   | 128 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |  

Database
--
WooCommerce database version: |   | 3.4.3
Database prefix |   | wp_q5i7bv1_
MaxMind GeoIP database: |   | /home/yearofu1/public_html/wp-content/uploads/GeoLite2-Country.mmdb
Total Database Size |   | 66.19MB
Database Data Size |   | 61.42MB
Database Index Size |   | 4.77MB
wp_q5i7bv1_woocommerce_sessions |   | Data: 0.37MB + Index: 0.02MB
wp_q5i7bv1_woocommerce_api_keys |   | Data: 0.00MB + Index: 0.01MB
wp_q5i7bv1_woocommerce_attribute_taxonomies |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_woocommerce_downloadable_product_permissions |   | Data: 0.00MB + Index: 0.01MB
wp_q5i7bv1_woocommerce_order_items |   | Data: 0.03MB + Index: 0.02MB
wp_q5i7bv1_woocommerce_order_itemmeta |   | Data: 0.19MB + Index: 0.13MB
wp_q5i7bv1_woocommerce_tax_rates |   | Data: 0.00MB + Index: 0.01MB
wp_q5i7bv1_woocommerce_tax_rate_locations |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_woocommerce_shipping_zones |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_woocommerce_shipping_zone_locations |   | Data: 0.00MB + Index: 0.01MB
wp_q5i7bv1_woocommerce_shipping_zone_methods |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_woocommerce_payment_tokens |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_woocommerce_payment_tokenmeta |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_woocommerce_log |   | Data: 0.02MB + Index: 0.02MB
wp_q5i7bv1_aff_affiliates |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_aff_affiliates_users |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_aff_hits |   | Data: 0.06MB + Index: 0.12MB
wp_q5i7bv1_aff_referrals |   | Data: 0.00MB + Index: 0.01MB
wp_q5i7bv1_aff_referral_items |   | Data: 0.02MB + Index: 0.05MB
wp_q5i7bv1_aff_robots |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_aff_uris |   | Data: 0.02MB + Index: 0.03MB
wp_q5i7bv1_aff_user_agents |   | Data: 0.02MB + Index: 0.02MB
wp_q5i7bv1_commentmeta |   | Data: 1.47MB + Index: 0.29MB
wp_q5i7bv1_comments |   | Data: 1.06MB + Index: 0.25MB
wp_q5i7bv1_download_log |   | Data: 0.38MB + Index: 0.07MB
wp_q5i7bv1_failed_jobs |   | Data: 0.04MB + Index: 0.00MB
wp_q5i7bv1_gravatars |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_huge_itslider_images |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_huge_itslider_params |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_huge_itslider_sliders |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_layerslider |   | Data: 0.03MB + Index: 0.00MB
wp_q5i7bv1_links |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_mailchimp_carts |   | Data: 0.05MB + Index: 0.00MB
wp_q5i7bv1_ngg_album |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_ngg_gallery |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_ngg_pictures |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_assets |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_launchfunnels |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_launchfunnels_pages |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_layout_categories |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_pb_products |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_post_layouts |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_predefined_layouts |   | Data: 0.03MB + Index: 0.00MB
wp_q5i7bv1_optimizepress_presets |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_options |   | Data: 18.94MB + Index: 0.09MB
wp_q5i7bv1_postmeta |   | Data: 17.41MB + Index: 1.99MB
wp_q5i7bv1_posts |   | Data: 20.46MB + Index: 0.99MB
wp_q5i7bv1_prli_clicks |   | Data: 0.41MB + Index: 0.29MB
wp_q5i7bv1_prli_groups |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_prli_links |   | Data: 0.00MB + Index: 0.03MB
wp_q5i7bv1_prli_link_metas |   | Data: 0.00MB + Index: 0.01MB
wp_q5i7bv1_queue |   | Data: 0.03MB + Index: 0.00MB
wp_q5i7bv1_termmeta |   | Data: 0.02MB + Index: 0.02MB
wp_q5i7bv1_terms |   | Data: 0.01MB + Index: 0.02MB
wp_q5i7bv1_term_relationships |   | Data: 0.04MB + Index: 0.08MB
wp_q5i7bv1_term_taxonomy |   | Data: 0.01MB + Index: 0.01MB
wp_q5i7bv1_usermeta |   | Data: 0.14MB + Index: 0.09MB
wp_q5i7bv1_users |   | Data: 0.01MB + Index: 0.01MB
wp_q5i7bv1_wc_download_log |   | Data: 0.02MB + Index: 0.03MB
wp_q5i7bv1_wc_webhooks |   | Data: 0.02MB + Index: 0.02MB
wp_q5i7bv1_woocommerce_termmeta |   | Data: 0.00MB + Index: 0.00MB
wp_q5i7bv1_yoast_seo_links |   | Data: 0.09MB + Index: 0.02MB
wp_q5i7bv1_yoast_seo_meta |   | Data: 0.02MB + Index: 0.00MB

Active plugins (37)
--
LayerSlider WP |   | by Kreatura Media – 5.6.2
Affiliates WooCommerce Light |   | by itthinx – 1.3.3 – Not tested with the active version of WooCommerce
Affiliates |   | by itthinx – 3.0.1
Akismet Anti-Spam |   | by Automattic – 4.0.7
amr shortcode any widget |   | by anmari – 3.6
Blogger 301 Redirect |   | by Sudipto Pratap Mahato – 2.5.2
Cloudflare |   | by John Wineman, Furkan Yilmaz, Junade Ali (Cloudflare Team) – 3.3.2
Download Monitor |   | by Never5 – 4.1.0
WordPress Editorial Calendar |   | by Colin Vernon, Justin Evans, Joachim Kudish, Mary Vogt, and Zack Grossbart – 3.6.8
File Manager |   | by Aftabul Islam – 5.0.2
Genesis Grid |   | by Bill Erickson – 1.4.2
Genesis Title Toggle |   | by Bill Erickson – 1.8.0
Image Regenerate & Select Crop |   | by Iulia Cazan – 4.2.2
Instagram Gallery |   | by Karan Singh – 1.6.1
Jetpack by WordPress.com |   | by Automattic – 6.2.1
MailChimp for WooCommerce |   | by MailChimp – 2.1.7 – Not tested with the active version of WooCommerce
MailChimp for WordPress |   | by ibericode – 4.2.3
Metorik Helper |   | by Metorik – 0.15.0 – Not tested with the active version of WooCommerce
PHP Compatibility Checker |   | by WP Engine – 1.4.5
PixelYourSite |   | by PixelYourSite – 5.3.1 – Not tested with the active version of WooCommerce
Pretty Links |   | by Blair Williams – 2.1.6
Printful Integration for WooCommerce |   | by Printful – 2.0.2 – Not tested with the active version of WooCommerce
Public Post Preview |   | by Dominik Schilling – 2.6.0
Q2W3 Fixed Widget |   | by Max Bond – 5.1.4
SB-RSS_feed-plus |   | by Ladislav Soukup (ladislav.soukup@gmail.com) – 1.4.20
SG Optimizer |   | by SiteGround – 4.0.7
SumoMe |   | by SumoMe – 1.29
Compress JPEG & PNG images |   | by TinyPNG – 2.2.6
WooCommerce QR Codes |   | by Subrata Mal – 1.1.0 – Not tested with the active version of WooCommerce
WooCommerce Dropbox |   | by Vadiem Janssens – 1.1.1 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway |   | by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Menu Cart |   | by Jeremiah Prummer, Ewout Fernhout – 2.7.1 – Not tested with the active version of WooCommerce
WooCommerce Services |   | by Automattic – 1.6.2 – Not tested with the active version of WooCommerce
WooCommerce |   | by Automattic – 3.4.3
Yoast SEO |   | by Team Yoast – 7.6.1
WP Responsive Menu |   | by MagniGenie – 3.0.3
WP Engine Automated Migration |   | by WPEngine – 1.66

</details>

**Comment by claudiulodro** [comment] 2018-07-10 21:03
Hi there.

I wasn't able to reproduce the issue on a site running just WooCommerce; variation downloads worked fine. 

I see you are using the WooCommerce Dropbox plugin which hasn't been updated in years. Your problems could be caused by that, and I recommend deactivating the plugin and setting the downloadable files using the regular WooCommerce interface. The problems may also be caused by Download Monitor or one of your other active plugins that potentially affects downloadable files on WP.

I'm going to close this issue as non-reproducible since it seems to be caused by plugin conflicts. If you can reproduce it on a site with only WooCommerce and no other active plugins please let me know the steps and I'll reopen this issue.

Thanks.

**Closed by claudiulodro** 2018-07-10 21:03 UTC

**Comment by DrMTR** [comment] 2018-07-11 10:53
Hi, i disabled both plugins and issue is still there. So not seems that is plugin related, because also other peoples issued this problem.

https://github.com/woocommerce/woocommerce/issues/19591
