### ISSUE TITLE
Edit product image - bug

### ISSUE THREAD

**Issue by lukecassar** [woocommerce/woocommerce#25866] opened 2020-03-10 20:49 UTC
Updated woocommerce, got the following issues.

Product image - refreshing page
Upload gallery - Not working either
Other woocommerce plugins + are not working properly. (Gravity form not showing)

**Comment by juliaamosova** [comment] 2020-03-10 20:59
Hi @lukecassar,

Thank you for raising the issue. However, it is not complete for us to take any action on it. 
>Product image - refreshing page

Can you please provide a bit more details? Are you trying to upload a new image to the product and the page is refreshing? 

>Upload gallery - Not working either

Can you please provide details explaining what happens? 

>Other woocommerce plugins + are not working properly. (Gravity form not showing)

This is very broad and is likely related to the individual plugin used on the site. I recommend you reach out to each plugin developer to see with them what could be going wrong.

**Comment by lukecassar** [comment] 2020-03-10 21:26
Hi, yes no problem.

Scenerio 1 - 

New product - Press on product image
![1](https://user-images.githubusercontent.com/49267454/76360585-9304fb00-631d-11ea-80c8-bee094a76729.JPG)

This loads. Which does not let you do much.
![2](https://user-images.githubusercontent.com/49267454/76360589-939d9180-631d-11ea-9d51-6288ead35246.JPG)


If i press the add to gallery.
![3](https://user-images.githubusercontent.com/49267454/76360651-b4fe7d80-631d-11ea-8191-688993d10c0d.JPG)

Nothing happens.

Scene 2 - Edit an already exsisting product with images.

When i press on the 'Set product image', actually what it does is scroll to the top, thats it.
![4](https://user-images.githubusercontent.com/49267454/76360846-1d4d5f00-631e-11ea-9bad-45cb76fd3ac2.JPG)

![5](https://user-images.githubusercontent.com/49267454/76360881-250d0380-631e-11ea-8eb1-55479a31e9bf.JPG)


When i press edit gallery, nothing happens. 

Hope this helps

**Comment by lukecassar** [comment] 2020-03-10 21:28
Note - installed the version prior to this, and the images worked fine.

Gravity Form is now working fine.

**Comment by lukecassar** [comment] 2020-03-10 21:31
@juliaamosova

**Comment by juliaamosova** [comment] 2020-03-10 21:49
@lukecassar thanks for the additional details. I can't reproduce the issue you are having.

Adding new images to a product without images:

![](http://g.recordit.co/FQkq2HzXu1.gif)

Editing an existing image of an existing product: 

![](http://g.recordit.co/Za3qggpuqX.gif)

Do you have many plugins installed? Do you use one of our default themes? Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by lukecassar** [comment] 2020-03-10 22:20
Hi @juliaamosova ,

An popup to update the database, just showed up.

Updated database and now working fine.

Thankyou for your quick response.

**Comment by juliaamosova** [comment] 2020-03-10 22:22
@lukecassar great to know the issue is now resolved. Thanks for letting me know! I am closing this issue for now.

**Closed by juliaamosova** 2020-03-10 22:22 UTC
Labels: status: needs feedback
