### ISSUE TITLE
Woocommerce Bug is being ignored 

### ISSUE THREAD

**Issue by Trevorlonewolf** [woocommerce/woocommerce#30008] opened 2021-05-30 20:36 UTC
My Account end points in woocommerce suddenly stop working !!  This is a serious bug that you havent bothered to fix WHY NOT ? I now sit with a site thats completely useless to me because you clowns are too lazy, stupid or just not interested in fixing. Since there are 100s of complaints regarding this. It can only be one of the those 3 excuses mentioned.  I must say you guys are not the brightest if you did not know this already! So i need to know HOW TO FIX THIS NOW PLEASE!!

**Comment by tammullen** [comment] 2021-05-31 20:12
Hi @Trevorlonewolf 

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Trevorlonewolf** [comment] 2021-06-01 03:29
Hi Tam 

Ok Im going to explain this as simply as I can like to a child Its actually very simple 

 

Firstly my links from My account failed over night 

Here is the “advanced” section of woocommerce showing the end points 

These PAGE SETUPS initially did not have an “ID” This is what created the failure 

I fixed each link with the new page name seen here


 

 

 



 

Now this is an example of one of the links 

 



 

This new link never works I tried changing the name as above in one of the links to “new-addresses” This does not work as well 

 

I’ve deactivated 26 plugins and started all over again. The problem remains from the beginning and never goes away The links from “My account” goes nowhere 

   

I deleted woocommerce and reinstalled However it does not clear because it still had any changes and remembered all the information and setting This is the not good 

As far as I can see Woocommerce IS THE BUG.

 

https://www.beingoffthegrid.co.za/ this is my website 

This my accounts page 

https://www.beingoffthegrid.co.za/?page_id=41

 

This is once ive logged in 


 

 

Now if I select Recent orders Account details Address or logout NOTHING HAPPENS 
Wishlist does work because it’s a separate page 

If I select (Not lonewolf? logout) That too works and the only way I can log out (as a customer) 

 

Further than this I have no idea what the cause is 

I’ve seen 1000s of the same complaint yet I’ve never seen a adequate resolution 

I would appreciate your help 

 

Thank you 

Trevor Von Bosch

072 776 9255

www.beingoffthegrid.co.za

**Comment by juliaamosova** [comment] 2021-06-01 17:22
Hi @Trevorlonewolf,

Thank you for opening the issue. 

>I now sit with a site thats completely useless to me because you clowns are too lazy, stupid or just not interested in fixing.

>I must say you guys are not the brightest if you did not know this already!

Please note that the behavior you demonstrate in your report is unacceptable. It violates our [Contributor Covenant Code of Conduct](https://github.com/woocommerce/woocommerce/blob/trunk/CODE_OF_CONDUCT.md). We will not tolerate abusive language. This is a safe space for all and we expect our community members to positively contribute to it. 

Regarding the issue you reported, please note that in order for us to confirm the bug, we need to first reproduce it on our own test site. This is the reason behind us requiring all bug reports to follow the template where we collect all the information needed for us to work on the issue. So far, you have not provided us with clear steps to reproduce the issue. 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug.

**Closed by juliaamosova** 2021-06-01 17:22 UTC
Labels: has feedback
