### ISSUE TITLE
3.6.0 Beta 1 and woo-gutenberg-products-block fatal error

### ISSUE THREAD

**Issue by MarinaWoo** [woocommerce/woocommerce#23070] opened 2019-03-18 14:42 UTC
Switching to 3.6.0 Beta caused a 500 error on my site.

Using the WooCommerce Beta Tester plugin on my store fajrbeirut.com, I switched version to 3.6.0 and got a 500 internal error. It turned out to be from 2 x fatal errors, one of which was from _woo-gutenberg-products-block_ trying to redeclare a class that already exists:

> Fatal error: Cannot declare class WC_Block_Featured_Product, because the name is already in use in /opt/sites/1125502/fajrbeirut/wp-content/plugins/woo-gutenberg-products-block/includes/blocks/class-wc-block-featured-product.php on line 15

It looks like WooCommerce is declaring it first:

> plugins/woocommerce/includes/blocks/class-wc-block-featured-product.php
> Line 17:class WC_Block_Featured_Product {

> plugins/woo-gutenberg-products-block/includes/blocks/class-wc-block-featured-product.php
> Line 15:class WC_Block_Featured_Product {

Deactivating the _woo-gutenberg-products-block_ plugin resolved the error. Happy to give you access to my site if useful. 

For what it's worth, I did this on my live site and am glad Pressable are so helpful🥇

**Comment by timmyc** [comment] 2019-03-18 22:30
@MarinaWoo thanks for opening the bug report - looks like this issue is a duplicate of #23049 - so I'm going to close this out. Looks like we have a bug fix already up for review too.

**Closed by timmyc** 2019-03-18 22:30 UTC

**Comment by MarinaWoo** [comment] 2019-03-19 10:02
Ah! Will remember to search through existing next time. Thanks @timmyc
