### ISSUE TITLE
[GlobalStep] "There has been a critical error on this website" error message is displayed upon clicking "Import Products" button on "Personalize Your Store" screen.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#30157] opened 2021-06-24 15:11 UTC
## Bug Description:
"There has been a critical error on this website" error message is displayed upon clicking "Import Products" button on "Personalize Your Store" screen.

## Environment:
Woocommerce Version : WooCommerce 5.5.0 Beta
WordPress version: v5.8-beta3-51218

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the OBW setup.
1. Go to Woocommerce >> Home.
1. Click on "Personalize Your Store" option from task list.
1. Click on  "Import Products" button.
1. Observe that "There has been a critical error on this website" error is displayed.

## Actual Result:
"There has been a critical error on this website" error message is displayed upon clicking "Import Products" button on "Personalize Your Store" screen.

## Expected Result:
User should be able to import products successfully upon clicking "Import Products" button.

## Video/Screenshot:

https://user-images.githubusercontent.com/41110392/123287978-ca0c1980-d52c-11eb-8587-47a159df5bfb.mp4

![#30157](https://user-images.githubusercontent.com/41110392/123288003-ced0cd80-d52c-11eb-8038-9e3819f4c75f.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

### WordPress Environment ###

WordPress address (URL): https://cognitive-humboldt.jurassic.ninja
Site address (URL): https://cognitive-humboldt.jurassic.ninja
WC Version: 5.5.0
REST API Version: ✔ 5.5.0
WC Blocks Version: ✔ 5.3.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.0-rc.2
Log Directory Writable: ✔
WP Version: 5.8-beta3-51224
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.0
WC Database Prefix: wp_
Total Database Size: 4.47MB
Database Data Size: 3.01MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 6
post: 2
product: 18
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Jetpack: by Automattic – 9.8.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce: by Automattic – 5.5.0-beta.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)

Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2021-06-23 11:53:04 +0000
Newest: 2021-06-24 12:04:24 +0000

### Status report information ###

Generated at: 2021-06-24 12:14:11 +00:00

</details>

**Comment by rodelgc** [comment] 2021-06-24 16:03
Hi @gglobalstep,
﻿
Thank you for raising the issue. However, I can’t reproduce it on my end.

I tested the importing of sample products using `WordPress 5.8-beta3-51224` and `WooCommerce 5.5.0-beta.1`, and I was able to successfully complete the import. Please see the video below:

https://user-images.githubusercontent.com/4509348/123295731-963eed00-d548-11eb-8598-bf689266ecd7.mov

Could you please try again and see if you could still replicate the issue?

**Comment by gglobalstep** [comment] 2021-06-25 10:21
> Could you please try again and see if you could still replicate the issue?
We have checked this issue again and able to reproduce it new JN site but observed the different error "The Response is not a valid JASON response"
Please refer to the below video:

https://user-images.githubusercontent.com/41110392/123410645-2f174c00-d5cd-11eb-8c01-de1c04ce71a2.mp4

**Comment by rodelgc** [comment] 2021-06-25 17:18
Hello @gglobalstep,

Thank you very much for trying again on your end. However, I still cannot reproduce it. Here are the exact steps I took:
1. Created a new JN site without the WooCommerce plugin
2. Logged in to the JN site as admin
3. Installed the WP Beta Tester Plugin
4. Used the WP Beta Tester Plugin to update WordPress to `5.8-beta3-51230`
5. Installed the zip file for WooCommerce 5.5.0-beta1 and activated it.
6. I went to 'WooCommerce > Home'
7. Completed the onboarding wizard.
8. Clicked 'Personalize my store'.
9. Clicked 'Import products'.

Actual result: The import was successful on my end. Please see the video below:

https://user-images.githubusercontent.com/4509348/123460303-023d5600-d61a-11eb-9906-f55f4658eede.mov

**Comment by gglobalstep** [comment] 2021-06-30 08:02
> Could you please double-check if there's a key step that you missed in order for us to recreate the issue?
> Since you get a different error message this time, it could mean that there might be an underlying issue somewhere else than the product import functionality.

We are still able to reproduce this issue on WooCommerce 5.5 RC 1. with the below steps:
1. Create any test site using JN site.
2. Install and activate the query monitor plugin.
3. Install WP Beta Tester Plugin and update WordPress to 5.8-beta3-51230.
4. Install and activate the WooCommerce plugin from Plugins->Add New.
5. Install and activate WooCommerce Beta tester plugin.
6. Switch to WooCommerce version 5.5 RC 1 using WooCommerce Beta tester.
7. Complete the OBW setup.
8. Go to Woocommerce >> Home.
9. Click on "Personalize Your Store" option from task list.
10. Click on "Import Products" button.
11. Observe the Error.

Please refer to the below attachment:

https://user-images.githubusercontent.com/41110392/123924323-7cb5ff00-d9a7-11eb-8ebd-1a747d567c62.mp4


Could you please check with the above mentioned steps?

**Comment by rodelgc** [comment] 2021-07-28 09:37
Hi @gglobalstep,

Since we cannot reproduce this issue in the last release and we do not encounter this issue anymore in the current release cycle, I believe it's already safe to close this.

**Closed by rodelgc** 2021-07-28 09:37 UTC
Labels: Bug, status: can't reproduce, needs: triage feedback
