### ISSUE TITLE
Orders overwriting when placed at same time

### ISSUE THREAD

**Issue by cdesewell** [woocommerce/woocommerce#17660] opened 2017-11-11 14:40 UTC
It seems as though when two customers place an order (complete checkout) at the same time (or very close together) all of the items in one of the orders are added into the other. This leaves one order with no items and another order with too many items. The totals, tax and shipping however all remain in tact. It's consistently always the adjcent order which accrues all of the items. For example:

Order 001 & 002 are placed at 12:00am

Customer A placed order 001 for product A at £10
Customer B placed order 002 for product B at £20

Upon checkout completion of both orders, the following is saved in the database:

Customer A's order 001 has no products at £10
Customer B's order 002 has product A & product B at £20 << always the adjacent order number

Our store is hosted on AWS. I'm using a load balanced elastic beanstalk with at least two servers at any time. Along with an RDS instance. Our average load is between 200 and 400 users with peak load being around 1000 users.

I have not been able to reproduce the issue in a non production environment to understand exactly why it happens. 

Is it possible that when an order item is saved in the 'woocommerce_order_items' table the wrong order ID is used?

System status dump: 

<details>
`
### WordPress Environment ###

Home URL: https://www.alpha.mous.co
Site URL: https://www.alpha.mous.co
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.21
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.51.0
NSS/3.28.4

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: mous_
MaxMind GeoIP Database: ✔
Total Database Size: 726.91MB
Database Data Size: 433.48MB
Database Index Size: 293.43MB
mous_woocommerce_sessions: Data: 23.59MB + Index: 1.52MB
mous_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
mous_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
mous_woocommerce_order_items: Data: 7.52MB + Index: 3.52MB
mous_woocommerce_order_itemmeta: Data: 58.59MB + Index: 63.17MB
mous_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
mous_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
mous_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
mous_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
mous_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_log: Data: 0.02MB + Index: 0.02MB
mous_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
mous_commentmeta: Data: 1.52MB + Index: 0.72MB
mous_comments: Data: 19.55MB + Index: 16.09MB
mous_links: Data: 0.02MB + Index: 0.02MB
mous_options: Data: 2.47MB + Index: 1.52MB
mous_pmlca_links: Data: 0.02MB + Index: 0.02MB
mous_pmxe_exports: Data: 1.52MB + Index: 0.00MB
mous_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
mous_pmxe_posts: Data: 5.52MB + Index: 0.00MB
mous_pmxe_templates: Data: 0.09MB + Index: 0.00MB
mous_pmxi_files: Data: 0.02MB + Index: 0.00MB
mous_pmxi_history: Data: 0.02MB + Index: 0.00MB
mous_pmxi_imports: Data: 0.14MB + Index: 0.00MB
mous_pmxi_posts: Data: 6.52MB + Index: 0.00MB
mous_pmxi_templates: Data: 0.02MB + Index: 0.00MB
mous_postmeta: Data: 147.70MB + Index: 165.44MB
mous_posts: Data: 58.59MB + Index: 34.19MB
mous_redirection_404: Data: 1.52MB + Index: 1.05MB
mous_redirection_groups: Data: 0.02MB + Index: 0.03MB
mous_redirection_items: Data: 0.02MB + Index: 0.08MB
mous_redirection_logs: Data: 3.52MB + Index: 0.91MB
mous_social_users: Data: 0.02MB + Index: 0.02MB
mous_termmeta: Data: 0.02MB + Index: 0.03MB
mous_terms: Data: 0.02MB + Index: 0.03MB
mous_term_relationships: Data: 7.52MB + Index: 4.52MB
mous_term_taxonomy: Data: 0.02MB + Index: 0.03MB
mous_usermeta: Data: 0.11MB + Index: 0.09MB
mous_users: Data: 0.02MB + Index: 0.05MB
mous_w3tc_cdn_queue: Data: 0.02MB + Index: 0.02MB
mous_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
mous_woel_woocommerce_order_emails_log: Data: 86.52MB + Index: 0.00MB
mous_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB
mous_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
mous_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 407
blocks: 2
custom_css: 1
klaviyo_shop_cart: 173946
nav_menu_item: 10
page: 22
post: 2
post_type: 2
product: 8
product_variation: 105
revision: 274
shop_coupon: 2065
shop_order: 30196
shop_order_refund: 636
warranty_request: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (22) ###

Add From Server: by Dion Hulse – 3.3.3
Disable/Configure Plugins: by Chris Sewell – 1.0.1
WooThumbs - Awesome Product Imagery: by Iconic – 4.6.1 – Not tested with the active version of WooCommerce
WooCommerce Order Emails Log (Premium): by RaiserWeb – 2.0 – Not tested with the active version of WooCommerce
Redirection: by John Godley – 2.9.2
SSL Insecure Content Fixer: by WebAware – 2.4.0
User Role Editor: by Vladimir Garagulya – 4.37
WooCommerce Variation Swatches: by ThemeAlien – 1.0.3 – Not tested with the active version of WooCommerce
W3 Total Cache: by Frederick Townes – 0.9.5.4
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629 – Not tested with the active version of WooCommerce
WooCommerce Tree Table Rate Shipping: by tablerateshipping.com – 1.16.4 – Not tested with the active version of WooCommerce
Woocommerce Advanced Bulk Edit: by George Iron – 3.6 – Not tested with the active version of WooCommerce
Aelia Currency Switcher for WooCommerce: by Aelia – 4.4.19.170602 – Not tested with the active version of WooCommerce
WooCommerce Direct Variation Link: by WP BackOffice – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.4 – 1.3.5 is available – Not tested with the active version of WooCommerce
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.12 – 4.1.18 is available – Not tested with the active version of WooCommerce
WooCommerce Smart Checkout: by AppPresser Team – 1.1.2 – Not tested with the active version of WooCommerce
WooCommerce Warranty Requests: by WooCommerce – 1.8.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
WP Crontrol: by John Blackbourn & contributors – 1.5
WP SES: by Sylvain Deaure – 0.7.21

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /basket/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: mous
Version: 99.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Mous
Parent Theme Version: 99.0.0
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: mous_child/woocommerce/archive-product.php
mous_child/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
mous_child/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0
mous_child/woocommerce/cart/proceed-to-checkout-button.php
mous_child/woocommerce/checkout/form-billing.php version 3.0.0 is out of date. The core version is 3.0.9
mous_child/woocommerce/checkout/form-coupon.php
mous_child/woocommerce/checkout/form-shipping.php version 3.0.0 is out of date. The core version is 3.0.9
mous_child/woocommerce/checkout/review-order.php version - is out of date. The core version is 2.3.0
mous_child/woocommerce/checkout/thankyou.php version 3.0.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/content-product.php
mous_child/woocommerce/content-product_cat.php
mous_child/woocommerce/content-single-product.php
mous_child/woocommerce/global/breadcrumb.php
mous_child/woocommerce/global/form-login.php
mous_child/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/global/wrapper-end.php
mous_child/woocommerce/global/wrapper-start.php
mous_child/woocommerce/loop/loop-end.php
mous_child/woocommerce/loop/loop-start.php
mous_child/woocommerce/loop/orderby.php
mous_child/woocommerce/loop/pagination.php
mous_child/woocommerce/loop/result-count.php
mous_child/woocommerce/loop/sale-flash.php
mous_child/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/myaccount/navigation.php
mous_child/woocommerce/notices/error.php
mous_child/woocommerce/notices/notice.php
mous_child/woocommerce/notices/success.php
mous_child/woocommerce/product-searchform.php
mous_child/woocommerce/single-product/add-to-cart/external.php
mous_child/woocommerce/single-product/add-to-cart/grouped.php version 3.0.3 is out of date. The core version is 3.0.7
mous_child/woocommerce/single-product/add-to-cart/simple.php
mous_child/woocommerce/single-product/add-to-cart/variable.php
mous_child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
mous_child/woocommerce/single-product/add-to-cart/variation.php
mous_child/woocommerce/single-product/photoswipe.php
mous_child/woocommerce/single-product/price.php
mous_child/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.1.0
mous_child/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.1.0
mous_child/woocommerce/single-product/related.php
mous_child/woocommerce/single-product/review.php
mous_child/woocommerce/single-product/sale-flash.php
mous_child/woocommerce/single-product/share.php
mous_child/woocommerce/single-product/short-description.php
mous_child/woocommerce/single-product/tabs/tabs.php
mous_child/woocommerce/single-product/title.php
mous_child/woocommerce/single-product/up-sells.php
mous_child/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0
mous_child/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment] 2017-11-13 12:30
Hi Chris,

Before I start; not a server expert. I confirmed my suspicions with @kloon anyhow and we believe this is due to your load balancer and isn't something WC can help with specifically afaik and needs to be solved server side.

>  it sounds like a setup issue with database replication and load balancers

It sounds like you have 2 clients creating orders at the same time, and both thought they had created the same ID due to the 2 DB servers. On a regular, non-load balanced server the tables would be locked so each client would get a unique ID.

Given the current setup, I expect you'd also be able to replicate this same issue with WP posts or any ID based post type, if the events happened at the same time.

> all reads after a write to the DB should happen on the master and not the slave

^ that was what @kloon said, and I know we have a similar setup on woocommerce.com which doesn't exhibit this issue.

> Is it possible that when an order item is saved in the 'woocommerce_order_items' table the wrong order ID is used?

No, the code would just use whatever ID was given. The issue is that both processes were given the same order ID.

Hope you're able to work it out :)

Thanks

**Comment by cdesewell** [comment] 2017-11-13 14:34
Hi mike

Thanks for replying. Sorry if I wasn't clear, we are only running a single database server no master/slave architecture. Only the web servers are load-balanced (with immutable code), we also employ sticky sessions so a user cant bounce between servers. 

> No, the code would just use whatever ID was given. The issue is that both processes were given the same order ID.

Is there no plan to address this? I'm asking WooCommerce this and not WordPress as it's likely not a common use case for blogs/content sites to have lots of concurrent writes.

**Comment by mikejolley** [comment] 2017-11-13 16:38
Plan to address what exactly? As I said, the code will user the insert ID given. If the tables are locked correctly, this type of conflict cannot happen? There are only 2 things I can think of that would cause the behaviour you describe and thats master/slave DB setup, or a shared session due to caching of the checkout page.

**Comment by cdesewell** [comment] 2017-11-28 11:53
@mikejolley We have turned of all CDN and caching on the site and still experience this issue. It's beginning to look like a race condition somewhere in the checkout. Does the WooCommerce team test their software in multi server configurations or under fake load?

**Comment by mikejolley** [comment] 2017-12-04 12:52
WooCommerce.com uses master/slave config, so in a way, yes we do.

**Comment by matt-h** [comment] 2018-05-01 19:30
I wanted to comment on this that we are seeing this exact same issue running WooCommerce 3.3.5
It is pretty rare, but has happened about 5 times over the past few months in a set of about 10,000 orders.

It only happens if the orders are placed at the same time.
Each order has their own distinct Order ID (post id). All order information is correct as far as the order post created in `wp_posts` and `wp_postmeta` are on the correct Post ID. The Shipping and Billing addresses are linked to the proper Order correctly.

The only thing is `woocommerce_order_items` table. All of the line items from both orders are assigned to one of the orders and the other one has nothing assigned to it.

We are also only running a single DB server with no master/slave replication.

**Comment by defran16** [comment] 2018-05-09 17:11
I'm running WC 3.1.2 on a single DB server with no master/slave replication and have been experiencing this exact same problem. We noticed the same behavior in the previous version of WC as well. It only seems to happen between adjacent orders that are placed within seconds of each other. We see the exact same thing as what matt-h described with order ID, order information and billing/shipping info.

**Comment by peterfabian** [comment] 2018-05-12 08:58
Seems like there might be a race condition somewhere, but can't really see where at the moment. 

It looks to me that `WC_Order::save()` (called from `WC_Checkout::create_order()`):
1. Fills the order with info like shipping, billing info, assigns the order items to the order
2. Creates the order by calling `wp_insert_post`, getting the order id as a result, 
3. Saves the order id in the `WC_Order` object itself
4. Updates the meta info in `wp_post_meta`, using the id from previous step [since this is always correct in your case, I'm assuming there can't be a conflict in order id's at this point]
5. Invalidates caches for this order, deletes transients
6. Saves items by going through them one by one and
  a. Assigns the order id saved in step 3 to order item
  b. Saves order item 

The interesting part is that order id is not fetched (at least based on stepping through code and looking at db query log) from anywhere between steps 4 and 6. 
If we assume that the PHP processes each request in isolation and no extra persistent caching, one user's request cannot change values of variables in the other user's process, so changing `WC_Order::id` is quite difficult to accomplish. It could be either something running afterwards that would update those order items or something (temporarily) persisted in the db?

@matt-h you mentioned that only line items are misplaced. Are also `shipping` order items assigned to the incorrect order?

Let's see if I can replicate this in test..

**Comment by matt-h** [comment] 2018-05-12 11:30
@peterfabian In the last example that I saw it happen in, the shipping line was on the correct order. I'm not sure if this was the case every time, but I'll keep an eye out for that.

I'm running MariaDB with InnoDB tables.

**Comment by peterfabian** [comment] 2018-05-12 13:04
If any of you still have the records related to those orders, would you mind sharing them (after anonymizing the personally identifiable information of customers)? It could provide us with some hints on where this might be happening...

**Comment by matt-h** [comment] 2018-05-29 18:58
Here is an anonymized SQL dump of 2 orders that we just had this happen with again. This case, both customer ordered the same product. But as with @defran16's example it still does happen with different products.

https://gist.github.com/matt-h/1151899e2cc582c57c45f2d27afc85e6

**Comment by matt-h** [comment] 2018-05-29 18:58
Can someone with permission re-open this issue as I don't think that it should be closed with it still happening?

**Comment by mikejolley** [comment] 2018-05-31 14:01
@matt-h If you change:

https://github.com/woocommerce/woocommerce/blob/7c120bb62fa7e46e69972a63d24a577c4ab2c598/includes/data-stores/abstract-wc-order-data-store-cpt.php#L327

to:

`$items = false;`

Does the issue occur?

Are there items in your order items table with order ID 0?

**Comment by matt-h** [comment] 2018-06-04 23:53
I can try it and see if it stops happening. It is hard to test without just waiting awhile as it only happened about 5 times in every about 10,000 orders.

**Comment by mikejolley** [comment] 2018-06-05 10:41
@matt-h got it.  Not sure if @cdesewell or anyone else above wants to try that. That was the only code I could find with a potential issue--sharing a cache if order ID was 0 for some reason.

**Comment by defran16** [comment] 2018-06-05 13:10
I'm in the process of trying to find a new developer, but if you can tell me where this needs to be changed I'll try to change it myself. We've been experiencing this problem at least once a week for the last few weeks.

I don't recall if this point was brought up earlier, but when this event happens in our environment, the order that the products were removed from is automatically marked as "complete". This makes it harder to find after the fact because there aren't any lingering orders in a processing state.

**Comment by cdesewell** [comment] 2018-06-08 13:34
Hey @defran16 I may be able to help you with your new developer! As for this issue @mikejolley we have since stopped using woocommerce so cannot try this fix anymore.

**Comment by defran16** [comment] 2018-06-08 14:13
Contact me at steve@raybuck.com about the developer. Thanks

**Closed** 2018-06-15 16:11 UTC
Labels: status: needs feedback

**Comment by anetosmz** [comment] 2019-01-18 22:00
@mikejolley Can we reopen this thread?  I am having this same issue with WooCommerce 3.5.2.  It occurs every time two customers place an order at basically the same time (within a second or so of each other).  All the order items (except for the shipping order item) for the first order are saved with the second order.  All the totals for each order are correct and both orders are processed through the payment processor correctly.  This issue occurs after payment processing when the orders are saved to the db.  Let me know of any other information I can provide that may help to resolve the issue. Thanks!

**Comment by anetosmz** [comment] 2019-01-21 21:05
@mikejolley I spent the morning working on this issue and here is what I've come up with:

In WC_Checkout::create_order_line_items() there is a hook called 'woocommerce_checkout_create_order_line_item'.  On our site, we use the Returns and Warranty Requests plugin sold through WooCommerce.com which uses this hook.  In the Warranty_Order class, the method (order_item_meta) associated with this hook calls $item->save() which I believe is causing the issue for us.  After commenting out this code (and some code around it) I haven't been able to reproduce the issue.

FYI: I was using my local dev environment which is running Bitnami WAMP (and has no load balancing) to troubleshoot this issue.  I was able to reproduce the issue multiple times (6 or so times out of 9 attempts) in this environment before commenting out the mentioned code.  After commenting it out, I wasn't able to reproduce it after 5 different attempts.

I'm not 100% convinced this is the issue, but I've looked through some of our other plugins that use this hook.  All of them approach adding extra metadata to the order_items by calling the 'add_meta_data' method on WC_Order_Item instead of calling $item->save() to get an item_id and then using 'wc_add_order_item_meta'.  This seems like better practice to me, but I wouldn't claim to be a woocommerce expert.

Any insight into my findings would be greatly appreciated.

**Comment by matt-h** [comment] 2019-01-22 14:43
@anetosmz Back in May when I was having this issue as well, we were also using the Returns and Warranty Requests plugin on our site. We no longer use this plugin and have not had this issue happening anymore. If that was the root cause all along. Nice job tracking it down.

**Comment by bingochen88** [comment] 2019-10-01 00:47
Hi,

We are still seeing this issue using WooCommerce 3.7.0.
With a tool like jmeter to place two orders at same time, this issue can be reproduced 100% either at my local or our staging environment.

After outputting '$order->get_order_number()' to a file in file 'woocommerce\includes\data-stores\abstract-wc-order-data-store-cpt.php' line 81, see below: 

`if ( $id && ! is_wp_error( $id ) ) {
			$order->set_id( $id );
			file_put_contents("test.txt","Abstract Data Store CPT After Set ID Order " . $order->get_order_number() . "\r\n", FILE_APPEND);
			$this->update_post_meta( $order );
			$order->save_meta_data();
			$order->apply_changes();
			$this->clear_caches( $order );
		}`

it seems to me the two orders somehow share the same unique id. My understanding is that they should have their own unique id instead. Maybe there is an concurrent issue with WC_Data?

We've enabled Wordpress MultiSite feature and we are also using a plugin called 'wp-marketplace-split-order' to split up orders from different vendors.

We need this issue be fixed before releasing to production; so any help is much needed. Thank you!

**Comment by przemek-git** [comment] 2019-11-12 16:34
Hi,

Lately I've noticed same issue using WooCommerce 3.6.5. One of the order is empty and marked as completed whereas second order contains all the items. Any solution to this issue? Can't see it being solved in the latest changelogs.

**Comment by przemek-git** [comment] 2019-11-12 16:37
Hi,

Lately I've noticed issue using WooCommerce 3.6.5. One of the order is empty and marked as completed whereas second order contains all the items. Any solution to this issue? Can't see it being solved in the latest changelogs.

**Comment by cristacheda** [comment] 2023-07-24 09:38
I'm noticing this issue from time to time when there's high traffic. How should I go about debugging this issue?
