### ISSUE TITLE
Lodash not visible? 

### ISSUE THREAD

**Issue by Artister06** [woocommerce/woocommerce#24655] opened 2019-09-18 16:19 UTC
Hello, I am using Wordpress 5.2.3 with Elementów Pro 2.6.5 and Woocommerce 3.7.0. The issue is that im admin panel, when I open product for edit or create product, I get an error in console that says

Uncaught TypeError: _.pluck is not a function
...
Uncaught TypeError: _.contains is not a function
...
Uncaught TypeError: Cannot read property 'hasClass' of undefined

I cannot add or edit products. Please help.

**Comment by kloon** [comment] 2019-09-23 10:23
Hi @Artister06, can I please ask you test by disabling all plugins except WooCommerce and then also switching your theme to a default one like Twentynineteen or Storefront and then test if the issue persists.

You can then enable plugins one by one testing after each to find which plugin is causing the issue, and then finally you can switch your theme back and test again to see if the theme might be the cause.

If I test with just WooCommerce 3.7 installed I do not get any errors like that so the issue is likely caused by a plugin or your theme.

I am closing the issue for now but will gladly reopen if you can provide steps to reproduce this with just WooCommerce installed on a site with a default theme like Twentynineteen or Storefront.

**Closed by kloon** 2019-09-23 10:23 UTC
