### ISSUE TITLE
Cannot read property 'export_products' of undefined

### ISSUE THREAD

**Issue by iamwaqas** [woocommerce/woocommerce#16891] opened 2017-09-22 06:33 UTC
Hello i have installed smart offers plugin in the add new offer in admin side i have getting this in console
Plz Help 
```
Uncaught TypeError: Cannot read property 'export_products' of undefined
    at HTMLDocument.<anonymous> (woocommerce_admin.min.js?ver=3.1.2:1)
    at i (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.2:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.2:2)
    at Function.ready (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.2:2)
    at HTMLDocument.K (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.2:2)
```

**Comment by iamwaqas** [comment] 2017-09-22 06:35
I have found this but how to register for woocommrece screen
Plugin using admin scripts without registering itself as a WooCommerce screen.

**Comment by claudiulodro** [comment] 2017-09-22 17:11
You probably want to add the plugin screens using a filter on [wc_get_screen_ids](https://github.com/woocommerce/woocommerce/blob/56e120790319c885fad6d07ddc3f3a38c4e42af9/includes/admin/wc-admin-functions.php#L55). This is not a bug in the WooCommerce core plugin so I am closing this.

**Closed by claudiulodro** 2017-09-22 17:11 UTC
