### ISSUE TITLE
How to add custom fields in customer as well as users table or API endpoint ?

### ISSUE THREAD

**Issue by Zubair-Ashraf** [woocommerce/woocommerce#30249] opened 2021-07-10 07:09 UTC
I want to use Woo commerce endpoints in my mobile APP but the issue I am facing now is the some fields that is not exist in customer or users endpoint. Can I add some extra fields like phone_number in users table and date_of_birth, gender fields in customers API/endpoint. If yes so please guide me how I can add these fields. 

*My scenario is I want to use phone_number filed from users  table and perform OTP Auth system on my Mobile APP and use date_of_birth and gender fields in customer table for storing some extra info about customer*

Thanks

**Comment by rodelgc** [comment] 2021-07-14 06:52
Hi @Zubair-Ashraf,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. You may check out the following support channels:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm a bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodelgc** 2021-07-14 06:52 UTC
