### ISSUE TITLE
The feature «Reviews can only be left by "verified owners"» does not has backend validation

### ISSUE THREAD

**Issue by chyvak1831** [woocommerce/woocommerce#28352] opened 2020-11-20 14:46 UTC
**Is your feature request related to a problem? Please describe.**
The feature «Reviews can only be left by "verified owners"» (on page `/wp-admin/admin.php?page=wc-settings&tab=products`) does not has backend validation so it's possible to add comment even if user is not "verified owners".
![image](https://user-images.githubusercontent.com/11210100/99812909-ad9b9f00-2b4f-11eb-86c8-dc45c60880a3.png)

**Describe the solution you'd like**
I've already added validation function.

**Comment by roykho** [comment] 2021-04-16 15:09
Hi @chyvak1831 - sorry for the very late reply here. That setting you see is more or less for the frontend. Because if you have `manage_woocommerce` capability as the user, then you should be able to add comments regardless of if you're the verified owner or not because you have access to admin only areas etc. Normal users without the right capabilities would not be able to access the product itself.

Unless I am missing something, this is working as designed. Closing this for now but feel free to comment if I missed something.

**Closed by roykho** 2021-04-16 15:09 UTC
Labels: needs developer feedback

**Comment by chyvak1831** [comment] 2021-04-16 15:19
@roykho I mean that any user may leave review - just needs to submit form, even if this setting enabled.  
Because this setting has no backend validation.

**Comment by roykho** [comment] 2021-04-16 15:22
> I mean that any user may leave review

Where exactly do they go to leave the review? Can you provide steps to reproduce this issue? Normal users don't have access to products settings.

**Comment by chyvak1831** [comment] 2021-04-16 15:32
@roykho please check attached video: I'm unlogged, theme twentytwentyone - displays msg "Only logged in customers who have purchased this product may leave a review."  

But I can to simply copy-paste form and send without any problem and review appears - because it has no validation on backend.


https://user-images.githubusercontent.com/11210100/115048315-1b22e000-9ee2-11eb-8c7f-816979453f20.mp4

**Comment by chyvak1831** [comment] 2021-04-16 15:34
@roykho please check attached video: I'm unlogged, theme twentytwentyone - displays msg "Only logged in customers who have purchased this product may leave a review."

But I can simply copy-paste form and send without any problem and review appears - because it has no validation on backend.


https://user-images.githubusercontent.com/11210100/115048465-43124380-9ee2-11eb-9012-3a20c968946a.mp4

**Comment by roykho** [comment] 2021-04-16 15:58
@chyvak1831 - thanks for the additional information however I can't reproduce it. This is what I see after using your steps ![](https://d.pr/i/dFCADI+)

Are you using latest WC version?

**Comment by chyvak1831** [comment] 2021-04-16 16:06
@roykho ah yes, on latest version all ok, just updated I'm getting the same.  
It's actual for 4.8x versions... when I've opened this issue was version 4.8x, it seems that it was already fixed in latest versions :-)

**Comment by roykho** [comment] 2021-04-16 16:08
@chyvak1831 - ah no worries, all good. Our fault for getting to this late. Thanks for reporting!
