### ISSUE TITLE
coupon: fixed amount is added per product -> issue when changing the product amount

### ISSUE THREAD

**Issue by Tobias-Conrad** [woocommerce/woocommerce#14872] opened 2017-05-04 08:13 UTC
a customer told me to higher his order amount from 5 to 6.
a cart 10 € coupon is added already.
woocommerce add the coupon to the product. 
10 € / 5 = 2 € per product
coupon value / amount of product.
so if i higher the amount of ordered products the coupon value is also higher.
see the screenshot the coupon amount is higher than 10 €, it is 12 €!!
![coupon-value-extra-please](https://cloud.githubusercontent.com/assets/7352673/25694939/5b74eafc-30b1-11e7-9786-22630623a6d3.png)

Solution: add the 10 € coupon code into an extra line please
then the coupon value stays untouched.

`
### WordPress Environment ###

Home URL: https://www.santegra-international.com
Site URL: https://www.santegra-international.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 7.0.18
PHP Post Max Size: 100 MB
PHP Time Limit: 1200
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: san_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

Advanced Database Cleaner: von Younes JFR. – 2.0.1
Antispam Bee: von pluginkollektiv – 2.7.1
BackupBuddy: von iThemes – 7.3.1.2
Bring Back the Get Shortlink Button: von Thorsten Frommen – 1.1.0
Wordpress Comments List Building: von Tobias B. Conrad – 4.0.0
Duplicate Post: von Enrico Battocchi – 3.2
Easy FancyBox - Pro extension: von RavanH – 1.5.3
Easy FancyBox: von RavanH – 1.5.8.2
Easy Theme and Plugin Upgrades: von Chris Jean – 2.0.0
Email Tracker: von Prashant Baldha – 1.2.3
Envato Market: von Derek Herman – 1.0.0-RC2
Google Analytics for WordPress by MonsterInsights: von MonsterInsights – 6.1.7
Idea Factory: von Nick Haskins – 1.2
IgniteWoo Updater: von IgniteWoo.com – 2.1.9
kk Star Ratings: von Kamal Khan – 2.5.1
Language Fallback: von Bernhard Kau – 1.0.3
Notely: von Michael Ott – 1.3
WooCommerce Product Filter: von Mihajlovic Nenad – 6.2.3
Pretty Link Pro: von Blair Williams – 2.0.8
Redirect Post to URL: von Stefan Böttcher – 1.0
Redirect to URL: von Marcel Fagas – 1.1.2
SearchWP Exclude UI: von Jonathan Christopher – 1.0.1
SearchWP Fuzzy Matches: von Jonathan Christopher – 1.4
SearchWP LIKE Terms: von Jonathan Christopher – 2.4.4.1
SearchWP German Stemmer: von Jonathan Christopher – 1.0.1
SearchWP Term Highlight: von Jonathan Christopher – 2.0.9
SearchWP Term Synonyms: von SearchWP
LLC – 2.4.9

SearchWP Xpdf Integration: von Jonathan Christopher – 1.1.1
SearchWP: von SearchWP
LLC – 2.8.7

Simple Tooltips: von Justin Saad – 2.1.3
SEO by SQUIRRLY: von Squirrly SEO 2017 – 7.0.6
Stream: von XWP – 3.2.0
Tawk.to Live Chat: von Tawkto – 0.2.5
Timed Content: von K. Tough – 2.6
TinyMCE Advanced: von Andrew Ozz – 4.5.6
Vendidero Helper: von Vendidero – 1.1.3
WooCommerce Checkout Field Editor Pro: von ThemeHiGH – 2.5.3
WooCommerce Klarna Gateway: von WooCommerce – 2.3.6
WooCommerce Germanized Pro: von Vendidero – 1.7.6
WooCommerce Germanized: von Vendidero – 1.8.10
WooCommerce Google Analytics Pro: von SkyVerge – 1.3.2 – 1.3.3 ist verfügbar
WooCommerce Quick Order Form: von IgniteWoo.com – 2.1.10
WooCommerce Sequential Order Numbers Pro: von SkyVerge – 1.11.1
WooCommerce Shipment Tracking: von WooCommerce – 1.6.4
WooCommerce URL Coupons: von SkyVerge – 2.5.1
WooCommerce: von Automattic – 3.0.5
WooCommerce Helper: von WooCommerce – 1.7.2 – Netzwerk aktiviert
WP-Optimize: von David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

Wordpress Rankie: von Atef – 1.6.2
WP SEO Structured Data Schema: von kcseopro – 2.0
WP Sitemap Page: von Tony Archambeau – 1.6
WooCommerce & WP Email Marketing Integration: von Tobias B. Conrad – 3.7.0
YITH WooCommerce Wunschliste: von YITHEMES – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #1013 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /checkout/
Mein Konto: #9 - /mein-konto/

### Theme ###

Name: Flatsome Child
Version: 3.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.4
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome-child/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: Eid not set Secret key not set Checkout URL not set
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: ✔
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`

**Comment by claudiulodro** [comment] 2017-05-05 21:10
To reproduce:
- Place an order and use a $10 cart coupon.
- Go to admin order page for the order.
- Edit a line item and increase the quantity by 1.
- Observe discount amount increases.

**Comment by mikejolley** [comment] 2017-05-07 14:47
@claudiulodro Not a bug really. There is no admin-side discount/coupons API, so there is no way to recalculate the discounts after the order is placed.

Therefore if you want to increase the item qty and not discount you either have to edit the line totals yourself, or add a new line item rather than editing the old line item.

This cannot be fixed without a discount API.

**Closed by mikejolley** 2017-05-07 14:47 UTC
Labels: Type: Bug

**Comment by Tobias-Conrad** [comment] 2017-05-07 14:54
i do not unterstand why we need a coupon API?
why not just add the coupon value in an extra line. ​

**Comment by mikejolley** [comment] 2017-05-07 15:12
@Tobias-Conrad Because thats more data to track and keep in sync, and you'd need to know what type of coupon it was. It needs an API.

**Comment by Tobias-Conrad** [comment] 2017-08-15 19:49
Hello @mikejolley ,
may this issue(coupon value divided on all products) fit exactly to milestone 3.2 where you create an coupon API?

best regards Tobias
