### ISSUE TITLE
Option add "Phone Number" (Billing and Shipping) column(s) to Admin Customers List

### ISSUE THREAD

**Issue by datverse** [woocommerce/woocommerce#30387] opened 2021-07-30 04:12 UTC
Hi,
I using "Phone Number" to manage Customers and Orders.
I think we should add "Phone Number" (Billing and Shipping) column(s) to Admin Customers List (wp-admin/admin.php?page=wc-admin&path=%2Fcustomers). Search and Filter by Phone number too.
This feature help we manage customers better.
Current WooCommerce version we have any solution (code/hook) to do this?
Thanks

**Comment by rodelgc** [comment] 2021-07-30 11:15
Hi @datverse,

I believe this is a duplicate of an issue you submitted [earlier](https://github.com/woocommerce/woocommerce/issues/30383). We are closing your issue in favor of the previously submitted.

**Closed by rodelgc** 2021-07-30 11:15 UTC

**Comment by datverse** [comment] 2021-07-30 17:40
Hi @rodelgc 
The issue #30383 is a support, you can close it.
But this issue, my mind is this is a request new feature (New Enhancement). Can you preview and allow it?
Thank.

**Comment by ELY3M** [comment] 2023-01-06 15:55
I need to add two columns to customer list.   phone number and discord username....     I think i have to edit code or make a plugin.

**Comment by datgausaigon** [comment] 2023-01-06 16:28
Hi @rodelgc
The issue https://github.com/woocommerce/woocommerce/issues/30383 is a support, you can close it.
But this issue, my mind is this is a request new feature (New Enhancement). This is can be duplicate with #30383 (because #30383 is a "Support" and Closed) and should be re-open.
Why you don't reply and open for us?
Please review and reply us!
Thanks

**Comment by datgausaigon** [comment] 2023-01-06 16:34
Hi @rodelgc
This issue is closed by wrong from July, 2023. And you don't answer us from July, 2023. 
Please review and reopen this.
Thanks

**Comment by KoolPal** [comment] 2023-01-20 07:59
@rodelgc This is SILLY
BOTH Issues have been closed in a circular loop!

@datverse Good suggestion! I just landed here as my business needed some additional columns for some analysis & campaign!

@vedanshujain Would you please take a look at this and open an enhancement request?

Cursory search in wordpress.org forum shows DEMAND for this FEATURE!
https://wordpress.org/support/topic/customizing-customer-columns-in-admin/
https://wordpress.org/support/topic/add-phone-to-customer-table-list/
https://wordpress.org/support/topic/add-more-column-to-woocommerce-customers/
