### ISSUE TITLE
Updated "Additional information"-field for product variations

### ISSUE THREAD

**Issue by asratech** [woocommerce/woocommerce#26997] opened 2020-07-09 15:19 UTC
When creating a product_variation, Woocommerce allows to specify variation-specific attributes. When selecting a variation, the Tab "Additional Information" which displays the product attributes does not get updated, but rather displays the attributes of the parent product.
I believe that variation attributes should be displayed for the currently selected variation and not only for the parent product. This kind of updating can already be seen with the weight and size attributes, which also change depending on the selected variation.

I created the product variations using wp-cli, adding the attributes via [--attributes=] commandline switch.

Please let me know if you need further information to reproduce / fix this bug.
Used Woocommerce Version 4.3.0
Used Wordpress Version 5.4.2

**Comment by rodrigoprimo** [comment] 2020-10-22 16:21
Closing as a duplicate of #26990

**Closed by rodrigoprimo** 2020-10-22 16:21 UTC
