### ISSUE TITLE
Products are restored with draft status and no variations

### ISSUE THREAD

**Issue by denis-evteev** [woocommerce/woocommerce#28758] opened 2021-01-08 11:23 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When restoring a deleted product, it comes up with a `draft` status regardless of the status it had been in prior to being deleted. Variable products are restored with no variations for the same reason (see below).

**Expected behavior**
I expect products to be restored in the same status they had been in prior to deletion. Variable products should be restored with all variations in place.

**Actual behavior**
Products are restored in the `draft` status. Variations are not available for variable products after they are restored.

**Steps to reproduce the bug**
1. Create and publish a variable product with at least one variation.
2. Delete this product.
3. Restore it — you will see it appears in the `draft` status.
4. Go to the product edit screen and check the Variations tab — you will see no variations there.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional Information**
The reason no variations are visible on the product edit page is because they are also restored in the `draft` status, but for some reason WooCommerce seems [to be ignoring variations](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-variable-data-store-cpt.php#L132) in any status other than `private` and `publish`.

I believe that the status of the `product_variation` post type must always be `inherit`, because a variation always belongs to a specific product and cannot be treated in isolation from that product. Therefore, there is no need for it to have its own status.

At the moment, though, a variation status can be different from that of its product. For example, by default a new variation is created with the `publish` status even for draft products. To me this doesn't make a lot of sense.

**Comment by masteradhoc** [comment] 2021-01-08 11:32
See #28652

**Comment by denis-evteev** [comment] 2021-01-08 12:51
@masteradhoc, the issue you mentioned is definitely related to this one, but the PR you also mentioned is only applicable to orders, but not products.

**Comment by kevinruscoe** [comment] 2021-01-09 14:53
@denis-evteev Updated the PR to work with products, as the issue is the same.

**Comment by juliaamosova** [comment] 2021-01-10 22:15
Hi @denis-evteev,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Thanks, @kevinruscoe for updating your PR to fix the product issue described in this report as well.

**Comment by apeksha10** [comment] 2021-01-11 12:39
Hello,

The above same issue is replicated with a Simple product type too.

**Comment by roykho** [comment] 2021-01-14 20:33
Closed via https://github.com/woocommerce/woocommerce/pull/28690

**Closed by roykho** 2021-01-14 20:33 UTC
Labels: component: product, priority: high, type: bug
