### ISSUE TITLE
Checkout error after 3d Secure code (stripe)

### ISSUE THREAD

**Issue by giveme11us** [woocommerce/woocommerce#29009] opened 2021-02-03 08:03 UTC
Hi guys ! I'm getting this error 
 " has been removed from your cart because it can no longer be purchased. Please contact us if you need assistance." 
 
 after someone try to checkout an item on my shops and the shop ask for the 3d secure code, already tried all the options/change stripe plugin, disabled all the plugin, and leave just woocommerce and stripes getaway but still getting this error.
 
 the order will stay on the dashboard on pending payment

**Comment by juliaamosova** [comment] 2021-02-03 20:30
Hi @giveme11us,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-02-03 20:30 UTC
