### ISSUE TITLE
Back coding showing on half of my woocommerce page

### ISSUE THREAD

**Issue by lunarbody** [woocommerce/woocommerce#27969] opened 2020-10-15 01:09 UTC
**Describe the bug**
On my woocommerce page, there is a half-page of back coding. It appeard out of know where

**Expected behavior**
I expect that to be off of my page.

**Actual behavior**
When I click lunarbody.com/shop half of the screen is full of coding and crazy writing.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
go to www.lunarbody.com/shop  it will be the first thing you see on the first half of the page.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/72898087/96061573-96d39f80-0e61-11eb-9bad-6325045123c3.png)

**Comment by tammullen** [comment] 2020-10-15 08:43
Hi @lunarbody 

It will help us evaluate this issue if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by lunarbody** [comment] 2020-10-15 11:18
`
### WordPress Environment ###

WordPress address (URL): https://lunarbody.com
Site address (URL): https://lunarbody.com
WC Version: 4.6.0
REST API Version: ✔ 4.6.0
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.1
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.11
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.0
WC Database Prefix: _9UQ_
Total Database Size: 34.35MB
Database Data Size: 29.47MB
Database Index Size: 4.88MB
_9UQ_woocommerce_sessions: Data: 0.43MB + Index: 0.01MB + Engine MyISAM
_9UQ_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_downloadable_product_permissions: Data: 0.07MB + Index: 0.08MB + Engine MyISAM
_9UQ_woocommerce_order_items: Data: 0.11MB + Index: 0.07MB + Engine MyISAM
_9UQ_woocommerce_order_itemmeta: Data: 0.81MB + Index: 0.62MB + Engine MyISAM
_9UQ_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_actionscheduler_actions: Data: 0.37MB + Index: 0.16MB + Engine MyISAM
_9UQ_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_actionscheduler_logs: Data: 0.26MB + Index: 0.18MB + Engine MyISAM
_9UQ_brizy_logs: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
_9UQ_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_comments: Data: 0.58MB + Index: 0.27MB + Engine MyISAM
_9UQ_edd_customermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_edd_customers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_newsletter: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_newsletter_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_newsletter_sent: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_newsletter_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_newsletter_user_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_options: Data: 8.38MB + Index: 0.14MB + Engine MyISAM
_9UQ_postmeta: Data: 14.43MB + Index: 2.00MB + Engine MyISAM
_9UQ_posts: Data: 2.69MB + Index: 0.24MB + Engine MyISAM
_9UQ_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_usermeta: Data: 0.68MB + Index: 0.46MB + Engine MyISAM
_9UQ_users: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
_9UQ_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_wc_customer_lookup: Data: 0.08MB + Index: 0.08MB + Engine MyISAM
_9UQ_wc_download_log: Data: 0.24MB + Index: 0.23MB + Engine MyISAM
_9UQ_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_wc_order_product_lookup: Data: 0.12MB + Index: 0.13MB + Engine MyISAM
_9UQ_wc_order_stats: Data: 0.09MB + Index: 0.06MB + Engine MyISAM
_9UQ_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_wc_product_meta_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_9UQ_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_9UQ_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_9UQ_wpforms_tasks_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 123
brizy-form-entry: 438
brizy-global-block: 3
brizy-project: 1
brizy-saved-block: 6
customize_changeset: 1
download: 1
edd_log: 3
edd_payment: 1
elementor_library: 1
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
mc4wp-form: 1
nav_menu_item: 12
page: 13
post: 4
product: 11
product_variation: 35
revision: 266
shop_order: 1094
shop_order_refund: 14

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Bluehost: by Bluehost – 2.3
Brizy: by Brizy.io – 2.0.14
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.12.3
Jetpack by WordPress.com: by Automattic – 9.0.2
Really Simple SSL: by Really Simple Plugins – 3.3.5
SumoMe: by SumoMe – 1.31
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.29

Country Based Restrictions for WooCommerce: by zorem – 2.7.5 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.39 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce: by Automattic – 4.6.0
WPForms Lite: by WPForms – 1.6.2.3

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.6.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.1

### Dropin Plugins (2) ###

db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.0.4
SSO: by Garth Mortensen
Mike Hansen – 0.3


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #718 - /shop/
Cart: #719 - /cart/
Checkout: #720 - /checkout/
My account: #721 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Sinatra
Version: 1.1.5
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: sinatra/woocommerce/cart/cart.php
sinatra/woocommerce/cart/cross-sells.php
sinatra/woocommerce/cart/proceed-to-checkout-button.php
sinatra/woocommerce/checkout/form-checkout.php
sinatra/woocommerce/content-single-product.php
sinatra/woocommerce/product-searchform.php
sinatra/woocommerce/single-product/meta.php
sinatra/woocommerce/single-product/rating.php
sinatra/woocommerce/single-product/tabs/tabs.php


### Action Scheduler ###

Complete: 626
Oldest: 2020-10-05 15:41:28 +0000
Newest: 2020-10-15 06:49:58 +0000

Pending: 2
Oldest: 2020-10-15 22:26:32 +0000
Newest: 2020-10-16 02:02:18 +0000

`

Sent from Mail for Windows 10

**Comment by tammullen** [comment] 2020-10-15 14:55
Thank you @lunarbody for raising the issue and providing the status report. However, I can’t reproduce it on my end.

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again. More help with this can be found here https://docs.woocommerce.com/document/how-to-test-for-conflicts/
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by lunarbody** [comment] 2020-10-15 15:13
I changed the theme to storefront and deactivated all of the plug ins. It did not work.
Do you have any other suggestions?

Sent from Mail for Windows 10

**Comment by tammullen** [comment] 2020-10-16 10:13
Hi @lunarbody 

> I changed the theme to storefront and deactivated all of the plug ins. It did not work.
Do you have any other suggestions?


Thanks for trying that, the code visible in the screenshot you shared isn't part of WooCommerce so may be part of the Brizy plugin and theme that you use. 
Can you share a screenshot or more details of the issue/error you see with the theme changed to storefront and other plugins deactivated? This will help us evaluate what is happening.

**Comment by lunarbody** [comment] 2020-10-17 18:06
Everything is disable but woocommerce. The theme is storefront.

Sent from Mail for Windows 10

**Comment by tammullen** [comment] 2020-10-19 10:02
Hi @lunarbody 

> Everything is disable but woocommerce. The theme is storefront.

Can you share a screenshot or more details of the issue/error you see with Storefront and only WooCommerce active? This will help us evaluate what is happening.

**Comment by lunarbody** [comment] 2020-10-19 10:34
That is exactly what my lash email was 
    	
    	

    	Get Outlook for iOS
    
  




On Mon, Oct 19, 2020 at 6:03 AM -0400, "Tam Mullen" <notifications@github.com> wrote:















Hi @lunarbody



Everything is disable but woocommerce. The theme is storefront.



Can you share a screenshot or more details of the issue/error you see with Storefront and only WooCommerce active? This will help us evaluate what is happening.

**Comment by tammullen** [comment] 2020-10-19 10:55
Hi @lunarbody 

> That is exactly what my lash email was

We are using GitHub to discuss, track and evaluate this issue at
[https://github.com/woocommerce/woocommerce/issues/27969](https://github.com/woocommerce/woocommerce/issues/27969). There is no screenshot or details of the issue/error you see with Storefront and only WooCommerce active on that issue.
Can you please let us know what you are seeing?

**Comment by lunarbody** [comment] 2020-10-19 10:58
You can see it at www.lunarbody.com/shop 


    	Get Outlook for iOS
    
  




On Mon, Oct 19, 2020 at 6:56 AM -0400, "Tam Mullen" <notifications@github.com> wrote:















Hi @lunarbody



That is exactly what my lash email was



We are using GitHub to discuss, track and evaluate this issue at

#27969. There is no screenshot or details of the issue/error you see with Storefront and only WooCommerce active on that issue.

Can you please let us know what you are seeing?

**Comment by tammullen** [comment] 2020-10-19 14:07
Thanks @lunarbody 

> You can see it at www.lunarbody.com/shop 

I've attached screenshot of that URL taken at 12:53 UTC today
![Screenshot 2020-10-19 at 13 53 23](https://user-images.githubusercontent.com/24649833/96461232-0a87fa80-121c-11eb-8ae7-847e3e5efeeb.png)

This looks like the Brizy plugin and theme that you use has inserted this code into the page and it isn't removed when deactivating the plugin and switching away from that theme.

Please contact the author of the plugin directly for further help. 

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-10-19 14:07 UTC
Labels: can't reproduce, status: needs feedback

**Comment by lunarbody** [comment] 2020-10-19 14:20
When I disable brizy, the entire website looks like that coding. Right now, it’s ONLY the shop page. I cannot afford to lose my entire site like that. Woocommerce is the only problem page
    	
    	

    	Get Outlook for iOS
    
  




On Mon, Oct 19, 2020 at 10:08 AM -0400, "Tam Mullen" <notifications@github.com> wrote:















Closed #27969.
