### ISSUE TITLE
[GlobalStep - WooCommerce 4.7.0-rc.1] "Save" button fails to enable for Password field when user has fulfilled its requirement during password reset

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28125] opened 2020-10-28 15:13 UTC
## Bug Description:
"Save" button fails to enable for Password field when user has fulfilled its requirement during password reset

## Environment:
Windows 10, Mac High Sierra v10.13.6
Browser: Chrome(Version 86.0.4240.75 (64-bit))
                 Firefox(Version 82.0)(64-bit)
                 Safari (Version 13.1.2)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Go to WooCommerce beta Tester.
1. Switch the WooCommerce version to 4.7.0-rc.1
1. Go to Frontend by clicking on "Home icon->Visit Site" option at top right corner.
1. Click on “My Account”.
1. Click on “Account details”.
1. Change “Email Address” ex- “gglobalstep@gmail.com”.
1.  Enter “First name” and “Last name”
1. Click on “Save changes” and Logout from the site on front end 
1. Click on "Lost your password?" link text
1. Enter email address and click on "Reset Password" button
1. For correct email address, link will be sent to your respective email  say “gglobalstep@gmail.com” account
1.Open the reset password link .
1. Set “New Password” and “Confirm Password” field ex- “Password123$”
1. Observe that "Save" button fails to enable for Password field when user has fulfilled its requirement.

## Actual Result:
"Save" button fails to enable for Password field when user has fulfilled its requirement during password reset

## Expected Result:
"Save" button should be enabled for Password field when user has fulfilled its requirement during password reset

## Artifacts:
[#28125.zip](https://github.com/woocommerce/woocommerce/files/5452877/28125.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-10-30 20:20
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I used TwentyTwenty theme for testing. The `Save` button gets activated there but still doesn't let you to proceed with `Password123$` password even though it meets all the password requirements:

![](http://g.recordit.co/Vyf5XCIOUE.gif)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment] 2023-06-19 17:34
Closing as I could not reproduce this in current `trunk`.

**Closed by rrennick** 2023-06-19 17:34 UTC
Labels: Bug, status: can't reproduce, Shopper Account/Management, plugin: woocommerce
