### ISSUE TITLE
The product price shown on the cateogry page does not reflect actual product-level price

### ISSUE THREAD

**Issue by tpittman1184** [woocommerce/woocommerce#26045] opened 2020-03-31 23:17 UTC
Check this URL for Skin Rejuv and the price is listed as $255 for HydraFacial. 
-https://neamanplasticsurgery.com/product-category/skin-rejuvenation/
Then click through to the product page and you can see the prices arn;t reflected properly on the prior page: 
-https://neamanplasticsurgery.com/product/hydrafacial/

It starts at $418, why is it listed as $255 on the category page?

**Comment by tammullen** [comment] 2020-04-01 10:14
Hi @tpittman1184 

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​

**Comment by tpittman1184** [comment] 2020-04-02 17:56
Sorry about that. Please let me know if this suffices:

Describe the bug
On the category page (Category=Skin Rejuvenation) of our store, the HydraFacial price that is shown is not correct. It says $255. It is a variable product with 4 package levels priced at $418, $540, $648, $720. These prices are shown on the actual HydraFacial product page: https://neamanplasticsurgery.com/product/hydrafacial/
​



To Reproduce
Steps to reproduce the behavior:

    Go to https://neamanplasticsurgery.com/product-category/skin-rejuvenation/
    Scroll down and look at HydraFacial (New!) listed product price is $255
    Click on HydraFacial (New!) product and review prices listed. URL Should be https://neamanplasticsurgery.com/product/hydrafacial/
    See four prices listed start at $418 up to $720
    ​
   Screenshots:

![image](https://user-images.githubusercontent.com/62968979/78281203-2c639f00-74cf-11ea-83f2-b423a122a982.png)

![image](https://user-images.githubusercontent.com/62968979/78281405-79477580-74cf-11ea-9a42-8e3e1ab5fa0c.png)

![image](https://user-images.githubusercontent.com/62968979/78281542-b0b62200-74cf-11ea-9db6-bf6df5ebc51b.png)
    ​
    Expected behavior
    The price listed on the category page for HydraFacial product should say $418 instead of $255. I have no idea where the $255 price is coming from.

**Comment by tpittman1184** [comment] 2020-04-02 22:43
Also system status info requested from WooCommerce tab: `
### WordPress Environment ###

WordPress address (URL): https://neamanplasticsurgery.com
Site address (URL): https://neamanplasticsurgery.com
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.25
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32-78.0-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: nea_
MaxMind GeoIP Database: ✔
Total Database Size: 51.56MB
Database Data Size: 40.92MB
Database Index Size: 10.64MB
nea_woocommerce_sessions: Data: 0.14MB + Index: 0.01MB + Engine MyISAM
nea_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_order_items: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nea_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
nea_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nea_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
nea_ewwwio_images: Data: 12.78MB + Index: 3.25MB + Engine MyISAM
nea_ewwwio_queue: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
nea_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nea_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
nea_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nea_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nea_pmxi_images: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
nea_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nea_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nea_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nea_postmeta: Data: 21.50MB + Index: 5.81MB + Engine InnoDB
nea_posts: Data: 3.52MB + Index: 0.80MB + Engine InnoDB
nea_rafflepress_contestants: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
nea_rafflepress_entries: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
nea_rafflepress_giveaways: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nea_rafflepress_polls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nea_redirects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nea_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nea_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
nea_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nea_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nea_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nea_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_wc_product_meta_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
nea_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nea_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nea_yoast_seo_links: Data: 0.34MB + Index: 0.17MB + Engine InnoDB
nea_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_hp_likes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_nf9kg2s1vd_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_gf_entry: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_gf_entry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_gf_entry_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_gf_form_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_gf_form_view: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_options: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_nf9kg2s1vd_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_nf9kg2s1vd_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_nf9kg2s1vd_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_nf9kg2s1vd_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf9kg2s1vd_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_nf9kg2s1vd_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Contact Form 7 MyMedLeads Lead Tracking Neaman: by MyMedLeads – 1.0b
Advanced Custom Fields PRO: by Elliot Condon – 5.8.1
Contact Form 7: by Takayuki Miyoshi – 99.9.9
Disable Gutenberg: by Jeff Starr – 1.8.1
Duplicate Post: by Enrico Battocchi – 3.2.2
301 Redirects: by WebFactory Ltd – 2.40
EWWW Image Optimizer: by Exactly WWW – 5.0.0
Official Facebook Pixel: by Facebook – 1.7.25
ACF Options Page Admin: by John A. Huebner II – 3.9.4
RafflePress Pro: by RafflePress – 1.3.1
Revisionize: by Jamie Chong – 2.3.2
WooCommerce: by Automattic – 3.8.0 – 4.0.1 is available
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO: by Team Yoast – 11.9 – Not tested with the active version of WooCommerce
WP All Import Pro: by Soflyy – 4.5.6
WP Mail SMTP: by WPForms – 1.3.3
WPForms Lite: by WPForms – 1.5.5

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Gravity Forms: by rocketgenius – 2.4.10
Header and Footer Scripts: by Digital Liberation – 2.1.1
Search Engine Visibility: by GoDaddy – 0.5
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.21
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Must Use Plugins (1) ###

System Plugin: by  – 3.16.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #37377 - /shop/
Cart: ❌ Page ID is set
but the page does not exist

Checkout: #37379 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: 
Version: 
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: neaman/woocommerce/archive-product.php
neaman/woocommerce/auth/footer.php
neaman/woocommerce/auth/form-grant-access.php
neaman/woocommerce/auth/form-login.php
neaman/woocommerce/auth/header.php
neaman/woocommerce/cart/cart-empty.php
neaman/woocommerce/cart/cart-item-data.php
neaman/woocommerce/cart/cart-shipping.php
neaman/woocommerce/cart/cart-totals.php
neaman/woocommerce/cart/cart.php
neaman/woocommerce/cart/cross-sells.php
neaman/woocommerce/cart/mini-cart.php
neaman/woocommerce/cart/proceed-to-checkout-button.php
neaman/woocommerce/cart/shipping-calculator.php
neaman/woocommerce/checkout/cart-errors.php
neaman/woocommerce/checkout/form-billing.php
neaman/woocommerce/checkout/form-checkout.php
neaman/woocommerce/checkout/form-coupon.php
neaman/woocommerce/checkout/form-login.php
neaman/woocommerce/checkout/form-pay.php
neaman/woocommerce/checkout/form-shipping.php
neaman/woocommerce/checkout/order-receipt.php
neaman/woocommerce/checkout/payment-method.php
neaman/woocommerce/checkout/payment.php
neaman/woocommerce/checkout/review-order.php
neaman/woocommerce/checkout/terms.php
neaman/woocommerce/checkout/thankyou.php
neaman/woocommerce/content-product.php
neaman/woocommerce/content-product_cat.php
neaman/woocommerce/content-single-product.php
neaman/woocommerce/content-widget-price-filter.php
neaman/woocommerce/content-widget-product.php
neaman/woocommerce/content-widget-reviews.php
neaman/woocommerce/emails/admin-cancelled-order.php
neaman/woocommerce/emails/admin-failed-order.php
neaman/woocommerce/emails/admin-new-order.php
neaman/woocommerce/emails/customer-completed-order.php
neaman/woocommerce/emails/customer-invoice.php
neaman/woocommerce/emails/customer-new-account.php
neaman/woocommerce/emails/customer-note.php
neaman/woocommerce/emails/customer-on-hold-order.php
neaman/woocommerce/emails/customer-processing-order.php
neaman/woocommerce/emails/customer-refunded-order.php
neaman/woocommerce/emails/customer-reset-password.php
neaman/woocommerce/emails/email-addresses.php
neaman/woocommerce/emails/email-customer-details.php
neaman/woocommerce/emails/email-downloads.php
neaman/woocommerce/emails/email-footer.php
neaman/woocommerce/emails/email-header.php
neaman/woocommerce/emails/email-order-details.php
neaman/woocommerce/emails/email-order-items.php
neaman/woocommerce/emails/email-styles.php
neaman/woocommerce/emails/plain/admin-cancelled-order.php
neaman/woocommerce/emails/plain/admin-failed-order.php
neaman/woocommerce/emails/plain/admin-new-order.php
neaman/woocommerce/emails/plain/customer-completed-order.php
neaman/woocommerce/emails/plain/customer-invoice.php
neaman/woocommerce/emails/plain/customer-new-account.php
neaman/woocommerce/emails/plain/customer-note.php
neaman/woocommerce/emails/plain/customer-on-hold-order.php
neaman/woocommerce/emails/plain/customer-processing-order.php
neaman/woocommerce/emails/plain/customer-refunded-order.php
neaman/woocommerce/emails/plain/customer-reset-password.php
neaman/woocommerce/emails/plain/email-addresses.php
neaman/woocommerce/emails/plain/email-customer-details.php
neaman/woocommerce/emails/plain/email-downloads.php
neaman/woocommerce/emails/plain/email-order-details.php
neaman/woocommerce/emails/plain/email-order-items.php
neaman/woocommerce/global/breadcrumb.php
neaman/woocommerce/global/form-login.php
neaman/woocommerce/global/quantity-input.php
neaman/woocommerce/global/sidebar.php
neaman/woocommerce/global/wrapper-end.php
neaman/woocommerce/global/wrapper-start.php
neaman/woocommerce/loop/add-to-cart.php
neaman/woocommerce/loop/loop-end.php
neaman/woocommerce/loop/loop-start.php
neaman/woocommerce/loop/no-products-found.php
neaman/woocommerce/loop/orderby.php
neaman/woocommerce/loop/pagination.php
neaman/woocommerce/loop/price.php
neaman/woocommerce/loop/rating.php
neaman/woocommerce/loop/result-count.php
neaman/woocommerce/loop/sale-flash.php
neaman/woocommerce/myaccount/dashboard.php
neaman/woocommerce/myaccount/downloads.php
neaman/woocommerce/myaccount/form-add-payment-method.php
neaman/woocommerce/myaccount/form-edit-account.php
neaman/woocommerce/myaccount/form-edit-address.php
neaman/woocommerce/myaccount/form-login.php
neaman/woocommerce/myaccount/form-lost-password.php
neaman/woocommerce/myaccount/form-reset-password.php
neaman/woocommerce/myaccount/lost-password-confirmation.php
neaman/woocommerce/myaccount/my-account.php
neaman/woocommerce/myaccount/my-address.php
neaman/woocommerce/myaccount/my-downloads.php
neaman/woocommerce/myaccount/my-orders.php
neaman/woocommerce/myaccount/navigation.php
neaman/woocommerce/myaccount/orders.php
neaman/woocommerce/myaccount/payment-methods.php
neaman/woocommerce/myaccount/view-order.php
neaman/woocommerce/notices/error.php
neaman/woocommerce/notices/notice.php
neaman/woocommerce/notices/success.php
neaman/woocommerce/order/form-tracking.php
neaman/woocommerce/order/order-again.php
neaman/woocommerce/order/order-details-customer.php
neaman/woocommerce/order/order-details-item.php
neaman/woocommerce/order/order-details.php
neaman/woocommerce/order/order-downloads.php
neaman/woocommerce/order/tracking.php
neaman/woocommerce/product-searchform.php
neaman/woocommerce/single-product/add-to-cart/external.php
neaman/woocommerce/single-product/add-to-cart/grouped.php
neaman/woocommerce/single-product/add-to-cart/simple.php
neaman/woocommerce/single-product/add-to-cart/variable.php
neaman/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
neaman/woocommerce/single-product/add-to-cart/variation.php
neaman/woocommerce/single-product/meta.php
neaman/woocommerce/single-product/photoswipe.php
neaman/woocommerce/single-product/price.php
neaman/woocommerce/single-product/product-attributes.php
neaman/woocommerce/single-product/product-image.php
neaman/woocommerce/single-product/product-thumbnails.php
neaman/woocommerce/single-product/rating.php
neaman/woocommerce/single-product/related.php
neaman/woocommerce/single-product/review-meta.php
neaman/woocommerce/single-product/review-rating.php
neaman/woocommerce/single-product/review.php
neaman/woocommerce/single-product/sale-flash.php
neaman/woocommerce/single-product/share.php
neaman/woocommerce/single-product/short-description.php
neaman/woocommerce/single-product/stock.php
neaman/woocommerce/single-product/tabs/additional-information.php
neaman/woocommerce/single-product/tabs/description.php
neaman/woocommerce/single-product/tabs/tabs.php
neaman/woocommerce/single-product/title.php
neaman/woocommerce/single-product/up-sells.php
neaman/woocommerce/single-product-reviews.php
neaman/woocommerce/single-product.php
neaman/woocommerce/taxonomy-product_cat.php
neaman/woocommerce/taxonomy-product_tag.php


### Action Scheduler ###

Complete: 2
Oldest: 2020-03-25 18:16:54 +0000
Newest: 2020-04-02 18:05:12 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by juliaamosova** [comment] 2020-04-24 19:57
Hi @tpittman1184,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it. We must be able to reproduce it on our own test sites without using yours. 

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-04-24 19:57 UTC
Labels: status: needs feedback
