### ISSUE TITLE
woo commerce checkout country field double drop down how to fixed it?

### ISSUE THREAD

**Issue by wtmPurnendu** [woocommerce/woocommerce#25291] opened 2019-12-23 09:28 UTC
![Capture](https://user-images.githubusercontent.com/50483586/71349251-94335100-2594-11ea-9ba4-4c410c1f3798.PNG)

**Comment by tammullen** [comment] 2019-12-23 21:10
Hi @wtmPurnendu! Thanks for raising this issue.

However it is not clear how to reproduce it, I don't see anything like this when I try to reproduce it.

Please provide more detail of the issue and the exact steps to reproduce the issue as well as the other information required by our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=)

**Comment by juliaamosova** [comment] 2019-12-24 13:02
Hi @wtmPurnendu! Please test your site for theme and plugins conflict - it looks like your theme or one of the plugins is interfering. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2019-12-24 13:05
@wtmPurnendu I am going to close this issue due to it not being reproducible with any of our default themes and on the sites where only WooCommerce is installed. 

Feel free to comment in case you think we missed something and we will take a second look.

**Closed by juliaamosova** 2019-12-24 13:05 UTC
Labels: can't reproduce
