### ISSUE TITLE
Issues after updating to 3.6.1

### ISSUE THREAD

**Issue by fesarlis** [woocommerce/woocommerce#23391] opened 2019-04-19 09:38 UTC
I have noticed the following after updating:

1. Upgrade database got stuck. Shop was not working. Workaround: I manually ran all scheduled tasks and I got 'upgrade complete'.

2. Order did not complete in the frontend. No thank you page. After 'Place order' was clicked, it simply scrolled back to the top (like when a required field is not filled). In the backend, the order is shown as expected. Workaround: Downgraded to 3.5.7. Still not sure if it will not cause any issues with the upgraded database.

**Comment by iMiMx** [comment] 2019-04-19 10:57
I think because of 2. New Order/Confirmation emails also do not fire.

**Comment by uok** [comment] 2019-04-19 10:58
ad 1) are you using a dedicated cron job? WP/Woo need it to process background jobs

**Comment by GlennMartin1** [comment] 2019-04-19 11:08
Point 1 is a known issue, duplicate of https://github.com/woocommerce/woocommerce/issues/23373.

**Comment by peterfabian** [comment] 2019-04-19 17:02
Hi, 

Regarding 1: For upgrade procedures to work, WP CRON must work, otherwise the scheduled tasks never get triggered. 
You can execute the pending tasks from WooCommerce > Status > Scheduled Actions, click on Pending and there is a 'Run' link on each line (it appears on mouse over).

If you encountered a failed tasks in Action Scheduler, you might need to delete it from the database manually. (It's in wp_posts, you can identify which one you need to delete from Action Scheduler list under Failed tasks, e.g. `Fatal error: Uncaught ActionScheduler_InvalidActionException: Action [2813] has invalid arguments. It cannot be JSON decoded...` means you need to delete task 2813).

Ad no 2: can you please include your system status report? Does this happen with all payment gateways or only with specific ones? I was not able to reproduce this, so if you have any hints how to reproduce this would be appreciated.

**Comment by fesarlis** [comment] 2019-04-19 17:08
I have tried with bank transfer. Not so easy to either test it thoroughly or try to upgrade WC again as this is a production site. As for the status report please let me know how to provide it to you without making it public.

**Comment by iMiMx** [comment] 2019-04-19 17:17
> I have tried with bank transfer. Not so easy to either test it thoroughly or try to upgrade WC again as this is a production site. As for the status report please let me know how to provide it to you without making it public.

I was seeing the exact same problem - it was also apparent with a Credit Card gateway as well, as it didn't return to the 'thank you' page but did redirect to the external gateway - bank transfer just kept scrolling back to the top, so people submitted multiple orders.

My cause turned out to be an email customiser plugin.  Woocommerce -> Logs -> Any fatal-errors shown there that coincide with your attempts?  This was how I narrowed mine down.

```
2019-04-19T09:55:35+00:00 CRITICAL Uncaught Error: Class 'Emogrifier' not found in /var/www/html/wp-content/plugins/woocommerce-email-control/ec-email-control.php:1068
Stack trace:
```

Once disabled everything went back to normal.  Suspect you have something similar perhaps.

**Comment by fesarlis** [comment] 2019-04-19 17:20
Could you please mention what email customizer plugin you use? Because I am also using one (yith email customizer)

**Comment by fesarlis** [comment] 2019-04-19 17:21
I am also using an email customizer plugin (yith email customizer).

**Comment by peterfabian** [comment] 2019-04-19 17:33
Thanks for the update. WC 3.6 updated the Emogrifier library to 2.1: #22342
Seems like the email customization plugins excpect Emogrifier to be loaded (or expects a different version?).

I would suggest contacting the authors of the email customization plugins and disabling the plugin until an update for them gets released.

**Comment by iMiMx** [comment] 2019-04-20 06:56
For my case specifically, a hack fix for the email customiser plugin I'm using

- In ec-email-control.php 
- Find the below at 1068:

`$emogrifier = new Emogrifier( $content, $css ); `

- Replace:

` $emogrifier = new \Pelago\Emogrifier( $content, $css );`

**Comment by peterfabian** [comment] 2019-04-22 17:17
@fesarlis is it fine to close this issue?

**Comment by fesarlis** [comment] 2019-04-22 19:11
Hello Peter, sorry for late reply.
I haven't had the time to test it yet, but I suppose it's OK to close the thread. Should I reply here or open a new one in case I encounter some more problems?
Thanks again

**Comment by peterfabian** [comment] 2019-04-23 07:07
Please create a new issue if you encounter more problems. Thanks!

**Closed by peterfabian** 2019-04-23 07:07 UTC
Labels: status: needs feedback
