### ISSUE TITLE
invalid download link

### ISSUE THREAD

**Issue by taswegienne** [woocommerce/woocommerce#17000] opened 2017-09-30 08:46 UTC
I'm at my wits' end. I swear I've checked all the things, but my customers still cannot download any digital goods purchased from my store. You click the link and it just says invalid download link, go to store. This is a new issue. Any ideas? 

### WordPress Environment ###

Home URL: https://www.sewknitlove.co
Site URL: https://www.sewknitlove.co
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_z2p9k6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Redux Framework: by Team Redux – 3.6.5
Akismet Anti-Spam: by Automattic – 4.0
Calculated Fields Form: by CodePeople – 1.0.178
Contact Form 7: by Takayuki Miyoshi – 4.9
Disable New User Notifications: by Thomas Griffin – 1.0.2
Disable Title: by Frank Staude – 0.9
EWWW Image Optimizer: by Shane Bishop – 3.6.1
WooCommerce Flip Product Image: by Fialovy – 1.2
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.1.3
Intense: by Intense Visions – 2.8.0
Jetpack by WordPress.com: by Automattic – 5.3
MailChimp for WooCommerce: by MailChimp – 2.0.1
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0.1
Really Simple SSL: by Rogier Lankhorst – 2.5.20
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.5.1.1

Simple Social Icons: by Nathan Rice – 2.0.1
To Top: by Catch Themes – 1.5.3
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.1.1

Ultimate Social: by WPSmarter – 6.0.5
Digital Goods Checkout for WooCommerce: by WebSmacker – 1.3
Shortcodes by Angie Makes: by Chris Baldelomar – 3.40
WooCommerce Weight Based Shipping +: by dangoodman – 4.2.1
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce Customizer: by SkyVerge – 2.5.0
WooCommerce MailChimp: by Saint Systems – 2.1.2
WooCommerce: by Automattic – 3.1.2
Yoast SEO: by Team Yoast – 5.4.2
WP Fastest Cache: by Emre Vona – 0.8.7.3
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WPS Hide Login: by Remy Perona for WPServeur – 1.1.7
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.4.3
YITH WooCommerce Cart Messages: by YITHEMES – 1.2.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2410 - /shop/
Cart: #2411 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Sew Knit Love
Version: 1.0.0
Author URL: http://www.alineddesign/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by dougaitken** [comment] 2017-10-01 09:14
Duplicate of #17001

**Closed by dougaitken** 2017-10-01 09:14 UTC
