### ISSUE TITLE
Woo Commerce-Category image edit

### ISSUE THREAD

**Issue by Sondg22** [woocommerce/woocommerce#23970] opened 2019-06-19 23:11 UTC
**Describe the bug**
Woo Commerce-Category Picture Edit.  When editing a current category in Woo Commerce the picture will not update after it has been changed.

**To Reproduce**
1. Go to Products 
2. Click on Category 
3. Choose an existing category choose "edit"
4. Scroll down to "Thumbnail"  upload image
5. scroll down to and click "update"
6. nothing updates or changes

**Expected behavior**
After you make your changes and edits. they should appear after you click update.

**WordPress Environment**
<details>

</details>

**Comment by claudiosanches** [comment] 2019-06-19 23:25
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried all steps and it appeared to work correctly.

It could be caused by a 3rd party plugin or code in your theme's. You could try disable your plugins and with a default WordPress theme.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-06-19 23:25 UTC

**Comment by Sondg22** [comment] 2019-06-20 01:21
Thank you.  I looked into the plugins and it was the "Yoast SEO" plugin that caused the problem.
