### ISSUE TITLE
Product importer unable to update products based on SKU

### ISSUE THREAD

**Issue by PatrikParkinenLevelup** [woocommerce/woocommerce#23648] opened 2019-05-08 08:16 UTC
The built-in product importer has an option to "Existing products that match by ID or SKU will be updated. Products that do not exist will be skipped". But supplying only an SKU and a product longdescription (content), results in errors that the SKU already exists.

**Comment by rodrigoprimo** [comment] 2019-05-08 18:13
I was not able to reproduce this issue on a clean WooCommerce install. To test, I first imported products from WooCommerce [sample_products.csv](https://github.com/woocommerce/woocommerce/blob/380ff713c2453f1b9c2bfcfd3a1a1419e525376d/sample-data/sample_products.csv). I then run the importer again, making sure to select the option "Update existing products" using a CSV file with the following content:

```
SKU,Description
Woo-tshirt-logo,New product description
```

As expected, the description of the product "Woo-tshirt-logo", was updated to "New product description". Do you get the same results using the same files that I used?

It would help to test this issue if you could export your products to a CSV file and share it together with the file that you are trying to import.

**Comment by kloon** [comment] 2019-05-09 10:41
As per Rodrigo, be sure to check the option `Update existing products` before importing and ensure you have the SKU header and fields present in the file.

![](https://cld.wthms.co/fCagxd+)

Following those steps the products update for me as well so not able to replicate.

Closing this issue now, but will gladly reopen when you can provide details steps on how to replicate as well as a copy of the file that is in the correct format.

**Closed by kloon** 2019-05-09 10:41 UTC
