### ISSUE TITLE
[GlobalStep] Product with 2 quantity gets added to the Cart while adding a product using "?add-to-cart=VARIABLE_PRODUCT_ID&variation_id=VARIABLE_PRODUCT_ID".

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29498] opened 2021-03-25 15:27 UTC
## Bug Description:
Product with 2 quantity gets added to the Cart while adding a product using "?add-to-cart=VARIABLE_PRODUCT_ID&variation_id=VARIABLE_PRODUCT_ID".

## Test Instructions:
https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.2#validate-variation-id-while-adding-products-to-the-cart--29208

## Environment:
Woocommerce Version: WooCommerce 5.2 Beta and 5.0
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard 
1. Add a Variable product with some variations.
1. Note down the Product ID and Variation ID.
1. Now go to frontend.
1. Try to add a product to the cart with ?add-to-cart=VARIABLE_PRODUCT_ID&variation_id=VARIABLE_PRODUCT_ID
1. Observe that  product with 2 quantity gets added to the cart.

## Actual Result:
Product with 2 quantity gets added to the Cart while adding a product using "?add-to-cart=VARIABLE_PRODUCT_ID&variation_id=VARIABLE_PRODUCT_ID".

## Expected Result:
Product with 1 quantity should get added to the Cart while adding a product using "?add-to-cart=VARIABLE_PRODUCT_ID&variation_id=VARIABLE_PRODUCT_ID".

## Video:

https://user-images.githubusercontent.com/41110392/112499104-284e2280-8dad-11eb-903d-bb18802f77d3.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://positive-milkweed.jurassic.ninja
Site address (URL): https://positive-milkweed.jurassic.ninja
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Total Database Size: 5.54MB
Database Data Size: 4.08MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
nav_menu_item: 5
page: 6
post: 2
product: 18
product_variation: 7
shop_order: 1
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.5
Facebook for WooCommerce: by Facebook – 2.3.3
Jetpack by WordPress.com: by Automattic – 9.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Shipping & Tax: by Automattic – 1.25.10
WooCommerce: by Automattic – 5.0.0 (update to version 5.1.0 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2021-03-24 14:32:52 +0000
Newest: 2021-03-25 09:20:32 +0000

`
```
</details>

**Comment by zhongruige** [comment] 2021-03-26 17:59
Hi @gglobalstep,

Thank you for reporting this issue! The issue appears to be with the Twenty Twenty-one theme where we aren't showing messages in the UI when a product is added to the cart. So what happened in this case (you can see this in the video as the cart message shows twice) is the URL may have been tried to be entered twice. I wasn't able to replicate the duplicate of the number of items in the cart, but I believe it's a UX issue with the way we aren't surfacing messages in the Twenty Twenty-one theme.

Loading the link (e.g. `https://mystore.com/?add-to-cart=10&variation_id=33`) on Storefront:

<img width="1153" alt="Screen Shot 2021-03-26 at 11 56 11 AM" src="https://user-images.githubusercontent.com/71906536/112673585-853bee00-8e2a-11eb-973f-c5a04001a620.png">

Loading the same link on the Twenty Twenty-one theme, note the lack of message:

<img width="965" alt="Screen Shot 2021-03-26 at 11 58 24 AM" src="https://user-images.githubusercontent.com/71906536/112673664-9d137200-8e2a-11eb-8ffb-3840e7e02f37.png">

This also occurs when using invalid combinations. For example, storefront:

<img width="1253" alt="Screen Shot 2021-03-26 at 11 46 47 AM" src="https://user-images.githubusercontent.com/71906536/112673710-a8669d80-8e2a-11eb-8fd8-232cc2e65625.png">

And again on Twenty Twenty-one:

<img width="965" alt="Screen Shot 2021-03-26 at 11 58 24 AM" src="https://user-images.githubusercontent.com/71906536/112673732-adc3e800-8e2a-11eb-9353-d62d9a80e3c0.png">

**Comment by gglobalstep** [comment] 2021-03-31 16:15
Verified this issue on WooCommerce 5.2 RC 1 and unable to reproduce it.

**Comment by zhongruige** [comment] 2021-03-31 16:18
Thank you for verifying this issue @gglobalstep! We will go ahead and close this. If there's anything else, please leave a comment here and we'll take another look :)

**Closed by zhongruige** 2021-03-31 16:18 UTC
Labels: needs feedback
