### ISSUE TITLE
HTML special characters become question mark on e-mail

### ISSUE THREAD

**Issue by cerfweb** [woocommerce/woocommerce#21099] opened 2018-08-20 07:45 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set Japanese as WordPress site setting
2. Submit a purchase with Woocommerce
3. Get an e-mail automatically

## Expected/actual behavior

When I follow those steps, I see ? (question mark) in the place of html special characters.
For example, the price is marked 23,00?? instead of 23,00 €.
&nbsp; and &euro; become "??".
This issue appears when the site language setting is in Japanese. With English or French, that shows correctly.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [?] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

WordPress 環境
--
ホーム URL: |   | https://testweb.kinuta.fr/ja
サイト URL: |   | https://testweb.kinuta.fr/ja
WooCommerce バージョン: |   | 3.5.0
ログディレクトリは書き込み可能です。: |   | /home/kinutafrgu/testweb/ja/wp-content/uploads/wc-logs/
WordPress バージョン: |   | 4.9.8
WordPress マルチサイト: |   | –
WordPress メモリ制限: |   | 512 MB
WordPress デバッグモード: |   | –
WordPress cron: |   |  
言語: |   | ja
外部オブジェクトキャッシュ: |   | –

```
</details>

**Comment by claudiulodro** [comment] 2018-08-28 18:06
Hi there.

It worked great in my testing on a site with only WooCommerce installed, a default theme (twentytwelve) and the latest version of the Japanese translations:

<img width="479" alt="screen shot 2018-08-28 at 10 57 43 am" src="https://user-images.githubusercontent.com/7317227/44741252-611ca280-aab1-11e8-96d4-c76db6c64b45.png">

You haven't provided any further details so I can't really investigate it further. Potential other sources you could look that may cause problems are the e-mail client you are using, your theme if it has any e-mail template overrides, or any multilingual plugins if you are using them.

Since there isn't further information to reproduce the problem and it can't be reproduced on a simple WooCommerce installation I must close this issue as non-reproducible. Thanks.

**Closed by claudiulodro** 2018-08-28 18:06 UTC
