### ISSUE TITLE
I am trying to upload CSV file and it is keep getting stuck. I have also tried to make pieces of the file But still stucking.

### ISSUE THREAD

**Issue by Zakrazy** [woocommerce/woocommerce#27342] opened 2020-08-14 17:51 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by Zakrazy** [comment] 2020-08-14 17:52
Woocommerce Import functions stucks always

**Comment by juliaamosova** [comment] 2020-08-14 19:12
Hi @Zakrazy,

Thanks for raising the issue. However, you did not fill out the but report template. It will be helpful to us if you could provide us with at least the System Status Report and also if you could ensure that you've done themes and plugins conflict which may cause an issue. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

If you are able to share the CSV file with us, it will be great as well so that we could test. If not, can you tell us how many products are in the CSV file?

**Comment by Zakrazy** [comment] 2020-08-15 06:58
There are 505 Products. I have been trying to break down the CSV file in to 4 Pieces. and I have also tried with disabling all the plugins & Changing theme to storefront.

**Comment by Zakrazy** [comment] 2020-08-15 08:24
it always uploads 305 Products and Publishes 275. then stucks
![Capture](https://user-images.githubusercontent.com/49778803/90308641-87d07f80-defa-11ea-955c-154099b821b6.JPG)

**Comment by tammullen** [comment] 2021-03-25 20:46
Hi @Zakrazy 

Sorry for the delay in replying.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 20:46 UTC
Labels: has feedback
