### ISSUE TITLE
Search not working on Order Page

### ISSUE THREAD

**Issue by Mikkaluokta** [woocommerce/woocommerce#14709] opened 2017-04-26 09:02 UTC
### EXPLANATION OF THE ISSUE

The search function on the ORDER PAGE dont work anymore. If I seacrh for customer or Order number I get no matches.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://www.shopinscandinavia.com
Site URL: https://www.shopinscandinavia.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 256 MB
PHP Time Limit: 240
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: gc6r_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

All In One SEO Pack Pro: av Michael Torbert – 2.4.12.1
Fusion Builder: av ThemeFusion – 1.1.6
Fusion Core: av ThemeFusion – 3.1.6
Insert Headers and Footers: av WPBeginner – 1.4.2
Search Everything: av Sovrn
zemanta – 8.1.9

WPML Multilingual CMS: av OnTheGoSystems – 3.7.0
WooCommerce Klarna Gateway: av WooCommerce – 2.3.6
WooCommerce Gateways Country Limiter: av OnTheGoSystems – 1.4
WooCommerce Klarna Avada theme Compatibility: av Krokedil – 1.0
WooCommerce Klarna Checkout change checkout URL: av Krokedil – 1.0
WooCommerce Multilingual: av OnTheGoSystems – 4.1.2
WooCommerce PDF Invoices & Packing Slips: av Ewout Fernhout – 1.6.5
WooCommerce: av Automattic – 3.0.4
WooCommerce Helper: av WooCommerce – 1.7.2 – Nätverk aktiverat
WP Google Maps: av WP Google Maps – 6.4.03
WP Super Cache: av Automattic – 1.4.9
WPML Media: av OnTheGoSystems – 2.2.0
WPML String Translation: av OnTheGoSystems – 2.5.3
WPML Translation Management: av OnTheGoSystems – 2.3.0
WPML Widgets: av Jeroen Sormani – 1.0.6
NextGEN Gallery: av Imagely – 2.2.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Butikbas: #7 - /butik/
Varukorg: #8 - /varukorg/
Kassan: #9 - /kassan/
Mitt konto: #10 - /mitt-konto/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.1.6
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: ✔
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Villkorssida: ✔
`
```
</details>

**Comment by mikejolley** [comment] 2017-04-26 10:57
Confirmed as working. Order ID search works, as does name search.

If you're doing a full name search, note it won't work on pre 3.0 orders due to the fields being separate. See https://wordpress.org/support/topic/wc-3-0-orders-search/#post-9060771

I'd also check WPML is not affecting this since it may change IDs for each language.

Closing as non reproducible.

**Closed by mikejolley** 2017-04-26 10:57 UTC

**Comment by somtam** [comment] 2017-04-27 12:21
Same problem here since few days.

In orders page, both with the search field on the right and with the "Find a customer" field.
Using email as search term, the ajax returns the customer, but after click Filter there is no orders found (instead there is).

Moreover if you make another ajax search, after using the ajax filter on the "no orderd found", you get an error and I think it is due to the not valid post type sent in the get var. Infact it sends "post_type=Array".

I didn't update to WC version 3 (still with 2.6.14) because of the incompatibility with Enfold. Waiting the update of the theme.

Thanks for support
