### ISSUE TITLE
Coupon "usage limit has been reached" after a failed payment

### ISSUE THREAD

**Issue by ChrisBates** [woocommerce/woocommerce#27673] opened 2020-09-15 00:44 UTC
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Coupons with a usage limit are showing "usage limit has been reached" after a failed payment using that coupon.

**Expected behavior**
Coupon should still be usable after a failed payment. 

**Actual behavior**
Applying a coupon to an order (specifically with a usage limit of 1) and making a failed payment at checkout places a `_maybe_used_by` lock on the coupon itself - making it unusable by the same person.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a coupon with a usage limit of 1
2. Add it to your cart
3. Checkout in a way that causes a failed payment
4. Coupon now gets removed as 'invalid'
5. Try re-add the coupon, you'll be told "usage limit has been reached"

**Screenshots**
![image](https://user-images.githubusercontent.com/50668839/93151457-24c14b00-f73b-11ea-86d5-8332a57f778f.png)
![image](https://user-images.githubusercontent.com/50668839/93151352-ddd35580-f73a-11ea-9a26-519d31c5a898.png)
![image](https://user-images.githubusercontent.com/50668839/93151369-e6c42700-f73a-11ea-83fd-637c3a6a4fcc.png)
![image](https://user-images.githubusercontent.com/50668839/93151388-f0e62580-f73a-11ea-9520-9a4d03f60332.png)
![image](https://user-images.githubusercontent.com/50668839/93151397-f7749d00-f73a-11ea-969e-6b9756ebf29e.png)

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.f*******e.com
Site address (URL): https://www.f*******e.com
WC Version: 4.5.1
REST API Version: ✔ 4.5.1
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ❌ To allow logging
make /var/www/html/src/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.9
PHP Post Max Size: 10 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.10
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.1
WC Database Prefix: wp_
Total Database Size: 5346.26MB
Database Data Size: 3706.20MB
Database Index Size: 1640.06MB
wp_woocommerce_sessions: Data: 14.03MB + Index: 1.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 25.55MB + Index: 8.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 448.98MB + Index: 387.97MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fakenames: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
w****o_products: Data: 13.52MB + Index: 2.84MB + Engine InnoDB
wp_actionscheduler_actions: Data: 10.03MB + Index: 17.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 8.02MB + Index: 8.03MB + Engine InnoDB
wp_as3cf_items: Data: 13.52MB + Index: 23.09MB + Engine InnoDB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blc_instances: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_blc_links: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_blc_synch: Data: 0.27MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 115.66MB + Index: 81.05MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 4.52MB + Index: 0.58MB + Engine InnoDB
wp_gf_entry_meta: Data: 11.52MB + Index: 17.56MB + Engine InnoDB
wp_gf_entry_notes: Data: 3.52MB + Index: 0.56MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mclean_refs: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_oauth_access_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_authorization_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 29.22MB + Index: 10.08MB + Engine InnoDB
wp_oses_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 1666.17MB + Index: 6.48MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_failures: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 952.66MB + Index: 842.36MB + Engine InnoDB
wp_posts: Data: 105.23MB + Index: 43.45MB + Engine InnoDB
wp_redirection_404: Data: 5.03MB + Index: 14.13MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_termmeta: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_terms: Data: 0.23MB + Index: 0.30MB + Engine InnoDB
wp_terms_back: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_term_relationships: Data: 13.55MB + Index: 8.47MB + Engine InnoDB
wp_term_relationships_back: Data: 7.52MB + Index: 4.39MB + Engine InnoDB
wp_term_taxonomy: Data: 0.22MB + Index: 0.27MB + Engine InnoDB
wp_term_taxonomy_back: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 130.45MB + Index: 81.17MB + Engine InnoDB
wp_users: Data: 7.41MB + Index: 7.25MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 10.52MB + Index: 12.00MB + Engine InnoDB
wp_wc_order_stats: Data: 5.52MB + Index: 4.53MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 7.52MB + Index: 13.83MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta_back: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcwl: Data: 2.06MB + Index: 0.09MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 2.17MB + Index: 4.31MB + Engine InnoDB
wp_yoast_indexable: Data: 54.61MB + Index: 26.61MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 2.39MB + Index: 2.36MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.38MB + Index: 0.22MB + Engine InnoDB
wp_yoast_seo_meta: Data: 13.36MB + Index: 0.00MB + Engine InnoDB
ziplatlng: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
_mig_wpmdb_alter_statements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 26
acf-field-group: 5
attachment: 65944
blocks: 17
custom_css: 1
li_event: 366
nav_menu_item: 369
oembed_cache: 17
page: 64
post: 331
product: 21325
product_variation: 13904
revision: 623
shop_coupon: 2927
shop_order: 94529
shop_order_refund: 11094
store: 21
wc_order_status: 7
wc_pickup_location: 18
wll_records: 589
wo_client: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Gravity Forms: by Gravity Forms – 2.4.20
Admin Menu Editor Pro: by Janis Elsts – 2.12.2
Advanced Custom Fields PRO: by Elliot Condon – 5.9.0
WP Offload Media: by Delicious Brains – 2.4.2
Application Passwords: by George Stephanis – 0.1.2
Classic Editor: by WordPress Contributors – 1.6
Custom Post Type UI: by WebDevStudios – 1.8.0
Geolocation IP Detection: by Yellow Tree (Benjamin Pick) – 3.1.1
Go Live Update Urls: by OnPoint Plugins – 6.1.2
Lucky Orange | Chat, heatmaps, polls, visitor recordings, live analytics.: by LuckyOrange.com – 1.98
Members: by MemberPress – 3.0.10
PixelYourSite PRO: by PixelYourSite – 7.6.5 – Installed version not tested with active version of WooCommerce 4.5.1
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 4.1.3 – Installed version not tested with active version of WooCommerce 4.5.1
PWD Content Sync Receiver: by Portland Web Design – 1.0.6
Redirection: by John Godley – 4.8
Redis Cache Pro: by Till Krüss – 1.9.0
Regenerate Thumbnails Advanced: by ShortPixel – 2.3.2
Safe SVG: by Daryll Doyle – 1.9.9
User Switching: by John Blackbourn & contributors – 1.5.5
When Last Login: by Yoohoo Plugins – 1.2
WooCommerce AvaTax [w****o Modified - DO NOT UPDATE AUTOMATICALLY]: by SkyVerge – 1.10.2 (update to version 1.10.3 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Brands: by WooCommerce – 1.6.19 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.3.0 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce UPS Shipping: by WooCommerce – 3.2.28 – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce Smart Coupons: by StoreApps – 4.8.0 (update to version 4.8.1 is available) – Installed version not tested with active version of WooCommerce 4.5.1
WooCommerce: by Automattic – 4.5.1 (update to version 4.5.2 is available)
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO: by Team Yoast – 14.8.1 – Installed version not tested with active version of WooCommerce 4.5.1
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Migrate DB Pro: by Delicious Brains – 1.9.10
WP Offload SES: by Delicious Brains – 1.5.3
YITH WooCommerce Anti-Fraud Premium: by YITH – 1.1.9 – Installed version not tested with active version of WooCommerce 4.5.1

### Inactive Plugins (10) ###

Bugsnag Error Monitoring: by Bugsnag Inc. – 1.5.0
GDPR Cookie Consent: by WebToffee – 1.9.0
PixelYourSite Pinterest: by PixelYourSite – 2.0.7 – Installed version not tested with active version of WooCommerce 4.5.1
PWD Flipping Book Scraper: by Portland Web Design – 1.0.1
PWD Gravity Forms Monday.com Integration: by Portland Web Design – 1.1
PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.245 – Installed version not tested with active version of WooCommerce 4.5.1

Query Monitor: by John Blackbourn – 3.6.4
ShortPixel Image Optimizer: by ShortPixel – 4.20.2
WP Rocket [Jareds Version 07/12/19]: by WP Media – 3.4.2.2
YITH WooCommerce Wishlist: by YITH – 3.0.13 – Installed version not tested with active version of WooCommerce 4.5.1

### Dropin Plugins (1) ###

object-cache.php: Redis Cache Pro

### Must Use Plugins (1) ###

Purge Cache: by The Code Company – 1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #74 - /shop
Cart: #75 - /cart
Checkout: #76 - /checkout
My account: #77 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: w****o
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.6.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: w****o-child/woocommerce/archive-product.php
w****o-child/woocommerce/cart/cart-empty.php
w****o-child/woocommerce/cart/cart-shipping.php
w****o-child/woocommerce/cart/cart-totals.php
w****o-child/woocommerce/cart/cart.php
w****o-child/woocommerce/cart/mini-cart.php
w****o-child/woocommerce/cart/proceed-to-checkout-button.php
w****o-child/woocommerce/checkout/form-billing.php
w****o-child/woocommerce/checkout/form-checkout.php
w****o-child/woocommerce/checkout/form-coupon.php
w****o-child/woocommerce/checkout/form-login.php
w****o-child/woocommerce/checkout/form-shipping.php
w****o-child/woocommerce/checkout/review-order.php
w****o-child/woocommerce/checkout/thankyou.php
w****o-child/woocommerce/content-product.php
w****o-child/woocommerce/content-product_cat.php
w****o-child/woocommerce/content-single-product.php
w****o-child/woocommerce/content-widget-product.php
w****o-child/woocommerce/emails/customer-new-account.php
w****o-child/woocommerce/emails/customer-on-hold-order.php
w****o-child/woocommerce/emails/customer-processing-order.php
w****o-child/woocommerce/emails/customer-reset-password.php
w****o-child/woocommerce/emails/email-footer.php version 2.3.0 is out of date. The core version is 3.7.0
w****o-child/woocommerce/emails/email-header.php version 2.4.0 is out of date. The core version is 4.0.0
w****o-child/woocommerce/emails/email-order-details.php
w****o-child/woocommerce/emails/email-order-items.php
w****o-child/woocommerce/emails/email-styles.php version 3.3.0 is out of date. The core version is 4.0.0
w****o-child/woocommerce/global/breadcrumb.php
w****o-child/woocommerce/global/quantity-input.php
w****o-child/woocommerce/global/wrapper-end.php
w****o-child/woocommerce/global/wrapper-start.php
w****o-child/woocommerce/loop/loop-end.php
w****o-child/woocommerce/loop/loop-start.php
w****o-child/woocommerce/loop/orderby.php
w****o-child/woocommerce/loop/pagination.php
w****o-child/woocommerce/loop/result-count.php
w****o-child/woocommerce/loop/sale-flash.php
w****o-child/woocommerce/myaccount/form-edit-account.php
w****o-child/woocommerce/myaccount/form-edit-address.php
w****o-child/woocommerce/myaccount/form-login.php
w****o-child/woocommerce/myaccount/form-lost-password.php
w****o-child/woocommerce/myaccount/my-address.php
w****o-child/woocommerce/myaccount/navigation.php
w****o-child/woocommerce/myaccount/orders.php
w****o-child/woocommerce/myaccount/view-order.php
w****o-child/woocommerce/notices/error.php
w****o-child/woocommerce/notices/notice.php
w****o-child/woocommerce/notices/success.php
w****o-child/woocommerce/order/order-details-item.php
w****o-child/woocommerce/order/order-details.php version 3.5.2 is out of date. The core version is 3.7.0
w****o-child/woocommerce/product-searchform.php
w****o-child/woocommerce/single-product/add-to-cart/simple.php
w****o-child/woocommerce/single-product/add-to-cart/variable.php
w****o-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
w****o-child/woocommerce/single-product/add-to-cart/variation.php
w****o-child/woocommerce/single-product/meta.php
flatsome/woocommerce/single-product/photoswipe.php
w****o-child/woocommerce/single-product/price.php
w****o-child/woocommerce/single-product/product-image.php
w****o-child/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
w****o-child/woocommerce/single-product/related.php
w****o-child/woocommerce/single-product/review.php
w****o-child/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
w****o-child/woocommerce/single-product/short-description.php
w****o-child/woocommerce/single-product/stock.php
w****o-child/woocommerce/single-product/tabs/description.php
w****o-child/woocommerce/single-product/tabs/tabs.php
w****o-child/woocommerce/single-product/title.php
w****o-child/woocommerce/single-product/up-sells.php
w****o-child/woocommerce/single-product-reviews.php version 3.6.0 is out of date. The core version is 4.3.0
w****o-child/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Save to Log
Webhooks Enabled: ❌
						No signature key configured

### Action Scheduler ###

Complete: 35,368
Oldest: 2020-08-14 17:43:00 -0700
Newest: 2020-09-14 17:37:20 -0700
`
```
</details>

**Comment by juliaamosova** [comment] 2020-09-15 15:57
Hi @ChrisBates,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using Stripe payment gateway but this seems to happen with [other gateways](https://github.com/woocommerce/woocommerce/issues/26743#issuecomment-692179962) as well. 

Below is a gif documenting my experience reproducing the issue:

http://g.recordit.co/2Le77QGIYM.gif

This seems like it could be a common use case and applying a coupon is one of our critical flows so I am giving this issue a `high` priority to work on.

**Comment by yukikatayama** [comment] 2020-09-22 17:24
Adding that this was also reported in 24322995-hc.

**Comment by ChrisBates** [comment] 2020-09-24 23:45
For anyone having this issue themselves, you can disable the behavior:
`add_filter( 'woocommerce_hold_stock_for_checkout', function() { return false; } );`

**Comment by basicsbyhill** [comment] 2020-10-25 03:37
Hi there, does anyone know if this bug has been fixed?

**Comment by damiannep** [comment] 2020-12-07 16:01
Another report of this in 3546055-zen

**Comment by renude** [comment] 2020-12-07 17:47
Another report: 3546055. Any updates on when this will be fixed?

**Comment by vedanshujain** [comment] 2020-12-15 10:46
This is happening because we are holding coupon from the earlier order for "hold stock" minutes and its getting counted towards the total usage. Coupon is freed only after the order is cancelled, instead of when payment fails, because it is still possible to retry the payment when the order is in payment failed status.

If we allow coupon to be used again after a failed payment, then usage limit cannot be enforced because if user has the correct link, they can complete the payment later on and coupon will be used twice. So coupon can be allowed to be used again only after the whole order is cancelled and not just after a failed payment.

I am adding a PR to improve these error messages (in #28592) so that we give better UX to customers instead of a bland "Usage limit reached" error message. Basically:
1. When user is logged in, and my account page is enabled, we will tell the user that they can retry the payment or cancel the order to free up the coupon.
2. When user is not logged in, we will tell the user to wait some time, or to contact the shop to request order cancellation to free up the coupon.

This should help with improving UX. I think this is the best approach for now, but please feel free to leave more questions/suggestions in case I am missing something.

**Comment by renude** [comment] 2020-12-15 15:40
Yeah, it should only get counted on a ‘successful’ order.  Are woocommerce techs working on fixing this?

Brandon

**Closed** 2020-12-21 13:22 UTC
Labels: category: release highlight, component: coupon, priority: high, type: bug

**Comment by renude** [comment] 2020-12-29 17:57
Hi Roy,

I know there’s been a long string of messages to resolve this issue. What’s the final solution to the coupon being used up after a failed payment?

Mush love,

Yosi Pearce
Chaga Dealer
c. 562-445-5358
drinkrenude.com
🍄

**Comment by yewzy** [comment] 2021-06-18 15:34
Is there a way to not count coupon usage until order is 'Successful‘？

**Comment by TimBHowe** [comment] 2022-02-10 21:54
As mentioned above this issue seems to steam from coupons that have a "usage limit per user" and the general inventory setting of "Hold stock (minutes)".
​https://woocommerce.com/document/configuring-woocommerce-settings/#products-inventory-options
​https://woocommerce.com/document/coupon-management/#usage-limits
​
https://github.com/woocommerce/woocommerce/blob/0a1b850fb35874e2b7dd639377c3ca0e4ba5c0be/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php#L491

​This means if a customer uses the coupon and the order fails, due to something like a card decline, and they do not complete the order they can't use the coupon until the hold stock limit expires.

There is the `woocommerce_coupon_hold_minutes` filter that can be used to override this timelimit. 

It looks like there isn't a setting for it in the backend and it just uses the  "Hold stock (minutes)" or 60 mins by default, but you should be able to add the following to allow users to excite the usage limit until there is a successful order with the following added to the site function.php file

```php
/**
 * Set the get_tentative_held_time for coupons to 0 mins
 */
add_filter(
	'woocommerce_coupon_hold_minutes',
	function() {
		return 0;
	}
);
```

There is a small possibility the users could end up firing multiple orders using the same coupon exceeding the usage limit but it seems difficult to do and unlikely.

Hope this helps some people.

**Comment by TimBHowe** [comment] 2022-02-11 15:13
Sorry to comment on a closed issue but this was the first one I found on the issue.

As mentioned in the comment above this is expected behavior https://github.com/woocommerce/woocommerce/issues/27673#issuecomment-745208406

The issue stems from a coupon that is set to have a "usage limit per user"  and the general inventory setting of "Hold stock (minutes)".
https://woocommerce.com/document/configuring-woocommerce-settings/#products-inventory-options
https://woocommerce.com/document/coupon-management/#usage-limits

This means if a customer uses the coupon and the order fails, due to something like a card decline, and they do not complete the order they can't use the coupon on another order until the hold stock time passes.

[` check_and_hold_coupon`](https://github.com/woocommerce/woocommerce/blob/0a1b850fb35874e2b7dd639377c3ca0e4ba5c0be/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php#L502)

So you could lower or set the Hold Stock to 0, but based on your business and inventory management this might not work for your store.

Alternatively, you can also use the following [`woocommerce_coupon_hold_minutes`](urhttps://github.com/woocommerce/woocommerce/blob/0a1b850fb35874e2b7dd639377c3ca0e4ba5c0be/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php#L492l) filter and function to set the time the site will hold coupons.

In this case, we set it to 0, but if you wanted to hold the coupons for sometime shorter or longer then you hold stock setting you update the following.

```php
/**
 * Set the get_tentative_held_time for coupons to 0 mins
 *
 * @param int $mins number of minutes to hole the coupon.
 * @return int
 */
function woo_set_coupon_hold_minutes( $mins ) {
	$mins = 0;
	return $mins;
};
add_filter( 'woocommerce_coupon_hold_minutes', 'woo_set_coupon_hold_minutes', 10, 1 );
```
Also @ChrisBates solution would work in the case you don't want to hold the coupon at all  https://github.com/woocommerce/woocommerce/issues/27673#issuecomment-698642894

Might be good to have this as a backend setting for Woo somewhere.

**Comment by React-quillaccursed8** [comment] 2025-02-09 00:03
> For anyone having this issue themselves, you can disable the behavior: `add_filter( 'woocommerce_hold_stock_for_checkout', function() { return false; } );`





kDeUoyyNSKzw
