### ISSUE TITLE
Multiple Coupon field in same page does not work.  

### ISSUE THREAD

**Issue by UmeedEmad** [woocommerce/woocommerce#19411] opened 2018-03-15 10:38 UTC
Like if we add another coupon input field in checkout page it does not work. only the first one applies the coupon code.

**Comment by mikejolley** [comment] 2018-03-15 11:30
I'm not really sure what you expect us to do with that information.

Just to humour the report, I duplicated the form in form-coupon.php and added a coupon to the second field. It applied.

If you can find an issue with the coupon form or scripts which prevents your form working, feel free to submit a pull request for consideration. There isn't much else we can do if this is something custom, and since there are no steps to reproduce I'm closing this report as invalid.

Thanks

**Closed by mikejolley** 2018-03-15 11:30 UTC

**Comment by mikejolley** [comment] 2018-03-15 11:58
This would be a form within a form, which is invalid.

**Comment by UmeedEmad** [comment] 2018-03-15 12:01
Do I need to use another action to hook inside order summary section? or it is not possible to have coupon code inside order summary sidebar?

**Comment by mikejolley** [comment] 2018-03-15 12:21
You'd probably need to handle the fields with javascript, but doing what you showed won't work because it will put a form within the existing checkout form.

**Comment by UmeedEmad** [comment] 2018-03-15 12:25
Ok Mike. Thanks for the help :)
