### ISSUE TITLE
CSV importer: preserve letter-casing in category names

### ISSUE THREAD

**Issue by paulcee** [woocommerce/woocommerce#24267] opened 2019-07-30 15:19 UTC
The CSV importer can create product categories.
Unfortunately, it seems to change the categories to title case, so you get "Dvds" instead of "DVDs", and "Usa" instead of "USA". This is bad English and looks unprofessional.
Is it possible to keep the original letter-casing from the import file?

**Comment by rodrigoprimo** [comment] 2019-07-30 22:40
I was not able to reproduce this problem. I tested using a modified version of the [sample_products.csv](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv) file where I added USA as the category of some products. After going through the importer, the category was successfully created preserving letter-casing. Could you please share the file that you are using to import where WooCommerce is not preserving the letter-casing? Are you testing on a clean WooCommerce install to rule out possible problems caused by other plugins? Thanks.

**Comment by claudiosanches** [comment] 2019-07-31 23:00
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried to submit a CSV like you described and it appeared to work correctly.

It could be that there's already two categories with similar name, try check it.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-07-31 23:00 UTC
Labels: status: needs feedback
