### ISSUE TITLE
CSV export JS package: Unnecessary escaping of negative numbers is preventing numerical analysis in spreadsheets

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce#25379] opened 2020-01-09 18:07 UTC
**Describe the bug**

> [!IMPORTANT]  
> This is the same issue as described in #53020 which is for PHP-based exporting from WC → Analytics. This issue is for the JS-based CSV exporting via `@woocommerce/csv-export`

When you export product data using the built-in CSV export tool, an apostrophe `'` is prepended to any 
negative Stock quantities. This is true on both simple and variable products.

**To Reproduce**
1. Set a product's stock to a negative number (this can happen "naturally" as a consequence of back orders)
2. Use the built-in CSV export tool
3. Look at the product's entry in the "Stock" column

**Screenshots**
![image](https://user-images.githubusercontent.com/20285748/72092361-2733f100-32e0-11ea-9f87-c72d0107aa40.png)

![image](https://user-images.githubusercontent.com/20285748/72092490-64987e80-32e0-11ea-8c84-38ddd5e6491b.png)

**Expected behavior**
As happens with a positive or 0 stock quantity, I expect the negative number to be exported cleanly.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

zen-2617821

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://admyn.mystagingwebsite.com
Site address (URL): https://admyn.mystagingwebsite.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.67.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Total Database Size: 33.03MB
Database Data Size: 16.19MB
Database Index Size: 16.84MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.22MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.20MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 4.45MB + Index: 4.42MB + Engine InnoDB
wp_posts: Data: 2.19MB + Index: 0.13MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 5.52MB + Index: 8.55MB + Engine InnoDB
wp_wps_key: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Classic Editor: by WordPress Contributors – 1.5
Hello Death: by Matt Mullenweg
Claudiu Lodromanean – 1.0

WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (103) ###

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #833 - /terms-and-conddfdsf/

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 106
Oldest: 2019-12-09 18:46:16 -0600
Newest: 2020-01-09 11:25:03 -0600

Pending: 3
Oldest: 2020-01-10 08:25:21 -0600
Newest: 2020-01-14 01:19:18 -0600

Canceled: 24
Oldest: 2019-12-18 15:59:30 -0600
Newest: 2020-01-08 01:14:53 -0600

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by ivantedja** [comment] 2020-01-12 13:28
Seems to be expected behaviour to prevent malicious input (if a field is prepended with `=` or `+` or `-` or `@`): https://github.com/woocommerce/woocommerce/blob/dbb8ab8d1e875528da6c81469df7855792a85e5f/includes/export/abstract-wc-csv-exporter.php#L371

**Comment by juliaamosova** [comment] 2020-01-14 20:43
Hi @dsmithweb,

Thank you for reporting the issue. However, this is not a bug. As mentioned by @ivantedja - the behavior is expected as described here:

https://github.com/woocommerce/woocommerce/blob/dbb8ab8d1e875528da6c81469df7855792a85e5f/includes/export/abstract-wc-csv-exporter.php#L355-L378

I am going to close this issue but please feel free to comment back in case you think I missed something.

**Comment by Jinksi** [comment] 2024-09-26 02:36
We're looking to rectify this downstream issue in WooPayments: https://github.com/Automattic/woocommerce-payments/issues/9303.

This is a burden for merchants who must remove the `'` from all negative values in a CSV manually. It is relatively common to see negative values in WooPayments, for fees and disputed transactions.

I'm re-opening this issue so we can consider making the escaping of negative values optional if the source is trusted and not user-generated (e.g. WC Analytics or WooPayments CSV exporting).

**Comment by haszari** [comment] 2024-10-17 23:23
> Seems to be expected behaviour to prevent malicious input (if a field is prepended with = or + or - or @):]

While it might be expected that we escape negative number values (or any cell starting with certain characters, e.g.`-`) … I don't think this is expected behaviour. It breaks the usability of the CSV. 

If we add a quote character at the start of a cell, should we not close the quote at the end? 

The current behaviour renders CSV files that merchants need to manually process to fix before they can use. 

- Is it safe to enquote the entire cell if the value is negative? e.g. `'-10.99`
- If we do that, is the CSV usable as is? i.e. does that fix the bug?

Our sanitisation must not break functionality.

**Comment by Jinksi** [comment] 2024-11-12 06:01
> If we add a quote character at the start of a cell, should we not close the quote at the end?

I conducted a quick test of this: [test-with-trailing-quote.csv](https://github.com/user-attachments/files/17711799/test-with-trailing-quote.csv)

Opening it in Apple Numbers results in a string value.

![Image](https://github.com/user-attachments/assets/355e037f-6f5c-4e2d-a42a-0f0b2c7df391)


Opening in Google Sheets hides the opening quote character but renders. Even if we remove the trailing quote, it is not treated as a valid number (e.g. for use in `SUM()`) until the opening quote is removed.

![Image](https://github.com/user-attachments/assets/afc28cca-112d-4185-ab69-e1e7c60234ed)


I think the best approach is to allow negative numeric values to remain unescaped since **pure numeric values cannot be used for formula injection**. I'm proposing this approach in #52727.

```js
// This is fine - just a number, no need to escape
const num = -42

// These string representations could be problematic and will still be escaped
const riskyStrings = [
  "=-42", // Explicit formula
  "=SUM(-42)", // Function call,
  "-42+cmd|' /C calc'!A0", // Injection attempt to invoke a command through Excel,
  "@-42"  // Macro/reference syntax in some spreadsheets
]
```

Examples of popular JS → CSV npm libraries that escape dangerous strings but not negative numbers:

[json2csv](https://github.com/juanjoDiaz/json2csv/blob/5c68cfbdabf7817f103cb8a7c9dbb83e41ba0f91/docs/others/known-gotchas.md?plain=1#L22)
[papaparse](https://github.com/mholt/PapaParse/blob/4af6882e0ea91b0baad30345f190b38d50e7535e/papaparse.js#L461-L464)

**Closed** 2024-12-02 09:36 UTC
Labels: type: bug, focus: payment, package: @woocommerce/csv-export, focus: analytics, team: Transact
