### ISSUE TITLE
I hope the orderby parameter can support menu_order field sorting

### ISSUE THREAD

**Issue by cha0ran** [woocommerce/woocommerce#30195] opened 2021-07-01 03:43 UTC
The categories interface in the rest api does not support menu_order sorting

I hope the orderby parameter can support menu_order field sorting

**Comment by tammullen** [comment] 2021-07-02 11:49
Hi @cha0ran 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

Or have a look at this existing issue with a similar discussion https://github.com/woocommerce/woocommerce/issues/22356

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it. If you want to suggest an enhancement instead please use the template we provide

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-07-02 11:49 UTC
