### ISSUE TITLE
Duplicate categories on Shop page

### ISSUE THREAD

**Issue by wpniall** [woocommerce/woocommerce#28282] opened 2020-11-14 07:34 UTC
**Prerequisites:**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When you set the Shop page to display categories, it displays the categories twice no matter what other settings you change.

**Expected behavior**
Categories should only be displayed once, not twice.

**Actual behavior**
* Setting the Shop page to display categories results in duplicate categories showing on the page.
* When previewing the Shop page using the **Storefront Theme** and **Twenty Twenty Theme**, the categories still duplicate.
* With **Jetpack Infinite Scroll** *enabled*, the Shop page loads in the second set of categories on the /shop/ URL.
* With **Jetpack Infinite Scroll** *disabled*, the duplicate categories still exist, but at the /shop/ or shop/page/1 and /shop/page/2 URLs.
* Changing any of the other settings, such as **Products per row** or **Default product sorting** still results in duplicate categories showing on the page

**Steps to reproduce the bug**
Steps to reproduce the bug:
1. Go to *Customize -> WooCommerce -> Product Catalog*
2. Click on "Show categories" under the "Shop page display" section
3. See error
4. (Select any other setting and see the same error)

**Screenshots**
Categories duplicate when "Show categories" option chosen:
![https://d.pr/i/IeZVIo](https://d.pr/i/IeZVIo+)

Changing the rows appears to remove the duplicates but that's because the Customizer shows the /shop/page/2 URL:
![https://d.pr/i/LLwyY7](https://d.pr/i/LLwyY7+)
![https://d.pr/i/Y7W5TO](https://d.pr/i/Y7W5TO+)

The front-end still shows the duplicates after selecting the "Save Changes" button at the top of the Customizer:
![https://d.pr/i/jscPD4](https://d.pr/i/jscPD4+)

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme (Twenty Twenty) active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

### WordPress Environment ###

WC Version: 4.7.0
WP Version: 5.5.3
Theme: Storefront 2.9.0

---

Reported here: 3476952-zen
Confirmed as not a Storefront Theme issue above and on https://github.com/woocommerce/storefront/issues/1531

**Comment by wpniall** [comment] 2020-11-18 15:10
Another report on: 15379946-hc

**Comment by nagpai** [comment] 2020-12-04 07:25
Another report 
#26102281-hc

Workaround for now is to Get to Jetpack settings and set Infinite scroll settings to 

`Load more posts using the default theme behaviour`

![2020-12-04 12 52 55 spajewellery com 6496a999e8f4](https://user-images.githubusercontent.com/4162931/101133960-a8e6e880-362f-11eb-8a01-8bbc9c9d7746.jpg)

**Comment by juliaamosova** [comment] 2020-12-04 22:35
Hi @wpniall,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Noting here that this issue needs to be tested with the theme that has Jetpack's Infinite Scroll support. Twenty Twenty and Twenty Twenty One themes don't support Jetpack's Infinite Scroll. if testing with these themes first (like I did), there is no way to reduce the issue.

However, it is visible in Storefront. But only if I have Jetpack's Infinite Scroll enabled and set to, for example, `Load more posts in-page with a button` - please see gif below.

![](http://g.recordit.co/JwUlL0iH4X.gif)

As confirmed by @nagpai, if to change the Jetpack's Infinite Scroll option to `Load more posts using the default theme behavior`, the issue goes away. 

At first, I thought this was a Jetpack issue. However, @wpniall's comment below makes me think it is a WooCommerce issue:

>With Jetpack Infinite Scroll enabled, the Shop page loads in the second set of categories on the /shop/ URL.
With Jetpack Infinite Scroll disabled, the duplicate categories still exist, but at the /shop/ or shop/page/1 and /shop/page/2 URLs.

I tested the above with Twenty Twenty One theme (that doesn't have Jetpack's Infinite Scroll support) and can indeed confirm  that there are product categories duplicates if you navigate to `/shop/page/2` URL:

![page2](https://user-images.githubusercontent.com/19143190/101222113-14907c00-3657-11eb-83cc-e64a97213ab6.jpg)

This seems like something that we should fix sooner than later so I am assigning this a `high` priority.

**Comment by wpniall** [comment] 2020-12-15 11:52
Hi @juliaamosova! 

Thanks for letting me know. I'll be more careful by testing different themes next time.

**Comment by zwiesman31** [comment] 2021-05-07 15:47
Another issue here: 3971542-zen

![https://d.pr/i/l1aH0Z](https://d.pr/i/l1aH0Z+)
Screencast link: https://d.pr/i/l1aH0Z

**Comment by ghost** [comment] 2022-02-01 11:16
hc-33093458 also had this issue. The workaround fixed it.

**Comment by thracefulton** [comment] 2023-01-20 00:52
Another instance in 5881760-zen, but this merchant was seeing the products themselves duplicated when using `Jetpack Infinite Scroll` along with the Default Sorting set to `Sort by most recent`. 

It was resolved by changing either the Infinite Scroll setting or the Default Sorting setting in this case, since the categories were not ever shown on the shop page.

**Comment by ROBERLANDIO** [comment] 2023-01-20 00:59
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Comment by rrennick** [comment] 2023-09-22 18:04
This is a duplicate of #36175 which is more recent but has a more complete description of the issue.

**Closed by rrennick** 2023-09-22 18:04 UTC
Labels: type: bug, priority: high, focus: category, focus: shop [team:Proton], plugin: woocommerce, team: Mothra

**Comment by ajbanx** [comment] 2025-03-08 09:29
> Another report #26102281-hc
> 
> Workaround for now is to Get to Jetpack settings and set Infinite scroll settings to
> 
> `Load more posts using the default theme behaviour`
> 
> ![2020-12-04 12 52 55 spajewellery com 6496a999e8f4](https://user-images.githubusercontent.com/4162931/101133960-a8e6e880-362f-11eb-8a01-8bbc9c9d7746.jpg)

Thank you! This is it!!!
This is how to get more rows to show up in the Storefront theme. I've been searching for like a month.
