### ISSUE TITLE
Add hook to prevent cache of shipping calculation..

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#29013] opened 2021-02-03 12:31 UTC
Its an update of this unresolved issue #22100.

We should implement new hook to disable this, so its a **win-win solution** for us. Yes caching is needed for speed. But some developer choose not to cache it for some reason like, for example calculating shipping based on payment method.

Yes, using 'woocommerce_shipping_debug_mode' hook will fixed the issue But this is obviously not a fix for live site though. Because that also displays the debug notices on checkout page.

**Comment by carazo** [comment] 2021-02-09 08:05
Yes I have the same problem. I tell you my case:

- my customer needs to show a shipping method only some hours by week (this is a special weekend shipping method)
- If I do not check this option, due to the cache, it is not shown when it should be shown
- but the message of the "zone" appears and we cannot disable it in some way
- I have seen how it is done, and there is not hook to do it

It would be great.

**Comment by ObliviousHarmony** [comment] 2021-08-19 19:54
Hello,

This issue is a duplicate of #22100, so I'm going to close it. I have also [left a reply on that issue](https://github.com/woocommerce/woocommerce/issues/22100#issuecomment-902197264) detailing the solution earlier in the thread in more detail.

**Closed by ObliviousHarmony** 2021-08-19 19:54 UTC
Labels: needs developer feedback
