### ISSUE TITLE
Default sorting not working properly

### ISSUE THREAD

**Issue by Pottsies** [woocommerce/woocommerce#27158] opened 2020-07-29 02:42 UTC
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Description**
The Default product sorting is set to 'Default sorting' but it does not work properly. My products are listed by sizes e.g. 180 x 120 x 180mm, 195 x 120 x 91mm etc... Previously my products all appeared in numerical order when under 'Default sorting'. Something has changed and my products no longer appear in numerical order but instead appear on the page in a semi jumbled order e.g. 320 x 220 x 280mm, 180 x 120 x 180mm, 195 x 120 x 91mm etc...

**Expectation**
I expected that when set to 'Default sorting' the products would appear in numerical order as they always have in the past. Something has changed over the past couple of weeks or so.

**Actual behavior**
The numerical order of the products on the product page should be automatic when the default is 'Default sorting', however it is not. Some higher digit numbers sometimes appear first, or appear out of place in a row of products.
The only way I've discovered to get the default sorting to work properly is to 
open the product page, 
go to the sorting drop down menu and select one of the other options besides 'default sorting' (e.g. sort by price: low to high). Once the product order has changed to that particular selection I then go back and select default sorting and the correct product order appears. 
(Note: The above error occurs despite 'Default sorting' being the default on the following
appearance/customise/woocommerce/product catalog/category display/default product sorting/default sorting (customise + name)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. Make sure that the default product sorting is set to 'default sorting'
2. Go to the product page 
2. View products that are organised by size measurements e.g. 180 x 120 x 180mm etc.
3. Scroll down the page
4. You will see that they do not appear in numerical order as they are supposed to

![How the first row of one of our product categories appears](https://user-images.githubusercontent.com/68894557/88750225-62bcdc80-d198-11ea-94ad-448725869783.JPG)
![How the first row should appear](https://user-images.githubusercontent.com/68894557/88750237-67819080-d198-11ea-999e-494c06dfa551.JPG)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### WordPress Environment ###

WordPress address (URL): https://boxesforbusiness.com.au
Site address (URL): https://boxesforbusiness.com.au
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.20
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1g-fips

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Total Database Size: 36.90MB
Database Data Size: 32.65MB
Database Index Size: 4.25MB
wp_woocommerce_sessions: Data: 1.30MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 3.52MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 8.52MB + Index: 1.23MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mgmlp_folders: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_options: Data: 4.11MB + Index: 0.12MB + Engine MyISAM
wp_postmeta: Data: 3.50MB + Index: 0.58MB + Engine MyISAM
wp_posts: Data: 9.90MB + Index: 0.15MB + Engine MyISAM
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_sc_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_redirection_404: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.11MB + Index: 0.08MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wccs_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wccs_condition_meta: Data: 0.31MB + Index: 0.14MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 386
custom_css: 1
customize_changeset: 5
et_footer_layout: 1
et_pb_layout: 9
et_template: 1
et_theme_builder: 1
global_product_addon: 1
mgmlp_media_folder: 258
nav_menu_item: 25
page: 45
post: 12
product: 199
revision: 417
shop_order: 39
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

BackupBuddy: by iThemes – 8.6.0.0
Classic Editor: by WordPress Contributors – 1.5
Easy WooCommerce Discounts - WooCommerce Dynamic Pricing & Shipping: by Asana Plugins – 4.6.1 – Installed version not tested with active version of WooCommerce 4.3.1
Erident Custom Login and Dashboard: by Libin V Babu – 3.5.8
Google XML Sitemaps: by Arne Brachhold – 4.1.0
iThemes Security Pro: by iThemes – 6.6.1
Jetpack by WordPress.com: by Automattic – 8.7.1
Media Library Folders for WordPress: by Max Foundry – 5.2.0
Media Library Folders for WordPress Reset: by Max Foundry – 5.2.0
Minimum Maximum quantity & Minimum Order amount for WooCommerce Pro: by Pi Websolution – 1.1.4 – Installed version not tested with active version of WooCommerce 4.3.1
Redirection: by John Godley – 4.8
SG Optimizer: by SiteGround – 5.6.1
WooCommerce Checkout Add-Ons: by SkyVerge – 2.3.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.35 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Services: by Automattic – 1.23.2 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce: by Automattic – 4.3.1

### Inactive Plugins (1) ###

Yoast SEO: by Team Yoast – 14.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #192 - /shop/
Cart: #193 - /cart/
Checkout: #194 - /checkout/
My account: #195 - /my-account/
Terms and conditions: #56 - /terms-and-conditions/

### Theme ###

Name: Divi
Version: 4.5.1
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 46
Oldest: 2020-07-01 08:05:54 +1000
Newest: 2020-07-29 11:45:09 +1000

`

**Comment by tammullen** [comment] 2020-07-29 19:52
Hi @Pottsies 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. Default sorting is displaying products alphabetically by name and I have no custom sorting setup.
​
![Screenshot 2020-07-29 at 20 26 32](https://user-images.githubusercontent.com/24649833/88846051-f9ab8800-d1dc-11ea-80bc-12d76f609168.png)

Can you review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;

In particular
WooCommerce Customizer Product Sorting
https://docs.woocommerce.com/document/woocommerce-customizer/#section-10

And Sorting Products
https://docs.woocommerce.com/document/managing-products/#section-23

**Comment by Pottsies** [comment] 2020-07-30 01:41
Hi Tam
Thank you for investigating.
I’m not sure why the problem is not reproducing for you, as the problem happens every time on every device, whether it’s mine or someone else’s.
It’s the numerical order that’s the problem, not the alphabetical order. It occurs when the product page is first opened as the products don’t automatically go into numerical order.
The problem is not going to occur if the default sorting is clicked again after already opening the page.

I will review the links you gave to see if there are any suggestions.

I also spoke to someone at woocommerce who discovered there was a problem and they suggested it was that the Divi builder is adjusting the default sort order and not taking into account what has been set in WooCommerce. i.e. the Divi element is not honouring the default sorting set by woocommerce.
They said this could be due to a recent update with woocommerce or divi.

At this stage my problem is still there.

Kind Regards
Simon Potts

[cid:image001.jpg@01D66666.46CFF720]

NEW BOXES • SECOND HAND BOXES • PACKAGING SUPPLIES

11 Nirvana St. Pendle Hill NSW 2145
Tel: 02 9636 8897 | 1300 620 620
simon@boxesforbusiness.com.au<mailto:simon@boxesforbusiness.com.au>
www.boxesforbusiness.com.au<http://www.boxesforbusiness.com.au/>

Recycling Facts: Recycling a single tonne of paper saves around 13 trees, 2.5 barrels of oil, 4100 kWh of electricity, 4 cubic metres of landfill and 31,780 litres of water. Source:Clean Up Australia; Paper & Cardboard Fact Sheet, Nov 2017.

**Comment by mbs1337** [comment] 2020-10-02 09:13
I’m having the same problem on some woocommerce sites. 
Here is a test with Twenty Twenty theme, and Woocommerce activated as the only plugin.

The price sorting is not working.

Here is the test, with default Woocommerce sample products. https://www.mbstech.dk/test/shop/?orderby=price

**Comment by tammullen** [comment] 2021-03-24 20:49
Hi @Pottsies 

Apologies for the delay in replying

> they suggested it was that the Divi builder is adjusting the default sort order and not taking into account what has been set in WooCommerce. i.e. the Divi element is not honouring the default sorting set by woocommerce.

Thanks for this update, while our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. It sounds like the issue you are having seems to be caused by the 3rd party plugin Divi builder. Please contact the author of the plugin directly for further help. 

I'm going to close this issue for now due to it being likely caused by the 3rd party plugin.

@mbs1337 thanks for your report, if you think you have found a bug with price sorting please raise a new bug report for it.

In case it is related to either of your issues there is a discussion about custom sorting on this issue https://github.com/woocommerce/woocommerce/issues/28870

**Closed by tammullen** 2021-03-24 20:49 UTC
Labels: category: can't reproduce, has feedback
