### ISSUE TITLE
Problem in adding other product sku in product variation in woocoomerce variable product

### ISSUE THREAD

**Issue by saquib189** [woocommerce/woocommerce#25136] opened 2019-11-28 10:33 UTC
I getting a problem on creating a variable products on my woo-commerce product page. I have different product which i want to assign as variation on my variable product. but it's display error on adding sku of other product. Invalid or duplicated SKU. i am seller on amazon and there is no problem in adding other sku to the parent product. but as i am new to wordpress. Please anyone who have well experience please help me in this matter. So this will solve my entire product problem.

Thank you

**Comment by juliaamosova** [comment] 2019-11-28 10:35
Hi there @saquib189,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-11-28 10:35 UTC
