### ISSUE TITLE
Product Type option not appearing 

### ISSUE THREAD

**Issue by hebaazmat** [woocommerce/woocommerce#27381] opened 2020-08-18 14:37 UTC
**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Hi there,

There was a dropdown option next to "Product Type" which isn't appearing anymore as now I am unable to see the below options. There is a similar issue already opened but I am still not able to fix it even though I also downloaded the Enable jQuery Migrate Helper.

**Expected behavior**

I should have the option to add different types of product types such as:

- Simple product 
- Grouped product 
- External/Affiliate product
- Variable product 

but I am unable to see these as there is no drop down menu.

**Actual behavior**

I am unable to see the above options

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to "Products"
2. Click on "Add New"
3. Scroll down to Product Data
4. and next to Product Data, there is no dropdown option

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

`
### WordPress Environment ###

WordPress address (URL): https://stylezoftomorrow.com
Site address (URL): https://stylezoftomorrow.com
WC Version: 4.3.3
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.12
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.3
WC Database Prefix: wp_1dvfgh37rb_
Total Database Size: 11.11MB
Database Data Size: 9.00MB
Database Index Size: 2.11MB
wp_1dvfgh37rb_woocommerce_sessions: Data: 0.19MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_1dvfgh37rb_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_1dvfgh37rb_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_options: Data: 2.50MB + Index: 0.08MB + Engine InnoDB
wp_1dvfgh37rb_postmeta: Data: 2.52MB + Index: 0.64MB + Engine InnoDB
wp_1dvfgh37rb_posts: Data: 2.52MB + Index: 0.13MB + Engine InnoDB
wp_1dvfgh37rb_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_slides: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_1dvfgh37rb_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_1dvfgh37rb_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_1dvfgh37rb_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_1dvfgh37rb_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_1dvfgh37rb_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_1dvfgh37rb_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_1dvfgh37rb_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 299
customize_changeset: 34
etheme_portfolio: 12
mc4wp-form: 1
nav_menu_item: 68
page: 30
post: 14
product: 59
product_variation: 89
revision: 48
shop_coupon: 1
shop_order: 14
shop_order_refund: 1
staticblocks: 11
testimonials: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

The SEO Framework: by The SEO Framework Team – 4.1.0
Contact Form 7: by Takayuki Miyoshi – 5.2.1
Cookie Notice: by dFactory – 1.3.2
XStore Core: by 8theme – 2.3.9.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.12.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.2.0
Kirki Customizer Framework: by David Vongries – 3.1.5
Really Simple SSL: by Really Simple Plugins – 3.3.4
Slider Revolution: by ThemePunch – 6.2.12
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.24
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.3 – Installed version not tested with active version of WooCommerce 4.3.3
WooCommerce: by Automattic – 4.3.3
GMAPS for WPBakery Page Builder: by WWP – 1.6

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.6
CoBlocks: by GoDaddy – 2.2.1
Enable jQuery Migrate Helper: by The WordPress Team – 1.0.1
Gravity Forms: by rocketgenius – 2.4.17
MC4WP: Mailchimp for WordPress: by ibericode – 4.8
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Dropin Plugins (1) ###

object-cache.php: APCu Object Cache

### Must Use Plugins (1) ###

System Plugin: by  – 3.18.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Basket: #15 - /cart/
Checkout: #16 - /checkout/
My account: #17 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: XStore Child
Version: 1.0
Author URL: http://8theme.com
Child Theme: ✔
Parent Theme Name: XStore
Parent Theme Version: 6.3.9.2
Parent Theme Author URL: http://www.8theme.com
WooCommerce Support: ✔

### Templates ###

Overrides: xstore/woocommerce/archive-product.php
xstore/woocommerce/cart/cart-empty.php
xstore/woocommerce/cart/cart-item-data.php
xstore/woocommerce/cart/cart-shipping.php
xstore/woocommerce/cart/cart.php
xstore/woocommerce/cart/cross-sells.php
xstore/woocommerce/cart/mini-cart.php
xstore/woocommerce/checkout/form-billing.php
xstore/woocommerce/checkout/form-checkout.php
xstore/woocommerce/checkout/form-shipping.php
xstore/woocommerce/checkout/thankyou.php
xstore/woocommerce/content-product.php
xstore/woocommerce/content-product_cat.php
xstore/woocommerce/content-single-product.php
xstore/woocommerce/content-widget-product.php
xstore/woocommerce/content-widget-reviews.php
xstore/woocommerce/global/breadcrumb.php
xstore/woocommerce/global/form-login.php
xstore/woocommerce/global/wrapper-end.php
xstore/woocommerce/global/wrapper-start.php
xstore/woocommerce/loop/loop-end.php
xstore/woocommerce/loop/loop-start.php
xstore/woocommerce/loop/no-products-found.php
xstore/woocommerce/loop/result-count.php
xstore/woocommerce/myaccount/form-login.php
xstore/woocommerce/single-product/add-to-cart/simple.php
xstore/woocommerce/single-product/meta.php
xstore/woocommerce/single-product/product-image.php
xstore/woocommerce/single-product/related.php
xstore/woocommerce/single-product/tabs/tabs.php
xstore/woocommerce/single-product/title.php
xstore/woocommerce/single-product/up-sells.php
xstore/woocommerce/single-product.php

### Action Scheduler ###

Complete: 16
Oldest: 2020-07-20 04:17:39 +0000
Newest: 2020-08-18 14:34:32 +0000

`

**Comment by juliaamosova** [comment] 2020-08-18 18:12
Hi @hebaazmat,

I am sorry to hear about the trouble. This bug had been fixed (https://github.com/woocommerce/woocommerce/pull/27170) in WooCommerce 4.3.2. 

Can you please check if there are any errors in the browser console and also if there are any errors in the logs? 

In addition to that, it will be great if you could test your site for themes and plugins conflict. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-08-18 18:25
@hebaazmat,

It is highly likely that the issue you are having is caused by one of the 3rd party plugins on your site.
​
WordPress 5.5 removed a javascript file called jQuery migrate that some of your plugins might have relied on, so until they update, you might want to use [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper) plugin to include the javascript files in the meantime. 

I see that you have tried this plugin already though. In which case, I recommend you conflict test your site and deactivate the plugin that is causing the issue (if possible). Once you know which plugin is causing the issue, please contact the author of the plugin directly for further help on when they plan to update their plugins.

**Comment by juliaamosova** [comment] 2020-08-18 19:12
@hebaazmat, another thing to try while using Enable jQuery Migrate Helper plugin is to clear your browser's cache and cookies. Let us know how it goes.

**Comment by junaidtk** [comment] 2020-08-20 05:25
After updating the WordPress to 5.5 and WooCommerce to 4.4.0. Then it is hiding the WooCommerce product data type.

We know, we can only add variable product, grouped product etc with the help WooCommerce product data type option. So the option for product data type are missing from the WooCommerce due to this plugin effect.

While checking the activated plugins, I found one plugin is removing the admin body classes, this is root cause of the issue. WooCommerce is displaying the product data type by checking the admin body class.

So I have deactivated the plugin for avoiding the conflict.

In order to check this conflict you just need to check wc-wp-version-gte-55 is available on the admin body class. If not then any of the plugin or theme is removing the WooCommerce added body class. So I recommend you to deactivate the plugin by one by one and find out the root cause.

WooCommerce is adding the admin body class using the below filter tag.

add_filter( ‘admin_body_class’, array( $this, ‘include_admin_body_class’ ) );

You can also do plugin wide search with tag admin_body_class, so you can find-out which one is removing the added body class. If you prefer you can deactivate the plugin or contact the plugin author.

**Comment by Konamiman** [comment] 2020-08-20 10:47
Hi @junaidtk, could you please provide the name of the plugin that you disabled to prevent the conflict?

**Comment by junaidtk** [comment] 2020-08-20 11:40
In my case I have deactivated the WPIDE plugin. This plugin is removing the admin body class. This is causing the issue.

**Comment by Konamiman** [comment] 2020-08-20 15:00
I've been able to reproduce the issue. Seems to happen in WordPress 5.5, even with WooCommerce older than 4.4. Thanks for reporting, we'll work on a fix.

**Comment by junaidtk** [comment] 2020-08-20 15:06
Thanks for the reply. 

Some plugin will remove the admin body class, this is making issue. You can either increase priority of the filter function 
add_filter( ‘admin_body_class’, array( $this, ‘include_admin_body_class’ ) );
or
add some other fix like apply javascript by checking the WP-version.

**Comment by claudiosanches** [comment] 2020-08-20 15:58
We shouldn't use JS for it, also it's an issue this plugin removing all body classes, no plugin suppose to be doing it.

**Comment by claudiosanches** [comment] 2020-08-20 16:00
Also seems like that the https://wordpress.org/plugins/wpide/ is very outdated.

**Comment by claudiosanches** [comment] 2020-08-20 16:06
I fixed the issue on WPide, but the plugin doesn't get updated since 2015. They are using `add_filter()` incorrectly and it should cause conflicts with several plugins.

@junaidtk I advise you to stop using this plugin since it's outdated.

**Comment by junaidtk** [comment] 2020-08-20 16:09
Yes, it is correct. WPIDE is outdated one, I have noted that. But it is a useful one. Sure, I will remove it from my site.
if any plugin which override the the admin_body_class, it may remove body class. This will be the plugin author responsibility to keep all the added body class by other plugin and theme.

**Closed** 2020-08-21 07:15 UTC
Labels: bug, has pull request, priority: high

**Comment by rodrigoprimo** [comment] 2020-09-04 13:27
I moved this issue to the 4.5.0 milestone to match the milestone of the related PR.
