### ISSUE TITLE
lostpassword_post and retrieve_password must be prefixed with woocommerce_, breaks reset password functionality

### ISSUE THREAD

**Issue by n-for-all** [woocommerce/woocommerce#22193] opened 2018-12-11 08:13 UTC
**Describe the bug**

lostpassword_post and retrieve_password must be prefixed with woocommerce_ ,since you are prefixing the request "woocommerce_lostpassword_form", the response actions should be also prefixed.
if i only want the captcha to be shown on wordpress reset password form, it breaks woocommerce reset password form. Plugins like recapatcha and invisible captcha breaks the reset password email if activated only on wordpress, because the are hooking lostpassword_post without showing the captcha to the user.

https://github.com/woocommerce/woocommerce/blob/bebd77c2b5e7bf63a4ed11ee0ecaa92ea851583b/includes/shortcodes/class-wc-shortcode-my-account.php#L274

**To Reproduce**
1- Install invisible recaptcha or recaptcha
2- Activate it only on wordpress reset password
3- woocommerce reset password will not work

**Comment by kloon** [comment] 2018-12-11 09:52
WooCommerce uses the native WordPress login system which includes lost password functionality, we simply provide a different form but it still utilises the WordPress login system hence the use of the WordPress hooks.

Your best bet would be to add the Captcha to the WooCommerce form as well.

Closing as this is not a bug, we intend to use the default WordPress login functionality.

**Closed by kloon** 2018-12-11 09:52 UTC

**Comment by n-for-all** [comment] 2018-12-11 10:12
if you intend to use wordpress login system, then use it also in the forms

<?php do_action( 'woocommerce_lostpassword_form' ); ?> becomes <?php do_action('lostpassword_form' ); ?>

https://github.com/woocommerce/woocommerce/blob/b85598a5762538c4e1c30a67e13b9f60e994eb5c/templates/myaccount/form-lost-password.php#L34

it is either prefix your actions with woocommerce_ both request and response, or don't for both.

**Comment by kloon** [comment] 2018-12-11 10:14
That is a custom template which loads a custom form that is why we prefix it with woocommerce_, as I said above, we have a custom form that utilises the WordPress login mechanism. Should not be too hard to add some custom code to add the captcha to that form.
