### ISSUE TITLE
Login bug with php 7.4.2 & space in username

### ISSUE THREAD

**Issue by trexya** [woocommerce/woocommerce#25660] opened 2020-02-13 15:10 UTC
With WooCommerce 3.9.1 WordPress 5.3.2 in a linux server with php 7.4.2 users with space in username can't login (checked that password is correct).
Changing the php version to 7.3.14 the login work fine.

1. register an user in woocommerce with space in username
2. try to login in woocommerce (cash
3. page reload without error messages and no login

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
Tested with twentytwenty
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://dev.xxxxxxxxxx.it
Site address (URL): https://dev.xxxxxxxxxxxxxx.it
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.2
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.25-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: gstef16_
Dimensione totale database: 42.73MB
Dimensione dati database: 28.03MB
Dimensione indice database: 14.70MB
gstef16_woocommerce_sessions: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
gstef16_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
gstef16_woocommerce_order_items: Dati: 0.36MB + indice: 0.11MB + motore InnoDB
gstef16_woocommerce_order_itemmeta: Dati: 6.52MB + indice: 3.03MB + motore InnoDB
gstef16_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
gstef16_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
gstef16_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_commentmeta: Dati: 0.13MB + indice: 0.14MB + motore InnoDB
gstef16_comments: Dati: 1.50MB + indice: 0.75MB + motore InnoDB
gstef16_failed_jobs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_feedmanager_channel: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_feedmanager_country: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_feedmanager_feed_status: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_feedmanager_field_categories: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_feedmanager_product_feed: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_feedmanager_product_feedmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_feedmanager_source: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_mailchimp_carts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_options: Dati: 3.28MB + indice: 0.20MB + motore InnoDB
gstef16_postmeta: Dati: 7.52MB + indice: 5.03MB + motore InnoDB
gstef16_posts: Dati: 1.52MB + indice: 0.58MB + motore InnoDB
gstef16_queue: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_redirection_404: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
gstef16_redirection_groups: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_redirection_items: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
gstef16_redirection_logs: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
gstef16_revslider_css: Dati: 0.13MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_css_bkp: Dati: 0.13MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_layer_animations: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_layer_animations_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_navigations: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_navigations_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_sliders: Dati: 0.03MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_sliders_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_slides: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_slides_bkp: Dati: 0.09MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_static_slides: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_revslider_static_slides_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_rnoc_abandoned_cart_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_rnoc_abandoned_email_queue: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_rnoc_email_sent_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_rnoc_email_templates: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
gstef16_rnoc_guest_abandoned_cart_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_say_what_strings: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_term_relationships: Dati: 0.08MB + indice: 0.05MB + motore InnoDB
gstef16_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_usermeta: Dati: 2.52MB + indice: 3.03MB + motore InnoDB
gstef16_users: Dati: 0.13MB + indice: 0.14MB + motore InnoDB
gstef16_vtprd_purchase_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_vtprd_purchase_log_product: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_vtprd_purchase_log_product_rule: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_wccs_conditions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wccs_condition_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_wc_admin_notes: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wc_customer_lookup: Dati: 0.11MB + indice: 0.09MB + motore InnoDB
gstef16_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
gstef16_wc_order_product_lookup: Dati: 0.17MB + indice: 0.22MB + motore InnoDB
gstef16_wc_order_stats: Dati: 0.09MB + indice: 0.08MB + motore InnoDB
gstef16_wc_order_tax_lookup: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
gstef16_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
gstef16_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_woocommerce_cartfee: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_woodmart_wishlists: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_woodmart_wishlist_products: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gstef16_wpefc_calendarCategories: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_calendarEvents: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_calendarReminders: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_calendars: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_coupons: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_customers: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_fields: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_forms: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_items: Dati: 0.14MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_layeredImages: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_links: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_logs: Dati: 1.52MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_redirConditions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_settings: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_steps: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_wpefc_variables: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
gstef16_yoast_seo_links: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
gstef16_yoast_seo_meta: Dati: 0.30MB + indice: 0.00MB + motore InnoDB

### Post Type Counts ###

amn_mi-lite: 1
attachment: 743
cms_block: 20
nav_menu_item: 38
page: 37
post: 1
product: 90
product_variation: 2
responsive_post: 3
revision: 151
scheduled-action: 743
shop_order: 718
shopping-cart: 2
tablepress_table: 2
tm_global_cp: 9
vc_grid_item: 1
vc_settings_preset: 1
waef: 1
woodmart_sidebar: 1
woodmart_slide: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.9.1

### Inactive Plugins (33) ###

Better Search Replace: by Delicious Brains – 1.3.3
Checkout Field Editor for WooCommerce: by ThemeHigh – 3.0.3 – Non testato con la versione attiva di WooCommerce
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.6
Cookie and Consent Solution for the GDPR & ePrivacy: by iubenda – 2.2.0
Disable Comments: by Samir Shah – 1.10.2
Duplicate Post: by Enrico Battocchi – 3.2.4
Envato Market: by Envato – 2.0.3
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.2 – Non testato con la versione attiva di WooCommerce
Health Check & Troubleshooting: by The WordPress.org community – 1.4.2
Loco Translate: by Tim Whitlock – 2.3.1
Mailgun: by Mailgun – 1.7.1
Redirection: by John Godley – 4.6.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Retainful - Abandoned Cart Recovery Emails and Next Order Coupons: by Retainful – 2.1.7
Safe SVG: by Daryll Doyle – 1.9.8
Say What?: by Lee Willis – 1.9.3
Slider Revolution: by ThemePunch – 6.1.7
WooCommerce Admin: by WooCommerce – 0.25.1
WooCommerce Amazon Pay: by WooCommerce – 1.11.0 – Non testato con la versione attiva di WooCommerce
WooCommerce Cart PDF: by Seattle Web Co. – 2.0.4 – Non testato con la versione attiva di WooCommerce
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.3.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.19
Woocommerce Purchase Limits: by Code Ninjas – 1.2 – Non testato con la versione attiva di WooCommerce
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2 – Non testato con la versione attiva di WooCommerce
WooCommerce TM Extra Product Options: by themeComplete – 4.9.12.1
Woodmart Core: by  – 1.0.21
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
WPBakery Page Builder (Visual Composer) Clipboard: by bitorbit – 4.5.5
WP Cost Estimation & Payment Forms Builder: by Biscay Charly (loopus) – 9.699
WP Product Feed Manager: by Michel Jongbloed – 1.19.1
WP Rollback: by Impress.org – 1.7.0
Yoast SEO: by Team Yoast – 13.0

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #70 - /prodotti/
Carrello: #71 - /carrello/
Cassa: #72 - /cassa/
Il mio account: #73 - /mio-account/
Termini e condizioni: #15 - /condizioni-di-vendita/

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://it.wordpress.org/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completato: 742
Oldest: 2020-01-13 16:27:03 +0100
Newest: 2020-02-13 15:03:03 +0100

In sospeso: 0
Oldest: –
Newest: –

Operazione annullata: 1
Oldest: 2020-02-13 16:03:03 +0100
Newest: 2020-02-13 16:03:03 +0100

In corso: 0
Oldest: –
Newest: –

Operazione non riuscita: 0
Oldest: –
Newest: –

`

**Comment by peterfabian** [comment] 2020-02-14 11:27
Thanks for reporting the bug. This is unrelated to WooCommerce and is caused by a PHP bug introduced in version 7.4.2. More information about it can be found in WP core ticket: https://core.trac.wordpress.org/ticket/49395.

I don't think we would be creating a workaround for it, so closing for now. If the need arises, we might look into a workaround, but will also be checking how WordPress core approaches it.

**Comment by knutsp** [comment] 2020-02-27 00:59
WooCommerce actually creates usernames with spaces, when option for auto username creation is enabled and Billing First name and Last name becomes he source. This severely contributes to the problem. When any of those contains space, username will contain space (and a dot between the names). Better to replace space with dot.

**Comment by peterfabian** [comment] 2020-03-04 11:10
Thanks for your comment, @knutsp , I wasn't aware of that. 

It might be better to change how usernames are created. Although not sure if a clean solution exists, we can't change existing usernames, so maybe we would need to find a workaround for PHP 7.4.2.

**Comment by knutsp** [comment] 2020-03-04 14:02
IMHO, there are two candidates for autogenerating a username:

1. Local part of billing_email, except when considered bad, like 'mail', 'post', 'info', 'contact' etc
2. `str_replace( ' ', '.', $billing_first_name . '.' . $billing_last_name );`

This can be filtered through 'woocommerce_new_customer_data', but $bad_names array may need a filter.

**Comment by rodrigoprimo** [comment] 2020-03-11 18:33
PHP 7.4.3 was released last month and it included a fix for this problem (https://bugs.php.net/bug.php?id=79174). I just tested it and I was able to confirm that it fixes the problem described here, so I'm closing this issue.

**Closed by rodrigoprimo** 2020-03-11 18:33 UTC
Labels: bug, priority: high, wordpress
