### ISSUE TITLE
woocommerce_rest_cannot_view issue

### ISSUE THREAD

**Issue by SWengineer-A** [woocommerce/woocommerce#27740] opened 2020-09-21 21:26 UTC
I have encountered "woocommerce_rest_cannot_view" issue some days ago. 
The credential was working well before, but this issue suddenly appeared now. 
Is there any solution for this issue?
`{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}`
Wordpress 5.5.1
Woocommerce Plugin 4.5.2

**Comment by om4james** [comment] 2020-10-06 11:38
Hi @SWengineer-A, have you seen #26847 and PR #27587?At 

Do you think that they are the same issue you are reporting?

**Comment by itallogravina** [comment] 2020-10-17 03:26
I'm also having the same problem, I installed the wp on the docker and when making an OAuth 1 request I can't get this error

**Comment by rodrigoprimo** [comment] 2020-10-22 20:59
Hi @SWengineer-A,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodrigoprimo** 2020-10-22 20:59 UTC
