### ISSUE TITLE
Woocommerce Order Export Tool not working

### ISSUE THREAD

**Issue by mal-42** [woocommerce/woocommerce#25450] opened 2020-01-21 18:14 UTC
Under _Woocommerce>Settings>Orders>Export>Orders>Open Tool_.

Both CSV and XML downloads aren't being downloaded completely. I've tried this on both Chrome and Firefox and downloads all fail. Any thoughts on why this is happening?

**Comment by tammullen** [comment] 2020-01-22 00:44
Hi @mal-42 ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

[Review WooCommerce Self-Service Guide](https://href.li/?https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://href.li/?https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://href.li/?https://wordpress.org/support/plugin/woocommerce/)
If you confirm the bug, please provide us with clear steps to reproduce it and any other details we ask for in the [Bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=4-Bug-report.md&title=).

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-01-22 00:44 UTC
