### ISSUE TITLE
Filter 'woocommerce_min_password_strength' Not Working

### ISSUE THREAD

**Issue by papplebee** [woocommerce/woocommerce#24770] opened 2019-10-04 13:12 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Make use of the `woocommerce_min_password_strength` filter [as found here](https://github.com/woocommerce/woocommerce/search?q=woocommerce_min_password_strength&unscoped_q=woocommerce_min_password_strength) with the following code, to reduce the required password strength in WooCommerce
```
/** 
 * Reduce the strength requirement on the woocommerce password.
 * 
 * Strength Settings
 * 3 = Strong (default)
 * 2 = Medium
 * 1 = Weak
 * 0 = Very Weak / Anything
 */
 function reduce_woocommerce_min_strength_requirement( $strength ) {
     return 1;
 }
 add_filter( 'woocommerce_min_password_strength', 'reduce_woocommerce_min_strength_requirement' );
```

2. Enter a password at the checkout, as a new customer.
3. But the checkout still requires at least a 'Medium' strength password, so clearly this filter does not work.

## Expected/actual behavior

As mentioned, when I follow those steps, the checkout still requires at least a 'Medium' strength password, so clearly this filter does not work

I was expecting the checkout to only require a 'Weak' strength password.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiosanches** [comment] 2019-10-04 22:01
> But the checkout still requires at least a 'Medium' strength password, so clearly this filter does not work.

In fact the `woocommerce_min_password_strength` will set the strength to lock the form from submission.
The strength meter will keep showing the same results like before, nothing is changed on it, just if should lock or not the form.

But even if you set to `0` or `3` at the checkout no one will get locked for place an order, you can see better how this behave trying to register in the "My account" page.
In the checkout will only be required if you enable the `woocommerce_enforce_password_strength_meter_on_checkout` filter.

You can see the code those checks happen in:

https://github.com/woocommerce/woocommerce/blob/68f5ccabc16bd9393ae7ec0f4841715085c65e16/assets/js/frontend/password-strength-meter.js#L23-L53

Closing since in my tests I'm not able by default reproduce this issue with the steps you provided.
But free feel do keep commenting here in case you think that is really a bug.

**Closed by claudiosanches** 2019-10-04 22:02 UTC
