### ISSUE TITLE
Get order by order number not by post ID

### ISSUE THREAD

**Issue by WebMedic-X** [woocommerce/woocommerce#28136] opened 2020-10-29 03:48 UTC
Hi,

Our client wants to have a sequential order numbers

Which meant the order numbers are no longer equal to post IDs

This caused issues on the payment gateways because they use functions like wc_get_order(POST_ID) which relies on the order number being the same as post ID

We need a way to get the order by order number not by post ID and it seems WooCommerce has no functions for that?

Thank you

**Comment by juliaamosova** [comment] 2020-10-29 18:44
Hi @WebMedic-X,

We have an extension available that should work: [Sequential Order Numbers Pro](https://woocommerce.com/products/sequential-order-numbers-pro/). 

if using the extension is not an option, the best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-29 18:44 UTC

**Comment by WebMedic-X** [comment] 2020-10-30 14:21
Hi @juliaamosova 

Thanks for getting back to me

Sequential order numbers pro looks good, if we use it then the wc_get_order function will work correctly?

And this could be a feature request, to have a way / function to get order by number not by ID and there seems to be no way right now?

Thank you

**Comment by WebMedic-X** [comment] 2020-10-30 14:37
I think there is a misunderstanding

We are already using a plugin that does sequential orders

However when using the plugin, the plugin gives the order numbers a sequential number (as intended) and that means it doesnt match it’s WordPress post ID

Due to this — wc_get_order() which is used in payment gateways, and use the post ID to get the order — no longer works

And it seems there is no function in WooCommerce code that gets the order using order number instead of post ID — and that makes sense because the way different plugins store the order number will be different 

In this case I am not sure how these plugins expect payment gateways and other plugins that rely on wc_get_order to work....

**Comment by roykho** [comment] 2020-10-30 14:44
Hi @WebMedic-X - it depends on the payment gateway you're using. If done correctly they should be using `wc_get_order( $order->get_id() )` and not `wc_get_order( $post_id )`.

**Comment by WebMedic-X** [comment] 2020-10-30 14:47
Hi @roykho 

Thanks!

And what is $order = to in this case?

Thanks

**Comment by roykho** [comment] 2020-10-30 14:54
@WebMedic-X - that is the order object.

**Comment by WebMedic-X** [comment] 2020-10-30 14:56
Thanks @roykho 

Without the plugin, how did we get the $order object without using the post ID and by using an order number?
