### ISSUE TITLE
Attribute variations not working when "Any variation" is used

### ISSUE THREAD

**Issue by YYAngel** [woocommerce/woocommerce#23746] opened 2019-05-17 13:08 UTC
Attribute variations are **not working for visitors** when "Any variation" is used , **but working for logged Wordpress administrators**.

**WordPress Environment**
<details>

### WordPress Environment ###

WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: bg_BG
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. Как се надгражда версията на PHP
PHP Post Max Size: 32 MB
PHP Time Limit: 1200
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.60-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Сървърът няма разрешен клас SoapClient - някои разширения за методи за плащане
използващи SOAP
може да не работят правилно.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
Total Database Size: 207.67MB
Database Data Size: 178.46MB
Database Index Size: 29.21MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.22MB + Index: 0.06MB
wp_woocommerce_order_itemmeta: Data: 0.80MB + Index: 0.53MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.53MB + Index: 0.15MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 2.82MB + Index: 0.16MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 0.31MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.13MB + Index: 0.09MB
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB
wp_postmeta: Data: 124.86MB + Index: 10.97MB
wp_posts: Data: 28.99MB + Index: 13.62MB
wp_redirection_404: Data: 0.32MB + Index: 0.15MB
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB
wp_redirection_items: Data: 0.24MB + Index: 0.14MB
wp_redirection_logs: Data: 0.29MB + Index: 0.05MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_say_what_strings: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.19MB + Index: 0.03MB
wp_terms: Data: 0.03MB + Index: 0.05MB
wp_term_relationships: Data: 0.35MB + Index: 0.65MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.02MB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 0.05MB + Index: 0.04MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.52MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 2.57MB + Index: 0.35MB
wp_wfHits: Data: 2.02MB + Index: 0.09MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.02MB + Index: 0.01MB
wp_wfKnownFileList: Data: 1.42MB + Index: 0.15MB
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.08MB + Index: 0.02MB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB
wp_wfNotifications: Data: 0.00MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.07MB + Index: 0.02MB
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wp_yoast_seo_links: Data: 11.02MB + Index: 1.52MB
wp_yoast_seo_meta: Data: 0.10MB + Index: 0.11MB

### Post Type Counts ###

acf-field: 5
acf-field-group: 5
advanced_ads: 1
attachment: 38247
br_labels: 2
nav_menu_item: 117
oembed_cache: 8
page: 35
post: 2373
product: 2175
product_variation: 1410
revision: 25
shop_coupon: 7
shop_order: 772
sidebar: 34
wapl: 1
wcct_countdown: 3
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

404page - your smart custom 404 error page: от Peter Raschendorfer – 10.5
Модерни потребителски полета: от Elliot Condon – 5.8.0
WooCommerce Advanced Product Labels: от BeRocket – 1.1.14 – Not tested with the active version of WooCommerce
Antispam Bee: от pluginkollektiv – 2.9.1
Autoptimize: от Frank Goossens (futtta) – 2.5.0
Webcraftic Clearfy – WordPress optimization plugin: от Webcraftic  – 1.5.3
WooCommerce Custom Related Products Pro: от WPCodelibrary – 1.2 – Not tested with the active version of WooCommerce
Contact Form 7: от Такаюки Миюши – 5.1.1
История на съгласието на GDPR: от WebToffee – 1.7.6
Facebook for WooCommerce: от Facebook – 1.9.12 – Not tested with the active version of WooCommerce
Finale - WooCommerce Sales Countdown Timer & Discount Plugin Lite: от XLPlugins – 2.8.0 – Not tested with the active version of WooCommerce
WPBakery Page Builder: от Michael M - WPBakery.com – 5.7
Loco Translate: от Tim Whitlock – 2.2.2
Mashshare Share Buttons: от René Hermenau – 3.6.5
OneSignal Push Notifications: от OneSignal – 1.17.3
Read More Without Refresh: от George Gkouvousis – 3.1
Really Simple SSL: от Rogier Lankhorst
Mark Wolters – 3.1.5

Redirection: от John Godley – 4.2.3
Lazy Load by WP Rocket: от WP Rocket – 2.2.2
Tawk.to Live Chat: от Tawkto – 0.3.6
TinyMCE Advanced: от Andrew Ozz – 5.0.1
W3 Total Cache: от Frederick Townes – 0.9.7.4
Checkout Field Editor for WooCommerce: от ThemeHiGH – 1.3.2
WooCommerce Extended Coupon Features FREE: от Soft79 – 3.0.5 – Not tested with the active version of WooCommerce
WooCommerce: от Automattic – 3.6.3
WooSidebars: от WooCommerce – 1.4.5
Wordfence Security: от Wordfence – 7.3.2
Yoast SEO: от Team Yoast – 11.2.1 – Not tested with the active version of WooCommerce
WP All Import: от Soflyy – 3.5.0
WP Menu Cart Pro: от Jeremiah Prummer
Ewout Fernhout – 3.1.4 – Not tested with the active version of WooCommerce

WP-Optimize: от David Anderson
Ruhani Rabin
Team Updraft – 2.3.3

WP All Import - WooCommerce Add-On Pro: от Soflyy – 3.0.6 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: от YITH – 2.2.10
WP All Import - Yoast WordPress SEO Add-On: от Soflyy – 1.1.8

### Inactive Plugins (10) ###

Better Search Replace: от Delicious Brains – 1.3.3
Duplicate Post: от Enrico Battocchi – 3.2.2
Official Facebook Pixel: от Facebook – 1.7.25
Product Feed PRO for WooCommerce: от AdTribes.io – 5.5.7
Query Monitor: от John Blackbourn – 3.3.5
Regenerate Thumbnails: от Alex Mills (Viper007Bond) – 3.1.1
Show Current Template: от JOTAKI Taisuke – 0.3.0
Smush: от WPMU DEV – 3.2.0.1
tagDiv Composer: от tagDiv – 2.3 | built on 12.10.2018 9:30
WooCommerce js cookie fix: от Rynaldo – 1.0 – Not tested with the active version of WooCommerce

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BGN (лв.)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

http://bit.ly/2Eg9wdn

### Theme ###

Name: Newspaper 7 Child theme
Version: 7.7c
Author URL: http://themeforest.net/user/tagDiv/portfolio
Child Theme: ✔
Parent Theme Name: Newspaper
Parent Theme Version: 9.5
Parent Theme Author URL: http://themeforest.net/user/tagDiv/portfolio
WooCommerce Support: ✔

### Templates ###

Overrides: Newspaper-child/woocommerce/archive-product.php
Newspaper-child/woocommerce/checkout/cart-errors.php
Newspaper-child/woocommerce/checkout/form-billing.php
Newspaper-child/woocommerce/checkout/form-checkout.php
Newspaper-child/woocommerce/checkout/form-coupon.php
Newspaper-child/woocommerce/checkout/form-login.php
Newspaper-child/woocommerce/checkout/form-pay.php
Newspaper-child/woocommerce/checkout/form-shipping.php
Newspaper-child/woocommerce/checkout/payment-method.php
Newspaper-child/woocommerce/checkout/payment.php
Newspaper-child/woocommerce/checkout/review-order.php
Newspaper-child/woocommerce/checkout/terms.php
Newspaper-child/woocommerce/checkout/thankyou.php
Newspaper-child/woocommerce/emails/email-order-details.php
Newspaper-child/woocommerce/order/order-details.php
Newspaper/woocommerce/single-product.php

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kaziqta** [comment] 2019-05-18 13:16
I can confirm I have the same issue. 
Working only for logged in WordPress admins

**Comment by YYAngel** [comment] 2019-05-19 13:42
Update:

Wordpress updated to the latest version
All plugins updated to the latest version incl. Woocommerce
Tested to switch off all plugins  

Nothing solves the issue.

**Comment by claudiosanches** [comment] 2019-05-20 13:31
Please, can you fill all information of this bug report?

<pre>
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
</pre>

Thanks!

**Comment by claudiosanches** [comment] 2019-05-20 13:32
> Attribute variations are not working for visitors when "Any variation" is used , but working for logged Wordpress administrators.

This is the widget or selecting the production variation?

**Comment by YYAngel** [comment] 2019-05-20 17:12
**Describe the bug**

When "Any variation" for a product is used, the visitor can't make an order.

For example when 2-3 or more different sizes and 10 (more or less) different colors have been added in the admin, and "Any variation" has been used for any of the attributes, on the front-end the visitor can't make an order. What happens after selecting the desired attribute variations, is an error message, saying that the color variation/variable must be selected.

**To Reproduce** 

Go to:  bit.ly/2Eg9wdn , select both attributes and press the Buy button (Купи).

**Expected behavior**

I expect the product to be added to the cart.

Wordpress environment: Latest version
Woocommerce environment: Latest version (but the bug was found on lower Woocommerce version and didn't get fixed after upgrade)
All plugins: Latest version (you can see all active plugins above)
Tested with all plugins off - no difference, the bug is still there

Hope that helps.

**Comment by claudiosanches** [comment] 2019-05-20 18:55
@YYAngel still missing several information from the bug report, have you tried to isolate the problem? see ****Isolating the problem (mark completed items with an [x]):****

**Comment by claudiosanches** [comment] 2019-05-20 18:56
If you have screenshots or videos, please you can upload here, or even use youtube, but please, do not use links like `bit.ly/2Eg9wdn`.

**Comment by YYAngel** [comment] 2019-05-21 08:20
**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with Storefront - NO, just tested. The website is a digital magazine and a shop in one. I'm using the Newspaper theme (a child theme) and I don't have any special Woocommerce theme. I have used the Newspaper theme to make both parts of the website (magazine and shop) look similar in the front-end.
- [x ] I can reproduce this bug consistently visiting the link I provided (plus hundreds more), selecting both variations (please ignore the Cyrillic language), and pressing the Buy button (Купи).

See here: https://imgur.com/a/epFoyic

**Comment by kloon** [comment] 2019-05-22 07:35
I am unable to replicate this, see product variation below

![](https://cld.wthms.co/3x17rY+)

See visiting the product logged out in ingocnito window with the add to cart button enabled below

![](https://cld.wthms.co/pVvIoq+)

See product added to cart after clicking the add to cart button logged out in incognito window below

![](https://cld.wthms.co/BFvdnB+)

![](https://cld.wthms.co/3iqR9S+)

As it stands I am unable to replicate with the steps you provided, you mention that you tested this with all plugins disabled but your system status report shows you have a lot of active plugins, you also are not running a default theme so please test with another theme like Twenty Seventeen or Storefront.

Alternatively, since you mention this only happens to logged out users then have a look at your caching setup, it could be causing issues there.

Closing this issue, but if you can provide steps to replicate this on a clean install with just WooCommerce and a default theme then I will gladly reopen the issue to look into this further.

**Closed by kloon** 2019-05-22 07:35 UTC
Labels: status: needs feedback

**Comment by YYAngel** [comment] 2019-05-23 12:23
I tested with all caches off - the result is the same. 
But are you able to replicate the issue on the site where I'm experiencing it?
