### ISSUE TITLE
$0 Initial Checkout option in Subscriptions stopped working with v 4.7.0

### ISSUE THREAD

**Issue by taropaa** [woocommerce/woocommerce#28344] opened 2020-11-19 23:43 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have performed a plugin de-activation test, and resorted to manually creating a new blank website with only the affected plugins installed. 
The v4.7.0 of Woocommerce breaks the "$0 Initial Checkout" feature found in the "Woocommerce Subscriptions" Plugin. 
The message displayed is "Error processing checkout. Please try again.". This error message is generated by Woocommerce, and not by Woocommerce subscriptions, which is why I believe the bug is with Woocommerce.

**Expected behavior**
I have created a simple subscription product.
Type > Virtual
Price $99/mo
Free Trial Period: 30 Days
___

As a customer I add the product to the cart and proceed to checkout. 
Since there is no initial charge (Free Trial), I am not asked for a credit card.
I check out and my free trial begins (expect to see order complete page/screen)

**Actual behavior**
As a customer I add the product to the cart and proceed to checkout. 
Since there is no initial charge (Free Trial), I am not asked for a credit card.
When clicking on checkout, I get a non descript error: "Error processing checkout. Please try again."
No errors are logged in the logs.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix) OpenSSL/1.1.1
PHP Version: 7.4.12
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB-1:10.4.17+maria~bionic-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 3.82MB
Database Data Size: 2.41MB
Database Index Size: 1.41MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 1
shop_order: 3
shop_subscription: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.5.5 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Subscriptions: by WooCommerce – 3.0.10
WooCommerce: by Automattic – 4.7.0

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Facebook for WooCommerce: by Facebook – 2.2.0
Google Ads & Marketing by Kliken: by Kliken – 1.0.6 – Installed version not tested with active version of WooCommerce 4.7.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: 
Subscription Statuses: wc-active: 1
wc-pending: 2

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Canada — Ontario

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders


### Action Scheduler ###

Complete: 11
Oldest: 2020-11-19 23:25:06 +0000
Newest: 2020-11-19 23:39:35 +0000

Pending: 6
Oldest: 2020-11-19 23:43:54 +0000
Newest: 2020-12-19 23:33:54 +0000

`
```
</details>

**Comment by jrick1229** [comment] 2020-11-20 19:18
Hi @taropaa - this has been recorded in the WooCommerce Subscriptions (private) repository. The bug is related not only to products with free trials, but other instances as well. While this may have been caused by a change in WC checkout, the fix is being rolled into a release in WooCommerce Subscriptions. I'll reply to your ticket.

3504718-zen

**Comment by tammullen** [comment] 2020-11-20 20:17
Hi @taropaa 

Thanks for raising this. The issue you are having is being looked at in the private WooCommerce Subscriptions repository. I am leaving this issue open for now in case anything is needed by the Subscriptions team on the core side.

**Comment by tammullen** [comment] 2021-03-22 20:54
Hi @taropaa,

I'm closing this issue as it has been resolved in WooCommerce Subscriptions.

Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2021-03-22 20:54 UTC
Labels: needs developer feedback
