### ISSUE TITLE
"Add To Cart" triggers warning when using AMP Standard mode

### ISSUE THREAD

**Issue by liviopv** [woocommerce/woocommerce#24974] opened 2019-11-05 14:27 UTC
**Describe the bug**
When a site is running both WooCommerce and the [official AMP WordPress plugin](https://wordpress.org/plugins/amp/), and the AMP plugin is set to the **Standard** mode, the "Add To Cart" will display the following message when triggered:

![Screenshot](https://cld.wthms.co/h1qBC3+)
Screenshot: https://cld.wthms.co/h1qBC3

It seems to happen no matter the theme (tested with Twenty Seventeen, Storefront and a Varia child theme). Setting AMP to **"Transitional"** avoids the warning message.

**To Reproduce**
1. Install and activate the [AMP plugin](https://wordpress.org/plugins/amp/)
2. Select "Standard" in the AMP Website Mode settings
2. Use the core "Add To Cart" button on any product
4. The product will be successfully added to the cart, but the `It appears your submission was successful. Even though the server responded OK, it is possible the submission was not processed. Please contact the developer of this form processor to improve this message.` warning message will show up

**Expected behavior**
No warning message should be shown

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://atlivio.blog
Site address (URL): https://atlivio.blog
WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.24
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.66.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.1
WC Database Prefix: wp_130416494_
MaxMind GeoIP Database: ✔
Total Database Size: 9.59MB
Database Data Size: 7.19MB
Database Index Size: 2.40MB
wp_130416494_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_130416494_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_130416494_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_130416494_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_130416494_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_130416494_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_bp_activity: Data: 0.02MB + Index: 0.16MB + Engine InnoDB
wp_130416494_bp_activity_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_130416494_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_130416494_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_130416494_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_options: Data: 2.09MB + Index: 0.06MB + Engine InnoDB
wp_130416494_postmeta: Data: 2.52MB + Index: 0.19MB + Engine InnoDB
wp_130416494_posts: Data: 1.27MB + Index: 0.25MB + Engine InnoDB
wp_130416494_redirection_404: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_130416494_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_redirection_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_130416494_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_130416494_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_130416494_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_130416494_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_130416494_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_130416494_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_130416494_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_130416494_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_130416494_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_130416494_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_130416494_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_wpml_mails: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_130416494_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_130416494_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Akismet Anti-Spam: by Automattic – 4.1.3
AMP: by AMP Project Contributors – 1.4.0
Classic Editor: by WordPress Contributors – 1.5
Gutenberg: by Gutenberg Team – 6.5.0
Jetpack by WordPress.com: by Automattic – 7.9
WooCommerce: by Automattic – 3.7.1 – 3.8.0 is available
WordPress Importer: by wordpressdotorg – 0.6.4

### Inactive Plugins (19) ###

Better Search Replace: by Delicious Brains – 1.3.3
Bulk Delete: by Sudar – 6.0.2
Child Theme Configurator: by Lilaea Media – 2.5.0
Cooked: by Boxy Studio – 1.7.6
Crowdsignal Polls & Ratings: by Automattic
Inc. – 2.1.2

Display Posts: by Bill Erickson – 3.0.2
Full Site Editing: by Automattic – 0.13
Insert Headers and Footers: by WPBeginner – 1.4.4
Loco Translate: by Tim Whitlock – 2.3.1
PJW Mime Config: by Peter Westwood – 1.00
Redirection: by John Godley – 4.4.2
The Events Calendar: by Modern Tribe
Inc. – 4.9.10

The Events Calendar Extension: Main Blog Loop: by Modern Tribe
Inc. – 1.0.0

Visual Composer: by visualcomposer.com – 22.0
WooCommerce Admin: by WooCommerce – 0.21.0
WooCommerce Distance Rate Shipping: by Automattic – 1.0.12 – 1.0.14 is available
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17
WP Mail Logging: by Christian Zöller – 1.9.1
Yoast SEO: by Team Yoast – 12.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

atomic-platform.php: by  –
WP.com Site Helper: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #46 - /loja/
Cart: #47 - /carrinho/
Checkout: #48 - /finalizar-compra/
My account: #49 - /minha-conta/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 533
Oldest: 2019-10-05 14:32:32 +0000
Newest: 2019-11-05 14:14:45 +0000

Pending: 1
Oldest: 2019-11-05 14:58:12 +0000
Newest: 2019-11-05 14:58:12 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment] 2019-11-13 10:29
Thank you for reporting this issue @liviopv. 

I can reproduce it:

![add_to_cart](https://user-images.githubusercontent.com/19143190/68755498-7e7b5500-0600-11ea-94a2-8e0cb6ceaa97.jpg)

**Comment by rwaynick** [comment] 2019-11-13 21:09
Another report in 15622672-hc today but I didn't realize it was this issue at the time.

**Comment by ObliviousHarmony** [comment] 2019-11-21 23:19
It seems like this extends much further than just the "Add To Cart" feature on the products page. One of the things the AMP plugin does is convert all POST forms into AJAX requests. The end result is that more or less every form in your store will exhibit this issue. I've seen it in the account pages, cart editing, and more. 

In addition to this, there will be some errors relating to Javascript and CSS to address. AMP doesn't allow for running arbitrary Javascript and has limitations on the size of CSS files. AMP is an entire component library, and as such, is meant to have a website built on top of it.

The plugin provides an `is_amp_endpoint()` function to support adding the necessary functionality to your theme and plugin code. From what I can tell, adding support for this plugin to WooCommerce Core would be a large undertaking, with similar work required in extensions as well.

The reason that setting the mode to "Transitional" works is because AMP is turned off for your pages. If you would like, I might suggest turning it to "Standard" and disabling AMP on all WooCommerce pages, as well as the Product post type. This way non-WooCommerce functionality will operate as expected.

**Comment by juliaamosova** [comment] 2020-02-28 23:28
Hi @liviopv, thanks for your patience as we've been evaluating this issue over with the WooCommerce Core Dev team. At this time, adding support for Google AMP is not a priority for the project. It is possible that we will reconsider this decision at some time. 

In the meantime, if Google AMP support is needed, [AMP for WooCommerce](https://ampforwp.com/woocommerce/) plugin can be used. Please know that it is a paid plugin. It is also worth mentioning that I don't have experience with it personally but it is worth a try. 

Due to the above, I am closing this issue at this time. Thanks for understanding!

**Closed by juliaamosova** 2020-02-28 23:28 UTC
Labels: bug, priority: low
