### ISSUE TITLE
WooCommerce flexslider touch screen issue

### ISSUE THREAD

**Issue by Nashoot** [woocommerce/woocommerce#29074] opened 2021-02-09 19:44 UTC
I have made some css changes to the gallery in single product page in woocommerce to make the thumbnails scroll horizontally. the issue is when trying to scroll the thumbnails on mobile devices the thubmnails won't scroll but the slider swipes left and right.

sometimes after resizing the browser to mobile size it scrolls and shows following error: **Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.**

I tried already multiple stuff with jQuery and filters but nothing is disabling the swipe conflict on mobile..

Tried to follow [THIS](https://wordpress.stackexchange.com/questions/338315/get-rid-of-product-images-mobile-swipe-functionality-from-woocommerce-single-pro/338350#338350) as well but nothing is working.

Here is the [LIVE EXAMPLE OF THE ISSUE](https://woocommerce-520989-1744121.cloudwaysapps.com/product/bulldozer-second/)

Here is a [VIDEO](https://gofile.io/d/gagKk0) showing the issue

After spending couple of hours on this and trying to fix the issue, i can cofirm this is a bug in woocommerce plugin.. I am not able to get rid of this annoying swipe when touching the thubmnails, so the thumbnails could scroll as expected!

https://user-images.githubusercontent.com/44740115/107418895-7bc72280-6b17-11eb-9c36-40acc369f206.mp4

**Comment by tammullen** [comment] 2021-02-11 21:52
Hi @Nashoot 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it as well as all the other information we ask for in our bug reports, without this info we cannot evaluate issues.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-02-11 21:52 UTC

**Comment by biboslaw** [comment] 2022-03-15 10:44
@Nashoot did you solve this problem? I am also facing this issue and I can't find a solution for this. Thanks :)

**Comment by Nashoot** [comment] 2022-03-17 08:35
> @Nashoot did you solve this problem? I am also facing this issue and I can't find a solution for this. Thanks :)

unfortunately no. i couldn't solve it! I have spent a lot of time trying to understand how this works but its a clear bug in woocommerce and seems nobody cares for it :). The touch issue on the phone is till today with the same behaviour.

**Comment by Rowdysign** [comment] 2024-05-10 14:07
Hello Nashoot,

I experienced the same problem before. You can use the following code in your functions.php:

add_filter( 'woocommerce_single_product_carousel_options', 'filter_single_product_carousel_options' );
function filter_single_product_carousel_options( $options ) {
	$options['touch'] = false;
    return $options;
}

This will disable the swipe functionality on the thumbnails.

I also got the error "Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.". I haven't found a solution for that, but if I found one I shall share it here aswell.
