### ISSUE TITLE
Product image changes don't show when previewing product page

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce#27780] opened 2020-09-25 09:03 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When updating the product image and then clicking preview, the updated product image is not displayed but the old/previous image is displayed.

However, it looks like the product preview button was hidden due to issue [#21723](https://github.com/woocommerce/woocommerce/issues/20641) as many WooCommerce product fields don't handle the preview function well. Maybe the actual issue here is that the button shouldn't be showing? 

**Expected behavior**

When previewing the page, all changes should be displayed, including an updated product image. 

**Actual behavior**

When previewing the page, the product image that was valid the last time the page was updated is displayed. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Steps to reproduce the bug:

1. Create a product or go to an existing product.
2. Set a product image and update the product. Confirm that you see the selected product image when viewing the product's page.
3. Edit the product and select a new product image. 
4. Preview the page. Confirm that you're seeing the product image set in step 2 rather than the one set in step 3. 

**Screenshots**

Example of the behavior: https://d.pr/i/tC03O3

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woodev.mystagingwebsite.com
Site address (URL): https://woodev.mystagingwebsite.com
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.71.1
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 20.10MB
Database Data Size: 11.40MB
Database Index Size: 8.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.28MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_commentmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
30_wp_comments: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
30_wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
30_wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_email_orders: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
30_wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
30_wp_followup_followup_history: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_options: Data: 0.19MB + Index: 0.05MB + Engine InnoDB
30_wp_postmeta: Data: 0.39MB + Index: 0.39MB + Engine InnoDB
30_wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
30_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
30_wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
30_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
30_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
30_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
30_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
30_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
30_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.38MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.22MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 48
aw_workflow: 1
bookable_person: 7
bookable_resource: 9
custom_css: 2
customize_changeset: 3
event_ticket: 4
follow_up_email: 12
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 16
page: 37
post: 3
product: 57
product_variation: 35
revision: 90
shop_coupon: 10
shop_order: 231
shop_order_refund: 8
shop_subscription: 11
slide: 2
user_request: 1
warranty_request: 6
wc_booking: 25
wc_membership_plan: 5
wc_product_tab: 2
wc_user_membership: 2
wcpf_item: 5
wcpf_project: 2
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Loco Translate: by Tim Whitlock – 2.4.3
WooCommerce Stripe Gateway: by WooCommerce – 4.5.2 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce: by Automattic – 4.5.2
WP Mail Logging: by MailPoet – 1.9.7

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.5.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 222
Oldest: 2020-08-25 09:19:26 +0000
Newest: 2020-09-25 08:39:43 +0000

Pending: 5
Oldest: 2020-09-25 09:03:01 +0000
Newest: 2020-09-27 10:47:56 +0000

`
```
</details>

**Comment by tammullen** [comment] 2020-09-25 15:12
Hi @hannahswain 

Thank you for taking the time to report this, we really appreciate your help. 

I can reproduce it on my end. 

The reason this is happening is because of a longstanding WordPress core issue https://core.trac.wordpress.org/ticket/20299 which means we can't auto save meta data and therefore include it in a preview. This also affects the Product data, Product tags, Product categories etc.

> Maybe the actual issue here is that the button shouldn't be showing?

The button was removed for a while but it was reintroduced as we found it was still useful for those making changes to the main content. https://github.com/woocommerce/woocommerce/pull/21838

I'm going to close this for now with `won't fix`. If there is any updates to the WordPress issue in the future we can revisit this.

**Closed by tammullen** 2020-09-25 15:12 UTC
