### ISSUE TITLE
Duplicate Order Number Created

### ISSUE THREAD

**Issue by irf143** [woocommerce/woocommerce#18579] opened 2018-01-24 08:04 UTC
There are 2 orders generated for 2 different customers using the same order number.
But only one order generated in backend. Also checked the databse, only one order is recorded.
The both customers placed at exactly the same time pretty much and they both got the email order confirmations.

So could it be that the woocommerce can’t recognise multiple orders placed at exactly the same time?
How can I prevent it from happen again?

Note: I am using WooCommerce 3.2.1

**Comment by kloon** [comment] 2018-01-24 08:58
Your issue is missing quite a lot of information, like your server setup, theme, plugins etc.

The times we have seen this is when you have caching present and it is not setup correctly, ie you have caching enabled on the cart and checkout pages, that can result in duplicate orders. The other scenario is when you have a master/slave DB setup and there is a considerable delay between the syncronization from master to slave or your db config is not set to do a read from master directly after writing to master. Since writes happen on master and reads from slave by default it would not pick up the first order when you gave multiple orders coming in at the same time which will cause it to overwrite the old order with the new one.

Closing this as invalid for now as I am not able to reproduce this with the latest 3.2 release or the master branch, plus we have not run into this on WooCommerce.com which utilises master/slave dbs correctly.

You are welcome to reopen this if you have steps to reproduce this on the master branch.

**Closed by kloon** 2018-01-24 08:58 UTC

**Comment by irf143** [comment] 2018-01-25 07:18
Thanks for the response.
Sorry for giving the additional information.

I cannot solve this issue yet. The cart and checkout pages disabled from cache. Also we have not using master/slave DB setup in our server.

**My Issue**:
When 2 customers ordered at same time, Only 1 order is created in database. But they both got the email order confirmations with **same order number**.
I don't know why WooCommerce is not recorded the both order in my database? If you have any other suggestion please share.

Thankyou



**WordPress Environment**
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en

**Server Environment**
Server Info: LiteSpeed
PHP Version: 5.6.33
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Database**
WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1049.92MB
Database Data Size: 609.73MB
Database Index Size: 440.19MB
wp_woocommerce_sessions: Data: 25.48MB + Index: 1.44MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.06MB + Index: 0.08MB
wp_woocommerce_order_items: Data: 16.55MB + Index: 6.52MB
wp_woocommerce_order_itemmeta: Data: 86.63MB + Index: 79.22MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
wp_advanced_notifications: Data: 0.00MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.00MB + Index: 0.00MB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
wp_cart_notices: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 2.52MB + Index: 3.03MB
wp_comments: Data: 38.58MB + Index: 27.09MB
wp_ewwwio_images: Data: 0.42MB + Index: 0.25MB
wp_feedmanager_channel: Data: 0.00MB + Index: 0.01MB
wp_feedmanager_country: Data: 0.01MB + Index: 0.02MB
wp_feedmanager_errors: Data: 0.00MB + Index: 0.00MB
wp_feedmanager_feed_status: Data: 0.00MB + Index: 0.00MB
wp_feedmanager_field_categories: Data: 0.00MB + Index: 0.00MB
wp_feedmanager_product_feed: Data: 0.00MB + Index: 0.00MB
wp_feedmanager_product_feedmeta: Data: 0.00MB + Index: 0.01MB
wp_feedmanager_source: Data: 0.00MB + Index: 0.01MB
wp_followup_coupons: Data: 0.00MB + Index: 0.01MB
wp_followup_coupon_logs: Data: 1.09MB + Index: 0.40MB
wp_followup_customers: Data: 1.49MB + Index: 2.96MB
wp_followup_customer_carts: Data: 6.40MB + Index: 0.83MB
wp_followup_customer_notes: Data: 0.00MB + Index: 0.00MB
wp_followup_customer_orders: Data: 1.00MB + Index: 0.61MB
wp_followup_email_coupons: Data: 0.00MB + Index: 0.00MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.03MB
wp_followup_email_logs: Data: 3.70MB + Index: 1.13MB
wp_followup_email_orders: Data: 18.98MB + Index: 3.78MB
wp_followup_email_order_coupons: Data: 0.00MB + Index: 0.00MB
wp_followup_email_tracking: Data: 1.43MB + Index: 1.02MB
wp_followup_followup_history: Data: 25.14MB + Index: 0.60MB
wp_followup_order_categories: Data: 1.76MB + Index: 3.01MB
wp_followup_order_items: Data: 2.51MB + Index: 4.56MB
wp_followup_subscribers: Data: 0.26MB + Index: 0.52MB
wp_followup_subscribers_to_lists: Data: 0.00MB + Index: 0.00MB
wp_followup_subscriber_lists: Data: 0.00MB + Index: 0.00MB
wp_hidemysiteSecure: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_miwosql_queries: Data: 0.00MB + Index: 0.00MB
wp_nf3_actions: Data: 0.00MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.01MB + Index: 0.00MB
wp_nf3_fields: Data: 0.00MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.01MB
wp_nf3_forms: Data: 0.00MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.01MB + Index: 0.00MB
wp_nf3_objects: Data: 0.00MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.00MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.00MB + Index: 0.00MB
wp_optins: Data: 0.00MB + Index: 0.00MB
wp_optin_meta: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 7.48MB + Index: 3.52MB
wp_postmeta: Data: 223.75MB + Index: 179.47MB
wp_posts: Data: 28.56MB + Index: 22.09MB
wp_rac_abandoncart: Data: 1.02MB + Index: 0.00MB
wp_rac_email_logs: Data: 0.14MB + Index: 0.00MB
wp_rac_templates_email: Data: 0.02MB + Index: 0.00MB
wp_redirection_404: Data: 0.00MB + Index: 0.00MB
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB
wp_redirection_items: Data: 0.06MB + Index: 0.05MB
wp_redirection_logs: Data: 1.24MB + Index: 0.41MB
wp_remarkety_carts: Data: 0.02MB + Index: 0.00MB
wp_remarkety_carts_guests: Data: 0.33MB + Index: 0.02MB
wp_simple_history: Data: 3.65MB + Index: 1.06MB
wp_simple_history_contexts: Data: 17.41MB + Index: 8.48MB
wp_siq_sync: Data: 0.00MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB
wp_sm_advanced_search_temp: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.01MB + Index: 0.02MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 70.59MB + Index: 72.19MB
wp_users: Data: 3.52MB + Index: 6.55MB
wp_w3tc_cdn_pathmap: Data: 0.02MB + Index: 0.02MB
wp_w3tc_cdn_queue: Data: 0.02MB + Index: 0.02MB
wp_wc_deposits_payment_plans: Data: 0.00MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.03MB + Index: 0.02MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.93MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.01MB
wp_wfFileMods: Data: 1.80MB + Index: 0.39MB
wp_wfHits: Data: 3.83MB + Index: 0.64MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.06MB + Index: 0.00MB
wp_wfKnownFileList: Data: 0.91MB + Index: 0.12MB
wp_wfLeechers: Data: 7.14MB + Index: 5.63MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.03MB + Index: 0.01MB
wp_wfLogins: Data: 0.54MB + Index: 0.10MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.01MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.03MB + Index: 0.01MB
wp_wfScanners: Data: 0.00MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.16MB + Index: 0.06MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB
wp_wpdatacharts: Data: 0.00MB + Index: 0.00MB
wp_wpeditor_settings: Data: 0.00MB + Index: 0.00MB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.11MB + Index: 0.05MB
wp_yith_wcwl_lists: Data: 0.14MB + Index: 0.14MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.01MB
wp_yoast_seo_meta: Data: 0.15MB + Index: 0.15MB

**Post Type Counts**
acf: 9
announcement: 2
attachment: 652
custom_css: 1
faq: 20
follow_up_email: 6
map: 1
mc4wp-form: 1
nav_menu_item: 46
page: 32
post: 53
product: 244
product_variation: 1004
recipe: 30
revision: 742
scheduled-action: 16905
scheduled_export: 2
shipping_zone: 8
shop_coupon: 11765
shop_order: 42979
shop_order_refund: 93
sidebar: 2
testimonials: 50
warranty_request: 7
was: 35
wccaf: 1
wc_voucher: 1
wpcf7_contact_form: 1

**Security**
Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

**Active Plugins (64)**
ManageWP - Worker: by ManageWP – 4.3.3
Redux Framework: by Team Redux – 3.6.7.7
Extension Works Framework: by Extension Works – 2.1.8 – Not tested with the active version of WooCommerce
Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.0.1
Admin Menu Editor: by Janis Elsts – 1.8.1
Advanced Custom Fields: by Elliot Condon – 4.4.12
WooCommerce Blacklister: by Aelia – 0.9.9.170925 – Not tested with the active version of WooCommerce
Ajax Search Lite: by Ernest Marcinko – 4.7.10
All 404 Redirect to Homepage: by Fakhri Alsadi – 1.8
WooCommerce Back In Stock Notifier: by Fantastic Plugins – 8.9 – Not tested with the active version of WooCommerce
Black Studio TinyMCE Widget: by Black Studio – 2.5.1
Contact Form 7 - Success Page Redirects: by Ryan Nevius – 1.2.0
Contact Form 7: by Takayuki Miyoshi – 4.9.1
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.1.2 – Not tested with the active version of WooCommerce
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.6
WP Hide Plugin Updates and Warnings: by Midland Web Company – 1.0
Idle User Logout: by Abiral Neupane – 2.3
MailChimp for WordPress: by ibericode – 4.1.11
Math Quiz: by ATI – 1.9.2
PixelYourSite PRO: by PixelYourSite – 6.3.4 – Not tested with the active version of WooCommerce
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.3.3.1 – Not tested with the active version of WooCommerce
Recover Abandoned Cart: by Fantastic Plugins – 16.6 – Not tested with the active version of WooCommerce
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0.1
Really Simple SSL: by Rogier Lankhorst – 2.5.24
Redirection: by John Godley – 2.8.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remarkety - Email Marketing for WooCommerce: by Remarkety – 1.2.9 – Not tested with the active version of WooCommerce
Reveal IDs: by Oliver Schlöbe – 1.5.2
SEO Ultimate: by SEO Design Solutions – 7.6.5.9
Simple History: by Pär Thernström – 2.18
Page Builder by SiteOrigin: by SiteOrigin – 2.5.12
Smart Manager: by Store Apps – 3.9.15 – Not tested with the active version of WooCommerce
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.7
W3 Total Cache: by Frederick Townes – 0.9.6
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629 – Not tested with the active version of WooCommerce
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.10 – 2.2.11 is available – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.9 – 1.3.0 is available – Not tested with the active version of WooCommerce
WooCommerce Create Customer on Order: by cxThemes – 1.23 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by cxThemes – 2.37 – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.5.2 – 4.6.4 is available – Not tested with the active version of WooCommerce
WooCommerce eWAY Payment Gateway: by WooThemes – 3.1.13 – 3.1.14 is available – Not tested with the active version of WooCommerce
Booster for WooCommerce: by Algoritmika Ltd – 3.2.2 – Not tested with the active version of WooCommerce
WooCommerce jQuery Cookie Fix: by Splashing Pixels (Roy Ho) – 1.0 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Bas Elbers – 2.6.4 – Not tested with the active version of WooCommerce
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2 – Not tested with the active version of WooCommerce
WooCommerce Shop as Customer: by cxThemes – 2.10 – Not tested with the active version of WooCommerce
WooCommerce Store Credit: by WooCommerce – 2.1.10 – 2.1.11 is available – Not tested with the active version of WooCommerce
WooCommerce - Store Exporter Deluxe: by Visser Labs – 2.4 – Not tested with the active version of WooCommerce
WooCommerce - Store Toolkit: by Visser Labs – 1.7.5 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.4 – 3.0.6 is available – Not tested with the active version of WooCommerce
WooCommerce WooSales Mobile: by Southern Cross Global Consulting – 2.9.5 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1 – 3.2.6 is available
Wordfence Security: by Wordfence – 6.3.21
Yoast SEO: by Team Yoast – 5.8
WP Add Custom CSS: by Daniele De Santis – 1.0.1
WP Crontrol: by John Blackbourn & contributors – 1.6.2
Custom Bulk Actions: by Seravo Oy – 0.1.3
WP Editor: by Benjamin Rojas – 1.2.6.3
WP Google Maps: by WP Google Maps – 6.4.06
WP Maintenance Mode: by Designmodo – 2.0.9
WooCommerce Google Feed Manager: by Michel Jongbloed – 1.9.4 – Not tested with the active version of WooCommerce
WP Smush: by WPMU DEV – 2.7.6
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce

**Settings**
API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

**WC Pages**
Shop base: #21227 - /shop/
Cart: #21228 - /cart/
Checkout: #21229 - /checkout/
My account: #21230 - /my-account/
Terms and conditions: #28 - /terms-and-conditions/

**Theme**
Name: Custom Theme
Version: 1.0
Author URL:
Child Theme: ✔
Parent Theme Name: Evolution
Parent Theme Version: 1.0
Parent Theme Author URL: https://www.seoempire.com.au
WooCommerce Support: ✔

Debugging mode for Store Exporter Deluxe: ✔
Extended logging mode for Store Exporter Deluxe: ✔
Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available; ssh2_connect()
ssh2_auth_password()
ssh2_sftp(). Contact your hosting provider.

**Comment by kloon** [comment] 2018-01-25 08:04
I can't seem to find your cart page so cannot test, but from the sounds of things and looking at your plugins this seems very likely related to caching.

I would suggest you disabled all plugins except woocommerce and switch to a default theme like storefront and test again, also be sure to delete the cache folder on your server after disabling the caching plugin as WordPress will continue serving content from that folder even if the plugin is disable.

If you continue to experience issues I suggest you contact support as this is used for issues with WooCommerce core and not for general support.
