### ISSUE TITLE
Paypal checkout page not working

### ISSUE THREAD

**Issue by phunkei** [woocommerce/woocommerce#27539] opened 2020-08-31 18:20 UTC
In a customers project using woocommerce, the paypal payment does not work as expected. The target page (first external page in checkout process) displays an error message without any specific information. We already changed the payment credentials to a different paypal-account, same error.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Paypal generates an error page without any return for the customer
![image](https://user-images.githubusercontent.com/758438/91751831-b53d4e80-ebc5-11ea-9c53-383a724f3f26.png)

**Expected behavior**
Regular checkout process

**Actual behavior**
Paypal generates an error page without any return for the customer

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
None, currently paypal is deactivated because of the known behavior and the project is in production mode.

**Screenshots**
see above.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
### WordPress Environment ###

WordPress address (URL): https://www.olivenoelbande.com
Site address (URL): https://www.olivenoelbande.com
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.4.2 - Es ist eine neuere Version von WordPress verfügbar (5.5)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41
PHP Version: 7.3.6
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.6.19-67.0-log
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 5.59MB
Datenbank-Datengröße: 3.81MB
Datenbank-Indexgröße: 1.78MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 1.17MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Daten: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Daten: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 30
customize_changeset: 1
invoice: 26
nav_menu_item: 10
page: 17
post: 3
product: 1
revision: 48
shop_coupon: 1
shop_order: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

All in One SEO Pack: von All in One SEO Team – 3.6.2
Jetpack von WordPress.com: von Automattic – 8.8.2
Klarna Order Management for WooCommerce: von klarna
krokedil – 1.5.5

Klarna Payments for WooCommerce: von krokedil
klarna
automattic – 2.1.1 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.4.1 getestet

Vendidero Helper: von Vendidero – 1.3.0
Germanized für WooCommerce Pro: von vendidero – 2.1.6
Germanized für WooCommerce: von vendidero – 3.1.12
WooCommerce Services: von Automattic – 1.24.1 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.4.1 getestet
WooCommerce: von Automattic – 4.4.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: von Automattic – 4.1.6
Hello Dolly: von Matt Mullenweg – 1.7.2

### Must Use Plugins (1) ###

cmb2.php: von  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #6 - /shop/
Warenkorb: #36 - /warenkorb/
Kasse: #8 - /checkout/
Mein Konto: #9 - /my-account/
Allgemeine Geschäftsbedingungen: #62 - /agb/

### Theme ###

Name: Olivenölbande
Version: 1.0.0
Author URL: https://www.phunkei.de
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: oob/woocommerce/cart/cart-empty.php
oob/woocommerce/cart/cart-item-data.php
oob/woocommerce/cart/cart-shipping.php
oob/woocommerce/cart/cart-totals.php
oob/woocommerce/cart/cart.php Version 3.8.1 ist veraltet. Die Hauptversion ist 4.4.0
oob/woocommerce/cart/cross-sells.php Version 3.0.0 ist veraltet. Die Hauptversion ist 4.4.0
oob/woocommerce/cart/mini-cart.php
oob/woocommerce/cart/proceed-to-checkout-button.php
oob/woocommerce/cart/shipping-calculator.php
oob/woocommerce/checkout/cart-errors.php
oob/woocommerce/checkout/form-billing.php
oob/woocommerce/checkout/form-checkout.php
oob/woocommerce/checkout/form-coupon.php
oob/woocommerce/checkout/form-login.php
oob/woocommerce/checkout/form-pay.php
oob/woocommerce/checkout/form-shipping.php
oob/woocommerce/checkout/order-receipt.php
oob/woocommerce/checkout/payment-method.php
oob/woocommerce/checkout/payment.php
oob/woocommerce/checkout/review-order.php
oob/woocommerce/checkout/terms.php
oob/woocommerce/checkout/thankyou.php
oob/woocommerce/emails/admin-cancelled-order.php Version 3.7.0 ist veraltet. Die Hauptversion ist 4.1.0
oob/woocommerce/emails/admin-failed-order.php
oob/woocommerce/emails/admin-new-order.php
oob/woocommerce/emails/customer-completed-order.php
oob/woocommerce/emails/customer-invoice.php
oob/woocommerce/emails/customer-new-account.php
oob/woocommerce/emails/customer-note.php
oob/woocommerce/emails/customer-on-hold-order.php
oob/woocommerce/emails/customer-processing-order.php
oob/woocommerce/emails/customer-refunded-order.php
oob/woocommerce/emails/customer-reset-password.php
oob/woocommerce/emails/email-addresses.php
oob/woocommerce/emails/email-customer-details.php
oob/woocommerce/emails/email-downloads.php
oob/woocommerce/emails/email-footer.php
oob/woocommerce/emails/email-header.php
oob/woocommerce/emails/email-order-details.php
oob/woocommerce/emails/email-order-items.php
oob/woocommerce/emails/email-styles.php
oob/woocommerce/emails/plain/admin-cancelled-order.php Version 3.7.0 ist veraltet. Die Hauptversion ist 4.1.0
oob/woocommerce/emails/plain/admin-failed-order.php
oob/woocommerce/emails/plain/admin-new-order.php
oob/woocommerce/emails/plain/customer-completed-order.php
oob/woocommerce/emails/plain/customer-invoice.php
oob/woocommerce/emails/plain/customer-new-account.php
oob/woocommerce/emails/plain/customer-note.php
oob/woocommerce/emails/plain/customer-on-hold-order.php
oob/woocommerce/emails/plain/customer-processing-order.php
oob/woocommerce/emails/plain/customer-refunded-order.php
oob/woocommerce/emails/plain/customer-reset-password.php
oob/woocommerce/emails/plain/email-addresses.php
oob/woocommerce/emails/plain/email-customer-details.php
oob/woocommerce/emails/plain/email-downloads.php
oob/woocommerce/emails/plain/email-order-details.php
oob/woocommerce/emails/plain/email-order-items.php
oob/woocommerce/myaccount/dashboard.php Version 2.6.0 ist veraltet. Die Hauptversion ist 4.4.0
oob/woocommerce/myaccount/downloads.php
oob/woocommerce/myaccount/form-add-payment-method.php Version 3.4.0 ist veraltet. Die Hauptversion ist 4.3.0
oob/woocommerce/myaccount/form-edit-account.php
oob/woocommerce/myaccount/form-edit-address.php
oob/woocommerce/myaccount/form-login.php Version 3.6.0 ist veraltet. Die Hauptversion ist 4.1.0
oob/woocommerce/myaccount/form-lost-password.php
oob/woocommerce/myaccount/form-reset-password.php
oob/woocommerce/myaccount/lost-password-confirmation.php
oob/woocommerce/myaccount/my-account.php
oob/woocommerce/myaccount/my-address.php
oob/woocommerce/myaccount/my-downloads.php
oob/woocommerce/myaccount/my-orders.php
oob/woocommerce/myaccount/navigation.php
oob/woocommerce/myaccount/orders.php
oob/woocommerce/myaccount/payment-methods.php
oob/woocommerce/myaccount/view-order.php
oob/woocommerce/order/form-tracking.php
oob/woocommerce/order/order-again.php
oob/woocommerce/order/order-details-customer.php
oob/woocommerce/order/order-details-item.php
oob/woocommerce/order/order-details.php
oob/woocommerce/order/order-downloads.php
oob/woocommerce/order/tracking.php

Outdated Templates: ❌

</details>

Paypal Log generated by Woocommerce:

<details>

2020-08-31T14:32:51+00:00 INFO Generating payment form for order 239. Notify URL: https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
2020-08-31T14:32:51+00:00 INFO PayPal Request Args for order 239: Array
(
    [cmd] => _cart
    [business] => info@olivenoelbande.com
    [no_note] => 1
    [currency_code] => EUR
    [charset] => utf-8
    [rm] => 2
    [upload] => 1
    [return] => https://www.olivenoelbande.com/checkout/order-received/239/?key=wc_order_xtdLOBvKLGiO3&utm_nooverride=1
    [cancel_return] => https://www.olivenoelbande.com/checkout/order-received/239/?key=wc_order_xtdLOBvKLGiO3&retry=1
    [page_style] => 
    [image_url] => https://www.olivenoelbande.com/wp-content/uploads/OOLlogo.png
    [paymentaction] => sale
    [invoice] => WC-239
    [custom] => {"order_id":239,"order_key":"wc_order_xtdLOBvKLGiO3"}
    [notify_url] => https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
    [first_name] => ***
    [last_name] => ***
    [address1] => ***
    [address2] => ***
    [city] => ***
    [state] => ***
    [zip] => ***
    [country] => ***
    [email] => ***@***
    [night_phone_a] => ***
    [night_phone_b] => ***
    [address_override] => 0
    [no_shipping] => 0
    [item_name_1] => Bio-Olivenöl x 1
    [quantity_1] => 1
    [amount_1] => 54
    [item_number_1] => 239
    [bn] => WooThemes_Cart
)

2020-08-31T15:11:27+00:00 INFO Generating payment form for order 239. Notify URL: https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
2020-08-31T15:11:27+00:00 INFO PayPal Request Args for order 239: Array
(
    [cmd] => _cart
    [business] => info@olivenoelbande.com
    [no_note] => 1
    [currency_code] => EUR
    [charset] => utf-8
    [rm] => 2
    [upload] => 1
    [return] => https://www.olivenoelbande.com/checkout/order-received/239/?key=wc_order_xtdLOBvKLGiO3&utm_nooverride=1
    [cancel_return] => https://www.olivenoelbande.com/checkout/order-received/239/?key=wc_order_xtdLOBvKLGiO3&retry=1
    [page_style] => 
    [image_url] => https://www.olivenoelbande.com/wp-content/uploads/OOLlogo.png
    [paymentaction] => sale
    [invoice] => WC-239
    [custom] => {"order_id":239,"order_key":"wc_order_xtdLOBvKLGiO3"}
    [notify_url] => https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
    [first_name] => ***
    [last_name] => ***
    [address1] => ***
    [address2] => ***
    [city] => ***
    [state] => ***
    [zip] => ***
    [country] => ***
    [email] => ***@***
    [night_phone_a] => ***
    [night_phone_b] => ***
    [address_override] => 0
    [no_shipping] => 0
    [item_name_1] => Bio-Olivenöl x 1
    [quantity_1] => 1
    [amount_1] => 54
    [item_number_1] => 239
    [bn] => WooThemes_Cart
)

2020-08-31T15:31:09+00:00 INFO Generating payment form for order 240. Notify URL: https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
2020-08-31T15:31:09+00:00 INFO PayPal Request Args for order 240: Array
(
    [cmd] => _cart
    [business] => info@olivenoelbande.com
    [no_note] => 1
    [currency_code] => EUR
    [charset] => utf-8
    [rm] => 2
    [upload] => 1
    [return] => https://www.olivenoelbande.com/checkout/order-received/240/?key=wc_order_iTKi4yQVUgPLE&utm_nooverride=1
    [cancel_return] => https://www.olivenoelbande.com/checkout/order-received/240/?key=wc_order_iTKi4yQVUgPLE&retry=1
    [page_style] => 
    [image_url] => https://www.olivenoelbande.com/wp-content/uploads/OOLlogo.png
    [paymentaction] => sale
    [invoice] => WC-240
    [custom] => {"order_id":240,"order_key":"wc_order_iTKi4yQVUgPLE"}
    [notify_url] => https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
    [first_name] => ***
    [last_name] => ***
    [address1] => ***
    [address2] => ***
    [city] => ***
    [state] => ***
    [zip] => ***
    [country] => ***
    [email] => ***@***
    [night_phone_a] => ***
    [night_phone_b] => ***
    [address_override] => 0
    [no_shipping] => 0
    [item_name_1] => Bio-Olivenöl x 1
    [quantity_1] => 1
    [amount_1] => 54
    [item_number_1] => 240
    [bn] => WooThemes_Cart
)

2020-08-31T15:37:44+00:00 INFO Generating payment form for order 239. Notify URL: https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
2020-08-31T15:37:44+00:00 INFO PayPal Request Args for order 239: Array
(
    [cmd] => _cart
    [business] => info@olivenoelbande.com
    [no_note] => 1
    [currency_code] => EUR
    [charset] => utf-8
    [rm] => 2
    [upload] => 1
    [return] => https://www.olivenoelbande.com/checkout/order-received/239/?key=wc_order_xtdLOBvKLGiO3&utm_nooverride=1
    [cancel_return] => https://www.olivenoelbande.com/checkout/order-received/239/?key=wc_order_xtdLOBvKLGiO3&retry=1
    [page_style] => 
    [image_url] => https://www.olivenoelbande.com/wp-content/uploads/OOLlogo.png
    [paymentaction] => sale
    [invoice] => WC-239
    [custom] => {"order_id":239,"order_key":"wc_order_xtdLOBvKLGiO3"}
    [notify_url] => https://www.olivenoelbande.com/wc-api/WC_Gateway_Paypal/
    [first_name] => ***
    [last_name] => ***
    [address1] => ***
    [address2] => ***
    [city] => ***
    [state] => ***
    [zip] => ***
    [country] => ***
    [email] => ***@***
    [night_phone_a] => ***
    [night_phone_b] => ***
    [address_override] => 0
    [no_shipping] => 0
    [item_name_1] => Bio-Olivenöl x 1
    [quantity_1] => 1
    [amount_1] => 54
    [item_number_1] => 239
    [bn] => WooThemes_Cart
)

</details>

**Comment by juliaamosova** [comment] 2020-09-11 15:37
Hi @phunkei,

Thanks for raising the issue. I tried using PayPal Standard on my test site and was not able to reproduce it. I managed to get to PayPal modal without any issues as I clicked on the `Proceed to PayPal` button. 

Here is a god showing that it works for me:

![](http://g.recordit.co/hYhWs8XmeK.gif)

You did not provide how your PayPal is set up so I tested with my set up as follows:

![pp](https://user-images.githubusercontent.com/19143190/92945276-0dc0e700-f423-11ea-92b2-df046a161a1e.jpg)

At this point, further troubleshooting is needed on your site. 

Also, the type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-09-11 15:37 UTC
