### ISSUE TITLE
Persistent cart not cleared after checkout without payment

### ISSUE THREAD

**Issue by nilsglow** [woocommerce/woocommerce#27576] opened 2020-09-03 11:05 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When an order is completed without payment (order total is 0), the persistent cart is not cleared and thus the items remain in the cart. 

**Expected behavior**
I believe completing an order without payment should also clear the persistent cart analogous to orders completed by payment gateways. Eg., `WC_Gateway_BACS::process_payment()` calls `WC_Cart::empty_cart()` with `$clear_persistent_cart` left at it's default of `true`.

**Actual behavior**
When an order is completed without payment (order total is 0 so `WC()->cart->needs_payment()` is `false`, checked in `WC_Checkout::process_checkout()`), `WC_Checkout::process_order_without_payment()` calls `wc_empty_cart()`, which in turn calls `WC_Cart::empty_cart()` with `$clear_persistent_cart` set to false. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add item to cart
2. Use 100% coupon code to have an order total of zero
3. Proceed with checkout
4. Observe that item is still in cart

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://uawg-wp-dev.uncia.local/x
Site address (URL): https://uawg-wp-dev.uncia.local/x
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: ❌ 5.4.2 - Es ist eine neuere Version von WordPress verfügbar (5.5.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Debian)
PHP Version: 7.2.33-1+0~20200807.47+debian10~1.gbpcb3068
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.45-MariaDB-0+deb9u1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 33.41MB
Datenbank-Datengröße: 30.73MB
Datenbank-Indexgröße: 2.68MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.22MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_aelia_dismissed_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mainwp_client_report: Daten: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_client_report_client: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_client_report_format: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_client_report_site_token: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_client_report_token: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_group: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_request_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_tips: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_users: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_wp: Daten: 0.31MB + Index: 0.02MB + Engine InnoDB
wp_mainwp_wp_backup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mainwp_wp_backup_progress: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mainwp_wp_group: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mainwp_wp_options: Daten: 0.25MB + Index: 0.02MB + Engine InnoDB
wp_mainwp_wp_settings_backup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mainwp_wp_sync: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 3.08MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Daten: 19.52MB + Index: 0.64MB + Engine InnoDB
wp_posts: Daten: 3.52MB + Index: 0.13MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 2.52MB + Index: 0.28MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 36
condition_group: 1
custom_css: 1
elementor_font: 2
elementor_library: 12
nav_menu_item: 6
page: 13
post: 1
product: 12
restriction: 1
revision: 354
shop_coupon: 29
shop_order: 80

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

uAwg Extensions: von Nils Kalchhauser  – 0.1.0
Autocomplete WooCommerce Orders: von Liam McArthur – 1.3.1 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.3.0 getestet
Autoptimize: von Frank Goossens (futtta) – 2.7.3
Classic Editor: von WordPress-Mitwirkende – 1.5
OpenID Connect Generic: von daggerhart – 3.6.0
Extras for Elementor: von Namogo – 2.2.32
Elementor Pro: von Elementor.com – 2.10.3
Elementor: von Elementor.com – 2.9.13
Gettext override translations: von Ramon Fincken – 1.0.1
Page scroll to id: von malihu – 1.6.7
PowerPack Pro for Elementor: von Team IdeaBox - PowerPack Elements – 1.5.1
rapidmail newsletter marketing: von rapidmail GmbH – 2.1.4
Aelia Foundation Classes for WooCommerce: von Aelia – 2.0.21.200629
WC Multiple Email Recipients: von Con Schneider – 1.3 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.3.0 getestet
WooCommerce EU VAT Assistant: von Aelia – 1.14.3.200630
WooCommerce PayPal Checkout Gateway: von WooCommerce – 2.0.3
WooCommerce Stripe-Gateway: von WooCommerce – 4.5.0 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.3.0 getestet
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 2.5.3
WooCommerce: von Automattic – 4.3.0 (Update auf Version 4.4.1 ist verfügbar)
WP Migrate DB: von Delicious Brains – 1.0.13
WP-Matomo: von André Bräkling – 1.0.22
Page Builder Framework Premium Addon: von David Vongries – 2.4.4

### Inactive Plugins (4) ###

Akismet Anti-Spam: von Automattic – 4.1.6
Comet Cache: von WebSharks
Inc. – 170220

Safe SVG: von Daryll Doyle – 1.9.9
ShortPixel Image Optimizer: von ShortPixel – 4.19.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Elementor Safe Mode: von Elementor.com – 1.0.0
WP Migrate DB Compatibility: von Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #174 - /shop/
Warenkorb: #175 - /warenkorb/
Kasse: #262 - /kasse/
Mein Konto: #177 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: uawg
Version: 1.0.0
Author URL: https://digitalkollektiv.at
Child Theme: ✔
Parent Theme Name: Page Builder Framework
Parent Theme Version: 2.5 – 2.5.5 ist verfügbar
Parent Theme Author URL: https://mapsteps.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 253
Oldest: 2020-08-03 23:48:52 +0200
Newest: 2020-09-03 12:23:35 +0200

Ausstehend: 1
Oldest: 2020-09-03 15:48:43 +0200
Newest: 2020-09-03 15:48:43 +0200

`
```
</details>

**Comment by juliaamosova** [comment] 2020-09-03 21:04
Hi @nilsglow,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I placed an order with the coupon that gives 100% discount and the cart was empty when the order was placed:

![cart](https://user-images.githubusercontent.com/19143190/92166856-5c5cf880-ee07-11ea-8eee-5e0846ecb998.jpg)

Can you please confirm that you can reproduce the issue with all plugins disabled except for WooCommerce and one of our default themes such as Storefront? I see that you marked it as you've done the plugins and theme conflict on your site but I always like to double-check.

**Comment by juliaamosova** [comment] 2020-09-15 16:33
Hi @nilsglow,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-09-15 16:33 UTC
Labels: status: needs feedback
