### ISSUE TITLE
Woocomerce Email has a bug

### ISSUE THREAD

**Issue by NelsonYiu023** [woocommerce/woocommerce#28658] opened 2020-12-23 07:14 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

To whom it may concern.

We found a bug related to the order in WooCommerce with an order note that are not the same content.
Order #14795 from our consumer made, but the order note from woocommerce email deliver to us are wrong data.
Around 50 items missing in the order note compared with backend "Order History".

Insted of bugs, any other reasons?

Please let me know the root cause and solution.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-12-23 22:40
Hi @NelsonYiu023,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Comment by NelsonYiu023** [comment] 2020-12-24 01:42
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.








**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Order #14795 from our consumer made, but the order note from woocommerce email deliver to us are wrong data.
Around 50 items missing in the order note compared with backend "Order History".

**Expected behavior**
The whole ordering items and information will be shown in the new order email 

**Actual behavior**
Total around 250 items, only 200 items can be shown. The remaining items are disappeared, but we can find the record in order page

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Order Page
2. Click on Order #14795, and choose to resend the order note 
3. See the email with loss data

**Screenshots**
If applicable, add screenshots to help explain your problem.



**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by barryhughes** [comment] 2024-01-19 01:05
There does not appear to be any cut-off for me, locally, if I use a tool that captures the email. 

So (assuming this wasn't solved by some other body of work) it seems the problem is not inside WooCommerce but, perhaps, happens after control is handed across to `wp_mail()` (or could even be a problem inside specific email clients, which cut the text off if the email body is too long)?

@zhongruige, @NelsonYiu023: I appreciate quite some time has passed since you looked at this, but if you have any notes about how you tested this, what email/SMTP plugins (if any), or what email client you used, that could be helpful.

Even if the problem is not directly inside WooCommerce, that doesn't necessarily mean it's not our responsibility: there could be strategies worth exploring (like only showing the first *n* orders, or providing a complete list as an attached text file if the number of line items passes some or other threshold).

**Comment by zhongruige** [comment] 2024-01-19 17:47
Hi @barryhughes 👋 

>  I appreciate quite some time has passed since you looked at this, but if you have any notes about how you tested this, what email/SMTP plugins (if any), or what email client you used, that could be helpful.

If I recall correctly, I don't believe I used a specific plugin for this, instead, I used a site that was configured to send out emails, so this went directly to my own email (Gmail). Otherwise I likely would have used something like [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) to test this.

**Comment by barryhughes** [comment] 2024-01-19 21:41
Thanks!

I can *somewhat* replicate but, if this is what others are experiencing here, I also don't think it's a problem for us to solve.

- I created a test site (JN, WP 6.4.2, WC 8.5.1).
- Used WP Mail SMTP to hook up emails.
- Generated a test order (I used my own Gmail account for the billing email address) with 250 line items.

Over in Gmail, I saw something very similar to the earlier screenshots, but there was also a note explaining they had clipped the message (and there was a link to view the full message):

<div align="center"><img width="700" alt="gmail-message-clipping" src="https://github.com/woocommerce/woocommerce/assets/3594411/d0bf868e-be76-4042-b242-1d41dd6fe653"></div>

On clicking that link, a new tab opened and I could see the complete order in all its glory. So, this definitely seems like an issue in one or more email clients, and is not directly in our control. For that reason, I'm going to close this issue (please let me know if anyone disagrees). Last few notes:

- I think this scenario could reasonably be described as an edge case and, of course, it's possible to customize our emails (such as via template overrides). So, for any projects where this problem is prevalent, the best solution 'today' is probably to create a bespoke email template.
- I'm sure we could also consider a further enhancement [(if someone wants to create one)](https://woo.com/feature-requests/woocommerce/) to add a means of handling this sort of thing from WC Core (I'm not immediately sure how desirable that is, though, so posting a request would help us to measure interest).

**Closed by barryhughes** 2024-01-19 21:41 UTC
Labels: type: bug, needs: author feedback, priority: normal, focus: email, plugin: woocommerce, team: Proton
