### ISSUE TITLE
try to add countdown after single product summary

### ISSUE THREAD

**Issue by Carlinhuuh** [woocommerce/woocommerce#25930] opened 2020-03-15 21:46 UTC
Hi! I’ve try everything to change my product page but cant see another option.
So, lets understand my problem:
i need add after button cart the countdown, but i dont know how!

Can anyone else help me?

The page I need help with: https://testeclientes.com.br/produto/huda-new-nude/

The code is: `/** excerpt position change **/
add_action( 'woocommerce_after_single_product_summary', 'woocommerce_template_single_add_to_cart' );

function woocommerce_template_single_add_to_cart () {

	echo '<form class="cart" action="https://upnid.com/go/p24070?p=7v1ke" method="get">
	
		<button type="submit" class="single_add_to_cart_button button alt">Comprar</button>
	
		<input type="hidden" name="p" value="7v1ke" />
		</form>';	
	
}

remove_action( 'woocommerce_after_shop_loop_item', 'woocommerce_template_loop_add_to_cart' );
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );
/** countdown position change **/
do_action( 'woocommerce_after_single_product_summary' . $product->get_type() . 'woocommerce_template_single_add_to_cart' );

function woocommerce_template_single_add_to_cart(){
	echo '<div class="woo-sctr-shortcode-wrap">';
	echo do_shortcode('[sales_countdown_timer id="salescountdowntimer"]');
	echo '</div>';
}`

**Comment by tammullen** [comment] 2020-03-17 09:20
Hi @Carlinhuuh 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-03-17 09:20 UTC
