### ISSUE TITLE
Shipping method that is unset using woocommerce_package_rates is still being calculated.

### ISSUE THREAD

**Issue by JacksonCleary** [woocommerce/woocommerce#27052] opened 2020-07-16 19:18 UTC
Hello,

- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

I found this when using the WooCommerce USPS shipping plugin, but I do not think it is confined to the USPS shipping plugin. 

I have found that when using `woocommerce_package_rates` to unset a shipping method, USPS plugin rates are still being calculated. This is using:

- Retrieve Standard Service rates from the USPS API
- Using dimensions for the box calculator.

___

**Expected behavior**
Unsetting a shipping method via `woocommerce_package_rates` should not have it be calculated.

**Actual behavior**
It seems that it is still calculated but hidden instead?

**WordPress Environment**
- WordPress 5.4.2
- Woocommerce 4.2+
- Woocommerce USPS Shipping 4.4.45
- Debugging is turned on.

___

**Steps to Reproduce**
I noticed this when conditionally unsetting USPS Priority Rates based on a product category for products in the cart.
1. Cart has 100 small items. 
2. Shipping calculation takes 2 minutes to load when USPS API is enabled.
3. Unset shipping method via `woocommerce_package_rates`
4. Shipping still takes 2 minutes to calculate.
5. Disable USPS completely in WooCommerce Shipping Zone settings.
6. Shipping takes 5 seconds to calculate.

Is there another hook I can use to unset shipping rates before they are calculated?

**Comment by jonathansadowski** [comment] 2020-10-22 20:57
Hi @JacksonCleary,

Thanks for taking the time to report this. The `woocommerce_package_rates` filter allows you to filter the rates after they've been calculated, so I believe that this is working as intended. I'm going to close this, but if there's any additional information you'd like to add, or something that I've missed, please feel free to reply.

**Closed by jonathansadowski** 2020-10-22 20:57 UTC
Labels: won't fix

**Comment by JacksonCleary** [comment] 2020-10-23 01:34
@jonathansadowski  Thanks for checking this out.

Is there no way to unset a shipping method before calculation?

My use case was on 200+ items ( stickers ) with weight, height, price, etc. being dynamically calculated at checkout. 
Shipping methods like UPS and USPS would calculate box shipping, taking upwards of 5 - 10 minutes, after which the shipping method would be unset. 

__

Why would a package rate be calculated and then be unset? 
Is there another way to do the opposite: unset and then calculate the remaining ones?

Thank you,
