### ISSUE TITLE
Can't remove product from "Uncategorized" category when bulk editing 

### ISSUE THREAD

**Issue by DeanForde** [woocommerce/woocommerce#29155] opened 2021-02-17 14:46 UTC
Any chance you can fix the below issue? I now have to manually uncheck 6000+ products.  

When a new product is manually created, or imported, the "uncategorized" category is tied to the product by default. When you bulk edit products, you can't remove the "uncategorized" category which is not even ticked:

### Prerequisites
 I have searched for similar issues in both open and closed tickets and cannot find a duplicate
 The issue still exists against the latest master branch of WooCommerce on Github (this is not the same version as on WordPress.org!)
 I have attempted to find the simplest possible steps to reproduce the issue
 I have included a failing test as a pull request (Optional)
Steps to reproduce the issue
Add a new product manually without setting up any category
Bulk edit the product and try to remove the uncategorized category
Expected/actual behavior
You should see the uncategorized category checked, but you won't. And checking or unchecking it makes no difference.

### Isolating the problem
 This bug happens with only WooCommerce plugin active
 This bug happens with a default WordPress theme active, or Storefront
 I can reproduce this bug consistently using the steps above

**Comment by DeanForde** [comment] 2021-02-17 15:04
current work around is to make a new default category then delete the uncategorized one then repeat.

**Comment by rrennick** [comment] 2021-02-17 19:53
> current work around is to make a new default category then delete the uncategorized one then repeat.

@DeanForde The function of the default category is to be the category assigned to products that haven't been assigned a category. If you follow your steps to reproduce with `Posts`, you will see the same behaviour/results. In WordPress, when a post type has a hierarchical taxonomy, the taxonomy is used as the primary organization for that post type. Because it's used as the primary organization WP requires that every post of that post type be assigned at least one term from that taxonomy. 

I'm closing the issue as it is core WP behaviour.

**Closed by rrennick** 2021-02-17 19:53 UTC

**Comment by DeanForde** [comment] 2021-02-17 21:57
No, even if the products are assigned to multiple categories you still
can’t batch uncheck the “uncategorised” category

**Comment by rrennick** [comment] 2021-02-18 13:00
@DeanForde Here is the screenshot of bulk editing `Posts` where you also cannot batch remove categories:

<img width="1100" alt="Screen Shot 2021-02-18 at 8 58 27 AM" src="https://user-images.githubusercontent.com/343847/108360486-aaa06100-71c7-11eb-90bb-21e719d8f9a6.png">

**Comment by ergec** [comment] 2022-04-18 05:57
As of today this problem still persists. If one or more product has no category (uncategorized), using bulk edit to assign a category doesn't remove them from "uncategorized". Each product has to be edited one by one to remove "uncategorized"
