### ISSUE TITLE
Woocommerce API no muestra todos los productos

### ISSUE THREAD

**Issue by cgsaavedrac** [woocommerce/woocommerce#19885] opened 2018-04-26 19:27 UTC
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://example.com', 
    'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 
    'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    [
        'wp_api' => true,
        'version' => 'wc/v2',
    ]
);

$productos = json_encode($woocommerce->get('products')); 
echo $productos;

this code return only 10 register. I have 54 register in wc

Any idea of the problem. What could I be doing wrong

**Comment by claudiulodro** [comment] 2018-04-26 20:57
[The default products per_page setting is 10](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products), so by default it will return up to 10 products. You can set it to `-1` to get all the products.

Closing this because it's not a bug in WooCommerce.

**Closed by claudiulodro** 2018-04-26 20:57 UTC
