### ISSUE TITLE
[3.3] Categories showing on shop page when the shouldn't be.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18674] opened 2018-01-30 21:46 UTC
Creating this as a parent issue for tracking this common reported issue. There seems to be different causes, sometimes plugins (Genesis Connect) and sometimes themes (Flatsome). Still trying to find the exact change that caused this.

While technically this the 3rd party conflict territory, it's something worth looking into to see if there is a bandaid that could be applied.

Some examples: 

- https://wordpress.org/support/topic/urgent-issues-because-of-todays-update/
- https://wordpress.org/support/topic/problem-shop-page/
- https://github.com/woocommerce/woocommerce/issues/18673

_____

If this is happening for you, please don't open a new issue or reply with just a "happening for me too". Instead, please try to find which plugin or theme is causing this to happen on your site, and let us know.

Also, double check and make sure the settings are correctly configured in the customizer: http://cld.wthms.co/1Xi59n

**Comment by nathanrice** [comment] 2018-01-30 22:21
We're looking into the conflict with Genesis Connect for WooCommerce right now in [this issue](https://github.com/copyblogger/genesis-connect-woocommerce/issues/15). If anyone finds something before we do, please feel free to let us know we'll push out a patch ASAP.

**Comment by Sanchollo** [comment] 2018-01-30 22:27
I am having this issue. I'm using the MasterStudy theme. Categories are showing on the shop page regardless of what I set in the Customizer. When I switch to the default WordPress themes, the problem is solved. Unfortunately, I can't switch permanently.

**Comment by AshleyPearceIHR** [comment] 2018-01-30 22:43
I am using the atelier theme by Swift Ideas. This problem is prominent for us. Can't get to the bottom of which plugin may be causing the issue. Will report back as and when we discover anything new. Is it possible to rollback to the previous version of the plugin in the interim?

**Comment by aeros0ul** [comment] 2018-01-30 22:56
@AshleyPearceIHR 
As a dirty fix you can use 
`ul.products li.product-category { display: none; }`
to completely hide the category display.

**Comment by Ianfwales** [comment] 2018-01-30 22:56
im using Homemarket Theme, I have the problem of category loop showing up in the shop

**Comment by Ianfwales** [comment] 2018-01-30 22:59
that would work but also my pagination is gone also, the categories where taking up the spaces of what should of been products in the shop

**Comment by mikejolley** [comment] 2018-01-30 22:59
As a temp fix you can edit your theme and remove any calls to `woocommerce_product_subcategories`. Or see if the theme has an update to resolve this already.

**Comment by Internapse** [comment] 2018-01-30 23:12
I'm actually experiencing the opposite problem with the products showing on the store landing page when I only want to show categories. The 6 categories show first, then 24 products.

Like others, when I switch to the default twentyseventeen theme, things work no problem. This lead me to the functions.php file although I don't see anything outstanding that would cause this issue.

I do have one filter to hide the empty categories although that's still working fine.

add_filter('woocommerce_product_subcategories_hide_empty', 'hide_empty_categories', 10, 1);
function hide_empty_categories($hide_empty)
{
    $hide_empty = FALSE;
    return $hide_empty;
}

I also have a filter to show the category descriptions on the store landing page, but again, this seems to be working fine.

// Add category description underneath title
function addCatDescUnderTitle($category)
{
    if(is_shop())
    {
        echo '<span class="category_description">' . $category->description . '</span>';
    }
}
add_action('woocommerce_after_subcategory_title', 'addCatDescUnderTitle', 10, 1);

I'll keep looking through the functions.php file - I'm sure the cause is around here somewhere.

**Comment by TomPichaud** [comment] 2018-01-30 23:16
@Internapse I'm having the same issue, please let me know if you find the solution !

**Comment by Internapse** [comment] 2018-01-30 23:40
@TomPichaud After reading Mike Jolley's mention of old template files causing the issue, I looked at the one basic template file I'm using in woocommerce.php.

```
<?php
// Template Name: WooCommerce
get_header();
?>
<div class="main">
	<div class="row"> 
		<div class="large-12 medium-12 small-12 columns content">
			<?php woocommerce_content(); ?>
		</div>
	</div>
</div>
<?php get_footer(); ?>
```

When I deleted this file from my server, the products were removed. However, so was all of the styling that goes along with my theme for this area.

Since there's not much there, as you can see, I looked at the woocommerce_content() function. https://docs.woocommerce.com/wc-apidocs/function-woocommerce_content.html

It seems this strategy is a bit dated, as the hooks are recommended instead. https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/

It does seem the issue will be fixed in 3.3.1 though.

**Comment by WPprodigy** [comment] 2018-01-30 23:52
Thanks for the report. If you could test the above PR from Mike, that'd be helpful.

Also, the hooks are quite easy to use, try these out instead of using woocommerce.php :) -
 https://gist.github.com/WPprodigy/35b9e401f5122fdfa73ec8afe30e015c

**Comment by brian8544** [comment] 2018-01-31 10:25
For anyone using the FlatSome theme, here's a temp fix :)

https://gist.github.com/brian8544/b0836b7b9519769b70da0cc439d8486d

**Comment by DarrellJMartin** [comment] 2018-01-31 16:15
@Internapse I had the same issue too with products appearing on the categories page and the customiser options having no effect with woocommerce version 3.3.0. My temporary workaround was to hide these products using css for example:

.post-type-archive.post-type-archive-product .has-children {
  display:none;
}

.tax-product_cat.term-[shopcategory] .has-children {
 display:none;
}

where [shopcategory] is your shop category stub name

**Comment by PBU1973** [comment] 2018-01-31 18:55
Hi there, I have also problems with categories showing on the shop page above all products. I use SShop Theme.

**Closed** 2018-01-31 19:27 UTC
Labels: Status: has-pr, Type: Bug

**Comment by demen20** [comment] 2018-02-01 11:07
Hi, I click on customize in my theme Anima of Cryout Creations, then Woocommerce --» product catalog, and I choose to use only the categories, but I see the categories and products together in homepage. Please, help me

**Comment by brian8544** [comment] 2018-02-01 11:30
They are working on a fix for this, next time make sure you have a backup of DB and www. So you can do a rollback

**Comment by rob** [comment] 2018-02-01 18:49
From the WooCommerce blog:

> "To ensure this update is stable, we’ve been doing plenty of testing and QA on our side with an extended beta period, increased unit and integration test coverage, compatibility testing with our extensions, working with customers to do managed updates, and running 3.3 on WooCommerce.com."

Strange that with all this testing and betas of 3.3 since December there weren't any reports of this issue? Looks like it's affecting a lot of people (including us), in addition to images not being cropped at all anymore, sorting dropdown just completely disappeared, etc. Gonna be a fun day fixing everything!

(Luckily, we do have backups...)

**Comment by WPprodigy** [comment] 2018-02-01 19:10
Hey @rob,

If possible, it'd be super helpful if you could test the latest branch of 3.3 on your site/staging: https://github.com/woocommerce/woocommerce/tree/release/3.3

I'm particularly interested in the `sorting dropdown just completely disappeared` part, and would like to help dig into that if it's not resolved in the branch above.

I'd be happy to help test if possible. You can email my email address on my GH profile page, and I'll open up a WooCommerce.com support ticket and we can proceed from there.

**Comment by rob** [comment] 2018-02-01 19:18
Hi @WPprodigy - thanks, I'll try the 3.3 branch within a couple of hours and let you know if anything changes.

I tried searching for the dropdown issue, but I can't see anybody else that has the same problem. Did you get reports? It DOES show up below the products, but above them there's nothing -- not even an empty HTML element. It was definitely working pre-3.3.

![screen shot 2018-02-01 at 2 16 38 pm](https://user-images.githubusercontent.com/503/35698367-d28d0ae0-075a-11e8-93c2-f292701d553b.png)

**Comment by WPprodigy** [comment] 2018-02-01 19:26
The only change in this area was this I believe: https://github.com/woocommerce/woocommerce/pull/18726/commits/5d11f660fe08e17b352079799a198c194048afc8. But that was fixing the opposite problem - sorting and such showing up when it shouldn't be when products shortcode was used.

So yea, I'm not sure why this is happening but would certainly like to help get to the bottom of it.

Let continue in email then in the support ticket I create, that way people in this thread aren't bothered :)
