### ISSUE TITLE
Missing attributes in Cart page when using ?add-to-cart URL Parameters

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/woocommerce#26337] opened 2020-04-29 19:15 UTC
**Describe the bug**
When adding a variation to the cart, the attributes of that variation is missing. In contrast, when adding that same variation using the traditional single product page method, the attributes are displayed as expected.

**To Reproduce**
1. Create a variable product
2. Craft a unique `?add-to-cart` URL to add that product directly to the cart - In my case, I used https://wc.local/?add-to-cart=208&variation_id=1073&attribute_color=Black&attribute_material=Cotton&attribute_size=17
3. Notice that on the cart page, the attributes are missing

**Screenshots**

Using `?add-to-cart` parameter:

![https://d.pr/i/bn8BHl](https://d.pr/i/bn8BHl+)
Full Image: https://d.pr/i/bn8BHl

Using traditional single product page:

![https://d.pr/i/4aREe4](https://d.pr/i/4aREe4+)
Full Image: https://d.pr/i/4aREe4

**Expected behavior**
I expected to see the variation attributes regardless of the method used to add the product to the cart.

Thanks to some additional debugging from @jessepearson, he found that when adding the variation through URL parameters, the object looks as follows on his local test site:

```
[28-Apr-2020 12:26:05 UTC] $cart_item:
[28-Apr-2020 12:26:05 UTC] Array
(
    [addons] => Array
        (
        )
    [key] => 255bc0047de77235f93a80c1db14d429
    [product_id] => 133883
    [variation_id] => 133884
    [variation] => Array
        (
        )
```

When using the traditional single product page, the object looks as follows:

```
[28-Apr-2020 12:26:05 UTC] Array
(
    [addons] => Array
        (
        )
    [key] => 135268bc8c769daa1fc183b8bcedd451
    [product_id] => 133883
    [variation_id] => 133886
    [variation] => Array
        (
            [attribute_pa_colors] => black
            [attribute_pa_size] => large
            [attribute_pa_amount] => full
        )
```

* Further discussion at: https://a8c.slack.com/archives/C0EEVN1V2/p1588074801334600
* Issue first raised at: 2924351-zen

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://wc.local
Site address (URL): https://wc.local
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 16.28MB
Database Data Size: 10.18MB
Database Index Size: 6.10MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_email_log: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.52MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 0.30MB + Index: 0.16MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.25MB + Index: 0.17MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 26
avia_framework_post: 10
follow_up_email: 2
nav_menu_item: 7
page: 16
post: 4
product: 467
product_variation: 112
revision: 29
shop_coupon: 3
shop_order: 36
shop_order_refund: 2
shop_subscription: 3
tt_font_control: 1
user_request: 1
wc_booking: 11
wc_membership_plan: 1
wc_user_membership: 2
wcpf_item: 4
wcpf_project: 1
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Plugin Toggle: by Cedaro – 1.3.1
WooCommerce: by Automattic – 4.0.1

### Inactive Plugins (91) ###

Add To Cart Redirect for WooCommerce: by Jeroen Sormani – 1.0.3 – Not tested with the active version of WooCommerce
Affiliate For WooCommerce: by StoreApps – 1.6.0
Akismet Anti-Spam: by Automattic – 4.1.4
Auctions for WooCommerce: by WPInstitut – 1.0.1
AutomateWoo: by WooCommerce – 4.9.0
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.4
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Not tested with the active version of WooCommerce
AutomateWoo - Templates: by EasyExtend – 1.0.0 – Not tested with the active version of WooCommerce
bbPress: by The bbPress Contributors – 2.6.4
Bookings Helper: by WooCommerce – 1.0.2 – Not tested with the active version of WooCommerce
Charitable: by WP Charitable – 1.6.37
Charitable Designer: by TinyGiantStudios – 1.0.0
Code Snippets: by Code Snippets Pro – 2.14.0
Customize Event Google Calendar for WooCommerce Booking: by Ivan Barreda – 1.0.1 – Not tested with the active version of WooCommerce
Debug Bar: by wordpressdotorg – 1.0
Debug Bar Cache Lookup: by Allan Collins – 0.1.1
Debug Objects: by Frank Bültge – 2.5.0
Disable Real MIME Check: by Sergey Biryukov – 1.0
Duplicate Post: by Enrico Battocchi – 3.2.4
Easy Google Fonts: by Titanium Themes – 1.4.4
Email Log: by Sudar – 2.3.2
Email Templates: by Damian Logghe – 1.3.1.2
Follow-Up Emails: by WooCommerce – 4.8.31
GD Library Check: by Riaan Knoetze – 1.0
GDPR Cookie Consent: by WebToffee – 1.8.7
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Hello Dolly: by Matt Mullenweg – 1.7.2
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.1
Loco Translate: by Tim Whitlock – 2.3.3
Mailchimp for WooCommerce: by Mailchimp – 2.3.6
Matty Theme QuickSwitch: by Matty – 1.2.3
One Click Demo Import: by ProteusThemes – 2.5.2
Product FAQs: by 99w – 1.0.1 – Not tested with the active version of WooCommerce
Say What?: by Lee Willis – 1.9.4
Show Current Template: by JOTAKI Taisuke – 0.3.3
Sticky Cart For WooCommerce: by SkroTron – 1.1.1
Storefront - Lefthand Account Tabs: by Riaan K. | WooCommerce – 1.0
Storefront Horizontal Tabs: by Riaan K. | WooCommerce – 1.0 – Not tested with the active version of WooCommerce
Storefront Powerpack: by WooCommerce – 1.5.0
Templates Pro for AutomateWoo: by EasyExtend – 1.0
Term Duplicator: by CGD Inc. – 1.0.0
Testimonials: by WooThemes – 1.5.4
Theme Customisations: by WooThemes – 1.0.0
User Role Editor: by Vladimir Garagulya – 4.53.1
User Switching: by John Blackbourn & contributors – 1.5.4
Walmart Integration for WooCommerce: by CedCommerce – 2.0.0 – Not tested with the active version of WooCommerce
WC Custom Add to Cart labels: by Rynaldo Stoltz – 1.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.34 – 4.1.36 is available
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.15
WooCommerce Admin: by WooCommerce – 1.0.3
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.13.3
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.9
WooCommerce Blocks: by Automattic – 2.5.15
WooCommerce Bookings: by WooCommerce – 1.15.16
WooCommerce Bookings Filters: by Codup – 1.1.3.13 – Not tested with the active version of WooCommerce
WooCommerce Box Office: by WooCommerce – 1.1.22
WooCommerce Chained Products: by StoreApps – 2.9.6
WooCommerce Composite Products: by SomewhereWarm – 6.2.2
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.7.6
WooCommerce Deposits: by WooCommerce – 1.4.20
Woocommerce Email Admin On Completed Order: by Özgür Özdemir – 0.1 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by WooCommerce – 1.1.14
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.24
WooCommerce Force Sells: by WooCommerce – 1.1.22
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.20
WooCommerce List Products By Category Widget: by Andrew Rapps – 1.2.2 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.17.3
WooCommerce Memberships: by SkyVerge – 1.17.2
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.15
WooCommerce Order Delivery: by WooCommerce – 1.6.6
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.21
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.3.9
WooCommerce PDF Product Vouchers: by SkyVerge – 3.7.5
WooCommerce Photography: by WooCommerce – 1.0.22
WooCommerce POS: by kilbot – 0.4.24 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.31
WooCommerce Product Bundles: by SomewhereWarm – 6.2.2
WooCommerce Product Vendors: by WooCommerce – 2.1.30
WooCommerce Regions Pack: by TinyGiantStudios – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.8
WooCommerce Smart Coupons: by StoreApps – 4.7.2
WooCommerce Square: by WooCommerce – 2.1.1 – 2.1.2 is available
WooCommerce Stripe Gateway: by WooCommerce – 4.3.3
WooCommerce Subscriptions: by WooCommerce – 3.0.3
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.25
WooCommerce Zapier: by OM4 – 2.0.3
WooSidebars: by WooCommerce – 1.4.5
WP Crontrol: by John Blackbourn & crontributors – 1.8.0
WPML Multilingual CMS: by OnTheGoSystems – 4.0.7
WP Notification Center: by Never5 – 1.0.1
Yoast SEO: by Team Yoast – 13.5

### Must Use Plugins (1) ###

Local by Flywheel Live Link Helper: by Flywheel – 1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 123
Oldest: 2020-04-20 08:22:29 +0000
Newest: 2020-04-29 19:12:27 +0000

Pending: 4
Oldest: 2020-04-29 19:12:47 +0000
Newest: 2020-04-30 19:12:27 +0000

Failed: 1
Oldest: 2020-04-20 08:21:04 +0000
Newest: 2020-04-20 08:21:04 +0000

`
```
</details>

**Comment by claudiosanches** [comment] 2020-04-29 20:21
Duplicate of #24000

**Closed by claudiosanches** 2020-04-29 20:21 UTC
