### ISSUE TITLE
Order Created Date is changed when pressing Update button

### ISSUE THREAD

**Issue by harryph105** [woocommerce/woocommerce#27649] opened 2020-09-10 21:43 UTC
I usually have to change information of an order: status, add product items, add note…
The problem is
Whenever I press Update button of an order, the Order Date will be plus by some hours
For example, when I create a new order, the Order date is September 10 2020 but when I update this order, the created date is September 11 2020 14:17
You can see the screenshot https://prnt.sc/uf6mgi
When I press update once more time, the created date changes to September 12 2020 Screenshot: https://prnt.sc/uf6ocm

I have also done a research like the closed topic Date column on shop_order is wrong and follow the guide (UTC time). However, there is nothing happened.

It is a big problem because it affects to the revenue report. Please help me

**Comment by juliaamosova** [comment] 2020-09-11 18:53
Hi @harryph105,

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. 

I have an order that was placed on my test site earlier today. I updated it by adding a note but the `Date created` time didn't change - please see gif below:

![](http://g.recordit.co/uULC0DGaPL.gif)

I tested using the WooCommerce 4.5.1 version. Can you please specify what version of WooCommerce are ou testing with?

In addition to that, can you please confirm if you performed theme and plugins conflict on your site?

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-09-21 21:22
Hi @harryph105,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-09-21 21:22 UTC
Labels: can't reproduce, status: needs feedback
