### ISSUE TITLE
[Accessibility] select2 + tabindexes

### ISSUE THREAD

**Issue by jaygidwitz** [woocommerce/woocommerce#14317] opened 2017-04-12 19:30 UTC
### EXPLANATION OF THE ISSUE

WooCommerce 3.0.1, With the TwentySeventeen theme. Tested on Chome (Latest) for on Mac.

On the checkout page there are a few issues when typing and tabbing through the form.

1. If you tab to the country or state dropdown + press return, accidentally, see that the correct country or state is already selected, and then press return again to continue, and then press tab again.
    - The skip links are then triggered and you are back up at the top of the page rather than just continuing to tab from where you were.
    - I would expect to simply continue tabbing on down the form from where I was.

2. If you continue through the checkout, after entering your email address, when you press tab, it does not go to the “create account” box, but rather the place order box.
    - I would expect it to go to the "create account" box

### STEPS TO REPRODUCE THE ISSUE

1. User is not logged in
1. Add product to cart.
2. Proceed to checkout.
3. Enter info, and tab through
4. when arriving at the country dropdown press return, see that the correct country is already selected, and then press return again to continue, and then press tab again.
5. The skiplinks will be triggered. Now proceed.
6. when arriving at the state dropdown repeat step 4.
6. Fill out the rest of the info, tabbing though.
7. Attempt to tab the the create an account checkbox, and press enter.
8. If this replicates, the payment will be processed rather than the account tab being checked.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://test.studiopress.com/twentyseventeen
Site URL: http://test.studiopress.com/twentyseventeen
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.9
PHP Version: ❌ 5.5.9-1ubuntu4.21 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 12 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_221_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

WooCommerce: by Automattic – 3.0.1
Genesis eNews Extended: by Brandon Kraft – 2.0.2
Akismet Anti-Spam: by Automattic – 3.3
Gravity Forms: by rocketgenius – 2.2.1.2
Genesis Beta Tester: by Nathan Rice – 0.9.3
Soliloquy: by Soliloquy Team – 2.5.3.1
Simple Social Icons: by Nathan Rice – 2.0.1
SSL Insecure Content Fixer: by WebAware – 2.2.3
Quick Cache: by s2Member® / WebSharks
Inc. – 150129.3


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment] 2017-04-20 11:18
Additionally we need to look at select2 accessibility and screen readers.

**Comment by claudiulodro** [comment] 2017-06-12 22:03
The country tabbing problem appears to be caused by select2. 

When it opens up the search dropdown it creates a new, temporary input field at the very end of the DOM and focuses on it. If you select a country, select2 focuses you back to the original input in the middle of the DOM. If you don't select a country and just hit Enter, it doesn't update your focus. Since the last-focused element was at the bottom of the DOM, the next time you hit Tab you will be back at the top.

<img width="632" alt="screen shot 2017-06-12 at 2 50 07 pm" src="https://user-images.githubusercontent.com/7317227/27057051-47c34f5c-4f7f-11e7-9137-95682dede4f2.png">

There does appear to be [a script](https://stackoverflow.com/questions/30630964/select2-v4-unable-to-tab-into-press-enter-and-then-select-with-firefox-aka-m/39605870#39605870) to fix this problem, but it might be wiser to wait and fix it when we fix all the other select2 problems. 

I haven't thoroughly investigated the second problem, but that one should be fix-able.

**Comment by mikejolley** [comment] 2017-06-13 09:42
@claudiulodro Sounds like a plan. Let's move this out of this sprint and tackle once we've discussed that project some more.

**Comment by claudiulodro** [comment] 2017-06-27 18:52
@jaygidwitz 
1. This problem has an open PR [here](https://github.com/woocommerce/woocommerce/pull/15792) and will be resolved in a near-future release.
2. This was [a minor UI issue in the 2017 theme](https://github.com/woocommerce/woocommerce/issues/15824) and will also be resolved in a near-future release.

I also feel I should note, that [the spacebar is used for checking checkboxes in forms](http://webaim.org/techniques/keyboard/).

**Closed** 2017-07-06 18:28 UTC
Labels: Focus: UI, Status: has-pr, Type: Enhancement

**Comment by mikejolley** [comment] 2017-07-14 12:57
![](https://github.trello.services/images/mini-trello-icon.png) [SelectWoo](https://trello.com/c/3U62HhNF/100-selectwoo)
