### ISSUE TITLE
WooCommerce No variant information in Order problem

### ISSUE THREAD

**Issue by rctneil** [woocommerce/woocommerce#30235] opened 2021-07-08 09:23 UTC
Hi,

We have a client who is experiencing a very strange issue with their WooCommerce site.

They have a wide variety of products that have variants.   Every now and again, an order comes in with an item that has variants selected but the variations do not show on the order information page. This is causing embarrassment and frustration for our client as they have to contact the customer to ask what variants they selected.

You can see this in the image below. This item did have some variant options selected but on the order information page, they do not show. Only the SKU shows up.   SKU’s are set on the Product and each variant.

![Screenshot 2021-07-06 at 14 12 22](https://user-images.githubusercontent.com/774459/124897750-80b0d500-dfd6-11eb-9b99-7b5f3fa1b67d.png)

We have seen a number of similar issues on GitHub the in the screenshots others have posted they all seem to show a Variation ID, but this one doesn’t.

We are experiencing major difficulties in tracking down a reliable way of making this happen or figuring out what is causing it.

Can anyone suggest any potential causes and/or possible solutions?

Thanks,
Neil

**Comment by juliaamosova** [comment] 2021-07-09 17:43
Hi @rctneil,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-07-09 17:43 UTC
