### ISSUE TITLE
WooCommerce API gives 401 in Google App Engine but works (200 OK) in local env

### ISSUE THREAD

**Issue by rajananusha** [woocommerce/woocommerce#18030] opened 2017-12-05 19:08 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I’m writing an app that allows users to integrate their WooCommerce stores with my site. I’m using the [Python wrapper for the WooCommerce REST API](https://pypi.python.org/pypi/WooCommerce) and my app is hosted on Google App Engine. Here’s my code to call the Woocommerce API. (I’m using https to connect to all the WooCommerce stores)

     def request_woo_api(self, user, request_url):
            wcapi = API(
                url=user.woo_url,
                consumer_key=user.woo_consumer_key,
                consumer_secret=user.woo_consumer_secret,
                wp_api=True,
                version="wc/v2",
                query_string_auth=True
                )
            resp = wcapi.get(request_url).json()
            return resp

I get a 200 OK response when I test my code on my dev machine. But when I deploy my code to Google App Engine I get a 401 response for **some** WooCommerce stores.

    {u'message': u'Sorry, you cannot list resources.', u'code': u'woocommerce_rest_cannot_view', u'data': {u'status': 401}}

I read [here](https://cloud.google.com/appengine/docs/standard/python/outbound-requests) in this documentation that Google App Engine appends a value (`AppEngine-Google; (http://code.google.com/appengine; appid: <application_id>)`) to the `user-agent` header for all outbound requests. And I think this is the problem because I tried calling a woocommerce api from my local machine and it worked, but when I appended this value to my header the same endpoint gave the 401 error.

    >>> headers = {'User-Agent': 'WooCommerce API Client-Python/1.2.1'} 
    >>> result = requests.get(url, headers=headers) 
    >>> print result.json() 
    [{u'date_completed_gmt': None, u'date_modified_gmt': u'2017-11-30T18:13:59', u'payment_method': u'.......
    >>> headers = {'User-Agent': 'WooCommerce API Client-Python/1.2.1; AppEngine-Google; (http://code.google.com/appengine; appid: 123)'} 
    >>> result = requests.get(url, headers=headers) 
    >>> print result.json() 
    {u'message': u'Sorry, you cannot list resources.', u'code': u'woocommerce_rest_cannot_view', u'data': {u'status': 401}}

The fact that this happens only for a couple of WooCommerce sites and not the others makes me think that these users might have a WooCommerce setting/plugin extension/security setting that is causing this isssue. Any idea why this is? Is there any way turn off a plugin or setting that prevents the WooCoomerce store from filtering requests based on the `user-agent` value? (I can request the users to change the security settings to their site)

Upon further investigation I found that the WooCommerce store server ignores the query string parameters.  
I'm able to get a response if I don’t send the “query_string_auth=true” setting. But the store ignores ALL query parameters. The query_string_auth parameter sends the consumer_key and secret in a query string. When I remove it, it goes as a auth header. Now that I'm sending it as a auth header it responds. But it ignores query parameters. My guess is that the server ignores ALL query parameters. That explains why I was getting the 401 in the first place. (Because we sent the key and secret as a query parameter). And this only happens when I send the "User-Agent: AppEngine-Google;"

Example:

    store_url = "https://teststore.com"
    endpoint = "/wp-json/wc/v2/orders?per_page=1"
    auth = ("ck_xxxxxxxxxxx", "cs_xxxxxxxxxxx")
    headers = {'Content-Type': 'application/json', 'User-Agent': 'WooCommerce API Client-Python/1.2.1'}
    url = '{}/{}'.format(store_url, endpoint)
    response = requests.get(url, auth=auth, headers=headers)
    print response.json()
This returns exactly one order.

    store_url = "https://teststore.com"
    endpoint = "/wp-json/wc/v2/orders?per_page=1"
    auth = ("ck_xxxxxxxxxxx", "cs_xxxxxxxxxxx")
    headers = {'Content-Type': 'application/json', 'User-Agent': 'WooCommerce API Client-Python/1.2.1; AppEngine-Google; (+http://code.google.com/appengine; appid: 123)'}
    url = '{}/{}'.format(store_url, endpoint)
    response = requests.get(url, auth=auth, headers=headers)
    print response.json()
^ This returns 10 orders (default page size is 10)

But I still have no idea why some stores do this or how to fix this.

Please help.

( I have already tried the following and it hasn't helped:

- Tried using [requests](http://docs.python-requests.org/en/master/) instead of [Python wrapper for the WooCommerce REST API](https://pypi.python.org/pypi/WooCommerce) and I get the same behaviour; works in local env but returns the 401 error on GAE.
- Added the `query_string_auth=True` and also tried adding `verify_ssl=False` (just in case the users were using a self-signed test site)
- Tried adding a `_method=GET` query parameter as suggested [here](https://github.com/woocommerce/woocommerce/issues/15404)
- Tried setting the `content-type` to "application/text" as suggested [here](https://stackoverflow.com/questions/42186757/woocommerce-woocommerce-rest-cannot-view-status-401) )

## Expected/actual behavior

When I follow those steps, I see...

    store_url = "https://teststore.com"
    endpoint = "/wp-json/wc/v2/orders?per_page=1"
    auth = ("ck_xxxxxxxxxxx", "cs_xxxxxxxxxxx")
    headers = {'Content-Type': 'application/json', 'User-Agent': 'WooCommerce API Client-Python/1.2.1; AppEngine-Google; (+http://code.google.com/appengine; appid: 123)'}
    url = '{}/{}'.format(store_url, endpoint)
    response = requests.get(url, auth=auth, headers=headers)
    print response.json()

This returns 10 orders.

I was expecting to see...
The above code should return 1 order.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

It only happens when I send the "User-Agent: AppEngine-Google;" header with my request and it only happens with a few WooCommerce Stores. Not with all stores. The Wordpress Environment given below is for one of the stores that's failing

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://trueshipsupply.com
Site URL: https://trueshipsupply.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10
PHP Post Max Size: 200 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Constant Contact Forms for WordPress: by Constant Contact – 1.2.5
Contact Form 7: by Takayuki Miyoshi – 4.8
Mailgun Email Validator: by Jesin – 1.2.3
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

TrueShip Boxes+Labels: by OppositeMind Technologies – 1.0.0
WooCommerce Automatic Download: by Tahir Yasin – 1.1
WooCommerce Bulk Pricing: by WP Lab – 1.9.1
WooCommerce Constant Contact: by SkyVerge – 1.8.0
WooCommerce Dropshipping: by WooCommerce – 1.1.2 – 1.2.1 is available
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.6.3 – 2.7.1 is available
WooCommerce Loyalty Rewards: by IgniteWoo.com – 4.1.1
WooCommerce PDF Invoices: by Andrew Benbow – 3.7.4 – 4.0.1 is available
WooCommerce Product Bundles: by SomewhereWarm – 5.4.0 – 5.6.1 is available
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.2 – 1.11.3 is available
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8
WooCommerce UPS Shipping: by WooCommerce – 3.2.4 – 3.2.6 is available
WooCommerce - Show order IDs: by Remi Corson – 1.0
WooCommerce Subscriptions: by Prospress Inc. – 2.2.9 – 2.2.15 is available
WooCommerce: by Automattic – 3.1.1 – 3.2.5 is available
WordPress Importer: by wordpressdotorg – 0.6.3
WP exec PHP: by Tom Thorogood – 2.0.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #63 - /shop/
Cart: #62 - /cart/
Checkout: #61 - /checkout/
My account: #60 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.1.6
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off
```
</details>

**Comment by claudiosanches** [comment] 2017-12-05 19:43
> The fact that this happens only for a couple of WooCommerce sites and not the others makes me think that these users might have a WooCommerce setting/plugin extension/security setting that is causing this isssue. Any idea why this is? Is there any way turn off a plugin or setting that prevents the WooCoomerce store from filtering requests based on the user-agent value? (I can request the users to change the security settings to their site)

Yeah, I agree about it, but there is no way to prevent or disable 3rd party plugins, better you found about that plugin and recommend your users to avoid using it.
And note that this kind of plugin should influence in all WordPress REST API, and not only WooCommerce endpoints.

Sadly there is nothing that we can do to improve it on WooCommerce side, even more that may or not be caused by a 3rd party plugin (if auto deactivating or blocking such plugin could be possible as you suggested), can even be something setting on ModSecurity, CloudFlare or however.

Closing since is not an issue on WooCommerce core, but please, let me know if you can find what plugin is causing it or if this come from some other software or weird server configuration.

**Closed by claudiosanches** 2017-12-05 19:43 UTC

**Comment by rajananusha** [comment] 2017-12-12 01:10
It was a WP Engine setting that was causing the problem. My app is hosted on Google App Engine and it adds a header value “AppEngine-Google; (+http://code.google.com/appengine; appid:<id)>” to the User-Agent header in ALL requests. WP Engine redirects requests from bots to a cached version of the page. It detects bots by parsing the User-Agent header. When it finds 'Google' in the value, it assumes that it is a Googlebot and redirects it to a cached page. And so, it ends up ignoring all the query parameters in the URL (credentials, filter parameters etc).
I simply contacted WP-Engine support and asked them to turn off the user-agent-based bot filter (It is turned on by default) for one of my test WooCommerce sites and it worked!
