### ISSUE TITLE
When creating a product with variation it is returning as simple.

### ISSUE THREAD

**Issue by erickvolles** [woocommerce/woocommerce#29390] opened 2021-03-15 19:24 UTC
I am integrating via the integration manual but when I send you to create a product with variation, it is returning but it is not registering with the variations. He is registering as a simple product.
shipping example:
https://lamagiebrand.com.br/wp-json/wc/v3/products/batch

shipping
{"create":[{"name":"MORMAII CALCA MOLETOM PLUS 65019","type":"variable","description":"","sku":"32121437","regular_price":"129.9","manage_stock":false,"stock_quantity":0,"stock_status":"instock","weight":"0","dimensions": {"length":"0","width":"0","height":"0"},"categories":[{"id":40}],"attributes": [{"id": 0,"name": "Cor","position": 0,"visible": true,"variation": true,"options": ["Sortido"]},{"id": 0,"name": "Tamanho","position": 0,"visible": true,"variation": true,"options": ["G1","G2","G3"]}]}]}

return
{"create":[{"id":271,"name":"MORMAII CALCA MOLETOM PLUS 65019","slug":"mormaii-calca-moletom-plus-65019","permalink":"https:\/\/lamagiebrand.com.br\/produto\/mormaii-calca-moletom-plus-65019\/","date_created":"2021-02-25T09:38:25","date_created_gmt":"2021-02-25T12:38:25","date_modified":"2021-02-25T09:38:25","date_modified_gmt":"2021-02-25T12:38:25","type":"variable","status":"publish","featured":false,"catalog_visibility":"visible","description":"","short_description":"","sku":"32121437","price":"","regular_price":"","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"purchasable":false,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"backorders":"no","backorders_allowed":false,"backordered":false,"sold_individually":false,"weight":"0","dimensions":{"length":"0","width":"0","height":"0"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0","rating_count":0,"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":40,"name":"Cal\u00e7as","slug":"calcas"}],"tags":[],"images":[],"attributes":[{"id":0,"name":"Cor","position":0,"visible":true,"variation":true,"options":["Sortido"]},{"id":0,"name":"Tamanho","position":0,"visible":true,"variation":true,"options":["G1","G2","G3"]}],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"price_html":"","related_ids":[267],"meta_data":[],"stock_status":"outofstock","_links":{"self":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271"}],"collection":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products"}]}}]}

variations

link
https://lamagiebrand.com.br/wp-json/wc/v3/products/271/variations/batch

shipping
{"create": [{"regular_price" :"129.9","attributes": [{"name": "Cor","option": "Sortido"},{"name": "Tamanho","option": "G1"}]},{"regular_price" :"129.9","attributes": [{"name": "Cor","option": "Sortido"},{"name": "Tamanho","option": "G2"}]},{"regular_price" :"129.9","attributes": [{"name": "Cor","option": "Sortido"},{"name": "Tamanho","option": "G3"}]}]}

return
{"create":[{"id":272,"date_created":"2021-02-25T09:41:07","date_created_gmt":"2021-02-25T12:41:07","date_modified":"2021-02-25T09:41:07","date_modified_gmt":"2021-02-25T12:41:07","description":"","permalink":"https:\/\/lamagiebrand.com.br\/produto\/mormaii-calca-moletom-plus-65019\/?attribute_cor=Sortido&attribute_tamanho=G1","sku":"32121437","price":"129.9","regular_price":"129.9","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"status":"publish","purchasable":true,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"stock_status":"instock","backorders":"no","backorders_allowed":false,"backordered":false,"weight":"0","dimensions":{"length":"0","width":"0","height":"0"},"shipping_class":"","shipping_class_id":0,"image":null,"attributes":[{"id":0,"name":"Cor","option":"Sortido"},{"id":0,"name":"Tamanho","option":"G1"}],"menu_order":0,"meta_data":[],"_links":{"self":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271\/variations\/272"}],"collection":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271\/variations"}],"up":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271"}]}},{"id":273,"date_created":"2021-02-25T09:41:09","date_created_gmt":"2021-02-25T12:41:09","date_modified":"2021-02-25T09:41:09","date_modified_gmt":"2021-02-25T12:41:09","description":"","permalink":"https:\/\/lamagiebrand.com.br\/produto\/mormaii-calca-moletom-plus-65019\/?attribute_cor=Sortido&attribute_tamanho=G2","sku":"32121437","price":"129.9","regular_price":"129.9","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"status":"publish","purchasable":true,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"stock_status":"instock","backorders":"no","backorders_allowed":false,"backordered":false,"weight":"0","dimensions":{"length":"0","width":"0","height":"0"},"shipping_class":"","shipping_class_id":0,"image":null,"attributes":[{"id":0,"name":"Cor","option":"Sortido"},{"id":0,"name":"Tamanho","option":"G2"}],"menu_order":0,"meta_data":[],"_links":{"self":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271\/variations\/273"}],"collection":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271\/variations"}],"up":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271"}]}},{"id":274,"date_created":"2021-02-25T09:41:10","date_created_gmt":"2021-02-25T12:41:10","date_modified":"2021-02-25T09:41:10","date_modified_gmt":"2021-02-25T12:41:10","description":"","permalink":"https:\/\/lamagiebrand.com.br\/produto\/mormaii-calca-moletom-plus-65019\/?attribute_cor=Sortido&attribute_tamanho=G3","sku":"32121437","price":"129.9","regular_price":"129.9","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"status":"publish","purchasable":true,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"stock_status":"instock","backorders":"no","backorders_allowed":false,"backordered":false,"weight":"0","dimensions":{"length":"0","width":"0","height":"0"},"shipping_class":"","shipping_class_id":0,"image":null,"attributes":[{"id":0,"name":"Cor","option":"Sortido"},{"id":0,"name":"Tamanho","option":"G3"}],"menu_order":0,"meta_data":[],"_links":{"self":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271\/variations\/274"}],"collection":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271\/variations"}],"up":[{"href":"https:\/\/lamagiebrand.com.br\/wp-json\/wc\/v3\/products\/271"}]}}]}

**Comment by ObliviousHarmony** [comment] 2021-03-29 19:39
Hi {username},

Thank you for raising the issue. However, I can’t reproduce it on my end.

We tested with the same API queries you've presented in this issue and everything worked as expected.

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Closed by ObliviousHarmony** 2021-03-29 19:39 UTC
Labels: category: wc rest api, needs developer feedback
