### ISSUE TITLE
wc_update_cart() helper function

### ISSUE THREAD

**Issue by rogervila** [woocommerce/woocommerce#29110] opened 2021-02-11 22:34 UTC
**Is your feature request related to a problem? Please describe.**
I cannot update the Cart from my custom PHP functions.

**Describe the solution you'd like**
I would like to call `WC_Form_Handler::update_cart_action()` from my custom functions.
A `wc_update_cart()` helper function would fit perfectly

**Describe alternatives you've considered**
I have not found any other solution, as explained [here](https://wordpress.stackexchange.com/questions/383232/how-to-call-woocommerce-update-cart-function-programatically)

**Comment by tammullen** [comment] 2021-02-12 13:30
Hi @rogervila 


While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-02-12 13:30 UTC
