### ISSUE TITLE
Use correct "state" label when defined at the country level instead of "State / Count/

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#18748] opened 2018-02-01 13:24 UTC
## Steps to reproduce the issue
1. Go to an order edit screen
2. Edit the billing or shipping address
3. Chose "Spain" or any other country that has specific state label defined at class-wc-countries.php

## Expected/actual behavior
When I follow those steps, I see the state label as "State / County"
I was expecting to see the country-specific label set at class-wc-countries.php
For example, for Spain it would be "Province".

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment] 2018-02-01 13:39
That localisation script is only applied for checkout. In the backend, it just uses standard/normalised names everywhere thoughout. Not a bug, but this would be an enhancement.

Nice idea but I think we should leave this for future redesigns where this and the rest of the order panel can be looked at together. There are other places such as shipping which use the same 'state/county' terminology. This would be translated based on the admin locale.

Marking as idea to revisit in the future.

Thanks

**Closed by mikejolley** 2018-02-01 13:39 UTC
Labels: Ideas, Type: Enhancement

**Comment by webdados** [comment] 2018-02-01 13:59
Roger that!
