### ISSUE TITLE
Many "Internal Server Error" responses when batching requests

### ISSUE THREAD

**Issue by wcdevadjustit** [woocommerce/woocommerce#24560] opened 2019-09-03 06:04 UTC
This is my first time posting here, so please bear with me if I've made some mistakes with regards to the format to use when posting what's going on.

**Describe the issue**
Seemingly at random we get an 'Internal Server Error' back from the REST API when we are trying to batch create/update items. It doesn't really matter which endpoint we try to use, but obviously it happens most often with the products and customers endpoints, because for those endpoints we end up with the largest requests. Especially when a lot of attribute (values) or meta data values are included.

Basically, it goes like this. 

In the last test I've disabled all the plugins we've build ourselves and even then I receive the 'Internal Server Error' issue from time to time. I started with a batch size (for products) of 100 and some did complete, but most of them gave me the 'Internal Server Error' issue. When I lowered the batch size to 50 every request did complete just fine. 

But in the past I've had occasions that some requests with a batch size of 100 did complete just fine and every request with a batch size of 10 keep coming back with the 'Internal Server Error' issue.

Any ideas on what the issue/problem could be? Is the server busy? Are the requests too large? Is it a bit of both?

**Expected behavior**
To get a complete response back, no matter what batch size is used. This may be a "success" response or a "error" response and in very minimal cases a "Internal Server Error" response.

**WordPress environment**
`
### WordPress Environment ###

WordPress address (URL): ###
Site address (URL): ###
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.22
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
Total Database Size: 117.51MB
Database Data Size: 73.41MB
Database Index Size: 44.10MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_adjust_it_email_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_adjust_it_log: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_adjust_it_offerte_aanvragen: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_adjust_it_offerte_producten: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_adjust_it_prijsafspraken: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_adjust_it_staffels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_adjust_it_user_identities: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_ait_offerte_aanvragen: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ait_offerte_aanvragen_producten: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ait_offerte_email_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.43MB + Index: 0.38MB + Engine MyISAM
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 4.52MB + Index: 6.89MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 5.52MB + Index: 2.52MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 1.52MB + Index: 3.97MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 12.07MB + Index: 1.02MB + Engine MyISAM
wp_postmeta: Data: 27.88MB + Index: 20.53MB + Engine MyISAM
wp_posts: Data: 6.61MB + Index: 1.96MB + Engine MyISAM
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.01MB + Index: 0.04MB + Engine MyISAM
wp_term_relationships: Data: 0.86MB + Index: 1.95MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 3.13MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Query Monitor: by John Blackbourn – 3.3.7
WPML Multilingual CMS: by OnTheGoSystems – 4.2.5
Checkout Address Sugessions for WooCommerce: by Raman – 1.2.9 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 7.6
Limit Login Attempts Reloaded: by WPChef – 2.9.0
Quantities and Units for WooCommerce: by Nicholas Verwymeren – 1.0.13 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.18.0
WooCommerce Multilingual: by OnTheGoSystems – 4.6.5 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0
Wordfence Security: by Wordfence – 7.4.0
WP Mail Logging: by Christian Zöller – 1.9.1
WP Super Cache: by Automattic – 1.7.0
WPML String Translation: by OnTheGoSystems – 2.10.3
WPML Translation Management: by OnTheGoSystems – 2.8.4

### Inactive Plugins (7) ###

ADJUST-IT | Core: by ADJUST-IT B.V. – 1.1.2
ADJUST-IT | Essentials: by ADJUST-IT B.V. – 1.1.3
ADJUST-IT | King Producten en Prijzen: by ADJUST-IT B.V. – 2.6.0
ADJUST-IT | King Velden en Metadata: by ADJUST-IT B.V. – 1.1.1
ADJUST-IT | Product Offertes: by Koert Lichtendonk – 2.0 – Not tested with the active version of WooCommerce
Checkout Address AutoFill For WooCommerce: by zetamatic – 0.7 – Not tested with the active version of WooCommerce
WP Mail SMTP: by WPForms – 1.6.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,331
Oldest: 2019-08-03 08:05:10 +0200
Newest: 2019-09-03 07:18:14 +0200

Pending: 3
Oldest: 2019-09-03 08:18:14 +0200
Newest: 2019-09-05 11:14:59 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by kloon** [comment] 2019-09-03 07:15
Could you please post a copy of the PHP error when the internal server error happens? This way we can see what is causing the issue for you.

**Comment by wcdevadjustit** [comment] 2019-09-03 07:25
If you can tell me where to find those logs, sure. At WooCommerce->Status I do have a tab called 'Logs' but those include only fatal errors and are all order than when I tested with batching yesterday.

**Comment by kloon** [comment] 2019-09-03 07:26
Your hosting provide should be able to assist with the location of the logs as they differ from host.

**Comment by wcdevadjustit** [comment] 2019-09-03 09:52
I've included the error log file of the latest sync. It's got a whole lot of errors. I hope you can make something of it.

[error log last sync.zip](https://github.com/woocommerce/woocommerce/files/3568910/error.log.last.sync.zip)

**Comment by kloon** [comment] 2019-09-03 09:58
Thanks, quick look there is just one error in the log that is repeated numerous times and it seems to be caused by a plugin Quantities and Units for WooCommerce. I suggest you disable that plugin and test again, unfortunately that is all I am able to tell from the error log.

Closing this issue now as from my investigation the issue is with a plugin and not WooCommerce. In the future, I suggest you first test with **all** plugins disabled except WooCommerce and your theme switched to a default one like Storefront or Twentynineteen before opening an issues.

**Closed by kloon** 2019-09-03 09:58 UTC
Labels: status: needs feedback
