### ISSUE TITLE
Can't change the editor color

### ISSUE THREAD

**Issue by devism** [woocommerce/woocommerce#26441] opened 2020-05-09 20:47 UTC
This is causing an issue now when we try to do any normal posts. Any way to revert this or make the editor background color back to default? 
![Screen Shot 2020-05-08 at 12 26 25 PM](https://user-images.githubusercontent.com/6060748/81442010-a4089780-9127-11ea-824e-83f7b1cf9a26.png)

_Originally posted by @devism in https://github.com/woocommerce/storefront/pull/1317#issuecomment-625980218_

**Comment by haszari** [comment] 2020-05-10 20:21
Hi @devism  - thanks for reaching out. 

From your [comment](https://github.com/woocommerce/storefront/pull/1317#issuecomment-626232927) I see you are using Elementor in combination with Storefront. 

Based on that, I think this is a compatibility issue that should be reported to Elementor. If you still have an issue without Elementor active, please let us know.

**Comment by haszari** [comment] 2020-05-10 20:26
@devism – I missed that this issue is reported against WooCommerce plugin rather than Storefront theme (where you originally raised in a PR comment). 

I'm closing this for now, as the issue isn't relevant to WooCommerce core. 

If you see this issue when using WooCommerce + Storefront only (no Elementor active), please log an issue in the [Storefront repository](https://github.com/woocommerce/storefront/issues/new/choose).

If you can only reproduce this issue when Storefront and Elementor are both active, I'd suggest reaching out to Elementor support or reporting an issue as a next step.

**Closed by haszari** 2020-05-10 20:26 UTC
