### ISSUE TITLE
Warning: Cookie paths cannot contain any of the following

### ISSUE THREAD

**Issue by rafamem** [woocommerce/woocommerce#25353] opened 2020-01-03 15:33 UTC
Please, I need help...

**In th website:** 

Warning: Cookie paths cannot contain any of the following ',; \t\r\n\013\014' in /home/mywebsite/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 889

**In the wp-admin:**

Warning: Cookie paths cannot contain any of the following ',; \t\r\n\013\014' in /home/mywebsite/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 889

Warning: Cannot modify header information - headers already sent by (output started at /home/mywebsite/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:889) in /home/mywebsite/public_html/wp-includes/pluggable.php on line 1265

Warning: Cannot modify header information - headers already sent by (output started at /home/mywebsite/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:889) in /home/mywebsite/public_html/wp-includes/pluggable.php on line 1268

**Comment by tammullen** [comment] 2020-01-09 18:11
Hi @rafamem,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

[Review WooCommerce Self-Service Guide](https://href.li/?https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://href.li/?https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://href.li/?https://wordpress.org/support/plugin/woocommerce/)
If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-01-09 18:11 UTC
