### ISSUE TITLE
Shipping tax rounding is incorrect when product prices are entered inclusive of tax

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce#26654] opened 2020-06-01 12:51 UTC
**Describe the bug**
Even though shipping prices are normally entered exclusive of tax, making product prices tax-inclusive causes a problem with shipping tax rounding. This problem doesn't happen when product prices are entered exclusive of tax.

**To Reproduce**
1. Set up a flat shipping rate of $75.10
2. Create a standard tax rate of 25%.
3. In **WooCommerce > Settings > Tax**, make product prices display **exclusive of tax**:

![Screenshot](https://d.pr/i/yUHzUU+)
Screenshot: https://d.pr/i/yUHzUU

4. Add a free product to cart and observe tax on shipping is rounded to $18.78 (which is the correct rounding of $75.10 * 25% = $18.775):

![Screenshot](https://d.pr/i/O6ViUE+)
Screenshot: https://d.pr/i/O6ViUE

5. Change tax display to prices **inclusive of tax**:

![Screenshot](https://d.pr/i/K7vxZR+)
Screenshot: https://d.pr/i/K7vxZR

6. Observe the tax amount is rounded now to $18.77, which is incorrect:

![Screenshot](https://d.pr/i/QZRJNl+)
Screenshot: https://d.pr/i/QZRJNl

**Screenshots**
See above.

**Expected behavior**
Shipping tax is always rounded the same way, no matter how product prices are entered.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://new.test
Site address (URL): http://new.test
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.3
PHP Version: 7.3.10
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.17
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Total Database Size: 73.34MB
Database Data Size: 48.75MB
Database Index Size: 24.59MB
wp_woocommerce_sessions: Data: 3.50MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 21.03MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 17.55MB + Index: 20.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.72MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.34MB + Index: 0.22MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.59MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 1
attachment: 998
aw_workflow: 7
customize_changeset: 1
follow_up_email: 1
global_product_addon: 1
oembed_cache: 1
page: 16
post: 3
product: 781
product_variation: 1535
revision: 12
shop_coupon: 17
shop_order: 75
shop_order_refund: 1
shop_subscription: 17
wc_booking: 2
wc_membership_plan: 1
wc_user_membership: 1
wcpf_item: 5
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.1.1

### Inactive Plugins (44) ###

Akismet Anti-Spam: by Automattic – 4.1.4
All-in-One WP Migration: by ServMask – 7.22
AutomateWoo: by WooCommerce – 4.9.1
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.1.1 – Installed version not tested with active version of WooCommerce 4.1.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.4 – Installed version not tested with active version of WooCommerce 4.1.1
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.1.1
Child Theme Configurator: by Lilaea Media – 2.5.2
Codepen Block: by madeincosmos – 1.0.0
Code Snippets: by Code Snippets Pro – 2.14.0
Follow-Up Emails: by WooCommerce – 4.9.0 – Installed version not tested with active version of WooCommerce 4.1.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Loco Translate: by Tim Whitlock – 2.3.3
Product Filters for WooCommerce: by WooCommerce – 1.2.0
Request a Quote for WooCommerce: by Addify – 1.4.1 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce 360° Image: by WooCommerce – 1.1.14
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.15 (update to version 1.1.16 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.21 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Advanced Notifications: by WooCommerce – 1.2.22 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.10
WooCommerce Blocks: by Automattic – 2.5.15 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Bookings: by WooCommerce – 1.15.18
WooCommerce FedEx Shipping: by WooCommerce – 3.4.28 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.13 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Memberships: by SkyVerge – 1.17.4
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.1 (update to version 2.0.2 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.6.31 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Pre-Orders: by WooCommerce – 1.5.24 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.31 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Product Bundles: by SomewhereWarm – 6.2.3
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.32 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Products Compare: by WooCommerce – 1.0.19
WooCommerce Product Vendors: by WooCommerce – 2.1.31 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.22
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.9
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.17
WooCommerce Smart Coupons: by StoreApps – 4.7.3 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Square: by WooCommerce – 2.1.1 (update to version 2.1.5 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Subscriptions: by WooCommerce – 3.0.4 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.43
WP Crontrol: by John Blackbourn & crontributors – 1.8.2
WP Mail Logging: by MailPoet – 1.9.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 200
Oldest: 2020-05-04 15:24:21 +0200
Newest: 2020-06-01 13:59:47 +0200

Pending: 4
Oldest: 2020-06-02 09:29:42 +0200
Newest: 2020-06-07 12:47:26 +0200

`
```
</details>

**Comment by juliaamosova** [comment] 2020-06-01 19:54
Hi @madeincosmos,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Exclusive of tax:

![1](https://user-images.githubusercontent.com/19143190/83448584-2b43e500-a420-11ea-8aa2-11b0b3741f8a.jpg)

Inclusive of tax:

![2](https://user-images.githubusercontent.com/19143190/83448596-30089900-a420-11ea-877f-bdf0573ff20b.jpg)

We’re going to work on this bug as soon as possible.

**Comment by johndcoy** [comment] 2020-06-08 14:34
@juliaamosova Could this be related to #26582 ? If so, could it be assigned to the same milestone?

**Comment by juliaamosova** [comment] 2020-06-08 17:00
Hi @johndcoy, we identified for the issue in this thread to be different from https://github.com/woocommerce/woocommerce/issues/26582. However, @vedanshujain mentioned he will look into the issue in this thread this week to see if it can be included in 4.3. But this week is also a Hack week so we are prioritizing Hack week projects. If we can't make it to 4.3 then we'd more likely be able to include the fix in 4.4.

**Comment by ggmacasaet** [comment] 2020-06-18 15:20
Hi,

We really need this done urgently because a lot of our accounting is having inconsistency with the total. Is there a schedule on when can this be done?

**Comment by negapo** [comment] 2020-06-22 10:16
This is messing up a large number of orders, order amounts are of by one cent, accounting is a nightmare, we cant invoice this orders, we have to go them one by one, this must be very high priority, incorrect order amounts on a ecommerce platform guys!!!

**Comment by vedanshujain** [comment] 2020-06-23 13:26
@ggmacasaet @negapo can you share more details on the exact tax configuration and product rate of your system when you are seeing this error. I have a fix for the issue in #26850 but it seems like this will be rare (not the free product, but the actual issue as well), so there is a chance that you are facing a different issue.

**Comment by ggmacasaet** [comment] 2020-06-26 09:25
hi @vedanshujain not sure what you mean but the screenshot on the configuration stated above should be the same. We have 25% for shipping, we have 15% for our main products, and 25% for accessories products. But the configuration on the prices should be inclusive of tax

**Comment by ggmacasaet** [comment] 2020-06-30 07:11
@vedanshujain any update on when the fix will be pushed?

**Comment by ggmacasaet** [comment] 2020-06-30 10:04
@vedanshujain have copied your changes listed on the pull request and it didn't fix our issue. :(

**Comment by vedanshujain** [comment] 2020-06-30 10:08
@ggmacasaet I meant that it will be helpful for me to reproduce and fix the issue if you can provide following details when the rounding issue happens:
1. Product(s) price and quantity
2. Shipping rate
3. Tax rate

I do not need prices and taxes for all the products, just for the ones that you add in your cart to reproduce the issue.

**Comment by ggmacasaet** [comment] 2020-06-30 10:55
Hi @vedanshujain,

Product Price: 242 inclusive of tax. This is the price entered on the product
Shipping Rate: 75.10 exclusive of tax.
Tax rate: 
Product Tax rate: 15%
Shipping Tax Rate: 25%

**Comment by vedanshujain** [comment] 2020-06-30 13:55
@ggmacasaet Looks like there was a display error, I have pushed a fix and should work now (I tried out with shipping tax of 25% and the product rate of 15% by using tax classes). 

Expected calculations:
Product total price (incl of tax @ 15%) = 242 
Shipping price (before tax) = 75.10
Shipping total price (inc of tax @ 25%) = 93.88

Expected total = 242 + 93.88 = 335.88

Cart total screenshot:

![Screenshot 2020-06-30 at 7 24 46 PM](https://user-images.githubusercontent.com/7571618/86134557-66acfe80-bb07-11ea-91c4-f19824b819c1.png)

**Comment by vedanshujain** [comment] 2020-06-30 13:56
Another screenshot with prices shown exclusive taxes:
![Screenshot 2020-06-30 at 7 25 50 PM](https://user-images.githubusercontent.com/7571618/86134677-8cd29e80-bb07-11ea-9452-7a72e9244841.png)

**Comment by ggmacasaet** [comment] 2020-07-01 19:20
Hi @vedanshujain,

There is an issue with regards to rounding off for PRODUCTS as well which there was a fix that was given to me directly through email. Basically, the change that was done there is on the file /includes/abstracts/abstract-wc-order.php and function calculate totals. Here is the code difference between the current version and on the fix that was provided to me:


![image](https://user-images.githubusercontent.com/1694742/86282956-250d7800-bc1b-11ea-856f-b671923ca594.png)

As you can see on the screenshot above, the left part is the fix that was provided to me and the one on the right is the current version released. The reason the fix was provided to me is that there is also a round off issue on product level. That code fixed it for me but i don't want to always do the update manually on the core plugin whenever there is a woocommerce plugin update.

**Comment by ggmacasaet** [comment] 2020-07-01 19:22
Here is the email provided to me by support:

Jesse P (Automattic)

May 22, 2020, 5:07:33 PM UTC

Hey again!

The developers have gotten back to me and wanted me to reach out to ask you to try to make an update to see if it corrects the issue in your store. Would you be able to take the attached file and add it to your staging/dev site and test to see if it corrects the issue? The file would replace the same named file in the folder at /wp-content/plugins/woocommerce/includes/abstracts/.

Once the file is added, please make sure the Round tax at subtotal level, instead of rounding per line is disabled/unticked at WooCommerce > Settings > Tax, and then check to see if order values are correct.

Have a good one!
Jesse - WooCommerce Happiness Engineer

**Comment by ggmacasaet** [comment] 2020-07-09 07:52
hi @vedanshujain,

Any update on the inquiry above please?

**Comment by vedanshujain** [comment] 2020-07-13 17:47
Hi @ggmacasaet, sorry for late reply.

I have changed the code a bit more after you were provided with the original code snippet, and since those changes are not trivial to apply, I would recommend that you wait till the PR is approved (its under review right now). The changes are bit more complicated than they were earlier.

That said, I did test out the specific case that you mention with exact pricing and it worked fine, so I am optimistic that once the pull request is approved the fix will make it to the next release and you won't have to update files manually.

**Comment by ggmacasaet** [comment] 2020-07-15 13:35
@vedanshujain does that mean this has not been shipped yet to the latest woocommerce version?

**Comment by vedanshujain** [comment] 2020-07-20 09:33
@ggmacasaet No it's not, it will be shipped only after the PR is approved and merged.

**Comment by ggmacasaet** [comment] 2020-07-21 09:17
Hi @vedanshujain,

Seems like the issue is still not fixed when i copied all the fixes attached to this. 

![image](https://user-images.githubusercontent.com/1694742/88036216-d302a700-cb75-11ea-8314-d0d6f0d2b759.png)

On the setup above. You should see that the total for the shipping tax should be 34.91 which is correct when you see the display:

![image](https://user-images.githubusercontent.com/1694742/88036305-f2013900-cb75-11ea-8ea1-feb6efc1c926.png)

But when you look on the totals computation on the screenshot below. It is not showing the correct value:
![image](https://user-images.githubusercontent.com/1694742/88036379-0e04da80-cb76-11ea-872c-5f6cdd7509ee.png)

It is only showing 34.90 and the totals is still not yet correct.

Thanks,

Geoff

**Comment by peterfabian** [comment] 2020-07-24 10:51
Hi Geoff, 

I've just tested your use case with the patch applied and this is what I see. Would you consider it correct?
<img width="1675" alt="Screenshot 2020-07-24 at 12 50 07" src="https://user-images.githubusercontent.com/2207451/88384204-41c94580-cdac-11ea-9e03-e4700980e9bc.png">

Using these settings:
<img width="1675" alt="Screenshot 2020-07-24 at 12 50 07" src="https://user-images.githubusercontent.com/2207451/88384228-54437f00-cdac-11ea-993a-8bd71758f076.png">

Product priced at 165, shipping cost 139.62.

**Comment by ggmacasaet** [comment] 2020-07-24 13:04
Hi,

Can you confirm if there we're changes applied outside of the original?
Since we've copied the changes on our server before it's implemented and
that one we can replicate the issue.

Thanks,

Geoffrey Macasaet / Operations Director
+63 9173121387 / geoffrey@iwoork.com
<http://iwoork.com/>

[image: Iwoork Web Solutions] <http://iwoork.com/>

Iwoork Web Solutions

http://iwoork.com

[image: Facebook] <http://www.facebook.com/iwoork.web> [image: Twitter]
<http://www.twitter.com/iwoork> [image: Google Plus]
<http://https//plus.google.com/109638330282000608441> [image: Linkedin]
<http://http//www.linkedin.com/company/2822686>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Iwoork Web
Solutions is not responsible for errors or omissions in this message and
denies any responsibility for any damage arising from the use of e-mail.
Any opinion and other statement contained in this message and any
attachment are solely those of the author and do not necessarily represent
those of the company.

**Closed** 2020-07-24 17:23 UTC
Labels: bug, component: calculation, priority: high

**Comment by vedanshujain** [comment] 2020-07-24 17:28
@ggmacasaet I think Peter applied the current set of changes, so there might be some inconsistency in the patch. Note that the PR is now merged, which means that this patch will be included in WooCommerce 4.4 (late August release).

**Comment by ggmacasaet** [comment] 2020-07-26 12:56
@vedanshujain can you share the changes that was implemented by @peterfabian please so i can implement it on our current woocommerce version as well. Thanks.

**Comment by ggmacasaet** [comment] 2020-07-30 07:54
hi guys,

back again.. so i got a hold of the version 4.4 beta and it didn't fix the issue for the 1 cent discrepancy that i last raised. can you please help?

**Comment by juliaamosova** [comment] 2020-07-31 15:44
I can confirm that the original issue filed by @madeincosmos in this thread is fixed in WC 4.4. beta1.

**Comment by ggmacasaet** [comment] 2020-07-31 16:09
Hi,

 

The problem is the original issue that we had already logged incorrect values due to the 1 cent discrepancy. Now what we need to do is to recalculate those values manually. Can you please confirm that on manual creation of shipping it does calculate it properly since when we downloaded 4.4 it doesn’t still calculate it properly.

**Comment by juliaamosova** [comment] 2020-07-31 17:02
Hi @ggmacasaet,

With your setup which is:

>Expected calculations:
Product total price (incl of tax @ 15%) = 242
Shipping price (before tax) = 75.10
Shipping total price (inc of tax @ 25%) = 93.88

I have the following when placing the order on the site:

**Inclusive of tax - correct total $335.88:**

![incl2](https://user-images.githubusercontent.com/19143190/89058589-8d8c6980-d32d-11ea-96fd-8bc93b2b1e18.jpg)

**Exclusive of tax - correct total $335.88:** 

![excl2](https://user-images.githubusercontent.com/19143190/89058617-9846fe80-d32d-11ea-9930-f51eadcdf9fd.jpg)

Also noting here how to set up the tax rates in your case for future reference:

1) Create a new tax class, uncheck Shipping tick box so that this tax does not apply to shipping.
2) In the Standard tax class, add the tax rate to be applied to shipping and check the Shipping checkbox.
3) Add the tax class created in step 1 to the product.

>The problem is the original issue that we had already logged incorrect values due to the 1 cent discrepancy. Now what we need to do is to recalculate those values manually. Can you please confirm that on manual creation of shipping it does calculate it properly since when we downloaded 4.4 it doesn’t still calculate it properly.

I don't understand what do you mean here, sorry. But I am testing placing manual order next. If you can provide a bit more clear details, it will be great.

**Comment by ggmacasaet** [comment] 2020-07-31 17:32
Hi Julia,

 

Thanks for your response but I am not talking about the cart. The problem now with regards to the calculation is on the MANUAL ORDER CREATION. If you will see on the screenshot below when adding a manual SHIPPING value of 139.62 it is displaying 2 things. First if you will check on the line item the MVA 25% is 34.91 but if you will check on the totals section the MVA 25% is 34.90. Now that is another calculation gap. We are not having problems anymore with regards to cart but our problem now is on the manual order recalculate button not throwing the correct values.

 



 

Thanks,


Geoff
