### ISSUE TITLE
Woocommerce - Spelling error

### ISSUE THREAD

**Issue by oscarruz** [woocommerce/woocommerce#27813] opened 2020-09-30 14:04 UTC
Hello,

I have running Woocommerce 4.5.2 and I have found a spelling error in spanish language. From the Checkout Page when I have completed the form with an existing account mail, it show:

'You already have an account registered with your email address. Please agree.'

In spanish:

Ya ha una cuenta registrada con tu dirección de correo electrónico. Por favor, accede.

The correct would be:

Ya ha**y** una cuenta registrada con tu dirección de correo electrónico. Por favor, accede.

So, Is it possible to correct this?

Thanks!

**Comment by tammullen** [comment] 2020-09-30 21:12
Hi @oscarruz 

Thank you for raising this issue. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. Translation is managed by teams over at translate.wordpress.org
​
The issue you are having seems to be caused by the Spanish language translation file so would need to be fixed on https://translate.wordpress.org/projects/wp-plugins/woocommerce/

Please contact the translation team https://translate.wordpress.org/projects/wp-plugins/woocommerce/ for further help.

**Closed by tammullen** 2020-09-30 21:12 UTC
Labels: i18n

**Comment by oscarruz** [comment] 2020-10-01 06:50
Thank you so much.
