### ISSUE TITLE
Ghost reviews appearing on product

### ISSUE THREAD

**Issue by shelleyphant** [woocommerce/woocommerce#21661] opened 2018-10-25 00:01 UTC
Hi, one of my products is reporting that it has 10708 reviews, but when I open the reviews tab, the product has 0.
I can't seem to reproduce the behavior on any other product. The settings all appear the same. The product in question is https://www.shelleybassett.com/shop/fonts/hedron-round/ and the screenshot shows the issue. There are no reviews in the database, and nothing reported in the product edit page.

![screen shot 2018-10-25 at 10 52 21 am](https://user-images.githubusercontent.com/17712529/47467982-97be3180-d844-11e8-9e6e-eee1b1cf4d86.png)

**Expected behavior**
I expect the number in the title to match the number of product reviews.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://www.shelleybassett.com
Site URL: https://www.shelleybassett.com
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.11
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.16-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: sb_
MaxMind GeoIP Database: ✔
Total Database Size: 12.47MB
Database Data Size: 8.59MB
Database Index Size: 3.88MB
sb_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
sb_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
sb_woocommerce_log: Data: 0.00MB + Index: 0.00MB
sb_ac_abandoned_cart_history_lite: Data: 0.01MB + Index: 0.00MB
sb_ac_email_templates_lite: Data: 0.00MB + Index: 0.00MB
sb_ac_guest_abandoned_cart_history_lite: Data: 0.00MB + Index: 0.00MB
sb_ac_sent_history_lite: Data: 0.00MB + Index: 0.00MB
sb_blogs: Data: 0.00MB + Index: 0.00MB
sb_blog_versions: Data: 0.00MB + Index: 0.00MB
sb_commentmeta: Data: 0.00MB + Index: 0.01MB
sb_comments: Data: 0.00MB + Index: 0.01MB
sb_defender_lockout: Data: 0.00MB + Index: 0.00MB
sb_defender_lockout_log: Data: 0.00MB + Index: 0.00MB
sb_ewwwio_images: Data: 0.05MB + Index: 0.04MB
sb_failed_jobs: Data: 0.00MB + Index: 0.00MB
sb_links: Data: 0.00MB + Index: 0.00MB
sb_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
sb_options: Data: 2.41MB + Index: 0.07MB
sb_pmxi_files: Data: 0.00MB + Index: 0.00MB
sb_pmxi_history: Data: 0.00MB + Index: 0.00MB
sb_pmxi_imports: Data: 0.02MB + Index: 0.00MB
sb_pmxi_posts: Data: 0.00MB + Index: 0.00MB
sb_pmxi_templates: Data: 0.00MB + Index: 0.00MB
sb_popularpostsdata: Data: 0.02MB + Index: 0.00MB
sb_popularpostssummary: Data: 0.11MB + Index: 0.17MB
sb_postmeta: Data: 2.07MB + Index: 0.28MB
sb_posts: Data: 2.87MB + Index: 1.52MB
sb_queue: Data: 0.00MB + Index: 0.00MB
sb_registration_log: Data: 0.00MB + Index: 0.00MB
sb_relevanssi: Data: 0.74MB + Index: 1.42MB
sb_relevanssi_log: Data: 0.00MB + Index: 0.01MB
sb_relevanssi_stopwords: Data: 0.00MB + Index: 0.00MB
sb_short_links: Data: 0.00MB + Index: 0.00MB
sb_short_link_clicks: Data: 0.00MB + Index: 0.00MB
sb_short_link_replacements: Data: 0.00MB + Index: 0.00MB
sb_signups: Data: 0.00MB + Index: 0.00MB
sb_site: Data: 0.00MB + Index: 0.01MB
sb_sitemeta: Data: 0.00MB + Index: 0.01MB
sb_smush_dir_images: Data: 0.00MB + Index: 0.00MB
sb_termmeta: Data: 0.00MB + Index: 0.01MB
sb_terms: Data: 0.00MB + Index: 0.01MB
sb_term_relationships: Data: 0.01MB + Index: 0.02MB
sb_term_taxonomy: Data: 0.00MB + Index: 0.01MB
sb_usermeta: Data: 0.02MB + Index: 0.02MB
sb_users: Data: 0.00MB + Index: 0.01MB
sb_wc_download_log: Data: 0.00MB + Index: 0.00MB
sb_wc_webhooks: Data: 0.00MB + Index: 0.00MB
sb_yarpp_related_cache: Data: 0.01MB + Index: 0.02MB
sb_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
sb_yoast_seo_meta: Data: 0.19MB + Index: 0.21MB

### Post Type Counts ###

attachment: 268
feedback: 1
ml-slide: 31
ml-slider: 6
nav_menu_item: 15
page: 16
portfolio: 14
post: 58
product: 5
revision: 22
shell-portfolio: 14
shop_order: 6
ssr_recipe: 7
videos: 26
wc_zapier_feed: 1
wpcf7_contact_form: 1
wphb_minify_group: 30

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Akismet Anti-Spam: by Automattic – 4.0.8
Categories in Hierarchical Order: by AS Tech Solutions – 1.3.1
Classic Editor: by WordPress Contributors – 0.4
Contact Form 7: by Takayuki Miyoshi – 5.0.4
Crayon Syntax Highlighter: by Aram Kocharyan – 2.8.4
Facebook for WooCommerce: by Facebook – 1.9.6 – Not tested with the active version of WooCommerce
Featured Images in RSS w/ Size and Position: by 5 Star Plugins – 1.4.8
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.5
Hummingbird: by WPMU DEV – 1.9.2
Instagram Feed: by Smash Balloon – 1.10.1
MetaSlider - Pro Add-on Pack: by Team Updraft – 2.7.3
MetaSlider: by Team Updraft – 3.9.1
Multiple Featured Images: by Marcus Kober – 0.5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Relevanssi: by Mikko Saari – 4.1.0.1
reSmush.it Image Optimizer: by reSmush.it – 0.1.16
Super Simple Recipes: by Oak & Cove – 1.0.4
Super Socializer: by Team Heateor – 7.12.2
WooCommerce - MailerLite: by MailerLite – 1.1.1 – Not tested with the active version of WooCommerce
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.0.2 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.5
WooCommerce POS: by kilbot – 0.4.20
WooCommerce: by Automattic – 3.5.0
WooSwipe: by Website Design – 1.1.6.6
WordPress Popular Posts: by Hector Cabrera – 4.2.0
Yoast SEO: by Team Yoast – 9.0.2 – Not tested with the active version of WooCommerce
WP Better Permalinks: by Mateusz Gbiorczyk – 3.0.2
WPS Hide Login: by WPServeur
NicolasKulka
tabrisrp – 1.4.4

Yet Another Related Posts Plugin: by Adknowledge – 4.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2368 - /shop/
Cart: #2370 - /cart/
Checkout: #2372 - /checkout/
My account: #2379 - /my-account/
Terms and conditions: #425 - /privacy-policy/

### Theme ###

Name: Shelley Bassett Update
Version: 1.0
Author URL: https://www.shelleybassett.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: ShelleyBassett/woocommerce/archive-product.php
ShelleyBassett/woocommerce/single-product.php

`
</details>

**Comment by keefyhub** [comment] 2018-10-25 07:46
When you look at that product in the `sb_posts` table is the `comment_count` set to 0? If not you can manually change it or run this piece of code which will update all products with the correct comment count

```
$entries = $wpdb->get_results("SELECT * FROM {$wpdb->prefix}posts WHERE post_type IN ('product')");

foreach($entries as $entry)
{
    $post_id = $entry->ID;
    $comment_count = $wpdb->get_var("SELECT COUNT(*) AS comment_cnt FROM {$wpdb->prefix}comments WHERE comment_post_ID = '$post_id' AND comment_approved = '1'");
    $wpdb->query("UPDATE {$wpdb->prefix}posts SET comment_count = '$comment_count' WHERE ID = '$post_id'");
}
```

I have run this code myself but definitely take a backup just incase.

**Comment by kloon** [comment] 2018-10-25 09:37
Log into you admin area and go to `WooCommerce` -> `Status` and click the Tools tab at the top of that page. The click the `Recount terms` and `Clear transients` buttons. This should refresh the caches and hopefully fix the issue for you.

**Comment by shelleyphant** [comment] 2018-10-25 20:58
Hi all,
Clearing the recounting the terms and clearing the transients and cache didn't work, so I went back to the database. The comment count is set to 0 for that product, but the number '10708' that is appearing on the page is the post ID. 
I have no idea why the theme is pulling the id for this product only. Any suggestions would be helpful.

**Comment by kloon** [comment] 2018-10-29 12:09
@shelleyphant It is difficult to say what the cause might be. My only suggestion would be to test with all plugins except WooCommerce disabled and then also switch your theme temporarily to a default one like Twentyseventeen and then test again.

If it works you can then enable plugins one by one testing in between and then finally switching your theme back to see what is causing the issue. It is possible that something is overriding the template and changing the title.

As it stands I am unable to reproduce this and the review count is showing fine for me http://cld.wthms.co/crXkR8

I am closing and will gladly reopen if you can provide steps to replicate this with just WooCommerce and a default theme.

**Closed by kloon** 2018-10-29 12:09 UTC
Labels: status: needs feedback
