### ISSUE TITLE
Importing products - Extern URL not working

### ISSUE THREAD

**Issue by Moseby** [woocommerce/woocommerce#19859] opened 2018-04-25 16:36 UTC
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. I have a CSV with products that I'm importing via WooCommerce Import-tool
2. I'm connecting the dots as they should be https://prnt.sc/ja18wq (You can see I've chosen the product URL for the "Extern URL"
3. All the variables are added correctly EXCEPT the Extern URL
4. The product appears BUT when I go in the product page there is a "1 - Add to cart" 

## Expected/actual behavior

There should be a "Buy now" button instead of the "Add to cart" and a forwarding to the extern URL. When going in to the product from the Admin CP, there is no Extern Link added (As it was never added at all on import)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

-Astra theme
-WooCommerce plugin
```
`
### WordPress Environment ###

Home URL: https://presentertillalla.se
Site URL: https://presentertillalla.se
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache/2.4.33 (FreeBSD) mpm-itk/2.4.7-04 PHP/7.1.16
PHP Version: 7.1.16
PHP Post Max Size: 200 MB
PHP Time Limit: 180
PHP Max Input Vars: 5000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ MaxMind GeoIP-databasen saknas – Geolokalisering kommer inte att fungera. Du kan ladda ned den och installera manuellt från http://dev.maxmind.com/geoip/legacy/geolite/ till adressen: . Bläddra ned till ”Nedladdningar” och ladda ned den ”binära/gzip”-filen intill ”GeoLite Country”. Kom ihåg att packa upp filen GeoIP.dat.gz och sedan endast ladda upp GeoIP.dat.
Total databasstorlek: 6.41MB
Datastorlek för databas: 5.22MB
Indexstorlek för databas: 1.19MB
wp_woocommerce_sessions: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_api_keys: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02 MB + Index: 0.05 MB
wp_woocommerce_order_items: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_order_itemmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_tax_rates: Data: 0.02 MB + Index: 0.06 MB
wp_woocommerce_tax_rate_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zones: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_shipping_zone_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zone_methods: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_payment_tokens: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_payment_tokenmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_log: Data: 0.02 MB + Index: 0.02 MB
wp_aws_cache: Data: 0.02 MB + Index: 0.00 MB
wp_aws_index: Data: 0.17 MB + Index: 0.00 MB
wp_commentmeta: Data: 0.02 MB + Index: 0.03 MB
wp_comments: Data: 0.02 MB + Index: 0.08 MB
wp_links: Data: 0.02 MB + Index: 0.02 MB
wp_nextend2_image_storage: Data: 0.02 MB + Index: 0.02 MB
wp_nextend2_section_storage: Data: 0.02 MB + Index: 0.03 MB
wp_nextend2_smartslider3_generators: Data: 0.02 MB + Index: 0.00 MB
wp_nextend2_smartslider3_sliders: Data: 0.02 MB + Index: 0.00 MB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02 MB + Index: 0.00 MB
wp_nextend2_smartslider3_slides: Data: 0.02 MB + Index: 0.00 MB
wp_options: Data: 2.02 MB + Index: 0.06 MB
wp_pmxi_files: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_history: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_imports: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_posts: Data: 0.02 MB + Index: 0.00 MB
wp_pmxi_templates: Data: 0.02 MB + Index: 0.00 MB
wp_postmeta: Data: 1.50 MB + Index: 0.22 MB
wp_posts: Data: 0.47 MB + Index: 0.06 MB
wp_smush_dir_images: Data: 0.02 MB + Index: 0.03 MB
wp_termmeta: Data: 0.02 MB + Index: 0.03 MB
wp_terms: Data: 0.02 MB + Index: 0.03 MB
wp_term_relationships: Data: 0.02 MB + Index: 0.02 MB
wp_term_taxonomy: Data: 0.02 MB + Index: 0.03 MB
wp_UPCP_Catalogues: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Catalogue_Items: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Categories: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Custom_Fields: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Fields_Meta: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Items: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Item_Images: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_SubCategories: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Tagged_Items: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Tags: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Tag_Groups: Data: 0.02 MB + Index: 0.00 MB
wp_UPCP_Videos: Data: 0.02 MB + Index: 0.00 MB
wp_usermeta: Data: 0.02 MB + Index: 0.03 MB
wp_users: Data: 0.02 MB + Index: 0.05 MB
wp_wc_download_log: Data: 0.02 MB + Index: 0.03 MB
wp_wc_webhooks: Data: 0.02 MB + Index: 0.02 MB
wp_woof_query_cache: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_links: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_meta: Data: 0.02 MB + Index: 0.00 MB

### Post Type Counts ###

advert: 1
al_product: 7
attachment: 74
customize_changeset: 89
nav_menu_item: 4
page: 7
post: 2
product: 49
revision: 105

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Advanced Woo Search: av ILLID – 1.40
Autoptimize: av Frank Goossens (futtta) – 2.3.4
Elementor: av Elementor.com – 2.0.8
Insert Headers and Footers: av WPBeginner – 1.4.2
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 3.0.2
Simple CSS: av Tom Usborne – 1.1
WooCommerce External Product New Tab: av Stuart Duff – 1.0.2 – Inte testat med den aktiva versionen för WooCommerce
WOOF - WooCommerce Products Filter: av realmag777 – 1.2.0
WooCommerce: av Automattic – 3.3.5
Yoast SEO: av Team Yoast – 7.3
WP Smush: av WPMU DEV – 2.7.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Butikbas: #337 - /produkter/
Varukorg: ❌ Sid-ID har konfigurerats
men sidan finns inte

Kassan: ❌ Sid-ID har konfigurerats
men sidan finns inte

Mitt konto: ❌ Sid-ID har konfigurerats
men sidan finns inte

Allmänna villkor: ❌ Sida har inte valts

### Theme ###

Name: Astra
Version: 1.3.1
Author URL: http://wpastra.com/about/
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by peterfabian** [comment] 2018-04-26 13:55
Hi Moseby,

I wasn't able to reproduce this problem. Would you mind sharing the csv file?

**Comment by claudiulodro** [comment] 2018-04-26 17:11
Looking at that screenshot, you are missing [the product type column](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting) so it will import the product as the default Simple product type instead of the External product type. You need to add the product type column with `external` as the type and you should be back in business.

Closing this because it's not a bug in the importer.

**Closed by claudiulodro** 2018-04-26 17:11 UTC
