### ISSUE TITLE
The URL string "?add-to-cart=1" for variations doesn't show the selected options in the cart/checkout or orders in admin

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#24409] opened 2019-08-15 00:45 UTC
**Describe the bug**
I assume you're familiar with using a URL string like https://core.local/?add-to-cart=821, if this happen to be an ID for a variation in a variable product it causes an issue though.

You won't see the selected option in the cart, checkout, or when viewing the order in the admin side of things.

If you visit a variable product and manually select variations they appear correctly, but the URL string doesn't work the same way.

**To Reproduce**
1. Find a product ID of a variable product.
2. Create a URL string and replace the URL and ID "https://core.local/?add-to-cart=821"
3. Once added to the cart, look at the cart and try to figure out what options you selected.

**Screenshots**
![https://cld.wthms.co/tW74tb](https://cld.wthms.co/tW74tb+)
Image link: https://cld.wthms.co/tW74tb
**Expected behavior**
I would expect to see the variation choices reflected in the cart and checkout like normally they do.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiosanches** [comment] 2019-08-19 23:53
Duplicate of #24000

**Closed by claudiosanches** 2019-08-19 23:53 UTC
