### ISSUE TITLE
Sorting product changes not saved

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#28870] opened 2021-01-21 00:40 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using the `sorting` function from WP Admin on the list of products, changes may not be properly saved due to caching. Flushing WP Object Cache after making the sorting change resolves the issue though.

**Expected behavior**
After a sorting change is made, ensure that the existing list order is not stored in WP Object cache or Memcached. And ensure that changes are saved and still shown after refreshing the page.

**Actual behavior**
Changed the product sorting order, refresh the page and the changes are lost.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
For consistency in hosting environments, I've replicated this on a WordPress.com Business/eCommerce plan
1. Go to `Products`
2. Click on 'Sorting`
3. Drag products into a new order
4. Not the animation that indicates on each line item that the change has been saved
5. Refresh the page and notice that your changes were not saved

**Screenshots**

![](https://d.pr/i/0WDavf+)
Image Link: https://d.pr/i/0WDavf

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://fullysupported.wpcomstaging.com
Site address (URL): https://fullysupported.wpcomstaging.com
WC Version: 4.9.1
REST API Version: ✔ 4.9.1
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.14
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.74.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.1
WC Database Prefix: wp_
Total Database Size: 4.41MB
Database Data Size: 2.71MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.33MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.22MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 42
custom_css: 1
jetpack-portfolio: 2
jetpack-testimonial: 1
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 7
oembed_cache: 1
page: 8
post: 4
product: 18
product_variation: 7
revision: 66
safecss: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Jetpack by WordPress.com: by Automattic – 9.3.2
WooCommerce: by Automattic – 4.9.1

### Inactive Plugins (9) ###

AMP: by AMP Project Contributors – 2.0.10
Classic Editor: by WordPress Contributors – 1.6
CoBlocks: by GoDaddy – 2.6.0
Crowdsignal Forms: by Automattic – 1.3.5
Gutenberg: by Gutenberg Team – 9.7.4
Layout Grid: by Automattic – 1.3
Page Optimize: by Automattic – 0.5.1
WordPress.com Editing Toolkit: by Automattic – 2.11
Yoast SEO: by Team Yoast – 15.6.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #839 - /shop/
Cart: #840 - /cart/
Checkout: #841 - /checkout/
My account: #842 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.3.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2021-01-20 15:51:02 -0500
Newest: 2021-01-20 15:51:58 -0500

Pending: 1
Oldest: 2021-01-20 19:40:14 -0500
Newest: 2021-01-20 19:40:14 -0500

`
```
</details>

**Comment by rrennick** [comment] 2021-01-21 20:59
@FreshPhil Thanks for reporting the issue. I tried this with `redis` object caching and was not able to reproduce the issue. Could you try this with `redis`?

**Comment by rrennick** [comment] 2021-01-25 20:06
I was able to reproduce this in an AT site. Removing `object-cache.php` from the site did resolve the issue. I wasn't able to get memcached installed and working on 7.4 in my local environment so I wasn't able to confirm it in another environment.

**Comment by douglas-johnson** [comment] 2021-03-03 19:14
I am also experiencing this problem.

My production site uses Memcached for object caching. The bug happens exactly as described in the issue.

I don't have this problem on my local environment that uses Local and doesn't have an object cache.

A workaround is to edit a product's menu order directly using Product Data > Advanced > Menu Order.

```
WC Version: 4.8.0
WP Version: 5.6.2
External object cache: ✔

### Dropin Plugins (2) ###

db.php: db.php
object-cache.php: Memcached
```

**Comment by tammullen** [comment] 2021-03-24 20:43
More reports here: https://github.com/woocommerce/woocommerce/issues/26626

**Comment by daveloodts** [comment] 2021-04-26 13:32
Hi, today a client noticed the same issue: Resaving a product results that previous sorting get back to zero for that product.
Flushing the Redis Cache solved it here.

**Comment by dzined** [comment] 2021-04-29 08:13
I  know this isn't strictly related, but it would be hugely useful if there was some visual cue as to where the item will end up when dropped...even an empty space of about 50px with a coloured background

**Comment by FreshPhil** [comment] 2021-08-04 14:29
Hey @tammullen any movement on this? Came across the issue again on some more Atomic sites.

**Comment by tammullen** [comment] 2021-08-04 15:08
It requires further feedback from the WooCommerce Core team. It has the `needs developer feedback` label so is in their backlog for them to get to it.

**Comment by vedanshujain** [comment] 2021-11-24 14:45
Seems like we are not busting the menu order cache. This is something that we should be able to directly after `woocommerce_after_product_ordering` action.

**Comment by rashedripon** [comment] 2022-08-21 10:34
Another AT site owner reported 36559508-zen

**Comment by orhanfernandes** [comment] 2022-08-22 08:00
Similar issue for AT site on 36322654-hc

Clearing cache partially solved the issue but the customer was clearly confused as to why they needed to clear cache every time they needed to sort products.

**Comment by jorgeatorres** [comment] 2022-08-22 22:22
Marking as duplicate of #31389.

**Closed by jorgeatorres** 2022-08-22 22:22 UTC
Labels: type: bug, type: good first issue, priority: low, focus: shop, focus: product, plugin: woocommerce
