### ISSUE TITLE
Refunds via REST doesn't refund line_item quantity (update: now tax)

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce#27376] opened 2020-01-08 18:07 UTC
**Describe the bug**
Doing a full refund of an order via REST doesn't behave as expected, from reading the docs.

Doing a POST (wp-json/wc/v3/orders/123/refunds) with the data:
```
{
    "api_refund": false,
    "amount": "90",
    "line_items": [
    	{
            "id": 123 // <-- the line_item ID on the order
            "quantity": -1,
            "subtotal": "-72",
            "total": "-72"
    	}
    ]
}
```

I cannot get it to refund the line items, which messes up the reports.

**To Reproduce**
1. Just try and do a complete refund of an order via REST.
If you succeed, I'd like to know the recipe.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I wish doing a full refund via REST would be a simple as:
```
{
   "api_refund": false,
   "full_refund": true
}
```

**Comment by falahati** [comment] 2020-09-03 16:31
@larssn's point is valid. However, may I suggest keeping this in mind when and if the Woocommerce team decided to release the 4th version of the REST API? In the next version, we should be able to fix this discrepancy between the request and responses of this endpoint. Meanwhile, since we already have working codes, it makes sense to just update the documentation. Even tho I am willing to modify my code personally, many people understandably are not.

**Comment by dexylea** [comment] 2020-10-29 20:36
@Konamiman using your suggestion we have now managed to get the line_item quantity updating properly. However, we now have the issue that a partial refund email is sent for every line updated and not the overall order. So if, for example, a customer purchases:

3x item A
2x item B
1 x item C

and we refund:

2x item A
1x item B

the customer is being sent 2 emails.

Do you or any other users know of a fix for this please?

**Comment by dexylea** [comment] 2021-01-18 20:44
@vedanshujain has there been any further development on this please? I would really like to avoid customers receiving a partial refund email for every line item refunded, plus then an overall refund email if the whole order is refunded. Thanks

**Comment by Konamiman** [comment] 2021-02-09 11:46
Hi @dexylea , I've been taking a look at the multiple emails issue you mentioned and I haven't been able to reproduce it. If I create a partial refund for two separate items, whether it's via admin UI or via REST API, I see that WooCommerce is sending one single email which includes both items. Maybe I'm misunderstading what the actual problem is?

**Closed** 2021-02-18 08:55 UTC
Labels: category: wc rest api, priority: high
