### ISSUE TITLE
woocommerce_order_status_changed not triggering

### ISSUE THREAD

**Issue by iamapinan** [woocommerce/woocommerce#23965] opened 2019-06-19 19:25 UTC
I use Woocommerce version 3.6.4 and latest WordPress version 5.2.2
When I changed order status the `woocommerce_order_status_changed` action not trigger.

**Example of code that I test**
```
function testtrigger() {
    //To do
}
add_action( 'woocommerce_order_status_changed', 'testtrigger');
```

**Site health**
`
### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: loading...
uploads_path: /var/www/html/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/html/wp-content/themes
themes_size: loading...
plugins_path: /var/www/html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: iWrite Child
version: 1.0.0
author: iOTech
author_website: http://iotech.co.th/
parent_theme: iWrite
theme_features: post-thumbnails, automatic-feed-links, title-tag, menus, html5, post-formats, custom-logo, custom-header, editor-styles, editor-style, infinite-scroll, widgets
theme_path: /var/www/html/wp-content/themes/iWrite

### wp-themes (1) ###

iWrite: version: 1.0.5, author: iOTech

### wp-plugins-active (6) ###

HTML Editor Syntax Highlighter: version: 2.4.1, author: James Bradford
Query Monitor: version: 3.3.6, author: John Blackbourn
WooCommerce: version: 3.6.4, author: Automattic
WooCommerce Admin: version: 0.13.2, author: WooCommerce
Woocommerce Line Notify: version: 1.1.0, author: Apinan Woratrakun
WP Page Builder: version: 1.2.0, author: Themeum.com

### wp-plugins-inactive (8) ###

Advanced Custom Fields: version: 5.8.1, author: Elliot Condon
iOTech WC Slip: version: 2.1.0, author: Best for Thailand use.
Loco Translate: version: 2.3.0, author: Tim Whitlock
Postmark (Official): version: 1.11.3, author: Andrew Yates & Matt Gibbs
Product Sales Report for WooCommerce: version: 1.4.8, author: Potent Plugins
Rank Math SEO: version: 1.0.27, author: Rank Math
Redis Object Cache: version: 1.4.3, author: Till Krüss
WP Super Cache: version: 1.6.7, author: Automattic

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 2
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.9.125-linuxkit x86_64
httpd_software: Apache/2.4.25 (Debian)
php_version: 7.3.6 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.52.1 OpenSSL/1.0.2r
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.5.5-10.3.15-MariaDB-1:10.3.15+maria~bionic
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: true
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by claudiosanches** [comment] 2019-06-19 21:52
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried your code, and it appeared to work correctly.

I tried with:

```php
function testtrigger() {
    error_log( print_r( 'Works???', true ) );
}
add_action( 'woocommerce_order_status_changed', 'testtrigger');
```

So, not able to reproduce this issue, check if some plugin is unregistered this hook, or something else happening on your installation.

It could be some plugin is unregistered this hook. You could try disable your plugins or change to a WordPress default theme to find where it is caused.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-06-19 21:52 UTC
