### ISSUE TITLE
Featured products not showing up on homepage, but do in widget? 

### ISSUE THREAD

**Issue by youradds** [woocommerce/woocommerce#14914] opened 2017-05-06 14:40 UTC
Hi,

This is with **WooCommerce 3.0.5**. My theme (Artificer) used to show the "featured" (starred) products on the homepage, using:

```
$args = array( 'post_type' => 'product', 'posts_per_page' => 3, 'meta_query' => array( array('key' => '_visibility','value' => array('catalog', 'visible'),'compare' => 'IN'),array('key' => '_featured','value' => 'yes')) );
$loop = new WP_Query( $args );
```

However, this no longer works! I've setup a basic install and installed WooCommerce + the theme, and then added one sample product. I can't see an `_featured`  entry in the `postmeta` table at all. I've done a full database dump and then searched for "featured", and it comes up with nothing.

Where on earth is the featured flag stored? It's driving me nuts! (and because its a free WooTheme's theme, I have no way of getting any support on it)

Thanks

Andy

**Comment by SewStylish** [comment] 2017-05-06 15:50
I'm having the same issues, and so are dozens of my pals who all use this same theme. As you say, free them = no support. But there must be thousands of us out there now with broken sites, maybe even tens of thousands.  I'm very disappointed in Woo for doing this to us all.

I found these two questions, but no answers. Maybe if you understand the techie stuff this might help you. It's all a foreign language to me - I need a theme update.

https://wordpress.stackexchange.com/questions/265967/debugging-why-featured-images-have-stopped-showing-in-woocommerce-on-the-homepag

and

https://wordpress.stackexchange.com/questions/265490/artificer-featured-images-stopped-showing-on-homepage?rq=1

**Comment by SewStylish** [comment] 2017-05-06 15:51
Ah, I just noticed you are called Andy. These might well be your questions! I'm stalking you for answers...desperate!

**Comment by youradds** [comment] 2017-05-06 15:57
Hi,

haha yes, those posts are me :) I forgot I posted the 2nd one (from the 1st May). 

I am a programmer, but not in PHP (I just happen to use Wordpress on a few sites). Unfortunately this is out of my area of expertise as well. I already have 6 programming languages going around in my head, but not sure I want another! 

Could you maybe post on this one as a comment, and say you are having the same issue?

https://wordpress.stackexchange.com/questions/265967/debugging-why-featured-images-have-stopped-showing-in-woocommerce-on-the-homepag

Maybe that will encourage someone to help us out :/ Otherwise, if someone can point me in the direction of HOW you get the featured items, I may well be able to fix it - but for now I can't even see where the data is stored (that tells it the product is featured). Very frustrating! 

Cheers

Andy

**Comment by SewStylish** [comment] 2017-05-06 16:18
I've also sent in a ticket to Woo although they will most likely ignore me because its a free theme. And I've posted in a Woo FB group too. I'm all over this, looking for the answer.

**Comment by youradds** [comment] 2017-05-06 16:30
Cool. Please post here if you hear anything

BTW, I would suggest removing your "answer" on wordpress.stackexchange.com , and repost it with the "add a comment" section (below by question). Otherwise,  you will no doubt get down-voted and complained against :(

**Comment by SewStylish** [comment] 2017-05-06 16:40
I deleted the 'answer' but I can't post a comment because I don't have enough points or something.  Will keep all these pages open and keep my ear to the ground.

**Comment by youradds** [comment] 2017-05-06 16:57
Cool. I forgot about that stupid rule! (they basically want you to add "answers" to peoples problems, before you can actually post comments!)

**Comment by carasmo** [comment] 2017-05-06 16:57
The code on that post works fine (https://wordpress.stackexchange.com/questions/265967/debugging-why-featured-images-have-stopped-showing-in-woocommerce-on-the-homepag). Turn on debug and what is the message you get? The only message I got, but it still ran is `get_product` should be `wc_get_product`. So this code here (copied from the SO site) works fine.

```

<ul class="featured-products">

<!-- The first 3 -->
<?php
$args = array( 'post_type' => 'product', 'posts_per_page' => 3, 'meta_query' => array( array('key' => '_visibility','value' => array('catalog', 'visible'),'compare' => 'IN'),array('key' => '_featured','value' => 'yes')) );
$loop = new WP_Query( $args );

while ( $loop->have_posts() ) : $loop->the_post(); $_product;

if ( function_exists( 'wc_get_product' ) ) {
    $_product = wc_get_product( $loop->post->ID );
} else {
    $_product = new WC_Product( $loop->post->ID );
}

?><li class="featured">

            <?php //woocommerce_show_product_sale_flash( $post, $_product ); ?>
            <a href="<?php echo get_permalink( $loop->post->ID ) ?>" title="<?php echo esc_attr($loop->post->post_title ? $loop->post->post_title : $loop->post->ID); ?>">
                <?php if (has_post_thumbnail( $loop->post->ID )) echo get_the_post_thumbnail($loop->post->ID, 'shop_catalog'); else echo '<img src="'.woocommerce_placeholder_img_src().'" alt="Placeholder" />'; ?>


            <h3><?php the_title(); ?> <span class="price"><?php echo $_product->get_price_html(); ?></span></h3>

            </a>

    </li><?php endwhile; ?><!-- the large 1 --><?php
$args = array( 'post_type' => 'product', 'posts_per_page' => 1, 'offset' => 3, 'meta_query' => array( array('key' => '_visibility','value' => array('catalog', 'visible'),'compare' => 'IN'),array('key' => '_featured','value' => 'yes')) );
$loop = new WP_Query( $args );
while ( $loop->have_posts() ) : $loop->the_post();
if ( function_exists( 'wc_get_product' ) ) {
    $_product = wc_get_product( $loop->post->ID );
} else {
    $_product = new WC_Product( $loop->post->ID );
}
?><li class="featured">

            <?php //woocommerce_show_product_sale_flash( $post, $_product ); ?>
            <a href="<?php echo get_permalink( $loop->post->ID ) ?>" title="<?php echo esc_attr($loop->post->post_title ? $loop->post->post_title : $loop->post->ID); ?>">
                <?php if (has_post_thumbnail( $loop->post->ID )) echo get_the_post_thumbnail($loop->post->ID, 'shop_single'); else echo '<img src="'.woocommerce_placeholder_img_src().'" alt="Placeholder" />'; ?>


            <h3><?php the_title(); ?> <span class="price"><?php echo $_product->get_price_html(); ?></span></h3>

            </a>

        </li><?php endwhile; ?><!-- the last 3 --><?php
$args = array( 'post_type' => 'product', 'posts_per_page' => 3, 'offset' => 4, 'meta_query' => array( array('key' => '_visibility','value' => array('catalog', 'visible'),'compare' => 'IN'),array('key' => '_featured','value' => 'yes')) );
$loop = new WP_Query( $args );
while ( $loop->have_posts() ) : $loop->the_post(); $_product;
if ( function_exists( 'wc_get_product' ) ) {
    $_product = wc_get_product( $loop->post->ID );
} else {
    $_product = new WC_Product( $loop->post->ID );
}
?><li class="featured">

            <?php //woocommerce_show_product_sale_flash( $post, $_product ); ?>
            <a href="<?php echo get_permalink( $loop->post->ID ) ?>" title="<?php echo esc_attr($loop->post->post_title ? $loop->post->post_title : $loop->post->ID); ?>">
                <?php if (has_post_thumbnail( $loop->post->ID )) echo get_the_post_thumbnail($loop->post->ID, 'shop_catalog'); else echo '<img src="'.woocommerce_placeholder_img_src().'" alt="Placeholder" />'; ?>


            <h3><?php the_title(); ?> <span class="price"><?php echo $_product->get_price_html(); ?></span></h3>

            </a>

        </li><?php endwhile; ?>
</ul>
```

**Comment by youradds** [comment] 2017-05-06 17:11
@carasmo - not for me unfortunately :( The SQL being outputted for me seems to be the big issue here. It's:

` SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) INNER JOIN wp_postmeta AS mt1 ON ( wp_posts.ID = mt1.post_id ) WHERE 1=1 AND ( ( wp_postmeta.meta_key = '_visibility' AND wp_postmeta.meta_value IN ('catalog','visible') ) AND ( mt1.meta_key = '_featured' AND mt1.meta_value = 'yes' ) ) AND wp_posts.post_type = 'product' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 3`

...yet there is no _featured values in the postmeta table! (which is why its not matching). Where would that even be stored? (I'm wondering if maybe its been moved for some reason?)

**Comment by carasmo** [comment] 2017-05-06 17:32
I installed Artificer and it works fine (without debug on). Check that the req with php (5.6) are met on your server. Sorry, can't help further, but it's probably your hosting environment (but that is a guess).

**Comment by youradds** [comment] 2017-05-06 17:34
mmm I'm on PHP 7.0.15, but I have the exact same problem on another server using PHP 5.6, so I'm pretty sure its not a server issue. The fact there is no data in the database that mentions "featured" just has me baffled :/

**Comment by youradds** [comment] 2017-05-06 17:35
@chrisfromthelc - what versions of WP/WooCommerce/Artificer are you using btw? (where it works)

**Comment by carasmo** [comment] 2017-05-06 17:45
I am using the latest version of all. Works fine. And the _featured key is found with a search in phpMyAdmin in my database. Those are my featured images with Yes. 
![screen shot 2017-05-06 at 1 43 27 pm](https://cloud.githubusercontent.com/assets/1124594/25774673/1e78a406-3262-11e7-87ee-e2aa39767e2c.png)

**Comment by SewStylish** [comment] 2017-05-06 17:48
I just set up a brand new site today for a friend. Latest version of WP, latest WooCommerce and latest Artificer. And no, I can't get any featured products on the front page. Decided to test with a brand new site, and still it won't work for me.  See here - http://homemadebytheheart.com/
This is what it should look like, and what it did look like before the Updates - https://sewstylishbags.com/
That one is still on the old theme and the old WC.

**Comment by youradds** [comment] 2017-05-06 18:29
@carasmo  - mm, that makes no sense at all. If I run:

`SELECT * FROM wp_postmeta WHERE meta_key = '_featured' `

...I get 0 rows. Eugh, so frustrating! 

I get 0 rows

**Comment by carasmo** [comment] 2017-05-06 18:39
It's very odd. Your site prints the html but no content. Have you tried the product widget to see if that "SEES" featured products?
![screen shot 2017-05-06 at 2 22 48 pm](https://cloud.githubusercontent.com/assets/1124594/25774955/a34dd0a2-3267-11e7-9bdb-7b35ef6bd32c.png)

Anyway, I can't help since I can't reproduce. You might want to rename this thread more accurately to reflect the issue.

**Comment by SewStylish** [comment] 2017-05-06 18:50
That's interesting @carasmo . If I add the products widget to my sidebar and select Featured products, yes, there they are.  If I uncheck the star and refresh the page, it's gone from the widget. So the widget seems to certainly be finding products that are marked as featured. Just not the front page!

**Comment by carasmo** [comment] 2017-05-06 21:42
@SewStylish :: keep this thread updated. I'm curious to find out what is up. On the site you are testing with, try this test code (linked below and clearly commented) replace the index.php file (copy it first). This is the same index.php file from the theme you're using but it has a test loop. See if this works. 

https://gist.github.com/carasmo/5751d529fb3a404f3e2768e59de17dec#file-test-index-page-php 

Get The second gist on this page with the file name file-test-index-page-php.php NOT the first one. View raw and replace your TEST index.php file on the site you are testing but back it up first. Use FTP to edit files.

**Comment by SewStylish** [comment] 2017-05-06 22:37
Sorry @carasmo , your instructions might well be Klingon. I'm not any kind of a developer or coder, just a regular WordPress user trying to find an answer. I don't know how to do what you are asking. But thanks for trying!

**Comment by youradds** [comment] 2017-05-07 05:25
@carasmo  - I just did that, but I don't see anything extra coming up?

https://thecostumerooms.co.uk/test/

You will need to edit your local hosts file to see this, as the "live" version is on another server ATM. 

`213.219.38.44  thecostumerooms.co.uk www.thecostumerooms.co.uk`

**Comment by mikejolley** [comment] 2017-05-07 15:41
Folks, please see https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#product-visibility-is-taxonomy-based-instead-of-meta-based

Featured was meta in 2.6, but is a taxonomy (for performance!) in 3.0 - so adjust queries to use tax_query instead of meta_query accordingly. 

https://gist.github.com/ciorici/5a9a8a8ed1545e15ea8b2d55b3b46f6a

**Closed by mikejolley** 2017-05-07 15:41 UTC

**Comment by carasmo** [comment] 2017-05-07 15:56
Thanks! Totally missed this. That is much easier to loop with.

**Comment by carasmo** [comment] 2017-05-07 16:24
@SewStylish -- the answer is updated WPSE https://wordpress.stackexchange.com/questions/265967/debugging-why-featured-images-have-stopped-showing-in-woocommerce-on-the-homepag/266154#266154

**Comment by youradds** [comment] 2017-05-08 05:55
@mikejolley - awesome, thanks!

**Comment by mediastuttgart** [comment] 2017-05-10 09:03
this change also breaks `pre_get_posts` if you want to show featured products first

```php
function show_featured_products_first($query) {
	$query->set('orderby', 'meta_value date');
	$query->set('meta_key', '_featured');
	
	return $query;
}

add_action('pre_get_posts', 'show_featured_products_first');
```

doing something like this will result in only showing the featured products

```php
$query->set('tax_query', [
	[
		'taxonomy' => 'product_visibility',
		'field'    => 'name',
		'terms'    => 'featured',
	]
]);
```

any ideas how to solve this?

**Comment by piotrdu** [comment] 2018-02-06 11:58
I have problem with old template :-(, Maybe someone will help me. 

`if($type == 'feautured'){
		$args = array( 'post_type' => 'product', 'orderby'=>'rand', 'posts_per_page' => $showpost ,'meta_query' => array(
			array(
				'key' => '_visibility',
				'value' => array('catalog', 'visible'),
				'compare' => 'IN'
			),
			array(
				'key' => '_featured',
				'value' => 'yes'
			) ), 'tax_query' => array( 
                     array (
                      'taxonomy' => 'product_cat',
                      'field' => 'id',
                      'terms' => $categories
                     ), 
                 ) );


		$pc = new WP_Query( $args );
	
	}
`

**Comment by piotrdu** [comment] 2018-02-06 12:03
I have problem with featured products on home page, mayby someone help me, thx.
My code:

 if($type == 'feautured'){
		$args = array( 'post_type' => 'product', 'orderby'=>'rand', 'posts_per_page' => $showpost ,'meta_query' => array(
			array(
				'key' => '_visibility',
				'value' => array('catalog', 'visible'),
				'compare' => 'IN'
			),
			array(
				'key' => '_featured',
				'value' => 'yes'
			) ), 'tax_query' => array( 
                     array (
                      'taxonomy' => 'product_cat',
                      'field' => 'id',
                      'terms' => $categories
                     ), 
                 ) );


		$pc = new WP_Query( $args );
	
	}
