### ISSUE TITLE
Woocommerce order template

### ISSUE THREAD

**Issue by masilat** [woocommerce/woocommerce#22358] opened 2019-01-07 16:27 UTC
In the 3.4 version of woocommerce the customer processing order template body message was:
"Your order has been received and is now being processed. Your order details are shown below for your reference"

But in the 3.4 version that message changed with:
"Just to let you know — your payment has been confirmed, and order #%s is now being processed"
Even subject also changed.

I want to know it is an error or woocommerce changed it completely? Because In cash on delivery scenario people don't get payment in advance

**Comment by masilat** [comment] 2019-01-08 07:48
Yes, I am.

**Comment by mikejolley** [comment] 2019-01-08 16:13
Duplicate of https://github.com/woocommerce/woocommerce/issues/22037

**Closed by mikejolley** 2019-01-08 16:13 UTC
