### ISSUE TITLE
WooCommerce custom order item key removed when using custom hooks

### ISSUE THREAD

**Issue by Johnny99211** [woocommerce/woocommerce#29923] opened 2021-05-17 08:00 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I'm adding a custom meta data to any order item inside the `woocommerce_reduce_order_stock` hook:

```
add_action( 'woocommerce_reduce_order_stock', 'woocommerce_reduce_order_stock_action', 10, 1 );
function woocommerce_reduce_order_stock_action( WC_Order $order ): void {
	$order_items = $order->get_items();

	if ( empty( $order_items ) ) {
		return;
	}

	foreach ( $order_items as $order_item ) {
		$data[20] = [
			'number' => 'ABC-2',
			'qty'    => 20
		];

		$order_item->update_meta_data( '_test_data', $data );
		$order_item->save();
	}
}
```

Since I want to display my custom meta in every order item meta (mails, account....), I'm using this function here:

```
add_filter( 'woocommerce_order_item_get_formatted_meta_data', 'filter_woocommerce_order_item_get_formatted_meta_data', 10, 2 );
function filter_woocommerce_order_item_get_formatted_meta_data( array $formatted_meta, WC_Order_Item $order_item ): array {
	if ( $order_item === null ) {
		return $formatted_meta;
	}

	$data = $order_item->get_meta( '_test_data' );

	if ( ! empty( $data ) ) {
		foreach ( $data as $data_set ) {
			$value = $data_set['number'] . ' (' . $data_set['qty'] . 'x)';

			$formatted_meta[] = (object) [
				'key'           => 'test',
				'display_key'   => 'Test',
				'value'         => $value,
				'display_value' => '<p>' . $value . '</p>'
			];
		}
	}

	return $formatted_meta;
}
```

So far so good. Now I'm using another hook to delete the custom meta data again, when the stock gets restored (can be triggered by setting the order to cancelled):

```
add_action( 'woocommerce_restore_order_stock', 'woocommerce_restore_order_stock_action', 10, 1 );
function woocommerce_restore_order_stock_action( $order ): void {
	$order_items = $order->get_items();

	if ( empty( $order_items ) ) {
		return;
	}
	error_log( print_r( $order_items, true ) );

	foreach ( $order_items as $order_item ) {
		if ( $order_item === null || ! is_object( $order_item ) ) {
			continue;
		}

		$data = $order_item->get_meta( '_test_data' );

		error_log( print_r( $data, true ) );

		$order_item->delete_meta_data( '_test_data' );
		$order_item->save();
	}
}
```

The strange thing is now that the delete don't works when the meta display filter `woocommerce_order_item_get_formatted_meta_data` is set. In this case the custom meta get's changed somehow as you can see in the logging here:

```
[7] => WC_Meta_Data Object
    (
        [current_data:protected] => Array
            (
                [id] => 3265
                [key] => test
                [value] => ABC-3 (3x)
            )
        [data:protected] => Array
            (
                [id] => 3265
                [key] => test
                [value] => ABC-3 (3x)
            )
    )
```

When I disable my filter hook, I'm getting back the correct meta and it can be deleted:

```
 [9] => WC_Meta_Data Object
(
    [current_data:protected] => Array
        (
            [id] => 3267
            [key] => _test_data
            [value] => Array
                (
                    [9] => Array
                        (
                            [number] => ABC-3
                            [qty] => 3
                        )
                )
        )
    [data:protected] => Array
        (
            [id] => 3267
            [key] => _test_data
            [value] => Array
                (
                    [9] => Array
                        (
                            [number] => ABC-3
                            [qty] => 3
                        )
                )
        )
)
```

Why? I'm totally confused and can't find the reason after debugging for two hours now...

Don't be confused by the meta ids... I'm using two orders here because atfer changing the status to cancelled, the meta gets changed and it don't comes back when chaging the status again e.g. to completed.

**Expected behavior**
The custom meta should be available in the restore hook too like shown in the logging output.

**Actual behavior**
The custom meta gets changed somehow during this process.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Add custom hooks from the description
2. Add a custom meta to an order item of the created order
3. Change the status of the order to cancelled
4. Experience the strange behavior

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
```
### WordPress Environment ###

<details>
WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_wsgi/3.5 Python/2.7.13 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 7.4.12
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.32
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 6.25MB
Datenbank-Datengröße: 3.41MB
Datenbank-Indexgröße: 2.84MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lmfwc_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lmfwc_generators: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lmfwc_licenses: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lmfwc_licenses_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lmfwc_products_installed_on: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 1.14MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Daten: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_posts: Daten: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_statistics_exclusions: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_statistics_search: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_useronline: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_visit: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_storeabill_documentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_documents: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_storeabill_document_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_items: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_notices: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wlm_generators: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlm_licenses: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlm_licenses_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlm_products_installed_on: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlm_rest_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woomex_exported_orders: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woomex_support: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woo_batches: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpo_wcpbn_batch_numbers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
document_template: 4
page: 11
post: 1
product: 4
product_variation: 2
revision: 6
shop_coupon: 2
shop_order: 26
shop_order_refund: 10

### Security ###

Secure connection (HTTPS): ❌
					Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (7) ###

Vendidero Helper: von Vendidero – 1.3.0
Germanized für WooCommerce: von vendidero – 3.4.8
WooCommerce Product Batch Numbers: von Alexandre Faustino – 1.2.3
WooCommerce: von Automattic – 5.3.0

### Inactive Plugins (7) ###

Germanized for WooCommerce Pro: von vendidero – 3.1.4
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 2.8.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #62 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /kasse/
Mein Konto: #9 - /mein-konto/
Allgemeine Geschäftsbedingungen: #12 - /agb/

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: http://stuartduff.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 3.5.0 – 3.6.0 ist verfügbar
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 186
Oldest: 2021-04-16 18:52:00 +0200
Newest: 2021-05-16 18:42:29 +0200

Ausstehend: 1
Oldest: 2021-05-17 18:42:29 +0200
Newest: 2021-05-17 18:42:29 +0200


### Status report information ###

Generated at: 2021-05-17 09:55:45 +02:00
```
</details>

**Comment by zhongruige** [comment] 2021-05-18 21:08
Hi @Johnny99211,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment] 2021-06-22 12:38
Hi @Johnny99211 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions.

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel.

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

Meanwhile perhaps you can use `https://developer.wordpress.org/reference/hooks/save_post_post-post_type/` instead.

**Closed by roykho** 2021-06-22 12:38 UTC
Labels: needs developer feedback
