### ISSUE TITLE
Woocommerce Product images

### ISSUE THREAD

**Issue by jarynleigh** [woocommerce/woocommerce#25397] opened 2020-01-13 20:15 UTC
I created a new product by duplicating an existing product, as they are similar set up. Uploaded a new product image. Correct photo shows in shop landing page. When you open product picture changes to original I duplicated Any ideas?

**To Reproduce**
I am having the same issue with all duplicated products.
I use the Divi Theme

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-01-14 15:21
Hi @jarynleigh,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end using the default Storefront theme:

**Shop page:**

![shop](https://user-images.githubusercontent.com/19143190/72356550-56cc6a00-36e1-11ea-8bb4-b214698a5445.jpg)

**Product page:**

![product](https://user-images.githubusercontent.com/19143190/72356564-5df37800-36e1-11ea-8bb8-44d53a065a09.jpg)

>I use the Divi Theme

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch to the default theme such as [Storefront](https://woocommerce.com/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by StroggCore** [comment] 2020-01-20 10:14
Did you try to contact the payment gateway which is connected to your Woocomerce? I think they can help you to operate with it.

**Comment by juliaamosova** [comment] 2020-01-21 11:11
Hi @jarynleigh,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-01-21 11:11 UTC
Labels: can't reproduce
