### ISSUE TITLE
get_total_spent() painfully slow

### ISSUE THREAD

**Issue by nhadsall** [woocommerce/woocommerce#25712] opened 2020-02-19 23:55 UTC
Looking at our slow query log we traced a query that has an average of 20 seconds to this function from the WC_Customer class. When external services like MailChimp enumerate customer spend, this brings our fairly large dedicated DB server to its knees. This again seems to be an issue of the infamous wp_postmeta table. I know we are working to eventually move away from this, but what can we do in the short term to not have this crash our site? Thanks!

**Comment by vedanshujain** [comment] 2020-05-13 13:20
Hi @nhadsall, can you provide more details on the exact query (of course after hiding any personal detail) so that we can find the source of this query and figure out a fix. 20s for a query is definitely not optimal. Also please add any other details that can help us if possible, like table size, any extra indexes etc.

**Comment by lkraav** [comment] 2020-05-13 20:34
This is a duplicate of https://github.com/woocommerce/woocommerce/issues/20513 and @nhadsall is already participating there.

**Comment by vedanshujain** [comment] 2020-05-14 12:27
Closing then in favor of #20513

**Closed by vedanshujain** 2020-05-14 12:27 UTC
Labels: status: needs feedback
