### ISSUE TITLE
/Order-Received opens as a blank page

### ISSUE THREAD

**Issue by source3media-creative** [woocommerce/woocommerce#19860] opened 2018-04-25 16:42 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Loaded template files into custom theme
2. Created default pages
3. Attempted to finish order and go to /order-received{order-id}

## Expected/actual behavior

When I follow those steps, I see...

![download](https://user-images.githubusercontent.com/38700936/39259822-7d77e504-4885-11e8-9596-cda331863eab.png)

I was expecting to see...
Some order information and or a thank you message.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

WordPress environment
--
Home URL: |   | http://testing.s3morder.com
Site URL: |   | http://testing.s3morder.com
WC version: |   | 3.3.4
Log directory writable: |   | /home/s3morder/public_html/wp-content/media/sites/4/wc-logs/
WP version: |   | 4.9.5
WP multisite: | yes  |  
WP memory limit: |   | 768 MB
WP debug mode: | no  | –
WP cron: | yes  |  
Language: |   | en_US

Server info: |   | Apache
-- | -- | --
PHP version: |   | 7.1.16
PHP post max size: |   | 128 MB
PHP time limit: |   | 120
PHP max input vars: |   | 3000
cURL version: |   | 7.53.0, OpenSSL/1.0.2k
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.36
Max upload size: |   | 2 MB
Default timezone is UTC: | yes  |  
fsockopen/cURL: | yes  |  
SoapClient: |  yes |  
DOMDocument: | yes  |  
GZip: | yes  |  
Multibyte string: | yes  |  
Remote post: | yes  |  
Remote get: | yes  |  

</details>

**Comment by vatri** [comment] 2018-04-26 13:19
I think I have same problem as I am getting 404 page.

I assume your page is actually 404 page but you might not have 404.php template (or something else).

I fixed problem by going to wp-admin > Settings > Permalinks > click Save ( https://docs.woocommerce.com/document/woocommerce-endpoints-2-1/#section-9 )

And it fixes the problem so correct "thank you page" is shown. But after few minutes, my client reported same problem again and I must update permalinks again.

Not sure if this is caused by some other plugin that calls "flush_rewrite_rules" or simiar function as discussed in this Ticket: https://github.com/woocommerce/woocommerce/issues/4863

Can anyone suggest us what to do?

**Comment by claudiulodro** [comment] 2018-04-26 20:43
@source3media-creative  It's impossible to tell specifically what is going on by just looking at that screenshot. Most likely you are getting a fatal error on that page caused by a bug in your custom theme. If you enable WP debug mode you can see what the specific error is when it happens, or you can check your error logs. 

@source3media-creative @vatri Easiest way to troubleshoot these problems is to switch to a default theme (Twenty Twelve) and deactivate all plugins except WooCommerce. If the problem still happens the issue is in the core WooCommerce plugin. If it doesn't happen, reactivate plugins one by one until it starts happening again, then you'll know which plugin causes the problem.

**Comment by kloon** [comment] 2018-04-30 09:33
Closing this issue, not able to recreate this on a clean WooCommerce install so it is highly likely caused by the theme or plugin. As @claudiulodro pointed out, please test by switching to a default theme like twenty seventeen or Storefront and then disable all plugins except WooCommerce and test if the issue persists. If not then re-enable plugins one by one testing in between to find the culprit and then switch back to your normal theme.

**Closed by kloon** 2018-04-30 09:33 UTC
Labels: Status: Needs Feedback

**Comment by vatri** [comment] 2018-04-30 09:46
@kloon 
@claudiulodro 

I actually tried to turn off ALL plugins and switch to Twenty Seventeen theme. The problem is still here. 

But I think this will be hard to reproduce as it might occur just in unusual cases.
