### ISSUE TITLE
WC 3.6.0 Beta 1 and Product Add-ons 3

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#23084] opened 2019-03-19 21:18 UTC
This is only a note: I had on staging site WC 3.6.0 beta 1 installed for testing purposes. All woo extension work well in case of wc except Product Add-ons. After installing beta of wc I had no access to admin. Only trashing extension by ftp access to site brought site back. There seems to be some changes in wc 3.6 which made Product Add-ons fully unusable.

**Comment by rodrigoprimo** [comment] 2019-03-20 13:32
Thanks for your report, @ajgw. I was not able to reproduce this on a quick test where I enable Product Add-ons on a WooCommerce store running 3.6.0-beta-1 and created a single product add-on. Would you be able to install the extension again in your staging environment and share the PHP error? You will find it either displayed on your browser or in the PHP error log file.

**Comment by ajgw** [comment] 2019-03-20 13:45
Well, I checked again and now I can go to wp-admin and use backend as before. But I get this on top:

- Warning: "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in …/wp-content/plugins/woocommerce-product-addons/includes/class-wc-product-addons-cart.php on line 329
- Warning: "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in …/wp-content/plugins/woocommerce-product-addons/includes/class-wc-product-addons-cart.php on line 346
- Warning: Cannot modify header information - headers already sent by (output started at …/wp-content/plugins/woocommerce-product-addons/includes/class-wc-product-addons-cart.php:329) in …/wp-admin/includes/misc.php on line 1198

I don’t know what was going on yesterday after I installed beta of WC.

**Comment by rodrigoprimo** [comment] 2019-03-20 13:57
Thanks for sharing the warnings you are seeing. @woocommerce/extendables could you please take a look and confirm if the warnings above are indeed a WooCommerce Product Add-ons issue or not?

**Comment by laurendavissmith** [comment] 2019-03-20 14:02
thanks for the report! we will be starting our compatibility testing for all of our extensions next week so we'll let you know what we find here

**Comment by ajgw** [comment] 2019-03-20 14:05
I’ve checked again with all plugins deactivated except WC 3.6.0 beta 1. After I activated Product Add-ons, this warning came up again. Thanks.

**Comment by budzanowski** [comment] 2019-03-20 14:10
@ajgw could you please provide your PHP version? It looks like the warnings are PHP related and not WC.

**Comment by ajgw** [comment] 2019-03-20 14:15
Hmm, I  use PHP 7.3.2-nmm1

**Comment by ajgw** [comment] 2019-03-20 14:18
You are right. Tried PHP 7.2.13 and warnig is gone. Thanks.

**Comment by budzanowski** [comment] 2019-03-20 14:19
We still need to fix the warning :P creating a PAO issue for that and closing this one.

**Closed by budzanowski** 2019-03-20 14:19 UTC
Labels: status: needs feedback
