### ISSUE TITLE
Missing Attributes and SKU ID for products that are in checkout and invoice( woocommerce )

### ISSUE THREAD

**Issue by nadiyasri195** [woocommerce/woocommerce#21502] opened 2018-10-05 19:41 UTC
Hi there, 

I'm using woocommerce checkout field editor pro plugin.

I have an issue on invoice and billing info page, for some of the products, it's missing SKU and variation id and attributes. but it's displaying some products though.

I checked all, but I could figure out the issue. please help me, if you know how to fix this issue.

here are the scrren for the issues: 
![ss1](https://user-images.githubusercontent.com/43892996/46556483-a9429800-c89b-11e8-9ec3-49edb7b931a4.JPG)

![image](https://user-images.githubusercontent.com/43892996/46556589-f32b7e00-c89b-11e8-9377-1e767285a1e7.png)

please help me, to fix it.

**Comment by claudiulodro** [comment] 2018-10-10 18:29
Hi there,

I was not able to reproduce this on a site running only WooCommerce. Clearly the order information is there because it shows up in the admin, so this seems to be an issue with either your theme or one of your other active plugins. I recommend going through the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if that will help pinpoint your problem. You have not really provided any other information that could help us troubleshoot this problem further, so I am closing this as non-reproducible.

Thanks.

**Closed by claudiulodro** 2018-10-10 18:29 UTC
