### ISSUE TITLE
Warning using the update_attributes method on WC_Product_Variation_Data_Store_CPT

### ISSUE THREAD

**Issue by gonzalesc** [woocommerce/woocommerce#27486] opened 2020-08-25 20:16 UTC
I'm creaing a variation using:

```
$Variation = new WC_Product_Variation();
...
...
$variation_id = $Variation->save();
```

When it executes the save method, it shows a warning:

```
component: "Plugin: woocommerce"
file: "wp-includes/taxonomy.php"
key: "acd43dfe78b7d050affffc9d50675187"
line: 1785
message: "array_map(): Argument #2 should be an array"

```

This error comes from:  **includes/data-stores/class-wc-product-variation-data-store-cpt.php** 
Method : **update_attributes()**
Line: **509**
Commit: **9c6c0d73d817328e3a90b6e3e0b1b0f0b7662270**

In this code is the error:

```
// ...and remove old taxonomy terms.
$attributes_to_delete = array_diff( wc_get_attribute_taxonomy_names(), array_keys( $attributes ) );
wp_delete_object_term_relationships( $product_id, $attributes_to_delete );
```

The "wp_delete_object_term_relationships" function doesn't validate if the taxonomy (attribute) exist to this product ($product_id), so it shows a warning.

Regards

**Comment by Konamiman** [comment] 2020-08-26 14:42
@gonzalesc Thanks for reporting the issue. I'm working on fixing other issues with the code that handles variable product attributes so I'll add this to the list of stuff to fix.

**Comment by Konamiman** [comment] 2020-08-28 09:21
Hi @gonzalesc. For what I see in the code the problem seems to be that the taxonomy doesn't exist in general, not that it doesn't exist for the product.

Could you please provide more details on your setup (e.g. the defined taxonomies) and a complete code snippet to reproduce the problem?

**Comment by gonzalesc** [comment] 2020-08-28 23:10
Hi.

The "_wp_delete_object_term_relationships_" function call to this functions :

`$term_ids = wp_get_object_terms( $object_id, $taxonomy, array( 'fields' => 'ids' ) );`

And this function return a WP_Error, because WooCommerce sends taxonomies that don't belong to this $object_id ( Product ID );

**Comment by Konamiman** [comment] 2021-01-07 15:37
Hi @gonzalesc , the chunk of code that caused the warning was removed as part of a rollback in a maintenance release of WooCommerce. I'm thus closing this issue, but please comment if you encounter it again in a different place and I'll reopen it.

**Closed by Konamiman** 2021-01-07 15:37 UTC
Labels: has feedback, needs developer feedback
