### ISSUE TITLE
CRITICAL Uncaught Error: Call to a member function getOffsetTimestamp() on null

### ISSUE THREAD

**Issue by thomastthai** [woocommerce/woocommerce#19360] opened 2018-03-12 08:59 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Open Woocommerce log file
2.
3.

## Expected/actual behavior

```
2018-03-11T07:23:22+00:00 CRITICAL Uncaught Error: Call to a member function getOffsetTimestamp() on null in /var/www/golocal.cc/html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:142
Stack trace:
#0 /var/www/golocal.cc/html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php(162): Abstract_WC_Order_Data_Store_CPT->update(Object(WC_Subscription))
#1 /var/www/golocal.cc/html/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-subscription-data-store-cpt.php(120): WC_Order_Data_Store_CPT->update(Object(WC_Subscription))
#2 /var/www/golocal.cc/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(169): WCS_Subscription_Data_Store_CPT->update(Object(WC_Subscription))
#3 /var/www/golocal.cc/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(220): WC_Data_Store->update(Object(WC_Subscription))
#4 /var/www/golocal.cc/html/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php(506): WC_Order->save()
```

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://golocal.cc
Site URL: https://golocal.cc
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 7.0.27
PHP Post Max Size: 40 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 18.04MB
Database Data Size: 15.32MB
Database Index Size: 2.72MB
wp_woocommerce_sessions: Data: 3.06MB + Index: 0.24MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.05MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wppl_friends_locator: Data: 0.02MB + Index: 0.00MB
wp_bm_user_location: Data: 0.02MB + Index: 0.02MB
wp_bp_activity: Data: 0.03MB + Index: 0.03MB
wp_bp_activity_meta: Data: 0.01MB + Index: 0.01MB
wp_bp_follow: Data: 0.00MB + Index: 0.00MB
wp_bp_friends: Data: 0.00MB + Index: 0.00MB
wp_bp_groups: Data: 0.00MB + Index: 0.00MB
wp_bp_groups_groupmeta: Data: 0.00MB + Index: 0.01MB
wp_bp_groups_members: Data: 0.00MB + Index: 0.01MB
wp_bp_messages_messages: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_meta: Data: 0.00MB + Index: 0.01MB
wp_bp_messages_notices: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_recipients: Data: 0.00MB + Index: 0.01MB
wp_bp_notifications: Data: 0.01MB + Index: 0.03MB
wp_bp_notifications_meta: Data: 0.00MB + Index: 0.00MB
wp_bp_user_blogs: Data: 0.00MB + Index: 0.00MB
wp_bp_user_blogs_blogmeta: Data: 0.00MB + Index: 0.01MB
wp_bp_xprofile_data: Data: 0.01MB + Index: 0.01MB
wp_bp_xprofile_fields: Data: 0.03MB + Index: 0.05MB
wp_bp_xprofile_groups: Data: 0.00MB + Index: 0.00MB
wp_bp_xprofile_meta: Data: 0.00MB + Index: 0.01MB
wp_commentmeta: Data: 0.01MB + Index: 0.01MB
wp_comments: Data: 0.02MB + Index: 0.01MB
wp_em_bookings: Data: 0.02MB + Index: 0.00MB
wp_em_events: Data: 0.02MB + Index: 0.08MB
wp_em_locations: Data: 0.02MB + Index: 0.08MB
wp_em_meta: Data: 0.02MB + Index: 0.00MB
wp_em_tickets: Data: 0.02MB + Index: 0.00MB
wp_em_tickets_bookings: Data: 0.02MB + Index: 0.00MB
wp_facetwp_index: Data: 0.02MB + Index: 0.05MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mappress_maps: Data: 0.02MB + Index: 0.00MB
wp_mappress_posts: Data: 0.02MB + Index: 0.00MB
wp_newsletter: Data: 0.00MB + Index: 0.01MB
wp_newsletter_emails: Data: 0.00MB + Index: 0.00MB
wp_newsletter_sent: Data: 0.00MB + Index: 0.00MB
wp_newsletter_stats: Data: 0.00MB + Index: 0.00MB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB
wp_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_slides: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.46MB + Index: 0.19MB
wp_places_locator: Data: 0.02MB + Index: 0.00MB
wp_pmpro_membership_levelmeta: Data: 0.02MB + Index: 0.03MB
wp_postmeta: Data: 4.53MB + Index: 0.62MB
wp_posts: Data: 3.42MB + Index: 0.17MB
wp_pv_commission: Data: 0.01MB + Index: 0.00MB
wp_recommendposts_votes: Data: 0.00MB + Index: 0.00MB
wp_signups: Data: 0.01MB + Index: 0.01MB
wp_simple_locator_history: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.01MB + Index: 0.02MB
wp_terms: Data: 0.01MB + Index: 0.03MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.19MB + Index: 0.09MB
wp_users: Data: 0.01MB + Index: 0.02MB
wp_wcv_feedback: Data: 0.03MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_recommendations: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_session_activity: Data: 0.14MB + Index: 0.00MB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB
wp_wpsp_agent_assign_data: Data: 0.02MB + Index: 0.03MB
wp_wpsp_agent_settings: Data: 0.02MB + Index: 0.00MB
wp_wpsp_attachments: Data: 0.02MB + Index: 0.00MB
wp_wpsp_canned_reply: Data: 0.02MB + Index: 0.00MB
wp_wpsp_catagories: Data: 0.02MB + Index: 0.00MB
wp_wpsp_custom_fields: Data: 0.02MB + Index: 0.00MB
wp_wpsp_custom_priority: Data: 0.02MB + Index: 0.02MB
wp_wpsp_custom_status: Data: 0.02MB + Index: 0.02MB
wp_wpsp_faq: Data: 0.02MB + Index: 0.00MB
wp_wpsp_faq_catagories: Data: 0.02MB + Index: 0.00MB
wp_wpsp_panel_custom_menu: Data: 0.02MB + Index: 0.00MB
wp_wpsp_support_menu: Data: 0.02MB + Index: 0.00MB
wp_wpsp_ticket: Data: 0.02MB + Index: 0.20MB
wp_wpsp_ticket_form_order: Data: 0.02MB + Index: 0.00MB
wp_wpsp_ticket_list_order: Data: 0.02MB + Index: 0.00MB
wp_wpsp_ticket_thread: Data: 0.02MB + Index: 0.06MB
wp_wpsp_users: Data: 0.02MB + Index: 0.00MB
wp_wsluserscontacts: Data: 0.02MB + Index: 0.02MB
wp_wslusersprofiles: Data: 0.05MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 44
bp-email: 16
customize_changeset: 16
event: 1
forum: 10
ia_invites: 1
location: 2
mc4wp-form: 1
nav_menu_item: 89
oembed_cache: 1
omapi: 6
page: 40
post: 2
postman_sent_mail: 250
product: 5
reply: 22
revision: 410
shop_order: 15
shop_order_refund: 1
shop_order_vendor: 44
shop_subscription: 3
sp_column: 7
sp_event: 4
sp_list: 1
sp_metric: 2
sp_official: 1
sp_outcome: 4
sp_performance: 8
sp_player: 4
sp_result: 6
sp_statistic: 3
sp_table: 1
sp_team: 5
stc: 1
ticket-meta-fieldset: 4
topic: 15
tribe_events: 10
tribe_organizer: 2
tribe_rsvp_attendees: 95
tribe_rsvp_tickets: 12
tribe_venue: 5
tribe_wooticket: 23
wc_membership_plan: 11
wc_user_membership: 4
wishlist: 370
wp_router_page: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (62) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.6.8
Akismet Anti-Spam: by Automattic – 4.0.3
Autoptimize: by Frank Goossens (futtta) – 2.3.2
bbP private groups: by Robin Wilson – 3.6.6
bbPress: by The bbPress Community – 2.5.14
BuddyPress Create Group Types: by Wbcom Designs – 1.0.5
BP Events Calendar: by WPDrift – 1.0.1
BP Groups Taxo: by imath – 1.0.1
BuddyPress Reorder Tabs: by BuddyBoss – 2.0.0
BuddyPress for SportsPress: by WPDrift – 1.0.2
BP xProfile Location: by shanebp – 1.5
MarketPlace: by BuddyBoss – 1.5.6
BuddyBoss Products Updater: by BuddyBoss – 1.0.2
BuddyPress Follow: by Andy Peatling
r-a-y – 1.2.2

BuddyPress Global Search: by BuddyBoss – 1.1.8
BuddyPress Xprofile Custom Fields Type: by donmik – 2.6.3
BuddyPress: by The BuddyPress Community – 2.9.3
Check Email: by Chris Taylor – 0.5.5
Admin Columns: by AdminColumns.com – 3.1.3
Color Filters for WooCommerce: by Elementous – 1.2.2 – Not tested with the active version of WooCommerce
Event Tickets Plus: by Modern Tribe
Inc. – 4.6.2

Event Tickets: by Modern Tribe
Inc. – 4.6.3.1

The Events Calendar PRO: by Modern Tribe
Inc. – 4.4.23

FacetWP: by FacetWP
LLC – 3.1.4

Invite Anyone: by Boone Gorges – 1.3.20
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
Nav Menu Roles: by Kathy Darling – 1.9.1
Newsletter: by Stefano Lissa & The Newsletter Team – 5.2.6
Post SMTP: by Jason Hendriks
Yehuda Hassine – 1.8

Progress Bar: by Chris Reynolds – 2.1.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Remove WP Logo from Admin Bar: by Md Touhidul Sadeek – 1.0
SportsPress Pro: by ThemeBoy – 2.5.10
Subscribe To Comments: by Mark Jaquith – 2.3
The Events Calendar Category Colors: by Andy Fragen
Barry Hughes – 4.6.11

The Events Calendar: Community Events Tickets: by Modern Tribe
Inc. – 4.5.3

The Events Calendar: Community Events: by Modern Tribe
Inc. – 4.5.9

The Events Calendar: Filter Bar: by Modern Tribe
Inc. – 4.5.3

The Events Calendar Shortcode: by Event Calendar Newsletter – 1.8
The Events Calendar: by Modern Tribe
Inc. – 4.6.12

User Tags for Wordpress: by Umesh Kumar – 1.2.6
WC Vendors - Stripe Commissions & Gateway: by WC Vendors – 1.0.5
WC Vendors Pro: by WC Vendors – 1.4.3
WC Vendors WooCommerce Bookings: by WC Vendors – 1.0.0 – Not tested with the active version of WooCommerce
WC Vendors: by WC Vendors – 1.9.14
WC4BP -> Groups: by ThemeKraft – 1.1.1 – Not tested with the active version of WooCommerce
WooCommerce Bookings: by Automattic – 1.10.2 – 1.10.12 is available – Not tested with the active version of WooCommerce
WooCommerce for SportsPress: by WordPay – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.8.4 – 1.9.8 is available – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.11
WooCommerce Product Reviews Pro: by SkyVerge – 1.8.0 – 1.11.0 is available – Not tested with the active version of WooCommerce
WooCommerce Recommendation Engine: by Lucas Stark – 3.1.4 – 3.1.9 is available – Not tested with the active version of WooCommerce
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0 – Not tested with the active version of WooCommerce

WooCommerce Subscription Downloads: by WooCommerce – 1.1.6 – 1.1.15 is available – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.6 – 2.2.18 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.3
Yoast SEO: by Team Yoast – 7.0.2
WordPress Social Login: by Miled – 2.3.3
WP Smush: by WPMU DEV – 2.7.8
WP Super Cache: by Automattic – 1.5.9
WPFront User Role Editor: by Syam Mohan – 2.14.1
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.6.4 – Not tested with the active version of WooCommerce


### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #58 - /shop/
Cart: #59 - /cart/
Checkout: #60 - /checkout/
My account: #61 - /my-account/
Terms and conditions: #2197 - /additional-terms/

### Theme ###

Name: OneSocial Child Theme
Version: 1.4.2
Author URL: http://www.buddyboss.com
Child Theme: ✔
Parent Theme Name: OneSocial
Parent Theme Version: 1.4.4
Parent Theme Author URL: https://www.buddyboss.com
WooCommerce Support: ✔

### Templates ###

Overrides: /var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/archive-product.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/cart/cart-empty.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/checkout/form-billing.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/checkout/form-checkout.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/checkout/thankyou.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/content-product_cat.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/loop/orderby.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/loop/result-count.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/order/order-details-customer.php
onesocial/woocommerce/product-searchform.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/meta.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/product-image.php version 3.1.0 is out of date. The core version is 3.3.2
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/product-thumbnails.php version 3.1.0 is out of date. The core version is 3.3.2
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/short-description.php
/var/www/golocal.cc/html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/up-sells.php

Outdated Templates: ❌Learn how to update

### WC Vendors Pro ###

Theme Compatability: -
Pro Dashboard Page: ✕ -Your pro dashboard page cannot be set to your free dashboard page. Click here to change.
Feedback form page: - #978
Vendor Shop Permalink: - vendors/

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
```
</details>

**Comment by claudiosanches** [comment] 2018-03-12 14:30
Unable to reproduce this steps, and sounds like something from WooCommerce Subscriptions, so better report on https://woocommerce.com/my-account/create-a-ticket/
Closing since does not sound like an issue on WooCommerce core.

**Closed by claudiosanches** 2018-03-12 14:30 UTC
