### ISSUE TITLE
Product Title appearing in Quantity Label

### ISSUE THREAD

**Issue by skillmatic-co** [woocommerce/woocommerce#24234] opened 2019-07-25 19:21 UTC
This is an odd issue, but after updating WooCommerce, on my product pages, the product title is appearing inside the Quantity label.

1. Go to https://overthemoon.com/product/blue-silk-alexandra-robe-daphne-newman/
2. Scroll down to Quantity field (I have the label hidden for now because of this issue but you can inspect)
3. See product title getting added to Quantity label.

**Screenshots**
https://i.imgur.com/p1X48dZ.png

**Expected behavior**
The product title doesn't appear here.

A quick Google shows one person seeming to have the same issue: https://generatepress.com/forums/topic/woocommerce-gp-appending-product-name-in-front-of-quantity-box/

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://overthemoon.com
Site address (URL): https://overthemoon.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
Total Database Size: 551.34MB
Database Data Size: 519.35MB
Database Index Size: 31.99MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.07MB + Index: 0.04MB
wp_woocommerce_order_itemmeta: Data: 0.57MB + Index: 0.38MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.19MB + Index: 0.04MB
wp_comments: Data: 0.45MB + Index: 0.17MB
wp_gf_addon_feed: Data: 0.00MB + Index: 0.00MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 2.52MB + Index: 0.44MB
wp_gf_entry_meta: Data: 4.52MB + Index: 5.55MB
wp_gf_entry_notes: Data: 1.52MB + Index: 0.28MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.06MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.17MB + Index: 0.16MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 14.04MB + Index: 0.19MB
wp_popularpostsdata: Data: 0.28MB + Index: 0.00MB
wp_popularpostsdatacache: Data: 1.52MB + Index: 0.00MB
wp_postmeta: Data: 399.50MB + Index: 11.91MB
wp_posts: Data: 78.82MB + Index: 3.76MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.06MB + Index: 0.00MB
wp_rg_form_view: Data: 0.17MB + Index: 0.16MB
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB
wp_rg_lead: Data: 2.52MB + Index: 0.38MB
wp_rg_lead_detail: Data: 1.52MB + Index: 3.69MB
wp_rg_lead_detail_long: Data: 2.52MB + Index: 0.00MB
wp_rg_lead_meta: Data: 2.52MB + Index: 3.39MB
wp_rg_lead_notes: Data: 1.52MB + Index: 0.28MB
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB
wp_sm_sync: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.01MB + Index: 0.01MB
wp_terms: Data: 0.02MB + Index: 0.04MB
wp_term_relationships: Data: 0.06MB + Index: 0.12MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 0.08MB + Index: 0.06MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.23MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 1.64MB + Index: 0.38MB
wp_wfHits: Data: 0.01MB + Index: 0.00MB
wp_wfHoover: Data: 0.21MB + Index: 0.03MB
wp_wfIssues: Data: 0.00MB + Index: 0.00MB
wp_wfKnownFileList: Data: 0.81MB + Index: 0.11MB
wp_wfLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.00MB + Index: 0.00MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.00MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.00MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.01MB + Index: 0.01MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.93MB + Index: 0.16MB
wp_yoast_seo_meta: Data: 0.03MB + Index: 0.03MB

### Post Type Counts ###

acf-field: 29
acf-field-group: 10
attachment: 34198
custom_css: 1
customize_changeset: 2
global_product_addon: 5
nav_menu_item: 18
oembed_cache: 89
page: 15
post: 1176
press: 19
product: 169
product_variation: 548
revision: 12829
scheduled-action: 93
shop_coupon: 1
shop_order: 573
shop_order_refund: 4
tweets: 970

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Gravity Forms: by rocketgenius – 1.9.17.5
Adminimize: by Frank Bültge – 1.11.5
Advanced Custom Fields PRO: by Elliot Condon – 5.8.2
Akismet Anti-Spam: by Automattic – 4.1.2
Classic Editor: by WordPress Contributors – 1.5
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Fast Velocity Minify: by Raul Peixoto – 2.7.0
Gravity Forms MailChimp Add-On: by rocketgenius – 4.2
Instagram: by DJ Mosca – 1.0
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.4.9
Public Post Preview: by Dominik Schilling – 2.9.0
rewardStyle: by DJ Mosca – 1.0
Rich Text Excerpts: by Peter Edwards  – 1.3.4
Search Regex: by John Godley – 1.4.16
Simple Page Ordering: by Jake Goldman
10up – 2.3.2

TinyMCE Advanced: by Andrew Ozz – 5.2.1
WooCommerce Checkout Add-Ons: by SkyVerge – 1.12.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.16
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3
WooCommerce Product Add-ons: by WooCommerce – 2.9.2 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.5
Yoast SEO: by Team Yoast – 11.7 – Not tested with the active version of WooCommerce
WP Rocket: by WP Media – 3.1.4

### Inactive Plugins (22) ###

Advanced Custom Fields: rewardStyle Products: by DJ Mosca – 1.0.0
Autoptimize: by Frank Goossens (futtta) – 2.5.1
Check Email: by Chris Taylor – 0.5.6
Debug This: by Brian Fegter
Chris Dillon – 0.6.1

Far Future Expiration Plugin: by Tips and Tricks HQ – 1.4
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
ImageMagick Engine: by Orangelab – 1.5.4
ImageMagick Sharpen Resized Images: by Hans van Eijsden,niwreg – 1.1.7
Imagify: by WP Media – 1.9.6
Instagram Slider Widget: by jetonr – 12.1.2
ManageWP - Worker: by GoDaddy – 4.8.1
My Eyes Are Up Here: by interconnect/it – 1.1.10
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.3

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
rewardStyle Widget: by rewardStyle – 1.56
Search & Replace: by Inpsyde GmbH – 3.2.1
Smush: by WPMU DEV – 3.2.2.1
Wordpress Popular Posts: by Héctor Cabrera – 21.3.7
WP-Stateless: by Usability Dynamics
Inc. – 2.2.7

WP Mail SMTP: by WPForms – 1.5.2
WP Migrate DB Pro: by Delicious Brains – 1.7.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (3) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
Stop long comments: by WPEngine – 0.0.4
WP Engine System: by WP Engine – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #46969 - /shop/
Cart: #46970 - /cart/
Checkout: #46971 - /checkout/
My account: #46972 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Over the Moon
Version: 2.0.0
Author URL: http://www.mindblownmedia.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: overthemoonblog/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
overthemoonblog/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.5.0
overthemoonblog/woocommerce/cart/cart-shipping.php version 2.3.0 is out of date. The core version is 3.6.0
overthemoonblog/woocommerce/cart/cart-totals.php
overthemoonblog/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.5.0
overthemoonblog/woocommerce/cart/mini-cart.php version 2.1.0 is out of date. The core version is 3.5.0
overthemoonblog/woocommerce/cart/proceed-to-checkout-button.php
overthemoonblog/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.5.0
overthemoonblog/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.4.4
overthemoonblog/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.6.0
overthemoonblog/woocommerce/content-widget-product.php version 2.5.0 is out of date. The core version is 3.5.5
overthemoonblog/woocommerce/emails/customer-processing-order.php version 2.5.0 is out of date. The core version is 3.5.4
overthemoonblog/woocommerce/emails/email-styles.php version 2.3.0 is out of date. The core version is 3.3.0
overthemoonblog/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
overthemoonblog/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
overthemoonblog/woocommerce/loop/loop-end.php
overthemoonblog/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
overthemoonblog/woocommerce/loop/no-products-found.php
overthemoonblog/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.6.0
overthemoonblog/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
overthemoonblog/woocommerce/myaccount/my-account.php version 2.6.0 is out of date. The core version is 3.5.0
overthemoonblog/woocommerce/myaccount/orders.php version 3.0.0 is out of date. The core version is 3.2.0
overthemoonblog/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.5.1
overthemoonblog/woocommerce/single-product/related.php
overthemoonblog/woocommerce/single-product/share.php version 1.6.4 is out of date. The core version is 3.5.0
overthemoonblog/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 93
Oldest: 2019-07-24 11:05:50 -0400
Newest: 2019-07-24 11:06:11 -0400

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```
</details>

**Comment by skillmatic-co** [comment] 2019-07-25 20:21
I ended up having to put a bandaid on it for the client but if you view source, instead of inspecting the dom, you can still see it being added.

**Comment by malviyaritesh** [comment] 2019-07-29 10:08
The quantity label is added for accessibility purposes. You can see that it has `screen-reader-text` class, so by default it should not be visible in browser.

https://github.com/woocommerce/woocommerce/blob/672f45881e3d703fa093e30757bd02d88ec29240/templates/global/quantity-input.php#L28-L32

However, if its visible on your site, then it may be because that either your theme didn't provided styles for this required class or it was overridden. As mentioned in WordPress [documentation](https://make.wordpress.org/accessibility/handbook/markup/the-css-class-screen-reader-text/):

> The CSS class screen-reader-text is a WordPress Generated Class. Each theme should have these styles in its CSS.

You can make the styles for `screen-reader-text` class available on product page.

```css
/* Text meant only for screen readers. */
.screen-reader-text {
	border: 0;
	clip: rect(1px, 1px, 1px, 1px);
	clip-path: inset(50%);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute !important;
	width: 1px;
	word-wrap: normal !important; /* Many screen reader and browser combinations announce broken words as they would appear visually. */
}

.screen-reader-text:focus {
	background-color: #eee;
	clip: auto !important;
	clip-path: none;
	color: #444;
	display: block;
	font-size: 1em;
	height: auto;
	left: 5px;
	line-height: normal;
	padding: 15px 23px 14px;
	text-decoration: none;
	top: 5px;
	width: auto;
	z-index: 100000;
	/* Above WP toolbar. */
}
```

**Comment by rodrigoprimo** [comment] 2019-07-30 22:56
Hi there!

It seems that the issue that you are experiencing is caused by your theme and not WooCommerce core. GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. You could try contacting the developers of your theme. You could also try the WooCommerce support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

What @malviyaritesh said above might also help.

Closing this issue for now. If I misunderstood something and you believe your problem is caused by a WooCommerce bug, please try to reproduce it using one of the default WordPress themes or Storefront. If the same error happens, let me know and I will take a look. Thanks.

**Closed by rodrigoprimo** 2019-07-30 22:56 UTC
