### ISSUE TITLE
every checkout visitor the system count it as a sale

### ISSUE THREAD

**Issue by jimbardim** [woocommerce/woocommerce#27659] opened 2020-09-12 00:59 UTC
hello my site is sentralshop.com
the problem is everytime someone go into my site and add a product to cart>> then to checkout

without even add his information or anything the system in the dashboard count it as a sale

https://ibb.co/wdJZC5m

i don't use many plugins
and the ones i use are pretty much standard
really simple ssl
paypal
stripe
product blocks

**Comment by nielslange** [comment] 2020-09-13 07:37
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
Contact WooCommerce support by opening a ticket.
https://woocommerce.com/contact-us/ 

**For help with custom code**
WooCommerce Slack Community: https://woocommerce.com/community-slack/ in the `#developers` channel. 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The Official WooCommerce Facebook Group https://www.facebook.com/groups/advanced.woocommerce/

**Comment by senadir** [comment] 2020-09-13 20:41
This happens on Checkout block only and is reported here https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3132, this is the intended behavior, that order is used to hold the customer data and order data before it transitions to another status, you shouldn't see that order in the analytics page and that bug is reported here https://github.com/woocommerce/woocommerce-admin/issues/5131

I'm going to close this issue for now because it's duplicate, if you can reproduce this using the classic checkout (shortcode checkout) open this issue again.

**Closed by senadir** 2020-09-13 20:41 UTC
