### ISSUE TITLE
line_items missing on GET request

### ISSUE THREAD

**Issue by Jannickla** [woocommerce/woocommerce#28222] opened 2020-11-09 22:34 UTC
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Fetching data from the API in django/python returns an emptly list of line_items on ~3400 of ~3800 orders. 

**Expected behavior**
Returning a list of dicts containing products purchased with the order

**Actual behavior**
Seems like it only returns dicts in line_items on the newer orders.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

```
view:
class WooAPICall(View):
    wcapi = API(
        url="call.domain",
        consumer_key="call.key",
        consumer_secret="call.secret",
        version="wc/v3"
    )


class TestOrder(WooAPICall):
    template_name = 'test.html'
    order_model = WCOrder.objects.all()
    def get(self, request, *args, **kwargs):
        orders = WooAPICall.wcapi.get("orders").json()
        for order in orders:
            res_order_items = order['line_items']
                for item in res_order_items:
                    b = WCOrderItem(
                        order_item_id=item['id'],
                        quantity=item['quantity'],
                        name=item['name'],
                        product_id=item['product_id'],
                        variation_id=item['variation_id'],
                        tax_class=item['tax_class'],
                        subtotal=item['subtotal'],
                        subtotal_tax=item['subtotal_tax'],
                        total=item['total'],
                        total_tax=item['total_tax'],
                        sku=item['sku'],
                        price=item['price'],
                    )
                    b.save()
```

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://kanel25aar.dk
Site address (URL): https://kanel25aar.dk
WC Version: 4.6.2
REST API Version: ✔ 4.6.2
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.12
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.7.31-34-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.2
WC Database Prefix: clk_e4be25fdeb_wp_
Total databasestørrelse: 82.50MB
Database datastørrelse: 56.37MB
Database indexstørrelse: 26.13MB
clk_e4be25fdeb_wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_actionscheduler_actions: Data: 2.52MB + Index: 1.22MB + Engine InnoDB
clk_e4be25fdeb_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_actionscheduler_logs: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
clk_e4be25fdeb_wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_comments: Data: 2.52MB + Index: 1.91MB + Engine InnoDB
clk_e4be25fdeb_wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_options: Data: 18.41MB + Index: 0.53MB + Engine InnoDB
clk_e4be25fdeb_wp_pakkelabel_shipping_diffrentiated: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_postmark_log: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_postmeta: Data: 17.55MB + Index: 19.06MB + Engine InnoDB
clk_e4be25fdeb_wp_posts: Data: 9.52MB + Index: 0.83MB + Engine InnoDB
clk_e4be25fdeb_wp_po_plugins: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
clk_e4be25fdeb_wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_css: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_css_bkp: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_sliders: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_sliders_bkp: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_slides: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_slides_bkp: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_static_slides: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_revslider_static_slides_bkp: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_yoast_indexable: Data: 0.27MB + Index: 0.31MB + Engine InnoDB
clk_e4be25fdeb_wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
clk_e4be25fdeb_wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
clk_e4be25fdeb_wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
clk_e4be25fdeb_wp_yoast_seo_links: Data: 0.13MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

amn_mi-lite: 3
attachment: 195
custom_css: 2
fusion_element: 1
nav_menu_item: 40
oembed_cache: 10
page: 39
post: 2
product: 30
revision: 325
schema: 2
shop_order: 4141
shop_order_refund: 35
wpcf7_contact_form: 1
ycdcountdown: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Bambora Online ePay: af Bambora Online – 5.1.4 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.6.2
Contact Form 7: af Takayuki Miyoshi – 5.3
Facebook for WooCommerce: af Facebook – 2.1.4
Avada Builder: af ThemeFusion – 3.1.1
Avada Core: af ThemeFusion – 5.1.1
Google Analytics for WordPress by MonsterInsights: af MonsterInsights – 7.13.0
Kadence WooCommerce E-mail Designer: af Kadence WP – 1.4.3 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.6.2
KP Fastest External Scripts: af Kreativo Pro – 1.0.0
Loco Translate: af Tim Whitlock – 2.4.4
SOGO Add Script Header Footer: af orenhav (SOGO) – 3.9
Postmark (Official): af Andrew Yates & Matt Gibbs – 1.13.3
Slider Revolution: af ThemePunch – 6.2.23
UpdraftPlus - Backup/Restore: af UpdraftPlus.Com
DavidAnderson – 2.16.6.0

W3 Total Cache: af BoldGrid – 0.15.1
Webshipper - Automated Shipping: af Webshipper – 1.3.6 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.6.2
Checkout Field Editor for WooCommerce: af ThemeHigh – 1.4.4 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.6.2
Product Feed PRO for WooCommerce: af AdTribes.io – 9.0.4
Viabill PriceTags: af cm-telecom.dk – 1.3 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.6.2
WooCommerce: af Automattic – 4.6.2
Yoast SEO: af Team Yoast – 15.2.1

### Inactive Plugins (0) ###


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: db.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop basisside: ❌ Siden er ikke indstillet
Kurv: #175 - /kurv/
Checkout: #176 - /checkout/
Min konto: ❌ Siden er ikke indstillet
Vilkår og betingelser: #1256 - /handelsbetingelser/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.1.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### Action Scheduler ###

Gennemført: 1.289
Oldest: 2020-10-10 09:53:25 +0000
Newest: 2020-11-09 21:30:32 +0000

Mislykket: 4
Oldest: 2019-10-25 05:57:28 +0000
Newest: 2020-08-04 08:11:39 +0000

`
```
</details>

**Comment by rrennick** [comment] 2021-01-21 19:15
Hi @Jannickla,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rrennick** 2021-01-21 19:15 UTC
