### ISSUE TITLE
[Globalstep-WooCommerce 5.2 Beta] On Installed plugins page, "There is new update for WooCommerce" message is displayed under WooCommerce plugin even if the WooCommerce version is switched to the latest version. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29482] opened 2021-03-24 18:28 UTC
## Bug Description:
On Installed plugins page, "There is new update for WooCommerce" message is displayed under WooCommerce plugin even if the WooCommerce version is switched to the latest version. 

## Environment:
Woocommerce Version : WooCommerce 5.2 beta
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Skip the onboarding setup wizard.
1. Go to WC beta Tester.
1. Switch the WooCommerce version to 5.2 beta.
1. Go to Plugins->Installed plugins page.
1. Observe that "There is new update for WooCommerce" message is displayed under WooCommerce plugin.

## Actual Result:
On Installed plugins page, "There is new update for WooCommerce" message is displayed under WooCommerce plugin even if the WooCommerce version is switched to the latest version. 

## Expected Result:
On Installed plugins page, "There is new update for WooCommerce" message is should not be displayed under WooCommerce plugin if the WooCommerce version is switched to the latest version. 

## ScreenShot:
![#29482](https://user-images.githubusercontent.com/41110392/112366433-cd5df200-8cfe-11eb-8eb7-3734d13e3c42.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://beautiful-gull.jurassic.ninja
Site address (URL): https://beautiful-gull.jurassic.ninja
WC Version: 5.2.0
REST API Version: ✔ 5.2.0
WC Blocks Version: ✔ 4.7.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.3
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Total Database Size: 4.57MB
Database Data Size: 3.10MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 8
nav_menu_item: 5
page: 13
post: 2
product: 19
product_variation: 7
revision: 8
shop_order: 2
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Query Monitor: by John Blackbourn – 3.6.7
Companion Plugin: by Osk – 1.18
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Gutenberg: by Gutenberg Team – 10.2.1
Jetpack by WordPress.com: by Automattic – 9.5
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce: by Automattic – 5.2.0-beta (update to version 5.2.0-beta.1 is available)
WP phpMyAdmin: by Puvox.software – 5.0.4.1

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Admin: by WooCommerce – 2.1.3

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 13
Oldest: 2021-03-24 07:39:52 +0000
Newest: 2021-03-24 16:33:42 +0000


### Status report information ###

Generated at: 2021-03-24 17:34:13 +00:00
`
```
</details>

**Comment by tammullen** [comment] 2021-03-26 16:27
Hi @gglobalstep 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Although this is occuring because of the Beta Tester plugin I believe it is due to the name being used in core here
https://github.com/woocommerce/woocommerce/blob/a1a89492da43d53ec4e36408cfafbd3719ff41a5/woocommerce.php#L6

This will be updated with the next pre-release version and we can check it again at that point .

**Comment by rrennick** [comment] 2023-06-19 19:57
Closing as fixed.

**Closed by rrennick** 2023-06-19 19:57 UTC
Labels: type: bug, priority: low, plugin: woocommerce
