### ISSUE TITLE
After the update to woocommerce 4.1.1, when I add new product with variations, the stock status is always out-of-stock. I cannot change it back to in-stock

### ISSUE THREAD

**Issue by nesearin** [woocommerce/woocommerce#26650] opened 2020-06-01 09:26 UTC
**Describe the bug**
I don't manage stock quantity. When I used to add any new product, the status was in-stock until I changed it to another status. After the update, the basic products are added without problem. But when I add a product with variations, the status is out-of-stock and I cannot change it back to in-stock no matter what I tried. The old products in the DB seem fine. The problems is about the new ones with variations. 

I have disabled all the plugins, even the very irrelevant ones. It didn't work. There may be a conflict between theme or DB. I updated them too. But it didn't help.

**To Reproduce**
1. Go to products
2. Add a new product with variations.
3. Set stock status to in-stock.
4. Save.
5. It appears out-of-stock in the admin side products page.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://activist.team
Site address (URL): https://activist.team
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) OpenSSL/1.0.1e-fips
PHP Version: 7.2.24
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 2500
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.30-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Toplam veritabanı boyutu: 19.13MB
Veritabanı veri boyutu: 14.00MB
Veritabanı indis boyutu: 5.13MB
wp_woocommerce_sessions: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_woocommerce_api_keys: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Veriler: 0.02 MB + Dizin: 0.06 MB + Motor InnoDB
wp_woocommerce_order_items: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_tax_rates: Veriler: 0.02 MB + Dizin: 0.06 MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_shipping_zones: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_woocommerce_payment_tokens: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_log: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_actionscheduler_actions: Veriler: 1.39 MB + Dizin: 1.19 MB + Motor InnoDB
wp_actionscheduler_claims: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_actionscheduler_groups: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_actionscheduler_logs: Veriler: 0.42 MB + Dizin: 0.31 MB + Motor InnoDB
wp_adtribes_my_conversions: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_categorymeta: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_commentmeta: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_comments: Veriler: 0.02 MB + Dizin: 0.08 MB + Motor InnoDB
wp_iyzico_card: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_iyzico_order: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_links: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_mailchimp_carts: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_mailchimp_jobs: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_member_catmeta: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_ms_snippets: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_options: Veriler: 5.02 MB + Dizin: 0.25 MB + Motor InnoDB
wp_portfolio_catmeta: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_postmeta: Veriler: 3.20 MB + Dizin: 1.89 MB + Motor InnoDB
wp_posts: Veriler: 2.33 MB + Dizin: 0.30 MB + Motor InnoDB
wp_product_catmeta: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_css: Veriler: 0.13 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_css_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_layer_animations: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_layer_animations_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_navigations: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_navigations_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_sliders: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_sliders_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_slides: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_slides_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_static_slides: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_static_slides_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_snippets: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_termmeta: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_terms: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_term_relationships: Veriler: 0.09 MB + Dizin: 0.06 MB + Motor InnoDB
wp_term_taxonomy: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_usermeta: Veriler: 0.05 MB + Dizin: 0.03 MB + Motor InnoDB
wp_users: Veriler: 0.02 MB + Dizin: 0.05 MB + Motor InnoDB
wp_user_registration_sessions: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wc_admin_notes: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wc_admin_note_actions: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wc_category_lookup: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wc_customer_lookup: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_download_log: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_order_coupon_lookup: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_order_product_lookup: Veriler: 0.02 MB + Dizin: 0.06 MB + Motor InnoDB
wp_wc_order_stats: Veriler: 0.02 MB + Dizin: 0.05 MB + Motor InnoDB
wp_wc_order_tax_lookup: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_product_meta_lookup: Veriler: 0.05 MB + Dizin: 0.09 MB + Motor InnoDB
wp_wc_tax_rate_classes: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wc_webhooks: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wfpklist_template_data: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wpml_mails: Veriler: 0.16 MB + Dizin: 0.00 MB + Motor InnoDB

### Post Type Counts ###

attachment: 396
block: 20
custom_css: 1
customize_changeset: 2
faq: 12
nav_menu_item: 51
oembed_cache: 1
page: 35
post: 9
product: 177
product_variation: 133
revision: 206
shop_order: 12
shop_order_refund: 2
user_registration: 1
wpcf7_contact_form: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

BackWPup: (Inpsyde GmbH) – 3.7.1
Checkout Files Upload for WooCommerce: (WP Wham) – 1.5.4 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
Code Snippets: (Code Snippets Pro) – 2.14.0
Contact Form 7: (Takayuki Miyoshi) – 5.1.9
Delete Me: (Clinton Caldwell) – 3.0
Dynamic Featured Image: (Ankit Pokhrel) – 3.7.0
Site Kit by Google: (Google) – 1.8.1
Google XML Sitemaps: (Arne Brachhold) – 4.1.0
iyzico WooCommerce: (iyzico) – 2.0.1 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
WordPress.com’dan Jetpack: (Automattic) – 8.5
WPBakery Page Builder: (Michael M - WPBakery.com) – 6.0.5
Loco Çeviri: (Tim Whitlock) – 2.4.0
Mailchimp for WooCommerce: (Mailchimp) – 2.4.0 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
CF Page or Post Duplicator: (Carlos Fazenda) – 1.1
Porto Theme - Functionality: (P-Themes) – 1.7.0
Slider Revolution: (ThemePunch) – 6.2.6
UpdraftPlus - Backup/Restore: (UpdraftPlus.Com
DavidAnderson) – 1.16.25

Extra Product Options (Product Addons) for WooCommerce: (ThemeHigh) – 2.1.3 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
Product Feed PRO for WooCommerce: (AdTribes.io) – 8.2.8
WooCommerce Admin: (WooCommerce) – 1.1.3
WooCommerce: (Automattic) – 4.1.1
WP Mail Logging: (MailPoet) – 1.9.6
WP Mail SMTP: (WPForms) – 2.0.1

### Inactive Plugins (9) ###

Akismet Anti-Spam: (Automattic) – 4.1.5
Checkout Field Editor for WooCommerce: (ThemeHigh) – 1.4.2 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
Facebook for WooCommerce: (Facebook) – 1.11.3
Hello Dolly: (Matt Mullenweg) – 1.7.2
HookMeUp – Additional Content for WooCommerce: (GetBowtied) – 1.3.0 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
Print Invoice & Delivery Notes for WooCommerce: (Tyche Softwares) – 4.5.5 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
Sözleşmeler: (Emre Güler) – 1.6 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir
User Registration: (WPEverest) – 1.8.4
WooCommerce Product as Gift: (Codup.io) – 1.1.1.7 – Yüklü versiyon WooCommerce 4.1.1 aktif versiyonu ile test edilmemiştir

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Mağaza giriş sayfası: #207 - /shop/
Sepet sayfası: #208 - /cart/
Ödeme sayfası: #209 - /checkout/
Hesabım sayfası: #210 - /my-account/
Şartlar ve koşullar: #1937 - /kullanim-kosullari/

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 5.3.2
Parent Theme Author URL: http://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/content-product.php
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

### Action Scheduler ###

Tamamla: 1.912
Oldest: 2020-05-01 09:22:52 +0000
Newest: 2020-06-01 09:02:35 +0000

Bekliyor: 3
Oldest: 2020-06-01 09:11:31 +0000
Newest: 2020-06-01 10:02:35 +0000

`

**Comment by juliaamosova** [comment] 2020-06-01 18:34
Hi @nesearin,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

I made a video documenting my steps (tested using WooCommerce 4.1.1):

https://recordit.co/1DF1K965Om

Can you please run a full theme and plugins conflict?

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by nesearin** [comment] 2020-06-02 10:39
Hi There

I deactivated everything. And switched to store-front. The problem still continues. 
Here is the link to the screen video I make:
https://www.dropbox.com/s/58uvfxggl3boo5u/stock%20status%20issue.mov?dl=0 <https://www.dropbox.com/s/58uvfxggl3boo5u/stock%20status%20issue.mov?dl=0>


I’m also in touch with the porto theme guys. 
I’m copying their reply. You can check their video as well.
_______________________________
Hi Activist,

Please check the attached video. It is a woocommerce and WordPress issue. Settings are not saving in woo commerce when I update status of stock it does not save settings. So please contact woo and wp to solve this issue as you see it is the same issue on wp default theme so when it works on default theme then it works on Porto too it is not a theme issue.

Check your ticket status & Reply from this link: https://smartwave.freshdesk.com/helpdesk/tickets/92057 <https://smartwave.freshdesk.com/helpdesk/tickets/92057>
__________________________________

It seems that the problem is on woocommerce side.


Best regards

Nese Arin

**Comment by juliaamosova** [comment] 2020-06-02 15:40
Thanks for the follow-up and troubleshooting done @nesearin. I am thinking the issue could be related to how the server where your site is configured is set up. Can you please take a look at the doc [Problems with large amounts of data not saving (variations, rates etc)](https://docs.woocommerce.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/) and contact your hosting company to make sure the server settings are up to par with recommendations in the doc?

**Comment by nesearin** [comment] 2020-06-03 11:20
Hi Julia

Thank you for our quick response.
I’ll share your feedback with our server guy.
However,  when I select “manage stock” and enter some stock quantity for the same product, it saves without a problem and stock status turns to green. That’s why I doubt that the problem is about server settings. Would the problem be due to some DB mismatch in the Turkish version?




Best regards

**Comment by tammullen** [comment] 2021-03-24 20:18
Hi @nesearin,

Apologies for the delay in replying.

Are you still experiencing this issue?

**Comment by juliaamosova** [comment] 2021-04-02 19:26
Hi @nesearin,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-04-02 19:26 UTC
Labels: category: can't reproduce, needs feedback
