### ISSUE TITLE
Currency position issue with Israeli new shekel currency with RTL

### ISSUE THREAD

**Issue by kalonya** [woocommerce/woocommerce#24885] opened 2019-10-23 17:34 UTC
**Describe the bug**
The position of currency is not placed correctly in RTL mode with Israeli New Shekel currency.

"Left" is displayed on the left,
"Right" is displayed on the right,
"Left with space" is displayed on the right,
"Right with space" is displayed on the left.

**To Reproduce**
1. Change the Wordpress site language to Hebrew
2. Go to Woocommerce > Settings
3. Change the currency position and check the Shop / Single Product Page for each position

**Screenshots**
Currency Position: Left
<img width="675" alt="Screen Shot 2019-10-23 at 19 24 51" src="https://user-images.githubusercontent.com/16854238/67418402-ff7b9980-f5ca-11e9-9865-79de9b69d7f7.png">
Displayed on front-end:
<img width="353" alt="Screen Shot 2019-10-23 at 19 24 23" src="https://user-images.githubusercontent.com/16854238/67418462-18844a80-f5cb-11e9-84b9-c5266d1a5820.png">

Currency Position: Right
<img width="675" alt="Screen Shot 2019-10-23 at 19 24 39" src="https://user-images.githubusercontent.com/16854238/67418516-32be2880-f5cb-11e9-9b66-416a2b6a263e.png">
Displayed on front-end:
<img width="354" alt="Screen Shot 2019-10-23 at 19 24 32" src="https://user-images.githubusercontent.com/16854238/67418560-46698f00-f5cb-11e9-8841-1dc50ba990e8.png">

Currency Position: Left with space
<img width="664" alt="Screen Shot 2019-10-23 at 19 29 12" src="https://user-images.githubusercontent.com/16854238/67418620-6dc05c00-f5cb-11e9-8830-14a41e9c4efe.png">
Displayed on front-end:
<img width="367" alt="Screen Shot 2019-10-23 at 19 25 13" src="https://user-images.githubusercontent.com/16854238/67418673-86c90d00-f5cb-11e9-8331-704deed76865.png">

Currency Position: Right with space
<img width="667" alt="Screen Shot 2019-10-23 at 19 25 25" src="https://user-images.githubusercontent.com/16854238/67418715-98aab000-f5cb-11e9-8ef4-e27780e652b7.png">
Displayed on front-end:
<img width="354" alt="Screen Shot 2019-10-23 at 19 25 33" src="https://user-images.githubusercontent.com/16854238/67418733-a3654500-f5cb-11e9-9d3e-1f1c2df548c1.png">

**Expected behavior**
The currency position should be the same for Left/Left with space and Right/Right with space.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://storefront.kalonya
Site address (URL): https://storefront.kalonya
WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.3.2
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
הגודל הכולל של בסיס הנתונים: 6.14MB
גודל הנתונים של בסיס הנתונים: 4.69MB
גודל האינדקס של בסיס הנתונים: 1.45MB
wp_woocommerce_sessions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_api_keys: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_attribute_taxonomies: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_downloadable_product_permissions: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
wp_woocommerce_order_items: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_order_itemmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_tax_rates: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
wp_woocommerce_tax_rate_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_shipping_zones: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_woocommerce_shipping_zone_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_shipping_zone_methods: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_woocommerce_payment_tokens: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_payment_tokenmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_log: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_commentmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_comments: נתונים: 0.02MB + אינדקס: 0.09MB + מנוע InnoDB
wp_failed_jobs: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_links: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_mailchimp_carts: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_options: נתונים: 2.11MB + אינדקס: 0.06MB + מנוע InnoDB
wp_postmeta: נתונים: 0.36MB + אינדקס: 0.36MB + מנוע InnoDB
wp_posts: נתונים: 1.52MB + אינדקס: 0.09MB + מנוע InnoDB
wp_queue: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_social_users: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_termmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_terms: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_term_relationships: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_term_taxonomy: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_usermeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_users: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
wp_wc_download_log: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_product_meta_lookup: נתונים: 0.02MB + אינדקס: 0.09MB + מנוע InnoDB
wp_wc_tax_rate_classes: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_webhooks: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_yith_wcwl: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_yith_wcwl_lists: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_yoast_seo_links: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_yoast_seo_meta: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌יש להציג הודעות שגיאה למבקרים.

### Active Plugins (1) ###

ווקומרס: מאת חברת אוטומטיק – 3.7.1

### Inactive Plugins (24) ###

AWEOS PHP Server Info: מאת AWEOS GmbH – 1.1
Classic Editor: מאת WordPress Contributors – 1.5
Collapsing categories for WooCommmerce: מאת subhansanjaya – 0.0.2
Contact Form 7: מאת Takayuki Miyoshi – 5.1.4
Debug Bar: מאת wordpressdotorg – 1.0
Debug Bar Actions and Filters Addon: מאת Subharanjan – 1.5.4
Featured Video Plus: מאת Alexander Höreth – 2.3.3
Jetpack by WordPress.com: מאת Automattic – 7.8
Klarna Checkout for WooCommerce: מאת Krokedil – 1.11.3
Loco Translate: מאת Tim Whitlock – 2.3.1
Mailchimp for WooCommerce: מאת Mailchimp – 2.2.4
Nextend Social Login: מאת Nextendweb – 3.0.20
OTF Regenerate Thumbnails: מאת Benjamin Intal - Gambit Technologies Inc – 0.3
Polylang: מאת WP SYNTEX – 2.6.5
Regenerate Thumbnails: מאת Alex Mills (Viper007Bond) – 3.1.1
Show Current Template: מאת JOTAKI Taisuke – 0.3.0
WooCommerce PayPal Checkout Gateway: מאת WooCommerce – 1.6.17
WooCommerce Product Type Column: מאת WooCommerce – 1.0.0 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WooCommerce Stripe Gateway: מאת WooCommerce – 4.3.0
WooCommerce Waitlist: מאת WooCommerce – 2.0.3 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WOOF - WooCommerce Products Filter: מאת realmag777 – 1.2.3
WooSidebars: מאת WooCommerce – 1.4.5
YITH WooCommerce Wishlist: מאת YITH – 2.2.13
Yoast SEO: מאת Team Yoast – 12.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

בסיס חנות: #59 - /shop/
עגלת קניות: #58 - /cart/
תשלום: #57 - /checkout/
החשבון שלי: #56 - /my-account/
תנאי שימוש: #401 - /toc/

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – אם משנים את ווקומרס בערכת נושא אב שלא נבנתה באופן אישי
מומלץ להשתמש בערכת עיצוב בת. אפשר לראות: כיצד ליצור ערכת עיצוב בת

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 18
Oldest: 2019-10-23 16:38:59 +0000
Newest: 2019-10-23 16:39:42 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by sudoshreyansh** [comment] 2020-10-01 04:08
Can I work on this issue ?

**Comment by mi5t4n** [comment] 2020-10-10 04:27
@claudiosanches 
Hello,
I just tested this issue and it seems like this is already fixed. I think, we need to close this issue.

**Comment by hsingyuc** [comment] 2021-02-16 22:23
I can't reproduce the issue either.

**Comment by claudiosanches** [comment] 2021-03-03 20:22
@mi5t4n @hsingyuc Thanks for let me know about it.

**Closed by claudiosanches** 2021-03-03 20:22 UTC
Labels: good first issue, hacktoberfest, priority: low, type: bug
