### ISSUE TITLE
wc_get_orders fails silently

### ISSUE THREAD

**Issue by Nemi5150** [woocommerce/woocommerce#29931] opened 2021-05-17 20:25 UTC
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I call wc_get_orders and pass in a customer id. It properly returns an array of orders. However, when the admin page is reloaded using a filter, the call to wc_get_orders returns nothing, even though the input params are exactly the same. 

**Expected behavior**
I would get a collection of orders back if the same args are passed in each time. I am guessing that somehow, some way using the filter bar for an admin page is causing the page to load resources differently and the woocommerce resources are not present, but I have no way to know that. 

If there is an "error" in the setup of the woocommerce libraries when calling the wc_get_orders function, I would expect it to fail loudly, instead of failing silently (which is what it is doing). Failing silently means I have absolutely no way in determining what is actually going on by myself. 

**Actual behavior**
I get different results even when the same args are passed in each time.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
I cannot supply a simple way to reproduce this since it happens in a complex web app. 

If I go to my admin page that shows orders, the page initially loads fine. 
![image](https://user-images.githubusercontent.com/5833302/118551806-bc8c9400-b723-11eb-963c-74eff9fe7269.png)

However, if I set the "Filter by user" to someone, it starts returning zero orders for the passed in user id, even though the passed in user id is exactly the same (verified by stepping through with a debugger and verifying the passed in data)
![image](https://user-images.githubusercontent.com/5833302/118552037-05dce380-b724-11eb-9960-0003faf6885c.png)

Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rodelgc** [comment] 2021-05-26 17:41
Hi @Nemi5150,

Thank you for taking the time to report this issue. I was trying to recreate your steps through the UI, but I have a few questions:

> If I go to my admin page that shows orders, the page initially loads fine.

May I ask which exact page in WP Admin were you referring to here? I initially assumed it was the `WooCommerce > Orders` page, but I do not see a "Filter by user..." option there. There is, however, a "Filter by registered customer".

Without any plugins installed other than WooCommerce, here's how the `WooCommerce > Orders` page would look like:
<img width="1604" alt="Screen Shot 2021-05-27 at 1 18 25 AM" src="https://user-images.githubusercontent.com/4509348/119704880-b8cae100-be8a-11eb-8d17-1b86b2d1f43e.png">

In your screenshot though, it seems you have a few other filters available, and the columns are quite different.

Let us know which page you were referring to so that we could replicate this issue more accurately on our end. Thanks! 🙂

**Comment by Nemi5150** [comment] 2021-05-27 16:11
Sorry, I should have been more clear. The page is a custom admin page for
an auction plugin. It is similar to the orders or products page. It is
custom code that calls wc_get_orders, but it is not the code itself. I can
hard code the values passed into the function and I still get inconsistent
results. When loading the page with default params the function returns
results. Simply putting in a user to filter by returns no results. But the
thing is, the filter in this case does not change the values passed into
the wc_get_orders function!

I have been a programmer for over 20 years, but only been doing
wordpress/php for about a year. Is there some sort of global that the
wc_get_orders function is using for it's query? Or maybe the wc_get_orders
function has to be called after the woocommerce init functions have been
called? I have used a debugger to step through the wc_get_ordwers function
but I cannot find why it would return different results when the same
params are passed in.

**Comment by rodelgc** [comment] 2021-05-28 10:47
Hi @Nemi5150,

Thank you very much for the clarification!

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

You can also make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/).

If, after interacting with our community you happen to encounter a bug that's specific to WooCommerce's core functionality, please feel free to open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by rodelgc** 2021-05-28 10:47 UTC
Labels: has feedback
