### ISSUE TITLE
send email with custom order status

### ISSUE THREAD

**Issue by bsahins** [woocommerce/woocommerce#29952] opened 2021-05-21 00:34 UTC
Hi,

"when add order from api, 'set_paid' => true, or 'status' => 'completed', woocommerce will send an email to customer"

Is it possible to get same action when we change order status via rest API.
We will used shipped status.

**Comment by zhongruige** [comment] 2021-05-21 19:51
Hi @bsahins,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions.

I took a quick look at possible solutions for you, and these may work for your use-case:

* [https://stackoverflow.com/questions/27112461/woocommerce-send-custom-email-on-custom-order-status-change](https://stackoverflow.com/questions/27112461/woocommerce-send-custom-email-on-custom-order-status-change)
* [https://wordpress.org/support/topic/how-to-send-email-from-custom-order-action/](https://wordpress.org/support/topic/how-to-send-email-from-custom-order-action/)

Outside of the above, the best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by zhongruige** 2021-05-21 19:51 UTC
