### ISSUE TITLE
Endless charge when you fill variables in the product page

### ISSUE THREAD

**Issue by jaime27** [woocommerce/woocommerce#19471] opened 2018-03-21 14:21 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. create a variable product
2. add 6 or more attributes with variables
3. publish the product
4. fill the variables on the product page
## Expected/actual behavior

When I follow those steps, I see...
 A spinning ball that never ends, i have a clean instalation of wordpress.
I was expecting to see...
the price of the product with the selected variables.
## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

Home URL: http://inkgenio.es
Site URL: http://inkgenio.es
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.15
PHP Post Max Size: 55 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 55 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ No existe la base de datos MaxMind GeoIP - La geolocalización no funcionará. Puedes descargarla e instalarla manualmente desde http://dev.maxmind.com/geoip/legacy/geolite/ en la ruta: . Ve a "Downloads" y descarga el archivo "Binary / gzip" junto a "GeoLite Country". Por favor
acuérdate de descomprimir GeoIP.dat.gz y subir solo el archivo GeoIP.dat.

Tamaño total de la base de datos: 1.26MB
Tamaño de los datos de la base de datos: 0.91MB
Tamaño del índice de la base de datos: 0.35MB
wp_woocommerce_sessions: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_order_items: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_order_itemmeta: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB
wp_commentmeta: Datos: 0.00MB + Índice: 0.00MB
wp_comments: Datos: 0.00MB + Índice: 0.01MB
wp_links: Datos: 0.00MB + Índice: 0.00MB
wp_options: Datos: 0.55MB + Índice: 0.03MB
wp_postmeta: Datos: 0.31MB + Índice: 0.23MB
wp_posts: Datos: 0.05MB + Índice: 0.04MB
wp_termmeta: Datos: 0.00MB + Índice: 0.01MB
wp_terms: Datos: 0.00MB + Índice: 0.01MB
wp_term_relationships: Datos: 0.00MB + Índice: 0.00MB
wp_term_taxonomy: Datos: 0.00MB + Índice: 0.00MB
wp_usermeta: Datos: 0.00MB + Índice: 0.01MB
wp_users: Datos: 0.00MB + Índice: 0.01MB
wp_wc_download_log: Datos: 0.00MB + Índice: 0.00MB
wp_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 9
customize_changeset: 4
page: 7
post: 2
product: 3
product_variation: 36
revision: 2

### Security ###

Secure connection (HTTPS): ❌Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: por Automattic – 3.3.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base de la tienda: #4 - /tienda/
Carrito: #5 - /carrito/
Finalizar compra: #6 - /finalizar-compra/
Mi cuenta: #7 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: GeneratePress
Version: 2.0.2
Author URL: https://tomusborne.com
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
![captura](https://user-images.githubusercontent.com/8851041/37715010-31f88672-2d1b-11e8-879a-0c4f05c85a31.PNG)

</details>

**Comment by mikejolley** [comment] 2018-03-23 11:49
Hi this is the endpoint timing out:

`504 Gateway Time-out`

To the endpoint http://inkgenio.es/?wc-ajax=get_variation.

This could be a timeout due to the number of variations it needs to search through, or it could be lack of support for `SQL_BIG_SELECTS`. Look at your error log for more details (server php error log, or maybe in WC > System Status > Logs > Fatal errors).

Once you find the error if it's a memory limit thing or extension it should be easy enough to act. 

You can also disable ajax by increasing the variation threshold so it's done on page, but if there are lots of variations here it may be slower. See:
https://iconicwp.com/blog/modify-ajax-variation-threshold/

Since this one is not reproducible and appears site specific (it's a timeout) I'm closing the issue but please relay back if you find something in the logs which looks like a WC error rather than memory limit issue.

Thanks

**Closed by mikejolley** 2018-03-23 11:49 UTC
