### ISSUE TITLE
wp-content/plugins/woo-products-widgets-for-elementor/assets/css/lib/jetwoowidgets-font/fonts/rating-star.ttf

### ISSUE THREAD

**Issue by liamc96-dotcom** [woocommerce/woocommerce#25337] opened 2019-12-29 14:32 UTC
Hello.
Hope someone can help, I recently have found these errors popping up on my 404 monitor.
Can Anyone please point me in the right direction to getting them removed please.

Image/gif;base64,R0lGODlhAQABAIAAAAAAAP/yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

wp-content/plugins/woo-products-widgets-for-elementor/assets/css/lib/jetwoowidgets-font/fonts/rating-star.woff

wp-content/plugins/woo-products-widgets-for-elementor/assets/css/lib/jetwoowidgets-font/fonts/rating-star.ttf

**Comment by tammullen** [comment] 2020-01-09 11:13
Hi @liamc96-dotcom,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

[Review WooCommerce Self-Service Guide](https://href.li/?https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://href.li/?https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://href.li/?https://wordpress.org/support/plugin/woocommerce/)
If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-01-09 11:13 UTC
