### ISSUE TITLE
Why doesn't "woocommerce_shipping_fields" filter in code.

### ISSUE THREAD

**Issue by dangvantri113** [woocommerce/woocommerce#26592] opened 2020-05-23 16:47 UTC
I have a problem that need to use filter. I read some document online mention about "woocommerce_shipping_fields" filter, but i can't find where this filter apply. Please help me why? help me find it.

**Comment by juliaamosova** [comment] 2020-05-27 14:20
Hi @dangvantri113,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-05-27 14:20 UTC
