### ISSUE TITLE
After Placing order, Order complete page don't show any product name, quantity!  It's only show the total amount of order price. And the invoice is also blank. But checkout page show all the information. How can i do to solve this problem? 

### ISSUE THREAD

**Issue by citybazar2020** [woocommerce/woocommerce#26405] opened 2020-05-07 11:24 UTC
![IMG_20200507_172725](https://user-images.githubusercontent.com/64962083/81289352-175acc80-9088-11ea-9a58-6795b179be34.jpg)

![IMG_20200507_173332](https://user-images.githubusercontent.com/64962083/81290008-1f673c00-9089-11ea-9717-ba138a972832.jpg)
![IMG_20200507_173406](https://user-images.githubusercontent.com/64962083/81290063-39a11a00-9089-11ea-8668-b93304f35294.jpg)
![IMG_20200507_173809](https://user-images.githubusercontent.com/64962083/81290386-ca77f580-9089-11ea-9f51-6eed5054bedc.jpg)

**Comment by juliaamosova** [comment] 2020-05-07 17:39
Hi @citybazar2020,

Thank you for raising the issue. 

Do you have many plugins installed on your site? One of them can be conflicting with WooCommerce and causes the issue. I also see that you don’t use one of our default themes either. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by citybazar2020** [comment] 2020-05-07 19:03
Thank you for your response. Special thanks for that, according to your
advice the problem  is solved now.
One of the plugin create the problem, when i deactivated that plugin, the
product name show invoice and order complete pages. Just want to say Wow😊

**Closed** 2020-05-07 19:09 UTC
Labels: status: needs feedback

**Comment by juliaamosova** [comment] 2020-05-07 19:10
I am glad to hear the issue is now resolved @citybazar2020! Thanks for following up here.

**Comment by citybazar2020** [comment] 2020-05-07 19:16
Actually ,  you are a good problem solver i think & really feel that.
Again, Thanks for your helping.
