### ISSUE TITLE
Geolocation fails to assign correct zip-code based on shipping costs + update zip-code fails to refresh shipping costs unless you change & revert the country

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#27231] opened 2020-08-05 10:33 UTC
Assume the following case :

- Geolocation (without caching) is enabled
- Shipping settings as in the attachment below

![image](https://user-images.githubusercontent.com/51261962/89401962-67444080-d716-11ea-8acb-ab253476bfc6.png)

a) For the capital of my country, I'm shipping at a reduced rate of only 1.75€. For this, I defined the zip codes that are applicable.
b) For the rest of my country, I'm shipping at a regular rate of 3.75€. For this, I defined the country itself and I put this zone as second in the list.

![image](https://user-images.githubusercontent.com/51261962/89402177-c013d900-d716-11ea-8274-04f67ca6a12c.png)

Those two shipping zones used to work fine until I enabled the geolocation, which has disrupted the good functionning of those two shipping zones. Why?

Because WooCommerce will geolocate the user as part of the country itself, so it will give the shipping cost of the SECOND zone altough this is wrong. It doesn't take into account the first one. Check this video : https://sgevcen.tinytake.com/tt/NDUxMzE1MF8xNDMwMDczNQ (if video doesn't load, click download)

From this video, you can see 2 issues :

1) the geolocation doesn't properly locate my location and therefore the shipping cost based on zip code is wrongly ignored => this is a big problem, because users that are in the zip code of shipping zone 1 will see prices of the shipping zone 2

2) the zip code doesn't make any cart refresh, therefore making it impossible to define the zip code-based shipping UNLESS you change country and then return back to initial country (which is obviously NOT an accepted behavior in reality)

Thanks

**Comment by gevcen** [comment] 2020-08-05 10:37
My solution would be to answer to this question : How can force a shipping refresh on zip code change ?

**Comment by juliaamosova** [comment] 2020-08-05 19:35
Hi @gevcen,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. Your questions are best suited for support, not for GitHub. In the future, please try one of the channels below before posting here:

- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am happy to help here this time as an exception. 

First things first, the Geolocation in WooCommerce works by using GeoLite2 database of MaxMind. It is a free IP geolocation database. From the [MaxMind website](https://dev.maxmind.com/geoip/geoip2/geolite2/):

>IP geolocation is inherently imprecise. Locations are often near the center of the population. Any location provided by a GeoIP database should not be used to identify a particular address or household.

In other words, it can identify the city in the country at its best but not the zip code. MaxMind has a paid service if the location needs to be more precise which allows identifying the postal code associated with the IP address of the user:

https://www.maxmind.com/en/geoip2-precision-city-service

Now to your case specifically, you should remove Belgium from the first zone and have only zip codes listed there to make sure there are no potential inaccuracies. The "narrower" zones should always be at the top of the list with "wider" zones at the bottom. 

Here is the equivalent on my test site - I have zone one for the specific zip code in Miami, Florida and the broader zone for the Unites States as my 2nd zone:

![Screen Shot 2020-08-05 at 3 24 19 PM](https://user-images.githubusercontent.com/19143190/89455092-c19dcb00-d72f-11ea-9c8f-963fd4cadd3c.png)

Changing this alone won't help to resolve the issue with Geolocation but it is a more accurate way of setting up shipping zones. 

>a) How can I make sure the geolocation correctly geolocates right? I already added MaxMind integration but seems not sufficient

I think the best would be to actually enable the setting `Hide shipping costs until an address is entered` option in `WooCommerce/Settings/Shipping options`:

![location](https://user-images.githubusercontent.com/19143190/89455560-83ed7200-d730-11ea-9aa7-26929bc6beea.jpg)
 
>b) How can force a shipping refresh on zip code change ?

This should work by default - you can see it working on my test site:

![](http://g.recordit.co/ICIp0u19F2.gif)

If it doesn't work on your site, there is likely a theme and plugins conflict. Please test for that. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-08-12 14:02
Hi @gevcen,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-08-12 14:02 UTC
Labels: status: needs feedback
