### ISSUE TITLE
Variations not deleted properly

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#17049] opened 2017-10-04 04:44 UTC
I import a CSV with 3 variable products and various variations. Everything is imported correctly. I delete these products (Trash > Empty Trash) and import the same CSV again. All variations are skipped because of duplicates.

I suspect that variations are not deleted properly when deleting the parent product.

CSV is not attached because of sensitive customer data in it, ping me when testing and I'll send it to you, or you can download it from #708502-zen.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment] 2017-10-04 06:27
I cannot recreate this, using 3.2 RC 1 I tested this by creating a variable product with 2 variations and then checked the wp_posts table. All 3 entries were added to the table as expected. I then proceeded to trash the main variable product and then emptying the trash and checking the wp_posts table again and all 3 entries were deleted as they should.

Would you mind sending me the import file so I can test? But I suspect the issue was fixed already since this is not reproducible with the latest RC.

**Comment by kloon** [comment] 2017-10-04 08:45
Tested with the file you provided on 3.2 RC and it removes everything as it should.

Closing, can always reopen should the issue persist.

**Closed by kloon** 2017-10-04 08:45 UTC
Labels: Type: Bug
