### ISSUE TITLE
Database considerations for a growing store

### ISSUE THREAD

**Issue by pokhiii** [woocommerce/woocommerce#28373] opened 2020-11-23 19:56 UTC
**Is your feature request related to a problem? Please describe.**
We maintain a WC-powered store which has turned over 5 years now (Thanks for the excellent product)! Over the years the number of orders and the data related to them, meta, items, item meta have just grown and there is no looking back. Some facts about the **completed** orders in our WooCommerce store database:
- Total number in the `posts` table = **119K**.
- Total number of post meta rows = **8M**.
- Total number of order-item rows = **1.2M**.
- Total number of order-item-meta rows = **11.7M**.

We are now at a stage where it feels like the store is going burst any day. 

**Describe the solution you'd like**
I'd like to know what are options we have. I just want to bring down the sizes of this table and want to place some sort of mechanism so they don't just keep growing.

**Describe alternatives you've considered**
I've heard about a plugin called [WooCommerce Custom Orders Table](https://github.com/liquidweb/woocommerce-custom-orders-table) but I'm not very hopeful about it primarily because:
1. I don't think it does anything about the `woocommerce_itemmeta` table (I may be wrong).
1. No stable version and seems like the development has gone inactive last release was on 24 Jul 2019.

**Additional context**
We recently updated WC from 4.4.1 to 4.6.1 (after updating all the other extensions) and the order item meta table just became inaccessible ("MySql server has gone away" types of errors). We had to revert back and I'm just too scared to re-update it so it is still running on 4.4.1.

---

### Edit (table size on May 21, 2021) (6 months)

- Total number in the `posts` table = **179K**.
- Total number of post meta rows = **12M**.
- Total number of order-item rows = **1.8M**.
- Total number of order-item-meta rows = **17M**.

**Comment by masteradhoc** [comment] 2020-11-23 20:57
@abhishek-pokhriyal woo also started a development quite a time ago on this: https://github.com/woocommerce/woocommerce-product-tables-feature-plugin

The team at liquidweb has plans to get the custom order table further - as far as i know.

I think you should take part in a monthly dev meeting and raise the question also in the slack core channel. (https://woocommercecommunity.slack.com/)

**Comment by abhishek-pokhriyal** [comment] 2020-11-24 06:17
> woo also started a development quite a time ago 

Again it looks like the development has been on hold (or abandoned). The last commit was over a year ag. Probably because these issues never make it to the core team's priority list.

**Comment by negapo** [comment] 2020-11-24 18:14
Hi @abhishek-pokhriyal we have the same problem. We have a fairly successful store based on Woo and im also really thankful for the product they have built although i increasingly think Woo is not a product for even a mid sized store, unfortunately. First, as you mentioned, it's bloats significantly with no way to clean that old information. There is no way to archive orders in a sense that they would be moved to a different table where everyday queries would not be hit and we could un-archive them if needed. There is no way to clean metadata (if it prefixes with "_") from order and products and unfortunately a lot of plug-ins just dump a  a whole lot of fields in there. 
We do run a lot of custom code using the API, cleaning metadata from orders and products when not needed, archiving old orders on local databases and then deleting them from the shop (with the downside that costumers lose access and the reports on Woo stop reporting accurate numbers).
But we find bigger issues, the business model of not developing basic features because there is a plug-in out there makes it very hard to run a store. We are constantly finding compatibility issues with plug-ins and have problems when updates come around.
It's a really cool product but i have reached a point where i wish i had built it with another tool.

**Comment by abhishek-pokhriyal** [comment] 2020-11-24 19:05
> i have reached a point where i wish i had built it with another tool

That's probably the saddest thing I've read in a while. But, to be honest, WooCommerce is really the only eCommerce framework I've worked with. So, I really don't know how these things are handled by other tools and frameworks. The problem of growing database size seems completely natural to me and I believe this will exist in every eCommerce system.

In this issue, I am seeking help from someone - who has already made it through or any architectural level ideas that we can pursue.

**Comment by lukecav** [comment] 2020-11-24 19:24
https://github.com/liquidweb/woocommerce-custom-orders-table
https://github.com/liquidweb/woocommerce-custom-orders-table/commits/develop

The plugin has been archived due to the feature coming to the WooCommerce core. One store has over 200k orders on it and another has over 1.8+ million orders on it.

**Comment by abhishek-pokhriyal** [comment] 2020-11-25 04:56
Thanks @lukecav. I'll definitely try this plugin out. However, my understanding is that plugin moves data from `postmeta` to a separate table, and does nothing for the other tables like posts, order_items, order_itemmeta.

**Comment by negapo** [comment] 2020-11-25 11:00
@abhishek-pokhriyal Do you need all orders with all the info on Woo?
We have a strategy that works in steps.
> First we always have a complete copy of the order on a local database, we set up a order update webhook and when there is an update we save the entire JSON received dumped in a local database.
> Then after 12 months we strip all meta data from the order.
> After 24 months we delete the order from WooCommerce (our products have a 24 month warranty).

If after that period we need to access the order we have it locally. This is not perfect but works for us.

**Comment by abhishek-pokhriyal** [comment] 2020-11-26 06:35
Thanks, @negapo for sharing the strategy. It's very specific and involved so I'll have to see if something like that can work for us or not. For now, I'm going to start with @lukecav suggestions and see how things go from there.

**Comment by rene-hermenau** [comment] 2020-12-04 10:18
> https://github.com/liquidweb/woocommerce-custom-orders-table
> https://github.com/liquidweb/woocommerce-custom-orders-table/commits/develop
> 
> Is stable and does have active development on it the plugin is also being used in a number of customer's stores. One store has over 200k orders on it and another has over 1.8+ million orders on it.

@lukecav I must be blind. I don't ask this without respect, but what do you want to show us with the links?  The last commit is 9 months ago and even the CI badge says, that the latest build failed:  ![Alt text](https://monosnap.com/image/PInLGWQlsWo2SIx3qf0erx3KCpwUTh)

Without any further looking into the code I absolutely understand when someone hesitates to implement this into production, especially when it's a big site that makes a lot of revenue. This is not a fire and forgets solution and it needs maintenance and adjustments. They can not rely on such an important plugin as long as it does not become part of the WC core. 

https://github.com/liquidweb/woocommerce-custom-orders-table is a great project. Really appreciate the effort and work that has been spent on this. It should be more on the WC core developers' priority to get it into WooCommerce. I don't know if this is already heavily discussed within the WooCommerce project management but for an outstanding person like me and from what I am seeing it does not seem to be the case.

Administrators are not able to push and pull easily to/from staging and development sites due to that. It's sad but true but I've spoken to a few very big enterprises who have decided against WooCommerce due to its technical debts of storing all of its order data in the WP core tables.

WooCoomerce, as it is, is often not the right choice for a bigger (enterprise) company. I would even say it's not suitable for smaller sites as well due to that issue but I don't want to hit on someone's toe here.

Please make this a priority. The plugin already exists for 3 years. What's the reason that no attempt is made to bring it into core?
If there is a roadmap or public discussion of integrating it I'd appreciate it if you can point me to that.

**Comment by liviujs** [comment] 2020-12-04 14:07
Just to add my 2 cents on this Topic. Same issue with 100K orders first dating from 2018, database is 4GB+. Our premium managed hosting is billing according on disk space.
@rene-hermenau  When we switched to WOO in late 2017 the https://github.com/liquidweb/woocommerce-custom-orders-table plugin was on their Trello Board, so it was an important point in our decision.
After that the plugin was abandoned, I even wrote an email to Woocommerce support team asking about it, the answer was that they dropped it because they implemented some database optimizations in latest versions of WC and they didn't see any need in keeping up the project.

@negapo 
> But we find bigger issues, the business model of not developing basic features because there is a plug-in out there makes it very hard to run a store. We are constantly finding compatibility issues with plug-ins and have problems when updates come around.
> It's a really cool product but i have reached a point where i wish i had built it with another tool.
Totally agree here. There are a couple of basic functionality that has to be in any core e-comm cms, plugins on the other side can co-exist. Shopify is the best example here.

p.s. last year was the most dynamic one in terms of development from their side, switching to monthly updates, moving to react, so on. Woo Team, keep up doing a great job, focus a bit more on mid up+ stores! (until now the focus was on making a new on boarding page)

**Comment by stevegrunwell** [comment] 2020-12-04 16:38
Hi all,

I'm one of the leads on the WooCommerce Custom Orders Table plugin, so I wanted to clarify a few things about the plugin:

## Is this plugin abandoned?

While development efforts have been slow, the plugin is **not** abandoned. It's purely a matter of prioritization, and I'm constantly getting pulled in a lot of different directions (platform features, customer support, other plugins, and more). This is still 100% on our radar, however.

Honestly, one of the big changes I need to implement is [leveraging PHP traits](https://github.com/liquidweb/woocommerce-custom-orders-table/issues/122) to dramatically-reduce the amount of duplicated logic against the data stores we've extended. Now that we're not constrained by PHP 5.2 (and the fact that WooCommerce is embracing a "package" approach for feature plugins like this), we can dramatically simplify and modernize the codebase, which will make working on the plugin far easier.

Since WooCommerce Custom Orders Table's test suite extends the core WooCommerce test suite ("if it works in stock WooCommerce, it'd better keep working with our plugin active."), there has also been plenty of work _outside_ of the plugin's repository: [I've been submitting PRs to WooCommerce core for order-related functionality with insufficient test coverage](https://github.com/woocommerce/woocommerce/pulls?q=author%3Astevegrunwell+).

## What exactly does the plugin do?

The plugin is designed to take all of the ~45 standard order-related postmeta entries and move them into a custom table, optimized for those meta values' data types. Instead of having separate meta keys for "billing_firstname", "billing_lastname", etc., we can store those values in a flat, optimized table.

For example, instead of storing a two-character country code (ISO 3166-1 Alpha-2) in a LONGTEXT database column (`wp_postmeta.meta_value`), we're able to store it in a much more efficient CHAR(2) in the custom table. Not only does this aid in read/write performance (crucial for stores receiving multiple concurrent orders), but can dramatically reduce database sizes for busy stores.

As @abhishek-pokhriyal mentioned above, the plugin **does not** move orders out of the `wp_posts` table. While this would be nice, it would touch nearly every part of WooCommerce to get it working properly. WordPress, for better or worse, is built around the idea of posts.

## Is it safe to use?

With regards to stability, the plugin largely works without issue and we are indeed running it on a number of large, production WooCommerce stores at Liquid Web/Nexcess (to be clear, it's installed as necessary at this point, not by default). However, until we're able to get the known issues worked out, I'm holding us back on tagging a 1.0.0 release. There's a lot of data types I don't mind messing up, but your order data isn't one of 'em 😉.

## When will it be in WooCommerce core?

We discussed what that path might look like with the WooCommerce core team last year. They're certainly open to it, but we need to do the legwork to a) get a tagged release that doesn't rely on WP-CLI to migrate data (read: action scheduler) and b) be able to provide hard numbers to show the performance gains over stock WooCommerce.

Since that call, [WooCommerce has also published documentation on the Feature Plugin inclusion process](https://docs.woocommerce.com/document/what-is-a-woocommerce-feature-plugin/), which [we'll need to adhere to](https://github.com/liquidweb/woocommerce-custom-orders-table/issues/153).

--- 
Hopefully this clarifies some of questions I'm seeing in this thread. I'm the first to admit that I'm the bottleneck here, but please know that the cautious pace at which we're making changes is out of respect of you, your customers, and your clients.

**Comment by liviujs** [comment] 2020-12-07 10:20
@stevegrunwell Huge THANK YOU for reaching to us with this info.
Hope we gone see this in core since it's a major pitfall of Woo that everyone seem to know about, somehow they don't see it.

**Comment by masteradhoc** [comment] 2021-02-17 05:57
FYI: https://wptavern.com/easy-digital-downloads-3-0-now-in-public-beta
easy digital downloads just went this way

"Version 3.0 will migrate the bulk of EDD data out of WordPress core tables to custom database tables. During the lifespan of this nearly 10-year old plugin, practices have changed regarding the use of custom tables and the coming update will bring improvements to performance and data structures. "

**Comment by asoap** [comment] 2021-03-23 16:24
I just tested the plugin and it did not change the woocommerce_order_itemmeta table.  

It also barely decreased the postmeta table.  It went from 3,599,538 records to 3,575,509

Not much of an improvement.

**Comment by lukecav** [comment] 2021-03-23 20:40
@asoap 

Did you preserve or migrate postmeta when you migrated orders?

https://github.com/liquidweb/woocommerce-custom-orders-table#migrate-order-data-from-post-meta-to-the-orders-table

**Comment by asoap** [comment] 2021-03-23 23:46
@lukecav 

I ran the command "wp wc orders-table migrate" which from reading the documentation does not preserve the original post_meta data after a migration.

**Comment by nicomollet** [comment] 2021-05-20 14:56
My company have multiple shops with 20k-50k orders and I am worried about the future too.
10 years ago the extensibility was fun and hid the rest of the issues.
Now the shops are bigger/slower.

Also they need redesigns that are a pain to make smoothly while the orders are in the posts table!
There is not obvious solution other than separating the orders from the rest in the database.

I don't understand why WooCommerce team doesn't consider this seriously, it will explode sooner or later.
This feature should not rely on a plugin, or WooCommerce team should provide help at least!

Thank you

**Comment by abhishek-pokhriyal** [comment] 2021-05-21 14:40
I'd like to know from the store managers here, is there some sort of strategy you use to clear old order data from your store? If you look at the issue's description, I've added the new table sizes. Here is the amount by which they've grown.

1. Total number in the posts table = **60K** 📈
1. Total number of post meta rows = **4 million** 📈 
1. Total number of order-item rows = **0.6 million** 📈
1. Total number of order-item-meta rows =  **5 million**📈

So I wanted to keep a check on the soaring table sizes.

**Comment by lkraav** [comment] 2021-05-22 07:41
> I'd like to know from the store managers here, is there some sort of strategy you use to clear old order data from your store?

Why would anyone ever delete any accounting information and take on various additional risks? I for one don't plan to.

We're approaching 50 k orders (+ similar amount of memberships, teams, subscriptions modelled as posts + meta). But depending on how well the store is built overall, this amount is not really a problem.

We're approaching 5 M posts due to an online school achievement tracking system, and our e-commerce speed is still mostly fine. Can't say it's been low cost to get there, but it can work. Regardless, we are first looking to upgrade to custom tables on the achievement tracking system, only then come back here to follow how Woo is doing with custom e-commerce tables.

Alternative: https://github.com/10up/ElasticPress could boost many things immediately, but still not sure how well it works with Subscriptions.

**Comment by abhishek-pokhriyal** [comment] 2021-05-22 13:41
> Why would anyone ever delete any accounting information and take on various additional risks?

Fair point. It just hurts making queries to large tables – a large portion of rows are just for historical or accounting purposes. A wild thought that comes to me is to move all the orders over (let's say) a year ago to a different table, that will be queried only when the data is not found in the original tables (kind of like the principle caching works on).

> depending on how well the store is built overall, this amount is not really a problem.

Interesting. Let's say I just have a plain WP-WC store, no customization nothing. Is that setup good enough? Or is it really not about that?

**Comment by lkraav** [comment] 2021-05-24 13:10
> A wild thought that comes to me is to move all the orders over (let's say) a year ago to a different table, that will be queried only when the data is not found in the original tables (kind of like the principle caching works on).

Sounds sane, but maybe also complicated. Ideally we'd not invent some new monstrosity here.

> Interesting. Let's say I just have a plain WP-WC store, no customization nothing. Is that setup good enough? Or is it really not about that?

If no added plugins, and theme's WC integrations don't do anything incredibly stupid with modifying queries, I think it would not experience much slowdown.

But reality is that a WC store that's actually competitive from a wide range of perspectives (UX, compliance, taxes, payment gateways) usually requires multiple 10s of addon plugins to get there.

**Comment by mklepaczewski** [comment] 2021-06-27 14:13
I work as a performance engineer and I wonder why people try to move orders to another table? There are a lot of "I feel that... ", "It seems that..." and "tables are big", but no performance tests, examples of slow queries, small # of orders vs big # of orders examples. I'm not saying that the slowdown isn't real, but has anyone actually measured it? RAM is cheap, CPUs are powerful and storing millions of rows is nothing for MySQL. I wouldn't worry about big tables unless it actually makes queries slow. Even then, I suspect that proper range queries would solve the problem (e.g. query for orders from last year instead of querying all orders).

WP isn't a performance beast and progress on lookup tables (which have been introduced in WC 3.6 I think) would help a lot, but I suspect that in many cases the issue isn't database size in itself.

**Comment by nicomollet** [comment] 2021-07-06 09:35
Since I don't have numbers to elaborate on the database performance, but I would like to insist on the difficulty to redesign a WooCommerce shop.

Please give an actual method to redesign a WooCommerce shop while in local development, involving updating or creating post/pages contents or other post types like page builder layouts.

Gravity Forms has separate tables, EDD (since version 3) has separate tables.
When deploying the staging site to prod, I simply have to exclude those tables and voilà.

**Comment by mferrara** [comment] 2021-11-26 01:37
I've been maintaining a WC shop for the last 6 or so years and we've had nagging/on-going issues with these/this issue. It currently looks like this...

Posts: 530,000 rows
Post meta: 30,000,000 rows
WC Order Items: 1,300,000 rows
WC Order Item meta: 13,500,000 rows

About a year ago we came to a critical point where continuing to throw money/hardware at the problem wasn't going to cut it anymore, as the numbers grew the overall response times fell. SEO rankings were suffering, revenue was suffering and the development of the liquid web plugin seemed to stall/not be taken seriously by the core so waiting for custom tables to not only make it to core but _also_ support plugins/existing integrations was seeming not-assured. 

After debating some strategies similar to those that were being tossed around in here we ended up splitting our Wordpress installation/application in two. We now run a very lean Wordpress install that serves all pages that aren't a product page (and even the 'product pages' are on the lean WP install that has the initial form/product setup that ends up redirecting the user on submit to the actual product page on the WooCommerce install). So, until the user adds the item to their cart / starts interacting with checkout/cart/their profile they're on the lean site (fast). 

This has proven to be a _wonderful_ "fix". SEO/rankings have rebounded, conversions are up (much more crisp responsiveness from the site all around) and the servers have considerably reduced load - though, it's only a matter of time until we're in the same boat again. 

(Migrating/deleting the old orders wasn't an option for our store for accounting/product-history related reasons)

- Searching the orders via the WooCommerce orders page search box... they timeout and fail. (our timeout is 30s due to cloudflare, so they just fail). 
- WCAPI get_order was also very slow (2-3s per request/query)

After diving pretty deep the solution that worked best was to add this key to `wp_postmeta`

`KEY 'meta_key_meta_value' ('meta_key'(30),'meta_value'(10))`

Now, I'm not sure that this is going to be the answer to these rather specific issues for everyone, but for our use case the API requests to get_order went from 2-3s to 0.25s.

Re: Searching orders through the WC dashboard/orders page:
In the `class-wc-order-data-store-cpt.php` file and the `search_orders()` method I've made the change of adding the following to the mysql query

`FORCE INDEX (meta_key_meta_value)`

So the following query...

`"SELECT DISTINCT p1.post_id FROM {$wpdb->postmeta} p1 WHERE p1.meta_value LIKE %s AND p1.meta_key IN ('" . implode( "','", array_map( 'esc_sql', $search_fields ) ) . "')"`

was changed to...

`"SELECT DISTINCT p1.post_id FROM {$wpdb->postmeta} p1 FORCE INDEX (meta_key_meta_value) WHERE p1.meta_value LIKE %s AND p1.meta_key IN ('" . implode( "','", array_map( 'esc_sql', $search_fields ) ) . "')"`

It's ugly, but effective. Searches work now (3s or so).

Before adding the new index, or FORCE INDEX to this query EXPLAIN routinely indicated it used no index at all. 
After adding the new index the query still wasn't using an index. 

Insert long wandering journey down the rabbit hole... 

`innodb_stats_persistent_sample_pages = 100` + `OPTIMIZE TABLE` = The query now uses the index and it's _fast_.

Hopefully this information will save those of you in a similar situation thousands of dollars/many hours of headaches.

**Comment by peterfabian** [comment] 2023-03-23 10:21
Thank you all for the valuable discussion and insights here. Since the core WC team is working on HPOS now, I think we can close this topic and hopefully, HPOS will improve the situation for many large and quickly growing stores, please refer to the updates on our dev blog, e.g. https://developer.woocommerce.com/2023/03/17/performance-benchmarking-for-woocommerce-hpos/.

**Closed by peterfabian** 2023-03-23 10:21 UTC
Labels: needs: discussion, plugin: woocommerce

**Comment by peterfabian** [comment] 2023-03-23 10:33
Also, please let us know if anyone from this thread is already testing or would like to test [HPOS](https://developer.woocommerce.com/2023/03/17/performance-benchmarking-for-woocommerce-hpos/), we'd love to help you get your site ready!

**Comment by kuldeep3** [comment] 2023-03-23 11:39
Hey @peterfabian I am interested in trying this out. What can be the next steps?

**Comment by lkraav** [comment] 2023-03-23 13:34
Oh I'm noticing not everybody in this issue might be aware: even before taking on HPOS migration risks, you should really try massively improved indexing with https://github.com/OllieJones/index-wp-mysql-for-speed

**Comment by peterfabian** [comment] 2023-03-27 11:56
@kuldeep3 
I'd recommend testing with your store on a staging/pre-prod environment. Grab the latest version of WC and you can enable HPOS via WC > Settings > Advanced > Features. Check if you have any incompatible plugins and if you do, please ping the authors to add HPOS support if possible. 

Our merchant-focused doc is in Woo docs: https://woocommerce.com/document/high-performance-order-storage/
For the latest dev-related updates, please follow the dev blog: https://developer.woocommerce.com/

**Comment by kuldeep3** [comment] 2023-03-27 19:09
> @kuldeep3 I'd recommend testing with your store on a staging/pre-prod environment. Grab the latest version of WC and you can enable HPOS via WC > Settings > Advanced > Features. Check if you have any incompatible plugins and if you do, please ping the authors to add HPOS support if possible.
> 
> Our merchant-focused doc is in Woo docs: https://woocommerce.com/document/high-performance-order-storage/ For the latest dev-related updates, please follow the dev blog: https://developer.woocommerce.com/

Thanks, will test it 😄
