### ISSUE TITLE
WooCommerce email templates unfindable in the website

### ISSUE THREAD

**Issue by Mark5663** [woocommerce/woocommerce#28431] opened 2020-11-27 06:39 UTC
Good day, 
I use WooCommerce in my website https://olives-en-provence.com/home/  for the shop. There are two languages, English and French. 
In the WooCommerce email templates for orders, I cannot find the text templates to amend/change the text. In the English templates, I can only find how to change the Header, whilst I cannot find the templates in French at all.  And yet customers are receiving order emails in French, so they must be there somewhere.

Can someone please tell me where I can find these email templates?

Regards, Mark
```
The System Status Report from my website:
````
### WordPress Environment ###

Home URL: https://olives-en-provence.com
Site URL: https://olives-en-provence.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.40
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.73.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 50.05MB
Database Data Size: 39.99MB
Database Index Size: 10.06MB
wp_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB
wp_blc_instances: Data: 0.05MB + Index: 0.05MB
wp_blc_links: Data: 0.16MB + Index: 0.06MB
wp_blc_synch: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_create_map: Data: 0.00MB + Index: 0.00MB
wp_et_social_stats: Data: 0.05MB + Index: 0.00MB
wp_group_map: Data: 0.00MB + Index: 0.00MB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB
wp_itsec_distributed_storage: Data: 5.02MB + Index: 0.02MB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_log: Data: 0.14MB + Index: 0.06MB
wp_itsec_logs: Data: 2.02MB + Index: 0.38MB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_map_locations: Data: 0.00MB + Index: 0.00MB
wp_ngg_album: Data: 0.02MB + Index: 0.02MB
wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB
wp_ngg_pictures: Data: 0.08MB + Index: 0.03MB
wp_options: Data: 3.45MB + Index: 0.11MB
wp_postmeta: Data: 2.52MB + Index: 0.70MB
wp_posts: Data: 4.48MB + Index: 0.31MB
wp_redirection_404: Data: 1.02MB + Index: 0.13MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_revslider_css: Data: 0.02MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_settings: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.05MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.08MB + Index: 0.06MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_usermeta: Data: 0.38MB + Index: 0.33MB
wp_users: Data: 0.06MB + Index: 0.05MB
wp_wfBlockedIPLog: Data: 0.05MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfConfig: Data: 1.28MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 3.52MB + Index: 0.00MB
wp_wfHits: Data: 9.02MB + Index: 5.55MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.31MB + Index: 0.13MB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB
wp_wfNotifications: Data: 0.06MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.14MB + Index: 0.11MB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB
wp_yoast_indexable: Data: 0.23MB + Index: 0.11MB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.19MB + Index: 0.11MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 613
custom_css: 1
customize_changeset: 3
display_type: 7
et_pb_layout: 85
gal_display_source: 5
lightbox_library: 7
nav_menu_item: 53
ngg_gallery: 7
ngg_pictures: 100
oembed_cache: 2
oxy_mega_columns: 2
oxy_mega_menu: 1
oxy_stack: 4
page: 54
portfolio_item: 1
post: 160
product: 13
revision: 263
shop_coupon: 1
shop_order: 42
timelinr: 28
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Polylang: by WP SYNTEX – 2.8.4
Cookie Consent - Free Edition: by Sebastien Bosquet – 1.9
Akismet Anti-Spam: by Automattic – 4.1.7
All-in-One WP Migration: by ServMask – 7.29
Plugin Security Checker: by juliobox – 2.2.1
iThemes Security: by iThemes – 7.9.0
Broken Link Checker: by WPMU DEV – 1.11.15
Contact Form 7 Datepicker: by Aurel Canciu – 2.6.0
Contact Form 7: by Takayuki Miyoshi – 5.3
Custom Sidebars: by WPMU DEV – 3.2.3
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 3.2.6
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.13.0
Google XML Sitemaps: by Auctollo – 4.1.1
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
iframe: by webvitaly – 4.5
WooCommerce Table Rate Shipping Plus: by mangohour – 1.6.0 – Not tested with the active version of WooCommerce
Monarch Plugin: by Elegant Themes – 1.2.2
PHP Compatibility Checker: by WP Engine – 1.5.0
Really Simple SSL: by Really Simple Plugins – 3.3.5
Redirection: by John Godley – 4.9.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.4
Revolution Slider: by ThemePunch – 4.6.5
Update ALT Attribute: by Maui Marketing – 2.3.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.34

WaspThemes - Yellow Pencil Pro: by WaspThemes – 5.5.6
WooCommerce Polylang Integration: by Darko Gjorgjijoski – 1.0.3
WooCommerce: by Automattic – 3.2.6 – 4.7.1 is available
WooSidebars: by WooCommerce – 1.4.5
Wordfence Security: by Wordfence – 7.4.12
Yoast SEO: by Team Yoast – 15.2.1
WP Google Maps: by WP Google Maps – 8.0.26
WP Mail Logging: by MailPoet – 1.9.7
WP Mail SMTP: by WPForms – 2.5.1
WP Robots Txt: by Christopher Davis – 1.1
WP Sitemap Page: by Tony Archambeau – 1.6.2
Smush: by WPMU DEV – 3.7.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1517 - /boutique-huile-d-olive-provence/
Cart: #1459 - /panier/
Checkout: #1460 - /paiement/
My account: #1461 - /mon-compte/
Terms and conditions: #1591 - /cgv/

### Theme ###

Name: Divi child theme
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 2.3.2
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 17
Oldest: 2020-11-09 16:29:14 +0000
Newest: 2020-11-27 06:29:09 +0000

Pending: 1
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

`
</details>

**Comment by rrennick** [comment] 2020-11-27 14:19
Hi @Mark5663,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rrennick** 2020-11-27 14:19 UTC

**Comment by Mark5663** [comment] 2020-11-27 16:37
OK Ron, thanks for your answer. 
Mark. 

Mark Whitcombe-Power
00 33 (0) 6 16 52 43 83



On 27 Nov 2020, at 15:21, Ron Rennick <notifications@github.com> wrote:


Hi @Mark5663,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

	• Review WooCommerce Self-Service Guide to see if the solutions listed there apply to your case;
	• If you are a paying customer of WooCommerce, contact WooCommerce support by opening a ticket or starting a live chat;
	• Make a post on WooCommerce community forum
If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
