### ISSUE TITLE
[GlobalStep - WooCommerce 4.8 Beta 1] For "Twenty Twenty One" theme, checkbox appears truncated on Checkout page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28341] opened 2020-11-19 16:02 UTC
## Bug Description:
For "Twenty Twenty One" theme, checkbox appears truncated on Checkout page.

## Environment:
Windows 10, macOS Mojave:10.14.6 (18G103)
Browser: Chrome(Version 86.0.4240.75 (64-bit))
                 Firefox(Version 82.0)(64-bit)
                 Safari(Version 13.1.1 (14609.2.9.1.3))

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Setup wizard.
1. Choose "Twenty Twenty One" theme.
1. Import or Add products.
1. Go to frontend.
1. Add any product to Cart.
1. Go to Checkout page.
1. Observe that checkbox appears truncated on Checkout page.

## Actual Result:
For "Twenty Twenty One" theme, checkbox appears truncated on Checkout page.

## Expected Result:
Checkbox should properly display on Checkout page.

## Artifacts:
![#28341](https://user-images.githubusercontent.com/41110392/99691021-c56f1680-2aae-11eb-9d73-de4301f9eb14.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment] 2020-11-20 19:16
Thanks @gglobalstep 

The issue you are having seems to be caused by the plugin Creative Mail by Constant Contact. I'm closing this for now and we will try raise it with them directly.

**Comment by tammullen** [comment] 2020-11-20 19:25
Reopening this as It appears to be happening to other checkboxes in Twenty Twenty-One such as the MailChimp checkbox so  may need checked if anything needs done in core for this.
![Screenshot_2020-11-20_at_19_21_27](https://user-images.githubusercontent.com/24649833/99841470-1ee64c80-2b66-11eb-8194-ad035529f539.png)

Related: https://github.com/woocommerce/woocommerce/issues/28305

**Comment by ObliviousHarmony** [comment] 2020-12-07 23:46
In my testing this appears to be fixed!

**Closed by ObliviousHarmony** 2020-12-07 23:46 UTC
Labels: status: needs developer feedback
