### ISSUE TITLE
My customer and I aren't getting emails notification when an order is placed

### ISSUE THREAD

**Issue by kevinkda12** [woocommerce/woocommerce#28768] opened 2021-01-09 17:06 UTC
Hello! It's a pretty simple issue that I yet haven't been able to find a solution. I recently launched an online store with wordpress and woocommerce (herbolariumjadis@gmail.com). I had my first order yesterday but I didn't get any email notification and neither my customer. I've checked the woocommerce settings page and it looks fine. I did make another order to check it it was going to work but nothing happened. I've watched a couple of tutorials but they all explain what I already know and people on the comments have been saying that they haven't been able to fix it either. Should I contact my webhost? wordpress? Please any help is appreciated and thank you beforehand!!

We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
Contact WooCommerce support by opening a ticket.
https://woocommerce.com/contact-us/ 

**For help with custom code**
WooCommerce Slack Community: https://woocommerce.com/community-slack/ in the `#developers` channel. 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The Official WooCommerce Facebook Group https://www.facebook.com/groups/advanced.woocommerce/

**Comment by juliaamosova** [comment] 2021-01-10 23:17
Hi @kevinkda12,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

**In your case, I can also recommend reviewing [WooCommerce Email FAQ](https://docs.woocommerce.com/document/email-faq/) documentation that suggests troubleshooting steps to take in order to fix your issue.** 

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2021-01-10 23:17 UTC
