### ISSUE TITLE
Applying coupon code - inconsistent behavior when applying from cart or from backend

### ISSUE THREAD

**Issue by simplenotezy** [woocommerce/woocommerce#26899] opened 2020-06-30 13:13 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate (that is not closed)

### The issue
Coupon is applied differently when added from cart than when added from backend.

#### From cart (`$order->apply_coupon('50-percent-off');`):
![image](https://user-images.githubusercontent.com/3786627/86128915-3ef76f80-bae2-11ea-8acb-792e3eba0e69.png)

#### From backend:
![image](https://user-images.githubusercontent.com/3786627/86128979-4f0f4f00-bae2-11ea-84b8-76e287e4a05c.png)

### A video illustrating the bug:
https://youtu.be/bEkpnWlqZA4

### How I apply the coupon code
Since WordPress in my case is acting as a headless CMS, I apply the coupon code in a custom code. This is how I apply it:

    $order->apply_coupon('50-percent-off');

I am not sure how the WordPress admin backend applies it, however, when it is applied from the backend / edit order section, it is applied correctly.

I previously tried to describe the error here, however, it was closed for an unknown reason: https://github.com/woocommerce/woocommerce/issues/26332

It is a pretty critical issue as we cannot issue discount codes to our customers.

**Comment by tammullen** [comment] 2020-07-02 10:41
Hi @simplenotezy 

To help us evaluate this issue further can you provide us with the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.


Can you also please try testing your site for theme and plugins conflict. To do that deactivate all plugins except for WooCommerce and switch to a default WordPress theme or [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again. If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by claudiosanches** [comment] 2020-07-16 01:50
Duplicated of #23655

**Comment by claudiosanches** [comment] 2020-07-16 14:56
Sorry, in fact it calculates a little different, I'll check this issue later, but it isn't duplicated.

**Comment by simplenotezy** [comment] 2020-07-22 19:22
Thanks for finally realizing this isn't a duplicate - I have made huge efforts to try to explain the issue 😊 I have made several checks to ensurethere'ss no conflicting plugins. What else do you need from me, to have a look at this issue?

**Comment by claudiosanches** [comment] 2020-08-07 00:47
@simplenotezy can you please share all details of the coupon? There's any restrictions?

**Comment by simplenotezy** [comment] 2020-08-12 13:53
@claudiosanches no, it's a default coupon with no restrictions. The tax/total discount of the coupon code is different when it is applied from frontend vs from the WordPress admin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by claudiosanches** [comment] 2020-08-13 22:12
@simplenotezy please share all settings of the coupon, I want to reproduce using the same coupon if possible, but I can't find any place, only in the video, but you pass there very quickly, so please paste here all information necessary to set this coupon.

**Comment by simplenotezy** [comment] 2020-08-18 13:46
Okay, so a bit more testing has been done, and I must admit the case is extremely weird.

I noticed the following: setting a product as "Taxable" to "None" would give the correct discount on product.

Then I did more testing and noticed the code was structured like so:

    // $order->add_product($product, 1)
    // $order->apply_coupon('50-percent-off')
    // $order->calculate_totals();
    // $order->save();

This would result in a total price of 720, even though it should be 600, since the total price of the product was 1200.

However, if I flip the position of `apply_coupon()` and `calculate_totals()` then the result is 600 (100% correct) no matter if the product is taxable or not. So the final code would be:

Working example:

    // $order->add_product($product, 1)
    // $order->calculate_totals();
    // $order->apply_coupon('50-percent-off')
    // $order->save();

What's even more weird is that apparently the old developer must've made the same mistake, because despite this code being my own (in a headless-CMS approach) our old theme developer must've made the same mistake, since we originally discovered the issue months ago on the told theme (https://github.com/woocommerce/woocommerce/issues/26332)

Would love to be enlightened a bit on this subject, because despite it working now, I can't explain why "calculate_totals" has to go before `apply_coupon`

**Comment by claudiosanches** [comment] 2020-08-18 17:24
@simplenotezy Thanks for giving me full details of the your custom implementation.

This happens because there's no proper tax information on your implementation, so `$order->calculate_totals()` will calculate with the standard values.
Instead you need:

```php
// Set tax args.
$calculate_tax_args = array(
    'country'  => 'COUNTRY_CODE',
    'state'    => 'STATE_CODE_OR_NAME',
    'postcode' => 'POSTCODE',
    'city'     => 'CITY_NAME',
);

$order->add_product( $product, 1 );

// Apply coupon and check if there's any error.
$result = $order->apply_coupon( '50-percent-off' );
if ( is_wp_error( $result ) ) {
	throw new Exception( html_entity_decode( wp_strip_all_tags( $result->get_error_message() ) ) );
}
$order->calculate_taxes( $calculate_tax_args );
$order->calculate_totals( false );
$order->save();
```

It should solve everything for you.

You can also check how we does it by ajax in:

https://github.com/woocommerce/woocommerce/blob/02cf0dfaed5923513de0c88add597d1560c2cfd2/includes/class-wc-ajax.php#L1122-L1178

I'll closing since issue since it's for custom implementation and it works just fine, but need to remember about taxes.

**Comment by simplenotezy** [comment] 2020-10-13 10:33
Hey @claudiosanches thanks for a very in-depth answer. Really appreciate it.

I have tried to implement your logic, but it seems to provide two very different results.

When applying in this order:

    - $order->calculate_taxes( $calculate_tax_args );
    - $order->calculate_totals(false);
    - $order->apply_coupon($coupon); // a fixed_discount coupon which amount is higher than the order items value
    - $order->save();

It WORKS perfectly. It generates the following output:
![image](https://user-images.githubusercontent.com/3786627/95849656-0bb6b480-0d50-11eb-9420-fedeec8eccbd.png)

However, some strange things happens when I try to do your proposal.

    - $order->apply_coupon($coupon); // a fixed_discount coupon which amount is higher than the order items value
    - $order->calculate_taxes( $calculate_tax_args );
    - $order->calculate_totals(false);
    - $order->save();

In this case, the order value is very weird, and I don't know why:

![image](https://user-images.githubusercontent.com/3786627/95849869-3d2f8000-0d50-11eb-84e1-71db723cf55f.png)

The only difference between two screenshots is, one Order is made with the "original" sequence, and the other one with your proposed new sequence.

This really looks like a bug to me, but I might be wrong.

**Comment by simplenotezy** [comment] 2020-10-14 09:04
Also, another issue we face now is that VAT is 0 when applying a fixed_amount discount code. Have a look here:

![image](https://user-images.githubusercontent.com/3786627/95967648-c86e4b80-0e0c-11eb-95e4-3b6d3ab5ce09.png)

You'll notice that VAT is 0.

However, the same products just bought with a percent discount (10%) it shows VAT perfectly:

![image](https://user-images.githubusercontent.com/3786627/95967725-dcb24880-0e0c-11eb-80c1-0da54f7c1648.png)

I am very surprised by the inconsistent behaviour we see, even with the same code. 

I would like to request you to kindly reopen the issue @claudiosanches

**Comment by simplenotezy** [comment] 2020-10-14 09:13
Some additional information; when applying coupon that has a fixed_amount, and then calling `$item->get_total_tax()` on the order item, it returns 0.

If I choose not to apply the coupon, and then call `$item->get_total_tax()` it returns the correct TAX amount.

Why is that?

**Comment by simplenotezy** [comment] 2020-10-14 09:23
Also theres a mismatch between the order confirmation e-mail we receive and the data inside the order.

![image](https://user-images.githubusercontent.com/3786627/95970002-bc37bd80-0e0f-11eb-98c9-ff3a9976b077.png)
![image](https://user-images.githubusercontent.com/3786627/95970012-bfcb4480-0e0f-11eb-8541-1654b57d3cc9.png)

**Comment by tammullen** [comment] 2020-10-27 14:22
Reopening with the additional information

**Comment by simplenotezy** [comment] 2021-03-10 10:19
Let me know if you need anything from me

**Comment by claudiosanches** [comment] 2021-09-27 21:35
Hello @simplenotezy,

Sorry for the delay.

Looking by the output of those images I don't think the results are correct: https://github.com/woocommerce/woocommerce/issues/26899#issuecomment-707650301

Note that the first screenshot there's no taxes calculated, this is the incorrect behavior, when you apply the same as I described it calculates all totals as expected, I understand that you are expecting different, but this seems to be correct, it need to include the taxes, it happens because need to have all tax information before running `$order->calculate_totals( false )`.
Also note that the coupon will be applied only to the products amount, since it's illegal to apply discounts to taxes.
Alternatively you could use `$order->calculate_totals( true )` so WooCommerce will use try match taxes based in the customer address already saved to the order, or maybe to run it before and after applying a coupon could help in your implementation.

I recommend you to follow the same we use inside our internal methods, trying to change the order of methods will result in unexpected behaviors as I advised before.

I'm going to close this issue again, because I can't see any bug on WooCommerce side, it works perfect and seems like to be caused by a custom implementation on your side.
Thanks.

**Closed by claudiosanches** 2021-09-27 21:35 UTC
Labels: needs developer feedback
