### ISSUE TITLE
Product data options not visible in admin

### ISSUE THREAD

**Issue by bwallx** [woocommerce/woocommerce#28280] opened 2020-11-13 19:45 UTC
Ongoing issue - product data options not showing, just the headings. I've done EVERYTHING and no joy.

![2020-11-13 16_16_16-Edit product ‹ Ventura Gifts — WordPress and 1 more page - Personal - Microsoft​](https://user-images.githubusercontent.com/50273227/99114447-1edbcf00-25f1-11eb-9421-e67d555f8a84.png)

**Comment by juliaamosova** [comment] 2020-11-13 19:48
Hi @bwallx,

Thanks for raising the issue and sorry to hear about the trouble. 

Note that we have fixed this issue on the WooCommerce side of things in version 4.3.2 (https://github.com/woocommerce/woocommerce/pull/27170). However, this issue is present on sites using WC 4.3.2+ where the issue is caused by 3rd party plugins.

WordPress 5.5 removed a javascript file called jquery-migrate that some of the plugins might still rely on. Until they update, the workaround is to use [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin to include the javascript files in the meantime.

Note that you may need to clear your browser’s cache and cookies in order for the Enable jQuery Migrate Helper plugin to take effect.

It is further recommended that you test your site for theme and plugins conflict to identify what plugin needs updating and contact that plugin author further for the issue to be fixed on that 3rd party plugin side.

To test your site for theme and plugins conflict, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by bwallx** [comment] 2020-11-13 19:57
Thanks for quick response, but it doesn't help. I followed everything you suggested (I'd already done that several times, including staging) but it makes no difference. I tried several themes too. 

My site is broken due to your programmers.

**Comment by juliaamosova** [comment] 2020-12-29 21:18
Hi @bwallx,

My apologies for the delayed response here. Would you please confirm if the issue is still present for you?

**Comment by juliaamosova** [comment] 2021-01-10 21:49
Hi @bwallx,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-01-10 21:49 UTC
Labels: needs feedback, type: support request
