### ISSUE TITLE
Bug regarding Product options

### ISSUE THREAD

**Issue by zarbmark** [woocommerce/woocommerce#27737] opened 2020-09-21 18:47 UTC
Wordpress in no longer giving me the option to select among the variables when creating a new product next to the **product data section**. The option disappeared which is why I can no longer have multiple options such as size for the customer to purchase my products. The variable product option is very important for my site and I need it back as soon as possible.
Looking forward to hearing from you,
Regards, 
zarbmark@hotmail.com

**Comment by juliaamosova** [comment] 2020-09-21 18:57
Hi @zarbmark,

Thanks for raising the issue and sorry to hear about the trouble. 

Note that we have fixed this issue on the WooCommerce side of things in version 4.3.2 (https://github.com/woocommerce/woocommerce/pull/27170). However, this issue is present on sites using WC 4.3.2+ where the issue is caused by 3rd party plugins.

WordPress 5.5 removed a javascript file called jquery-migrate that some of the plugins might still rely on. Until they update, the workaround is to use [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin to include the javascript files in the meantime.

Note that you may need to clear your browser’s cache and cookies in order for the Enable jQuery Migrate Helper plugin to take effect.

It is further recommended that you test your site for theme and plugins conflict to identify what plugin needs updating and contact that plugin author further for the issue to be fixed on that 3rd party plugin side.

To test your site for theme and plugins conflict, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by zarbmark** [comment] 2020-09-22 16:23
Dearest Julia,
Last I upgraded to the latest version of woocommerce (last week), I had my shop deleted and had to resort to a back-up. I am by no means an expert in tech and this is a great inconvenience to me because I am afraid it will jeopardize all the work I have built up in the last year and have it deleted again. What shall I do, this is very frustrating and my client is getting upset.
regards,
mark

________________________________

**Comment by tammullen** [comment] 2020-10-02 21:09
Hi @zarbmark 

> What shall I do

Can you confirm if you have tried either of the suggested solutions suggested?
- Use [Enable jQuery Migrate Helper plugin](https://wordpress.org/plugins/enable-jquery-migrate-helper/)
- Test your site for theme and plugins conflict

**Comment by juliaamosova** [comment] 2020-10-09 21:40
Hi @zarbmark,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-10-09 21:40 UTC
Labels: status: needs feedback, support request
