### ISSUE TITLE
Error saving action: Database error. on checkout page 

### ISSUE THREAD

**Issue by rachnawasnik** [woocommerce/woocommerce#28733] opened 2021-01-06 12:16 UTC
Hi,
I am facing issue since past 2 days. when added a product in shopping cart and clicked submit. i was able to  see  checkout page. But when updating the shipping address, it showed me error "Error saving action: Database error." .

But today neither Frontend nor Backend is working. 

URL : - https://brainwork.co.in/anwarco/
Admin url : https://brainwork.co.in/anwarco/wp-admin

Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'https://brainwork.co.in/anwarco/'

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2021-01-10 21:58
Hi @rachnawasnik,

Thank you for raising the issue. However, you did not provide clear steps to reproduce the issue. 

It will also be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment. 

Aside from that, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2021-01-10 22:05
Hi @rachnawasnik,

Thank you for reporting the issue. However, this issue had been reported by you here as well https://github.com/woocommerce/woocommerce/issues/28746. We are closing your issue in favor of https://github.com/woocommerce/woocommerce/issues/28746. Please continue sharing your feedback there if needed.

**Closed by juliaamosova** 2021-01-10 22:05 UTC
Labels: needs feedback
