### ISSUE TITLE
Could not insert term into the database.

### ISSUE THREAD

**Issue by scottknowls** [woocommerce/woocommerce#29360] opened 2021-03-12 07:33 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Experiencing error when trying to make a new value in product attribute. The error message is "Could not insert term into the database."

Screenshot added for ref. http://prntscr.com/10jhcfk

**Expected behavior**
A new value in attribute must be added

**Actual behavior**
After adding necessary input and clicking the Submit button, an error message appear on top of the page

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment] 2021-03-12 16:25
Hi @scottknowls ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested on the following:

* WooCommerce 5.1
* WordPress 5.7

### Replication steps
* I navigated to Products > Attributes > and selected "Configure Terms"

<img width="798" alt="Screen Shot 2021-03-12 at 9 20 26 AM" src="https://user-images.githubusercontent.com/71906536/110968008-3ebb9f00-8314-11eb-9af8-a3bff9017739.png">

* I went to add a new Color, in this case, `Fuchsia`:

<img width="1508" alt="Screen Shot 2021-03-12 at 9 17 35 AM" src="https://user-images.githubusercontent.com/71906536/110968236-87735800-8314-11eb-8e35-7340c1795dd0.png">

* I clicked "Add attribute" and it was successfully added to the list:

<img width="984" alt="Screen Shot 2021-03-12 at 9 17 46 AM" src="https://user-images.githubusercontent.com/71906536/110968298-93f7b080-8314-11eb-98d6-6b85fde7ced0.png">

I noticed the attribute terms interface is a bit different than mine, where it does not include the option for a product image:

<img width="530" alt="Screen Shot 2021-03-12 at 9 17 12 AM" src="https://user-images.githubusercontent.com/71906536/110968128-67439900-8314-11eb-9781-f16f0f6d7593.png">

I believe this issue may be being caused by a plugin. Have you deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active?

If you can also help provide your system report, this will help us further evaluate the issue. You can do this by going to `WooCommerce > System Status`. Thank you!

**Comment by scottknowls** [comment] 2021-03-15 01:53
Thank you for your reply @zhongruige. Highly appreciated

For the product image, we used a plugin to add image in our swatches.

We already did the plugin deactivation but still the error is there.

Here is our Woocommerce Status Report

`
### WordPress Environment ###

WordPress address (URL): https://www.[hidden].com.au
Site address (URL): https://www.[hidden].com.au
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.4
PHP Version: 7.3.24-3+ubuntu20.04.1+deb.sury.org+1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wpqb_
Total Database Size: 142.05MB
Database Data Size: 124.96MB
Database Index Size: 17.09MB
wpqb_woocommerce_sessions: Data: 5.02MB + Index: 0.16MB + Engine InnoDB
wpqb_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wpqb_woocommerce_order_items: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wpqb_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.03MB + Engine InnoDB
wpqb_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqb_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_actionscheduler_actions: Data: 2.02MB + Index: 0.72MB + Engine InnoDB
wpqb_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_actionscheduler_logs: Data: 1.03MB + Index: 0.41MB + Engine InnoDB
wpqb_booking_block_price_attribute_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_booking_block_price_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_booking_fixed_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_booking_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_booking_order_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpqb_comments: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wpqb_cp_calculated_fields_form_discount_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_cp_calculated_fields_form_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_cp_calculated_fields_form_revision: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wpqb_cp_calculated_fields_form_settings: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpqb_expm_hiiden_content: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_expm_maker: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_expm_maker_pages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_find_and_replace: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_gf_entry: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wpqb_gf_entry_meta: Data: 0.28MB + Index: 0.20MB + Engine InnoDB
wpqb_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_gf_form_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpqb_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_gf_form_view: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wpqb_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_litespeed_img_optm: Data: 0.22MB + Index: 0.13MB + Engine InnoDB
wpqb_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_ngg_pictures: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_options: Data: 4.34MB + Index: 0.22MB + Engine InnoDB
wpqb_postmeta: Data: 34.53MB + Index: 8.02MB + Engine InnoDB
wpqb_posts: Data: 58.48MB + Index: 1.33MB + Engine InnoDB
wpqb_redirection_404: Data: 2.02MB + Index: 0.25MB + Engine InnoDB
wpqb_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_redirection_items: Data: 0.33MB + Index: 0.45MB + Engine InnoDB
wpqb_redirection_logs: Data: 0.17MB + Index: 0.05MB + Engine InnoDB
wpqb_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wpqb_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_revslider_sliders: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wpqb_revslider_slides: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wpqb_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_rg_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpqb_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqb_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_termmeta: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wpqb_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpqb_term_relationships: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wpqb_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpqb_usermeta: Data: 0.47MB + Index: 0.28MB + Engine InnoDB
wpqb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wc_customer_lookup: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wpqb_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_wc_order_product_lookup: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wpqb_wc_order_stats: Data: 0.09MB + Index: 0.23MB + Engine InnoDB
wpqb_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpqb_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wpqb_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_wfblockediplog: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wpqb_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_wfconfig: Data: 1.30MB + Index: 0.00MB + Engine InnoDB
wpqb_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqb_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wflogins: Data: 0.34MB + Index: 0.13MB + Engine InnoDB
wpqb_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqb_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqb_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wpqb_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_wonderplugin_gridgallery: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpqb_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpqb_woocommerce_shipping_table_rates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpqb_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqb_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqb_yoast_indexable: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wpqb_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpqb_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqb_yoast_primary_term: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wpqb_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wpqb_yoast_seo_meta: Data: 2.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 95
acf-field-group: 3
attachment: 1472
bkap_booking: 15
brands: 8
custom_css: 2
customize_changeset: 10
fade_slider: 1
footer: 2
gallery: 12
image-gallery: 1
mc4wp-form: 1
ml-slide: 2
ml-slider: 1
nav_menu_item: 113
ocw_carousel: 1
page: 54
popup: 4
popup_theme: 9
post: 132
postman_sent_mail: 250
product: 54
product_variation: 312
revision: 4468
sa_slider: 2
shop_coupon: 3
shop_order: 604
shop_order_refund: 7
shop_subscription: 8
slick_slider: 1
soliloquy: 1
tcportfolio: 2
testimonials: 4
vc_grid_item: 1
vc_settings_preset: 11
wp_block: 6
wp1slider: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

ManageWP - Worker: by GoDaddy – 4.9.8
Gravity Forms: by rocketgenius – 2.4.5.2
Advanced Custom Fields: by Elliot Condon – 5.9.5
Schema - All In One Schema Rich Snippets: by Brainstorm Force – 1.6.4
Better Search Replace: by Delicious Brains – 1.3.4
Recurring Bookings Addon for Bookings and Appointment plugin: by Tyche Softwares – 2.1
Rental System Addon: by Tyche Softwares – 1.12
Calculated Fields Form: by CodePeople – 1.0.450
Classic Editor: by WordPress Contributors – 1.6
Display Posts: by Bill Erickson – 3.0.2
Duplicate Page: by mndpsingh287 – 4.3
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.6
Enhanced E-commerce for Woocommerce store: by Tatvic – 3.0.1
Read More: by Edmon – 2.7.0
Facebook for WooCommerce: by Facebook – 2.3.2
GaviasFramework: by Gaviasthemes Team – 1.0.0
Go Gallery: by AMPAE – 1.1
Insert Headers and Footers: by WPBeginner – 1.5.0
WPBakery Page Builder: by Michael M - WPBakery.com – 6.6.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.3
Meta Box: by MetaBox.io – 5.3.9
NitroPack: by NitroPack LLC – 1.5.2
Open External Links in a New Window: by WebFactory Ltd – 1.42
Popup Maker: by Popup Maker – 1.16.0
Post SMTP: by Yehuda Hassine – 2.0.22
Read More Without Refresh: by George Gkouvousis – 3.1
Redirection: by John Godley – 5.0.1
Woocommerce Shipping Calculator On Product Page: by Magerips – 2.4
Simple 301 Redirects: by Scott Nellé – 1.07
Slide Anything - Responsive Content / HTML Slider and Carousel: by Simon Edge – 2.3.33
Update ALT Attribute: by Maui Marketing – 2.4.0
Wonder Grid Gallery Trial: by Magic Hills Pty Ltd – 15.7
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.13
WooCommerce Admin: by WooCommerce – 2.1.2
Booking & Appointment Plugin for WooCommerce: by Tyche Softwares – 5.6.0
WooCommerce Stripe Gateway: by WooCommerce – 4.9.0
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.8.20
PPOM for WooCommerce by N-MEDIA: by Najeeb Ahmad – 21.2
WooCommerce Google Product Feed: by Lee Willis – 7.0.1
WooCommerce Subscriptions: by WooCommerce – 3.0.7
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30
WooCommerce: by Automattic – 5.1.0
Wordfence Security: by Wordfence – 7.4.14
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO: by Team Yoast – 15.9.2
WP 1 Slider: by AccessPress Themes – 1.2.8
WP 404 Auto Redirect to Similar Post: by hwk-fr – 1.0.3
WP Htaccess Editor: by WebFactory Ltd – 1.70
Smush Nonstop: by obiPlabon – 2.0.0
WP Product Selector: by WP Dev Shed – 1.0.6
Smush: by WPMU DEV – 3.8.3

### Inactive Plugins (5) ###

Calculate Shipping Button: by  – 1.2.2
Contact Form 7: by Takayuki Miyoshi – 5.4
Max Mega Menu: by megamenu.com – 2.9.3
Really Simple SSL: by Really Simple Plugins – 4.0.11
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.4
ManageWP - Worker Loader: by GoDaddy –

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2922 - /shop/
Cart: #3820 - /cart/
Checkout: #3701 - /checkoutpage/
My account: #2925 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Kiamo child
Version: 1.11
Author URL: http://gaviasthemes.com/
Child Theme: ✔
Parent Theme Name: Kiamo
Parent Theme Version: 1.2.0
Parent Theme Author URL: http://gaviasthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: kiamo-child/woocommerce/archive-product.php
kiamo-child/woocommerce/cart/cart.php
kiamo-child/woocommerce/cart/mini-cart.php
kiamo-child/woocommerce/content-product.php
kiamo-child/woocommerce/content-single-product.php
kiamo-child/woocommerce/global/breadcrumb.php
kiamo-child/woocommerce/global/quantity-input.php
kiamo-child/woocommerce/global/wrapper-end.php
kiamo-child/woocommerce/global/wrapper-start.php
kiamo-child/woocommerce/loop/add-to-cart.php
kiamo-child/woocommerce/loop/loop-end.php
kiamo-child/woocommerce/loop/loop-start.php
kiamo-child/woocommerce/loop/orderby.php
kiamo-child/woocommerce/loop/pagination.php
kiamo-child/woocommerce/loop/price.php
kiamo-child/woocommerce/loop/rating.php
kiamo-child/woocommerce/loop/sale-flash.php
kiamo-child/woocommerce/notices/error.php
kiamo-child/woocommerce/notices/notice.php
kiamo-child/woocommerce/notices/success.php
kiamo-child/woocommerce/single-product/meta.php
kiamo-child/woocommerce/single-product/rating.php
kiamo-child/woocommerce/single-product/related.php
kiamo-child/woocommerce/single-product/sale-flash.php
kiamo-child/woocommerce/single-product/share.php
kiamo-child/woocommerce/single-product/short-description.php
kiamo-child/woocommerce/single-product/tabs/additional-information.php
kiamo-child/woocommerce/single-product/tabs/description.php
kiamo-child/woocommerce/single-product/tabs/tabs.php
kiamo-child/woocommerce/single-product/title.php
kiamo-child/woocommerce/single-product/up-sells.php
kiamo-child/woocommerce/single-product.php


### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.[hidden].com.au
Subscription Statuses: wc-expired: 2
wc-on-hold: 4
wc-cancelled: 2

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Australia — New South Wales

### Subscriptions by Payment Gateway ###

other: wc-cancelled: 2
wc-on-hold: 3

Stripe: wc-expired: 2
wc-on-hold: 1


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

Direct bank transfer: products

### Action Scheduler ###

Complete: 2,409
Oldest: 2021-02-12 01:30:18 +0000
Newest: 2021-03-15 01:15:30 +0000

Failed: 4
Oldest: 2020-04-23 06:27:49 +0000
Newest: 2020-07-14 06:14:28 +0000

Pending: 3
Oldest: 2021-03-15 02:15:30 +0000
Newest: 2021-03-15 02:15:30 +0000


### Status report information ###

Generated at: 2021-03-15 01:27:52 +00:00
`

**Comment by juliaamosova** [comment] 2021-04-27 20:24
Hi @scottcwilson,

Thank you for providing additional information. The issue you are having seems to be caused by WordPress, not WooCommerce. I found this thread here with the solution that you can try: https://wordpress.stackexchange.com/questions/226245/could-not-insert-term-into-the-database. 

If this doesn't help, I recommend you post your question further on WordPress forums: https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Meanwhile, I am closing this thread as a non-WooCommerce bug.

**Closed by juliaamosova** 2021-04-27 20:24 UTC
Labels: has feedback
