### ISSUE TITLE
Importer Does Not Import Images w/Just Filename Despite Documentation

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#30038] opened 2021-06-03 21:58 UTC
![Screenshot 2021-06-03 173619](https://user-images.githubusercontent.com/11934431/120717322-59c22900-c495-11eb-8d8e-00454933446d.png)
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Doc says images need only the file name if they are placed in /wp-content/uploads/product_images/ ahead of time. This is not accurate in practice. Only when the full path is used (https://domain.com/wp-content/uploads/product_images/) do the images attach and the importer sees them.

**Expected behavior**
Images are supposed to be found and attached using just the file name in the import CSV, according to the Woo documentation. 

**Actual behavior**
Produces an error "Unable to use [image.jpg]". Error message isn't even accurate. Message should say "Unable to FIND [image.jpg]". Error makes it seem like there is something wrong with the file, which is not the case. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Place your images in the /product_images/ folder. 
2. Add just the file names to the Images column in your import CSV
3. Run the import.

**Screenshots**
Attached. Left image shows images in proper folder. Right top shows Woo docs incorrect info on image file names. Right bottom shows error upon import.

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://sandwichspotssf.com
Site address (URL): https://sandwichspotssf.com
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.16
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.19-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wpa4_
Total Database Size: 7.90MB
Database Data Size: 5.75MB
Database Index Size: 2.15MB
wpa4_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpa4_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpa4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpa4_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpa4_duplicator_packages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpa4_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpa4_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_options: Data: 2.27MB + Index: 0.16MB + Engine InnoDB
wpa4_postmeta: Data: 2.02MB + Index: 0.03MB + Engine InnoDB
wpa4_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wpa4_realmedialibrary: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_realmedialibrary_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_realmedialibrary_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpa4_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpa4_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpa4_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpa4_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpa4_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpa4_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpa4_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpa4_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_woos_search_trends: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 10
cs_footer: 1
cs_header: 1
cs_template: 1
page: 9
post: 2
postman_sent_mail: 1
product: 14
revision: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Classic Editor: by WordPress Contributors – 1.6
Customer Reviews for WooCommerce: by CusRev – 4.15
Disable Admin Notices Individually: by Creative Motion  – 1.2.6
Duplicator: by Snap Creek – 1.4.1
GPLVault Update Manager: by GPL Vault – 3.4.0
Gravity Forms: by Gravity Forms – 2.5.5
Imagify: by WP Media – 1.9.14
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.7
MainWP Child: by MainWP – 4.1.6.1
Mobile Address Bar Changer: by Anshul Labs – 3.0
Post Duplicator: by Metaphor Creations – 2.22
Really Simple SSL: by Really Simple Plugins – 4.0.15
Hide SEO Bloat: by SO WP – 3.14.7
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.58.25

WC Password Strength Settings: by Daniel Santoro – 2.2.2
Advanced Shipment Tracking for WooCommerce: by zorem – 3.2.4.1
Woo Search Box: by Guaven Labs – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 5.2.0
WooCommerce Google Analytics Pro: by SkyVerge – 1.10.0
WooCommerce Smart Coupons: by StoreApps – 4.21.0
WooCommerce Tab Manager: by SkyVerge – 1.14.1
WooCommerce: by Automattic – 5.3.0
YITH WooCommerce Best Sellers Premium: by YITH – 1.1.26
YITH WooCommerce Customize My Account Page: by YITH – 3.1.1

### Inactive Plugins (10) ###

Add Descendants As Submenu Items: by Alex Mills (Viper007Bond) – 1.2.1
ManageWP - Worker: by GoDaddy – 4.9.8
My Custom Functions: by Space X-Chimp – 4.49
Post SMTP: by Yehuda Hassine – 2.0.23
Stop Generating Unnecessary Thumbnails: by codexpert – 3.2.2
Tracking Code Manager: by IntellyWP – 2.0.1
White Label CMS: by www.videousermanuals.com – 2.2.2
WP Rocket: by WP Media – 3.9
Yoast SEO: by Team Yoast – 16.4
Yoast SEO: WooCommerce: by Team Yoast – 14.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #101 - /shop/
Cart: #102 - /cart/
Checkout: #103 - /checkout/
My account: #104 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Pro
Version: 4.3.3
Author URL: https://theme.co
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: pro/woocommerce/single-product/tabs/tabs.php
pro/woocommerce/single-product-reviews.php


### Action Scheduler ###

Complete: 25
Oldest: 2021-05-24 15:01:13 -0400
Newest: 2021-06-03 17:27:00 -0400


### Status report information ###

Generated at: 2021-06-03 17:49:34 -04:00
`
```
</details>

**Comment by tammullen** [comment] 2021-06-07 17:40
Hi @co50 ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

- I uploaded a test image to my site media library 
<img width="1373" alt="Screenshot_2021-06-07_at_18_32_51" src="https://user-images.githubusercontent.com/24649833/121064381-6a3d1100-c7bf-11eb-9269-e26589d09f31.png">

- I added the file name to the `Images` in a csv to import a new product
![Screenshot 2021-06-07 at 18 33 32](https://user-images.githubusercontent.com/24649833/121064544-a3758100-c7bf-11eb-816c-eded5ab74e68.png)

- I imported the CSV from Products > Import
<img width="769" alt="Screenshot 2021-06-07 at 18 35 04" src="https://user-images.githubusercontent.com/24649833/121064571-abcdbc00-c7bf-11eb-8672-51b0ba12065f.png">

- Product was imported and existing image was used
<img width="297" alt="Screenshot 2021-06-07 at 18 35 15" src="https://user-images.githubusercontent.com/24649833/121064606-b7b97e00-c7bf-11eb-98df-caa8c550fd1b.png">
<img width="299" alt="Screenshot 2021-06-07 at 18 35 26" src="https://user-images.githubusercontent.com/24649833/121064625-bc7e3200-c7bf-11eb-8c10-874ca9e91509.png">





Please provide us with more details about the issue which may help us to evaluate it further. 
Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by co50** [comment] 2021-06-08 18:07
Unfortunately, we've already had to use the alternate (full URL) method to import the catalog and since that part of this build is finished, I don't have the means or resources to continue troubleshooting. I mainly wanted to point out the bug. FWIW, the CSV Import Suite plugin works fine with just the file name and the file in the uploads folder. Perhaps this issue can be used as an example to, at the very least, make the error message more informative.

**Comment by AashikP** [comment] 2021-07-23 02:49
Hello @co50 

I tried to replicate this again and like @tammullen , I couldn't replicate the issue as well.

* Here's the CSV for a single product import that I used: https://d.pr/f/fDTSsD
* Image uploaded to site prior to importing the product:

    ![https://d.pr/i/Zs57QG+](https://d.pr/i/Zs57QG+)

**After successful import:**

![https://d.pr/i/1s6qmh+](https://d.pr/i/1s6qmh+)

![https://d.pr/i/aRTjMp+](https://d.pr/i/aRTjMp+)

Considering that this cannot be replicated, and you can't further troubleshoot this, we'll go ahead and close this issue for now. 

Please feel free to add a comment if there are steps we missed during testing and we're happy to further investigate.

**Closed by AashikP** 2021-07-23 02:49 UTC
Labels: category: can't reproduce
