### ISSUE TITLE
CSV upload issue

### ISSUE THREAD

**Issue by paxxshoes** [woocommerce/woocommerce#26826] opened 2020-06-19 20:56 UTC
I've found a few posts about this, but am not sure what i should be doing.  I have version 5.4.2. and it shows my plugins are up to date.  When i first worked with woocommerce i uploaded to square and then synced everything over.  It worked well, with minor issues.  I had 61 products uploaded and they all showed up.  I added 22 products to my spreadsheet, which showed up in square, but would not sync or show up in woocommerce.  I decided to upload directly to woocommerce and created a csv file to do so.  The csv file was uploaded directly and the original 61 products came in as duplicates, which is correct, however none of the new 22 uploaded.  They were tagged with 'invalid'.  One of the forum posts spoke about a 'mime' issue with the file, but i'm new to this and have no idea exactly what that means.  I've included some screenshots of the issue.  Thank you for any assistance or direction that can be given!
![Screenshot (8)](https://user-images.githubusercontent.com/67083567/85178917-a9d8b900-b24d-11ea-9743-bff660fa3423.png)
![Screenshot (7)](https://user-images.githubusercontent.com/67083567/85178940-b3fab780-b24d-11ea-808a-824e7883014c.png)

**Comment by juliaamosova** [comment] 2020-06-22 18:14
Hi @paxxshoes,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- If you are a paying customer of WooCommerce (looks like you are because you mentioned using Square extensions), contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/);
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case. 

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-06-22 18:14 UTC
