### ISSUE TITLE
WCObject "Faulted"

### ISSUE THREAD

**Issue by csamet07** [woocommerce/woocommerce#26208] opened 2020-04-18 08:49 UTC
Hello everyone,

I writing WooCommerce API.
Create api class:
```
public class myRestApi : RestAPI
    {
        public myRestApi(string url, string key, string secret, bool authorizedHeader = true, 
                                     Func<string, string> jsonSerializeFilter = null, 
                                     Func<string, string> jsonDeserializeFilter = null, 
                                     Action<HttpWebRequest> requestFilter = null,
                                     Action<HttpWebResponse> responseFilter = null) : base(url, key, secret, 
         authorizedHeader, jsonSerializeFilter, jsonDeserializeFilter, requestFilter, responseFilter) {   }
    }
```
continue.. nex class
```
public string x()
        {

            var result="";
            using (WebClient client= new WebClient())
            {
                result = client.DownloadString("https://www.domain.com/wp-json/wc/v3/products? 
                                                                  consumer_key=ck_75xxx&consumer_secret=cs_xxx");
            }
            var products2 = JsonConvert.DeserializeObject<List<Product>>(result);



            RestAPI rest = new RestAPI("https://www.domain.com/wp-json/wc/v3/", "ck_75xxx", 
                                                               "cs_xxxx");
            WCObject wc = new WCObject(rest);

            var products = wc.Product.GetAll();

            return products2.ToString();
        
        }
```

WebClient working and get products but, WCObject not working
 wc.Product.GetAll() = >   Error: Faulted Or WaitingForActivation

**Comment by claudiosanches** [comment] 2020-04-28 17:15
Hi csamet07,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2020-04-28 17:15 UTC
