### ISSUE TITLE
WooCommerce webhooks delivery

### ISSUE THREAD

**Issue by dcoturel** [woocommerce/woocommerce#28625] opened 2020-12-18 15:59 UTC
Hi everyone,

I wanted to know if there is any way to make webhook delivery recurrent. Let's say, every 5 minutes and by cron. I'm working on an ERP integration and it would be desirable to have this. I looked in the WooCommerce docs but couldn't find anything referring to this.

Saludos,

**Comment by ObliviousHarmony** [comment] 2021-01-21 20:54
Hi @dcoturel ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by ObliviousHarmony** 2021-01-21 20:54 UTC
Labels: needs developer feedback

**Comment by dcoturel** [comment] 2021-02-05 12:50
Hi Oblivious,

Thanks for your answer. This in fact isn't a bug, it is more like a doubt, question or request for information. I'll take a look at the slack channel.

Saludos,
