### ISSUE TITLE
Triplicate listing

### ISSUE THREAD

**Issue by Horsetags1** [woocommerce/woocommerce#14877] opened 2017-05-04 10:42 UTC
Latest release of everything.

Using the plugin Extra Product Options (who I've contacted and they say it's you), i go to choose a product for it to act on. and when i get the list of products (and it happens every time with different products) i get triplicate listings of the results.

Only choosing the top one works. 

If i choose the 2nd or 3rd listing  EPO doesn't recognise them

**Comment by claudiosanches** [comment] 2017-05-04 16:57
Not sure what you mean, not sure how "Extra Product Options" works and not sure why "it's WooCommerce".
Can you explain?

**Comment by claudiulodro** [comment] 2017-05-04 17:28
> who I've contacted and they say it's you

Did you get any info about what specifically is the problem on our end? Generally, it's on plugin developers to keep their plugins working correctly with new versions of WooCommerce and not the other way around. If we've broken backwards compatibility on something, that's different, but I don't have much info to go on here.

**Comment by Horsetags1** [comment] 2017-05-04 17:31
Hi Claudio,

Sorry, wrong for me to assume you know the Extra Product Options (EPO) plugin!

I will say that this is not causing me a problem but if a bug, i thought you may like to know

EPO gives me options for some of my products, more than i can get with the basic setup.

I can have a range of napkin colours with varying ranges of foils for each colour for example.

When i have made a 'Global form' (say for birthday napkins) in  EPO, i can then add the products i want affected within that form.

Usually i search (within the form)  for a product starting with, say, 40th (as you only need 3-4 letters for the search to work.)

(I am sure this was ok before the last Woo update btw.)

Here is the screen shot i sent the EPO author, showing, that now, when i put in for example 40th

i get 3 results of the same product.

![triple choice](https://cloud.githubusercontent.com/assets/28388755/25716486/1ac3c2a8-30f7-11e7-8a30-a640ec65ee49.png

When i first told the EPO author, is answer was - 

'Never seen something like that before. This list is coming from WooCommerce though. The plugin just uses WooCommerce API to show the product list.'
)

**Comment by claudiosanches** [comment] 2017-05-04 17:52
Sorry, but I can't see how this is an issue on WooCommerce.
There is no steps to reproduce, there is no explanation of how WooCommerce affect it.
For me the problem is in "Extra Product Options" plugin and the author should fix it or at least come here to report this issue, since for what you are saying, is affecting all "Extra Product Options" customers.

**Comment by Horsetags1** [comment] 2017-05-04 18:03
I wasn't actually saying it was the fault of woocommerce, i was just going by what the EPO author said, and the only reason i contacted you was, if it was a woocommerce bug, then you might like to know.

I'm not bothered by it and it doesn't cause me a problem, i only reported it as the EPO author said it was a woo problem and i though you may like to know, just in case it was your problem.

I am no coder and certainly don't want to go between one coder and another pointing fingers.

**Comment by claudiulodro** [comment] 2017-05-05 21:19
Going to close this, as it's something on EPO's end. WooCommerce's product searching seems to be working fine. Thanks for the report!

<img width="513" alt="screen shot 2017-05-05 at 2 18 00 pm" src="https://cloud.githubusercontent.com/assets/7317227/25764647/bdf988ee-319d-11e7-8e6a-f4c10969dbbe.png">

**Closed by claudiulodro** 2017-05-05 21:19 UTC

**Comment by Horsetags1** [comment] 2017-05-06 09:58
Small update.

This is nothing to do with EPO as the same thing happens when i search for upsells and cross sells in linked products tab.

The odd thing is, it only seems to be giving me triplicate results in products i have listed in the past week, the earlier products are shown with one listing on the searches. 

I have updated woo and i thing wordpress updated itself in the past week or so, so it is not EPO as that doesn't affect searches on the linked products tab.

**Comment by claudiosanches** [comment] 2017-05-08 17:39
Have you tested the other plugins that you have installed?

**Comment by Horsetags1** [comment] 2017-05-08 17:49
the only other plugin that uses the product search is a related products plugin that i have.

That plugin resides on the same 'linked products' tab as the cross and upsells choices

This field (and the native up sell and cross sell fields), all have the same 'problem' of listing the products that i have added after the last woo update, in triplicate.

Products that i added to my shop before the update, only show once in the results.

Weird, i know

**Comment by claudiosanches** [comment] 2017-05-08 17:51
Sorry, but have you tested the other plugins that you have installed?
I mean, with ALL plugins?

**Comment by claudiosanches** [comment] 2017-05-08 18:35
Yes.

**Comment by Horsetags1** [comment] 2017-05-08 18:42
ALL plugins deactivated except woocommerce and triplicate listing still shows on linked products upsell and cross sells.

So same problem with just Woocommerce activated

**Comment by Horsetags1** [comment] 2017-05-08 18:45
add a test product to a store (with latest woo update) now and see if you get the same result

**Comment by mikejolley** [comment] 2017-05-08 18:49
Are you using translation plugins e.g. WPML..?

**Comment by Horsetags1** [comment] 2017-05-08 20:34
no, and the problem exists with all plugins deactivated (except woocommerce

**Comment by mikejolley** [comment] 2017-05-09 12:18
Look in your DB and see if there are actually multiple records? I'm not able to replicate it so not much I can do from my side.

**Comment by Horsetags1** [comment] 2017-05-09 12:20
ok, will do

------ Original Message ------

**Comment by Horsetags1** [comment] 2017-05-09 13:41
Hi Mike,

It looks as though there is three entries in the database for the later product additions.

[triplicate.txt](https://github.com/woocommerce/woocommerce/files/986687/triplicate.txt)

Not being technical, I'm not 100% sure why.

I have done a very crude copy and paste on one set and saved it in the text file
