### ISSUE TITLE
Tax Rates for UK don't seem to work.

### ISSUE THREAD

**Issue by Josh-Millard** [woocommerce/woocommerce#30147] opened 2021-06-22 13:28 UTC
**I would also like to mention that I have set this up on a complete free Install of Wordpress and Woocommerce and still have the same issue.**

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I am trying to setup Woocommerce Tax Rates at 20% VAT for all postcodes within the UK except for Jersey. This is a postcode in the format of JE*. When I enter a Jersey postcode(JE38DB) - The user is getting 20% and shouldn't be.

**Expected behavior**
When a user enters a valid Jersey Postcode(ie - JE38DB) during checkout, the postcode should show NO TAX.

**Actual behavior**
When the postcode is entered, ?wc-ajax=update_order_review is triggered and returns VAT on a postcode that should actually be 0% Tax.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to checkout page
2. Change Country to 'United Kingdom'
3. Change Postcode to 'JE38DB' -> Should show NO VAT
4. Change Postcode to 'WV13NH' -> Should show 20% VAT

**Screenshots**

<img width="521" alt="Screenshot 2021-06-22 at 14 20 49" src="https://user-images.githubusercontent.com/84436732/122931741-14429e80-d365-11eb-8bf5-bf603f1e4773.png">

<img width="1249" alt="Screenshot 2021-06-22 at 14 10 20" src="https://user-images.githubusercontent.com/84436732/122930245-b792b400-d363-11eb-9281-65ecb9577d54.png">

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888
Site address (URL): http://localhost:8888
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.3.1 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.3.1
PHP Post Max Size: 120 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.25
Max Upload Size: 120 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Total Database Size: 4.23MB
Database Data Size: 2.86MB
Database Index Size: 1.37MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 6
acf-field-group: 1
attachment: 1
page: 6
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Advanced Custom Fields: ACF Code Field: by Peter Tasker – 1.8
Advanced Custom Fields PRO: by Elliot Condon – 5.7.8
AIM Theme Overrider: by Josh Millard – 1.0.0
Classic Editor: by WordPress Contributors – 1.6
WooCommerce: by Automattic – 5.4.1

### Inactive Plugins (1) ###

Aliss API: by Josh Millard – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #18 - /shop/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2021-06-22 12:38:13 +0000
Newest: 2021-06-22 12:38:13 +0000

### Status report information ###

Generated at: 2021-06-22 13:24:11 +00:00
`
</details>

**Comment by rodelgc** [comment] 2021-06-24 08:02
Hi @Josh-Millard,

As I can see from the screenshot of your tax rates, you had set different priority numbers for the two tax rates (priority 10 for `JE*` and priority 20 for everything else). 

In order for WooCommerce to select only one, you will have to assign the same priority number to both of them. For example, try setting both of them to priority 10 as I did here:
<img width="1739" alt="Screen Shot 2021-06-24 at 3 33 27 PM" src="https://user-images.githubusercontent.com/4509348/123223999-f6f80680-d503-11eb-903d-a08e933fec2f.png">

This will enable WooCommerce to select the correct tax rate on the checkout page, as you can see from the images below:
<img width="778" alt="Screen Shot 2021-06-24 at 3 36 25 PM" src="https://user-images.githubusercontent.com/4509348/123224542-7c7bb680-d504-11eb-9408-1cb1a4c2bd07.png">
<img width="778" alt="Screen Shot 2021-06-24 at 3 40 08 PM" src="https://user-images.githubusercontent.com/4509348/123224577-856c8800-d504-11eb-951a-0f73974c4f83.png">

You may refer to the [Tax Rate Examples](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#tax-rate-examples) section of the WooCommerce documentation if you need more information.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodelgc** 2021-06-24 08:02 UTC
