### ISSUE TITLE
[GlobalStep ] "Database error" is triggered upon activating "WooCommerce Product Bundle" plugin.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28471] opened 2020-12-02 17:08 UTC
## Bug Description:
"Database error" is triggered upon activating "WooCommerce Product Bundle" plugin.

## Environment:
Windows 10, macOS Catalina: v10.15.7 (19H15)
Browser: Chrome(Version 86.0.4240.75 (64-bit))
                 Firefox(Version 82.0)(64-bit)
                 Safari(Version 14.0)(15610.1.28.1.9, 15610)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Go to Plugins->Add New.
1. Install and Activate "WooCommerce Product Bundle" Plugin.
1. Observe that "Database error" is triggered on query monitor.

## Actual Result:
"Database error" is triggered upon activating "WooCommerce Product Bundle" plugin.

## Expected Result:
WooCommerce Product Bundle" plugin should get activate without any errors.

## Artifacts:
[#28471.zip](https://github.com/woocommerce/woocommerce/files/5630865/28471.zip)
![#28471](https://user-images.githubusercontent.com/41110392/100906626-5f8f7f80-34ef-11eb-87c3-3d183b4367d7.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://ephemeral-tammullen-20201201.atomicsites.blog
Site address (URL): https://ephemeral-tammullen-20201201.atomicsites.blog
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.2
Log Directory Writable: ✔
WP Version: 5.6-RC1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.0
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 4.00MB
Database Data Size: 2.37MB
Database Index Size: 1.63MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.19MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
global_product_addon: 2
nav_menu_item: 5
page: 8
post: 3
product: 19
product_variation: 7
shop_coupon: 1
shop_order: 14
shop_subscription: 6
wc_membership_plan: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Query Monitor: by John Blackbourn – 3.6.5
Akismet Anti-Spam: by Automattic – 4.1.7
Code Snippets: by Code Snippets Pro – 2.14.0
Creative Mail by Constant Contact: by Constant Contact – 1.2.2 – Installed version not tested with active version of WooCommerce 4.0
Facebook for WooCommerce: by Facebook – 2.2.0
Jetpack by WordPress.com: by Automattic – 9.2
Google Ads & Marketing by Kliken: by Kliken – 1.0.6
Mailchimp for WooCommerce: by Mailchimp – 2.4.7
WooCommerce Bookings: by WooCommerce – 1.15.31
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5
WooCommerce Memberships: by SkyVerge – 1.19.2
WooCommerce Payments: by Automattic – 1.7.0
WooCommerce Product Add-ons: by WooCommerce – 3.2.0
WooCommerce Product Bundles: by SomewhereWarm – 6.6.0
WooCommerce Shipping & Tax: by Automattic – 1.25.3
WooCommerce Subscriptions: by WooCommerce – 3.0.11
WooCommerce: by Automattic – 4.8.0-rc.1

### Inactive Plugins (8) ###

AMP: by AMP Project Contributors – 2.0.7
CoBlocks: by GoDaddy – 2.5.3
Crowdsignal Forms: by Automattic – 1.3.3
Gutenberg: by Gutenberg Team – 9.4.1
Jetpack Beta Tester: by Automattic – 2.4.2
Layout Grid: by Automattic – 1.3
Page Optimize: by Automattic – 0.5.1
WordPress.com Editing Toolkit: by Automattic – 2.8.9

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.0.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: ❌ No published plans

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://ephemeral-tammullen-20201201.atomicsites.blog
Subscription Statuses: auto-draft: 5
wc-pending: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Direct bank transfer: products
Check payments: products
Cash on delivery: products
PayPal Standard: subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_delayed_change
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ✔ Yes
PayPal Checkout: products
refunds
subscriptions
subscription_cancellation
subscription_reactivation
subscription_suspension
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders


### Product Bundles ###

Database Version: 6.6.0
Loopback Test: ✔
Template Overrides: –

### Action Scheduler ###

Complete: 29
Oldest: 2020-12-01 20:11:57 +0000
Newest: 2020-12-02 16:02:59 +0000

`
```
</details>

**Comment by tammullen** [comment] 2020-12-02 21:56
I can reproduce this. I also tried in 4.5.2 and could reproduce it there so this does not appear related to 4.8 RC 1

![Screenshot 2020-12-02 at 21 52 08](https://user-images.githubusercontent.com/24649833/100936250-218f5d00-34e9-11eb-9ebe-2ec861755b84.png)

**Comment by juliaamosova** [comment] 2020-12-04 18:04
Hi @gglobalstep,

Thanks for reporting the issue! And thank you for confirming it @tammullen. We don't have access to the Product Bundles repository so we can't easily move the issue there. I am pinging @franticpsyx here who is the developer of Product Bundles to take a look. But I am also closing this issue since it is not related to WooCommerce Core.

**Closed by juliaamosova** 2020-12-04 18:04 UTC
