### ISSUE TITLE
Quantity bug stock

### ISSUE THREAD

**Issue by LDC22** [woocommerce/woocommerce#22978] opened 2019-03-08 15:57 UTC
Hi, i have problem with quantity in stock:

I set 200 pieces ... but after the first order I get out of stock and -1

**Comment by mikejolley** [comment] 2019-03-08 15:59
This is a duplicate of https://github.com/woocommerce/woocommerce/issues/22944#issuecomment-470972615 and lacks details.

Please go comment on that other issue, provding more details on your store setup, and steps to reproduce.

**Closed by mikejolley** 2019-03-08 15:59 UTC
