### ISSUE TITLE
Compatibility message misleading/incorrect

### ISSUE THREAD

**Issue by stephhjacq** [woocommerce/woocommerce#25073] opened 2019-11-19 17:09 UTC
**Describe the bug**
Extension compatibility message discourages users from updating, because it reads as though the new version has not been tested. 

**To Reproduce**
1. Go to status report on a site with extensions that require updates
2. See message, e.g. `– 2.4.12 is available – Not tested with the active version of WooCommerce`

**Screenshots**
![https://cld.wthms.co/rfvTTZ](https://cld.wthms.co/rfvTTZ+)
Full Image: https://cld.wthms.co/rfvTTZ

**Expected behavior**
The message clearly and correctly states compatibility with WooCommerce.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2019-11-20 09:47
Thank you for raising this issue @stephhjacq. However, these messages are out of control of the WooCommerce core. It is up to each plugin / extension developer to update this message before the WooCommerce release. On our end, we will think about how we can encourage extension and plugin developers to make sure the message about compatibility stays up to date (so as the extension itself).

**Comment by juliaamosova** [comment] 2019-11-20 10:44
On the 2nd look at this issue, I see that the problem is not with the fact that the notice appears but with the fact that it appears even on plugins that have indeed been tested up to the current version of WooCommerce. 

A good example is `WooCommerce Min/Max Quantities` extension. If version number `2.4.11` is installed on the site, it shows the following message: `2.4.12 is available – Not tested with the active version of WooCommerce`:

![2 4 11](https://user-images.githubusercontent.com/19143190/69232025-21dce480-0b82-11ea-921e-2408048950f0.jpg)

From the message, it sounds like even if the plugin is upgrade to `2.4.12` - it is still not tested with the active version of WooCommerce. 

But in fact if the plugin is upgraded to `2.4.12`, the message goes away:

![2 4 12](https://user-images.githubusercontent.com/19143190/69232165-69637080-0b82-11ea-8f50-c31270f6301e.jpg)

The issue here is that `Not tested with the active version of WooCommerce` message is applied to the currently installed version of `WooCommerce Min/Max Quantities` extension which is `2.4.11`. 

It should instead be clear that if the plugin is updated to `2.4.12`, it will be at the point where it is tested with the active version of WooCommerce.

**Comment by thomas-zg** [comment] 2019-12-04 05:55
@juliaamosova I do see the <code>Not tested ...</code> message for a number of plugins, which are up to date:
<img width="994" alt="grafik" src="https://user-images.githubusercontent.com/25877146/70115814-26fd6180-1661-11ea-8ecc-c15650fd6b3e.png">

I did a test in my staging environment, I removed all plugins except WooCommerce and WooCommerce Admin. Then I copied plugin by plugin back to the plugin folder until the message reapears. While adding the plugins, the refreshed status report only shows the message for those plugin without the correct version number in the tag <code>WC tested up to</code>. After adding a number of plugins, the <code>Not tested ...</code> message reapears for compatible plugins like on the screenshot above. I'll repeat the test tomorrow.

**Comment by thomas-zg** [comment] 2019-12-04 09:37
Starting the test by removing all plugins except those two:
<img width="689" alt="grafik" src="https://user-images.githubusercontent.com/25877146/70118187-b443b480-1667-11ea-8d05-535f1f9eac01.png">

Copy back two plugins, the message for the <code>WooCommerce Delivery Slots by Iconic</code> is correct do to the <code>WC tested up to: 3.6.4</code> tag.
<img width="931" alt="grafik" src="https://user-images.githubusercontent.com/25877146/70118286-e48b5300-1667-11ea-9f95-cfa1076ed1cb.png">

Adding a number of plugins, everything is fine till now:
<img width="989" alt="grafik" src="https://user-images.githubusercontent.com/25877146/70118582-a5113680-1668-11ea-861e-777ca0e56762.png">

I figured out, that one plugin causes the issue. I'll try to reproduce the cause, after a first look, the header information is well formatted and availlable.

**Comment by DanReyLop** [comment] 2019-12-12 19:16
> I figured out, that one plugin causes the issue.

Which one? In your last screenshot there's 2 error messages, one for "WooCommerce Delivery Slots" (which is correct) and another for "Product Sales Report" (which may be correct too). What plugi did you enable so every WooCommerce-related plugin suddenly shows the error message?

I'm thinking that there's a plugin out there that hooks into the `extra_plugin_headers` filter but rewrites the array instead of adding to it. Depending on the execution order, that could be very well causing this issue.

**Comment by thomas-zg** [comment] 2019-12-12 21:30
@DanReyLop I'll send you a PM with the plugin attached.

**Comment by DanReyLop** [comment] 2019-12-14 18:29
@thomas-zg Thanks! I figured out what's wrong. It isn't the same problem that's being discussed here though (confusing messages). I'll create a PR to explore a fix and have more context, I'll tag you in it.

**Comment by rodrigoprimo** [comment] 2020-03-10 17:06
@stephhjacq and @juliaamosova, what if we first display the message saying that the current version of the extension is not tested with the active version of WooCommerce and then, if there is an update available, display a phrase in parenthesis asking the user to update. Something like:

`Not tested with the active version of WooCommerce (a newer version of this extension is available, please consider updating)`

What do you think? Happy to hear suggestions of better ways to communicate this to the users.

**Comment by stephhjacq** [comment] 2020-03-10 20:33
Thanks @rodrigoprimo! 
How about this:
`This version not tested with the active version of WooCommerce (update is available)`

**Comment by juliaamosova** [comment] 2020-03-10 21:20
@rodrigoprimo can we actually specify version numbers in these messages? For example, `This version not tested with the active 3.9.3 version of WooCommerce (update is available)`

**Comment by rodrigoprimo** [comment] 2020-03-12 14:47
@juliaamosova yes, it is possible to include the WooCommerce version, but to be honest I don't see much value in doing that. Why do you think including the WooCommerce version will help users?

I do think including the latest extension version number could help. I'm happy to include it if any of you have any suggestions on how to phrase the message including the extension version number.

**Comment by rodrigoprimo** [comment] 2020-03-12 15:12
I created PR #25904 to address this issue. For now, it is marked as in progress. The only thing remaining is a decision on the phrasing of the message.

**Comment by stephhjacq** [comment] 2020-03-12 16:35
Thanks for this @rodrigoprimo 
After discussing this with @jessepearson we've updated the message to emphasize that it's the currently installed version which is not tested:

`Installed version not tested with the active version of WooCommerce (update is available)`

or, if we can fit/automate the version number in there:

`Installed version not tested with active version of WooCommerce 4.0.0 (update is available)`

**Comment by rodrigoprimo** [comment] 2020-03-12 17:00
Thanks, @stephhjacq, and @jessepearson. I like your suggestion, especially the first version. As I mentioned above I don't see what is the value of adding the WooCommerce core version number but I could be missing something.

**Comment by stephhjacq** [comment] 2020-03-12 17:10
Thanks @rodrigoprimo 

I've just seen this other notice on my site as well - would this be covered by the same PR?

![https://d.pr/i/Yc2STI](https://d.pr/i/Yc2STI+)
Full Image: https://d.pr/i/Yc2STI

**Comment by rodrigoprimo** [comment] 2020-03-12 17:22
> I've just seen this other notice on my site as well - would this be covered by the same PR?

No, this notice is generated in a different part of the code. Happy to hear your thoughts on improvements to it as well.

**Comment by juliaamosova** [comment] 2020-03-12 18:51
@rodrigoprimo thanks!

>@juliaamosova yes, it is possible to include the WooCommerce version, but to be honest I don't see much value in doing that. Why do you think including the WooCommerce version will help users?

>I do think including the latest extension version number could help. I'm happy to include it if any of you have any suggestions on how to phrase the message including the extension version number.

I like the idea of including the version number of the installed plugin as well as it will add more clarity to what version is being used. 

Regarding adding version number for active version of WooCommerce, I think it also adds clarity - meaning, by looking at the notice, it is immediately clear what version of the plugin is being used and what version of WooCommerce is being used. But maybe I am overthinking it and we can drop the version number of WooCommerce from the message. 

I like @stephhjacq's version as well. Could be:

Option 1:

Installed version of the extension is not tested with active version of WooCommerce 4.0.0 (update is available)

Option 2:

Installed version XX of the extension is not tested with active version of WooCommerce XX (update is available)

**Comment by yukikatayama** [comment] 2020-03-25 19:31
Adding another [instance](https://wordpress.org/support/topic/woocommerce-paypal-checkout-gateway-not-compatible-with-woocommerce-4-0/) where there's confusion and worry about updating WC and PayPal Checkout due to similar [message](https://github.com/woocommerce/woocommerce/issues/25073#issuecomment-598306064) from @stephhjacq's last image.

**Comment by claudiosanches** [comment] 2020-04-02 14:48
@juliaamosova we already display the current extension version, so I tried a little different version of option 2:

![Screenshot from 2020-04-02 11-43-07](https://user-images.githubusercontent.com/1264099/78262579-25d92580-74d7-11ea-95e0-26b9bbc90cf2.png)

Still not sure about the `(update is available)` sounds like update available for WooCommerce now.

Maybe we could change to:

> WooCommerce Services by Automattic – 1.22.4 (update to version 1.22.5 is available) – Installed version of the extension is not tested with active version of WooCommerce 4.1.0 

Thoughts?

**Comment by stephhjacq** [comment] 2020-04-02 15:36
That is clearer, thanks @claudiosanches 
It might be too long to fit on the line, how about this:

>WooCommerce Services by Automattic – 1.22.4 (update is available) – Installed version not tested with active version of WooCommerce 4.1.0

**Comment by juliaamosova** [comment] 2020-04-02 15:48
@claudiosanches thanks for continuing to refine the message! I think it gets more clear. @stephhjacq how about combining your latest and Claudio's latest to:

>WooCommerce Services by Automattic – 1.22.4 (update to version 1.22.5 is available) – Installed version not tested with active version of WooCommerce 4.1.0

I think it is good to include the new version of the extension that is available so that it is also clear how far behind on the update the user is and for overall clarity. What do you both think?

**Comment by claudiosanches** [comment] 2020-04-02 16:21
One more screenshot before I send the commit:

![Screenshot from 2020-04-02 13-20-10](https://user-images.githubusercontent.com/1264099/78273068-b5d19c00-74e4-11ea-87d1-47ee1c2748f8.png)

Looks good now?

**Comment by juliaamosova** [comment] 2020-04-02 16:22
It looks good to me, thanks @claudiosanches! What do you think @stephhjacq?

**Comment by stephhjacq** [comment] 2020-04-02 16:44
This is great, thank you both @juliaamosova and @claudiosanches!

**Closed** 2020-04-06 17:48 UTC
Labels: bug, component: system status report, priority: high
