### ISSUE TITLE
4.3.0-rc.2 ChunkLoadError: Loading chunk 42 failed.

### ISSUE THREAD

**Issue by ChromeOrange** [woocommerce/woocommerce#26954] opened 2020-07-04 13:59 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I installed WC 4.3 RC2 using the Beta Tester plugin and now I get the errors shown below. These errors persist even when reverting back to 4.2.2

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (42.11cc196c5f0cb3a17439.js, line 0)
[Error] ChunkLoadError: Loading chunk 42 failed.
(error: https://woocommerce-sagepay.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/42.11cc196c5f0cb3a17439.js)
	readLazyComponentType (react-dom.js:12276)
	mountLazyComponent (react-dom.js:17337)
	callCallback (react-dom.js:341)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.js:391)
	invokeGuardedCallback (react-dom.js:448)
	beginWork$$1 (react-dom.js:23355)
	performUnitOfWork (react-dom.js:22349)
	workLoopSync (react-dom.js:22323)
	renderRoot (react-dom.js:22016)
	renderRoot
	runRootCallback (react-dom.js:21692)
	runRootCallback
	(anonymous function) (react-dom.js:11491)
	unstable_runWithPriority (react.js:2820)
	flushSyncCallbackQueueImpl (react-dom.js:11487)
	flushTask (react.js:2653)
	flushWork (react.js:2784)
	performWorkUntilDeadline (react.js:2408)
[Error] The above error occurred in one of your React components:
    in Unknown (created by PrimaryLayout)
    in Suspense (created by PrimaryLayout)
    in div (created by PrimaryLayout)
    in PrimaryLayout
    in div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
	logCapturedError (react-dom.js:19952)
	logError (react-dom.js:19988)
	(anonymous function) (react-dom.js:21067)
	callCallback (react-dom.js:13067)
	commitUpdateEffects (react-dom.js:13106)
	commitUpdateQueue (react-dom.js:13097)
	commitLifeCycles (react-dom.js:20236)
	commitLayoutEffects (react-dom.js:22951)
	callCallback (react-dom.js:341)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.js:391)
	invokeGuardedCallback (react-dom.js:448)
	commitRootImpl (react-dom.js:22723)
	commitRootImpl
	unstable_runWithPriority (react.js:2820)
	commitRoot (react-dom.js:22552)
	commitRoot
	runRootCallback (react-dom.js:21692)
	runRootCallback
	(anonymous function) (react-dom.js:11491)
	unstable_runWithPriority (react.js:2820)
	flushSyncCallbackQueueImpl (react-dom.js:11487)
	flushTask (react.js:2653)
	flushWork (react.js:2784)
	performWorkUntilDeadline (react.js:2408)

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Edit an order
2. Open the console

**Screenshots**

![](https://p193.p3.n0.cdn.getcloudapp.com/items/7Kumzbkl/Image%202020-07-04%20at%202.46.51%20pm.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woocommerce-sagepay.com
Site address (URL): https://woocommerce-sagepay.com
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0-rc.2
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.3.19-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.30-0ubuntu0.18.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Total Database Size: 310.66MB
Database Data Size: 172.69MB
Database Index Size: 137.97MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 29.56MB + Index: 25.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fakenames: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.38MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 12.52MB + Index: 9.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 1.03MB + Engine InnoDB
wp_postmeta: Data: 104.63MB + Index: 91.09MB + Engine InnoDB
wp_posts: Data: 9.52MB + Index: 7.97MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.28MB + Index: 0.31MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcsc_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_sagepay_transaction: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 4.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

afreg_fields: 1
attachment: 27
def_reg_fields: 10
nav_menu_item: 6
order_shipment: 2
page: 15
pdfi_templates: 2
post: 2
product: 28
product_variation: 8
revision: 55
shop_coupon: 1
shop_order: 22613
shop_order_refund: 53
shop_subscription: 60

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.3.0-rc.2

### Inactive Plugins (0) ###

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /basket/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #19 - /terms/

### Theme ###

Name: Storefront
Version: 2.5.3 (update to version 2.5.7 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 562
Oldest: 2020-06-03 14:56:23 +0100
Newest: 2020-07-04 14:46:29 +0100

Pending: 3
Oldest: 2020-07-04 15:20:45 +0100
Newest: 2020-07-05 11:30:32 +0100

`
```
</details>

**Comment by peterfabian** [comment] 2020-07-06 14:30
Thanks for opening the issue. It's a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/4738, so will be fixed in woocommerce admin repo.

**Closed by peterfabian** 2020-07-06 14:30 UTC
