### ISSUE TITLE
Can't edit product description anymore.

### ISSUE THREAD

**Issue by RosanneBoxum** [woocommerce/woocommerce#28608] opened 2020-12-17 09:50 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If i click on 'edit product', I can no longer edit the name, description, stock etc. The fields are blanc, but I also cannot type in them anymore. The place where i should be able to edit the stock, and some extra info are gone.

<img width="1271" alt="Schermafbeelding 2020-12-17 om 10 39 31" src="https://user-images.githubusercontent.com/76156223/102470477-50164780-4054-11eb-9f7c-59ebc01b7f3b.png">
<img width="1274" alt="Schermafbeelding 2020-12-17 om 10 35 49" src="https://user-images.githubusercontent.com/76156223/102470501-59071900-4054-11eb-8c0a-9a830555486d.png">

**Expected behavior**
Seeing my text and everything I already added to the product (it's not a new product, but exist for already 2 years). I want to edit the stock. But because the product consists of 2 variables, i can't edit the stock with 'quick adjustments'.
<img width="1136" alt="Schermafbeelding 2020-12-17 om 10 41 28" src="https://user-images.githubusercontent.com/76156223/102470650-8d7ad500-4054-11eb-8ff1-52f05a824205.png">

**Actual behavior**
All places where I should be able to change or add information are blanc or gone.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'shop items'
2. Click on 'any item to edit'
3. Scroll down to 'the whole page'

**Screenshots**
<img width="1274" alt="Schermafbeelding 2020-12-17 om 10 35 49" src="https://user-images.githubusercontent.com/76156223/102470879-ca46cc00-4054-11eb-9e9b-2e6ab92ee9dd.png">

<img width="1271" alt="Schermafbeelding 2020-12-17 om 10 39 31" src="https://user-images.githubusercontent.com/76156223/102470896-d16dda00-4054-11eb-8d8a-bb4f6d957ff0.png">

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.studiorosanne.nl
Site address (URL): https://www.studiorosanne.nl
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.34
PHP Post Max Size: 64 MB
PHP Time Limit: 240
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 10.1.48-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Totale databasegrootte: 136.94MB
Database datagrootte: 103.88MB
Database index grootte: 33.06MB
wp_woocommerce_sessions: Data: 0.53MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.09MB + Index: 0.12MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.48MB + Index: 0.27MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 3.70MB + Index: 2.28MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 4.52MB + Index: 3.38MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 15.71MB + Index: 0.24MB + Engine MyISAM
wp_comments: Data: 16.22MB + Index: 3.98MB + Engine MyISAM
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_huge_itgallery_gallerys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_huge_itgallery_images: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_huge_itgallery_like_dislike: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_learndash_pro_quiz_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_form: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_learndash_pro_quiz_lock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_prerequisite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_question: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_learndash_pro_quiz_statistic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_statistic_ref: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_learndash_pro_quiz_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_toplist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_user_activity: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_learndash_user_activity_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailerlite_checkouts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.11MB + Index: 0.31MB + Engine MyISAM
wp_pay_options: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pay_option_subs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pay_transactions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pms_member_subscriptionmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pms_member_subscriptions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pms_paymentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pms_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta: Data: 16.75MB + Index: 7.54MB + Engine MyISAM
wp_posts: Data: 24.54MB + Index: 3.15MB + Engine MyISAM
wp_queue: Data: 0.67MB + Index: 0.00MB + Engine MyISAM
wp_redirection_404: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 4.52MB + Index: 0.66MB + Engine InnoDB
wp_termmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_relationships: Data: 0.27MB + Index: 0.57MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 4.41MB + Index: 2.80MB + Engine MyISAM
wp_users: Data: 0.31MB + Index: 0.31MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.27MB + Index: 0.22MB + Engine InnoDB
wp_wc_download_log: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.45MB + Index: 0.53MB + Engine InnoDB
wp_wc_order_stats: Data: 0.27MB + Index: 0.28MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.13MB + Index: 0.06MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.40MB + Index: 0.46MB + Engine MyISAM

### Post Type Counts ###

attachment: 458
br_labels: 7
custom_css: 1
elementor_library: 2
nav_menu_item: 16
oembed_cache: 36
page: 56
post: 57
postman_sent_mail: 250
product: 50
product_variation: 33
revision: 2407
robo_gallery_table: 2
shop_coupon: 46
shop_order: 2723
shop_order_refund: 49
slide: 3
vc4_templates: 3
vc_settings_preset: 6
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

WooCommerce Advanced Product Labels: door BeRocket – 1.2
Akismet Anti-Spam: door Automattic – 4.1.7
Cache External Scripts: door Diego Voors – 0.4
Contact Form 7: door Takayuki Miyoshi – 5.3.1
Cookie Notice: door dFactory – 1.3.2
Enable jQuery Migrate Helper: door Het WordPress team – 1.3.0
WPBakery Page Builder: door Michael M - WPBakery.com – 6.5.0
LearnDash ProPanel: door LearnDash – 2.1.4
Mailchimp voor WooCommerce: door Mailchimp – 2.5.0
Members: door MemberPress – 3.1.3
Mollie-betalingen voor WooCommerce: door Mollie – 6.0
My Simple Space: door Michael Mann – 1.2.8
Official Facebook Pixel: door Facebook – 2.2.2
WooCommerce Order Export: door JEM Plugins – 3.0.5
Post SMTP: door Yehuda Hassine – 2.0.16
Redirection: door John Godley – 4.9.2
LearnDash LMS: door LearnDash – 3.3.0.1
W3 Total Cache: door BoldGrid – 2.0.0
WooCommerce - MailerLite: door MailerLite – 1.4.10
WooCommerce Google Analytics Integration: door WooCommerce – 1.4.25
MoneyBird API integratie voor WooCommerce: door Marco Cox
<a href="https://extensiontree.com/nl/">ExtensionTree.com</a> – 3.20.0

WooCommerce MyParcel: door MyParcel – 4.1.5 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.0
WooCommerce: door Automattic – 4.8.0
Countdown Widget: door Metin Saylan – 3.1.7
Yoast SEO: door Team Yoast – 15.5
Perfect Images + Retina: door Jordy Meow – 6.1.0

### Inactive Plugins (2) ###

Better Analytics: door Digital Point – 1.2.5
Enhanced E-commerce for Woocommerce store: door Tatvic – 2.3.6.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Winkelbasis: #29 - /shop/
Winkelmand: #30 - /cart/
Afrekenen: #31 - /checkout/
Mijn account: #32 - /my-account/
Algemene voorwaarden: #594 - /voorwaarden/

### Theme ###

Name: Mystile
Version: 1.3.19
Author URL: http://www.woothemes.com
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Afgerond: 612
Oldest: 2020-11-16 13:37:55 +0100
Newest: 2020-12-17 10:05:24 +0100

Mislukt: 1
Oldest: 2020-01-22 21:57:13 +0100
Newest: 2020-01-22 21:57:13 +0100

In afwachting: 1
Oldest: 2020-12-22 10:46:39 +0100
Newest: 2020-12-22 10:46:39 +0100

`
<img width="1274" alt="Schermafbeelding 2020-12-17 om 10 35 49" src="https://user-images.githubusercontent.com/76156223/102470048-c9fa0100-4053-11eb-9b50-06e6df1f99a9.png">

```
</details>

**Comment by tammullen** [comment] 2020-12-18 14:10
Hi @RosanneBoxum 
Thank you for raising the issue. However, I can’t reproduce it on my end.
​
![Screenshot 2020-12-18 at 14 09 09](https://user-images.githubusercontent.com/24649833/102623625-b70e2c00-413a-11eb-8267-d750ed43ca82.png)

​
I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-12-29 21:11
Hi @RosanneBoxum,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-12-29 21:11 UTC
Labels: category: can't reproduce, needs feedback
