### ISSUE TITLE
Non-dismissible Notice for Optional Feature (Connect your store to WooCommerce.com)

### ISSUE THREAD

**Issue by benjibee** [woocommerce/woocommerce#24996] opened 2019-11-07 16:37 UTC
### Description

WooCommerce displays a non-dismissible notice for for an optional feature of the plugin, namely connecting the store to _WooCommerce.com_. This notice is displayed on nearly all pages of the admin interface and is only dismissible by connecting your shop to the WooCommerce website or the following filter:

```add_filter('woocommerce_helper_suppress_admin_notices', '__return_true');```

This is quite bad practise as many users may simply not wish to connect their store to your website, for many good reasons.

### Screenshots / expected behaviour

This is the current dialog shown to users:

![image](https://user-images.githubusercontent.com/620119/68406807-c0307980-0182-11ea-870a-a6e6f9373149.png)

And this is how it should appear:

![image](https://user-images.githubusercontent.com/620119/68407419-d428ab00-0183-11ea-9bb6-7e0cdf63fdaa.png)

This thinking is well in line with [this issue and discussion](https://github.com/woocommerce/woocommerce/issues/23198) and I wonder who considers these kind of intrusive and obnoxious dialogs the be beneficial to the user, honestly.

**Comment by claudiosanches** [comment] 2019-11-11 14:30
Duplicated of https://github.com/woocommerce/woocommerce/issues/18452

**Comment by juliaamosova** [comment] 2019-11-11 15:56
Thank you for opening the issue @benjibee. As mentioned above, this issue is a duplicate of https://github.com/woocommerce/woocommerce/issues/18452 - please see the discussion we had related to it there. The arguments are still valid on our end today, therefore, we won't be working on fixing it at this time.

**Closed by juliaamosova** 2019-11-11 15:56 UTC

**Comment by benjibee** [comment] 2019-11-11 16:52
Hi @juliaamosova thanks for the info. I've read the full thread and the referenced PR, but the issue isn't resolved. On the contrary quite a few users seem to be upset by members and contributors insisting it's already been addressed, perhaps it'd be worth some of this team re-reading the thread. 

Also including @mikejolley and @bekarice here – please consider either re-opening the referenced issue, or my issue here.

Thanks

**Comment by bekarice** [comment] 2019-11-11 19:07
@benjibee I'm not part of the WooCommerce core team, but do work on over 50 WooCommerce.com extensions for a third party provider. I'm overwhelmingly in favor of the current behavior, and support the Woo core team's decision not to change it.

1. This notice **is only shown when you have a premium WooCommerce.com extension installed**. It is not shown if you only use WooCommerce. You must have downloaded a plugin from WooCommerce.com, installed it, and activated it to see this notice in the first place.
1. If you have done that, **you will not be notified of plugin updates without a connection**. By default, WordPress sites ping wordpress.org to find out if there are plugin updates. None of these WooCommerce.com plugins are hosted on wordpress.org, so they need somewhere else to ping for updates instead -- they ping WooCommerce.com to see if there are updates. _They must connect to WooCommerce to do so_. A site will never know if plugin updates are available **without a WooCommerce.com connection**, because WooCommerce.com is the only source of truth for the latest plugin version. This means an eCommerce site, for which security is paramount, would never know of crucial fixes or security updates without this.
1. Even when the notice is shown, it's only shown on **highly relevant pages**. Users see this on WooCommerce-specific pages, and the plugins page, never throughout the admin.
1. The notice is dismissible by taking the required action, which is to connect to WooCommerce.com to get updates.

We never had this problem prior to WC 3.1 because folks were required to install the Woo Helper plugin, which handled connecting to WooCommerce.com for updates -- there was a persistent notice to do so, just like there is now. The only difference is that WooCommerce core generates the notice instead as of version 3.1.

There were a couple minor versions of WooCommerce without this notice being shown, and WooCommerce.com plugin developers saw a huge increase in folks not updating their plugins and having support issues as a result of consistently out of date software. When you install a plugin you purchased, if you've never done this before, something needs to tell you _what to do next_ to get updates. Those issues have now been eradicated by re-adding this notice.

So, given this notice is highly targeted and only shows when you're installing a plugin you purchased from WooCommerce.com, is a required step to use that WooCommerce.com software effectively, and makes efforts to be as minimally intrusive as it can, I don't think it makes sense to remove given it **helps** the user it's targeted at.

**Comment by benjibee** [comment] 2019-11-12 12:07
@bekarice thanks for such a thorough explanation, I appreciate you taking the time to clarify your point-of-view, and I imagine it's shared in one form or another by many of the core team and your colleagues.

It looks like the dialog is a symptom of a bigger problem not addressed in this issue. I've been working with Wordpress since sometime in late 2004 and I've seen a lot of developer / user behaviors come and go. I can say with some certainty that circumventing the Wordpress updates system, or really replacing any core functionality as critical as updates with your own solutions, almost always ends up degrading the user experience (or being integrating into core 🤔) and should be avoided. Isn't this one of the first things we repeat over and over to new plugin developers when they're getting started?

Anyway it sounds like the team is quite invested in this path, and not very open to reconsidering it (judging from the tone in a few threads on here) so perhaps I'll take this issue somewhere it'll be more effective, but I'd like to ask for this approach to be reconsidered either way.

Even if I disagree with this particular policy I'm really thankful for all the hard work going into this plugin over the years. Thank you!
