### ISSUE TITLE
Subtotal, Shipping and Tax Total Calculating Incorrectly

### ISSUE THREAD

**Issue by sethta** [woocommerce/woocommerce#10076] opened 2016-01-14 20:47 UTC
I have orders failing because the amount being charged to the credit card isn't matching the order total.

On certain orders, it appears that there's a rounding error somewhere. In the example screenshot, The subtotal + shipping + tax comes out to a $.01 higher than the displayed total.

This only happens when shipping to certain areas. Sometimes it calculates properly, and if I disable tax on shipping (which I can't do) then the total adds correctly.

Tax is set to apply at the subtotal level, but it seems like there should be an option to apply it to the entire subtotal, including shipping, over calculating each individually and adding that up. 

![incorrect-calculation](https://cloud.githubusercontent.com/assets/220730/12336919/11e697d0-bad5-11e5-8406-4ff27b932252.png)

**Comment by mikejolley** [comment] 2016-01-14 20:58
Gateway? If the gateway sends taxes per line, but you round at subtotal level, the gateway likely won't do the same. You'd have to make the gateway send a single total instead to avoid and rounding their side.

**Comment by sethta** [comment] 2016-01-14 21:05
Would it be the gateway? I just tried disabling the Payment Gateway and quickly set it to Cash on Delivery, and the order total was still off by one, even as I went further in the checkout process.

If I disable round taxes at subtotal, the total is still off by one cent.

**Comment by sethta** [comment] 2016-01-14 21:06
The gateway is First Data Global Gateway (working on getting them to switch to a different gateway as their is in legacy mode).

**Comment by mikejolley** [comment] 2016-01-14 21:14
Can you turn off round at subtotal and in a clean session/different browser try the same products? The rounded value may be cached. 

If it's the same, post your tax settings and product prices so I can reproduce.

**Comment by sethta** [comment] 2016-01-14 21:30
Still the same issue.

Checkout screen:
<img width="915" alt="screen shot 2016-01-14 at 4 18 49 pm" src="https://cloud.githubusercontent.com/assets/220730/12337878/b52c10fa-bada-11e5-9355-cc70ef632e82.png">

Tax settings (round at subtotal unchecked):
<img width="1109" alt="screen shot 2016-01-14 at 4 20 45 pm" src="https://cloud.githubusercontent.com/assets/220730/12337920/f1cfec2a-bada-11e5-9fe0-b97f6305063a.png">

Product price: $15.60

Formula to reproduce: Buy 2 of the $15.60 products. Match with UPS autogenerated shipping of $17.51 shipping on Texas 8.25% tax.

15.60*2*1.0825+17.51*1.0825=52.728575, so 52.72 is displaying for total (rounding down) and 52.73 is what the total is actually (and should be) coming to.

Is there a hook available to make sure the total rounds correctly?

**Comment by mikejolley** [comment] 2016-01-14 21:32
Prices inc or excl tax?

**Comment by sethta** [comment] 2016-01-14 21:33
Excluding

**Comment by mikejolley** [comment] 2016-01-14 22:12
http://glui.me/?i=t3lv2n01rifg4r2/2016-01-14_at_22.12.png/

Where are you getting 15.6021.0825?

**Comment by mikejolley** [comment] 2016-01-14 22:13
This was a test with flat rate shipping hard coding the price. Try like that.

**Comment by sethta** [comment] 2016-01-14 22:33
Sorry, that was my math missing the asterisks. I've edited it: 15.60*2*1.0825+17.51*1.0825=52.728575.

I just tried flat rate, and it looks like the issue is with the UPS shipping extension. Flat Rate comes out perfectly. I'll have to send in a bug report.

Thanks for all of your help Mike!

**Comment by mikejolley** [comment] 2016-01-14 22:35
Might be missing a round in the rates, however, I *think* this may be resolved in 2.5 as well. Does look familiar. Thats out next week.

**Comment by DanielSantoro** [comment] 2016-01-26 21:58
@mikejolley It looks like this issue is continuing post-2.5, as seen here: https://woothemes.zendesk.com/agent/tickets/373450

Any ideas?

**Comment by sethta** [comment] 2016-01-27 14:30
That fixed it. Thank you!

**Comment by madeincosmos** [comment] 2016-11-30 22:14
501499-zd-woothemes

Please help me understand if the tax is counted correctly here:

I have a product that costs 29.98 with 5.99 shipping, at a tax rate of 20%. The option `round tax at a subtotal level` is disabled.

29.98 * 20% = 5.996 (rounds up to 6)
5.99 * 20% = 1.198 (rounds up to 1.20)

I would expect total tax to be 7.20 but instead it is showing me 7.19:

![Screenshot](http://cld.wthms.co/isRq+) 
(WP 4.6.1, WC 2.6.8 with Storefront, no other plugins active).

Am I missing something obvious here? How can I make the tax round up for each item individually?

**Comment by mikejolley** [comment] 2016-12-01 10:20
> How can I make the tax round up for each item individually?

We do per-line taxes, so the 29.98 in your example may be wrong (because thats rounded already for display).

Do the calculation on paper for each line, then add the unrounded values together to get your 7.19 total. That should be valid.

We wrote this wiki entry on how taxes work should you want to read more:

https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce Ping on slack if stuck; the OP's issue is unrelated.

**Closed by mikejolley** 2016-12-01 10:20 UTC

**Comment by bassamsaif** [comment] 2017-09-14 14:25
I having the same issue even though I added the same fix #86c404c .. Below the total is showing 0.01 less than what is displayed ..

![screen shot 2017-09-14 at 5 22 03 pm](https://user-images.githubusercontent.com/4449782/30434975-4aabec7e-9971-11e7-8dc2-3e46af0270ae.png)
