### ISSUE TITLE
Thumbnail image in woocommerce are not loading because of the url is not correct in home site.

### ISSUE THREAD

**Issue by Devendramprasad** [woocommerce/woocommerce#16756] opened 2017-09-08 07:58 UTC
I'm creating a ecommerce site and i add few product. when i run the frontent thumbnail image are not loading, but when i click on any of the product its all loading. Then i inspect on the thumbnail and found that the url of the image source is display wrong "8080/marketplace1/wp-content/uploads/2013/06/hoodie_6_front-300x300.jpg". Why is not display as "http://localhost:8080/marketplace1/wp-content/uploads/2013/06/hoodie_6_front-300x300.jpg".
Any lead would be great.

**Comment by mikejolley** [comment] 2017-09-08 09:47
We'd need an online example to see this happening. 

Have you checked to see if regular posts and post images are affected?

Are you using plugins to remove the base or use relative images?

Have you ruled out plugins etc like requested on the new issue field? What about the theme?

I'm closing this because it appears to be config related, on local host, and there has been no status report and steps to reproduce the issue. There isn't really anything we can do without seeing the issue first hand or being able to replicate.

Let us know if you narrow your issue down.

**Closed by mikejolley** 2017-09-08 09:47 UTC
