### ISSUE TITLE
Clear button, under customer, on "Edit Order" page not working

### ISSUE THREAD

**Issue by rockeypjb** [woocommerce/woocommerce#25688] opened 2020-02-17 15:05 UTC
**Describe the bug**
Since updating to WC 3.9.1, the clear field button (X) under "Customer" on the "Edit Order/Add New Order" page is not working. This appears to be a CSS issue. If I isolate `<span class="select2-selection__clear">x</span>` and increase the z-index I can then click and clear the field. 

**Screenshots**
<img width="1101" alt="Screen Shot 2020-02-17 at 9 58 23 AM" src="https://user-images.githubusercontent.com/27113199/74664762-530e8600-516c-11ea-8dbc-fa7442b33d8f.png">

**Expected behavior**
Clicking on the X should clear the field

**WordPress Environment**
WC Version: 3.9.1
WP Version: 5.3.2

**Comment by tammullen** [comment] 2020-02-20 23:38
Hi @rockeypjb 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end, clicking on the x doesn't clear the field you have to click slightly to the left of the x.

It looks like this was introduced in 3.8.1
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by juliaamosova** [comment] 2020-02-25 19:56
Hi @rockeypjb,

Thank you for reporting the issue. This issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25427. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Closed by juliaamosova** 2020-02-25 19:56 UTC
Labels: bug, priority: low
