### ISSUE TITLE
WooCommerce doesn't init as expected after an ajax modal checkout

### ISSUE THREAD

**Issue by psntr** [woocommerce/woocommerce#20489] opened 2018-06-11 16:01 UTC
I created a modal using ajax to show on a modal box my checkout. To display the checkout I'm using the following code in my functions.php
`define( 'WOOCOMMERCE_CHECKOUT', true );
  echo do_shortcode('[woocommerce_checkout]');`

Then with the regular "wp_ajax_url" I'm showing the content of the checkout page on my modal box. 
But the checkout scripts or default behaviour is not working, is like I'm launching the checkout page without the WooCommerce scripts, although all woocommerce scripts are in my page. 

Things I tried:
1) Recreate the scripts src tag, -> document.createElement('script') with the URL of all WooCommerce 
2) eval() the WooCommerce scripts tag
3) manually copy paste the scripts tag in the modal box

None of the above solution seems to work.

**Comment by mikejolley** [comment] 2018-06-12 10:14
Scripts are enqueued in the header of the website. Doing what you're doing won't render them - it's not the full page you're returning.

Also, some modal window plugins don't run scripts. Be warned.

We don't support customisations here so I'm closing this issue. It's not a bug in WooCommerce.

Thanks

**Closed by mikejolley** 2018-06-12 10:14 UTC
