### ISSUE TITLE
[4.0 beta1] error in Comments page: map_meta_cap was called incorrectly 

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#25709] opened 2020-02-19 16:35 UTC
This is testing on a Jurassic Ninja site. I was testing Reviews in WC Admin. When viewing Reviews via WC Admin icon, everything is fine:

![](https://d.pr/i/sckPw8+)
Link to screenshot: https://d.pr/i/sckPw8

![](https://d.pr/i/X5cAcQ+)
Link to screenshot: https://d.pr/i/X5cAcQ

But if I click directly to Comments tab, I get the following error:

![](https://d.pr/i/6ONY0A+)
Link to screenshot: https://d.pr/i/6ONY0A

```
Notice: map_meta_cap was called incorrectly. The post type scheduled-action is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see Debugging in WordPress for more information. (This message was added in version 4.4.0.) in /srv/users/user7a2d6246/apps/user7a2d6246/public/wp-includes/functions.php on line 4986woocommerce_deliver_webhook_async

Notice: Trying to get property 'labels' of non-object in /srv/users/user7a2d6246/apps/user7a2d6246/public/wp-admin/includes/class-wp-comments-list-table.php on line 926Notice: Trying to get property 'view_item' of non-object in /srv/users/user7a2d6246/apps/user7a2d6246/public/wp-admin/includes/class-wp-comments-list-table.php on line 926
```

Note: I'm not sure if this error was already there before I submitted a review or not

**Comment by tammullen** [comment] 2020-02-22 13:08
Hi @yukikatayama 

Thank you for testing and for submitting the issue. However, I can’t reproduce the issue. I checked the comments page directly and from the wc-admin reviews tab before and after adding reviews and didn't have any errors.
​
![Screenshot_2020-02-22_at_13_00_37](https://user-images.githubusercontent.com/24649833/75092855-02d06300-5574-11ea-8f82-b22d26891b4a.png)
​
Can you provide us with more details about the issue which may help us to evaluate it further. 
I notice in the screenshot the ActionScheduler comment that appeared before your review. Do you know what caused it to appear? Had you done ActionScheduler testing prior to this?​

**Comment by yukikatayama** [comment] 2020-02-25 15:18
Yes, I had done the steps outlined [here](https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions#action-scheduler-30) first before starting the WC Admin testing steps. I tried again on a fresh JN site, but now unable to reproduce...might have been a misstep somewhere I did the first time around   😅

**Comment by juliaamosova** [comment] 2020-02-25 15:30
Noting here that you likely had one of the plugins (any plugin really) active at first and then deactivated it @yukikatayama. It can bring these errors. 

We had 2 more similar issues logged:

https://github.com/woocommerce/woocommerce/issues/25127
https://github.com/woocommerce/woocommerce/issues/25744

The issue is on the WordPress core side of things. And there are a few tickets open related to it:

https://core.trac.wordpress.org/ticket/49437
https://core.trac.wordpress.org/ticket/36208

I am still testing on JN site to see if I can reproduce it though to be sure.

**Comment by juliaamosova** [comment] 2020-02-25 15:42
Noting here that I couldn't reproduce it on JN site still even after deactivating plugins (WooCommerce Admin, WooCommerce, Jetpack). Going to leave this issue open for now but looks like it is indeed WordPress core related.

**Comment by rodrigoprimo** [comment] 2020-02-27 19:55
cc @rrennick as this seems related to Action Scheduler.

**Comment by rrennick** [comment] 2020-02-28 00:09
@rodrigoprimo You would see the same from https://core.trac.wordpress.org/ticket/36208 on order notes, product reviews, and any other CPT if the CPT has comments and stops being registered. An example when WC is deactivated

```PHP Notice:  map_meta_cap was called <strong>incorrectly</strong>. The post type shop_order is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.4.0.) in /Users/ronrennick/Sites/ron/wp-includes/functions.php on line 4986```

**Comment by rodrigoprimo** [comment] 2020-02-28 10:25
Thanks for the clarification, @rrennick. @juliaamosova and @tammullen, IMO, we can close this issue as I don't think there is anything for us to do to prevent this PHP notice.

**Comment by juliaamosova** [comment] 2020-02-28 13:54
@rodrigoprimo I agree. Thanks for double-checking once again @rrennick. Closing.

**Closed by juliaamosova** 2020-02-28 13:54 UTC
Labels: can't reproduce
