### ISSUE TITLE
Shipping calculator update / page refresh error

### ISSUE THREAD

**Issue by lindenism** [woocommerce/woocommerce#22348] opened 2019-01-05 06:00 UTC
When I am logged in and I have saved in my account my billing address to an Australian address (1 Street Name, Bardon, QLD, 4065, Australia) and I am on the cart page, regarding the shipping calculator, when I click 'change address' and change my country to United States, and leave blank the other fields, I see the correct label  'Estimate for United States (US).'  Then I refresh the page, I see the shipping estimate as 'Estimate for QLD, United States (US).' This is wrong. See screenshot.

Is anyone else able to reproduce this error?
![capture](https://user-images.githubusercontent.com/46392231/50720945-dd2f9280-1102-11e9-9777-5df26a7e4471.PNG)

**Comment by rrennick** [comment] 2019-01-08 18:39
> Is anyone else able to reproduce this error?

In my install, the other fields are not blank. Changing the country does blank the state, but not the city or post code/zip field. Is your issue/concern the fact that updating the country does not require updating the state?

**Comment by mikejolley** [comment] 2019-01-15 16:13
Seems to be a dupe of https://github.com/woocommerce/woocommerce/issues/22241 - some fields show from calculator, some show from account.

**Closed by mikejolley** 2019-01-15 16:13 UTC
