### ISSUE TITLE
Woocommerce Reports not showing income more 3 days

### ISSUE THREAD

**Issue by Enemy7** [woocommerce/woocommerce#24408] opened 2019-08-14 21:48 UTC
Hello !
I moved the site from hosting to the VPS.
And I had a problem, the reports do not show the amount of sales.
[http://prntscr.com/osmdnp](http://prntscr.com/osmdnp)

Previously, everything worked well, but now the report shows the amount only if you select 2 sometimes 3 days.
[http://prntscr.com/osmqyu](http://prntscr.com/osmqyu)

7 days, month and year does not work.
A report on the sale of a product or category works well.

Can you help, what could be the problem?

```
### WordPress Environment ###

Home URL: http://lunchbox.com.ua
Site URL: http://lunchbox.com.ua
WC Version: 2.4.7
Log Directory Writable: ✔ /home/lunchbox/public_html/wp-content/uploads/wc-logs/
WP Version: 4.3.17
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
Language: ru_RU

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.40
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.5
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Удалить запись: ✔
Удалённое получение: ✔

### Database ###

WC Database Version: 2.4.7
:
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (37) ###

Custom Order Status for WooCommerce: от Algoritmika Ltd – 1.2.1
WooCommerce Multiple Free Gift: от Ankit Pokhrel – 1.1.5
Advanced Cron Manager: от BracketSpace – 2.3.6
Akismet: от Automattic – 3.1.6
All In One SEO Pack: от http://semperfiwebdesign.com – 2.2.7.5
HTML in Category Descriptions: от Arno Esterhuizen – 1.2.1.1
Arconix Shortcodes: от John Gardner – 2.0.3
Google XML Sitemaps: от Arne Brachhold – 4.0.8
Hide Title: от Brandon Kraft & Randall Runnels – 1.0.4
PixelYourSite: от PixelYourSite – 5.3.4
RusToLat: от Anton Skorobogatov – 0.3
eSputnik: от Saphali – 1.0
Saphali Нова почта PRO: от Saphali – 1.0.1
phone wc format: от Saphali – 1.0
Saphali Woocommerce Russian: от Saphali – 1.8.3
Search By SKU – for Woocommerce: от Matthew Lawson – 0.6.1
Simple Custom CSS: от John Regan
Danny Van Kooten – 3.2

Simple IP Ban: от Sandor Kovacs – 1.3.0
WooCommerce Simple LiqPay: от Alex Shandor – 1.7
Page Builder by SiteOrigin: от SiteOrigin – 2.4.21
SiteOrigin Бандл Виджетов: от SiteOrigin – 1.7.2
Speed Contact Bar: от Alexandra Mutter
Martin Stehle – 6.4.2

WooCommerce Product Feed: от WebAppick – 2.2.9
Twist – Woocommerce Product Gallery Slider Free: от Niloy Sarker – 1.1
Shindiri Woo Shop Slider Lite: от Shindiri Studio – 1.0.0
WooCommerce Colors: от WooThemes – 1.0.6
WooCommerce Google Ads Dynamic Remarketing: от Wolf+Bär Agency – 1.7.7
WooCommerce PDF Invoices & Packing Slips: от Ewout Fernhout – 1.5.28
WooCommerce Product Details Customiser: от jameskoster – 0.2.0
Woo Radio Buttons: от DesignLoud – 3.0.0
WooCommerce: от WooThemes – 2.4.7
WooDiscuz – WooCommerce Comments: от gVectors Team (A. Chakhoyan
G. Zakaryan
H. Martirosyan) – 2.0.11

WP Lightbox 2: от Syed Balkhi – 3.0.5
WP-Optimize: от David Anderson
Ruhani Rabin
Team Updraft – 2.1.0

WP Super Cache: от Automattic – 1.4.8
WP User Avatar: от flippercode – 2.0.6
YITH WooCommerce Badge Management: от YIThemes – 1.2.7

### Settings ###

Force SSL: ✔
Currency: UAH (грн.)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Ссылка магазина: #12 – /shop/
Корзина: #13 – /cart/
Оформление заказа: #14 – /checkout/
Мой аккаунт: #15 – /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)
yith_bundle (yith_bundle)

### Theme ###

Name: Ornea
Version: 1.0.3
Author URL: http://aristeides.com
Child Theme: ✕ – Если вы модифицируете WooCommerce или родительскую тему
которую вы не разрабатывали самостоятельно
мы рекомендуем использовать дочернюю тему. Смотри: Как создать дочернюю тему

WooCommerce Support: ✔

### Templates ###

Overrides: ornea/woocommerce/emails/admin-new-order.php
ornea/woocommerce/global/wrapper-end.php
ornea/woocommerce/global/wrapper-start.php
ornea/woocommerce/single-product/product-image.php
```

In the chrome console, I see just such an error, if I select statistics for 2 days there is no error. Maybe this will help:

```
Uncaught TypeError: Cannot read property ‘height’ of null
at t.value (E-v1.js:1)
at t.value (E-v1.js:1)
at B (E-v1.js:1)
at T (E-v1.js:1)
at x (E-v1.js:1)
at A (E-v1.js:1)
at _ (E-v1.js:1)
at I (E-v1.js:1)
at t.value (E-v1.js:1)
at E-v1.js:1
```
I found a similar problem, but there is no solution.
[https://github.com/woocommerce/woocommerce/issues/8854](https://github.com/woocommerce/woocommerce/issues/8854)
[https://github.com/woocommerce/woocommerce/issues/9375](https://github.com/woocommerce/woocommerce/issues/9375
)

**Comment by kloon** [comment] 2019-08-16 07:53
Hi @Enemy7, you seem to be running a very, very, very outdated version of WooCommerce. According to your system status report, you are running 2.4.7.

Since that version, we have had many releases with many fixes already. My suggestion for you would be to setup a staging environment and then try and get your site updated on there and if all goes well you can update your live site as well.

Please also make sufficient backups before performing any kind of update and be sure to also update all your extensions and theme to the latest versions to ensure they are compatible with the latest version of WooCommerce.

I am going to close this issue due to the outdated version of WooCommerce. Will gladly reopen if you can reproduce this with the latest version to validate that this is still a bug, but in my testing the reporting works as it should in the latest version.

**Closed by kloon** 2019-08-16 07:53 UTC
