### ISSUE TITLE
New order notification email sometimes displays a (ex. VAT) mention, sometimes not

### ISSUE THREAD

**Issue by delcorp** [woocommerce/woocommerce#28779] opened 2021-01-11 10:56 UTC
Hi, I'm using the latest Woocommerce plugin, and I've a bug reported by my accounting team in the "New customer order" email that is sent to us, administrators of the shop.

Sometimes it displays next to the price of the first item in the table an "(ex. VAT)" mention, and sometimes not. I really can't find the option that would fix that. Otherwise, this is just something visual, everything in the shop works well, from price calculation to stock management. This seems to be very random, and I can't find how to reproduce that, nor to fix it.

**Here is what happens sometimes, with that "ex. VAT" mention :**

<a href='https://www.casimages.com/i/210111120009314997.jpg.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/01/11/210111120009314997.jpg' border='0' alt='Mon image' /></a>

**Here is what seems to be more normal :**

<a href='https://www.casimages.com/i/210111120009467190.jpg.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/01/11/210111120009467190.jpg' border='0' alt='Mon image' /></a>

Thanks a lot for any help, I can answer every question if you need more details...

**Comment by delcorp** [comment] 2021-01-11 12:13
Ok, still trying to understand, the funniest part of the thing is that on the first screencap the first item is displayed with no VAT, and the second one with VAT, otherwise the total amount is correct, but with a mix of with and without VAT prices within the same order. All of these products are set as "taxable"...

**Comment by tammullen** [comment] 2021-01-12 20:25
Hi @delcorp 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-01-12 20:25 UTC
