### ISSUE TITLE
 the price does not work

### ISSUE THREAD

**Issue by Tecnonastri** [woocommerce/woocommerce#21212] opened 2018-08-28 15:30 UTC
After loading the prices of my products, they are not shown on the website or on the "Products" page

**To Reproduce**
1. Go to 'Products'
2. See error: 
prices are not shown

**Screenshots**
![cattura](https://user-images.githubusercontent.com/42777608/44733191-54b33c80-aae7-11e8-8590-24ff9bc5209e.PNG)

I would expect prices to be shown, as is normally the case

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

`
### WordPress Environment ###

Home URL: http://www.tecnonastri.com
Site URL: http://www.tecnonastri.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25 - Consigliamo di usare PHP versione 7.2 o superiore per prestazioni e sicurezza maggiori. Come aggiornare la versione di PHP
PHP Post Max Size: 55 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.55.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-38.12-log - Consigliamo l'uso di MySQL con versione minima 5.6. Per i dettagli: Requisiti WordPress
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Dimensione totale database: 6.59MB
Dimensione dati database: 5.79MB
Dimensione indice database: 0.80MB
wp_woocommerce_sessions: Dati: 0.41MB + Indice: 0.02MB
wp_woocommerce_api_keys: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_attribute_taxonomies: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_downloadable_product_permissions: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_order_items: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_order_itemmeta: Dati: 0.02MB + Indice: 0.02MB
wp_woocommerce_tax_rates: Dati: 0.00MB + Indice: 0.01MB
wp_woocommerce_tax_rate_locations: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_shipping_zones: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_shipping_zone_locations: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_shipping_zone_methods: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_payment_tokens: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_payment_tokenmeta: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_log: Dati: 0.00MB + Indice: 0.00MB
wp_commentmeta: Dati: 0.00MB + Indice: 0.00MB
wp_comments: Dati: 0.01MB + Indice: 0.01MB
wp_forte: Dati: 0.06MB + Indice: 0.01MB
wp_fw_termmeta: Dati: 0.00MB + Indice: 0.00MB
wp_links: Dati: 0.00MB + Indice: 0.00MB
wp_login_redirects: Dati: 0.00MB + Indice: 0.00MB
wp_options: Dati: 3.66MB + Indice: 0.07MB
wp_postmeta: Dati: 1.02MB + Indice: 0.51MB
wp_posts: Dati: 0.46MB + Indice: 0.08MB
wp_product_catmeta: Dati: 0.00MB + Indice: 0.00MB
wp_revslider_css: Dati: 0.09MB + Indice: 0.00MB
wp_revslider_layer_animations: Dati: 0.00MB + Indice: 0.00MB
wp_revslider_navigations: Dati: 0.00MB + Indice: 0.00MB
wp_revslider_sliders: Dati: 0.01MB + Indice: 0.00MB
wp_revslider_slides: Dati: 0.04MB + Indice: 0.00MB
wp_revslider_static_slides: Dati: 0.00MB + Indice: 0.00MB
wp_smush_dir_images: Dati: 0.00MB + Indice: 0.00MB
wp_termmeta: Dati: 0.00MB + Indice: 0.01MB
wp_terms: Dati: 0.00MB + Indice: 0.01MB
wp_term_relationships: Dati: 0.00MB + Indice: 0.01MB
wp_term_taxonomy: Dati: 0.00MB + Indice: 0.01MB
wp_usermeta: Dati: 0.01MB + Indice: 0.01MB
wp_users: Dati: 0.00MB + Indice: 0.01MB
wp_wcuf_upload_sessions: Dati: 0.00MB + Indice: 0.01MB
wp_wc_download_log: Dati: 0.00MB + Indice: 0.00MB
wp_wc_webhooks: Dati: 0.00MB + Indice: 0.00MB
wp_yoast_seo_links: Dati: 0.00MB + Indice: 0.00MB
wp_yoast_seo_meta: Dati: 0.00MB + Indice: 0.00MB

### Post Type Counts ###

attachment: 164
custom_css: 1
nav_menu_item: 18
page: 18
portfolio: 1
post: 17
product: 22
product_variation: 177
revision: 98
shop_coupon: 1
shop_order: 25
testimonial: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (9) ###

Contact Form 7: by Takayuki Miyoshi – 5.0.3
Cookie Notice: by dFactory – 1.2.44
WPBakery Page Builder: by Michael M - WPBakery.com – 5.3
Login No Captcha reCAPTCHA: by Robert Peake – 1.2.3
Porto Theme - Functionality: by SW-THEMES – 1.0.0
Slider Revolution: by ThemePunch – 5.4.6.6
W3 Total Cache: by Frederick Townes – 0.9.7
WooCommerce: by Automattic – 3.4.4
Yoast SEO: by Team Yoast – 8.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3629 - /shop/
Carrello: #3550 - /cart/
Cassa: #3551 - /checkout/
Il mio account: #3552 - /my-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Tecnonastri
Version: 1.1
Author URL: http://newsmartwave.net/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 4.0.2
Parent Theme Author URL: http://www.newsmartwave.net/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php versione 2.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/cart/cart-shipping.php versione 3.1.0 è obsoleta. La versione attuale è 3.2.0
tecnonastri/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php versione 3.1.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php versione 3.2.0 è obsoleta. La versione attuale è 3.3.0
tecnonastri/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php versione 3.2.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php versione 2.2 è obsoleta. La versione attuale è 3.4.4
tecnonastri/woocommerce/checkout/form-login.php versione 2.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/checkout/form-pay.php versione 2.5.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/checkout/payment.php versione 2.5.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/checkout/review-order.php versione 2.3.0 è obsoleta. La versione attuale è 3.3.0
porto/woocommerce/content-product.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/content-widget-product.php versione 2.5.0 è obsoleta. La versione attuale è 3.3.0
tecnonastri/woocommerce/emails/admin-new-order.php
tecnonastri/woocommerce/emails/customer-on-hold-order.php
porto/woocommerce/global/form-login.php versione 2.1.0 è obsoleta. La versione attuale è 3.3.0
porto/woocommerce/global/quantity-input.php versione 2.5.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/loop/add-to-cart.php versione 3.0.0 è obsoleta. La versione attuale è 3.3.0
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php versione 2.0.0 è obsoleta. La versione attuale è 3.3.0
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php versione 2.2.0 è obsoleta. La versione attuale è 3.3.0
porto/woocommerce/loop/pagination.php versione 2.2.2 è obsoleta. La versione attuale è 3.3.1
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/myaccount/form-edit-account.php versione 2.6.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/myaccount/form-edit-address.php versione 3.0.9 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/myaccount/form-login.php versione 2.6.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/myaccount/form-lost-password.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/myaccount/form-reset-password.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php versione 3.2.0 è obsoleta. La versione attuale è 3.4.0
tecnonastri/woocommerce/order/order-details.php versione 3.0.0 è obsoleta. La versione attuale è 3.3.0
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/external.php versione 2.1.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/single-product/add-to-cart/grouped.php versione 3.0.7 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/single-product/add-to-cart/simple.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/single-product/add-to-cart/variable.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.1
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php versione 3.1.0 è obsoleta. La versione attuale è 3.3.2
porto/woocommerce/single-product/product-thumbnails.php versione 3.1.0 è obsoleta. La versione attuale è 3.3.2
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php versione 3.0.0 è obsoleta. La versione attuale è 3.4.0
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/share.php
porto/woocommerce/single-product/short-description.php versione 1.6.4 è obsoleta. La versione attuale è 3.3.0
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php versione 2.3.2 è obsoleta. La versione attuale è 3.2.0

Outdated Templates: ❌
					
					
						Scopri come aggiornare
`

**Comment by claudiulodro** [comment] 2018-08-28 19:07
Hi there,

I cannot reproduce this issue on a WooCommerce site running only a default theme with no other plugins. The prices show up and work correctly. I can see that prices are set for the products because the cart totals seem correct and I can see the price in the structured data of the page source: 
`<script type="application/ld+json">{"@context":"https:\/\/schema.org\/","@type":"Product","@id":"http:\/\/www.tecnonastri.com\/shop\/biadesivo-6-rotoli-risma-5cm-x-50m\/","name":"Biadesivo 6 Rotoli (risma) 5cm X 50m","image":"http:\/\/www.tecnonastri.com\/wp-content\/uploads\/2018\/05\/nastro-biadesivo-in-polipropilene_PDT01215.jpg","description":"6 nastri di biadesivo ultraresistente, facile da staccare dalla carta di supporto e molto rapido da attaccare. prezzo compreso di trasporto con consegna in 5gg Lav.","sku":"","offers":[{"@type":"Offer","price":"34.90","priceSpecification":{"price":"34.90","priceCurrency":"EUR","valueAddedTaxIncluded":"false"},"priceCurrency":"EUR","availability":"https:\/\/schema.org\/InStock","url":"http:\/\/www.tecnonastri.com\/shop\/biadesivo-6-rotoli-risma-5cm-x-50m\/","seller":{"@type":"Organization","name":"Nastro adesivo personalizzato online - Tecnonastri","url":"http:\/\/www.tecnonastri.com"}}]}</script>`

The issue seems to most likely be cause by either your custom theme or your parent Porto theme which is almost 2 years out of date. I recommend trying a default theme (twentytwelve or Storefront) and seeing if the problem still happens. If it does keep happening with a default theme, I recommend [the support forums](https://wordpress.org/support/plugin/woocommerce/).

I'm closing this issue because this is not a bug in the WooCommerce core plugin. Thanks.

**Closed by claudiulodro** 2018-08-28 19:07 UTC
