### ISSUE TITLE
"_order_count" and _money_spent" deleted on order creation 

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#28042] opened 2020-10-21 16:03 UTC
not sure if this is a bug or a design decision which I don't understand. 

We're looking to write reports based on customer data and have found the following user meta data:
"paying_customer" (true / false)
"_order_count" (value)
"_money_spent" (value)

But "_order_count" and "_money_spent" are deleted when an order is created (tested with an order created in admin). 

wc_delete_shop_order_transients() in wc-order-functions.php:

```
	// Clear money spent for user associated with order.
	if ( is_a( $order, 'WC_Order' ) ) {
		$order_id = $order->get_id();
		delete_user_meta( $order->get_customer_id(), '_money_spent' );
		delete_user_meta( $order->get_customer_id(), '_order_count' );
	}
```

Can I ask why "_order_count" and _money_spent" are deleted when order is created (tested with an order created in admin)?

**Comment by robertocyrino** [comment] 2021-01-21 14:19
27162701-hc / 3669491-zen

I have confirmed that this happens with WooCommerce 4.9.1 — if we create an order manually via the admin area, the `_order_count` value gets erased.

**Comment by vedanshujain** [comment] 2021-01-22 08:46
Hi, this is by design actually. We use `_order_count` as sort of a caching mechanism because calculating this on the fly is expensive.
This means we would need to invalidate the cache when this value changes, and we do it by deleting it when a new order comes in. We cannot reset the cache with every new order because of the performance implications. This is set whenever `wc_get_customer_order_count` is called as per need basis.

If you'd like this to be always present, there are two workarounds:

1. [Recommended] Before running the report, call `wc_get_customer_order_count` method to reset the cache.

2.  You can hook into `woocommerce_delete_shop_order_transients` action and set it again, but beware that this could slow down your site on some operations as expensive queries will run to reset this value.

I am closing this issue, hopefully one these workaround will work for you. That said, if you have additional questions feel free to ask and we can reopen the issue and discuss more.

**Closed by vedanshujain** 2021-01-22 08:46 UTC
Labels: needs developer feedback
