### ISSUE TITLE
Authorizarion using endpoint REST API

### ISSUE THREAD

**Issue by NickM9** [woocommerce/woocommerce#28128] opened 2020-10-28 16:29 UTC
Hi everyone! I have a problem with endpoint /wc-auth/v1/authorize
I want to make integration with woocommerce shop, and to get keys i use this endpoint with all required fields, but I have an error. Using url ->
https://localhost/woocommerce/index.php/wc-auth/v1/authorize?app_name=onollo&user_id=1001&scope=read_write&return_url=https://localhost:3000/login&callback_url=https://localhost:3000/api/woocommerce/callback
Can someone help me with this problem?
![image_2020_10_28T12_08_10_084Z](https://user-images.githubusercontent.com/50871939/97466109-ca2f2780-1953-11eb-8720-371a176432c9.png)

**Comment by rrennick** [comment] 2021-01-21 18:09
Hi @NickM9,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rrennick** 2021-01-21 18:09 UTC
