### ISSUE TITLE
How to add "Phone number" Column to WooCommerce Admin Customers List?

### ISSUE THREAD

**Issue by datverse** [woocommerce/woocommerce#30383] opened 2021-07-29 17:43 UTC
Hi,
I manage my customers and orders with a important Field is Phone Number. 
In current WooCommerce we have the Customers List feature **_(wp-admin/admin.php?page=wc-admin&path=%2Fcustomers)_**

I want add the Phone Number column to Customer List. Is there any solution? Code / Hook etc
Thanks

**Comment by rodelgc** [comment] 2021-07-30 11:05
Hi @datverse,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rodelgc** 2021-07-30 11:05 UTC

**Comment by datgausaigon** [comment] 2023-01-06 16:32
Hi @rodelgc , 
Please review and reply we comment in https://github.com/woocommerce/woocommerce/issues/30387. 
Re-open one of https://github.com/woocommerce/woocommerce/issues/30387 or this.
This is not a support, this is a new feature request.
Thanks.

**Comment by KoolPal** [comment] 2023-01-20 07:58
@rodelgc This is SILLY
BOTH Issues have been closed in a circular loop!

@datverse Good suggestion! I just landed here as my business needed some additional columns for some analysis & campaign!

@vedanshujain Would you please take a look at this and open an enhancement request?

Cursory search in wordpress.org forum shows DEMAND for this FEATURE!
https://wordpress.org/support/topic/customizing-customer-columns-in-admin/
https://wordpress.org/support/topic/add-phone-to-customer-table-list/
https://wordpress.org/support/topic/add-more-column-to-woocommerce-customers/

**Comment by datgausaigon** [comment] 2023-01-20 11:20
@KoolPal you can follow this  #30505
