### ISSUE TITLE
cart not updating properly (woocommerce_cart_hash)

### ISSUE THREAD

**Issue by rwkyyy** [woocommerce/woocommerce#29225] opened 2021-02-25 18:29 UTC
I have an issue on a client website, initially I thought it was a plugin conflicting or theme issue, but I created a stage env. 1:1 deactivated all plugins, cleared all transients/sessions and the issue still persists.

More specific, you add a product to the cart, and if you change the quantity in the cart, it will reload (via ajax) with the same quantity (the quantity selected in the product page).

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Update cart button does not work properly

**Expected behavior**
Expecting cart quantities to be properly updated

**Actual behavior**
From my testing, when I get to the cart and update product data in the cart, the wocommerce_cart_hash value changes for a brief second, then reverts to it's initial value.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. add product to cart
2. go to cart
3. change quantity and hit update

**Screenshots**
I have a stage env, with emails and noindex, publicly accesible: https://staging-juashop.kinsta.cloud/

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://staging-juashop.kinsta.cloud
Site address (URL): https://staging-juashop.kinsta.cloud
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.6.2
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.5
PHP Version: 7.4.1
PHP Post Max Size: 128 Mo
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.6-MariaDB-1:10.4.6+maria~xenial
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Dimensiune totală bază de date: 931.27MB
Dimensiune date bază de date: 605.67MB
Dimensiune index bază de date: 325.60MB
wp_woocommerce_sessions: Date: 0.08 MO + Index: 0.00 MO + Motor InnoDB
wp_woocommerce_api_keys: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Date: 0.02 MO + Index: 0.06 MO + Motor InnoDB
wp_woocommerce_order_items: Date: 18.55 MO + Index: 5.52 MO + Motor InnoDB
wp_woocommerce_order_itemmeta: Date: 105.64 MO + Index: 82.17 MO + Motor InnoDB
wp_woocommerce_tax_rates: Date: 0.02 MO + Index: 0.06 MO + Motor InnoDB
wp_woocommerce_tax_rate_locations: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_woocommerce_shipping_zones: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_woocommerce_payment_tokens: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_woocommerce_log: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_actionscheduler_actions: Date: 2.02 MO + Index: 0.91 MO + Motor InnoDB
wp_actionscheduler_claims: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_actionscheduler_groups: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_actionscheduler_logs: Date: 1.02 MO + Index: 0.00 MO + Motor InnoDB
wp_admin_columns: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_adtribes_my_conversions: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_aepc_custom_audiences: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_aepc_logs: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_commentmeta: Date: 0.23 MO + Index: 0.25 MO + Motor InnoDB
wp_comments: Date: 59.58 MO + Index: 34.09 MO + Motor InnoDB
wp_links: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_mailchimp_carts: Date: 1.16 MO + Index: 0.00 MO + Motor InnoDB
wp_mailchimp_jobs: Date: 27.55 MO + Index: 0.00 MO + Motor InnoDB
wp_options: Date: 3.05 MO + Index: 0.05 MO + Motor InnoDB
wp_pmxe_exports: Date: 0.05 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxe_google_cats: Date: 0.38 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxe_posts: Date: 0.11 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxe_templates: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxi_files: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxi_hash: Date: 1.52 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxi_history: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxi_images: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxi_imports: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxi_posts: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_pmxi_templates: Date: 0.05 MO + Index: 0.00 MO + Motor InnoDB
wp_postmeta: Date: 316.83 MO + Index: 165.36 MO + Motor InnoDB
wp_posts: Date: 31.52 MO + Index: 10.05 MO + Motor InnoDB
wp_rank_math_404_logs: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_rank_math_analytics_gsc: Date: 0.02 MO + Index: 0.06 MO + Motor InnoDB
wp_rank_math_analytics_objects: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_rank_math_internal_links: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_rank_math_internal_meta: Date: 0.08 MO + Index: 0.00 MO + Motor InnoDB
wp_rank_math_redirections: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_rank_math_redirections_cache: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_rank_math_sc_analytics: Date: 1.52 MO + Index: 0.38 MO + Motor InnoDB
wp_termmeta: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_terms: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_term_relationships: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_term_taxonomy: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_usermeta: Date: 2.52 MO + Index: 3.03 MO + Motor InnoDB
wp_users: Date: 0.19 MO + Index: 0.16 MO + Motor InnoDB
wp_wc_admin_notes: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_wc_admin_note_actions: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_wc_category_lookup: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_wc_customer_lookup: Date: 6.52 MO + Index: 4.03 MO + Motor InnoDB
wp_wc_download_log: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_wc_order_coupon_lookup: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_wc_order_product_lookup: Date: 8.52 MO + Index: 6.06 MO + Motor InnoDB
wp_wc_order_stats: Date: 7.52 MO + Index: 5.55 MO + Motor InnoDB
wp_wc_order_tax_lookup: Date: 8.52 MO + Index: 7.03 MO + Motor InnoDB
wp_wc_product_meta_lookup: Date: 0.02 MO + Index: 0.09 MO + Motor InnoDB
wp_wc_reserved_stock: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_wc_tax_rate_classes: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_wc_webhooks: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB
wp_woocommerce_bundled_itemmeta: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_woocommerce_bundled_items: Date: 0.02 MO + Index: 0.03 MO + Motor InnoDB
wp_woos_search_analytics: Date: 0.02 MO + Index: 0.00 MO + Motor InnoDB
wp_woos_search_trends: Date: 0.02 MO + Index: 0.02 MO + Motor InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 2
attachment: 119
custom_css: 1
elementor_library: 10
nav_menu_item: 11
page: 16
post: 3
postman_sent_mail: 5
product: 40
product_variation: 7
revision: 83
shop_order: 55371
shop_order_refund: 29

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: de John Blackbourn – 3.6.7
WooCommerce: de Automattic – 5.0.0
WP Rollback: de Impress.org – 1.7.1

### Inactive Plugins (26) ###

Advanced Custom Fields PRO: de Elliot Condon – 5.9.5
Ajax Cart AutoUpdate for WooCommerce: de taisho – 1.5.4
Comenzi duplicate JUA: de rwky – 1.2
Disable Emails: de WebAware – 1.7.0
Disable WooCommerce Bloat: de ospiotr – 2.4.4
Elementor: de Elementor.com – 3.1.1
Elementor Pro: de Elementor.com – 3.1.1
Filter WooCommerce Orders by Payment Method: de SkyVerge – 1.0.0
Hotjar: de Hotjar – 1.0.9
Loco Translate: de Tim Whitlock – 2.5.0
Mailchimp for WooCommerce: de Mailchimp – 2.5.0
ManageWP - Worker: de GoDaddy – 4.9.8
Netopia mobilPay Payment Gateway: de Netopia – 1.0
PixelYourSite: de PixelYourSite – 8.0.7
Post SMTP: de Yehuda Hassine – 2.0.22
Product Feed PRO for WooCommerce: de AdTribes.io – 9.6.8
Qty Increment Buttons for WooCommerce: de taisho – 2.7.5
Rank Math SEO: de Rank Math – 1.0.58
reSmush.it Image Optimizer: de reSmush.it – 0.3.11
States, Cities, and Places for WooCommerce: de Kingsley Ochu – 1.3.2
Two Factor: de Plugin Contributors – 0.7.0
Urgent Cargus Printing AWB: de Safe Alternative – 1.7.9
WooCommerce Checkout Field Editor: de WooCommerce – 1.5.39
WooCommerce Postis: de Ciobanu George – 1.0.0
WooCommerce SmartBill: de Ciobanu George – 1.0.0
Woo Search Box: de Guaven Labs – 2.1.12

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Disable Emails Must Use: de WebAware – 1.0.0
Kinsta Must-use Plugins: de Kinsta Team – 2.3.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Bază magazin: #59110 - /
Coș: #10 - /cart/
Finalizare: #59112 - /checkout/
Contul meu: #45413 - /contul-meu/
Termeni și condiții: ❌ Vizibilitatea paginii ar trebui să fie publică

### Theme ###

Name: Twenty Twenty-One
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – Dacă modifici WooCommerce într-o temă părinte pe care nu ai construit-o personal recomandăm folosirea unei teme copil. Vezi: Cum creezi o temă copil
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Finalizează: 3.113
Oldest: 2021-02-18 19:36:33 +0200
Newest: 2021-02-25 20:15:39 +0200

În așteptare: 2
Oldest: 2021-02-25 21:15:39 +0200
Newest: 2021-02-27 02:13:06 +0200

`
```
</details>

**Comment by rwkyyy** [comment] 2021-02-26 08:40
after more digging (and trying a different server) I noticed that the problem is in the woocommerce_cart_hash request <> response cookies.
<img width="1076" alt="Screenshot 2021-02-26 at 10 39 22" src="https://user-images.githubusercontent.com/13552349/109276617-ea49f700-781e-11eb-9129-54b8da307fcf.png">

**Comment by juliaamosova** [comment] 2021-02-26 20:13
Hi @rwkyyy,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. Please see gif below:

![](http://g.recordit.co/BH31gk7cTo.gif)

I am not sure what could be the issue on your end since you also stated that you tested this in isolation with only WooCommerce activated. I am adding the `needs developer feedback` label here to see if others have any ideas.

**Comment by rwkyyy** [comment] 2021-02-27 11:06
@juliaamosova I know this is an isolated case, but the problem is that I can't find the issue causing this. After more digging today, I deleted the wc plugin, redownloaded it from wordpress.org and cleared almost everything via wc tools (transients, sessions, etc.) 

Initially just the 1st session would work properly, then after another clear (via tools) it started working again properly... now I just need to find what exactly I did that caused the cart hashes to work properly again.

**Comment by rwkyyy** [comment] 2021-02-27 22:04
I managed to find the issue, after more digging apparently there was an issue with the sessions table in the database (although the clear sessions did not fix the issue).

In order to fix this issue I had to do the following:
1. clear all transients
2. clear user sessions
3. verify database
After doing this, the bellow error shows:
![Image 1](https://user-images.githubusercontent.com/13552349/109401524-f38aaf00-7957-11eb-8d8b-3480b6f84dfd.png)

**After** hitting the **verify database again**, everything is **back to normal.**

p.s. there was no notice from the verify database that it fount any issues, the above image is from query monitor who reported the issues in the database query, so there is a bug with the response from the verify database tool.
p.p.s. if anyone needs the database/table to study I can sent it, it's been cleaned keeping just this issue.

**Comment by claudiosanches** [comment] 2021-04-01 00:34
Hello @rwkyyy,

I couldn't reproduce this issue, sounds like something or some plugin caused this issue with your sessions table.
I'm glad to know that the options to clean user sessions and transients helped to make it work again.
But you can also try to disable WooCommerce and drop that database, so while activating again WooCommerce will recreate this table, but note that removing it will end any user session in the front-end.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2021-04-01 00:34 UTC
Labels: needs developer feedback
