### ISSUE TITLE
Products cannot add to the cart 

### ISSUE THREAD

**Issue by JovyTong** [woocommerce/woocommerce#26766] opened 2020-06-15 03:45 UTC
![ss21hk- add to cart problem](https://user-images.githubusercontent.com/66932116/84615811-913e6b00-aefc-11ea-887e-54e98a9f67ae.png)
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
[ss21hk system report.docx](https://github.com/woocommerce/woocommerce/files/4777938/ss21hk.system.report.docx)

**Comment by tammullen** [comment] 2020-06-15 14:42
Hi @JovyTong 


Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by JovyTong** [comment] 2020-06-15 17:04
Go to ' https://ss21hk.com/ss21hk-enzyme-drinks/ 'Click on 'Button”Add to Cart”'Scroll down to ' https://ss21hk.com/product/ss21hk-21days-slimming-enzyme/ 'See errorError is   You cannot add another "紅藜鰹魚彈力蛋白肽綜合發酵果蔬飲品 (酵素)" to your cart. = you cannot add another “product a” to your cart. [y ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.[ y] This bug happens with active with OceanWP.[y ] I can reproduce this bug consistently using the steps above.This problem is created after I tried to add one more “add to cart” button on the same page (as I add new product on that page) Best regards, Jovy Sent from Mail for Windows 10 From: Tam MullenSent: Monday, June 15, 2020 10:42 PMTo: woocommerce/woocommerceCc: JovyTong; MentionSubject: Re: [woocommerce/woocommerce] Products cannot add to the cart (#26766) Hi @JovyTongThank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.​Describe the bugA clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.​To ReproduceSteps to reproduce the behavior:Go to '...'Click on '....'Scroll down to '....'See error​ScreenshotsIf applicable, add screenshots to help explain your problem.​Expected behaviorA clear and concise description of what you expected to happen.​Isolating the problem (mark completed items with an [x]):[ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.[ ] This bug happens with a default WordPress theme active, or Storefront.[ ] I can reproduce this bug consistently using the steps above.​WordPress Environment``` Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin. ``` —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tammullen** [comment] 2020-06-15 21:27
Hi @JovyTong 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
Label:

**Closed by tammullen** 2020-06-15 21:27 UTC
Labels: can't reproduce, status: needs feedback
