### ISSUE TITLE
Session issues with cached pages

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#21944] opened 2018-11-16 11:31 UTC
As WC sets cookies on PHP, caching any page that would normally set or update a core cookie like Cart, Checkout or even pages with add-to-cart, results in issues with sessions. This is understandable to a degree, but has the potential of breaking stuff unexpectedly and potentially cause #8504 and a number of other past tickets.

In our setup, we use nginx fastcgi and bypass caching for WC pages (cart, my-account, checkout, etc) as well as specific query strings (wc-ajax, add-to-cart, etc).

We noticed that for some reason, our home page and few other pages, are setting a session cookie which is then cached. We use Visual Composer, custom theme and a number of plugins so this session could be initiated by any one of them.

The problem is those pages send a set-cookie header for wp_woocommerce_session_. This could be due to a number of reasons but the moment it fires, it will be served to anyone else who's accessing the page, causing a session mixup and random items added to the cart.

The `fastcgi_hide_header "Set-Cookie";` directive can strip the header from the cached file, but would prevent cookies being set and therefore break the site.

A solution to this issue, would be to set the WC cookies in JS instead of PHP. I understand WC should work without JS, so maybe can make this optional?

I notice the JS cookie is already part of WC (https://github.com/woocommerce/woocommerce/blob/master/assets/js/jquery-cookie/jquery.cookie.js) althought this is now deprecated and replaced by JS Cookie (https://github.com/js-cookie/js-cookie)

A workaround is to bypass cache for people who have items in their cart, but that is not ideal as it skips cache across the site for everyone with items in their cart. The cart contents are already retrieved via Ajax, so it's a waste to skip cache on all pages as soon as someone adds something to their cart.

**Comment by glagonikas** [comment] 2018-11-19 18:33
I've not dug deep into this, but we do use some Visual Composer elements across the site that pull information from WooCommerce. Any one of them could cause the issue, or any other plugin.

@xbb123, do you initiate a session outside the standard WooCommerce pages? This is what causes the issue.

**Comment by xbb123** [comment] 2018-11-19 18:40
@glagonikas Try grep wc_setcookie this should give you a clue.

**Comment by glagonikas** [comment] 2018-11-20 10:20
We don't use related products and exclude the product pages from cache.

There's no denying a session is set by one of our plugins, the question is whether other people think it's a good idea to set session cookies in PHP or they can optionally be moved to JS.

To be clear, i'm saying there's something broken with WC, as it clearly works with a lot of stores. I wonder hoever if the whole caching can/should be improved.

There are a number of caching and session related issues that keep coming up every so often, so there might be some common ground between them that can be improved?

**Comment by mikejolley** [comment] 2019-02-22 13:54
The problem is that once you have a cart cookie, there may be PHP rendered things on the page which looks at that cookie/shows data from that cart. The JS cart widget + fragments does aim to get around static caching, but this isn't the only use case out there.

Setting the cookies with JS is a no-go. The logic which relies on cookies is all on the PHP code.

Perhaps we can look at not setting cookies if they exist already except for on WC pages but that could lead to cookies timing out if you're not active on store pages? I'll have a look.

FWIW most static caching *plugins* exclude logged in users from cache. Thats probably a close comparison to users with carts. At that point, most pages need to be dynamic otherwise cart logic cannot run, and content on the page that is based on the cart cannot function.

**Comment by mikejolley** [comment] 2019-02-27 16:02
Looks like that was already done. Cookies are only set if they do not exist and there is a cart/session, or if the cookie value needs to be updated.

Nothing more can be done there. The only way to totally avoid cookie setting would be to have a JS powered cart so the PHP does not handle it. Thats not something we can do short term nor is it something we could do without fully considering the side effects.

Since the idea of setting cookies via JS only is a no-go I'm closing this issue.

Thanks

**Closed by mikejolley** 2019-02-27 16:02 UTC
