### ISSUE TITLE
Can only hide extended task list when L3 tasks are in the list

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce#32252] opened 2021-05-17 20:57 UTC
**Is your feature request related to a problem? Please describe.**
In woocommerce/woocommerce-admin#6638 a show/hide feature was added to the extended task list, however it should only be available when there aren't high priority or required tasks in the list. High priority tasks and required extension tasks need immediate attention to maintain functionality of the store, so these tasks should appear in the list until completed.

**Describe the solution you'd like**
![L1 tooltip](https://user-images.githubusercontent.com/5121465/118555285-1f802a00-b728-11eb-98df-adc1d31afe2b.png)

If L1 or L2 tasks appear in the extended task list (red or yellow border color), the the card menu (ellipses) doesn't appear. L3 tasks aren't required, so if there are only L3 tasks in the list, the task list menu appears with the option to Hide the list (as it's currently built.)

**Describe alternatives you've considered**
I considered introducing a notification dot on the Display menu with more context on the required tasks in the dropdown, but chatted with @jeffstieler about this in Slack and it's much simpler and straightforward to only allow hiding the task list if no required tasks are in the list.

**Should this be prioritized? Why?**
Yes. This will be important to make sure merchants don't miss important notices.

**Comment by joshuatf** [comment] 2022-01-20 15:29
I don't think we're using the collapsible list at the moment, but this could be a regression from refactoring.  cc @woocommerce/mothra for anyone that might have more info on when it's supposed to be shown.  Always for the extended list?

It still looks like it can be used, but none of the task lists have the prop currently.

If we still plan to use it, this issue still needs to be addressed.  cc @jarekmorawski  since @elizaan36 is AFK.

<img width="484" alt="Screen Shot 2022-01-20 at 10 27 47 AM" src="https://user-images.githubusercontent.com/10561050/150369117-fb09c955-5131-4453-a394-e0a203e62aa7.png">

**Comment by jarekmorawski** [comment] 2022-01-20 21:17
> If we still plan to use it, this issue still needs to be addressed.

I confirm that we'll use collapsible lists in the future and it'd be great to have it working. Thanks for the ping!

**Comment by adrianduffell** [comment] 2023-01-06 03:41
I'll close this out due to the age, but it can potentially still be implemented as part of a design iteration on the task list.

cc @verofasulo @FlorianBru fyi

**Closed by adrianduffell** 2023-01-06 03:41 UTC
Labels: type: enhancement, plugin: woocommerce, focus: react admin, focus: activity panel
