### ISSUE TITLE
Showing client address without the delivery option - confusing the user

### ISSUE THREAD

**Issue by biasga** [woocommerce/woocommerce#28802] opened 2021-01-12 20:29 UTC
I sell some products only in my city using the WooCommerce plugin, and I don't give the option to delivery the products, the clients must come and pick the order in my house. 

When they are in the cart page, they see the "delivery field" where they would choose the delivery option and see the delivery fees, but there is any option for that, just the option for "pick up at the place", but the client address keep showing below that, confusing the users.

Some clients just see their address and think I'm gonna delivery the orders to they without a fee, and don't read the "pick up at the place" above the address.

I think when the users don't have the delivery order, their address must not be showed to not confuse the clients, they must see only the "pick up at the place" option and nothing more than that.

**Comment by tammullen** [comment] 2021-01-12 20:42
Hi @biasga 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review the documentation for Local Pickup https://docs.woocommerce.com/document/local-pickup/
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-01-12 20:42 UTC
