### ISSUE TITLE
Order details not showing in some customers' dashboard

### ISSUE THREAD

**Issue by ninanevski** [woocommerce/woocommerce#21078] opened 2018-08-16 17:34 UTC
**Describe the bug**
I can view all the test purchases made on my separate account. However, one of my customers is not seeing their order details. it simply says they have not placed any orders. However, on my end it shows her order and everything they have purchased. How can I fix this? This doesn't seem to be an issue for all customers. 

**To Reproduce**
1. Go to 'orders'
2. Click on 'a specific order'
3. See the proof that the customer paid and has access to orders
4. Go to "my account"
5. Sign in with customers credentials they have shared
6. Go to "orders"
7. See error. It says that there are no orders. 

**Screenshots**

**Expected behavior**
It's expected that order details will show to the customer, especially downloadable links. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiulodro** [comment] 2018-08-16 20:45
Hi there.

Just to confirm, when you go to the order details in the admin screen the customer's profile is linked to the order and it does not say 'Guest' in the customer section, correct?

<img width="358" alt="screen shot 2018-08-16 at 1 36 27 pm" src="https://user-images.githubusercontent.com/7317227/44233735-8af0d380-a159-11e8-8629-29f07df81945.png">

It is possible that this customer may have placed a new order as a guest without logging into their account, in which case it wouldn't be linked to their account.

I was not able to reproduce this, and without the system status report it is impossible for us to troubleshoot this further. Other possibilities include plugin conflicts, theme conflicts, etc. Without further information I must close this issue as non-reproducible. If you can post back with more information and the system status report I can reopen this if further troubleshooting is possible.

**Closed by claudiulodro** 2018-08-16 20:45 UTC

**Comment by ninanevski** [comment] 2018-08-16 22:58
Thank you so much. After much troubleshooting, the customer had two
accounts and confused them
