### ISSUE TITLE
3.3.1 update makes shop products disappear (Divi)

### ISSUE THREAD

**Issue by theasander** [woocommerce/woocommerce#18915] opened 2018-02-09 20:29 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Shop built using Divi Theme from Elegant Themes and version 3.2.6 of WooCommerce plugin. Very simple layout: standard section with 2 modules, a text module and a shop module. 7 products uploaded to woocommerce products.
2. Upgrade to 3.3.1 WooCommerce (along with upgrades to most recent woocommerce services and stripe gateway). Result: All elements on shop page disappear, except for the fixed banner. 
3. Re-save all permalinks. Result: No change
4. Rollback to 3.2.6 of just the woocommerce plugin. Result: Shop page displays correctly again.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://www.theasander.com
Site URL: https://www.theasander.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: 43b_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.41MB
Database Data Size: 1.27MB
Database Index Size: 0.14MB
43b_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
43b_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
43b_woocommerce_log: Data: 0.00MB + Index: 0.00MB
43b_commentmeta: Data: 0.00MB + Index: 0.00MB
43b_comments: Data: 0.00MB + Index: 0.00MB
43b_links: Data: 0.00MB + Index: 0.00MB
43b_options: Data: 0.97MB + Index: 0.05MB
43b_postmeta: Data: 0.07MB + Index: 0.03MB
43b_posts: Data: 0.22MB + Index: 0.02MB
43b_termmeta: Data: 0.00MB + Index: 0.01MB
43b_terms: Data: 0.00MB + Index: 0.01MB
43b_term_relationships: Data: 0.00MB + Index: 0.00MB
43b_term_taxonomy: Data: 0.00MB + Index: 0.00MB
43b_usermeta: Data: 0.00MB + Index: 0.01MB
43b_users: Data: 0.00MB + Index: 0.01MB
43b_wc_download_log: Data: 0.00MB + Index: 0.00MB
43b_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

amn_wpforms-lite: 2
attachment: 19
custom_css: 2
customize_changeset: 1
et_pb_layout: 1
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 5
page: 8
post: 1
product: 9
revision: 32

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.2

Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.17
Jetpack by WordPress.com: by Automattic – 5.8
WooCommerce Stripe Gateway: by WooCommerce – 4.0.5
WooCommerce Services: by Automattic – 1.11.0
WooCommerce: by Automattic – 3.2.6 – 3.3.1 is available
WP Rollback: by WordImpress – 1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #200 - /shop/
Cart: #206 - /cart/
Checkout: #208 - /checkout/
My account: #210 - /login/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi
Version: 3.0.101
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by WPprodigy** [comment] 2018-02-09 22:48
I have tested Divi pretty extensively, and I'm not seeing this occur on the latest version of WC.

1) Does this happen when all plugins except for WooCommerce are disabled?
2) Is the problem fixed when temporarily switching to a default WP theme (need to narrow down to Divi related)

Other things to check/try:

- Disable the Divi page builder on the shop page and save. Test again.
- Remove all shop page content and save. Test again.

**Comment by shirokoweb** [comment] 2018-02-09 22:49
Same here.
A workaroud is to create an alt page and use it as shop page with divi shop module on it.
(Do not define that page as shop page in BO, it will reproduce the same issue.)

Another thing, dunno if it's related, but paying with Paypal from Android do not work.
Cancelled transactions do not return back items in stock.

**Comment by mikejolley** [comment] 2018-02-10 00:27
Turn off divi builder visual editor on the shop page and products will display. We're talking to divi about best way forward because the options conflict.

**Comment by shirokoweb** [comment] 2018-02-10 10:02
@mikejolley and @theasander 

*A quick and dirty fix:*
Edit /wp-content/themes/Divi/includes/builder/compat/woocommerce.php file and comment line 98:
`// $query->is_page              = true;`

**Comment by berkmh** [comment] 2018-02-11 20:57
@shirokoweb works for now! thanks

**Comment by shirokoweb** [comment] 2018-02-11 23:02
@berkmh glad it worked !

**Comment by supsupsup** [comment] 2018-02-12 08:12
@shirokoweb Many thanks for the fix, works perfectly now.

**Comment by sephmilanes** [comment] 2018-02-12 08:53
i followed shirokoweb, still divi layout not showing on my woocommerce shop page

**Comment by shirokoweb** [comment] 2018-02-12 14:11
@sephmilanes it is an author theme issue and WC is aware of. Thery already took action and contacted Divi authors to tell what is needed to resolve this according to what I've been told.
Sorry to hear the temporarily workaround didn't fix your issue. My best advise is to contact ET support.

**Comment by sephmilanes** [comment] 2018-02-13 01:23
thanks for the update sir, hoping Elegant devs fix this..

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by stevehazza411** [comment] 2018-02-13 16:08
The comment by @shirokoweb solves this. ET support are also aware of it:  https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=817010&hilit=latest+woocommerce&p=4496535#p4496535

**Comment by mikejolley** [comment] 2018-02-15 16:41
Gonna close this out as Divi are aware and will be pushing ^ that fix out. We're still chasing for access to do our own tests but if any other issues crop up after doing so I'll reopen or create a fresh issue.

Thanks everyone.

**Closed by mikejolley** 2018-02-15 16:41 UTC
Labels: Status: Blocked / Hold, Status: Needs Author Feedback

**Comment by jgarciab83** [comment] 2018-02-28 20:20
To resolve this you just need to go to the reading settings of wordpress and choose again the static page of your store http://prntscr.com/il2opc

**Comment by shirokoweb** [comment] 2018-03-02 15:16
@jgarciab83 please don't dig old threads if it doesn't add any value to it.
Did you make sure we talk about same versions of WC + Divi ?
The incompatibility issue ahas been fixed since. Regards
Just kindly sayin...

**Comment by sephmilanes** [comment] 2018-03-05 00:48
not it's not, may woocommerce shop page doesn't show up my divi modules, so
there's still an error


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by WPprodigy** [comment] 2018-03-05 17:57
Open up a new issue @sephmilanes. Be sure to read and follow the steps when creating an issue. Closing this issue to avoid people getting notified over and over.
