### ISSUE TITLE
Can't override html-order-download-permission.php template

### ISSUE THREAD

**Issue by andreagrillo** [woocommerce/woocommerce#18112] opened 2017-12-12 13:22 UTC
In the file /includes/admin/meta-boxes/class-wc-meta-box-order-downloads.php at line 56 I have found this line of code: 

`include( 'views/html-order-download-permission.php' );`

In this way I haven't a way to override this template.
If possible to add a way to override it, in example `use wc_get_template()` or an hook ? 
Thanks for your time. 

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected/actual behavior

This file it is showing the download link of a downloadable product of an order. I have a plugin that use the S3 amazon storage service to this file and I need to edit the template to change the file url in order to allow the customer to donwload it. 

In this case I haven't a way to override this template. The only solution is to change the home_url uri with the `apply_filters( 'home_url', $url, $path, $orig_scheme, $blog_id )`, but I can't reach my goal, too.

I was expecting to see a ` wc_get_template()` function in order to override the template.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://support.dev
Site URL: http://support.dev
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.7
PHP Version: 7.0.14-2+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 20.93MB
Database Data Size: 12.88MB
Database Index Size: 8.05MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.13MB + Index: 0.06MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.92MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_adsw_activities: Data: 0.02MB + Index: 0.00MB
wp_adsw_ali_meta: Data: 0.02MB + Index: 0.03MB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
wp_ap_qameta: Data: 0.02MB + Index: 0.00MB
wp_ap_reputations: Data: 0.02MB + Index: 0.00MB
wp_ap_subscribers: Data: 0.02MB + Index: 0.00MB
wp_ap_views: Data: 0.02MB + Index: 0.00MB
wp_ap_votes: Data: 0.02MB + Index: 0.00MB
wp_bp_activity: Data: 0.02MB + Index: 0.16MB
wp_bp_activity_meta: Data: 0.02MB + Index: 0.03MB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB
wp_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.23MB + Index: 0.28MB
wp_faq_termmeta: Data: 0.02MB + Index: 0.00MB
wp_layerslider: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 4.27MB + Index: 0.17MB
wp_postmeta: Data: 3.52MB + Index: 3.95MB
wp_posts: Data: 1.52MB + Index: 0.23MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.11MB + Index: 0.09MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_appointment_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_cancel_orders: Data: 0.02MB + Index: 0.00MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_yith_padp_receiver_commissions: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_commissions: Data: 0.06MB + Index: 0.00MB
wp_yith_vendors_commissions_notes: Data: 0.20MB + Index: 0.00MB
wp_yith_vendors_payments: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_payments_relathionship: Data: 0.02MB + Index: 0.00MB
wp_yith_wapo_groups: Data: 0.02MB + Index: 0.00MB
wp_yith_wapo_types: Data: 0.02MB + Index: 0.00MB
wp_yith_wcact_auction: Data: 0.02MB + Index: 0.00MB
wp_yith_wcbk_booking_notes: Data: 0.02MB + Index: 0.00MB
wp_yith_wcch_emails: Data: 0.02MB + Index: 0.00MB
wp_yith_wcch_sessions: Data: 0.02MB + Index: 0.00MB
wp_yith_wccl_meta: Data: 0.02MB + Index: 0.00MB
wp_yith_wcdn_desktop_notification: Data: 0.02MB + Index: 0.00MB
wp_yith_wcmbs_downloads_log: Data: 0.02MB + Index: 0.00MB
wp_yith_wcps_shippings: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yith_ywsbs_activities_log: Data: 0.02MB + Index: 0.00MB
wp_ylc_chat_rows: Data: 0.02MB + Index: 0.00MB
wp_ylc_chat_sessions: Data: 0.02MB + Index: 0.02MB
wp_ylc_chat_visitors: Data: 0.02MB + Index: 0.00MB
wp_ylc_offline_messages: Data: 0.02MB + Index: 0.00MB
wp_ywcars_messagemeta: Data: 0.02MB + Index: 0.00MB
wp_ywcars_messages: Data: 0.02MB + Index: 0.00MB
wp_ywcdd_calendar: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf: 1
answer: 1
attachment: 102
avia_framework_post: 6
bp-email: 16
contactform: 5
custom_css: 2
et_pb_layout: 32
gift_card: 2
nav_menu_item: 11
page: 21
post: 3
product: 36
product_variation: 57
question: 1
revision: 12
scheduled-action: 3
shop_coupon: 8
shop_order: 497
shop_order_refund: 175
shop_subscription: 1
wc_appointment: 1
wc_booking: 1
wc_order_status: 7
yith_carrier: 1
yith_proc_method: 1
yith_refund_request: 1
yith-wcbm-badge: 1
yith-wcet-etemplate: 1
ywsbs_subscription: 1
ywtm_tab: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

Members: by Justin Tadlock – 2.0.2
User Switching: by John Blackbourn – 1.3.0
WooCommerce: by Automattic – 3.2.5
YITH Frontend Manager for WooCommerce Premium: by YITHEMES – 1.2.1
YITH Frontend Manager Hide Info to Vendors: by YITHEMES – 1.0.0
YITH Plugin Framework Test: by YITHEMES – 3.0.0
YITH WooCommerce Ajax Product Filter Premium: by YITHEMES – 3.4.7
YITH WooCommerce Color and Label Variations Premium: by YITHEMES – 1.5.0 – Not tested with the active version of WooCommerce
YITH WooCommerce Multi-step Checkout Premium: by YITHEMES – 1.6.1
YITH WooCommerce Multi Vendor Premium SW MaxShop Theme Support: by YITHEMES – 1.0.0 – Not tested with the active version of WooCommerce
YITH WooCommerce Multi Vendor Premium: by YITHEMES – 2.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: appointment (appointment)
auction (auction)
booking (booking)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #221 - /vendors-terms-and-conditions/

### Theme ###

Name: Twenty Sixteen
Version: 1.3 – 1.4 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment] 2017-12-12 14:32
Admin files cannot be overridden - they are core to WC. Only frontend template files can be overridden.

If you need actions/filters inside https://github.com/woocommerce/woocommerce/blob/31651e41cbc1ad8b731532f6629a334c8ddf94c2/includes/admin/meta-boxes/views/html-order-download-permission.php, raise a PR and justify your reasoning.

>  I have a plugin that use the S3 amazon storage service to this file and I need to edit the template to change the file url in order to allow the customer to donwload it.

IMO the "Customer download link" should be left alone. handle the redirect from local WC download link to service elsewhere. Other s3 download plugins manage this?

I'm closing this as it's not a bug/intended functionality.

Thanks

**Closed by mikejolley** 2017-12-12 14:32 UTC

**Comment by andreagrillo** [comment] 2017-12-13 08:25
Thanks for your reply. I ask to S3 dev to look for another solution! 
Bye! 

AG
