### ISSUE TITLE
Column Mapping is not working in woocommerce product importar

### ISSUE THREAD

**Issue by PoojaMintex** [woocommerce/woocommerce#27411] opened 2020-08-19 16:57 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Describe the bug**
i uploaded sample csv file in woocommerce product importer but column mapping is not working 

**Expected behavior**
![image](https://user-images.githubusercontent.com/69916051/90666138-986e5600-e26a-11ea-8d1c-05b04fb5bd84.png)

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 
![image](https://user-images.githubusercontent.com/69916051/90666284-c6ec3100-e26a-11ea-883d-c5bf1b0f1a6b.png)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Products 
2. Click on 'Import' and upload woocommerce demo sample_csv file
3. After click continue
4. and column mapping tab and see error

**Isolating the problem (mark completed items with an [x]):**

- [x ] This bug happens with a Emarket  WordPress theme active

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by claudiosanches** [comment] 2020-08-19 18:05
Hello @PoojaMintex 

I can't reproduce this issue, at least not with just the steps you provided.
It sounds like you are changing the CSV delimiter, there's options for it on the Importer page, so you can choice the correct delimiter so all fields can get mapped.

I'm closing since it works as expected, and the delimiter settings works correctly, you just need to set the correct option for your CSV file.

**Closed by claudiosanches** 2020-08-19 18:05 UTC

**Comment by PoojaMintex** [comment] 2020-08-20 06:53
i used "," delimiter and i use woocommerce sample csv file but its not working 
can you tell me which delimiter am i use?
i also attached csv file link so you can see
https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv
