### ISSUE TITLE
Order status "On Hold" not sending email alerts

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [woocommerce/woocommerce#20563] opened 2018-06-18 14:40 UTC
Whenever admin changes the order status to on hold, the status updated successfully but email alert is not being sent to the recipient (customer) 

## Prerequisites
nothing

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. admin changed order to on hold (on hold status successfully  changed), but email is not sent.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment] 2018-06-19 10:31
Tested and seems to be working. Code accounts for these transitions:

```
add_action( 'woocommerce_order_status_pending_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_failed_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
```

So this only sends if the order was pending or failed previously.

Please go through https://docs.woocommerce.com/document/email-faq/ - if you can provide any more details or steps to reproduce please comment back and I'll take another look. For now, closing as it doesn't appear to be a core bug.

Thanks

**Closed by mikejolley** 2018-06-19 10:31 UTC

**Comment by spradooooo** [comment] 2018-08-20 23:39
Hello,

I have the same issue, when I change the order status to on-hold, it never send an email to customers.
Only if the status is changed from pending or failed it works fine.

How can I make woocommerce send the emails when the status changed to on-hold because in some secarios I just want to put the order on-hold not because of the payment but other reasons.

Can you help please?

**Comment by peterfabian** [comment] 2018-08-24 07:51
Hi, 

Have you checked the Order on-hold email settings in Admin > WooCommerce > Settings > Email?
<img width="1348" alt="order_on_hold" src="https://user-images.githubusercontent.com/2207451/44572150-454c9000-a783-11e8-827c-6afb8374fa90.png">

**Comment by clarmendes** [comment] 2019-06-04 09:03
Hello, what have you guys come to the conclusion on this one?
Woocommerce core settings are to sending On hold mail only when the order is on failed or pending. 
I also wanted to add more triggers, so the email will be sending from processing order. How do I do that?

**Comment by peterfabian** [comment] 2019-06-18 11:04
> Woocommerce core settings are to sending On hold mail only when the order is on failed or pending.

This might need to change similarly to how we changed it for `capture_payment` in https://github.com/woocommerce/woocommerce/pull/23634.

> email will be sending from processing order

I think you should be able to use `woocommerce_order_status_processing` action.

**Comment by codesarts** [comment] 2020-12-02 03:57
I had same exactly the same issue, the around solution is to change the order status to Pending payment (which is not triggering any emails) then change it to on-hold status which can trigger two emails (admin and customer).

**Comment by jeanpaul1304** [comment] 2021-01-21 09:14
I have the same issue

**Comment by creative365** [comment] 2021-01-25 03:57
I have the same issue. If the status changes to on-hold, the email is not being sent.

@codesarts: Can you do it automatically? without manually changing the order status in Wordpress? Thank you!

**Comment by codesarts** [comment] 2021-02-02 20:26
No

Thanks,
Mohaned Khudher
Hashrates Services

________________________________

**Comment by maawco** [comment] 2021-02-03 12:19
HI,
I don't get why this topic is close.

 I still have the same issue, can't send email order status "on hold" without come from "pending payement" or "failed" and can't do this manipulation because those status change the stock and others data order. 

I just want to be able to set directly "on hold" and then push "update" button for send the email... 

Please WooCommerce do something... :'(

**Comment by jvwrx** [comment] 2021-03-04 01:21
Having the same issue.

On staging site:

- I've switched theme to Storefront
- Deactivated all plugins except WooCommerce and Email Logs
- Woo > Settings > Emails > **Order on-hold** email is enabled
- When changing an order to **On Hold** status, customer email **is not** sent
- When changing an order to **Completed** or **Processing**, customer email **is** sent

**Comment by tkymuk** [comment] 2021-03-11 14:58
i am also having this issue. I have the email enabled in email settings. How do I go about fixing this?

**Comment by MDAdler** [comment] 2021-07-08 03:18
This is such a core requirement. Like others, I don't understand why WooCommerce does not automatically trigger an On-hold email when the administrator puts and order on hold. If I order something from any supplier, I want to know if and as soon as my order is placed on hold. It's a no brainer.

If WooCommerce does not want to implement this as a default trigger event, then can someone [@WooCommerce] please provide some code we can add to trigger on process_to_hold??

**Comment by Dustie** [comment] 2021-09-24 18:05
This is still not fixed in 5.7.1!

**Comment by peterfabian** [comment] 2021-10-15 11:16
What status is the order in before you change it to on hold, please? It seems we have triggers for 
- pending -> on hold
- failed -> on hold
- cancelled -> on hold

so these should work. If they don't please let us know. If you want to add other emails, that's a new feature request, I'm afraid, and would require more interest from users.

**Comment by jvwrx** [comment] 2021-10-15 19:56
@peterfabian Ahhh, didn't realize the email only triggered for _Pending/Failed/Cancelled -> On Hold_.

It feels like the _Settings > Emails Order on-hold_ tooltip could be more clear, as it currently says:
> _This is an order notification sent to customers containing order details after an order is placed on-hold._

There seems to be precedent as the tooltip for Cancelled Order is more specific in that way:
> _Cancelled order emails are sent to chosen recipient(s) when orders have been marked cancelled (if they were previously processing or on-hold)._

I'll be submitting a feature request, though, for _Completed -> On Hold_, which is my needed case. Thanks for chiming in!

**Comment by jvwrx** [comment] 2021-10-15 21:21
If this helps others needing a _Completed -> On Hold_ email triggered, I found https://wpmudev.com/forums/topic/woocommerce-need-on-hold-email-notidfication-when-status-changes/#post-3591084 which is working for me.

```
add_filter( 'woocommerce_email_actions', 'add_another_email_action' );
function add_another_email_action( $array ) {
  $array[]='woocommerce_order_status_completed_to_on-hold';
  return $array;
}

add_action( 'woocommerce_email', 'hook_another_email_on_hold' );
function hook_another_email_on_hold( $email_class ) {
  add_action( 'woocommerce_order_status_completed_to_on-hold_notification', array( $email_class->emails['WC_Email_Customer_On_Hold_Order'], 'trigger' ) );
}
```

I believe you'd change both references of `completed` above to the **email ID slug** you want (I can't seem to find where these are listed but I'm seeing them at https://stackoverflow.com/a/47742782/2157742)

**Comment by amigoow** [comment] 2023-02-06 10:34
This works for me:
```
add_action( 'woocommerce_order_status_processing_to_on-hold', 'enable_processing_to_on_hold_notification', 10, 2 );
function enable_processing_to_on_hold_notification( $order_id, $order ){
    // Getting all WC_emails array objects
    $mailer = WC()->mailer()->get_emails();

    // Send the "On Hold" notification
    $mailer['WC_Email_Customer_On_Hold_Order']->trigger( $order_id );
}
```

Thanks to [LoicTheAztek on Stackoverflow](https://stackoverflow.com/questions/54746567/make-on-hold-order-status-notification-working-in-woocommerce/54747109#54747109)
