### ISSUE TITLE
Geolocation: Page reloads the first time you land on a site

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#29873] opened 2021-05-10 18:11 UTC
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When `Default customer location` is set to `Geolocate (With page caching support)` and the visitor lands on any page containing the correct `v=` parameter, the page reloads.

**Expected behavior**
The page should only reload if the `v=` parameter is missing or is incorrect

**Actual behavior**
The page reloads the **first** time a visitor lands on the site, regardless of the value of the `v=` parameter
This happens on both Chrome and Firefox (latest versions). It also consistently happens on remote servers and can even be seen on the waterfall of the likes of gtmetrix.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Ensure `Default customer location` is set to `Geolocate (With page caching support)`
2. On any browser window, load a page (such as /shop)
3. Copy the entire URL, including the `v=` parameter
4. Start an incognito window
5. Press F12, go to `Network` and ensure `Preserve log` is ticked.
6. Paste the URL you copied before and press enter
7. Keep an eye on the document/html requests.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Possible cause**
On https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L88-L89 there's no check if the current `v=` matches the hash, and is always replaced.

**Possible solutions**
1. On https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L89 check if the `hash` is the same as the `v=`
2. On https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L96 check if `this_page` is identical to `window.location.toString()` and if so, don't set it again and don't trigger a reload.

**Related**
https://github.com/woocommerce/woocommerce/pull/29182
https://github.com/woocommerce/woocommerce/issues/26973

**Comment by zhongruige** [comment] 2021-05-18 19:47
Hi @glagonikas,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment] 2021-06-11 14:46
Hi @glagonikas,

Thanks for the report. I was able to recreate this issue, and I'm marking it as a bug. Thanks for the report along with the detailed steps to resolve the issue. If you'd like to submit a PR for the issue, we would be happy to review it.

**Comment by mattyhockey** [comment] 2021-07-16 02:10
Does anyone know what could be causing this? I can't seem to figure out what could be causing this. I have a duplicate of this site that is not behaving this way, all server settings are the same. Host support can't figure it out either unfortunately.

**Comment by glagonikas** [comment] 2021-07-16 09:09
@mattyhockey based on our findings, this is caused by the code found on https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L88-L89 where there's no check if the current v= matches the hash, and is always replaced, causing the page to reload.

This is caused by the code (not the server) and only happens the first time someone lands on the site and only if you have enabled the option of `Geolocate (With page caching support)`. Any other options on that drop-down do not cause this issue.

I'm not too sure what you're saying in your comment? Are you saying you've got one site that reloads and a duplicate site that doesn't reload?

**Comment by mattyhockey** [comment] 2021-07-16 15:12
> @mattyhockey based on our findings, this is caused by the code found on https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L88-L89 where there's no check if the current v= matches the hash, and is always replaced, causing the page to reload.
> 
> This is caused by the code (not the server) and only happens the first time someone lands on the site and only if you have enabled the option of `Geolocate (With page caching support)`. Any other options on that drop-down do not cause this issue.
> 
> I'm not too sure what you're saying in your comment? Are you saying you've got one site that reloads and a duplicate site that doesn't reload?

Thank you for pointing me in the right direction. Replaced geolocation.js with the geolocation.js from the original site and it seems to be working now. Really appreciate the help!

**Comment by glagonikas** [comment] 2021-07-16 15:26
@mattyhockey so you no longer experience this issue after replacing your geolocation.js? Can upload it here?

**Comment by mattyhockey** [comment] 2021-07-16 15:39
This worked for me

`/*global wc_geolocation_params */
jQuery( function( $ ) {

	var this_page = window.location.toString();

	var $append_hashes = function() {
		if ( wc_geolocation_params.hash ) {
			$( 'a[href^="' + wc_geolocation_params.home_url + '"]:not(a[href*="v="]), a[href^="/"]:not(a[href*="v="])' ).each( function() {
				var $this      = $( this ),
					href       = $this.attr( 'href' ),
					href_parts = href.split( '#' );

				href = href_parts[0];

				if ( href.indexOf( '?' ) > 0 ) {
					href = href + '&v=' + wc_geolocation_params.hash;
				} else {
					href = href + '?v=' + wc_geolocation_params.hash;
				}

				if ( typeof href_parts[1] !== 'undefined' && href_parts[1] !== null ) {
					href = href + '#' + href_parts[1];
				}

				$this.attr( 'href', href );
			});
		}
	};

	var $geolocation_redirect = function( hash ) {
		if ( this_page.indexOf( '?v=' ) > 0 || this_page.indexOf( '&v=' ) > 0 ) {
			this_page = this_page.replace( /v=[^&]+/, 'v=' + hash );
		} else if ( this_page.indexOf( '?' ) > 0 ) {
			this_page = this_page + '&v=' + hash;
		} else {
			this_page = this_page + '?v=' + hash;
		}

		window.location = this_page;
	};

	var $geolocate_customer = {
		url: wc_geolocation_params.wc_ajax_url.toString().replace( '%%endpoint%%', 'get_customer_location' ),
		type: 'GET',
		success: function( response ) {
			if ( response.success && response.data.hash && response.data.hash !== wc_geolocation_params.hash ) {
				$geolocation_redirect( response.data.hash );
			}
		}
	};

	if ( '1' === wc_geolocation_params.is_available ) {
		$.ajax( $geolocate_customer );

		// Support form elements
		$( 'form' ).each( function() {
			var $this  = $( this );
			var method = $this.attr( 'method' );
			var hasField = $this.find('input[name="v"]').length > 0;

			if ( method && 'get' === method.toLowerCase() && !hasField ) {
				$this.append( '<input type="hidden" name="v" value="' + wc_geolocation_params.hash + '" />' );
			} else {
				var href = $this.attr( 'action' );
				if ( href ) {
					if ( href.indexOf( '?' ) > 0 ) {
						$this.attr( 'action', href + '&v=' + wc_geolocation_params.hash );
					} else {
						$this.attr( 'action', href + '?v=' + wc_geolocation_params.hash );
					}
				}
			}
		});

		// Append hashes on load
		$append_hashes();
	}

	$( document.body ).on( 'added_to_cart', function() {
		$append_hashes();
	});
	
	// Enable user to trigger manual append hashes on AJAX operations
	$( document.body ).on( 'woocommerce_append_geo_hashes', function() {
		$append_hashes();
	});

});`

**Comment by glagonikas** [comment] 2021-07-16 15:44
```
if ( this_page.indexOf( '?v=' ) > 0 || this_page.indexOf( '&v=' ) > 0 ) {
		this_page = this_page.replace( /v=[^&]+/, 'v=' + hash );
```
This is still there so I don't know why your JS wouldn't reload the page? Have you got `Geolocate (With page caching support)` enabled on your site? Are you on the latest version on both sites?

**Comment by mattyhockey** [comment] 2021-07-26 15:50
> ```
> if ( this_page.indexOf( '?v=' ) > 0 || this_page.indexOf( '&v=' ) > 0 ) {
> 		this_page = this_page.replace( /v=[^&]+/, 'v=' + hash );
> ```
> 
> This is still there so I don't know why your JS wouldn't reload the page? Have you got `Geolocate (With page caching support)` enabled on your site? Are you on the latest version on both sites?

The issue ended up just being some kind of issue with the minified geolocation.js file. Deleting the minified file makes it behave properly. Hope this can help someone else.

**Comment by mattyhockey** [comment] 2021-07-31 13:43
> ```
> if ( this_page.indexOf( '?v=' ) > 0 || this_page.indexOf( '&v=' ) > 0 ) {
> 		this_page = this_page.replace( /v=[^&]+/, 'v=' + hash );
> ```
> 
> This is still there so I don't know why your JS wouldn't reload the page? Have you got `Geolocate (With page caching support)` enabled on your site? Are you on the latest version on both sites?

I hope you don't mind me asking another question here about this. I am having a strange issue with Geolocate that I can't seem to find an answer to anywhere online.

With geolocate (with cache support) enabled, the redirect is stripping UTM parameters from the URL. Is this the correct behaviour for geolocate with cache support? Is there a way to preserve UTM parameters when ?v= is added to the URL?

Thanks!

**Comment by glagonikas** [comment] 2021-07-31 14:18
> I hope you don't mind me asking another question here about this. I am having a strange issue with Geolocate that I can't seem to find an answer to anywhere online.
> 
> With geolocate (with cache support) enabled, the redirect is stripping UTM parameters from the URL. Is this the correct behaviour for geolocate with cache support? Is there a way to preserve UTM parameters when ?v= is added to the URL?
> 
> Thanks!

UTM parameters work fine for us when `Geolocate (With page caching support)` is enabled. This is regardless of where we position them (test.com/?utm or test.com?utm).

Also, the fact your JS behaves differently, makes me wonder if you have any customisations or are running a different version of WC, which could also explain your UTM issues.

I'd suggest that you investigate this further and open a new issue if this doesn't work as intended when all other plugins are disabled and the latest version of WC is used.

**Comment by namiokuzono** [comment] 2023-08-05 17:47
Reported - 6622710-zd-a8c

**Comment by neilmccreadie** [comment] 2023-08-16 10:23
Reported: 6674054-zen

**Closed** 2023-08-25 21:41 UTC
Labels: type: bug, type: good first issue, priority: low, plugin: woocommerce
