### ISSUE TITLE
Report & Jetpack not showing yesterday's orders

### ISSUE THREAD

**Issue by PaulCyberEngel** [woocommerce/woocommerce#26683] opened 2020-06-03 15:09 UTC
**Describe the bug**
I just started using WooCommerce, and made my first sale yesterday, but have not completed fulfillment. When I look at the WooCommerce Dashboard, it shows my sale. But when I look at the Jetpack dashboard it says I have zero sales this month. When I clicked the widget it took me to WooCommerce Reports, which also shows zero sales.

**To Reproduce**
View JetPack wizard or WooCommerce Reports.

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by juliaamosova** [comment] 2020-06-03 17:28
Hi @PaulCyberEngel,

Thanks for raising the issue. However, it will be very helpful if you could provide some screenshots showing where things don't work. It is not clear to me what Jetpack wizard is or what widget did you click on to get to WooCommerce Reports?

Also, you mentioned you are using WooCommerce Dashboard but also WooCommerce Reports - it would be great to clarify:

![reports](https://user-images.githubusercontent.com/19143190/83668479-05444f00-a59e-11ea-9645-37ad3d6ec9ef.jpg)

**Comment by PaulCyberEngel** [comment] 2020-06-03 20:03
The WooCommerce widget for JetPack does not show the sale:

As I said, the WooCommerce Dashboard shows the sale, but the WiiCommerce Reports does not.
![Screen Shot 2020-06-03 at 12 33 01 PM](https://user-images.githubusercontent.com/8237744/83683576-3d05c380-a5ab-11ea-9baf-fff829c4d430.png)
<img width="2051" alt="Screen Shot 2020-06-03 at 12 33 25 PM" src="https://user-images.githubusercontent.com/8237744/83682292-5d348300-a5a9-11ea-838a-8397d30e97a8.png">
<img width="2051" alt="Screen Shot 2020-06-03 at 12 33 40 PM" src="https://user-images.githubusercontent.com/8237744/83682311-66255480-a5a9-11ea-8f2f-7747d46c805d.png">




And the JetPack widget also does not show the sale.

**Comment by PaulCyberEngel** [comment] 2020-06-03 20:03
Closed by accident.

**Comment by tammullen** [comment] 2021-03-24 19:42
Hi @PaulCyberEngel 

Apologies for the delayed reply.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case; 
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-24 19:42 UTC
Labels: has feedback
