### ISSUE TITLE
Shipping taxes incorrectly calculated after order is placed, rounded.

### ISSUE THREAD

**Issue by AKSUTAH** [woocommerce/woocommerce#19792] opened 2018-04-19 16:51 UTC
I just experienced a similar issue that is pretty serious.... https://github.com/woocommerce/woocommerce/issues/17779

An order was placed and the order confirmation was sent to the customer for the amount of $120.17.
The order was authorized for that amount, $120.17...
When I tried to capture, it was rejected because the amount I was trying to capture was more than authorized.
I looked at the order and noticed that the total was now $120.18...
No changes had been made to the order. Upon further inspection, I see that a state tax item of 3.808 was rounded to the amount of 3.81.
How this occurred after the fact is the real problem.

**Comment by mikejolley** [comment] 2018-04-19 17:07
Are we supposed to guess your setup? Please follow the new issue template.

**Comment by mikejolley** [comment] 2018-04-20 10:31
As I said, we won't be able to offer advice without more details. 

> I looked at the order and noticed that the total was now $120.18...

The total is a fixed amount rounded *before* it's saved/sent to gateways. Perhaps the gateway is getting a value from elsewhere or calculating it itself?

> I see that a state tax item of 3.808 was rounded to the amount of 3.81.

Thats correct to round up. The order total would have done this during calculation.

Closing as the issue lacks details + steps to reproduce. Thanks

**Closed by mikejolley** 2018-04-20 10:31 UTC

**Comment by asolutions** [comment] 2018-04-23 20:11
I believe I'm experiencing the same issue, and can reproduce this?

Example:
Product quantity 9, ($25.25 ea.) shipping to New York, taxable. Zip Code11232, tax rate is 8.875%. 

9 products total cost $227.25. Tax is $20.168 ($20.17)
Shipping costs $20.46. Tax is $1.815 ($1.82)
$227.25 + $20.17 + $20.46 + $1.82 = $269.70.
Customer sees $269.69 on checkout. On the backend when we updated and recalculate the order, total shows $269.70.

**Comment by AKSUTAH** [comment] 2018-04-23 20:15
Yeah, this was closed after less than 24 hours. I need time to get the details to satisfy the requirements for additional info and steps to reproduce.

**Comment by asolutions** [comment] 2018-04-23 20:38
It looks like, (per my settings) that the tax is rounding at the subtotal level on the frontend, but on the backend, it's doing it by line item? I can get $269.69 by doing the calculation on the subtotal level, i.e. 1.815+20.168=21,983 (21.98) + 227.25 + 20.46 = $269.69

But again, the issue seems to be that the frontend and backend do not match.

**Comment by AKSUTAH** [comment] 2018-04-24 15:09
That's the same thing I saw... @mikejolley , I will submit new issue with details on this problem.

**Comment by mikejolley** [comment] 2018-04-24 15:20
@AKSUTAH Just reply here? 

As I said, the total store is what is sent to gateways.

I also recommend not toggling on the option to round at subtotal level; it's problematic and not checked by default.
