### ISSUE TITLE
Use pagination in product page

### ISSUE THREAD

**Issue by MattTrovao** [woocommerce/woocommerce#25657] opened 2020-02-13 12:30 UTC
Hello there, I am trying make a pagination in my product page, I try a few documments saying who to make, even the one here ( [this one ](https://github.com/woocommerce/woocommerce/blob/master/templates/loop/pagination.php )).

Any tips of who I can make it work?

**Comment by tammullen** [comment] 2020-02-19 01:09
Hi @MattTrovao 


While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-02-19 01:09 UTC
