### ISSUE TITLE
Brand api problem

### ISSUE THREAD

**Issue by alirezat66** [woocommerce/woocommerce#29069] opened 2021-02-09 10:04 UTC
**Issue Description: the issue is most of woocomerce websites has brands like categories while the woocommerce api didnt support brands. what we do?**

**Comment by tammullen** [comment] 2021-02-11 17:27
Hi @alirezat66 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

Please also look at our Rest API Documentation https://woocommerce.github.io/woocommerce-rest-api-docs/#product-categories
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-02-11 17:27 UTC
