### ISSUE TITLE
Blanks are shown instead of category names

### ISSUE THREAD

**Issue by fesarlis** [woocommerce/woocommerce#24322] opened 2019-08-05 07:52 UTC
Hello.
Out of the blue Woocommerce started showing blanks instead of categories names. This applies only to the checkboxes (either in quick or normal edit). In the product list or category list they are shown. Latest WC, WPML, updated themes/plugins. Tried to disable everything except WC, switched to default WP theme. Issue persists.

Please see attached screenshot.
![Image1](https://user-images.githubusercontent.com/7560228/62447871-0682d080-b76f-11e9-8857-9353a7eea61a.jpg)

**Comment by rodrigoprimo** [comment] 2019-08-05 19:11
Hi there!

Closing this issue as there is not enough information to try to reproduce it and this is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If you believe your problem is caused by a WooCommerce bug, please open another issue following the bug report template (https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and provide clear steps on how to reproduce the problem.

**Closed by rodrigoprimo** 2019-08-05 19:11 UTC
