### ISSUE TITLE
Widgets filter by price dont show on site

### ISSUE THREAD

**Issue by iry0502** [woocommerce/woocommerce#25779] opened 2020-02-27 19:18 UTC
Pls I need help,
I am working on site on localhost, with woocomerce plugin. I adding widgets on sidebar on shop page and everithing was fine till one moment “sort by price” widgets wasnt seen anymore. I didnt do nothing, yes, I’ve been posting and removing multiple times, tried to look how it works nad just in one moment its gone. In WP widgets is there, but when I go to the shop page in side bar it wasnt there. Another widgets is there.
What happend? Pls help? What should I do! Thanks!

**Comment by juliaamosova** [comment] 2020-02-27 19:36
Hi @iry0502,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-02-27 19:36 UTC
