### ISSUE TITLE
Staus Page produces 500 error

### ISSUE THREAD

**Issue by streamworksaudio** [woocommerce/woocommerce#25987] opened 2020-03-21 02:12 UTC
This seems like an odd bug to get through to the release, however whenever I go the WooCommerce Admin Status page I am always getting a 500 error.  The page still loads but Chrome developer shows the error response.

I first noticed this because my own custom plugin uses Jquery in the admin and it wasn't firing correctly.  I have tried to disable every plugin and even with just WordPress and WooCommerce 4.01 installed, I am still getting the error.

<img width="743" alt="Screen Shot 2020-03-21 at 11 11 36 AM" src="https://user-images.githubusercontent.com/20709333/77217308-c12bdb80-6b64-11ea-8530-8b683fc6444a.png">

I am also still seeing a lot of errors in the logs related to the Action Scheduler but that is another topic ;-)

Cheers

**Comment by streamworksaudio** [comment] 2020-03-21 03:46
Perhaps the action scheduler issue were an problem.

I deleted all the wp_actionscheduler_ tables from the database, then WooCommerce re-created them and both the action scheduler problems I was seeing as well as this 500 error were resolved.

**Comment by LamLamLLC** [comment] 2020-03-22 15:58
🅰️

**Comment by juliaamosova** [comment] 2020-03-23 14:39
Hi @streamworksaudio, sorry for the trouble and thanks for reporting! @rrennick would you please take a look at this issue here?

**Comment by rrennick** [comment] 2020-03-24 12:56
@juliaamosova Without the DB tables, settings, etc. trying to reproduce this would likely be a needle in a haystack.

**Comment by streamworksaudio** [comment] 2020-03-28 03:35
@rrennick sorry I should have noted that originally.  I have been away since posting this.  I cannot recall as to why during my testing made me think that there could be an issue with the database tables, however after deleting the following tables and allowing WooCommerce to recreate them the errors I was getting with the action scheduler went away.

wp_actionscheduler_actions
wp_actionscheduler_claims
wp_actionscheduler_groups
wp_actionscheduler_logs

This also fixed other issues as well, as listed at https://github.com/woocommerce/action-scheduler/issues/486#issuecomment-601984400

Cheers

**Comment by rrennick** [comment] 2020-03-30 12:30
@streamworksaudio Thanks for the follow up.

**Comment by juliaamosova** [comment] 2020-03-30 13:38
Thanks for your follow-up @streamworksaudio. Looks like you are all set for now so I am going to close the issue. Let us know if we missed anything via comment and we'd take a 2nd look.

**Closed by juliaamosova** 2020-03-30 13:38 UTC
Labels: question
