### ISSUE TITLE
woocommerce payment cannot be processed (amount must be numeric.amount no longer than ten characters)

### ISSUE THREAD

**Issue by Scott-Rogers2020** [woocommerce/woocommerce#26204] opened 2020-04-17 00:24 UTC
We have encountered a very strange error when trying to check out " woo-commerce payment cannot be processed (amount must be numeric.amount no longer than ten characters)"

the strange thing it has only occurred for a particular set of products to date. To troubleshoot we took one product out of the cart and the checkout went through without error. 

We assumed that the error must have been caused by the products that we removed, so tried to check out with the individual products and it went through fine. If we add the same products back into the original order that failed with the above error, we again get the same error.

We have gone through and checked all product price amounts and even entered them again to ensure they are correct.

Can anyone shed light on what this error is about? We have updated price and issues remains, so are stumped.
`
### WordPress Environment ###

WordPress address (URL): https://twppalmbeach.com.au
Site address (URL): https://twppalmbeach.com.au
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ❌ Inactive 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 40 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.47-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wo_
Total Database Size: 35.14MB
Database Data Size: 30.62MB
Database Index Size: 4.52MB
wo_woocommerce_sessions: Data: 14.28MB + Index: 0.44MB + Engine MyISAM
wo_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_order_items: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wo_woocommerce_order_itemmeta: Data: 0.36MB + Index: 0.26MB + Engine MyISAM
wo_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wo_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wo_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wo_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wo_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wo_aws_cache: Data: 1.76MB + Index: 0.00MB + Engine MyISAM
wo_aws_index: Data: 2.06MB + Index: 0.00MB + Engine MyISAM
wo_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wo_comments: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
wo_crellyslider_elements: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_crellyslider_nonces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wo_crellyslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_crellyslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_options: Data: 1.11MB + Index: 0.14MB + Engine MyISAM
wo_pmxe_exports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wo_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wo_pmxe_posts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wo_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wo_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wo_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wo_pmxi_images: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wo_pmxi_imports: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wo_pmxi_posts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wo_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wo_postmeta: Data: 5.00MB + Index: 1.89MB + Engine MyISAM
wo_posts: Data: 4.01MB + Index: 0.37MB + Engine MyISAM
wo_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wo_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wo_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wo_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wo_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wo_sbi_instagram_posts: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
wo_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wo_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wo_term_relationships: Data: 0.05MB + Index: 0.12MB + Engine MyISAM
wo_term_taxonomy: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wo_usermeta: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
wo_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wo_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wo_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wo_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wo_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wo_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wo_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wo_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wo_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wo_wc_product_meta_lookup: Data: 0.14MB + Index: 0.30MB + Engine InnoDB
wo_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wo_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wo_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wo_wprm_ratings: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wo_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wo_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 22
acf-field-group: 6
attachment: 1280
customize_changeset: 18
custom_css: 1
is_search_form: 1
nav_menu_item: 17
oembed_cache: 1
page: 19
post: 3
product: 800
product_variation: 252
revision: 811
shop_coupon: 1
shop_order: 74
shop_order_refund: 1
store: 1
wccs_showcase: 1
wcps: 1
wc_category_slider: 1
wc_pickup_location: 1
woo_discount: 1
woo_discount_cart: 1
wpl_wcslider: 1
wprm_recipe: 1
ywar_reviews: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Extension Works Framework: by Extension Works – 2.1.15
WooCommerce FastWay(AU): by Extension Works – 1.6.17
Advanced Custom Fields PRO: by Elliot Condon – 5.8.4
Advanced Woo Search: by ILLID – 1.98
Blog Designer: by Solwin Infotech – 2.1
Classic Editor: by WordPress Contributors – 1.5
Crelly Slider: by Fabio Rinaldi – 1.3.6
Disable Dashboard for WooCommerce: by ospiotr – 1.0.1
Duplicate Post: by Enrico Battocchi – 3.2.4
Facebook for WooCommerce: by Facebook – 1.10.2
Smash Balloon Instagram Feed: by Smash Balloon – 2.3.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.0
Post Types Order: by Nsp Code – 1.9.4.3
Qty Increment Buttons for WooCommerce: by taisho – 2.7.1
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.3.1

Redirection: by John Godley – 4.7.1
TinyMCE Advanced: by Andrew Ozz – 5.4.0
WC Pickup Store: by Keylor Mendoza A. – 1.5.23
WooCom SecurePay Payment Gateway: by Hem Thapa – 1.3 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.7.5
WooCommerce: by Automattic – 4.0.1
Yoast SEO: by Team Yoast – 13.4.1
WP All Export: by Soflyy – 1.2.5
WP All Import: by Soflyy – 3.5.2
WP Fastest Cache: by Emre Vona – 0.9.0.5
WP Migrate DB: by Delicious Brains – 1.0.13
WPB Product Categories Slider for WooCommerce: by wpbean – 1.1.8

### Inactive Plugins (4) ###

Autoptimize: by Frank Goossens (futtta) – 2.6.2
WooCommerce Local Pickup Plus: by SkyVerge – 2.7.5
WP All Import - WooCommerce Add-On: by Soflyy – 1.4.4
WP Recipe Maker: by Bootstrapped Ventures – 5.11.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #105 - /shop/
Cart: #106 - /cart/
Checkout: #107 - /checkout/
My account: #108 - /my-account/
Terms and conditions: #414 - /returns-refunds/

### Theme ###

Name: wrayorganic Theme
Version: 2.0
Author URL: http://sapian.co.in
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: wrayorganic-theme/woocommerce/emails/customer-completed-order.php version 3.5.0 is out of date. The core version is 3.7.0
wrayorganic-theme/woocommerce/emails/customer-processing-order.php version 3.5.4 is out of date. The core version is 3.7.0
wrayorganic-theme/woocommerce/emails/plain/customer-completed-order.php version 3.5.0 is out of date. The core version is 3.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 57
Oldest: 2020-03-18 23:01:15 +0000
Newest: 2020-04-16 13:01:14 +0000

Pending: 1
Oldest: 2020-04-17 13:00:00 +0000
Newest: 2020-04-17 13:00:00 +0000

`

**Comment by juliaamosova** [comment] 2020-04-20 22:38
Hi @Scott-Rogers2020,

Thanks for reporting the issue. It is not clear what payment gateway are you using? 

I also see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-04-28 18:40
Hi @Scott-Rogers2020,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-04-28 18:40 UTC
Labels: status: needs feedback
