### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by sagar199518** [woocommerce/woocommerce#28478] opened 2020-12-03 09:50 UTC
I am unable to create a webhhok.
receving error - woocommerce_rest_cannot_create

**Comment by juliaamosova** [comment] 2020-12-04 17:29
Hi @sagar199518,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. It will be great to know what type of webhook you are trying to create and what is your environment (WooCommerce, WordPress versions, etc).  

Please provide us with the information requested so we could take a look further.

**Comment by sagar199518** [comment] 2020-12-08 05:08
I am trying to create product webhook using woo commerce environment

**Comment by tammullen** [comment] 2021-03-25 21:41
Hi @sagar199518 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-25 21:41 UTC
Labels: has feedback
