### ISSUE TITLE
Some variable products disappeared suddenly!

### ISSUE THREAD

**Issue by BBCBB** [woocommerce/woocommerce#29130] opened 2021-02-15 06:30 UTC
Hello,
I noticed some products vanishing from the back end, so had an export of products and saw the variations exist yet, but the variables don't exist. In the search box of the products, no one of the products, neither variable nor variation is available. I think the variable exists in the database but something doesn't work properly. it would be appreciated if you could help me with this issue.

**Comment by zhongruige** [comment] 2021-02-17 22:22
Hi @BBCBB,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by zhongruige** 2021-02-17 22:22 UTC
