### ISSUE TITLE
My account page is not responding 

### ISSUE THREAD

**Issue by shubhamshashank** [woocommerce/woocommerce#26789] opened 2020-06-17 09:22 UTC
**Describe the bug**
The forms to register the user on the my account page get shrinked after the installation.

**To Reproduce**
1. Go to 'My account'
2. Click on '.Register or login.'
3. Scroll down to 'Any of the forms'

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by tammullen** [comment] 2020-06-17 12:40
Hi @shubhamshashank 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 
​
![Screenshot 2020-06-17 at 13 38 41](https://user-images.githubusercontent.com/24649833/84898965-f41c3780-b09f-11ea-9160-a03a6b387cf0.png)

​
Please provide us with more details about the issue which may help us to evaluate it further. 
​
Please let us know what setting you are using for accounts in:
WooCommerce / Settings / Accounts & Privacy
![Screenshot 2020-06-17 at 13 37 09](https://user-images.githubusercontent.com/24649833/84899047-101fd900-b0a0-11ea-8721-299b7a3e0e31.png)

Also please fill out the other details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Comment by shubhamshashank** [comment] 2020-06-17 12:46
I'm using the Astra theme, I guess there's a problem with the theme

**Comment by tammullen** [comment] 2020-06-18 14:51
Hi @shubhamshashank,

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-06-25 20:19
Hi @shubhamshashank,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-06-25 20:19 UTC
Labels: can't reproduce, status: needs feedback
