### ISSUE TITLE
When clicking 'save changes' on variable product, it just gets stuck

### ISSUE THREAD

**Issue by MorneHumanoid** [woocommerce/woocommerce#19538] opened 2018-03-27 07:51 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set up variable product, set up custom product attribute
2. Setup 3 option for custom product attribute
3. In variations tab, add a variation and assign value and click save changes, this is where it just gets stuck with the spinning ball.

![screen shot 2018-03-27 at 9 41 39 am](https://user-images.githubusercontent.com/37828944/37953716-fd7e34c2-31a3-11e8-8865-05954fcfa859.png)

## Expected/actual behavior

When I follow those steps, I see...
The screenshot attached above
I was expecting to see...
the ability to insert the next variable state
## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://twyne.co.za/rachelskitchen
Site URL: http://twyne.co.za/rachelskitchen
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.34
PHP Post Max Size: 32 MB
PHP Time Limit: 3000
PHP Max Input Vars: 10000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wpq9_
MaxMind GeoIP Database: ✔
Total Database Size: 7.68MB
Database Data Size: 7.10MB
Database Index Size: 0.58MB
wpq9_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wpq9_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpq9_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpq9_categorymeta: Data: 0.00MB + Index: 0.00MB
wpq9_commentmeta: Data: 0.00MB + Index: 0.00MB
wpq9_comments: Data: 0.04MB + Index: 0.02MB
wpq9_dopbsp_api_keys: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_availability: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_availability_no: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_availability_price: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_calendars: Data: 0.00MB + Index: 0.01MB
wpq9_dopbsp_coupons: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_days: Data: 0.00MB + Index: 0.01MB
wpq9_dopbsp_discounts: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_discounts_items: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_discounts_items_rules: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_emails: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_emails_translation: Data: 0.00MB + Index: 0.01MB
wpq9_dopbsp_extras: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_extras_groups: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_extras_groups_items: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_fees: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_forms: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_forms_fields: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_forms_select_options: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_languages: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_locations: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_models: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_reservations: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_rules: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_searches: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_settings: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_settings_calendar: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_settings_notifications: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_settings_payment: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_settings_search: Data: 0.00MB + Index: 0.00MB
wpq9_dopbsp_translation_en: Data: 0.22MB + Index: 0.09MB
wpq9_dopbsp_woocommerce: Data: 0.00MB + Index: 0.00MB
wpq9_links: Data: 0.00MB + Index: 0.00MB
wpq9_member_catmeta: Data: 0.00MB + Index: 0.00MB
wpq9_options: Data: 1.47MB + Index: 0.05MB
wpq9_portfolio_catmeta: Data: 0.00MB + Index: 0.00MB
wpq9_postmeta: Data: 1.24MB + Index: 0.16MB
wpq9_posts: Data: 3.74MB + Index: 0.10MB
wpq9_product_catmeta: Data: 0.00MB + Index: 0.00MB
wpq9_revslider_css: Data: 0.09MB + Index: 0.00MB
wpq9_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wpq9_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wpq9_revslider_sliders: Data: 0.01MB + Index: 0.00MB
wpq9_revslider_slides: Data: 0.05MB + Index: 0.00MB
wpq9_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wpq9_sg_fblike_popup: Data: 0.02MB + Index: 0.00MB
wpq9_sg_html_popup: Data: 0.02MB + Index: 0.00MB
wpq9_sg_image_popup: Data: 0.02MB + Index: 0.00MB
wpq9_sg_popup: Data: 0.02MB + Index: 0.00MB
wpq9_sg_popup_addons: Data: 0.02MB + Index: 0.02MB
wpq9_sg_popup_addons_connection: Data: 0.02MB + Index: 0.00MB
wpq9_sg_popup_settings: Data: 0.02MB + Index: 0.00MB
wpq9_sg_shortCode_popup: Data: 0.02MB + Index: 0.00MB
wpq9_termmeta: Data: 0.00MB + Index: 0.01MB
wpq9_terms: Data: 0.01MB + Index: 0.02MB
wpq9_term_relationships: Data: 0.01MB + Index: 0.03MB
wpq9_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wpq9_toolset_post_guid_id: Data: 0.00MB + Index: 0.00MB
wpq9_usermeta: Data: 0.01MB + Index: 0.01MB
wpq9_users: Data: 0.00MB + Index: 0.01MB
wpq9_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpq9_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpq9_wptripadvisor_post_templates: Data: 0.00MB + Index: 0.00MB
wpq9_wptripadvisor_reviews: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_campaign: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_custom_field: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_email: Data: 0.03MB + Index: 0.00MB
wpq9_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_form: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_list: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_queue: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_subscriber_ips: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_url: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_url_mail: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_user: Data: 0.00MB + Index: 0.01MB
wpq9_wysija_user_field: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_user_history: Data: 0.00MB + Index: 0.00MB
wpq9_wysija_user_list: Data: 0.00MB + Index: 0.00MB
wpq9_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wpq9_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 253
block: 8
dd_layouts: 2
faq: 13
mc4wp-form: 2
member: 3
nav_menu_item: 9
page: 23
popup: 1
popup_theme: 6
post: 83
product: 6
product_variation: 2
revision: 436
view: 3
view-template: 4
wp-types-group: 1
wpcf7_contact_form: 3
wysijap: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (29) ###

Contact Form 7: by Takayuki Miyoshi – 5.0.1
Toolset CRED Commerce: by OnTheGoSystems – 1.6.1
Toolset CRED: by OnTheGoSystems – 1.9.5
Duplicate Page: by mndpsingh287 – 2.6
Dynamic Featured Image: by Ankit Pokhrel – 3.6.5
Envato WordPress Toolkit: by Envato – 1.7.3
Insert Pages: by Paul Ryan – 3.3.0
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
MailChimp for WordPress: by ibericode – 4.2
Popup Maker: by WP Popup Maker – 1.7.0
Porto Theme - Functionality: by SW-THEMES – 1.0.5
WooCommerce Pay Your Price: by Fantastic Plugins – 7.7 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Toolset Module Manager: by OnTheGoSystems – 1.6.9
RSS Reviews: by Gregory Pearcey – 1.1
Toolset Access: by OnTheGoSystems – 2.4.3.5
Toolset Types: by OnTheGoSystems – 2.2.22
Cookie Consent: by Catapult_Themes – 2.3.9
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.5
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.2
Toolset WooCommerce Views: by OnTheGoSystems – 2.7.6 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.4
WordPress Importer: by wordpressdotorg – 0.6.3
WP Sitemap Page: by Tony Archambeau – 1.6.1
WP TripAdvisor Review Slider: by LJ Apps – 2.7
Toolset Views: by OnTheGoSystems – 2.5.2
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.5.0
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.5
YITH WooCommerce Wishlist: by YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #344 - /public-classes/
Cart: #345 - /cart/
Checkout: #346 - /checkout/
My account: #347 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: http://newsmartwave.net/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 4.2
Parent Theme Author URL: http://www.newsmartwave.net/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/content-product.php
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/external.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/share.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

`
```
</details>

**Comment by claudiulodro** [comment] 2018-03-27 18:40
Most likely the ajax request that updated that is breaking or failing in some way. It's impossible to tell specifically what error is happening from the information here, and the problem could be caused by one of your other active plugins.

> [x ] This bug happens with only WooCommerce plugin active
> [x ] This bug happens with a default WordPress theme active, or Storefront

I see a bunch of active plugins and the Porto theme in your system status report. Have you tried these steps? They are an important part of troubleshooting the issue.

There are further steps you can try to debug the problem [in this issue](https://github.com/woocommerce/woocommerce/issues/19471#issuecomment-375634699). For now I'm closing this as non-reproducible since it doesn't appear to be a problem in the WooCommerce core plugin. Let me know if you find out any more information after trying these steps and I can take another look if needed.

**Closed by claudiulodro** 2018-03-27 18:40 UTC
