### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate, webhooks

### ISSUE THREAD

**Issue by edvinassss98** [woocommerce/woocommerce#29490] opened 2021-03-25 10:06 UTC
Hello, i have a question about webhooks. For some reason i can't manage to send webhooks to my website. At the start it was because it was because i was running server on locally and by changing my WooCommerce plugin code using this [https://stackoverflow.com/questions/31875442/woocommerce-webhook-invalid-url](url) i don't mind doing that when i am running server locally, but i have a problem that when i pushed my code to test webhooks on released website which has host i was getting error which you can see in the photo. Also  my website has certificates and wordpress where wooCommerce plugin is installed doesn't could that be an issue? At the same time webhook were working perfectly with webhook.site

![image](https://user-images.githubusercontent.com/48483794/112454555-7b9a8380-8d61-11eb-9e0e-bbde5111e4ec.png)

**Comment by tammullen** [comment] 2021-03-26 14:29
Hi @edvinassss98

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2021-03-26 14:29 UTC
