### ISSUE TITLE
[REST API] /products/attributes/<attribute_id> how to get all related terms within this one request.

### ISSUE THREAD

**Issue by masthisis** [woocommerce/woocommerce#28365] opened 2020-11-22 06:11 UTC
i want to include related terms in each a attribute object  when i get all attributes.
 i saw this [ ` /wp/v2/posts?_embed=author,wp:term ` ](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/)that can include related information in a request but i don't know how to use it to get attribute terms.

**Comment by rrennick** [comment] 2020-11-24 14:58
Hi @masthisis,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request. If you would like to report a bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by rrennick** 2020-11-24 14:58 UTC
