### ISSUE TITLE
Bank account details are not in the order email sent to the customer

### ISSUE THREAD

**Issue by Jorsana** [woocommerce/woocommerce#28812] opened 2021-01-14 11:04 UTC
Hello,
I have the bank transfer payment option.
My problem: 
Bank account details show only on the Order Received page, 
but **NOT in the order email** sent to the customer, like here bellow:
https://docs.woocommerce.com/document/bacs/#prettyPhoto
![Zajeta slika](https://user-images.githubusercontent.com/77439433/104582181-db88f580-565f-11eb-8dc8-3a18edf003e8.JPG)
Appreciate your help.
Jorsana
jorsana@linking-art.com

**Comment by tammullen** [comment] 2021-01-18 10:30
Hi @Jorsana 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 
​
![Screenshot_2021-01-18_at_03_19_15](https://user-images.githubusercontent.com/24649833/104903581-1e0c4400-5978-11eb-9048-b951ccc2a095.png)

​
Please provide us with steps to reproduce the issue on our end. We need to know how your category pages are set-up - step by step instructions for us to recreate your use case.

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.


​

**Comment by Jorsana** [comment] 2021-01-18 11:46
Hi Tam,

 

I'm so, so sorry. 

When I tested the payment, I filled in my testing email-address instead of the mail-address I always use. Accidently I opened that inbox after a long time and saw my mistake.

I'm so embarrassed. But this is important, so, please, understand my worry.

Thank you for your understanding, the time, and effort for my problem.

 

Lepi pozdravi / All the best

Jorsana & Stane from  <https://www.linking-art.com/> Linking Art

**Comment by tammullen** [comment] 2021-03-25 22:27
Thanks for the update. Closing but let us know if we missed anything.

**Closed by tammullen** 2021-03-25 22:27 UTC
Labels: has feedback
