### ISSUE TITLE
This order’s status is “Pending payment”—it cannot be paid for. Shows after checkout page.

### ISSUE THREAD

**Issue by ajaypandey03** [woocommerce/woocommerce#26730] opened 2020-06-09 06:18 UTC
**Describe the bug**
This order’s status is “Pending payment”—it cannot be paid for. Shows after checkout page.

Also event after customer in logged In no data is shown in order page other then order id.

**To Reproduce**

**Screenshots**

**Expected behavior**
Payment is done and order status is changed to processing.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.


`
### WordPress Environment ###

WordPress address (URL): https://ingluglobal.com
Site address (URL): https://ingluglobal.com
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.31
PHP Post Max Size: 12 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wpxe_
Total Database Size: 32.29MB
Database Data Size: 26.71MB
Database Index Size: 5.58MB
wpxe_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_downloadable_product_permissions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpxe_woocommerce_order_items: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
wpxe_woocommerce_order_itemmeta: Data: 0.82MB + Index: 0.25MB + Engine MyISAM
wpxe_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_actionscheduler_actions: Data: 2.02MB + Index: 0.92MB + Engine InnoDB
wpxe_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_actionscheduler_logs: Data: 1.41MB + Index: 0.56MB + Engine InnoDB
wpxe_cartflows_ca_cart_abandonment: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wpxe_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_cf_forms: Data: 1.47MB + Index: 0.02MB + Engine InnoDB
wpxe_cf_form_entries: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wpxe_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_cf_form_entry_values: Data: 0.39MB + Index: 0.53MB + Engine InnoDB
wpxe_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_cf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_cf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_comments: Data: 0.21MB + Index: 0.10MB + Engine MyISAM
wpxe_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_nextend2_image_storage: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_nextend2_section_storage: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpxe_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_nextend2_smartslider3_slides: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wpxe_options: Data: 5.95MB + Index: 0.37MB + Engine MyISAM
wpxe_postmeta: Data: 11.38MB + Index: 0.92MB + Engine MyISAM
wpxe_posts: Data: 0.67MB + Index: 0.18MB + Engine MyISAM
wpxe_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpxe_usermeta: Data: 0.72MB + Index: 0.40MB + Engine MyISAM
wpxe_users: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wpxe_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_wc_customer_lookup: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
wpxe_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_wc_order_coupon_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wpxe_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine MyISAM
wpxe_wc_order_stats: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wpxe_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpxe_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_audit_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_company_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_files_upload: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_dependents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_hr_depts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_designations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_education: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_hr_employees: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_hr_employee_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_wphr_hr_employee_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_employee_performance: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_hr_holiday: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_leaves: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_hr_leave_entitlements: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_hr_leave_policies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_leave_requests: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_wphr_hr_upload: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpxe_wphr_hr_work_exp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_peoplemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_wphr_peoples: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_people_types: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_wphr_people_type_relations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_yoast_indexable: Data: 0.28MB + Index: 0.17MB + Engine InnoDB
wpxe_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpxe_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpxe_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpxe_yoast_seo_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpxe_yoast_seo_meta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 395
cartflows_flow: 1
cartflows_step: 2
course: 1
custom_css: 4
elementor_library: 26
elementor-hf: 1
elementskit_content: 1
envato_kits: 9
envato_tk_import: 4
ig_campaign: 2
ig_message: 5
inglu_internships: 1
nav_menu_item: 33
oembed_cache: 2
page: 45
popup: 6
popup_theme: 7
post: 6
product: 15
profile: 1
revision: 71
shop_coupon: 279
shop_order: 678
tablepress_table: 1
um_directory: 1
um_form: 3
wp_block: 1
wpforms: 1
wphr_hr_announcement: 1
wpm-testimonial: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Caldera Forms: by Caldera Labs – 1.8.11
CartFlows: by CartFlows Inc – 1.5.10
Elementor: by Elementor.com – 2.9.11
Envato Elements: by Envato – 2.0.5
Flat Preloader: by Thien Nguyen – 1.2
Site Kit by Google: by Google – 1.9.0
Paytm Payment Gateway: by Paytm – 1.0 – Installed version not tested with active version of WooCommerce 4.2.0
Popup Maker: by Popup Maker – 1.10.1
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.3.3

Sticky Header OceanWP: by Oren Hahiashvili – 1.0.5
Tawk.to Live Chat: by Tawkto – 0.4.2
Toolbar Extras: by David Decker - DECKERWEB – 1.4.9
Tracking Code Manager: by IntellyWP – 1.12.2
WooCommerce: by Automattic – 4.2.0
WP Rocket: by WP Media – 3.5.5.1

### Inactive Plugins (10) ###

Advanced Custom Fields: by Elliot Condon – 5.8.11
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.4 – Installed version not tested with active version of WooCommerce 4.2.0
Custom Post Type UI: by WebDevStudios – 1.7.4
Essential Addons for Elementor: by WPDeveloper – 4.0.2 – Installed version not tested with active version of WooCommerce 4.2.0
Jetpack by WordPress.com: by Automattic – 8.6.1
Official Facebook Pixel: by Facebook – 2.0.2
Razorpay for WooCommerce: by Team Razorpay – 2.4.2 – Installed version not tested with active version of WooCommerce 4.2.0
TablePress: by Tobias Bäthge – 1.11
User Menus: by Code Atlantic – 1.2.3
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.6 – Installed version not tested with active version of WooCommerce 4.2.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1175 - /shop/
Cart: #1178 - /cart/
Checkout: #1181 - /checkout/
My account: #1184 - /my-account/
Terms and conditions: #3541 - /terms-and-conditions/

### Theme ###

Name: OceanWP
Version: 1.8.2 (update to version 1.8.3 is available)
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php


### Action Scheduler ###

Complete: 3,539
Oldest: 2020-05-09 06:57:21 +0000
Newest: 2020-06-09 06:02:52 +0000

Failed: 2
Oldest: 2020-06-08 08:12:10 +0000
Newest: 2020-06-08 08:17:15 +0000

Pending: 2
Oldest: 2020-06-09 06:56:45 +0000
Newest: 2020-06-09 06:56:45 +0000

`
```
</details>

**Comment by juliaamosova** [comment] 2020-06-09 14:30
Hi @ajaypandey03,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-06-09 14:30 UTC
