### ISSUE TITLE
Add to cart URL does not work unless cookie already exists

### ISSUE THREAD

**Issue by samnazarko** [woocommerce/woocommerce#19677] opened 2018-04-10 16:46 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Giving a user a direct link to the /cart?add-to-cart= endpoint no longer functions as expected. I am redirected and I see 'Your cart is empty'.

I am using Varnish 5.x, but I have edited my VCL so that vcl_deliver() is called for the entire domain vcl_backend_response() to ensure that the issue was not caused by cookies being dropped to improve hit ratio. 

1. Use incognito mode / ensure no cookies are set for the domain
2. Visit https://STOREURL/cart/?add-to-cart=PRODUCTID
3. Browser will redirect to cart page which will state the cart is empty

If this is repeated, it will succeed, as a cookie now exists.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

A live example can be reproduced via wget: 

wget "https://my.osmc.tv/cart/?add-to-cart=4255" --server-response -O /dev/null

woocommerce_items_in_cart; woocommerce_cart_hash and wp_woocommerce_session cookies are set correctly.

A 302 is then issued. Items in cart is set to 0 and woocommerce_cart_hash=deleted

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://my.osmc.tv
Site URL: https://my.osmc.tv/cms
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 8 MB
PHP Time Limit: 720
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.6.39
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 224.29MB
Database Data Size: 137.44MB
Database Index Size: 86.85MB
wp_woocommerce_sessions: Data: 5.02MB + Index: 0.09MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB
wp_woocommerce_order_itemmeta: Data: 35.52MB + Index: 10.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_automatewoo_abandoned_carts: Data: 0.16MB + Index: 0.08MB
wp_automatewoo_customers: Data: 1.52MB + Index: 2.25MB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_guests: Data: 2.52MB + Index: 3.39MB
wp_automatewoo_guest_meta: Data: 3.52MB + Index: 2.97MB
wp_automatewoo_logs: Data: 1.52MB + Index: 3.50MB
wp_automatewoo_log_meta: Data: 8.52MB + Index: 5.03MB
wp_automatewoo_queue: Data: 0.05MB + Index: 0.05MB
wp_automatewoo_queue_meta: Data: 0.16MB + Index: 0.14MB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.06MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 6.52MB + Index: 9.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.52MB + Index: 0.36MB
wp_postmeta: Data: 46.58MB + Index: 36.13MB
wp_posts: Data: 4.52MB + Index: 2.52MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 11.52MB + Index: 8.03MB
wp_users: Data: 1.52MB + Index: 0.42MB
wp_wcpdf_invoice_number: Data: 0.16MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 0.20MB + Index: 0.00MB
wp_wfHits: Data: 0.41MB + Index: 0.17MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.05MB + Index: 0.00MB
wp_wfKnownFileList: Data: 0.13MB + Index: 0.00MB
wp_wfLeechers: Data: 0.11MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.19MB + Index: 0.06MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.14MB + Index: 0.09MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 88
aw_workflow: 27
braintree_log: 17
nav_menu_item: 22
page: 22
post: 11
product: 18
product_variation: 14
revision: 19
shop_coupon: 375
shop_order: 10765
shop_order_refund: 259
sidebar: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

AutomateWoo - Referrals Add-on: by AutomateWoo – 1.7.10
AutomateWoo: by AutomateWoo – 3.4.2.3 – Not tested with the active version of WooCommerce
Facebook for WooCommerce: by Facebook – 1.4.2 – Not tested with the active version of WooCommerce
Salient WPBakery Page Builder: by Michael M - WPBakery.com | Modified by ThemeNectar – 5.4.7
Site Plugin for OSMC 2FA TAB: by  –
Site Plugin for OSMC.tv: by  –
Site Plugin for OSMC Shipping: by  –
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Two Factor Authentication (Premium): by David Nutbourne + David Anderson
original plugin by Oskar Hane – 1.2.35 – Not tested with the active version of WooCommerce

WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.2.0
WooCommerce EU VAT Compliance (Premium): by David Anderson – 1.12.2
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.8.2
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.1.6
WooCommerce Subscriptions: by Prospress Inc. – 2.2.11 – 2.2.19 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.4
WooSidebars: by WooThemes – 1.4.3
WP-Discourse: by Discourse – 1.6.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
```
</details>

System environment has not changed for a year.

**Comment by mikejolley** [comment] 2018-04-10 17:14
@samnazarko Why so quick to dismiss varnish? I just tested this local in different browser, private mode, and it worked first time.

**Comment by samnazarko** [comment] 2018-04-10 18:31
I've done some more digging. It doesn't seem to be Varnish.

If I disable the option 'Redirect to the cart page after successful addition' I don't experience problems anymore.

One thing that may be useful to know is that I override the site URL in wp-config.php as I often test it in different environments:

```
        define('WP_SITEURL', 'https://' . $DOMAIN_NAME . '/cms');
        define('WP_HOME',    'https://' . $DOMAIN_NAME . '');
```

If I revert WooCommerce + CMS in Git (I bumped both at the same time), I cannot produce the issue anymore.

**Comment by mikejolley** [comment] 2018-04-11 10:11
You're saying the bug is specific to ^ custom config?

**Comment by samnazarko** [comment] 2018-04-11 10:13
Seems to be the case, yes. 
I have a solution for now, but will see if I can chase down the change in behaviour to a specific commit.

**Comment by mikejolley** [comment] 2018-04-13 09:05
Odd. Let me know if you trace it back to a problem in WC. Closing for now as I'm not able to reproduce the problem on regular config.

**Closed by mikejolley** 2018-04-13 09:05 UTC
Labels: Status: Needs Feedback

**Comment by samnazarko** [comment] 2018-09-19 00:44
Just to let you know that in my environment, I was seeing items added to cart twice. 
After re-enabling 

>Redirect to the cart page after successful addition

This is now resolved. My cart is also no longer reported as empty.

**Comment by jshmut** [comment] 2019-06-10 19:38
@samnazarko Hello, 
were you able to figure out how to keep your add to cart URL links with 'Redirect to the cart page after successful addition' enabled? I am experiencing this same problem.
