### ISSUE TITLE
Woocommerce extra product options plugin

### ISSUE THREAD

**Issue by kryten68** [woocommerce/woocommerce#25867] opened 2020-03-10 21:30 UTC
The extra product options plugin calendar component seems to think that Monday the 30th of March, and every Monday recurring thereafter is actually a Sunday.

If we say that the calendar object is id 'day_checker' then the following simple JS to squeak out the day of week show the issue perfectly.

```
<script>
  
    document.getElementById('day_checker').change = function() {
      
        var val = document.getElementById("day_checker").value;
        var a = new Date(val);
        console.log("Date is: " + val)
        var d = a.getUTCDay();
        
      switch (d) {
        case 0:
    				day = "Sunday";
    				break;
  			case 1:
    				day = "Monday";
    				break;
  			case 2:
     				day = "Tuesday";
    				break;
  			case 3:
    				day = "Wednesday";
    				break;
  			case 4:
    				day = "Thursday";
    				break;
  			case 5:
    				day = "Friday";
    				break;
  			case 6:
    				day = "Saturday";
		  }
      
      console.log("Day is: ", day);
      
      if (day != "Monday") {
        document.getElementById("day_checker").value="NOT A MONDAY!";
      }   
      
    }
    
</script>
```

**Comment by juliaamosova** [comment] 2020-03-10 21:41
Hi @kryten68,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by juliaamosova** [comment] 2020-03-20 15:22
Hi @kryten68, the issue you are having seems to be related to the 3rd party plugin you are using - WooCommerce Extra Product Options. Please contact the developers of the plugin further for help. 

I am closing this issue on our end. However, please feel free to comment in case I missed something and we will take another look.

**Closed by juliaamosova** 2020-03-20 15:22 UTC
Labels: status: needs feedback
