### ISSUE TITLE
Shop Manager can switch Privacy Policy page, but can't edit its content

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce#25606] opened 2020-02-07 11:37 UTC
**Describe the bug**
Shop Manager is not allowed to edit content of the current Privacy Policy page. But there's a way to overcome this limitation, which makes it no sense. 

As you can see on the screenshot, the page on the list is faded out and has no Edit link.

**To Reproduce**
1. Create an account with Shop manager role
2. Log into WP Admin using this account
3. Go to Pages list
4. See that you can not edit page marked currently as "Privacy Policy Page"
5. Go to WooCommerce->Settings->Accounts & Privacy
6. See that in section Privacy policy you can actually switch the page that will be used as WP Privacy Policy page.
7. If you've switched the page, go back to Pages list and see that now the another page is blocked, but the original one is accessible, so you can edit it now. Then maybe switch them once again and get the results you want to have at the first place…

**Screenshots**
![Zrzut ekranu 2020-02-07 o 12 19 57](https://user-images.githubusercontent.com/27000783/74026362-518fd180-49a6-11ea-8e60-eb069d6f17b5.png)

**Expected behavior**
Store Manager role should also have capabilities to edit Privacy Policy page content.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888/wc
Site address (URL): http://localhost:8888/wc
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.2.1
PHP Post Max Size: 8 MB
PHP Time Limit: 1000
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: wp_
Total Database Size: 2.64MB
Database Data Size: 1.66MB
Database Index Size: 0.98MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 3
product: 1
revision: 1
scheduled-action: 3
shop_coupon: 1
shop_order: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.9.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2020-01-26 17:21:10 +0000
Newest: 2020-01-26 17:21:11 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment] 2020-02-10 15:26
Hi @starypop,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

I am not entirely sure if Shop Manager should have a right to edit the Privacy Policy page but in any case, we need to make sure that the experience is consistent throughout different pages and options available. If Shop Manage doesn't have a permission to edit the Privacy Policy page, they should not be able to switch which page the Privacy Policy page is set to. 

We’re going to work on this bug as soon as possible.

**Comment by starypop** [comment] 2020-02-10 16:35
@juliaamosova I understand, that the consistency here is very important.

In my opinion, as long as there is no user role between Administrator and Shop Manager, we should grant them priviliges to edit this page content.

In our workflow, we're trying to avoid using Administrator role accounts on day-to-day basis, having site's security in mind. 

Moreover, Shop Manager has already full access to privacy options such as customers data removal, editing Terms and Conditions content, etc. So this role is already actually capable of doing potential harmfull things to site privacy and customers data.

**Comment by MitchAfundi** [comment] 2020-02-25 11:44
Just wondering if any updates have been made on this?

**Comment by rodrigoprimo** [comment] 2020-03-12 17:19
I agree that this is confusing and we need to do something about it, but I'm not sure what is the best way to fix it. Some ideas bellow to help whoever ends up working on a fix for this.

The privacy page is created by WordPress and not WooCommerce. WooCommerce extends this feature and let shop managers define things such as a registration privacy policy notice that normally points to the privacy page. Despite being a WP setting and originally appearing on `Settings -> Privacy`, `Privacy page` is also added by WooCommerce to `WooCommerce -> Settings -> Accounts and Privacy`.

WP defines that only users with the `manage_privacy_options` capability can edit the privacy page. 
The easiest solution would be to give this capability to shop managers, but I don't think we should do this because it would also give shop managers access to all the settings on `Settings -> Privacy`. 

My understanding is that the difference between a shop manager and an admin is that the former has access to all WooCommerce settings but not WordPress settings. If we give `manage_privacy_options` to shop managers, we are blurring the distinction between the two roles.

One thing to check is if it is possible to give shop managers permission just to edit the privacy page without giving them access to the `Settings -> Privacy` page. That might be the best option that we have but it is still not ideal.

**Closed** 2020-06-23 16:34 UTC
Labels: bug, has pull request, priority: high
