### ISSUE TITLE
Add to cart button stuck when clicking once in turquazarts.com

### ISSUE THREAD

**Issue by axcar95** [woocommerce/woocommerce#28289] opened 2020-11-15 16:18 UTC
When i open a product page and clicked the add to cart button it became stuck and disabled i cant add to cart again if i want to do it again. İf i enter the variations wrong i cant change it because both variations tab and add to cart button remains disabled and didnt work unless i refresh the page
![IMG_20201115_191739](https://user-images.githubusercontent.com/48660460/99190387-5d9b9180-2777-11eb-997e-e534d8e314c9.jpg)

**Comment by juliaamosova** [comment] 2020-12-04 20:33
Hi @axcar95,

Thank you for raising the issue. However, I can’t reproduce it on my end. I can successfully add items to the cart on the mobile device. 

According to your screenshot, it looks like you have several plugins installed. Specifically, the plugin that adds the `Personalization` field, for example. These plugins or a theme you are using may cause an issue. 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-12-11 20:18
Hi @axcar95,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-12-11 20:18 UTC
Labels: can't reproduce, status: needs feedback
