### ISSUE TITLE
After update getting error "you website have critical error" 

### ISSUE THREAD

**Issue by UsamaYaqoob100** [woocommerce/woocommerce#27389] opened 2020-08-18 18:11 UTC
After update 3 hours ago getting an error to the website that "your website has critical error" after disabling the Woo-commerce plugin site is working but what we do without this plugin?

**Comment by Ceaco** [comment] 2020-08-18 18:21
I have same problem here. The new update crashed the site and sadly i have no backup for 4.3.3. A 4.3.3. version would fix the issue if somebody have it.

**Comment by rrennick** [comment] 2020-08-18 18:24
@Ceaco There were no DB updates in WC 4.4.0 so you should be able to reinstall 4.3.3.

**Comment by DragonEnergy** [comment] 2020-08-18 18:25
I rolled back to 4.3 the issue is with 4.4.0 so far I am still uploading the woocommerce file via FTP and issue went away. avoid the new 4.4 update for now

**Comment by Ceaco** [comment] 2020-08-18 18:26
@rrennick how can I roll back to 4.3.3? Or how can i reinstall it if i don't have the zip archive?

**Comment by DragonEnergy** [comment] 2020-08-18 18:27
https://github.com/woocommerce/woocommerce/releases/tag/4.3.0

**Comment by DragonEnergy** [comment] 2020-08-18 18:28
Add via FTP

**Comment by rrennick** [comment] 2020-08-18 18:51
> how can I roll back to 4.3.3? Or how can i reinstall it if i don't have the zip archive?

@Ceaco  Scroll to the bottom of https://wordpress.org/plugins/woocommerce/advanced/

**Comment by zwiesman31** [comment] 2020-08-18 18:57
If you all check your fatal-error log (`WooCommerce > Status > Logs`) are you getting a similar message as the one below? 

```
PHP Fatal error: Declaration of Automattic\WooCommerce\Internal\DependencyManagement\ExtendedContainer::get($id, bool $new = false) must be compatible with League\Container\Container::get($alias, array $args = Array) in /wp-content/plugins/woocommerce/src/Internal/DependencyManagement/ExtendedContainer.php on line 18
```

**Comment by rrennick** [comment] 2020-08-18 19:07
@Ceaco That doesn't have the error message for creating the table.

Also, transferring this to the action-scheduler repo.

**Comment by Kipperlenny** [comment] 2020-08-18 19:59
see #27384

**Comment by juliaamosova** [comment] 2020-08-18 21:12
@zwiesman31 👋  for the error in your comment, please see https://github.com/woocommerce/woocommerce/issues/27388#issuecomment-675719520. 

@UsamaYaqoob100 it will be helpful to know what error exactly you are having. If you have no way to access error logs yourself, please contact your hosting company and ask them to provide you with the server error log.

**Comment by Bufffffffffff** [comment] 2020-08-18 22:21
I found that was a redirection problem because my front page worked and i could add products to the basket but not follow the links, always getting 500.

For some reasons the last woocommerce update (at 8:02UTC) called flush_rewrite_rules (.htacces modified at 8:02UTC) or something and because we have wpml installed it was messed up. There was no FATAL error at all since it was a rewrite fault.

**Comment by eyre90** [comment] 2020-08-18 22:46
Hi Guys, ive not read through the comments apart from the first few.   but heres the link to download previous versions. head to the bottom of the page, regards Jay@Alwayscompetitions.co.uk
heres the link -
https://wordpress.org/plugins/woocommerce/advanced/

**Comment by BastiaanBosch** [comment] 2020-08-19 13:11
Same here. Where zwiesman31 mentioned error on line 18.
I have on line 154. (Multi-site installation ) 

Fatal error: Declaration of Automattic\WooCommerce\Internal\DependencyManagement\ExtendedContainer::get($id, bool $new = false) must be compatible with
League\Container\Container::get($alias, array $args = Array) in
/home/......../public_html/wp-content/plugins/woocommerce/src/Internal/DependencyManagement/ExtendedContainer.php on line 154

**Comment by jasonmj** [comment] 2020-08-19 14:16
I got this too:
```Fatal error: Declaration of Automattic\WooCommerce\Internal\DependencyManagement\ExtendedContainer::get($id, bool $new = false) must be compatible with League\Container\Container::get($alias, array $args = Array) in /var/www/html/wp-content/plugins/woocommerce/src/Internal/DependencyManagement/ExtendedContainer.php on line 18```

**Comment by tammullen** [comment] 2020-08-28 10:40
Hi @UsamaYaqoob100 

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2020-08-28 10:40 UTC
Labels: status: needs feedback
