### ISSUE TITLE
Checkout Field Editor by Themehigh checkout error

### ISSUE THREAD

**Issue by ahnafadil23** [woocommerce/woocommerce#25117] opened 2019-11-26 18:56 UTC
![Screenshot 2019-11-27 at 12 55 29 AM](https://user-images.githubusercontent.com/58231329/69663581-bd091900-10b0-11ea-986b-5e3c04740834.png)
I think there is something wrong please help me.

**Comment by juliaamosova** [comment] 2019-11-27 12:17
Hi there @ahnafadil23,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs specific to the WooCommerce plugin only. It looks like you are having an issue with a 3rd party plugin [Checkout Field Editor by Themehigh](https://www.themehigh.com/product/woocommerce-checkout-field-editor-pro/). I recommend you reach out to them for further help. 

Moreover, the type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end **related to WooCommerce**, please provide us with clear steps to reproduce the issue. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-11-27 12:17 UTC
