### ISSUE TITLE
UI & Ajax Bug : After removing all products in the cart, the page becomes "only content" without header and footer.

### ISSUE THREAD

**Issue by andriamirul** [woocommerce/woocommerce#28539] opened 2020-12-10 09:15 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After removing all products in the cart, the page becomes "only content" without header and footer. We found that  there is a function that not returned when the cart is empty the function is wc-ajax=get_refreshed_fragments. by unregister the wc-cart-fragment from the cart page then this issue is solved.

**Expected behavior**
When removing the product, the ajax returned correctly and the footer and header should not disappeared.

**Actual behavior**
When removing the product, the ajax is not returned, the footer and the header is disappeared.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add 1 item to your cart
2. Go to cart page
3. Remove the last item from your cart
4. The page becomes "only content" without header and footer.

**Screenshots**
![image](https://user-images.githubusercontent.com/42957537/101750726-fd8fd500-3b01-11eb-9af3-3a0ca74c0d0e.png)

Video bug reproduce : https://youtu.be/rym7C7YSccI
Video bug is solved after we unregister wc-cart-fragments : https://youtu.be/63M_0aVFZ4c

the code i use for unregister the wc-cart-fragments : 

add_action( 'woocommerce_before_cart', 'deregister_cart_ajax_get_refreshed_fragments' );
 
function deregister_cart_ajax_get_refreshed_fragments() {	

			wp_deregister_script( 'wc-cart-fragments' );
}

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2020-12-12 19:32
Hi @andriamirul,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. Please see the gif below that shows that there is no issue on my end:

![](http://g.recordit.co/EnWekPnwIM.gif)

My environment details are as follows:

- PHP 7.4.13
- WordPress 5.6
- WooCommerce 4.8
- Twenty Twenty One theme (default)

I watched the video you provided (thank you!) and it looked like a theme issue to me. You indicated that you tested your site for conflicts but I always like to confirm. 

In case you did not, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/) or Twenty Twenty One. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by juliaamosova** [comment] 2020-12-23 22:45
Hi @andriamirul,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2020-12-23 22:45 UTC
Labels: category: can't reproduce, needs feedback
