### ISSUE TITLE
Account login issue

### ISSUE THREAD

**Issue by ashmongia** [woocommerce/woocommerce#21216] opened 2018-08-29 10:21 UTC
Hi,

We are facing login issue multiple time its not consistent its randomly occurred first we thought its cache issue now our dev. has sorted the same but still no improvement screen shot attached.

"something went wrong" error shows to user while login

https://thepleasuretrend.in/

pls reply at ashutosh0mongia@gmail.com

![img-20180829-wa0003](https://user-images.githubusercontent.com/42803151/44781892-2abf5000-aba3-11e8-989a-28cdc284fd33.jpg)

**Comment by claudiulodro** [comment] 2018-08-30 17:04
Hi there.

Sorry we cannot provide support on GitHub. That error message is a generic error message and could be caused by a number of possible things. I wasn't able to reproduce the problem on a site running only WooCommerce, and it is highly unlikely the login is broken in WooCommerce as this is the only report of it we've seen. I recommend trying [the support forums](https://wordpress.org/support/plugin/woocommerce/) and maybe someone can be of more help there. I'm closing this issue as non-reproducible.

Thanks.

**Closed by claudiulodro** 2018-08-30 17:04 UTC
