### ISSUE TITLE
Order API showing dictionary on new orders in 4.8 while list on pre 4.8 orders

### ISSUE THREAD

**Issue by lanec** [woocommerce/woocommerce#28589] opened 2020-12-14 20:35 UTC
Orders in our site entered prior to 4.8 show up as a list when we access the API:

customer id:  11736
[{'date': '2020-12-11 08:54:13',
  'item_id': 162765,
  'name': '2021 Product',
  'order_id': 44184,
  'qty': 1,
  'shipped': 0,
  'status': 'not-shipped'},
 {'date': '2020-12-11 08:55:37',
  'item_id': 162766,
  'name': '2021/2022 Product',
  'order_id': 44184,
  'qty': 1,
  'shipped': 0,
  'status': 'not-shipped'}]

Orders in the site entered after upgrading to 4.8 show up as a dictionary when we access the API: 

customer id:  4958
{'0': {'date': '2020-12-11 07:00:23',
       'item_id': 162735,
       'name': '2021 Product '
               'Legislature',
       'order_id': 44178,
       'qty': 1,
       'shipped': 0,
       'status': 'not-shipped'},
 '1': {'date': '2020-12-11 07:00:23',
       'item_id': 162736,
       'name': '2021 Product',
       'order_id': 44178,
       'qty': 3,
       'shipped': 0,
       'status': 'not-shipped'},
 '3': {'date': '2020-12-11 07:00:23',
       'item_id': 162738,
       'name': '2021 Product',
       'order_id': 44178,
       'qty': 2,
       'shipped': 0,
       'status': 'not-shipped'},
 '4': {'date': '2020-12-11 07:00:23',
       'item_id': 162739,
       'name': '2021 Product',
       'order_id': 44178,
       'qty': 3,
       'shipped': 0,
       'status': 'not-shipped'}}

**Comment by rrennick** [comment] 2021-10-22 14:13
> Orders in the site entered after upgrading to 4.8 show up as a dictionary when we access the API:

@lanec Are you still experiencing this issue with WooCommerce 5.8.0? The results were returned correctly in my dev install:

```
[
  {
    "id": 18732,
    "parent_id": 0,
    "status": "pending",
    "currency": "EUR",
    "version": "5.9.0",
    "prices_include_tax": false,
    "date_created": "2021-10-19T14:27:42",
    "date_modified": "2021-10-19T14:27:42",
```

**Comment by lanec** [comment] 2021-10-30 08:44
It has been 10 months since I reported this issue. 

WooCommerce has not gotten better for me. I gave up relying on it's API after this and other issues. 

I've begun working with a team on an headless API driven e-commerce solution so we can throw WooCommerce in a dumpster and light it on fire.

**Comment by AashikP** [comment] 2021-11-08 10:20
Hello @lanec 

Sorry to hear about the trouble you've had with API, but this is not something we can replicate.

Here's how it works in version 4.7 on my test site:

![https://d.pr/i/4jzAaQ+](https://d.pr/i/4jzAaQ+)

After updating to the latest version, the order still displays as expected:

Previous order:

![https://d.pr/i/Oyfb9e+](https://d.pr/i/Oyfb9e+)

New order placed after updating:

![https://d.pr/i/Q8S67d+](https://d.pr/i/Q8S67d+)

---


While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by AashikP** 2021-11-08 10:20 UTC
Labels: has feedback, category: wc rest api
