### ISSUE TITLE
Empty orders with status "auto-draft" returned from REST API

### ISSUE THREAD

**Issue by george2seven** [woocommerce/woocommerce#23179] opened 2019-03-30 14:34 UTC
**Describe the bug**
While using the REST API (v3) when I try to retrieve a list of orders I get also orders with status "auto-draft" that are empty (only ID and dates are present).  Can those orders be excluded from the endpoint when the status parameter is "any" (default)?

**Screenshots**
sample order returned from the REST API:

[{
	"id": 2333,
	"parent_id": 0,
	"number": "2333",
	"order_key": "",
	"created_via": "",
	"version": "3.5.7",
	**"status": "auto-draft",**
	"currency": "EUR",
	"date_created": "2019-03-30T13:28:14",
	"date_created_gmt": "2019-03-30T11:28:14",
	"date_modified": "2019-03-30T13:28:14",
	"date_modified_gmt": "2019-03-30T11:28:14",
	"discount_total": "0.00",
	"discount_tax": "0.00",
	"shipping_total": "0.00",
	"shipping_tax": "0.00",
	"cart_tax": "0.00",
	"total": "0.00",
	"total_tax": "0.00",
	"prices_include_tax": false,
	"customer_id": 0,
	"customer_ip_address": "",
	"customer_user_agent": "",
	"customer_note": "",
	"billing": {
		"first_name": "",
		"last_name": "",
		"company": "",
		"address_1": "",
		"address_2": "",
		"city": "",
		"state": "",
		"postcode": "",
		"country": "",
		"email": "",
		"phone": ""
	},
	"shipping": {
		"first_name": "",
		"last_name": "",
		"company": "",
		"address_1": "",
		"address_2": "",
		"city": "",
		"state": "",
		"postcode": "",
		"country": ""
	},
	"payment_method": "",
	"payment_method_title": "",
	"transaction_id": "",
	"date_paid": null,
	"date_paid_gmt": null,
	"date_completed": null,
	"date_completed_gmt": null,
	"cart_hash": "",
	"meta_data": [],
	"line_items": [],
	"tax_lines": [],
	"shipping_lines": [],
	"fee_lines": [],
	"coupon_lines": [],
	"refunds": [],
	"_links": {
		"self": [{
			"href": ""
		}],
		"collection": [{
			"href": ""
		}]
	}
}]

Thank you

**Comment by mikejolley** [comment] 2019-04-01 10:51
Hi,

I tried to replicate this one by adding an order (unsaved) which had an ID, then hitting the `/wp-json/wc/v3/orders` endpoint. I had no drafts returned on both WC 3.6 RC and 3.5.7.

I also tested with:

```
{
	"status":"any"
}
```

which produced the same results. I suspect a plugin is filtering the response or changing statuses in your case as it's not affecting other installs.

Checking the docs here https://codex.wordpress.org/Class_Reference/WP_Query, the docs for post_status and 'any' specifically state auto-drafts are excluded:

> 'any' - retrieves any status except those from post statuses with 'exclude_from_search' set to true (i.e. trash and auto-draft).

If a plugin were to change that, the REST API would also be affected.

Hope this helps narrow down your issue. I'm marking this closed as it's not reproducable on other installs.

**Closed by mikejolley** 2019-04-01 10:51 UTC

**Comment by gkanellopoulos** [comment] 2019-04-02 05:18
Thanks @mikejolley !! I appreciate the info and I hope I can track down the plug-in that is doing that because non of the plug-ins installed explicitly is stating that is messing around with the WP_Query or with the filter of "any".

**Comment by mikejolley** [comment] 2019-04-02 09:22
Good luck @gkanellopoulos, probably some trial and error to find the one doing it :) let me know if you can repro it with only wc core.
