### ISSUE TITLE
PayPal _stripe_net equivalent

### ISSUE THREAD

**Issue by raymondlittle100** [woocommerce/woocommerce#26004] opened 2020-03-24 16:24 UTC
I'm integrating with WooCommerce and I'm using the WooCommerceNET NuGet package to fetch sales orders. When getting credit card values I can see _stripe_fee and _stripe_net. When accessing PayPal orders I can see PayPal Transaction Fee but this is just the fee PayPal the same as _stripe_fee. I'm trying to access the final GBP value the client gets. Is there a PayPal equivalent to the _stripe_net?

**Comment by jonathansadowski** [comment] 2020-05-18 00:48
Hi @raymondlittle100,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by jonathansadowski** 2020-05-18 00:48 UTC
