### ISSUE TITLE
Coupon search don't work

### ISSUE THREAD

**Issue by lexphx** [woocommerce/woocommerce#29148] opened 2021-02-16 13:30 UTC
![Screenshot_20210216_153537](https://user-images.githubusercontent.com/40895073/108070072-c2170700-706c-11eb-80fa-5a4c55e81d84.png)
![Screenshot_20210216_152731](https://user-images.githubusercontent.com/40895073/108070110-cd6a3280-706c-11eb-8b09-b37c7f5142ec.png)
![Screenshot_20210216_152707](https://user-images.githubusercontent.com/40895073/108070140-d1965000-706c-11eb-8a84-9dd0efca08d3.png)

Hi, so in my back-end when I try to search for a particular coupon it always says "No coupons found". I have changed woocommerce/includes/class-wc-post-types.php shop_coupon type to public, exclude_from_search set to false. But coupon search still don't work.

**Comment by joelclimbsthings** [comment] 2021-02-16 19:41
Thanks for reporting @lexphx ! It looks like this code resides in the `woocommerce` repository, so I'm transferring this issue that direction.

**Comment by zhongruige** [comment] 2021-02-16 23:12
Hi @lexphx,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

1. I created a variety of coupons with different codes: `zrxymuza` (auto-generated), `test coupon` (testing with a space), `ten_percent_off` (testing with underscores):
<img width="1496" alt="Screen Shot 2021-02-16 at 4 04 59 PM" src="https://user-images.githubusercontent.com/71906536/108132894-e248c500-7070-11eb-9cc2-8af356c8721f.png">
2. I tried a partial search and the correct coupon was returned:
<img width="1496" alt="Screen Shot 2021-02-16 at 3 51 08 PM" src="https://user-images.githubusercontent.com/71906536/108132959-fee4fd00-7070-11eb-9c84-8c0878461ce4.png">
3. I did another search, but using the full coupon code:
<img width="1505" alt="Screen Shot 2021-02-16 at 3 51 27 PM" src="https://user-images.githubusercontent.com/71906536/108133003-16bc8100-7071-11eb-89df-3df17459436d.png">
4. I also repeated this similar process for the other coupon codes, and in each case the correct coupon was returned:
<img width="1494" alt="Screen Shot 2021-02-16 at 3 51 37 PM" src="https://user-images.githubusercontent.com/71906536/108133084-3358b900-7071-11eb-95b1-96d764179499.png">
<img width="1498" alt="Screen Shot 2021-02-16 at 3 51 45 PM" src="https://user-images.githubusercontent.com/71906536/108133093-381d6d00-7071-11eb-86fb-fa3ae0600fd2.png">
<img width="1495" alt="Screen Shot 2021-02-16 at 3 54 40 PM" src="https://user-images.githubusercontent.com/71906536/108133106-3c498a80-7071-11eb-8155-801ea2633704.png">

I tested the above using:
* WordPress 5.6.1
* WooCommerce 5.0.0

Please provide us with more details about the issue which may help us to evaluate it further. The following steps will help us to further isolate the problem, please try these steps and mark them completed in a new comment:

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] I can reproduce this bug consistently using the steps above.

Additionally, if you can provide details on the current WordPress environment that will help us further investigate:
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

Thanks!

**Comment by juliaamosova** [comment] 2021-02-27 00:29
Hi @lexphx,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-02-27 00:29 UTC
Labels: needs feedback
