### ISSUE TITLE
Variations of Variable Products Not Added to Order

### ISSUE THREAD

**Issue by NomadAndInLove** [woocommerce/woocommerce#27928] opened 2020-10-12 11:31 UTC
I received an order which consisted of several variable products. When I tried to calculate shipping, I was unable to generate the product weights. Upon investigation, I noticed that the variations for each product were not added to the order but the prices were added correctly. I replicated the order and everything worked fine the second time around.

I have processed over 100 orders and since March 2020 and this has never happened before. 

I have created a staging environment to investigate this further. 

The order that failed to generate the variations is order 4499. I replicated the order (4509) and it works fine. But for some reason, the original order did not generate the variations.

Here's the details for the order:

Order Number: 4499
Username: XXXXXXXXXXXXX
Email: XXXXXXXXXXX
Password: XXXXXXXXXX
Login Link: https://staging28.multitrance.com/wp-admin/

I am unable to reproduce the bug. Not sure if this is worth looking into? Also, none of the products on the above orders have been recently edited.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment] 2020-10-14 17:05
Hi @NomadAndInLove,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. 

Also please note that this thread is accessible to anyone on the internet and you shouldn't include any sensitive login details for your site (even staging). I went ahead and removed the login details from your issue. 

In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-14 17:05 UTC
