### ISSUE TITLE
[GlobalStep - 4.1 beta 1] Database error thrown in query monitor upon installing "Snippet Tool".

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26142] opened 2020-04-09 16:42 UTC
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on Plugins.
4. Add new Plugin.
5. Install and Activate Snippet Tool.
6. Observe that database error is displayed.

**Actual Result:**
Database error is displayed upon installing "Snippet Tool".

**Expected Result:**
No error should occur while installing the plugins.
![18](https://user-images.githubusercontent.com/41110392/78919203-39742580-7aaf-11ea-89f2-3e9e8521e6c0.jpg)

**Comment by juliaamosova** [comment] 2020-04-14 21:48
Hi @gglobalstep,

Thanks for reporting the issue! I can reproduce the same:

![snippets](https://user-images.githubusercontent.com/19143190/79277427-c6d0c480-7e77-11ea-8302-7aa626cce5c0.jpg)

However, this seems to be on the code snippet plugin side of things which is a 3rd party plugin, therefore, I am closing this issue.

**Comment by juliaamosova** [comment] 2020-04-15 15:18
Reopening this issue. @denho experienced the same error when switching to `WC 4.1 beta2` via `WooCommerce Beta Tester` plugin:

![db-error](https://user-images.githubusercontent.com/19143190/79354518-82423900-7f0a-11ea-8df9-e2d8fb6c80b6.png)

Reference: pb22l9-8V-p2#comment-387

Still not sure what is causing it but reopening so that we could investigate further.

**Comment by juliaamosova** [comment] 2020-04-28 21:48
Reported by @andrewjkerr: pb22l9-8V-p2#comment-397. 

Same error when connecting to Square. I could reproduce the same on both NJ and Pressable sites. 

The error happens when you actually click the `Connect` button:

![Screen Shot 2020-04-28 at 5 42 17 PM](https://user-images.githubusercontent.com/19143190/80540999-5eeea380-8978-11ea-863a-e2a9f7736148.png)

![Screen Shot 2020-04-28 at 5 42 58 PM](https://user-images.githubusercontent.com/19143190/80541007-63b35780-8978-11ea-832d-d86a75bc6029.png)

**Comment by juliaamosova** [comment] 2020-05-04 21:37
Noting here that there are 3 different issues in this thread:

- Error on Code Snippets activation: opened an [issue on the Code Snippet's support forum](https://wordpress.org/support/topic/1146-error-table-doesnt-exist-upon-activating-code-snippets-plugin/).

- Error in WooCommerce when switching to 4.1: I no longer experience it in WC 4.1 rc.3.

- Error on Square plugin activation: opened an issue in Square repository: https://github.com/woocommerce/woocommerce-square/issues/419. 

Closing this thread as there isn't anything for us to do.

**Closed by juliaamosova** 2020-05-04 21:37 UTC
