### ISSUE TITLE
Single Report woocommerce_output_content_wrapper is not overriding

### ISSUE THREAD

**Issue by nimeshgoyal** [woocommerce/woocommerce#25192] opened 2019-12-09 08:15 UTC
I am using a twentynineteen theme and maked a child theme of that and in that i am overriding the woocommerce global folder and want to make changes in wrapper-start.php and wrapper-end.php but they are not overiding infact the whole global folder is not overiding in my child theme.

**Comment by juliaamosova** [comment] 2019-12-10 15:34
Hi there @nimeshgoyal,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs. 

The type of issue you submitted looks like `support request`. My understanding is that you are having issues configuring your theme correctly to override WooCommerce templates. To help you further, please refer to our [Template structure & Overriding templates via a theme](https://docs.woocommerce.com/document/template-structure/) documentation. 

If you are still having troubles, I recommend doing the following:

* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Closed by juliaamosova** 2019-12-10 15:34 UTC
