### ISSUE TITLE
Override Core Functions

### ISSUE THREAD

**Issue by yward** [woocommerce/woocommerce#28082] opened 2020-10-23 21:48 UTC
Hello there,

For a certain use case in a multi-vendor marketplace, I need to edit multiple core functions to only pull parents as follows:
```
	public function get_order_count( $status ) {
		global $wpdb;
		return absint( $wpdb->get_var( $wpdb->prepare( "SELECT COUNT( * ) FROM {$wpdb->posts} WHERE post_type = 'shop_order' AND post_parent = '0' AND post_status = %s", $status ) ) );
	}
```
In the previous function I've added `post_parent = '0'` to only query parent orders

another example:
`
protected function query_orders( $args ) {

		// set base query arguments
		$query_args = array(
			'fields'      => 'ids',
			'post_type'   => $this->post_type,
			'post_status' => array_keys( wc_get_order_statuses() ),
			'post_parent' => '0',
		);
	}
`

My question here is: can I override those functions using a filter? I know they are not pluggable functions, but it's a nuisance to edit core files every woocommerce update.

**Comment by PaulodoPorto** [comment] 2020-10-23 22:22
Why don't you use Hooks for this simple task?
What page do u intend to show your result?

`https://blog.atomicsmash.co.uk/blog/how-to-customise-woocommerce-templates-with-hooks/`

**Comment by yward** [comment] 2020-10-23 22:30
> 
> 
> Why don't you use Hooks for this simple task?
> What page do u intend to show your result?
> 
> `https://blog.atomicsmash.co.uk/blog/how-to-customise-woocommerce-templates-with-hooks/`

If I understand hooks correctly, they are more about where I display the code, not how the code is executed. I don't believe hooks are fitting here.

To simplify what I'm trying to do, the multi-vendor plugin I use creates what is known as "sub-orders", so if you buy 2 products from 2 different vendors, 3 orders are created in woocommerce, one parent order and two childs. Now this is troublesome for other plugins that call all orders from database using original woocommerce functions. As it'll result on false/duplicate order counts and false/duplicate statistics.

And since almost every woocommerce plugin calls those functions I mentioned in my first post, it's much easier to edit the core functions that to edit each and every plugin to use a custom function to query the db.

**Comment by TobyOsborne** [comment] 2020-10-27 20:38
Hi, @yward 

I'm not sure if you're still looking for a solution and, though this wouldn't really be a WooCommerce issue per se, I think you could accomplish your goal by utilising the query filter from within your theme's functions.php file.

https://developer.wordpress.org/reference/classes/wpdb/query/

Of course, you'll need to find a way to only modify the correct queries, as this filter will affect everything on the site if used incorrectly.

**Comment by juliaamosova** [comment] 2020-10-28 21:36
Hi @yward,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-10-28 21:36 UTC
