### ISSUE TITLE
"Changes you made may not be saved." message when leaving product, even if no changes have been made, WP 5.6.2

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/woocommerce#29256] opened 2021-03-01 22:37 UTC
I am still having the problem similar to the one reported in ticket #28557 "Changes you made may not be saved." message when leaving product, even if no changes have been made." I'm not seeing the issue in Products anymore, but just had it happen while attempting to edit a Page. That ticket has been closed, and says the issue was fixed with Word Press 5.6.2. And maybe it was, for Products. All my plugins, including WooCommerce, are up to date. This is the page where I just experienced the problem: https://www.georgeglazer.com/wpmain/celestial-globes-with-george-martha-stewart-living-june-29-2001/

**Comment by tammullen** [comment] 2021-03-02 10:05
Hi @GlazerGallery 

Can you please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate **all** plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great to help us evaluate the issue if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by claudiosanches** [comment] 2021-03-02 18:42
Hello @GlazerGallery 

> but just had it happen while attempting to edit a Page. 

WooCommerce doesn't control or insert new meta boxes for pages in WP. Note that some SEO extensions and others had the same issue, since isn't an issue in WooCommerce, but in WordPress core, so maybe you are seeing those errors, but not related to WooCommerce.

**Comment by juliaamosova** [comment] 2021-03-19 23:15
Hi @GlazerGallery,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed by juliaamosova** 2021-03-19 23:15 UTC
Labels: needs feedback
