### ISSUE TITLE
Add Coupon name in "my account" and order emails

### ISSUE THREAD

**Issue by Alphabc** [woocommerce/woocommerce#25175] opened 2019-12-05 13:03 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hi,
Could it be possible to add the coupon's name just below the label "discount" in order emails and in user's "my account" please? (in order to have same information as in admin)
Thx!
**Describe alternatives you've considered**

**Additional context**

**Comment by juliaamosova** [comment] 2019-12-05 13:18
Hi there @Alphabc,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs or enhancements only. 

The type of issue you submitted is a `support request`. 

To do what you are looking for, take a look at the links below:

- https://docs.woocommerce.com/document/send-coupons-used-in-an-order-by-email/
- https://remicorson.com/woocommerce-display-coupons-used-in-an-order-in-the-confirmation-email/

If you need further help, I recommend doing the following:

* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it is a support request and not a bug or an enhancement request.

**Closed by juliaamosova** 2019-12-05 13:18 UTC
