### ISSUE TITLE
ORDER MISSING

### ISSUE THREAD

**Issue by LYDIAMESUBIN** [woocommerce/woocommerce#21472] opened 2018-10-01 13:05 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by LYDIAMESUBIN** [comment] 2018-10-01 13:07
AN ORDER NUMBER IS MISSING. IT DOES NOT APPEARE AND JUMPS FROM 8205 TO 8207. 
THERE IS NO 8206 ORDER.

**Comment by claudiulodro** [comment] 2018-10-03 15:42
@BFTrick has a good article explaining why this is and solutions if you really need sequential order numbers: https://www.speakinginbytes.com/2014/07/woocommerce-order-numbers-order/

Closing this issue as this is not a bug in WooCommerce.

**Closed by claudiulodro** 2018-10-03 15:42 UTC
