### ISSUE TITLE
Wrong review count after loading the page

### ISSUE THREAD

**Issue by sodbileg** [woocommerce/woocommerce#16645] opened 2017-08-30 03:11 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Navigate to a specific product page with reviews.

## Expected/actual behavior

When I follow this step, the review count changes from 4 to 1 like on the image below. 4 is the right review count which can be seen on the tab title below. Also after refreshing the page, I can reproduce the issue.

Theme: Default Twenty Seventeen
Data: WooCommerce dummy data

![](https://cdn-std.dprcdn.net/files/acc_195640/kmUWRb)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: ❌ 5.5.9-1ubuntu4.20 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Contact Form 7: by Takayuki Miyoshi – 4.9
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Intuitive Custom Post Order: by hijiri – 3.1.0
Kirki Toolkit: by Aristeides Stathopoulos – 3.0.9
MailChimp for WordPress: by ibericode – 4.1.6
Meta Box: by MetaBox.io – 4.12.3
Google Analytics by WebKinder: by WebKinder – 1.6.2
WooCommerce: by Automattic – 3.1.2
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #257 - /shop/
Cart: #258 - /cart/
Checkout: #259 - /checkout/
My account: #260 - /my-account/

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment] 2017-08-30 10:21
Without a link to the site I cannot verify this. It's not happening on other installs, and this is not something that is dynamic or updated un the fly. This is static HTML. I suspect some kind of caching mechanism or plugin conflict. You tested with a default theme but plugins are active.

Notice the text also says "1 customer reviews". If WC was outputting this is would say "1 customer review" - the localisation is wrong. Maybe you have code or a plugin present which updates the 'count' span element which wraps the count here?

Feel free to respond back with a link to the site, but since this is not reproducible I'm closing the issue for now.

Thanks

**Closed by mikejolley** 2017-08-30 10:21 UTC
