### ISSUE TITLE
3.0 Up-selling and Cross-selling not working between product variations.

### ISSUE THREAD

**Issue by edvinbrobeck** [woocommerce/woocommerce#13937] opened 2017-04-05 11:23 UTC
### EXPLANATION OF THE ISSUE

When linking products in Up-selling and Cross-selling fields on a product that has variations, you attach linked objects to the parent product/entity. When a variation is added to cart, the object ID that `WC()->cart->get_cross_sells()` is the variation ID, which has no linked product ID's attached.

### STEPS TO REPRODUCE THE ISSUE

1. Add a product with variants
2. Connect linked products in up-selling, cross-selling on the created product.
3. Visit product page or Add a variant of created product to cart, and visit cart.

No link, since local development - not gone live yet
### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://admin.NNNNNNN
Site URL: https://admin.NNNNNN/wp
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.11
Enhanced Media Library: by wpUXsolutions – 2.4.4
Slider Revolution: by ThemePunch – 5.4.1
Search & Replace: by Inpsyde GmbH – 3.1.2
WPML Multilingual CMS: by OnTheGoSystems – 3.6.3
SVG Support: by Benbodhi – 2.3.7
WooCommerce Klarna Gateway: by WooCommerce – 2.3.3
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce Mapiful integration: by Edvin Brobeck – 1.0
WooCommerce Multilingual: by OnTheGoSystems – 4.1.2
WooCommerce Product Add-ons: by WooCommerce – 2.8.1
WooCommerce Shipping Estimates: by SkyVerge – 2.0.0
WooCommerce: by Automattic – 3.0.0
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WPML Media: by OnTheGoSystems – 2.1.24
WPML String Translation: by OnTheGoSystems – 2.5.2
WPML Translation Management: by OnTheGoSystems – 2.2.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: NNNNN Site V3
Version: 0.1.0
Author URL: http://NNNNN.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: mapiful/.DS_Store
mapiful/woocommerce/archive-product.php
mapiful/woocommerce/auth/footer.php
mapiful/woocommerce/auth/form-grant-access.php
mapiful/woocommerce/auth/form-login.php
mapiful/woocommerce/auth/header.php
mapiful/woocommerce/cart/cart-empty.php
mapiful/woocommerce/cart/cart-item-data.php
mapiful/woocommerce/cart/cart-shipping.php
mapiful/woocommerce/cart/cart-totals.php
mapiful/woocommerce/cart/cross-sells.php
mapiful/woocommerce/cart/mini-cart.php
mapiful/woocommerce/cart/proceed-to-checkout-button.php
mapiful/woocommerce/cart/shipping-calculator.php
mapiful/woocommerce/checkout/cart-errors.php
mapiful/woocommerce/checkout/form-billing.php
mapiful/woocommerce/checkout/form-checkout.php
mapiful/woocommerce/checkout/form-coupon.php
mapiful/woocommerce/checkout/form-login.php
mapiful/woocommerce/checkout/form-pay.php
mapiful/woocommerce/checkout/form-shipping.php
mapiful/woocommerce/checkout/payment-method.php
mapiful/woocommerce/checkout/payment.php
mapiful/woocommerce/checkout/review-order.php
mapiful/woocommerce/checkout/terms.php
mapiful/woocommerce/checkout/thankyou.php
mapiful/woocommerce/content-product.php
mapiful/woocommerce/content-product_cat.php
mapiful/woocommerce/content-single-product.php
mapiful/woocommerce/content-widget-product.php
mapiful/woocommerce/emails/.DS_Store
mapiful/woocommerce/emails/admin-cancelled-order.php
mapiful/woocommerce/emails/admin-failed-order.php
mapiful/woocommerce/emails/admin-new-order.php
mapiful/woocommerce/emails/customer-completed-order.php
mapiful/woocommerce/emails/customer-invoice.php
mapiful/woocommerce/emails/customer-new-account.php
mapiful/woocommerce/emails/customer-note.php
mapiful/woocommerce/emails/customer-on-hold-order.php
mapiful/woocommerce/emails/customer-processing-order.php
mapiful/woocommerce/emails/customer-refunded-order.php
mapiful/woocommerce/emails/customer-reset-password.php
mapiful/woocommerce/emails/email-addresses.php
mapiful/woocommerce/emails/email-customer-details.php
mapiful/woocommerce/emails/email-footer.php
mapiful/woocommerce/emails/email-header.php
mapiful/woocommerce/emails/email-order-details.php
mapiful/woocommerce/emails/email-order-items.php
mapiful/woocommerce/emails/email-styles.php
mapiful/woocommerce/emails/plain/admin-cancelled-order.php
mapiful/woocommerce/emails/plain/admin-failed-order.php
mapiful/woocommerce/emails/plain/admin-new-order.php
mapiful/woocommerce/emails/plain/customer-completed-order.php
mapiful/woocommerce/emails/plain/customer-invoice.php
mapiful/woocommerce/emails/plain/customer-new-account.php
mapiful/woocommerce/emails/plain/customer-note.php
mapiful/woocommerce/emails/plain/customer-on-hold-order.php
mapiful/woocommerce/emails/plain/customer-processing-order.php
mapiful/woocommerce/emails/plain/customer-refunded-order.php
mapiful/woocommerce/emails/plain/customer-reset-password.php
mapiful/woocommerce/emails/plain/email-addresses.php
mapiful/woocommerce/emails/plain/email-customer-details.php
mapiful/woocommerce/emails/plain/email-order-details.php
mapiful/woocommerce/emails/plain/email-order-items.php
mapiful/woocommerce/global/breadcrumb.php
mapiful/woocommerce/global/form-login.php
mapiful/woocommerce/global/quantity-input.php
mapiful/woocommerce/global/sidebar.php
mapiful/woocommerce/global/wrapper-end.php
mapiful/woocommerce/global/wrapper-start.php
mapiful/woocommerce/loop/add-to-cart.php
mapiful/woocommerce/loop/loop-end.php
mapiful/woocommerce/loop/loop-start.php
mapiful/woocommerce/loop/no-products-found.php
mapiful/woocommerce/loop/orderby.php
mapiful/woocommerce/loop/pagination.php
mapiful/woocommerce/loop/price.php
mapiful/woocommerce/loop/rating.php
mapiful/woocommerce/loop/result-count.php
mapiful/woocommerce/loop/sale-flash.php
mapiful/woocommerce/myaccount/dashboard.php
mapiful/woocommerce/myaccount/downloads.php
mapiful/woocommerce/myaccount/form-add-payment-method.php
mapiful/woocommerce/myaccount/form-edit-account.php
mapiful/woocommerce/myaccount/form-edit-address.php
mapiful/woocommerce/myaccount/form-login.php
mapiful/woocommerce/myaccount/form-lost-password.php
mapiful/woocommerce/myaccount/form-reset-password.php
mapiful/woocommerce/myaccount/lost-password-confirmation.php
mapiful/woocommerce/myaccount/my-account.php
mapiful/woocommerce/myaccount/my-address.php
mapiful/woocommerce/myaccount/my-downloads.php
mapiful/woocommerce/myaccount/my-orders.php
mapiful/woocommerce/myaccount/navigation.php
mapiful/woocommerce/myaccount/orders.php
mapiful/woocommerce/myaccount/payment-methods.php
mapiful/woocommerce/myaccount/view-order.php
mapiful/woocommerce/notices/error.php
mapiful/woocommerce/notices/notice.php
mapiful/woocommerce/notices/success.php
mapiful/woocommerce/order/form-tracking.php
mapiful/woocommerce/order/order-again.php
mapiful/woocommerce/order/order-details-customer.php
mapiful/woocommerce/order/order-details-item.php
mapiful/woocommerce/order/order-details.php
mapiful/woocommerce/order/tracking.php
mapiful/woocommerce/product-searchform.php
mapiful/woocommerce/single-product/add-to-cart/external.php
mapiful/woocommerce/single-product/add-to-cart/grouped.php
mapiful/woocommerce/single-product/add-to-cart/simple.php
mapiful/woocommerce/single-product/add-to-cart/variable.php
mapiful/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
mapiful/woocommerce/single-product/add-to-cart/variation.php
mapiful/woocommerce/single-product/meta.php
mapiful/woocommerce/single-product/photoswipe.php
mapiful/woocommerce/single-product/price.php
mapiful/woocommerce/single-product/product-attributes.php
mapiful/woocommerce/single-product/product-image.php
mapiful/woocommerce/single-product/product-thumbnails.php
mapiful/woocommerce/single-product/rating.php
mapiful/woocommerce/single-product/related.php
mapiful/woocommerce/single-product/review-meta.php
mapiful/woocommerce/single-product/review-rating.php
mapiful/woocommerce/single-product/review.php
mapiful/woocommerce/single-product/sale-flash.php
mapiful/woocommerce/single-product/share.php
mapiful/woocommerce/single-product/short-description.php
mapiful/woocommerce/single-product/stock.php
mapiful/woocommerce/single-product/tabs/additional-information.php
mapiful/woocommerce/single-product/tabs/description.php
mapiful/woocommerce/single-product/tabs/tabs.php
mapiful/woocommerce/single-product/title.php
mapiful/woocommerce/single-product/up-sells.php
mapiful/woocommerce/single-product-reviews.php
mapiful/woocommerce/single-product.php
mapiful/woocommerce/taxonomy-product_cat.php
mapiful/woocommerce/taxonomy-product_tag.php

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: Klarna Checkout page points to an invalid URL. Make sure you are using a valid
absolute URL. Relative URLs are not allowed.

Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`
</details>

**Comment by edvinbrobeck** [comment] 2017-04-05 11:26
Got it working for my instance, unsure if this is the correct way of solving, or if this causes other issues, but it at least show's the problem in a comprehendable manner.

In `WC_Cart (class-wc-cart.php)`

Changing from:
`public function get_cross_sells() {
		$cross_sells = array();
		$in_cart = array();
		if ( ! $this->is_empty() ) {
			foreach ( $this->get_cart() as $cart_item_key => $values ) {
				if ( $values['quantity'] > 0 ) {
					$cross_sells = array_merge( $values['data']->get_cross_sell_ids(), $cross_sells );
					$in_cart[]   = $values['product_id'];
				}
			}
		}
		$cross_sells = array_diff( $cross_sells, $in_cart );
		return $cross_sells;
	}
`

To:
`
public function get_cross_sells() {
		$cross_sells = array();
		$in_cart = array();
		if ( ! $this->is_empty() ) {
			foreach ( $this->get_cart() as $cart_item_key => $values ) {
				if ( $values['quantity'] > 0 ) {

				    if($values['data']->post_type == 'product_variation'){
				        $parent = new WC_Product($values['data']->parent_id);
				        $cross_sells_ids = $parent->get_cross_sell_ids();
                    } else {
                        $cross_sells_ids = $values['data']->get_cross_sell_ids();
                    }

					$cross_sells = array_merge( $cross_sells_ids, $cross_sells );
					$in_cart[]   = $values['product_id'];
				}
			}
		}
		$cross_sells = array_diff( $cross_sells, $in_cart );
		return $cross_sells;
	}
`

**Comment by mikejolley** [comment] 2017-04-05 11:51
This should be fixed in cart. There is no problem with adding variations to cart directly.

**Comment by edvinbrobeck** [comment] 2017-04-05 11:58
@mikejolley Not sure if i described the issue correctly. It was never an issue of adding products to cart or not.

After upgrading to 3.0 products previously displayed on i.e. `/cart` in the cross-selling/collaterals section did no longer show up.

In my specific case i have a base product, with variations. The linked products are attached to the base product object. The products added to the cart are product variation objects.

When `WC()->cart->get_cross_sells()` is looking for connected items to the variation ID instead of the parent object.

**Comment by mikejolley** [comment] 2017-04-05 22:29
Confirmed no issue; when you set cross sells, you can choose to pick either the parent or the variation. 

If you choose the variation, you can add it to cart directly. 
If you choose the parent, there is a 'select options' link.

This seems to be working fine.

**Closed by mikejolley** 2017-04-05 22:29 UTC
