### ISSUE TITLE
Using WC_Shortcode_My_Account::edit_address( 'billing' ) changes won't save

### ISSUE THREAD

**Issue by SeynalKim** [woocommerce/woocommerce#27497] opened 2020-08-27 06:34 UTC
I tried using `WC_Shortcode_My_Account::edit_address( 'billing' );` to show the billing form and its working fine. However, upon saving, the page just refreshes but changes won't save.

**Comment by tammullen** [comment] 2020-08-28 21:20
Hi @SeynalKim 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-08-28 21:20 UTC

**Comment by SeynalKim** [comment] 2021-01-10 14:01
It seems like everyone is pointing out to each of you.
