### ISSUE TITLE
auto update warning

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#27337] opened 2020-08-14 11:28 UTC
I get dozens of these in my admin area going to the plugins tab.  It does not matter what version i run 4.3.3 or 4.4.0 rc1

also wp 5.5 or wp 5.6-alpha-48790 does not change this.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'auto_update_woocommerce' not found or invalid function name in /var/docs/server.tst/public/wp-includes/class-wp-hook.php on line 287

![afbeelding](https://user-images.githubusercontent.com/6078370/90245003-1fb66680-de32-11ea-8f29-f89f54d61274.png)

**Comment by juliaamosova** [comment] 2020-08-14 18:47
Hi @BackuPs,

Thanks for raising the issue. Can you please confirm if you are using the [WooCommerce Beta Tester](https://wordpress.org/plugins/woocommerce-beta-tester/) plugin to switch to development versions of WooCommerce?

If so, these warnings are caused by the WooCommerce Beta Tester plugin - we have an issue filed for it as well: https://github.com/woocommerce/woocommerce-beta-tester/issues/68.

**Comment by BackuPs** [comment] 2020-08-15 07:40
Hi

Yes i am using the woocommerce beta tester plugin. Thank you for the additional information.

**Comment by tammullen** [comment] 2020-08-26 16:39
Thanks @BackuPs 

Closing this as it is resolved.

**Closed by tammullen** 2020-08-26 16:39 UTC
Labels: status: needs feedback
