### ISSUE TITLE
Unable to select product in popup modal using an offloaded MySQL database 

### ISSUE THREAD

**Issue by piperis1** [woocommerce/woocommerce#28629] opened 2020-12-18 21:36 UTC
We're using a managed database through DigitalOcean and whilst every part of the site works great, with many plugins working well too, I've recently noticed that the "add product" popup modal when editing/adding an order through the backend, no products appear. I've disabled all plugins and gone to storefront.

Please see video here - https://www.loom.com/share/2c25f3a130af461ca48225c9ddebd9da

I have also brought the database locally, keeping all plugins and theme enabled and it works. There are no errors that I can see on Digitalocean's side.

Thanks!

**Comment by juliaamosova** [comment] 2020-12-23 22:26
Hi @piperis1,

Thanks for raising the issue. I am not immediately sure what could be going on yet. Could you please confirm how did you create products on the site:

- Manually on the site?
- Imported via CSV file?
- Through some migration tool?
- Any other way?

This will help us to narrow down the issue and try to understand its cause further.

**Comment by piperis1** [comment] 2020-12-23 22:52
Manually on the site, always

**Comment by juliaamosova** [comment] 2021-01-10 21:56
Thanks for your patience @piperis1!

It seems like a similar issue had been reported which contains the steps to try to reproduce it https://github.com/woocommerce/woocommerce/issues/28722. We will investigate it further and will provide a proper answer after.

**Comment by piperis1** [comment] 2021-01-10 22:05
I sorted mine out, thanks

Issue is if the database server has ansi_quotes mode enabled. Removing that
sorted the issue.
Would be good to see this as part of the status tool or check WC performs.

**Comment by tammullen** [comment] 2021-01-11 22:15
Thanks for the update @piperis1 

As your issue went away with disabling `ANSI_QUOTES` It looks like the issue you are having is related to https://github.com/woocommerce/woocommerce/issues/28417

I'm closing this for now as I don't think any further action is needed. Please feel free to comment on here in case we missed something. We’d be happy to take another look.

**Closed by tammullen** 2021-01-11 22:15 UTC
Labels: has feedback
