### ISSUE TITLE
Thank you for your payment emails for COD payment method

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#22037] opened 2018-11-25 11:08 UTC
When using "Cash On Delivery" payment method, users still receive an email saying "Thank you for your payment" which is "Processing order" email template. The payment haven't been received yet so it is confusing for customers:

![http://cld.wthms.co/pIzoMJ](http://cld.wthms.co/pIzoMJ+) 
Full Size: http://cld.wthms.co/pIzoMJ

**Describe the solution you'd like**
An email for placing the order, without mentioning that the payment has been received

I understand that it's an edgy case, but is there any logic behind that?

**Comment by slyermedia** [comment] 2018-11-26 10:54
Got the same problem..

**Comment by jobthomas** [comment] 2018-11-26 14:30
Duplicate of #21742

**Comment by janeng424** [comment] 2018-12-05 05:45
Same problem here

**Comment by kloon** [comment] 2019-01-11 12:38
See #22418

**Closed by kloon** 2019-01-11 12:38 UTC
Labels: bug, has pull request
