### ISSUE TITLE
Under Products > All Products,  there used to be a drop down list of categories when you used "filter by categoried".  Now it asks you to put in the first 3 letters.  This means actually knowing what you have called a category.  With a site with over 30 categories, this is causing an issue.

### ISSUE THREAD

**Issue by JaneNorris** [woocommerce/woocommerce#18543] opened 2018-01-21 02:20 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by dougaitken** [comment] 2018-01-22 10:07
Closing, dupe of #18544

**Comment by dougaitken** [comment] 2018-01-22 10:08
This is a dupe of #18544

**Closed** 2018-01-22 10:25 UTC
