### ISSUE TITLE
Rest API 401 (Woo Support sent me here)

### ISSUE THREAD

**Issue by New-Hope-Mills** [woocommerce/woocommerce#24338] opened 2019-08-06 16:24 UTC
**Describe the bug**
When trying to connect to WooCommerce and [Kosmos Central](https://www.kosmoscentral.com/) via RestAPI it gives a 401 error. Kosmos and WooCommerce support have both tried to help to no avail. Woo support told me to post here.

**To Reproduce**

*Method 1:*
1. Log into [Kosmos eSync](https://www.kosmosesync.com/login)
2. Add action > WooCommerce
3. Description: NHM Woo
4. URL: https://newhopemills.com
5. API keys from WooCommerce > Settings > Advanced > Rest API (read/write, created with full admin account)

*Method 2:*
1. Using [Postman API Environment](https://www.getpostman.com/), create "New GET request"
2. Basic Auth
3. URL: http://newhopemills.com/wp-json/wc/v3/orders or http://newhopemills.com/wp-json/wc/v3/products
4. Username and password are consumer key and consumer secret respectively.
5. Error: ```{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}```  
This happens with SSL verification enabled or disabled via Postman > Settings > SSL certification verification.

**Screenshots**
Method 1:
![Kosmos](https://user-images.githubusercontent.com/53828464/62557358-d60d6600-b844-11e9-974b-826e3ad52f7f.png)

Method 2:
![postman](https://user-images.githubusercontent.com/53828464/62557161-6d25ee00-b844-11e9-93ce-0c3ed9eea5a6.png)

**Expected behavior**
For Kosmos Central to be authorized to sync data from WooCommerce to Revel, our Point of Sale. (Revel connects fine).

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] Server is already running another sync service via Rest API connecting to WooCommerce, so there shouldn't be a problem with the server.
- [x] Folowed steps [here](https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#401-unauthorized) for common connection issues to no avail.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://newhopemills.com
Site address (URL): https://newhopemills.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.19
PHP Post Max Size: 768 MB
PHP Time Limit: 600
PHP Max Input Vars: 16384
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.25-MariaDB
Max Upload Size: 768 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 558.40MB
Database Data Size: 351.42MB
Database Index Size: 206.98MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.20MB + Index: 0.08MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.95MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_comments: Data: 0.02MB + Index: 0.09MB
wpstg0_links: Data: 0.02MB + Index: 0.02MB
wpstg0_options: Data: 2.52MB + Index: 0.13MB
wpstg0_postmeta: Data: 1.52MB + Index: 0.42MB
wpstg0_posts: Data: 1.52MB + Index: 0.13MB
wpstg0_slp_extendo_meta: Data: 0.02MB + Index: 0.05MB
wpstg0_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wpstg0_store_locator: Data: 0.02MB + Index: 0.05MB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB
wpstg0_term_relationships: Data: 0.06MB + Index: 0.05MB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpstg0_usermeta: Data: 0.05MB + Index: 0.03MB
wpstg0_users: Data: 0.02MB + Index: 0.05MB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_sessions: Data: 1.52MB + Index: 0.02MB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpstg1_commentmeta: Data: 0.09MB + Index: 0.14MB
wpstg1_comments: Data: 12.52MB + Index: 16.09MB
wpstg1_db7_forms: Data: 0.05MB + Index: 0.00MB
wpstg1_fg_redirect: Data: 0.02MB + Index: 0.00MB
wpstg1_links: Data: 0.02MB + Index: 0.02MB
wpstg1_nf3_actions: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_fields: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_forms: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_objects: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wpstg1_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
wpstg1_options: Data: 7.52MB + Index: 1.52MB
wpstg1_postmeta: Data: 13.52MB + Index: 13.03MB
wpstg1_posts: Data: 33.52MB + Index: 10.09MB
wpstg1_slp_extendo_meta: Data: 0.02MB + Index: 0.05MB
wpstg1_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wpstg1_social_users: Data: 0.02MB + Index: 0.02MB
wpstg1_store_locator: Data: 0.02MB + Index: 0.05MB
wpstg1_termmeta: Data: 0.05MB + Index: 0.03MB
wpstg1_terms: Data: 0.05MB + Index: 0.03MB
wpstg1_term_relationships: Data: 1.52MB + Index: 1.52MB
wpstg1_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wpstg1_usermeta: Data: 6.52MB + Index: 9.03MB
wpstg1_users: Data: 0.38MB + Index: 0.36MB
wpstg1_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wpstg1_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wpstg1_wc_customer_lookup: Data: 0.27MB + Index: 0.23MB
wpstg1_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg1_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wpstg1_wc_order_product_lookup: Data: 0.28MB + Index: 0.30MB
wpstg1_wc_order_stats: Data: 0.14MB + Index: 0.17MB
wpstg1_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wpstg1_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wpstg1_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg1_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wpstg1_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.03MB
wpstg1_woocommerce_order_items: Data: 0.33MB + Index: 0.11MB
wpstg1_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg1_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_sessions: Data: 1.52MB + Index: 0.05MB
wpstg1_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg1_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg1_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg1_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg1_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpstg1_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wpstg1_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.06MB + Index: 0.06MB
wp_comments: Data: 66.61MB + Index: 74.67MB
wp_db7_forms: Data: 0.03MB + Index: 0.00MB
wp_fg_redirect: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 12.42MB + Index: 1.11MB
wp_postmeta: Data: 38.58MB + Index: 22.03MB
wp_posts: Data: 125.64MB + Index: 34.73MB
wp_slp_extendo_meta: Data: 0.02MB + Index: 0.05MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_social_users: Data: 0.02MB + Index: 0.02MB
wp_store_locator: Data: 0.02MB + Index: 0.05MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.05MB + Index: 0.03MB
wp_term_relationships: Data: 7.48MB + Index: 4.50MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 5.52MB + Index: 8.03MB
wp_users: Data: 0.33MB + Index: 0.34MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Data: 0.27MB + Index: 0.17MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.42MB + Index: 0.28MB
wp_wc_order_stats: Data: 0.13MB + Index: 0.11MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

amn_mi-lite: 1
attachment: 387
blocks: 9
custom_css: 4
elementor_library: 2
et_pb_layout: 5
et_pb_layout_stashed: 8
featured_item: 8
happyform: 1
happyforms-message: 3
jetpack_migration: 2
jp_img_sitemap: 111
jp_sitemap: 111
jp_sitemap_master: 111
jp_vid_sitemap: 111
layout: 3
nav_menu_item: 20
oembed_cache: 2
page: 68
post: 60
product: 65
product_variation: 26
revision: 772
scheduled-action: 3446
shop_coupon: 1360
shop_order: 1243
shop_order_refund: 48
wpcf7_contact_form: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.5

### Inactive Plugins (23) ###

Beeketing For WooCommerce: by Beeketing – 3.8.15
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Contact Form 7 Conditional Fields Pro: by Jules Colle – 1.6.4
Conversio for WooCommerce: by Receiptful – 1.5.1 – Not tested with the active version of WooCommerce
Duplicate Post: by Enrico Battocchi – 3.2.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.7.1
Jetpack by WordPress.com: by Automattic – 7.5.3
Kosmos eSync Dashboard Connector: by Kosmos Central – 1.0.0
Nextend Social Login: by Nextendweb – 3.0.20
No Category Base (WPML): by Marios Alexandrou – 1.3
Product Reviews Import Export (Basic): by WebToffee – 1.2.4
ShipWorks Connector: by AdvancedCreation – 4.5.12 – Not tested with the active version of WooCommerce
Smush: by WPMU DEV – 3.2.2.1
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.21
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.16

WooCommerce Admin: by WooCommerce – 0.16.0
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.16
WooCommerce Subscriptions: by Automattic – 2.5.7
WooCommerce UPS Shipping: by WooCommerce – 3.2.16
WooCommerce USPS Shipping: by WooCommerce – 4.4.27
WooSidebars: by WooCommerce – 1.4.5
WP Staging: by WP-Staging – 2.6.1
YITH WooCommerce Wishlist: by YITH – 2.2.12

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4712 - /shop/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /my-account/
Terms and conditions: #3081 - /terms-of-sale/

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3,384
Oldest: 2019-07-06 15:34:29 +0000
Newest: 2019-08-06 14:32:31 +0000

Pending: 1
Oldest: 2019-08-09 19:28:08 +0000
Newest: 2019-08-09 19:28:08 +0000

Canceled: 45
Oldest: 2019-07-08 15:40:01 +0000
Newest: 2019-08-06 15:32:32 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 16
Oldest: 2019-06-07 04:02:20 +0000
Newest: 2019-08-06 01:22:39 +0000

`
```
</details>

**Comment by claudiosanches** [comment] 2019-08-06 21:24
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried follow the steps you provided and it appeared to work correctly.

It could be that your user don't have enough permissions, or even not setting properly the authentication. There's no issue or bug, if is returning 401, it's because something still is wrong with your request.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Closed by claudiosanches** 2019-08-06 21:24 UTC

**Comment by zwiesman31** [comment] 2019-08-06 21:51
@New-Hope-Mills I just opened a ticket for you in your WooCommerce.com account about this. Please follow up with any further details for troubleshooting there. Thanks!

**Comment by slmcdee** [comment] 2019-08-23 19:23
I'm having pretty much the same problem... and I've tried pretty much all the solutions... and nothing has worked. @New-Hope-Mills did you ever get a solution.

**Comment by New-Hope-Mills** [comment] 2019-08-23 19:39
@slmcdee - Yeah, it ended up being a problem with FastCGI PHP. This is what my host stated and patched:

```
This issue should now be resolved. In testing, we found that the "Authorization" header was indeed being properly set:

[root@sip1-162 %Replace with your root location%]$ cat test.php

$ curl https://newhopemills.com/test.php -u user:pass | grep -A 1 Authorization
["Authorization"]=>
string(18) "Basic dXNlcjpwYXNz"

However, a known issue with PHP FastCGI is preventing this header from being properly read. FastCGI changes the variables passed into Apache from $x to REDIRECT_$x -- in this case, it changed the HTTP_AUTHORIZATION header, which WooCommerce is expecting, to REDIRECT_HTTP_AUTHORIZATION. To correct this, we added code to the domain's Apache vhost to manually set the correct variable:

SetEnvIf REDIRECT_HTTP_AUTHORIZATION (.+) HTTP_AUTHORIZATION=$1
SetEnvIf HTTP_CONTENT_TYPE (.+) CONTENT_TYPE=$1

This will likely occur with any server using FastCGI. I would recommend you post this information back to WooCommerce, as it is likely other users on FastCGI servers are experiencing the same issue. They could easily patch this by checking for the presence of the REDIRECT_HTTP_AUTHORIZATION header as well.
```

WooCommerce did add this to their Wiki - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API/8e69ca78f418858ae95e6c7352cdc8b4e6a5f9b2#401-unauthorized . See the link under "401 Unauthorized" section.

I ended up having the problem come back a few days later, even though the fix was still in place. My host then made another change, and it seemed to have fixed it, I haven't been able to jump back in since. 

That said, this is what my host did the second time:

```
Thanks for your patience. I've gotten this fixed again. The issue was similar, but slightly different -- this time, the credentials were being passed as "Authorization" instead of "HTTP_AUTHORIZATION", for some reason. I added another condition to the vhost to rewrite this as well:

 SetEnvIf Authorization (.+) HTTP_AUTHORIZATION=$1

I'm now seeing the expected response:

$ curl -IL --user ck_b32692391fb43ed9c4d1eb67942aa4023df9cb5b:cs_f9f1c34b824c8834ab35c155e7fde3dd49dc1125 https://newhopemills.com/wp-json/wc/v3/products
HTTP/1.1 200 OK
```

**Comment by arnab-rupa** [comment] 2024-01-06 09:44
I have been trying in my localhost(XAMPP latest version).
![ERROR 401](https://github.com/woocommerce/woocommerce/assets/154499789/699cedf9-dede-4ca3-85e3-88e898732499)

![ERROR 401 OAUTH 1 0](https://github.com/woocommerce/woocommerce/assets/154499789/dafb0c3b-5c7e-4f6b-91dc-1016815aaa68)


This error is shown

```
require "woocommerce_api"

woocommerce = WooCommerce::API.new(
  "https://example.com",
  "consumer_key",
  "consumer_secret",
  {
    wp_json: true,
    version: "wc/v1",
    query_string_auth: true
  }
)

```
this code provided by stackoverflow.

Please help me in this regard
