### ISSUE TITLE
Product_page on frontpage

### ISSUE THREAD

**Issue by nootarius46** [woocommerce/woocommerce#27654] opened 2020-09-11 10:03 UTC
Hey!

I would like to display one of my product page on my frontpage. I tried it with simple shortcode: [product_page id=”362″] (This id my test product)

This works well but there are some problems. Why i have a Woo picture and title and price in 2 column when i set just one column. And why i have desription and in my description my woo picture price and title again with other products twice.

If i change something the changes works “in description product page”. So i just want import my product page exactly or disappear second product page and put off my product from description.

Which shortcodes should i use or how to display my one of my product pages exactly?

Thanks guys and sorry for my english.

Ps.: I use Divi theme.
![problem](https://user-images.githubusercontent.com/71127531/92908694-c50b2d00-f426-11ea-952b-b05100bf7fba.png)

**Comment by juliaamosova** [comment] 2020-09-11 17:30
Hi @nootarius46,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by juliaamosova** 2020-09-11 17:30 UTC
