### ISSUE TITLE
Autocomplete triggers Webhook "created" twice.

### ISSUE THREAD

**Issue by derweili** [woocommerce/woocommerce#20685] opened 2018-07-02 13:08 UTC
**Describe the bug**
I'm using the code from: https://docs.woocommerce.com/document/automatically-complete-orders/ to change all orders automatically to completed. (To enable downloads immediately)

Since I updated to the latest WooCommerce Version (I skipped some versions) my "order created" webhook is triggered twice.

While inspecting the webhook log files I found out that both sent hooks are almost the same except one difference: 
The "completed at" value within the body of the first hook is always 
`completed_at\":\"1970-01-01T00:00:00Z\`
The "completed_at" value within the body of the second hook has always the correct datetime.
For example 
`\"completed_at\":\"2018-07-02T11:37:55Z\"`

**To Reproduce**
1. Paste the Code from https://docs.woocommerce.com/document/automatically-complete-orders/ in your functions.php or in a custom plugin
2. Create a webhook with the topic "order created"
3. Place an order
4. See the Webhook Log files

**Screenshots**

![bildschirmfoto 2018-07-02 um 15 00 22](https://user-images.githubusercontent.com/6911678/42165608-e1fdcf30-7e08-11e8-82d1-8639016a371c.png)
![bildschirmfoto 2018-07-02 um 15 01 10](https://user-images.githubusercontent.com/6911678/42165609-e21742da-7e08-11e8-9757-5ce9e424e6f8.png)
![bildschirmfoto 2018-07-02 um 15 01 27](https://user-images.githubusercontent.com/6911678/42165610-e2315d8c-7e08-11e8-861e-bdd97df0750c.png)

**Expected behavior**
I expected the webhook to be called only once, as it has been running for 2 years.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://skillqube-webhook.test
Site URL: http://skillqube-webhook.test
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.33 (Unix) OpenSSL/1.0.2o PHP/7.2.4
PHP Version: 7.2.4
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
LibreSSL/2.0.20

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.14-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_yjnisvveei_
MaxMind GeoIP Database: ❌ Die MaxMind GeoIP Datenbank existiert nicht - Die Geolokalisierung (Ortung) wird nicht funktionieren. Sie können sie von https://dev.maxmind.com/geoip/geoip2/geolite2/ manuell herunterladen und in den Pfad:  installieren. Scrollen Sie dazu nach unten bis zu „Downloads“ und laden Sie die Datei „MaxMind DB binär
gzipped“ vom Typ „GeoLite2 Country“ herunter. Denken Sie bitte daran
die Datei GeoLite2-Country_xxxxxxxx.tar.gz zu entpacken und nur die entpackte Datei GeoLite2-Country.mmdb hochzuladen.

Datenbank-Gesamtgröße: 88.33MB
Datenbank-Datengröße: 55.93MB
Datenbank-Indexgröße: 32.40MB
wp_yjnisvveei_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB
wp_yjnisvveei_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_yjnisvveei_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_yjnisvveei_woocommerce_downloadable_product_permissions: Daten: 1.52MB + Index: 2.16MB
wp_yjnisvveei_woocommerce_order_items: Daten: 0.36MB + Index: 0.14MB
wp_yjnisvveei_woocommerce_order_itemmeta: Daten: 2.52MB + Index: 3.03MB
wp_yjnisvveei_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_yjnisvveei_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB
wp_yjnisvveei_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB
wp_yjnisvveei_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_yjnisvveei_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_yjnisvveei_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
bexio_client: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_afap_logs: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_commentmeta: Daten: 0.44MB + Index: 0.27MB
wp_yjnisvveei_comments: Daten: 1.52MB + Index: 0.98MB
wp_yjnisvveei_ewwwio_images: Daten: 0.09MB + Index: 0.06MB
wp_yjnisvveei_links: Daten: 0.02MB + Index: 0.02MB
wp_yjnisvveei_nf3_actions: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_nf3_action_meta: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_nf3_fields: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_nf3_field_meta: Daten: 0.06MB + Index: 0.00MB
wp_yjnisvveei_nf3_forms: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_nf3_form_meta: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_nf3_objects: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_nf3_object_meta: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_nf3_relationships: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_options: Daten: 2.48MB + Index: 0.38MB
wp_yjnisvveei_postmeta: Daten: 22.56MB + Index: 18.06MB
wp_yjnisvveei_posts: Daten: 19.48MB + Index: 1.31MB
wp_yjnisvveei_realmedialibrary: Daten: 0.02MB + Index: 0.00MB
wp_yjnisvveei_termmeta: Daten: 0.06MB + Index: 0.03MB
wp_yjnisvveei_terms: Daten: 0.06MB + Index: 0.03MB
wp_yjnisvveei_term_relationships: Daten: 0.17MB + Index: 0.13MB
wp_yjnisvveei_term_taxonomy: Daten: 0.06MB + Index: 0.06MB
wp_yjnisvveei_usermeta: Daten: 3.52MB + Index: 5.03MB
wp_yjnisvveei_users: Daten: 0.20MB + Index: 0.25MB
wp_yjnisvveei_user_activity: Daten: 0.09MB + Index: 0.00MB
wp_yjnisvveei_wc_download_log: Daten: 0.09MB + Index: 0.09MB
wp_yjnisvveei_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
wp_yjnisvveei_yoast_seo_links: Daten: 0.11MB + Index: 0.05MB
wp_yjnisvveei_yoast_seo_meta: Daten: 0.06MB + Index: 0.00MB

### Post Type Counts ###

360view: 2
acf-field: 173
acf-field-group: 22
ajde_events: 115
attachment: 1636
bi-debug: 22
course: 16
custom_css: 1
export_template: 1
homeslider: 5
lesson: 72
nav_menu_item: 64
oembed_cache: 7
page: 108
post: 169
product: 87
product_variation: 145
question: 27
quiz: 86
redirect_rule: 105
revision: 2920
scheduled_export: 2
shop_coupon: 77
shop_order: 1718
shop_order_refund: 3
wp_block: 2
wpcf7_contact_form: 13

### Security ###

Secure connection (HTTPS): ❌
					Ihr Shop benutzt kein HTTPS. Erfahren Sie mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: von Automattic – 3.4.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)
rated-5 (rated-5-2)

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /shop/warenkorb/
Kasse: #6 - /shop/warenkorb/kasse/
Mein Konto: #7 - /mein-konto/
Allgemeine Geschäftsbedingungen: #335 - /allgemeine_geschaeftsbedingungen/

### Theme ###

Name: Twenty Thirteen
Version: 1.7 – 2.4 ist verfügbar
Author URL: https://wordpress.org/
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rodrigoprimo** [comment] 2018-07-03 18:31
I can confirm that the webhook is triggered twice when the snippet to change the order status is used. I'm not sure if that is a bug or if it is intentional. @claudiosanches, could you please take a look as you know the webhook system better than I do?

@derweili, you mentioned that previously you were running an older version of WooCommerce and, in that version, the webhook was triggered only once. Do you happen to remember which version is that?

**Comment by derweili** [comment] 2018-07-04 06:50
Thank's for you reply. The last version I can confirm it worked well is `3.3.3`.

**Comment by derweili** [comment] 2018-07-12 09:19
Today I found out, that not every Order is send twice.
Can't find a pattern when this happens and when not. 

Some of the orders that are send a single time have the correct "completed_at" value but some have `1970-01-01T00:00:00Z` as a value.
So even there Is no pattern recognizable.

@claudiosanches do you have any information about webhock changes?

**Comment by claudiosanches** [comment] 2018-07-12 15:28
@derweili we did not had many big changes on it anymore for now, not able to reproduce this, maybe some related to a plugin changing the `completed_at` or something like it.

**Comment by derweili** [comment] 2018-07-16 07:37
I just switched back to `3.3.3` and it's working as expected. The webhook is only triggered once.

**Comment by derweili** [comment] 2018-07-16 10:06
@claudiosan I continued to pursue the problem and recogniced the webhook is triggered only once when the async delivery is disabled (via the `woocommerce_webhook_deliver_async` filter)

For me this means there is definitely a bug within the async webhook function or at least an inconsistent behavior between the async and the non-async webhooks.

**Comment by rodrigoprimo** [comment] 2018-07-16 19:41
I can confirm that on clean WC 3.4.2 install the webhook is called only once and on master it is called twice. I didn't check if the behavior changes if the async delivery is disabled. On a first look, it seems indeed odd that the webhook that is triggered when a order is created is fired twice so I'm reopening this. Thoughts, @claudiosanches?

> Should trigger twice, since it's changing the order status twice, one while created (probably a gateway changing to "on-hold") and then to "processing".

You mean this for the "Order created" or "Order updated" webhook type?

**Comment by claudiosanches** [comment] 2018-07-16 20:37
@rodrigoprimo should trigger twice for "order update", not "order created", that's why my comment.

**Comment by peterfabian** [comment] 2018-08-02 17:25
Tried a bit of a dive into Webhooks today and to me, it seems like it's caused by a race condition in cron. 

The order of events is (I imagine) the following:

1. Order is being created 
2. woocommerce_deliver_webhook_async is scheduled into `$crons` array from `WC_Order_Data_Store_CPT::create`
3. delete_version_transients is also getting scheduled from `wc_delete_shop_order_transients` function that runs from `Abstract_WC_Order_Data_Store_CPT::clear_caches` called from `Abstract_WC_Order_Data_Store_CPT::update`, getting the `$crons` array 
4. cron starts running
  i. woocommerce_deliver_webhook_async is unscheduled from $crons
  ii. order.created is emitted
5. cron runs for the second time to process events for delete_version_transients, getting the `$crons` array including the woocommerce_deliver_webhook_async hook, thus emitting the order.created action again.

I believe this is caused by async processing of version transients clearing introduced in 3.4.3 by #20537 in [`WC_Cache_Helper::get_transient_version`](https://github.com/woocommerce/woocommerce/pull/20537/files#diff-c0310299cb522d1c9add22898d47f915R143) (both branches end up queueing the delete_version_transients to cron).

However, now that [ActionScheduler has been merged to master](https://github.com/woocommerce/woocommerce/pull/20030) and is scheduled for release in 3.5, I'm not sure if it makes sense to spend more time on this at the moment, as it can be disabled by disabling async in 3.4.3 and I could not reproduce this problem in master branch any more, so I'd say this has been fixed.

**Closed by peterfabian** 2018-08-02 17:25 UTC
Labels: bug

**Comment by derweili** [comment] 2018-08-03 06:49
@peterfabian, great news. Many thanks.
I testet the current master and had no errors. It seems like it is fixed. Is there already a release schedule for the 3.5 version?

**Comment by rodrigoprimo** [comment] 2018-08-16 12:41
@derweili, the plan is to release it in the second fortnight of October.
