### ISSUE TITLE
Orders have been failing for months

### ISSUE THREAD

**Issue by compassema** [woocommerce/woocommerce#25453] opened 2020-01-21 21:03 UTC
Please provide help. Orders have been failing on powaydermatology.com using Woocommerce on Wordpress. The first failed order was on Nov. 18, 2019.

**Comment by tammullen** [comment] 2020-01-21 23:47
Hi @compassema,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

[Review WooCommerce Self-Service Guide](https://href.li/?https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://href.li/?https://woocommerce.com/contact-us/)
Make a post on [WooCommerce community forum](https://href.li/?https://wordpress.org/support/plugin/woocommerce/)
If you confirm the bug, please provide us with clear steps to reproduce it and any other details we ask for in the [Bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=4-Bug-report.md&title=).

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by tammullen** 2020-01-21 23:47 UTC
