### ISSUE TITLE
Woocommerce Plugin set "OUT of STOCK " as soon as I Import any new product to my store.

### ISSUE THREAD

**Issue by PreetMaan** [woocommerce/woocommerce#23411] opened 2019-04-20 22:24 UTC
How to Reproduce this issue?

When I Imported a product it was "IN Stock"

<img width="1255" alt="Before updating the Product" src="https://user-images.githubusercontent.com/33556511/56462831-69528680-638f-11e9-9db1-96e10b2ebbc6.png">

As soon as I update anything for a product it will set the product “OUT of STOCK”. In below example I set the Product Tags and saved and Product was set to "OUT of STOCK". 

 **After updating the Product Tags:**

<img width="1255" alt="After Updating Tags for a Product" src="https://user-images.githubusercontent.com/33556511/56462843-8dae6300-638f-11e9-80b9-3ba071a81af4.png">

**Temporary Fix**
Temporary and very time consuming fix is Edit–>Variation–>Select any variation and uncheck manage stock and check it again and update. This will again show your products back “IN STOCK”. This is very time consuming task which means if I will import 100 product then manually I have to go inside each product and uncheck and check back the manage stock button to fix.

<img width="1255" alt="Screen Shot 2019-04-20 at 5 14 42 PM" src="https://user-images.githubusercontent.com/33556511/56462882-3957b300-6390-11e9-8950-195be1280c50.png">

Please NOTE: All Product variations has prices and qty(more than 500) available. I don't feel there is any issue in importing the product because I just unchecked and checked back the manage stock button to fix the issue.

Any clue why updating the product would cause “OUT of STOCK”. Please help.

**Comment by peterfabian** [comment] 2019-04-21 09:58
Hi, 

seems related to https://github.com/woocommerce/woocommerce/issues/23388, however, I wasn't able to reproduce that one. Can you please provide further details about your setup from [system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) and check if you can reproduce this on a site running WooCommerce plugin only?

**Comment by PreetMaan** [comment] 2019-04-21 21:09
Thanks for Looking into this. I tried after removing all plugins except Woo-commerce and issue still persists.

To me it looks like under variation tab unchecking/Checking manage stock is calling some function at the backend which are not being called while using quick edit or while editing something else on a product.  You can refer to the above screen where I have shown how unchecking/checking the manage stock fix this issue. 

I have tested it with PHP version to 7.3 as well but same issue. It looks like after upgrading to Woo-commerce 3.6.1 has caused this issue. I rollbacked to 3.6.0 as well to check but no luck. Don't what is wrong here.


**SYSTEM STATUS REPORT**

`
### WordPress Environment ###

WordPress address (URL): https://shopvouge.com
Site address (URL): https://shopvouge.com
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.16
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.43-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 8.30MB
Database Data Size: 7.03MB
Database Index Size: 1.27MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_adsw_activities: Data: 0.10MB + Index: 0.01MB
wp_adsw_ali_meta: Data: 1.67MB + Index: 0.03MB
wp_adsw_search_analytics: Data: 0.00MB + Index: 0.01MB
wp_commentmeta: Data: 0.90MB + Index: 0.19MB
wp_comments: Data: 0.21MB + Index: 0.07MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.16MB + Index: 0.05MB
wp_postmeta: Data: 1.52MB + Index: 0.50MB
wp_posts: Data: 1.26MB + Index: 0.12MB
wp_smush_dir_images: Data: 0.08MB + Index: 0.03MB
wp_social_users: Data: 0.00MB + Index: 0.00MB
wp_swift_performance_warmup: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.01MB + Index: 0.02MB
wp_terms: Data: 0.04MB + Index: 0.10MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.06MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.01MB + Index: 0.02MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 333
customize_changeset: 149
nav_menu_item: 43
page: 22
post: 3
product: 27
product_variation: 419
revision: 237
scheduled-action: 25

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.1

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

Swift Performance Lite early loader: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: #8971 - /cart/
Checkout: #8973 - /checkout/
My account: #8975 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Flatsome
Version: 3.8.3
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### Action Scheduler ###

Complete: 20
Oldest: 2019-04-18 22:16:58 -0500
Newest: 2019-04-18 23:01:06 -0500

Pending: 5
Oldest: 2019-04-25 22:16:58 -0500
Newest: 2019-04-25 22:16:59 -0500

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by j0hnnym1** [comment] 2019-04-22 09:12
I am having the same issue. Editing and saving any product sets it as "Out of Stock"

**Comment by webwaves** [comment] 2019-04-22 15:20
It's significantly worse than the above implies.

Literally ALL variable products are being marked out of stock after the 3.6/3.61 update.

I also recently updated to PHP 7.3.

I just spent HOURS fixing a site by manually marking each product back in stock.

This should never have been released with this massive of a bug.

**Comment by mikejolley** [comment] 2019-04-23 12:28
This is the same issue as https://github.com/woocommerce/woocommerce/issues/23388 so closing this in favour of the other. On first look, it's due to missing lookup table data (the database update may not have yet completed). Moving conversion to the other issue.

**Closed by mikejolley** 2019-04-23 12:28 UTC
Labels: status: needs feedback
