### ISSUE TITLE
Redundant search query sql

### ISSUE THREAD

**Issue by henry-cotton** [woocommerce/woocommerce#30309] opened 2021-07-19 09:36 UTC
**Is your feature request related to a problem? Please describe.**
I've got a bit of code that extends the wordpress search query to match the search term with a category, and get matching results. I noticed that a search wasn't returning all the results it should, given this code, and realised that WC added some sql (get_main_search_query_sql()) to search queries that overrode the changes I'd made. However, this additional sql was entirely redundent - it was an additional AND that was just a copy of the AND wordpress made.

**Describe the solution you'd like**
Perhaps only add the additional sql where there is more than one search query - i.e. only edit the search query when WP won't do the full job

**Describe alternatives you've considered**
Otherwise, maybe a hook for get_main_search_query_sql() so that developers can edit the code that is added to the search sql query.

**Comment by lkraav** [comment] 2021-07-19 16:34
It would be most clear if you linked to the specific code block in question (and GH embeds it automatically).

**Comment by tammullen** [comment] 2021-07-21 18:40
Hi @henry-cotton ,

Thank you for opening the issue! This might be due to the same root cause as https://github.com/woocommerce/woocommerce/issues/30298

It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by tammullen** [comment] 2021-07-23 10:28
Closing as this will hopefully be covered by the fix in https://github.com/woocommerce/woocommerce/pull/30335 which is now available in 5.5.2 released today.

**Closed by tammullen** 2021-07-23 10:28 UTC
Labels: needs developer feedback
