### ISSUE TITLE
$headers[‘Cache-Control’] = no-transform interfering with CloudFlare compression

### ISSUE THREAD

**Issue by marcusig** [woocommerce/woocommerce#25833] opened 2020-03-06 12:16 UTC
Hi there,

CloudFlare uses the `Cache-Control: no-transform` header to NOT compress the response (https://support.cloudflare.com/hc/en-us/articles/200168396). 

The issue https://github.com/woocommerce/woocommerce/issues/22525 and associated PR added `$headers[‘Cache-Control’] = ‘no-transform, no-cache, no-store, must-revalidate’;` to `WC_Cache_Helper`, and this is applied to every request when WC is active.

So for websites using WooCommerce and CloudFlare, their content isn't gzip/brotli compressed.

The original issue had the following in the description:

> Note that this header generally isn't necessary on non-WC pages; so, consider not opting out the whole site.

But it seems this consideration was left out. Is there a particular reason for adding those headers to every page, or could it be limited to the cart/checkout pages?

Removing the compression on everything is quite detrimental to performance. 

Marc.

**Comment by galbaras** [comment] 2020-03-08 11:27
I've just looked at the home page of one of my sites that's on CF and saw this:

```
cache-control: max-age=0, no-cache, no-store, must-revalidate
cf-cache-status: DYNAMIC
cf-ray: 570c2f6f7c09fd56-SYD
content-encoding: br
```

On the same site's cart page, I saw this:

```
cache-control: no-transform, no-cache, no-store, must-revalidate
cf-cache-status: DYNAMIC
cf-ray: 570c32c9bbb4fd56-SYD
content-encoding: gzip
```

What makes you think there's a problem?

**Comment by marcusig** [comment] 2020-03-09 05:57
It's likely that your home page uses a cached version, so it doesn't pass the `no-transform` header. 
When a) a website doesn't have page caching or b) the user is logged in (which in most cases bypasses cache), WooCommerce will send the `no-transform` header on every page, disabling the brotly compression in Cloudflare. Here's what I get on one of our websites:

Home page anonymous: 

```
cache-control: no-transform, no-cache, no-store, must-revalidate
cf-cache-status: DYNAMIC
cf-ray: 5712723b3c40b7b1-CDG
content-encoding: br
content-type: text/html; charset=UTF-8
```

Homepage logged-in:

```
cache-control: no-transform, no-cache, no-store, must-revalidate
cf-cache-status: DYNAMIC
cf-ray: 5712723b3c40b7b1-CDG
content-type: text/html; charset=UTF-8
```

In your example, the content is Gziped by your server. But in many cases, the server doesn't have GZIP enabled and users might rely on Cloudflare to compress the html. 

I understand the need to send `no-transform` for Google's "Web Light" compatibility, but I think it should follow the same logic as where DONOTPAGECACHE is used, i.e. on the cart/checkout/my account pages.

**Comment by galbaras** [comment] 2020-03-09 08:29
You're right about caching. Here is my home page while logged in:

```
cache-control: no-transform, no-cache, no-store, must-revalidate
cf-cache-status: DYNAMIC
cf-ray: 571344cbce4a655b-SYD
content-encoding: gzip
```

Illuminati confirmed 👍 I can also confirm that this happens on pages where there shouldn't be any dynamic WC elements, but I still see the cart-fragments.min.js script, which makes me wonder how WC separates static from dynamic pages.

Unless I'm really confused here, class-wc-cache-helper.php is always included and always runs its `init()` function, which indeed seems way too much.

**Comment by marcusig** [comment] 2020-03-09 08:39
> Unless I'm really confused here, class-wc-cache-helper.php is always included and always runs its init() function, which indeed seems way too much.

Yes that's what I also concluded.

>  but I still see the cart-fragments.min.js script, which makes me wonder how WC separates static from dynamic pages.

My understanding is that "dynamic" pages are those where `the_content` is dynamic, i.e. cart, checkout and my-account, and thus can't be cached. `cart-fragments.min.js` adds dynamic elements to static pages.

**Comment by vedanshujain** [comment] 2020-05-14 14:45
I agree with what is suggested here and marking this as a bug because ideally no-cache headers should only be set on pages that really need them.

**Comment by DavidAnderson684** [comment] 2020-05-14 14:48
@vedanshujain I disagree with the "priority: low" tag. Not killing performance across the site through disabling page cacheing is surely a high priority for a large majority of shop owners.

**Comment by rrennick** [comment] 2020-06-16 16:45
The issue we'll need to look at for this is the `nocache_headers` occurs before WP has parsed the query. At that point none of the WP or WC query conditionals can be used to determine whether to include the header or not.

**Comment by galbaras** [comment] 2020-06-17 01:22
I agree that this should get a higher priority. It actually explains why my site is so slow, despite all the work I've put into optimizing it.

Since most people use CDNs to avoid needing Web Light, why not just provide a plugin setting for this, and let admins/developers set/unset it as required. How about something like "Send Web Light compatibility headers"?

No parsing required. Clean and simple, and please return the default to "no", because turning it on by default was a breaking change.

**Comment by Camilo517** [comment] 2020-06-19 13:05
This is a priority and moved to 4.4.0👍👌

**Comment by rrennick** [comment] 2020-06-23 16:38
Addressed in #26802

**Comment by Camilo517** [comment] 2020-06-23 18:10
@rrennick Isn't this going to apply automatically? Do I need to manually apply a filter on a WooCommerce + Cloudflare?

**Comment by rrennick** [comment] 2020-06-23 19:05
>  Do I need to manually apply a filter on a WooCommerce + Cloudflare?

Yes, CDN plugins will need to use the filter to disable the caching headers.

**Comment by DavidAnderson684** [comment] 2020-06-24 09:33
@rrennick The code merged doesn't begin to address a large amount of the root problem. It adds a filter so that shop owners can learn about and try to fix the problem themselves. But note that even web browsers respond to this header - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Browser_compatibility . i.e. They won't cache a page because of that header. The original issue description used Cloudflare as background to the specific experience of that user, but the problem is actually universal; WooCommerce by default forbids all cacheing of all pages on a site by *any* mechanism.

i.e. The root problem is that WC now causes a header `cache-control: no-transform, no-cache, no-store, must-revalidate` to be emitted on all pages of a site. *One* use-case that that causes a problem with is when using a remote CDN or proxy service (e.g. Cloudflare). *Some* uses of such services may also be using a plugin in conjunction with that service, but that's not necessarily the case (e.g. it's not necessary to use the "Cloudflare" WP plugin, or any particular plugin at all, to use Cloudflare with WP - the plugin is just adding tighter convenience integration; personally I don't use it).

So, the code merged basically adds a filter to outsource the solving of the problem which WC's universal unwanted headers cause. This isn't good. Performance will still be degraded for everyone by default; but now there's a filter for users who want to become developers to dive into the guts if they don't want that universal performance degradation.

**Comment by galbaras** [comment] 2020-06-24 13:17
I wholeheartedly agree. The default should be no headers, with a filter or setting for those that want a header to get one. The current solution is not backwards compatible, introducing a change that may not be breaking, but is invasive.

**Comment by rrennick** [comment] 2020-06-24 17:35
I created #26858 to default to only including the headers when the `googleweblight` agent is detected.

**Comment by DavidAnderson684** [comment] 2020-06-24 17:44
I don't follow.... as I see it, the root problem is that WooCommerce is adding `Cache-Control` headers, informing *every* user-agent to not cache and not transform *every* page on the site. This was not its historical behaviour, and there's no good reason for it. I don't think that exempting a specific list of user agents from universal broken-ness makes sense as a solution. Surely the proper solution is for WooCommerce to only advise not-caching, and only advise not-transforming, when there's a known reason for it? Why is it being done on every page of a site anyway? The original issue - https://github.com/woocommerce/woocommerce/issues/22525 - discussed exempting specific pages from transformation. Somehow, a pull request that exempted every page from both transformation and caching was then produced and merged; there was no explanation in the issue or pull request as to why this was done.

**Comment by rrennick** [comment] 2020-06-24 17:54
> the root problem is that WooCommerce is adding Cache-Control headers, informing every user-agent to not cache and not transform every page on the site.

By default the header is only added when the `googleweblight` user agent is detected in the pull request I linked to..

**Comment by DavidAnderson684** [comment] 2020-06-24 17:59
Got it, sorry - I'd missed that the PR changed the default.

**Closed** 2020-07-01 12:31 UTC
Labels: bug, performance, priority: low
