### ISSUE TITLE
id was called incorrectly. Product properties should not be accessed directly. Backtrace: 

### ISSUE THREAD

**Issue by Angiedima** [woocommerce/woocommerce#21158] opened 2018-08-22 20:57 UTC
I have a problem with my checkout page .. this is the error in my log for xampp

id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('C:\\xampp\\htdocs\\wp-blog-header.php'), require_once('C:\\xampp\\htdocs\\wp-load.php'), require_once('C:\\xampp\\htdocs\\wp-config.php'), require_once('C:\\xampp\\htdocs\\wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart_Session->get_cart_from_session, WC_Product->is_purchasable, apply_filters('woocommerce_is_purchasable'), WP_Hook->apply_filters, TC_WooCommerce_Bridge->maybe_modify_product_is_purchasable, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.,

**Comment by claudiulodro** [comment] 2018-08-23 17:27
Hi.

You are getting that message because you are using some plugin that has not been updated for WooCommerce 3.0+, and it is directly accessing class fields (this was deprecated in WooCommerce 3.0). Looking at your backtrace, it is whichever plugin contains the TC_WooCommerce_Bridge class (Tickera Bridge for WooCommerce?). You should update that plugin if possible and contact the author of the plugin if an update is not available.

I'm closing this issue as this is not a bug in WooCommerce. Thanks.

**Closed by claudiulodro** 2018-08-23 17:27 UTC
